### DISCUSSION TITLE
vars replacement overview

### DISCUSSION THREAD

**Discussion by joebowbeer** [kubernetes-sigs/kustomize#5046] [Q&A]
Background:

I read in the kustomize v5 release notes and open issue #4049 that the entire `vars` feature is deprecated, and that we are advised to use `replacements` instead.

Unfortunately, if I understand correctly, replacements cannot replace all uses of [vars](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/), but there are several proposals to address some of the deficits: #3787 #4517

However, even these proposals do not [completely fill the gap](https://github.com/kubernetes-sigs/kustomize/pull/4558#discussion_r1038404083) because they target structured data, whereas vars supports string replacement.

Another issue with `replacements` is that it does not _compose_ in the same way that `vars` does, so it may not be possible to replace a Component using vars with one using replacements: https://github.com/kubernetes-sigs/kustomize/issues/4099#issuecomment-1098362896

Questions:

Is this a fair summary?

What is the strategy for resolving this impasse? I only see a deprecation notice, a partial alternative, and several (incomplete) proposals.

Am I missing something? Where can I find more discussion?

**Comment by vugardzhamalov** [comment]
I think there was a saying: if KRM function is your sledge hammer then every problem is a nail!  Well maybe not exactly, but something along these lines... ;-P

**Comment by zs-dima** [comment]
+1 `replacements` are useless for most useful cases, such as domain substitution.
hopefully FluxCD has vars substitution (ArgoCD requares extra sidecar setup for vars substitution)

**Reply by webwurst** [reply]
Flux supports [post build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution).

**Reply by zs-dima** [reply]
This topic about Kustomize, as I mentioned FluxCD substitution will not help if I will prefer ArgoCD or plain Kustomize

**Comment by pre** [comment]
A way to define common variables is such a common requirement that all my kustomize based setups (with or without ArgoCD) have always had a companion envsubst mechanism.

it would be great if kustomize offered a mechanism of its own - without having to eg generate an extra configmap just to be able to use the awkward Replacements feature.

**Comment by staylorx** [comment]
I've also run into this, and I see where vars is powerful, especially when mixed with CI/CD such as ArgoCD. I've become quite fond of the Component and I can imagine a place where the only place to use a variable would be a parameterized Component. That way Kustomization objects can be left as-is, but anything that takes an argument (environment, passed in, piped?) must come through a Component. That those can't be param'd is surprising, and I've struggled with the lack of encapsulation that Components hint at.

**Comment by alexrecuenco** [comment]
I will preface this by saying that I might be wrong on my assumptions on how replacements is meant to work. From what I understand, it needs an array of every spec of fields it needs to replace written down into its definition, right?

As staylorx says, parametrizing a few fields based on some variable, and then using varReplacements as a configuration to generate a broad set of definitions is quite powerful and intuitive. I can give that to anyone with barely any experience with this entire system, and they very quickly can make modifications, without having to learn the entire toolset.

1. I still don’t quite get how we are meant to replace all places that say $(PROJECTROOTFOLDER) with replacements. The whole prefix thing is very limited, I need to know ahead of time if my variable to replace is before or after a `-`, and how many `-` there are on each field I am replacing this variable.
2. It is definitely unintuitive to get replacements to work, and vars are extremely intuitive.
3. I still don’t get how we are meant to write global configurations, so that I don’t need to replicate the fields the replacement is targeting constantly.

It is very verbose to try to achieve a “replace all mentions of $(PROJECTROOTFOLDER)” in a set of non-trivial definitions. With `vars` generating a Component that contains those definitions and a wide enough config with varReplacements is quite intuitive and does everything you need.

Besides, I believe the deprecation of vars is poorly explained. And I think it is a mistake.

From reading different discussions, I *think* what happened is that, (And I can’t find the references anymore, please someone help finding those references again)

1. A bug was introduced that allowed using in a properties file a raw name `variable` without a `=` sign, and Kustomize would fetch that `variable` from your bash environment. 
4. That bug was later documented as a feature
5. That _feature_ in conjunction with `vars` can be used for evil. Since the goal here is YAML in, YAML out, with no tricks, and using environment variables kind of defeats the purpose of that.
6. That _feature_ was reverted and a deprecation warning was placed

Now, here, the culprit is *not* `vars`. It is the injection of environment variables, `vars` just happened to play nicely with that.

I *think* that is why `vars` was deprecated. I might be wrong, and vars on its own is also _evil_. But I would love some discussion/explanation of the deprecation *and*/*or* a way to use replacements to achieve similar substitution inside variables.

**Reply by alexrecuenco** [reply]
For example, nameReplacements might be better suited for certain types of interpolations, adding definitions to those. 

But what if, as is the case with ArgoCD RBAC, you need to interpolate a text within a field, the pattern is `field: “proj:(resourcename):(rolename), …,allow”`

**Comment by sda399** [comment]
imho, it's about shifting philosophy, from parameterized templating to static declarative definitions.
The latter is said to be more traceable (with gitops) and deterministic.
The shift is not easy, when we come from ansible or helm background.
With kustomize, I believe we need to keep things simple, otherwise use functions or custom transformers for custom needs.

**Reply by alexrecuenco** [reply]
How is replacements more traceable to vars? What about vars is hard to trace?

Vars explicitly says "this value will be changed by a var". And the var is explained in gitops explicitly. Replacements happens in some other file, with a notation that is hard to track. And a way to obtain that value to change that is ... interesting.


<details>
<summary>Example </summary>
For example,

imagine you have a value in a CRD  A.x that needs to be equal to some other value(s) in B.y; with vars I just define both fields to look the same and the appropriate configuration. With replacements I need to keep track of both of them and add 5 lines of explanation with the exact change I want in B.y and how to get it. And if I later have C.z that also has to have that same value.m, but with a different format, good luck! not to mention, you need to split on . Or -, etc; and you need to know ahead of time how it is split  
</details>


Moreover, if you now need that same replacement in another field, it is not trivial how to accomplish that, or to even make sure you got it right.

In any case, you should be inflating your charts, Kustomize, etc for verification and diffing those changes; if you miss-type a name in  Kustomize all of the sudden you can be skipping important patches.

**Comment by gabrielgbs97** [comment]
I do not know if I am missing something, please correct me if there is a better solution. I think simple variable-value substitution is a fair use case for kustomize.

Domain, user principals, production and development paths, etc. are standard use cases and it takes a ton of wording in kustomize right now. #5516 is a good approach way. Still, a simple ansible-style 'vars' with variables that hold partial yaml trees or a string would suffice a respectable number of use cases. As of now, we must:
- define a dummy configmap that holds our variables
- perform replacements based on previous configmap elements, poor user HAS TO KNOW beforehand where every variable targets.
- Now we had to get rid of this dummy configmap, or then it will be a dangling k8s resource causing confusion.

Average user would be happy with:

```YAML
- notVars:
  myvar1: "smyValue1"
  myvar2:
    hey: thisisvalue2_1
    ho: thisisvalue2_2
```

**Comment by kferrone** [comment]
I made a vars transformer

Check it: https://github.com/kubed-io/krm

Heres the code for it: https://github.com/kubed-io/krm/tree/main/kustomize/plugin/krm.kubed.io/vartransformer

**Comment by alexrecuenco** [comment]
Here is an example that I think makes it clear that replacements can't replace vars. And how vars properly used is a very declarative DRY mode


1. Use a ConfigMap with `config.kubernetes.io/local-config: "true"` to not upload it

```
kind: ConfigMap
metadata:
  name: kustomize-globals
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  our-gitops-repo: ssh://git@gitlab.com/mycorp/infrastructure
  our-root-host: mycorp.com
```

2, You make a component that uses vars

```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./global-configmap.yaml

vars:
  - name: REPOURL
    objref:
      version: v1
      kind: ConfigMap
      name: kustomize-globals
    fieldref:
      fieldpath: data.our-gitops-repo
  - name: ROOT_HOST
    objref:
      version: v1
      kind: ConfigMap
      name: kustomize-globals
    fieldref:
      fieldpath: data.our-root-host

configurations:
  - revisionVarReference.yaml
  ```
  
  3. Write a configuration file `revisionVarReference.yaml`, where you say which places are allowed to use your vars
  
  ```yaml
varReference:
  - path: spec/source
    kind: Application
  - path: spec/sources/targetRevision
    kind: Application
  - path: spec/sources/repoURL
    kind: Application
  - path: spec/generators/git
    kind: ApplicationSet
  - path: spec/generators/git/files/path
    kind: ApplicationSet
  - path: spec/generators/template/spec/sources
    kind: ApplicationSet
  - path: spec/acme
    kind: ClusterIssuer
  - path: spec/sources/secret
    kind: Bundle
  - path: metadata/annotations
    kind: Ingress
  - path: spec/template/spec/containers/env/value
    kind: Deployment
```
    
4. Just use them with `$(VAR_NAME)` across all your resources

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
  name: applications-manager
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc/
  project: default
  source:
    path: $(ROOT_FOLDER)/cluster/applications/overlays/$(REVISION)
    repoURL: $(REPOURL)
    targetRevision: $(REVISION)
  syncPolicy:
    retry:
      limit: 3
    automated:
      prune: true
      selfHeal: true
```     
      
5. Finally add to your kustomize the global component

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata:
  - originAnnotations

resources:
  - ../../base

components:
  - ../../../../global/development/
  
  ```


100% declarative, and DRY:

- One place to change the configurations
- One very simple to understand place to understand how to extend to make modifications to other field paths
- Easy to understand how to create multiple components that would provide different outputs.

Can someone tell me how this would be done with replacements?

---
> *Apologies for the double notification if someone got notifications here, I used the wrong account to make a comment*

**Reply by sda399** [reply]
isn't this just a replacements equivalent?

**Reply by joebowbeer** [reply]
@sda399 The problem with replacements in components is https://github.com/kubernetes-sigs/kustomize/issues/4099#issuecomment-1470934286

If you can figure out how to replace vars with replacements in this component, I'd like to see it.

**Reply by sda399** [reply]
for your question, here it is. but to be honest I would probably go for a full field replacement instead of partial variables.

```
replacements:
    - source:
      kind: ConfigMap
      name: cm
      fieldPath: data.root_folder
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.path
        options:
          delimiter: /
          index: 0

  - source:
      kind: ConfigMap
      name: cm
      fieldPath: data.revision
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.path
          - spec.source.targetRevision
        options:
          delimiter: /
          index: 4

  - source:
      kind: ConfigMap
      name: cm
      fieldPath: data.repo_url
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.repoURL
```

**Reply by joebowbeer** [reply]
I agree that replacements can perform the type of substitution used in this example – though there are other kinds of vars substitutions that replacements can't yet perform.

However, my question was about compose-ability. How can your implemention work inside a Component?

**Reply by sda399** [reply]
I use replacements in Components.

**Reply by joebowbeer** [reply]
If you can demonstrate how replacements can be used in the Component in this example, then we can evolve this discussion further.

**Reply by sda399** [reply]
I try to keep it simple, repeated bits and configurations, and complex cases go in krm functions, implemented as simple scripts and small kustomize compatible yaml configuration files to generate manifests.

**Reply by sda399** [reply]
> If you can demonstrate how replacements can be used in the Component in this example, then we can evolve this discussion further.

there is no Component in your example, would elaborate?

**Reply by sda399** [reply]
I see now, just put the replacement in a Component, is it what you are looking for?

**Reply by alexrecuenco-hf** [reply]
Just to be clear. You can't. The sources and targets must be specified together. They are not decoupled. You must repeat the same list of target for each replacement, and it doesnt do in-place replacements, 

You cant replace "name is $(VAR) doing" and "inner.$(VAR).com" with the same rule either, it doesnt do variable substitution. You must know ahead of time the structure of what you are replacing

**Reply by alexrecuenco-hf** [reply]
> for your question, here it is. but to be honest I would probably go for a full field replacement instead of partial variables.
> 
> 
> 
> ```
> 
> replacements:
> 
>     - source:
> 
>       kind: ConfigMap
> 
>       name: cm
> 
>       fieldPath: data.root_folder
> 
>     targets:
> 
>       - select:
> 
>           kind: Application
> 
>         fieldPaths:
> 
>           - spec.source.path
> 
>         options:
> 
>           delimiter: /
> 
>           index: 0
> 
> 
> 
>   - source:
> 
>       kind: ConfigMap
> 
>       name: cm
> 
>       fieldPath: data.revision
> 
>     targets:
> 
>       - select:
> 
>           kind: Application
> 
>         fieldPaths:
> 
>           - spec.source.path
> 
>           - spec.source.targetRevision
> 
>         options:
> 
>           delimiter: /
> 
>           index: 4
> 
> 
> 
>   - source:
> 
>       kind: ConfigMap
> 
>       name: cm
> 
>       fieldPath: data.repo_url
> 
>     targets:
> 
>       - select:
> 
>           kind: Application
> 
>         fieldPaths:
> 
>           - spec.source.repoURL
> 
> ```


Your example fails to replace the target revision properly if I change the folder structure, I all of the sudden need to reconfigure all my replacements.

It also doesn't work if you have some folder that are more nested than others.

And it also will try to replace folders in applications that dont have a TARGET_REVISION, and are instead fixed.

**Reply by alexrecuenco-hf** [reply]
Imagine if you had to write a var replacement function in python, and it would only replace vars that are exactly 10 characters deep. Then you write another function for replacing characters that is 3 slashes deep.

And also, in the source there is no way to explicitly declare a variable name, so you are at the whims of the developer to remember which components will do replacements there later

**Reply by sda399** [reply]
I get your concern.
You can implement krm functions for your needs, or use a template engine along kustomize with a piping strategy (eg. kustomize | render | filter | kubectl apply).

Having said that, I feel like there is more to this discussion/thread.

If we expect Kustomize to behave like a general-purpose programming language or a templating solution, then yes, it looks awkward. Kustomize's purpose, to my understanding, is to be a constrained configuration transformer yaml-in-yaml-out, allowing predictability, composability, and tooling.

At some point, this comes down to tool fit. If you need free-form templating and implicit variable expansion, Kustomize is not trying to solve that, by design. Its value is in constrained, declarative transformations that scale in GitOps and multi-team environments. Given that, continuing to debate it as “templating done awkwardly” doesn’t really move the discussion forward — it’s a different philosophy, not an accidental limitation.

**Reply by alexrecuenco-hf** [reply]
> I get your concern.
> 
> You can implement krm functions for your needs, or use a template engine along kustomize with a piping strategy (eg. kustomize | render | filter | kubectl apply).
> 
> 
> 
> Having said that, I feel like there is more to this discussion/thread.
> 
> 
> 
> If we expect Kustomize to behave like a general-purpose programming language or a templating solution, then yes, it looks awkward. Kustomize's purpose, to my understanding, is to be a constrained configuration transformer yaml-in-yaml-out, allowing predictability, composability, and tooling.
> 
> 
> 
> At some point, this comes down to tool fit. If you need free-form templating and implicit variable expansion, Kustomize is not trying to solve that, by design. Its value is in constrained, declarative transformations that scale in GitOps and multi-team environments. Given that, continuing to debate it as “templating done awkwardly” doesn’t really move the discussion forward — it’s a different philosophy, not an accidental limitation.

Nobody is talking about general purpose programming. That is an unfair analogy that IMO tries to be non-constructive.

There is a DRY, GitOps, Scalable, solution already, that is declarative: vars. 

It is getting replaced by replacements, which is awkward to use in scalable ways; as we have outlined in this thread, and I don't think you debate that point.

I am just asking for an explanation why vars is being deprecated, since replacements doesn't cover its use case; it is a different paradigm; and quite brittle I might add

**Reply by alexrecuenco-hf** [reply]
Here is an example that I was tinkering with, since at my current company we can't use something that is deprecated


App 1 is the root app, so it points to itself

App 2 points to a different repository managed by a different team, so static branch name.

Now I need to modify the replacements to only target based on an annotation... 

Note how all paths must be the same depths or this starts adding at random places the string, either overwriting an earlier section, or adding it additionally at the end as `whateverwasthere/development`

```
# Replacements works in mysterious ways, so all paths must be the same depth {path}/overlays/{version}
# See https://github.com/kubernetes-sigs/kustomize/discussions/5046
replacements:
  - source:
      kind: ConfigMap
      name: kustomize-globals
      fieldPath: data.branch
    targets:
      - select:
          kind: Application
          labelSelector: "app.kubernetes.io/component=argocd"
        fieldPaths:
          - spec.source.path
        options:
          # we expect deployments/kubernetes/A/B/C/overlays/REPLACE
          delimiter: /
          index: 6
      - select:
          kind: ApplicationSet
          labelSelector: "app.kubernetes.io/component=argocd"
        fieldPaths:
          - spec.template.spec.source.path
        options:
          # we expect {{.path}}/overlays/REPLACEME
          delimiter: /
          index: 2
      - select:
          kind: ApplicationSet
          labelSelector: "app.kubernetes.io/component=argocd"
        fieldPaths:
          - spec.template.spec.source.targetRevision
          - spec.generators.*.git.revision
      - select:
          kind: Application
          labelSelector: "app.kubernetes.io/component=argocd"
        fieldPaths:
          - spec.source.targetRevision
```
