### DISCUSSION TITLE
Override URL resource

### DISCUSSION THREAD

**Discussion by gregory-j-baker** [kubernetes-sigs/kustomize#5056] [Q&A]
Is it possible to override a URL resource in an overlay?

For example, let's say I have the following base:

``` yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

and I want to override it using a specific version of Argo CD:

``` yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - ../bases/argocd/
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.2/manifests/install.yaml
```

I know the above won't work (I tried it), but is there a recommended way to do this?

**Comment by levikobi** [comment]
You could do the following:
```
.
└── k8s
    ├── base
    │   └── kustomization.yaml
    ├── kind-config.yaml
    └── overlays
        └── dev
            └── kustomization.yaml
```

k8s/base/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

k8s/overlays/dev/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
patchesStrategicMerge:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.2/manifests/install.yaml
```

To test it run:
```bash
# Create KinD cluster with base ArgoCD
kind create cluster --name kustomize-base-argocd && \
	kustomize build k8s/base | kubectl apply -f -

# Create KinD cluster with dev ArgoCD
kind create cluster --name kustomize-dev-argocd && \
	kustomize build k8s/overlays/dev | kubectl apply -f -

# Delete both clusters
kind delete cluster --name kustomize-base-argocd
kind delete cluster --name kustomize-dev-argocd
```
