### DISCUSSION TITLE
Is it possible to filter resources /invert a selector

### DISCUSSION THREAD

**Discussion by btrepp** [kubernetes-sigs/kustomize#5188] [Q&A] [answered]
So I have been trying to make my setup more declarative, kustomize being fantastic for this.
However the k8s distributions of tools, not so much.

Many seem to want helm, or bundle everything in one yaml, no doubt aiming for ease of use. However I would like to apply CRDs and applications separately. In my mind it's different roles, and CRDs usually need to come first anyway, so that makes sense to do.

This is successful in some cases (seperate remote files), or tools that use customise, just point at their base, but in some it's a nightmare.

https://openebs.io seems to put it all in one yaml file, it seems they really want you to use helm. I am able to write a patch to remove the CRDs from this, fantastic and beautiful.
The problem is I still *need* the crds in a seperate kustomization, that I bundle up and apply first.

Is there anyway to 'invert' a selector?.

Given for the 'deploy app part'
```
patches:
- path: remove-crds.yaml
  target:
    kind: CustomResourceDefinition
- path: remove-ns.yaml
```

Perhaps

```
patches:
- path: remove-resources.yaml
  target:
    kind: !CustomResourceDefinition or ^CustomResourceDefinition
```

I imagine this is a bit of a non common/desired use-case, but it's one of those issues in the broader ecosystem. Only workarounds are
1) Try to convince openers to package a different way
2) Use the helm plugin for kustomize. It would work, but I'm using kustomize to try to avoid all the pain it generated me, so it's awkward to bring it back.
3) Write resource definitions by hand

**Comment by btrepp** [comment, marked as answer]
I found.. a very weird way to do this.

First 1) create a kustomization wrapping your 'upstream' and add an annotation

```
resources:
- src/upstream/somefile.yaml

commonAnnotations:
  vendor: "true"

```
In this case, I'm using git submodules

2) Now use this as a base elsewhere

```
resources:
- ../../../vendor/

patches:
- target:
    kind: CustomResourceDefinition
  patch: |
    - op: remove
      path: /metadata/annotations/vendor
- target:
    annotationSelector: "vendor=true"
  patch: |
    $patch: delete
    kind: IGNORED
    metadata:
      name: DOES NOT MATTER
```

What we are doing is, adding an annotation, removing that for the 'resources we want'. Then deleting all the resources that still match that annotation.

It works, and is also nice as I only have to add a submodule once (before I was having to do it twice because of the folder rules).


I'm not sure if there is a risk here about the 'order in which kustomize runs patches', that could be an issue, but it does work for whoever needs this ability.

There is definition some quirks in kustomizes patching. As you need some 'ignored' text, otherwise you will get errors, but the text isn't actually used at all...
