### DISCUSSION TITLE
How to Override Remote Resource Versions in Kustomize Base/Overlay Setup

### DISCUSSION THREAD

**Discussion by ptr1120** [kubernetes-sigs/kustomize#5357] [Q&A]
Hello,

I am using Kustomize's base/overlay directory layout for managing Kubernetes resources across multiple clusters (development, staging, and production).

**Current Setup:**

In my `base/kustomization.yaml`, I have specified a remote resource with a specific version.
```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - resources/namespace.yaml
    - github.com/stefanprodan/podinfo/kustomize?ref=6.4.0
    - resources/ingress.yaml

patches:
...
```

For environment-specific configurations, I use overlays. Here's an example for staging:

```yaml
# overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
...
```

**The Issue:**

I'd like to test different versions of the remote resource (github.com/stefanprodan/podinfo/kustomize) in different environments. For instance, I'd like to override the ref=6.4.0 with ref=7.0.0 in my staging overlay. However, I haven't found a straightforward way to do this within the existing Kustomize functionality.

**Questions:**

1. Is it possible to override the version of a remote resource in an overlay using Kustomize?
2. If not, what are the recommended best practices for handling different versions of remote resources in a base/overlay setup?
