### DISCUSSION TITLE
Using `Replacements` to substitute a key in multi-line strings of a ConfigMap

### DISCUSSION THREAD

**Discussion by midhun1998** [kubernetes-sigs/kustomize#5358] [Q&A]
Hi,

I'm working on the https://github.com/kubeflow/pipelines/issues/10053 effort to port old vars reference to replacements and I stumbled upon a specific case. In the below example, I would like to replace the `KFP_NAMESPACE`  and  `KFP_ARTIFACT_BUCKET_NAME` strings with some value. Can someone help with how I can structure my replacements section in the `Kustomization.yaml`?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # * https://github.com/argoproj/argo-workflows/blob/v3.3.10/docs/workflow-controller-configmap.yaml

  # In artifactRepository.s3.endpoint, $(kfp-namespace) is needed, because in multi-user mode, pipelines may run in other namespaces.
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: "minio-service.KFP_NAMESPACE:9000"
      bucket: "KFP_ARTIFACT_BUCKET_NAME"
      # keyFormat is a format pattern to define how artifacts will be organized in a bucket.
      # It can reference workflow metadata variables such as workflow.namespace, workflow.name,
      # pod.name. Can also use strftime format
```

I think this might be related to #4517 and #4558 ? Any workarounds or solutions at this time?

Thanks!
