### DISCUSSION TITLE
How to patch with a resourceMatcher function? What if resourceMatcher function were a selector?

### DISCUSSION THREAD

**Discussion by marcellodesales** [kubernetes-sigs/kustomize#5388] [Q&A]
# How to use `resourceMatcher` function in `kustomization.yaml`?

I see the target object with the property `resourceMatcher`, but it's not exposed as a yaml object... 

https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fn/framework/selector.go#L38-L40

> **NOTE**: Without some kind of `resourceMatcher`, the patches are applying to ALL target resources without any filters... 

# Desired behavior: have a matcher for the properties

* The use case is very simple: I'd like to only apply this patch if the resourceMatcher is a match... 
* I wonder if we can have a generic matcher as follows:
  * That would require to expose the `resourceMatcher` as a yaml property in the provided link... etc...

```yaml
patches:
  - target:
       group: actions.summerwind.dev
       version: v1alpha1
       kind: RunnerDeployment
       resourceMatcher:
         - match:
            expressions:
              - key: "spec.template.spec.image"
                 operator: "Equals"                 
                 value: "summerwind/actions-runner"

    patch: |-
       - op: add
         path: /spec/template/spec/image
         value: docker.artifactory.company.com/runtime/github-actions-runner:89c22b2-main
```
