### DISCUSSION TITLE
Moving away from patchesStrategicMerge to patches with multiple patches in one file

### DISCUSSION THREAD

**Discussion by juchom** [kubernetes-sigs/kustomize#5392] [Q&A] [answered]
Hello,

I try to update my kustomize.yaml file, but it fails because I have multiple patches in one file.

It seems that this issue has been solved according to : https://github.com/kubernetes-sigs/kustomize/issues/5049

I'm wondering what am I doing wrong ?

**kubectl version**
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

**kustomization.yaml**
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: _k8s_secrets.yaml
```

**_k8s_secrets.yaml**
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager

stringData:
  api-token: ***

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meilisearch-environment
  namespace: app-shared

data:
  MEILI_MASTER_KEY: "***"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maildev-environment
  namespace: app-shared

data:
  MAILDEV_WEB_USER: "***"
  MAILDEV_WEB_PASS: "***"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-environment
  namespace: my-app

data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  
```

**Error output**
```
error: trouble configuring builtin PatchTransformer with config: `
path: _k8s_secrets.yaml
`: unable to parse SM or JSON patch from [---
***
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager

stringData:
  api-token: ***

---
***
***Map
metadata:
  name: meilisearch-environment
  namespace: app-shared

data:
  MEILI_MASTER_KEY: "***"

---
***
***Map
metadata:
  name: maildev-environment
  namespace: app-shared

data:
  MAILDEV_WEB_USER: "***"
  MAILDEV_WEB_PASS: "***"

---
***
***Map
metadata:
  name: app-environment
  namespace: my-app

data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  ]
```
