### DISCUSSION TITLE
helmCharts valuesFile doesn't handle up a directory?

### DISCUSSION THREAD

**Discussion by arkmech** [kubernetes-sigs/kustomize#5493] [Q&A]
```yaml
helmCharts:
- namespace: ingress
  valuesFile: ../base-nginx-values.yaml
```
Documentation states valuesFile takes a file path, it works for filePaths going down, but does not work when file path contains `..` to go up a directory.
