### DISCUSSION TITLE
The labels in Rollouts spec.selector.matchLabels doesn't works

### DISCUSSION THREAD

**Discussion by felixrb86** [kubernetes-sigs/kustomize#5496] [Q&A]
### What happened?

I need to apply the 
commonLabels  in spec.selector.matchLabels in the Rollouts file.

### What did you expect to happen?

It have to add the matchLabels in both files (deployment.yml and rollout.yml)

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../test-base

labels:
  - pairs:
      some-label: NEW-LABEL
    includeSelectors: true
    includeTemplates: true
```

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Deploy en pxt-qa 1.0"
  name: DEPLOYMENT_NAME
  namespace: pxt-qa
spec:
  revisionHistoryLimit: 5
  replicas: 0
  template:
    metadata:
      labels:
        some-label: value-of-label
    spec:
      containers:
        - name: CONTAINER_NAME
          image: IMAGE_NAME
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2000Mi"
              cpu: "1"
            requests:
              memory: "51Mi"
              cpu: "0.01"
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```
```yaml
# rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ROLLOUT_NAME
  namespace: pxt-qa
spec:
  revisionHistoryLimit: 5
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: DEPLOYMENT_NAME
  strategy:
    canary:
      stableMetadata:
        labels:
          role: current
      canaryMetadata:
        labels:
          role: new
      maxUnavailable: 0
      canaryService: canaryService-name
      stableService: stableService-name
      trafficRouting:
       istio:
         virtualService:
           name: stableService-name
           routes:
           - primary
      steps:
      - setWeight: 100
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: Deploy en pxt-qa 1.0
  labels:
    new-label: NEW-LABEL
  name: DEPLOYMENT_NAME
  namespace: pxt-qa
spec:
  replicas: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      new-label: NEW-LABEL
  template:
    metadata:
      labels:
        new-label: NEW-LABEL
        some-label: value-of-label
    spec:
      containers:
      - env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: IMAGE_NAME
        name: CONTAINER_NAME
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: "0.01"
            memory: 51Mi
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    new-label: NEW-LABEL
  name: ROLLOUT_NAME
  namespace: pxt-qa
spec:
  selector:
    matchLabels:
      new-label: NEW-LABEL
  revisionHistoryLimit: 5
  strategy:
    canary:
      canaryMetadata:
        labels:
          role: new
      canaryService: canaryService-name
      maxUnavailable: 0
      stableMetadata:
        labels:
          role: current
      stableService: stableService-name
      steps:
      - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: stableService-name
            routes:
            - primary
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: DEPLOYMENT_NAME
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: Deploy en pxt-qa 1.0
  labels:
    new-label: NEW-LABEL
  name: DEPLOYMENT_NAME
  namespace: pxt-qa
spec:
  replicas: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      new-label: NEW-LABEL
  template:
    metadata:
      labels:
        new-label: NEW-LABEL
        some-label: value-of-label
    spec:
      containers:
      - env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: IMAGE_NAME
        name: CONTAINER_NAME
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 2000Mi
          requests:
            cpu: "0.01"
            memory: 51Mi
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    new-label: NEW-LABEL
  name: ROLLOUT_NAME
  namespace: pxt-qa
spec:
  revisionHistoryLimit: 5
  strategy:
    canary:
      canaryMetadata:
        labels:
          role: new
      canaryService: canaryService-name
      maxUnavailable: 0
      stableMetadata:
        labels:
          role: current
      stableService: stableService-name
      steps:
      - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: stableService-name
            routes:
            - primary
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: DEPLOYMENT_NAME
```

### Kustomize version

v5.1.0

### Operating system

MacOS
