### DISCUSSION TITLE
KEDA: scaleTargetRef.name is not updated correctly

### DISCUSSION THREAD

**Discussion by cesar32az** [kubernetes-sigs/kustomize#5497] [Q&A]
### What happened?

I am using keda with kustomize and when adding the namePrefix and nameSuffix properties in the kustomization.yaml, the value of scaleTargetRef.name of the KEDA ScaledObject is not updated correctly

### What did you expect to happen?

what is expected is that the scaleTargetRef.name of the KEDA ScaledObject is updated correctly with the namePrefix and nameSuffix properties

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: hello-
nameSuffix: -world

resources:
  - scaled-object.yaml
  - deployment.yaml
```

```yaml
# scaled-object.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: example-scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment
  minReplicaCount: 0
  maxReplicaCount: 100
  triggers:
    - type: example-trigger
      metadata:
        property: examle-property
```

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      containers:
      - name: example-deployment
        image: example-image
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-example-deployment-world
spec:
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      containers:
      - image: example-image
        name: example-deployment
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: hello-example-scaledobject-world
spec:
  maxReplicaCount: 100
  minReplicaCount: 0
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-example-deployment-world # correct name
  triggers:
  - metadata:
      property: examle-property
    type: example-trigger
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-example-deployment-world
spec:
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      containers:
      - image: example-image
        name: example-deployment
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: hello-example-scaledobject-world
spec:
  maxReplicaCount: 100
  minReplicaCount: 0
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment
  triggers:
  - metadata:
      property: examle-property # incorrect name
    type: example-trigger
```

### Kustomize version

5.1.0

### Operating system

Linux

**Comment by pawndev** [comment]
Maybe you can add a `kustomconfig.yaml` with a specific transformer for name reference: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#name-reference-transformer

Something like:

```yaml
nameReference:
  - kind: ScaledObject
    fieldSpecs:
      - path: spec/scaleTargetRef/name
```

and then reference it in your `kustomization.yaml` with:

```yaml
configurations:
  - kustomconfig.yaml
```

I didn't test it, so it could not be working
