### DISCUSSION TITLE
Using and overriding variables in ConfigMaps?

### DISCUSSION THREAD

**Discussion by ArthurSap** [kubernetes-sigs/kustomize#5508] [Q&A]
I'm trying to use variables in the `ConfigMap` of my base overlay, variables which will be set differently in each overlay.
The folder structure is something along the lines of:
```
.
├── base/
│   ├── service_a/
│   │   ├── kustomization.yaml
│   │   └── service-a-configmap.yaml
│   ├── service_b/
│   │   └── ...
│   ├── kustomization.yaml
│   └── base-configmap.yaml
└── overlays/
    ├── dev/
    │   ├── kustomization.yaml
    │   └── dev-configmap.yaml
    └── prod/
        └── ...
```
I will describe more-or-less each relevant file to explain my question better:
`service-a-configmap.yaml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a-configmap
data:
  FOO_VAR: "something-$(BAR_VAR)"
```
--
`base-configmap`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: base-configmap
data:
  BAR_VAR: "per-overlay-$(ENV_NAME)-stuff"
```
`base/kustomization`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- name: BAR_VAR
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: base-configmap
  fieldref:
    fieldPath: data.BAR_VAR

resources:
- base-configmap.yaml
- ./service-a
- ./service-b
```
When I run `build` in the base folder, the result is as expected:
```
# Result in service-a-configmap
FOO_VAR: "something-per-overlay-$(ENV_NAME)-stuff"
...
# Result in base-configmap:
BAR_VAR: "per-overlay-$(ENV_NAME)-stuff"
```

I want to replace the `$(ENV_NAME)` with a different value in each overlay.
`dev-configmap`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-configmap
data:
  ENV_NAME: "dev"
```
And when running `build` from the dev overlay, my **_desired_** result is:
```
# Result in service-a-configmap
FOO_VAR: "something-per-overlay-dev-stuff"
...
# Result in base-configmap:
BAR_VAR: "per-overlay-dev-stuff"
```
But what I get is:
```
# Result in service-a-configmap
FOO_VAR: "something-per-overlay-$(ENV_NAME)-stuff" # <-- nothing changed
...
# Result in base-configmap:
BAR_VAR: "per-overlay-dev-stuff" # <-- changed as expected
```
Here's the `dev/kustomization` I'm trying to use:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
- name: ENV_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: dev-configmap
  fieldref:
    fieldPath: data.ENV_NAME

configurations:
- configuration.yaml # (contains only `varReference`  with {kind: ConfigMap, path: data})

resources:
- dev-configmap.yaml
- ../../base
```

What am I missing? Is this even possible?

There are 14 services in the `base` overlay, there are 13 values in the `base-configmap` that contain the `$(ENV_VAR)` (and other 2 similarly used variables), these values are used in most services (mostly as values in their respective `ConfigMap`s).
I don't think `replacements` is a good fit for my use-case.
I tried using `patches` in the `dev` overlay (by changing the name of the `ConfgiMap` to `base-configmap` too) to no avail.
