### DISCUSSION TITLE
Extend configMapGenerator to work with application.yml files

### DISCUSSION THREAD

**Discussion by mcdolding** [kubernetes-sigs/kustomize#5619] [Ideas]
The configMapGenerator will manage a configmap using properties of the form _myproperty=myvalue_. 
However I have springboot and quarkus applications which are configured using application.yml files (in place of application.properties files). At runtime we provide configmaps of the form:

```
  - kind: ConfigMap
    apiVersion: v1
    data:
      application.yml: |-
        my:
	  nested:
	    property1: myvalue1
	    property2: myvalue2
```

Would it be possible to extend configMapGenerator to handle yml properties?

**Comment by stormqueen1990** [comment]
Hello there, @mcdolding! 👋🏻

Currently, it's possible to add YAML file contents to a Kustomization using the `configMapGenerator` through the `files` field, or the `--from-file` CLI option if you're using `kustomize edit add`. For example, in a directory structure such as:
```none
.
|____kustomization.yaml
|____application.yaml
```

where your `application.yaml` has a content such as:
```yaml
server:
  port: 8080
```

you could use `kustomize edit add configmap test-cm --namespace test-ns --from-file=application.yaml` to generate the following `kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - application.yaml
  name: test-cm
  namespace: test-ns
```

which would then generate the following structure on `kustomize build`:
```yaml
apiVersion: v1
data:
  application.yaml: |
    server:
      port: 8080
kind: ConfigMap
metadata:
  name: test-cm-bd9fg9hb5h
  namespace: test-ns
```

It's also possible to override the YAML key when using `--from-file` by specifying it before the file name. For instance, running `kustomize edit add configmap test-cm --namespace test-ns --from-file=test.yaml=application.yaml` would yield:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - test.yaml=application.yaml
  name: test-cm
  namespace: test-ns
```

which then results in:
```yaml
apiVersion: v1
data:
  test.yaml: |
    server:
      port: 8080
kind: ConfigMap
metadata:
  name: test-cm-d76c2hh757
  namespace: test-ns
```

Does that address your use case?

**Comment by mcdolding** [comment]
Thanks for your detailed response. This is exactly what I need.

**Comment by jonenst** [comment]
Hi @stormqueen1990 , do you know if there is an easy way to write application.yaml files like this
```
a:
  b:
    c: val1
    d: val2
```

and from them generate configmaps like this:
```
data:
  a.b.c: val1
  a.b.d: val2
```

My use case is to be able to compose/override values in these application.yaml files. If you have everything in one big file, you can't selectively add/override values. Instead, if you have everything as one key in the configmap, you can mount this as a configtree and spring knows how to read them in the same way as one big file. And so you can use `behavior: merge` or `behavior: replace` to compose configmaps.

One alternative is to mount many big application.yaml files and rely on spring's order of precedence (usually with a wildcard like /config/* you get alphabetical order precedence) but I always find this not practical because each application.yaml needs to be in its own folder.
Another possibility is to have one big folder with many application-XXX.yaml files where XXX is the profile, but then you have to separately activate these profiles and I don't think there's a composable way to do this. 
A third alternative is to define the values manually like for properties, but it's pretty verbose espacially if you have deeply nested configuration (you need to repeat the prefix at each line). And it doesn't look like the usual spring yaml format (it looks more lire the usual spring properties format). Or you could define environment variables in the same way

Spring documentation on its configuration: https://docs.spring.io/spring-boot/reference/features/external-config.html

Maybe you have more insight on this topic ?

TIA,
Jon
