### DISCUSSION TITLE
Using configGeneration hash suffix with arbitrary resources referring to it (e.g. Flux HelmRelease)

### DISCUSSION THREAD

**Discussion by grrttedwards** [kubernetes-sigs/kustomize#5710] [Q&A]
Hello. Is there a general solution which allows for using the hash suffix generation and have kustomize replace references to it from other arbitrary resources? Or perhaps another workaround using replacements or transformers? For example, take the following setup:
```yaml
---
# helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp
spec:
  values:
    secretName: FOOBAR
---
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
secretGenerator:
  - name: FOOBAR
    options:
      disableNameSuffixHash: false
    files:
    - config.json
```
and `config.json` containing `123abc`

Using kustomize's config generation suffix hash feature, as far as I can tell, does not work with arbitrary resources which refer to this configmap name (of course kustomize cannot just blindly replace all instances of `FOOBAR` it finds in other resources). In my case, a Flux HelmRelease has no meaning to kustomize.

The output from above is
```yaml
$ kustomize build test | yq --colors
apiVersion: v1
data:
  config.json: MTIzYWJj
kind: Secret
metadata:
  name: FOOBAR-6642c8mk9m
type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp
spec:
  values:
    secretName: FOOBAR
```

This https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#name-reference-transformer seems very close to my solution, but given that this is 5+ year old documentation, is this at risk of being deprecated? I find it difficult to establish truth with kustomize and what features are new or old or deprecated.

**Comment by grrttedwards** [comment]
Name reference transformer is one solution to this problem:

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
secretGenerator:
  - name: FOOBAR
    options:
      disableNameSuffixHash: false
    files:
    - config.json
configurations:
  - nameReference.yaml
```

```yaml
# nameReference.yaml
---
nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: HelmRelease
        path: spec/values/secretName
```

```yaml
# helmrelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp
spec:
  values:
    secretName: FOOBAR
```

then `kustomize build .` produces

```yaml
apiVersion: v1
data:
  config.json: MTIzYWJj
kind: Secret
metadata:
  name: FOOBAR-6642c8mk9m
type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myapp
spec:
  values:
    secretName: FOOBAR-6642c8mk9m
```
