### DISCUSSION TITLE
configmap and content aware hashing

### DISCUSSION THREAD

**Discussion by tcurdt** [kubernetes-sigs/kustomize#5711] [Q&A]
I really don't get the config map hashing feature as documented.

What I want:

List all the configmaps in the config that should be renamed to their name with their content hash added as a suffix.

Is this possible or not? The `configMapGenerator` does not really seem to help here.

What I tried

```
resources:
- infra/caddy.yaml

configMapGenerator:
  - name: caddy
    files:
      - infra/caddy.yaml
```

Which already is a bit flawed because I want configmap caddy - but in the infra namespace.
What I would like is to have this modification:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: infra
  name: caddy-HASH
  labels:
    app: caddy
data:
  Caddyfile: |
    ...

...
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-HASH
```

**Comment by ChristianCiach** [comment]
You cannot use Kustomize to add a hash-suffix to an existing ConfigMap that you are providing yourself. Kustomize only adds hash-suffixes to ConfigMaps that are *generated* by Kustomize. 

I assume the file `infra/caddy.yaml` from your example is actually a ConfigMap *containing* the Caddy configuration, right?

What you should do is this:

```yaml
resources:
  - deployment.yaml # or some other workload that consumes the ConfigMap named `caddy-config`

configMapGenerator:
  - name: caddy-config
    files:
      - Caddyfile
```
