### DISCUSSION TITLE
OCI Bitnami charts

### DISCUSSION THREAD

**Discussion by qdrddr** [kubernetes-sigs/kustomize#5717] [Q&A]
Hi. Am I the only one having trouble with OCI bitnamicharts with kustomize?

```shell
kubectl kustomize infra-deployments/litellm/kustomizations --enable-helm > infra-deployments/litellm/kustomizations/litellm.kustimized.yaml
```

For example, if I have other OCI charts like this, all good:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-system
helmCharts:
  - name: litellm-helm
    repo: oci://ghcr.io/berriai
    #helm inspect chart oci://ghcr.io/berriai/litellm-helm
    version: 0.1.263
    releaseName: litellm-proxy
    valuesFile: helm-chart_litellm_v1.40.10.yaml
    includeCRDs: true
    namespace: ai-system
```

But with bitnamicharts OCI repo, I have a problem:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-system
helmCharts:
  - name: postgresql
     #repo: https://repo.vmware.com/bitnami-files
     repo: oci://registry-1.docker.io/bitnamicharts
     #helm inspect chart oci://registry-1.docker.io/bitnamicharts/postgresql
     version: 15.5.5
     releaseName: litellm-postgresql
     valuesFile: helm-values_postgresql_15.5.5.yaml
     includeCRDs: true
     namespace: ai-system
```
`kubectl kustomize infra-deployments/litellm/kustomizations --enable-helm > infra-deployments/litellm/kustomizations/litellm.kustimized.yaml`
Error message:
```
error: Error: looks like "oci://registry-1.docker.io/bitnamicharts/postgresql" is not a valid chart repository or cannot be reached: object required
: unable to run: 'helm pull --untar --untardir /Users/dberezenko/Library/CloudStorage/OneDrive-Personal/git/git.wiseinfotec.net/k8s-so/infra-deployments/litellm/kustomizations/charts --repo oci://registry-1.docker.io/bitnamicharts/postgresql postgresql --version 15.5.5' with env=[HELM_CONFIG_HOME=/var/folders/5h/qvzp0mfx2jd1rsxg4f9z91880000gn/T/kustomize-helm-357564855/helm HELM_CACHE_HOME=/var/folders/5h/qvzp0mfx2jd1rsxg4f9z91880000gn/T/kustomize-helm-357564855/helm/.cache HELM_DATA_HOME=/var/folders/5h/qvzp0mfx2jd1rsxg4f9z91880000gn/T/kustomize-helm-357564855/helm/.data] (is 'helm' installed?): exit status 1
```

**Comment by ishaan-jaff** [comment]
[👋 LiteLLM CTO] Hi @qdrddr , thanks for using LiteLLM. Can we hop on a quick call sometime this week? I’d love to help out with this issue + learn how we can improve litellm for you 

My cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2023-10 
My linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by ChristianCiach** [comment]
Your example works for me (ignoring the illegal yaml indentation). Fixed example:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-system
helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 15.5.5
    releaseName: litellm-postgresql
    includeCRDs: true
    namespace: ai-system
```

Running `kustomize build . --enable-helm` with this file works as expected.
