### DISCUSSION TITLE
Variable substitutions order.

### DISCUSSION THREAD

**Discussion by ArthurSap** [kubernetes-sigs/kustomize#5740] [Q&A]
I'm having a hard time understanding variable substitution order, especially if a value of a config map uses a variable from the same config map.
Given the following directory tree
```
├─ base
│  ├─ gateway
│  │  ├─ base
│  │  │  ├─ deployment.yaml
│  │  │  └─ config-map-base.yaml
│  │  ├─ kustomization.yaml
│  │  ├─ config-map.yaml
│  │  └─ kustomizeconfig.yaml
│  ├─ kustomization.yaml
│  └─ global-config-map-auto.yaml
└─ overlays
   └─ dev
      └─ kustomization.yaml
      └─ config-map.yaml
```
The base/gateway/config-map.yaml is used in a `patchesStrategicMerge` in the `kustomization.yaml` and has the following variable:
` BASE_URL_FRONTEND: "$(BUCKET_URL_PREFIX)/$(BUCKET_FRONTEND)"`

base/global-config-map-auto is used in a `patches`  in it's respective `kustomization.yaml` has the following:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: global-configmap
data:
  SERVICE_URL_SUFFIX: "$(NAMESPACE).svc.cluster.local"
  SERVICE_URL_PREFIX: "http://"
  BUCKET_URL_SERVICE: "gcs-test"
  BUCKET_URL_PREFIX: "$(SERVICE_URL_PREFIX)$(BUCKET_URL_SERVICE).$(SERVICE_URL_SUFFIX)"
  BUCKET_FRONTEND: "plugin-$(PROJECT)-$(ENV)-frontend-bucket"
```
The values of `NAMESPACE`, `PROJECT` and `ENV` are defined in the base overlay.

When I run `kustomize build` in the dev overlay, the result of `global-configmap` is correct - `BUCKET_URL_PREFIX` has the expected value.
But the result of `BASE_URL_FRONTEND` is insufficient - it is `$(SERVICE_URL_PREFIX)$(BUCKET_URL_SERVICE).$(SERVICE_URL_SUFFIX)/plugin-$(PROJECT)-$(ENV)-frontend-bucket`.
It seems it first substituted the variables in the gateway configmap and only then in the global configmap.
Why? 
What is the correct order?

For context, if necessary:
base/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./gateway

configurations:
- global-configs.yaml

vars:
- fieldref:
    fieldPath: data.SERVICE_URL_SUFFIX
  name: SERVICE_URL_SUFFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: global-configmap
- fieldref:
    fieldPath: data.SERVICE_URL_PREFIX
  name: SERVICE_URL_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: global-configmap
- fieldref:
    fieldPath: data.BUCKET_URL_PREFIX
  name: BUCKET_URL_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: global-configmap
- fieldref:
    fieldPath: data.BUCKET_FRONTEND
  name: BUCKET_FRONTEND
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: global-configmap

patches:
- path: global-configmap-auto.yaml
```
base/global-configs.yaml is the same as base/gateway/kustomizeconfig.yaml:
```
varReference:
- path: data
  kind: ConfigMap
```

overlays/dev/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plugin-dev

patches:
- path: config-map.yaml

resources:
- ../../base/
```
overlays/dev/config-map.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: bee-global-configmap
data:
  NAMESPACE: plugin-dev
  PROJECT: my-project
  ENV: dev
```
