### DISCUSSION TITLE
Overlay local values.yaml from remote Helm repo using Kustomize

### DISCUSSION THREAD

**Discussion by mihaigalos** [kubernetes-sigs/kustomize#5769] [Q&A]
I'm triying to use a kustomize remote base which wraps a Helm repo and template a local Helm values.yaml:

```yaml
resources:
  - https://github.enterprise.company/company/mercury-kyverno-manifest.git//deployment/?ref=feat/MERCURY-427/redesign/deps

generators:
- |-
  apiVersion: fn.kpt.dev/v1alpha1
  kind: RenderHelmChart
  metadata:
    name: demo
    annotations:
      config.kubernetes.io/function: |
        container:
          network: true
          image: gcr.io/kpt-fn/render-helm-chart:v0.2.2
          mounts:
            - type: bind
              src: ./values.yaml
              dst: /tmp/values.yaml
```
Doesn't work, only the resource is present in the output, nothing from the generator. I tried calling with:
```
kustomize build --enable-alpha-plugins --network .
```

The generator is processed after the resources, according to the [docs](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#plugin-orchestration):

> Generator plugins are run after processing the resources field (which itself can be viewed as a generator, simply reading objects from disk).

The following, however, does work but needs an Artifactory Helm repository. How can I adapt it to directly use GitHub Enterprise instead of Artifactory?

```yaml
generators:
- |-
  apiVersion: fn.kpt.dev/v1alpha1
  kind: RenderHelmChart
  metadata:
    name: demo
    annotations:
      config.kubernetes.io/function: |
        container:
          network: true
          image: gcr.io/kpt-fn/render-helm-chart:v0.2.2
          mounts:
            - type: bind
              src: ./values.yaml
              dst: /tmp/values.yaml
  helmCharts:
  - chartArgs:
      name: mercury-kyverno
      version: "2024.39.1"
      repo: https://artifacts.company/artifactory/mercury-helm-host
    templateOptions:
      # namespace: mynamespace
      # releaseName: foo
      values:
        valuesFiles:
          - tmp/values.yaml
```
