### DISCUSSION TITLE
Namespace fieldPath missing

### DISCUSSION THREAD

**Discussion by fhalde** [kubernetes-sigs/kustomize#5797] [General]
Can someone tell why kustomize complains that the fieldPath `.metadata.namespace` is missing even though I set the "namespace" in my kustomization.yaml ?

```
.
├── prod
│   ├── flink.yaml
│   └── kustomization.yaml
├── base
│   ├── flink.yaml
│   └── kustomization.yaml
├── components
│   └── dns
│       └── kustomization.yaml
└── app
    ├── flink.yaml
    └── kustomization.yaml
```

I have a base kustomize with a single resource
```
base/flink.yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flinkapp
spec:
  imagePullPolicy: Always
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"

base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flink.yaml
```

I have a prod overlay that adds an ingress to the flink deployment
```
prod/flink.yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flinkapp
spec:
  ingress:
   template: "{{name}}.mydns.com"
   className: "nginx"
   annotations:
     external-dns.alpha.kubernetes.io/hostname: "{{name}}.mydns.com"

prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../base

patches:
- path: flink.yaml
```

The "app", uses the prod overlay, adds a namespace, does a irrelevant patch to the spec and refers a component that alters the dns entry in ingress
```
app/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ./../prod

namespace: foobar

patches:
- path: flink.yaml

components:
- ./../components/dns
```

The component is basically using "replacements" to alter the ingress
```
components/dns/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: FlinkDeployment
      name: flinkapp
      fieldPath: .metadata.namespace
    targets:
      - select:
          kind: FlinkDeployment
        fieldPaths:
          - .spec.ingress.annotations.[external-dns.alpha.kubernetes.io/hostname]
        options:
          delimiter: '.'
          index: 0
          create: true
```

For some reason, kustomize is complaining that .medata.namespace does not exist. Even though in the app kustomization.yaml I've set the "namespace"

Am I missing something? The DNS subdomain HAS to be that of the provided namespace which is only known in the "app" kustomization
