### DISCUSSION TITLE
Configmap , add content to key file ->

### DISCUSSION THREAD

**Discussion by fontexD** [kubernetes-sigs/kustomize#5835] [General]
So i have this configmap.yml file i want to add data to the key  
rabbitmq.conf |-

ive tried so many diff methods according to docs, also tried with the configmap generator, im using overlays for diff env so in my base i have this ( i have more just for ease of complexity)

```yml
apiVersion: v1
data:
  enabled_plugins: |    [rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_prometheus].
  rabbitmq.conf: |-
    # Security settings
    loopback_users.guest = false

    # Queue settings
    classic_queue.default_version = 2

    # Networking settings
    listeners.tcp.default = 5672
    kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: p2l-test-services
```
  
  now in my overlay i want to append this to the rabbitmq.conf key
  
```yml
  cluster_name = RabbitMQ-default
  cluster_formation.k8s.hostname_suffix = '.rabbitmq-headless.p2l-default-services.svc.cluster.local'
```

so it turns out like this

```yml
apiVersion: v1
data:
  enabled_plugins: |    [rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_prometheus].
  rabbitmq.conf: |-
    # Security settings
    loopback_users.guest = false

    # Queue settings
    classic_queue.default_version = 2

    # Networking settings
    listeners.tcp.default = 5672
    cluster_name = RabbitMQ-default
    cluster_formation.k8s.hostname_suffix = '.rabbitmq-headless.p2l-default-services.svc.cluster.local'
    kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: p2l-test-services
```
  
  
  ive tried as mentioned with generator, merge, replace, add files everythiing, is  this just not a thing in kustomize ?
