### DISCUSSION TITLE
How to apply common annotations, labels, and transformations from base Kustomization in overlays that require new resources?

### DISCUSSION THREAD

**Discussion by x80486** [kubernetes-sigs/kustomize#5857] [Q&A]
I'm trying to refactor some Kubernetes applications to make use of bases and overlays but I'm running into an issue where labels and annotations are not being applied correctly to some specific resource files.

Basically, I have a base configuration consisting of `config-map.yaml`, `service.yaml`, `deployment.yaml`, `kustomization.yaml`, and `virtual-service.yaml`. These files contain common configuration settings that apply to all environments. This is the base `kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  key: value # Annotations that should be applied to all environments
namePrefix: app-name-
kind: Kustomization
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      key: value # Common labels that should be applied to all environments
resources:
  - config-map.yaml
  - deployment.yaml
  - service.yaml
  - virtual-service.yaml
```

I have one environment that doesn't require new resources — and everything works well. In another environment, where I need to add two additional configuration files: `autoscaler.yaml` and `destination-rules.yaml`, the labels, annotations, and some other transformations (e.g.: `namePrefix`) from the base `kustomization.yaml` are not being correctly applied to these additional files.

The `kustomization.yaml` for this environment looks like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  annotations-for-this-specific-environment: value
kind: Kustomization
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      labels-for-this-specific-environment: value
patches:
  - patch: some-patch-file.yaml # Patches for some resources
resources:
  - ../base # I've tried referring to base before and after the additional files
  - autoscaler.yaml
  - destination-rules.yaml
```

Is there a way to resolve this issue? It looks like a pretty common use case 🤔

I did try using components as well, but I've got exactly the same output.
