### DISCUSSION TITLE
NamespaceTransformer `unsetOnly: true` expectiation wrong

### DISCUSSION THREAD

**Discussion by menzbua** [kubernetes-sigs/kustomize#5897] [General]
Hi 👋,

I have configured a NamespaceTransformer to avoid namespace transformation for already set namespaces.

custom_namespace.yaml
```
---
apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: notImportantHere
  namespace: default
unsetOnly: true
```

My expectation is that manifests where the namespace is set would not be transformed anymore. I have this two kustomizations:

helm-release.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 10m
  values:
```

helm-repository.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/external-dns/
```

kustomization.yaml
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - helm-repository.yaml
  - helm-release.yaml
transformers:
  - transformers/custom_namespace.yaml
```

In the HelmRelease manifest, the namespace should be set by the transformer. In the HelmRepository the namespace should not be set because it is already set. But when I run `kustomize build .` I see this output.

output.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.16.1
  interval: 10m
  values: null
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/external-dns/
```

On both resources, the namespace would be set. Do I have a misunderstanding how the `unsetOnly` flag works? Or is there a configuration error on my site?
