### ISSUE TITLE
"conflicting fieldspecs" when trying to enable creation of antiAffinity commonLabel selectors

### ISSUE THREAD

**Issue by bcbrockway** [kubernetes-sigs/kustomize#1013]
Similar to https://github.com/kubernetes-sigs/kustomize/issues/817 but in my case I want to *enable* the addition of commonLabels to specific selectors. I have a StatefulSet for Elasticsearch for which I currently have to define these manually:

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: logging-plane
  template:
    metadata:
      labels:
        tier: logging-plane
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
```

The default transformer config disables auto-creation:

```yaml
commonLabels:
- path: spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/podAffinityTerm/labelSelector/matchLabels
  create: false
  group: apps
  kind: StatefulSet
```

I figured I could just create a new file with `create` set to `true` and then reference it in the `kustomization.yaml` file like so:

```yaml
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/app: elasticsearch
  app: elasticsearch
  role: master

resources:
  - resources/elasticsearch-master-statefulSet.yml

configurations:
  - configurations/commonlabels.yaml
```

But when I try and do a `kustomize build .` I get the following error:

```
Error: AccumulateTarget: AccumulateTarget: conflicting fieldspecs
```

**Comment by jbrette** [comment]
Looks like the only thing you need to do is add an empty matchLabels:. No need to override the default kustomizeconfig. I think you could close the bug

This file as resource:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: logging-plane
  template:
    metadata:
      labels:
        tier: logging-plane
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                matchExpressions:
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
```

produces:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
    app.kubernetes.io/app: elasticsearch
    role: master
  name: elasticsearch-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      app.kubernetes.io/app: elasticsearch
      role: master
      tier: logging-plane
  serviceName: elasticsearch-data
  template:
    metadata:
      labels:
        app: elasticsearch
        app.kubernetes.io/app: elasticsearch
        role: master
        tier: logging-plane
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - data
                matchLabels:
                  app: elasticsearch
                  app.kubernetes.io/app: elasticsearch
                  role: master
              topologyKey: kubernetes.io/hostname
            weight: 100
  updateStrategy:
    type: RollingUpdate
```

**Comment by rlaakkol** [comment]
@aexvir I think PodDisruptionBudgets are included in commonLabels propagation by default! I had the same issue and just removing the configuration fixed it for me.

**Comment by Maxim-Durand** [comment]
> [@aexvir](https://github.com/aexvir) I think PodDisruptionBudgets are included in commonLabels propagation by default! I had the same issue and just removing the configuration fixed it for me.


`commonLabels` is now deprecated and `labels` should be used instead.

I'm on kustomize v5.4.3 and using
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/poddisruptionbudget.yaml

labels:
  - pairs:
      app.kubernetes.io/name: X
      app.kubernetes.io/component: X
      app.kubernetes.io/part-of: X
    includeTemplates: true
    includeSelectors: true
```
With
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fake
spec:
  maxUnavailable: 50%
  selector: {}
```

Results in
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/component: X
    app.kubernetes.io/name: X
    app.kubernetes.io/part-of: X
  name: fake
spec:
  maxUnavailable: 50%
  selector: {}
```

So PodDisruptionBudget selector isn't propagated correctly, so I tried specifying the field like so
```
labels:
  - pairs:
      app.kubernetes.io/name: X
      app.kubernetes.io/component: X
      app.kubernetes.io/part-of: X
    includeTemplates: true
    includeSelectors: true
    fields:
      - path: spec/selector/matchLabels
        create: true
        kind: PodDisruptionBudget
        version: v1
        group: policy
```
But it only runs into the original error of this issue `Error: failed to merge labels: conflicting fieldspecs`
This issue can be fixed by setting `includeSelectors: false` (default value), but what if I want it for other resources...
