### ISSUE TITLE
"kustomize build" fails on empty "annotations:" line

### ISSUE THREAD

**Issue by embik** [kubernetes-sigs/kustomize#1017]
kustomize `2.0.3` fails with this example:

kustomization.yaml:
```yaml
commonAnnotations:
  test: test

resources:
  - pod.yaml
```

pod.yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
spec:
  containers:
    - image: busybox
      name: busybox
```

```sh
$ kustomize build
Error: <nil> is expected to be map[string]interface {}
```

The `annotations:` line in `pod.yaml` is responsible for this. It seems like kustomize cannot handle an empty but defined `annotations` field here.

This is an issue because cert-manager distributes a YAML bundle that contains this issue (see [cert-manager.yaml](https://github.com/jetstack/cert-manager/blob/v0.7.1/deploy/manifests/cert-manager.yaml#L1407)) and makes adding common annotations impossible as of now, at least without updating the source file by hand.

I guess this is a more of an edge case and it probably should not happen (kustomize should not handle all mistakes made in distributed manifests), but IMHO kustomize should be smart enough for this, at least with labels and annotations.
