### ISSUE TITLE
Unexpected magic - kustomize build changes values without an explicit patch

### ISSUE THREAD

**Issue by antonosmond** [kubernetes-sigs/kustomize#1026]
Hi
I'm not sure if this is a feature, a lack of understanding on my part or something else but I have a strange thing happening when doing a kustomize build using overlays.

kustomize version: v2.0.3

Given the following structure:

```
├── base
│   ├── kustomization.yaml
│   ├── pod.yaml
│   └── service-account.yaml
└── overlays
    └── example
        ├── kustomization.yaml
        └── patch-service-account.yaml
```

And the following base files:
```yaml
# base/kustomization.yaml
resources:
- pod.yaml
- service-account.yaml
```

```yaml
# base/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["tail", "-f", "/dev/null"]
  terminationGracePeriodSeconds: 0
  serviceAccountName: example
```

```yaml
# base/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example
```

And the following overlay files:

```yaml
# overlays/example/kustomization.yaml
bases:
- ../../base

patchesJson6902:
- path: patch-service-account.yaml
  target:
    version: v1
    kind: ServiceAccount
    name: example
```

```yaml
# overlays/example/patch-service-account.yaml
- op: replace
  path: "/metadata/name"
  value: "updated-example"
```

I run `kustomize build overlays/example/`

My expectation was that the metadata.name field of the service account resource would be updated from `example` to `updated-example` as per the patch.
What actually happens is the `serviceAccountName` field of the pod resource is also being patched regardless of no explicit patch for it.

Is this the expected behaviour? 
What if I don't want to update the pod?

Thanks

Anton
