### ISSUE TITLE
The patchesStrategicMerge cannot merge crd tfjobs

### ISSUE THREAD

**Issue by jinchihe** [kubernetes-sigs/kustomize#1027]
Hello,

I have a problem for merge crd tfjobs by using `patchesStrategicMerge`. My case is simple, `base` + `overlay`, as below.

There are 4 files:
```
# tree 
.
├── base
│   ├── kustomization.yaml
│   └── training.yaml
└── overlay
    └── local
        ├── kustomization.yaml
        └── training.yaml
```
The `base` kustomization.yaml and training.yaml are as following:
```
# cat base/kustomization.yaml 
resources:
- training.yaml
# cat base/training.yaml 
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: mnist-train-local
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            command:
            - /usr/bin/python
            - /opt/model.py
            image: docker.mixhub.cn/jinchi/mnist_example:0.1
            workingDir: /opt
          restartPolicy: OnFailure
```

```
# cat base/kustomization.yaml 
resources:
- training.yaml
```
And the `overlay` files are as following:
```
# cat overlay/local/kustomization.yaml 
bases:
- ../../base
patchesStrategicMerge:
- training.yaml
# cat overlay/local/training.yaml 
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: mnist-train-local
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            volumeMounts:
            - mountPath: /mnt
              name: local-storage
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: mnist-pvc
```
```
# cat overlay/local/kustomization.yaml 
bases:
- ../../base

patchesStrategicMerge:
- training.yaml
```

Run the `kustomize build overlay/local/`.
```
$ kustomize build overlay/local/
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: mnist-train-local
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            volumeMounts:
            - mountPath: /mnt
              name: local-storage
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: local-storage
            persistentVolumeClaim:
              claimName: mnist-pvc
```
Then you will find containers metrics in `base` such as `command` and `image` are lost, only have `overlay` configurations, but I want to merge `base` and `overlay` configurations.

How to resolve the problem? Thank a lot!
