### ISSUE TITLE
use transformer plugin to update fields which can't be done easily otherwise

### ISSUE THREAD

**Issue by alexppg** [kubernetes-sigs/kustomize#1039]
This kind of patches are useful to manage lists. When you're managing lists, you don't know or care how long this list is. For example, in this resumed file:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: http
spec:
  groups:
  - name: blackbox.rules
    rules:
    - alert: HTTP1
      for: 60s
```

You would create the next `kustomization.yml` file:
```yaml
...
patchesJson6902:
- path: severity.yml
  target:
    group: monitoring.coreos.com
    kind: PrometheusRule
    name: http
    version: v1
```

And `severity.yml` being this:

```yaml
- op: add
  path: /spec/groups/0/rules/0/labels
  value:
    severity: none
```

This would generate:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: http
spec:
  groups:
  - name: blackbox.rules
    rules:
    - alert: HTTP1
      for: 60s
      labels:
        severity: none
```

But what if I add another rule?

```yaml
...
spec:
  groups:
  - name: blackbox.rules
    rules:
    - alert: HTTP1
      for: 60s
    - alert: HTTP2
      for: 60s
```

Then, I'd need to add to the `severity.yml` file another rule to patch:

```yaml
- op: add
  path: /spec/groups/0/rules/0/labels
  value:
    severity: none
- op: add
  path: /spec/groups/1/rules/0/labels
  value:
    severity: none
```

This is very clumpsy when you have 20 members of a list, it's easy to forget one. 

It would be way better to be able to do this:

```
op: add
  path: /spec/groups/*/rules/0/labels
  value:
    severity: none
```

This also would be usefule because I could apply the same patch file to many files, since I wouldn't care about the list's length.
