### ISSUE TITLE
The images in base will be used if defined images both in base and overlay.

### ISSUE THREAD

**Issue by jinchihe** [kubernetes-sigs/kustomize#1040]
Problem: The images in base will be used if defined images both in base and overlay.

Define image in base Kustomization.yaml as below.
```
images:
- name: training-image
  newName: myimage/base
  newTag: v1
```
in Overlay Kustomization.yaml as below.
```
bases:
- ../base

images:
- name: training-image
  newName: myimage/overlay
  newTag: v2
```

The `myimage/base:v1` will be used, I think the overlay image shoule overwrite the base one.

**Comment by Liujingfang1** [comment]
By the `newName` in the base, the image name has been updated to `myimage/base`. So the overlay `images` doesn't find any matched image to replace.

You can fix this by different ways:
1. In the base, keep the image unchanged. Then you can create two overlays, one with  `myimage/base` and the other with `myimage/overlay`
2. In the overlay, change `images` to the following
```
bases:
- ../base

images:
- name: myimage/base
  newName: myimage/overlay
  newTag: v2
```
