### ISSUE TITLE
field specified in var not found in corresponding resource

### ISSUE THREAD

**Issue by aviau** [kubernetes-sigs/kustomize#1058]
Hello! I am trying to create a `var` that points to a deployment's `spec.replicas` field:

```yaml
vars:
- name: SOMETHING_REPLICAS
  objref:
    group: apps
    apiVersion: v1beta1
    kind: Deployment
    name: something
  fieldref:
    fieldpath: spec.replicas
```

And I am getting the following error when running ``kustomize build``:
```
Error: field specified in var '{SOMETHING_REPLICAS apps_v1beta1_Deployment {spec.replicas}}' not found in corresponding resource
```

I can point to any field in ``metadata`` just fine, but not to the fields in ``spec``. Is this a bug?

**Comment by Liujingfang1** [comment]
You can't have `group` and `apiVersion` at the same time. Change it to
```
vars:
- name: SOMETHING_REPLICAS
  objref:
    group: apps
    version: v1beta1
    kind: Deployment
    name: something
  fieldref:
    fieldpath: spec.replicas
```
