### ISSUE TITLE
[bug] ConfigMap behavior add / replace both failed

### ISSUE THREAD

**Issue by kwladyka** [kubernetes-sigs/kustomize#1059]
kustomization.yaml
```
bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v0.12.3
- argocd-cm
```

argocd-cm/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  disableNameSuffixHash: true

configMapGenerator:
- name: argocd-cm
  behavior: replace
  files:
  - repositories
  - helm.repositories
```

```
Error: AccumulateTarget: id resid.ResId{gvKind:gvk.Gvk{Group:"", Version:"v1", Kind:"ConfigMap"}, name:"argocd-cm", prefix:"", suffix:"", namespace:""} does not exist; cannot merge or replace
```

When changed to  `behavior: add`
```
Error: github.com/argoproj/argo-cd/manifests/cluster-install?ref=v0.12.3: id '"~G_v1_ConfigMap|~X|~P|argocd-cm|~S"' already used
```

bases order doesn't matter.

**Comment by Liujingfang1** [comment]
@kwladyka Instead of creating a base to override the ConfigMap `arocd-cm`, you need to put the `configMapGenerator` in the overlay kustomization.yaml

```
bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v0.12.3

configMapGenerator:
- name: argocd-cm
  behavior: replace
  files:
  - repositories
  - helm.repositories
```
