### ISSUE TITLE
Json patch with deep objects fail

### ISSUE THREAD

**Issue by fentas** [kubernetes-sigs/kustomize#1061]
If I want to add a _deep_ object via JSON patch it won't work
```yaml
- op: add
  path: /spec/template/spec/volumes/-
  value:
  - name: cilium-ipsec-secrets
    secret:
      secretName: cilium-ipsec-keys
```

resulting in 
```sh
➜ kustomize build kustomize/infrastructure/overlays/hetzner/
Error: []interface {}{map[string]interface {}{"name":"cilium-ipsec-secrets", "secret":map[string]interface {}{"secretName":"cilium-ipsec-keys"}}} is expected to be map[string]interface {}
```

note: flat objects work as expected.
