### ISSUE TITLE
not overlay correctly

### ISSUE THREAD

**Issue by coolyrat** [kubernetes-sigs/kustomize#1062]
### cli version
`▶ kustomize version
Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}`

### my project layout
```
root
|_app_a
|_app_b
|_app_...
|_overlays
  |_dev
    |_app_a
      |_kustomization.yaml
    |_app_b
      |_kustomization.yaml
    |_app_...
      |_kustomization.yaml
	|_kustomization.yaml
```

overlays/dev/kustomization.yaml
```yaml
commonLabels:
  tier: backend
  env: dev

bases:
 - app_a
 - app_b
 - app_...
```

overlays/dev/a/kustomization.yaml
```yaml
commonLabels:
  tier: fronend
  app: app_a
```

exec kustomize build overlays/dev expect to see:
app_b to app_n have labels
```
labels:
  app: app_b
  tier: backend
  env: dev
```

app_a have labels
```
labels:
  app: app_a
  tier: frontend
  env: dev
```

instead i have all tier=backend.
