### ISSUE TITLE
Error: json: unknown field "envs" when building the example in docs

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#1069]
It seems caused by the `secretGenerator`.

```
~/go/src/sigs.k8s.io/kustomize/ master
❯ kustomize build docs
Error: json: unknown field "envs"

❯ kustomize version
Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}
```

The error will disappear if we modify `envs` to `env`, e.g.

```
secretGenerator:
- name: env_file_secret
  # paths to files with k=v pairs, one pair per line.
  env: env.txt
  type: Opaque
```

Is there a change in the spec recently?
