### ISSUE TITLE
Kustomize fails to find object in base modified with nameSuffix

### ISSUE THREAD

**Issue by jessesuen** [kubernetes-sigs/kustomize#1082]
Consider the following directory structure:

```
.
├── aggregate                // contains guestbook-a and guestbook-b as bases.
│   ├── kustomization.yaml   // also applies a patch on guestbook-a
│   └── patch-a.yaml
├── guestbook-a              // contains template as base with nameSuffix: -a
│   └── kustomization.yaml
├── guestbook-b              // contains template as base with nameSuffix: -b
│   └── kustomization.yaml
└── template                 // single resource
    ├── guestbook.yaml
    └── kustomization.yaml
```

When attempting to build the aggregate, it fails with error:
```bash
$ kustomize build aggregate
Error: failed to find an object with ~G_v1_Pod|guestbook-a to apply the patch
```

* aggregate/kustomization.yaml
```yaml
bases:
- ../guestbook-a
- ../guestbook-b
patchesStrategicMerge:
- patch-a.yaml
```

* aggregate/patch-a.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: guestbook-a
spec:
  containers:
  - name: nginx
    env:
    - name: FOO
      value: bar
```

* guestbook-a/kustomization.yaml
```yaml
bases:
- ../template
nameSuffix: -a
```

* template/kustomization.yaml
```yaml
resources:
- guestbook.yaml
```

I made this available here:
https://github.com/jessesuen/k8s-deployments/tree/master/kustomize-suffix-failed-find-obj

I expect patching to work on objects in the base, even after name transformation using `namePrefix` or `nameSuffix`. However, it does not find the object transformed with nameSuffix. Interestingly, if I modify `patch-a.yaml` to reference the name of the resource without the suffix, it gets the following error:

```bash
$ kustomize build aggregate
Error: found multiple objects []resid.ResId{resid.ResId{gvKind:gvk.Gvk{Group:"", Version:"v1", Kind:"Pod"}, name:"guestbook", prefix:"", suffix:"-b", namespace:""}, resid.ResId{gvKind:gvk.Gvk{Group:"", Version:"v1", Kind:"Pod"}, name:"guestbook", prefix:"", suffix:"-a", namespace:""}} targeted by patch resid.ResId{gvKind:gvk.Gvk{Group:"", Version:"v1", Kind:"Pod"}, name:"guestbook", prefix:"", suffix:"", namespace:""} (ambiguous)
```

This is reproducible with both v2.0.3 and tip of master from today (f9c631e9).
