### ISSUE TITLE
namespace transformer should be processed even for ignored types

### ISSUE THREAD

**Issue by tkellen** [kubernetes-sigs/kustomize#1094]
Due to the [hard-coding of `APIService` as a skipped type](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/gvk/gvk.go#L179-L188) it is not possible to have kustomize use the namespace transformer for fields within that resource which *do* require a namespace.

By example, here is an APIService from cert-manager which has a namespace under `spec/service`.
```
# Source: cert-manager/charts/webhook/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.admission.certmanager.k8s.io
  labels:
    app: webhook
  annotations:
    certmanager.k8s.io/inject-ca-from: "cert-manager/cert-manager-webhook-webhook-tls"
spec:
  group: admission.certmanager.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook
    namespace: "cert-manager"
  version: v1beta1
```

...adding a namespace transformer of this type:
```
namespace:
  - kind: APIService
    path: spec/service/namespace
```

...has no effect. If you rename the kind to "APIService**s**" in both places the namespace transformer works as expected.
