### ISSUE TITLE
ease changing replica count via kustomization

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#1114]
One can modify replicas now with a patch, but its verbose.

To kustomization.yaml add the field

```
replicas:
- name: {resourceName1}
  count: {numReplicasFor1}
- name: {resourceName2}
  count: {numReplicasFor2}
```

To modify replicas field in Deployments (or any resource that has a replicas field).
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
```
