### ISSUE TITLE
No name reference on admission webhook configuration

### ISSUE THREAD

**Issue by qiujian16** [kubernetes-sigs/kustomize#1122]
kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - local.yaml
namePrefix: test-
```

with local.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: my-service

---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: example
webhooks:
  - name: example
    clientConfig:
      caBundle: ""
      service:
        name: my-service
        namespace: default
```

service name in ValidatingWebhookConfiguration does not change
