### ISSUE TITLE
Having null value in a configmap patch removes property 

### ISSUE THREAD

**Issue by SatheeshJM** [kubernetes-sigs/kustomize#1124]
When I apply a configmap patch which contains a null value for a key, it removes the key completely. 
For example

--
This is my folder structure. 
```
_base
  kustomization.yaml
  configmap.yaml
flower
  kustomization.yaml
  configmap_patch.yaml
```
`_base/configmap.yaml`
```
apiVersion: v1
kind: ConfigMap

metadata:
  name: my-config
data:
  fruit:
  flower:
```
`flower/configmap_patch.yaml`
```
apiVersion: v1
kind: ConfigMap

metadata:
  name: my-config
data:
  flower: rose
```

Now when I run `kustomize build flower` the output is 
```
apiVersion: v1
data:
  flower: rose
  fruit: null
kind: ConfigMap
metadata:
  name: my-config
``` 

which is expected.. 
Note the `fruit: null` config property. 

---

now when I change my `configmap_patch.yaml` to 
```
apiVersion: v1
kind: ConfigMap

metadata:
  name: my-config
data:
  fruit: 
  flower: rose
```
and run  `kustomize build flower` the output I get is 

```
apiVersion: v1
data:
  flower: rose
kind: ConfigMap
metadata:
  name: my-config
```
Note that the `fruit: null` config property is missing. 

Is this expected behaviour or bug?

**Comment by Liujingfang1** [comment]
If you are using strategic merge patch, that is the expected behavior.

**Comment by yalegria** [comment]
I'm having a similar issue, here is my patch in kustomization.yml

```
patches:
- target:
    version: v1
    kind: Service
    name: nodeappd-service
  path: patch-service-type.yml
```

and here is my patch-service-type.yml
```

apiVersion: v1
kind: Service
metadata:
  name: nodeappd-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort:
```

the build does not include nodePort.

FYI, I am trying to change a service from LoadBalancer to ClusterIP, and I need this workaround in order to apply.
