### ISSUE TITLE
Proposal: Support overlaying guide comment

### ISSUE THREAD

**Issue by anarcher** [kubernetes-sigs/kustomize#1125]
Sometimes, I think It would be nice if bases should guide how overlays extend the bases. When writing overlays, we maybe realize easily which parts of the bases we should do and we can validate the overlay is good or not with this guide. So this annotation can help to make documentation about how to use the base.
IMHO, It seems like `Access Modifier` concept with various languages.  I feel good to use `annotation comment` for it. (like `import comment` in go)

```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    # @overlay:required
    # replace with the correct value of the generated certificate in the AWS console
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "your resource tags"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "your ssl cert"
    # @overlay:end
```
When overriding the base, the overlays should override this part(`annotations.s.../aws-...`) and `kustomize build` can detect with this `annotation comment`.

What do you think about it? :-)

**Comment by dexhorthy** [comment]
+1, some way of specifying recommended or required overlay fields seems super useful for the OTS case. As an alternative to comments, has something in `kustomization.yaml` been considered? E.g. (super rough)

```yaml
patches: ...
bases: ...
required:
- name:
  group:
  version:
  kind:
  path: metadata.annotations["service.kubernetes.io/..."]
```
