### ISSUE TITLE
ConfigMap Name & Referencing it in a Deployment

### ISSUE THREAD

**Issue by bitva77** [kubernetes-sigs/kustomize#1127]
I think I'm misunderstanding something with the ConfigMap name and how to reference it in a Deployment. Either that or there's a bug but I'm assuming the problem lies with me specifically :) 

My base deployment YAML has:

```
    spec:
      volumes:
      - name: config
        configMap:
          name: logstash-config
```

My `kustomization.yaml` has:

```
namePrefix: rabbitmq-to-rabbitmq-

configMapGenerator:
- name: logstash-config
  namespace: logstash
  behavior: replace
  files:
    - config/pipeline.conf
    - config/jvm.options
    - config/logstash.yml
```

But what gets built is:

```
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: rabbitmq-to-rabbitmq
  name: rabbitmq-to-rabbitmq-logstash-config
```

It's pre-pending the namePrefix, which I sort of get, what's the point of the `-name` field for `configMapGenerator` if it get's overwritten?

Reading the `kustomization.yaml` documentation it mentions this:

```
# Vars should _not_ be used for inserting names in places
# where kustomize is already handling that job.  E.g.,
# a Deployment may reference a ConfigMap by name, and
# if kustomize changes the name of a ConfigMap, it knows
# to change the name reference in the Deployment.
```

How can kustomize change the name reference in the Deployment exactly?

Thanks!
