### ISSUE TITLE
remote build take too long

### ISSUE THREAD

**Issue by dungdm93** [kubernetes-sigs/kustomize#1132]
`kustomize` take too long to build remote bases. For example:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6
```
run:
```bash
$ time kustomize build .
....
real    1m25.333s
user    0m3.969s
sys     0m0.663s
```

----------
And time to build the real apps:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
bases:
- github.com/kubernetes/ingress-nginx//deploy/cluster-wide
- github.com/kubernetes/ingress-nginx//deploy/cloud-generic
```

```bash
$ time kustomize build .
...
real    14m41.983s
user    0m23.722s
sys     0m4.513s
```

**Comment by monopole** [comment]
i'm guessing network latency?

although it's _possible_ to depend on remote repos in this way, it's not recommended, because of the latency, and because more importantly those repos can change at any time (if not under your control).  

the best practice here would be to clone those repositories locally, and depend on your cloned repos via a base expressed as a relative file path.

you can rebase those clones whenever you want.

please re-open if i've misunderstood the issue.

**Comment by hc-chien** [comment]
simple test:

`apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6
- github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6
- github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6
- github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6
- github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6`

it was very slow

**Comment by dungdm93** [comment]
Hello @monopole 
I know this slowness mostly because of network latency, but not everyone in the world has super-fast internet connection, right? And we still have ways to improve the speed, like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
bases:
- github.com/kubernetes/ingress-nginx//deploy/cluster-wide
#- github.com/kubernetes/ingress-nginx//deploy/cloud-generic
```

```bash
$ time kustomize build .
...
real    7m21.835s
user    0m11.168s
sys     0m2.256s
```
In comparison to above test, the time is only a half.
So, It seems like Kustomize did **double clone** the same repo.

BTW, could u plz reopen this issue?
