### ISSUE TITLE
Supporting multiple secrets stored in one yaml file for secretGenerator

### ISSUE THREAD

**Issue by nickamorim** [kubernetes-sigs/kustomize#1135]
It would be useful if Kustomize's secretGenerator supported a stringData field or something similar; so it would parse the file provided in the 'files' field that consists of multiple secrets. This doesn't have to be the solution but just something that allows for multiple secrets being stored in one file would be extremely helpful.

Example:
xyz.yaml consists of three secrets x.pem, y.pem and z.pem.

Thanks!

**Comment by monopole** [comment]
The `secretGenerator` can generate N secrets:

```
secretGenerator:
- name: alice
  files:
  - foo.env
- name: bob
  files:
  - passphrase=phrase.dat
```

or generate one secret with data from N files:

```
secretGenerator:
- name: alice
  files:
  - foo.env
  - passphrase=phrase.dat
```
or combine these notations (N secrets with multiple files per secret).

Does that help?
