### ISSUE TITLE
CRDs containing 'containers' or 'initContainers' key unusable with image transformer

### ISSUE THREAD

**Issue by bzub** [kubernetes-sigs/kustomize#1146]
Although https://github.com/kubernetes-sigs/kustomize/issues/890 is closed I am seeing a similar if not identical problem as described there.

`kustomize version`
```
Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}
```

I get this error:
```
Error: containers path is not of type []interface{} but map[string]interface {}
```

With this `kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/coreos/kube-prometheus?ref=v0.1.0

images:
  - name: anyImageName
```

[0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml](https://github.com/coreos/kube-prometheus/blob/master/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml) is one of the CRDs that seems to cause this issue.
