### ISSUE TITLE
configMapGenerator can't make multiple identically named ConfigMaps with different namespaces

### ISSUE THREAD

**Issue by tkellen** [kubernetes-sigs/kustomize#1155]
```
kustomize version 
```
```
Version: {KustomizeVersion:2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-05T20:37:42Z GoOs:linux GoArch:amd64}
```
```
cat <<EOF > kustomization.yml
configMapGenerator:
- name: test
  namespace: default
  literals:
    - key=value
- name: test
  namespace: kube-system
  literals:
    - key=value
EOF
```
```
kustomize build .
```
```
Error: id resid.ResId{gvKind:gvk.Gvk{Group:"", Version:"v1", Kind:"ConfigMap"}, name:"test", prefix:"", suffix:"", namespace:"default"} exists; must merge or replace
```

**Comment by jbrette** [comment]
@tkellen Can you check that this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1221) addressed the issue.

The kustomization.yaml looks like this

```yaml
configMapGenerator:
- name: test
  namespace: default
  literals:
    - key=value
- name: test
  namespace: kube-system
  literals:
    - key=value
secretGenerator:
- name: test
  namespace: default
  literals:
  - username=admin
  - password=somepw
- name: test
  namespace: kube-system
  literals:
  - username=admin
  - password=somepw
```

This is the result of the `kustomize build .` command
```yaml
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: test-t5t4md8fdm
  namespace: default
---
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: test-t5t4md8fdm
  namespace: kube-system
---
apiVersion: v1
data:
  password: c29tZXB3
  username: YWRtaW4=
kind: Secret
metadata:
  name: test-h65t9hg6kc
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  password: c29tZXB3
  username: YWRtaW4=
kind: Secret
metadata:
  name: test-h65t9hg6kc
  namespace: kube-system
type: Opaque
```
