### ISSUE TITLE
support inlining patches in kustomization.yaml 

### ISSUE THREAD

**Issue by prydonius** [kubernetes-sigs/kustomize#1157]
It would be easier to share and provide examples for kustomize configurations if patches could be inlined, e.g.:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/my/wordpress-base

patchesStrategicMerge:
- |
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: wordpress
  spec:
    template:
      spec:      
        containers:
        - name: wordpress
          env:
          - name: MARIADB_HOST
            value: my-external-mariadb
          - name: MARIADB_PORT_NUMBER
            value: "3306"

patchesJson6902:
- target:
    version: extensions/v1beta1
    kind: Deployment
    name: wordpress
  patch: |
    - op: replace
      path: /spec/replicas
      value: 3
```

This would then allow me to share a single kustomization.yaml file for an application and expose certain configurations to users.
