### ISSUE TITLE
commonAnnotations from file

### ISSUE THREAD

**Issue by tkellen** [kubernetes-sigs/kustomize#1168]
Would you support a PR that adds the ability to specify commonAnnotations from external files in a similar manner as the configMapGenerator?

**Comment by monopole** [comment]
I think v.2.1.1 should have new directives for labels, selectors and annotations that supports this and the behavior described in #1009 in some consistent fashion

`commonLabels` and `commonAnnotations` are by design simple (they just take a map) and this makes them hard to modify without either breaking everyone or introducing some bizarre syntax.  These fields can continue to exist alongside new directives.

Any specific proposals for a new field?  I like the idea of an annotations maker field that looks like the configMapGenerator field.

**Comment by tkellen** [comment]
Hmm. I think perhaps we're talking about different things. Assume I have a cluster produced by terraform that outputs files which each have a single line value in them to record commonly needed values for workloads in the cluster:
```
.
├── cluster-config           
    └── environment
        ├── elb_hostname    
        ├── hostname       
        └── rds_ci_hostname  
```

Currently the only way I can bring those values into the cluster using kustomize is like this:
```
configMapGenerator:
  - name: environment
    files:
      - cluster-config/environment/hostname
      - cluster-config/environment/rds_ci_hostname
      - cluster-config/environment/elb_hostname
```


...which means, for example, in a pod spec, I consume them like this:
```
          env:
            - name: CONCOURSE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: rds_ci_hostname
```

I would prefer to put the value directly on the pod doing something like this:
```
commonAnnotationGenerator:
  files:
    - cluster-config/environment/hostname
    - cluster-config/environment/rds_ci_hostname
    - cluster-config/environment/elb_hostname
```

...and retrieve it like this:
```
      env:
        - name: CONCOURSE_POSTGRES_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations.rds_ci_hostname
```

This would eliminate the configmap indirection and allow more fine grained control of what values are passed around.

After having typed this all out, I think a more general/powerful approach to accomplish this would be allowing `kustomize` to populate any `value` key indirectly with `valueFrom` e.g.
```
valueFrom:
  fileRef:
    path: cluster-config/environment/hostname
```

I'm going to close this issue in favor of that and open a new ticket.
