### ISSUE TITLE
Add support for indexing in fieldPath of a variable

### ISSUE THREAD

**Issue by ian-howell** [kubernetes-sigs/kustomize#1179]
Currently, kustomize is unable to target an array value. This could be improved to support the following format for a fieldPath:

```
spec.template.spec.containers[0].command[0]
```

As an example, suppose we have the following directory structure, with relevant file contents provided after:

```
.
├── foo
│   ├── deployment.yaml
│   └── kustomization.yaml
├── kustomization.yaml
├── patch.yaml
└── bar
    ├── deployment.yaml
    └── kustomization.yaml
```

**foo/deployment:**
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: alpine
        name: foo
        command:
          - printf "I'm foo\n"
```

**bar/deployment:**
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  selector:
    matchLabels:
      app: bar
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - image: alpine
        name: bar
```

**kustomization.yaml:**
```
bases:
  - foo
  - bar
namePrefix: indexing-example-
patchesStrategicMerge:
  - patch.yaml
vars:
  - name: COMMAND
    objref:
      kind: Deployment
      name: foo
      apiVersion: apps/v1beta2
    fieldref:
      fieldpath: spec.template.spec.containers[0].command[0]
```

**patch.yaml:**
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bar
spec:
  template:
    spec:
      containers:
      - name: bar
        command:
          - $(COMMAND)
```

Given these kustomizations, we would expect a `kustomize build .` to look up the **first** command of the **first** container of the foo Deployment, and use the value it finds as the command for the container named bar in the bar Deployment.
