### ISSUE TITLE
Jobs should not add spec.selector

### ISSUE THREAD

**Issue by traherom** [kubernetes-sigs/kustomize#118]
Kustomize adds `spec.selector` to Job definitions, which normally [you don't want to do](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#specifying-your-own-pod-selector).

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: "core:latest"
        imagePullPolicy: IfNotPresent
        command: ["python3", "manage.py", "initializedb"]
        envFrom:
          - configMapRef:
              name: settings-map
          - secretRef:
              name: secrets-map
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secrets-map
                key:  django-secret-key
```

Results in 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: xylok
  name: migration
  namespace: default
spec:
  backoffLimit: 4
  selector:
    matchLabels:
      app: xylok
  template:
    metadata:
      labels:
        app: xylok
    spec:
      containers:
      - command:
        - python3
        - manage.py
        - initializedb
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: secrets-map-hmh762fg95
        envFrom:
        - configMapRef:
            name: settings-map-5hhf57bc2d
        - secretRef:
            name: secrets-map-hmh762fg95
        image: core:latest
        imagePullPolicy: IfNotPresent
        name: migration
      restartPolicy: Never
```

Applying it results in:
```
The Job "migration" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"xylok", "controller-uid":"a2126cd5-7316-11e8-86df-08002746865b"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated
```

Commenting out the `spec.selector` portion allows the Job to be correctly applied.

Is there a reason Kustomize *should* add matchLabels?

I assume removing lines 85-89 of the [transformations](https://github.com/kubernetes-sigs/kustomize/blob/785291af6269959f8acbafc44e7dea4f97d8f9da/pkg/transformers/labelsandannotationsconfig.go#L85) is all that's needed. I can submit a PR if it's confirmed this is an issue.
