### ISSUE TITLE
Add support for non-string variables

### ISSUE THREAD

**Issue by ian-howell** [kubernetes-sigs/kustomize#1184]
Kustomize currently only supports string variables. It would be nice to be able to reference other types of variables, such as ints and bools. For example, I can't currently synchronize the number of replicas I have between two deployments since `replicas` is an int.

Here's some example files to demonstrate:

```
.
├── bar.yaml
├── foo.yaml
├── kustomization.yaml
└── transformerconfig.yaml
```

**kustomization.yaml:**
```
resources:
- foo.yaml
- bar.yaml

configurations:
- transformerconfig.yaml

vars:
  - name: REPLICAS
    objref:
      kind: Deployment
      name: foo
      apiVersion: apps/v1beta2
    fieldref:
      fieldpath: spec.replicas
```

**transformerconfig.yaml:**
```
varReference:
- kind: Deployment
  path: spec/replicas
```

**foo/deployment.yaml:**
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: alpine
        name: foo
```

**bar/deployment.yaml:**
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  replicas: $(REPLICAS)
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - image: alpine
        name: bar
```

I would expect `kustomize build .` to create the bar Deployment with the same number of replicas as the foo Deployment, i.e. 5.
