### ISSUE TITLE
globbing/wildcards in "resources" field

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/kustomize#119]
It looks like if I have tens of YAML files in a directory, my kustomization.yaml will exhaustively list them like this:

```yaml
resources:
- secret.yaml
- service.yaml
- deployment.yaml
```

It feels like a bit inconvenience. Is it possible to use globs (i.e. `**.yaml`) for this field? (Skaffold does support this and it's helpful.)

I think if I use kustomize and add new YAML files, aside from `kubectl apply -R -f .dir` working out of the box, I now have to go back and edit kustomization.yaml for it to work (in other words: two places to update).

**Comment by tkellen** [comment]
As a recent first time user I was reaching for this immediately as well.

**Comment by mxey** [comment]
This is a duplicate of #107

**Comment by ahmetb** [comment]
I can closr in favor of #107 although this has a bit more rationale/explanation.

**Comment by Liujingfang1** [comment]
Let's keep this one.

**Comment by Liujingfang1** [comment]
kustomize uses a `Loader` interface to load the resource content. The loader interface can support both file system loader and remote link loader(#32)
Current interface doesn't support wildcards. We can add it for only file system loader.
Here is a possible approach, in `Load` function at https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/loader/fileloader.go#L75,
determine if the path has wildcards. If it has, read all the matching files and append the content to the same byte slice with `---` separator.

**Comment by Place1** [comment]
this was randomly removed in #217 what's up with that.

**Comment by Liujingfang1** [comment]
@Place1 We recommend users to use `kustomize edit add resource` command to add files from a directory, globbing is supported in this command. Then all the files matching a glob will be added to kustomization.yaml file.

**Comment by aiman-alsari** [comment]
@Liujingfang1 I don't think that's a great solution, if we have a hierarchy of kustomization.yamls that would mean we have to traverse up each kustomization.yamls "base" and `kustomize edit add resource` on those as well.

**Comment by tammersaleh** [comment]
I agree with @aiman-alsari - I don't think this matches real-world usage.  Any chance we could reconsider the removal of resource globbing support?

**Comment by jshearer** [comment]
This seems like a fundamental flaw. While I understand the spirit of the decision, the reality is that it unnecessarily complicates writing kustomize files becuase not only do I have to learn a new file syntax, I also have to learn a new CLI just to include new files/folders?

The concept of tool fatigue is real -- the k8s operation space is already crowded as it is, don't make people learn _extra_ tools unless there's a really good reason, and this does not seem like one...

**Comment by tkellen** [comment]
> This seems like a fundamental flaw. While I understand the spirit of the decision, the reality is that it unnecessarily complicates writing kustomize files becuase not only do I have to learn a new file syntax, I also have to learn a new CLI just to include new files/folders?

This is not a fundamental flaw. It's a design choice consistent with the ideology of the tool. The reasoning is thoroughly documented in the repo.

I wanted this when I started using kustomize too. But, after a year of daily use I've come to the conclusion this isn't a real problem. If one can't stand the practically effortless task of typing a few filenames, chances are strong one is the kind of person who can easily find a way around it (e.g. find or write a command that does it).

Finally, there is real value in having no chance of unintended side effects (e.g. someone dropping a file in a folder without knowing it will impact a kustomization file somewhere that has a globbing pattern in it).

**Comment by jshearer** [comment]
> Finally, there is real value in having no chance of unintended side effects (e.g. someone dropping a file in a folder without knowing it will impact a kustomization file somewhere that has a globbing pattern in it).

I guess I don't really see this as an issue, since I only ever run `kustomize build` in CI as part of an automated build process based on a git repo, so I already have to explicitly decide that I want every file in the repo, and while I can understand that some users might not use this repeatable workflow, it seems kind of sad that people in my situation should have to do extra work to work around it.

I guess it just feels smelly similar to a database with duplicate data in it feels smelly: if I have files in folders committed to git, it feels clunky to manually push a button to make kustomize pick up these files.

**Comment by vanufryiuk** [comment]
> This is not a fundamental flaw. It's a design choice consistent with the ideology of the tool. The reasoning is thoroughly documented in the repo.
> 
> I wanted this when I started using kustomize too. But, after a year of daily use I've come to the conclusion this isn't a real problem. If one can't stand the practically effortless task of typing a few filenames, chances are strong one is the kind of person who can easily find a way around it (e.g. find or write a command that does it).
> 
> Finally, there is real value in having no chance of unintended side effects (e.g. someone dropping a file in a folder without knowing it will impact a kustomization file somewhere that has a globbing pattern in it).

In practice, lack of globs support doesn't help to avoid unintended side effects. It forbids having **intended** side effects, and more -  creates one more place to mistake. I really don't want do add each of my 64 system level manifests to kustomization.yaml. Also, I really do want to deploy all of my 20+ microservices automatically, just by adding/removing one more build artifact to the release definition, instead of cloning the repo and typing 4 more manifest paths in the kustomization.yaml.

**Comment by bzon** [comment]
This is so sad. I ended up building a refresh script...

```bash
#!/bin/bash -e
# refresh.sh
# Create a kustomization.yaml and then add all kubernetes YAMLs into resources...
echo -n "
# built by ./refresh.sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
" > kustomization.yaml

yamls=$(find . -type f -name "*.yaml" | grep -v kustomization.yaml)

for y in ${yamls[@]}; do
  kustomize edit add resource $y
done
```

**Comment by aodj** [comment]
To add my use case, I ended up here, and don't have `kustomize` installed since it's invocation is now part of `kubectl`.

I'm already working around Helm/Tiller to render out Helm charts locally, so having yet another required tool simply to handle globbing is frustrating.

**Comment by tprobinson** [comment]
Would it be possible to get this feature re-added as an extra key? It would satisfy everyone to keep the current behavior of `bases`, `patches`, and `resources` and add additional keys like `baseGlobs`, `resourceGlobs`, and `patchGlobs` that do allow wildcards.

To be clear, I don't *like* this solution, if it were me I'd rather just allow globs in the keys themselves and I personally agree with everything that's been said in this thread so far that's in support of reinstating globs.

But I recognize that people and organizations have their reasons for changing things, and generally don't go back on that for a variety of reasons. A compromise like this would allow users who really want the glob feature to "opt in" to using it, while keeping the arguments of avoiding unintended side effects for the users who don't.

As an alternate compromise, there could be a top-layer key like `allowGlobs: true`, or a CLI flag like `--allow-globs`.

**Comment by gregorybrzeski** [comment]
@tprobinson I support your idea of higher layer switch/flag which would enable globing, it would satisfy all parties in this discussion without being a breaking change. The naming of this flag is important as well as it should allow for control of globing for other keys in future. More granular control than allow/deny on all chosen keys.  

I believe adding additional keys like `baseGlobs` adds additional clutter which should be avoided.

**Comment by codecyclist** [comment]
+1 for simply re-introducing globbing or providing a switch to turn it back on.

**Comment by JoeSainsburys** [comment]
+1 for me as well

**Comment by codecyclist** [comment]
I would be happy to submit a PR for that if one of the maintainers would be so kind to express acceptance towards that approach.

**Comment by so-jelly** [comment]
i was unaware of the `kustomize edit` subcommand, nice:

for an operator with multiple apis
`kustomize edit add resource crds/*crd.yaml`

no helper script needed @bzon

**Comment by yellowmegaman** [comment]
I just don't get how this tool ended up part of kubectl

**Comment by mr-bjerre** [comment]
I was hoping to be able to do something like this

```
resources:
- ../base/**/development
```
instead of 

```
resources:
- ../base/some-app/development
```

There is no way to do that, right?

**Comment by towens** [comment]
On an overlay:
`thing/overlays/dev/kustomization.yaml` 

That looks like:
```
---
bases:
  - ../../base
namespace: argocd
resources:
  - applications/httpbin.yaml
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - url=https://argocd.thing.com

```
When running:
`kustomize edit add resource applications/*.yaml`

Turns into:
```
namespace: argocd
resources:
- applications/httpbin.yaml
- ../../base
configMapGenerator:
- behavior: merge
  literals:
  - url=https://argocd.thing.com
  name: argocd-cm
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

```

The bases key is removed and the value is merged with resources. Something I am missing?

**Comment by Shell32-Natsu** [comment]
@towens `bases` is replaced by `resources` in newer version of kustomize.

**Comment by towens** [comment]
@Shell32-Natsu understood, thanks. The local kustomize version is ahead of what kubectl has. `kubectl -k` is pretty nice. Redirecting kustomize build isn't a deal breaker.

**Comment by simplenotezy** [comment]
> This is fixed. You can put all the resource files into a resource folder. Then in `kustomization.yaml`, use
> 
> ```
> resources:
> - resource/*.yaml
> ```
> 
> This also works for `patches`

When I am using this, in a folder called "k8s" I get error:
```
Error: accumulating resources: accumulating resources from 'k8s/*.yaml': evalsymlink failure on '/home/runner/work/project-k8s/project-k8s/k8s/*.yaml' : lstat /home/runner/work/project-k8s/project-k8s/k8s/*.yaml: no such file or directory
error: no objects passed to apply
Error: Process completed with exit code 1.
```

Config:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/*.yaml
```

**Comment by seh** [comment]
Note this comment: https://github.com/kubernetes-sigs/kustomize/issues/119#issuecomment-412709201. This globbing feature was there briefly, but now it's gone again.

**Comment by fjmacagno** [comment]
> > This is fixed. You can put all the resource files into a resource folder. Then in `kustomization.yaml`, use
> > ```
> > resources:
> > - resource/*.yaml
> > ```
> > 
> > 
> > This also works for `patches`
> 
> When I am using this, in a folder called "k8s" I get error:
> 
> ```
> Error: accumulating resources: accumulating resources from 'k8s/*.yaml': evalsymlink failure on '/home/runner/work/project-k8s/project-k8s/k8s/*.yaml' : lstat /home/runner/work/project-k8s/project-k8s/k8s/*.yaml: no such file or directory
> error: no objects passed to apply
> Error: Process completed with exit code 1.
> ```
> 
> Config:
> 
> ```
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> resources:
> - k8s/*.yaml
> ```

You should read through the thread, this was removed shortly after it was added.

**Comment by arash-bizcover** [comment]
What the hell is wrong with Kustomize maintainers. Lacking this basic feature is ridiculous, Open this issue up.

**Comment by arash-bizcover** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/3205

**Comment by xdoncalvox** [comment]
Was this feature ever added back?
Will be?

**Comment by migueleliasweb** [comment]
Still not present in 2023.

```
$ kustomize version
v5.0.0
```

Can we bring this back? It's a nightmare when you have multiple overlays and you're adding more patches or resources...

Pretty please 🙏

**Comment by thiDucTran** [comment]
> This is so sad. I ended up building a refresh script...
> 
> ```shell
> #!/bin/bash -e
> # refresh.sh
> # Create a kustomization.yaml and then add all kubernetes YAMLs into resources...
> echo -n "
> # built by ./refresh.sh
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> 
> resources:
> " > kustomization.yaml
> 
> yamls=$(find . -type f -name "*.yaml" | grep -v kustomization.yaml)
> 
> for y in ${yamls[@]}; do
>   kustomize edit add resource $y
> done
> ```

thanks for this. we changed it a bit since we have existing patches in our base's `kustomization.yaml` file
```bash
#!/bin/bash
# Inspired by author of https://github.com/kubernetes-sigs/kustomize/issues/119#issuecomment-526234246
echo -n "
resources:
" >> kustomization.yaml

yamls=$(find . -type f -name "*.yaml" | sort -bf | grep -v kustomization.yaml)

for yaml_file in ${yamls[@]}; do
  kustomize edit add resource $yaml_file
done
```

our base's `kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: grafana-datasources
  files:
    - datasources.yaml=grafana-datasources/grafana-dashboardDatasources.txt
  type: "Opaque"
  namespace: monitoring
  behavior: replace
configMapGenerator:
# https://grafana.com/grafana/dashboards/15757-kubernetes-views-global/
- name: grafana-dashboard-kuberenetes-views-global
  files:
    - kuberenetes-views-global.json=grafana-dashboards/kuberenetes-views-global.json
  namespace: monitoring
# https://grafana.com/grafana/dashboards/9614-nginx-ingress-controller/
- name: grafana-dashboard-nginx-ingress-controller
  files:
    - nginx-ingress-controller.json=grafana-dashboards/nginx-ingress-controller.json
  namespace: monitoring  
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      namespace: monitoring
    patch: |-
      kind: not-important
      metadata:
        name: not-important    
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.azure.com/mode
                      operator: In
                      values:
                      - user
  - target:
      version: v1
      group: apps
      kind: Deployment
      namespace: monitoring
      name: grafana
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GF_PATHS_CONFIG
          value: /etc/grafana/grafana.ini
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /etc/grafana/certs
          name: omaticcloud-io-wildcard-tls
          readOnly: false
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: omaticcloud-io-wildcard-tls
          secret:
            secretName: omaticcloud-io-wildcard-tls-grafana
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /grafana-dashboard-definitions/0/kuberenetesviewsglobal
          name: grafana-dashboard-kuberenetes-views-global
          readOnly: false
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: grafana-dashboard-kuberenetes-views-global
          configMap:
            name: grafana-dashboard-kuberenetes-views-global
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /grafana-dashboard-definitions/0/nginxingresscontroller
          name: grafana-dashboard-nginx-ingress-controller
          readOnly: false
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: grafana-dashboard-nginx-ingress-controller
          configMap:
            name: grafana-dashboard-nginx-ingress-controller             
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: prometheus-k8s
    patch: |-
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: prometheus-k8s
      rules:
      - apiGroups:
        - '*'
        resources:
        - '*'
        verbs:
        - '*'
      - nonResourceURLs:
        - '*'
        verbs:
        - '*'
```
