### ISSUE TITLE
Improve variable expansion to include tree structures

### ISSUE THREAD

**Issue by ian-howell** [kubernetes-sigs/kustomize#1190]
I would like to be able to use a variable to reference an entire tree of YAML as opposed to a single piece of primitive data. Consider the following example, where kustomize should take the entire `template` tree from the foo deployment and use it in the bar deployment.

```
.
├── bar
│   ├── deployment.yaml
│   └── kustomization.yaml
├── foo
│   ├── deployment.yaml
│   └── kustomization.yaml
├── kustomization.yaml
└── transformer.yaml
```

**kustomization.yaml:**
```
bases:
  - foo
  - bar
namePrefix: inlining-example-
vars:
  - name: CUSTOM_TEMPLATE
    objref:
      kind: Deployment
      name: foo
      apiVersion: apps/v1beta2
    fieldref:
      fieldpath: spec.template
configurations:
  - transformer.yaml
```

**transformer.yaml:**
```
varReference:
- kind: Deployment
  path: spec/template
```

**foo/deployment.yaml:**
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - image: alpine
        name: foo
```

**bar/deployment.yaml:**
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  selector:
    matchLabels:
      app: bar
  template: $(CUSTOM_TEMPLATE)
```
