### ISSUE TITLE
Adding the configmap/secret hash into the annotation of itself

### ISSUE THREAD

**Issue by solacens** [kubernetes-sigs/kustomize#1215]
Hi, I'm new to Kustomize from Helm.

I'm wondering if the CM/Secret itself can contains the hash so that I can reference it from other resources such as deployment.

Generating hash in the resource as suffix is a bit annoyed to me becuz there are already dozen of resources there and I don't really need a rollback.

P.S. From my observation, Kustomize didn't really take care of the rollback control, we should be having versioning with another tools like git, etc.

---

Sample generated manifest:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  annotations:
    hashedValue: XXXXXXXXXXXXXXXX
...
```

**Comment by arnodel** [comment]
You can do this by having a `vars` section in your kustomization:

```yaml
vars:
  - name: CONFIG_NAME
    objref:
      kind: ConfigMap
      name: config
      apiVersion: v1
```

Then in e.g. a deployment you can have:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
     spec:
      containers:
        - name: main
          env:
            - name: CONFIG_NAME
              value: $(CONFIG_NAME)
```

The same applies for secrets.
