### ISSUE TITLE
Automatic creation for kustomization.yaml var section and varReference

### ISSUE THREAD

**Issue by jbrette** [kubernetes-sigs/kustomize#1216]
Creating the entries in the var section can be a quite long process if the number of variable increases and get the kustomization.yaml hard to read:

For instance:
```
- name: SoftwareVersions.software-versions.spec.images.mysql.tag
  objref:
    apiVersion: my.group.org/v1alpha1
    kind: SoftwareVersions
    name: software-versions
  fieldref:
    fieldpath: spec.images.mysql.tag
- name: CommonAddresses.common-addresses.spec.dns.upstream_servers[2]
  objref:
    apiVersion: my.group.org/v1alpha1
    kind: CommonAddresses
    name: common-addresses
  fieldref:
    fieldpath: spec.dns.upstream_servers[2]
```

On the varReference side of the process, the process make complicated very quickly:
For K8s standard objects (if not part of the default configuration)
```
varReference:
- kind: Deployment
  path: spec/template/spec/containers/image
- kind: Deployment
  path: metadata/labels
- kind: Deployment
  path: spec/template/metadata/labels
- kind: Deployment
  path: spec/selector/matchLabels
- kind: Deployment
  path: spec/template/spec/initContainers
```
or

For CRD:
```
varReference:
- kind: Chart
  path: spec/values/endpoints/messaging/auth/user/password
- kind: Chart
  path: spec/source
- kind: Chart
  path: spec/values/images
- kind: Chart
  path: spec/values/labels
```

This proposal aims at the automatic creation of the var and varReference section by simply scanning for the resources:

If we take the following example:
```
apiVersion: my.group.org/v1alpha1
kind: Chart
metadata:
  name: wordpress
spec:
  source: $(SoftwareVersions.software-versions.spec.charts.wordpress)
  values:
    ......
    pod:
      replicas:
        api: 1
```
we can conclude that we need to create the following varReference
```
varReference:
- kind: Chart
  path: spec/source
...
```

and the following var
```
vars:
- name: SoftwareVersions.software-versions.spec.charts.wordpress
  objref:
    apiVersion: GROUP/VERSION
    kind: SoftwareVersions
    name: software-versions
  fieldref:
    fieldpath: spec.charts.wordpress
```

By adding turning on the autoconfig feature, the user would only have to create the entries for which the detection process would have failed.
