### ISSUE TITLE
support valueFrom in any location kustomize allows value

### ISSUE THREAD

**Issue by tkellen** [kubernetes-sigs/kustomize#1233]
*This is a more generalized form of the feature discussion originally held in https://github.com/kubernetes-sigs/kustomize/issues/1168.*

Would you accept a PR that made it possible for kustomize to source the content of any `value` from an external file?

Here is one possible use-case:

Assume I have a cluster produced by terraform that outputs files which each have a single line of data in them to record commonly needed values for workloads in the cluster:
```
.
├── cluster-config           
    └── environment
        ├── elb_hostname    
        ├── hostname       
        └── rds_ci_hostname  
```

Currently the only way I know how to bring those values into the cluster using kustomize without manually hard-coding them (or dynamically generating an entire `kustomization.yml` using literals) is like this:
```
configMapGenerator:
  - name: environment
    files:
      - cluster-config/environment/hostname
      - cluster-config/environment/rds_ci_hostname
      - cluster-config/environment/elb_hostname
```

...which means, for example, in a pod spec, I consume them like this:
```
          env:
            - name: CONCOURSE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: rds_ci_hostname
```

I would prefer to assign these common values in my resources directly using a json patch operation:
```
- op: add
  path: /spec/template/spec/containers/0/env/0
  value:
    name: CONCOURSE_POSTGRES_HOST
    valueFrom:
      fileRef:
        path: cluster-config/environment/rds_ci_hostname
```

This would eliminate the configmap indirection and allow more fine grained control of what values are passed around. It would also make it possible to configure resources like ingress which don't support getting values from configmaps.

Last thought... is there some way to do this already with `vars` that I don't understand?

**Comment by tkellen** [comment]
If you're reading this via email @monopole, just a heads up that I edited this numerous times as the idea evolved. Thanks in advance for any time you can give this!

**Comment by Liujingfang1** [comment]
@tkellen, there is no `fileRef` in `env.ValueFrom` based on Kubernetes [APIs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#envvarsource-v1-core).
You can change your pod and configmap a little. It may simplify your process.
```
configMapGenerator:
  - name: environment
    files:
      - CONCOURSE_POSTGRES_HOST=cluster-config/environment/hostname
      - CONCOURSE_POSTGRES_CI_HOST=cluster-config/environment/rds_ci_hostname
      - CONCOURSE_POSTGRES_ELB_HOST=cluster-config/environment/elb_hostname
```
change `env` in the pod spec to
```
          envFrom:
           - configMapRef:
               name: environment
```
