### ISSUE TITLE
Kustomize generated files when using -o <folder> option should contain the namespace

### ISSUE THREAD

**Issue by jbrette** [kubernetes-sigs/kustomize#1243]
Was investigating difference of behavior between 2.0.3 and 2.1.0, and realized the kustomize build <xxx> -o <folder> needs improvement in the generation of the file names:
The filename do not contain the namespace which causes issues at build time:

Create first object in one namespace using the dply1 name:

```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dply1
  labels:
    app: dply1
  namespace: base-namespace
spec:
  selector:
    matchLabels:
      app: dply1
  template:
    metadata:
      labels:
        app: dply1
    spec:
      containers:
      - image: alpine
        name: dply1
```
Create second object in another namespace using the dply1 name:
```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dply1
  namespace: staging-namespace
spec:
  template:
    metadata:
      labels:
        hello: world
```

Check kustomize version
```bash
kustomize.2.1.0 version
Version: {KustomizeVersion:2.1.0 GitCommit:af67c893d87c5fb8200f8a3edac7fdafd61ec0bd BuildDate:2019-06-18T22:01:59Z GoOs:linux GoArch:amd64}
```

Generate one yaml file
```bash 
kustomize.2.1.0 build staging/ -o outputfile.yaml
cat outputfile.yaml
```

Result is a expected:
```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: dply1
  name: dply1
  namespace: base-namespace
spec:
  selector:
    matchLabels:
      app: dply1
  template:
    metadata:
      labels:
        app: dply1
    spec:
      containers:
      - image: alpine
        name: dply1
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dply1
  namespace: staging-namespace
spec:
  template:
    metadata:
      labels:
        hello: world
```

Now try to generate into a directory
```bash
mkdir outputdir
kustomize.2.1.0 build staging/ -o outputdir/
```

Expected to have two files or 1 file with both definitions, Only one file is generated
```
ls outputdir/
apps_v1beta2_deployment_dply1.yaml
```

The issue is that the generated file only contains one deployment
```
cat outputdir/apps_v1beta2_deployment_dply1.yaml
```

```yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dply1
  namespace: staging-namespace
spec:
  template:
    metadata:
      labels:
        hello: world
```
