### ISSUE TITLE
Add volumeMounts outside of configMapGenerator

### ISSUE THREAD

**Issue by bitva77** [kubernetes-sigs/kustomize#1245]
I'm trying to add a new volumeMount to a container (for a hostPath volume).  The deployment already contains configMaps added via configMapGenerator.  Is there anyway to patch it?

I've tried 

```
spec:
  template:
    spec:
      containers:
        name: logstash
        volumeMounts:
        - mountPath: /share
          name: dlq
        - $patch: merge
```

but that just ends up replacing everything under `spec.template.spec.containers` still.

What's the difference between replace and merge in this case?

overlaying `spec.template.spec.volumes` works to add a hostPath but can't seem to get both configMaps and the hostPath added to the volumeMounts.  It's like it's one or the other.

Thanks!

**Comment by bitva77** [comment]
let me follow up and say that trying to overlay (no $patch statement) that it sill replaces everything as above

**Comment by bitva77** [comment]
I figured out how to use the JSON patch to get the same effect.  It's confusing how we have to use different methods in kustomize to get the same effect.

For anyone who comes across this in their google support searches, here's how I "fixed" this:

I created a `patch.yaml` with the following:

```
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: dlq
    hostPath:
     type: DirectoryOrCreate
     path: /logstash

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: dlq
    mountPath: /share
```

And then added this to my `kustomization.yaml`:

```
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: logstash-deployment
  path: patch.yaml
```

That get's me this Deployment YAML:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: logstash
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: logstash
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: privateregistry/logstash/logstash:6.7.1
        imagePullPolicy: Always
        name: logstash
        resources:
          limits:
            cpu: 250m
            memory: 2048Mi
          requests:
            cpu: 250m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /usr/share/logstash/config/jvm.options
          name: config
          subPath: jvm.options
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: config
          subPath: logstash.yml
        - mountPath: /usr/share/logstash/pipeline/pipeline.conf
          name: config
          subPath: pipeline.conf
        - mountPath: /share
          name: dlq
      imagePullSecrets:
      - name: commoncr
      volumes:
      - configMap:
          name: config-dk68mb6bmf
        name: config
      - hostPath:
          path: /logstash
          type: DirectoryOrCreate
        name: dlq
```
