### ISSUE TITLE
2.1.0 broke Vars using fieldPaths whose components contain dots  - regression bug

### ISSUE THREAD

**Issue by primeroz** [kubernetes-sigs/kustomize#1249]
This is a regression bug since the issue was reported and fixed in #526 

With kustomize 2.0.3 it works as expected, in my case this snippet
```
  - name: elasticsearch-data-statefulset-instance-label
    objref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: elasticsearch-data
    fieldref:
      fieldpath: metadata.labels["app.kubernetes.io/instance"]
```

works as expected and the var value is set.

Testing 2.1.0 this is broken 

```
Error: field specified in var '{elasticsearch-data-statefulset-instance-label ~G_~V_StatefulSet {metadata.labels["app.kubernetes.io/instance"]}}' not found in corresponding resource
```

Or is somehow the syntax changed to reference dotted labels ?
