### ISSUE TITLE
JSONPatch annotations containing slashes

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#1256]
Not really a Kustomize issue but we definitely need a work around.

When patching annotations, it happens that the keys contain `/`. Like for example when patching my ingress:
```yaml
- op: add
  path: /metadata/annotations/traefik.ingress.kubernetes.io/redirect-permanent
  value: false
```

This doesn't work since it should be interpreted as
```yaml
metadata:
  annotations:
    traefik.ingress.kubernetes.io/redirect-permanent: false
```
But is actually interpreted as:
```yaml
metadata:
  annotations:
    traefik.ingress.kubernetes.io:
      redirect-permanent: false
```
