### ISSUE TITLE
add genericGenerator

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#126]
for example:

```
genericGenerator:
  resourcePath: cronjob.yaml
  fieldPathArgs:
  - path: metadata.name
    value: mycronjob
  - path: spec.schedule
    value: "* * * * *"
```

**Comment by Liujingfang1** [comment]
@sethpollack Can you add some explanation of meaning of each field? I also opened  #122 for supporting extensible transformation. It seems to have some overlap with the motivation of `genericGenerator` you proposed.

**Comment by sethpollack** [comment]
Sure! This would be a transformation where you can take a base resource `resourcePath` and modify its fields by passing  `fieldPathArgs` with the `path` to the field and the replacement `value`.

A good example would be cronjobs where I may want to create a bunch of them from the same base - just with different names, commands, and schedules.

The transformation would just loop through the provided `fieldPathArgs` rather than hardcoded PathConfigs and just call mutateField for each.

**Comment by Liujingfang1** [comment]
Is `resourcePath` a file path to a resource file in the base folder? Usually the overlays are not supposed to know the exact files or structs of the base.

**Comment by sethpollack** [comment]
yes

**Comment by Liujingfang1** [comment]
This feature looks promising to me. I am also thinking about some other use cases that it might support. Say I want to replace a container image name no matter it is in a deployment object or in a pod. How could I define the resource and field path so that it can work? 

Can you write a brief design doc about this genericGenerator(maybe some other name genericTransformer)? Let have others' opinion on it.

**Comment by sethpollack** [comment]
I think the `genericGenerator` solves a different problem than the `genericTransformer`. 

For example If I have 25 cronjob variations I would need 25 subdirectories with a kustomization and a patch file in each and then do something like your suggestion in #38 to generate them all from the same base resource: 

```
kustomizations:
- ./cronjobs/cronjob1
- ./cronjobs/cronjob2
...
```

The idea for the `genericGenerator` would be to use 25 `genericGenerator`'s in the base kustomization file instead.

```
genericGenerator:
  resourcePath: cronjob.yaml
  fieldPathArgs:
  - path: metadata.name
    value: cronjob1
  - path: spec.schedule
    value: "* * * * *"

genericGenerator:
  resourcePath: cronjob.yaml
  fieldPathArgs:
  - path: metadata.name
    value: cronjob2
  - path: spec.schedule
    value: "* * * * *"
...
```

As for the `genericTransformer` we can do something with `PathConfigs` like this:

```
genericTransformer:
  pathConfigs:
  - path: spec.template.spec.containers.name
    createIfNotPresent: true
    groupVersionKind:
      kind: Deployment
    matches: docker.io/nginx:latest
    value: docker.io/nginx:1.15.0
  - path: spec.jobTemplate.spec.template.spec.containers
    createIfNotPresent: true
    groupVersionKind:
      kind: CronJob
    matches: docker.io/nginx:latest
    value: docker.io/nginx:1.15.0    
```
