### ISSUE TITLE
kustomize doesn't add the secret name suffix to the end of `credentialName` fields on istio gateways

### ISSUE THREAD

**Issue by hach-que** [kubernetes-sigs/kustomize#1262]
For example, this secret name generator:

```
secretGenerator:
  - name: hello-tls
    files:
      - tls.crt
      - tls.key
```

and this istio gateway declared in a resource file for kustomize:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "hello-tls"
      hosts:
        - "hello.com"
```

kustomize doesn't append the name hash suffix to the `credentialName` field.

I also tried:

```
secretGenerator:
  - name: hello-tls
    files:
      - tls.crt
      - tls.key
vars:
  - name: HELLO_TLS_SECRET_NAME
    objref:
      kind: Secret
      name: hello-tls
      apiVersion: v1
```

and

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: $(HELLO_TLS_SECRET_NAME)
      hosts:
        - "hello.com"
```

but that didn't work either.

It would be really nice if there was a way of getting generated secret names and being able to put them into fields. `vars` seems like it's designed for this, but for some reason it doesn't work.
