### ISSUE TITLE
Match of like name, different namespace, collides sometimes

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#1264]
See the attached file.
[1264.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/3332517/1264.tar.gz)

I have two objects with the same type/name, different namespace.
Here it is v1/ServiceAccount, name: prometheus.

1 is in namespace `prometheus` (as set by the kustomization.yaml file)
1 is in the namespace `istio-system` (as set in the object itself).

Here's where it gets weird:
```
kustomize build .
Error: string case - multiple matches for ~G_v1_ServiceAccount|istio-system|prometheus:
  [~G_v1_ServiceAccount|istio-system|prometheus
 ~G_v1_ServiceAccount|prometheus|prometheus
]
```

shows the problem. But, I remove an *unrelated* object (a ClusterRoleBinding), the error vanishes.

This implies to me that the order (in hashmap) matters.

to repro, unpack attached, run `kustomize build ca-1-dev`. There is only 1 object in each of the dirs, its really not a lot of YAML.

**Comment by donbowman** [comment]
is this related to https://github.com/kubernetes-sigs/kustomize/issues/1044 ?

**Comment by jbrette** [comment]
@donbowman Seems that pull request [1266](https://github.com/kubernetes-sigs/kustomize/pull/1266) addresses the issue.

Saved the configuration files used to reproduce [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1264)

```bash
kustomize build ca-1-dev/
```

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus
    cluster: ca-1-dev
    heritage: Tiller
    release: istio
  name: prometheus
  namespace: istio-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    cluster: ca-1-dev
  name: prometheus
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    cluster: ca-1-dev
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: prometheus

```

**Comment by alexeldeib** [comment]
I think I'm also seeing this behavior. Identical objects with different name prefix and namespace prefix generate a collision. This is how kubebuilder scaffolds the controller-manager output. It's also useful because you can define the deployment/statefulset once for the controller, and configure multiple managers for different repos using overlays on a common base. 

```
Error: Multiple matches for name ~G_v1_ServiceAccount|operator-system|operator-|manager-account|~S:
  [~G_v1_ServiceAccount|cloud-system|cloud-|manager-account|~S ~G_v1_ServiceAccount|operator-system|operator-|manager-account|~S]
```

**Comment by jbrette** [comment]
@donbowman Looks like 3.0.3 is fixing your bug. Can you confirm and close it.

```bash
$HOME/bin/kustomize.3.0.2 build ca-1-dev
```
``yaml
Error: string case - multiple matches for ~G_v1_ServiceAccount|istio-system|prometheus:
  [~G_v1_ServiceAccount|istio-system|prometheus
 ~G_v1_ServiceAccount|prometheus|prometheus
]

```bash
$HOME/bin/kustomize.3.0.3 build ca-1-dev
```

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus
    cluster: ca-1-dev
    heritage: Tiller
    release: istio
  name: prometheus
  namespace: istio-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    cluster: ca-1-dev
  name: prometheus
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    cluster: ca-1-dev
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: prometheus
```
