### ISSUE TITLE
CRD support for variables + images - broken

### ISSUE THREAD

**Issue by rosscdh** [kubernetes-sigs/kustomize#1268]
I setup "variables"
When using `kind: Deployment`
the variables are substituted

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  strategy:
    blueGreen:
      activeService: helloworld-svc-active
      autoPromotionEnabled: false
      previewService: helloworld-svc-preview
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - env:
        - name: DEPLOY_VERSION
          value: orange
        image: someplage/hellopy
        imagePullPolicy: Always
```

When using a CRD `kind: Rollout`
the variables are not substituted

```
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  strategy:
    blueGreen:
      activeService: helloworld-svc-active
      autoPromotionEnabled: false
      previewService: helloworld-svc-preview
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - env:
        - name: DEPLOY_VERSION
          value: $(DEPLOYMENT_COLOUR)
```

Expectation, variables get substituted regardless of `kind`

**Comment by jbrette** [comment]
@rosscdh I do believe that you are missing a varReference configuration:

```yaml
varReference:
- path: spec/template/spec/containers[]/env[]/value
  kind: Rollout
```

Have a look at the files used to reproduce the issue [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1268). The output folder is [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1268/expected)

An example for a CRD is [in doc](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md#adding-a-custom-resource)

The reason is works out of the box for deployment is [here](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/varreference.go#L76)


The output with such a field is:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  strategy:
    blueGreen:
      activeService: helloworld-svc-active
      autoPromotionEnabled: false
      previewService: helloworld-svc-preview
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - env:
        - name: DEPLOY_VERSION
          value: orange
```

Also we are trying to get feedback on the usability of another PR: [Automatic Creation of 'vars:' and 'varReferences:' sections](https://github.com/kubernetes-sigs/kustomize/pull/1217)

Have a look at the **strategy** field in the rollout input and rendered files. See variable **$(Values.file1.spec.blueGreen)** is automatically replaced without the need for vars: nor varReferences:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  strategy:
    blueGreen: $(Values.file1.spec.blueGreen)
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - env:
        - name: DEPLOY_VERSION
          value: $(DEPLOYMENT_COLOR)
```
