### ISSUE TITLE
Pull secret names don't appear to be templated correctly with the target secret name

### ISSUE THREAD

**Issue by bickfordb** [kubernetes-sigs/kustomize#128]
1. Create a Deployment with an `imagePullSecret` like `foo`:

```yaml
kind: Deployment
... 
  imagePullSecrets:
    - name: foo
```

2. Create an imagePullSecret in your kustomization.yaml named `foo`:

```yaml
secretGenerator:
  - name: docker
    commands:
      .dockerconfigjson: "echo -n secret"
    type: "kubernetes.io/dockerconfigjson"
```
Expected behavior:

`kustomize build` outputs a Deployment manifest like 

```yaml
kind: Deployment
...
   imagePullSecrets:
     - name: ${namePrefix}-foo-${hash(foo)}
...
```
Instead of like:

```yaml
kind: Deployment
... 
  imagePullSecrets:
    - name: foo
```
