### ISSUE TITLE
Support a high-level merge behavior in kustomize

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#1292]
The `resources:` field in a kustomization file specifies a list of files and / or other kustomizations to be processed in a `kustomize build`.

These artifacts are read or built, resulting in _a list of resources_, which are supposed to be _added_ to the set of resources kustomize is processing.

If an incoming resource matches the Id (where Id is a tuple of namespace, group, version, kind, name) of an Id already known to kustomize, the build fails with an error.  This invariant maintains the Id is a primary key used for all sorts of purposes.

We could however, allow a _merge_ on Id collision instead of an error (at this stage of the build process).  Or we could make _merge_ the default behavior, and have some mode that enables errors on Id collisions.

Some uses cases prefer an error, some prefer a merge.

There are low level cases where this is already allowed, e.g. Secret and ConfigMap generators have an option that allows merging or replacing on Id collision, rather than failing.

**Comment by monopole** [comment]
take into account
- build wide resolution, (e.g. a flag to `build`), per kustomization resolution, or even per Kind resolution (as we already do with ConfigMap and Secret being different from other Kinds) - i.e. always merge Deployments, but never merge/replace Namespace.
- leave `resources` alone, and make a new field that does merging?
- reuse https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/generationbehavior.go generally, or deprecate in favor of something else?

**Comment by monopole** [comment]
[generationbehavior](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/generationbehavior.go) defines three behaviors for generators

- create: make a new thing, and throw an error if it already exists.
- replace: make a new thing, expect to replace an existing thing, and error if the existing thing isn't there
- merge: make a new thing, and expect to merge it with an existing thing, and error if the existing thing isn't there.

That logic is in ResMap.AbsorbAll, but is not invoked when reading the `resources` field.

So how about a new field that offer all flexibility:

```
sources: []Source
type Source {
  behavior: create, replace or merge or ...
  resources: []string
}
```

e.g.

```
sources:
- behavior: merge
  resources:
  - a/path/to/file
  - a/kustomization
- behavior: create
  resources:
  - b/path/to/file
  - b/kustomization
- behavior: replace
  resources:
  - c/path/to/file
  - c/kustomization
```

The existing `resources` field, kept for backward compatibility, is thus shorthand for 
```
sources:
- behavior: create
  resources:
  - some/path/to/file
  - some/kustomization
```

This way future behaviors can be identified, e.g. `override` which is like createOrReplace (no error)

**Comment by apyrgio** [comment]
Allowing the user to specify a conflict resolution strategy for resources is a nice addition. To get the discussion started, we have the following comments:

1. Why not keep the resources as is, e.g.:

```
resources:
- a/path/to/file
- a/kustomization
- b/path/to/file
- b/kustomization
- c/path/to/file
- c/kustomization
```

and also allow this format:

```
resources:
- source: a/path/to/file
  behavior: merge
- source: a/kustomization 
  behavior: merge
- source: b/path/to/file
  behavior: create
- b/kustomization  # This format is also allowed,
                   # with "create" as the default behaviour
- source: c/path/to/file
  behavior: replace
- source: c/kustomization
  behavior: replace
```

The default behavior is currently `create`, so users will rarely need to write the full format. Also, this format allows us to add more fine-grained control for resources in the future, and the user does not need to group resources per behavior.

2. The merging strategy in generators is simple to reason out, since they deal with created resources. In the case of patching the same resource from different overlays, how do you plan to implement merging? From what I gather, merging the produced YAMLs can overwrite changed fields (see @jbrette's solution), and recreating the patches is very tricky.
