### ISSUE TITLE
configMap/secretGenerator named hashes are not applied to resource that include them

### ISSUE THREAD

**Issue by ptemmer** [kubernetes-sigs/kustomize#1301]
kustomize version: v3.0.0-pre1 and current master branch

When a namespace is specified in the base kustomization.yaml, but none in the overlay kustomization.yaml, the ouput yielded does not modify the resources referencing a configmapGenerator  with it's proper name-hash.

How to reproduce:

* Note that the deployment resource is included in the base, while the configMapGenerator is included in the overlay.

base/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- test-deployment.yaml
```
overlay/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

configMapGenerator:
- name: cafe-configmap
  literals:
  - FOO=BAR
```

When building this overlay, the configMapRef in test-deployment.yaml is left as "cafe-configmap", without any hashed suffix.

```
kind: ConfigMap
metadata:
  name: cafe-configmap-66d9hf4ghg
---

deployment.yaml
...surpressed output..
      volumes:
      - configMap:
          name: cafe-configmap
```
If however, you either remove the namespace definition in the base, or add an arbitrary namespace in the overlay (they don't need to match), the referencing resources contain the proper name hashed value for the configmap

```
kind: ConfigMap
metadata:
  name: cafe-configmap-66d9hf4ghg
---

deployment.yaml
...surpressed output..
      volumes:
      - configMap:
          name: cafe-configmap-66d9hf4ghg
```

**Comment by linjmeyer** [comment]
I'm seeing the same thing with a project that doesn't use overlays.  Without setting `namespace` and `nameprefix` my ConfigMaps are not updated in deployment.  After setting both it works as expected.

**Comment by ptemmer** [comment]
Today's released v3.0.0 also fails

**Comment by ptemmer** [comment]
Does not happen with v2.1.0 though..

**Comment by ptemmer** [comment]
I cannot reproduce the issue you describe @linjmeyer

**Comment by lwille** [comment]
I'm observing the same issue in 3.0.0, but only when the base itself uses `nameSuffix` or `namePrefix`:

```
# base/kustomization.yml
---
nameSuffix: -suffix
configMapGenerator:
- name: bar
  files: [file2]
```

```
# overlay/kustomization.yml
---
resources:
- ../base
- podspec.yml
```

```
# overlay/podspec.yml
kind: Pod
metadata:
  name: pod
spec:
  volumes:
    - name: config-bar
      configMap:
        name: bar
```

expected output:

```
apiVersion: v1
data:
  file2: ""
kind: ConfigMap
metadata:
  name: bar-suffix-8hb7b57g9t
---
kind: Pod
metadata:
  name: pod
spec:
  volumes:
  - configMap:
      name: bar-suffix-8hb7b57g9t
    name: bar
```

actual output:

```
apiVersion: v1
data:
  file2: ""
kind: ConfigMap
metadata:
  name: bar-suffix-8hb7b57g9t
---
kind: Pod
metadata:
  name: pod
spec:
  volumes:
  - configMap:
      name: bar
    name: bar
```

**Comment by sethpollack** [comment]
I'm seeing this as well, resources in a kustomization.yaml that have a `namePrefix` get ignored.

**Comment by jbrette** [comment]
@ptemmer  Seems to be fixed by this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1326).

Can you confirm that [the following tests](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1301) is valid and close the bug.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: component2
  name: test-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component2
  template:
    metadata:
      labels:
        app: component2
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - cat /etc/config/component2 && sleep 60
        image: k8s.gcr.io/busybox
        name: component2
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          name: cafe-configmap-bm6m88fk92
        name: config-volume
```

**Comment by hidekuro** [comment]
it's affects only pure k8s resources?
At least it didn't work with a CRD like the Argo-events Sensor.

**Comment by Liujingfang1** [comment]
@hidekuro You need to add configurations in kustomization.yaml so that it knows which field to update. Take a look at this [example](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd)

**Comment by hidekuro** [comment]
@Liujingfang1 thx a lot!

**Comment by 0gajun** [comment]
@jbrette I think it seems not to be fixed 👀 

[The tests](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1301) you provided works fine. However, with non-default namespace, it doesn't work.

I changed `base/kustomization.yaml` in the example like the following.

```diff
diff --git a/examples/issues/issue_1301/base/kustomization.yaml b/examples/issues/issue_1301/base/kustomization.yaml
index 9287a9ff..46a7624f 100644
--- a/examples/issues/issue_1301/base/kustomization.yaml
+++ b/examples/issues/issue_1301/base/kustomization.yaml
@@ -1,7 +1,7 @@
 apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization

-namespace: default
+namespace: non-default

 resources:
 - test-deployment.yaml
```

Then, `kustomize build overlay` outputs are like below.

```yaml
apiVersion: v1
data:
  FOO: BAR
kind: ConfigMap
metadata:
  name: cafe-configmap-bm6m88fk92
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: component2
  name: test-deployment
  namespace: non-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component2
  template:
    metadata:
      labels:
        app: component2
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - cat /etc/config/component2 && sleep 60
        image: k8s.gcr.io/busybox
        name: component2
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          name: cafe-configmap
        name: config-volume
```

In this case, configMap.name in Deployment doesn't have a hash suffix.

To resolve this issue, we have to also set `namespace: non-default` in `overlay/kustomization.yaml`.

Is this expected behavior?

**Comment by jbrette** [comment]
What is expected is that two config-map with the same name can exist in kubernetes as long as they are in different namespaces.
In your case you are indicating:
1) generate a config-map in the default namespace, 
2) get a deployment in non-default namespace to point a to config-map in the non-default namespace. Since non-default-ns/cafe-configmap does not exist, kustomize will not touch it.
==> So it is expected.

To solve it, you are not forced to put everything in the overlay into a new namespace. You can if you want just put the config-map in the non-default-ns, by adding namespace: xxx just bellow the name: in the config map generator.

**Comment by 0gajun** [comment]
Thanks for your really kind explanation! 
I got it!

**Comment by steinybot** [comment]
An alternative workaround is to specify the configMapGenerator in the `base/kustomization.yaml` and then use `behaviour: replace` in the overlay.

**Comment by wvidana** [comment]
What we ware seeing is that `volume` doesn't work with `kubectl kustomize`but it does with the standalone `kustomize`.

For example, this code snipplet

```yaml
      volumes:
      - configMap:
          name: cafe-configmap
        name: config-volume
```

Should generate
```yaml
      volumes:
      - configMap:
          name: cafe-configmap-XXXXXX
        name: config-volume
```

But the SHA suffix only gets generated with `kustomize build` but not with `kubectl kustomize`

**Comment by ppihus** [comment]
> But the SHA suffix only gets generated with `kustomize build` but not with `kubectl kustomize`

The standalone `kustomize` and `kubectl kustomize` are different versions of Kustomize. The one bundled with `kubectl` is quite old.

Since [v1.14][kubectl announcement] the kustomize build system has been included in kubectl.

| kubectl version | kustomize version |
|---------|--------|
| v1.16.0 | v2.0.3 |
| v1.15.x | v2.0.3 |
| v1.14.x | v2.0.3 |

but the [latest](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize/v3.5.4) `kustomize` release is v3.5.4.

**Comment by povilasv** [comment]
I have the same behaviour, with regular `kustomize`.

Version:
```
{Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
```

I also tried to use compiled version from master branch, didn't help.

This is how to reproduce:

```
helm repo add loki https://grafana.github.io/loki/charts
helm repo update

helm template loki --namespace=sys-mon loki/loki-stack > loki.yaml
```

Create `loki-conf.yaml`, with contents `auth_enabled: false`.

Create a `kustomization.yaml`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sys-mon
secretGenerator:
- files:
  - loki.yaml=loki-conf.yaml
  name: loki
  behavior: replace
  namespace: sys-mon
```

This what gets generated:
```
apiVersion: v1
data:
  loki.yaml: YXV0aF9lbmFibGVkOiBmYWxzZQo=
kind: Secret
metadata:
  annotations: {}
  labels:
    app: loki
    chart: loki-0.28.0
    heritage: Helm
    release: loki
  name: loki
  namespace: sys-mon
type: Opaque
```

And this is the reference in Statefulset:

```
      volumes:
      - name: config
        secret:
          secretName: loki
```

Both of these don't have a hash.

**Comment by jdevalk2** [comment]
@povilasv I can confirm this is definitely still broken as I ran into the same issue

I am setting it to replace mode on secret generator. Merge, same effect.
I also tried adding an extra need-hash annotation on the secret, no effect

The strange thing is it does seem to respect the name suffix if you specify one.  All the secret names update.  However the hash is never added.  Since the name replacement works, I assume once the hash would be added the hashed name would update everywhere as well.

```
  annotations:
    kustomize.config.k8s.io/needs-hash: 'true'
```
Also in one place it says "This annotation is for internal use only it will not show in the output"  But in my case - Secret generator - this does not seem to be true:  it WILL happily show in the output.  Maybe its just not processed?

Also weird:  If I set the mode to "Create" and delete the secret from the source, then a new secret is created, which WILL have the hash set.  So it works in "Create" mode but not in "Merge", "Replace"

**Comment by olegburov** [comment]
> To solve it, you are not forced to put everything in the overlay into a new namespace. You can if you want just put the config-map in the non-default-ns, by adding namespace: xxx just bellow the name: in the config map generator.

Adding `namespace: xyz` into `kustomization.yaml` helps, but only when using `kustomize build ./overlay`. Doesn't work when using `kubectl kustomize ./overlay`.

**Comment by omninonsense** [comment]
For people discovering this bug recently, here is a summary:

 - This is still an issue as of Kustomize 3.8+
 - With `kustomize build` (but not `kubectl kustomize`) you can add a `namespace: foo` into the _overlay_ kustomization as a workaround.
   - This workaround _does not_ work when `namespace: foo` is in a base _base_ kustomization.

**Comment by jketcham** [comment]
I just ran into this as well after changing my project's kustomize config layout. I am now including a component (not a base) that sets a `namespace` and `namePrefix` in an overlay that sets a `configMapGenerator`. I tested with 3.8.6 and the latest 4.0.5 and I get the behavior described by others above.

The workaround for adding a redundant namespace definition to the overlay works for getting the hash added to the generated ConfigMap name, but the namePrefix is still left off. Thankfully for my purposes I can live with that, but it's still a bug.

A fix for this would be greatly appreciated!

**Comment by varshithreddy21** [comment]
[https://github.com/kubernetes-sigs/kustomize/blob/master/examples/generatorOptions.md]
we can disable the hash using this

**Comment by guAnsunyata** [comment]
> What is expected is that two config-map with the same name can exist in kubernetes as long as they are in different namespaces.
> In your case you are indicating:
> 
> 1. generate a config-map in the default namespace,
> 2. get a deployment in non-default namespace to point a to config-map in the non-default namespace. Since non-default-ns/cafe-configmap does not exist, kustomize will not touch it.
>    ==> So it is expected.
> 
> To solve it, you are not forced to put everything in the overlay into a new namespace. You can if you want just put the config-map in the non-default-ns, by adding namespace: xxx just bellow the name: in the config map generator.

It works!

**Comment by Ebrithil95** [comment]
I am facing this issue as well.

I am trying to override a configmap and a secret that is provided in an all-in-one deployment.
My kustomization looks like this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/infracloudio/botkube/v0.12.1/deploy-all-in-one.yaml
secretGenerator:
  - name: botkube-communication-secret
    namespace: botkube
    behavior: replace
    files:
      - comm_config.yaml
configMapGenerator:
  - name: botkube-configmap
    namespace: botkube
    behavior: replace
    files:
      - resource_config.yaml
```

The replacement of the configmap/secret works fine but no hash is appended to the name so an update doesn't trigger a redeployment.

**Comment by lily-es** [comment]
Can also confirm this issue, and can confirm that adding `namespace: xyz` to the overlay kustomization.yaml functions as a workaround. In my case I am using `behavior:merge`

base
```configMapGenerator:
  - name: x-configmap
    files:
      - static-data.xml=data/k8s-proddata.xml
      - data/x-config.yml```

overlay
```configMapGenerator:
  - name: x-configmap
    behavior: merge
    files:
      - data/x-config.yml```

**Comment by jimethn** [comment]
I am seeing this same problem, but specifically for CRDs.

If I have a `secretGenerator`, any Deployments or StatefulSets that reference the generated secret will have the reference updated with the name suffix hash. However, if a CRD references that secret, it does not get the reference updated.

**Comment by thesuperzapper** [comment]
It seems like this issue happens when you have one kustomization (the "outer") that has another kustomization as a base resource (the "inner").

When the "inner" kustomization defines a global `namespace`, the "outer" kustomization is unaware of this, so if a new ConfigMap is defined in the "outer" (e.g. using `configMapGenerator`), this ConfigMap will end up in the default namespace.

I think this is __the expected behavior for kustomize__, and for most users, one of the following will result in the correct output:

1. Set a global namespace in your "outer" kustomization
2. Set the namespace explicitly in your ConfigMap

---

_TIP: it turns out that you can set a `namespace` explicitly in the `configMapGenerator`:_

```yaml
configMapGenerator:
  - name: pipeline-install-config
    namespace: my-namespace
    literals:
      - aaa=bbb
```
