### ISSUE TITLE
Name reference vars do not take configmap suffix into account

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#131]
When using the vars feature, it will respect the global name prefix, but not the configmap hash suffix.

kustomization.yaml:
```yaml
resources:
  - manifest.yaml

namePrefix: test-

vars:
  - name: NGINX_CONFIG_MAP
    objref:
      kind: ConfigMap
      name: nginx-configuration
      apiVersion: v1

```

manifest.yaml:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
          args:
            - /nginx-ingress-controller
            - --configmap=$(NGINX_CONFIG_MAP)
```

Output of kustomize build:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ingress-nginx
  name: test-nginx-configuration-54b84dcft6
  namespace: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-ingress-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --configmap=test-nginx-configuration
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
        name: nginx-ingress-controller
```

As you can see, the argument comes out as `--configmap=test-nginx-configuration` when it should be `test-nginx-configuration-54b84dcft6`. This also means the example in https://github.com/kubernetes-sigs/kustomize/issues/50#issuecomment-397107761 does not work.

**Comment by Liujingfang1** [comment]
This bug should be related to the order of different transformations.
The hash suffix for configmap is added in the final transformation. We need to apply the variable reference transformer after it.

**Comment by dguggi** [comment]
I have the same problem with secrets, e.g.

kustomization.yaml:

```yaml
resources:
  - traefik-ui-ingress.yaml

secretGenerator:
  - name: traefik-cert
    commands:
      tls.crt: "cat tls.crt"
      tls.key: "cat tls.key"
    type: "kubernetes.io/tls"
  - name: traefik-ui-secret
    commands:
      traefik-ui-secret: "cat traefik-ui-secret"
    type: Opaque

vars:
  - name: TRAEFIK_UI_SECRET
    objref:
      kind: Secret
      name: traefik-ui-secret
      apiVersion: v1
  - name: TRAEFIK_CERT
    objref:
      kind: Secret
      name: traefik-cert
      apiVersion: v1
```

taefik-ui-ingress.yaml:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ui
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: $(TRAEFIK_UI_SECRET)
spec:
  rules:
  - host: minikube
    http:
      paths:
      - path: /traefik
        backend:
          serviceName: traefik-ui
          servicePort: web
  tls:
   - secretName: $(TRAEFIK_CERT)
```

output:
```yaml
apiVersion: v1
data:
  tls.crt: blabla
  tls.key: blabla
kind: Secret
metadata:
  creationTimestamp: null
  name: traefik-cert-h7654c9df6
type: kubernetes.io/tls
---
apiVersion: v1
data:
  traefik-ui-secret: blabla
kind: Secret
metadata:
  creationTimestamp: null
  name: traefik-ui-secret-gbkkchtm8h
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-secret: $(TRAEFIK_UI_SECRET)
    ingress.kubernetes.io/auth-type: basic
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  name: traefik-ui
spec:
  rules:
  - host: minikube
    http:
      paths:
      - backend:
          serviceName: traefik-ui
          servicePort: web
        path: /traefik
  tls:
  - secretName: $(TRAEFIK_CERT)
```
