### ISSUE TITLE
kustomize messes with kubectl over envs

### ISSUE THREAD

**Issue by mhubig** [kubernetes-sigs/kustomize#1310]
Since version 2.1.0 kustomize silently changes

```yaml
configMapGenerator:
- name: environment
  env: environment.txt
```

to:

```yaml
configMapGenerator:
- name: environment
  envs:
    - environment.txt
```

But kubectl doesn't like the the new `envs` key since it has only version 2.0.3 build in ... :-(

```shell
$ kubectl apply -k $(pwd)
error: json: unknown field "envs"
```
