### ISSUE TITLE
Job spec/template/spec/volumes/projected/sources/configMap/name missing in configmap transformer

### ISSUE THREAD

**Issue by waldiTM** [kubernetes-sigs/kustomize#1322]
kustomize 433733eb0eb5d85659e220ddde94d9819792fe8b does not transform generate configMap names inside projected volumes of jobs.  The following entry is missing:

```
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/template/spec/volumes/projected/sources/configMap/name
    kind: Job
```
