### ISSUE TITLE
Deploying resources with same basic template

### ISSUE THREAD

**Issue by KyleMasterson** [kubernetes-sigs/kustomize#1339]
I am attempting to create a significant number of resources (CronJobs) that will all use the same basic template, but will have variants in the name of the job, the schedule, and the command to run on the container in the pod. 

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: custom-name
spec:
  schedule: * * * * *
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: custom-name
            args: [ "custom command" ]
...
```

Ideally there would be some mechanism to maintain one template, and then have some form of a hash containing the required custom fields for each job, rather than having a full yaml file for each job. I am open to suggestions on how this, or something similar, can be done, but so far I have not found a good way to achieve this.

**Comment by jbrette** [comment]
@KyleMasterson I'll create a example showing how this can be achieved using autovar.

**Comment by jbrette** [comment]
@KyleMasterson   To achieve the "template" feature, you can use the kustomize strategicMergePatches which is the way kustomize has always  been used.   The "autovar" feature [PR](https://github.com/kubernetes-sigs/kustomize/pull/1217) gets you to use kustomize more like you would use helm values.yaml

Checked-in the example files [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1339)

Here is an output:

```bash
kustomize build instance1/
```

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo hello from Instance1 using vars
            image: busybox
            name: usingvars
          - args:
            - /bin/sh
            - -c
            - date; echo hello from Instance1 using strategiMergePatch
            image: busybox
            name: usingpatch
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
---
apiVersion: apps/v1
kind: Values
metadata:
  name: forcronjob
spec:
  args:
  - /bin/sh
  - -c
  - date; echo hello from Instance1 using vars
  schedule: '*/1 * * * *'
```

```bash
kustomize build instance2
```

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo hello from Instance2 using vars
            image: busybox
            name: usingvars
          - args:
            - /bin/sh
            - -c
            - date; echo hello from Instance2 using strategiMergePatch
            image: busybox
            name: usingpatch
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
---
apiVersion: apps/v1
kind: Values
metadata:
  name: forcronjob
spec:
  args:
  - /bin/sh
  - -c
  - date; echo hello from Instance2 using vars
  schedule: '*/2 * * * *'
```
