### ISSUE TITLE
Undocumented change in patchesJson6902 handling from v2.1.0 and v3.0.x

### ISSUE THREAD

**Issue by looztra** [kubernetes-sigs/kustomize#1351]
## Context

This is somewhat related to #1332 (actually I extracted my comment to create a new issue in an attempt to get someone else point of view on the topics).

I have a repo showcasing the change => https://github.com/looztra/kustomize-issue--failed-to-find-unique-target-for-patch

## Usecase 1

- namespace in the _base_ resource specified to *any* value

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
  namespace: OVERLOADED_DURING_KUSTOMIZATION
  labels:
    app: atlantis
.
```

- namespace specified in the _base_ `kustomization.yml`

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlantis
.
```

- patchesJson6902 in the _overlay_ not specifying a namespace

```yaml
patchesJson6902:
  # atlantis
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: atlantis
    path: patches/atlantis/atlantis--deployment.yml
```

Kustomize `v2.1.0` : **OK**
Kustomize `v3.0.x` : **NOK**

Error with `v3.0.x` : `Error: no matches for OriginalId apps_v1_Deployment|~X|atlantis; no matches for CurrentId apps_v1_Deployment|~X|atlantis; failed to find unique target for patch apps_v1_Deployment|atlantis`

### Fix to make it work with Kustomize `v3.0.x`

- remove the namespace in in the _base_ resource (still works with `v2.1.0`)
- **OR** specify the namespace in the patch target (breaks kustomize `v2.1.0`, see Usecase2)

## Usecase 2

- namespace in the _base_ resource specified to *any* value

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
  namespace: OVERLOADED_DURING_KUSTOMIZATION
  labels:
    app: atlantis
.
```

- namespace specified in the _base_ `kustomization.yml`

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlantis
.
```

- patchesJson6902 in the _overlay_ specifying a namespace

```yaml
patchesJson6902:
  # atlantis
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: atlantis
      namespace: atlantis
    path: patches/atlantis/atlantis--deployment.yml
```

Kustomize `v2.1.0` : **NOK**
Kustomize `v3.0.x` : **OK**

Error with `v2.1.0` : `Error: couldn't find target apps_v1_Deployment|atlantis|atlantis for json patch`

## Usecase 3

- **NO** namespace in the _base_ resource

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlantis
  labels:
    app: atlantis
.
```

- namespace specified in the _base_ `kustomization.yml`

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlantis
.
```

- patchesJson6902 in the _overlay_ **NOT** specifying a namespace

```yaml
patchesJson6902:
  # atlantis
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: atlantis
    path: patches/atlantis/atlantis--deployment.yml
```

Kustomize `v2.1.0` : **OK**
Kustomize `v3.0.x` : **OK**

## Proposal

I didn't see anything related to that change in the patch behaviour regarding namespaces in the changelog (but I may have missed it), maybe that should be documented somewhere
