### ISSUE TITLE
Cannot update image using digest with images kustomization

### ISSUE THREAD

**Issue by arvan-pritchard** [kubernetes-sigs/kustomize#1357]
Using kustomize Version: {KustomizeVersion:3.0.0 GitCommit:e0bac6ad192f33d993f11206e24f6cda1d04c4ec BuildDate:2019-07-03T18:21:24Z GoOs:linux GoArch:amd64}

If an image is specified using. a digest rather than a tag, the images kustomization does not update it.

with pod.yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.29.0
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-mydb
    image: busybox@sha256:1111111111111111
    command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']
```

and kustomization.yaml
```yaml
resources:
- pod.yaml
images:
- name: busybox
  newName: alpine
  digest: sha256:2222222222222222
```
kustomize build outputs:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: alpine@sha256:2222222222222222
    name: myapp-container
  initContainers:
  - command:
    - sh
    - -c
    - until nslookup mydb; do echo waiting for mydb; sleep 2; done;
    image: busybox@sha256:1111111111111111
    name: init-mydb
```

Only the tag-specified image has been updated.

**Comment by jbrette** [comment]
@arvan-pritchard Seems to be fixed by this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1359)

Reproduced environment [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1357)

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: alpine@sha256:2222222222222222
    name: myapp-container
  initContainers:
  - command:
    - sh
    - -c
    - until nslookup mydb; do echo waiting for mydb; sleep 2; done;
    image: alpine@sha256:2222222222222222
    name: init-mydb
```
