### ISSUE TITLE
Apply resource quotas eagerly

### ISSUE THREAD

**Issue by EronWright** [kubernetes-sigs/kustomize#1368]
**Issue**
Since `ResourceQuota` and `LimitRange` are resource types related to admission control, they should be applied eagerly (e.g. before any pods are created).  Otherwise the quota might be applied inconsistently, since ([ref](https://kubernetes.io/docs/concepts/policy/resource-quotas/)):
> Neither contention nor changes to quota will affect already created resources.

**Suggested Fix**
Adjust the ordering logic to include `ResourceQuota` and `LimitRange` immediately after `Namespace` ([ref](https://github.com/kubernetes-sigs/kustomize/blob/v3.0.2/pkg/gvk/gvk.go#L78)).   Note the similar logic in Helm ([ref](https://github.com/helm/helm/blob/v2.14.2/pkg/tiller/kind_sorter.go#L28)).

**Comment by jbrette** [comment]
@EronWright @Liujingfang1 We should potentially think about improving the pkg/commands/build/reorderoutput.go so that we can get the reverse order. If you think about is you want to be able to do "kustomize build <params> | kubectl apply -f -" but also "kustomize build <params>  | kubectl delete -f -". In the second case you need a reverse order.

**Comment by Liujingfang1** [comment]
@jbrette Agreed. We need a reverse order for delete.

**Comment by jbrette** [comment]
@EronWright This is fixed by [#1451](https://github.com/kubernetes-sigs/kustomize/pull/1451)

**Comment by jbrette** [comment]
@EronWright @Liujingfang1 @monopole 

Please have a look a this [test environment](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1368#execution)

The user can now specify through config file the order of resources during kubectl apply 
[HERE](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1368#execution)

```bash
kustomize build base  --reorder=kubectlapply --enable_alpha_plugins | kubectl apply -f -
```

and other one for the kubectl delete
```bash
kustomize build base  --reorder=kubectldelete --enable_alpha_plugins | kubectl delete -f -
```

The user can control the order by change the plugin configuration:

For instance
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: KubectlApplyOrderTransformer
metadata:
  name: kubectlapplyordertransformer
kindorder:
- CustomResourceDefinition
- Namespace
- Deployment
- Service
- Ingress
- MyCRD
```
and

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: KubectlDeleteOrderTransformer
metadata:
  name: kubectldeleteordertransformer
kindorder:
- MyCRD
- Ingress
- Service
- Deployment
- Namespace
- CustomResourceDefinition
```
