### ISSUE TITLE
namespace transformation fails to update rolebinding subject

### ISSUE THREAD

**Issue by richardmarshall** [kubernetes-sigs/kustomize#1377]
Starting in v3.0.3 if a resource is included with the same namespace as the target for the namespace transformer the service account update for rolebindings will not set the namespace correctly.

For the following kustomization and resources:

```yaml
cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foo
resources:
- test.yaml
```

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb
subjects:
- kind: ServiceAccount
  name: sa
  namespace: bar
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: foo # this configmap has the same namespace as the transformer target
```

Output from v3.0.2
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: foo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb
subjects:
- kind: ServiceAccount
  name: sa
  namespace: foo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: foo
```

Output from v3.0.3
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: foo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb
subjects:
- kind: ServiceAccount
  name: sa
  namespace: null
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: foo
```

In v3.0.3 the subject of the ClusterRoleBinding has a null namespace instead of the expected value `foo`.

Without the explicit `.metadata.namespace` in the configmap the update of the role binding works as expected.

Discovered in this slack thread for more context:
https://kubernetes.slack.com/archives/C9A5ALABG/p1563542754114100

Will look into what is causing this when I have some available time.

**Comment by jbrette** [comment]
Fixed by [Update Namespace and Name simultaneously](https://github.com/kubernetes-sigs/kustomize/pull/1379)

**Comment by jbrette** [comment]
@richardmarshall The #1379 has been merged. Can you check it and close the bug.

**Comment by richardmarshall** [comment]
@jbrette Looks good, closing.

**Comment by jannickfahlbusch** [comment]
It seems like #1379 (f649b626295151afe6925ef530d95764195512f0 to be precise) broke our setup with replacing the namespace. We are using kubebuilder and kustomize on top of it.

Here is a simplified example which reproduces the issue:

`default/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "foo"

bases:
 - ../manager
```

`manager/kustomization.yaml`:
```yaml
resources:
  - clusterRoleBinding.yaml
```

`manager/clusterRoleBinding.yaml`:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
```

After running `kustomize build` we get the following YAML:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
```

Expected was:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
```

**Comment by Liujingfang1** [comment]
@jannickfahlbusch Thank you for reporting the issue. This is a new bug. The namespace transformation on `default` ServiceAccount was hard coded previously. This change removed it. We should fix that. @jbrette Can you take a a look? If solving it in the namereference is not feasible, we can reuse the previous logic.

**Comment by jannickfahlbusch** [comment]
Interesting, I just tried to change the name of the ServiceAccount to a value different than `default`. It's not working in the last versions if the name is not `default` (Tried all `v3.0.x` versions and `v2.1.0`)

**Comment by Liujingfang1** [comment]
@jannickfahlbusch   This is fixed in 3.1.0.

**Comment by YiannisGkoufas** [comment]
Just to say that is not working in `3.8.2` as well. If you use any other name besides `default` the namespace won't be updated.

`kustomization.yaml`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace
resources:
  - role_binding.yaml
```

`rolebinding.yaml`:

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dataset-operator
subjects:
- kind: ServiceAccount
  name: dataset-operator
  namespace: foo
roleRef:
  kind: ClusterRole
  name: dataset-operator
  apiGroup: rbac.authorization.k8s.io
```
The above keeps the namespace as `foo`

However if I modify the subjects as:

`rolebinding.yaml`:

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dataset-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
roleRef:
  kind: ClusterRole
  name: dataset-operator
  apiGroup: rbac.authorization.k8s.io
```

Kustomize will work correctly and replace namespace with `my-namespace`

**Comment by YiannisGkoufas** [comment]
By the way also by using vars it won't work:

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dataset-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: $(dataset-operator-namespace)
roleRef:
  kind: ClusterRole
  name: dataset-operator
  apiGroup: rbac.authorization.k8s.io
```
