### ISSUE TITLE
Transformation of RoleBindng and ClusterRoleBinding roleRef should use kind field

### ISSUE THREAD

**Issue by jbrette** [kubernetes-sigs/kustomize#1380]
This has been reproduced with kustomize 2.0.3, 2.10, 3.0.2 and 3.0.3

The main idea to prove the issue is to create a ClusterRole with the name "role" in on folder, a Role in another folder with the same name "role" in another folder, and check how kustomize handles name prefixes.

In this case, kustomize is looking for a ClusterRole or a Role with  name "role"  in order to replace the name field in the RoleRef.  There are two resources matching that description but kustomize does not detect any conflict and maps to the wrong value.

**Comment by jbrette** [comment]
```bash
DEMO_HOME=$(mktemp -d)
```

## Preparation


```bash
mkdir -p ${DEMO_HOME}/cluster-role
mkdir -p ${DEMO_HOME}/combined
mkdir -p ${DEMO_HOME}/role
```

### Preparation Step KustomizationFile0


```bash
cat <<'EOF' >${DEMO_HOME}/cluster-role/kustomization.yaml
namePrefix: prefix-for-cluster-

resources:
- resources.yaml
EOF
```


### Preparation Step KustomizationFile1


```bash
cat <<'EOF' >${DEMO_HOME}/combined/kustomization.yaml
bases:
- ../role
- ../cluster-role

resources:
- resources.yaml
EOF
```


### Preparation Step KustomizationFile2


```bash
cat <<'EOF' >${DEMO_HOME}/role/kustomization.yaml
namePrefix: prefix-for-role-

resources:
- resources.yaml
EOF
```


### Preparation Step Resource0


```bash
cat <<'EOF' >${DEMO_HOME}/cluster-role/resources.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - watch
EOF
```


### Preparation Step Resource1


```bash
cat <<'EOF' >${DEMO_HOME}/combined/resources.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cockroachdb
  name: cockroachdb
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroachdb
subjects:
- kind: ServiceAccount
  name: cockroachdb
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cockroachdb
subjects:
- kind: ServiceAccount
  name: cockroachdb
  namespace: default
EOF
```


### Preparation Step Resource2


```bash
cat <<'EOF' >${DEMO_HOME}/role/resources.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
EOF
```

## Execution


```bash
mkdir ${DEMO_HOME}/actual
kustomize build ${DEMO_HOME}/combined -o ${DEMO_HOME}/actual
```
The cluster role binding is right
```yaml
kind: ClusterRoleBinding
metadata:
  labels:
    app: cockroachdb
  name: cockroachdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prefix-for-cluster-cockroachdb
subjects:
- kind: ServiceAccount
  name: cockroachdb
  namespace: default
EOF
```

But the RoleBinding is wrong

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: cockroachdb
  name: cockroachdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefix-for-cluster-cockroachdb
subjects:
- kind: ServiceAccount
  name: cockroachdb
  namespace: default
EOF
```
