### ISSUE TITLE
Need to improve namereference conflict detection

### ISSUE THREAD

**Issue by jbrette** [kubernetes-sigs/kustomize#1381]
This was reproduce with kustomize 2.0.3, 2.10, 3.0.2 and 3.0.3

The idea is to force namereference algorithm to run. Create three folder each with a cluster wide resource with the same name "orgname". In each context, add a name prefix
```yaml
resources:
- ../validatingwebhook
- ../persistentvolume
- ../storageclass
- clusterrole.yaml
```

The resourceName is containing "orgname". kustomize does not use the "resources" field to deconflict.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orgname
rules:
  resourceNames:
  - orgname
  resources:
  - persistentvolumes
````

Kustomize does not detect any conflict where it should, and pick storageclass.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-orgname
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orgname
rules:
  resourceNames:
  - storageclass-orgname
  resources:
  - persistentvolumes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolumes-orgname
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validatingwebhook-orgname
```
