### ISSUE TITLE
support reading values from version-controlled files in json patch definitions

### ISSUE THREAD

**Issue by tkellen** [kubernetes-sigs/kustomize#1387]
@Liujingfang1 / @monopole would you consider a PR that introduces support for reading external files for values in json patch operations? If yes, I'd be happy to submit an implementation and associated tests.

Here is an example usage:
```
- op: add
  path: /spec/template/spec/containers/0/env/0
  value:
    name: CONCOURSE_POSTGRES_HOST
    valueFrom:
      fileRef:
        path: ../../config/environment/rds_ci_hostname
```

*A version of this feature was originally discussed here: https://github.com/kubernetes-sigs/kustomize/issues/1233*
