### ISSUE TITLE
secretName in azureFile doesn't expand vars

### ISSUE THREAD

**Issue by jstralko** [kubernetes-sigs/kustomize#1390]
For example, the following example doesn't seem to expand the vars for secretName:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
          - name: app
            volumeMounts:
            - name: appMnt
              mountPath: /data
      volumes:
      - name: appMnt
        azureFile:
          secretName: $(STORAGE_SECRET)
          shareName: appMnt-share
          readOnly: true
---
vars:
- name : STORAGE_SECRET
  objref:
    kind: Secret
    name: storage-secret
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
```
STORAGE_SECRET is never transformed.  I even get a warning saying: `well-defined vars that were never replaced: STORAGE_SECRET` Is this something that isn't supported?  Since I'm using namePrefix I need to get storage name via this way.

**Comment by jbrette** [comment]
@jstralko Your are missing a kustomizeconfig.yaml

We attempted to reproduce your [issue here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1390/manual)
 
The output will look like that:
```bash
kustomize build manual
```

```yaml
apiVersion: v1
data:
  password: c29tZXB3
  username: YWRtaW4=
kind: Secret
metadata:
  name: pfx-storage-secret
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfx-app
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
        - mountPath: /data
          name: appMnt
      volumes:
      - azureFile:
          readOnly: true
          secretName: pfx-storage-secret
          shareName: appMnt-share
        name: appMnt
```

kustomizeconfig.yaml:

```yaml
varReference:
- kind: Deployment
  path: spec/template/spec/volumes[]/azureFile/secretName
```

kustomization.yaml

```yaml
namePrefix: pfx-

resources:
- deployment.yaml
- secret.yaml

configurations:
- kustomizeconfig.yaml

vars:
- name : STORAGE_SECRET
  objref:
    kind: Secret
    name: storage-secret
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
```
