### ISSUE TITLE
Error: json: cannot unmarshal number into Go struct field ConfigMapArgs.files of type string

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#1401]
If we do the below:
```
configMapGenerator:
  - name: cert-inject
    namespace: api
    files: 
      - 0a3654cf.0
      - 38915415.0
```
we see that the `38915415.0` file causes an error `Error: json: cannot unmarshal number into Go struct field ConfigMapArgs.files of type string`. The `0a3654cf.0` one does not cause an error.

If i put quotes around the filename, i end up with quotes in the name in yaml:
```
  "38915415.0": |
    -----BEGIN CERTIFICATE-----
    MIIDFTCCAf2gAwIBAgIUCl6nMpzIOHEYTaq3m5erOqxXmb8wDQYJKoZIhvcNAQEL
```

why is it interpreting this file name as a number?
