### ISSUE TITLE
Failed to find target with or without namespaces being specified 3.1.0

### ISSUE THREAD

**Issue by karlmutch** [kubernetes-sigs/kustomize#1404]
When using nested directories Deployments cannot be resolved by kustomize.  This occurs with or without namespaces being specified and also when using both json and strategic merge patch types.

This appears to differ from other reported cases as the namespaces do not seem to influence the problem.

Given the following, when using the following command in the root directory and error occurs.

<pre><b>
kustomize build
</b>
Error: accumulating resources: recursed accumulation of path 'test-kus/overlays/production': accumulating resources: recursed accumulation of path 'green': no matches for OriginalId apps_v1_Deployment|~X|esp-green; no matches for CurrentId apps_v1_Deployment|~X|esp-green; failed to find unique target for patch apps_v1_Deployment|esp-green
</pre>

<pre>
.
├── kustomization.yaml
└── test-kus
    ├── base
    │   ├── deployment.yaml
    │   └── kustomization.yaml
    └── overlays
        └── production
            ├── green
            │   ├── deployment.yaml
            │   └── kustomization.yaml
            └── kustomization.yaml

</pre>

[patch-issue.zip](https://github.com/kubernetes-sigs/kustomize/files/3437552/patch-issue.zip)

Base deploy.yaml

<pre>
at test-kus/base/deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-green
spec:
  template:
    spec:
      containers:
      - name: esp
        imagePullPolicy: Always
        image: leaf/esp-service
</pre>

Patching deployment.yaml

<pre>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-green
spec:
  template:
    spec:
      containers:
      - name: esp
        image: leaf/esp-service:latest
</pre>

**Comment by jbrette** [comment]
@karlmutch Just adjust your green kustomization.yaml to include esp-green resource and it works fine as shown bellow. This environment to reproduce your issue is available [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1404).

```bash
prompt$ kustomize version
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}
```

```bash
$ kustomize build .
```

```yaml
kind: Deployment
metadata:
  annotations:
    note: This is the production green environment
  name: esp-green
  namespace: test
spec:
  template:
    metadata:
      annotations:
        note: This is the production green environment
    spec:
      containers:
      - image: 11111.dkr.ecr.us-west-2.amazonaws.com/leaf/esp-service:latest
        imagePullPolicy: Always
        name: esp
```

**Comment by karlmutch** [comment]
Thanks for the really complete answer, this however leaves me with a dilemma for a more complex situation. This example has a blue and a green deployment at the same level.
<pre>
.
├── kustomization.yaml
└── test-kus
    ├── base
    │   ├── deployment.yaml
    │   └── kustomization.yaml
    └── overlays
        ├── kustomization.yaml
        └── production
            ├── blue
            │   ├── deployment.yaml
            │   └── kustomization.yaml
            └── green
                ├── deployment.yaml
                └── kustomization.yaml
</pre>

Changing each of the kustomize.yaml files to include the base results in a duplication error.

<code>
Error: accumulating resources: recursed accumulation of path 'test-kus/overlays': accumulating resources: recursed merging from path 'production/blue': may not add resource with an already registered id: apps_v1_Deployment|~X|esp-green
</code><p><p>
Leaving it out of any one of the green or blue Kustomize.yaml file results in the not found error within the peer directory it was omitted from.
Here is the use-case archive.

[patch-issue.zip](https://github.com/kubernetes-sigs/kustomize/files/3437882/patch-issue.zip)

**Comment by karlmutch** [comment]
Am I simply duplicating https://github.com/kubernetes-sigs/kustomize/pull/1316 ?

**Comment by jbrette** [comment]
@karlmutch You are not duplicated #1316 is a very interesting use case where we are trying to compose service a lot like you would use git to merge and cherry pick patches. We have a beginning of solution of it.

For your more simple use case, I think it works: [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1404)

```bash
 kustomize build .
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: This is the production blue environment
  name: esp-blue
  namespace: test
spec:
  template:
    metadata:
      annotations:
        note: This is the production blue environment
    spec:
      containers:
      - image: 11111.dkr.ecr.us-west-2.amazonaws.com/leaf/esp-service:latest
        imagePullPolicy: Always
        name: esp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: This is the production green environment
  name: esp-green
  namespace: test
spec:
  template:
    metadata:
      annotations:
        note: This is the production green environment
    spec:
      containers:
      - image: 11111.dkr.ecr.us-west-2.amazonaws.com/leaf/esp-service:latest
        imagePullPolicy: Always
        name: esp
```
