### ISSUE TITLE
Unexpected name globbing in multi-target patch

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#1409]
Hi,

I have been testing the new `patches` syntax for patching multiple targets and I have found the following oddity.
When defining a target as:
```yaml
  - path: mypatch.yml
    target:
      kind: Deployment
      name: myapp-*
```
It will match all deployments starting by `myapp-` but also deployments starting by anything else and containing `myapp-*` such as `x-myapp-a`. I was expecting it to behave like the regex `^mymapp-*`.

I don't know if it's a misunderstanding on my side and this behaviour is expected or not but it is quite surprising.
