### ISSUE TITLE
Resources with same name in different namespaces conflict

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#141]
While trying to model all my cluster infrastructure resources, I ran into #38. As a workaround, I wrote the output of several kustomizations into YAML files and used them as resources in another kustomization. That did not work either, because the resource names are still duplicates, although they are in different namespaces. 

Minimal reproduction for that:

kustomization.yaml:
```
resources:
- service_a.yaml
- service_b.yaml
```

service_a.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-controller
  namespace: a
spec: {}
```

service_b.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-controller
  namespace: b
spec: {}
```

kustomize build:
`Error: loadResMapFromBasesAndResources: rawResources failed to read Resources: id '"v1_Service_ingress-controller.yaml"' already used`
