### ISSUE TITLE
Example on how to create a docker-registry secret

### ISSUE THREAD

**Issue by mhubig** [kubernetes-sigs/kustomize#1420]
There is a kubectl command to create a docker-registry secret object which can be used to pull images from private registrys.

```shell
kubectl create secret docker-registry regcred \
  --docker-server=<your-registry-server> \
  --docker-username=<your-name> \
  --docker-password=<your-pword> \
  --docker-email=<your-email>
```

It would be very nice and helpfull if there were some kind of documentation on how to generate the same secret object with kustomize! Something like this:

```yaml
secretGenerator:
  - name: regcred
    literals:
      - .dockerconfigjson=<Encoded Secret>
    type: "kubernetes.io/dockerconfigjson"
```

The `<Encoded Secret>` seems to be the base64 encoded string:

```json
{
  "auths": {
    "your-registry-server": {
      "username": "your-name",
      "password": "your-pword",
      "email": "your-email",
      "auth": "<Secret>"
    }
  }
}
```

The `<Secret>` seems to be the base64 encoded string:

```
your-name:your-pword
```

Source: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#inspecting-the-secret-regcred
