### ISSUE TITLE
dash generated by configMapGenerator fail pod creation for fluent-bit configMap

### ISSUE THREAD

**Issue by mdpixel** [kubernetes-sigs/kustomize#1425]
**What happened** : 

I use configMapGenerator to load my fluent-bit config file placed on my desktop computer
```yaml
bases:
  - ../../../../projects/kustomize-registry/fluent-bit/bases/

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: fluent-bit-config
    behavior: merge
    files:
    - configs/fluent-bit.conf
```
Here is my kustomization.yaml : 
```sh
├── fluent-bit
│   ├── configs
│   │   ├── fluent-bit.conf
│   │   ├── filter-kubernetes.conf
│   │   ├── output-stdout.conf
│   └── kustomization.yaml
```
After apply kustomize CLI : `kustomize build fluent-bit | kubectl apply -f -`
```yaml
apiVersion: v1
data:
  filter-kubernetes.conf: |-
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  fluent-bit.conf: |-
    [SERVICE]
        Flush         2
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   off
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

        @INCLUDE input-kubernetes.conf
        @INCLUDE filter-kubernetes.conf
        @INCLUDE output-stdout.conf
  output-stdout.conf: |-
    [OUTPUT]
        Name        forward
        Match       *
        Upstream    upstream-forward.conf
```
Pod creating fail because dashes at the end of config file name such as ` output-stdout.conf: |-`

If I apply changes without `configMapGenerator`, Pod is up and running without errors and my  generated configmap has the same previous result but without dashes.

**Environment** : 
Google Kubernetes Engine : **1.13.7-gke.8**
kubectl : **v1.13.7**
kustomize: **v3.1.0**

How I delete dash of the end of config file name ?
