### ISSUE TITLE
kustomize edit clears `replicas` section

### ISSUE THREAD

**Issue by igorcoding** [kubernetes-sigs/kustomize#1427]
Tried using replicas field in kustomization.yaml as follows:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- depl.yaml
replicas:
  - name: api
    count: 3
```

After applying `kustomize edit set image` `replicas` section disappears from the kustomization.yaml:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- depl.yaml
images:
- name: image
  newName: nginx
  newTag: latest
```

Expected behaviour: replicas are preserved between executions of `kustomize edit`.

```
➜ kustomize version                          
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}
```
