### ISSUE TITLE
hostAliases are not correctly patched

### ISSUE THREAD

**Issue by yanc0** [kubernetes-sigs/kustomize#143]
Hi, here my setup:

**base/deployment.yml:**

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deploy
[...]
    spec:
      hostAliases:
      - ip: "10.1.200.200"
        hostnames:
        - "memcached-sessions"
      - ip: "127.0.0.1"
        hostnames:
        - "memcached"
[...]
```

**overlays/qa/patch-memcached.yaml**

```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deploy
spec:
  template:
    spec:
      hostAliases:
      - ip: "10.5.200.200"
        hostnames:
        - "memcached-sessions"
```

**kustomize build**:

```
[...]
      hostAliases:
      - hostnames:
        - memcached-sessions
        ip: 10.5.200.200
      - hostnames:
        - memcached-sessions
        ip: 10.1.200.200
      - hostnames:
        - memcached
        ip: 127.0.0.1
[...]
```

Overlay is added to the array but I expected `10.5.200.200` to replace `10.2.200.200`. IP is not the key to look after, IMHO, this is the combination of all hostnames because they probably don't change between environments.

Thanks ;)

**Comment by Liujingfang1** [comment]
Kustomize uses stategic merge patch. Maybe this is a problem in strategicpatch. What do you think @mengqiy?

**Comment by mengqiy** [comment]
@yanc0 
Currently the IP is the merge key for `hostAliases`, see: https://github.com/kubernetes/kubernetes/blob/3a3d6564b6ef5810988abb26782bc571b6bec31f/staging/src/k8s.io/api/core/v1/types.go#L2835-L2840
The merge key is used to identify an entry in a list. IOW it's immutable.
To "change" it, you need to go through delete and recreate.
The workaround is:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deploy
spec:
  template:
    spec:
      hostAliases:
      - ip: "10.1.200.200"
        $patch: delete
      - ip: "10.5.200.200"
        hostnames:
        - "memcached-sessions"
```
