### ISSUE TITLE
Namespace transformer can create conficts

### ISSUE THREAD

**Issue by richardmarshall** [kubernetes-sigs/kustomize#1438]
A kustomization can contain multiple objects with the same GVK and name as long as they are in different namespaces. However if the namespace transformer is used the resulting resmap after the transformer has run will contain an undetected ID conflict.

The following simple example demonstrates this:

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
- resources.yaml
```

**resources.yaml**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: ns1
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: ns2
data:
  baz: fuz
```

**output**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: test
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: test
data:
  baz: fuz
```

While obvious in this simple example when mixed into the output with a large number of other objects this would be easy to miss. kubectl will also not complain and simply update the same object in the cluster twice with different contents. Depending on the type of object this could have problematic side effects.

kustomize should return an error in this case informing the user that a conflict has been produced by the namespace transformation.
