### ISSUE TITLE
patchesJson6902 add annotation

### ISSUE THREAD

**Issue by wuestkamp** [kubernetes-sigs/kustomize#1439]
I would like to add an annotation using json patch to my ingress. I'm trying it like this right now:

```
- op: add
  path: "/metadata/annotations/-"
  value:
    nginx.ingress.kubernetes.io/auth-type: basic
```

The result is:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    '-':
      nginx.ingress.kubernetes.io/auth-type: basic
```

How can this be patched correctly?

**Comment by richardmarshall** [comment]
The `/-` syntax is used for inserting a value at the end of a list. The annotations field is a map so this syntax doesn't work in the same way.

If you want to completely replace the set of annotations in an object or if no annotations are currently set you can use:

```yaml
- op: add
  path: "/metadata/annotations"
  value:
    nginx.ingress.kubernetes.io/auth-type: basic
```

If there are existing annotations and you don't want to override them:

```yaml
- op: add
  path: "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-type"
  value: basic
```

However if you want to be able to support patching an object that may or may not have existing annotations and also not clobber other annotations you're kind of out of luck with json patches. In that case you'll need to use a strategic merge patch instead.

**Comment by wuestkamp** [comment]
Thanks for your answer! Yes I would like to add annotations to an exiting map of annotations. As far as I know, the strategic merge patch does not work with an Ingress resource, that's why I used json patching.

**Comment by Jojoooo1** [comment]
Did you resolve it ?

**Comment by c0da** [comment]
> This trick here, using `~` instead of `/` seems to work only for standard annotations.
> 
> If you want to patch something which is not a standard Kubernetes annotation the same way, the `~` is not replaced by a `/` smiling_face_with_tear

I was thinking the same thing, but the point is that you have to replace it with "~1", not "~"  👍

**Comment by srm09** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/1439#issuecomment-520614831

I was reading this comment and figured that there is no clear answer for appending to an existing annotation map. The following worked for me
```yaml
# to add annotation foo=bar this is the following definition
- op: add
  path: /metadata/annotations/foo
  value: bar
```
