### ISSUE TITLE
configMapGenerator namePrefix ignored with multiple levels of base inheritance

### ISSUE THREAD

**Issue by nabadger** [kubernetes-sigs/kustomize#1440]
Note, this worked in `2.0.3` but fails in `3.1.0`.

This test creates a base (a generic deployment), an intermediate-base (say a web-app), and an overlay (say a production instance).

The general idea is that we want to override a properties file (a configmap `env`) in the overlay.

The configmap is used in container's `envFrom`.

- In kustomize `2.x` the configmap name is correct (it uses the generated name).
- In kustomize `3.x` the configmap name is not changed
```
mkdir -p /tmp/test-kustomize-issue
cd /tmp/test-kustomize-issue
mkdir base intermediate-base overlay

cat << EOF > ./base/kustomization.yaml
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deploy.yaml
EOF

cat << EOF > ./base/deploy.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - args: []
        command: []
        image: container-image
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: main
        ports:
        - containerPort: 8000
          name: http
EOF

cat << EOF > ./intermediate-base/kustomization.yaml 
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namePrefix: frontend-web-
namespace: sandbox

bases:
- ../base

patches:
- patch-deploy-env.yaml

configMapGenerator:
- env: env.properties
  namespace: sandbox
  name: env
EOF

cat << EOF > ./intermediate-base/env.properties
DEBUG=False
EOF

cat << EOF > ./intermediate-base/patch-deploy-env.yaml 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: main
          envFrom:
          - configMapRef:
              name: env
EOF

cat << EOF > ./overlay/kustomization.yaml
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../intermediate-base

namePrefix: production-
namespace: sandbox

configMapGenerator:
- env: env.properties
  name: env
  namespace: sandbox
  behavior: merge
EOF

cat << EOF > ./overlay/env.properties
DEBUG=True
EOF
```

```
kustomize build overlay
```

In kustomize `2.x` we get:
```
 containers:
      - args: []
        command: []
        envFrom:
        - configMapRef:
            name: production-frontend-web-env-59bmdgdmkh
```
In kusotmize `3.x` we get:
```
  containers:
      - args: []
        command: []
        envFrom:
        - configMapRef:
            name: env
```
