### ISSUE TITLE
Cycle detection for git resources only identifies direct cycles.

### ISSUE THREAD

**Issue by richardmarshall** [kubernetes-sigs/kustomize#1447]
The current cycle detection for git resources will detect a direct cycle `A -> A` however an indirect cycle `A -> B -> A` will not be detected.

**Example overlay:**
```yaml
namespace: overlay
resources:
- https://gist.github.com/e71f6cc87da5c317a56f5688e2a524c8.git # base1
```

**base 1:** https://gist.github.com/richardmarshall/e71f6cc87da5c317a56f5688e2a524c8
```yaml
namespace: base1
resources:
- git::https://gist.github.com/7947e45b2ab817944bf37e188389a0c1.git # base2
```

**base 2:** https://gist.github.com/richardmarshall/7947e45b2ab817944bf37e188389a0c1
```yaml
namespace: base2
resources:
- git::https://gist.github.com/e71f6cc87da5c317a56f5688e2a524c8.git # base1
```

This will produce an infinite clone loop that will leak whatever number of successful cloned repos into the temp directory when kustomize is eventually ungracefully killed (user hitting ^C, CI system timeout, etc).

/kind bug
