### ISSUE TITLE
How can I use ENV var?

### ISSUE THREAD

**Issue by fanux** [kubernetes-sigs/kustomize#1448]
```
# DRONE_TAG="latest" kustomize build
```
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
....
        image: controller:$(DRONE_TAG)
```
I need set some var from command line, it is useful for CI/CD,  so we can deploy what version we build using kustomize.

**Comment by fanux** [comment]
```
spec:
  # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
  commonName: $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  dnsNames:
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
```
How `$(SERVICE_NAME)` substituted ?

**Comment by fanux** [comment]
Now CRD needs using sed...
```
sed -i'' -e 's@image: .*@image: '"${IMG}"'@' ./config/default/manager_image_patch.yaml
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: IMAGE_URL
        name: manager
```
