### ISSUE TITLE
Add pod selector to CRD

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#1458]
HI,
I am testing the prometheus operator and it uses a CRD ServiceMonitor which requires a `spec.selector.matchLabels`. Currently I manage all my labels and selectors with kustomize. Some of them are defined in my base and other in my overlays. What is the recommended way to manage the selector of my CRD to keep it in sync with my other selectors? I basically want to have the exact same selector for my Service and ServiceMonitor.

**Comment by richardmarshall** [comment]
The commonLabel transformer can be configured to inject labels into CRDs. This example shows how you can add additional types and fields that should be updated by the transformer: 

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md

**Comment by benjamin-bergia** [comment]
Hi @richardmarshall,

Thanks for your help. I tested and it does work!

Unfortunately, I have to define the config in each overlay that use this CRD. And since for security reason kustomize doesn't let me access a config outside the directory of the kustomization.yml, I have to copy my config file in each overlay.

Is there a way to define a "global" transformer config file? If not can I add my config to my top-level kustomzation.yml and get it applied to all my nested ones (which doesn't work for me at the moment)? 

I still would like to be able to define a kustomize config that is project wide, that will be easier to maintain.

**Comment by benjamin-bergia** [comment]
So I followed the [FAQ](https://github.com/kubernetes-sigs/kustomize/blob/3cb6c7f1f4293b28c0c3fd319d98a48a5ce66f09/docs/FAQ.md) and created a base containing my config file and a kustomization.yml. I then import it as a base. Unfortunately is doesn't change the configuration of other bases and overlays. For example if I have:
```
.
├── base
│   ├── web // commonLabels: type=web
│   └── worker //  commonLabels: type=worker
└── overlays
    ├── a  // commonLabels: part-of=a
    ├── b  // commonLabels: part-of=a
    └── c  // commonLabels: part-of=a
```
Where am I supposed to import my configuration for it to work with all this commonLabels?
If I add it in `overlays/*/kustomization.yml` it will only work for the `part-of` label. In `base/*/kustomization.yml` it will work for the `type` label only. I also tried with a `base/kustomization.yml` in which case it just doesn't do anything.

**Comment by jbrette** [comment]
@benjamin-bergia @richardmarshall Have a look [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1458)

kustomize is accumulating the transformer configs. One easy way to share configs is by having a "common" kustomize folder where you put your configurations and import that folder as resource (directly or indirectly) where you need it.

I do believe we can close this bug.

/cc @monopole @Liujingfang1 

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    part-of: b
    type: web
  name: monitor-web
spec:
  endpoints:
  - interval: 10s
    port: web
  selector:
    matchLabels:
      part-of: b
      type: web
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    part-of: b
    type: worker
  name: monitor-worker
spec:
  endpoints:
  - interval: 10s
    port: worker
  selector:
    matchLabels:
      part-of: b
      type: worker
```
