### ISSUE TITLE
commonLabels applied to podAffinity labelSelector.matchLabels

### ISSUE THREAD

**Issue by mshkrebtan** [kubernetes-sigs/kustomize#1459]
I want to run an application (`masterdata`) on a host where Memcached is already running, hence I specify `Affinity` in the `PodSpec`.

I use `kustomize` version `3.1.0`:
```
$ kustomize version
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T19:21:45+01:00 GoOs:darwin GoArch:amd64}
```

I build a configuration out of the following files:

`kustomization.yaml`:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: common-label

resources:
 - deployment.yaml
```

`deployment.yaml`:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: masterdata
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: memcached
              topologyKey: kubernetes.io/hostname
      containers:
```

When I run `kustomize build`, I get the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: common-label
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-label
  template:
    metadata:
      labels:
        app: common-label
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: common-label
            topologyKey: kubernetes.io/hostname
      containers:
```
Pay attention to the `matchLabels` map in the affinity block. It was altered by Kustomize.

So, as a workaround, I have to use the `matchExpressions` array in the `labelSelector`:
```
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - memcached
              topologyKey: kubernetes.io/hostname
```

Then I get the output I need
```
$ kustomize build
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: common-label
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-label
  template:
    metadata:
      labels:
        app: common-label
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - memcached
            topologyKey: kubernetes.io/hostname
      containers:
```

In the docs [here](https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#commonlabels) it's said:
> commonLabels will also be applied both to Label Selector fields and Label fields in PodTemplates.

As seen now, it also affects affinity rules in a PodTemplate. So, is this a bug or a feature?
