### ISSUE TITLE
configmap with multiple envs and conflicting keys

### ISSUE THREAD

**Issue by frejsoya** [kubernetes-sigs/kustomize#1468]
```
kustomize.yaml:
configMapGenerator:
- name: config
  behavior: merge
  envs:
    - default.local.env
    - component.local.env
```
Config contents:
```
$ echo "F=foo" >> default.local.env
$ echo "B=foo" >> default.local.env
$ echo "B=bar" >> component.local.env
```

Fails with
```
NewResMapFromConfigMapArgs: cannot add key B, another key by that name already exists: map[F:foo B:foo]
```

Should `behavior: merge` also merge two env files, similar to how you can merge to configMapGenerators.

So the expected config map would be:
```
...
F=Foo
B=Bar
...
```
