### ISSUE TITLE
Help: Use keys with configMapGenerator

### ISSUE THREAD

**Issue by mr-karan** [kubernetes-sigs/kustomize#1471]
Hi

Is it possible to [set a custom key](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-the-key-to-use-when-creating-a-configmap-from-a-file) while creating a configMap from a file?

I have 2 configs in the folder `config` as such
```
|-- config
|   |-- api.toml
|   `-- worker.toml
```

This is my `kustomization.yaml`

```
configMapGenerator:
  - name: app-worker
    files:
      - config/worker.toml
  - name: app-api
    files:
      - config/api.toml
```

What happens now (which is normal):

```
apiVersion: v1
kind: ConfigMap
data:
  worker.toml: blah blah
---
apiVersion: v1
kind: ConfigMap
data:
  api.toml: blah blah
```

What I expect to have in `configMap` generated after specifying a custom key `special-name.toml`

```
apiVersion: v1
kind: ConfigMap
data:
  special-name.toml: blah blah
```

Hope the question is clear and sorry if it has been mentioned before. I searched through the docs but couldn't find the same usecase anywhere.

**Comment by vreon** [comment]
Yep, the syntax is similar to `literals`:

```yaml
configMapGenerator:
- name: app-whatever
  files:
  - special-name.toml=config/whatever.toml
```
