### ISSUE TITLE
specifying label for secretGenerator item

### ISSUE THREAD

**Issue by pckhoi** [kubernetes-sigs/kustomize#1472]
I'm running a complex deployment service where it dynamically create new namespace and create secret in new namespace based on existing secret which I want to declare with secretGenerator. However there is no way for me to get the base secret, the name keep changing and I don't have a way to assign label to just this secret. Ideally the below syntax should work:
```
secretGenerator:
  - name: my-secret
    files:
      - abc.json
    labels:
      secret: my-secret
```

Alternatively if the secret comes with an automatic label such as `kustomize-base-name: my-secret`, that is also fine.

**Comment by richardmarshall** [comment]
@pckhoi generated resources can be patched using their non-suffixed names.

For example:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- literals:
  - foo=bar
  name: my-secret
  type: Opaque
patches:
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: my-secret
      labels:
        special: secret
```

Output:
```yaml
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  labels:
    special: secret
  name: my-secret-2948m89dkm
type: Opaque
```
