### ISSUE TITLE
Allow Var for Dynamic name in Namespace

### ISSUE THREAD

**Issue by TechnicalMercenary** [kubernetes-sigs/kustomize#1475]
I'm using `kustomize edit set namespace "$CUSTOMER_ID"` to have all of my kubernetes resources to be put into the same namespace.  Works great.

But I'm struggling with actually creating that namespace with-in kustomize.  I read there were some attempts at this by dynamic creation of  namespaces. 

#500 

what I'm thinking is would it be possible to allow`varreference.go` to

```
- path: metadata.name
  kind: Namespace
```

Then I would have to additionally create a config map...

```
kustomize edit add configmap source-vars --from-literal CUSTOMER_ID="$CUSTOMER_ID"
```

and in my kustomization.yaml

```
vars:
  - name: CUSTOMER_ID
    objref:
      kind: ConfigMap
      name: source-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.CUSTOMER_ID
```

**Comment by richardmarshall** [comment]
You can do this by setting up a custom transformer config in your kustomization.

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
vars:
- fieldref:
    fieldPath: data.CUSTOMER_ID
  name: CUSTOMER_ID
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: source-vars
configurations:
- config.yaml
```

**config.yaml**
```yaml
varReference:
- path: metadata/name
  kind: Namespace
```

**ns.yaml**
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: $(CUSTOMER_ID)
```

```
$ CUSTOMER_ID=cust1234
$ kustomize edit add configmap source-vars --from-literal CUSTOMER_ID="$CUSTOMER_ID"
$ kustomize edit set namespace "$CUSTOMER_ID"
$ kustomize build .
apiVersion: v1
kind: Namespace
metadata:
  name: cust1234
---
apiVersion: v1
data:
  CUSTOMER_ID: "cust1234"
kind: ConfigMap
metadata:
  name: source-vars-k59btk8td4
  namespace: cust1234
```

**Comment by Jeffwan** [comment]
Is there a way to use `namespace` in Kustomization directly? 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xxx
```

**Comment by pckhoi** [comment]
Here's how I do it using [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/)
```yaml
# kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - deployment.yml
replacements:
  - source:
      kind: Deployment
      name: doctr
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
```
```yaml
# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctr
spec:
  ...
```
```yaml
# namespace.yml
apiVersion: v1
kind: Namespace
metadata:
  name: any-name
```
When you want to set the namespace, just... set the namespace:
```bash
$ kustomize edit set namespace abcde
$ kustomize build .
apiVersion: v1
kind: Namespace
metadata:
  name: abcde
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctr
  namespace: abcde
spec:
  ...
```
