### ISSUE TITLE
Patch service name in Ingress object

### ISSUE THREAD

**Issue by mr-karan** [kubernetes-sigs/kustomize#1478]
I've an Ingress object which looks like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-private
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: my-service-name
          servicePort: 3333
        path: /*
---
```

Since I've a `kustomization.yaml` which has defined a suffix for all resources
```
nameSuffix: -dev
```
The corresponding service object gets created with that suffix name which doesn't match the ingress object

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service
  name: my-service-name-dev
---
```

**What's happening**:  Ingress has a service name, which doesn't match the actual service name

**What should happen**: Ingress object must be patched with the correct service name

**Comment by jbrette** [comment]
@mr-karan Please have a look at the following environment [issue_1478](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1478)

Could you indicate what you are doing differently. At a glance, kustomize seems to be working as expected

```bash
$HOME/bin/kustomize.3.1.0 build app
```

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service
  name: my-service-name-dev
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-private-dev
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: my-service-name-dev
          servicePort: 3333
        path: /*
```
