### ISSUE TITLE
kustomize doesn't transform claimName for PersistentVolumeClaims

### ISSUE THREAD

**Issue by ryane** [kubernetes-sigs/kustomize#149]
If I have a pod spec that defines a volume from a PersistentVolumeClaim, kustomize will not transform the name when a `namePrefix` is set. Here is an example.

test.yaml:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  labels:
    app: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-test
  labels:
    app: pvc-test
spec:
  selector:
    matchLabels:
      app: pvc-test
  template:
    metadata:
      labels:
        app: pvc-test
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: pvc-test
```

kustomization.yaml:

```yaml
namePrefix: my-
resources:
- test.yaml
```

You can see the name of the PersistentVolumeClaim is prefixed with "my-":

```
$ kustomize build . | grep -C 4 PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvc-test
  name: my-pvc-test
```

However, the `claimName` in the deployment does not reference the prefixed name:

```
$ kustomize build . | grep -C 3 claimName
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: pvc-test
```

If you try to apply the kustomized manifests, your pod will be stuck in the pending state as it waits for a pvc that will never exist:

```
$ kubectl get pod -lapp=pvc-test
NAME                           READY     STATUS    RESTARTS   AGE
my-pvc-test-55659498c4-kx857   0/1       Pending   0          7m

$ kubectl describe pod -lapp=pvc-test | grep -A 4 Events
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  54s (x26 over 7m)  default-scheduler  persistentvolumeclaim "pvc-test" not found (repeated 4 times)
```
