### ISSUE TITLE
Changing 'imagePullPolicy' of all containers in all deployments

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/kustomize#1493]
originally asked here https://github.com/kubernetes-sigs/kustomize/issues/412 - but the question is still left unanswered:

following kustomization
```
patches:
  - path: imagepullpolicytoalways.yaml
    target:
      kind: Deployment
```
and
```
- op: replace
  path: "/spec/template/spec/containers/0/imagePullPolicy"
  value: Always
```

changes/adds the imagePullPolicy to *first* container, but how to set it to all containers? using `*`does not work.

**Comment by matti** [comment]
And I can't use AlwaysPullImages AdmissionController in GKE

**Comment by matti** [comment]
```
- op: replace
  path: "/spec/template/spec/containers[]/imagePullPolicy"
  value: Always
```

results in `doc is missing path: /spec/template/spec/containers[]/imagePullPolicy: missing value`

**Comment by matti** [comment]
workaround:
```
patches:
  - path: jsonpatches/first-container-pull-policy-to-always.yaml
    target:
      kind: Deployment
  - path: jsonpatches/second-container-pull-policy-to-always.yaml
    target:
      kind: Deployment
      name: this|that
```

**Comment by antoninbas** [comment]
Any thoughts on adding this to the default `images` transformer?

```
images:
  - name: postgres
    newName: my-registry/my-postgres
    newTag: v1
    newPullPolicy: IfNotPresent
```

I am aware that this is not quite the ask of this issue...

**Comment by jbmcfarlin31** [comment]
> workaround:
> 
> ```
> patches:
>   - path: jsonpatches/first-container-pull-policy-to-always.yaml
>     target:
>       kind: Deployment
>   - path: jsonpatches/second-container-pull-policy-to-always.yaml
>     target:
>       kind: Deployment
>       name: this|that
> ```

@matti , what does your patch yaml file look like for setting the `imagePullPolicy`? I am trying to set the `imagePullPolicy` values for all rendered yaml generated from `kompose` (which translates docker-compose into kubernetes yaml).

**Comment by matti** [comment]
sorry I kinda stopped using kustomize - it is too hard or impossible to have things like this.

**Comment by jbmcfarlin31** [comment]
@matti I feel you. I cannot seem to get `imagePullPolicy` to work, at all. I either end up replacing the whole container spec or something else... thinking I might have to implement by own patching utility..

**Comment by antoninbas** [comment]
@jbmcfarlin31 

You have to apply a patch like this one:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: antrea-agent
spec:
  template:
    spec:
      containers:
        - name: antrea-agent
          imagePullPolicy: IfNotPresent
        - name: antrea-ovs
          imagePullPolicy: IfNotPresent
      initContainers:
        - name: install-cni
          imagePullPolicy: IfNotPresent
```
It is less than ideal. There should be a way to change the imagePullPolicy with the `images` transformer.

**Comment by jbmcfarlin31** [comment]
@antoninbas do you need to have a specific patch file like that? What I mean by specific is like exact name mappings and so on?

We basically take a compose file, convert with kompose, and then want to apply kustomize patches to that rendered yaml file. The compose files we are converting aren't necessarily stuff we own, so we won't know the names of services and so on.

We ideally want something just like `deployment_patch.yaml`:
```yaml
kind: Deployment
spec:
  templates:
    spec:
       containers:
          imagePullPolicy: Always
```
That is then applied to all future `Deployments` generated by kompose.

**Comment by antoninbas** [comment]
I tried that a while back but it didn't work for me. I had to enumerate all containers by name.

For your use case, it would be great if @matti's patch worked:
```
- op: replace
  path: "/spec/template/spec/containers/*/imagePullPolicy"
  value: Always
```
but the wildcard `*` does not work here. It is not part of the JSON patch RFC (https://tools.ietf.org/html/rfc6902) as far as I can tell, so that explains why kustomize does not support it.

It would be great if one of the kustomize developers could comment on this issue though, in case there is an alternative solution.

**Comment by jbmcfarlin31** [comment]
@antoninbas man that was not the news I was hoping for lol. So as it sits currently, without the developers commenting, there currently is no way to patch through kustomize or potentially through the `kubectl patch ...` command all `imagePullPolicy` fields within deployments?

**Comment by antoninbas** [comment]
Not that I know of. But I have been using kustomize very lightly so I am definitely not an expert.

**Comment by pre** [comment]
You can deploy an adminission controller webhook which mutates all the objects live on the cluster and ensures imagePullPolicy is what you need 😅 🌮

**Comment by TekTimmy** [comment]
We are using self build docker images in Minikube, therefore the _ImagePullPolicy_ should be _Never_ for local development but _Always_ for all other environments. I did not expect this to be so hard with kustomize :cry:

**Comment by TekTimmy** [comment]
Made it working with inline _patchesStrategicMerge_...
My cronjob YML:
`
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: base-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: "cronjob:latest"
              imagePullPolicy: "Never"
              args: ['python3 cronjob.py']
`

My _kustomization.yml_ (important is providing the containers __name__):
`
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob
patchesStrategicMerge:
  - |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: base-cronjob
    spec:
      schedule: "*/2 * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: base-cronjob
                  image: "cronjob:dev"
                  imagePullPolicy: "Always"
`

**Comment by agascon** [comment]
> sorry I kinda stopped using kustomize - it is too hard or impossible to have things like this.

Hi @matti, might I ask which other tool you moved for this kind of templating?

I'm trying similar templating like in this issue and feeling exactly the same, that either it's not possible or very diffcult.  I think there should be another way.

Thanks!

**Comment by matti** [comment]
helm. Helm is the clear winner of these tools.

**Comment by bygui86** [comment]
Helm is a great tool, but write and maintain a chart is really a pain!
Go-templating and the shitty yaml indentation are a deadly mix :(

**Comment by matti** [comment]
I know. That's why I tried kustomize (and kpt), but issues like these just wont work with declarative approach. Just give another try for helm, it also handles removal of resources nicely (have you tried what happens when you remove a kustomize resouce? you need to delete that manually)

**Comment by bygui86** [comment]
There is already an issue about resources removal, so I think that it will be fixed soon.

I think that Kustomize offers lots of really important features and the community will add more and more within next months. Features that are completely compliant with declarative approach.

@matti can you make an example of declarative approach when Kustomize does not work?

**Comment by matti** [comment]
This issue? And also this "closed" issue here: https://github.com/kubernetes-sigs/kustomize/issues/168#issuecomment-618387782

**Comment by bygui86** [comment]
Sorry maybe I did the wrong question.
Why do you think this issue is preventing Kustomize to be a good fit for a declarative approach?

**Comment by matti** [comment]
I think that there is nothing wrong with kustomize, but rather wrong with the declarative approach itself. In theory it is nice that your yamls are in git and they don't have side effects. And it works for many cases.

Then you need to add something to an array key, or all arrray keys and potentially all array keys except one and it becames a massive jsonPatch/strategicMergePatch party.

For more concrete example see this: https://github.com/kubernetes-sigs/kustomize/issues/347 - because of this I have massive amount of duplication.

And kustomize overlays are great for adding, but how do you remove stuff? Often you start structuring your kustomization yamls files and write bunch of extra kustomization resources and have a lot of directories and kustomization.yamls all over and then you realize that something can not be done, which again in "helm" would be a simple variable / condition.

Eventually everything becomes some sort of Generator in kustomize where declarative approach fails and this just becomes super difficult to read.

Helm, or some other template based tool, does not provide the same pure properties, but atleast you never get stuck in issues like this.

As a long time user of Terraform, it has the same kind of issues and now with latest "generators" like support for count in modules (issue open for yeeeaars) it might have enough ways to mitigate the downsides of declarative approach (basically you also ended up copy/pasting/duplicating your terraform files a lot - just like in the kustomize&ingress issue above)

So yes, when given enough time kustomize might have enough generators/patching/stuff, but while waiting for it Helm is not slowing you down.

**Comment by blaggacao** [comment]
@matti I think what you're really looking for is jsonnet, eg through `kubecfg`.

**Comment by agascon** [comment]
Thanks for the answers, definitely there is a lot of valuable information in this thread.

What I'm trying to achieve is for example having a base template which is later decorated or enhanced with a number of overlays or transformations.  For example if I define a deployment for a Kafka consumer, have an overlay which automatically would add default Kafka required settings on that deployment.

For simple stuff, Kustomize can support this, but if you need some more complex stuff as already mentioned quickly you will end building very complex templates or even worst hitting some dead end way.

Helm can support this, but for sure won't be so elegant as this base + overlays approach.  In the end is another language and in some cases only the templating is needed, using helm could be overkill.

These days reading about this, I saw some posts proposing using any standard language to do the templating, maybe using go or python or even javascript, handling json internally and finally producing the yaml manifest.  What do you think about that?

PD: @blaggacao jsonnet looks promising I'll check for sure.

**Comment by bygui86** [comment]
I think that @agascon  is right: Kustomize is the best for easy and medium-complex stuffs, but for complex to really complex others is not the best.
On the other hand we have Helm and Jsonnet: powerful but putting another language as a wrapper around yaml files.
Honestly I don't like Helm go templating and I don't like the idea of learning another language just to maintain a bunch of yaml files. What can be realized with Jsonnet, can be done as well (maybe even better) with a language using the Kubernetes client: golang, python, even javascript.
So rather than maintain a new language (Jsonnet), I prefer to use a well known one (in my case golang).
This way I can report even a bigger win: using something I already know to deal with less yaml :P

**Comment by matti** [comment]
I don't think jsonnet is way to go, feels too low level.

What about using Terraform - Before kustomize I used terraform kubernetes provider a lot. Now with terrraform 0.13 most of the classic terraform problems are gone. 

For example this issue would be super simple to solve with terraform. Also writing modules (now when modules finally support count) that provide re-usability and less lines.

**Comment by matti** [comment]
> Kustomize is the best for easy and medium-complex stuffs

I wouldn't way that this is true: you can do extremely complex stuff with kustomize, but then you hit these kind of hard issues that just can not be done with kustomize even if they are "easy" or "medium"

The problem with kustomize is that because you can not express some things at all (without massive amount of repetition), but you don't know those issues beforehand, it is just safer to use something that has the expressiveness like helm, pulumi, terraform etc.

**Comment by blaggacao** [comment]
Jsonnet is lazily and hermetically evaluated, similar to nix. Those are handy features for configuration management. The learningcurve is unhandy. If we rule out the bias of knowledge, ceteris paribus a purely functional, lazy evaluated language paradigm has its good amount of aces under the sleeve.

Yet bias of knowledge is a real thing, most of the time.

Had jsonnet/nix's paradigms be applied to terraform, problems would not have been there - by design as opposed to "by workaround/fix".

**Comment by jamiechapmanbrn** [comment]
We just got hit by this one. Would be great if there were a convenient way to set imagePullPolicy per image or a working multi-object patch.

**Comment by Shell32-Natsu** [comment]
The original problem in the issue is because of the limitation of JSON patch ([RFC 6902](https://tools.ietf.org/html/rfc6902)). The path cannot express "all items in array".

What I can suggest is creating a customize [plugin](https://kubernetes-sigs.github.io/kustomize/guides/plugins/) to modify the resources.

**Comment by karolistamutis** [comment]
Any updates on this? Struggling as well

**Comment by pickfire** [comment]
Looks like it is not updated, I guess I need to write 10 patches for all the different components. Maybe json patches since it is easier to handle for situation like these. Using plugin seemed troublesome, need to define environment variables and such. Since all the deployments / daemonsets only have one container and golang likes boilerplates, so I see no issue adding boilerplates here.

`kustomize.yaml`
```yaml
...
patchesJson6902:
- target: &gvk 
    group: apps
    version: v1
    kind: Deployment
    name: a
  path: image_pull_policy_never.yaml
- target:   
    <<: *gvk 
    name: o
  path: image_pull_policy_never.yaml
- target:
    <<: *gvk
    name: e
  path: image_pull_policy_never.yaml
- target:  
    <<: *gvk 
    kind: DaemonSet
    name: u
  path: image_pull_policy_never.yaml
- target:
    <<: *gvk
    name: i
  path: image_pull_policy_never.yaml
- target:
    <<: *gvk
    name: d
  path: image_pull_policy_never.yaml
- target:
    <<: *gvk
    name: h
  path: image_pull_policy_never.yaml
```

`image_pull_policy_never.yaml`
```yaml
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Never
```

Either way, I wish there is a transformer to do this, but for part of the images but not all since we have some external dependencies and easier to just use them.

**Comment by ringerc** [comment]
Pretty surprised to find this limitation. It's explained by the fact that a json patch specifies paths as "JSON Pointers"  http://jsonpatch.com/#json-pointer which are specific identifiers for a single document-element. It is not JSONPath, there are no wildcards and there is no pattern matching.

I guess the correct answer is probably to write a custom kustomize transformer. I'm very surprised to see the need for that for a task that seems likely to be as commonplace and basic as this though.

**Comment by ringerc** [comment]
See also https://github.com/kubernetes-sigs/kustomize/issues/720

**Comment by cmeury** [comment]
/remove-lifecycle rotten

Just got hit by this as well, not for images, but for removing a bunch of keys from a list in a single manifest. I was frantically trying to understand why the asterisk is not supported, until I stumbled across this thread.

**Comment by matti** [comment]
just use sed and/or envsubst on kustomize yaml before apply

this will never be fixed in kustomize, because kustomize is designed to be promising, but painful.

**Comment by blachniet** [comment]
I had the same need and solved it by creating a plugin: [`PullPolicyTransformer`](https://github.com/blachniet/kustomize-plugins#pullpolicytransformer). There's usage instructions and an example in the repository: <https://github.com/blachniet/kustomize-plugins>.

It's packaged as a [Containerized KRM Function](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/containerized_krm_functions/), which is an **alpha** feature at the time of this writing (see [Plugin feature status](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#plugin-feature-status)).

**Comment by Vanderscycle** [comment]
/remove-lifecycle rotten

@antoninbas feature would be amazing. I am sure it can be applied elsewhere too.

**Comment by marcuslund** [comment]
This can sort of be done with raw Kustomize using [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) since it supports wildcard fieldPaths.

The caveat is that your deployments/containers need to have the _imagePullPolicy_ already specified. 

There is a "create=true" option if the value is missing but you cannot use it when using wildcards to select all containers.

`Error: cannot support create option in a multi-value target`

**Comment by rkdrnf** [comment]
Instead of listing every target deployment in `patches`, specifying targets using `labelSelector` may resolve some problems.

```
patches:
  - path: image-pull-policy.patch.yml
    target:
      labelSelector: "image=my-image"
```

**Comment by moatorres** [comment]
I think that should work, no? 🤔

```
patches:
  - target:
      kind: Deployment
      name: my-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
```

**Comment by joebowbeer** [comment]
@moatorres as stated in the description with respect to /0/

> changes/adds the imagePullPolicy to first container, but how to set it to all containers?

**Comment by marculsi** [comment]
They fixed create=true for Wildcard replacements that I mentioned earlier so if anyone is still looking for this here is an example.

Not sure which version it got fixed in. Im using latest Kustomize(5.1.1+) but it should be in some earlier versions.


**kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
- name: replacement-config
  options:
    disableNameSuffixHash: true
  literals:
    - imagePullPolicy=Always

resources:
  - "deployment.yaml"


replacements:
- source:
    kind: ConfigMap
    name: replacement-config
    fieldPath: data.imagePullPolicy
  targets:
  - select:
      kind: Deployment
      name: nginx-deployment
    options:
      create: true
    fieldPaths:
    - spec.template.spec.containers.*.imagePullPolicy

```
**deployment.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: nginx2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
````
