### ISSUE TITLE
Unknown fields error after `kustomize edit set image`

### ISSUE THREAD

**Issue by ivanliu1989** [kubernetes-sigs/kustomize#1499]
Getting following errors after `kustomize edit set image`
<img width="1581" alt="Screen Shot 2019-09-04 at 4 25 20 pm" src="https://user-images.githubusercontent.com/8368049/64257522-dba3bc00-cf68-11e9-9608-170b9dd95099.png">
It happens to any files with `configMapGenerator` and `fieldpath`

Example:
Before
```configMapGenerator:
- name: workflow-controller-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: executorImage
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.executorImage
```

After
```configMapGenerator:
- envs:
  - params.env
  name: workflow-controller-parameters
generatorOptions:
  disableNameSuffixHash: true
vars:
- fieldref:
    fieldPath: data.executorImage
  name: executorImage
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: workflow-controller-parameters
```

**Comment by jbrette** [comment]
@ivanliu1989 This does not look like a bug. 
your original file seems to be missing the first line. If you add it back like this:
```yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: workflow-controller-parameters
  env: params.env
vars:
- name: executorImage
  objref:
    kind: ConfigMap
    name: workflow-controller-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.executorImage
```
then

```bash
kustomize build .
```

works

```yaml
2019/09/06 13:22:57 well-defined vars that were never replaced: executorImage
apiVersion: v1
data:
  executorImage: 1.2.3
kind: ConfigMap
metadata:
  name: workflow-controller-parameters
```

then if you use edit image:

```bash
kustomize edit set image node:8.15.0
```

kustomization.yaml looks like this (not the configmap generator is updated to support more than one file)
```yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - params.env
  name: workflow-controller-parameters
vars:
- fieldref:
    fieldPath: data.executorImage
  name: executorImage
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: workflow-controller-parameters
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: node
  newTag: 8.15.0
```

kustomize build still works

```bash
kustomize build .
```

```yaml
apiVersion: v1
data:
  executorImage: 1.2.3
kind: ConfigMap
metadata:
  name: workflow-controller-parameters
```
