### ISSUE TITLE
Adding individual labels to configMap

### ISSUE THREAD

**Issue by nbn** [kubernetes-sigs/kustomize#1501]
I have come cross a situation where I would like to generate the configmap using kustomize, but I need to add an additional label to some individual configMaps. They are needed in our case because of cluster-wide management tools need to introspect certain configMaps, which are designated with specific labels.

I cannot find a simple solution (commonLabel would be too much), but am currently resolving it by keeping those configMaps in yaml.

```
configMapGenerator:
- name: my-config-map
  envs:
  - some.properties
  labels:
  - howto: do-this
```

Any suggestions or is this a feature request.

**Comment by jbrette** [comment]
Don't think this is a bug nor a feature request. Have a look at a mix of generator and patches [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1501). This shows you how to add individual labels.

This is the output of the kustomize build command
```yaml
apiVersion: v1
data:
  a: "0"
kind: ConfigMap
metadata:
  labels:
    apps: a
  name: a-config-map-26kgmbk2md
---
apiVersion: v1
data:
  b: "1"
kind: ConfigMap
metadata:
  labels:
    apps: b
  name: b-config-map-gh56k7ggb5
```

**Comment by benjamin-bergia** [comment]
Having the same issue here.
I generate a bunch of configmaps (~10) and I just want to add a labels on each. There is no value in the generator if I need to make 10 distinct json patches to add a label.

Can we have a feature request for this? The current CM generators are very powerful and concise but are pointless if adding metadata requires patches.

**Comment by adrian-gierakowski** [comment]
can we please reopen this?

**Comment by dkuroczk** [comment]
Since v3.5.5 it is already available by an options field [LINK](https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_configmapgenerator)


```
- name: dashboards
  files:
  - mydashboard.json
  options:
    annotations:
      dashboard: "1"
    labels:
      app.kubernetes.io/name: "app1"
```
