### ISSUE TITLE
kustomize can't load builtin transformers when leveraging 'transformers:' entry

### ISSUE THREAD

**Issue by jbrette** [kubernetes-sigs/kustomize#1508]
This example is a reproduction of automatic feature test: `customconfigofbuiltinplugin_test.go` but is run from the command line as a normal user: 

kustomize does not seem to be able to locate the plugin and looks for it XDG_CONFIG_HOME

To reproduce:

```bash
DEMO_HOME=$(mktemp -d)
mkdir -p ${DEMO_HOME}
cat <<'EOF' >${DEMO_HOME}/kustomization.yaml
resources:
- deployment.yaml
- role.yaml
- service.yaml
transformers:
- prefixer.yaml
EOF
cat <<'EOF' >${DEMO_HOME}/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myDeployment
spec:
  template:
    metadata:
      labels:
        backend: awesome
    spec:
      containers:
      - name: whatever
        image: whatever
EOF
cat <<'EOF' >${DEMO_HOME}/prefixer.yaml
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: customPrefixer
prefix: zzz-
fieldSpecs:
- kind: Deployment
  path: metadata/name
- kind: Service
  path: metadata/name
EOF
cat <<'EOF' >${DEMO_HOME}/role.yaml
apiVersion: v1
kind: Role
metadata:
  name: myRole
EOF
cat <<'EOF' >${DEMO_HOME}/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myService
EOF
```

```bash
$HOME/bin/kustomize.3.1.0 version

Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}
```

```bash
$HOME/bin/kustomize.3.1.0 build $DEMO_HOME --enable_alpha_plugins
Error: plugin 

xxxx/.config/kustomize/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer fails to load: plugin: not implemented
```

**Comment by jbrette** [comment]
when running against the latest version of kustomize:

```
$HOME/bin/kustomize build $DEMO_HOME --enable_alpha_plugins
Error: plugin /home/xxx/.config/kustomize/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer fails to load: plugin.Open("/home/xxx/.config/kustomize/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.so"): realpath failed
```
After rebuilding kustomize from master (make install) and building and installing the PrefixSuffixTransformer.go (GOPATH=$myGoPath GO111MODULE=on go build -buildmode plugin -o ${HOME}/.config/kustomize/${i}.so ./$i.go), it seems to be behaving properly

```bash
$HOME/bin/kustomize build $DEMO_HOME --enable_alpha_plugins
```

```yaml
apiVersion: v1
kind: Role
metadata:
  name: myRole
---
apiVersion: v1
kind: Service
metadata:
  name: zzz-myService
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zzz-myDeployment
spec:
  template:
    metadata:
      labels:
        backend: awesome
    spec:
      containers:
      - image: whatever
        name: whatever
```
