### ISSUE TITLE
Provide simple way of sharing transformers configuration.

### ISSUE THREAD

**Issue by jbrette** [kubernetes-sigs/kustomize#1509]
During the investigation of the best option to allow a user simple adjust the default configuration of builtin transformers, the idea was proposed to leverage kustomize transformers in kustomization.yaml.

The example here is adding a label "env: canary" in one kustomize context, and "env: production" in the other.

The current issue is that the commonslabeltransformer.yaml is basically copy/pasted from the canary to production and only the "labels" section changes.

Full example is available [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0519_b)

production kustomization.yaml look so:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

transformers:
- ./kustomizeconfig/imagetransformer.yaml
- ./kustomizeconfig/namesuffixtransformer.yaml
- ./kustomizeconfig/commonlabelstransformer.yaml
- ./kustomizeconfig/patchstrategicmergetransformer.yaml
```

The commonlabelstransformer.yaml for the production environment looks this way.

```yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labeltransformer
labels:
  env: production
fieldSpecs:
- path: metadata/labels
  create: true
  kind: Service
- path: spec/selector
  create: true
  kind: Service
- path: metadata/labels
  create: true
  kind: Deployment
- path: spec/selector/matchLabels
  create: true
  kind: Deployment
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
```

On the canary side:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

transformers:
- ./kustomizeconfig/imagetransformer.yaml
- ./kustomizeconfig/namesuffixtransformer.yaml
- ./kustomizeconfig/commonlabelstransformer.yaml
- ./kustomizeconfig/patchstrategicmergetransformer.yaml
```

```yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labeltransformer
labels:
  env: canary
fieldSpecs:
- path: metadata/labels
  create: true
  kind: Service
- path: spec/selector
  create: true
  kind: Service
- path: metadata/labels
  create: true
  kind: Deployment
- path: spec/selector/matchLabels
  create: true
  kind: Deployment
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
```
