### ISSUE TITLE
[Question] Override a label key and value

### ISSUE THREAD

**Issue by mr-karan** [kubernetes-sigs/kustomize#1514]
Is it possible to override a single label key/value in `Deployment` / `Service` / `Configmap` together?

Consider I have a deployment with: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  template:
    metadata:
      labels:
        service: nginx
```

Can I simply apply a patch which updates the label `service=nginx` to `tier=proxy` and propagates the changes in `selector/matchLabels` and `template/metadata/labels` in Deployment and also wherever it is referred in `Service` ?

This would really come handy for remote targets, where you would want to "kustomize" certain properties of the remote base. For example, I'd like to update the labels in this remote nginx [base](https://github.com/mr-karan/kustomize-bases/tree/master/nginx/) to my custom labels.
