### ISSUE TITLE
patchesStrategicMerge on clusterrole through overlays is not working 

### ISSUE THREAD

**Issue by SatwikBhandiwad** [kubernetes-sigs/kustomize#1523]
This how the directory structure looks like:
```
.
├── base
│   ├── cluster-role.yaml
│   └── kustomization.yaml
├── kustomization.yaml
└── overlays
    └── psp
        ├── cluster-role.yaml
        ├── kustomization.yaml

```
contents of **base/cluster-role.yaml**:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: argo
  name: argo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - update
  - patch
```

contents of **base/kustomization.yaml**:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role.yaml
commonLabels:
  kustomize.component: argo
```

Overlay is created to patch the cluster role.

contents of **overlays/psp/cluster-role.yaml** :

```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: argo
  name: argo
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use

```

contents of **overlays/psp/kustomization.yaml**:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- cluster-role.yaml

```

When **patchesStrategicMerge** is applied, the output received is as below:

```
[root@cluster01-control-host03 argo]# kustomize build overlays/psp/
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: argo
    kustomize.component: argo
  name: argo
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

Expected output is both the files should be merged as below:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: argo
  name: argo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

Is this expected behaviour?
How can this be achieved?

**Comment by jbrette** [comment]
@SatwikBhandiwad This is the expected behavior. StrategicMergePatch relies, especially when merging list, on "natural keys" added as annotations to the go code. When you merge the container list of two deployments, SMP will rely on the

```yaml
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      - name: anothernginx
        image: nginx:1.7.9
        ports:
        - containerPort: 81
```

In the case of the `rules` of the ClusterRoleBinding, there is not such key, therefore SMP will replace the entire list. You should use json patch here, and specify where you want the new rule to be added.

**Comment by SatwikBhandiwad** [comment]
Thank you @jbrette for the quick response.
I tried with json patch and it worked. 

contents of **psp/kustomization.yaml** after using patchesJson6902:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1beta1
    kind: ClusterRole
    name: argo
  path: patch.yaml

```

contents of **psp/patch.yaml**:

```
- op: add
  path: /rules/0
  value:
    apiGroups:
      - extensions
    resourceNames:
      - privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use
```
