### ISSUE TITLE
Issue patching in multiple volumes via patchJSON6902

### ISSUE THREAD

**Issue by jstralko** [kubernetes-sigs/kustomize#1527]
I'm trying to patch in (patchJSON6902) multiple volumeMounts to a base kustomization. However, when I patch in more than one volumeMounts I get errors. Here's my configuration:

kustomization.yaml
```yaml
commonLabels:
  app: my-app

imageTags:
  - name: my-app
    newName: localhost/my-app
    newTag: latest

bases:
- app

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-app
  path: create_volume_one.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-app
  path: create_volume_two.yaml
```
app/kustomization.yaml:
```yaml
resources:
- deployment.yaml
```

app/development.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-app
        image: my-app
        ports:
        - containerPort: 8080
```

create_volume_one.yaml:
```yaml
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: volumeOne
    mountPath: /data/one
```

create_volume_two.yaml:
```yaml
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: volumeTwo
    mountPath: /data/two
```

But I get the following errors:
```bash
$> kubectl kustomize .
Error: found conflict between different patches
&resource.Resource{Kunstructured:(*kunstruct.UnstructAdapter)(0xc000010058), options:(*types.GenArgs)(0xc00038eb00)} doesn't deep equal &resource.Resource{Kunstructured:(*kunstruct.UnstructAdapter)(0xc0000c6038), options:(*types.GenArgs)(0xc00038eb00)}


Examples:
  # Use the current working directory
  kubectl kustomize .

  # Use some shared configuration directory
  kubectl kustomize /home/configuration/production

  # Use a URL
  kubectl kustomize github.com/kubernetes-sigs/kustomize.git/examples/helloWorld?ref=v1.0.6

Usage:
  kubectl kustomize <dir> [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

found conflict between different patches
&resource.Resource{Kunstructured:(*kunstruct.UnstructAdapter)(0xc000010058), options:(*types.GenArgs)(0xc00038eb00)} doesn't deep equal &resource.Resource{Kunstructured:(*kunstruct.UnstructAdapter)(0xc0000c6038), options:(*types.GenArgs)(0xc00038eb00)}
```
Here is the version of kustomize (kubectl) i am running:
```bash
$> kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
```
I tried various different things and keep getting the same errors.  Is this something that kustomize supports or am I just not understanding how to patch in volumeMounts?

Thanks,
