### ISSUE TITLE
Projected configmap not interpreted

### ISSUE THREAD

**Issue by george-angel** [kubernetes-sigs/kustomize#153]
My base configuration contains:

```
...
      volumes:
        - name: prometheus-config-shared
          emptyDir: {}
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-alerts
          projected:
            sources:
              - configMap:
                  name: prometheus-alerts
...
```

kustomization.yaml:

```
...
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus-config.yaml
  - name: prometheus-alerts
    files:
      - system-alerts.yaml
```

`kustomize build` produces:

```
      volumes:
      - emptyDir: {}
        name: prometheus-config-shared
      - configMap:
          name: prometheus-config-ght7d485tk
        name: prometheus-config
      - name: prometheus-alerts
        projected:
          sources:
          - configMap:
              name: prometheus-alerts
```

And so my deployment fails:

```
MountVolume.SetUp failed for volume "prometheus-alerts" : configmaps "prometheus-alerts" not found
```

```
NAME                                     DATA      AGE
configmap/prometheus-alerts-gtkkhc6md2   1         2d
```

**Comment by robbyt** [comment]
I have the same issue, but I'm not even using the `configMapGenerator`.  Hashes are not being appended onto the configMap names under the projected configMap volume.

```
      volumes:
      - name: nginx-config
        projected:
          sources:
          - configMap:
              name: nginx-v1
          - configMap:
              name: nginx-main-v1
          - configMap:
              name: nginx-public-default-redirect-v1
          - configMap:
              name: nginx-members-v1
```
