### ISSUE TITLE
Var reference does not work in volumes

### ISSUE THREAD

**Issue by phillebaba** [kubernetes-sigs/kustomize#1540]
Var reference does not work when used in volumes.
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: $(NFS_SERVER)
            - name: NFS_PATH
              value: /var/nfs
      volumes:
      - name: nfs-client-root
        nfs:
          server: $(NFS_SERVER)
          path: /var/nfs
```

When kustomizing this manifest with a varible that references a Service ClusterIP the following is outputed.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: fuseim.pri/ifs
        - name: NFS_SERVER
          value: 10.43.118.159
        - name: NFS_PATH
          value: /var/nfs
        image: quay.io/external_storage/nfs-client-provisioner-arm:latest
        name: nfs-client-provisioner
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-client-root
      serviceAccountName: nfs-client-provisioner
      volumes:
      - name: nfs-client-root
        nfs:
          path: /var/nfs
          server: $(NFS_SERVER)
```

I would expect the `$(NFS_SERVER)` in the volume to also be replaced with the ClusterIP. I need this as there are currently issues with using the service dns to resolve the ip of a nfs server running in the same cluster.

**Comment by jbrette** [comment]
@phillebaba You can solve that the complicated way by changing the variable reference configuration.
Have a look [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1540_b)
and especially at the varreference.yaml kustomize config file

```yaml
varReference:
- path: spec/template/spec/volumes[]/nfs
  kind: Deployment
```

or you can do it the easy way leveraging this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1217). Check how much more simple the [configuration is](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1540).
No need for varReference file nor entry in the kustomization.yaml.
The only thing you need to do is to have an variable name like this:
$(<kind>.<metadataname>.<fieldpath>)

/cc @monopole @Liujingfang1 @ian-howell
