### ISSUE TITLE
Nulling namespace of ClusterRole subject ServiceAccount

### ISSUE THREAD

**Issue by Devin-Holland** [kubernetes-sigs/kustomize#1545]
Kustomize 3.0.3

I'm trying to apply a ClusterRole and a ClusterRoleBinding for a service account for the kubernetes  dashboard.  The service account is created outside of our kustomize but I'm trying to add the ClusterRole to the service account. I also have a policy in the namespace. I have the following specifications

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-dashboard
  apiGroup: rbac.authorization.k8s.io
```
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: k8s-dashboard
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - 'list'
  - 'get'
  - 'watch'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - 'list'
  - 'get'
  - 'watch'
```
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: kube-system
spec:
  peers:
    - mtls:
        mode: PERMISSIVE
```
And my kustomization is:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mtls.yaml
- cluster-role-binding.yaml
- cluster-role.yaml

namespace: kube-system
```

When I run kustomize build . my ClusterRoleBinding comes out like this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: null
```
It does not have a namespace which makes sense because it's a ClusterRoleBinding but the namespace of the subject ServiceAccount is nulled out. This didn't seem right to me so I removed the namespace from the policy: 
```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
spec:
  peers:
    - mtls:
        mode: PERMISSIVE
```
And now my ClusterRoleBinding is output as:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
```
Now the namespace of the ServiceAccount subject is not nulled out. This does not seem like intended functionality to me but maybe I'm just missing something here. 

It appears as though at any point in the output of the kustomization one of the files has the namespace specified in the yaml file (not just using namespace in the kustomization file) then the service account's subject namespace will become null.
