### ISSUE TITLE
Kustomize build unable to find objects for hash transformation in annotations

### ISSUE THREAD

**Issue by robbyt** [kubernetes-sigs/kustomize#155]
Semi-related to #153 - we use Traefik as an ingress controller, and one of it's features is to enable basic auth for an ingress rule.

An example of using this is below. The `auth-secret` (which becomes the password) must be a secret object in the same namespace. However, when using this with Kustomize, the hashed name of the secret is not interpolated, because Kustomize obviously doesn't know about this annotation.

My example Traefik ingress:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: admin-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: admin
spec:
  rules:
  - host: admin.myhost.com
    http:
      paths:
      - path: /
        backend:
          serviceName: admin
          servicePort: admin-http
```
