### ISSUE TITLE
Patch replacing yml instead of merge it

### ISSUE THREAD

**Issue by williamthiago** [kubernetes-sigs/kustomize#1551]
kustomize build is removing part of my yaml when I try to change another key (it's a list of hosts)

I have the following structure and files:

```
├── base
│   ├── gateway.yaml
│   └── kustomization.yaml
└── overlays
    └── dev 
        ├── gateway.yaml
        └── kustomization.yaml
```

base/gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "some.host.com"
```

overlays/dev/gateway.yaml
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  servers:
     - hosts:
        - "another.host.com"
```

I wish the result of the build was only change some.host.com to another.host.com, but the output is removing the /spec/servers/port key, making it invalid:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "another.host.com"
```

Is it a bug or this is not supported? There's any workaround (besides JMP)?
