### ISSUE TITLE
Using overlay-provided secrets in a base

### ISSUE THREAD

**Issue by atombender** [kubernetes-sigs/kustomize#1553]
I have a deployment that needs multiple values from a secret. The deployment is in my base, and the secret values are defined in overlays. That's fine.

But the secret doesn't exist in the base, which means that if my deployment has this, it's making an assumption about its name:

```
# In base/deployment.yaml:
env:
- name: SENTRY_DNS
  valueFrom:
    secretKeyRef:
      name: myapp-whatever
      key: sentryDSN
```

Ideally this should be `name: $(SECRET_NAME)`, but that isn't allowed because the secret variable is defined by the overlay. The base cannot have a `secretGenerator` for a secret it doesn't know about.

So my solution is to define the secret in the overlay and inject it using patches:

```
# In overlays/staging/kustomization.yaml:
secretGenerator:
- name: core
  type: Opaque
  envs:
  - secrets.txt

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: core
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SENTRY_DNS
        valueFrom:
          secretKeyRef:
            name: $(SECRET_NAME)
            key: sentryDSN

vars:
- name: SECRET_NAME
  objref:
    kind: Secret
    name: core
    apiVersion: v1
```

~~This works~~, but that means there's much less declaration sharing going on. There's nothing dynamic here. The overlay-specific config data is in `secrets.txt`, but not in the envvars. The above will be identical for each overlay.

Edit: The above _doesn't_ work. `$(SECRET_NAME)` is not expanded after patching.

**Comment by bzub** [comment]
Have you tried just using the name of the secret you generated (`core`) in the deployment?

I tested it out and everything looks good that way. In my case my secret name is (`mysecret`) and you can see the name gets updated in the base deployment.

`$ cat base/deploy.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: test
          image: test
          env:
            - name: SENTRY_DNS
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: key2
```

`$ cat base/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
```

`$ cat overlay/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

secretGenerator:
  - name: mysecret
    literals:
      - key1=value1
      - key2=value2
```

`$ kustomize build overlay`
```yaml
apiVersion: v1
data:
  key1: dmFsdWUx
  key2: dmFsdWUy
kind: Secret
metadata:
  name: mysecret-f4h8tk4kkg
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
        - name: SENTRY_DNS
          valueFrom:
            secretKeyRef:
              key: key2
              name: mysecret-f4h8tk4kkg
        image: test
        name: test
```

**Comment by jbrette** [comment]
You can address your problem two issues:
- Has show above with using variables nor patches, and it works out of the box. Check [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1553_b)
- Following what you had in mind using, by using patch and variable. It is a little more complicated but still works. Check [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1553)

It seems you close that bug.

**Comment by atombender** [comment]
@jbrette Thanks. That alternative solution is complicated and unintuitive. Too many dependency declarations spread out between multiple files.

Where is `varreference` documented? Why can't it be declared inline, without `configurations`? I'm not sure what it does. From what I can see, it _whitelists_ `secretKeyRef.name` so it is allowed to refer to a variable. If that is the case, why is this necessary? I don't have Kustomize built with the PR you mention, since it's not been merged or apparently accepted, so I'd like to understand the mechanics of it.

Where is `configurations` documented? Is it just a way to include YAML fragments from external files? It doesn't appear to be, since `varreference` can't be in `kustomize.yaml`.

If Kustomize is going to compete with Helm (which we currently use; I'm sounding out competitors like Kustomize as possible replacements) Kustomize has to be easier than this. Kustomize should be able to solve something simple like this in a simple, readable way.

---

For the record, the solution offered by @jbrette isn't really acceptable. Obviously it works, but the base would be making an assumption it shouldn't be making, and it would have a dependency on a resource (the secret) which might not even exist. For example, if an overlay sets a name prefix or `generatorOptions: {disableNameSuffixHash: false}`, then the secret name will _not_ be what `base/deployment.yaml` expects. The point of vars, as I understand Kustomize, is to be able to extract dynamic information so you don't have such implicit dependencies, only explicit ones.

**Comment by atombender** [comment]
As an aside, the amount of boilerplate in each "environment" (prod, staging, etc.) is not great. Here's my current `staging/kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

commonLabels:
  environment: staging

namePrefix: myapp-

resources:
- ../../base

generatorOptions:
  labels: {}
  annotations: {}
  disableNameSuffixHash: true

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: core
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: [... some flag ...]
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: [... some flag ...]
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: NODE_ENV
        value: staging
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SENTRY_ENVIRONMENT
        value: staging
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SENTRY_DSN
        valueFrom:
          secretKeyRef:
            name: $(SECRET_NAME)
            key: sentryDSN
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: STRIPE_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: $(SECRET_NAME)
            key: stripeSecretKey
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: MG_API_KEY
        valueFrom:
          secretKeyRef:
            name: $(SECRET_NAME)
            key: mailgunAPIKey
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: $(SECRET_NAME)
            key: postgreSQLPassword

secretGenerator:
- name: core
  type: Opaque
  envs:
  - secrets.txt
  files:
  - serviceaccount-key.json

# The following is boilerplate to allow us to refer to the secret as a variable.
# See https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1553
# and https://github.com/kubernetes-sigs/kustomize/pull/1217.

vars:
- name: SECRET_NAME
  objref:
    kind: Secret
    name: core
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name

configurations:
- ./varreference.yaml
```

With the exception of the namespace, common labels and `_ENV` vars, this will in fact be identical for `production/kustomization.yaml`.

Ideally, I'd move this into `base/kustomization.yaml`, but it doesn't have the secret data. From what I can tell, there's no way for the base to declare a parameter (e.g. secrets) that must be supplied by an overlay.

Of course, some of the secret data is also shared between production and staging. There doesn't seem to mechanism for this, either.

For envvars, with Helm I'd just do this directly in the deployment spec:

```yaml
env:
- name: NODE_ENV
   value: {{.Values.environment}}
```

…and it'd be in _one_ location. It's much more intuitive that this, where each environment has to supply that envvar (which isn't optional), which always has the same name, but a different variable depending on the environment.

**Comment by jcassee** [comment]
@atombender Not sure if I'm making your problem easier, but I find it easiest to reason about Kustomize if I assume bases are also independently usable. Even if just for spinning up a development version on a laptop. This may mean introducing dummy/fake values for this use-case.

In the case, it seems the simplest solution is to use a configMap/SecretGenerator in the base and reference it from the container `envFrom`. Then use a configMap/SecretGenerator in the overlay with `behavior: merge`. You can easily introduce new environment variables this way.

(If this requires an example, let me know.)

Also, feels like your adjustment of the Deployment would be easier with a merge patch instead.

**Comment by atombender** [comment]
@jcassee Thanks, I didn't know about `behavior: merge` since there's almost no documentation for this (that key is not [documented where it should be](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md)).

This solves things much better than the previous answer — that means the base can set up all the secrets, and the overlays just supply the values.

I'm not sure how to do the same for non-secret data. When developing apps, we avoid config files in favour of "12 factor" argument passing, so I need something that works with `args`, without using configmaps. This would otherwise force me to introduce envvars for those args just so that I can pull the data from a configmap, since `args` doesn't support that.

**Comment by jcassee** [comment]
Yeah, `args` is more difficult. Don't really have a generic solution for you there without a specific instance of your problem.

In general, though, I have not seen many Docker images use `args` in the way you describe. Or they allow environment variables instead of them, like you hesitate to introduce. (For example, Python's gunicorn webserver uses a generic `GUNICORN_SOME_VAR=foo` = `--some-var=foo` translation.)

**Comment by jbrette** [comment]
@jcassee @atombender @bzub Our project went through the exact same path of figuring out what should be done with helm and what should be done with kustomize

The first issue we encountered was the complexity of have using variables, which could only  be strings and in very limited number of place. This is why we implemented this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1217).

The second issue we that we could not have a variable that could be a map or list. So we implemented this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1208).

The third issue was that it is really hard to have a mix of local/folder variables and global variables especially when you have a "diamond" import. Let's say you have a common folder declaring resources and variables, which is in turned imported by component1 and component2....and finally your app imports component1 and component2. So we implemented this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1316)

**At the end, we get a lot very interesting features such as beeing able to define values.yaml like in helm, but be able to use the power of kustomize to patch them and render them.**

Have a look at [that example based on your usecase](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1553_c). You have values.yaml like in helm...but you have great features like secret generator, commonlabels, patching from kustomize. 

We are coming back to some important warning in the kustomize README: Basically, not trying to use variables for everything, very often you can do it in a much simpler way using kustomize builtin transformers.

Also, I would advise you to run

```bash
mkdir -p $(GOPATH)/src/sig.k8s.io
cd $(GOPATH)/src/sig.k8s.io
git clone -b allionone https://github.com/keleustes/kustomize.git
cd kustomize
make install
cd examples/issues/issue_1553_c
$(GOPATH)/bin/kustomize build overlay/staging
```

Finally, our project is using a mix of kustomize, helm/armadachart. [Check here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1553_c)

**Comment by atombender** [comment]
@jbrette I agree with the challenges you addressed with those PRs, and I really like the value file idea. Thanks for creating that example! It's more explicit and less boilerplate-encumbered than what's been suggested so far, and makes much more sense to me. 

That said, what are the chances that these PRs will be accepted and merged in the near future? I'm not getting any impression from the discussions what the prognosis is. I don't want to rely on third-party PRs unless I know they are definitely on the path to acceptance. It's too expensive in terms of waste of work. As it stands, Kustomize is still so new and immature that it's hard even to deal with the official version (bugs, lack of documentation, etc.), never mind an uncertain fork.

**Comment by bzub** [comment]
I guess I don't see what's hard or complex about using a secret name in resources that matches the name in the secretGenerator (`core`).

**Comment by atombender** [comment]
@bzub It's not about complexity. It's about being explicit about dependencies, which should only point in a single direction. Overlays should refer to bases, but bases should never refer to overlays.

As @jcassee pointed ut, it's a good idea for bases to be valid even without its overlays, which is not true about your suggestion. Putting the secret _in_ the base and then using `behavior: merge` to override is a good one. That avoids using variables entirely.

**Comment by phillycheeze** [comment]
Just throwing out another use case for inheriting `vars` from an overlay for non-secrets.

`$ base/kustomize.yaml`

```
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - deployment.yaml
vars:
  - name: APP_NAME
    objref:
      kind: Deployment
      name: app-name
      apiVersion: v1
```

`$ base/deployment.yaml`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
  labels:
    app: $(APP_NAME)
spec:
 .............
```

`$ overlay/production/kustomize.yaml`

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
```

`$ overlay/production/deployment.yaml`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
 .........
```

We are using a monorepo with 10+ microservices, where they each have a Deployment file with a different `APP_NAME`. There are other secrets that we would like to pass from the overlays to the base file, but showing this as a simple example. 

It produces the following error:
`Error: var '{APP_NAME ~G_v1_Deployment {metadata.name}}' cannot be mapped to a field in the set of known resources`

**Comment by mnpenner** [comment]
I'm having pretty much this exact same problem, but the `merge` solution isn't working for me. Here's my setup:

```txt
k8s
├── base
│   ├── app.yaml
│   ├── kustomization.yaml
│   └── my.env
├── development
│   ├── golinks.sql
│   ├── kustomization.yaml
│   ├── mariadb.yaml
│   ├── my.cnf
│   └── my.env
```

`base/kustomization.yaml`:

```yaml
namespace: go-mpen
resources:
- app.yaml
images:
- name: server
  newName: dreg.mpen.ca/go.mpen.ca/server
secretGenerator:
  - name: db-env
    behavior: create
    envs:
      - my.env
```

`development/kustomization.yaml`:

```yaml
resources:
  - ../base
  - mariadb.yaml
configMapGenerator:
  - name: mariadb-config
    files:
      - my.cnf
  - name: initdb-config
    files:
      - golinks.sql  
secretGenerator:
  - name: db-env
    behavior: merge
    envs:
      - my.env
#patchesStrategicMerge:
#  - app.yaml
```

I'm using `db-env` in both `development/mariadb.yaml` and `base/app.yaml`.

When I try to build this, the `app.yaml` one gets hashed, but `mariadb.yaml` does not:

```
❯ kustomize build k8s/development | grep db-env -B20
...
---
apiVersion: v1
data:
  (secrets)
kind: Secret
metadata:
  annotations: {}
  labels: {}
  name: db-env-km5h98t84b
--
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: go-mpen
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      pod: 338f54d2-8f89-4602-a848-efcbcb63233f
  template:
    metadata:
      labels:
        pod: 338f54d2-8f89-4602-a848-efcbcb63233f
        svc: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-env-km5h98t84b
--
      - name: regcred
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: bf4f837d-38d8-4a8a-b105-2f3532c0649b
  serviceName: mariadb
  template:
    metadata:
      labels:
        pod: bf4f837d-38d8-4a8a-b105-2f3532c0649b
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-env
```

If I `create` the secret in `development/kustomization.yaml` then it's the other way around -- `mariadb.yaml` gets updated but `app.yaml` does not.

But I want to use the same secrets in both `base/app.yaml` and `development/mariadb.yaml` -- can I not do that?
