### ISSUE TITLE
Allow excluding some label selectors from commonLabels

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#157]
I thought about this while implementing https://github.com/kubernetes-sigs/kustomize/pull/140. Sometimes you will have label selectors that you don't want Kustomize to make more specific by adding the commonLabels. 

The example use case for me is NetworkPolicy. I want to allow access to my application pods from my ingress controllers, but the ingress controllers are deployed separately, since they are part of the cluster infrastructure. Adding an application-specific label to those NetworkPolicy label selectors might prevent the ingress controllers from accessing my pods.

What I imagine would be a new configuration option, like this:

```
unmodifiedLabelPaths:
- objref:
    kind: NetworkPolicy
    name: my-application
  fieldref:
    fieldpath: spec.ingress.from.podSelector.matchLabels
```

Without this, the alternatives would be:

* use lots of patches instead of commonLabels to apply my extra labels to everything but the areas I  don't want
* have a separate NetworkPolicy resource outside of the Kustomization, which is unwieldy 
* potentially generic transformation https://github.com/kubernetes-sigs/kustomize/issues/91
