### ISSUE TITLE
add configMapGenerator option to force use of 'I-` instead of `|` when using `files`  

### ISSUE THREAD

**Issue by adrian-gierakowski** [kubernetes-sigs/kustomize#1574]
given the following `kustomization.yaml`:
```
configMapGenerator:
- name: example
  files:
  - var1
```

and a `var1` file in the same directory:
```
values

```

running kustomize build:
generates the following ConfigMap:
```
apiVersion: v1
data:
  var1: |
    value
kind: ConfigMap
metadata:
  name: example-d6khtmf8fc
```

I'd like to be able to force use of `|-` to strip the whitespace (in this case the trailing newline) from the value. Many devs use editors which add a newline at the end of a file on save, but most of the time the newline is not desired in the value of a config variable.
