### ISSUE TITLE
`kustomize edit add label` mutate the bases

### ISSUE THREAD

**Issue by kvokka** [kubernetes-sigs/kustomize#1582]
Initial content con `kustomize.yaml` file

```yaml
bases:
  - ../../bases/rails
```

After execution `kustomize edit add label foo:bar`:

```yaml
commonLabels:
  foo: bar
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases/rails
```
