### ISSUE TITLE
Transformer Configurations is not working

### ISSUE THREAD

**Issue by Rukeith** [kubernetes-sigs/kustomize#1584]
I got a `networkPolicy` YAML file and I want to custom Transformer Configurations to skip `commonLabels` to not create at egress `podSelector`.
But I found the default Transformer Configurations has already skipped this. But `commonLabels` still override egress podSelector. And then I created config to specify skip this, but it still not working.  Here are my files and my command.

**command**：`kustomize build demo`

**`kustomization.yaml`**

```YAML
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: demo-

commonLabels:
  app: api
  project: demo

configurations:
  - commonlabels.yaml

resources:
  - networkPolicy.yaml
```

**`commonlabels.yaml`**
```YAML
commonLabels:
  - path: spec/egress/to/podSelector/matchLabels
    create: false
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy

```
**`networkPolicy.yaml`**

```YAML
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
  labels:
    service: network-policy
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector:
            matchLabels:
    - ports:
        - port: 80
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: web
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
        - port: 80
          protocol: TCP
```

**Actual Output**
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  clusterName: shopee24
  labels:
    app: api
    project: demo
    service: network-policy
  name: demo-network-policy
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: api
          project: demo
          vv: as1
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 80
      protocol: TCP
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api
          project: demo
  - ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      app: api
      project: demo
  policyTypes:
  - Ingress
  - Egress
```

**Except Output**

```YAML
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  clusterName: shopee24
  labels:
    app: api
    project: demo
    service: network-policy
  name: demo-network-policy
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: api
          project: demo
          vv: as1
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 80
      protocol: TCP
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api
          project: demo
  - ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
-     app: api
+    app: web
-     project: demo
  policyTypes:
  - Ingress
  - Egress
```
