### ISSUE TITLE
Inject TLS Hosts into Ingress 

### ISSUE THREAD

**Issue by dsekhart** [kubernetes-sigs/kustomize#1586]
How to patch tls.hosts in the below example. kumization version 2.0.3
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
spec:
  rules:
# This value should be editable
  - host: mydomain.com
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: 80
  tls:
  - hosts: 
    - mydomain.com
    secretName: ingress-tls-secret
```
created a json patch 
```
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: helloworld
  path: helloworld-ingress-patch.yaml
```
helloworld-ingress-patch.yaml as below:
```
- op: replace
  path: /spec/rules/0/host
  value: example.com
- op: replace
  path: /spec/tls/hosts/0/<**what should be the key**>
  value: example.com

without the second operation in the above patch yaml, i could patch the host name, but not sure on the path for tls host patch.
