### ISSUE TITLE
Can't use kustomize vars in images

### ISSUE THREAD

**Issue by kkasravi** [kubernetes-sigs/kustomize#1592]
use case

params.env
```
registry=gcr.io
centraldashboardImageName=kubeflow-images-public/centraldashboard
centraldashboardImageTag=v20190823-v0.6.0-rc.0-69-gcb7dab59
```

params.yaml
```
- path: images/name
  kind: Kustomization
- path: images/newName
  kind: Kustomization
- path: images/newTag
  kind: Kustomization
```

kustomization.yaml
```
...
configMapGenerator:
- name: parameters
  env: params.env
vars:
- name: registry
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.registry
- name: centraldashboardImageName
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.centraldashboardImageName
- name: centraldashboardImageTag
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.centraldashboardImageTag
configurations:
- params.yaml
images:
  - name: $(registry)/$(centraldashboardImageName)
    newName: $(registry)/$(centraldashboardImageName)
    newTag: $(centraldashboardImageTag)
```
