### ISSUE TITLE
Is it possible to remove a whole resource from a manifest?

### ISSUE THREAD

**Issue by CermakM** [kubernetes-sigs/kustomize#1593]
Use case: I have a yaml manifest which is composed of multiple resources already (this is my base), I want to apply a patch which removes a resource from that manifest.

I am kinda struggling with this and I would really appreciate some advice.

Thanks in advance!
Marek

**Comment by jcassee** [comment]
Removing stuff is an explicit eschewed feature, so I'm afraid not:

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#removal-directives

**Comment by CermakM** [comment]
OK, gotcha. Thanks for the answer @jcassee 

FWIW I worked around the problem by using kustomize to apply custom labels and then using `kubectl apply` with the **label selector** to apply only the stuff I want.

Hope that helps someone stumbling upon a similar issue.

Cheers,
Marek

**Comment by jbrette** [comment]
Actually plenty of people had that exact same issue. In most of the examples I found, people end up being forced to do something like this:

``` bash
kustomize build . | python load-yaml-and-filter-and-order.py | kubectl apply -f -
```

The other trick is to do something like this
```bash
mkdir outputdir
kustomize build . -o outpudir
```

This creates one file per resources....which gives you full control on the order and filtering of the resources.

**Comment by johnmarcou** [comment]
A solution which could be helpful. I am using a remote kustomize module which deploys an empty secret.
But I have another system creating that secret.

Here the hack to remove the secret provided by Kustomize and avoid collision.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v0.7.0/manifests/install.yaml

patches:
  # Hacky way to disable the default secret
  - target:
      kind: Secret
      name: argocd-notifications-secret
    patch: |-
      - op: replace
        path: /metadata/name
        value: argocd-notifications-secret-dandling
```

**Comment by bimtauer** [comment]
@johnmarcou Were you able to solve this? I noticed that your hack will also change the secret name in the `Role` definition, thereby preventing the app from actually reading the real secret once its deployed. 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-notifications-controller
rules:
- apiGroups:
  - ""
  resourceNames:
  - argocd-notifications-secret-dangling #<- changes as well
  resources:
  - secrets
  verbs:
  - get
  ``` 
  
  When trying the `$patch: delete` trick suggested above I run into the following problem which drives me insane: 
  `Error: no matches for Id ~G_v1_Secret|argocd|argocd-notifications-secret; failed to find unique target for patch ~G_v1_Secret|argocd-notifications-secret` 
  I have absolutely no clue why it cannot match. A similar patchesStrategicMerge for the `argocd-notifications-cm` works without problems. 
  
 kustomization.yaml:
 ```yaml
 apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.6/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.2.0/manifests/install.yaml

patchesStrategicMerge:
  - patch-notifications.yaml    #<- works
  - delete-secret.yaml    #<- throws Error: no matches, failed to find unique target
 ```
 
patch-notifications.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
  subscriptions: |
    - recipients:
      - slack:flyte-argocd-alerts
      triggers:
      - on-sync-status-unknown
      - on-sync-running
      - on-sync-succeeded
      - on-sync-failed
      - on-created
      - on-deleted
      - on-deployed
      - on-health-degraded
```
delete-secret.yaml:
```yaml
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
```
Any help is greatly appreciated!

**Comment by bimtauer** [comment]
@johnmarcou were you able to solve this? I noticed that your hack will also change the secret reference in the `Role` thereby preventing access rights to real secret. 
However with the `$patch: delete solution` I get 
`Error: no matches for Id ~G_v1_Secret|argocd|argocd-notifications-secret; failed to find unique target for patch ~G_v1_Secret|argocd-notifications-secret` - similar patchesStrategicMerge works fine for `notifications-cm`

**Comment by bluebrown** [comment]
Would be nice if that would work without `.metadata.name`

**Comment by larsks** [comment]
@bluebrown You can make it work without a matching `metadata.name`. For example, this will delete all Route resources, regardless of their name:

```
patches:
  - target:
      kind: Route
    patch: |
      $patch: delete
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: DOES NOT MATTER
```

**Comment by kphunter** [comment]
Use ^^^ with selectors to filter out the unwanted resources.

**Comment by eternalphane** [comment]
Another solution would be to add the annotation `config.kubernetes.io/local-config: "true"` to resources you'd like to remove. [Kustomize removes objects with this annotation from its final build output](https://kubernetes.io/docs/reference/labels-annotations-taints/#config-kubernetes-io-local-config).

**Comment by GuyPaddock** [comment]
Extending the answer from [emwalker](https://github.com/emwalker), here's how you could target a specific name while using `patches` in the `kustomization.yaml` instead of putting the patch in a separate file (in this case, I'm eliminating a cronjob from an upstream repo):
```
patches:
- target:
    kind: CronJob
    name: bad-cron-job
  patch: |
    $patch: delete
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: bad-cron-job
```

**Comment by choeffer** [comment]
> Extending the answer from [emwalker](https://github.com/emwalker), here's how you could target a specific name while using `patches` in the `kustomization.yaml` instead of putting the patch in a separate file (in this case, I'm eliminating a cronjob from an upstream repo):
> 
> ```
> patches:
> - target:
>     kind: CronJob
>     name: bad-cron-job
>   patch: |
>     $patch: delete
>     apiVersion: batch/v1
>     kind: CronJob
>     metadata:
>       name: bad-cron-job
> ```

Plain kustomize even works without specifying the target, see https://github.com/fluxcd/kustomize-controller/issues/464

So

```
- patch: |
    $patch: delete
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: bad-cron-job
```

should be sufficient, and also works well.
