### ISSUE TITLE
kustomize overwrites RoleBinding Subject namespace

### ISSUE THREAD

**Issue by leroy0211** [kubernetes-sigs/kustomize#1599]
When I create a RoleBinding like this: 

```
# rolebinding.yaml
apiVersion: v1
kind: RoleBinding
metadata:
  name: my-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: my-namespace
roleRef:
  name: edit
```

and a kustomization file like this: 

```
# kustomization.yaml
namespace: loremipsum

resources:
  - rolebinding.yaml
```

and I run `kustomization build .` on this setup, the `subjects[0].namespace` will be changed to the namespace provided in the `kustomization.yaml` file. 

Result: 

```
# Wrong result
apiVersion: v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: loremipsum
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: default
  namespace: loremipsum
```

What I assume what would have happened is that only the `metadata.namespace` would be inserted, and the `subjects[0].namespace` would be left alone, like this: 

```
# Expected result
apiVersion: v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: loremipsum
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: default
  namespace: my-namespace      <--- this namespace should be left alone
```
