### ISSUE TITLE
kustomize build doesn't update .dockerconfigjson prefix

### ISSUE THREAD

**Issue by dhrp** [kubernetes-sigs/kustomize#1606]
Issue:

When using kustomize to build a spec including a .dockerconfigjson `type: kubernetes.io/dockerconfigjson` _and_ a namePrefix is given, then the secret is generated with said prefix, but the secretReference is not updated to include that prefix. As a result a user receives a imgPullError, even if the config was correct.

In other words:
```
resources:
  - deployment.yaml
namePrefix: test-
secretGenerator:
  - name: regcred
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
  - name: regcred-secret
    files:
      - .dockerconfigjson
```

with:
```
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  imagePullSecrets:
    - name: regcred
  template:
    spec:
      volumes:
        - name: regcred-secret
          secret:
            secretName: regcred-secret
      containers:
        - name: test
          image: dhrp/tools
```

Generates:
```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjdXN0b20ucmVnaXN0cnkuaW8iOnsicGFzc3dvcmQiOiJwYXNzIiwidXNlcm5hbWUiOiJ1c2VyIn19fQ==
kind: Secret
metadata:
  name: test-regcred-765d229md4
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjdXN0b20ucmVnaXN0cnkuaW8iOnsicGFzc3dvcmQiOiJwYXNzIiwidXNlcm5hbWUiOiJ1c2VyIn19fQ==
kind: Secret
metadata:
  name: test-regcred-secret-998kft7mhh
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-Enter deployment name
spec:
  imagePullSecrets:
  - name: regcred
  template:
    spec:
      containers:
      - image: dhrp/tools
        name: test
      volumes:
      - name: regcred-secret
        secret:
          secretName: test-regcred-secret-998kft7mhh
```
