### ISSUE TITLE
Add container reference in kustomization.yaml

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#161]
Add an extra fields in `kustomization.yaml` file and implement a new transformer. 
The new field format looks like this
```
require-tag: true
cr:
- image-name: myimage
  image-tag: sometag

cr:
- image-name: myimage2
  env: IMAGE2_TAG
```
The transformer will scan all resources, look at the resource object's spec session. For every container inside spec, check if the container name is in `kustomization.yaml` container reference and substitute the tag.
