### ISSUE TITLE
[bug] exec plugins - generator not appending hash

### ISSUE THREAD

**Issue by rosscdh** [kubernetes-sigs/kustomize#1612]
Hey there, thanks for taking the time

https://github.com/rosscdh/cc2-plugins/blob/master/com.mindcurv/v1/ansiblevaultsecretgenerator/secret.py

As per the file above have added the annotation and manualy the hash, but for some reason the reference to the generated secrets is not being updated in a deployment that refers to a secret. 

May I ask someone to give some pointers? Will be browsing the codebase in the meantime too

**Comment by vreon** [comment]
You don't need to manually add the hash, just the annotation :smile_cat:

Here's an `ExampleSecretGenerator` which generates a hard-coded Secret named `example`:

```
$ cat .config/kustomize/plugin/example.com/v1/examplesecretgenerator/ExampleSecretGenerator
```
```bash
#!/bin/bash
cat <<EOF
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
  name: example
data:
  foo: YmFy
EOF
```

And a kustomization that uses it:

```
$ cat kustomization.yaml
```
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- generator.yaml

resources:
- pod.yaml
```

```
$ cat generator.yaml
```
```yaml
apiVersion: example.com/v1
kind: ExampleSecretGenerator
metadata:
  name: whatever
```

```
$ cat pod.yaml
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: example
    image: busybox
    env:
    - name: FOO
      valueFrom:
        secretKeyRef:
          name: example
          key: foo
```

And the output:

```
$ kustomize build --enable_alpha_plugins .
```
```yaml
apiVersion: v1                        
data:
  foo: YmFy
kind: Secret
metadata:
  name: example-k6gf6b275m
---
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - env:
    - name: FOO
      valueFrom:
        secretKeyRef:
          key: foo
          name: example-k6gf6b275m
    image: busybox
    name: example
```

You can see that the `secretKeyRef` was correctly updated.
