### ISSUE TITLE
Namespace not set on APIService .spec.service.namespace

### ISSUE THREAD

**Issue by coryodaniel** [kubernetes-sigs/kustomize#1619]
`.spec.service.namespace` does not get populated by the namespace transformer.

```yaml
namespace: system
resources:
- apiservice.yaml
```

```yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.webhook.certmanager.k8s.io
spec:
  group: webhook.certmanager.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook
  version: v1beta1
```

Version: `Version: {Version:kustomize/v3.2.3 GitCommit:f8412aa3d39f32151525aff97a351288f5a7470b BuildDate:2019-10-08T23:30:25Z GoOs:darwin GoArch:amd64}`

**Comment by jbrette** [comment]
There is a bug in the default configuration [here](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/namereference.go#L272). The service field is one of those fields which require a simultaneous transformation of the name and the namespace.  It should be `path: spec/service` instead of `path: spec/service/name`

Meanwhile you can address the issue by updating the configuration using a simple config file as demonstrated [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1619).

```bash
$HOME/go/bin/kustomize.3.2.0 build examples/issues/issue_1619
```

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cert-manager
  name: cert-manager-webhook
  namespace: new-cert-namespace
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: cert-manager
  type: ClusterIP
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  labels:
    app: cert-manager
  name: v1beta1.admission.certmanager.k8s.io
spec:
  group: admission.certmanager.k8s.io
  groupPriorityMinimum: 1000
  service:
    name: cert-manager-webhook
    namespace: new-cert-namespace
  version: v1beta1
  versionPriority: 15
```

/bug
