### ISSUE TITLE
request nameSuffix to add suffix to resource names

### ISSUE THREAD

**Issue by easeway** [kubernetes-sigs/kustomize#163]
Similar to namePrefix, but adding suffix to resource names helps unlocking a use case I'm currently facing:

My automated build pipeline will generate a Kubernetes manifest file containing resources, and I want the names of these resources to have a suffix which is generated from build number, because I need side-by-side deployment of old and new versions and give customer a smooth upgrade/rollback experience. Here's an example:

in the base:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
```

And in a patch, I'd love to have `kustomization.yaml` include something like:

```yaml
nameSuffix: -101
```

Where `-101` is generated from build number in the automated pipeline. And ultimately get the manifest including:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-101
```

I've no idea if I can achieve this without something like `nameSuffix`. And definitely, I don't want to put build number as a prefix of all resource names.
