### ISSUE TITLE
commonLabels should be merged/stacked over depth-first exploration of base tree?

### ISSUE THREAD

**Issue by shaunc** [kubernetes-sigs/kustomize#1632]
I have a structure like:

base/kustomization.yaml:
```yaml
resources:
- service.yaml
```
stage/dev/kustomization.yaml:
```yaml
commonLabels:
  stage: dev
```
cluster/local/kustomization.yaml:
```yaml
commonLabels:
  clusterName: local
```
target/local-dev/kustomization.yaml:
```yaml
resources:
- ../../base
- ../../stage/dev
- ../../cluster/local
```

I expect the service to have `stage: dev` and `clusterName: local` labels, but it doesn't. If I put these labels in "base" or "target/local-dev" it works, but obviously thats not what I want.

```
$ kustomize version
Version: {Version:kustomize/v3.2.3 GitCommit:f8412aa3d39f32151525aff97a351288f5a7470b BuildDate:2019-10-08T23:30:25Z GoOs:darwin GoArch:amd64}
```
### Note

I tried removing the base resource from "target" and putting it in both stage/dev and cluster/local, but this gives me an error:
```
Error: accumulating resources: recursed merging from path '../../cluster/local': may not add resource with an already registered id: ~G_v1_Service|~X|ai-site
```

### Note 2

I am now trying to replicate the effect of `commonLabels` with a patch. This is the first time I used patching, and the instructions seem sketchy. 

In `stage/dev/kustomization.yaml` I added:
```yaml
patchesStrategicMerge:
- path: patch.yaml
  target: []
```

The `patch.yaml` looks like (snapshot, as I fiddle with it):
```yaml
metadata:
  labels:
    stage: dev
    $patch: merge
spec:
  selector:
    matchLabels:
      stage: dev
      $patch: merge
  template:
    metadata:
      labels:
        stage: dev
        $patch: merge
```
This gives me:
```
Error: accumulating resources: couldn't make target for path '../../stage/dev': json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type types.PatchStrategicMerge
```
(I tried without the "$patch: merge" elements as well.)

Is this the place to turn to for directions? https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md

More instructions would be helpful.

### Note 3

I tried `stage/dev/kustomization.yaml` instead with:
```yaml
patches:
- patch: |2
    - op: add
      path: metadata.labels.stage
      value: dev
    - op: add
      path: spec.selector.matchLabels.stage
      value: dev
    - op: add
      path: spec.template.metadata.labels.stage
      value: dev
  target: []
```
Adapted from https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#field-name-patches

Unfortunately this also doesn't work:
```
Error: accumulating resources: couldn't make target for path '../../stage/dev': json: cannot unmarshal array into Go struct field Patch.patches.target of type types.Selector
```
### Note 4

Tried this patch spec as well:
```yaml
patches:
- patch: |2
    - op: test
      path: metadata
      value: labels
    - op: add
      path: metadata.labels.stage
      value: dev
  target:
    labelSelector: '!stage'
```
Sigh ... also doesn't work:
```
Error: failed to apply json patch '- op: test
  path: metadata
  value: labels
- op: add
  path: metadata.labels.stage
  value: dev
': test operation does not apply: is missing path: metadata: missing value
```
