### ISSUE TITLE
Building a Gitlab Review-app flow with Kustomize

### ISSUE THREAD

**Issue by paultiplady** [kubernetes-sigs/kustomize#164]
I currently use Gitlab's [review apps](https://docs.gitlab.com/ee/ci/review_apps/) extensively, and I have a mix of Helm and Python for deploying apps. I have done a bit of digging and haven't quite found a clean/documented way of doing this sort of flow with Kustomize, so I thought I'd open an issue to get a discussion going.

The key aspect of the review app flow is that every MR (aka PR in Github terminology) gets its own deployed environment. So I need to create a patch that my CI server can check out, fill in a per-branch namespace value, and also a unique image tag, and then deploy to my cluster.

While long-lived overlays like "production" and "development" are fairly well documented, I can't see a clear idiomatic way of doing what I'm trying to do.

Some options:

1. Simple template replacement, like `find . -name '*.yaml' | xargs sed -i "/s/<namespace>/${NAMESPACE}/"`. This is quite awkward, but will work for a small number of substitutions
2. Maybe `kustomize edit set` could be extended to allow the namespace and other parameters to be overridden in my overlay?
3. ? 

I am interested to know if this is a use-case that the SIG has already considered, and what the right approach here would be.

**Comment by mxey** [comment]
The workflow at my job is to put the review apps into the same namespace as the development environment, especially since the deploy job do not have the permission to create more namespaces.

The relevant features are:

* set labels dynamically: https://github.com/kubernetes-sigs/kustomize/pull/147
* `kustomize edit set nameprefix`  

What you'd need is `kustomize edit set namespace`. Kustomize can already override the namespace, there is just no command to put that into the configuration file, but you could of course do it by any other method of editing YAML files.

**Comment by paultiplady** [comment]
Having dug a little more, I think there's two different categories of changes here --

1. metadata changes, like namespace or name prefixes, which would be applied to every resource that kustomize is creating. These are for scoping/tagging.
2. one-off changes, like setting image-tag=$GIT-SHA. I suspect that everyone doing a review-app flow will need a way of making this specific change, but not sure it warrants its own command. Though perhaps it could be satisfied by `kustomize edit set deployment.spec.template.spec[containername].image $GIT-SHA`, i.e. using a Go selector to specify an individual resource key/value. If this was fleshed out, it would obviate the need for special-cases like 1. (though doesn't cleanly fix the "provide a prefix" case).

**Comment by mxey** [comment]
I use Skaffold to build the image and deploy, it sets the image version accordingly and deploys through Kustomize+Kubectl

**Comment by mxey** [comment]
Since you are not committing those one-off changes, you could just use `kubectl patch --local` on your resource files

**Comment by paultiplady** [comment]
I just started looking at Skaffold, that might be the piece that's missing. Wasn't aware of `--local` for `kubectl patch`, that also sounds useful. Thanks!

If I get this up and running I'll look at submitting an example to tie this all together.

**Comment by paultiplady** [comment]
Looks like this is relevant too: https://github.com/kubernetes-sigs/kustomize/issues/109

**Comment by paultiplady** [comment]
Which links to https://github.com/kubernetes-sigs/kustomize/issues/122, specifically for generating transforms for things like `image`.

**Comment by paultiplady** [comment]
Reporting back -- `kubectl patch --local` does what I need for the CI/CD pipeline, but isn't great for a local developer's flow, since it's destructive (i.e. overwrites local files). Doesn't look like there's a way to run the patch command on a piped input (`kustomize build | kubectl patch --local | kubectl apply` does not work AFAICT), so I think this will have to be a CI-only workflow for now. 

#122 would give what I need to apply transformations inside kustomize.

**Comment by Liujingfang1** [comment]
@paultiplady Recently kustomize added a feature to change image tags. That is what you need. Check out the example here https://github.com/kubernetes-sigs/kustomize/blob/master/examples/imageTags.md

**Comment by paultiplady** [comment]
Circling back on this, there are still some items that are awkward.

I have per-review-app config, e.g. DNS name that gets loaded into an annotation. I don't see a good way to achieve per-branch parametrization in Kustomize.

I'm looking at emitting the overlay YAML dynamically, something like `echo "{\"metadata\": {\"annotations\": {\"dns_name\": ${ENV_DNS_NAME}}}}" > overlays/builds/service.yaml` in the build pipeline before running kustomize, but this feels a bit ad-hoc, and isn't going to scale well.

Is there a more "canonical" approach to adding ad-hoc dynamic custom fields? I saw some work recently on transformers which looks like it might be appropriate, although you rolled back transforms from the CLI, which sounds like exactly the fix for this case.

**Comment by nabadger** [comment]
Keeping an eye on this as I'm experimenting with using kustomize in our GitlabCI pipeline too.

Similar issues which are essentially:
- Various manifests need to know the cluster-domain. Typically this is generated from a GitlabCI environment var, and needs to make its way into the manifests
- Ingresses for feature branches. Such branches come and go and the ingress host is typically in the form "$app-$branch.$cluster-domain"
- Image tags (looks like there's a solution for this already)

I feel the direction I'll go in will be one of the following:
- Dynamic overlays per branch, created as part of the pipeline
- Dynamic config-maps generated from say an `environment.properties` file

**Comment by nabadger** [comment]
As a way to get custom info. through to kustomize, something like this seems to be working for me. I can at least get to an output that starts to reasonable that of the auto-devops pipeline.

Using vars/configMapGenr preferable over patches and overlays (at least to me):

```
# kustomization.yaml

# Generate some vars for the deployment name and domain of the k8s cluster.
# Both of these end up being used to generate the Ingress host.

vars:
- name: DEPLOYMENT_NAME
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  fieldref:
    fieldpath: metadata.name
- name: DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-properties
  fieldref:
    fieldpath: data.DOMAIN

# Setup configMapGenerator from properties files, which could be committed or even 
# populated at runtime by the Gitlab CI
# Values in these properties can be over-ridden per environment (using an overlay)

configMapGenerator:
- name: cluster-properties
  env: properties/cluster.properties
```
```
# ./properties/cluster.properties
DOMAIN=k8s.example.com
```
Ingress ends up something like this:

```
...
spec:
  rules:
  - host: $(DEPLOYMENT_NAME).$(DOMAIN)
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 8000
  tls:
  - hosts:
     - $(DEPLOYMENT_NAME).$(DOMAIN)
```

---
Another piece of the puzzle is how to setup application names to be specific per branch (which they are in Gitlab by using the slug of the branch name).

I don't know a great way to achieve this, but since the slug is available as a GITLAB_CI variable, something like this may work:

kustomize edit set nameprefix $(CI_ENVIRONMENT_SLUG)-

This would be a local change mind...
