### ISSUE TITLE
Name references in annotations for CRDs

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-sigs/kustomize#1685]
I'm trying to use `namePrefix` together with a cert-manager `Issuer` and a normal `Ingress`. The prefix is added to the Issuer without problem, but the reference to the Issuer name in the Ingress annotation is not updated.

This is what I have:

```yaml
# kustomization.yaml
resources:
  - issuer.yaml
  - ingress.yaml
namePrefix: staging-
configurations:
  - issuer-kustomize-config.yaml

# issuer.yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@example.com

# ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: letsencrypt-staging # <--- Reference to Issuer
spec:
  tls:
  - hosts:
    - example.com
    secretName: wordpress-cert
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
        path: /

# issuer-kustomize-config.yaml
nameReference:
- kind: Issuer
  version: certmanager.k8s.io/v1alpha1
  fieldSpecs:
    - kind: Ingress
      path: metadata/annotations/certmanager.k8s.io\/issuer
```

The path contains a slash, but I'm escaping it according to [the documentation](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#supporting-escape-characters-in-crd-path).

Possible related: [#234](https://github.com/kubernetes-sigs/kustomize/issues/234)

A possible workaround would be to not apply the name prefix on the Issuer. But this does [not seem possible](https://github.com/kubernetes-sigs/kustomize/issues/519) at the moment.
