### ISSUE TITLE
Patch Delete fails for CustomResourceDefinition

### ISSUE THREAD

**Issue by dmayle** [kubernetes-sigs/kustomize#1689]
I'm attempting to kustomize the cert-manager installation ( https://github.com/jetstack/cert-manager/releases/download/v0.11.0/cert-manager.yaml ), which for some reason includes 'status' in the CRD with empty keys.

I'm trying to strip the the status key so that it becomes useful with other tooling.  I've tried both a strategic merge patch, and a json patch, but neither work, from the following kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/cert-manager.yaml

patchesStrategicMerge:
- overlays/production/cert-manager.yaml

patchesJson6902:
- target:
    group: cert-manager.io
    version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  path: "./jsonpatch.yaml"
```

The strategic merge patch:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificaterequests.cert-manager.io
  annotations:
    douglas: test
status:
  $patch: delete
```

The json patch:
```
- op: remove
  path: "/status"
```

I'm using kubectl 1.15 to perform the patch `kubectl kustomize .`.

For the strategic merge patch, the annotation is correctly added, but the 'status' field just gets a '$patch: delete' key added to it.  (Using 'nil' removes the subkeys, but leaves the nil 'status' entry).

For the json patch, I fail to match the object:
```
Error: couldn't find target cert-manager.io_apiextensions.k8s.io/v1beta1_CustomResourceDefinition|~X|~P|certificaterequests.cert-manager.io|~S for json patch
```

**Comment by dmayle** [comment]
I've tried updating to the kustomize in kubectl 1.16.2-00  (Debian package maintained by kubernetes.io) and it stil has the same behavior.  The strategic patch merge leaves this:
```
status:
  $patch: delete
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

**Comment by Liujingfang1** [comment]
So far we haven't updated the kustomize inside kubectl. So different kubectl should have the same behavior on `kubectl kustomize`. They all use kustomize 2.0.3.

Then, the strategic merge patch doesn't work with `status` on CustomResourceDefinition since this field doesn't have "x-kubernetes-patch-merge-key" in its openapi spec.

You can use json patch to delete `status`. The one you provided here is not correct. Change it to the following
```
patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1beta1
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  path: "./jsonpatch.yaml"
```
