### ISSUE TITLE
Support for JSON Patch

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#169]
Sometimes, the strategic merge patch or JSON merge patch approach does not merge in a way one would like. For example, Ingress rules are replaced entirely.

`kubectl patch` supports the [JSON Patch standard](http://jsonpatch.com). It would be useful for Kustomize to support it as well.

**Comment by Liujingfang1** [comment]
Kustomize uses stategic patch for types with schema and json patch for types without schema.

**Comment by mxey** [comment]
Kustomize uses JSON Merge Patch (RFC 7396) for types without schema. I am referring to JSON Patch (RFC 6902). 

The command description for `kubectl patch` does not mention it, but it's supported, and [shown in the cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#patching-resources).

**Comment by mengqiy** [comment]
IMO we should support other patch types.
cc: @monopole

**Comment by monopole** [comment]
yep, agreed

**Comment by Liujingfang1** [comment]
one possible implementation: when applying a patch, check if it is a JSON patch. If it is, apply it as JSON patch. Otherwise, use current approach.

**Comment by Liujingfang1** [comment]
We will need `gvk` and `name`, no need for prefix and namespace.
JSON patch doesn't contain this info, we could let the user to specify `gvk` and `name` for JSON patch in kustomization.yaml.

**Comment by Liujingfang1** [comment]
We can use [ObjectReference](https://v1-10.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#objectreference-v1-core) to specify which object the JSON patch is applied to.

There is one more concern. In a JSON patch, one can have operations for changing the object's `metadata.name`. If Kustomize supports this operation, the object becomes a different object after applying the patch. I don't think we expect this to happen in a kustomization. The reason is that, by looking at the resources, we can get the objects (names, prefix, namespace and so on). Having a JSON patch which potentially may change the object name breaks this rule and includes new uncertainty. 

I suggest to skip the operations for changing the object `metadata.name` with a message. WDYT @mengqiy @monopole

**Comment by monopole** [comment]
Yes, disallow name change in patch until we edfine a safe approach (and someone asks for it).

**Comment by Liujingfang1** [comment]
I created POCs for two different approaches. @mxey  @ivan4th @sethpollack, can you take a look and let us know your feedback from an user aspect. Thank you.

#286  adds a new filed `jsonPatches` in `kustomization.yaml`, the format is
```
patches:     #This filed is not affected
- patch1.yaml 
- patch2.yaml

jsonPatches:
- path: patch1.json
  target:
     kind: Service
     name: some-service
- path: patch2.json
  target:
     kind: Deployment
     name: some-deployment
```
This approach is backward compatible, but doesn't have good extend-ability. If we need to support another kind of patch in the future, we have to add new fields in `kustomization.yaml`



#295 doesn't introduce new filed in kustomization.yaml, but allow current `patches` to accept a map. The format is
```
patches:
- patch1.yaml
- patch2.yaml
- path: patch1.json
  type: JSONPatch
  target:
     kind: Service
     name: some-service
- path: patch2.json
  type: JSONPatch
  target:
     kind: Service
     name: some-deployment
```
This approach is backward compatible and have good extendability. The drawback is this approach will make Kustomization API unstructured.
