### ISSUE TITLE
Configured PrefixSuffixTransformer does not update back references

### ISSUE THREAD

**Issue by ryandbump** [kubernetes-sigs/kustomize#1695]
The following example reproduces the issue I am seeing.

Setup:
```sh
EXAMPLE=$(mktemp -d)
mkdir -p ${EXAMPLE}
cat <<'EOF' >${EXAMPLE}/kustomization.yaml
resources:
  - deployment.yaml
  - secret.yaml
transformers:
  - suffixer.yaml
EOF
cat <<'EOF' >${EXAMPLE}/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
spec:
  selector:
    matchLabels:
      app: group-service
  template:
    metadata:
      labels:
        app: group-service
    spec:
      containers:
        - name: group-service
          image: image
          envFrom:
            - secretRef:
                name: group
EOF
cat <<'EOF' >${EXAMPLE}/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: group
data:
  secretKey: c2VjcmV0VmFsdWUK
type: Opaque
EOF
cat <<'EOF' >${EXAMPLE}/suffixer.yaml
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: suffix
suffix: -service
fieldSpecs:
  - kind: Secret
    path: metadata/name
EOF
```

```sh
$ kustomize version
Version: {KustomizeVersion:3.2.0 GitCommit:a3103f1e62ddb5b696daa3fd359bb6f2e8333b49 BuildDate:2019-09-18T18:31:04+01:00 GoOs:darwin GoArch:amd64}
```

Test:
```
kustomize build ${EXAMPLE}
```

Result:
```yaml
apiVersion: v1
data:
  secretKey: c2VjcmV0VmFsdWUK
kind: Secret
metadata:
  name: group-service
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
spec:
  selector:
    matchLabels:
      app: group-service
  template:
    metadata:
      labels:
        app: group-service
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: group
        image: image
        name: group-service
```

Expectations:

I expected the `envFrom/secretRef/name` to be update to `group-service`. I have been able to get a configured PrefixSuffixTransformer to properly update the back references by including the kind `Deployment` in the `fieldSpecs` for the transformer. The issue with this solution is that it also adds the suffix to the `Deployment`.
