### ISSUE TITLE
Variable replacement seems inconsistent

### ISSUE THREAD

**Issue by aceeric** [kubernetes-sigs/kustomize#1710]
Folks, given the following directory structure:

```
'
|-- kustomize
    `-- kustomizeconfig
```

And the following files in that directory structure with the following content:

**./kustomize/alert-ns-patch.yaml**
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  alerting:
    alertmanagers:
    - name: alertmanager
      namespace: $(NS)
      port: alertmanager
```

**./kustomize/service-monitor.yaml**
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
spec:
  selector:
    namespaceSelector:
      matchNames:
      - IWANTTOREPLACETHIS
  endpoints:
  - port: metrics
    honorlablels: true
    interval: 10s
    scrapeTimeout: 10s
    etc: etc
```

**./kustomize/set-svc-mon-ns.yaml**
```
- op: replace
  path: /spec/selector/namespaceSelector/matchNames/0
  value: $(NS)
```

**./kustomize/catalog-source.yaml**
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: foocorp-operators-registry
spec:
  displayName: Foo
  publisher: Foo Corp.
  sourceType: grpc
  image: docker-registry.default.svc:/foocorp/foocorp-operators-registry:0.0.1
```

**./kustomize/kustomization.yaml**
```
resources:
- prometheus.yaml
- catalog-source.yaml
- service-monitor.yaml

namespace: kustomizedns

configurations:
- kustomizeconfig/prometheus.yaml
- kustomizeconfig/servicemonitor.yaml

patchesStrategicMerge:
- set-catalog-source-image.yaml
- alert-ns-patch.yaml

patchesJson6902:
- target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    name: prometheus-service-monitor
  path: set-svc-mon-ns.yaml

vars:
- name: NS
  objref:
    apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    name: foocorp-operators-registry
  fieldref:
    fieldpath: metadata.namespace
```

**./kustomize/prometheus.yaml**
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: k8s
spec:
  replicas: 2
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector: {}
  ruleSelector: {}
  alerting:
    alertmanagers:
    - namespace: IWANTTOREPLACETHIS
      name: alertmanager
      port: alertmanager
```

**./kustomize/set-catalog-source-image.yaml**
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: foocorp-operators-registry
spec:
  image: docker-registry.default.svc:/foocorp/foocorp-operators-registry@sha256:NOTIMPORTANTFORTHETEST
```

**./kustomize/kustomizeconfig/prometheus.yaml**
```
varReference:
- path: spec/alerting
  kind: Prometheus
```

**./kustomize/kustomizeconfig/servicemonitor.yaml**
```
varReference:
- path: spec/selector/namespaceSelector/matchNames
  kind: ServiceMonitor
```

and this command: `kustomize build .`

I get this result for `ServiceMonitor` with `matchNames` substituted:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: kustomizedns
spec:
  endpoints:
  - etc: etc
    honorlablels: true
    interval: 10s
    port: metrics
    scrapeTimeout: 10s
  selector:
    namespaceSelector:
      matchNames:
      - kustomizedns
```

But for `Prometheus` I get this - the `$(NS)` variable flows through like a constant:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: prometheus
  namespace: kustomizedns
spec:
  alerting:
    alertmanagers:
    - name: alertmanager
      namespace: $(NS)
      port: alertmanager
  replicas: 2
  ruleSelector: {}
  securityContext: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
```

At a minimum this is inconsistent. Would you consider it a bug? Thanks
