### ISSUE TITLE
Kustomize vars not applied to Namespace resources

### ISSUE THREAD

**Issue by anth0d** [kubernetes-sigs/kustomize#1713]
You can run this to reproduce the issue. (Thanks to @tkellen for the idea on how to share repro steps easily)

Expected: `$(MY_NAMESPACE)` is actually substituted.

```
#!/usr/bin/env bash

cd "$(mktemp -d)"

cat <<EOF > kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
- name: MY_NAMESPACE
  objref:
    kind: ServiceAccount
    name: my-service-account
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
resources:
- namespace.yaml
- other.yaml
EOF

cat <<EOF > namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: \$(MY_NAMESPACE)
EOF

cat <<EOF > other.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: some-namespace
EOF

tree
kustomize build .

```

Output:
```
2019/10/30 17:36:42 well-defined vars that were never replaced: MY_NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: $(MY_NAMESPACE)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: some-namespace
```
