### ISSUE TITLE
Feature request - merge patch handles list of dictionaries

### ISSUE THREAD

**Issue by aceeric** [kubernetes-sigs/kustomize#1715]
If a CR looks like this:
```
apiVersion: org.mycompany/v1
kind: MyKind
metadata:
  name: mykind
spec:
  components:
  - name: foo
    property: leave-as-is
  - name: bar
    property: replace-me
```
Then conceptually I would like to be able to specify a patch that expresses this:
```
- op: replace
  path: /spec/components/{where name=bar}/property
  value: new-value
```
Resulting in:
```
apiVersion: org.mycompany/v1
kind: MyKind
metadata:
  name: mykind
spec:
  components:
  - name: foo
    property: leave-as-is
  - name: bar
    property: new-value
```
This doesn't work:
```
- op: replace
  path: /spec/components/2/property
  value: new-value
```
Because of:
```
apiVersion: org.mycompany/v1
kind: MyKind
metadata:
  name: mykind
spec:
  components:
  - name: foo
    property: leave-as-is
  - name: order-isnt-deterministic
    property: x
  - name: bar
    property: replace-me
```
