### ISSUE TITLE
Variable is expected to be string

### ISSUE THREAD

**Issue by davidmogar** [kubernetes-sigs/kustomize#1721]
I'm replacing a variable in my base to map the replicas in a Deployment with the minReplicas in a HorizontalPodAutoscaler. This is the basic config:

Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetserver
spec:
  replicas:  $(REPLICAS)
...
```
HorizontalPodAutoscaler:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: puppetserver
spec:
  maxReplicas: 15
  minReplicas: 1
```
Configuration for varReferences:
```
varReference:
  - path: spec/replicas
    kind: Deployment
  - path: spec/metrics/object/describedObject/name
    kind: HorizontalPodAutoscaler
  - path: spec/scaleTargetRef/name
    kind: HorizontalPodAutoscaler
```
kustomization.yaml:
```
configurations:
  - kustomizeconfig/var_references.yaml

resources:
  - deployment.yaml
  - horizontal_pod_autoscaler.yaml

vars:
  - name: REPLICAS
    objref:
      kind: HorizontalPodAutoscaler
      name: puppetserver
      apiVersion: autoscaling/v1
    fieldref:
      fieldpath: spec.minReplicas
```

This is working as expected and the variable gets replaced. But, when I try to kustomize an overlay which only contains this:
```
bases:
  - ../../base

replicas:
- name: puppetserver
  count: 5
```
I get the next error:
```
Error: "$(REPLICAS)" is expected to be string
```
What am I doing wrong?

This is happening with the latest release (3.3.0).
