### ISSUE TITLE
VerticalPodAutoscaler: targetRef not updated with namePrefix

### ISSUE THREAD

**Issue by philhug** [kubernetes-sigs/kustomize#1727]
Example:
kustomization.yaml:
```
namePrefix: dev-
resources:
- deployment.yaml
- vpa.yaml
```
vpa.yaml:
```
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hello-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       the-deployment
  updatePolicy:
    updateMode: "Auto"
```

Output:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-the-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - command:
        - /hello
        - --port=8080
        image: monopole/hello:1
        name: the-container
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dev-hello-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: the-deployment
  updatePolicy:
    updateMode: Auto
```

`name: the-deployment` should have been replace by `name: dev-the-deployment`
