### ISSUE TITLE
Overlay can't override port in Service or Deployment

### ISSUE THREAD

**Issue by nicksnyder** [kubernetes-sigs/kustomize#173]
```yaml
# base/frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http 
    port: 80
  selector:
    app: frontend
  type: NodePort
```

I want to change the port in an overlay.
```yaml
# overlay/port.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http 
    port: 90
```

Building the overlay results in the following yaml (note that http port is declared twice with two values):
```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
    port: 90
  - name: http
    port: 80
  selector:
    app: frontend
  type: NodePort
```

 Same thing happens with Deployments.
