### ISSUE TITLE
Support for variable replacement in literals

### ISSUE THREAD

**Issue by dsyer** [kubernetes-sigs/kustomize#1737]
Currently, to get an env var to point to a service name, I have to do this (which makes the k8s resource into a template - the famous anti-pattern that no-one wanted but we ended up with anyway):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: MYSQL_HOST
          value: $(MYSQL_SERVICE_NAME)
```

I also had to create an `env` entry in my Deployment that I didn't really want - I prefer to use a ConfigMap. What I would like is to put that placeholder in `kustomization.yaml` via a literal (or similar):

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - MYSQL_HOST=$(MYSQL_SERVICE_NAME)
vars:
  - name: MYSQL_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: mysql
```

The `vars` can even go in the base if I don't want it here.

**Comment by tkellen** [comment]
Dupe of: https://github.com/kubernetes-sigs/kustomize/issues/318.
Also see: https://github.com/kubernetes-sigs/kustomize/pull/1620#issuecomment-542375406

It would probably be best if you avoided this rabbit hole and just used envsubst instead.

**Comment by tkellen** [comment]
At this point a real contribution around vars to this project would be a PR that adds loudly to the documentation how broken vars are and encourages folks to consider this responsibility (var handling, any sort of templating at all) outside the scope of kustomize.

**Comment by dsyer** [comment]
I'm not sure I understand, but I'm not really very deep in any rabbit hole right now. Maybe you can spare some time to explain a bit more to someone who doesn't have as good an understanding of how kustomize works.

My reading of #318 was that it is about something different (I did find that one before I opened this issue). Isn't it? It says it's about literals as the value of vars. Maybe it morphed into something else and I didn't spot it. I'm afraid reading the whole of #1620 and #1600 didn't help me either to understand the problem better or solve it.

I would appreciate any help anyone can give getting my example to work (i.e. extracting a service name, which is actually needed by another deployment, and has been generated by kustomize, so I don't know what it is in advance). I doubt I can do that with envsubst, but I'm open to being educated.

**Comment by bkuschel** [comment]
Variables are only "bound" in the output resources as a final step after the top level build has finished, even if declared in a child build. What this means is that any variables that are "consumed" by transformers/generators as input that don't have a direct representation in the final output are never substituted.
Further, variable substitution is only performed on output `resources`, since you using a transformer and never outputting it as a resource from a build (which is not possible through builtins, which are executed directly as `generators` or `transformers`), they would never get substituted, regardless.

We are preparing a PR which bind variables immediately where the variable is declared, which will only help in your scenario if you create a separate resources for the transformer and process them as resources first that have the vars you want substituted.

**Comment by bkuschel** [comment]
Here is a transformer we created that does kustomize child level build substitution. It has some examples.
https://github.com/qlik-oss/kustomize-plugins/tree/master/kustomize/plugin/qlik.com/v1/supervars

**Comment by bkuschel** [comment]
@dsyer actually, in your example the literal _does_ get passed through but its not included in the varRefences. You need to create a configuration with a new varReferences that contains the kind 'ConfigMap' and path to your variable.
 example:
varreferences.yaml:
```
- path: data/MYSQL_HOST
  kind: ConfigMap
```
kustomization.yaml:
```
configurations:
  - varreference.yaml
```

**Comment by dsyer** [comment]
That was helpful, and I didn't understand your first comment at all, so thanks for taking the time. If anyone else is trying it, I think `varreference.yaml` has to be:

```yaml
varReference:
- path: data/MYSQL_HOST
  kind: ConfigMap
```
