### ISSUE TITLE
commonLabels don't propagate from base to overlays 

### ISSUE THREAD

**Issue by coryodaniel** [kubernetes-sigs/kustomize#174]
commonLabels don't propagate from base to overlays when a resource is only defined in the overlay. I'm not sure if this is the intention or a bug, but I was expecting that any label in base would end up on all resources.

For example:
```yaml
# in base/kustomization.yaml
commonLabels:
  app: kewl
```

```yaml
# in overlays/staging/kustomization.yaml
namespace: staging
commonLabels:
  env: staging
bases:
-  ../../base
resources:
- pod.yaml
```

```yaml
# in overlays/staging/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-pod
    image: pod:latest
```

I expected that the pod would be labeled as follows, but `app: kewl` is missing.

```yaml
labels:
  app: kewl # missing
  env: staging
```

If I make the resource from `base` and patch it in the overlay, it works as expected.
