### ISSUE TITLE
Image Transformer Empty Containers

### ISSUE THREAD

**Issue by DustinChaloupka** [kubernetes-sigs/kustomize#1747]
Similar to #890, but on an empty `containers` or `initContainers` and on any type of resource:

**test.yaml**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
    spec:
      initContainers:
      containers:
        - name: test
          image: other.registry.com/test:1.0.0
```
**kustomization.yaml**
```yaml
resources:
  - test.yaml

images:
  - name: other.registry.com/test
    newName: my.registry.com/test
```
Either one can be empty and doing a `kustomize build` will result in:
```
Error: containers path is not of type []interface{} but <nil>
```
