### ISSUE TITLE
Handle empty YAML manifests

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes-sigs/kustomize#178]
When using `helm template` to generate your base resources, there may be times when a resource is empty due to the way templating works in upstream charts. We should ignore empty manifests. Here is an example:

```yaml
---
# Only a comment exists in this block
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci-jenkins
spec:
  template:
    spec:
      containers:
        - name: ci-jenkins
          image: jenkins/jenkins:lts
```

The error returned is:
```shell
$  kustomize buildError: loadResMapFromBasesAndResources: rawResources failed to read Resources: YAML file [/home/viglesias/git/kustomize-jenkins/charts/stable/my-jenkins/jenkins-base.yaml] encounters a format error.
error unmarshaling JSON: Object 'Kind' is missing in 'null'
```

For a example:
```
git clone https://github.com/kubernetes/charts.git
cd charts
helm template stable/jenkins
```
