### ISSUE TITLE
Variable substitution only partly working on Jobs

### ISSUE THREAD

**Issue by stravag** [kubernetes-sigs/kustomize#1782]
We are using kustomize bundled with kubectl and have some issues with variable replacement.

We have a `Job` and `Deployment` both make use of `initContainers` and in all we'd like to use kustomize `vars` that should automatically apply a prefix.

When applying kustomize, for the `Deployment` the variables get correctly substituted and prefixed.

**Deployment definition**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  ...
  template:
    ...
    spec:
      containers:
        - name: nginx
          env:
            - name: BACKEND_HOST
              value: $(BACKEND_SERVICE_NAME)
      initContainers:
        - name: init-nginx-wait-backend
          image: busybox:1.31
          command: ['sh', '-c', 'until nslookup $(BACKEND_SERVICE_NAME); do sleep 2; done;']
```

**Deployment Kustomize substitution**
```
apiVersion: apps/v1
kind: Deployment
...
      containers:
      - env:
        - name: BACKEND_HOST
          value: test-backend-service
      initContainers:
      - command:
        - sh
        - -c
        - until nslookup test-backend-service; do echo waiting for backend; sleep
          2; done;
        env:
        - name: IAM_HOST
          value: test-iam-service
        image: busybox:1.31
        name: init-nginx-wait-backend
```

As expected `$(BACKEND_SERVICE_NAME)` gets substituted with: `test-backend-service` in both the command and the env var of both container and initContainer 👍

The same thing with the `Job`

**Job definition**
```
apiVersion: batch/v1
kind: Job
metadata:
  name: some-job
spec:
  template:
    ...
    spec:
      containers:
          env:
            - name: HOST
              value: $(SERVICE_NAME)
      initContainers:
        - name: init-test
          env:
            - name: HOST
              value: $(SERVICE_NAME)
          command: ['sh', '-c', 'printenv; echo $(SERVICE_NAME); echo $HOST']
  backoffLimit: 0
```

**Job Kustomize substitution**
```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    env: test
  name: test-some-job
spec:
  template:
    ...
    spec:
      containers:
        env:
        - name: HOST
          value: test-service
      initContainers:
      - command:
        - sh
        - -c
        - printenv; echo $(SERVICE_NAME); echo $IAM_HOST
        env:
        - name: HOST
          value: $(SERVICE_NAME)
        name: init-test
```

The same setup for Jobs. First as exptected `$(SERVICE_NAME)` gets substituted with `test-service` but only the variable in the `container` section! Everything under `initContainers` remains as is. If I change the type from `Job` to `Deployment` the substitution works as expected.

Is this a known issue?

My current workaround is to to patch the values with an overlay instead of using the variables.
