### ISSUE TITLE
`kustomize` changed my file mode from `mode: 0755`  to `mode: 493` in configMap volume

### ISSUE THREAD

**Issue by dove-young** [kubernetes-sigs/kustomize#1790]
Here is my kustomization,  its quite weird that `kustomize` changed my file mode from `mode: 0755`  to `mode: 493`. 

```
[root@worker3 kust-issue]# cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flatten.yaml
[root@worker3 kust-issue]# cat flatten.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-db
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: test-db
        image: alpine:curl
        env:
          - name: PAYLOAD
            value: /tmp/payload/raw-payload.json
        command:
        - /tmp/test-sh/test.sh
      volumes:
      - name: payload
        configMap:
          name: release-name-postgresql-init
          items:
          - key: raw-payload
            path: raw-payload.json
      - name: script
        configMap:
          name: release-name-postgresql-init
          items:
          - key: test-sh
            path: test.sh
            mode: 0755                  <---------------
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure

```

Here is the result

```
[root@worker3 kust-issue]# kustomize build .
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: test-db
spec:
  template:
    spec:
      containers:
      - command:
        - /tmp/test-sh/test.sh
        env:
        - name: PAYLOAD
          value: /tmp/payload/raw-payload.json
        image: alpine:curl
        name: test-db
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      volumes:
      - configMap:
          items:
          - key: raw-payload
            path: raw-payload.json
          name: release-name-postgresql-init
        name: payload
      - configMap:
          items:
          - key: test-sh
            mode: 493                  <---------------
            path: test.sh
          name: release-name-postgresql-init
        name: script
```
