### ISSUE TITLE
Transformer exec plugin issue: 

### ISSUE THREAD

**Issue by amitsaha** [kubernetes-sigs/kustomize#1817]
Hi all, I am trying to write a `transformer` exec plugin to replace the name of an overlayed-manifest by something else. The transformation plugin is invoked correctly, but then `kustomize` complains that it cannot find a unique match i.e. is it trying to overlay again? The complete reproducer can be found [here](https://github.com/amitsaha/kustomize-plugin-demo).Of note is my overlay's kustomization file which looks like:

```yaml
namespace: myns
nameSuffix: -qa
bases:
- ../base/
patches:
- db_migration.yaml
images:
- name: some/image
  newTag: develop-{{RELEASE_TAG}}
transformers:
  - NameReplacer.yaml

```
Essentially, what I get from the above is:

```
$ XDG_CONFIG_HOME=./plugin kustomize build --enable_alpha_plugins
Error: unable to find unique match to batch_v1_Job|myns|db-migration-new-qa
```
I was expecting that the plugin based transformers run after all the other things have been done? I can also verify it by what my exec plugin gets as input which is the overlayed file:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kustomize.config.k8s.io/id: |
      group: batch
      kind: Job
      name: db-migration-qa
      namespace: myns
      version: v1
  name: db-migration-qa
  namespace: myns
spec:
  template:
    spec:
      containers:
      - env:
        - name: TRUNCATE_DATABASE
          value: "true"
        - name: ENVIRONMENT
          value: qa
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: secret-token
        image: some/image:develop-{{RELEASE_TAG}}
        name: db-migration
      nodeSelector:
        environment: qa
        nodegroup: x1
      restartPolicy: OnFailure
```

Kustomize version:

```
 kustomize version
Version: {KustomizeVersion:3.2.0 GitCommit:a3103f1e62ddb5b696daa3fd359bb6f2e8333b49 BuildDate:2019-09-18T16:26:36Z GoOs:linux GoArch:amd64}
```

Any ideas would be appreciated as to what I am doing wrong?
