### ISSUE TITLE
SecretGenerator not working from a multi-tier overlay configuration

### ISSUE THREAD

**Issue by RolandTa** [kubernetes-sigs/kustomize#1825]
Hi

We have a multi-tier overlay configuration like Base <- Prod <- CustomerA where we define different kind of configurations similar to:

base\kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podsecurity.yaml
- deployment.yaml
- ...
```

base-overlay\prod\kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namePrefix: prod-
images:
- name: myimage
  newTag: 1.0.0.42
```

overlays\prod\customer-a
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../base-overlays/prod
namespace: prod-customer-a
nameSuffix: -customer-a
commonLabels:
  app: customer-a
  name: customer-a
secretGenerator:
- name: secret-appsettings
  files:
    - config/appsettings.secrets.json
  type: Opaque
```

Everything works fine, except that the secretgenerator is not working on the level of the overlays\prod\customer-a - if I move the configuration part of the secret-generator down a level to the base-overlay/prod/kustomization.yaml everything works as expected - the secret generator is defining a secret with a name like prod-secret-appsettings-customera-dt5c4bgfgfg and reference it correctly into my usage of a deployment.
