### ISSUE TITLE
configMapRef and secretRef in envFrom are not merged correctly

### ISSUE THREAD

**Issue by rihardssceredins** [kubernetes-sigs/kustomize#1835]
I've created a simple sample to demonstrate the incorrent behaviour. I'm trying to append `secretRef` in `envFrom` with patchesStrategicMerge but after merge `configMapRef` is missing from `envFrom`. Am I correct in thinking that this should work as I've shown in expected output? 🤔
I also tested a similar use case with `volumeMounts` (seen in examples below) and it works correctly.

**Version of kustomize:**
`{Version:3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T05:15:32+01:00 GoOs:darwin GoArch:amd64}`

**deployment.yaml:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: php
          image: php:latest
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
          envFrom:
            - configMapRef:
                name: some-config
        - name: redis
          image: redis:latest
```

**patch.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: php
          volumeMounts:
            - name: sock
              mountPath: /sock
          envFrom:
            - secretRef:
                name: some-secret
```

**kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

patchesStrategicMerge:
  - patch.yaml
```

**Current output** of `kustomize build`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: some-secret
        image: php:latest
        name: php
        volumeMounts:
        - mountPath: /sock
          name: sock
        - mountPath: /etc/nginx/conf.d
          name: config
      - image: redis:latest
        name: redis
```

**Expected output** of `kustomize build`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: some-config
        - secretRef:
            name: some-secret
        image: php:latest
        name: php
        volumeMounts:
        - mountPath: /sock
          name: sock
        - mountPath: /etc/nginx/conf.d
          name: config
      - image: redis:latest
        name: redis
```

**Comment by MortlMcCrisis** [comment]
Any progress on this issue? I am facing the same problem and would be happy about a fix.

**Comment by rihardssceredins** [comment]
@MortlMcCrisis haven't done anything in Go so I wouldn't even know where to start.. :D

Any idea how to get someone's attention?

**Comment by rihardssceredins** [comment]
Tested once again with kustomize 3.8.1 and `envFrom` is still overwritten after merge.

**Comment by Gikkman** [comment]
Also ran into this issue today. Pulled a good chunk of hair out wondering what I was doing wrong at first but now that I know of this issue, I could work around it. Would be good to address though

**Comment by mleklund** [comment]
I also ran into this.

**Comment by mleklund** [comment]
Nevermind, it was not having matching namespaces between cm/secrets and doployment, again.

**Comment by harirajanv** [comment]
any luck with the issue. I still have exactly the same issue. 
Issue:
the original resource  deployment file has  couple of configMapRef
     envFrom:
        - configMapRef:
            name: first
        - configMapRef:
            name: second

then you use patchesStrategicMerge:   to include another yaml that has some _more_ envFrom
     envFrom:
        - configMapRef:
            name: third

expectation was that , the output would have all the three configMapRef.  but in actual. instead of adding the  third configmapref, it is overwritting it and you end with only the 'name: third'  in the result.
patchesStrategicMerge  as the name, should have merged  it instead of overwrite.
Thaanks.

**Comment by Shell32-Natsu** [comment]
Explanation: https://github.com/kubernetes-sigs/kustomize/issues/3047#issuecomment-701014534

> Strategic Merge Patch doesn't merge arbitrary lists. Kustomize can only merge the lists in the resources that can be merged (merge key defined in k8s). When it comes to unknown resource like in this issue, the list in the patch will replace the list in the original resource. Try to use JSON 6902 patch.

Example JSON 6902 patch:
```
resources:
- deployment.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        secretRef:
          name: some-secret
  target:
    kind: Deployment
```
