### ISSUE TITLE
cmd/config: Create base image for writing Helm functions

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#1843]
Assignee: @artmello 

1. create a new directory in the kustomize root: `functions/helm`
2. define an API schema for running helm charts
3. write a *function* (in go) which implements the API
  - use helm template to expand the configuration -- either exec or vendor helm libraries
  - uses the kustomize kyaml libraries to merge the results back into the input

- first iteration should read the helm chart from disk and expect it in the same directory as the function config
- should use the values file in the function config if specified

Example function config:

```yaml
apiVersion: config.kubernetes.io/v1alpha1
kind: HelmChart
spec:
  chart:
    path: path/to/chart
  values:
    embedded: values
  mergeStrategy: merge|replace
```

Running `docker build` on the Docker file should produce an image implementing what is shown.
