### ISSUE TITLE
`$patch: delete` doesn't support CRD

### ISSUE THREAD

**Issue by icy** [kubernetes-sigs/kustomize#1846]
I have a patch file as below

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: metrics

$patch: delete

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx

$patch: delete
```

The second directive works fine (`serviceaccount` is deleted), but the first one doesn't work, its output is as below

```
---
$patch: delete
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus/server: default
  name: nginx-ingress-controller-metrics
  namespace: metrics
spec:
  endpoints:
  - interval: 15s
    port: metrics
  namespaceSelector:
    matchNames:
    - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
```
