### ISSUE TITLE
Add support for attaching schema to function images -- explain

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#1852]
Depends on #1771 

We should allow function images run by `kustomize config run-fns` to attach schema for the api type(s) they support.  Similar to `kubectl explain`, but flattened.

```sh
kustomize config explain gcr.io/example.com/image:v1.0.0

APIVERSION:  example.com/v1beta1
KIND:     Example

DESCRIPTION:
     Example modifies Resource configuration by...

FIELDS:
   apiVersion	<string>
   kind	<string>
   metadata	<Object>: Object metadata.
      name: <string>: Name is the...
   spec	<Object>: Specification of the desired behavior of the Deployment.
      foo <string>: Foo is the...
      bar <string>: Bar is the...
   status	<Object>
     ...

```

**Comment by seaneagan** [comment]
Currently it looks like function metadata such as container image, network, volumes, and presumably now schema, is embedded into each resource consumed by the function. Has it been considered to have a common location to define this metadata. Something similar to a subset of CRD:

```yaml
apiVersion: "config.kubernetes.io/v1alpha1"
kind: "Function"
metadata:
  name: "myfunction.org.example"
spec:
  group: "org.example"
  names:
    Kind: MyFunction
  versions:
    - name: v1alpha1
      container:
        image: docker.io/example/myfunction
        network: true
        volumes: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                myprop:
                  type: string
```

and then it can be referenced as:

```yaml
apiVersion: org.example/v1alpha1
kind: MyFunction
spec:
  myprop: foo
```
