### ISSUE TITLE
Gettit error: AccumulateTarget: couldn't find target

### ISSUE THREAD

**Issue by bharatjarwal** [kubernetes-sigs/kustomize#1857]
Hi Team,

I am trying to apply network policy on my app with kustomize but I am getting below error. If possible can someone guide me to fix this.

$ kubectl apply --kustomize='./' --record
error: AccumulateTarget: couldn't find target networking.k8s.io_v1_NetworkPolicy|default|~P|myapp|~S for json patch

**Here is my yaml file**
```
cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- overlay.yaml
patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
    name: myapp
    namespace: default
  path: netpol-patch.yaml
```

**Here is my netpol yaml file**

```
cat netpol-patch.yaml
- op: add
  path: /spec/egress/-
  value:
    to:
    ports:
    # Allow all outbound
    - port: 443
```
