### ISSUE TITLE
transform service name in ingress object

### ISSUE THREAD

**Issue by leopay** [kubernetes-sigs/kustomize#1858]
I have a file structure as follows:
```shell
├── base
│   ├── kustomization.yaml
│   └── service.yaml
└── component
    ├── bar
    │   └── kustomization.yaml
    ├── foo
    │   └── kustomization.yaml
    ├── ingress.yaml
    └── kustomization.yaml
```
base/service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: dummy
spec:
  selector:
    app: dummy
  ports:
    - port: 80
```

cat component/foo/kustomization.yaml
```yaml
resources:
- ../../base
namePrefix: test-
patches:
- patch: |-
    - op: replace
      path: "/metadata/name"
      value: "foo"
  target:
    kind: Service
```
cat component/foo/kustomization.yaml
```yaml
resources:
- ../../base
namePrefix: test-
patches:
- patch: |-
    - op: replace
      path: "/metadata/name"
      value: "bar"
  target:
    kind: Service`
cat component/kustomization.yaml
`resources:
  - foo
  - bar
  - ingress.yaml
```
cat component/ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: foo
          servicePort: 80
        path: /foo
      - backend:
          serviceName: bar
          servicePort: 80
        path: /bar
```
run kustomize build component

```yaml
apiVersion: v1                                                                                                                                     
kind: Service                                                                                                                                      
metadata:                                                                                                                                          
  name: test-bar                                                                                                                                   
spec:                                                                                                                                              
  ports:                                           
  - port: 80
  selector:
    app: dummy
---
apiVersion: v1
kind: Service
metadata:
  name: test-foo
spec:
  ports:
  - port: 80
  selector:
    app: dummy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: foo   //expect test-foo
          servicePort: 80
        path: /foo
      - backend:
          serviceName: bar //expect test-bar
          servicePort: 80
        path: /bar
```
