### ISSUE TITLE
configmapGenerator generated no | or |+ for file contains trailing whitespace

### ISSUE THREAD

**Issue by manlme** [kubernetes-sigs/kustomize#1868]
I'm trying to use kustomize to generate configmap from promethues alerts, rules and its configuration.
I need to keep the file unchanged when generating configmap. 

```
kustomize version
Version: {Version:3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-10-03T19:25:14+01:00 GoOs:darwin GoArch:amd64}
```
here is the kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: prometheus-server
  files:
  - alerts
```
alerts (whitespace contains at the end of kubernetes-apps)

```
groups:
- "name": "kubernetes-apps" 
  "rules":
  - "alert": "KubePodCrashLooping"
    "annotations":
      "message": "Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf \"%.2f\" $value }} times / 5 minutes."
      "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping"
    "expr": |
      rate(kube_pod_container_status_restarts_total{job="kubernetes-state-metrics"}[15m]) * 60 * 5 > 0
    "for": "15m"
    "labels":
      "severity": "critical"
```
kustomize build  output 

```
apiVersion: v1
data:
  alerts: "groups:\n- \"name\": \"kubernetes-apps\" \n  \"rules\":\n  - \"alert\":
    \"KubePodCrashLooping\"\n    \"annotations\":\n      \"message\": \"Pod {{ $labels.namespace
    }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf \\\"%.2f\\\"
    $value }} times / 5 minutes.\"\n      \"runbook_url\": \"https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping\"\n
    \   \"expr\": |\n      rate(kube_pod_container_status_restarts_total{job=\"kubernetes-state-metrics\"}[15m])
    * 60 * 5 > 0\n    \"for\": \"15m\"\n    \"labels\":\n      \"severity\": \"critical\"\n"
kind: ConfigMap
metadata:
  name: prometheus-server-582ft7fk6f
```

after removing the trailing whitespace. output for kustomize build .
```
apiVersion: v1
data:
  alerts: |
    groups:
    - "name": "kubernetes-apps"
      "rules":
      - "alert": "KubePodCrashLooping"
        "annotations":
          "message": "Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf \"%.2f\" $value }} times / 5 minutes."
          "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping"
        "expr": |
          rate(kube_pod_container_status_restarts_total{job="kubernetes-state-metrics"}[15m]) * 60 * 5 > 0
        "for": "15m"
        "labels":
          "severity": "critical"
kind: ConfigMap
metadata:
  name: prometheus-server-85d4ffg9ct
```
