### ISSUE TITLE
duplicate "patches:" sections in kustomization.yaml are not cumulative

### ISSUE THREAD

**Issue by hornpolish** [kubernetes-sigs/kustomize#1878]
if i repeat a section of the kustomization.yaml, the contents of the first section are silently ignored.  this was unexpected.

our use case as an ISV is we ship a fairly vanilla base; and a "library of example kustomizations".
we'd like a customer workflow to be "cat ex1 ex3 ex7 >>kustomization.yaml" once they determine 1,3,7 are appropriate for their setup.

the rest of this issue is in the markdown style of the ./examples folder.  as written, only patch2 gets into the rendered yaml.  of course, if you put both -path's under one patches: you get what you wanted

# Demo: patches do not accumulate (maybe they should)

Define a place to work:

```
DEMO_HOME=$(mktemp -d)

cat <<EOF >$DEMO_HOME/kustomization.yaml
resources:
- pod.yaml
patches:
- path: patch1.yaml
  target:
    kind: Pod
patches:
- path: patch2.yaml
  target:
    kind: Pod
EOF

cat <<EOF >$DEMO_HOME/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: busybox:1.29.0
    command: ['sleep 3600']
EOF

cat <<EOF >$DEMO_HOME/patch1.yaml
- op: add
  path: /spec/labelSelector
  value:
    patch1: was-here
EOF

cat <<EOF >$DEMO_HOME/patch2.yaml
- op: add
  path: /spec/nodeSelector
  value:
    patch2: was-here-too
EOF
```

Now build this `kustomization`

```
kustomize build $DEMO_HOME
```

Confirm that both labelSelector and nodeSelectors are there

```
test 2 = \
  $(kustomize build $DEMO_HOME | grep was-here | wc -l); \
  echo $?
```
