### ISSUE TITLE
volumeClaimTemplates/spec/accessModes missing when specified in base

### ISSUE THREAD

**Issue by george-angel** [kubernetes-sigs/kustomize#190]
Base `Statefulset` contains:

```
...
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: ebs-gp2
```

My patch contains:

```
...
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 15Gi
      storageClassName: pd-standard
```

And kustomize build produces:

```
...
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 15Gi
```

Also `storageClassName` completely disappears.

**Comment by Liujingfang1** [comment]
It looks like the content for `volumeClaimTemplates` from the patch overrides the base `volumeClaimTemplates`.  You can add `accessModes` in the patch as well.

**Comment by george-angel** [comment]
I can, is that the intended behaviour?

And (2) - `storageClassName` disappears from the rendered output, even when specified in both base and patch.

**Comment by Liujingfang1** [comment]
@george-angel `storeageClassName` shouldn't disappear. Please double check the output.

**Comment by george-angel** [comment]
base file:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  labels:
    kubernetes.io/ingress.class: traefik-private
  annotations:
    external-dns.alpha.kubernetes.io/target: in-k8s.base.domain
spec:
  rules:
  - host: prometheus.base.domain
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/affinity: "true"
    traefik.backend.loadbalancer.stickiness: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
  labels:
    name: prometheus
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9090
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-peers
spec:
  clusterIP: None
  ports:
  - name: cluster
    port: 10900
    targetPort: cluster
  selector:
    # Useful endpoint for gathering all thanos components for common gossip cluster.
    thanos-peer: "true"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prometheus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
      thanos-peer: "true"
  serviceName: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
        role: prometheus
        service: prometheus
        thanos-peer: "true"
    spec:
      terminationGracePeriodSeconds: 1200
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - prometheus
              topologyKey: kubernetes.io/hostname
            weight: 100
      securityContext:
        runAsUser: 0
      containers:
      - name: prometheus
        image: prom/prometheus:v2.3.1
        env:
        - name: WEB_EXTERNAL_URL
          value: https://prometheus.base.domain
        args:
          - --config.file=/etc/prometheus-shared/prometheus-config.yaml
          - --storage.tsdb.path=/prometheus/data
          - --storage.tsdb.retention=24h
          - --storage.tsdb.min-block-duration=2h
          - --storage.tsdb.max-block-duration=2h
          - --web.external-url=$(WEB_EXTERNAL_URL)
          - --web.enable-lifecycle
          - --web.console.libraries=/usr/share/prometheus/console_libraries
          - --web.console.templates=/usr/share/prometheus/consoles
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 4
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 4
          successThreshold: 1
        ports:
        - name: web
          containerPort: 9090
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 4000m
            memory: 4000Mi
        volumeMounts:
        - name: prometheus-config-shared
          mountPath: /etc/prometheus-shared
        - name: data
          mountPath: /prometheus
        - name: prometheus-alerts
          mountPath: /etc/alerts
      - name: thanos-sidecar
        image: improbable/thanos:master-2018-06-28-71d519f
        args:
        - sidecar
        - --log.level=warn
        - --tsdb.path=/prometheus/data
        - --prometheus.url=http://127.0.0.1:9090
        - --cluster.peers=thanos-peers.sys-prom:10900
        - --cluster.peers=thanos-peers.sys-mon:10900
        - --cluster.peers=thanos-peers.telecom:10900
        - --reloader.config-file=/etc/prometheus/prometheus-config.yaml
        - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus-config.yaml
        - --reloader.rule-dir=/etc/alerts/..data/
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        volumeMounts:
        - name: data
          mountPath: /prometheus
        - name: prometheus-config-shared
          mountPath: /etc/prometheus-shared
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-alerts
          mountPath: /etc/alerts
      volumes:
        - name: prometheus-config-shared
          emptyDir: {}
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-alerts
          projected:
            sources:
              - configMap:
                  name: prometheus-alerts
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: ebs-gp2
```

patch:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    external-dns.alpha.kubernetes.io/target: xxxxxxxxxx
spec:
  rules:
  - host: xxxxxxxxxxxx
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
      - name: prometheus
        env:
        - name: WEB_EXTERNAL_URL
          value: xxxxxxxxxxxxxxx
        resources:
          requests:
            cpu: 250m
            memory: 1500Mi
          limits:
            cpu: 2500m
            memory: 1500Mi
      - name: thanos-sidecar
        env:
        - name: S3_ACCESS_KEY
          value: xxxxxxxxxxxxxxxx
        - name: S3_BUCKET
          value: xxxxxxxxxxxxxxxx
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 15Gi
```

output:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: sys-prom
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
      thanos-peer: "true"
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        role: prometheus
        service: prometheus
        thanos-peer: "true"
      name: prometheus
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - prometheus
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --config.file=/etc/prometheus-shared/prometheus-config.yaml
        - --storage.tsdb.path=/prometheus/data
        - --storage.tsdb.retention=24h
        - --storage.tsdb.min-block-duration=2h
        - --storage.tsdb.max-block-duration=2h
        - --web.external-url=$(WEB_EXTERNAL_URL)
        - --web.enable-lifecycle
        - --web.console.libraries=/usr/share/prometheus/console_libraries
        - --web.console.templates=/usr/share/prometheus/consoles
        env:
        - name: WEB_EXTERNAL_URL
          value: xxxxxxxxxxxxxxxx
        image: prom/prometheus:v2.3.1
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: web
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: prometheus
        ports:
        - containerPort: 9090
          name: web
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/ready
            port: web
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 2500m
            memory: 1500Mi
          requests:
            cpu: 250m
            memory: 1500Mi
        volumeMounts:
        - mountPath: /etc/prometheus-shared
          name: prometheus-config-shared
        - mountPath: /prometheus
          name: data
        - mountPath: /etc/alerts
          name: prometheus-alerts
      - args:
        - sidecar
        - --log.level=warn
        - --tsdb.path=/prometheus/data
        - --prometheus.url=http://127.0.0.1:9090
        - --cluster.peers=thanos-peers.sys-prom:10900
        - --cluster.peers=thanos-peers.sys-mon:10900
        - --cluster.peers=thanos-peers.telecom:10900
        - --reloader.config-file=/etc/prometheus/prometheus-config.yaml
        - --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus-config.yaml
        - --reloader.rule-dir=/etc/alerts/..data/
        env:
        - name: S3_ACCESS_KEY
          value: xxxxxxxxxxxxxxxx
        - name: S3_BUCKET
          value: xxxxxxxxxxxxxxxx
        image: improbable/thanos:master-2018-06-28-71d519f
        name: thanos-sidecar
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
        - containerPort: 10900
          name: cluster
        volumeMounts:
        - mountPath: /prometheus
          name: data
        - mountPath: /etc/prometheus-shared
          name: prometheus-config-shared
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /etc/alerts
          name: prometheus-alerts
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 1200
      volumes:
      - emptyDir: {}
        name: prometheus-config-shared
      - configMap:
          name: prometheus-config-g66g862dmm
        name: prometheus-config
      - name: prometheus-alerts
        projected:
          sources:
          - configMap:
              name: prometheus-alerts
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 15Gi
```

**Comment by Liujingfang1** [comment]
@george-angel Sorry I didn't make myself clear. You need to include both `accessModes` and `storageClassName` in the patch as following
```
 volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 15Gi
      storageClassName: pd-standard
```
