### ISSUE TITLE
Support exposing network as a function option

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#1901]
Assigned To: `Eddie Zaneski`

Context: `kustomize config run`

Functions should be able to request access to the network in the Resource metadata.

e.g.

```
apiVersion: v1beta1
kind: Foo
metadata:
  name: foo
  configFn:
    container:
      image: gcr.io/kustomize-functions/example-tshirt:v0.1.0
      network:
        required: true
```

- `kustomize config run` should accept the flag `--network`, which will enable network *only* on functions which have specified it as a requirement.
- if a function specifies `configFn.container.network.required=true`, and the flag is not provided, then `kustomize config run` should exit failure and print an error message.
- `kustomize config run` should validate all input Resource preconditions are met (e.g. network) before attempting to run any of them

Example:

```sh
kustomize config run DIR/
error: function Foo.foo (DIR/function.yaml) requires network to be enabled with the --network flag.  only do this if the container is trusted to run with network access.
``` 

## Files to change

- `cmd/config/run-fns.go`: add the flag and pass them to the `RunFns` struct in the `runE` function
- `kyaml/runfn/runfn.go`: 
  - Pass-through the flag
  - In `init` -- have the `containerFilterProvider` function check if the container requires network and if the network is enabled.
  - If the container requires network and it is not enabled, return an error
  - If the container does not require network, do not enable network
  - If the container requires network and it is enabled, enable network on the container
