### ISSUE TITLE
resource in namespace cannot reference the resource without namespace

### ISSUE THREAD

**Issue by haohaolee** [kubernetes-sigs/kustomize#1982]
Hi folks,
I am using cert-manager now, which contains a global resource `ClusterIssuer`, I want to declare a certificate in a namespace which references the ClusterIssuer, but it doesn't work.
Here is a demo to reproduce this issue:
```
$ tree .
.
├── cert
│   ├── cert.yaml
│   └── kustomization.yaml
├── issuer
│   ├── issuer.yaml
│   └── kustomization.yaml
├── kustomization.yaml
└── kustomizeconfig.yaml
```
```yaml
# cert/cert.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-test
spec:
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
```

```yaml
# cert/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-ns # adding this namespace leads to unexpected result 
resources:
- ./cert.yaml
```

```yaml
# issuer/issuer.yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
```
```yaml
# issuer/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./issuer.yaml
```

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -test
resources:
- ./issuer
- ./cert

configurations:
- ./kustomizeconfig.yaml
```

```yaml
# kustomizeconfig.yaml
nameReference:
- kind: ClusterIssuer
  fieldSpecs:
  - path: spec/issuerRef/name
    kind: Certificate
```
=============================================
`kustomize build .`
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-test-test
  namespace: test-ns
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-test
```

=============================================
if remove the namespace, we can get the right result: the cert can reference the issuer correctly
```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-test-test
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer-test
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-test
```

Thanks
