### ISSUE TITLE
`kustomize config run`: Add support for config.k8s.io/function annotation

### ISSUE THREAD

**Issue by frankfarzan** [kubernetes-sigs/kustomize#1990]
It's desirable to use any object type as functionConfig. Example:

```yaml
apiVersion: example.com/v1beta1
kind: Nginx
metadata:
  name: my-instance
  annotations:
    config.kubernetes.io/local-config: "true"
    config.k8s.io/function: |
      container:
        image: gcr.io/example-functions/nginx-template:v1.0.0
spec:
  replicas: 5
```
