### ISSUE TITLE
Variants for array elements not working?

### ISSUE THREAD

**Issue by galderz** [kubernetes-sigs/kustomize#1997]
What kind of variant would you need to only replace [this field](https://github.com/infinispan/infinispan-operator/blob/master/deploy/olm-catalog/infinispan-operator.clusterserviceversion.yaml#L181):

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: infinispan-operator
  namespace: placeholder
spec:
  install:
    spec:
      deployments:
        - name: infinispan-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: infinispan-operator-alm-owned
            template:
              metadata:
                name: infinispan-operator-alm-owned
                labels:
                  name: infinispan-operator-alm-owned
              spec:
                serviceAccountName: infinispan-operator
                containers:
                  - name: infinispan-operator
                    command:
                      - infinispan-operator
                    image: jboss/infinispan-operator:latest
                    ports:
                      - containerPort: 60000
                        name: metrics
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "infinispan-operator"
                      - name: DEFAULT_IMAGE
->                     value: "infinispan/server:latest"
```

Applying this:

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: infinispan-operator
  namespace: placeholder
spec:
  install:
    spec:
      deployments:
      - name: infinispan-operator
        spec:
          template:
            spec:
              containers:
              - name: infinispan-operator
                env:
                - name: DEFAULT_IMAGE
                  value: "infinispan/server:10.1.0.CR1-1"
```

Results in lot of data lost:

```
  install:
    spec:
      deployments:
      - name: infinispan-operator
        spec:
          template:
            spec:
              containers:
              - env:
                - name: DEFAULT_IMAGE
                  value: infinispan/server:10.1.0.CR1-1
                name: infinispan-operator
```
