### ISSUE TITLE
Use openapi to apply correct field types in `fmt`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#2003]
depends on #2004

yaml 1.1 supports a lot of ambiguous values that parse to bool such as `yes` and `on`.  when putting these unquoted as field values -- e.g. in container args, they will be interpreted as booleans.

We should use the openapi for Kubernetes, and support loading jsonschema / openapi from files in format, and then format each field so that they are correctly parsed in yaml 1.1

e.g. 

```yaml
spec:
  template:
    spec:
      containers:
        args:
        - on
```

should be formatted as

```yaml
spec:
  template:
    spec:
      containers:
        args:
        - "on"
```

Because `spec.template.spec.containers.args` has type []string, but yaml 1.1 will parse it as []bool

Steps:

- Add openapi as a field [here](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/kio/filters/fmtr.go#L57).
- Get the openapi from upstream Kubernetes
- Write a function that returns the type from a given field path
- When formatting a node, lookup the type from the path (already calculated)
- If the value will be parsed as a non-string value by yaml 1.1, but the field type is a string, quote the field
- If the value is quoted, but the field type is a non-string, unquote the value and apply the correct `Tag` -- e.g. `!!int`, `!!bool`
