### ISSUE TITLE
GCP BackendConfig Support

### ISSUE THREAD

**Issue by ymym3412** [kubernetes-sigs/kustomize#2013]
I try to apply Cloud IAP to my GKE resources.  
For Cloud IAP settings, I have to create `BackendConfig` resource .
https://cloud.google.com/iap/docs/enabling-kubernetes-howto?hl=en

I have created Secret resource by kustomize secretGenerator.

```yaml
namespace: demo

resources:
- deployment.yaml
- backend-config.yaml

secretGenerator:
- name: credentials
  files:
    - client_id
    - client_secret
```

By default, secretGenerator create Secret resource with hash suffix.  And kustomize also add hash suffix in other resources like Deployment.  

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ...

      volumes:
      - name: credentials
        secret:
          secretName: credentials-btbff69c76
``` 

But, kustomize don't add hash suffix in `BackendConfig` resource's  `spec.iap.oauthclientCredentials.secretName` .  

```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: config-default
  namespace: demo
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: credentials
```

Because of above,  BackendConfig says not found error `BackendConfig default/config-default is not valid: error retrieving secret "credentials": secrets "credentials" not found.`.

So I want `BackendConfig` resource support of secretGenerator.
