### ISSUE TITLE
Ordering of output results

### ISSUE THREAD

**Issue by sleepycat** [kubernetes-sigs/kustomize#202]
Is there a way to control the order of the resources?
Since the order these resource appear in seems to matter, I'm wondering what the recommended way of controlling that order is. 

In my case, I need to create some RBAC stuff before a resource then tries to use it. I experimented with the order of the `kustomization.yaml` hoping that this

```yaml
bases:
  - ../../base
resources:
  - traefik-config.yaml
  - cluster-admin-role.yaml
  - certs-claim.yaml
patches:
  - deployment.yaml
  - traefik.yaml
```
Would produce different output than this
```yaml
resources:
  - cluster-admin-role.yaml
  - traefik-config.yaml
  - certs-claim.yaml
bases:
  - ../../base
patches:
  - deployment.yaml
  - traefik.yaml
```
It does not. According to #65 input is sorted and now namespaces are special cased and ordered first. Which would explain what is going on.

In that issue @monopole mentioned that "To preserve general order as specified in the kustomization files, across all the mapping and merging, would require a more powerful approach, e.g. upon first read establish some kind of order index, and use that index when spitting things back out."

This sounds like exactly what I tried, so my question is... is this a feature that could/should/might be added to kustomize?
