### ISSUE TITLE
no matches for OriginalId with PersistentVolume 

### ISSUE THREAD

**Issue by huytn12** [kubernetes-sigs/kustomize#2050]
How to reproduce:

- Kustomize: 3.5.3
- base/kustomization.yaml:

```
resources:
 - deployment.yaml
 - service.yaml
 - pvc.yaml
 - pv.yaml
```

- base/pv.yaml

```
 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: gearman-pv
 spec:
   storageClassName: normal
   capacity:
     storage: 2Gi
   accessModes:
     - ReadWriteOnce
     - ReadWriteMany
   hostPath:
     path: TO_BE_MODIFIED
```
- overlays/dev/pv.yaml
```
 bases:
 - ../../base
 patchesStrategicMerge:
 - pv.yaml
```
- overlays/dev/kustomization.yaml
```
 bases:
 - ../../base
 patchesStrategicMerge:
 - pv.yaml
```

- error after running `kustomize build dev`

> Error: no matches for OriginalId ~G_~V_PersistentVolume|default|gearman-pv-local; no matches for CurrentId ~G_~V_PersistentVolume|default|gearman-pv-local; failed to find unique target for patch ~G_~V_PersistentVolume|gearman-pv-local

Note:
I tried to add  `namespace: default` to the **pv.yaml** in overlays but it didn't help.
