### ISSUE TITLE
Can't delete a CRD, neither via strategic merge, nor via Json Patch

### ISSUE THREAD

**Issue by dmayle** [kubernetes-sigs/kustomize#2056]
I have a base document that I don't control containing CRD elements (argoproj.io/v1alpha1 Application).

I need to delete these objects using kustomize, but a strategic merge patch is failing, I imagine because it's a CRD (it just inserts the $patch: delete key-value rather than deleting the object).

I'm trying to use a json patch, but I cant target the path '/', so I have to remove the individual keys: apiVersion, metadata, spec.

Finally, 'kind' can't be removed via the json patch, and setting the value to 'nil' means I have a bunch of strange objects in my output:
```
kind: nil
---
kind: nil
---
kind: nil
---
kind: nil
---
kind: nil
---
kind: nil
---
kind: nil
---
kind: nil
```

Example base file:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd
    repoURL: git@url
    targetRevision: HEAD
```

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1¬                                                                                                                 kind: Kustomization¬

bases:¬
- ../../base¬

patchesJson6902:¬
- target:¬
    group: argoproj.io¬
    version: v1alpha1¬
    kind: Application¬
    name: argo-cd
    namespace: argocd
  path: patches/hide-application.yaml¬
```

patches/hide-application.yaml
```
- op: remove
  path: /apiVersion
- op: remove
  path: /metadata
- op: remove
  path: /spec
- op: replace
  path: /kind
  value: nil
```
Is there anything I can do?
