### ISSUE TITLE
Fine grained version checking

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/kustomize#2073]
I have a kustomization that does [this](https://github.com/jpeach/kustomize/blob/master/contour/base/kustomization.yaml):

```
vars:
- name: CONTOUR_XDS_PORT
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: contour
  fieldref:
    fieldpath: spec.template.spec.containers[0].ports[0].containerPort
- name: ENVOY_HTTP_PORT
```

This works with kustomize 3.5.3 but not with kubectl 1.17.0. It would be great to be able to signal which tool version a kustomization depends on.
