### ISSUE TITLE
Support explicit declarative functions for `config run`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#2087]
We should think about how functions are declared.  Currently it is implicit by being in the directory that is run.  We should consider making it explicit with a `functions.yaml` or something which explicitly declares each function that is run.  This will make it simpler to understand what happens when `config run` is called

```yaml
apVersion: config.kubernets.io/v1alpha1
kind: FunctionsList
items:
- path: path/to/function.yaml # scoped globally
- path: other/path/function.yaml
   scope: resources/ # scoped to resources

```
