### ISSUE TITLE
In case namePrefix config/secret not found, how to use upper level ones?

### ISSUE THREAD

**Issue by brunoluiz** [kubernetes-sigs/kustomize#2091]
I have a kustomize overlay which works quite well for one service. If I understood correctly, `namePrefix` transformer would allow me to create multiple services using the same template. The issue is that some of the resources might not need prefixing, such as `spec.template.spec.imagePullSecrets`.This, for example, leads to image pull error. 

Is there a way to filter this specific field when applying the `namePrefix`? Or perhaps a way to make it fallback to upper level configs (the one without the prefix)?

**Comment by yujunz** [comment]
You may add the builtin PrefixSuffixTransformer as a resource which allows specifying the `fieldSpecs`, e.g.

```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: suffix
suffix: -service
fieldSpecs:
  - kind: Secret
    path: metadata/name
```

n.b. there is a known bug with name reference. See #1695
