### ISSUE TITLE
Base namePrefix is ignored

### ISSUE THREAD

**Issue by martinhanzik** [kubernetes-sigs/kustomize#2106]
The following example reproduces my issue.

Setup:
```bash
EXAMPLE=$(mktemp -d)
mkdir -p ${EXAMPLE}/base
cat <<'EOF' >${EXAMPLE}/base/kustomization.yaml
namePrefix: app-
EOF
cat <<'EOF' >${EXAMPLE}/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: test
        name: test
EOF
cat <<'EOF' >${EXAMPLE}/kustomization.yaml
nameSuffix: -staging

resources:
  - base
  - deployment.yaml
EOF

```

```
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T06:57:29+00:00 GoOs:darwin GoArch:amd64}
```

Test:
```bash
kustomize build ${EXAMPLE}
```

Result:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-staging
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: test
        name: test
```

Expectations:
I expected name to be `app-web-staging` - applying both the namePrefix from base and nameSuffix from overlay.
Resources added to the base get both the prefix and suffix, resources in overlay don't get the prefix. Additional namePrefix specified in overlay applies to all resources.
