### ISSUE TITLE
unable to use configmap generator with daemonsets

### ISSUE THREAD

**Issue by GBMSLA1** [kubernetes-sigs/kustomize#2139]
Should configmaps and daemon sets work out without any extra configuration? I'm trying to use the configmap generator with a daemonset and the generated name is not updating inside the daemonset config. 

Looking at the default config this should already work I believe, but I looked at adding a custom namereference without any joy.

Here's my config: 

**$ cat kustomization.yaml** 

```
resources:
- ds.yaml

configurations:
- kustomizeconfig.yaml

configMapGenerator:
- name: config-map
  files:
  - redis-config

```
**$ cat kustomizeconfig.yaml** 

```
# Make Kustomize and DaemonSet find dynamically named ConfigMaps
nameReference:
- kind: ConfigMap
  fieldSpecs:
    - path: spec/template/spec/volumes/configMap/name
      kind: DaemonSet
```

Truncated daemonset file:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      volumes:
      - name: config-map
        configMap:
          name: config-map
          items:
          - key: redis-config
            path: redis.conf
```

Running a kustomize build updates the configmap name for the configmap but not inside the daemonset yaml. 

Any help would be great, thanks.
