### ISSUE TITLE
'fieldpath' parsing fails with error 'field specified in var not found in corresponding resource'

### ISSUE THREAD

**Issue by hmanikkothu** [kubernetes-sigs/kustomize#2144]
See below the yaml files to reproduce the issue. 

1. deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqspringboot-deployment
  labels:
    app: mqspringboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mqspringboot
  template:
    metadata:
      labels:
        app: mqspringboot
    spec:
      containers:
        - name: mqspringboot
          image: hmanikkothu/mqspringboot:latest
          ports:
            - containerPort: 8080
```

2. mqsvc.yaml
```
kind: Service
apiVersion: v1
metadata:
  name: ibmmqsvc
spec:
  ports:
    - port: 1414
      targetPort: 1414
```
3. kustomization.yaml
```
resources:
  - mqsvc.yaml
  - deployment.yaml
patchesStrategicMerge:
  - patch.yaml

vars:
  - name: MQ_SVC_PORT
    objref:
      kind: Service
      name: ibmmqsvc
      apiVersion: v1
    fieldref:
      fieldpath: spec.ports[0].port
```
4. patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqspringboot-deployment
spec:
  template:
    spec:
      containers:
        - name: mqspringboot
          env:
            - name: MQ_PORT
              value: $(MQ_SVC_PORT)
```

### kustomize version - 3.5.4 (latest)
```
kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T06:57:29+00:00 GoOs:darwin GoArch:amd64}
```
### kubectl version - 1.17 (latest)
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
``` 

#### Step 1
Run kustomize build . , which correctly finds the port from service definition and merges in the deployment 
```
$ kustomize build .

apiVersion: v1
kind: Service
metadata:
  name: ibmmqsvc
spec:
  ports:
  - port: 1414
    targetPort: 1414
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mqspringboot
  name: mqspringboot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mqspringboot
  template:
    metadata:
      labels:
        app: mqspringboot
    spec:
      containers:
      - env:
        - name: MQ_PORT
          value: **1414**
        image: hmanikkothu/mqspringboot:latest
        name: mqspringboot
        ports:
        - containerPort: 8080
```

### Step 2 
Use kubectl apply to deploy the yaml configs to the cluster, this throws an error. 
```
$ kubectl apply -k .

**error: field specified in var '{MQ_SVC_PORT ~G_v1_Service {spec.ports[0].port}}' not found in corresponding resource**
```

**Expected result**: Step 2 should successfully generated the final deployment and mqsvc yaml files and applies to the cluster. 
**Actual result**: Step 2 throws the error 'field specified in var '{MQ_SVC_PORT ~G_v1_Service {spec.ports[0].port}}' not found in corresponding resource'
