### ISSUE TITLE
Fix remote patches

### ISSUE THREAD

**Issue by strikeout** [kubernetes-sigs/kustomize#2156]
**Patches from remote locations do not get applied.**

`{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T06:57:29+00:00 GoOs:darwin GoArch:amd64}`

It does not work with either specifying them in `resources:` (together with a kustomization.yaml) nor directly in the `patches:` definition. 
It gives no error and outputs yaml, but the patches are not applied and are **silently discarded**.
How can this be fixed? Is there another approach to take to get remote patches working for my team?

Example:
```
# local - base/kustomization.yaml

resources: 
  - https://some.host.com/kustomize-presets.git//ingress-patch
```

```
# remote - kustomize-presets.git//ingress-patch/kustomization.yaml

patches:
  - path: ingress-patch.yml
    target:
      kind: Ingress
```

```
# remote - kustomize-presets.git//ingress-patch/ingress-patch.yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt
```
