### ISSUE TITLE
Error: no matches for OriginalId

### ISSUE THREAD

**Issue by gadelkareem** [kubernetes-sigs/kustomize#2161]
```
kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:28:58+00:00 GoOs:darwin GoArch:amd64}
```
```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/knative/serving/releases/download/v0.12.0/serving.yaml

patchesStrategicMerge:
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: custom-metrics-auth-reader
    namespace: knative-serving
  $patch: delete
```
Error:
```
> kustomize build . > template.yaml
Error: no matches for OriginalId rbac.authorization.k8s.io_v1_RoleBinding|knative-serving|custom-metrics-auth-reader; no matches for CurrentId rbac.authorization.k8s.io_v1_RoleBinding|knative-serving|custom-metrics-auth-reader; failed to find unique target for patch rbac.authorization.k8s.io_v1_RoleBinding|custom-metrics-auth-reader
```
