### ISSUE TITLE
Support generatorOptions per configmap/secret

### ISSUE THREAD

**Issue by chancez** [kubernetes-sigs/kustomize#2179]
Currently generatorOptions is defined once per kustomization, rather than once per resource. I have to apply some annotations to a configmap so that a component knows to use that configmap's contents to dynamically inject some configuration to a running pod (grafana's extra datasources configmap). 

However, I don't want that annotation applied to other configmaps within the same `kustomization.yaml`, otherwise the component doing the injection will erroneously inject the contents of unrelated configmaps/secrets due to the annotation being applied to all generated configmaps/secrets in the kustomization.yaml. 

I'm proposing we have the ability to supply generatorOptions on each resource:

```
configmapGenerator:
  - name: grafana-config
    namespace: monitoring
    files:
      - grafana.ini
  # only the grafana-datasource configmap gets the grafana_datasource: "1" annotation
  - name: grafana-datasource
    namespace: monitoring
    files:
      - datasource.yml
    generatorOptions:
      annotations:
        grafana_datasource: "1"

```

**Comment by chancez** [comment]
I think I figured out how to implement this. I believe it's a relatively simple change. I'll try to get an MVP PR up and then hopefully figure out how to add tests for it.

**Comment by chancez** [comment]
And since I had to find a work-around until this is implemented or otherwise, I thought I'd mention how I did that in case anyone else hits this. Basically just use json patch or strategicMergepatch to add the annotation. For example:

```
configmapGenerator:
  - name: grafana-datasource
    namespace: monitoring
    files:
      - monitoring/grafana/datasource.yml

patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: grafana-datasource
    namespace: monitoring
  patch: |-
    - op: add
      path: /metadata/annotations
      value:
        grafana_datasource: "1"
```
