### ISSUE TITLE
Ability to merge maps in Kustomize

### ISSUE THREAD

**Issue by neilharris123** [kubernetes-sigs/kustomize#2188]
It would be nice to have a method of using a patch to merge a map in Kustomize.
To demonstrate as an example, I have the following Application defined which makes use of an upstream helm chart:

grafana.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-k8s-grafana
  labels:
    environment: prod
    project: k8s
    role: grafana
spec:
  project: prod-k8s
  source:
    repoURL: 'https://github.com/helm/charts.git'
    path: 'stable/grafana'
    targetRevision: 'ba1d08a129255167457480e29339ab5bfe75d918'
    helm:
      parameters:
      - name: 'datasources."datasources\.yaml".datasources[0].access'
        value: proxy
      - name: 'datasources."datasources\.yaml".datasources[0].isDefault'
        value: 'true'
      - name: service.type
        value: LoadBalancer
```

 I have the following patch.

kustomization.yaml

```
  patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: prod-k8s-grafana
    spec:
      source:
        helm:
          parameters:
          - name: persistence.storageClassName
            value: gp2
          - name: 'datasources."datasources\.yaml".apiVersion'
            value: '1'
          - name: 'datasources."datasources\.yaml".datasources[0].name'
            value: Prometheus
```

When I run $ kustomize build . the output shows the parameter name/values in the granana.yaml are completely replaced by the ones in the kustomization.yaml, when my intention is to merge the two so that they are all applied, but from what I can tell this behaviour is not available in Kustomize.
