### ISSUE TITLE
Bug in the Base64 encoding

### ISSUE THREAD

**Issue by hrmrules** [kubernetes-sigs/kustomize#2191]
There seems to be a bug in the Base64 encoding used to add secrets and configmaps with the appropriate generator.
It seems the problem is related to the character 0x0a in the file. We encountered this problem when trying to add binary keystore files to secrets.

The following is a minimal example to illustrate the problem.

Version: Kustomize v3.5.4
Sample kustomization.yaml:
```
configMapGenerator:
  - name: TestB64ConfigMap
    files:
      - binfile
```
Contents of binfile: 
`echo SIsNCgE= |  base64 -d > binfile `
where SIsNCgE= is the proper base64 value

Sample output of `kustomize build`
```
apiVersion: v1
binaryData:
  binfile: SIsKAQ==
kind: ConfigMap
metadata:
  name: TestB64ConfigMap-bfg8g4dc27
```

The base64 value which should have been SIsNCgE= is now SIsKAQ==
The base64 decoding happens according to the proper rules, so the wrong base64 encoding yields a corrupted binary in the pod.
