### ISSUE TITLE
Kustomize in combination with existing SealedSecrets and name prefix/suffix

### ISSUE THREAD

**Issue by lanmarti** [kubernetes-sigs/kustomize#2193]
While there is an open issue for SealedSecret support (#702), it seems to be focused on generating sealed secrets from files, rather than using existing sealed secrets.

The issue I'm currently facing is as follows: 
I have the following files (see below for abbreviated file content):

-  SealedSecret .json files
-  a deployment.yaml and an ingress.yaml referencing the secrets contained within those SealedSecrets
- a kustomization.yaml with a nameSuffix.

Both the SealedSecret and the generated Secret have the correct suffix, but the references in the deployment/ingress objects retain the unmodified secret references, instead of appending the suffix to those as well.

Is there a way to prevent the '-staging' suffix to be attached to specific files or the SealedSecret type in general (this would also forgo the need to add the "sealedsecrets.bitnami.com/namespace-wide": "true" annotation to allow renaming of secrets defined within sealed secrets)?
For now, I'm using a patch defined in my kustomization.yaml to ovewrite the references to the secrets and add the suffix manually, but I'm wondering if there's an easier way to handle this problem?

### base files:
kustomization.yaml
```
resources:
- deployment.yaml
- sealedsecret.json
nameSuffix: '-staging'
```
sealedSecret.json
```
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysecret",
	[...]
    "annotations": {
      "sealedsecrets.bitnami.com/namespace-wide": "true"
    }
  },
  [...]
}
```
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  [...]
  name: my-deployment
spec:
  [...]
  template:
    [...]
    spec:
	  [...]
      volumes:
      - name: mysecret-volume
        secret:
          secretName: mysecret
```

**Comment by lanmarti** [comment]
As a small aside: while name prefix/suffix is applied to the Sealed Secrets and the corresponding Secrets, common labels are not applied.

**Comment by rodrigo-molina** [comment]
Another approach that allows kustomize to properly replace sealed secrets names is to create a [Custom Resource Definition](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/glossary.md#custom-resource-definition) (actually a [Name reference transformer](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#name-reference-transformer)) to detail all the possible fields that can refer to a `SealedSecret` in your application.

The CRD definition for your example should be (in `base/kustomizeconfig/sealedsecret.yaml` file):

```
nameReference:
- kind: SealedSecret
  fieldSpecs:
  # Deployment references
  - path: spec/template/spec/volumes/secret/secretName
    kind: Deployment
  # Add all kind/paths  depending on which resources use your sealed secrets
```

Then in your `base/kustomization.yaml` add the reference to the configuration

```
configurations:
- kustomizeconfig/sealedsecret.yaml
```

You should be able to follow the same approach for [common labels](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#labels-transformer). Here is a tutorial for [Supporting Custom Resources](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd)
