### ISSUE TITLE
ConfigMap file mounting as directory, not file

### ISSUE THREAD

**Issue by richstokes** [kubernetes-sigs/kustomize#2202]
Regarding kustomization.yaml, In base I have:

```
configMapGenerator:
- name: config
  files:
  - config.toml
```

In an overlay for staging I have:

```
configMapGenerator:
- name: config
  behavior: replace
  files:
  - staging-config.toml
```

The base works fine, but when I apply the overlay it is mounted in the container as a directory and not a file. If I "kubectl get" the staging config map it all looks good - I can see the file contents, etc.

In the deployment.yaml I have:

```
          volumeMounts:
          - name: config
            mountPath: /my/project/config/config.toml
            subPath: config.toml

      volumes:
          - name: config
            configMap:
              name: config
```

Any ideas why it mounts as a file in base but as a directory with the staging overlay?

Thanks!

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
