### ISSUE TITLE
Should be able to JSON Patch Containers directly

### ISSUE THREAD

**Issue by Datamance** [kubernetes-sigs/kustomize#2204]
With a `my-patch.yaml` like so:

```
- op: add
  path: /env/-
  value:
    name: SENTRY_DSN_JS
    valueFrom:
      secretKeyRef:
        key: SENTRY_DSN_JS
        name: lookit-secrets
```

and a `kustomize.yaml` with the following patches clause:

```
patches:
  - path: my-patch.yaml
    target:
      group: core
      version: v1
      kind: Container
      name: builder
```

kustomize *should* be able to "deeply patch" into a container contained within a Deployment manifest, targeting by name (since labels don't go directly on containers).

Instead, the `patches` target in kustomize.yaml has to be the outer construct of some template (e.g., a StatefulSet or Deployment), and I have to have a path like `/spec/template/spec/containers/0/env/-` in the patch itself.

The underlying motivation here is to share bits of the `env` clause across multiple containers.  #952 attempted to address this and provide various alternatives, however, it appears that the generators promised in PR #1208 never came to fruition.

FWIW, I still think that smarter JSON patches are the way to go here from an API standpoint - JSON patches are already really flexible and this is just something they should do already.

Let me know if you need any further information. Thanks!
