### ISSUE TITLE
`kubectl apply -k` vs `kustomize build` "env" and "envs" error

### ISSUE THREAD

**Issue by tamipangadil** [kubernetes-sigs/kustomize#2205]
Hi,

I'm trying to simplify the structures of my yaml files. I segregated the common configs and secrets so I can re-use it into my deployment manifests.

I used:
```
# sample file.yaml
configMapGenerator:
   name: my-config 
   envs: #env
       - config.env
```

Then I ran:
```
$ kubectl apply -k .

error: AccumulateTarget: couldn't make target for path/to/config/folder: json: unknown field "envs"
couldn't make target for path/to/config/folder: json: unknown field "envs"

AccumulateTarget: couldn't make target for base: json: unknown field "envs"
```

After changing it from `envs` to `env` then ran:
```
$ kustomize build .

Error: accumulating resources: recursed accumulation of path 'path/to/configs/folder': accumulating resources: couldn't make target for path 'path/to/configs/folder/subfolder': json: unknown field "env"
```

**Comment by pwittrock** [comment]
Seems like this may be a backwards compatibility issue with the 2 version of kubectl

**Comment by brunojcm** [comment]
The same thing happens with other commands such base.. How can we find documentation in regards to compatibility between `kustomize build` and `kubectl apply -k`?

**Comment by mmajko** [comment]
Had similar error message, it seems that there might be some kind of issue with YAML parsing.

I had this in my `kustomization.yaml`:

```yml
secretGenerator:
  - name: platform
    env: secrets/platform.env
  - name: database
    env: secrets/database.env
```

Which resulted in correctly processed through `kubectl apply -k ...`, but failed when ran `kustomize build ...` on  
`Error: accumulating resources: couldn't make target for path '.../platform/spec/base': json: unknown field "env"`.

After changing the contents of the file to (notice the indentation):

```yml
secretGenerator:
  - name: platform
      env: secrets/platform.env
  - name: database
      env: secrets/database.env
```

it goes through without a problem.
