### ISSUE TITLE
kustomize edit set image merges bases into resources

### ISSUE THREAD

**Issue by timmydo** [kubernetes-sigs/kustomize#2217]
I'm using v3.5.4

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../xx

resources:
- a.yaml
```

run `kustomize edit set image a=b/c:2`

new kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- a.yaml
- ../xx
images:
- name: a
  newName: b/c
  newTag: "2"
```
