### ISSUE TITLE
var of integer pased as integer in container.env

### ISSUE THREAD

**Issue by joar** [kubernetes-sigs/kustomize#2222]
Given:
`kustomization.yaml`:
```yaml
resources:
  - minimal-deployment.yaml

vars:
  - name: NUMBER_OF_REPLICAS
    objref:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: minimal
    fieldref:
      fieldpath: spec.replicas
```
`minimal-deployment.yaml`:
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minimal
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: minimal
          image: scratch
          env:
            - name: NUMBER_OF_REPLICAS
              value: $(NUMBER_OF_REPLICAS)
```
`kustomize build .` produces:
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minimal
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: NUMBER_OF_REPLICAS
          value: 1
        image: scratch
        name: minimal
```
which is invalid, because container.env.value must be a string.
