### ISSUE TITLE
custom varRefernces should support slash escape

### ISSUE THREAD

**Issue by dmolik** [kubernetes-sigs/kustomize#2223]
in a `varRefence` field of `path` names that have slashes in them should be escaped with the ~1 sequence.

Example:
```
  varReference:
  -  path: spec/selector/app.kubernetes.io~1name
     kind: Service
```

Where that service definition would look like:
```
  apiVersion: v1
  kind: Service
  metadata:
    name: api-server
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/name: $(DEPLOYMENT_NAME)
```

should properly replace the `DEPLOYMENT_NAME` var.

**Comment by casek14** [comment]
Having same issue:
```
- op: remove
  path: metadata/annotations/getambassador.io~1config
```

Service definition:
```
apiVersion: v1
kind: Service
metadata:
  name: blits-drafts
  annotations:
    getambassador.io/config: |-
      ---
      "apiVersion": "ambassador/v1"
      "kind": "Mapping"
      "name": "some-name"
      "prefix": "some-prefix"
      "rewrite": "some-rewrite"
      "service": "some-service"
```

Will result in `Error: failed to apply json patch '[{"op":"remove","path":"metadata/annotations/getambassador.io~1config"}]': remove operation does not apply: doc is missing path: "metadata/annotations/getambassador.io~1config": missing value`

kustomize version: 
`{Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}`

Except to match the annotation with escaped `/` by `~1`
