### ISSUE TITLE
Issue with updating image hash for container with multiple "versions".

### ISSUE THREAD

**Issue by mabushey** [kubernetes-sigs/kustomize#2227]
I have a container that is run with multiple release digests.

With this in kustomize, it will update both containers:
```
images:
- digest: sha256:1ceb1e3e84da4b6ce92c4ee990d07bffb21a16b6ddd61c7ce97aa9385d84ac38
  name: 7742104830927.dkr.ecr.us-east-1.amazonaws.com/engine
```

What I would like to do is something like this:
```
images:
- digest: sha256:1ceb1e3e84da4b6ce92c4e84a3d07bffb21a16b6ddd61c7ce97aa9385d84ac38
  name: 7742104830927.dkr.ecr.us-east-1.amazonaws.com/engine
  label: service1
- digest: sha256:e89611837b324eda7ae646af594e8c3763790e364226015e851c646b69aecd50
  name: 7742104830927.dkr.ecr.us-east-1.amazonaws.com/engine
  label: service2
```

Is this possible currently with kustomize, or do I have to change having a kustomize config for stg and prd to stg-service1, stg-service2, prd-service1, prd-service2 (going from 2 kustomize files to 4)?

P.S. Kustomize rocks!
