### ISSUE TITLE
ConfigMapGenerator adds single quotes 

### ISSUE THREAD

**Issue by SMR39** [kubernetes-sigs/kustomize#2230]
```
kustomization.yaml
================
configMapGenerator:
- envs:
  - oauth.properties
  name: oauth-conf
  behavior: merge
```
```
ouath.properties
==============
SECRET_PATH="app-name keyname"
CHAMBER_AWS_REGION=us-west-1
```
Generated config map adds single quotes to environment variable
```
apiVersion: v1
data:
  CHAMBER_AWS_REGION: us-west-1
 SECRET_PATH: '"app-name keyname"'
kind: ConfigMap
```
