### ISSUE TITLE
Configmap or secret generators doesn't work when specified namespace

### ISSUE THREAD

**Issue by rverma-jm** [kubernetes-sigs/kustomize#2233]
If we specify a namespace in metadata, configmap and secret generator doesn't ovveride the name of configmap with the computed one.

**Comment by pickfire** [comment]
I tried using namespace transformer for it but I am surprised it does not affect config map generator namespace so it gets deployed in the current namespace.

**Comment by benjamin-bergia** [comment]
I think that I am hitting the same issue. I fetch a remote yaml file that contains a ConfiMap in a specific namespace. In my kustomization.yml I do something like:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https:// .....

namespace: my-new-namespace

configMapGenerator:
  - name: name-of-the-existing-configmap
    behavior: replace
    files:
      - myfile.yml
```

And i get an error:

> Error: merging from generator &{0xc000594000 { } {{ name-of-the-existing-configmap merge {[] [myfile.yml] []} <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap"}, Name:"name-of-the-existing-configmap", Namespace:""} does not exist; cannot merge or replace


It looks to me like the configmap generator runs before the namespace transformer.

**Comment by Shell32-Natsu** [comment]
@benjamin-bergia generators are definitely run before transformers otherwise the resources generated will be transformed. If you want to run a generator to replace a resource you can put the original resource into base layer.

**Comment by benjamin-bergia** [comment]
@Shell32-Natsu makes sense. The problem is that it's not possible to target the original.

**Comment by pickfire** [comment]
I solved it by just adding another extra layer of kustomization with namespace specified.

**Comment by benjamin-bergia** [comment]
@Shell32-Natsu can you leave this open? There is an actual problem here. @pickfire finding is more a workaround than an actual solution. What @rverma-jm reported is an actual bug.

**Comment by KnVerey** [comment]
I think there are two separate cases being discussed on this issue. The original issue description is:

> If we specify a namespace in metadata, configmap and secret generator doesn't ovveride the name of configmap with the computed one.

If I understand correctly, the desired behavior is that the existing configmap would receive a generated name suffix. It seems to me this never happens when using the generator to update an existing configMap; I'm not seeing different behaviour based on the presence or absence of a namespace.

I agree that a suffix is not added when a generator is used to update or replace an existing resource. However, I'm not sure that's a bug, and I'd be very hesitant to change the long-standing behaviour of such a core feature. There is in fact test coverage showing this does not happen. If you use a generator to create the resource in the first place, the suffixing will happen whether or not another generator subsequently modifies/replaces the content. In other words, it is the origin of the resource that determines suffixing of the name.

If I've misunderstood the scenario, please re-open with samples to reproduce. 
If you want a new feature for configMapGenerator that would enable suffixing existing resources (or perhaps HashTransformer could be augmented to support this), please open an issue for that and help us understand why the solution of creating the original configMap via the generator isn't viable for you.

--- 

The second problem is the "does not exist; cannot merge or replace" error message reported [here](https://github.com/kubernetes-sigs/kustomize/issues/2233#issuecomment-796650498). The cause is that an empty namespace isn't interpreted as a wildcard; on the contrary, it matches "default" specifically. So for configMapGenerator to match an existing configmap with a namespace set, you *must* specify that namespace. That is intended behaviour. As has already been pointed out, it also works to create an intermediate Kustomization layer in order to change the namespace before generators run, if you prefer.

The following works as expected:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-new-namespace

resources:
- input.yaml

configMapGenerator:
  - name: existing
    namespace: existing # needs to match
    behavior: replace
    literals:
      - ENV=dev

```

correctly generates

```yaml
apiVersion: v1
data:
  ENV: dev
kind: ConfigMap
metadata:
  name: existing
  namespace: my-new-namespace
```

/unassign
/close

**Comment by benjamin-bergia** [comment]
Hi @KnVerey,

thank you for your help. Before closing this, would it be possible to document this behavior that you mentioned:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-new-namespace

resources:
- input.yaml

configMapGenerator:
  - name: existing
    namespace: existing # needs to match
    behavior: replace
    literals:
      - ENV=dev
```
in here https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/.
Despite being an intended behavior it doesn't seems to be mentioned anywhere in the reference.
