### ISSUE TITLE
"panic: interface conversion: interface {} is []interface {}, not string" in replaceVars, at refvartransformer.go:43

### ISSUE THREAD

**Issue by smurfralf** [kubernetes-sigs/kustomize#2241]
### Summary
The variable replacement routine panics when given invalid content. Having an error is OK but not telling the user where the input is invalid isn't OK. 

### kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:28:58+00:00 GoOs:darwin GoArch:amd64}

### What happens
kustomize fails with panic. No output generated. No info as to cause of panic.

### What should happen
panic should be rescued and error returned indicating the problematic input text. For the example below this might be `Searching for variable replacements,  expected array of strings, found [["mistakenly use a array value"]].`

### Steps to Reproduce
Starting with valid yaml so it will pass the checker:
```
cat <<EOF > pod.yaml
apiVersion: core/v1
kind: Pod
metadata:
  name: kbug
  namespace: default
spec:
  containers:
    - name: kbug
      command:
        - replaceme
EOF
```
kustomization has a patch and also needs to have variable in it in order to execute the replaceVars function:
```
cat <<EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: global
    literals:
      - blah=foobar
vars:
  - name: FOO_BAR
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: global
    fieldref:
      fieldpath: data.blah
resources:
  - pod.yaml
patchesJson6902:
  - target:
      group: core
      version: v1
      kind: Pod
      name: kbug
      namespace: default
    path: badreplace.yaml
EOF
```
Patch file uses an incorrect replacement value by mistake
```
cat <<EOF > badreplace.yaml
- op: replace
  path: /spec/containers/0/command/0
  value:
     - mistakenly use a array value
EOF
```
The correct syntax would be 
```
- op: replace
  path: /spec/containers/0/command/0
  value:
     correctly use a string value
```
Then running the build results in a panic
```
kustomize build .
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/internal/accumulator.(*refVarTransformer).replaceVars(0xc0005eddd0, 0x50dd560, 0xc0005f5880, 0xc0001990e0, 0x7, 0xc0001990e8, 0x4513717)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/internal/accumulator/refvartransformer.go:43 +0x639
sigs.k8s.io/kustomize/api/transform.MutateField(0xc0005edb30, 0xc0005ede80, 0x1, 0x1, 0xc000199200, 0xc0005759b8, 0x1, 0x1, 0xc0005ede60, 0x30)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/transform/mutatefield.go:36 +0x185
sigs.k8s.io/kustomize/api/transform.MutateField(0xc0005edb00, 0xc0005ede70, 0x2, 0x2, 0xc000198f00, 0xc0005759b8, 0x1, 0x1, 0x2, 0x3)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/transform/mutatefield.go:61 +0x45a
sigs.k8s.io/kustomize/api/transform.MutateField(0xc0005eda70, 0xc0005ede60, 0x3, 0x3, 0xc0002e6d00, 0xc0005759b8, 0x1, 0x1, 0x0, 0xc0005ede60)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/transform/mutatefield.go:53 +0x622
sigs.k8s.io/kustomize/api/internal/accumulator.(*refVarTransformer).Transform(0xc0005eddd0, 0x55fc180, 0xc00013ad20, 0x0, 0xc000575b70)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/internal/accumulator/refvartransformer.go:104 +0x3bc
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/internal/accumulator/resaccumulator.go:138
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).ResolveVars(0xc00013ad00, 0x0, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/internal/accumulator/resaccumulator.go:151 +0x126
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc000255a40, 0x1, 0x0, 0x55ef820, 0x6278b80, 0x55ca800)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/internal/target/kusttarget.go:140 +0x9c
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/internal/target/kusttarget.go:110
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000575cf8, 0x7ffeefbfee58, 0x1, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.3.2/krusty/kustomizer.go:77 +0x3d8
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc000307830, 0x5586880, 0xc0000d0008, 0x1, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/build/build.go:124 +0x86
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc0003a7b80, 0xc000269800, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/build/build.go:68 +0xab
github.com/spf13/cobra.(*Command).execute(0xc0003a7b80, 0xc0002697d0, 0x1, 0x1, 0xc0003a7b80, 0xc0002697d0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a7680, 0x9, 0x55d2100, 0xc0003a81a0)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/main.go:23 +0x71
```
