### ISSUE TITLE
Namespace selector shouldn't match cluster scoped objects. 

### ISSUE THREAD

**Issue by bmenasha** [kubernetes-sigs/kustomize#2248]
This test example shows that applying a patch to all resources in a namespace is incorrectly matching resources that don't have any namespace defined. 
```
cat << EOF > cluster-resource.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-role
EOF

cat << EOF > my-patch.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ignored
metadata:
  labels:
    my-label: my-value
  name: ignored
EOF

cat << EOF > kustomization.yaml 
bases:
  - cluster-resource.yaml
patches:
- path: my-patch.yaml
  target:
    namespace: my-namespace
EOF


kustomize build

---- OUTPUTS----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    my-label: my-value
  name: my-role

---- EXPECTED ----

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-role

```

See this matching code in kustomize/api/resmap/resmap.go

```
		// matches the namespace when namespace is not empty in the selectorc
		// It first tries to match with the original namespace
		// then matches with the current namespace
		if r.GetNamespace() != "" {
			matched := ns.MatchString(orgId.EffectiveNamespace())
			if !matched {
				matched = ns.MatchString(curId.EffectiveNamespace())
				if !matched {
					continue
				}
			}
		}
```

That's not correct processing.  This should be   

```
		if s.Namespace != "" {...
```
As the goal is to always apply the namespace restriction even if the resouce doesn't have a namespace. 

thanks for looking at this.
