### ISSUE TITLE
vars with ClusterRole does not populate

### ISSUE THREAD

**Issue by bitva77** [kubernetes-sigs/kustomize#2250]
Trying to use `vars` to overlay a ClusterRoleBinding but this does not work:

I have my base clusterrole.yaml (snipped to keep it shorter):

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nginx-ingress-clusterrole
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
rules:
  - apiGroups:
      - ""
```

base clusterrolebinding.yaml:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-clusterrole-nisa-binding
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $(CLUSTERROLE)
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: ingress-nginx
```

Overlay clusterrolebinding.yaml:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-clusterrole-nisa-binding
```

kustomization.yaml:

```
bases:
- ../base

patchesStrategicMerge:
- ./clusterrolebinding.yaml

vars:
  - name: CLUSTERROLE
    objref:
      kind: ClusterRole
      name: nginx-ingress-clusterrole
      apiVersion: rbac.authorization.k8s.io/v1beta1
```

and when I run it together:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: nginx-ingress-nginx-ingress-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $(CLUSTERROLE)
subjects:
- kind: ServiceAccount
  name: nginx-ingress-nginx-ingress-serviceaccount
  namespace: ingress-nginx
```

$CLUSTERROLE never got filled out.

This seems to work with Role and RoleBinding - just not ClusterRole/ClusterRoleBinding

**Comment by bitva77** [comment]
yeah I'm dumb.

If I change the overlay clusterrolebinding.yaml to this, it works:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-clusterrole-nisa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress-clusterrole
```

My base clusterrolebinding.yaml is this:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-clusterrole-nisa-binding
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: $(CLUSTERROLE)
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: ingress-nginx
```
