### ISSUE TITLE
Patches within bases are not cumulatively applied along with with patches in overlays

### ISSUE THREAD

**Issue by govinda-attal** [kubernetes-sigs/kustomize#2259]
Please correct my understanding, if incorrect.

We would like to have base where we would like to define standard patches which are mentioned within Kustomization definition file, (for example apply patch for a resource of a kind). For us these are standard customisations.
<img width="406" alt="Screen Shot 2020-03-06 at 4 11 22 pm" src="https://user-images.githubusercontent.com/30035879/76054551-2c05e000-5fc5-11ea-8123-715f8402f481.png">

In overlay 'dev' refers 'base' and would also like to apply its own subset of patches for same kind.

Expected: kustomize when applied on overlay 'dev' should be able to apply patches in a cumulative fashion. Apply the patch within base and then apply/merge patch from overlay 'dev'.

But I have noticed that kustomize build simply ignores patches from the base.

**Comment by govinda-attal** [comment]
Referred to https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md

**Comment by pwittrock** [comment]
@Liujingfang1 do you have context on this?

**Comment by govinda-attal** [comment]
Having this will really help us to have super "dry" kustomize configs, so that overlays (like dev/prod) can simply provide variable substitution.

**Comment by chancez** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/2168 Seems like what you want.

**Comment by govinda-attal** [comment]
> #2168 Seems like what you want.

I am not sure about it, please correct me.

I this case, what we are after it the base will not have any resources. The base will contain certain standard patches that would apply to any resources within overlays which meet patch conditions.

The `patches` section within kustomization file of the base can be used list one or more patches that identifies one or multiple resources (but defined within overlays)

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md

**Comment by chancez** [comment]
In 2168, you would define or reference patches in a `KustomizationPatch` which every overlay would reference and those patches would be applied to anything int hat overlay. 

Basically, instead of a base containing patches, you have a `KustomizationPatch` that has patches you include, rather than a base.

**Comment by govinda-attal** [comment]
Thanks @chancez - sounds great! I could close this issue and track same against #2168

**Comment by QuinnBast** [comment]
> In https://github.com/kubernetes-sigs/kustomize/pull/2168, you would define or reference patches in a KustomizationPatch

@chancez could you provide an example of this?

**Comment by dvcrn** [comment]
I'm similarly confused. Adding a 

```yml
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets/
        value:
          - name: regcred
```

in my base, and including that from a overlay with 
```
resources:
- ../base
```

is not causing anything to get patched. If I move the identical patches section into the kustomization file of my overlay, then everything works as expected

**Comment by dvcrn** [comment]
For future googlers, since I just learned about [components](https://kubectl.docs.kubernetes.io/guides/config_management/components/), the solution is: 

```yml
# components/pullsecrets/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    kind: Deployment
  patch: |-
    kind: Deployment
    metadata:
      name: not-used
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: regcred
```

Then in the overlay:
```yml
# myoverlay/kustomization.yaml

components:
  - ../components/pullsecrets/

resources:
  - ../base/
```

Patches in components are getting applied to the overlay, patches in bases are not and only apply to the current tree
