### ISSUE TITLE
error when kustomize build : support for escape special characters in path for a patch json6902

### ISSUE THREAD

**Issue by govinda-attal** [kubernetes-sigs/kustomize#2268]
hi there,

noticed that kustomize 3.5.4 is not able to escape special characters.

patch.yaml
```yaml

- op: replace
  path: /metadata/annotations/cnrm.cloud.google.com\/project-id
  value: dummy-2

```

Resource file
```yaml

apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: dummy
  name: some-ns

```
It gives an error: 
```bash

Error: failed to apply json patch '[{"op":"replace","path":"/metadata/annotations/cnrm.cloud.google.com\\/project-id","value":"dummy-2"}]': replace operation does not apply: doc is missing path: /metadata/annotations/cnrm.cloud.google.com\/project-id: missing value
```

https://github.com/kubernetes-sigs/kustomize/issues/907

https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#supporting-escape-characters-in-crd-path
