### ISSUE TITLE
Annotation Selector can be a map[string]string for applying patches

### ISSUE THREAD

**Issue by govinda-attal** [kubernetes-sigs/kustomize#2269]
hi there,

noticed that on kustomize 3.5.4, annotation selectors need to be comma separated string to select a resource based on multiple annotations.

It will be nice to have map annotations selectors

kustomize.yaml
```yaml

patches:
  - target:
      kind: xyz
      # annotationSelector: ann1=val1,ann2=val2; this works but following would look better.
      annotationSelector:
        ann1: val1
        ann2: val2
    path: patches/some-patch.yaml

```

It gives an error: 
```bash

Error: json: cannot unmarshal object into Go struct field Selector.patches.target.annotationSelector of type string
```
