### ISSUE TITLE
secret/configmap generator: support yaml config patching

### ISSUE THREAD

**Issue by seaneagan** [kubernetes-sigs/kustomize#2271]
Use case: I have a secret that i want to generate which contains helm chart values overrides, which is a yaml string. I want to be able to use kustomize patch functionality into this yaml:

With current ConfigMapGenerator the initial values override would look like this:

```
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: values_overrides
literals:
  - |
      values_overrides=
      foo: 1
      bar: 1
```

but overriding those values overrides would require string interpolation, patching won't work.

I'd like to be able to do this:

```
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: values_overrides
literals:
  values_overrides:
    foo: 1
    bar: 1
```

and patch it with:

```
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: values_overrides
literals:
  values_overrides:
    bar: 2
    baz: 2
```

which after patching would generate:

```
apiVersion: v1
data:
  values_overrides: | # stringified patched yaml
    bar: 2
    baz: 2
    foo: 1
kind: ConfigMap
metadata:
  name: values_overrides
`)
```
I could write a custom plugin (or "function") to do this, but thought perhaps it might fit with the builtin ones.
