### ISSUE TITLE
Environment variables of overlay are replacing the ones from base despite add operation

### ISSUE THREAD

**Issue by PapoyEdits** [kubernetes-sigs/kustomize#2274]
So I have a base deployment containing some environment variables (shortened for brevity):
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: dummy-image:0.0.1
        imagePullPolicy: IfNotPresent
        name: dummy-image
        env: 
        - name: HELLO
          value: world
```
that I add to my service in the kustomization.yaml like this:
```
bases:
  - git::<repo-url-stuff>//base/deployment
```
In this service, I want to apply a patch to add environment variables specific to the service
```
- op: add
  path: /spec/template/spec/container/0/env
  value:
    - name: foo
      value: bar
```
However, I run into some unexpected behavior where the environment variables from the base deployment are overwritten by the variables of the service, despite it being an add operation. Is this intended behavior, a bug or am I doing something wrong?

Though, I can get the result I'm after by doing below instead (add /- to path and make the value not a list), but it isn't optimal as I was hoping that the changes in the services (we have many that use the deployment base) would be minimal and that the add operation on the /env path would work the way you'd expect by adding together the lists of variables instead of replacing it:
```
- op: add
  path: /spec/template/spec/container/0/env/-
  value:
    name: foo
    value: bar
```

**Comment by pgpx** [comment]
Have you considered using ConfigMaps to contain the environment variables, and then using
```yaml
envFrom:
  - configMapRef:
    name: configMapName
```
Kustomize's configMapGenerator can nicely merge the values from overlays onto the base (just use `behavior: merge` in the overlay, and remove it in the base):

```yaml
configMapGenerator:
  - name: configMapName
    behavior: merge
    literals:
      - foo=bar
```
