### ISSUE TITLE
Unable to patch ConfigMap

### ISSUE THREAD

**Issue by steinybot** [kubernetes-sigs/kustomize#2293]
No matter what I do I cannot seem to identify a ConfigMap as a patch target.

It fails with:
```
❯ kustomize build
Error: no matches for OriginalId core_v1_ConfigMap|~X|config; no matches for CurrentId core_v1_ConfigMap|~X|config; failed to find unique target for patch core_v1_ConfigMap|config
```

```
❯ kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:23:25+00:00 GoOs:darwin GoArch:amd64}
```

`kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
patchesJson6902:
  - target:
      group: core
      version: v1
      kind: ConfigMap
      name: config
    path: config-patch.yaml
```

`configmap.yaml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  foo: "bar"
```

`config-patch.yaml`:
```
- op: replace
  path: /data/bar
  value: baz
```
