### ISSUE TITLE
Don't add a selector to services of types ExternalName

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#2294]
I have a service of type ExternalName. In my kustomization file I specified a list of commonLabels.
Currently kustomize add the commonLabels to all objects metadata and service selectors. This is expected and correct. Unfortunately it also add a selector to the services of type ExternalName. Kubernetes doesn't seem to complain about it but the behaviour of a service of type ExternalName that also has a selector seems to be to entirely bypass the externalName and act as a normal service.

Would it be possible to add a check to the commonLabels transformer to add labels only in the metadata of the ExternalName services and don't add any selector.

**Comment by benjamin-bergia** [comment]
I think this is also messing up headless services.

**Comment by nbn** [comment]
I believe I am encountering this problem too. Is there a way to bypass it in anyway?

As an example, having this kustomization file:

```
commonLabels:
  owner: me

resources:
  - service.yaml
```

And a service:

````
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    podlabel: mypod
````
Give me the label as metadata, but also in the selector, like this:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    owner: me
  name: myservice
spec:
  selector:
    owner: me
    podlabel: mypod
```

My problem is that not all pods are managed by this kustomization project, so I cannot label as usual.
When I use [kapp](http://get-kapp.io), i can disable label-scoping (as they call it) by annotating the service.
```
metadata:
  annotations:
    kapp.k14s.io/disable-label-scoping: ""
```

Can something similar be expressed in kustomize?
