### ISSUE TITLE
Kustomize command to add environment variables to containers in a kustomization

### ISSUE THREAD

**Issue by guibirow** [kubernetes-sigs/kustomize#2301]
Some applications allow configuration to be defined via Environment Variables. When deploying the yaml file with customize, we need to define these environment variables into the deployment.yaml file and pass the values accordingly.

In many cases, when the values are optional, we shouldn't need to provide any values or define the variables into the deployment.

Would make much more convenient if we could set these environment variable using customize commands instead of filling the deployment.yaml with all possible parameters.

Example:
Instead of defining the file like this:
```
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:
      containers:
      - name: wordpress
        env:           // Just one for simplicity, this could have a long list of optional variables 
        - name: WORDPRESS_DB_HOST
          value: $(MYSQL_SERVICE)
```
We could define like this:

```
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:
      containers:
      - name: wordpress
```

And inject environment variables with:

Specific container:
```
kustomize edit set env WORDPRESS_DB_HOST=$(MYSQL_SERVICE) container=wordpress
```
for specific deployment 
```
kustomize edit set env WORDPRESS_DB_HOST=$(MYSQL_SERVICE) deployment=wordpress
```
for a specific container in a deployment:
```
kustomize edit set env WORDPRESS_DB_HOST=$(MYSQL_SERVICE) deployment=wordpress container=wordpress
```
For all containers in the kustomization
```
kustomize edit set env WORDPRESS_DB_HOST=$(MYSQL_SERVICE)
```

This will be useful to provide Environment Variables to containers dynamically at deployment time without setup the yaml file in advance.
