### ISSUE TITLE
make kustomize edit keep yaml structure and comments

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#2310]
`kustomize edit` drops kustomization.yaml structure and comments due to the serialization

Rebasing on to `kyaml/yaml` would address this.

Example:

Change this to read using the kyaml/yaml libraries:

- https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/internal/commands/edit/add/addbase.go#L51
- https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/yaml/types.go#L99

**Comment by bat79a** [comment]
I think that I have similar probleme where my bases value is removed.

Here is my original file : 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/
namespace: dev

patchesStrategicMerge:
- configmap-patch.yml

images:
- name: my_image
  newName: my_image
  newTag: 0.1.0
```

And when I Edit the image tag, my file loose the bases attribute 
```
 kustomize edit set image my_image=my_image:2.0.0
```

Here the final file that doesn't work, because the bases attribute is not here anymore and replace by the ressources attribute : 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

patchesStrategicMerge:
- configmap-patch.yml

images:
- name: my_image
  newName: my_image
  newTag: 2.0.0
**resources**:
- ../../base/
```
