### ISSUE TITLE
v1.0.5: Error: loadResMapFromBasesAndResources: SemiResources: <nil> is expectd ...

### ISSUE THREAD

**Issue by remoe** [kubernetes-sigs/kustomize#232]
Unclear error message for this simple sample:

https://github.com/remoe/kustomize-issue1

```shell
> kustomize build kustomize-issue1/overlays/staging
Error: loadResMapFromBasesAndResources: SemiResources: <nil> is expectd to be map[string]interface {}
```

The error comes from here:

https://github.com/kubernetes-sigs/kustomize/blob/83b3eb9d5415663169e580982b373667762f6af8/pkg/transformers/util.go#L59

One don't understand the reason for this error.

**Comment by Liujingfang1** [comment]
I took a look at it. The failure is due to invalid resource files.
In the base directory, you have deployment.yaml and service.yaml, but both of them are not valid.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
  strategy: {}
  template:
    metadata:
    spec:
      containers:
```
`containers` and `selector` fields are required for Deployment type. When creating a base, make sure you add valid resources.
