### ISSUE TITLE
Common Labels and Annotations in Base

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kustomize#2328]
So I am trying to put some `commonLabels`,  `commonAnnotations`, and `generatorOptions` in a base kustomization. Then in all the other dirs with a `kustomization.yaml` I add the base like so:
```yaml
resources:
  - ../base/
```
Basically I wanted the following common info in anything which uses the base:
```yaml
commonLabels:
  org: MyOrg
commonAnnotations:
  app.kubernetes.io/managed-by: me
```

However nothing in the base actually transforms anything. No labels, annotations, or generator options are used. It seems the only thing you can import from a base is the resources, am I correct? Is there a way to share common labels across things using a base? Am I looking at this wrong?

**Comment by jeusdi** [comment]
I'm facing with the same issue.

In all my k8s manifests there's snippet code like:

metadata:
  labels: 
    name: project-name
    version: project-version
  name: project-name
I don't quite figure out how to use kustomize in order to set that "please kustomize, add those metadata.labels and metadata.name to all objects".

I've took a look on some transformers, but I don't quite figure out what they are intended to...

Any ideas?

**Comment by bittner** [comment]
We have `commonLabels` in our base configuration and add more of them in the overlays. Works for us. You can see a working example in our GitLab demo repository:

- [base/kustomization.yaml](https://gitlab.com/appuio/example-django/-/blob/master/deployment/application/base/kustomization.yaml)
- [overlays/development/kustomization.yaml](https://gitlab.com/appuio/example-django/-/blob/master/deployment/application/overlays/development/kustomization.yaml)
- [overlays/integration/kustomization.yaml](https://gitlab.com/appuio/example-django/-/blob/master/deployment/application/overlays/integration/kustomization.yaml)
- [overlays/production/kustomization.yaml](https://gitlab.com/appuio/example-django/-/blob/master/deployment/application/overlays/production/kustomization.yaml)

Can you see a significant difference to your approach, or is this issue already fixed?

**Comment by Shell32-Natsu** [comment]
Please reopen the issue if you are stilling having it.

**Comment by mbigras** [comment]
That [kustomization.yaml](https://gitlab.com/appuio/example-django/-/blob/master/deployment/application/overlays/development/kustomization.yaml) example-django Kustomization works since you patch the same application ConfigMap. You create the application ConfigMap in the base, then patch in the overlays/dev overlays like the following commands show.

1. Look at the application ConfigMap for [deployment/application/base](https://gitlab.com/appuio/example-django/-/tree/master/deployment/application/base).

   ```
   kustomize build https://gitlab.com/appuio/example-django.git/deployment/application/base | yq 'select(.kind == "ConfigMap")'
   ```

   Your output should look like the following.

   ```
   $ kustomize build https://gitlab.com/appuio/example-django.git/deployment/application/base | yq 'select(.kind == "ConfigMap")'
   apiVersion: v1
   kind: ConfigMap
   metadata:
     labels:
       component: application
     name: application-6ct58987ht
   ```

1. Look at the application ConfigMap for [deployment/application/overlays/development](https://gitlab.com/appuio/example-django/-/blob/master/deployment/application/overlays/development/kustomization.yaml).

   ```
   kustomize build https://gitlab.com/appuio/example-django.git/deployment/application/overlays/development | yq 'select(.kind == "ConfigMap")'
   ```

   Your output should look like the following.

   ```
   $ kustomize build https://gitlab.com/appuio/example-django.git/deployment/application/overlays/development | yq 'select(.kind == "ConfigMap")'
   apiVersion: v1
   data:
     DJANGO_LOG_LEVEL: DEBUG
   kind: ConfigMap
   metadata:
     annotations:
       app.gitlab.com/app: appuio-example-django
       app.gitlab.com/env: development
     labels:
       component: application
       environment: development
     name: application-49c6c5c4kg
     namespace: example-django
   ```

   Notice that the same application ConfigMap is patched. Kustomize automatically changes hash but the original ConfigMaps were still named application.


But what if you want to generate a new ConfigMap in the overlays/dev overlay? Can you propagate the commonLabels labels from the base? That's not what happens in the following example.


```
DEMO=$(mktemp -d)

mkdir -p $DEMO/{base,overlays} $DEMO/overlays/dev

cat <<EOF >$DEMO/base/kustomization.yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  generated-by: kustomize
configMapGenerator:
  - name: base
    literals:
      - ORG=myorg
EOF

cat <<EOF >$DEMO/overlays/dev/kustomization.yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  env: dev
configMapGenerator:
  - name: dev
    literals:
      - ENV=dev
resources:
  - ../../base
EOF

kustomize build $DEMO/overlays/dev
```

Your output should look like the following.

```
$ kustomize build $DEMO/overlays/dev
apiVersion: v1
data:
  ORG: myorg
kind: ConfigMap
metadata:
  labels:
    env: dev
    generated-by: kustomize
  name: base-7mcf68g48c
---
apiVersion: v1
data:
  ENV: dev
kind: ConfigMap
metadata:
  labels:
    env: dev
  name: dev-cbc6h26dgf
```

Notice that the dev ConfigMap doesn't get the generated-by=kustomize label. Is there a way to avoid duplicating commonLabels.generated-by=kustomize in all the kustomization.yaml files?
