### ISSUE TITLE
Unable to use secretKeyRef when key is not value

### ISSUE THREAD

**Issue by mabushey** [kubernetes-sigs/kustomize#2329]
```
✗  cat apikey.env 
exact=testkey
```

```
✗  cat kustomize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-stg
commonLabels:
  env: stg
resources:
- project-stg-vs.yaml
patchesJson6902:
- path: project-stg-vs-patch.yaml
  target:
    group: networking.istio.io
    kind: VirtualService
    name: project-stg
    namespace: default
    version: v1alpha3
secretGenerator:
- name: apikey
  envs:
    - apikey.env
```

```
✗  cat project-stg-vs.yaml
...
  http:
...
  - match:
    - headers:
        apikey:
          exact: replaceme
```

```
✗  cat project-stg-vs-patch.yaml
...
- op: replace
  path: /spec/http/1/match/0/headers/apikey/exact
  value:
  - name: apikey
    valueFrom:
      secretKeyRef:
         key: exact
         name: apikey
```

The secret looks good, but it's not applying it:
```
apiVersion: v1
data:
  exact: dGVzdGtleQ==
kind: Secret
metadata:
  labels:
    env: stg
  name: apikey-5fk9tkgkbt
  namespace: project-stg
type: Opaque
...
  - match:
    - headers:
        apikey:
          exact:
          - name: apikey
            valueFrom:
              secretKeyRef:
                key: exact
                name: apikey
```

```
✗  kustomize build . | kubectl apply -f -                                                                                                                                                                                                                                                                     
secret/apikey-5fk9tkgkbt unchanged                                                                                                                                                                                                                                                                                                                         
Error from server: error when applying patch:
...
```

**Comment by mabushey** [comment]
Here's the actual error:
```
✗  cat apikey.env 
apikey=MyNewApiKey
```
```
✗  cat project-stg-vs-patch.yaml 
- op: replace
  path: /spec/http/1/match/0/headers/apikey/exact
  value:
  - name: exact
    valueFrom:
      secretKeyRef:
         key: apikey
         name: apikey
```
```
✗  kustomize build . | kubectl apply -f -
secret/apikey-kh48b68cbh unchanged
The VirtualService "project-stg" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"networking.istio.io/v1alpha3", "kind":"VirtualService", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"VirtualService\",\"metadata\":{\"annotations\":{},\"labels\":{\"env\":\"stg\"},\"name\":\"project-stg\",\"namespace\":\"default\"},\"spec\":{\"gateways\":[\"elb-gateway.istio-system.svc.cluster.local\"],\"hosts\":[\"project-stg.green.example.com\",\"project-stg.blue.example.com\"],\"http\":[{\"match\":[{\"uri\":{\"exact\":\"/info-one\"}}],\"retries\":{\"attempts\":8},\"rewrite\":{\"uri\":\"/info\"},\"route\":[{\"destination\":{\"host\":\"project-one.project-stg.svc.cluster.local\",\"port\":{\"number\":8080}}}],\"timeout\":\"2s\"},{\"match\":[{\"headers\":{\"apikey\":{\"exact\":{\"valueFrom\":{\"secretKeyRef\":{\"key\":\"apikey\",\"name\":\"apikey\"}}}}},\"uri\":{\"prefix\":\"/financial\"}}],\"retries\":{\"attempts\":8},\"route\":[{\"destination\":{\"host\":\"project-one.project-stg.svc.cluster.local\",\"port\":{\"number\":8080}}}],\"timeout\":\"360s\"},{\"match\":[{\"uri\":{\"exact\":\"/info-two\"}}],\"retries\":{\"attempts\":8},\"rewrite\":{\"uri\":\"/info\"},\"route\":[{\"destination\":{\"host\":\"project-two.project-stg.svc.cluster.local\",\"port\":{\"number\":8080}}}],\"timeout\":\"2s\"},{\"match\":[{\"headers\":{\"apikey\":{\"exact\":\"NoApiKey\"}},\"uri\":{\"prefix\":\"/path-two\"}}],\"retries\":{\"attempts\":8},\"route\":[{\"destination\":{\"host\":\"project-two.project-stg.svc.cluster.local\",\"port\":{\"number\":8080}}}],\"timeout\":\"360s\"},{\"match\":[{\"uri\":{\"prefix\":\"/\"}}],\"route\":[{\"destination\":{\"host\":\"httpbin.httpbin.svc.cluster.local\",\"port\":{\"number\":80}}}]}]}}\n"}, "creationTimestamp":"2019-12-18T22:43:47Z", "generation":8, "labels":map[string]interface {}{"env":"stg"}, "name":"project-stg", "namespace":"default", "resourceVersion":"53938176", "uid":"da4ddee9-21e7-11ea-a621-06b970bc80ec"}, "spec":map[string]interface {}{"gateways":[]interface {}{"elb-gateway.istio-system.svc.cluster.local"}, "hosts":[]interface {}{"project-stg.green.example.com", "project-stg.blue.example.com"}, "http":[]interface {}{map[string]interface {}{"match":[]interface {}{map[string]interface {}{"uri":map[string]interface {}{"exact":"/info-one"}}}, "retries":map[string]interface {}{"attempts":8}, "rewrite":map[string]interface {}{"uri":"/info"}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"project-one.project-stg.svc.cluster.local", "port":map[string]interface {}{"number":8080}}}}, "timeout":"2s"}, map[string]interface {}{"match":[]interface {}{map[string]interface {}{"headers":map[string]interface {}{"apikey":map[string]interface {}{"exact":map[string]interface {}{"valueFrom":map[string]interface {}{"secretKeyRef":map[string]interface {}{"key":"apikey", "name":"apikey"}}}}}, "uri":map[string]interface {}{"prefix":"/financial"}}}, "retries":map[string]interface {}{"attempts":8}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"project-one.project-stg.svc.cluster.local", "port":map[string]interface {}{"number":8080}}}}, "timeout":"360s"}, map[string]interface {}{"match":[]interface {}{map[string]interface {}{"uri":map[string]interface {}{"exact":"/info-two"}}}, "retries":map[string]interface {}{"attempts":8}, "rewrite":map[string]interface {}{"uri":"/info"}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"project-two.project-stg.svc.cluster.local", "port":map[string]interface {}{"number":8080}}}}, "timeout":"2s"}, map[string]interface {}{"match":[]interface {}{map[string]interface {}{"headers":map[string]interface {}{"apikey":map[string]interface {}{"exact":"NoApiKey"}}, "uri":map[string]interface {}{"prefix":"/path-two"}}}, "retries":map[string]interface {}{"attempts":8}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"project-two.project-stg.svc.cluster.local", "port":map[string]interface {}{"number":8080}}}}, "timeout":"360s"}, map[string]interface {}{"match":[]interface {}{map[string]interface {}{"uri":map[string]interface {}{"prefix":"/"}}}, "route":[]interface {}{map[string]interface {}{"destination":map[string]interface {}{"host":"httpbin.httpbin.svc.cluster.local", "port":map[string]interface {}{"number":80}}}}}}}}: validation failure list:
spec.http.match.headers.apikey.exact in body must be of type string: ""
```
