### ISSUE TITLE
feature request - generator based on existing yaml 

### ISSUE THREAD

**Issue by cameronbraid** [kubernetes-sigs/kustomize#2335]
I have a use case where I need to generate new resources based on a config file, and the existing resources.

So its like a generator, but receives the existing YAML as stdin and writes full YAML to stdout

My use case doesn't require changing the existing YAML so the output could be restricted to just new resources.

The use case is as follows.

Currently we use istio and external dns.  

To configure external DNS without using an kube ingress we hand code ExgternalName services like the following :

```
apiVersion: v1
kind: Service
metadata:
  name: some-service-external-name
  annotations:
    external-dns.alpha.kubernetes.io/hostname: some-service.example.com
spec:
  type: ExternalName
  externalName: gateway.example.com
```

Our istio virtual services we define like the following :

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: some-service
spec:
  hosts:
    - some-service.example.com
  gateways:
    - istio-system/ingressgateway
  http:
    - route:
        - destination:
            host: some-service
            port:
              number: 8080
```

We would like to be able to create a plugin for kustomize that generates these ExternalName services based on the hosts values from the VirtualServices using a config file like 

```
apiVersion: kustomize.drivenow.com.au/v1
kind: ExternalNameGenerator
metadata:
  name: dev-external-names
spec:
  gateway: gateway.example.com
```
