### ISSUE TITLE
kustomize.config.k8s.io/behavior not work in exec plugin

### ISSUE THREAD

**Issue by liuyangc3** [kubernetes-sigs/kustomize#2346]
version
```shell
kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:23:25+00:00 GoOs:darwin GoArch:amd64}
```
files
```
tree -l
├── base
│   ├── kustomization.yaml
│   └── pv.yaml
├── kustomize
│   └── plugin
│       └── test
│           └── pvgenerator
│               └── PVGenerator
└── overlays
    ├── kustomization.yaml
    └── pv.yaml
```

base
```yaml
# cat base/kustomization.yaml
resources:
- pv.yaml

# cat base/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - "ReadWriteOnce"
```
plugin, kustomize/plugin/test/pvgenerator/PVGenerator
```shell
#!/bin/bash
shift

cat <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $1
spec:
  capacity:
    storage: $2
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
EOF
```
overlays
```yaml
# cat overlays/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
generators:
- pv.yaml

# cat overlays/pv.yaml
apiVersion: test
kind: PVGenerator
metadata:
  name: notImportantHere
  kustomize.config.k8s.io/behavior: "replace"
argsOneLiner: test 4Gi
```

error
```shell
XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins $(pwd)/overlays
Error: merging from generator &{/Users/yang/kustomize/test/kustomize/plugin/test/pvgenerator/PVGenerator [test 4Gi] [97 112 105 86 101 114 115 105 111 110 58 32 116 101 115 116 10 97 114 103 115 79 110 101 76 105 110 101 114 58 32 116 101 115 116 32 57 57 71 105 10 107 105 110 100 58 32 80 86 71 101 110 101 114 97 116 111 114 10 109 101 116 97 100 97 116 97 58 10 32 32 107 117 115 116 111 109 105 122 101 46 99 111 110 102 105 103 46 107 56 115 46 105 111 47 98 101 104 97 118 105 111 114 58 32 114 101 112 108 97 99 101 10 32 32 110 97 109 101 58 32 110 111 116 73 109 112 111 114 116 97 110 116 72 101 114 101 10] 0xc0004fdc20}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"PersistentVolume"}, Name:"test", Namespace:""} exists; must merge or replace
```
