### ISSUE TITLE
Get Error: json: unknown field "patch" on Windows, but not from Mac

### ISSUE THREAD

**Issue by XiaobinYuan** [kubernetes-sigs/kustomize#2347]
```
$ kustomize.exe build .> tmp.yaml
Error: json: unknown field "patch"
```
```
$ kustomize.exe version
Version: {KustomizeVersion:2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-05T20:37:42Z GoOs:windows GoArch:amd64}
```

The kustomization.yaml file:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - https://gitlab+deploy-token-xxxx@xxxx.net/abc/xyz/namespaces?ref=0.2.1
  - https://gitlab+deploy-token-xxxx@xxxx.net/abc/xyz/overlays/aks?ref=0.2.1

patchesJson6902:
- target:
    group: "crd.projectcalico.org"
    version: v1
    kind: GlobalNetworkPolicy
    name: 2001.allow-list
  patch: |-
    - op: replace
      path: /spec/egress/0/destination/nets/0
      value: xxxx
    - op: add
      path: /spec/egress/0/destination/nets/-
      value: xxxx
- target:
    group: helm.fluxcd.io
    version: v1
    kind: HelmRelease
    namespace: monitoring-system
    name: prometheus-operator
  path: alert-routing.yaml
```
