### ISSUE TITLE
patch transformer path escape character?

### ISSUE THREAD

**Issue by pokcetjokers87** [kubernetes-sigs/kustomize#2368]
I'm trying to add a patch transformer for a resource request, where the name of the resource has a forward slash in it "/":  "nvidia.com/gpu"

```
patch: |-
   - op: add
     path: /spec/controllerTemplate/spec/containers/0/resources/requests/nvidia.com/gpu
     value:
       1
```
I've tried "nvidia.com\/gpu" and that doesn't seem to work.  Are there any escape characters I can use?
Edit: the example above should have a backward slash before the forward slash, but it doesn't show up in the post for some reason.

The desired result in the manifest is this:

```
          requests:
            nvidia.com/gpu: 1
```

Any help is greatly appreciated.
