### ISSUE TITLE
Using both namePrefix and namespace changes the metadata.name in the namespace

### ISSUE THREAD

**Issue by k8sz** [kubernetes-sigs/kustomize#2371]
kustomization.yaml
```yaml
namePrefix: prod-
```
namespace.yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: prod
```
kustomize build

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: prod-prod
```
