### ISSUE TITLE
Secret- & ConfigMap generator functionality is broken (Genrates not usable yaml)

### ISSUE THREAD

**Issue by juhaku** [kubernetes-sigs/kustomize#2379]
__kustomization.yaml__ file like following:
```
secretGenerator:
  - name: my-super-secrest
  - literals:
      - username=SuperSecretUser
      - password=MyLittlePony
configMapGenerator:
  - name: foo-config
  - literals:
      - fooValue=BarValue
```
Will result secrests and config's below: See the duplicates and the metadata names looks funny.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-config-6d486c256d
---
apiVersion: v1
data:
  fooValue: BarValue
kind: ConfigMap
metadata:
  name: -f265hffkcd
---
apiVersion: v1
kind: Secret
metadata:
  name: my-super-secrest-ktt6296g42
type: Opaque
---
apiVersion: v1
data:
  password: TXlMaXR0bGVQb255
  username: U3VwZXJTZWNyZXRVc2Vy
kind: Secret
metadata:
  name: -cc86mf9mm5
type: Opaque
```

Im using the kubectl version 1.18:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
