### ISSUE TITLE
namePrefix doesn't work on array of strings

### ISSUE THREAD

**Issue by fenngwd** [kubernetes-sigs/kustomize#2386]
namePrefix supports custom path definition in configurations.

But when facing yml field is array of strings, namePrefix doesn't work well.

e.g
This is a resource yaml. 
```yaml
apiVersion: example.com/v1
kind: Example
metadata:
  name: example-1
spec:
  name: example-1
  labels:
    - label-1
    - label-2
```

This is a kustomizeconfig yaml. 
```yaml
namePrefix:
  - path: metadata/name
    kind: Example
  - path: spec/name
    kind: Example
  - path: spec/labels/0
    kind: Example

```

When I build with these yamls, kustomize report an error about this.
`Error: "label-1" is expected to be map[string]interface {}`

Please help me to find out how can I insert name prefix for json string array(Like labels definition in Example).
