### ISSUE TITLE
Wrong output files names for resources using the core API group

### ISSUE THREAD

**Issue by marco2704** [kubernetes-sigs/kustomize#2393]
Hey guys, I started using the `-o, --output` flag from the `build` subcommand to write the build output to a directory. As far as I've seen in the code, the API group, the API version and the resource name is used to compose the output files names when the path set by the `-o, --output` flag is a directory. This is causing weird names for the resources using the core API group, i.e. services, configmaps. I was able to reproduce it in a new simpler kustomization:

```sh
.
├── deployment.yaml
├── kustomization.yaml
├── rendered
└── service.yaml
```

`deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

`service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
```

`kustomization.yaml`
```yaml
resources:
- deployment.yaml
- service.yaml

nameSuffix: -testing
```

```sh
$ kustomize build -o rendered/
$ tree
.
├── deployment.yaml
├── kustomization.yaml
├── rendered
│   ├── apps_v1_deployment_my-nginx-testing.yaml
│   └── ~g_v1_service_my-nginx-svc-testing.yaml
└── service.yaml
```
The the output files content is correct, but I do not think the service yaml file name is. Please let me know if I'm missing something. I used a Macbook Pro with zsh for this example.
