### ISSUE TITLE
Nameprefix is broken while using statefulset, but works with deployment.

### ISSUE THREAD

**Issue by rverma-jm** [kubernetes-sigs/kustomize#2400]
```
# statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: puppetserver
  name: prodpfx-puppetserver
  namespace: prodns
spec:
  replicas: $(HorizontalPodAutoscaler.puppetserver.spec.minReplicas)
  selector:
    matchLabels:
      app: puppetserver
  serviceName: prodpfx-puppetserver
  template:
    metadata:
      labels:
        app: puppetserver
    spec:
      containers:
      - image: hack4easy/kubesim_health-amd64:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8081
        name: main
        ports:
        - containerPort: 8081
          name: pupperserver
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
---
# hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: puppetserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: puppetserver
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: main-route
        # namespace: default
      target:
        type: Value
        value: 10k

# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- hpa.yaml

```
When applied with nameprefix
```
# overlay/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameprefix: prodpfx-
namespace: prodns

bases:
- ../../base
namePrefix: vpcflowlogs-
```
results HPA's resulting `spec/scaleTargetRef/name` without nameprefix.

While the same setup works when using deployment as illustrated here https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1721, works with `spec/scaleTargetRef/name` including nameprefix
