### ISSUE TITLE
PersistentVolume claimRef is not templated by kustomize

### ISSUE THREAD

**Issue by PacoDu** [kubernetes-sigs/kustomize#2405]
Hey,
The claimRef of a PersistentVolume if not templated by kustomize, is it intended or is it a bug ?

Thanks.

kubectl version: `v1.18.2`

**Comment by PacoDu** [comment]
I was able to customize this behavior using the transformer configuration `nameReference`.

**Comment by PacoDu** [comment]
But  this configuration for namespace doesn't work :
```
namespace:
  - kind: PersistentVolume
    path: spec/claimRef/namespace
```

**Comment by Jojoooo1** [comment]
I have the same problem.

**Comment by gmspinheiro** [comment]
> But this configuration for namespace doesn't work :
> 
> ```
> namespace:
>   - kind: PersistentVolume
>     path: spec/claimRef/namespace
> ```

Having the same issue, which is causing issues when attempting to use the claimRef.namespace field for binding a PV to a specific PVC.

**Comment by monopole** [comment]
So a nameReference you expect to be updated isn't updated?
To save time, and help anyone who address this, please provide a full example.
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/bugs.md

**Comment by zhsj** [comment]
```
==> kustomization.yaml <==
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml

configurations:
  - kustomizeconfig.yaml

==> kustomizeconfig.yaml <==
namespace:
- kind: PersistentVolume
  path: spec/claimRef/namespace
  create: true

==> persistentvolumeclaim.yaml <==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual

==> persistentvolume.yaml <==
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    name: demo-pvc
    namespace: default
  storageClassName: manual
```

`kubectl kustomize` result is:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    name: demo-pvc
    namespace: default
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
```

But the expected result is:

```
...
  claimRef:
    name: demo-pvc
    namespace: demo
...
```

I think the pv resource is skiped in https://github.com/kubernetes-sigs/kustomize/blob/v2.0.3/pkg/transformers/namespace.go#L39

However the master version of `kustomize` seems ok.

**Comment by Shell32-Natsu** [comment]
Seems that HEAD doesn't have this issue. Will close this.

/close

**Comment by jaroslawhartman** [comment]
A solution with replacements I've implemented:

```
replacements:
  - source:
      kind: StatefulSet
      name: mnpdb-ubi-ldap-readreplicas
      fieldPath: metadata.namespace
    targets:
    - select:
        kind: PersistentVolume
        labelSelector: updateClaimRef=ns
      fieldPaths:
        - spec.claimRef.namespace
```

So all PVs with label `updateClaimRef=ns` are treated with a namespace derived from an other resource in the NS (e.g. Deployment).

Seems working reasonable well and does not need maintenance 😀
