### ISSUE TITLE
labelsTransformer ignored from base

### ISSUE THREAD

**Issue by jeusdi** [kubernetes-sigs/kustomize#2408]
Here my kustomize structure:

```
./kustomize/
├── base
│   ├── kustomization.yaml
│   ├── kustomizeconfig
│   │   └── transformers
│   │       └── labels-transformer.yaml
│   └── resources
│       ├── deployment.yaml
│       └── service.yaml
└── overlays
    ├── dev
    │   ├── kustomization.yaml
    │   └── kustomizeconfig
    │       ├── generators
    │       │   ├── config-generator.yaml
    │       └── transformers
    │           ├── labels-transformer.yaml
    └── prod
        ├── kustomization.yaml
        └── kustomizeconfig
            ├── generators
            │   ├── config-generator.yaml
            └── transformers
                ├── labels-transformer.yaml
```

As you can see, on each `dev` and `prod` overlays, I've a `kustomizeconfig/generators/config-generator`.

By other side, on each `dev` and `prod` overlays **and also on `base`**, I've a `kustomizeconfig/transformers/labels-transformer.yaml`.

On **base** (`base/transformers/labels-transformer`) it looks like:

```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  app.kubernetes.io/name: backend
  app.kubernetes.io/instance: backend
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: service
  app.kubernetes.io/part-of: covid
fieldSpecs:
- kind: ConfigMap
  path: metadata/labels
  create: true
...
```

On **prod** (`overlays/prod/transformers/labels-transformer`) overlay:

```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  stage: production
fieldSpecs:
- kind: ConfigMap
  path: metadata/labels
  create: true
...
```

When I perform `kustomize build kustomize/overlays/prod`:

```
apiVersion: v1
data:
  ...
kind: ConfigMap
metadata:
  labels:
    stage: production
  name: prod-covid-backend-config-cc624fc45h
```

As you can see, only `stage: production` label is added.

I need that when configmap is generated on each overlay it inherits `base` labels transformer. currently it seems it's ignored.

Any ideas?

I've tested with removing labels from `prod` overlay, and as I suggest, `base` `label transformer` is ignored. I mean, no labels are attached.

```
apiVersion: v1
data:
  ...
kind: ConfigMap
metadata:
  name: prod-covid-backend-config-cc624fc45h
```
