### ISSUE TITLE
[HELP] vars well defined but not replaced

### ISSUE THREAD

**Issue by jeusdi** [kubernetes-sigs/kustomize#2425]
I've this `kustomization.yaml`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - resources/configmap.yaml

vars:
- name: COVID_LABELS
  objref:
    kind: ConfigMap
    name: covid-backend-config
    apiVersion: v1
  fieldref:
    fieldpath: metadata.labels
```

My `resources/configmap.yaml` is:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: covid-backend-config-other
labels: $(COVID_LABELS)
data:
  key: value
```

When I'm trying to generate artifacts, I'm getting this message:

> well-defined vars that were never replaced: COVID_LABELS

Genarted configmap:

```
apiVersion: v1
data:
  key: value
kind: ConfigMap
labels: $(COVID_LABELS)
metadata:
  name: dev-covid-backend-config-other
```

Any ideas?

**Comment by ricochet** [comment]
So your kustomization yaml basically says, create a var named COVID_LABELS based on the literal value at metadata.labels. In your configmap, you have $(COVID_LABELS). So there are several problems here: vars are not for arrays and no literal value for the var was specified.

Can you use a LabelTransformer instead? I think this will be a better fit for what you're trying to do.

`kustomization.yaml`

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - resources/configmap.yaml

transformers:
 - transformers/transformer.yaml
```

`transformers/transformer.yaml`

```yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: covid-backend-label-transformer
labels:
  someLabel: someValue
  someLabel2: someValue2
fieldSpecs:
- path: metadata/labels
  create: true
```

Generated ConfigMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: covid-backend-config-other
  labels:
      someLabel: someValue
      someLabel2: someValue2
data:
  key: value
```
