### ISSUE TITLE
Kustomize generates different outputs for the same set of input files

### ISSUE THREAD

**Issue by dualbus** [kubernetes-sigs/kustomize#2431]
I've uploaded the input files I'm using to reproduce this issue here: https://github.com/dualbus/kustomize-output-bug/tree/07fbe10c0180a6bd6659045bea7b6cd425aadc6a

Running the same kustomize command against these files returns different results:

```
dualbus@system76-pc:~/tmp$ ./kubectl kustomize overlay/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
```

```
dualbus@system76-pc:~/tmp$ ./kubectl kustomize overlay/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: my-namespace
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
```

I understand that this is an incorrect use of the overlays (i.e. I should've put the `deployment.yaml` under `patches` and not `resources` in overlay/kustomization.yaml), although I was expecting kustomize to return some sort of validation error.

I'm using `kubectl` version `1.18.2`:

```
dualbus@system76-pc:~/tmp$ ./kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
