### ISSUE TITLE
Clarify merge error

### ISSUE THREAD

**Issue by mcristina422** [kubernetes-sigs/kustomize#2450]
When setting up a secretGenerator with a base that has a secret named the same I came across this error

```yaml
secretGenerator:
  - name: app
    files:
      - secret/foo
      - secret/bar

```

```
$ kustomize build kustomize/overlays/lab

Error: merging from generator &{0xc0004cdd70 { } {map[] map[] false} {{ app  {[] [secret/foo secret/bar] []}} merge}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"Secret"}, Name:"app", Namespace:""} exists; must merge or replace
```

So I tried adding `type`, not realizing it would set the `secret.type` to `merge`
```yaml
secretGenerator:
  - name: witness
    type: merge
    files:
      - secret/foo
      - secret/bar
```

where I should have set 
```yaml
secretGenerator:
  - name: app
    behavior: merge
    files:
      - secret/foo
      - secret/bar
```

Updating the error to be `behavior must be merge or replace` would clarify this a ton

https://github.com/kubernetes-sigs/kustomize/blob/b3ce3a7882e62b70da2a0a95f901139183ee5c5f/api/resmap/resmap.go#L694
