### ISSUE TITLE
Plugin Secret Hash not updating with stringData

### ISSUE THREAD

**Issue by bertrmz** [kubernetes-sigs/kustomize#2466]
When a plugin generates a Secret with `stringData` & the needs-hash annotation, and the `stringData` changes, the hash is expected to change. Currently, the hash stays the same.

It seems like only `data` is taken into account in the [secretHash functionality here](https://github.com/kubernetes-sigs/kustomize/blob/a0b997308a4dbadf665b975837adb0a07dd903fa/api/k8sdeps/kunstruct/hasher.go#L66).

`stringData` should also be taken into account, similar to how the ConfigMap hasher takes `binaryData` into account.

kustomize version:
```
Version:kustomize/v3.5.4
GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026
BuildDate:2020-01-11T03:12:59Z
GoOs:darwin
GoArch:amd64
```

#### Input

plugin/someteam.example.com/v1/bashedsecret/BashedSecret

```bash
#!/bin/bash

cat <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: foo
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
  bar: baz
EOF
```

base/bashedSecret.yaml

```yaml
apiVersion: someteam.example.com/v1
kind: BashedSecret
metadata:
  name: qux
```

base/kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - bashedSecret.yaml
```

#### Output

`kustomize build --enable_alpha_plugins`

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: foo-b6457bd6t6
stringData:
  bar: baz
type: Opaque
```

#### Input

Change a value in stringData, in plugin/someteam.example.com/v1/bashedsecret/BashedSecret.

```diff
diff --git a/scripts/kustomize/plugin/someteam.example.com/v1/bashedsecret/BashedSecret b/scripts/kustomize/plugin/someteam.example.com/v1/bashedsecret/BashedSecret
index e728c4dc84..6e94612ca1 100755
--- a/scripts/kustomize/plugin/someteam.example.com/v1/bashedsecret/BashedSecret
+++ b/scripts/kustomize/plugin/someteam.example.com/v1/bashedsecret/BashedSecret
@@ -9,5 +9,5 @@ metadata:
     kustomize.config.k8s.io/needs-hash: "true"
 type: Opaque
 stringData:
-  bar: baz
+  bar: quz
 EOF
```

#### Output

`kustomize build --enable_alpha_plugins` produces a name with the **same hash**, but an updated value.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: foo-b6457bd6t6
stringData:
  bar: quz
type: Opaque
```
