### ISSUE TITLE
AnnotationsTransformer failure when unmarshaling string that is a number

### ISSUE THREAD

**Issue by ricochet** [kubernetes-sigs/kustomize#2472]
kustomize version
```bash
{Version:3.5.5 GitCommit:897e7b6e61e65188d846c32bd3af9ef68b0f746a BuildDate:2020-05-12T00:09:31+01:00 GoOs:darwin GoArch:amd64}
```

```yaml
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
name: deployment-annotations-transformer
annotations:
cadence/name: "stable"
cadence/release: "20200513.1589404923224"
cadence/version: "2020"
fieldSpecs:
- path: metadata/annotations
  create: true
```

```bash
Error: json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string
```

With git-bisect, this appears to be the change: https://github.com/kubernetes-sigs/kustomize/commit/7feb873ef685b2246a14ac53592fffe3e907b59d

This is not reproducible on 3.5.4.

According to the annotations spec, passing numbers as a string is valid: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
