### ISSUE TITLE
commonLabels adds selector to headless service without selector

### ISSUE THREAD

**Issue by bsuh** [kubernetes-sigs/kustomize#249]
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

Sometimes you want to specifically create a service without any selectors.

external-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service
subsets:
  - addresses:
      - ip: 192.168.60.1
      - ip: 192.168.60.2
    ports:
      - port: 80
```

kustomization.yaml
```
commonLabels:
  environment: "staging"

resources:
  - external-service.yaml
```

```
~/test % kustomize build .
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    environment: staging
  name: external-service
subsets:
- addresses:
  - ip: 192.168.60.1
  - ip: 192.168.60.2
  ports:
  - port: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: staging
  name: external-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    environment: staging
```

The transformed service has a selector with only the commonLabel effectively making the service backed by every pod.
