### ISSUE TITLE
AnnotationsTransformer does not create annotations if annotations is set to null

### ISSUE THREAD

**Issue by ephesused** [kubernetes-sigs/kustomize#2491]
This issue appears in v3.5.5 and master (66e889e).

Test files:

kustomization.yaml
```
resources:
- resources.yaml

transformers:
- annotations.yaml
```

resources.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations: null
  name: annotations-are-null
data:
  hello: world
```

annotations.yaml
```
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: annotations-transformer
annotations:
  testing.invalid/addition: greetings
fieldSpecs:
- path: metadata/annotations
  create: true
```

Expected behavior (seen in v3.4.0 up to, and including, v3.5.4):
```
$ /workspace/kustomize/v3.5.4/kustomize version
{Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
$ /workspace/kustomize/v3.5.4/kustomize build .
apiVersion: v1
data:
  hello: world
kind: ConfigMap
metadata:
  annotations:
    testing.invalid/addition: greetings
  name: annotations-are-null
$
```

Actual behavior (v3.5.5 and master / 66e889e):
```
$ /workspace/kustomize/v3.5.5/kustomize version
{Version:kustomize/v3.5.5 GitCommit:897e7b6e61e65188d846c32bd3af9ef68b0f746a BuildDate:2020-05-11T16:51:33Z GoOs:linux GoArch:amd64}
$ /workspace/kustomize/v3.5.5/kustomize build .
apiVersion: v1
data:
  hello: world
kind: ConfigMap
metadata:
  annotations: null
  name: annotations-are-null
$
```

Not surprisingly, the behavior is the same as an explicit null when the ConfigMap has:
```
metadata:
  annotations:
  name: annotations-are-null
```

The following scenarios work as expected:
```
metadata:
  name: annotations-are-absent
```

```
metadata:
  annotations: {}
  name: annotations-are-null
```

```
metadata:
  annotations:
    test.invalid: some-value
  name: annotations-are-populated
```
