### ISSUE TITLE
Unable to add command strings with patchesStrategicMerge

### ISSUE THREAD

**Issue by L-U-C-K-Y** [kubernetes-sigs/kustomize#2492]
Hi all

I would like to apply the following patchesStrategicMerge:

```yaml
spec:
  template:
    spec:
      containers:
        - name: cloud-sql-proxy
          command:
            - "/cloud_sql_proxy"
            - "-instances=xxx:xxx:xxx=tcp:5432"
            - "-credential_file=/secrets/cloudsql/sql_credentials.json"
```
Or:
```yaml
spec:
  template:
    spec:
      containers:
        - name: cloud-sql-proxy
          command:
            [
              "/cloud_sql_proxy",
              "-instances=xxx:xxx:xxx=tcp:5432",
              "-credential_file=/secrets/cloudsql/sql_credentials.json",
            ]
```

And I get the following output:
```
spec:
  template:
    spec:
      containers:
      - command:
        - /cloud_sql_proxy
        - -instances=xxx:xxx:xxx=tcp:5432
        - -credential_file=/secrets/cloudsql/sql_credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        name: cloud-sql-proxy
```
When I remove the command part, it works correctly.

Anyone has a clue and can help me out?

**Comment by paultiplady** [comment]
`patchStrategicMerge` uses replacement by default for lists: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#background

If you want to merge a list, I believe you should use the `$patch: merge` directive ([docs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#merge-directive)).

This would look something like this (haven't tested this though):

```yaml
spec:
  template:
    spec:
      containers:
        - $patch: merge
        - name: cloud-sql-proxy
          command:
            - "/cloud_sql_proxy"
            - "-instances=xxx:xxx:xxx=tcp:5432"
            - "-credential_file=/secrets/cloudsql/sql_credentials.json"
```
