### ISSUE TITLE
Create environment variables from env file with Kustomize

### ISSUE THREAD

**Issue by lucbas** [kubernetes-sigs/kustomize#2497]
Hi all

I try to add/generate a configmap from a file with kuztomize.

Previously, I have used the following command to create the configMap:
`kubectl create configmap service1-env-vars --from-env-file=env-file`

Afterwards, I added it through the following reference:

```
spec:
  template:
    spec:
      containers:
        - name: service1
          envFrom:
            - configMapRef:
                name: service1-env-vars
```

While this is working fine manually, I'm having a hard time to achieve the same in Kustomize.

I have tried the following things:

# configMapGenerator

**kustomize.yaml**
```
configMapGenerator:
- name: service1-env-vars
  files:
    # configfile is used as key
    - env-file
```
**env-file**
```
VAR1=xxx
VAR2=xyz
```
**Output**
```
apiVersion: v1
data:
  .env-file: |+
    VAR1=xxx
    VAR2=xyz
kind: ConfigMap
metadata:
  name: service1-env-vars
  namespace: yyy
```
`kubectl-apply -f` works, but the vars are not correctly used within the container.

# configMap.yaml
**kustomize.yaml**
```
resources:
  - deployment.yaml
  - service.yaml
  - configMap.yaml
```
**configMap.yaml**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobdone-chat-service-env
data:
  VAR1: xxx
  VAR2: xyz
```
**Ouput**
```
apiVersion: v1
data:
  VAR1: xxx
  VAR2: xyz
kind: ConfigMap
metadata:
  name: service1-env-vars
  namespace: yyy
```
`kubectl apply -f:`

```
`Error from server (BadRequest): error when creating "STDIN": ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found 5, error found in #10 byte of ...
```
**EDIT:** I was able to generate a configMap from env files by adding the following to the `kustomize.yaml` in the overlay that required it.:
```
configMapGenerator:
- envs:
  - env-file
  name: service1-env-vars
```
While this works, is there an option how I can have the common envs generated from an env file in the `base` directory and generate overlay-specific envs in the `overlay` from another env file?
