### ISSUE TITLE
Don't apply namespace transform to cluster scoped custom resources

### ISSUE THREAD

**Issue by jlewi** [kubernetes-sigs/kustomize#2498]
Is there a way to prevent the namespace transform from adding the namespace to cluster scoped custom resources?

I looked at the docs for customizing transformers but it seems like those are only additive; e.g. I can make the transformer aware of a namespace field in a nonstandard location but not remove some resouces.

I have kustomize packages which contain instances of cluster scoped resources in addition to namespace scoped resources.

The namespace transform ends up adding the namespace field to those resources. This will cause problems for certain tools that consider having a namespace on ClusterScoped resources to be an error.

In my case I'm using ACM which is GCP's solution for GitOps.

**Comment by liuyangc3** [comment]
somting like this?
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: ns
    $patch: delete
```
