### ISSUE TITLE
Update an array containing a parameterized value (and conditionally adding env to deployments) 

### ISSUE THREAD

**Issue by rrichardson** [kubernetes-sigs/kustomize#2500]
I have a collection of manifests that I am mutating for a specific set of environments.  
Specifically,  a subset of these manifests are Deployments. I want to add an environment variable if it doesn't already exist.  This poses 3 problems: 

1. For each Deployment I want to update the `spec/template/spec/containers/N`  where  `N.name` == the `metadata.name`  
2. In the Containers object in the deployment mentioned in #1,  I want to add `env` if it doesn't already exist.  
3. If env does exist, and the variable I want is present, I want to alter its value,  if it's not present, I want to add a new element to the array that contains my intended name and value. 

I thought I might be able to accomplish part one using vars, but I keep running into 
`Error: var '{DEPLOYMENT_NAME apps_v1_Deployment {metadata.name}}' cannot be mapped to a field in the set of known resources`  

The relevant part of my kustomize is: 
```
vars:
  - name: DEPLOYMENT_NAME
    objref:
      kind: Deployment
      apiVersion: apps/v1
patches:
- path: setenv.yaml
  target:
    kind: Deployment
```

Then the setenv.yaml: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
spec:
  template:
    spec:
      containers:
      - name: $(DEPLOYMENT_NAME)
        env:
        - name: NODE_ENV
          value: development
```

I am not sure what is causing the `cannot be mapped to a field...` error,  but even if I got past that,  I am assuming that I can't use $(DEPLOYMENT_NAME) as a selector.  
Is there an alternate approach for this that might work?

After I accomplish that, how can I "upsert" both the env object and its contents?  
In the approaches that I've tried,  I can't seem to get kustomize to not just create another array entry so that the result ends up looking like 

```spec: 
      containers:  
      - env: 
          name: NODE_ENV
          value: development
      - name: myintendedcontainer
         image: ...
``` 

Am I taking the wrong approach here?   I would really like to avoid having to spell out a kustomization patch for every named deployment I am using.
