### ISSUE TITLE
Transformer replicas get wrong replicas type after replacing a resource Kind

### ISSUE THREAD

**Issue by liuyangc3** [kubernetes-sigs/kustomize#2512]
kustomize versoin 3.5.5

layout
```
├── base
│   ├── mykind-config.yaml
│   ├── deployment.yaml
│   ├── kustomization.yaml
│   └── replace.yaml
├── kustomize
│   └── plugin
│       └── someteam.example.com/v1
│           ├── replacementtransformer
│               └── ReplacementTransformer.so
├── overlay
│   ├── kustomization.yaml
```

base/kustomization.yaml 
```yaml
cat > base/kustomization.yaml <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- mykind-config.yaml

resources:
- deployment.yaml

# replace Deployment to Mykind
transformers:
- replace.yaml
EOF
```

base/deployment.yaml
```yaml
cat > base/deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
EOF
```

base/mykind-config.yaml, I only defined `replicas` here.
```yaml
cat > base/mykind-config.yaml <<EOF
replicas:
- path: spec/replicas
  create: true
  kind: Mykind
EOF
```

base/replace.yaml,  I compiled the plugin ReplacementTransformer.go to `ReplacementTransformer.so`, and I am tring to replace the `kind: Deployment` to `kind: Mykind`.
```yaml
cat > base/replace.yaml <<EOF
apiVersion: someteam.example.com/v1
kind: ReplacementTransformer
metadata:
  name: whatever
replacements:
- target:
    objref:
      kind: Deployment
    fieldrefs:
    - kind
  source:
    value: Mykind
EOF
```
everything works well now, as you can see, `Deployment` is replaced to `Mykind`.
```bash
kustomize build --enable_alpha_plugins base
apiVersion: apps/v1
kind: Mykind
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
```

---

Then I added a overlay dir to change the replicas
```yaml
cat > overlay/kustomization.yaml <<EOF
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

replicas:
- name: mysql
  count: 2
```

and replicas is changed to `2` as expected.

```bash
kustomize build --enable_alpha_plugins overlay
apiVersion: apps/v1
kind: Mykind
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
```

but if I add a patch before replicas transform, change it to `9`.
```diff
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../base

+ patchesStrategicMerge:
+ - patch.yaml

replicas:
 - name: mysql
  count: 2
---
cat overlay/patch.yaml
apiVersion: apps/v1
kind: Mykind
metadata:
  name: mysql
spec:
  replicas: 9
```

replicas will be fail
```bash
kustomize build --enable_alpha_plugins overlay
Error: 9 is expected to be float64
```
I check the code, replicas count type should be `int64`, but it was changed to `float64` in patchesStrategicMerge somehow.
