### ISSUE TITLE
Merge Kustomization fields from another file

### ISSUE THREAD

**Issue by michaelgeorgeattard** [kubernetes-sigs/kustomize#2514]
Given the following structure:

```yaml
application
  kustomization.yaml
  patch.yaml
base
  kustomization.yaml
  service.yaml
environment
  a
    kustomization.yaml
  b
    kustomization.yaml
```

https://github.com/michaelgeorgeattard/multiple-inheritance-kustomize

What is the best way to achieve the following?

![kustomization](https://user-images.githubusercontent.com/5755302/82578794-2ca61f80-9b8d-11ea-9c15-4be56dca8af2.png)

Expected output of kustomize build in `environment/a`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    foo: bar
    patched: selector # this needs to be added by the patch
```

Expected output of kustomize build in `environment/b`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
  - name: http
    port: 1234
    protocol: TCP
    targetPort: http
  selector:
    foo: bar
    patched: selector # this needs to be added by the patch
```
