### ISSUE TITLE
configMapGenerator name with suffix not applied to custom resources

### ISSUE THREAD

**Issue by whyvez** [kubernetes-sigs/kustomize#2524]
I'm deploying an Argo WorkflowTemplate with Kustomize and the configMapGenerator generated name with the suffix does not get applied to my WorkflowTemplate. Is there a way to enable this or will Kustomize only make changes to K8s builtin resource?

My WorkflowTemplate contains an `env` property that sources from a ConfigMap. 

```
env:
- name: PGHOST
  valueFrom:
    configMapKeyRef:
      name: config-api-exports
      key: PGHOST
- name: PGDATABASE
  valueFrom:
    configMapKeyRef:
      name: config-api-exports
      key: PGDATABASE
- name: PGUSER
  valueFrom:
    configMapKeyRef:
      name: config-api-exports
      key: PGUSER
```

The `config-api-exports` ConfigMap is generated by a configMapGenerator.

```
configMapGenerator:
  - name: config-api-exports
    literals:
      - PGUSER="postgres"
      - PGDATABASE="my-db"
      - PGHOST="127.0.0.7"
```
Even though this is a custom type I would expect Kustomize to walk the manifest and find and replace any yaml block that matches up with a valid Kubernetes type, env/configMapKeyRef in this case.

**Comment by pst** [comment]
Have you specified the namereferences like [documented](https://github.com/kubernetes-sigs/kustomize/blob/d5b44461b9b0978207eb49d0a6c3e2f94bf5b417/examples/transformerconfigs/crd/README.md)?

**Comment by whyvez** [comment]
@pst  Awesome, got it. Thank you!

Ended up adding this configuration...

```yaml
nameReference:
  - kind: ConfigMap
    fieldSpecs:
    - path: spec/templates/script/env/valueFrom/configMapKeyRef/name
      kind: WorkflowTemplate

images:
  - path: spec/templates/script/image
    kind: WorkflowTemplate
```
