### ISSUE TITLE
Failed to add labels to statefulset , unsupported yaml node

### ISSUE THREAD

**Issue by bluven** [kubernetes-sigs/kustomize#2533]
I wanted to add some label to all mysql resources, but some error happened when I executed
`kustomize build .`, here is a [demo project ](https://github.com/bluven/kustomize-sts-bug)

My kustomize is 3.5.5. I have tried 3.5.4, it worked.

kustomization.yaml
```
resources:
  - all.yaml

commonLabels:
  app.bocloud.com/name: foo
```

all.yaml
```
---
# Source: mysql-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
    chart: mysql-operator-0.4.0-rc.1
    release: mysql-operator
    heritage: Helm
---
# Source: mysql-operator/templates/orc-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-operator-orc
  labels:
    app: mysql-operator
    chart: mysql-operator-0.4.0-rc.1
    release: mysql-operator
    heritage: Helm
data:
  TOPOLOGY_USER: "b3JjaGVzdHJhdG9y"
  TOPOLOGY_PASSWORD: "Nnc2NHBhaGJzUA=="
---
# Source: mysql-operator/templates/orc-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-operator-orc
  labels:
    app: mysql-operator
    chart: mysql-operator-0.4.0-rc.1
    release: mysql-operator
    heritage: Helm
data:
  orchestrator.conf.json: "{\n  \"ApplyMySQLPromotionAfterMasterFailover\": false,\n  \"BackendDB\": \"sqlite\",\n  \"Debug\": false,\n  \"DetachLostReplicasAfterMasterFailover\": true,\n  \"DetectClusterAliasQuery\": \"SELECT CONCAT(SUBSTRING(@@hostname, 1, LENGTH(@@hostname) - 1 - LENGTH(SUBSTRING_INDEX(@@hostname,'-',-2))),'.',SUBSTRING_INDEX(@@report_host,'.',-1))\",\n  \"DetectInstanceAliasQuery\": \"SELECT @@hostname\",\n  \"DiscoverByShowSlaveHosts\": false,\n  \"FailMasterPromotionIfSQLThreadNotUpToDate\": true,\n  \"HTTPAdvertise\": \"http://{{ .Env.HOSTNAME }}-svc:80\",\n  \"HostnameResolveMethod\": \"none\",\n  \"InstancePollSeconds\": 5,\n  \"ListenAddress\": \":3000\",\n  \"MasterFailoverDetachReplicaMasterHost\": true,\n  \"MySQLHostnameResolveMethod\": \"@@report_host\",\n  \"MySQLTopologyCredentialsConfigFile\": \"/etc/orchestrator/orc-topology.cnf\",\n  \"OnFailureDetectionProcesses\": [\n    \"/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcFailureDetection' 'Failure: {failureType}, failed host: {failedHost}, lost replcas: {lostReplicas}' || true\",\n    \"/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true\"\n  ],\n  \"PostIntermediateMasterFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostIntermediateMasterFailover' 'Failure type: {failureType}, failed hosts: {failedHost}, slaves: {countSlaves}' || true\"\n  ],\n  \"PostMasterFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper event '{failureClusterAlias}' 'OrcPostMasterFailover' 'Failure type: {failureType}, new master: {successorHost}, slaves: {slaveHosts}' || true\"\n  ],\n  \"PostUnsuccessfulFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper event -w '{failureClusterAlias}' 'OrcPostUnsuccessfulFailover' 'Failure: {failureType}, failed host: {failedHost} with {countSlaves} slaves' || true\"\n  ],\n  \"PreFailoverProcesses\": [\n    \"/usr/local/bin/orc-helper failover-in-progress '{failureClusterAlias}' '{failureDescription}' || true\"\n  ],\n  \"ProcessesShellCommand\": \"sh\",\n  \"RaftAdvertise\": \"{{ .Env.HOSTNAME }}-svc\",\n  \"RaftBind\": \"{{ .Env.HOSTNAME }}\",\n  \"RaftDataDir\": \"/var/lib/orchestrator\",\n  \"RaftEnabled\": true,\n  \"RaftNodes\": [],\n  \"RecoverIntermediateMasterClusterFilters\": [\n    \".*\"\n  ],\n  \"RecoverMasterClusterFilters\": [\n    \".*\"\n  ],\n  \"RecoveryIgnoreHostnameFilters\": [],\n  \"RecoveryPeriodBlockSeconds\": 300,\n  \"RemoveTextFromHostnameDisplay\": \":3306\",\n  \"SQLite3DataFile\": \"/var/lib/orchestrator/orc.db\",\n  \"SlaveLagQuery\": \"SELECT TIMESTAMPDIFF(SECOND,ts,NOW()) as drift FROM sys_operator.heartbeat ORDER BY drift ASC LIMIT 1\",\n  \"UnseenInstanceForgetHours\": 1\n}"
  orc-topology.cnf: |
    [client]
    user = {{ .Env.ORC_TOPOLOGY_USER }}
    password = {{ .Env.ORC_TOPOLOGY_PASSWORD }}
---
# Source: mysql-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: 'mysql-operator'
    chart: 'mysql-operator-0.4.0-rc.1'
    heritage: 'Helm'
    release: 'mysql-operator'
  name: 'mysql-operator'
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlbackups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - events
  - jobs
  - pods
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlclusters
  - mysqlclusters/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
# Source: mysql-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
    chart: mysql-operator-0.4.0-rc.1
    release: mysql-operator
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-operator
subjects:
  - name: mysql-operator
    namespace: "default"
    kind: ServiceAccount
---
# Source: mysql-operator/templates/orc-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-operator-0-svc
  labels:
    app: mysql-operator
    chart: mysql-operator-0.4.0-rc.1
    release: mysql-operator
    heritage: Helm
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 3000
  - name: raft
    port: 10008
    targetPort: 10008
  selector:
    statefulset.kubernetes.io/pod-name: mysql-operator-0
---
# Source: mysql-operator/templates/orc-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
    chart: mysql-operator-0.4.0-rc.1
    release: mysql-operator
    heritage: Helm
spec:
  type: ClusterIP
  selector:
    app: mysql-operator
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
# Source: mysql-operator/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-operator
  labels:
    app: mysql-operator
    chart: mysql-operator-0.4.0-rc.1
    release: mysql-operator
    heritage: Helm
spec:
  replicas: 1
  serviceName: mysql-operator-orc
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: mysql-operator
      release: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
        release: mysql-operator
      annotations:
        checksum/config: 59f1829eaf82854c278eae4074a67583ac139bae3d63ecdb1d3445be4dc9b100
        checksum/secret: b1f94900d7ea07c7af1ea308aec78c3169cf7720a75eddeb746b6b8bfb8d3f38
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          image: "registry.bluven.me:5000/bocloud/mysql-operator:0.4.0-rc.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: ORC_TOPOLOGY_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-operator-orc
                  key: TOPOLOGY_USER
            - name: ORC_TOPOLOGY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-operator-orc
                  key: TOPOLOGY_PASSWORD
          args:
            - --leader-election-namespace=default
            # connect to orchestrator on localhost
            - --orchestrator-uri=http://127.0.0.1:3000/api
            - --sidecar-image=registry.bluven.me:5000/bocloud/mysql-operator-sidecar:0.4.0-rc.1
            - --metrics-exporter-image=registry.bluven.me:5000/bocloud/mysqld-exporter:v0.11.0
          resources:
            {}
          # TODO: add livenessProbe to controller
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
        - name: orchestrator
          image: registry.bluven.me:5000/bocloud/mysql-operator-orchestrator:0.4.0-rc.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: web
              protocol: TCP
            - containerPort: 10008
              name: raft
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - prefix: ORC_
              secretRef:
                name: mysql-operator-orc
          volumeMounts:
            - name: data
              mountPath: /var/lib/orchestrator/
            - name: config
              mountPath: /templates/
          livenessProbe:
            timeoutSeconds: 10
            initialDelaySeconds: 200
            httpGet:
              path: /api/lb-check
              port: 3000
          # https://github.com/github/orchestrator/blob/master/docs/raft.md#proxy-healthy-raft-nodes
          readinessProbe:
            timeoutSeconds: 10
            httpGet:
              path: /api/raft-health
              port: 3000
          resources:
            null

      volumes:
        - name: config
          configMap:
            name: mysql-operator-orc

      # security context to mount corectly the volume for orc
      securityContext:
        fsGroup: 777

      affinity:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 1Gi
```

error 
```
Error: obj {"apiVersion": "apps/v1", "kind": "StatefulSet", "metadata": {"labels": {"app": "mysql-operator",
      "chart": "mysql-operator-0.4.0-rc.1", "heritage": "Helm", "release": "mysql-operator"},
    "name": "mysql-operator"}, "spec": {"podManagementPolicy": "Parallel", "replicas": 1,
    "selector": {"matchLabels": {"app": "mysql-operator", "release": "mysql-operator",
        app.bocloud.com/name: foo}}, "serviceName": "mysql-operator-orc", "template": {
      "metadata": {"annotations": {"checksum/config": "59f1829eaf82854c278eae4074a67583ac139bae3d63ecdb1d3445be4dc9b100",
          "checksum/secret": "b1f94900d7ea07c7af1ea308aec78c3169cf7720a75eddeb746b6b8bfb8d3f38"},
        "labels": {"app": "mysql-operator", "release": "mysql-operator"}}, "spec": {
        "affinity": null, "containers": [{"args": ["--leader-election-namespace=default",
              "--orchestrator-uri=http://127.0.0.1:3000/api", "--sidecar-image=registry.bluven.me:5000/bocloud/mysql-operator-sidecar:0.4.0-rc.1",
              "--metrics-exporter-image=registry.bluven.me:5000/bocloud/mysqld-exporter:v0.11.0"],
            "env": [{"name": "ORC_TOPOLOGY_USER", "valueFrom": {"secretKeyRef": {
                    "key": "TOPOLOGY_USER", "name": "mysql-operator-orc"}}}, {"name": "ORC_TOPOLOGY_PASSWORD",
                "valueFrom": {"secretKeyRef": {"key": "TOPOLOGY_PASSWORD", "name": "mysql-operator-orc"}}}],
            "image": "registry.bluven.me:5000/bocloud/mysql-operator:0.4.0-rc.1",
            "imagePullPolicy": "IfNotPresent", "name": "operator", "resources": {}},
          {"env": [{"name": "POD_IP", "valueFrom": {"fieldRef": {"fieldPath": "status.podIP"}}}],
            "envFrom": [{"prefix": "ORC_", "secretRef": {"name": "mysql-operator-orc"}}],
            "image": "registry.bluven.me:5000/bocloud/mysql-operator-orchestrator:0.4.0-rc.1",
            "imagePullPolicy": "IfNotPresent", "livenessProbe": {"httpGet": {"path": "/api/lb-check",
                "port": 3000}, "initialDelaySeconds": 200, "timeoutSeconds": 10},
            "name": "orchestrator", "ports": [{"containerPort": 3000, "name": "web",
                "protocol": "TCP"}, {"containerPort": 10008, "name": "raft", "protocol": "TCP"}],
            "readinessProbe": {"httpGet": {"path": "/api/raft-health", "port": 3000},
              "timeoutSeconds": 10}, "resources": null, "volumeMounts": [{"mountPath": "/var/lib/orchestrator/",
                "name": "data"}, {"mountPath": "/templates/", "name": "config"}]}],
        "securityContext": {"fsGroup": 777}, "serviceAccountName": "mysql-operator",
        "volumes": [{"configMap": {"name": "mysql-operator-orc"}, "name": "config"}]}},
    "volumeClaimTemplates": [{"metadata": {"name": "data", labels: {app.bocloud.com/name: foo}},
        "spec": {"accessModes": ["ReadWriteOnce"], "resources": {"requests": {"storage": "1Gi"}}}}]}}
 at path spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/labelSelector/matchLabels: unsupported yaml node
```
