### ISSUE TITLE
configMapGenerator unknown field "options"

### ISSUE THREAD

**Issue by QuRa** [kubernetes-sigs/kustomize#2535]
I need to add additional label to one generated ConfigMap, according to [documentation](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#field-name-configMapGenerator) I should be able to do so by `options` field:

```
configMapGenerator:
  - name: my-java-server-env-vars
    literals:
      - JAVA_HOME=/opt/java/jdk
      - JAVA_TOOL_OPTIONS=-agentlib:hprof
    options:
      disableNameSuffixHash: true
      labels:
        pet: dog
```
But I'm getting:
`Error: json: unknown field "options"`

```
kustomize version                                                                                                                                                                                                                                           
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:28:58+00:00 GoOs:darwin GoArch:amd64}
