### ISSUE TITLE
serviceAccountName does not add prefix as expected

### ISSUE THREAD

**Issue by leopay** [kubernetes-sigs/kustomize#2559]
deployment.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  template:
    spec:
      containers:
      - image: dummy
        name: dummy
```

serviceaccount.yaml

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy
```

kustomization.yaml
```yaml
resources:
- deployment.yaml
- serviceaccount.yaml
namePrefix: foo-

patches:
- patch: |-
    - op: replace
      path: "/metadata/name"
      value: bar
  target:
    kind: ServiceAccount
- patch: |-
    - op: replace
      path: "/metadata/name"
      value: bar
    - op: add
      path: "/spec/template/spec/serviceAccountName"
      value: bar
  target:
    kind: Deployment
```

kustomize build output:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo-bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-bar // work as expected
spec:
  template:
    spec:
      containers:
      - image: dummy
        name: dummy
      serviceAccountName: bar //expect foo-bar not bar
```

kustomize is v3.6.1
