### ISSUE TITLE
Secret names in Knative service does get mapped to generated secret name

### ISSUE THREAD

**Issue by munjalpatel** [kubernetes-sigs/kustomize#2564]
Hello,

I have following config:

**service.yaml**
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-data-twitter
spec:
  template:
    spec:
      containers:
        - image: svc-data-twitter
          env:
            - name: TWITTER_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: svc-data-twitter
                  key: TWITTER_TOKEN_KEY
            - name: TWITTER_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: svc-data-twitter
                  key: TWITTER_TOKEN_SECRET

```

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: svc-data-twitter
    envs:
      - .env
resources:
  - ./service.yaml
images:
  - name: svc-data-twitter
    newTag: dev
```

Running `kustomization build` generates this:
```yaml
apiVersion: v1
data:
  TWITTER_TOKEN_KEY: base64-encoded-value
  TWITTER_TOKEN_SECRET: base64-encoded-value
kind: Secret
metadata:
  name: svc-data-twitter-2dc784h7g8
type: Opaque
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: svc-data-twitter
spec:
  template:
    spec:
      containers:
      - env:
        - name: TWITTER_TOKEN_KEY
          valueFrom:
            secretKeyRef:
              key: TWITTER_TOKEN_KEY
              name: svc-data-twitter # incorrect; should be: svc-data-twitter-2dc784h7g8
        - name: TWITTER_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: TWITTER_TOKEN_SECRET
              name: svc-data-twitter # incorrect; should be: svc-data-twitter-2dc784h7g8
        image: svc-data-twitter:dev
```

Notice that in generated `knative service` config, value of `secretKeyRef.name` is still original and not updated to match the name in generated secret: `svc-data-twitter-2dc784h7g8`

** If I change `kind: Service` to `kind: Deployment`, it works. But that is not correct Knative config.

**Comment by monopole** [comment]
@Shell32-Natsu might be able to take a look at this.

This likely requires a modification to name back references 

https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namereference.go

**Comment by Shell32-Natsu** [comment]
@monopole Should we natively support Knative in Kustomize? If so we may need to add more back references than just service.

@munjalpatel For a work around, you can try to use a config file to allow Kustomize update the key name. Firstly, create a `config.yaml` file with content:

```
nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
    kind: Service
    group: serving.knative.dev
```

Then add this to you `kustomization.yaml` file:

```
configurations:
  - config.yaml
```

Then run `build`.
