### ISSUE TITLE
Patching block scalar,not merging correctly ? 

### ISSUE THREAD

**Issue by HugoRh** [kubernetes-sigs/kustomize#2572]
Hi,

In test.yaml I have a block scalar ( I hope it's the right name for it):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: http://someurl.com/argocd/repo1.git
    - url: http://someurl.com/argocd/repo2.git
    - url: http://someurl.com/argocd/repo3.git
    - url: http://someurl.com/argocd/repo4.git
    - url: http://someurl.com/argocd/repo5.git
  something: else
```

I'm trying with the below patch (patch-add-repo.yaml) to add some more repositories
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: http://someurl.com/argocd/repo6.git
    - url: http://someurl.com/argocd/repo7.git
    - url: http://someurl.com/argocd/repo8.git
```

But the end result looks like 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: http://someurl.com/argocd/repo6.git
    - url: http://someurl.com/argocd/repo7.git
    - url: http://someurl.com/argocd/repo8.git
  something: else
```
Instead of expected
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: http://someurl.com/argocd/repo1.git
    - url: http://someurl.com/argocd/repo2.git
    - url: http://someurl.com/argocd/repo3.git
    - url: http://someurl.com/argocd/repo4.git
    - url: http://someurl.com/argocd/repo5.git
    - url: http://someurl.com/argocd/repo6.git
    - url: http://someurl.com/argocd/repo7.git
    - url: http://someurl.com/argocd/repo8.git
  something: else
```

I'm a bit clueless here, any idea?

Thanks !!
