### ISSUE TITLE
Set image remove env parameter in configMapGenerator

### ISSUE THREAD

**Issue by Labbs** [kubernetes-sigs/kustomize#2574]
Hello,

I have this configuration before edit the image version with kustomize command

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: frontend
  newName: hashicorp/http-echo
  newTag: 0.2.1
- name: server
  newName: hashicorp/http-echo
  newTag: 0.2.1

configMapGenerator:
- name: server-config
  env: resources/server.env
- name: frontend-config
  files:
  - frontend.yaml=resources/frontend.env
  
```

When I run this command
```
 kustomize edit set image frontend=hashicorp/http-echo:latest
```

the result is this
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: frontend
  newName: hashicorp/http-echo
  newTag: latest
- name: server
  newName: hashicorp/http-echo
  newTag: 0.2.1

configMapGenerator:
- name: server-config
- files:
  - frontend.yaml=resources/frontend.env
  name: frontend-config
```

The env configuration is removed from the configMapGenerator for the server-config.
I test with the literal syntax and no problem.

Tested with 2 versions of kustomize (MacOS and Linux same result) :
- 3.6.1
- 3.5.5

**Comment by Shell32-Natsu** [comment]
We have changed to use `envs` instead of `env`. So use
```
configMapGenerator:
- name: server-config
  envs: 
  - resources/server.env
- name: frontend-config
  files:
  - frontend.yaml=resources/frontend.env
```

Some documentations are out-of-date.
