### ISSUE TITLE
Name reference transformer not working for ingress

### ISSUE THREAD

**Issue by saeed617** [kubernetes-sigs/kustomize#2582]
I have this ingress object
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              serviceName: example
              servicePort: 8000
            path: /
  tls:
    - hosts:
        - example.com
      secretName: example
```

and a service object
```yaml
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: example-app
```
and `nameSuffix: -staging` in kustomization.yaml file.
After running kustomize, the service name changes but the `serviceName` in ingress object does not.
I know that there are default transformers for these paths, but they are not working.
```yaml
  - path: spec/tls/secretName
    kind: Ingress
   ....
  - path: spec/rules/http/paths/backend/serviceName
    kind: Ingress
  - path: spec/backend/serviceName
    kind: Ingress
```
kustomie version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
