### ISSUE TITLE
Multiple image tags do not conflict

### ISSUE THREAD

**Issue by mattcary** [kubernetes-sigs/kustomize#2590]
If two patches are applied that conflict with each other (eg, modify the same field), the kustomize reports an error. However, if two image tag transformations happen, both are applied, with apparently the last one listed winning.

This seems to be a recipe for confusion. It would be better for kustomize to fail, I think, rather than succeed in a hard-to-predict manner (especially in a realistic deployment).

Here is an example. The final tag output is 2.0.0. If the resources i1.yaml and i2.yaml in images/kustomization.yaml are switched, then the output tag is 1.0.0.

`base/pod.yaml`:

```
kind: Pod
apiVersion: apps/v1
metadata:
  name: pod
spec:
  containers:
    - name: node
      image: some/image
```

`base/kustomization.yaml`

```
resources:
- pod.yaml
```

`overlay/kustomization.yaml`

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
transformers:
- ../image
```

`image/kustomization.yaml`

```
resources:
- i1.yaml
- i2.yaml
```

`image/i1.yaml`

```
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-registrar-1
imageTag:
  name: some/image
  newTag: "v1.0.0"
```

`image/i2.yaml`

```
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: imagetag-registrar-2
imageTag:
  name: some/image
  newTag: "v2.0.0"
```
