### ISSUE TITLE
patchesStrategicMerge: override container's env valueFrom by value results in both

### ISSUE THREAD

**Issue by Bobgy** [kubernetes-sigs/kustomize#2606]
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - image: dummy
        name: container1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
deployment-patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: container1
        env:
        - name: NAMESPACE
          value: ''
          # valueFrom: null
```
kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- deployment.yaml
patchesStrategicMerge:
- deployment-patch.yaml
```

results in
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: ""
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: dummy
        name: container1
```
Note, both value and valueFrom exists now.

Is this expected behavior?
Should I expect valueFrom to be removed automatically?

Workaround, add a `valueFrom: null` in the patch, then it will remove valueFrom.
