### ISSUE TITLE
Inline yaml comments not preserved in v1.0.6

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/kustomize#261]
Apparently #233 added support for preserving comments.

However with v1.0.6 (017c4ae0aa19195db2a51ecc5aa82c56a1f1c99b) I'm not seeing this behavior. 

kustomization.yaml:

```yaml
resources:
- service.yaml
```

base.yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: "<name-here>"
  labels:
    app: "<label>"
spec:
  selector:
    app: "<pod-label>"
  ports:
  - protocol: TCP
    port: 80         # port number the Service load balancer will accept traffic
    targetPort: 5000 # port number defined on Pod's containerPort
```

patch/patch.yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: "<name-here>"
spec:
  loadBalancerIP: "TYPE.IP.ADDR.HERE" # static IP address reserved for this LB
```

patch/kustomization.yaml

```yaml
bases:
- "../"
patches:
- patch.yaml
```

`kustomize build patch/` output (has no comments):

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <label>
  name: <name-here>
spec:
  kind: LoadBalancer
  loadBalancerIP: TYPE.IP.ADDR.HERE
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: <pod-label>
```
