### ISSUE TITLE
[Feature request] Customize container environment variables

### ISSUE THREAD

**Issue by akieling** [kubernetes-sigs/kustomize#2611]
I'd like to customize environment variables for a specific image container in `kustomization.yaml`. 

Currently, the only way to do that is generating a ConfigMap (using `configMapGenerator`) with the variable values and mapping them with `vars`. It works but could be a lot simpler. Example of current workaround below:

```
kind: Kustomization
...
configMapGenerator:
  - name: my-env-vars
    literals:
      - VAR1=value1
      - VAR2=value2
vars:
  - name: VAR1
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: my-env-vars
    fieldref:
        fieldpath: data.VAR1
  - name: VAR2
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: my-env-vars
    fieldref:
        fieldpath: data.VAR2
resources:
  - deployment.yaml
```

```
kind: Deployment
...
spec:
  template:
    spec:
      containers:
      - name: mypostgresdb
        image: postgres:8
        env:
          - name: VAR1
            value: $(VAR1)
          - name: VAR2
            value: $(VAR2)
```

**Comment by msk-** [comment]
I might misunderstand, but I think you want this:
`kustomization.yaml`:
```yaml
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: my-env-vars
    literals:
      - VAR1=value1
      - VAR2=value2
patches:
  # This patch will populate the environment of container mypostgresdb with configmap vars
  # one-by-one from the my-env-vars configmap
  - target:
      kind: Deployment
      name: dep
    patch: |-
      kind: Deployment
      metadata:
        name: required-but-ignored
      spec:
        template:
          spec:
            containers:
              - name: mypostgresdb
                env:
                  - valueFrom:
                      configMapKeyRef:
                        name: my-env-vars
                        key: VAR1
  # This patch will populate the environment of container mypostgresdb with all configmap vars from
  # the my-env-vars configmap
  - target:
      kind: Deployment
      name: dep
    patch: |-
      kind: Deployment
      metadata:
        name: required-but-ignored
      spec:
        template:
          spec:
            containers:
              - name: mypostgresdb
                envFrom:
                  configMapRef:
                    name: my-env-vars
```
`deployment.yaml`:
```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dep
spec:
  template:
    spec:
      containers:
      - name: mypostgresdb
        image: postgres:8
```

You will only need one of the patch examples I've given. Both will achieve the objective of getting `VAR1=value1` and `VAR2=value2` in your postgres container environment. Kustomize understands what constitutes an identifier for a given level in your manifest. What I mean is that when I say in a patch:
```yaml
containers:
  - name: mypostgresdb
    ...
```
Kustomize knows to apply the patch content to the container named `mypostgresdb`. So the idea of a patch is to _identify_ a resource, and apply some changes to it.

**Comment by akieling** [comment]
Thanks for the tip.

**Comment by angularsen** [comment]
@msk- In your last example, you patch environment variables for a named container. 

Is it possible to somehow patch _all_ containers? 

If I omit the container name, nothing is applied.
If I give the value `not-important`, then a new container is added.

My usecase is that I want to add these environment variables to all my containers:
```
          - env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

I don't believe I can achieve this via config maps either.

**Comment by msk-** [comment]
I can't see how you would do that. The patchMultipleObjects link suggests that you might be able to use only a wildcard `*` for the name, but I guess that like me, you found that didn't work. It looks like the wildcard doesn't work at all for matching containers.

One way you might be able to at least reduce some duplication is with the following:
 `kustomization.yaml`:
```
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: my-env-vars
    literals:
      - VAR1=value1
      - VAR2=value2
patches:
  # This patch will populate the environment of container mypostgresdb with configmap vars
  # one-by-one from the my-env-vars configmap
  - target:
      kind: Deployment
      name: dep
    patch: |-
      kind: Deployment
      metadata:
        name: required-but-ignored
      spec:
        template:
          spec:
            containers:
              - name: mypostgresdb
                env: &env
                  - valueFrom:
                      configMapKeyRef:
                        name: my-env-vars
                        key: VAR1
                  - valueFrom:
                      configMapKeyRef:
                        name: my-env-vars
                        key: VAR2
              - name: othercontainer
                env: *env
              - name: anothercontainer
                env: *env
              - name: myredis
                env: *env
  # This patch will populate the environment of container mypostgresdb with all configmap vars from
  # the my-env-vars configmap
  - target:
      kind: Deployment
      name: dep
    patch: |-
      kind: Deployment
      metadata:
        name: required-but-ignored
      spec:
        template:
          spec:
            containers:
              - name: mypostgresdb
                envFrom: &envFrom
                  configMapRef:
                    name: my-env-vars
              - name: othercontainer
                envFrom: *envFrom
              - name: anothercontainer
                envFrom: *envFrom
              - name: myredis
                envFrom: *envFrom
```
`deployment.yaml`:
```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dep
spec:
  template:
    spec:
      containers:
      - name: mypostgresdb
        image: postgres:8
      - name: othercontainer
        image: postgres:8
      - name: anothercontainer
        image: postgres:8
      - name: myredis
        image: redis:latest
```
Though it's a bit unsatisfying, it's better than having to maintain duplicates of that config.
