### ISSUE TITLE
Set image tag only

### ISSUE THREAD

**Issue by saleh199** [kubernetes-sigs/kustomize#2625]
Hello,

In my case I would only to change the image tag and keep `newName` value I need only to pass the `tag` and keep the `newName` as is.

Command `kustomize edit set image` does not support this

Example:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: api-image
    newTag: v3.0
    newName: image-path
bases:
  - ../base
```
