### ISSUE TITLE
Name change patch applied to incorrect roleRef target

### ISSUE THREAD

**Issue by akretschmar-IP** [kubernetes-sigs/kustomize#2640]
Applying a patch to a base with a Role and a ClusterRole that share a name.  The patch (among other things) changes the name of the cluster role to add a prefix.

Simplified example:
rbac.yaml: (note the Role and ClusterRole have the same name)
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  version: v1
  kind: Role
  name: my-role
subjects:
- kind: ServiceAccount
  name: default
```

kustomization.yaml:
```
namespace: foo
resources:
- rbac.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/name
      value: prefix_my-role
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: my-role
```

Expected output:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: foo
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefix_my-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-role
  version: v1
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prefix_my-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
```

Actual output:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: foo
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefix_my-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefix_my-role                         # <--- INCORRECT!
  version: v1
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prefix_my-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
```

Two things jumped out at me:

1. The `roleRef` in the ClusterRoleBinding is patched to `prefix_my-role`.  This is actually smarter behavior than I was expecting, and was something I was going to end up patching in separately anyway.  So it may very well be correct (and in any case isn't "wrong").  But, I suspect the logic that accomplishes this is related to...
2. The `roleRef` in the RoleBinding is patched to `prefix_my-role`. Assuming that (1) is correct behavior, *this* is still incorrect, as the patch has a target of `rbac.authorization.k8s.io|v1|**ClusterRole**|my-role`, and this `roleRef` is `rbac.authorization.k8s.io|v1|**Role**|my-role`.  Interestingly, the Role itself is unmodified, so perhaps something related to resolving roleRefs is only keying off of the name instead of the name+GVK?

From poking around in the code (which I'm not intimately familiar with) a little bit, I suspect the error isn't with the `PatchJson6902Transformer`, but rather with the `nameReferenceTransformer`.

The base that I'm patching is remotely-sourced; I was hoping to be able to reference directly using `git::`, but because of this behavior, I don't think I can accomplish the name prefixing I want without changing the base.  I can work around this by maintaining a local copy of the base instead and giving the Role and ClusterRole different names, but this still feels like a bug since Roles and ClusterRoles are different Kinds and thus should be able to safely have identical names.
