### ISSUE TITLE
$patch: delete - doesn't work for env valueFrom

### ISSUE THREAD

**Issue by cameronbraid** [kubernetes-sigs/kustomize#2644]
I wish to use a patchesStrategicMerge to convert an env from a valueFrom to a value

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
          - name: STRIMZI_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
...
```

patch.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
            - name: STRIMZI_NAMESPACE
              value: "*"
              valueFrom:
                $patch: delete

```

expected.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
          - name: STRIMZI_NAMESPACE
            value: "*"
...
```

actual.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
          - name: STRIMZI_NAMESPACE
            valueFrom: {}
            value: "*"
...
```

**Comment by cameronbraid** [comment]
Though  I would try something and it seems to work, is this how it is **meant** to be done ?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
spec:
  template:
    spec:
      containers:
        - name: strimzi-cluster-operator
          env:
            - name: STRIMZI_NAMESPACE
              $patch: delete
            - name: STRIMZI_NAMESPACE
              value: "*"
```
