### ISSUE TITLE
Function to change metadata/name

### ISSUE THREAD

**Issue by dunkelbunt1** [kubernetes-sigs/kustomize#2645]
Does anyone know a way/workaround to replace a single in resource (metadata/name) with Kustomize ?
I can not use name suffix or prefix, because that would change every name resource ..
 In my case I just want to have the metadata/name resource changed on a single place. If I do so via a patch Kusotimze fails to find a unique target. 
i.e. From (base file)
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
 labels:
  K8s-app:label
 name: foo
spec:
```
to (via patch)
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
 labels:
  K8s-app:label
 name: bar
spec:
```
A workaround would be not to patch it and apply  it as a full resource in the Kustomize file but that is what I am trying to avoid.

**Comment by dunkelbunt1** [comment]
This will replace metadata/name in a StatefulSet
```
patches:
- target:
    kind: StatefulSet
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: bar
```

**Comment by prakashkl88** [comment]
How do we patch both metadata fields as well as spec fields at the same time using kustomize
It either updates the spec or updates the metadata, based on the order of the patch in kustomization.yaml. Does not do both !! 


I tried something like this:

> ./overlay/test/kustomization.yaml

```
bases:
- ../../base
patches:
- target:
    kind: CustomRsrc
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: test123
- target:
    kind: SamplePersistenceService
    namespace: .*
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: test-namespace
patches:
- variant.yaml
```


> ./overlay/test/variant.yaml

```
kind: CustomRsrc
spec:
  storageClass: gold
metadata:
  name: base-name
  namespace: default
```
