### ISSUE TITLE
commonLabels and commonAnnotations defined in Base are not applied to the resources generated in overlays

### ISSUE THREAD

**Issue by RR90** [kubernetes-sigs/kustomize#2647]
To add common labels to all resources, I added commonLabels and commonAnnotations in base.

I realised that it was not applied  to the resources generated via the generators in my overlays directory, for example via  configMapGenerator and secretGenerator.

In order to propagate the labels and annotations defined in base to the generated secrets and configMap in overlays , I had to add generatorOptions on overlays level or to duplicate commonLabels and commonAnnotations previously defined  in base.

To avoid this duplication of code and especially  having to define the same labels and annotations in two places, maybe you can propagate the labels and annotations defined in base to all resources generated in the overlays?

Otherwise, can someone suggest me a more efficient solution to avoid this duplication?

I thank you in advance.

**Comment by Shell32-Natsu** [comment]
I don't get your point.

You probably have different values for `commonLabels` and `commonAnnotations` in different overlays. That's why we have overlays. If they are different, then there is no duplication. If these values are same, they should be put into base instead of overlays.

**Comment by Lepird** [comment]
@Shell32-Natsu I ran into the same issue and it is a generic issue and not just in the generators as mentions by @RR90 
moreover note that this behavior is also there with common annotations.

for reference check the below kustomization.yamls.

base:
```yaml
resources:
- resource1.yaml
commonLabels:
  app.kubernetes.io/name: my-app
```

production overlay:
```yaml
resources:
- ../../base
- resource2.yaml
commonLabels:
  app.kubernetes.io/instance: production
```

test overlay:
```yaml
resources:
- ../../base
- resource3.yaml
commonLabels:
  app.kubernetes.io/instance: test
```

the expectation here is that the label `app.kubernetes.io/name: app-name` should be propagated to all resources even ones added in the overlays since it was not overwritten in an overlay, but right now it is only added to resources in the base, so in the example above it is only written to `resource1.yaml`.
