### ISSUE TITLE
Support variables in ingress resources

### ISSUE THREAD

**Issue by pst** [kubernetes-sigs/kustomize#267]
To allow using the `minikube ip` command to get the current VMs IP in a development overlay it would be convenient to be able to use variables in ingress resources.

It seems the paths that would need to be supported are (probably incomplete):
```
{
    GroupVersionKind: &schema.GroupVersionKind{Kind: "Ingress"},
    Path:             []string{"spec", "rules"},
},

{
    GroupVersionKind: &schema.GroupVersionKind{Kind: "Ingress"},
    Path:             []string{"spec", "tls", "hosts"},
},
```

Example kustomize.yaml
```
secretGenerator:
- name: minikube
  commands:
    ip: "minikube ip"

vars:
  - name: MINIKUBE_IP
    objref:
      kind: Secret
      name: minikube
      apiVersion: v1
    fieldref:
      fieldpath: data.ip
```
Example ingress.yaml
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minikube-example
spec:
  tls:
    - hosts:
      - $(MINIKUBE_IP).xip.io
      - api.$(MINIKUBE_IP).xip.io
      - www.$(MINIKUBE_IP).xip.io
  rules:
  - host: api.$(MINIKUBE_IP).xip.io
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: 80
  - host: www.$(MINIKUBE_IP).xip.io
    http:
      paths:
      - backend:
          serviceName: www
          servicePort: 80

```

Adding the paths to the refVarTransformers path variables seems easy enough. However, the value from `fieldpath: data.ip` would also need to be base64 decoded. Using the `MINIKUBE_IP` variable in a container's env currently produces this:

```
env:
        - name: API_URL
          value: https://api.MTkyLjE2OC4zOS4xNTEK.xip.io
```

Is this use-case in scope for variables?
