### ISSUE TITLE
persistentvolume claime's volumeName have no namePrefix

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes-sigs/kustomize#268]
kustomize version: bb8233ceff643df64e1da8b2370f461c0880c25c
build from master

kustomization.yaml
```
resources:
  - pv-influxdb.yaml
  - pvc-influxdb.yaml

namePrefix: dev-
```

pvc-influxdb.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: influxdb
```

pv-influxdb.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data/influxdb
    server: 192.168.1.73
  persistentVolumeReclaimPolicy: Retain

```
run kustomize build, will see:
pvc:
```
volumeName: influxdb
```
pv
```
name: dev-influxdb
```

is this a bug or feature of kustomize?
3ks!!
