### ISSUE TITLE
Unknown fields are removed by "kustomize edit" instead of returning an error and terminating

### ISSUE THREAD

**Issue by maurizio-lattuada** [kubernetes-sigs/kustomize#2681]
Hi,

I'm using Kustomize v3.6.1 and I noticed a particular behavior using this `kustomization.yaml` file (please note that there is an unknown field called `vaultSecretsGenerator` there):
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: configmap-variables
    literals:
      - config=https
vaultSecretsGenerator:
  - name: am-env-secrets
    behavior: merge
    environment: devops/am
secretGenerator:
  - name: secret-variables
    type: kubernetes/tls
    literals:
      - SERVICE_LISTENING_PROTOCOL=https
```

Well, when executing `kustomize build .`, I got correctly an error:
```
Error: json: unknown field "vaultSecretsGenerator"
```

On the other hand, when executing e.g. `kustomize edit set image x=y`, the resulting `kustomization.yaml` file is:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- literals:
  - config=https
  name: configmap-variables
secretGenerator:
- literals:
  - SERVICE_LISTENING_PROTOCOL=https
  name: secret-variables
  type: kubernetes/tls
images:
- name: x
  newName: "y"
```

So
* `kustomize edit set xxxx` did not fail due to the unknown field `vaultSecretGenerator`
* the unknown field `vaultSecretGenerator` has now been removed from the `kustomization.yaml` file

Here I would have expected a different behavior:
* either fail fast: ok, maybe not necessary, at the end there is `kustomize build` kicking in and claiming about the unknown field
* or nevertheless not removing unknown fields from `kustomization.yaml` file

Does it make sense for you?

Thank you in advance,
Maurizio

(sorry if it is a duplicate, I tried to look for "unknown" or similar words, but found nothing related).
