### ISSUE TITLE
jsonpatch add when existing object is present doesn't throw an error

### ISSUE THREAD

**Issue by base698** [kubernetes-sigs/kustomize#2685]
Running `kustomize .` for `nginx.yaml`, `nginx-patch.yaml, and `kustomize.yaml` below results in:

**Current output:**

```
$ kubectl kustomize .
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    replacement: true
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: k8s.gcr.io/nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
```

**Expected output:** Error saying that `/metadata/annotations` is already present.  

kustomization.yaml:
```yaml
---
resources:
  - nginx.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx
  path: nginx-patch.yaml
```

nginx.yaml:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    patch: true
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx:1.7.9
        ports:
        - containerPort: 80
```

nginx-patch.yaml:
```yaml
---
- op: add
  path: "/metadata/annotations"
  value: {"replacement":true}
```
