### ISSUE TITLE
Cannot read multiple storage classes from single file

### ISSUE THREAD

**Issue by mick88** [kubernetes-sigs/kustomize#2687]
Example kustomize file:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
```

storage.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: psql-data
provisioner: docker.io/hostpath
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-storage
provisioner: docker.io/hostpath
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup-storage
provisioner: docker.io/hostpath
---
```

output from `kustomize build`
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: psql-data
provisioner: docker.io/hostpath
```

As you can see, kustomize picked up only the first storage class from the storage.yaml file.
Other yaml files with multiple resources read correctly. 

Version: {KustomizeVersion:2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-05T20:37:42Z GoOs:windows GoArch:amd64}
