### ISSUE TITLE
patchesJson6902 annotationSelector and labelSelector do not work

### ISSUE THREAD

**Issue by rocketraman** [kubernetes-sigs/kustomize#2689]
{Version:3.7.0 GitCommit:e5b0ceb4e37bec29c3be2e14017c199f7d9101a6 BuildDate:2020-07-02T21:26:02+00:00 GoOs:linux GoArch:amd64}

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- target:
    kind: Service
    version: v1
    name: ".*"
    labelSelector: foo=bar"
```

```
Error: json: unknown field "labelSelector"
```

Same for annotationSelector.
