### ISSUE TITLE
patchesJson6902 cannot select multiple resources

### ISSUE THREAD

**Issue by rocketraman** [kubernetes-sigs/kustomize#2690]
{Version:3.7.0 GitCommit:e5b0ceb4e37bec29c3be2e14017c199f7d9101a6 BuildDate:2020-07-02T21:26:02+00:00 GoOs:linux GoArch:amd64}

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- target:
    kind: Service
    version: v1
    name: ".*"
```

```
Error: no matches for OriginalId ~G_v1_Service|~X|.*; no matches for CurrentId ~G_v1_Service|~X|.*; failed to find unique target for patch ~G_v1_Service|.*
```

Removing the `name` field doesn't work either -- though the docs seem to indicate this should be possible, this results in the error:

```
Error: trouble configuring builtin PatchJson6902Transformer with config: `
jsonOp: ...
target:
  kind: Service
  name: ""
  version: v1
`: must specify the target name
```
