### ISSUE TITLE
Updating images

### ISSUE THREAD

**Issue by rasberrypie** [kubernetes-sigs/kustomize#2701]
I have multiple version of images in base deployment.yaml files
eg: 
In base 
 **deployment1.yaml** 
..spec:
      containers:
      - name: nginx
        image: nginx:latest
**deployment2.yaml** 
..spec:
      containers:
      - name: nginx2
        image: nginx:1.15.10

In overlay if i give 
images:
  - name: nginx
    newname: nginx
    newTag: "1.15.4"

all the deployment images with get updated with "1.15.4"
is there is a way i can update both the deployment with different version of nginx image? how to identify the image specific to a deployment in kustomization.yaml in overlay

**Comment by ephesused** [comment]
How about identifying the images in deployment1.yaml and deployment2.yaml with different names, and then override them both as needed?

deployment1.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flavor1
spec:
  template:
    spec:
      containers:
      - image: nginx-flavor1
```

deployment2.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flavor2
spec:
  template:
    spec:
      containers:
      - image: nginx-flavor2
```

kustomization.yaml

```yaml
resources:
- deployment1.yaml
- deployment2.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx-flavor1
  newName: nginx
  newTag: latest
- name: nginx-flavor2
  newName: nginx
  newTag: 1.15.4
```

kustomize build results

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flavor1
spec:
  template:
    spec:
      containers:
      - image: nginx:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flavor2
spec:
  template:
    spec:
      containers:
      - image: nginx:1.15.4
```
