### ISSUE TITLE
commonLabels is not applied to PodDisruptionBudget selector

### ISSUE THREAD

**Issue by rocketraman** [kubernetes-sigs/kustomize#2716]
Given a `PodDisruptionBudget` that looks like this (note there is no existing `selector`):

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: foo
spec:
  maxUnavailable: 1
```

and `kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: foo

resources:
- pdb.yaml
```

the output has no selector block:

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: foo
  name: foo
  namespace: default
spec:
  maxUnavailable: 1
```

However, if the input has an existing label, then the selector is updated correctly:

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      app: bar
  maxUnavailable: 1
```

then the output is correct -- note the selector has been updated to the value given in `commonLabels`:

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: foo
  name: foo
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: foo
```

Using kustomize 3.7.0:

```
kustomize version                                                                                                                                                           13:57:25
{Version:3.7.0 GitCommit:e5b0ceb4e37bec29c3be2e14017c199f7d9101a6 BuildDate:2020-07-02T21:26:02+00:00 GoOs:linux GoArch:amd64}
```

**Comment by DerTiedemann** [comment]
Heyyo,
I ran into this today and did some testing. I ran it both with kubectl and kustomize
This is my setup for this test:
**base/kustomization.yaml**
```yaml
resources: 
  - service.yaml

commonLabels:
  app: superawesomeapp
  type: backend
```

**base/service.yaml**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 443
      targetPort: 80
```
**overlays/production/kustomization.yaml**
```yaml
bases:
  - ../../base
resources:
  - pdb.yaml

commonLabels:
  env: production
```

**overlays/production/pdb.yaml**
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
spec:
  minAvailable: 1
```
kustomize version: `{Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}`
kubectl version: `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

The output for kustomize and kubectl is the same (`diff <(kubectl kustomize overlays/production) <(kustomize build overlays/production)`)
Output:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: superawesomeapp
    env: production
    type: backend
  name: backend-service
spec:
  ports:
  - port: 443
    targetPort: 80
  selector:
    app: superawesomeapp
    env: production
    type: backend
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    env: production
  name: backend-pdb
spec:
  minAvailable: 1
```

It seems the the labels from the overlay kustomization are not correctly merged as they are with the service.
But again when no previous labels are present then nothing is generated at all.
No idea why and how this occurs but I need this to work so if someone could point me in the right direction on where and how to fix this I will have a look at this to fix it.

**Comment by Shell32-Natsu** [comment]
`spec/selector/matchLabels` will not be created if it's not there. 

https://github.com/kubernetes-sigs/kustomize/blob/077c7b2d20bfdb0de78e6873a4ae1ce08afa1c40/api/konfig/builtinpluginconsts/commonlabels.go#L130-L133

@monopole Is there any specific reason that we don't create it?

**Comment by Shell32-Natsu** [comment]
@rocketraman @DerTiedemann Please see [this](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#labels-transformer) for how to customize the fields specs for commanLabels.

**Comment by so-jelly** [comment]
i'm not sure if anyone will read this but i have done this that i think is a bit cleaner and more explicit in my configurations

```yaml
replacements:
- source:
    kind: Deployment
    fieldPath: spec.selector
  targets:
  - select:
      kind: PodDisruptionBudget
    fieldPaths:
    - spec.selector
```

you can be a bit more prescriptive, selecting names and kinds more specifically.
