### ISSUE TITLE
namespace does not work with ClusterRoleBinding subjects when using PrefixSuffixTransformer plugin

### ISSUE THREAD

**Issue by r0bj** [kubernetes-sigs/kustomize#2717]
Namespace overriding does not work with ClusterRoleBinding subjects when using PrefixSuffixTransformer plugin.

Example
workloads.yaml:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
```

prefixSuffixTransformer.yaml:
```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: notImportantHere
suffix: -suffix
fieldSpecs:
- path: metadata/name
  kind: ClusterRoleBinding
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workloads.yaml
namespace: prod
transformers:
- prefixSuffixTransformer.yaml
```

Result:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp-suffix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp
```
Note: there is no `namespace: prod` in `ClusterRoleBinding` `subjects`.

After removing `transformers` section from `kustomization.yaml` output looks fine:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp
  namespace: prod
```

```
$ kustomize version
{Version:3.8.0 GitCommit:6a50372dd5686df22750b0c729adaf369fbf193c BuildDate:2020-07-05T17:55:53+01:00 GoOs:darwin GoArch:amd64}
```
