### ISSUE TITLE
Don't add commonLabels to service selector

### ISSUE THREAD

**Issue by kong62** [kubernetes-sigs/kustomize#2740]
```
commonLabels:
  app: base
  apptype: python3
  env: default
  version: v1
  datetime: 2020-06-03-21-12-50-975208
```

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: base
    apptype: python3
    datetime: 2020-06-03-21-12-50-975208
    env: default
    version: v1
  name: base
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: base
    apptype: python3
    datetime: 2020-06-03-21-12-50-975208
    env: default
    # I don't want add version to service, because  one service select two version pods managed by two deployments.
    version: v1
  sessionAffinity: None
  type: ClusterIP
```

I don't want add version to service, because  one service select two version pods managed by two deployments.
