### ISSUE TITLE
Use environment variable in command line

### ISSUE THREAD

**Issue by malcolm061990** [kubernetes-sigs/kustomize#2746]
Hi.
My version is:
```
kustomize version
{Version:3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T05:15:32+01:00 GoOs:darwin GoArch:amd64}
```

I have db.yaml file (it's not full, just for example):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:
      containers:
        - name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: $(MYSQL_SERVICE)
```
I have kustomization.yaml file:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db.yaml
```

What do I want?
I want to run something like that:
```
export MYSQL_SERVICE=db-master
kustomize build .
```
And I want to get the output:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: db-master
        name: wordpress
```

Right now the env variable from shell isn't applied to db.yaml.
Please, tell me how can I read the env variables directly from env to use them for kustomize.
