### ISSUE TITLE
Use SOPS for secret generation

### ISSUE THREAD

**Issue by lswith** [kubernetes-sigs/kustomize#277]
I currently use the tool https://github.com/mozilla/sops to store the secrets for the resource. This tool encrypts and decrypts a full yaml file.

It would be nice to use something like this in the kustomization.yaml:
```yaml
secretGenerator:
- name: test
  yamlCommand: sops -d secret.enc.yaml
```

This would supply the yaml for each and every key.
