### ISSUE TITLE
Generated resources don't have hash suffix appended if the manifests declare a namespace

### ISSUE THREAD

**Issue by LP0101** [kubernetes-sigs/kustomize#2781]
When using a resource created by a SecretGenerator (and probably by a configMapGenerator), they will not have the hash suffix appended if any manifests declare a namespace.

As an example:

With the following kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: bar
```

If you then write another manifest, and explicitly declare a namespace:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: foo
...
valueFrom:
                secretKeyRef:
                  name: bar
                  key: bar
```

The secret `bar` will not have the suffix applied to it, even when the kustomization is installed to the `foo` namespace.

However, if you modify the kustomization yaml and add in `namespace: foo`, the behaviour works as intended, and the hash suffixes are properly applied.

This behaviour feels inconsistent.
