### ISSUE TITLE
Patch Target Regex on Group Kind and Version Too

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kustomize#2782]
I recently came across a use case where the same patch could be used on a number of Kinds from a number of related groups. I could not simply make one patch though, I needed to repeat the same patch over and over for each time the group had a prefix and for all the different Kinds. 

In my case I'm using an operator called [Crossplane](https://crossplane.io/). This operator has quite a bit of custom resources and they all have `crossplane.io` as part of the API Group name. They all have a common field in the spec for choosing an AWS Account provider, among other commonalities.

For example:
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
spec:
  providerRef: 
    name: aws-dev
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
spec:
  providerRef: 
    name: aws-dev
```

I would like to patch in the `/spec/providerRef/name` on all of them in one single patch like below using a regex on the API Group Name.
```yaml
patches:
- patch:  |- 
    - op: add
      path: /spec/providerRef/name
      value: aws-dev
  target:
    group: *.aws.crossplane.io
```

Currently a regex expression may only be used on `name` and `namespace` fields on the patches target. 

With this limitation my workaround is to use yaml templating and repeat the patch a whole lot of times. [As you can see here](https://doc.crds.dev/github.com/crossplane/provider-aws), there are a lot of groups and kinds.
```yaml
patches:
- patch:  &patch |- 
    - op: add
      path: /spec/providerRef/name
      value: aws-dev
  target:
    group: ec2.aws.crossplane.io
- patch: *patch
  group: identity.aws.crossplane.io
```

Here is an example of when it would have been nice to have a regex on the Kind. 
```yaml
patches:
- patch: |- 
    - op: add
      path: /spec/forProvider/groupName
      value: administrators
  target:
    group: identity.aws.crossplane.io
    kind: (IAMGroupUserMembership|IAMGroupPolicyAttachment)
```

**Comment by afirth** [comment]
this is unbelievably useful for patching upstream code which targets more recent k8s than yours (particularly from helm3 template which dropped `--kubernetes-version` support. I am dropping this on these issues as google led me here.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
[...]
patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: rbac.authorization.k8s.io/v1beta1
  target:
    group: rbac.authorization.k8s.io
    version: v1
    labelSelector: "app.kubernetes.io/managed-by=Helm"
```
