### ISSUE TITLE
yaml anchors

### ISSUE THREAD

**Issue by tomplus** [kubernetes-sigs/kustomize#2785]
I try to avoid repeating some parts of yaml by using anchors, but it looks like it's supported only inside one K8s document.

Example:

```yaml
apiVersion: extensions/v1beta1
kind: Something
metadata:
  name: i1
spec: &my-spec
  rules:
  - host: "*.example.com"
test:
 *my-spec                                                << it works
---
apiVersion: extensions/v1beta1
kind: Something
metadata:
  name: i2
test:
 *my-spec                                               << my-spec not-defined?
```

It works without i2, but adding i2 ends with output:

Error: accumulating resources: accumulateFile "accumulating resources from '../../base/': read /k8s-manifests/base: is a directory", accumulateDirector: "recursed accumulation of path '/k8s-manifests/base': accumulating resources: accumulateFile \"accumulating resources from 'cloud/': read /k8s-manifests/base/cloud: is a directory\", accumulateDirector: \"recursed accumulation of path '/k8s-manifests/base/cloud': accumulating resources: accumulateFile \\\"accumulating resources from 'ingress.yaml': YAML file [ingress.yaml] encounters a format error.\\\\nerror converting YAML to JSON: yaml: unknown anchor 'my-spec' referenced\\\\n\\\", loader.New \\\"Error loading ingress.yaml with git: url lacks orgRepo: ingress.yaml, dir: got file 'ingress.yaml', but '/k8s-manifests/base/cloud/ingress.yaml' must be a directory to be a root, get: invalid source string: ingress.yaml\\\"\""

version:

{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}
