### ISSUE TITLE
kustomize `build` should work with kpt packages

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2837]
Currently the command
```
kustomize build $target
```
expects `$target` to be a path to a directory with a `kustomization.yaml` file. The notation also supports a github repo URL, in which case the repo is cloned to a local tmp dir, and the path part of the URL is followed in that clone to find an kustomization file.  A directory with a kustomization.yaml file is recognized as something that kustomize can read and `build`.

Further, the `resources` field in a `kustomization.yaml` file is a list of paths.

Each path can point to a simple KRM file, or it can refer to a `kustomization` using the same rules as described for `$target` (a directory, or a directory in a repo).  In the latter case, the kustomization is recursively built to create resources, which become input to the current kustomization.

The `resources` field should also accept a path to a _kpt package_, which is then honored as kpt would honor it, finding all the KRM files in it and feeding them into the kustomization.

**Comment by ricochet** [comment]
Is there a reverse issue for kpt? If I create a kpt package that points to a kustomization.yaml with resources with git go-getter URL's, the recursive strategy for resolving kustomization's is not employed.

What I expected: kpt app -> clones resources including kustomization -> resolve resources of kustomization -> recursive strategy for cloning -> resulting generated Kptfile for sample project includes upstream kustomization resources.

Application `Kptfile`
```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
    name: .
packageMetadata:
    shortDescription: sample description
dependencies:
  - name: sample
    git:
        repo: git@gitlab.com:sample/foo
        directory: /sample/k8s/foo
        ref: master
    updateStrategy: fast-forward
```

Above `Kptfile` points to "sample/foo" git repo with a `kustomization.yaml`:

```yaml
kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git@gitlab.com:sample/k8s-bases.git/bases/deployment/golang?ref=release-1.0
```

Generated `Kptfile`. I expected dependencies on upstream k8s-bases (which references a Deployment resource) to be pulled in. Instead it tops at the first level.

```yaml
apiVersion: kpt.dev/v1alpha1
kind: Kptfile
metadata:
    name: .
upstream:
    type: git
    git:
        commit: 9b56049a7521411ae15ef668857d1481bc5d0520
        repo: git@gitlab.sas.com:sample/foo
        directory: /sample/k8s/foo
        ref: master
packageMetadata:
    shortDescription: sample description
dependencies:
  - name: types
    git:
        repo: git@gitlab.sas.com:sample/foo
        directory: /sample/k8s/foo
        ref: master
    updateStrategy: fast-forward
```
