### ISSUE TITLE
How can I use images -> newTag as label?

### ISSUE THREAD

**Issue by kivio** [kubernetes-sigs/kustomize#2841]
It's possible to use images definitions newTag to be used as label for example for my deployment?

I'm aware that I can use variables for that - but it make it more complicated.

**Comment by Shell32-Natsu** [comment]
Could you provide an example of the kustomization file to explain what you want to do?

**Comment by neverexists** [comment]
Sorry for the intrusion but maybe i'm searching to do the same thing.

I would to add automatically a label to my pod with the version of my container tag .

> deployment.yaml
```
apiVersion: apps/v1
kind: Deployment  
metadata:  
  name: myapp-deployment
spec:  
  replicas: 2
  template:
    spec:
      containers:
        - name: myapp
          image: myrepo/myapp
          ports:  
            - containerPort: 8080
```
>kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: myapp

resources:
- deployment.yaml

images:
  - name: myrepo/myapp
    newTag: "0.0.2"
```
> kubectl kustomize .
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: myrepo/myapp:0.0.2
        name: myapp
        ports:
        - containerPort: 8080
```
I would like to get something like (see myappver label below):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        myappver: 0.0.2
    spec:
      containers:
      - image: myrepo/myapp:0.0.2
        name: myapp
        ports:
        - containerPort: 8080
```
Is it possible?
