### ISSUE TITLE
Kustomize with Elasticsearch types

### ISSUE THREAD

**Issue by tmyroadctfig** [kubernetes-sigs/kustomize#2843]
I'm trying to use `kustomize` with the Elasticsearch ECK types, e.g. `kind: Elasticsearch', but it doesn't seem to be matching that custom type:
```
kustomize build .
Error: no matches for OriginalId ~G_elasticsearch.k8s.elastic.co/v1_Elasticsearch|~X|tenant; no matches for CurrentId ~G_elasticsearch.k8s.elastic.co/v1_Elasticsearch|~X|tenant; failed to find unique target for patch ~G_elasticsearch.k8s.elastic.co/v1_Elasticsearch|tenant
```

Adjusting the `kustomize.yaml` to match `kind: Service` does work though. Are custom types like those supplied by ECK supported? I'm trying to replace the `placeholder-east1-a` values with a real region FWIW.

`kustomize.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- elasticsearch.yaml
patchesJson6902:
- target:
    version: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: tenant
  path: patch.yaml
```

`patch.yaml`:
```
- op: add
  path: /spec/test
  value: testing-123
```

`elasticsearch.yaml`:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: tenant
spec:
  version: 6.8.0
  nodeSets:
    - name: zone-a
      count: 1
      config:
        node.attr.zone: placeholder-east1-a
        cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
      podTemplate:
        spec:
          nodeSelector:
            nuixRole: elasticsearch
            tenant: placeholder
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - placeholder-east1-a
```

**Comment by alexander-knezevic-luetke-gcx** [comment]
changing your `kustomization.yaml` to
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elasticsearch.yaml
patchesJson6902:
  - target:
      version: v1
      group: elasticsearch.k8s.elastic.co
      kind: Elasticsearch
      name: tenant
    path: patch.yaml
```

works for me.
