### ISSUE TITLE
Inconsistency between API and CLI in the field `env` for SecretGenerator 

### ISSUE THREAD

**Issue by manute** [kubernetes-sigs/kustomize#2856]
Hi,

In the SecretGenerator's [docs](https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#secretgenerator) there's a field called `env` that apparently can be used for data entries. 

Although , running the kustomize build via CLI (v3.8.1) for this yaml produces this error -> ```Error: json: unknown field "env``` 
```yaml
resources:
- deployment.yaml
- service.yaml
- hpa.yaml

secretGenerator:
- name: env-api-secrets-platform-deployment
  env: envs.txt
  type: Opaque
```

And running it via golang API programatically : 
```golang	
       var kustomizeOutput bytes.Buffer
	if err := kustomize.RunKustomizeBuild(&kustomizeOutput, fs.MakeRealFS(), path); err != nil {
		return nil, errors.Wrapf(err, "failed to run kustomize build over path: %s", path)
	}
```
, it works fine with these versions  (go.mod) : 
```golang
	sigs.k8s.io/kustomize/api v0.5.1 // indirect
	sigs.k8s.io/kustomize/kyaml v0.7.0
```
