### ISSUE TITLE
ConfigMap and Secret Generators do not update CronJobs

### ISSUE THREAD

**Issue by xakraz** [kubernetes-sigs/kustomize#2865]
Hi there,

We are using `kustomize` to manage our deployments with `configMapGenerator` and external `generator` plugin for our secrets.
This works like a charm :smile: 

However, in one of our deployment, we have created `CronJob` and we have noticed that the `configMap` and `secret` references are not update like they are in the `deployment` ...

Any clues about this one ?
What should I provide to help debugging this ?

As `configMap` and `secret` names are updated, it will be pretty annoying to update manually their references in the `CronJob` definitions ...

Thanks !

**Comment by xakraz** [comment]
To add some code / context for the description:

### Master branch

Which is tagged when released


```
# deployment/base/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  ...
  template:
    ...
    spec:
      containers:
      - name: my-app
        ...
        volumeMounts:
        - name: config
          mountPath: /src/config/config.json
          subPath: config.json
        - name: secrets
          mountPath: /src/config/secrets.json
          subPath: secrets.json
      
      volumes:
      - name: config
        configMap:
          name: my-app
      - name: secrets
        secret:
          secretName: my-app
...
```

```
# deployment/base/cron-1.yaml
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-1
  labels:
    app: cron-1
spec:
  schedule: "*/6 * * * *"
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-1
              ...
              volumeMounts:
              - name: config
                mountPath: /src/config/config.json
                subPath: config.json
             - name: secrets
                mountPath: /src/config/secrets.json
                subPath: secrets.json
      
          volumes:
          - name: config
            configMap:
               name: my-app
          - name: secrets
            secret:
               secretName: my-app
```

As you can see, the volume specs are the same.

```
# deployment/base/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - cron-1.yaml
  ...
```


### Deployment branch
Branch name `deployment/env-1`

```
# deployment/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: env-1

# Base common
resources:
- github.com/xxxx/xxxx/deployment/base?ref=vX.Y.Z

...

# Config and Secrets
configMapGenerator:
- files:
  - config/config.json
  name: config
```

As expected there is a file `deployment/config/config.json`


### Kustomization result

```
$ kustomize build deployment > full.yaml
```

And the result

```
---
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: my-app
        ...
        volumeMounts:
        - name: config
          mountPath: /src/config/config.json
          subPath: config.json
        - name: secrets
          mountPath: /src/config/secrets.json
          subPath: secrets.json
      
      volumes:
      - name: config
        configMap:
          name: my-app-kfd76fgc5h            <---- yeah !!!
      - name: secrets
        secret:
          secretName: my-app-kdm27b9k2m  <---- yeah !!!

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-1
  labels:
    app: cron-1
spec:
  schedule: "*/6 * * * *"
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-1
              ...
              volumeMounts:
              - name: config
                mountPath: /src/config/config.json
                subPath: config.json
             - name: secrets
                mountPath: /src/config/secrets.json
                subPath: secrets.json
      
          volumes:
          - name: config
            configMap:
               name: my-app                   <--- Not updated
          - name: secrets
            secret:
               secretName: my-app        <--- Not updated
```

### Apply result

When applying the cronJobs creation failes because the `configMap` or `secret` with that name do not exists.
The ones existing are secret `my-app-kdm27b9k2m` and cm `my-app-kfd76fgc5h`


## Info

* We hit the bug with kustomize `v3.5.5`
* We have check and still an issue with the latest at that time: `v3.8.1`
