### ISSUE TITLE
With namespace set name of kind: Namespace should be augmented as well

### ISSUE THREAD

**Issue by elmariofredo** [kubernetes-sigs/kustomize#2867]
When `namespace` is set it will update all `namespace:` properties but skipping `name:` property of `kind: Namespace`  see example and expected result below.

## Setup example

```
cat <<'EOF' >kustomization.yaml
namespace: nginx-system
resources:
- manifests.yaml
EOF

cat <<'EOF' >manifests.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: init-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
EOF
```

## Current output

```
➜ kustomize build
apiVersion: v1
kind: Namespace
metadata:
  name: init-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: nginx-system
spec:
  containers:
  - image: nginx
    name: nginx
```

## Expected output

```
➜ kustomize build
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-system
---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  namespace: nginx-system
spec:
  containers:
  - image: nginx
    name: nginx
```

**Comment by elmariofredo** [comment]
Workaround:

```
namespace: nginx-system

resources:
- manifests.yaml

patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: init-demo
  patch: |-
    - op: replace
      path: "/metadata/name"
      value: nginx-system
```
