### ISSUE TITLE
Kustomize doesn't seem to look at a port's name when applying an overlay to a service

### ISSUE THREAD

**Issue by gaigepr** [kubernetes-sigs/kustomize#288]
```
The Service "my-service-1" is invalid: spec.ports[1].name: Duplicate value: "my-service-1-external"

script returned exit code 1
```

This error occurs when the overlay changes the port number of an existing entry in the list of ports of a service.

**Comment by Liujingfang1** [comment]
The problem is how to patch a service object properly. We use stategetic merge patch in Kustomize. So if you want to update a port, you need to write something like this
```
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    $patch: delete
  - name: http
    port: 90
```
 You can also take a look at a similar issue #173.
