### ISSUE TITLE
Support immutable attribute on configMapGenerator, secretGenerator

### ISSUE THREAD

**Issue by ijl** [kubernetes-sigs/kustomize#2895]
ConfigMap and Secret resources can have `immutable: true` set with the [ImmutableEphemeralVolumes](https://github.com/kubernetes/enhancements/issues/1412) feature and apparently reduce kube-apiserver load. This works well with kustomize appending a hash to the resource names.

It's not possible to generate resources with this attribute on kustomize v3.8.1. It seems like it could be added as a generator option:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: example
    literals:
      - KEY="val"
generatorOptions:
  immutable: true
```

Generating:

```yaml
apiVersion: v1
data:
  KEY: val
kind: ConfigMap
immutable: true
metadata:
  name: example-hash
```

I don't know if it would be appropriate to add support while the feature is unstable.
