### ISSUE TITLE
Kustomize Doesn't append nameSuffix from base when patch is applied to derived file in version 3.8.1

### ISSUE THREAD

**Issue by jg-26** [kubernetes-sigs/kustomize#2896]
Hi Here's an example: 
My base app under `./base/test-api/` directory has these two files:
deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
        - name: example
          image: example:1.0
          volumeMounts:
            - name: conf
              mountPath: /etc/config
      volumes:
        - name: conf
          configMap:
            name: conf
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -test-api

resources:
 - deployment.yaml
```

Here's how my derived app kustomization file looks like under `./overlays/derived`:
kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base/test-api


patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: example
      spec:
        template:
          spec:
            containers:
             - name: example
               image: example:2.0

```

When I try to run the command:
`kustomize build --load_restrictor none overlays/derived/`

I get this output:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:2.0
        name: example
        volumeMounts:
        - mountPath: /etc/config
          name: conf
      volumes:
      - configMap:
          name: conf
        name: conf
```

While if I use version 3.7.0; I get this output:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-test-api
spec:
  template:
    spec:
      containers:
      - image: example:2.0
        name: example
        volumeMounts:
        - mountPath: /etc/config
          name: conf
      volumes:
      - configMap:
          name: conf
        name: conf
```

As you can see from the above two output, the nameSuffix is not appended to the output in version 3.8.1 while it is being appended to version 3.7.0. Has anything changed from 3.7.0 to 3.8.1 to cause this bug or is it intended behavior?
