### ISSUE TITLE
error: couldn't find target networking.k8s.io_v1beta1_Ingress|magento|~P|main|~S for json patch

### ISSUE THREAD

**Issue by fahimghl** [kubernetes-sigs/kustomize#2897]
I am getting an error: couldn't find target networking.k8s.io_v1beta1_Ingress|magento|~P|main|~S for JSON patch when I run kubectl apply -k .

```
ingress.yaml patch file content:

    - op: replace
      path: /spec/backend/serviceName
      value: varnish
    - op: replace
      path: /spec/backend/servicePort
      value: 6091


```
my Kustomize file contains following:

```
    bases:
      - ../step-3
      - ../bases/varnish
    
    patchesJson6902:
    - target:
        group: networking.k8s.io
        version: v1beta1
        kind: Ingress
        name: main
        namespace: magento
      path: patch/ingress.yaml
    
    configMapGenerator:
    - name: aux
      behavior: merge
      env: config/aux.env
```

And my service and deployment files contains:

```
    apiVersion: v1
    kind: Service
    metadata:
      name: varnish
      labels:
        app: varnish
        k8s-app: magento
    spec:
      selector:
        app: varnish
      ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
      - name: proxy
        port: 6091
        protocol: TCP
        targetPort: 6091
    
    ---
    
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: varnish
      namespace: magento
    spec:
      selector:
        matchLabels:
          app: varnish
      replicas: 1
      template:
        metadata:
          labels:
            app: varnish
            k8s-app: magento
        spec:
          containers:
          - image: varnish:6.2
            name: varnish
            command: ["/bin/sh"]
            args:
              - -c
              - |
                varnishd -a :80 -a :6091 -f /etc/varnish/default.vcl -s default,512M;
                varnishncsa -F '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %{Varnish:handling}x'
            ports:
            - containerPort: 80
            - containerPort: 6091
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
            env:
            - name: VARNISH_BACKEND_HOST
              value: web
            - name: VARNISH_BACKEND_PORT
              value: "80"
            volumeMounts:
            - name: config
              mountPath: /etc/varnish/default.vcl
              subPath: default.vcl
          restartPolicy: Always
          volumes:
          - name: config
            configMap:
              name: varnish
```

I think it is something to do with **namespace** as when I run default namespace it working fine. I have tried adding namespaces in deployment, service, patch but result is still the same.
