### ISSUE TITLE
kustomize generator should accept a kpt function

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#2899]
I have the following kpt function config, which is to render a helm chart.
```
# fn-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-func-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/helm-template
data:
  name: redis
  chart_path: /source
  --namespace: staging
```

Kustomize generator should accept it and generates the resources from the helm chart.

```
generators:
- fn-config.yaml
```
Currently it encounters the following error.
```
Error: loading generator plugins: plugin .../.config/kustomize/plugin/v1/configmap/ConfigMap fails to load: plugin.Open(".../.config/kustomize/plugin/v1/configmap/ConfigMap.so"): realpath failed
```

**Comment by Liujingfang1** [comment]
cc @monopole @Shell32-Natsu

**Comment by Shell32-Natsu** [comment]
Which version of kustomize are you using? The function support in kustomize should be there after 3.7.0

**Comment by Liujingfang1** [comment]
I used a previous version. Let me try with 3.7.0.

**Comment by Liujingfang1** [comment]
Cool! This works with the nignx generators.

```
# fn-config.yaml
kind: Nginx
metadata:
  name: demo
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kustomize-functions/example-nginx:v0.2.0
spec:
  replicas: 4
```

```
# kustomization.yaml

generators:
- nignx.yaml
```
