### ISSUE TITLE
Secret reference does not work on the ReplicationController

### ISSUE THREAD

**Issue by qwzhou89** [kubernetes-sigs/kustomize#2914]
When i use env data generated by secretGenerator,it's name not mached the secretGenerator generated name。
### Test setup
kustomization.yaml
```yaml
resources:
- mysql-server-replicationcontroller.yaml
secretGenerator:
- name: db-secret
  env: env.txt
  type: Opaque
```
env.txt
```yaml
db-root-pass=root
db-zbx-user=zabbix
db-zbx-pass=123456
```
mysql-server-replicationcontroller.yaml
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
    spec:
      volumes:
      - name: zabbix-mysql-data
        persistentVolumeClaim:
          claimName: zabbix-mysql-data-claim
      containers:
        - name: zabbix-db
          image: mysql:5.7
          ports:
          - containerPort: 3306
            name: mysql
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
            - mountPath: "/var/lib/mysql/"
              name: zabbix-mysql-data
              readOnly: false
```
kustomize build .  > out.yaml
```yaml
apiVersion: v1
data:
  db-root-pass: cm9vdA==
  db-zbx-pass: MTIzNDU2
  db-zbx-user: emFiYml4
kind: Secret
metadata:
  name: db-secret-67k28k8dkm
type: Opaque
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: db-zbx-user
              name: db-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-zbx-pass
              name: db-secret
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-root-pass
              name: db-secret
        - name: MYSQL_DATABASE
          value: zabbix
        image: mysql:5.7
        name: zabbix-db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql/
          name: zabbix-mysql-data
          readOnly: false
      volumes:
      - name: zabbix-mysql-data
        persistentVolumeClaim:
          claimName: zabbix-mysql-data-claim

```
expected: "name: db-secret" → "name: db-secret-67k28k8dkm"

**Comment by secret104278** [comment]
You can use `nameReference` to fix this issue

kustomization.yaml
```yaml
resources:
- mysql-server-replicationcontroller.yaml
secretGenerator:
- name: db-secret
  env: env.txt
  type: Opaque

configurations:
- my_configuration.yaml
```

my_configuration.yaml
```yaml
nameReference:
# Configure named references to Secret objects to be updated by Transformers and Generators - e.g. namePrefix, secretGenerator, etc
- kind: Secret
  version: v1
  fieldSpecs:
  # v1. ReplicationController that reference a Secret in spec.containers.env.valueFrom.secretKeyRef.name will have it updated
  - path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
    version: v1
    kind: ReplicationController
```

BTW, A Deployment that configures a ReplicaSet is now the recommended way to set up replication.
