### ISSUE TITLE
Docker registry example `The Secret "image-pull-secret-dd4m867ffm" is invalid: data[.dockerconfigjson]: Required value`

### ISSUE THREAD

**Issue by hadrien-toma** [kubernetes-sigs/kustomize#2925]
## Description

The secret generation of the `.docker/config.json` failed in the minimal following attempt to create a Docker registry.

## Context

- `tree .`
```
.
├── base
│   ├── deployment.yml
│   ├── kustomization.yml
│   └── service.yml
└── overlays
    └── dev
        ├── index.bash
        └── tmp
```

- `cat ./base/deployment.yml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: docker-registry
              mountPath: /auth
              readOnly: true
          resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: docker-registry
          secret:
            secretName: docker-registry
            items:
              - key: AUTH_HTPASSWD
                path: htpasswd
```

- `cat ./base/kustomization.yml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - deployment.yml
```

- `cat ./base/service.yml`
```
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: docker-registry
  type: ClusterIP
```

- `cat ./overlays/dev/index.bash`
```
#!/usr/bin/env bash

hereDir=$(dirname "${0}" | while read -r a; do cd "${a}" && pwd && break; done )

login="login"
password="password"
email="login@yopmail.com"

authHtpasswd=$(docker run --entrypoint htpasswd --rm registry:2 -Bbn ${login} ${password})

namespace=$(date +%s)

mkdir --parents ${hereDir}/tmp/.docker
cat <<EOF > ${hereDir}/tmp/.docker/config.json
{
	"auths": {
		"http://docker-registry/v2/": {
			"username": "${login}",
			"password": "${password}",
			"email": "${email}"
		}
	}
}

cat <<EOF > ${hereDir}/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: "${namespace}"

secretGenerator:
  - name: docker-registry
    behavior: create
    literals:
      - AUTH_HTPASSWD=${authHtpasswd}
  - name: image-pull-secret
    files:
      - tmp/.docker/config.json
    type: kubernetes.io/dockerconfigjson
EOF

kubectl kustomize ${hereDir}/
```

## Logs

```
secret/docker-registry-ctc69fkt96 created
service/docker-registry created
deployment.apps/docker-registry created
The Secret "image-pull-secret-dd4m867ffm" is invalid: data[.dockerconfigjson]: Required value
```

## Question

Does anyone know what can I do to solve this issue?

## Context

- `kubectl version ; k3d version`
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
k3d version v3.0.1
k3s version v1.18.6-k3s1 (default)
```

## Related issues

- #1420
