### ISSUE TITLE
Combining multiple overlays of the same base with different prefixes breaks name reference

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#293]
I have a base Kustomization for an application. I have several overlays based on it with different name prefixes. I then combine those into another Kustomization.

Name references are not resolved properly when multiple prefixes are in play. Sometimes, a name reference will point to the name from its sibling Kustomization.

The repo https://github.com/mxey/kustomize-nameprefix-reproduction contains the files to reproduce this.

output of `kustomize build combined`:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: b-serviceaccount
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: a-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: a-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
- kind: ServiceAccount
  name: b-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: b-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
- kind: ServiceAccount
  name: b-serviceaccount
```

As you can see, the `a-rolebinding` has the `b-serviceaccount` as its subject. 

This does not happen for every run, I assume it is basically random which resource is selected depending on the hashing for Go maps.
