### ISSUE TITLE
Kustomize 3.8.2 fails to set image in some list resources

### ISSUE THREAD

**Issue by gordalina** [kubernetes-sigs/kustomize#2937]
This issue affects only kustomize 3.8.2 and to my testing only cronjobs inside of a list resource, see how to reproduce below:

```yaml
# kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - list.yaml
images:
  - name: hello
    newName: gcr.io/cloudrun/hello
```

```yaml
# list.yaml

apiVersion: v1
kind: List
items:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: hello-cronjob
    spec:
      schedule: "* * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: hello
                  image: hello
  - apiVersion: batch/v1beta1
    kind: Deployment
    metadata:
      name: hello-deployment
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: hello
              image: hello
```

When building with 3.8.2 it does not replace the image in the cronjob, but does so in the deployment:

```yaml
$ kustomize version && kustomize build .
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-09-02T07:10:16+01:00 GoOs:darwin GoArch:amd64}

apiVersion: batch/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: gcr.io/cloudrun/hello
        name: hello
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: hello
            name: hello
  schedule: '* * * * *'
```

Whereas with 3.8.1 it correctly sets the image:

```yaml
$ kustomize-3.8.1 version && kustomize-3.8.1 build .
{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:darwin GoArch:amd64}

apiVersion: batch/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: gcr.io/cloudrun/hello
        name: hello
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: gcr.io/cloudrun/hello
            name: hello
  schedule: '* * * * *'
```
