### ISSUE TITLE
$patch: delete on an object results: Error: Object 'Kind' is missing in '{}'

### ISSUE THREAD

**Issue by r0bj** [kubernetes-sigs/kustomize#2945]
`$patch: delete` on an object results:
```
Error: Object 'Kind' is missing in '{}'
```

Example
workloads.yaml:
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp1
  name: myapp1
spec:
  ports:
  - port: 80
  selector:
    app: myapp1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp2
  name: myapp2
spec:
  ports:
  - port: 80
  selector:
    app: myapp2
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workloads.yaml
patches:
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: myapp1
    $patch: delete
  target:
    kind: Service
    name: myapp1
```

Execution:
```
$ kustomize build
Error: Object 'Kind' is missing in '{}'
```

It should work according to https://github.com/kubernetes-sigs/kustomize/issues/1384#issuecomment-514775221
