### ISSUE TITLE
Allow "kustomize cfg set" to set multi-line string values (setter type required)

### ISSUE THREAD

**Issue by seh** [kubernetes-sigs/kustomize#2947]
For a setter of type "string", I'd like to be able to set the value to a multi-line string, and have the resulting value be substituted in various places (into fields and into substitutions that reference the setter). Using _kustomize cfg set_, though, it's either impossible or difficult to set such a value.

Some things I've tried:
- Supply a string with newline characters
```shell
% kustomize cfg set . setter-name --values "abc
def
123"
set 0 fields
Error: yaml: line 3: could not find expected ':'
```
- Supply a double-quoted string with escaped newline characters
```shell
% kustomize cfg set . setter-name --values '"abc\ndef\n123"'
set 1 fields
```
The intention there is to force _kustomize_ to include the double quotation marks, so that the `\n` sequence constitutes a newline character in YAML.
- Supply a string with newline escape sequence
```shell
% kustomize cfg set . setter-name --values 'abc\ndef\n123'
set 1 fields
```
Here, since _kustomize_ doesn't surround the value written into the _Krmfile_ in double quotes, the `\n` sequence isn't respected by a YAML parser.

The goal is to use this setter's value in a `configMapGenerator`'s `literals` field entry. I've worked around the problem by using a file to convey the value instead of a literal, but it seems like this should be possible to accomplish. If it is already possible and I'm invoking _kustomize cfg set_ incorrectly, some documentation on the matter would help.

_kustomize version_ reports:
`{Version:3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-08-29T19:15:49+01:00 GoOs:darwin GoArch:amd64}`

**Comment by seh** [comment]
There's [some follow-on discussion of this problem in the "kustomize" channel](https://kubernetes.slack.com/archives/C9A5ALABG/p1599312833041500?thread_ts=1599262605.038200&cid=C9A5ALABG) in the "Kubernetes" Slack team.

**Comment by seh** [comment]
It seems that if the setter name contains hyphens, _kustomize cfg set_ does not work. Substituting underscores for hyphens in the setter name—in particular, in the definition mapping key—allows it to work.

**Comment by seh** [comment]
More findings: The hyphens in the setter definition key and display name don't cause any problems when a substitution doesn't refer to the setter. Commenting out a substitution referring to this setter allows _kustomize cfg set_ to set the setter's value as expected.

**Comment by seh** [comment]
Yet more findings: If I never refer to the setter or a substitution that refers to the setter from any other files, avoiding using the set value in interpolated field values, then all of these _kustomize cfg set_ invocations work correctly, in the sense that they capture the multiline value and write it into the _Krmfile_ file's "values" field in the following format:
```yaml
values: "abc\ndef\n123"
```
That's what I expect to make it into the _Krmfile_ file.

However, I can't *use* that value anywhere else successfully. Inserting references of the form `# {"$openapi":"setter-name"}` near field values in other YAML files (used as resources) causes _kustomize cfg set_ to fail.

**Comment by seh** [comment]
As far as I can tell, the way to get all of this to work is to declare explicitly that a setter has type "string".

Here's a working example:
```yaml
apiVersion: config.k8s.io/v1alpha1
kind: Krmfile
openAPI:
  definitions:
    io.k8s.cli.setters.image-names:
      type: string  # NB: Removing this line causes "kustomize cfg set" to fail.
      x-k8s-cli:
        setter:
          name: image-names
          description: 'Container image names to pull, listed one per line.'
          required: true
    io.k8s.cli.substitutions.image-names-spec:
      x-k8s-cli:
        substitution:
          name: image-names-spec
          pattern: image-names='${image-names}'
          values:
          - marker: ${image-names}
            ref: '#/definitions/io.k8s.cli.setters.image-names'
```
In [the `yaml.FormatNonStringStyle` function](https://github.com/kubernetes-sigs/kustomize/blob/678ae12115346f72c03929e241adfaf6d24354fe/kyaml/yaml/compatibility.go#L23-L52)—called on by _kustomize cfg set_—we see that if the schema for the setter is "string" and the format is not "int-or-string", we use the double-quoted style. I'm not sure what sets `node.Style` ahead of time to catch [these guard conditions](https://github.com/kubernetes-sigs/kustomize/blob/678ae12115346f72c03929e241adfaf6d24354fe/kyaml/yaml/compatibility.go#L36).

I had figured that the default setter type would be "string". Apparently either it's not, or specifying that type explicitly still yields behavior different from accepting a default type.
