### ISSUE TITLE
unknown field "$setElementOrder/containers" & "$setElementOrder/env"

### ISSUE THREAD

**Issue by strangeminds** [kubernetes-sigs/kustomize#2954]
After upgrading to kustomize v3.8.2 we are now getting an odd error when trying to deploy to our cluster using kustomize.

```
kustomize build --load_restrictor none kubernetes/kustomize/testapp/ | kubectl apply -f -;
error: error validating "STDIN": error validating data: [ValidationError(Deployment.spec.template.spec): unknown field "$setElementOrder/containers" in io.k8s.api.core.v1.PodSpec, ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "$setElementOrder/env" in io.k8s.api.core.v1.Container]; if you choose to ignore these errors, turn validation off with --validate=false
```

```
kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-09-02T07:01:55+01:00 GoOs:darwin GoArch:amd64}
kubectl version --short
Client Version: v1.19.0
Server Version: v1.16.14
```

When I downgrade to kustomize v3.5.4 I'm able to deploy without any issues.

This is what our deployment.yaml file looks like.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: testing
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - $setElementOrder/env:
        - name: ES_URL
        - name: RAILS_ENV
        - name: RAILS_MAX_THREADS
        - name: WEB_CONCURRENCY
        - name: POSTGRES_POOL
        - name: RAILS_SERVE_STATIC_FILES
        - name: RAILS_MASTER_KEY
        image: XXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/myimage:testing-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        name: app
``` 

My first thought is that `$setElementOrder` was removed in the "Deployment.spec.template.spec" but I'm not able to find anything in the kubernetes-api docs.

**Comment by Shell32-Natsu** [comment]
Can you provide your kustomizaztion.yaml file? And also the output of your kustomize command.

**Comment by strangeminds** [comment]
Running `kustomize build --load_restrictor none kubernetes/kustomize/testapp/ > kustomize3.5.4.yaml` in both versions I can see what the changes are using diff.  The older kustomize v3.5.4 strips out "$setElementOrder/containers" & "$setElementOrder/env" and the newest version keeps them in.  Here is a diff of the outputs from both versions.

```
--- kustomize3.5.4.yaml	2020-09-10 10:09:06.000000000 -0400
+++ kustomize3.8.2.yaml	2020-09-10 10:09:09.000000000 -0400
@@ -107,6 +107,8 @@
         env: staging
         track: stable
     spec:
+      $setElementOrder/containers:
+      - name: app
       affinity:
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
@@ -120,7 +122,15 @@
             weight: 100
       automountServiceAccountToken: false
       containers:
-      - args:
+      - $setElementOrder/env:
+        - name: ES_URL
+        - name: RAILS_ENV
+        - name: RAILS_MAX_THREADS
+        - name: WEB_CONCURRENCY
+        - name: POSTGRES_POOL
+        - name: RAILS_SERVE_STATIC_FILES
+        - name: RAILS_MASTER_KEY
+        args:
         - bin/puma
         - --control-url
         - tcp://127.0.0.1:9293
```

This is my kustomizaztion.yaml file

```
commonLabels:
  env: staging
bases:
- ../base
namespace: testing
patchesStrategicMerge:
- flux.yml
- db.yml
vars:
- name: RAILS_ENV
  objref:
    kind: Deployment
    name: app
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.labels.env
```

Here is the output from `kustomize build --load_restrictor none kubernetes/kustomize/testapp/` using kustomize v3.8.2.

```
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app: testing
    env: staging
  name: no-service-account
  namespace: testing
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testing
    component: application
    env: staging
    track: stable
  name: app
  namespace: testing
spec:
  ports:
  - name: rails
    port: 3000
    targetPort: rails
  selector:
    app: testing
    component: application
    env: staging
    track: stable
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testing
    component: database
    env: staging
    track: stable
  name: db
  namespace: testing
spec:
  externalName: db
  ports:
  - port: 5432
  selector:
    app: testing
    env: staging
  type: ExternalName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/locked: "false"
    flux.weave.works/tag.app: glob:staging-*
  labels:
    app: testing
    component: application
    env: staging
    track: stable
  name: app
  namespace: testing
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app
      component: application
      env: staging
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testing
        component: application
        env: staging
        track: stable
    spec:
      $setElementOrder/containers:
      - name: app
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: testing
                  component: application
                  env: staging
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - $setElementOrder/env:
        - name: ES_URL
        - name: RAILS_ENV
        - name: RAILS_MAX_THREADS
        - name: WEB_CONCURRENCY
        - name: POSTGRES_POOL
        - name: RAILS_SERVE_STATIC_FILES
        - name: RAILS_MASTER_KEY
        args:
        - bin/puma
        - --control-url
        - tcp://127.0.0.1:9293
        - --control-token
        - abc999
        command:
        - ./docker/docker-entrypoint.sh
        env:
        - name: RAILS_ENV
          value: staging
        - name: RAILS_MAX_THREADS
          value: "5"
        - name: WEB_CONCURRENCY
          value: "3"
        - name: POSTGRES_POOL
          value: "6"
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: master.key
              name: rails-master-key
        image: XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/testing:staging-v1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /
            port: rails
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 30
        name: app
        ports:
        - containerPort: 3000
          name: rails
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: rails
          periodSeconds: 30
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 1000m
            memory: 3Gi
          requests:
            cpu: 300m
            memory: 750Mi
        terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      serviceAccountName: no-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/ignore: "true"
  labels:
    app: testing
    component: webserver
    env: staging
    track: stable
  name: nginx
  namespace: testing
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: testing
      component: webserver
      env: staging
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testing
        component: webserver
        env: staging
        track: stable
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: testing
                  component: webserver
                  env: staging
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - image: XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/nginx:1.19
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5 && /usr/sbin/nginx -s quit
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /
            port: http-port
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 30
        name: nginx
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 443
          name: ssl-port
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: http-port
            scheme: HTTP
          periodSeconds: 30
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 25m
            memory: 256Mi
        terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      serviceAccountName: no-service-account
      terminationGracePeriodSeconds: 90
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: testing
    env: staging
  name: application-pdb
  namespace: testing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: testing
      component: application
      env: staging
      track: stable
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: testing
    env: staging
  name: nginx-pdb
  namespace: testing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: testing
      component: webserver
      env: staging
      track: stable
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: testing
    env: staging
  name: app-vpa
  namespace: testing
spec:
  targetRef:
    kind: Deployment
    name: app
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: testing
    env: staging
  name: nginx-vpa
  namespace: testing
spec:
  targetRef:
    kind: Deployment
    name: nginx
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: testing
    env: staging
  name: application
  namespace: testing
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 90
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: testing
    env: staging
  name: nginx
  namespace: testing
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
```
