### ISSUE TITLE
Image replacement broken for CronJobs in 3.8.2

### ISSUE THREAD

**Issue by JohnPaton** [kubernetes-sigs/kustomize#2961]
I just upgraded my kustomize to 3.8.2 and have encountered a nasty surprise: the changes in the `images` array of `kustomization.yaml` are no longer being applied to my CronJobs. This will cause all sorts of failures in our pipelines if the version in our CI/CD system gets bumped.

Minimal example:

```yaml
# base.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job-runner
              image: python:3.7
              imagePullPolicy: Always
              command:
                - -c
                - "print('hello')"
```

```yaml
# kustomization.yaml
resources:
  - base.yaml
images:
  - name: python
    newName: another-image
    newTag: another-tag

```
And the output
```console
$ kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-09-02T07:10:16+01:00 GoOs:darwin GoArch:amd64}
$ ls
base.yaml          kustomization.yaml
$ kustomize build .
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - -c
            - print('hello')
            image: python:3.7
            imagePullPolicy: Always
            name: job-runner
  schedule: '* * * * *'
```
As you see, the container's `image` is still `python:3.7`, neither the `newName` nor the `newTag` has been applied. Previously (last active version I had was 3.5.2), this would have output 
```console
            image: another-image:another-image
```
for the container.

I've tried all sorts of different combinations of including/excluding tags, spacing, punctuation, casing, but nothing seems to work, the `image` is never changed. We have many `CronJobs` that all have a shared `resource` as a base, this was one of the main draws for Kustomize for us, but this is really killing the key piece of functionality we are using.
