### ISSUE TITLE
How can I do a patch / merge on a ConfigMap with configMapGenerator with a yaml file as the source?

### ISSUE THREAD

**Issue by davisford** [kubernetes-sigs/kustomize#2962]
kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

I'm at a loss here, and maybe I'm missing something, but I'm trying all the different patch strategies, and I have yet to make this work.  Here's my example project:

`/base/kustomization.yaml`

```yaml
commonLabels:
  app: hello
configMapGenerator:
  - name: my-config
    behavior: create
    files: 
      - my-config.yaml
```

`/base/my-config.yaml`

```yaml
foo: bar
bar:
  - baz
  - qux
```

`/overlays/staging/kustomization`

```yaml
namePrefix: staging-
bases:
- ../../base/
configMapGenerator:
  - name: my-config
    behavior: merge
    files:
      - my-config.yaml
```

`/overlays/staging/my-config.yaml`

```yaml
newField: "i should be added"
foo: "i should be replaced"
```

`kc kustomize overlays/staging` generates this output (note that we've just completely replaced the original configMap from base and lost the fields that were there)

```
apiVersion: v1
data:
  my-config.yaml: |-
    newField: "i should be added"
    foo: "i should be replaced"
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: hello
  name: staging-my-config-ckhmcmbftd
```

So, then I try `patchesStrategicMerge` like so:

`/overlays/staging/kustomization`

```yaml
namePrefix: staging-
bases:
- ../../base/
patchesStrategicMerge:
- update-configmap.yaml
```

`/overlays/staging/update-configmap.yaml`

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  newField: "i should be added"
  foo: "i should be replaced"
```

`kc kustomize overlays/staging` generates this output (still not right we added the fields at the top-level, not in `my-config.yaml` literal):

```yaml
apiVersion: v1
data:
  foo: i should be replaced
  my-config.yaml: |-
    foo: bar
    bar:
      - baz
      - qux
  newField: i should be added
kind: ConfigMap
metadata:
  labels:
    app: hello
  name: staging-my-config-7gfdt27bc8
```

So, I try to change `overlays/staging/update-configmap.yaml` to the following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  my-config.yaml: |-
    newField: "i should be added"
    foo: "i should be replaced"
```

`kc kustomize overlays/staging` now generates (now it is a complete replacement, not a merge).

```yaml
apiVersion: v1
data:
  my-config.yaml: |-
    newField: "i should be added"
    foo: "i should be replaced"
kind: ConfigMap
metadata:
  labels:
    app: hello
  name: staging-my-config-ckhmcmbftd
```

So, now I try `patchesJson6902`....

`/overlays/staging/kustomization`

```yaml
namePrefix: staging-
bases:
- ../../base/
patchesJson6902:
  - path: patch.yaml
    target: 
      version: v1
      kind: ConfigMap
      name: my-config
```

`/overlays/staging/patch.yaml`

```yaml
- op: add
  path: /data/newField
  value: "I should be added"
- op: replace
  path: /data/foo
  value: "I should be replaced"
```

`kc kustomize /overlays/staging` generates the following (still not right, fields are merged at top level)

```yaml
apiVersion: v1
data:
  foo: I should be replaced
  my-config.yaml: |-
    foo: bar
    bar:
      - baz
      - qux
  newField: I should be added
kind: ConfigMap
metadata:
  labels:
    app: hello
  name: staging-my-config-8tmgkmbgbh
```

So, I try to modify the `path` in the `patch.yaml`....

`/overlays/staging/patch.yaml`

```yaml
- op: add
  path: /data/my-config.yaml/newField
  value: "I should be added"
- op: replace
  path: /data/my-config.yaml/foo
  value: "I should be replaced"
```

This generates an error.

```
Error: failed to apply json patch '- op: add
  path: /data/my-config.yaml/newField
  value: "I should be added"
- op: replace
  path: /data/my-config.yaml/foo
  value: "I should be replaced"': add operation does not apply: doc is missing path: "/data/my-config.yaml/newField": missing value
```

How can I achieve what I'm trying to do?  I get that the configMapGenerator creates a literal with the filename as the `data` value, and then its just a string, I guess.  Is there no way to do this?  It works with `.properties` files (as shown in your examples) and also works with literals.  Why can't it work with yaml from a file?
