### ISSUE TITLE
patchesStrategicMerge doesn't merge env properly 

### ISSUE THREAD

**Issue by kahou82** [kubernetes-sigs/kustomize#2966]
I have a base manifest that has a env variable relies on fieldPath:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          imagePullPolicy: IfNotPresent
          image: kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-svc:2181

```
I need to deploy this on another envirnoment that status.hostIP will not work (for example docker for mac). When I apply an overlay:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  template:
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 192.168.86.35

```

I see a duplicate value from the output:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.86.35
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-svc:2181
        image: kafka:latest
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
```

Looks like I cannot overlay the value and valueFrom. Is there another way I can do it?

**Comment by icy** [comment]
> Looks like I cannot overlay the value and valueFrom. Is there another way I can do it?

You may want to use patchJson to delete some field from the base. In your kustomization

```
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: kafka
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/env/0/valueFrom
```
