### ISSUE TITLE
"$patch: replace" doesn't work for entire lists

### ISSUE THREAD

**Issue by osela** [kubernetes-sigs/kustomize#2980]
In version 3.6.1 it was possible to replace an entire list by adding the following item to the list in a strategic merge patch:
```
- $patch: replace
```
as describe [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#list-of-maps).

It seems it's not possible any more with both 3.8.2 and 3.8.1 (didn't try older versions). The directive is ignored and list items are merged.

Is it an intentional change? I couldn't find anything in the docs or release notes.

```
deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: test
```
```
kustomization.yaml

resources:
- deploy.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test
  spec:
    template:
      spec:
        containers:
        - $patch: replace
        - name: replaced
          image: replaced
```
```
result with 3.8.2

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - image: test
        name: test
      - image: replaced
        name: replaced
```
```
result with 3.6.1

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - image: replaced
        name: replaced
```
