### ISSUE TITLE
Starting with 00f0fd71, performance degradation for strategic patch merges

### ISSUE THREAD

**Issue by ephesused** [kubernetes-sigs/kustomize#2987]
The run time for strategic patch merges in 00f0fd71 is roughly five times the run time for 1c6481d0 (the commit immediately before 00f0fd71).

Apologies for the lack of a test case PR.

### Test setup

kustomization.yaml

```yaml
resources:
  - resources.yaml

patchesStrategicMerge:
  - merge.yaml
```

resources.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: this-is-my-container
        image: this-is-my-image
```

merge.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        anno1: value1
```

### Equivalent output

The `kustomize build` output agrees between builds of the two commits:

```
$ diff <(./kustomize-1c6481d0 build ./input) <(./kustomize-00f0fd71 build ./input)
$
```

### Expected run time (based on 1c6481d0)

Execution using 1c6481d0 takes about an eighth of a second:

```
$ time ./kustomize-1c6481d0 build ./input > /dev/null

real    0m0.124s
user    0m0.122s
sys     0m0.016s
$
```

### Actual run time for 00f0fd71

Execution using 00f0fd71 takes about five eighths of a second:

```
$ time ./kustomize-00f0fd71 build ./input > /dev/null

real    0m0.636s
user    0m0.650s
sys     0m0.021s
$
```
