### ISSUE TITLE
kustomization/3.8.2: patches/target/namespace selects all non-namespace deployments

### ISSUE THREAD

**Issue by icy** [kubernetes-sigs/kustomize#2995]
When I specify a namespace as part of a patch target, that patch selects all deployments that don't include namespace. Is this a feature, or a bug?

In the following code, I expect the patch to be applied to deployments in `non-existent-namespace`. However, all deployments that don't include `namespace` specification are also patched. I have some poc in my repository: https://github.com/icy/kustomize-misc

```
resources:
- current.yaml

patches:
- path: p_deployment_nodeSelector_ops.json
  target:
    kind: Deployment
    namespace: non-existent-namespace
```

**Comment by icy** [comment]
Updated: Move my demo code here https://github.com/icy/kustomize-misc/tree/master/2995

**Comment by icy** [comment]
Files (duplication here, just in case)

## Actual output

```
$ kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-08-29T17:44:01Z GoOs:linux GoArch:amd64}

$ kustomize build |grep mine/group
        mine/group: my_worker_group
        mine/group: default
```

## Expected output

```
$ kustomize build |grep mine/group
        mine/group: my_worker_group
        mine/group: my_worker_group
```

## p_deployment_nodeSelector_ops.json

```
[
  {
    "op": "replace",
    "path": "/spec/template/spec/nodeSelector/mine~1group",
    "value": "default"
  }
]
```


## kustomization.yaml

```
resources:
- current.yaml

patches:

- path: p_deployment_nodeSelector_ops.json
  target:
    kind: Deployment
    namespace: non-existent-namespace
```

## current.yaml

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: myorg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: myorg
  name: myorg-with-namespace
  namespace: foo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: myorg
      app.kubernetes.io/name: myorg
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: myorg
        app.kubernetes.io/name: myorg
    spec:
      containers:
      - image: foo/bar
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: "/healthcheck.php"
            port: http
          timeoutSeconds: 10
        name: nginx
        ports:
      nodeSelector:
        mine/group: my_worker_group

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: myorg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: myorg
  name: myorg-without-namespace
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: myorg
      app.kubernetes.io/name: myorg
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: myorg
        app.kubernetes.io/name: myorg
    spec:
      containers:
      - image: foo/bar
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: "/healthcheck.php"
            port: http
          timeoutSeconds: 10
        name: nginx
        ports:
      nodeSelector:
        mine/group: my_worker_group
```
