### ISSUE TITLE
Endpoints after Service prevent from clean deleting objects

### ISSUE THREAD

**Issue by r0bj** [kubernetes-sigs/kustomize#3004]
Kustonize put Endpoints object after Service during manifest build. As a consequence there is no way to cleanly delete both object from kubernetes: after removing Service, kubernetes removes all corresponding endpoints by itself so deleting Endpoints finishes with error.

Example

svc.yaml
```
apiVersion: v1
kind: Endpoints
metadata:
  name: myapp
subsets:
- addresses:
  - ip: 1.1.1.1
    nodeName: node1
  ports:
  - name: metrics
    port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 8080
```

How kustomize generates manifest
```
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: myapp
subsets:
- addresses:
  - ip: 1.1.1.1
    nodeName: node1
  ports:
  - name: metrics
    port: 8080
```

Note: Service before Endpoints in order.

Create objects
```
# kustomize build | kubectl apply -f -
service/myapp created
endpoints/myapp created
```

Delete objects:
```
# kustomize build | kubectl delete -f -
service "myapp" deleted
Error from server (NotFound): error when deleting "STDIN": endpoints "myapp" not found
```

After Service was deleted, kubernetes removed corresponding Endpoints do there is no Endpoints object to delete and command finishes with error.

As a solution Endpoints object should be probably ordered before Service - in this case deleting works fine and finishes without error.
