### ISSUE TITLE
Merge multiple overlays that reference same resource without duplication

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes-sigs/kustomize#3014]
Hello `kustomize` team, great tool! I'm trying to see if we can use this for our multi-aws-account, multi-region, and multi-environment services. So far my attempt is:

```
├── base
│   ├── deployment.yaml
├── clusters
│   ├── prod_us-east-1
│   │   └── kustomization.yaml
│   ├── prod_us-west-2
│   │   └── kustomization.yaml
│   ├── staging_us-east-1
│   │   └── kustomization.yaml
│   └── staging_us-west-2
│       └── kustomization.yaml
└── overlays
    ├── registries
    │   ├── dev_us-east-1
    │   │   └── kustomization.yaml
    │   ├── dev_us-west-2
    │   │   └── kustomization.yaml
    │   ├── prod_us-east-1
    │   │   └── kustomization.yaml
    │   └── prod_us-west-2
    │       └── kustomization.yaml
    └── envs
        ├── prod
        │   ├── deployment_cpu_requests.yaml
        │   ├── kustomization.yaml
        └── staging
            ├── deployment_node_env.yaml
            └── kustomization.yaml
```
As you can see, `base` has the basic deployment.yaml. There are two types of overlays,

- `registries`, which changes the image name to AWS ECR format based on account and region. Example:
    ```yaml
    resources:
      - ../../../base/deployment.yaml
    images:
      - name: my-service
        newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/my-service
    ```
- `envs`, which updates deployment with environment specific setting. Example:
    ```yaml
    namespace: prod
    resources:
      - ../../../base/deployment.yaml
    patchesStrategicMerge:
      - deployment_cpu_requests.yaml # patch cpu requests for prod
    ```

Lastly, I have `clusters`  as "final" overlay which combines the above two together, to create a region,account,environment specific manifest:
```yaml
resources:
  - ../../overlays/registries/prod_us-east-1
  - ../../overlays/envs/production
```

However `kustomize build` generates two `Deployment` objects, one with CPU request patched, the other with image name patched. Is it possible to merge the two?

Or more generally, is it possible to create modular, re-usable transformations that can mix-and-match in another layer of overlay?

Thanks in advance.
