### ISSUE TITLE
can't use patch file with multiple patches and targeted patch together

### ISSUE THREAD

**Issue by dave93cab** [kubernetes-sigs/kustomize#3028]
```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - resource1
  - resource2
patches:
  - multiple_patches.yaml
  - path: single_patch.yaml
    target:
      kind: Deployment
      labelSelector: app=some_app
```

It doesn't appear to be possible to use both forms for patches in one `Component` (and I assume one `Kustomization`)

If I remove either of the patch items, the output is as expected, either:
1) All patches in `multiple_patches.yaml` are applied
2) Single patch in `single_patch.yaml`  is applied per selector

Error reported:
`json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type types.PatchStrategicMerge`

**Comment by dave93cab** [comment]
Seems if I do the following it works, using **patchesStrategicMerge**:

```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - resource1
  - resource2
patchesStrategicMerge:
  - multiple_patches.yaml
patches:
  - path: single_patch.yaml
    target:
      kind: Deployment
      labelSelector: app=some_app
```
