### ISSUE TITLE
PodTemplateSpec Namespace not converted within Deployment

### ISSUE THREAD

**Issue by blaggacao** [kubernetes-sigs/kustomize#3035]
```console
$ ./kustomize version
{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T15:39:21Z GoOs:linux GoArch:amd64}
```

```yaml
# ./deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
  namespace: spire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-server
    spec:
      containers:
        - name: spire-server
          image: gcr.io/spiffe-io/spire-server:0.11.0
```

```yaml
# ./kustomization.yaml
resources:
- ./deployment.yaml
namespace: test
```
---

## Wrong result:
```yaml
...
  template:
    metadata:
      namespace: spire  # wrong, should be 'test'
...
```

I can't reason about the impact at this moment, but it's undeniably wrong.
