### ISSUE TITLE
kustomize not replacing secret reference in container env section

### ISSUE THREAD

**Issue by larsks** [kubernetes-sigs/kustomize#3039]
**Describe the bug**

I am using kustomize to deploy metallb from http://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml. The pods in the daemonset created by this file include a secret key reference to a secret named `memberlist` that looks something like this:

```
apiVersion: apps/v1
kind: DaemonSet
spec:
  template:
    spec:
      containers:
        - name: speaker
          env:
            - name: METALLB_ML_SECRET_KEY
              valueFrom:
              secretKeyRef:
                name: memberlist
                key: secretkey
```

In my `kustomization.yml`, I have:

```
---
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml

secretGenerator:
  - name: memberlist
    files:
      - secretkey
```

The resulting output from `kustomize build` includes this secret resource:

```
apiVersion: v1
data:
  secretkey: ...
kind: Secret
metadata:
  labels:
    app: metallb
  name: memberlist-d5d2tfbg2m
type: Opaque
```
But the pod template still refers to `memberlist` rather than `memberlist-d5d2tfbg2m`.  

What's going on here?

**Expected output**

```
containers:
  - name: speaker
    env:
      - name: METALLB_ML_SECRET_KEY
        valueFrom:
	  secretKeyRef:
	    name: memberlist-d5d2tfbg2m
	    key: secretkey
```

**Actual output**

```
containers:
  - name: speaker
    env:
      - name: METALLB_ML_SECRET_KEY
        valueFrom:
	  secretKeyRef:
	    name: memberlist
	    key: secretkey
```

**Kustomize version**

{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-08-29T17:44:01Z GoOs:linux GoArch:amd64}

**Platform**

Linux

**Comment by larsks** [comment]
If I try to reproduce this behavior with a [simpler configuration](https://gist.github.com/larsks/af045955daa20aa5a186cd3354be8520), it works as expected.

**Comment by Shell32-Natsu** [comment]
Name reference update is one of most messy part in kustomize. Will take a look soon.

**Comment by larsks** [comment]
Here is a minimal reproducer:

https://github.com/larsks/kustomize-issue-3039

The only difference between the working and the failing version is:

```
diff -ruN fails/metallb.yml works/metallb.yml
--- fails/metallb.yml	2020-09-25 13:25:45.399570824 -0400
+++ works/metallb.yml	2020-09-25 13:26:28.593535470 -0400
@@ -3,7 +3,6 @@
 kind: DaemonSet
 metadata:
   name: speaker
-  namespace: metallb-system
 spec:
   selector:
     matchLabels:
```

**Comment by larsks** [comment]
Note that:

(a) I'm trying to avoid editing or forking the original resource.
(b) I can't set `namespace: <something>` in `kustomization.yml` because some of the resources created by the manifest are not namespaced (e.g., it create a new `ClusterRole`).

**Comment by Shell32-Natsu** [comment]
`Secret` [can only be accessed by the Pods in same namespace](https://kubernetes.io/docs/concepts/configuration/secret/#details). You can add a `namespace` to `secretGenerator`.

```
secretGenerator:
  - name: memberlist
    namespace: metallb-system
    files:
      - secretkey
```

**Comment by larsks** [comment]
Ah, thank you! That was easy.

**Comment by larsks** [comment]
Wait, I'm back! :) 

I'm configuring an oauth provider in openshift according to [these docs](https://docs.openshift.com/container-platform/4.5/authentication/identity_providers/configuring-oidc-identity-provider.html).

The client secret is a `Secret` resource in the `openshift-config` namespace. I'm generating it like this:

```
secretGenerator:
  - name: moc-sso-client-secret
    namespace: openshift-config
    literals:
      - clientSecret=secret
```

Which results in:

```
apiVersion: v1
data:
  clientSecret: c2VjcmV0
kind: Secret
metadata:
  name: moc-sso-client-secret-ct9hf85985
  namespace: openshift-config
type: Opaque
```

I'm generating an `OAuth` resource that refers to this secret:

```
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  namespace: openshift-config
spec:
  identityProviders:
    - mappingMethod: claim
      name: example
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: example
        clientSecret:
          name: moc-sso-client-secret
        extraScopes: []
        issuer: https://sso.example.com/auth/realms/moc
      type: OpenID
```

When I `kustomize build` in this directory, the generated `Oauth` resource is not using the hashed version of the secret name.

I assume this is because `kustomize` doesn't know that `clientSecret` is referring to the `Secret` resource. Is that correct?
