### ISSUE TITLE
Feature: add values from commands in configMapGenerator

### ISSUE THREAD

**Issue by laupow** [kubernetes-sigs/kustomize#304]
I'd like the abiltiy to load ConfigMap values from a command, like the functionality found in secretGenerator.

A specific example:

1. Terraform provisions a new CloudFront distribution
1. Terraform exposes the new hostname as a Terraform output value: CLOUDFRONT_HOSTNAME
1. The secretGenerator executes a command to load the hostname value from the Terraform output

Example kustomization.yaml I have today: 
```yaml
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - HOSTNAME=www.example.com
      - S3_BUCKET=my-s3-bucket
      - S3_REGION=us-east-2
      - S3_ACCESS_KEY=my-access-key

secretGenerator:
  - name: app-secrets
    commands:
      # Get a named variable from a Terraform output
      CLOUDFRONT_HOSTNAME: "get_terraform_output.sh  CLOUDFRONT_HOSTNAME"
      # Get a named env var from an Ansible Vault encrypted .env file
      S3_SECRET_KEY: "get_vaulted_secret.sh  S3_SECRET_KEY"
```

The current workaround is to put certain values inside of secrets, rather than configmaps, which is a little confusing.

Ideally we'd have the ability to write a configMapGenerator similar to:
```yaml
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - HOSTNAME=www.example.com
      - S3_BUCKET=my-s3-bucket
      - S3_REGION=us-east-2
      - S3_ACCESS_KEY=my-access-key
    commands:
      CLOUDFRONT_HOSTNAME: "get_terraform_output.sh  CLOUDFRONT_HOSTNAME"
```

PS: _Thank you_ for developing kustomize! 👏
