### ISSUE TITLE
commonAnnotations not added in deployment:template:spec 

### ISSUE THREAD

**Issue by DanyHenriquez** [kubernetes-sigs/kustomize#3042]
**Describe the bug**
When using the "commonAnnotations it does not add the annotations within the deployment template spec. It outputs the variables in stead of the values. For the deployment spec itself it works fine

note: The gitlab.properties are echoes out as *KEY=value*. One on every line.
```
GITLAB_ENV=<env_value>
GITLAB_APP=<app_value<
```

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: gitlab
    envs:
      - ./../../gitlab.properties

vars:
  - name: GITLAB_ENV
    objref:
      kind: ConfigMap
      name: gitlab
      apiVersion: v1
    fieldref:
      fieldpath: data.GITLAB_ENV
  - name: GITLAB_APP
    objref:
      kind: ConfigMap
      name: gitlab
      apiVersion: v1
    fieldref:
      fieldpath: data.GITLAB_APP

commonAnnotations:
  app.gitlab.com/env: $(GITLAB_ENV)
  app.gitlab.com/app: $(GITLAB_APP)

resources:
  - deployment.yml
  - service.yml
```

**Actual output**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/app: <app_value>
    app.gitlab.com/env: <env_value>
    ...
spec:
  ...
  template:
    metadata:
      annotations:
        app.gitlab.com/env: $(GITLAB_ENV)
        app.gitlab.com/app: $(GITLAB_APP)
```

**Expected output**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/app: <app_value>
    app.gitlab.com/env: <env_value>
    ...
spec:
  ...
  template:
    metadata:
      annotations:
        app.gitlab.com/app: <env_value>
        app.gitlab.com/env: <app_value>
```

**Kustomize version**

Version:kustomize/v3.8.2

**Platform**

Linux
