### ISSUE TITLE
kustomization.yaml file does not allow metadata field

### ISSUE THREAD

**Issue by mortent** [kubernetes-sigs/kustomize#3043]
**Describe the bug**

I would like to be able to add an annotation to the `kustomization.yaml` file, but it seems like the `metadata` field is not allowed. 

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
resources:
- dep.yaml
```

dep.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
...
```

Command:
```
kustomize build .
```

**Expected output**

I would expect the manifests printed to stdout.

**Actual output**

Error: json: unknown field "metadata"

**Kustomize version**

Built from HEAD

**Platform**

macOS

**Comment by Shell32-Natsu** [comment]
Yes, metadata is not allowed in kustomization file.

https://github.com/kubernetes-sigs/kustomize/blob/1bc9225302e7b2042b3eadd91ac35f19918e20c4/api/types/kustomization.go#L21-L140

**Comment by blaggacao** [comment]
This is also a problem for other tools such as https://github.com/derailed/k9s which bail as follows:
![image](https://user-images.githubusercontent.com/7548295/94609995-36d7d900-0265-11eb-8ca5-cc12a50b1c5b.png)

It might not be particularly intelligent to put the kustomization file in this place alongside the other files at the same level, but it might neither be invalid.

It seems as if tools would generally convert to selection based on:

1. `yaml|yml`
2. the referenced metadata key

**Comment by blaggacao** [comment]
Funnily, this maybe might have been the reason why `kustomize live` was withdrawn: it exposes the same error:

```console
$ kpt live apply deploy/playground
Error: can't find scope for resource Kustomization.kustomize.config.k8s.io

$ kustomize live apply deploy/playground/
Fatal error: can't find scope for resource Kustomization.kustomize.config.k8s.io
```

**Comment by blaggacao** [comment]
This also seems to break kubeval:
```console
$ kubeval -d deploy                  
ERR  - deploy/playground/kustomization.yaml: Missing 'metadata' key
PASS - deploy/upstream/asterisk/deployment.yaml contains a valid Deployment (asterisk)
ERR  - deploy/upstream/asterisk/kustomization.yaml: Missing 'metadata' key
PASS - deploy/upstream/asterisk/service.yaml contains a valid Service (asterisk)
PASS - deploy/upstream/goautodial/deployment.yaml contains a valid Deployment (goautodial)
ERR  - deploy/upstream/goautodial/kustomization.yaml: Missing 'metadata' key
PASS - deploy/upstream/goautodial/service.yaml contains a valid Service (goautodial)
ERR  - deploy/upstream/kustomization.yaml: Missing 'metadata' key
ERR  - deploy/upstream/storage/goautodial/kustomization.yaml: Missing 'metadata' key
PASS - deploy/upstream/storage/goautodial/pv.yaml contains a valid PersistentVolume (pv001)
PASS - deploy/upstream/storage/goautodial/pvc.yaml contains a valid PersistentVolumeClaim (pvc-caddy-data)
PASS - deploy/upstream/vicidial/deployment.yaml contains a valid Deployment (vicidial)
ERR  - deploy/upstream/vicidial/kustomization.yaml: Missing 'metadata' key
```
/cc @GodZalo

**Comment by monopole** [comment]
Let's add this: https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/objectmeta.go
as the type for a new `metadata` field.  it's why the file exists, we just never got around to it.

**Comment by monopole** [comment]
we can add other fields from https://pkg.go.dev/k8s.io/apimachinery@v0.19.2/pkg/apis/meta/v1#ObjectMeta
as needed, but not reference that file directly as it will block integration into kubectl (#1500)

**Comment by monopole** [comment]
parenthetically, we should allow these fields certainly, but requiring `apiVersion`, `kind` and `metadata` will require adding the fields to all examples and tests.

**Comment by mamiu** [comment]
@monopole 

Does this fix mean that we're now able to do something like this:

**The folder structure:**

```
manifests
├─ envs
│  ├─ dev
│  │  └─ kustomization.yaml
│  └─ ...
│     └─ kustomization.yaml
└─ resources
   ├─ kustomization.yaml
   ├─ app
   │  ├─ some-kubernetes-resource-files.yaml
   │  └─ kustomization.yaml
   └─ db
      ├─ some-kubernetes-resource-files.yaml
      └─ kustomization.yaml
```

**The** `manifests/resources/kustomization.yaml` **file:**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app
  - db
```

**With your fix we could now name the** `manifests/resources/db/kustomization.yaml` **kustomization file like this:**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: db-kustomization

commonLabels:
  app: postgresql

resources:
  - secret.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ...
```

**Does that mean we're now able to do a multi level/layer kustomization like in the following example?**

`manifests/envs/dev/kustomization.yaml` file:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../resources

patches:
  - target:
      kind: Kustomization
      name: db-kustomization
    patch: |-
      - op: replace
        path: /commonLabels/app
        value: postgresql-dev
```

Because it wasn't or only hardly possible to kustomize `kustomizations` so far. Not even with the [configuration of builtin plugins](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configureBuiltinPlugin.md).
