### ISSUE TITLE
Patches do not work over dynamic resources defined by variables

### ISSUE THREAD

**Issue by toninis** [kubernetes-sigs/kustomize#3045]
**Describe the bug**

Patches do not patch the resources when there is a variable specified for the resource.

**Files that can reproduce the issue**

Actual source https://github.com/kubeflow/manifests/tree/master/istio-1-3-1/cluster-local-gateway-1-3-1/base

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: PreSync
          kustomize.config.k8s.io/behavior: replace
    target:
      kind: Namespace
      name: istio-system

vars:
  - name: namespace
    objref:
      kind: ConfigMap
      name: cluster-local-gateway-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.namespace

configurations:
  - params.yaml

configMapGenerator:
  - name: cluster-local-gateway-parameters
    envs:
      - params.env
```

ns.yaml

```
apiVersion: v1
kind: Namespace
metadata:
  name: $(namespace)
```

params.yaml

```
varReference:
- path: metadata/name
  kind: Namespace

```

params.env

```
namespace=istio-system
```

**Expected output**

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    kustomize.config.k8s.io/behavior: replace
  name: istio-system
---
apiVersion: v1
data:
  namespace: istio-system
kind: ConfigMap
metadata:
  name: cluster-local-gateway-parameters-tbbdb2842d
```

**Actual output**

```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
data:
  namespace: istio-system
kind: ConfigMap
metadata:
  name: cluster-local-gateway-parameters-tbbdb2842d
```

**Kustomize version**

```
{Version:v3.8.1+ksops.e006126197136251601b65c9fba51897761fb0a6 GitCommit:v3@v3.8.1 BuildDate:2020-08-14T12:11:58Z GoOs:darwin GoArch:amd64}
```

**Platform**

```
Darwin Kernel Version 19.6.0
```
