### ISSUE TITLE
Patches of same annotations do not override commonAnnotations

### ISSUE THREAD

**Issue by toninis** [kubernetes-sigs/kustomize#3046]
**Describe the bug**

Patches on annotations should override commonAnnotations of all resources.

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  foo: bar

resources:
  - ns.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          foo: should-be-replaced
          kustomize.config.k8s.io/behavior: replace
    target:
      kind: Namespace
      name: istio-system

```

ns.yaml

```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
```

**Expected output**

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    foo: should-be-replaced
    kustomize.config.k8s.io/behavior: replace
  name: istio-system
```

**Actual output**

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    foo: bar
    kustomize.config.k8s.io/behavior: replace
  name: istio-system
```

**Kustomize version**

```
{Version:v3.8.1+ksops.e006126197136251601b65c9fba51897761fb0a6 GitCommit:v3@v3.8.1 BuildDate:2020-08-14T12:11:58Z GoOs:darwin GoArch:amd64}
```

**Platform**

```
Darwin Kernel Version 19.6.0
```

**Comment by Shell32-Natsu** [comment]
This is because AnnotationTransformer is run after PatchTransformer. https://kubernetes-sigs.github.io/kustomize/contributing/howitworks/

**Comment by toninis** [comment]
@Shell32-Natsu Indeed if we use this kustomization.yaml it works as expected. 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  foo: bar

resources:
  - ns.yaml

patchesJson6902:
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          foo: should-be-replaced
          kustomize.config.k8s.io/behavior: replace
    target:
      version: v1
      kind: Namespace
      name: istio-system
```

Should this behaviour be the same with `PatchTransformer` and  `PatchStrategicMergeTransformer` ??
