### ISSUE TITLE
Unmatched fields from base file are not reproduced after overlaying.

### ISSUE THREAD

**Issue by chainhead** [kubernetes-sigs/kustomize#3047]
I am using `kustomize` to generate files corresponding to the [`eksctl` configuration schema file](https://eksctl.io/usage/schema/). However, the generated file is only the overlay file and not the whole file. What am I missing?

`yaml/kustomization.yaml`
```yaml
resources:
  - mysql-node-group.yaml
```

`yaml/mysql-node-group.yaml`
```bash
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-db
  region: ap-southeast-1
managedNodeGroups:
  - name: ng-mysql
    instanceType: m5.large
    instancePrefix: mysql
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: eks-cluster-ng1
      sourceSecurityGroupIds:
        - sg-0c05744a8ddaabc00
    labels:
      workload: db
    privateNetworking: true
    tags:
      env: dev
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        cloudWatch: true
    securityGroups:
    volumeType: io1
    volumeIOPS: 1000
```

`overlay/kustomization.yaml`
```bash
bases:
  - ../yaml
patches:
  - mysql-node-group.yaml
```

`overlay/mysql-node-group.yaml`
```bash
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-db
  region: ap-southeast-1
managedNodeGroups:
  - name: ng-mysql
    ssh:
      allow: true
      sourceSecurityGroupIds:
        - sg-0c05744a8ddaabc00
```

To generate the YAML. I am running `kustomize build overlay` and I get as the response.

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
managedNodeGroups:
- name: ng-mysql
  ssh:
    allow: true
    sourceSecurityGroupIds:
    - sg-0c05744a8ddaabc00
metadata:
  name: demo-db
  region: ap-southeast-1
```

```bash
# On MacOS Catalina
kustomize version
{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T17:31:52+01:00 GoOs:darwin GoArch:amd64}
```

**Comment by Shell32-Natsu** [comment]
Kustomize can only merge the resources that is known to it, i.e. k8s standard resources. When it comes to unknown resource like in this issue, the list in the patch will replace the list in the original source. Try to use [JSON 6902 patch](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md).

**Comment by angeloplsight** [comment]
```yaml
patchesJSON6902:
- target:
    kind: "somekind"
    group: "somekind.somekind.io"
    version: v1
    name: "some-kind"
    namespace: "some-kind"
  patch: |-
    - op: add
      path: "/spec/values/cronjobs/global/orgIds"
      value:
        - 2949
        - 4070
        - 5936
        - 5243
        - 6231
        - 6027
        - 5996
        - 4824
        - 5352
        - 2366
        - 5146
        - 4897
        - 5615
        - 4080
        - 4307
        - 4714
```
Will try with this...
