### ISSUE TITLE
Merge Not Occurring Correctly

### ISSUE THREAD

**Issue by angeloplsight** [kubernetes-sigs/kustomize#3063]
I have the base and the overlay. The final output of the merge file is excluding some data from the overlay...

The base yaml
```yaml
    cronjobs:
      global:
        orgIds:
          - 1234
          - 4474
```
```yaml
    cronjobs:
      global:
        orgIds:
          - 2949
          - 4070
          - 5936
          - 5243
          - 6231
          - 6027
          - 5996
          - 4824
          - 5352
          - 2366
          - 5146
          - 4897
          - 5615
          - 4080
          - 4307
          - 4714
```
The output yaml exclude the base yaml
```yaml
    cronjobs:
      global:
        orgIds:
        - 2949
        - 4070
        - 5936
        - 5243
        - 6231
        - 6027
        - 5996
        - 4824
        - 5352
        - 2366
        - 5146
        - 4897
        - 5615
        - 4080
        - 4307
        - 4714
```

**Expected output**

    cronjobs:
      global:
        orgIds:
          - 1234
          - 4474
          - 2949
          - 4070
          - 5936
          - 5243
          - 6231
          - 6027
          - 5996
          - 4824
          - 5352
          - 2366
          - 5146
          - 4897
          - 5615
          - 4080
          - 4307
          - 4714

**Actual output**
```yaml
      global:
        orgIds:
        - 2949
        - 4070
        - 5936
        - 5243
        - 6231
        - 6027
        - 5996
        - 4824
        - 5352
        - 2366
        - 5146
        - 4897
        - 5615
        - 4080
        - 4307
        - 4714
```

**Kustomize version**
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin amd64}

**Platform**
macOS

**Additional context**
