### ISSUE TITLE
v3.8.5 Error: add operation does not apply: doc is missing path: "/spec/template/spec/containers/0/env/-": missing value

### ISSUE THREAD

**Issue by hiroshi** [kubernetes-sigs/kustomize#3070]
**Describe the bug**

Hi,
I found the version v3.8.5 causes an error while it wasn't with v3.8.4.
`Error: add operation does not apply: doc is missing path: "/spec/template/spec/containers/0/env/-": missing value`

**Files that can reproduce the issue**

base/kustomization.yaml
```
resources:
- deployment.yaml
```
base/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        env: []
```

overlay/kustomize.yaml
```
bases:
- ../base
patchesStrategicMerge:
- merge.yaml
patches:
- path: patch.yaml
  target:
    kind: Deployment
```

overlay/merge.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - name: nginx2
        image: nginx
```

overlay/patch.yaml
```
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ENV
    value: overlay
```

**Expected output**
```
$ curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s 3.8.4
$ ./kustomize  build overlay
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - env:
        - name: ENV
          value: overlay
        image: nginx
        name: nginx
      - image: nginx
        name: nginx2
```

**Actual output**
```
$ curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s 3.8.5
$ ./kustomize  build overlay
Error: add operation does not apply: doc is missing path: "/spec/template/spec/containers/0/env/-": missing value
```

**Kustomize version**

`{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:darwin GoArch:amd64}`

**Platform**

- macOS 10.15.7 Catalina 
- docker (linux amd64)
