### ISSUE TITLE
RoleBinding roleRef.name wrongly adjusted by PrefixSuffixTransformer

### ISSUE THREAD

**Issue by r0bj** [kubernetes-sigs/kustomize#3073]
**Describe the bug**

RoleBinding roleRef.name wrongly adjusted by PrefixSuffixTransformer.

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workloads.yaml
transformers:
- suffixTransformer.yaml
namespace: test

```

workloads.yaml

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myapp
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myapp
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp

```

suffixTransformer.yaml
```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: notImportantHere
suffix: -suffix
fieldSpecs:
- path: metadata/name
  kind: ClusterRole
  name: myapp
- path: metadata/name
  kind: ClusterRoleBinding
  name: myapp

```

**Expected output**

[...]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapp
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myapp
subjects:
- kind: ServiceAccount
  name: myapp
  namespace: test
```
[...]

**Actual output**

[...]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapp
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myapp-suffix
subjects:
- kind: ServiceAccount
  name: myapp
  namespace: test
```
[...]

Note: `roleRef.name` is adjusted by adding suffix which is wrong.
PrefixSuffixTransformer is configured to only adjust `ClusterRole` and `ClusterRoleBinding` but somehow `Role` in `RoleBinding` is also changed.

**Kustomize version**
```
{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T17:31:52+01:00 GoOs:darwin GoArch:amd64}
```
