### ISSUE TITLE
[Question] Replace secretgenerator secret with a plugin-generated secret?

### ISSUE THREAD

**Issue by larsks** [kubernetes-sigs/kustomize#3078]
I am trying to replace a `secretGenerator`-generated resource in a base with a plugin generated (ksops-encrypted) secret, and it's failing because:

```
Error: merging from generator &{0xc0002a76a0 0xc00012d680 [./certificate.yml ./deploykeys.yml ./bitlbee_config.yml]}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", K
ind:"Secret"}, Name:"bitlbee-config", Namespace:""} exists; behavior must be merge or replace
```

In `../base/kustomization.yml`, I have:

```
secretGenerator:
  - name: bitlbee-config
    files:
      - bitlbee.conf
```

In my local directory, I have:

```
bases:
  - ../base

generators:
  - secret-generator.yml
```

In `secret-generator.yml` I have:

```
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - ./bitlbee_config.yml
```

And in `bitlbee_config.yml` I have:

```
apiVersion: v1
kind: Secret
metadata:
    name: bitlbee-config
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    bitlbee.conf: |
      ...content goes here...
```

I want the secret created from the sops-encrypted file to replace the static secret in the base directory. I see that e.g. for `configMapGenerator` and `secretGenerator` I can set a `behavior` key to control create vs replace, but I don't see a similar option for `generators`, which is a list rather than a map and doesn't appear to support anything other than a list of files.

**Comment by Shell32-Natsu** [comment]
Are you using your own generator?

**Comment by larsks** [comment]
@Shell32-Natsu no, I am using [ksops](https://github.com/viaduct-ai/kustomize-sops).

**Comment by Shell32-Natsu** [comment]
The `behavior` should be added by the generator.

**Comment by larsks** [comment]
That sounds like an awful lot of boilerplate code for plugins to implement. I was hoping this could be controlled by `kustomize`. I guess I will move this issue over to ksops...

**Comment by larsks** [comment]
@Shell32-Natsu how would a plugin implement this behavior? I thought a plugin effectively consumed a YAML description and produces YAML output containing one or more resources. If I were writing a plugin, how would I indicate to `kustomize` that resources should be handled with replace/merge/create behavior?

**Comment by Shell32-Natsu** [comment]
When the plugin is generating the `Resource` struct, there is an `options` field in it.

https://github.com/kubernetes-sigs/kustomize/blob/7c8c827a88cbc5bfde88154d4c6e0fe791bd3443/api/resource/resource.go#L20-L29

`types.GenArgs` contains `GeneratorArgs` and then there is a `Behavior` field in it.

https://github.com/kubernetes-sigs/kustomize/blob/20643c933ec5ff06089d160e47933ad226b4338e/api/types/generatorargs.go#L16-L20

**Comment by larsks** [comment]
@Shell32-Natsu Thanks; that's helpful. Is that metadata that I can provide in generated yaml/json output if I am using an exec plugin?

**Comment by Shell32-Natsu** [comment]
Yes, you can use `kustomize.config.k8s.io/behavior` annotation to specify the behavior.

**Comment by larsks** [comment]
Awesome! That means that I don't need to fix this in a plugin. I can just place the necessary annotation in the sops-encrypted file:

```
apiVersion: v1
kind: Secret
metadata:
    name: bitlbee-config
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: replace
stringData:
  ...
```

That seems to work great and doesn't require updates to the plugin.  Thank you!
