### ISSUE TITLE
[Question] Inline patchesJson6902 on kustomize/v3.8.5 

### ISSUE THREAD

**Issue by andresilva97** [kubernetes-sigs/kustomize#3079]
Why on my code kustomize give the follow error:
`Error: json: unknown field "patch"`

Code:
```
patchesJson6902:
- patch: |-
    - op: add
      path: /spec/clusterIP
      value: 0.0.0.0
  target:
    group: apps
    version: v1
    kind: Service
    name: service-dns
```
I saw multiple examples using this kind of patch , but i dont understand why it wont work on mine.
