### ISSUE TITLE
How to reuse Deployment patch for CronJob

### ISSUE THREAD

**Issue by 2shsh** [kubernetes-sigs/kustomize#3089]
Hi!

I use same environment variables in Deployment and CronJob. And I need to create two patches for that.
How to reuse patch?
```
.
├── base/
│   ├── deployment.yaml
│   ├── cronjob.yaml
│   └── kustomization.yaml
└── overlays/
    └── prod/
        ├── kustomization.yaml
        ├── env_vars_patch_deployment.yaml
        └── env_vars_patch_cronjob.yaml
```

Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: finisher
  name: finisher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: finisher
  template:
    metadata:
      labels:
        name: finisher
    spec:
      containers:
      - command:
        - /bin/call
        image: dummy-image:latest
        name: finisher
        ports:
        - containerPort: 8000
          name: http
```
and patch for this:
```yaml
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: GUNICORN_WORKERS
      value: "6"
    - name: GUNICORN_THREADS
      value: "1"
    - name: GUNICORN_TIMEOUT
      value: "60"
    - name: DB_CONNECTION_TIMEOUT
      value: "3"
    - name: DB_POOL_PRE_PING
      value: "false"
```

CronJob:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: partition-upgrader
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cron: partition-upgrader
        spec:
          containers:
          - image: dummy-image:latest
         ...
```

and patch for CronJob (diferent path, but same value):
```yaml
- op: add
  path: /spec/jobTemplate/spec/template/spec/containers/0/env
  value:
    - name: GUNICORN_WORKERS
      value: "6"
    - name: GUNICORN_THREADS
      value: "1"
    - name: GUNICORN_TIMEOUT
      value: "60"
    - name: DB_CONNECTION_TIMEOUT
      value: "3"
    - name: DB_POOL_PRE_PING
      value: "false"
```
