### ISSUE TITLE
[Question] How to patch a single resource if multiple copies exist in different namespaces?

### ISSUE THREAD

**Issue by farrajota** [kubernetes-sigs/kustomize#3092]
I want to reuse a single component in two different namespaces and patch each one of them with different configs. What I'm attempting to do is the following:
- create two databases with the same setup (incl. name) in different namespaces
- patch each database with different resource specs

When building the manifest with `kubectl kustomize > deploy.yaml` this is the output I'm getting:

```
$ kubectl kustomize > deploy.yaml
Error: found multiple objects []resid.ResId{resid.ResId{gvKind:gvk.Gvk{Group:"apps", Version:"v1", Kind:"StatefulSet"}, name:"postgres", prefix:"", suffix:"", namespace:"database"}, resid.ResId{gvKind:gvk.Gvk{Group:"apps", Version:"v1", Kind:"StatefulSet"}, name:"postgres", prefix:"", suffix:"", namespace:"monitoring"}} targeted by patch resid.ResId{gvKind:gvk.Gvk{Group:"apps", Version:"v1", Kind:"StatefulSet"}, name:"postgres", prefix:"", suffix:"", namespace:"database"} (ambiguous)
```

It cannot disambiguate between the two resources because they have the same name but it does not take into consideration the namespace. 

Is it possible to do this currently with kustomize?

## kubectl version

```
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
``` 

> Note: I've tried with the latest kubectl `v1.20.0-alpha.1` and I got the same error.

# Example code

Here is an example of what I'm attempting to do with a simplified scenario. Bellow is the repository dir structure

```
patches/
    database/
        postgres.yaml
    monitoring/
        postgres.yaml
resources/
    database/
        kustomization.yaml
        postgres.yaml
    monitoring/
        kustomization.yaml
        postgres.yaml
kustomization.yaml
```

### kustomization.yaml
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- resources/database
- resources/monitoring
patches:
- patches/database/postgres.yaml
```

### patches/database/postgres.yaml
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: primary
  name: postgres
  namespace: database
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      component: primary
  template:
    metadata:
      labels:
        component: primary
    spec:
      containers:
      - name: postgres
        resources:
          limits:
            cpu: "5"
            memory: 5Gi
          requests:
            cpu: "5"
            memory: 5Gi
```

### patches/monitoring/postgres.yaml
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: primary
  name: postgres
  namespace: monitoring
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      component: primary
  template:
    metadata:
      labels:
        component: primary
    spec:
      containers:
      - name: postgres
        resources:
          limits:
            cpu: "6"
            memory: 6Gi
          requests:
            cpu: "6"
            memory: 6Gi
```

### kustomization.yaml
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

commonLabels:
  app: database

resources:
- postgres.yaml

images:
- name: POSTGRES
  newName: postgres
  newTag: "13"
```

### postgres.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    component: primary
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
  selector:
    component: primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: primary
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      component: primary
  template:
    metadata:
      labels:
        component: primary
    spec:
      containers:
      - name: postgres
        image: POSTGRES
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: pg
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        securityContext:
          runAsUser: 70  # postgres user
```

### kustomization.yaml
```yaml
--
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  app: monitoring

resources:
- postgres.yaml

images:
- name: POSTGRES
  newName: postgres
  newTag: "13"
```

### postgres.yaml

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    component: primary
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
  selector:
    component: primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: primary
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      component: primary
  template:
    metadata:
      labels:
        component: primary
    spec:
      containers:
      - name: postgres
        image: POSTGRES
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: pg
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        securityContext:
          runAsUser: 70  # postgres user
```
