### ISSUE TITLE
vars only works on top level labels

### ISSUE THREAD

**Issue by YujiShen** [kubernetes-sigs/kustomize#3098]
**Describe the bug**

#682 closed, but as @srfrnk mentioned, the fix does not work for lower level labels.

**Files that can reproduce the issue**

cronjob.yaml

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example
  labels:
    job: $(JOB_NAME)
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    metadata:
      labels:
        job: $(JOB_NAME)
    spec:
      template:
        metadata:
          labels:
            job: $(JOB_NAME)
        spec:
          containers:
            - name: example
              image: example-image
              envFrom:
                - configMapRef:
                    name: example-env
```

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- behavior: add
  name: example-env
  literals:
    - JOB_NAME=job_value
resources:
  - cronjob.yaml
vars:
  - name: JOB_NAME
    objref:
      kind: ConfigMap
      name: example-env
      apiVersion: v1
    fieldref:
      fieldpath: data.JOB_NAME
```

**Expected output**

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    job: job_value
  name: example
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    metadata:
      labels:
        job: job_value
    spec:
      template:
        metadata:
          labels:
            job: job_value
        spec:
          containers:
             - envFrom:
                configMapRef:
                    name: example-env-2t6k6bhtmd
                image: example-image
                name: example
```

**Actual output**

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    job: job_value
  name: example
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    metadata:
      labels:
        job: $(JOB_NAME)
    spec:
      template:
        metadata:
          labels:
            job: $(JOB_NAME)
        spec:
          containers:
             - envFrom:
                configMapRef:
                    name: example-env-2t6k6bhtmd
                image: example-image
                name: example
```

**Kustomize version**

3.8.5

**Platform**

macOS

**Additional context**

**Comment by Shell32-Natsu** [comment]
The fields that will be updated by variable reference can be customized by `configurations` field in kustomize.

create a `config.yaml` file
```yaml
varReference:
- path: spec/jobTemplate/metadata/labels/job
  kind: CronJob
- path: spec/jobTemplate/spec/template/metadata/labels/job
  kind: CronJob
```

Then add 
```yaml
configurations:
  - config.yaml
```
to your `kustomization.yaml` file. You will get expect result.
