### ISSUE TITLE
[Question] How to include labels for every configmap in a configmapList?

### ISSUE THREAD

**Issue by KR411-prog** [kubernetes-sigs/kustomize#3108]
I have a yaml file like below.This yaml file needs to be patched with a new label under each configmap.

```
apiVersion: v1
kind: ConfigMapList
items:
  - apiVersion: v1
    data:
      test: 1
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-apiserver1
      namespace: monitoring   
  - apiVersion: v1
    data:
      test: 2
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-apiserver2
      namespace: monitoring   
  - apiVersion: v1
    data:
      test: 3
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-apiserver3
      namespace: monitoring    

```
I want to insert labels under every configmap in this configmaplist as below,

```
apiVersion: v1
kind: ConfigMapList
items:
  - apiVersion: v1
    data:
      test: 1
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-apiserver1
      namespace: monitoring
      labels:
        grafana_dashboard: "1"   
  - apiVersion: v1
    data:
      test: 2
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-apiserver2
      namespace: monitoring   
      labels:
        grafana_dashboard: "1" 
  - apiVersion: v1
    data:
      test: 3
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-apiserver3
      namespace: monitoring    
      labels:
        grafana_dashboard: "1" 
```
I tried to do this using Kustomize by following https://kubectl.docs.kubernetes.io/pages/app_customization/customizing_arbitrary_fields.html. But its not working.

Here is my file,
```
overlays/patch.yaml
- op: add
  path: /items/?/metadata/labels/testlabel
  value: test
```

overlays/kustomization.yaml
```
bases:
- ../base
patchesJson6902:
- target:
    kind: ConfigMapList
  path: patch.yaml
```

Since ConfigMapList does not contain a name, its not working in target,
but it reports error as , `: must specify the target name
How to do patching in ConfigMapList?
Also for the patch.yaml file,I have used "?" here in this example..but I am not sure what to use to replace it..because it is around 100 different configmaps under items.Should I use wildcard * ?

**Comment by pantaoran** [comment]
I have the exact same question/problem. I need to add an annotation to every item in a list, and the annotation should be different for every environment.

**Comment by Shell32-Natsu** [comment]
1. Please use `patches` instead of `patchesJson6902`.
2. `*List` resources will be parsed to a list of resources in kustomize instead of a single resource. So there is no `ConfigMapList` in kustomize but a list of `ConfigMap`. In `target.kind` you should use `ConfigMap`.
3. JSON patch requires the `path` except last item does exist. If you want to add a label `/metadata/labels/testlabel`, `/metadata/labels` must exist.
4. If you just want to add labels, you can use LabelTransformer and custom fieldSpec to add labels to a list. [doc](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configureBuiltinPlugin.md)

Transformer YAML:
```yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: notImportantHere
labels:
  app: hello
fieldSpecs:
- kind: ConfigMap
  path: /metadata/labels
  create: true
```

Then add 
```yaml
transformers:
- label_transformer.yaml
```
to the kustomization.yaml file.
