### ISSUE TITLE
Regression at master for PatchTransformer when ports have matching containerPort values

### ISSUE THREAD

**Issue by ephesused** [kubernetes-sigs/kustomize#3109]
When a deployment has a container with two differently-named ports that match on the containerPort, a PatchTransformer is causing one port to disappear.

Note that I have not adjusted to the new pin/unpin process, and this issue arose with a straight pull from master. If there is something I need to do (past a pull), I'm happy to adjust.

My testing used 7e04be9e, running the testcase described over in #2767:

### Test setup

kustomization.yaml

```yaml
resources:
  - resources.yaml

transformers:
  - transformers.yaml
```

resources.yaml

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  template:
    spec:
      containers:
      - image: test-image
        name: test-deployment
        ports:
        - containerPort: 8080
          name: take-over-the-world
          protocol: TCP
        - containerPort: 8080
          name: disappearing-act
          protocol: TCP
```

transformers.yaml

```yaml
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: test-transformer
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-transformer
    labels:
      test-transformer: did-my-job
target:
  kind: Deployment
  name: test-deployment
```

### Expected behavior

This is the behavior seen in 0a1fde1e. The two port entries are present.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test-transformer: did-my-job
  name: test-deployment
spec:
  template:
    spec:
      containers:
      - image: test-image
        name: test-deployment
        ports:
        - containerPort: 8080
          name: take-over-the-world
          protocol: TCP
        - containerPort: 8080
          name: disappearing-act
          protocol: TCP
```

### Actual behavior

This is the behavior seen in 7e04be9e. The take-over-the-world port disappeared.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test-transformer: did-my-job
  name: test-deployment
spec:
  template:
    spec:
      containers:
      - image: test-image
        name: test-deployment
        ports:
        - containerPort: 8080
          name: disappearing-act
          protocol: TCP
```
