### ISSUE TITLE
How to use dynamic namespace name in ingress ?

### ISSUE THREAD

**Issue by bcouetil** [kubernetes-sigs/kustomize#3116]
Hello,

I first want you to thank contributors to this great tool :smiling_face_with_three_hearts: 

On my projects, I apply my manifests to dev/staging/prod, but also to namespaces choosen dynamically, named after the feature branches, or named after a given developer for local development, for real time synchronization with a personal namespace in cluster.

For those dynamic namespaces, the name of the branch (or of the developer) is used in ingresses paths. For example, as a developer named `bcouetil`, kustomize will be applied to `bcouetil` namespace, and my app will be available at `app-bcouetil.example.dev`

How would I do that with kustomize ? I'm falling back to using `envsubst` for now... (please don't kill me).

I will try solution described in #164, using a `configMapGenerator`, but I'm wondering if there could be some special treatment around namespace, as there already is with docker image tag.

**Comment by bcouetil** [comment]
Substitution does not work in my case for the officially authorized `Ingress` field `spec/rules/host`, I must have missed something :
> well-defined vars that were never replaced: NAMESPACE

Here are my files :

> kustomization.yml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: cluster-properties
  envs:
  - cluster.properties

vars:
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-properties
  fieldref:
    fieldpath: data.namespace

resources:
  - ingress.yaml
```

> ingress.yaml
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kib-kibana
spec:
  rules:
    - host: kibana-${NAMESPACE}.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kib-kibana
              servicePort: 5601
```

> cluster.properties
```
namespace=my-feature
```

Please enlighten me :smile:
