### ISSUE TITLE
[Question] How to avoid mutating namespace field of default ServiceAccount in RoleBinding.subjects ?

### ISSUE THREAD

**Issue by everpeace** [kubernetes-sigs/kustomize#3127]
I wanted to generate `RoleBinding` resource which binds `default` ServiceAccount in __another namespace__.   I tried to customize namespace built-in transformer as below.  However, it looks like kustomize forcefully mutates namespace field of ServiceAccount when its name is default. How could we avoid it??

```shell
$ cd $ (mktemp -d)
$ cat << EOT > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foo
configurations:
- kustomizeconfig.yaml
resources:
# there are other resources that I want to use namespace transformer in actual usecase
- rbac.yaml
EOT

$ cat << EOT > kustomizeconfig.yaml
# exclude RoleBinding.subjects and ClusterRoleBinding.subjects from default namespaceFieldRef
# ref: https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namespace.go
namespace:
- path: metadata/namespace
  create: true
- path: metadata/name
  kind: Namespace
  create: true
- path: spec/service/namespace
  group: apiregistration.k8s.io
  kind: APIService
  create: true
EOT

$ cat << EOT > rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role
subjects:
- kind: ServiceAccount
  name: default
  namespace: other-ns
- kind: ServiceAccount
  name: non-default
  namespace: other-ns
EOT
```

```shell
$ kustomize version
{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T15:39:21Z GoOs:darwin GoArch:amd64}

$ kustomize build .
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo  # THIS EXPECTS TO BE 'other-ns'
- kind: ServiceAccount
  name: non-default
  namespace: other-ns
```

**Comment by Shell32-Natsu** [comment]
`subjects` in RoleBinding is configured in builtin plugins. You can avoid this by explicitly using [plugin](https://kubernetes-sigs.github.io/kustomize/guides/plugins/builtins/#_namespacetransformer_). In this way, builtin configurations will be overridden.

**Comment by everpeace** [comment]
@Shell32-Natsu 
I thought I tried it by using `configurations` clause in `kustomization.yaml`.  And, I tried to use builtin plugin as you described, this also mutates it.  Could you kindly reopen this because it seems I don't have permission to reopen??

```shell
$ cd $(mktemp -d)
$ cat << EOT > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
- trans.yaml
resources:
- rbac.yaml
EOT

$ cat << EOT > trans.yaml
# exclude RoleBinding.subjects and ClusterRoleBinding.subjects from default namespaceFieldRef
# ref: https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namespace.go
apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: not-important-to-example
  namespace: foo
fieldSpecs:
- path: metadata/namespace
  create: true
- path: metadata/name
  kind: Namespace
  create: true
- path: spec/service/namespace
  group: apiregistration.k8s.io
  kind: APIService
  create: true
EOT

$ cat << EOT > rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role
subjects:
- kind: ServiceAccount
  name: default
  namespace: other-ns
- kind: ServiceAccount
  name: non-default
  namespace: other-ns
EOT
```


```shell
$ kustomize version
{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T15:39:21Z GoOs:darwin GoArch:amd64}

$ kustomize build .
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo      # THIS EXPECTS TO BE 'other-ns'
- kind: ServiceAccount
  name: non-default
  namespace: other-ns
```

**Comment by Shell32-Natsu** [comment]
I see. The subject with name `default` is hardcoded and has a special hack. https://github.com/kubernetes-sigs/kustomize/issues/2906#issuecomment-684036911. The hack will always update the namespace for default service account. What I can suggest is not using `default` name.

**Comment by everpeace** [comment]
> The subject with name default is hardcoded and has a special hack.

hmm...  I'm interested in the reason for this hack.  I'm thinking to add an option bypassing the hack in namespace transformer?

**Comment by Shell32-Natsu** [comment]
@monopole Do you have any idea of why do we have this hack?

https://github.com/kubernetes-sigs/kustomize/blob/719532e4df44f553fcfa5b51fb519eca2bcf4e9d/api/filters/namespace/namespace.go#L93-L106

**Comment by Shell32-Natsu** [comment]
@pwittrock Could you remember the reason to add this?

**Comment by mjuarez** [comment]
Currently experiencing this issue with a non-default ServiceAccount on `{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}`

I'm trying to configure a ClusterRoleBinding for prometheus to a ServiceAccount managed with kustomize:

input:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-nexus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: foo
```

transformer:
```
---
apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: role-bindings
  namespace: nexus
fieldSpecs:
- path: metadata/namespace
  create: true
- path: subjects
  kind: ClusterRoleBinding
  group: rbac.authorization.k8s.io
```

output:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: nexus
  name: prometheus
  namespace: nexus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: nexus
  name: prometheus-nexus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: foo
  ```
  
Switching ServiceAccount's metadata.name to `default` works, but I already have a ServiceAccount with that name and I don't wish to replace.
