### ISSUE TITLE
namePrefix not updating resource references

### ISSUE THREAD

**Issue by andredasilvapinto** [kubernetes-sigs/kustomize#3130]
**Describe the bug**
masterInstanceRef (sql instance) and instanceRef (sql database) are not updated with the prefix when using namePrefix overlay.

**Files that can reproduce the issue**

A simplified case can be found here: https://github.com/andredasilvapinto/kustomize-prefix-issue

After cloning you should run `kustomize build overlays/test/`

**Expected output**

```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: testing-thedatabase
  namespace: the-namespace
spec:
  instanceRef:
    name: testing-the-primary
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: testing-the-primary
  namespace: the-namespace
spec:
  databaseVersion: POSTGRES_10
  region: europe-west1
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: testing-the-replica
  namespace: the-namespace
spec:
  databaseVersion: POSTGRES_10
  masterInstanceRef:
    name: testing-the-primary
  region: europe-west1
```

**Actual output**

```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: testing-thedatabase
  namespace: the-namespace
spec:
  instanceRef:
    name: the-primary
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: testing-the-primary
  namespace: the-namespace
spec:
  databaseVersion: POSTGRES_10
  region: europe-west1
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: testing-the-replica
  namespace: the-namespace
spec:
  databaseVersion: POSTGRES_10
  masterInstanceRef:
    name: the-primary
  region: europe-west1
```

**Kustomize version**

```{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T05:35:40+01:00 GoOs:darwin GoArch:amd64}```

**Platform**

macOS
