### ISSUE TITLE
vars not being populated properly in deployment.yaml but are populated in configmap

### ISSUE THREAD

**Issue by y00j** [kubernetes-sigs/kustomize#3138]
**Describe the bug**
vars are not being replaced properly when defined in configmapgenerator literal field

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: var1
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configmap
      namespace: default
    fieldref:
      fieldpath: data.var1
  - name: var2
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configmap
      namespace: default
    fieldref:
      fieldpath: data.var2
configMapGenerator:
  - name: configmap
    literals:
     - var2= bar
      - var1=  foo-$(var2)
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - config.yaml

```
config.yaml

```
varReference:
- path: data
  kind: ConfigMap
  path: spec/template/spec/volumes/secret/secretName
- kind: Deployment
  path: spec/template/spec/volumes/secret/items/key
- kind: Deployment
```

deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some_app
  labels:
    app: some_app
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: some_app
  template:
    metadata:
      labels:
        app: some_app
    spec:
      containers:
        - name: some_app
          image: image_url
          imagePullPolicy: Always
          env:
          volumeMounts:
            - name: backup-secret
              mountPath: /secrets/backup-secret
      volumes:
        - name: backup-secret
          secret:
            secretName: $(var1)
            items:
              - key: $(var1)
                path: backup.credentials

```
...

**Expected output**
deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some_app
  labels:
    app: some_app
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: some_app
  template:
    metadata:
      labels:
        app: some_app
    spec:
      containers:
        - name: some_app
          image: image_url
          imagePullPolicy: Always
          env:
          volumeMounts:
            - name: backup-secret
              mountPath: /secrets/backup-secret
      volumes:
        - name: backup-secret
          secret:
            secretName: foo-bar
            items:
              - key: foo-bar
                path: backup.credentials

```

**Actual output**
deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some_app
  labels:
    app: some_app
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: some_app
  template:
    metadata:
      labels:
        app: some_app
    spec:
      containers:
        - name: some_app
          image: image_url
          imagePullPolicy: Always
          env:
          volumeMounts:
            - name: backup-secret
              mountPath: /secrets/backup-secret
      volumes:
        - name: backup-secret
          secret:
            secretName: $(var1)
            items:
              - key: $(var1)
                path: backup.credentials
```

**Platform**
Ubuntu 20.04.1 LTS

**Additional context**
var1 in the config map is being replaced with foo-bar

**Comment by dan-slinky-ckpd** [comment]
Regarding the variables in your deployment not being populated, your example `config.yaml` as given is incorrectly structured.

Regarding populating a varaible inside a variable, I don't think that'll work. You would be better concatenating them in your `deployment.yaml`.

Based on your examples above, like this:

config.yaml

```
varReference:
- path: spec/template/spec/volumes/secret/secretName
  kind: Deployment
- path: spec/template/spec/volumes/secret/items/key
  kind: Deployment
```

deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some_app
  labels:
    app: some_app
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: some_app
  template:
    metadata:
      labels:
        app: some_app
    spec:
      containers:
        - name: some_app
          image: image_url
          imagePullPolicy: Always
          env:
          volumeMounts:
            - name: backup-secret
              mountPath: /secrets/backup-secret
      volumes:
        - name: backup-secret
          secret:
            secretName: $(var1)-$(var2)
            items:
              - key: $(var1)-$(var2)
                path: backup.credentials
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
vars:
  - name: var1
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configmap
      namespace: default
    fieldref:
      fieldpath: data.var1
  - name: var2
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: configmap
      namespace: default
    fieldref:
      fieldpath: data.var2
configMapGenerator:
  - name: configmap
    literals:
     - var2=bar
     - var1=foo
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - config.yaml
```

**Comment by Shell32-Natsu** [comment]
@dan-slinky-ckpd Thanks for the comment.

@y00j In your example there is a dependency cycle. `configmap` =>`var2`=>`configmap`. That won't work.

**Comment by y00j** [comment]
the thing is that I want to be pull in a configmapgenerator downstream so that my var2 can be constructed differentl based on the environment

for example one downstream configmap might be:
```
configMapGenerator:
  - name: configmap
    behavior: merge
    literals:
      - var2=$(var1)-foo

```
and another is: 
```
configMapGenerator:
  - name: configmap
    behavior: merge
    literals:
      - var2=foo-$(var1)
```

and that way I only need to pull in var2 in my deployment.yaml
