### ISSUE TITLE
Declarative function storage mounts are ignored

### ISSUE THREAD

**Issue by ashlineldridge** [kubernetes-sigs/kustomize#3141]
**Describe the bug**

When storage mounts are specified to a declarative function definition they are ignored. It looks like [this code](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/runfn/runfn.go#L433) has been written to cater for command line `--mount` arguments, which get stored in the `RunFns.StorageMounts` slice, but declarative mounts which are stored in `spec.Container.Network.StorageMounts` are ignored.

**Files that can reproduce the issue**

In a new directory create the following files:

```yaml
# kpt.yaml

apiVersion: kpt.example.com/v1alpha1
kind: FunctionConfig
metadata:
  name: example-function
  annotations:
    config.kubernetes.io/function: |
      container:
        image: example:latest
        mounts:
        - type: bind
          src: .
          dst: /src
spec: {}
```

```dockerfile
# Dockerfile

FROM bash:latest
CMD ls /src >&2
```

First, build the function image:

```
docker build -t example:latest .
```

Then, run the Kpt function:

```bash
> kpt fn run .

ls: /src: No such file or directory
error: exit status 1
```

But if a command line mount is specified the function executes successfully:

```bash
> kpt fn run --mount type=bind,src="$(pwd)",dst=/src .

Dockerfile
kpt.yaml
```

**Expected Output**

It should be possible to configure storage mounts for kyaml functions declaratively.
