### ISSUE TITLE
[Question] Namespace conflict between components

### ISSUE THREAD

**Issue by davidknezic** [kubernetes-sigs/kustomize#3142]
Love the idea of components in Kustomize, so I started adapting our many definitions to the structure outlined in the [Kustomize componentes guide](https://kubernetes-sigs.github.io/kustomize/guides/components/).

Each of our components usually comes with a namespace definition and a `namespace: foo` declaration in its `kustomization.yaml`. This is especially useful in operator components with remote resource files, for which we want to override the default namespace.

Unfortunately, that setup leads to namespace conflicts. You can find a reproduction of my setup below. A `kustomize build overlays/local` leads to the following error:

```
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/Users/davidknezic/repos/github.com/davidknezic/kustomize-ns-per-component/components/db': namespace transformation produces ID conflict: [{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"name\":\"db\"}}{nsfx:false,beh:unspecified} {\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"name\":\"db\"}}{nsfx:false,beh:unspecified}]"
```

<details>
  <summary><code>components/operator/kustomization.yaml</code></summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: operator

resources:
- namespace.yaml
- https://k8s.io/examples/application/deployment.yaml
```

</details>

<details>
  <summary><code>components/operator/namespace.yaml</code></summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: operator
```

</details>

<details>
  <summary><code>components/db/kustomization.yaml</code></summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: db

resources:
- namespace.yaml
- deployment.yaml
```

</details>

<details>
  <summary><code>components/db/namespace.yaml</code></summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: db
```

</details>

<details>
  <summary><code>components/db/deployment.yaml</code></summary>

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: hello-world
```

</details>

<details>
  <summary><code>overlays/local/kustomization.yaml</code></summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../components/operator
- ../../components/db
```

</details>

Is it possible that components aren't as isolated from each other as I thought or is what I'm seeing unexpected behaviour?
