### ISSUE TITLE
Kustomize 3.8.5 orders overlayed environment variable differently than 3.7.0

### ISSUE THREAD

**Issue by maeb** [kubernetes-sigs/kustomize#3157]
There is a difference in the ordering of environment variables between 3.7.0 and 3.8.5. Because variable substitution in kubernetes depends on the depended variable being defined before using it, this can lead to unresolved variables as shown in the example.

Not sure if this a breaking change and working-as-intended.

Example:

The value of `DB_HOST` is expected to be substituted with the host IP in the overlayed kustomization but because of variable ordering it ends up being literally `$(NODE_NAME)`.
```
$ tree
├── base
│   ├── deployment.yaml
│   └── kustomization.yaml
└── overlay
    ├── deployment-patch.yaml
    └── kustomization.yaml

```

base/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
```
base/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speak-with-db-proxy
  labels:
    app.kubernetes.io/name: speak-with-db-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: speak-with-db-proxy
  template:
    spec:
      containers:
        - name: speak-with-db-proxy
          image: database-exporter
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: "database-proxy"

```
overlay/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment-patch.yaml
```
overlay/deployment-patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speak-with-db-proxy
spec:
  template:
    spec:
      containers:
        - name: speak-with-db-proxy
          env:
            - name: DB_HOST
              value: $(NODE_NAME)

```

**Expected output**
```
$ kustomize-3.7.0 version
{Version:kustomize/v3.7.0 GitCommit:42d1f7b792a80af34828ec4c89af99e1043351a7 BuildDate:2020-07-04T19:15:46Z GoOs:linux GoArch:amd64}

$ kustomize-3.7.0 build
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: speak-with-db-proxy
  name: speak-with-db-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: speak-with-db-proxy
  template:
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DB_HOST
          value: $(NODE_NAME)
        image: database-exporter
        name: speak-with-db-proxy
```

**Actual output**
```

$ kustomize version
{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:linux GoArch:amd64}

$ kustomize build
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: speak-with-db-proxy
  name: speak-with-db-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: speak-with-db-proxy
  template:
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: $(NODE_NAME)
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: database-exporter
        name: speak-with-db-proxy
```

**Kustomize version**

`{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:linux GoArch:amd64}`

**Platform**

Linux

**Comment by Shell32-Natsu** [comment]
Related with #2907 and #3048 

We changed the internal implementation of patch strategic merge to kyaml. In #2907 the behavior is changed from prepending to appending but in this issue the behavior is from appending to appending in v3.8.0 and then changed to prepending in #3048.

What we can get from it is the old implementation doesn't have a consistent behavior about merging order. Sometimes it prepends and sometimes it appends. However kyaml implementation does have a definite prepending/appending behavior. Currently we choose to prepend in patch strategic merge. So the behavior in your example is intended.

**Comment by ephesused** [comment]
@Shell32-Natsu, I'm interested in a detail on the intended behavior change. Let me know if I should open a separate ticket for this question.

I'm seeing cases with v3.7.0 where a merge might not alter the order at all; it alters the element in place. For v3.8+, the merge always alters the array order. Based on the above discussion, I'm assuming the change is expected - but I'd like to confirm.

*Example scenario*

**kustomization.yaml**
```yaml
resources:
  - resources.yaml

transformers:
  - transformers.yaml
```

**resources.yaml**
```yaml
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-deployment
  template:
    metadata:
      name: test-deployment
    spec:
      containers:
      - image: test-image
        name: test-image
      initContainers:
      - image: a
        name: a
      - image: b
        name: b
      - image: c
        name: c
```

**transformers.yaml**
```yaml
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: patch-one
patch: |-
  kind: Deployment
  metadata:
    name: wildcard
  spec:
    template:
      spec:
        initContainers:
        - name: b
          image: b
          env:
          - name: ENV_VAR
            value: value
target:
  kind: Deployment
```

**v3.7.0 build output**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-deployment
  template:
    metadata:
      name: test-deployment
    spec:
      containers:
      - image: test-image
        name: test-image
      initContainers:
      - image: a
        name: a
      - env:
        - name: ENV_VAR
          value: value
        image: b
        name: b
      - image: c
        name: c
```

**v3.8.5 build output*
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-deployment
  template:
    metadata:
      name: test-deployment
    spec:
      containers:
      - image: test-image
        name: test-image
      initContainers:
      - env:
        - name: ENV_VAR
          value: value
        image: b
        name: b
      - image: a
        name: a
      - image: c
        name: c
```
