### ISSUE TITLE
[Question] Single-command workflow to build with container functions

### ISSUE THREAD

**Issue by msk-** [kubernetes-sigs/kustomize#3162]
My objective is to supply my users with a single command to execute the build, including building and running requisite container functions, rather than requiring them to manually build container function images as part of their workflow.

I note that container image functions can be used as transformers e.g. in the test here: https://github.com/kubernetes-sigs/kustomize/blob/981959ffcfce7ade3071d7a8b9e8dae2310fb8df/api/krusty/fnplugin_test.go#L344-L406. This falls short because the user must manually build the container image before running `kustomize build`.

I also note that `kustomize fn run` will build and run a local container function, but I haven't seen any mechanism to build functions and execute `kustomize build` functionality in a single command.

I don't see any way to use e.g. the following (note the local container path on the last line) as a transformer:
```
apiVersion: examples.config.kubernetes.io/v1beta1
kind: Validator
metadata:
  name: valid
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: /path/to/local/image/Dockerfile
```

If achieving my objective as stated above is not possible, but is desirable for the project, I would consider creating a PR for said functionality. In this case, a short comment about how and perhaps a link to the file in which to begin would probably be appreciated. Additionally, if #3095 is likely to be worked on soon, I expect that would obviate this request.

Thanks.
