### ISSUE TITLE
Enhancement: Literal vars

### ISSUE THREAD

**Issue by ssboisen** [kubernetes-sigs/kustomize#318]
Sometimes I have vars that doesn't necessarily make sense to put into a configmap. Currently I use a configMapGenerator with literal values and then refer to that from the vars section of kustomization.yaml. However that is the only reason I'm creating the configmap and thus being able to do the following would be nice.

```
vars:
  - name: MY_VAR
    literal: "my var value"
```

**Comment by Liujingfang1** [comment]
In this case, it's better to use JSON patch once it's available #169

**Comment by ssboisen** [comment]
that sounds great, looking forward to a JSON patch example :)

thanks!

**Comment by saturnism** [comment]
quick que - how does json patch solve the literal var problem?

**Comment by jonathanunderwood** [comment]
A JSON patch doesnt solve this use case. Can we reopen this?

**Comment by jkubrynski** [comment]
+1 for reopening this issue. Json patch doesn't help here at all

**Comment by b2cbre** [comment]
@Liujingfang1 how does the JSON patch feature address setting literal variables without going through hoops like @ssboisen stated in his opening post?

**Comment by dirien** [comment]
Hi,

i would like express the need vor having vars with literall. Especially, when we want to use the vars in the data value of a configmap. 

At the moment i use varReference to expand vars in the data value of a configMap.

Is there a chance to address this request?

**Comment by micke** [comment]
I would also like to see this being reopened. I've been using a configmap literal as a workaround but it adds a lot of unnecessary complexity...

**Comment by tkellen** [comment]
Add a another request to the pile. I am doing the same seemingly contorted dance of generating a configmap that will never be used so I can reference values in it. If a PR would be considered I would be happy to implement this.

**Comment by cabrinha** [comment]
It seems that defining environment variables for containers, with different values per environment would be one of the first problems solved with a templating tool.

Somehow, this is still a very confusing topic with almost no documentation or usage examples.

What is the _right way_ to have environment variables configured in different environments/overlays using Kustomize?

**Comment by tkellen** [comment]
@cabrinha there is no right way, this is considered an antipattern within kustomize. here is a relevant section in the documentation:
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables

The basic concept is that within a given manifest (that is, the output of `kustomize build`), you can mix and match values between the resources in a structured way (see [vars](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#vars). This prevents kustomize from devolving into a general purpose programming language like every other templating solution out there.

If this issue tracker is any evidence, the way people are getting per-environment values into kustomize is by generating a configmap or crd-type file with the "global" variables for a given environment and then using references to it throughout the rest of their resources. This works wonderfully but the whole process could be greatly simplified by simply allowing literal values to be specified in a file and version controlled.

/cc @jbrette

**Comment by jonathanunderwood** [comment]
@tkellen that's a great summary of the situation, nicely put.

**Comment by jbrette** [comment]
@ssboisen @jonathanunderwood @tkellen @ian-howell @cabrinha Another occurrence where I think that this [Automatic Creation of 'vars:' and 'varReferences:' sections](https://github.com/kubernetes-sigs/kustomize/pull/1217)

Have a look at: [issue 0318](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0318) but mainly at [issue 0318 b](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0318_b).

In 0318_b we almost doing exactly what you are proposing. Simply instead of putting that in the kustomization.yaml we add that to values.yaml.  We can then using strategicMergePatch, jsonPatch...on that values.yaml. Currently kustomize needs a special transformer to filter the Values resource from the output, but it could be builtin. (The same we don't render the kustomization.yaml)

**Comment by monopole** [comment]
@tkellen Thanks for the summary. As you've alluded, there's no point to letting kustomize become  yet another templating system or domain-specific language.   Plenty of choices there already.

We want to see if its possible to maintain the base YAML in such a way that it's entirely functional - i.e. you can apply it to a cluster and it works.  Any mutation mechanism that requires one to place dollar variables in the base breaks this, as it converts the base into a template that cannot be used without processing.  Further, dollar variables open the door to [unstructured edits](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#unstructured-edits), which breaks many wonderful things in a git rebase workflow.  Baby tossed with bath-water.

What about something like
```
replacements:
- value: someValue
  targets:
  -  gvk: Deployment
     path: some/path
  -  gvk: Deployment
     path: some/other/path
```

The value of `someValue` could be a literal (e.g. `8080`) or a reflection style address to some other resource path in scope for the kustomization.   This is just another form of patching.

aside:  we know we _already_ allow dollar vars in the base - but we're looking to back away from that feature rather than make it more sophisticated for reasons already mentioned.

**Comment by tkellen** [comment]
Thanks for re-opening this @monopole (also thanks to you and anyone else involved in illuminating this method of managing config, I'm a complete convert even with the rough edges!)

I'm not 100% sure I'm following what you've suggested here, but I think I can share succinctly a config format that would solve every use-case I can think of and eliminate the usage of dollar variables in any context other than inside a `kustomization.yml`.

```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -$(vars.name)
commonLabels:
  app: $(resources.base.vars.type)-$(vars.name)
images:
  - name: container
    newName: $(resources.base.vars.env.registry)/$(commonLabels.app)
    newTag: $(vars.version)
resources:
- name: base
  path: ../../shared/kubernetes/service
patches:
  - target: extensions/v1beta1/Ingress/service-poller
    patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: $(branch)poller.$(resources.base.vars.env.domain)
  - target: apps/v1/Deployment/service-poller
    patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/0
      value:
          name: APP_PGHOST
          value: $(resources.base.env.rds_host)
vars:
  name: poller
  branch:
    path: branch
    type: text/plain
    defaultValue: master
  version:
    path: version
    type: text/plain
    defaultValue: $(vars.branch)
```

Below, I've enumerated what the external files referenced above would contain:

**../../shared/kubernetes/service/kustomization.yml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - manifests/deployment.yml
 - manifests/service.yml
 - manifests/ingress.yml
vars:
  type: service
  env:
    path: ../cluster/dev/env.yml
    type: text/yaml
```

**../cluster/dev/env.yml**
```yaml
domain: dev.domain.com
rds_host: demo-dev-ci.ct5hetunyyge.us-east-1.rds.amazonaws.com
registry: 925201748409.dkr.ecr.us-east-1.amazonaws.com/demo
```

**branch** (generated by CI, only present during feature branch deployments to an isolated namespace):
```
feature-123
```

**version** (generated by CI, checked into repo):
```
b85e67a06c5e332271e36b29c45afc000cf8248d
```

This, in conjunction with @jbrette's autovar work for mixing and matching values between resources without having to specify them would be amazing. Again, in this proposal it would not be possible to use dollar vars directly within the source k8s yaml files.

What do you think? I wish I had the time to implement this!
