### ISSUE TITLE
Missing selectors on PersistentVolumeClaim

### ISSUE THREAD

**Issue by Sabatino78** [kubernetes-sigs/kustomize#3181]
My kustomization file:
```
#kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prefix-

commonLabels:
  someName: someValue
  owner: alice
  app: bingo

resources:
- storage.yaml
```
My storage.yaml
```
#storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debug-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
```
The official documentation tells:
commonLabels: Add labels and selectors to add all resources.

I expected to find all commonLabels as labels and selector on all object, but in my case the PersistentVolumeClaim does not have any selector.
The generated output:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bingo
    owner: alice
    someName: someValue
  name: prefix-debug-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
```
My expected output:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bingo
    owner: alice
    someName: someValue
  name: prefix-debug-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  selector:
    app: bingo
    owner: alice
    someName: someValue

```
i'm using lustomize on windows platform and i got it as binary, the output of the version command is:
{Version:kustomize/v3.8.6 GitCommit:c1747439cd8bc956028ad483cdb30d9273c18b24 BuildDate:2020-10-29T23:07:50Z GoOs:windows GoArch:amd64}
