### ISSUE TITLE
[Question] How to refer a name attribute from another resource?

### ISSUE THREAD

**Issue by suryak** [kubernetes-sigs/kustomize#3184]
There are two resources say **Group** and **Account**. 
```
apiVersion: test
kind: Group
  name: groupName
```

```
apiVersion: test
kind: Account
spec:
  groupRef:
    kind: Group
    name: groupName ( -> needs to be refer to the group's name)
```

There are **namePrefix** and **nameSuffix** transformers which are used for generating names of resources, I would like to get the name of the Group from the Group Resource referenced in the Account Resource. Is there anyway I can achieve this?
