### ISSUE TITLE
Json Schema does not match documentation

### ISSUE THREAD

**Issue by ChaosGramer** [kubernetes-sigs/kustomize#3190]
**Describe the bug**

The schema uploaded [here](http://json.schemastore.org/kustomization) does not match the described options in the documentation available here: [patchesjson6902 Documentation](https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/patchesjson6902/)
Example from doc:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: my-deployment
  patch: |-
    - op: add
      path: /some/new/path
      value: value
    - op: replace
      path: /some/existing/path
      value: "new value"
```

The schema available is lacking this property in the description. 
```json
"PatchJson6902": {
      "required": [
        "path",
        "target"
      ],
      "properties": {
        "path": {
          "description": "relative file path for a json patch file inside a kustomization",
          "type": "string"
        },
        "target": {
          "description": "Refers to a Kubernetes object that the json patch will be applied to. It must refer to a Kubernetes resource under the purview of this kustomization",
          "$ref": "#/definitions/PatchTarget"
        }
      },
      "additionalProperties": false,
      "type": "object"
    }
```

**Files that can reproduce the issue**
Example:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: my-deployment
  patch: |-
    - op: add
      path: /some/new/path
      value: value
    - op: replace
      path: /some/existing/path
      value: "new value"
```

**Expected output**
Schema should either contain the property or the value should be removed from the documentation. 

**Actual output**

Output in VS Code: 
![image](https://user-images.githubusercontent.com/8437563/98365758-28829700-2033-11eb-8ace-6c737d2e9b04.png)

**Kustomize version**

```
λ  kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
```

**Platform**

Windows
