### ISSUE TITLE
Mangled manifests with env with valueFrom:fieldRef fieldPath

### ISSUE THREAD

**Issue by epcim** [kubernetes-sigs/kustomize#3195]
**Describe the bug**

some broken manifests on output, in conjunction with using secret generator w/without hashes enabled , I am using gogetter + custom inflator similar to what helm one does, except this one only render go tpl.

output from inflator command has no issues, so looks good

custom inflator cmd looks like:
```
command: source $KUSTOMIZE_HOME/functions.sh && inflateGotpl values.yaml | tee $KUSTOMIZE_WORKDIR/.generated.yaml
```
and the below compared output is from .generated.yaml and previous .generated.yaml.HEAD

**With configuration**

LEFT: With hashes
RIGHT: Without hashes enabled

**Got output**

![image](https://user-images.githubusercontent.com/1211552/98541181-4f3d0980-228f-11eb-8a21-a8f350e9be34.png)

![image](https://user-images.githubusercontent.com/1211552/98541240-6ed43200-228f-11eb-8f7f-b1d57fb951ca.png)

Interesting is that it got `kubectl apply -f` without any failure as:

```
    sidecars:
    - env:
      - name: serviceNames
        value: '{{inputs.parameters.certFQDN}}'
      image: docker.io/acmeio/wingman:latest
      imagePullPolicy: Always
      name: wingman
      volumeMounts:
      - mountPath: /acme/secrets/identity
        name: certs-volume
      - mountPath: /acme/secrets/wingman
        name: signer-certs
        readOnly: true
```

**Expected**

generator/secret is fully ok as expected.

On the 2nd screnshot above,  where " busybox, name: fail:" - that is end of some fully rendered manifest

Then, there is part higlighted by diff. In both cases wrong. As inflated output looks like:

```
    sidecars:
      - name: wingman
        image: docker.io/acmeio/wingman:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /acme/secrets/identity
          name: certs-volume
        - mountPath: /acme/secrets/wingman
          name: signer-certs
          readOnly: true
        env:
        - name: serviceNames
          value: "{{inputs.parameters.certFQDN}}"
        - name: STDLIB_FLUENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_LABELS_APP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        - name: K8S_CONTAINER_NAME
          value: wingman

```

**Kustomize version**

```
{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T17:31:52+01:00 GoOs:darwin GoArch:amd64}

{Version:kustomize/v3.8.6 GitCommit:c1747439cd8bc956028ad483cdb30d9273c18b24 BuildDate:2020-10-31T17:15:40+00:00 GoOs:darwin GoArch:amd64}
```

**Platform**

macOS

**Additional context**

ref: https://github.com/kubernetes-sigs/kustomize/issues/1529
