### ISSUE TITLE
`patchesStrategicMerge` seems to make problems with `PersistentVolumeClaim`s

### ISSUE THREAD

**Issue by iirekm** [kubernetes-sigs/kustomize#3210]
It works for other kinds of objects, but not for PVCs:

```yaml
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongo-pv-claim0
    spec:
      resources:
        requests:
          storage: 1Gi
```

Output:
```
 lstat /.../apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim0
spec:
  resources:
    requests:
      storage: 1Gi: no such file or directory
```

It treats everything as file name!
