### ISSUE TITLE
[Question] Is a var required when names are ambiguous?

### ISSUE THREAD

**Issue by michaelurban** [kubernetes-sigs/kustomize#3228]
I'm using the same component in two resources but need to refer to hashed Secret and ConfigMap name from both resources in my project. Do I need to use a var to get the correct Secret/ConfigMap name + hash if the name reference is ambiguous or am I missing something?

Example:

I've tried to boil my issue down to a bare minimum. xql-zero & xql-one inherit from xql, app references xql-zero and xql-one

A rough Helm Chart equivalent would be:

```
apiVersion: "v2"
description: Helm Chart for "app"
name: app
version: 0.0.1
appVersion: "0.0.1-initial"

dependencies:
- name: xql
  version: 0.0.1
  alias: xql-zero
- name: xql
  version: 0.0.1
  alias: xql-one
```

Ex:

Note: `XQL_ONE_PASSWORD` and `XQL_ZERO_PASSWORD`, which are not referenced using vars, have a keyref name of `xql-secret` while `XQL_ZERO_ARG` and `XQL_ONE_ARG`, which use vars, have hashed names: `project-xql-zero-xql-secret-6khmtc56hm`

`XQL_ONE_ARG` (with var):
```
- name: XQL_ONE_ARG
  valueFrom:
    secretKeyRef:
      name: $(PROJECT_XQL_ONE_SECRET_NAME) # Defined below in "INPUT"
      key: arg
```

`XQL_ONE_PASSWORD` (without var):
```
- name: XQL_ONE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: xql-secret
      key: password
```

OUTPUT:
```
Error: obj '{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": "project-app"},
  "spec": {"template": {"spec": {"containers": [{"env": [{"name": "XQL_ZERO_ARG",
                "valueFrom": {"secretKeyRef": {"key": "arg", "name": "$(PROJECT_XQL_ZERO_SECRET_NAME)"}}},
              {"name": "XQL_ZERO_PASSWORD", "valueFrom": {"secretKeyRef": {"key": "password",
                    "name": "xql-secret"}}}, {"name": "XQL_ONE_ARG", "valueFrom": {
                  "secretKeyRef": {"key": "arg", "name": "$(PROJECT_XQL_ONE_SECRET_NAME)"}}},
              {"name": "XQL_ONE_PASSWORD", "valueFrom": {"secretKeyRef": {"key": "password",
                    "name": "xql-secret"}}}], "image": "example.com/app:latest", "imagePullPolicy": "Always",
            "name": "app"}]}}}}
' at path 'spec/template/spec/containers/env/valueFrom/secretKeyRef/name': visit traversal on path: [env valueFrom secretKeyRef name]: visit traversal on path: [valueFrom secretKeyRef name]: multiple matches for ~G_v1_Secret|~X|xql-secret:
  [~G_v1_Secret|~X|project-xql-zero-xql-secret-6khmtc56hm
 ~G_v1_Secret|~X|project-xql-one-xql-secret-79mhmf5dgt
]

```

INPUT:

[wat.zip](https://github.com/kubernetes-sigs/kustomize/files/5542879/wat.zip)

```
==> ./kustomization.yaml <==
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: project-

resources:
- app
==> ./app/kustomization.yaml <==
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/deployment.yaml
- resources/xql
==> ./app/resources/xql/kustomization.yaml <==
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- xql-zero
- xql-one

configurations:
- ./kustomizeconfig.yaml

==> ./app/resources/xql/kustomizeconfig.yaml <==
varReference:
- path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
==> ./app/resources/xql/xql-one/kustomization.yaml <==
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: xql-one-

resources:
- ../../../../../bases/xql

secretGenerator:
- name: xql-secret
  behavior: merge
  envs:
  - config/xql-one-secret.env

vars:
- name: PROJECT_XQL_ONE_SECRET_NAME
  objref:
    kind: Secret
    name: xql-secret
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name

==> ./app/resources/xql/xql-one/config/xql-one-secret.env <==
arg=1
==> ./app/resources/xql/xql-zero/kustomization.yaml <==
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: xql-zero-

resources:
- ../../../../../bases/xql

secretGenerator:
- name: xql-secret
  behavior: merge
  envs:
  - config/xql-zero-secret.env

vars:
- name: PROJECT_XQL_ZERO_SECRET_NAME
  objref:
    kind: Secret
    name: xql-secret
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name

==> ./app/resources/xql/xql-zero/config/xql-zero-secret.env <==
arg=0
==> ./app/resources/deployment.yaml <==
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        image: example.com/app:latest
        imagePullPolicy: Always
        env:
        - name: XQL_ZERO_ARG
          valueFrom:
            secretKeyRef:
              name: $(PROJECT_XQL_ZERO_SECRET_NAME)
              key: arg
        - name: XQL_ZERO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xql-secret
              key: password
        - name: XQL_ONE_ARG
          valueFrom:
            secretKeyRef:
              name: $(PROJECT_XQL_ONE_SECRET_NAME)
              key: arg
        - name: XQL_ONE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xql-secret
              key: password
```

Referring to the two `xql-secert`-s exclusively using the vars `PROJECT_XQL_ZERO_SECRET_NAME` and `PROJECT_XQL_ONE_SECRET_NAME` produces the expected output, but, again, is hacky.

INPUT WITH VARS:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        image: example.com/app:latest
        imagePullPolicy: Always
        env:
        - name: XQL_ZERO_ARG
          valueFrom:
            secretKeyRef:
              name: $(PROJECT_XQL_ZERO_SECRET_NAME)
              key: arg
        - name: XQL_ZERO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(PROJECT_XQL_ZERO_SECRET_NAME)
              key: password
        - name: XQL_ONE_ARG
          valueFrom:
            secretKeyRef:
              name: $(PROJECT_XQL_ONE_SECRET_NAME)
              key: arg
        - name: XQL_ONE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(PROJECT_XQL_ONE_SECRET_NAME)
              key: password
```

OUTPUT WITH VARS:

```
apiVersion: v1
data:
  arg: MQ==
  password: U1VQRVJfU0VDUkVUX1BBU1NXT1JE
kind: Secret
metadata:
  annotations: {}
  labels: {}
  name: project-xql-one-xql-secret-79mhmf5dgt
type: Opaque
---
apiVersion: v1
data:
  arg: MA==
  password: U1VQRVJfU0VDUkVUX1BBU1NXT1JE
kind: Secret
metadata:
  annotations: {}
  labels: {}
  name: project-xql-zero-xql-secret-6khmtc56hm
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
spec:
  template:
    spec:
      containers:
      - env:
        - name: XQL_ZERO_ARG
          valueFrom:
            secretKeyRef:
              key: arg
              name: project-xql-zero-xql-secret-6khmtc56hm
        - name: XQL_ZERO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: project-xql-zero-xql-secret-6khmtc56hm
        - name: XQL_ONE_ARG
          valueFrom:
            secretKeyRef:
              key: arg
              name: project-xql-one-xql-secret-79mhmf5dgt
        - name: XQL_ONE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: project-xql-one-xql-secret-79mhmf5dgt
        image: example.com/app:latest
        imagePullPolicy: Always
        name: app
```

**Comment by Shell32-Natsu** [comment]
There some points.

1. app should be an overlay of the xql-zero and xql-one. If you put app as a sibling, it cannot refer any name in the xql-zero or xql-one. So it should look like this
```
               project
                  |
                 app
                 /  \
                /    \
          xql-zero  xql-one
                \    /
                 \  /
                 xql
```
2. The name `xql-secret` does have ambiguity in this situation. The overlay, which should be app, doesn't know which one it should use when there are 2 Secrets with exactly same original name and namespace.
3. Var reference is different. It breaks the encapsulation of each kustomization. That's one of the reasons that we want to remove/replace it. #2052.

**Comment by michaelurban** [comment]
Moved app to the "top of the diamond" in my local copy of the example code. As-per your point #2 the ambiguity is still there so the output is identical. 

For #3, vars didn't feel like the right choice, just the only thing that I could think of that worked. Any thoughts on how to accomplish this in an idiomatic way?

**Comment by michaelurban** [comment]
I've updated the example in my original comment.

**Comment by Shell32-Natsu** [comment]
The solution is making the resource IDs different. So

1. Use different original names for the secrets
2. Use different namespaces for secrets.

**Comment by michaelurban** [comment]
In my real project I have a generic thumbor deployment that references a ConfigMap called `thumbor-config` that has several defaults set. I'm patching a few values in `thumbor-config` for each deployed instance, but, it's useful to define and reference the `varnish-conf` ConfigMap in the base kustomization. 

The naming conflicts arise whenever you need to use two instances in the same app. Which, for common services like memcached, varnish, etc, is likely to happen.

I can architect my app to put components in silos just to avoid the name collisions, but, it feels like such a common case ("I need two of a base thing with a few defaults defined") that automatic naming shouldn't get in the way.

**Comment by Shell32-Natsu** [comment]
kustomize uses the same method that k8s api server uses to identify resources, GVK+name+namespace. When there are multiple resources with exactly same original GVK+name+ns existing, technically kustomize has no way to distinguish them.

**Comment by michaelurban** [comment]
Going back to my original example with xql-one and xql-zero and Helm. In Helm you would give the concrete child instances of your base chart aliases so that the user/system can distinguish between the components of each. (e.g. `varnish-configmap` becomes `alias-varnish-configmap`.) 

`namePrefix` appears to do that in kustomize, but, it falls apart when you try to create two instances of a base and need to rely on kustomize automatically adjusting names for you.

By defining a var I'm able to accomplish what I need to accomplish, but, again, it has drawbacks. 

Can something like Helm's chart aliases be implemented to get around this issue?

**Comment by Shell32-Natsu** [comment]
To locate a resource in kustomize in the case that resource name is modified by kustomize, you can use current name or original name. In you example, that means you can use `project-xql-zero-xql-secret-6khmtc56hm` or `xql-secret`. That works like an alias (`project-xql-zero-xql-secret-6khmtc56hm` is the alias of `xql-secret`). What's different is current name depends on which overlay you are in.

**Comment by michaelurban** [comment]
Yes. That's my understanding too. The issues is the "depends on which overlay you are in" bit. 

So, going my original example, there is no absolutely no way to differentiate between the two `xql-secret`-s in the app overlay without using a var to break encapsulation and get the hashed name `project-xql-zero-xql-secret-6khmtc56hm`. [0] 

**Which brings me back to my original question**: Is there a way to get the hashed name of a ConfigMap/Secret without breaking encapsulation, using a var, and having to add entries like the following to `kustomizeconfig.yaml` for any place I'd use those vars:
```
varReference:
- kind: Deployment
  path: spec/template/spec/containers[]/envFrom[]/configMapRef/name

- kind: StatefulSet
  path: spec/template/spec/containers[]/envFrom[]/configMapRef/name
```
All I'm looking for is a way to get the prefixed, suffixed, and hashed Secret/ConfigMap names so I can refer to both secrets in the example.

[0] It would have been better for me to have used a ConfigMap in the example, because there's an actual case for a common ConfigMap that isn't defined in an overly. This was just a quick example of the mechanisms.
