### ISSUE TITLE
Var replacement does not work in volumes in DaemonSet

### ISSUE THREAD

**Issue by moficodes** [kubernetes-sigs/kustomize#3241]
**Describe the bug**
Trying to replace the variable `$(some-var)` in the following DaemonSet yaml

```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: s3
  namespace: default
spec:
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "default"
        app: s3
    spec:
      serviceAccountName: s3
      containers:
        - name: driver
          image: "image/tag:v1.2.0"
          imagePullPolicy: Always
          args:
            - --some-arg=$(some-var)/more/stuff
        - name: csi-s3
          image: "iamge/tag:archive-amd64"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: $(some-var)/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - hostPath:
            path: $(some-var)/plugins
            type: DirectoryOrCreate
          name: socket-dir
```

Kustomize Var reference unable to replace variables in `DaemonSet.spec.template.spec.volumes[].hostPath`. 

Issue is very similar to [#1540](https://github.com/kubernetes-sigs/kustomize/issues/1540) The solution suggested there was to add 
```yaml
varReference:
- path: spec/template/spec/volumes[]/hostPath
  kind: DaemonSet
``` 

That does not work. I also tried `spec/template/spec/volumes/hostPath` `spec/template/spec/volumes[]/hostPath/path`

**Files that can reproduce the issue**
https://github.com/moficodes/issue-examples/tree/master/kustomize-volume-var-reference

**Expected output**
```yaml
apiVersion: v1
data:
  some-var: new-value-for-var
kind: ConfigMap
metadata:
  labels:
    app: dlf
  name: params
  namespace: dlf
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dlf
  name: s3
  namespace: dlf
spec:
  selector:
    matchLabels:
      app: dlf
  template:
    metadata:
      labels:
        app: dlf
        app.kubernetes.io/name: default
    spec:
      containers:
      - args:
        - --some-arg=new-value-for-var/more/stuff
        image: image/tag:v1.2.0
        imagePullPolicy: Always
        name: driver
      - image: iamge/tag:archive-amd64
        imagePullPolicy: Always
        name: csi-s3
        volumeMounts:
        - mountPath: new-value-for-var/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
      serviceAccountName: s3
      volumes:
      - hostPath:
          path: new-value-for-var/plugins
          type: DirectoryOrCreate
        name: socket-dir
```

**Actual output**
```yaml
apiVersion: v1
data:
  some-var: new-value-for-var
kind: ConfigMap
metadata:
  labels:
    app: dlf
  name: params
  namespace: dlf
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dlf
  name: s3
  namespace: dlf
spec:
  selector:
    matchLabels:
      app: dlf
  template:
    metadata:
      labels:
        app: dlf
        app.kubernetes.io/name: default
    spec:
      containers:
      - args:
        - --some-arg=new-value-for-var/more/stuff
        image: image/tag:v1.2.0
        imagePullPolicy: Always
        name: driver
      - image: iamge/tag:archive-amd64
        imagePullPolicy: Always
        name: csi-s3
        volumeMounts:
        - mountPath: new-value-for-var/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
      serviceAccountName: s3
      volumes:
      - hostPath:
          path: $(some-var)/plugins
          type: DirectoryOrCreate
        name: socket-dir
```

**Kustomize version**
Tested on kustomize 3.2.1 and 3.8.7

**Platform**
macOS and Linux

**Additional context**
