### ISSUE TITLE
Allow certain commonLabels to not be part of selector.matchLabels

### ISSUE THREAD

**Issue by sylr** [kubernetes-sigs/kustomize#3249]
**Is your feature request related to a problem? Please describe.**

Changing commonLabels of an already deployed resources cause the following errors:

```
The Deployment "external-dns" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"external-dns", "instance":"public"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Describe the solution you'd like**

A mean to mark a set of commonLabels to be excluded from `selector.matchLabels`. e.g.:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../_base/karma
commonLabels:
  app: karma
  instance: prod
  ~maintainer: team-blahblah # Would set the  maintainer label everywhere expect in selector.matchLabels
```

**Describe alternatives you've considered**

**Additional context**
