### ISSUE TITLE
Replace identifier tuple of name/group/kind with a hash

### ISSUE THREAD

**Issue by ricochet** [kubernetes-sigs/kustomize#3264]
We are unable to move off of vars for names because of how names are used to identify resources within kustomize. If this changes to hash unique to each resource for example, we can transition to setters.

If there are specific pointers for how this could/should be implemented, please share. @mikeyrcamp or I are interested in getting started on a PR for this soon.

**Comment by Shell32-Natsu** [comment]
Can you provide an example pf what are you trying to do?

**Comment by ricochet** [comment]
We want to move from vars to setters to avoid being in a deprecation bind. Currently, we use vars to replace names. Because of how resources are identified in kustomize (name of the resource), we are unable to move.

A high-level example of how kustomize bases are being used: https://github.com/kubernetes-sigs/kustomize/issues/2052#issuecomment-577279491

Specifically, it's not being able to use a setter for name:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: $(SERVICE_NAME)
  name: $(SERVICE_NAME)
```
