### ISSUE TITLE
How do I append container arguments?

### ISSUE THREAD

**Issue by KnicKnic** [kubernetes-sigs/kustomize#3265]
## Issue
I have an existing deployment and I want to edit one of the container's arguments and append an item. By default arguments are overwritten, and I do not know how to change defaults.

## Repro steps
kustomization.yaml
```yaml
resources:
- test.yaml

patchesStrategicMerge:
  - test_patch.yaml
```

test_patch.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        args:
          - "--argument-2=efg"
          # - $patch:merge
          # I tried adding $patch:merge, that did not work 
          # I thought it would due to https://github.com/kubernetes-sigs/kustomize/blob/ff927fd11aa81d2600c7aab76212162f773602b2/kyaml/yaml/merge2/list_test.go#L156
```

test.yaml
```yaml
# test.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: test
        args:
          - "--argument-1=abc"
```

## Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - args:
        - --argument-1=abc
        - --argument-2=efg
        image: test
        name: test
```

## Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - args:
        - --argument-2=efg
        image: test
        name: test
```

## Kustomize version

Git version / last commit
commit 052a6b4e967b8cba7f9c12623c9dd53fb16e2f7a (HEAD -> master, origin/master, origin/HEAD)
Merge: a0a89e1a 4add7ecc
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Fri Nov 20 15:07:33 2020 -0800

**Platform**

Linux

**Additional context**
I thought about using json patch. I do not know how to write it to target just one of the containers for argument append if there are multiple containers.

**Comment by natasha41575** [comment]
> I thought about using json patch. I do not know how to write it to target just one of the containers for argument append if there are multiple containers.

To your point in additional context, you can reference different targets in a json patch when there are multiple targets by using indeces, e.g. 

test.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: test
        args:
          - "--argument-1=abc"
      - name: test_1`

test_json_patch.yaml
`[
  {"op": "add", 
   "path": "/spec/template/spec/containers/0/args",
   "value": "--argument-2=efg" },
  {"op": "add",
   "path": "/spec/template/spec/containers/1/args",
   "value": "--argument-1=hij" }
]`

This, however, results in the following output:
`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - args: --argument-2=efg
        image: test
        name: test
      - args: --argument-1=hij
        name: test_1`

Which still has the issue that it overwrites the first container's first argument instead of appending to it. I wonder if this is a bug @Shell32-Natsu @monopole ? Or is this expected behavior?

**Comment by Shell32-Natsu** [comment]
`$patch` directive only works when the merge key for the array is defined in k8s API. `args` doesn't have merge key defined so it always replace.

You can use JSON patch like this
```
# kustomization.yaml
resources:
- test.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --argument-2=efg
  target:
    kind: Deployment
```

Output:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - args:
        - --argument-1=abc
        - --argument-2=efg
        image: test
        name: test
```

**Comment by KnicKnic** [comment]
@Shell32-Natsu 

Okay so I can use a json patch for this trivial example. However this is not great, as it doesn't address when container changes index.

My setup is a bit more complicated and optionally another container is injected into the deployment. When this happens due to https://github.com/kubernetes-sigs/kustomize/issues/2907 a new container is placed in position 0, and the container I want to append args to is now placed at position 1. This prevents json patch from being used generically for this situation.

**Comment by Shell32-Natsu** [comment]
Yes that's not good for complicated situation. But what you want to achieve is not natively supported by kustomize. You can try create your own plugin to do it. https://kubectl.docs.kubernetes.io/guides/extending_kustomize/execpluginguidedexample/

**Comment by KnicKnic** [comment]
@Shell32-Natsu would it make sense to reopen this issue as it cannot be accomplished by kustomize. Or do you think it would not be a goal of kustomize.

**Comment by Shell32-Natsu** [comment]
Sorry we don't have plan to support arbitrary array merge in near future **natively**.

**Comment by wgj** [comment]
> Sorry we don't have plan to support arbitrary array merge in near future natively.

Well, why the heck not? ;) This seems like an obvious usecase for Kustomize; Yaml in, yaml out. Apologies for trivializing the work y'all are doing, but saying no to merging arrays seems like a weird stance to take on a program that is so opinionated on merging yaml.

Additionally, it's discouraging to be told "make a plugin" when they're so alpha that even the link is broken.

**Comment by davinkevin** [comment]
I really like Kustomize and promote it to the community during conferences a lot and I feel this kind of corner case makes the tool harder to understand for newcomers, and not coherent for one with experience. 

As a example, if you want to enable gateway api feature for cert-manager, it would make totally sense to support something like this:

```
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
      spec:
        template:
          spec:
            containers:
              - name: cert-manager-controller
                args:
                  - $patch: merge
                  - --feature-gates=ExperimentalGatewayAPISupport=true
```

Simple, straightforward and easy to read. Instead, we have to use the following one:

```
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=ExperimentalGatewayAPISupport=true
    target:
      group: apps
      version: v1
      kind: Deployment
      name: cert-manager
```

The solution introduce a coupling to the pod order, which is really not good and error prone… 

Thank you for all the work done on kustomize, the product is really good, but I feel this one could be reopen, at least to be find by users when they are looking for this.
