### ISSUE TITLE
[Question] Insert nameSuffix only to specific resource and use var in annotation

### ISSUE THREAD

**Issue by malcolm061990** [kubernetes-sigs/kustomize#3268]
Hi.
```
kustomize version
{Version:kustomize/v3.8.7 GitCommit:ad092cc7a91c07fdf63a2e4b7f13fa588a39af4f BuildDate:2020-11-14T20:06:26+00:00 GoOs:darwin GoArch:amd64}
```

I have several k8s yaml files in one dir that are handled kustomization. One of them is:
```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-INGRESS_APPLICATION_VAL
  namespace: ingress-nginx-INGRESS_APPLICATION_VAL
  labels:
    app.kubernetes.io/name: INGRESS_APPLICATION_VAL
    app.kubernetes.io/part-of: INGRESS_APPLICATION_VAL
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: LOAD_BALANCER_CERT_VAL
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx-INGRESS_APPLICATION_VAL
    app.kubernetes.io/part-of: ingress-nginx-INGRESS_APPLICATION_VAL
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
```

And another k8s yaml in same folder:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-load-balancer
  namespace: PROJECT_NAMESPACE  # other namespace from previous yaml file
  annotations:
    kubernetes.io/ingress.class: INGRESS_APPLICATION_VAL
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600s"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
  - host: EXTERNAL_DOMAIN_NAME_VAL
    http:
      paths:
        - path: /
          backend:
            serviceName: load-balancer
            servicePort: 8080
```

What do I want to do via kustomize?
- replace INGRESS_APPLICATION_VAL to some nameSuffix only in specific yaml (in first example), not in all yamls
- assign LOAD_BALANCER_CERT_VAL, INGRESS_APPLICATION_VAL and EXTERNAL_DOMAIN_NAME_VAL to some var (in second example)

**Comment by Shell32-Natsu** [comment]
Use LabelTransformer and AnnotationTransformer to add labels and annotations.

Use PrefixSuffixTransformer to add suffix to the resource name in first yaml.

Use PatchTransformer to update the values in `spec`.

https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/

**Comment by malcolm061990** [comment]
> Use LabelTransformer and AnnotationTransformer to add labels and annotations.
> 
> Use PrefixSuffixTransformer to add suffix to the resource name in first yaml.
> 
> Use PatchTransformer to update the values in `spec`.
> 
> https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/

Thanks for your answer. 
But I don't understand how can I filter in one kustomize.yaml to what file I want to apply some transformations.

**Comment by Shell32-Natsu** [comment]
Take a look at the [fieldSpecs](https://github.com/kubernetes-sigs/kustomize/tree/master/api/types/fieldspec.go). The selector works on resources, not files.

**Comment by malcolm061990** [comment]
> Take a look at the [fieldSpecs](https://github.com/kubernetes-sigs/kustomize/tree/master/api/types/fieldspec.go). The selector works on resources, not files.

Still don't understand :(
How can I provide explicitly in fieldSpecs to what resource I want to add some custom annotation?
For example, I have one kustomization.yaml file to handle all project yamls:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app1.yaml
- app2.yaml
#- %many-other-yamls%
```
And I want to add specific annotation only to app1.yaml that consists app1 deployment. What changes do I need to do?

**Comment by malcolm061990** [comment]
Solved by using such configuration to add labels only to specific resource:
```yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      namespace: PROJECT_NAMESPACE
      name: action-service
      labels:
        app123: action-service123
```
It adds new label "app123: action-service123" to the "action-service" deployment.
I think it will work for any other field.
