### ISSUE TITLE
Strategic Merge Patch Silently Converts Overriding Value Type to Match Original Type of Value Getting Overriden

### ISSUE THREAD

**Issue by Magnitus-** [kubernetes-sigs/kustomize#3286]
**Files that can reproduce the issue**

patch.yml:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
```

source.yml:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  privateKey:
    algorithm: __UNDEFINED__
    encoding: __UNDEFINED__
    size: __UNDEFINED__
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - source.yml

patchesStrategicMerge:
  - patch.yml
```

In the directory with those files, run: kustomize build .

**Expected output**

Either:
  - Output a type mismatch error (if you want to enforce overriding values type matching the type of the value getting overriden)
  - Or output:

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
```

**Actual output**

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: "4096"
```

**Kustomize version**

3.8.4 and 3.8.7.

The problem was not observable in 3.6.x, it got introduced later.

**Platform**

Linux
