### ISSUE TITLE
cannot unmarshal object into Go struct field Kustomization.secretGenerator

### ISSUE THREAD

**Issue by andy-kwo-any** [kubernetes-sigs/kustomize#3318]
description：

I'm using kustomize, no databases, just a `basic auth` for a traefik with two files in the overlay folder, `Kustomization.yaml` and `middleware-basicauth.yaml`.

The content for kustomization.yaml is the following

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig/ingressroute.yaml
- kustomizeconfig/middleware.yaml

namespace: formationmlfmonde
namePrefix: formationmlfmonde-
commonLabels:
 instance: formationmlfmonde

bases:
- ../../base
resources:
- middleware-basicauth.yaml

patchesStrategicMerge:
- ingressroute-routes.yaml

secretGenerator:
 name: formationmlfmonde-basicauth-secret
 literals:
 - users=mlf:{SHA}<sha_code_here>

vars:
- name: TRAEFIK_MIDDLEWARE_BASICAUTH_NAME
  objref:
    kind: Middleware
    name: formationmlfmonde-basicauth
    apiVersion: traefik.containo.us/v1alpha1
  fieldref:
    fieldpath: metadata.name

```

The content for the `middleware-basicauth.yaml` is the following:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: formationmlfmonde-basicauth
spec:
  basicAuth:
    secret: formationmlfmonde-basicauth-secret

```

I'm not sure why I'm having this error. I guess it is due to the secret generator part but as there is nothing else, I cannot pintpoint where lies the issue.

error info:

`Error: json: cannot unmarshal object into Go struct field Kustomization.secretGenerator of type []types.SecretArgs`

I could not find anything relevant over internet therefore I'm trying to find help here.

Thanks
