### ISSUE TITLE
Merging configmap files with the same file name

### ISSUE THREAD

**Issue by jojijohn** [kubernetes-sigs/kustomize#3319]
How can I merge two config map files (overlay and base) which has the same name? When I try the below sample, the configs from the base config.properties isn't there in the output even though the `configMapGenerator.behavior` is set as `merge`

```
$ kustomize version
{Version:kustomize/v3.8.7 GitCommit:ad092cc7a91c07fdf63a2e4b7f13fa588a39af4f BuildDate:2020-11-12T01:08:43+00:00 GoOs:darwin GoArch:amd64}
```

The base kustomization file
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonAnnotations:
  description: Common ConfigMap
commonLabels:
  owner: sre
  purpose: common-config
configMapGenerator:
 - name: app-config
   files:
     - ../../config.properties
generatorOptions:
  disableNameSuffixHash: false
```

The config.properties file it refers to:
```
foo = bar
foo1 = bar1
```

overlay kustomization file

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: qa
commonLabels:
  env: qa
namePrefix: qa-
nameSuffix: -v1
configMapGenerator:
 - name: app-config
   behavior: merge
   files:
     - ../../../qa/config.properties
```

The config.properties file it refers to:
```
foo = bar-qa
foo2 = bar3
```

And this is the output I am getting . Note the property `foo1` is missing in this output

```
$ kustomize build overlays/qa --load_restrictor=none

apiVersion: v1
data:
  config.properties: |
    foo = bar-qa
    foo2 = bar3
kind: ConfigMap
metadata:
  annotations:
    description: Common ConfigMap
  labels:
    env: qa
    owner: sre
    purpose: common-config
  name: qa-app-config-v1-hkg2h9tt5b
  namespace: qa

```
