### ISSUE TITLE
Missing namePrefix in csi volumes

### ISSUE THREAD

**Issue by transkonduktor** [kubernetes-sigs/kustomize#3320]
**Describe the bug**

Kustomize doesn't add a namePrefix to secretProviderClass property in Deployment manifests (deployment.spec.template.spec.volumes.csi.volumeAttributes.secretProviderClass)

**Files that can reproduce the issue**

files:
```
├── base
│   ├── kustomization.yaml
│   ├── proftpd-deployment.yaml
│   └── proftpd-secretprovider-ssh-key.yaml
└── dev
    └── kustomization.yaml

```
base/kustomization.yaml
```
resources:
- proftpd-deployment.yaml
- proftpd-secretprovider-ssh-key.yaml
```
base/proftpd-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-proftpd-deployment
  labels:
    app: platform-proftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-proftpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: platform-proftpd
    spec:
      volumes:
      - name: proftpd-secret-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: platform-proftpd-ssh-key-secretprovider
      containers:
      - name: sftp-server
        image: proftpd:12
        ports:
        - containerPort: 22
        volumeMounts:
        - name: proftpd-secret-volume
          mountPath: /var/run/secrets/proftpd
          readOnly: true
```

base/proftpd-secretprovider-ssh-key.yaml
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: platform-proftpd-ssh-key-secretprovider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: kvName
    resourceGroup: rgName
    subscriptionId: subId
    objects: |
      array:
        - |
          objectName: secretKey
          objectType: secret
    tenantId: tenantId

```

dev/kustomization.yaml:

```
resources:
- ../base
namePrefix: dev-
images:
- name: proftpd
  newTag: '15'
```

**Expected output**

I expect to have namePrefix added to secretProviderClass property in Deployment manifest, like:
```
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: dev-platform-proftpd-ssh-key-secretprovider
        name: proftpd-secret-volume

```

**Actual output**
./kustomize build .

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platform-proftpd
  name: dev-platform-proftpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-proftpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: platform-proftpd
    spec:
      containers:
      - image: proftpd:15
        name: sftp-server
        ports:
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/run/secrets/proftpd
          name: proftpd-secret-volume
          readOnly: true
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: platform-proftpd-ssh-key-secretprovider
        name: proftpd-secret-volume
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: dev-platform-proftpd-ssh-key-secretprovider
spec:
  parameters:
    keyvaultName: kvName
    objects: |
      array:
        - |
          objectName: secretKey
          objectType: secret
    resourceGroup: rgName
    subscriptionId: subId
    tenantId: tenantId
    usePodIdentity: "true"
  provider: azure

```

**Kustomize version**

```
{Version:kustomize/v3.8.7 GitCommit:ad092cc7a91c07fdf63a2e4b7f13fa588a39af4f BuildDate:2020-11-11T23:14:14Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux
