### ISSUE TITLE
`kustomize edit set image` and `kustomize cfg fmt` write file in different layout

### ISSUE THREAD

**Issue by pinkavaj** [kubernetes-sigs/kustomize#3323]
**Describe the bug**

Each of the commands bellow produces a bit different kustomization.yaml, some keys are reordered. This is unexpected and cause troubles in our code linting (sinc after kustomize edit by some automation the new commited code does not comply with the expected formating previously provided by the `kustomize cfg fmt` and the pipeline fails).

* `kustomize edit set image image-name:image-tag`
* `kustomize cfg fmt kustomization.yaml`

**Files that can reproduce the issue**

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: morgan-accuracy
  files:
  - file.name
images:
- name: image-name
  newTag: image-tag
```

**Expected output**

The diff will be empty.

**Actual output**

Diff betwen the file caused by issuing the commands above

```diff
diff --git a/kustomization.yaml b/kustomization.yaml
index 6f17081..0277157 100644
--- a/kustomization.yaml
+++ b/kustomization.yaml
@@ -1,9 +1,9 @@
 apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization
 configMapGenerator:
-- files:
+- name: morgan-accuracy
+  files:
   - file.name
-  name: morgan-accuracy
 images:
 - name: image-name
   newTag: image-tag
```

**Kustomize version**
**Platform**

<!--{Version:3.8.7 GitCommit:$Format:%H$ BuildDate:2020-11-14T23:34:22Z GoOs:linux GoArch:amd64}
