### ISSUE TITLE
configMapGenerator will not merge another configMapGenerator in resources on 3.9.0

### ISSUE THREAD

**Issue by YujiShen** [kubernetes-sigs/kustomize#3364]
**Describe the bug**

I defined some common env vars inside common.env and other envs will merge their specific env vars into it. I found it works well until I upgrade to 3.9.0, works well on 3.8.8.

**Files that can reproduce the issue**

File tree:
```
├── common
│   ├── common.env
│   └── kustomization.yaml
├── dev
│   ├── dev.env
│   └── kustomization.yaml
```

common/common.env

```
COMMON_ENV=1
```
common/kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: example-env
  behavior: create
  envs:
   - common.env
```

dev/dev.env

```
DEV_ENV=1
```

dev/kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
commonLabels:
  environment: dev
resources:
  - ../common
configMapGenerator:
- name: example-env
  behavior: merge
  literals:
    - LITERALS=1
  envs:
    - dev.env
```

**Expected output**

```
apiVersion: v1
data:
  COMMON_ENV:"1"
  DEV_ENV: "1"
  LITERALS: "1"
kind: ConfigMap
metadata:
  labels:
    environment: dev
  name: example-env-dev-2ghct759tc
```

**Actual output**

```
apiVersion: v1
data:
  DEV_ENV: "1"
  LITERALS: "1"
kind: ConfigMap
metadata:
  labels:
    environment: dev
  name: example-env-dev-2ghct759tc

```

`COMMON_ENV=1` is missing.

**Kustomize version**

3.9.0
**Platform**

macOS
**Additional context**
