### ISSUE TITLE
configMapGenerator behavior merge does not appear to merge values

### ISSUE THREAD

**Issue by greenkiwi** [kubernetes-sigs/kustomize#3365]
**Describe the bug**

We are experiencing a strange behavior where overlays are overwriting all of at config-map rather than merging values.

In our base kustomization we define two values
* `value_base=base`
* `value_override=base`

We then create an overlay with the following config map values
* `value_OVERLAY_OVERRIDE=overlay-1`
* `value_override=overlay-1`

We expect to have these merged into the following config map
* `value_base=base`
* `value_OVERLAY_OVERRIDE=overlay-1`
* `value_override=overlay-1`

However, the resulting config map only has
* `value_OVERLAY_OVERRIDE=overlay-1`
* `value_override=overlay-1`

**Files that can reproduce the issue**

`base/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

configMapGenerator:
  - name: job
    literals:
      - value_base=base
      - value_override=base
```

`base/namespace.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: base
```

`overlay-no-merge/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
```

`overlay-override/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

configMapGenerator:
  - name: job
    behavior: merge
    literals:
      - value_OVERLAY_OVERRIDE=overlay-1
      - value_override=overlay-1
```

**Expected output**

`kustomize build base/kustomization.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: base
---
apiVersion: v1
data:
  value_base: base
  value_override: base
kind: ConfigMap
metadata:
  name: job-k64bgtthfb
```

`kustomize build no-merge/kustomization.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: base
---
apiVersion: v1
data:
  value_base: base
  value_override: base
kind: ConfigMap
metadata:
  name: job-k64bgtthfb
```

`kustomize build overlay-override/kustomization.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: base
---
apiVersion: v1
data:
  value_OVERLAY_OVERRIDE: overlay-1
  value_base: base
  value_override: overlay-1
kind: ConfigMap
metadata:
  name: job-ch9mhcthd7
```

**Actual output**

The actual output is missing the merge of `value_base=base` from `base/kustomization.yaml`

`kustomize build overlay-override/kustomization.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: base
---
apiVersion: v1
data:
  value_OVERLAY_OVERRIDE: overlay-1
  value_override: overlay-1
kind: ConfigMap
metadata:
  name: job-hf5t9g8tt5
```
**Kustomize version**

```
{Version:kustomize/v3.9.0 GitCommit:826b5d9792fb67c4d8f8cd59747698ebf0b22720 BuildDate:2020-12-10T22:29:12+00:00 GoOs:darwin GoArch:amd64}
```

**Platform**

MacOS

**Additional context**

Script that will run and create all the files above.
```
#!/bin/bash -xe

export ROOT_DIR=example
export BASE_DIR=$ROOT_DIR/base
export OVERLAY_OVERRIDE_DIR=$ROOT_DIR/overlay-override
export OVERLAY_NO_MERGE_DIR=$ROOT_DIR/overlay-no-merge

rm -rf $ROOT_DIR

mkdir -p $BASE_DIR
mkdir -p $OVERLAY_OVERRIDE_DIR
mkdir -p $OVERLAY_NO_MERGE_DIR

cat << EOF >> $BASE_DIR/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

configMapGenerator:
  - name: job
    literals:
      - value_base=base
      - value_override=base
EOF

cat << EOF >> $BASE_DIR/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: base
EOF


cat << EOF >> $OVERLAY_OVERRIDE_DIR/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

configMapGenerator:
  - name: job
    behavior: merge
    literals:
      - value_OVERLAY_OVERRIDE=overlay-1
      - value_override=overlay-1
EOF

cat << EOF >> $OVERLAY_NO_MERGE_DIR/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

EOF

tree $ROOT_DIR

kustomize build $BASE_DIR > build_base.yaml
kustomize build $OVERLAY_OVERRIDE_DIR > build_OVERLAY_OVERRIDE.yaml
kustomize build $OVERLAY_NO_MERGE_DIR > build_OVERLAY_NO_MERGE.yaml

```
