### ISSUE TITLE
[Question] Updating service hostnames when using namePrefix

### ISSUE THREAD

**Issue by bubba** [kubernetes-sigs/kustomize#3380]
Say I have a some micro service made up of a deployment and a service:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: acme/foo
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: foo
```

If I have another pod that wants to connect to this service internally, say via an environment variable:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: bar
        image: acme/bar
        env:
        - name: FOO_URL
          value: http://foo
```

If I want to host multiple environments for this setup in the same namespace using labels, then I could use prefixName. Here's an example `prod/kustomization.yaml`:
```yaml
bases:
- ../base
namePrefix: prod-
commonLabels:
  environment: prod
```

Applying this creates the `prod-foo` and `prod-bar` pods, as well as the `prod-foo` service. However `prod-bar` won't be able to connect to `http://foo`: Because it's now exposed under `http://prod-foo`. What is the recommended way of templating this?
