### ISSUE TITLE
secretGenerator type always defaults to Opaque

### ISSUE THREAD

**Issue by overtfuture** [kubernetes-sigs/kustomize#3386]
**Describe the bug**

When using the secretGenerator, type is ignored when building and defaults to Opaque.

**Files that can reproduce the issue**

Example:

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: test
  literals:
    - "example=env"
  type: 'kubernetes.io/dockerconfigjson'
```

**Expected output**

```yaml
apiVersion: v1
data:
  example: ZW52
kind: Secret
metadata:
  name: test-kbtk7dgthm
type: kubernetes.io/dockerconfigjson
```

**Actual output**

```yaml
apiVersion: v1
data:
  example: ZW52
kind: Secret
metadata:
  name: test-kbtk7dgthm
type: Opaque
```

**Kustomize version**

`{Version:kustomize/v3.9.0 GitCommit:826b5d9792fb67c4d8f8cd59747698ebf0b22720 BuildDate:2020-12-10T22:29:12+00:00 GoOs:darwin GoArch:amd64}`

**Platform**

macOS

**Additional context**

Example docs describing the `type` parameter: [reference](https://kubectl.docs.kubernetes.io/references/kustomize/secretgenerator/)
