### ISSUE TITLE
[Question] Why doesn't Kustomize apply strategic merge on my array?

### ISSUE THREAD

**Issue by zizhengwu** [kubernetes-sigs/kustomize#3387]
[This same question is posted to stackoverflow: https://stackoverflow.com/questions/65401905/why-doesnt-kustomize-apply-strategic-merge-on-my-array]

I have 3 files, base.yaml, overlay.yaml, and kustomization.yaml

base.yaml:
```
apiVersion: authentication.gke.io/v2alpha1
kind: ClientConfig
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: default
  namespace: kube-public
spec:
  authentication:
  - name: proxy
    proxy: 127.0.0.1
```

overlay.yaml:
```
apiVersion: authentication.gke.io/v2alpha1
kind: ClientConfig
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: default
  namespace: kube-public
spec:
  authentication:
  - name: oidc
    clientID: asdf
    clientSecret: asdf
    issuerURI: a.google.com
```

kustomization.yaml:
```
resources:
- base.yaml

patchesStrategicMerge:
- overlay.yaml
```

When I do `kustomize build .`, I got actual:

```
apiVersion: authentication.gke.io/v2alpha1
kind: ClientConfig
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: default
  namespace: kube-public
spec:
  authentication:
  - clientID: asdf
    clientSecret: asdf
    issuerURI: a.google.com
    name: oidc
```

While I expect
```
apiVersion: authentication.gke.io/v2alpha1
kind: ClientConfig
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: default
  namespace: kube-public
spec:
  authentication:
  - name: proxy
    proxy: 127.0.0.1
  - clientID: asdf
    clientSecret: asdf
    issuerURI: a.google.com
    name: oidc
```

I wonder why the "proxy" item is replaced by the "oidc" item instead of being merged together.
