### ISSUE TITLE
Kustomize fails to build manifest with config.istio.io/v1alpha2 Instance resource

### ISSUE THREAD

**Issue by dfarr** [kubernetes-sigs/kustomize#3391]
**Describe the bug**

I have a kustomization that defines an Istio `Instance` as one of the resources.

```yaml
apiVersion: config.istio.io/v1alpha2
kind: Instance
metadata:
  labels:
    kustomize.component: aws-authzadaptor
  name: authzadaptor-instance
  namespace: istio-system
spec:
  params:
    key: request.headers["x-amzn-oidc-data"] | "unknown"
  template: authzadaptor
```

Additionally, my kustomization declares an images section to do image transformations. When I attempt to run `kustomize build .` I am seeing the following error.

```
Error: obj '{"apiVersion": "config.istio.io/v1alpha2", "kind": "instance", "metadata": {"labels": {
      "kustomize.component": "aws-authzadaptor"}, "name": "authzadaptor-instance",
    "namespace": "istio-system"}, "spec": {"params": {"key": "request.headers[\"x-amzn-oidc-data\"]
        | \"unknown\""}, "template": "authzadaptor"}}
' at path 'spec/template/spec/containers[]/image': expected sequence or mapping node
```

**Files that can reproduce the issue**

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- instance.yaml

# required to replicate bug
images:
- name: python
  newName: newPython
```

instance.yaml
```yaml
apiVersion: config.istio.io/v1alpha2
kind: Instance
metadata:
  labels:
    kustomize.component: aws-authzadaptor
  name: authzadaptor-instance
  namespace: istio-system
spec:
  params:
    key: request.headers["x-amzn-oidc-data"] | "unknown"
  template: authzadaptor
```

**Expected output**
The compiled manifests, in this case a single `Instance` resource.

**Actual output**
```
Error: obj '{"apiVersion": "config.istio.io/v1alpha2", "kind": "instance", "metadata": {"labels": {
      "kustomize.component": "aws-authzadaptor"}, "name": "authzadaptor-instance",
    "namespace": "istio-system"}, "spec": {"params": {"key": "request.headers[\"x-amzn-oidc-data\"]
        | \"unknown\""}, "template": "authzadaptor"}}
' at path 'spec/template/spec/containers[]/image': expected sequence or mapping node
```

**Kustomize version**
```
> kustomize version
{Version:kustomize/v3.8.8 GitCommit:72262c5e7135045ed51b01e417a7e72f558a22b0 BuildDate:2020-12-10T18:11:11Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOS

**Comment by natasha41575** [comment]
Can you please specify what you want the desired output to be? It is unclear to me what you are trying to achieve with the images field in your kustomization.

**Comment by dfarr** [comment]
In this example the desired output would simply be:
```
apiVersion: config.istio.io/v1alpha2
kind: Instance
metadata:
  labels:
    kustomize.component: aws-authzadaptor
  name: authzadaptor-instance
  namespace: istio-system
spec:
  params:
    key: request.headers["x-amzn-oidc-data"] | "unknown"
  template: authzadaptor
```

Note: there is no actual image replacement happening here, I boiled my `kustomization.yaml`  down to the minimal amount of information to reproduce this issue.

**Comment by dfarr** [comment]
That worked! Thank you, in case anyone is curious here is the fix:

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- instance.yaml

transformers:
- transformer.yaml
```

transformer.yaml
```yaml
apiVersion: builtin
kind: ImageTagTransformer
metadata:
  name: image-transformer
imageTag:
  name: python
  newTag: newPython
```
