### ISSUE TITLE
Issue with configMapGenerator / behavior merge since v3.9.0 tag

### ISSUE THREAD

**Issue by eko** [kubernetes-sigs/kustomize#3393]
**Describe the bug**

Since the [v3.9.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.9.0), I have an issue where the `configMapGenerator` with a `behavior: merge` does not merge anymore: it overrides the given values.

When I downgrade to release [v3.8.8](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.8) I don't have this issue so I think this bug was introduced recently.

**Files that can reproduce the issue**

Here is an example on how to reproduce this issue:

*File*: kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cm.yaml
configMapGenerator:
  - name: project
    behavior: merge
    literals:
    - ANOTHER_ENV_VARIABLE="bar"
```

*File*: cm.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: project
data:
  A_FIRST_ENV_VARIABLE: "foo"
```

**Expected output**

```yaml
apiVersion: v1
data:
  A_FIRST_ENV_VARIABLE: foo
  ANOTHER_ENV_VARIABLE: bar
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: project
```

**Actual output**

```yaml
apiVersion: v1
data:
  ANOTHER_ENV_VARIABLE: bar
kind: ConfigMap
metadata:
  name: project
```

**Kustomize version**

This issue is occurring with the latest `v3.9.0` tag, I don't have this issue when I downgrade to `v3.8.8`.

**Platform**

macOS Big Sur (11.1)

**Additional context**

Thank you, don't hesitate to ask for more details if needed.
