### ISSUE TITLE
v3.8.8 doesn't substitute the name of the generated secret, if it is mounted as a volume

### ISSUE THREAD

**Issue by phonexicum** [kubernetes-sigs/kustomize#3409]
**Describe the bug**

If generated secret are mounted as a volume, its name will be not patched (neither suffix hash, neither prefix, neither suffix).
(the configmap generator works correctly)

**Files that can reproduce the issue**

kustomization.yaml

```
secretGenerator:
- name: secret
  type: Opaque
  literals:
  - flag=TheSecretString
resources:
- resources.yaml
```

resources.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl
spec:
  selector:
    matchLabels:
      component: some
  template:
    metadata:
      labels:
        component: some

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          env:
            - name: SMTH
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: flag
          volumeMounts:
            - name: flag
              mountPath: /tmp/flag
      volumes:
        - name: flag
          valueFrom:
            secretKeyRef:
              name: secret
              key: flag
```

**Expected output**

Both secretKeyRef reference names expected to be substituted.

**Actual output**

```
spec:
  selector:
    matchLabels:
      component: some
  template:
    metadata:
      labels:
        component: some
    spec:
      containers:
      - env:
        - name: SMTH
          valueFrom:
            secretKeyRef:
              key: flag
              name: secret-tdhg9dgbmt
        image: nginx:latest
        name: nginx
        volumeMounts:
        - mountPath: /tmp/flag
          name: flag
      volumes:
      - name: flag
        valueFrom:
          secretKeyRef:
            key: flag
            name: secret
```

**Platform**: Ubuntu 18.04.2
