### ISSUE TITLE
ConfigMapGenerator drops quotes from quoted fields

### ISSUE THREAD

**Issue by Thomb89** [kubernetes-sigs/kustomize#3412]
the problem occured today, so only version 3.9.1 should be affected.

When a ConfigMap in merged with the configMapGenerator the output will result in invalid values for the data field. 
The surrounding quotation marks are stripped away (which converts some strings to int64), or in the case of an empty string it is converted to null

setting the flag --enable_kyaml=false fixed the issue 

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml

configMapGenerator:
  - name: test
    behavior: merge
    literals:
      - 'SOMETHING=""'
      - 'SMTP_PORT="993"'
```

resources.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  SOMETHING: 'not relevant'
  SMTP_PORT: '587'
  MYSQL_PORT: '3306'
```

**Expected output**

```
apiVersion: v1
data:
  MYSQL_PORT: "3306"
  SMTP_PORT: "993"
  SOMETHING: ""
kind: ConfigMap
metadata:
  name: test
```

**Actual output**

```
apiVersion: v1
data:
  MYSQL_PORT: 3306
  SMTP_PORT: 993
  SOMETHING: null
kind: ConfigMap
metadata:
  name: test
```

**Kustomize version**: kustomize/v3.9.1

**Platform**
 
- macos 
- ubuntu 20.04 with the snap package

**Comment by monopole** [comment]
Thanks. If setting the flag is a problem, use https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.9 instead which defaults the flag to false.

Changing `SOMETHING: ""` to `null` is certainly a problem. 

See also: 

https://github.com/kubernetes-sigs/kustomize/blob/master/api/krusty/configmaps_test.go#L13

https://github.com/kubernetes-sigs/kustomize/blob/master/api/krusty/configmaps_test.go#L63

Need to check a round trip of a configmap

**Comment by eigood** [comment]
Changing "3306" to 3306 is also a problem, because that's a number, and when you then send the CM to the environment, it'll complain?

**Comment by ephesused** [comment]
Another test case, this time for booleans:

**kustomization.yaml**

```yaml
configMapGenerator:
  - name: test-map
    literals:
      - INITIAL=true
  - name: test-map
    behavior: merge
    literals:
      - MERGED=false
```

Results:

```
[root@fc4d153db0d5 project_root]# build/kustomize-execs/release-v3.9.1/kustomize --enable_kyaml=false build testdata/kust-generator-merge/
apiVersion: v1
data:
  INITIAL: "true"
  MERGED: "false"
kind: ConfigMap
metadata:
  name: test-map-2k29mchd54
[root@fc4d153db0d5 project_root]# build/kustomize-execs/release-v3.9.1/kustomize build testdata/kust-generator-merge/
apiVersion: v1
data:
  INITIAL: true
  MERGED: false
kind: ConfigMap
metadata:
  name: test-map-h98ttf6fdk
[root@fc4d153db0d5 project_root]#
```

**Comment by babygoat** [comment]
This issue also occurs when `configMapGenerator` constructs configmap from `.properties` file as suggested in the documentation. Only the `merge` operation will incur the issue but `replace` will not.

Files to reproduce

**base/kustomization.yml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: test-configmap
    behavior: "create"
    envs:
    - base.properties
```

**base/base.properties**
```
VAR1=100
```

**replace-overlay/kustomization.yml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

configMapGenerator:
  - name: test-configmap
    behavior: "replace"
    envs:
    - replace.properties
```

**replace-overlay/replace.properties**
```
VAR2=100
```

**merge-overlay/kustomization.yml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

configMapGenerator:
  - name: test-configmap
    behavior: "merge"
    envs:
    - merge.properties
```

**merge-overlay/merge.properties**
```
VAR2=100
```

**kustomize@3.8.9 gives**
```
> kustomize build replace-overlay/
apiVersion: v1
data:
  VAR2: "100"
kind: ConfigMap
metadata:
  name: test-configmap-cg9m2dk2f8

> kustomize build merge-overlay/
apiVersion: v1
data:
  VAR1: "100"
  VAR2: "100"
kind: ConfigMap
metadata:
  name: test-configmap-gfmbdmd4b
```

**kustomize@3.9.1 gives**
```
> kustomize build replace-overlay/
apiVersion: v1
data:
  VAR2: "100"
kind: ConfigMap
metadata:
  name: test-configmap-cg9m2dk2f8

> kustomize build merge-overlay/     # issue occurs
apiVersion: v1
data:
  VAR1: 100
  VAR2: 100
kind: ConfigMap
metadata:
  name: test-configmap-mt5bhhcf7g
```

**Comment by snuggie12** [comment]
I have a similar quoting issue trying to use jmespath but it's on 3.8.4 and 3.9.1 with or without the kyaml option.

kustomization.yaml:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-extra-env
    literals:
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups[*], 'infra@foo.com') && 'Admin' || 'Viewer'
```

kustomize 3.8.4, 3.9.1 with kyaml enabled or disabled (NOTE the final single quote is missing)
```
apiVersion: v1
data:
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups[*], 'infra@foo.com') && 'Admin' || 'Viewer
kind: ConfigMap
metadata:
  name: grafana-extra-env-gdm7dbb4d6
```
