### ISSUE TITLE
kyaml applies incorrect block chomping with multi-document generators

### ISSUE THREAD

**Issue by ephesused** [kubernetes-sigs/kustomize#3419]
When processing multi-document generators that contain clipped block scalars, kyaml builds apply a strip chomp method on the final scalar in the document.

### kustomize version

```
[root@fc4d153db0d5 project_root]# build/kustomize-execs/release-v3.9.1/kustomize version
{Version:kustomize/v3.9.1 GitCommit:7439f1809e5ccd4677ed52be7f98f2ad75122a93 BuildDate:2020-12-29T19:25:35Z GoOs:linux GoArch:amd64}
[root@fc4d153db0d5 project_root]#
```

### Test setup

kustomization.yaml

```yaml
generators:
  - configmaps.yaml
```

configmaps.yaml (Note that each scalar uses clip.)

```yaml
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: testing
literals:
  - |
    initial.txt=greetings
    everyone
  - |
    final.txt=different
    behavior
---
# A second document, even just this comment,
# is necessary to exhibit the issue.
```

### Actual output

The chomp method for final.txt is strip:

```
[root@fc4d153db0d5 project_root]# build/kustomize-execs/release-v3.9.1/kustomize build testdata/kust-configmap-eol
apiVersion: v1
data:
  final.txt: |-
    different
    behavior
  initial.txt: |
    greetings
    everyone
kind: ConfigMap
metadata:
  name: testing-7f42mbmfmg
[root@fc4d153db0d5 project_root]#
```

### Expected output

Shown by using --enable_kyaml=false. The chomp method for final.txt is clip:

```
[root@fc4d153db0d5 project_root]# build/kustomize-execs/release-v3.9.1/kustomize --enable_kyaml=false build testdata/kust-configmap-eol
apiVersion: v1
data:
  final.txt: |
    different
    behavior
  initial.txt: |
    greetings
    everyone
kind: ConfigMap
metadata:
  name: testing-tt4769fb52
[root@fc4d153db0d5 project_root]#
```
