### ISSUE TITLE
Variable Fieldpath can't reference key name with dashes

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kustomize#3421]
**Describe the bug**

I have a kustomize variable which was working until a recent update. Now the variables are misbehaving for strange reasons. 

**Files that can reproduce the issue**

Here is the var in my `kustomization.yaml`
```yaml
vars:
  - name: ZONE
    objref:
      apiVersion: v1
      kind: PersistentVolume
      name: bitcoind
    fieldref:
      fieldpath: metadata.labels[failure-domain.beta.kubernetes.io/zone]
```
Then here is the corresponding PV with the label
`pv.yaml`
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoind
  labels:
    failure-domain.beta.kubernetes.io/region: eu-west-2
    failure-domain.beta.kubernetes.io/zone: eu-west-2a
```
**Expected output**

I expect the variable to be able to reference any key even with special characters in the name

**Actual output**

```
Error: field specified in var '{ZONE ~G_v1_PersistentVolume {metadata.labels[failure-domain.beta.kubernetes.io/zone]}}' not found in corresponding resource
```

**Kustomize version**

```
{Version:kustomize/v3.9.1 GitCommit:7439f1809e5ccd4677ed52be7f98f2ad75122a93 BuildDate:2020-12-30T00:43:15+00:00 GoOs:darwin GoArch:amd64}
```
**Platform**

Tested on Mac and Windows, both had the issue

**Additional context**

I pretty much determined it's the dash because below works:
```yaml
vars:
  - name: ZONE
    objref:
      apiVersion: v1
      kind: PersistentVolume
      name: bitcoind
    fieldref:
      fieldpath: metadata.labels[failure_domain.beta.kubernetes.io/zone]
```
... so long as there are no dashes `-`, a key can be referenced even with dots and slashes in the name
