### ISSUE TITLE
kustomize namespace entry for RoleBinding gives  "tranformation produces ID conflict..." error 

### ISSUE THREAD

**Issue by kenotsolutions** [kubernetes-sigs/kustomize#3422]
**Describe the bug**

if we use namespace in kustomize.yaml;  kustomize changes metadata namespaces for RoleBindings and makes double of them and gives below error. If we delete namespace line in the kustomization.yaml file it does not fail.

```
Error: namespace tranformation produces ID conflict: [{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":

``` 

**Files that can reproduce the issue**

```
kustomize build . 
```

Example:

kustomization.yaml

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - rboc.yaml

namespace: nam3spac3

...
```

 rboc.yaml

```
---
apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: kube-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: monitoring
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
kind: RoleBindingList
```

**Expected output**

Kustomize should have a parameter and disable the namespace changes for "kind: RoleBinding" 

**Actual output**

```
Error: namespace tranformation produces ID conflict: [{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"name":"prometheus-k8s","namespace":"nam3spac3"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s"},"subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"monitoring"}]}{nsfx:false,beh:unspecified} {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"name":"prometheus-k8s","namespace":"nam3spac3"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s"},"subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"monitoring"}]}{nsfx:false,beh:unspecified}]
```

**Kustomize version**

Version:kustomize/v3.5.4
**Platform**

Linux
