### ISSUE TITLE
patchesStrategicMerge removes duplicate containerPorts

### ISSUE THREAD

**Issue by f-herceg** [kubernetes-sigs/kustomize#3426]
**Describe the bug**
If resource has ports defined like this
```
 ports:
    - containerPort: 8080
      name: monitoring-port
    - containerPort: 8080
      name: api-port
```
After applying patchesStrategicMerge expected output is changed to
```
 ports:
    - containerPort: 8080
      name: api-port
```
And they should stay unchanged.

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - "deployment.yaml"

patches:
  - target:
      name: app
      kind: Deployment
    path: "app_image.yaml"
```

deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          ports:
            - name: monitoring-port
              containerPort: 8080
            - name: api-port
              containerPort: 8080
```
app_image.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          image: image:tag
```

**Expected output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - image: image:tag
        name: app
        ports:
        - containerPort: 8080
          name: monitoring-port
        - containerPort: 8080
          name: api-port
```

**Actual output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - image: image:tag
        name: app
        ports:
        - containerPort: 8080
          name: api-port
```

**Kustomize version**
both have unexpected output
{Version:kustomize/v3.8.8 GitCommit:72262c5e7135045ed51b01e417a7e72f558a22b0 BuildDate:2020-12-10T18:11:11Z GoOs:darwin GoArch:amd64}
{Version:kustomize/v3.9.0 GitCommit:826b5d9792fb67c4d8f8cd59747698ebf0b22720 BuildDate:2020-12-10T21:52:58+00:00 GoOs:darwin GoArch:amd64}

**Platform**
macOS

**Additional context**
version 3.6.1 works as expected
{Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:darwin GoArch:amd64}
