### ISSUE TITLE
[Question] How to create a setter for an item in array?

### ISSUE THREAD

**Issue by flickerfly** [kubernetes-sigs/kustomize#3429]
I have the following kustomization.yaml and Krmfile. It includes an array of ENV values that I'd like to turn into setters. So far the best I can figure out is a single setter for the entire array. Can I set list items in the array individually? 

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: minecraft-bedrock-
namespace: bedrock
resources:
- manifests/service.yaml
- manifests/statefulSet.yaml
configMapGenerator:
- name: minecraft-bedrock
  literals: # {"$openapi":"configMapGenerator.name"}
  - EULA="FALSE" # Must accept EULA to use this minecraft server (Set to TRUE)
  - GAMEMODE="survival" # Options=survival, creative, adventure
  - DIFFICULTY="normal" # Options=peaceful, easy, normal, hard
  - DEFAULT_PLAYER_PERMISSION_LEVEL="member" # Options=visitor, member, operator
  - LEVEL_NAME="my_minecraft_world"
  - LEVEL_SEED="33480944"
  - SERVER_NAME="my_minecraft_server"
  - SERVER_PORT="19132"
  - LEVEL_TYPE="DEFAULT" # Options=FLAT, LEGACY, DEFAULT
  - ALLOW_CHEATS="false" # Options=true, false
  - MAX_PLAYERS="10"
  - PLAYER_IDLE_TIMEOUT="30"
  - TEXTUREPACK_REQUIRED="false" # Options=true, false
  - OPS=""
  - MEMBERS=""
  - VISITORS=""
  - ONLINE_MODE="true"
  - WHITE_LIST="false"
  - WHITE_LIST_USERS="commma,separated,names"
  - VIEW_DISTANCE="10" # Performance impact
  - TICK_DISTANCE="4" # Performance impact
  - MAX_THREADS="8" # Performance impact
  ```

**Krmfile**
```yaml
apiVersion: config.k8s.io/v1alpha1
kind: Krmfile
openAPI:
  definitions:
    io.k8s.cli.setters.configMapGenerator.name:
      type: array
      x-k8s-cli:
        setter:
          name: configMapGenerator.name
          value: ""
          description: "Set Configuration array for Minecraft Bedrock server"
          listValues:
          - EULA="FALSE"
          - GAMEMODE="survival"
          - DIFFICULTY="normal"
          - DEFAULT_PLAYER_PERMISSION_LEVEL="member"
          - LEVEL_NAME="my_minecraft_world"
          - LEVEL_SEED="33480944"
          - SERVER_NAME="my_minecraft_server"
          - SERVER_PORT="19132"
          - LEVEL_TYPE="DEFAULT"
          - ALLOW_CHEATS="false"
          - MAX_PLAYERS="10"
          - PLAYER_IDLE_TIMEOUT="30"
          - TEXTUREPACK_REQUIRED="false"
          - OPS=""
          - MEMBERS=""
          - VISITORS=""
          - ONLINE_MODE="true"
          - WHITE_LIST="false"
          - WHITE_LIST_USERS="commma,separated,names"
          - VIEW_DISTANCE="10"
          - TICK_DISTANCE="4"
          - MAX_THREADS="8"
          required: true
```
