### ISSUE TITLE
namePrefix behavior differs depending on namespace specification in resources

### ISSUE THREAD

**Issue by sriumcp** [kubernetes-sigs/kustomize#3430]
**Describe the bug**
namePrefix behavior is applied inconsistently depending on the value of namespace in resources.

**Files that can reproduce the issue**

kustomization.yaml
```
namePrefix: iter8-
namespace: iter8-monitoring
resources:
- clusterrolebinding.yaml
- serviceaccount.yaml
```

serviceaccount.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
```

clusterrolebinding.yaml
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: iter8-monitoring
```

**Expected output**

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iter8-prometheus
  namespace: iter8-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: iter8-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: iter8-prometheus
  namespace: iter8-monitoring
```

**Actual output**

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iter8-prometheus
  namespace: iter8-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: iter8-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: iter8-monitoring
```

The issue is with the `name` field of the subject above, which needs to be `iter8-prometheus`.

**Kustomize version**

```
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-09-02T07:10:16+01:00 GoOs:darwin GoArch:amd64}
```
I was able to reproduce the issue with v3.8.7 as well.

**Platform**

macOS Big Sur version 11.1

**Additional context**

Changing the value of `namespace` field to `default` in `clusterrolebinding.yaml` makes actual output match expected output.
