### ISSUE TITLE
HelmChartInflationGenerator does not work when building outside kustomization dir

### ISSUE THREAD

**Issue by aogier** [kubernetes-sigs/kustomize#3435]
**Describe the bug**

In kustomization 3.9.1 it is not possible to use `HelmChartInflationGenerator` when building outside files' dir.

**Files that can reproduce the issue**

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - generators.yaml
```
```yaml
# generators.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: xxx
chartName: ingress-nginx
chartRepoUrl: https://kubernetes.github.io/ingress-nginx
values: myvalues.yaml
```
```yaml
# myvalues.yaml
nameOverride: foobar
```

**Expected output**

kustomize build should indeed render this chart as it does when invoked in `kustomization.yaml`'s dir

**Actual output**

```
kustomize build kusto
Error: Error: open myvalues.yaml: no such file or directory
: failed to run command helm template /tmp/kustomize-448884726/chart/ingress-nginx --values myvalues.yaml
```

**Kustomize version**

3.9.1

**Platform**

linux

Thank you, regards!

**Comment by Shell32-Natsu** [comment]
kustomize will not try to copy your `myvalues.yaml` file to the temporary directory. Please use an absolute path to it.

**Comment by aogier** [comment]
it does not seems a proper solution to me, in fact `--help` tell me
```
To generate the resources specified in 'someDir/kustomization.yaml', run

  kustomize build someDir

The default argument to 'build' is '.' (the current working directory).
```
so, apart this **broken contract**, anything that use kustomize as an internal tool (let's say, argocd), cannot properly use it because workdir is a temporary repo clone whose path we can easily reconstruct by hardcoding it

```yaml
metadata:
  name: xxx
chartName: ingress-nginx
chartRepoUrl: https://kubernetes.github.io/ingress-nginx
# FIXME: upstream bug
values: /tmp/git@github.com_xxx/foo/bar/baz/anotherdir/yeah_complex/monorepo/staging/values-default.yaml
```
I don't think I have to tell you how much this is lame. In fact I'm not doing that, baking a custom argocd image instead with a `wrapper.sh` that chdir to the first `build` argument, it's just a letdown to adopt a tool with such a sloppy QA and it raises many doubts about the goodness of this adoption choice. But who I am at the end :man_shrugging: :)

**Comment by Shell32-Natsu** [comment]
kustomize itself does support the relative path. However, HelmChartInflationGenerator plugin is different. It's a plugin and the implementation is different from kustomize itself. The `helm` command must be run in a separate directory to avoid messing up the stuffs in your working directory. That makes the relative path not working.

**Comment by aogier** [comment]
It is still not clear how this could work when invoked on the proper `kustomization.yaml`'s dir then. Don't doubt there is a reason for this ~bug~ behavior but as I can fix it by chdir on a well know, not temp dir, it's so weird kustomize can't do it by itself: with the three files I pasted above:
```python
if pwd == basedir('kustomization.yaml'):
  work()
else:
  dontwork()
```
I thought that such a trivial problem could be reported. Thanks!

**Comment by Shell32-Natsu** [comment]
Will take a look.

**Comment by aogier** [comment]
It is also to be noted that `helm template` will not mess in any way any directory, in fact the error message I've reported to you report that:

```
helm template /tmp/kustomize-448884726/chart/ingress-nginx --values myvalues.yaml
```
so the problem seem obvious: helm subprocess live in the invoking process' cwd and this lead to all this fuss. 

HTH, ciao, and thanks for all your work!

**Comment by aogier** [comment]
Another quirk I think could definitely related to this bug: I have a base where I inflate some helm charts, keeping overlays to do last mile modifications:

```
oggei@cane $  tree
.
├── base
│   ├── ingress-generator.yaml
│   ├── kustomization.yaml
│   ├── values-cs.yaml
│   ├── values-default.yaml
│   └── values-nlb.yaml
└── prod-1
    └── kustomization.yaml
```

so `base/kustomization.yaml` has:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - ingress-generator.yaml
```

with all the stuff, and `prod-1/kustomization.yaml` only has:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
```

Now if i build `base`, everything goes as expected, but if I try to build `prod-1`:

```shell
oggei@cane $  kustomize build prod-1
Error: accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from '../base': '/home/oggei/dev/[REDACTED]/applications/nginx-ingress-controller/base' must resolve to a file"
        * accumulateDirector error: "recursed accumulation of path '/home/oggei/dev/[REDACTED]/applications/nginx-ingress-controller/base': Error: open values-default.yaml: no such file or directory\n: failed to run command helm template default /tmp/kustomize-809617376/chart/ingress-nginx --namespace ingress --values values-default.yaml"
```

If I copy values file in `prod-1`, then build works, but definitely defeat the design all these shenanigans are intended to support :)

HTH, ciao!

**Comment by aogier** [comment]
Just for completeness, this is generator:
```yaml
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-default
chartName: ingress-nginx
chartRepoUrl: https://kubernetes.github.io/ingress-nginx
chartVersion: 2.12.1
releaseName: default
releaseNamespace: ingress
values: values-default.yaml
# ---
# apiVersion: builtin
# kind: HelmChartInflationGenerator
# metadata:
#   name: ingress-cs
# chartName: ingress-nginx
# chartRepoUrl: https://kubernetes.github.io/ingress-nginx
# chartVersion: 2.12.1
# releaseName: cs
# releaseNamespace: ingress
# values: values-cs.yaml
---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nlb
chartName: ingress-nginx
chartRepoUrl: https://kubernetes.github.io/ingress-nginx
chartVersion: 2.12.1
releaseName: nlb
releaseNamespace: ingress
values: values-nlb.yaml
```

thx, ciao
