### ISSUE TITLE
Should NamespaceTransformer run before PatchStrategicMergeTransformer?

### ISSUE THREAD

**Issue by fernando-villalba** [kubernetes-sigs/kustomize#3447]
Using Kustomize 3.9.0 on Mac

if I do this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - https://github.com/ricoberger/vault-secrets-operator/config/default?ref=1.11.0

patchesStrategicMerge:
  - overlays/deploy.yaml

images:
  - name: ricoberger/vault-secrets-operator
    newTag: 1.11.0

namespace: vault
```

The above overlay is the following:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-operator
  namespace: vault
  labels:
    app: vault-secrets-operator
spec:
  template:
    metadata:
      labels:
        app: vault-secrets-operator
    spec:
      containers:
      - name: manager
        env:
        - name: VAULT_ADDRESS
          value: https://blah
        - name: VAULT_AUTH_METHOD
          value: kubernetes
        - name: VAULT_KUBERNETES_PATH
          value: auth/test-cluster
        - name: VAULT_KUBERNETES_ROLE
          value: test-cluster
        - name: VAULT_RECONCILIATION_TIME
          value: "60"
        - name: WATCH_NAMESPACE
          value: ""
```
I get the following error:

`Error: no matches for OriginalId apps_v1_Deployment|vault|vault-secrets-operator; no matches for CurrentId apps_v1_Deployment|vault|vault-secrets-operator; failed to find unique target for patch apps_v1_Deployment|vault-secrets-operator`

This seems only happening with remote sources?

**Comment by fernando-villalba** [comment]
The only way to fix the above is by using the original namespace in the remote repository like this: 



```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator
  labels:
    app: vault-secrets-operator
spec:
  template:
    metadata:
      labels:
        app: vault-secrets-operator
    spec:
      containers:
      - name: manager
        env:
        - name: VAULT_ADDRESS
          value: https://blah
        - name: VAULT_AUTH_METHOD
          value: kubernetes
        - name: VAULT_KUBERNETES_PATH
          value: auth/test-cluster
        - name: VAULT_KUBERNETES_ROLE
          value: test-cluster
        - name: VAULT_RECONCILIATION_TIME
          value: "60"
        - name: WATCH_NAMESPACE
          value: ""
```

This is okay, but it's just odd the way this works. You should be able to specify the namespace that are you are modifying in kustomize perhaps.
