### ISSUE TITLE
`$patch: delete` does not work for not existing variables 

### ISSUE THREAD

**Issue by mikhail-nikitin** [kubernetes-sigs/kustomize#3463]
**Describe the bug**

When a strategic merge patch contain `$patch: delete` directive for not existing elements,
kustomize produces resources containing `$patch: delete`.

**Files that can reproduce the issue**

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resource.yaml
patches:
- path: patch.yaml
  target:
    kind: Deployment
```

resource.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatever
spec:
  template:
    spec:
      containers:
      - env:
        - name: EXISTING
          value: EXISTING_VALUE
        - name: FOR_REMOVAL
          value: FOR_REMOVAL_VALUE
        name: whatever
        image: helloworld
```

patch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatever
spec:
  template:
    spec:
      containers:
      - name: whatever
        env:
        - name: FOR_REMOVAL
          $patch: delete
        - name: NOT_EXISTING_FOR_REMOVAL
          $patch: delete
```

**Expected output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatever
spec:
  template:
    spec:
      containers:
      - env:
        - name: EXISTING
          value: EXISTING_VALUE
        image: helloworld
        name: whatever
```

**Actual output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatever
spec:
  template:
    spec:
      containers:
      - env:
        - $patch: delete
          name: NOT_EXISTING_FOR_REMOVAL
        - name: EXISTING
          value: EXISTING_VALUE
        image: helloworld
        name: whatever
```
**Kustomize version**

v3.8.9

**Platform**

Linux

**Additional context**

PR with the test case - #3462
