### ISSUE TITLE
[Question] Share env between deployments

### ISSUE THREAD

**Issue by thanhpd-teko** [kubernetes-sigs/kustomize#3468]
Hi, i have a flask application with 3 deployments, one for api, one for worker, and one for beat.
They have the same env, but different commands.
How can I share env between them without declaring again? Please help.

```
          env:
            - name: ENV_MODE
              value: dev
            - name: VERSION_IOS
              value: 0.0.3
            - name: VERSION_ANDROID
              value: 0.0.3
            - name: VERSION_API
              value: 0.0.1
            - name: MYSQL_DATABASE
              value: abc
            - name: MYSQL_HOST
              value: db-mysql-dev
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: mysql-password
```
