### ISSUE TITLE
kyaml panics on duplicate keys

### ISSUE THREAD

**Issue by stefanprodan** [kubernetes-sigs/kustomize#3480]
In [Flux v2](https://github.com/fluxcd/flux2) we decided to use kustomize libraries in our controllers and we make extensive use of `kyaml`. We found that if a manifest contains duplicate keys, kyaml panics taking down the whole controller.

Can we please not panic and instead return an error from kyaml containing the **manifest name** so that both Kustomize and Flux users can track down which object/manifest caused this? Without a hint to the invalid manifest, there is no way for users that have hundreds of manifests in a single kustomization to debug such errors.

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

resources.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfod
        image: ghcr.io/stefanprodan/podinfo:5.0.3 
        command:
        - ./podinfo
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        env:
          - name: PODINFO_UI_COLOR
            value: "#34577c"
```

**Actual output**

```
 $ kustomize build --enable_kyaml=true
2021/01/18 13:21:50 failed to decode ynode: yaml: unmarshal errors:
  line 50: mapping key "env" already defined at line 47
```

**Kustomize version**

```
$ kustomize version
{Version:kustomize/v3.9.2 GitCommit: BuildDate:2021-01-17T19:01:12+00:00 GoOs:darwin GoArch:amd64}
```

```go
module github.com/fluxcd/kustomize-controller

require (
	sigs.k8s.io/kustomize/api v0.7.2
)
```

```go
module github.com/fluxcd/image-automation-controller

// Force downgrade to version used by kyaml.
replace gopkg.in/yaml.v3 => gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c

require (
	sigs.k8s.io/kustomize/kyaml v0.10.5
)
```
