### ISSUE TITLE
Unable to find Kustomize version '3.6.1' for platform 'linux' and architecture amd64.

### ISSUE THREAD

**Issue by tkayyyyys** [kubernetes-sigs/kustomize#3482]
**Describe the bug**
 I'm using kustomize in my Github actions workflow. As of today I receive the following error when executing a Github action workflow. 

**Unable to find Kustomize version '3.6.1' for platform 'linux' and architecture amd64.**

I filed a bug with the Github actions team. They investigated at https://github.com/actions/virtual-environments/issues/2485 . Their feedback was as follows:

 Looks like when setup-kustomize retrieves the list of versions kubernetes-sigs/kustomize, pagination doesn't work properly and it retrieves only first 30 results.
Previously, it worked but recently, a bunch of new versions were added to https://github.com/kubernetes-sigs/kustomize and version 3.6.1 is not in the first 30 results.

In the Github Action we use; imranismail/setup-kustomize@v1 to download and install kustomize in runtime from https://github.com/kubernetes-sigs/kustomize.

**Files that can reproduce the issue**
Attached is my master.yml which references imranismail/setup-kustomize which in-turn runs setup-kustomize:

```
name: CI
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: azure/docker-login@v1
        with:
          login-server: 
          username: 
          password: 

      - name: Run the auto build script
        run: _build/auto/build-and-push.rb sandbox
  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          context: careful
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Run the auto build script
        run: _build/auto/deploy.rb sandbox
```

**Platform**

 Ubuntu-latest
