### ISSUE TITLE
double quote disappear

### ISSUE THREAD

**Issue by hansanghoon** [kubernetes-sigs/kustomize#3485]
**Describe the bug**

vars variable is surrounded by double quotes `""`
after build, double quotes disappear.

**Files that can reproduce the issue**

kustomization.yaml loads redis port using vars

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis.yaml
- quote.yaml
- web.yaml
vars:
- name: QUOTE_APP_URL
  objref:
    apiVersion: v1
    kind: Service
    name: quote-app-service
  fieldref:
    fieldpath: metadata.name
- name: QUOTE_APP_PORT
  objref:
    apiVersion: v1
    kind: Service
    name: quote-app-service
  fieldref:
    fieldpath: spec.ports.0.port
- name: REDIS_HOST
  objref:
    apiVersion: v1
    kind: Service
    name: redis
  fieldref:
    fieldpath: metadata.name
- name: REDIS_PORT
  objref:
    apiVersion: v1
    kind: Service
    name: redis
  fieldref:
    fieldpath: spec.ports.0.port
```

quote-patch.yaml patches deployment. put redis port into environment variable. `REDIS_PORT` var inside double quote.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  template:
    spec:
      containers:
      - name: app-container
        env:
        - name: REDIS_HOST
          value: $(REDIS_HOST)
        - name: REDIS_PORT
          value: "$(REDIS_PORT)"
```

**Expected output**

kustomize version 3.9.1 build output

```yaml
...
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-dev
        - name: REDIS_PORT
          value: "6379"
```

**Actual output**

kustomize version 3.9.2 build output

```yaml
...
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-dev
        - name: REDIS_PORT
          value: 6379
```

```
$ kustomize build --load_restrictor none overlay/dev/v1 | kubectl apply -f -

namespace/quote-dev unchanged
configmap/web-config-dev-9g62k48669 unchanged
service/quote-app-service-dev unchanged
service/redis-dev unchanged
service/web-dev unchanged
deployment.apps/redis-dev configured
deployment.apps/web-dev unchanged
Error from server (BadRequest): error when creating "STDIN": Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 6, error found in #10 byte of ...|,"value":6379}],"ima|..., bigger context ...|value":"redis-dev"},{"name":"REDIS_PORT","value":6379}],"image":"callicoder/go-redis-app:1.0.0","ima|...
```

**Kustomize version**

3.9.1 works as expected
3.9.2 removes double quotes surrounding var

**Platform**

macOS, kustomize cli upgraded via homebrew. regression test performed by download release from this github

**Additional context**

**Comment by epcim** [comment]
The same issue here 
```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: hass

chartName: home-assistant
chartRepoUrl: https://k8s-at-home.com/charts/
chartRelease: stable
chartVersion: 2.5.1

releaseName: hass
releaseNamespace: home

valuesLocal:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.priority: "10"
      kubernetes.io/tls-acme: "true"
```

end up as 
```
kubernetes.io/tls-acme: true
traefik.ingress.kubernetes.io/router.priority: 10
```

^^ both, on kubectl apply throws 

```
error: unable to decode "ing.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|ls-acme":true,"traef|..., bigger context ...|:"traefik-cert-manager","kubernetes.io/tls-acme":true,"traefik.ingress.kubernetes.io/router.entrypoi|...
```

Some discussin here:
- https://stackoverflow.com/questions/61905549/helm-install-with-set-ends-in-an-error-v1-objectmeta-annotations-readstring

Required
- backward compatibility
- if desired, change behaviour on major version upgrade with option like `\"` to preserve `"`

**Comment by Shell32-Natsu** [comment]
@monopole Is this the same with other quotes issues?

**Comment by tehmoon** [comment]
Same here, had to downgrade because it was messing up with annotations. I did not find any workaround though.

**Comment by aariacarterweir** [comment]
Same here... bit weird

**Comment by hansanghoon** [comment]
4.0.1 still has problem. I think this should have more priority as this will hinder people from upgrading.

**Comment by hansanghoon** [comment]
kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis.yaml
- deployment.yaml
vars:
- name: REDIS_HOST
  objref:
    apiVersion: v1
    kind: Service
    name: redis
  fieldref:
    fieldpath: metadata.name
- name: REDIS_PORT
  objref:
    apiVersion: v1
    kind: Service
    name: redis
  fieldref:
    fieldpath: spec.ports.0.port
```

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  template:
    spec:
      containers:
      - name: app-container
        env:
        - name: REDIS_HOST
          value: $(REDIS_HOST)
        - name: REDIS_PORT
          value: "$(REDIS_PORT)"
```

redis.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
```

and build output
```
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  template:
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: 80
        name: app-container
```

problem still persist as we have integer value for environment variable. tested on windows 10 with kustomize cli(installed via chocolatey `choco install kustomize`).

```
\ kustomize version
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:windows GoArch:amd64}
```

**Comment by eddiezane** [comment]
We are planning to deprecate vars and this will not be fixed.

Please see https://github.com/kubernetes-sigs/kustomize/issues/2052.

/close

**Comment by air3ijai** [comment]
Same issue with port number and password which contains special characters. Solutions proposed in https://github.com/kubernetes-sigs/kustomize/issues/3412 doesn't work in our case.

```
DB_PORT: ${DB_PORT} --> Error
DB_PORT: "${DB_PORT}" --> Error
DB_PORT: '${DB_PORT}' --> Error
DB_PORT: "'${DB_PORT}'" --> '443' --> Can't be interpreted correctly by container shell
```

Workaround we use:

**secrets.yml**
```yml
apiVersion: v1
kind: Secret
metadata:
  name: db
type: Opaque
stringData:
  DB_HOSTNAME: '${DB_HOSTNAME}'
  DB_PORT: |
    ${DB_PORT}
```

**result**
```yml
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: db
stringData:
  DB_PORT: |
    443
```

**container**
```bash
echo $DB_PORT
443
```
