### ISSUE TITLE
Set image tag preserving image name

### ISSUE THREAD

**Issue by alecunsolo** [kubernetes-sigs/kustomize#3487]
When using `kustomize edit set image` to change the tag of an image the `newName` is not preserved
I should be able to change only the image tag and keep the `newName` as-is

This is similar to #2625, but the proposed solution doesn't work as I expected.
This is the source kustomization
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: myname
  newName: newName
  tag: v1.0.0
```
After `kustomize edit set image myname=:v2.0.0` the resulting kustomization.yaml is
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: myname
  newTag: v2.0.0
```

I'm using version 3.9.2:
```sh
kustomize version
{Version:kustomize/v3.9.2 GitCommit: BuildDate:2021-01-17T19:01:50+00:00 GoOs:darwin GoArch:amd64}
```
