### ISSUE TITLE
Yaml Anchor not supported?

### ISSUE THREAD

**Issue by leptonyu** [kubernetes-sigs/kustomize#3497]
**Describe the bug**

```
+ kustomize build .
Error: obj 'apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  annotations:
    config.kubernetes.io/originalNs: default
  namespace: blog
spec:
  tls:
  - hosts:
    - xyz.me
    - www.xyz.me
    secretName: cert-tls
  rules:
  - host: xyz.me
    http: &xxx_rules
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 80
  - host: www.xyz.me
    http: * xxx_rules
' at path 'spec/rules/http/paths/backend/serviceName': visit traversal on path: [http paths backend serviceName]: expected sequence or mapping node
```
**Files that can reproduce the issue**

kustomize version 3.9.2_1

**Comment by Shell32-Natsu** [comment]
Please provide your resource files so we can reproduce it.

**Comment by leptonyu** [comment]
test.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
spec:
  tls:
  - hosts:
    - xyz.me
    - www.xyz.me
    secretName: cert-tls
  rules:
  - host: xyz.me
    http: &xxx_rules
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 80
  - host: www.xyz.me
    http: *xxx_rules
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test.yaml
namespace: blog
```

**Comment by leptonyu** [comment]
```
Error: obj 'apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  annotations:
    config.kubernetes.io/originalNs: default
  namespace: blog
spec:
  tls:
  - hosts:
    - xyz.me
    - www.xyz.me
    secretName: cert-tls
  rules:
  - host: xyz.me
    http: &xxx_rules
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 80
  - host: www.xyz.me
    http: *xxx_rules
' at path 'spec/rules/http/paths/backend/serviceName': visit traversal on path: [http paths backend serviceName]: expected sequence or mapping node
```

**Comment by leptonyu** [comment]
@Shell32-Natsu

**Comment by george-angel** [comment]
Hello, should I open a new issue?

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: &app proximo
    uw.systems/mirror: "true"
  name: *app
spec:
  ports:
  - name: ops
    port: 8080
    protocol: TCP
  - name: http
    port: 6868
    protocol: TCP
  selector:
    app: *app
```

```
Error: accumulating resources: accumulation err='accumulating resources from 'kafka': '<redacted-path>' must resolve to a file': recursed accumulation of path '<redacted-path>': accumulating resources: accumulation err='accumulating resources from 'proximo': '<redacted-path>' must resolve to a file': recursed accumulation of path '<redacted-path>': considering field 'metadata/name' of object
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: &app proximo
    uw.systems/mirror: "true"
  name: *app
spec:
  ports:
  - name: ops
    port: 8080
    protocol: TCP
  - name: http
    port: 6868
    protocol: TCP
  selector:
    app: *app
: wrong Node Kind for metadata.name expected: ScalarNode was AliasNode: value: {*app}
```
