### ISSUE TITLE
configMapGenerator doesn't merge binaryData

### ISSUE THREAD

**Issue by haisum** [kubernetes-sigs/kustomize#3504]
**Describe the bug**

When using a base with a binary file in a generated configmap, the overlay doesn't add the key/value pair for said binary file in the final configmap manifest.

...

**Files that can reproduce the issue**

I have attached a zip file containing all the files listed below.
[Archive.zip](https://github.com/kubernetes-sigs/kustomize/files/5946726/Archive.zip)

base/kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-configmap
    files:
      - common-binary-file.zip

generatorOptions:
  disableNameSuffixHash: true

```

base/common-binary-file.zip

```bash
zip common-binary-file.zip kustomization.yaml 
```

overlays/app1/kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: app-configmap
    behavior: merge

generatorOptions:
  disableNameSuffixHash: true

```

...

**Command**

`kustomize build overlays/app1`

**Expected output**

```yaml
apiVersion: v1
binaryData:
  common-binary-file.zip: |
    UEsDBAoAAAAAAF1tOVJ+6vLoFAAAABQAAAATABwAbGlmZS1hcHAtY29tbW9uLmVudlVUCQ
    ADMhEPYGIRD2B1eAsAAQT1AQAABBQAAABhYmM9eHl6CmVudjE9dmFsdWUxClBLAQIeAwoA
    AAAAAF1tOVJ+6vLoFAAAABQAAAATABgAAAAAAAEAAACkgQAAAABsaWZlLWFwcC1jb21tb2
    4uZW52VVQFAAMyEQ9gdXgLAAEE9QEAAAQUAAAAUEsFBgAAAAABAAEAWQAAAGEAAAAAAA==
kind: ConfigMap
metadata:
  name: app-configmap
```

**Actual output**

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
```

**Kustomize version**

{Version:kustomize/v3.9.2 GitCommit:e98eada7365fc564c9aba392e954f306a9cbf1dd BuildDate:2021-01-17T17:49:45Z GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

Regular text files, env files work as expected and get merged properly. Please guide me to where this code may be and I can work on a PR to fix this.
