### ISSUE TITLE
v 1.0.8 does not include secret key ref suffix

### ISSUE THREAD

**Issue by coryodaniel** [kubernetes-sigs/kustomize#351]
When using `secretGenerator` a secret is created with a suffix, but when referencing it the resource does not have the suffix. See output on the same code from 1.0.3 vs 1.0.8 below.

Given:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cory-test-pod
spec:
  containers:
  - name: test-pod
    image: busybox
    env:
      - name: USER
        valueFrom:
          secretKeyRef:
            name: env
            key: user
```

On 1.0.3 outputs:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations: {}
  labels:
    app: test
  name: test-cory-test-pod
  namespace: playground
spec:
  containers:
  - env:
    - name: USER
      valueFrom:
        secretKeyRef:
          key: user
          name: env-b77282thcd # <--- Has the suffix
    image: busybox
    name: test-pod
---
apiVersion: v1
data:
  pass: a2V3bA==
  user: Y29yeQ==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: env-b77282thcd
  namespace: playground
type: Opaque
```

On 1.0.8 outputs:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations: {}
  labels:
    app: test
  name: test-cory-test-pod
  namespace: playground
spec:
  containers:
  - env:
    - name: USER
      valueFrom:
        secretKeyRef:
          key: user
          name: env  # <--- No suffix
    image: busybox
    name: test-pod
---
apiVersion: v1
data:
  pass: a2V3bA==
  user: Y29yeQ==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: env-b77282thcd
  namespace: playground
type: Opaque
```

**Comment by mgoodness** [comment]
> Can you add the kustomization.yaml code for the secretgenerator (i.e. the full bug reproduction?)

Not OP, but I'm running into this too.

Putting the secretGenerator in `base/kustomization.yaml`, where the deployment is also listed, works.
```
commonLabels:
  app: spotinst-cluster-controller
  inventorycode: spotinst-cluster-controller
  productcode: prd354

namespace: prd354

resources:
- certs-secret.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml

secretGenerator:
- name: spotinst-cluster-controller
  commands:
    ACCOUNT: "printf ..."
    CLUSTER_IDENTIFIER: "printf ..."
    TOKEN: "printf ..."
  type: Opaque
```
but moving the secretGenerator to an overlay `kustomization.yaml` results in the deployment's reference not having the suffix.
