### ISSUE TITLE
Patch to add label fails if label: {} is not in resources

### ISSUE THREAD

**Issue by rob8714** [kubernetes-sigs/kustomize#3520]
Hi

Came across a problem adding a label with the following files:

service.yml
```
---
kind: Service
apiVersion: v1
metadata:
  name: app-svc
spec:
  ports:
    - name: app
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app
  type: ClusterIP
```

kustomization.yaml
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml

patches:
- patch: |-
    - op: add
      path: /metadata/labels/testLabel
      value: test
  target:
    kind: Service
    version: v1
    name: app-svc
```

Running kustomize build . gives an error:

Error: add operation does not apply: doc is missing path: "/metadata/labels/testLabel": missing value

**Expected output**

```
---
kind: Service
apiVersion: v1
metadata:
  name: app-svc
  labels:
    testLabel: test
spec:
  ports:
    - name: app
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app
  type: ClusterIP
```

**Actual output**

Error: add operation does not apply: doc is missing path: "/metadata/labels/testLabel": missing value

**Kustomize version**

v3.8.9

**Platform**

macOS

**Additional context**

Adding ```labels: {}``` in service.yml solves the problem, however understanding is that this should not fail especially since we are adding adding objects.

**Comment by Shell32-Natsu** [comment]
That is how json patch works. To add label please use [LabelTransformer](https://kubectl.docs.kubernetes.io/references/kustomize/commonlabels/)

**Comment by rob8714** [comment]
This assumes that I want to add the label to all the resources... I want to add the label to just one resource so using the commonLabel is not really an option, what I provided in the above was a simple example.  It also assumes that the base layer needs to cater for possibilities that may be added in the overlays.

I will work around by adding label: {}, but it would be great if the documentation could be updated to clarify on this behavior since, in my opinion, this is not clear.

**Comment by Shell32-Natsu** [comment]
If you want to use json patch, I assume you have clear understanding of it. Please take a look at the specification of `add` operation: https://tools.ietf.org/html/rfc6902#section-4.1.

**Comment by rob8714** [comment]
Thanks for clarifying, I wasn't looking at the RFC but now I read through the section and understand :)

**Comment by akankshakothari** [comment]
This works , but it overwrites the existing labels

**Comment by jeffmccune** [comment]
One gotcha with the quick solution above, it _replaces_ the labels.  If instead you do want to add a label and you're wondering why kustomize is gas-lighting you with `op: add` a [replacing instead of adding](https://pauldally.medium.com/the-most-common-problem-i-see-when-using-json6902-patching-with-kustomize-1d19a0f4a038) , then try this:

```yaml
patches:
  - target:
      kind: Deployment
      name: httpbin
    patch: |-
      - op: add
        path: "/spec/template/metadata/labels/sidecar.istio.io~1inject"
        value: "true"
```
