### ISSUE TITLE
Transformer ValueAdd should allow escaping forward slash

### ISSUE THREAD

**Issue by wolfmah** [kubernetes-sigs/kustomize#3537]
**Describe the bug**

When using ValueAdd transformer, it is not possible to add a label/annotation that contains a forward slash (`/`).

**Files that can reproduce the issue**

Example:

kustomization.yaml
```yaml
resources:
- deployment.yaml

transformers:
- transformer.yaml
```

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: busybox
        image: busybox:latest
```

transformer.yml
```yaml
apiVersion: builtin
kind: ValueAddTransformer
metadata:
  name: any
value: "FOO"
targets:
- selector:
    kind: Deployment
    name: test
  fieldPath: metadata/labels/name
- selector:
    kind: Deployment
    name: test
  fieldPath: metadata/labels/app.kubernetes.io/instance
- selector:
    kind: Deployment
    name: test
  fieldPath: metadata/labels/app.kubernetes.io\/name
```

**Expected output**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    app.kubernetes.io:
      instance: FOO
    app.kubernetes.io/name: FOO
    name: FOO
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: busybox:latest
        name: busybox
```

**Actual output**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    app.kubernetes.io:
      instance: FOO
    app.kubernetes.io\:
      name: FOO
    name: FOO
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: busybox:latest
        name: busybox
```

**Kustomize version**

`{Version:kustomize/v3.9.2 GitCommit:e98eada7365fc564c9aba392e954f306a9cbf1dd BuildDate:2021-01-21T15:37:58+00:00 GoOs:darwin GoArch:amd64}`

**Platform**

macOS Big Sur version 11.2

**Additional context**

Looks like this is the line to add some logic to: https://github.com/kubernetes-sigs/kustomize/blob/4345cd2adecf29d864c0d9531bcfbe1cb327d867/api/filters/valueadd/valueadd.go#L101
