### ISSUE TITLE
[Question] How do we change the image of non-deployment resource

### ISSUE THREAD

**Issue by vvavepacket** [kubernetes-sigs/kustomize#3542]
Typically if we have a deployment and we want kustomize to change it we do the following command 

`kustomize edit set image xxxxx.dkr.ecr.us-east-1.amazonaws.com/janestreet/hft:${env.GIT_COMMIT}"`

But how do we use the edit set image command to a non deployment resource (like some custom CRDs) like below?

In this case, how do we change this image `gcr.io/spark-operator/spark:v3.0.0` below using command line?

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-streaming1-popular
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.0.0"
  imagePullPolicy: Always
  mainClass: com.gzhr.streaming.Popular
  sparkVersion: "3.0.0"
  sparkConf:
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: my-release-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"

```
