### ISSUE TITLE
CommonLabels don't apply to configMapGenerators

### ISSUE THREAD

**Issue by jacoboldroyduvu** [kubernetes-sigs/kustomize#3570]
# Describe the bug
If commonLabels are used in the base kustomization.yaml as well as the kustomization.yaml of your patch, the commonLabels in both kustomization get merged corectly. However, if in the kustomization.yaml of your patch you also have a configMapGenerator, only the commonLabel in the patch's kustomization.yaml will be applied.

# How to reproduce the issue
base/kustomization.yaml
```yaml
...
resources:
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cache-properties
    files:
      - configmaps/cache.properties

commonLabels:
  app.kubernetes.io/name: nginx-test-deployment
  app.kubernetes.io/version: "1"
  app.domain/suite: testing
  app.domain/platform: testing.1-alpha
```
dev/kustomization.yaml
```yaml

bases:
  - ../base

configMapGenerator:
  - name: test-properties
    files:
      - configmaps/test.properties

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.domain/environment: dev
```

After issuing a `kubectl kustomize dev/`
```yaml

---
apiVersion: v1
data:
  test.properties: |
    test.prop1=1
    test.prop2=2
kind: ConfigMap
metadata:
  labels:
      app.kubernetes.io/name: nginx-test-deployment
    app.kubernetes.io/version: "1"
    app.domain/environment: dev
    app.domain/platform: testing.1-alpha
    app.domain/suite: testing
  name: test-properties
  namespace: test-dev

  test.properties: |
    test.prop1=1
    test.prop2=2
kind: ConfigMap
metadata:
  labels:
    app.domain/environment: dev
  name: test-properties
  namespace: test-dev
```
# Expected Output
```yaml
apiVersion: v1
data:
  cache.properties: |
    cache.dir=/tmp/cache
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: nginx-test-deployment
    app.kubernetes.io/version: "1"
    app.domain/environment: dev
    app.domain/platform: testing.1-alpha
    app.domain/suite: testing
  name: cache-properties
  namespace: test-dev
---
apiVersion: v1
data:apiVersion: v1
data:
  cache.properties: |
    cache.dir=/tmp/cache
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: nginx-test-deployment
    app.kubernetes.io/version: "1"
    app.domain/environment: dev
    app.domain/platform: testing.1-alpha
    app.domain/suite: testing
  name: cache-properties
  namespace: test-dev
```
# Kustomize Version
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Shell32-Natsu** [comment]
The version of kustomize that shipped with kubectl is very old. Please try the latest kustomize.

**Comment by jacoboldroyduvu** [comment]
Same issue.
# Kustomize v3.10.0
```bash
kustomize version
{Version:kustomize/v3.10.0 GitCommit:602ad8aa98e2e17f6c9119e027a09757e63c8bec BuildDate:2021-02-10T00:00:50Z GoOs:linux GoArch:amd64}
```
# Results Using Latest Kustomize
```bashkustomize build dev/
apiVersion: v1
data:
  cache.properties: |
    answer_to_everything: 42
kind: ConfigMap
metadata:
  labels:
    app.domain.com/environment: dev
    app.domain.com/platform: testing.1-alpha
    app.domain.com/suite: testing
  name: cache-properties
---
apiVersion: v1
data:
  test.properties: |
    test
kind: ConfigMap
metadata:
  labels:
    app.domain.com/environment: dev
  name: test-properties
```

# Simple Test Yaml
/base/kustomization.yaml
```yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: cache-properties
  files:
  - cache.properties
commonLabels:
  app.domain.com/suite: testing
  app.domain.com/platform: testing.1-alpha
```
/dev/kustomization.yaml
```yaml
bases:
- ../base/
configMapGenerator:
- name: test-properties
  files:
  - test.properties
generatorOptions:
  disableNameSuffixHash: true

commonLabels:
 app.domain.com/environment: dev
```
