### ISSUE TITLE
Pipefail Should be Set in Generator Shells

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes-sigs/kustomize#358]
In SecretGenerator shells, pipefail is not set and therefore you can get unexpected results when a command fails. Here's a minimal repro:

```yaml
---
secretGenerator:
  - name: pipefail-secret-test
    commands:
      test-0: exit 1 | tr -d '\n'
```

I'd expect kustomize to exit with non-zero status and produce an error message. Instead, there is no error reported, and an empty secret is created:

```bash
$ kustomize build /tmp/kustomize-test
apiVersion: v1
data:
  test-0: ""
kind: Secret
metadata:
  creationTimestamp: null
  name: pipefail-secret-test-kt9bcb4tb6
type: Opaque
$ echo $?
0
```
