### ISSUE TITLE
`kustomize edit add resource` deletes comment lines

### ISSUE THREAD

**Issue by dulltz** [kubernetes-sigs/kustomize#3587]
**Describe the bug**

After I ran `kustomize edit add resource`, the comment lines in `resources` are removed.

**Files that can reproduce the issue**

- kustomization.yaml
  ```yaml
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  resources:
  - namespace.yaml
  - install.yaml # https://raw.githubusercontent.com/argoproj/argo-rollouts/v0.10.2/manifests/install.yaml
  ```
- foo.yaml (empty ok)

and run the following command

```console
$ kustomize edit add resource foo.yaml
```

**Expected output**

```console
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- install.yaml # https://raw.githubusercontent.com/argoproj/argo-rollouts/v0.10.2/manifests/install.yaml
- foo.yaml
```

**Actual output**

```console
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- install.yaml
- foo.yaml
```

**Kustomize version**

```console
$ kustomize version
{Version:kustomize/v3.10.0 GitCommit:602ad8aa98e2e17f6c9119e027a09757e63c8bec BuildDate:2021-02-10T00:00:50Z GoOs:darwin GoArch:amd64}
```

**Platform**

```console
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H114
```

**Comment by rajeshkudaka** [comment]
This is using Unmarshal which uses yaml.YAMLToJSON() and then it is converted back to yaml in the process. When converting to JSON, as per the format it does not allow any comments, and when converted back to yaml there will be no comments.

yamltojson snip: https://github.com/kubernetes-sigs/kustomize/blob/release-kustomize-v3.10/api/types/kustomization.go#L198

**Comment by Shell32-Natsu** [comment]
I would like to remove these conversions but it will breaks many tests and I haven't had time to work on it.

**Comment by eddiezane** [comment]
Can you please confirm if this is still an issue on kustomize 4.x?

Also please test if comments above lines are working as expected. The issue might just lie with trailing comments.

**Comment by jlewi** [comment]
This looks to still be an issue with 

```
{Version:kustomize/v4.3.0 GitCommit:cd17338759ef64c14307991fd25d52259697f1fb BuildDate:2021-08-24T19:24:28Z GoOs:darwin GoArch:amd64}
```

Input kustomization

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: hello  # some inline comment.
```

Run

```
~/tmp/kustomize edit set image flink=flink:1234 
```

Output

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: hello
images:
- name: flink
  newName: flink
  newTag: "1234"
```

So the inline comment is stripped out.

The code [RunSetImage](https://github.com/kubernetes-sigs/kustomize/blob/4d002af7356776cf72a4a92ec5eb4d5c7b022b27/kustomize/commands/edit/set/setimage.go#L120)

is using unmarshal [here](https://github.com/kubernetes-sigs/kustomize/blob/4d002af7356776cf72a4a92ec5eb4d5c7b022b27/kustomize/commands/internal/kustfile/kustomizationfile.go#L169) to parse the file. This wouldn't preserve comments. So this code would most likely need to be changed to use kyaml to make the changes.
