### ISSUE TITLE
"Snippet" support

### ISSUE THREAD

**Issue by coryodaniel** [kubernetes-sigs/kustomize#360]
I'm grimacing as I'm making this request.

I know one of the goals is to be template free, but I'm curious if there is a place for "snippets" in kustomize.

My use case is working with filebeat's autodiscover mechanism for kubernetes. I have users that are using the ['raw'](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover-hints.html#_literal_co_elastic_logs_raw_literal) feature which is stringified JSON in a k8s annotation.

Here is an abbreviated example. They can get pretty complex.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    co.elastic.logs/raw: "[{\"multiline\":{"negate\":\"true\",\"pattern\":\"^test\"},\"type\":\"docker\"}]"
```

Currently its painful to edit with kustomize. We keep annotation hints in a separate file, edit it, minify it, then copy paste it into a resource.
