### ISSUE TITLE
`kustomize build` cause the panic with non-ASCII characters

### ISSUE THREAD

**Issue by 110y** [kubernetes-sigs/kustomize#3605]
**Describe the bug**

When I execute `kustomize build` with patches including comments with non-ASCII characters, it cause the panic like below:

```
panic: runtime error: index out of range [7] with length 6 [recovered]
        panic: runtime error: index out of range [7] with length 6
```

**Files that can reproduce the issue**

I've created the repository which can reproduce this issue: https://github.com/110y/kustomize-issue-3605

```
> git clone https://github.com/110y/kustomize-issue-3605.git
> cd kustomize-issue-3605
> kustomize build .
```

```
> cd kustomize-issue-3605
> cat kustomization.yaml
---
resources:
  - ./deployment.yaml

patchesStrategicMerge:
  - ./patch-deployment.yaml

> cat deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.6
          ports:
            - containerPort: 80

> cat patch-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 3 # 本番環境
```

**Expected output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.19.6
        name: nginx
        ports:
        - containerPort: 80
```

**Actual output**

```
panic: runtime error: index out of range [7] with length 6 [recovered]
        panic: runtime error: index out of range [7] with length 6
```

**Kustomize version**

- Linux
```
> kustomize version
{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-13T21:21:14Z GoOs:linux GoArch:amd64}
```

- macOS

```
> kustomize version
{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-13T21:21:14Z GoOs:darwin GoArch:amd64}
```

**Platform**

I've just checked this behavior with the following platforms:
- Linux
- macOS

**Additional context**

The same issue was already filed as https://github.com/kubernetes-sigs/kustomize/issues/3417. 
Although #3417 said:

> Seems that this issue is resolved in kustomize v3.9.2.

I think this problem is still reproducible [as my investigation](https://github.com/110y/kustomize-issue-3605).

**Comment by hansanghoon** [comment]
I have different observation regarding placement of the comment.

This doesn't cause problem in 4.0.1

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: quote-dev #한글한글
```

Those below cause problem.

```yaml
apiVersion: v1
kind: Namespace
metadata:
#한글한글
  name: quote-dev
```

or

```yaml
#한글한글
apiVersion: v1
kind: Namespace
metadata:
  name: quote-dev
```

```
panic: runtime error: index out of range [6] with length 5 [recovered]
	panic: runtime error: index out of range [6] with length 5
...
```

```
$ kustomize version
{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-14T05:00:02+00:00 GoOs:darwin GoArch:amd64}
```
