### ISSUE TITLE
Multiple matches for Id after kustomize v3.9.3

### ISSUE THREAD

**Issue by chicocvenancio** [kubernetes-sigs/kustomize#3609]
**Describe the bug**
Up until kustomize v3.9.2 it was possible to reuse a base in different overlays and use both the original and an overlay in a final overlay as long as the resource name was changed. Since kustomize v3.9.3 this returns an error `Error: multiple matches for Id apps_v1_Deployment|~X|deployment; failed to find unique target for patch` apps_v1_Deployment|deployment

**Files that can reproduce the issue**

#3608 is a test case that can reproduce the issue.

**Comment by natasha41575** [comment]
Thanks for submitting the issue and a test for it! I've reviewed your PR and left a couple comments

**Comment by dorianmariefr** [comment]
/reopen

I'm experiencing this with `Error: multiple matches for Id HorizontalPodAutoscaler.v2beta2.autoscaling/...`

**Comment by avli** [comment]
I have encountered the same issue using version 5.6.0. Below is a minimal layout to reproduce it (try rendering `parent`). Everything works as expected with version 3.9.2, as noted in the original report.


```
base/
  deployment.yaml
  kustomization.yaml

layer-a/
  kustomization.yaml

layer-b/
  kustomization.yaml

parent/
  kustomization.yaml
```

`base/deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
```

`base/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
```

`layer-a/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-a
resources:
  - ../base
```

`layer-b/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ns-b
resources:
  - ../layer-a
```

`parent/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../layer-a
  - ../layer-b
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: myapp
        namespace: ns-a
      spec:
        replicas: 2
```
