### ISSUE TITLE
`protocol` field in base config ports spec sometimes results in an empty ports list

### ISSUE THREAD

**Issue by taneliang** [kubernetes-sigs/kustomize#3620]
**Describe the bug**

If a `protocol` field is specified in a service's ports spec in the base config, it will be omitted from the build output if the patch also has a ports spec with the same port numbers. More variations tried are listed at the bottom.

**Files that can reproduce the issue**

https://github.com/taneliang/kustomize-protocol-issue-repro. Reproduced below for convenience:

kustomization.yaml

```yaml
---
resources:
  - ./deployment.yaml

patchesStrategicMerge:
  - ./patch-deployment.yaml
```

deployment.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 30900
      targetPort: 30900
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
```

patch-deployment.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
spec:
  ports:
    - port: 30900
      targetPort: 30900
  selector:
    service: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
```

**Expected output**

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
spec:
  ports:
  - port: 30900
    protocol: TCP
    targetPort: 30900
  selector:
    service: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
```

**Actual output**

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
spec:
  ports: [] # <-- this is empty
  selector:
    service: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
```

**Kustomize version**

{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-14T05:00:02+00:00 GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

Variations of the repro files above I've tried:

* Specified `protocol: UDP` instead of TCP: issue remains
* Specified different port numbers in the patch config: resulting ports array contains the base ports, but not the patch ports
* Removed `protocol: TCP` from the base config (i.e. both configs don't have a `protocol` field set): resulting ports array is correct
* Specified `protocol: TCP` in the patch config instead of the base config: resulting ports array is correct
* Specified `protocol: TCP` in both configs: resulting ports array is correct

I don't believe this can be reproduced on v3.9.2, so the cause was likely introduced between 3.9.2 and 4.0.1
