### ISSUE TITLE
[Question] Support podAntiAffinity

### ISSUE THREAD

**Issue by qnapnickchang** [kubernetes-sigs/kustomize#3623]
Hi,

We want to deploy same service to different worker nodes. 
If I have a lot of deployment, How to write a template for any deployment? 

below is our sample : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxxxx
  namespace: default

spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - xxxxx
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - xxxxx
              topologyKey: kubernetes.io/hostname
            weight: 100
```

Thanks
