### ISSUE TITLE
[Question] kustomize plugin custom

### ISSUE THREAD

**Issue by basefas** [kubernetes-sigs/kustomize#3624]
Hello，I want to develop my own kustomize plugin, so I follow the guide
https://kubectl.docs.kubernetes.io/guides/extending_kustomize/gopluginguidedexample/
to install kustomize.

Then I copy all files in
https://github.com/kubernetes-sigs/kustomize/tree/master/plugin/builtin/configmapgenerator
instead of clone the sopsencodedsecrets project as my own plugin, and rename configmapgenerator as configmapg

```
//kustomize/plugin/someteam.example.com/v1/configmapg/ConfigMapG.go
package main

import (
	"fmt"

	"sigs.k8s.io/kustomize/api/kv"
	"sigs.k8s.io/kustomize/api/resmap"
	"sigs.k8s.io/kustomize/api/types"
	"sigs.k8s.io/yaml"
)

type plugin struct {
	h                *resmap.PluginHelpers
	types.ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
	types.ConfigMapArgs
}

//noinspection GoUnusedGlobalVariable
var KustomizePlugin plugin

func (p *plugin) Config(h *resmap.PluginHelpers, config []byte) (err error) {
	p.ConfigMapArgs = types.ConfigMapArgs{}
	fmt.Println(config)

	err = yaml.Unmarshal(config, p)
	if p.ConfigMapArgs.Name == "" {
		p.ConfigMapArgs.Name = p.Name
	}
	if p.ConfigMapArgs.Namespace == "" {
		p.ConfigMapArgs.Namespace = p.Namespace
	}
	p.h = h
	fmt.Println(p)
	return
}

func (p *plugin) Generate() (resmap.ResMap, error) {
	fmt.Println(p.ConfigMapArgs)
	return p.h.ResmapFactory().FromConfigMapArgs(
		kv.NewLoader(p.h.Loader(), p.h.Validator()), p.ConfigMapArgs)
}
```

```
//kustomize/plugin/someteam.example.com/v1/configmapg/ConfigMapG_test.go
package main_test

import (
	"testing"

	kusttest_test "sigs.k8s.io/kustomize/api/testutils/kusttest"
)

func TestConfigMapG(t *testing.T) {
	th := kusttest_test.MakeEnhancedHarness(t).
		BuildGoPlugin("someteam.example.com", "v1", "ConfigMapG")
	defer th.Reset()

	th.WriteF("devops.env", `
SERVICE_PORT=32
`)
	th.WriteF("uxteam.env", `
COLOR=red
`)

	rm := th.LoadAndRunGenerator(`
apiVersion: someteam.example.com/v1
kind: ConfigMapG
metadata:
  name: myMap
envs:
- devops.env
- uxteam.env
literals:
- FRUIT=apple
- VEGETABLE=carrot
`)

	th.AssertActualEqualsExpected(rm, `
apiVersion: v1
data:
  COLOR: red
  FRUIT: apple
  SERVICE_PORT: "32"
  VEGETABLE: carrot
kind: ConfigMap
metadata:
  name: myMap
`)
}
```

```
//kustomize/plugin/someteam.example.com/v1/configmapg/go.mod
module sigs.k8s.io/kustomize/plugin/builtin/configmapg

go 1.15

require (
	sigs.k8s.io/kustomize/api v0.8.1
	sigs.k8s.io/yaml v1.2.0
)

replace sigs.k8s.io/kustomize/kyaml => ../../../../kyaml

replace sigs.k8s.io/kustomize/api => ../../../../api
```
Run go test ConfigMapG_test.go, and everything is OK.
But I change flag "envs" to "files", the test does not passed.

LOG is 
```
apiVersion: v1
data:
  FRUIT: apple
  VEGETABLE: carrot
  devops.env: |2

    SERVICE_PORT=32
  uxteam.env: |2

    COLOR=red
kind: ConfigMap
metadata:
  name: myMap
```
I expect the result is 

```
apiVersion: v1
data:
  FRUIT: apple
  VEGETABLE: carrot
  devops.env: |-
    SERVICE_PORT=32
  uxteam.env: |-
    COLOR=red
kind: ConfigMap
metadata:
  name: myMap
```

I have no idea with this, thank you for your help.
