### ISSUE TITLE
Is it possible Kustomize namespaces?

### ISSUE THREAD

**Issue by philwinder** [kubernetes-sigs/kustomize#364]
My first use case was to kustomize the namespace creation. I want to do this because there will be annotations to the namespace which are namespace specific. Eventually I see different bases, but a simple example would be this:

```
cat <<EOF > ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    iam.amazonaws.com/permitted: .*
EOF

cat <<EOF > kustomization.yaml
namespace: test
resources:
- ns.yaml
EOF

kustomize build .
```

However, when it outputs, it doesn't set the namespace.

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    iam.amazonaws.com/permitted: .*
```

Is this possible?

Thanks, Phil
