### ISSUE TITLE
[Question]How to patch service account?

### ISSUE THREAD

**Issue by Magicloud** [kubernetes-sigs/kustomize#3660]
This seems quite simple yet I cannot figure out.

SA manifest (from cert-manager) (already applied)
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-cert-manager
  namespace: "my-ns"
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "controller"
    helm.sh/chart: cert-manager-v1.2.0
```

My patch
```
- op: add
  path: "/metadata/annotations/eks.amazonaws.com~1role-arn"  
  value: "arn:aws:iam::012345678901:role/my-cert-manager"
```

My kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- path: patch-service-account.yaml
  target:
    version: v1
    kind: ServiceAccount
    name: cm-cert-manager
```

With or without namespace, `kubectl apply -k .` failed similarly. Without namespace, I got:

`error: couldn't find target ~G_v1_ServiceAccount|~X|~P|cm-cert-manager|~S for json patch`
