### ISSUE TITLE
Var referencing key in secret in HelmChartInflationGenerator is not interpolated

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes-sigs/kustomize#3674]
**Describe the bug**
Var referencing key in secret in HelmChartInflationGenerator is not interpolated

**Files that can reproduce the issue**

```
cat << EOF > postgresql.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: postgresql
releaseName: postgresql
chartName: postgresql
chartVersion: 10.3.2
chartRepoUrl: https://charts.bitnami.com/bitnami
valuesLocal:
  postgresqlUsername: foobar
  postgresqlDatabase: foobar
  postgresqlPassword: $(DATABASE_PASSWORD)
EOF
```

```
cat << EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

namespace: foobar

generators:
  - postgresql.yaml

secretGenerator:
- name: foobar-secrets
  literals:
    - PASSWORD=s3cr3t

vars:
  - name: DATABASE_PASSWORD
    fieldref:
      fieldPath: data.PASSWORD
    objref:
      apiVersion: v1
      kind: Secret
      name: foobar-secrets
EOF
```
```
cat << EOF > deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
spec:
  selector:
    matchLabels:
      app: foobar
  template:
    metadata:
      labels:
        app: foobar
    spec:
      containers:
        - image: foobar/foobar
          imagePullPolicy: IfNotPresent
          name: foobar
          envFrom:
            - secretRef:
                name: foobar-secrets
EOF
```

**Expected output**

- postgresql is using `s3cr3t` password
- foobar deployment has `PASSWORD=s3cr3t` env variable
- there is no need to create shared password multiple times

**Actual output**

- postgres is using `$(DATABASE_PASSWORD)` as database password

**Kustomize version**

v4.0.1

**Platform**

Linux

**Additional context**

No
