### ISSUE TITLE
YAML Anchor support

### ISSUE THREAD

**Issue by george-angel** [kubernetes-sigs/kustomize#3675]
Starting from `kustomize/v4.0.0` - there is no way for us to build manifests that contain yaml anchors. Previously we were able to workaround by setting `--enable_kyaml=false`.

Example:

proximo.yaml

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: &app proximo
    uw.systems/mirror: "true"
  name: *app
spec:
  ports:
  - name: ops
    port: 8080
    protocol: TCP
  - name: http
    port: 6868
    protocol: TCP
  selector:
    app: *app
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proximo.yaml
```

Trying to do a build:

```
$ kustomize build .
Error: considering field 'metadata/name' of object
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: &app proximo
    uw.systems/mirror: "true"
  name: *app
spec:
  ports:
  - name: ops
    port: 8080
    protocol: TCP
  - name: http
    port: 6868
    protocol: TCP
  selector:
    app: *app
: wrong Node Kind for metadata.name expected: ScalarNode was AliasNode: value: {*app}
```

Thank you.

**Comment by eddiezane** [comment]
@KnVerey to reply

**Comment by KnVerey** [comment]
Several issues have been opened about this YAML anchor regression, which affects v4+ universally and v3+ if kyaml is enabled. Although they don't all result in the same error message, it seems to me that they are all related to the switch from apimachinery to kyaml. To that end, I'm going to close the various other issues and consolidate on this one. 

If a community member would be interested in diving in to restore YAML anchor support, we would be happy to accept the changes. That said, given the effort involved, it would be helpful to have more information about the purpose of the feature from those who have historically been using it. YAML anchors provide a way to reuse configuration snippets, but in the examples I've seen so far, the same result could be achieved with Kustomize-native mechanisms (patches, commonLabels, etc.). This is even more true now that the extremely powerful ReplacementsTranformer has merged. It would be helpful to have more information as to why and in which cases YAML anchors are being preferred. 

If there isn't interest in contributing support, and effective results can be achieve within Kustomize's own mechanisms, we should instead consider simplifying by removing the feature entirely (as some other projects [have chosen to do](https://hitchdev.com/strictyaml/why/node-anchors-and-references-removed/)) and providing clear error messages to that effect.

If you use YAML anchors with Kustomize, please comment with more context to help us understand why this feature is important to you.

/triage under-consideration

**Comment by levsha** [comment]
Anchors are part of YAML specification. Just dropping anchors instead of properly implementing YAML parser will mean that it will be not correct to claim that configuration is written in YAML.

**Comment by levsha** [comment]
@KnVerey can you please show how the example from https://github.com/kubernetes-sigs/kustomize/issues/3614 can be solved with kustomize-native mechanisms?

**Comment by diarmuidie** [comment]
In my case I'm using YAML anchors not by choice, but because they are present in the the third party YAML that my customise is overlaying on. Knative is an example of this: https://github.com/knative/serving/blob/8a9bb8e5f2f6959d0de2119498e32102dc2df942/config/core/deployments/webhook.yaml#L100

Because I don't control the code it's not practical to remove the anchors.

**Comment by metasim** [comment]
This has been a major PITA for us (we used anchor/aliases to DRY in our infrastructure). Our workaround was to create a `kustomize` generator that looks something like this:

`ExplodeAnchors`
```bash
#!/usr/bin/env bash
# Workaround for https://github.com/kubernetes-sigs/kustomize/issues/3614
if ! [ -x "$(command -v yq)" ]; then
  echo "Error: please install yq."
  exit 1
fi

shift # skip config file. exec plugins pass 'argsOneLiner'
SRC="$@"

# Invoke on specified source yml
yq eval 'explode(.)' "$SRC"
```

When placed in your kustomize plugin path as `kustomize/plugin/astraea.io/v1/ExplodeAnchors/ExplodeAnchors` it can be invoked something like this:

`kust-3614-hack.yaml`
```yaml
# This should hopefully go away once
# https://github.com/kubernetes-sigs/kustomize/issues/3614 is resolved
apiVersion: astraea.io/v1
kind: ExplodeAnchors
metadata:
  name: explode-anchors
argsOneLiner: <file to explode>.yaml
```

`kustomization.yaml`
```yaml
generators:
  - kust-3614-hack.yaml
```

ref: https://github.com/kubernetes-sigs/kustomize/issues/3614
