### ISSUE TITLE
Question: how to handle user input parameters within custom resource

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-sigs/kustomize#3677]
Hi, I'm working on the [KubeVela](https://kubevela.io/#/) project and trying to use Kustomize to handle multi-environment application deployment. We have a CRD that looks like below:

```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: website
spec:
  components:
    - name: backend
      type: worker
      settings:
        image: busybox
        cmd:
          - sleep
          - '1000'
    - name: frontend
      type: webservice
      settings:
        image: nginx
      traits:
        - name: autoscaler
          properties:
            min: 1
            max: 10
        - name: sidecar
          properties:
            name: "sidecar-test"
            image: "fluentd"
```

I'm super excited about the upcoming support for custom resource via OpenAPI schema. I have been hoping  that once applying openapi schema we can use Kustomize native patchesStrategicMerge over our Application resources too.

I give it a try -- here is main.go and schema.json: https://gist.github.com/hongchaodeng/2a3fe0afcb7ab2e116d2533e407ce151

But something unexpected happens. The fields `settings` and `properties` are unstructured user input and of type `runtime.RawExtension`. The schema couldn't be know ahead of time and in openapi schema is described as `object` type:

```json
"settings": {
  "type": "object",
  "x-kubernetes-preserve-unknown-fields": true
}
```

The problem is when applying patches it overrides instead of merging fields. Let me give an example below.

Here's the base:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: example
spec:
  components:
    - name: backend
      type: worker
      settings:
        change: change
        keep: keep
```
Here's the patch:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: example
spec:
  components:
    - name: backend
      settings:
        change: done
        new: new
```

Here will be the final output:
```yaml
apiVersion: core.oam.dev/v1alpha2
kind: Application
metadata:
  name: example
spec:
  components:
    - name: backend
      settings:
        change: done
        new: new
```

As shown above, the `keep` field is gone since the entire `settings` is overriden.

Would appreciate any solutions for this problem. Thanks!
