### ISSUE TITLE
Poor error reporting when using an executable plugin

### ISSUE THREAD

**Issue by graemerobertson** [kubernetes-sigs/kustomize#3681]
**Describe the bug**

I'm using a custom executable plugin (https://github.com/kubernetes-sigs/kustomize/tree/master/plugin) to manipulate my YAML documents.

Sometimes my plugin results in invalid YAML, and I get error messages that look like this:

```
Error: yaml: line 25: did not find expected key
```

However, that line number is not useful (if it's meaningful I'm not sure what it means - even knowing my error I can't correlate the line number with anything).

One way or another it would be extremely useful if I could see the invalid YAML - i.e. I think I just need access to the `output` variable at https://github.com/kubernetes-sigs/kustomize/blob/1d524b6fbe27178961657539756acc16c4be2b82/api/internal/plugins/utils/utils.go#L152.

**Files that can reproduce the issue**

Contrived minimal example using the [SedTransformer](https://github.com/kubernetes-sigs/kustomize/blob/1d524b6fbe27178961657539756acc16c4be2b82/plugin/someteam.example.com/v1/sedtransformer/SedTransformer)

_kustomization.yaml_

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
transformers:
- transformer.yaml
```

_resources.yaml_

```
apiVersion: someteam.example.com/v1
data:
  FOO: BAR.example
kind: ConfigMap
metadata:
  name: test-configmap
```

_transformer.yaml_

```
apiVersion: v1
kind: SedTransformer
metadata:
  name: sed-transformer
argsOneLiner: s/BAR/\"BAR\"/
```

_.config/kustomize/plugin/someteam.example.com/v1/sedtransformer/SedTransformer_

```
#!/bin/bash

# Skip the config file name argument.
shift
args=()
for arg in "$@"; do
  args+=(-e "$arg")
done

sed "${args[@]}"
```

**Expected output**

As alluded to above, I'm not 100% sure. At the very least I need access to that `output` variable, which in this example looks like this:

```
apiVersion: v1
data:
  FOO: "BAR".example
kind: ConfigMap
metadata:
  annotations:
    kustomize.config.k8s.io/id: |
      kind: ConfigMap
      name: test-configmap
      version: v1
  name: test-configmap
```

**Actual output**

```
~/tmp $ KUSTOMIZE_PLUGIN_HOME=.config/kustomize/plugin ~/src/kustomize/kustomize/kustomize build . --enable-alpha-plugins --load-restrictor LoadRestrictionsNone
Error: yaml: line 2: did not find expected key
```

**Kustomize version**

I'm reproing on master at the moment - commit `1d524b6fbe27178961657539756acc16c4be2b82` - but I've also reproed on older versions.

**Platform**

Linux
