### ISSUE TITLE
Image setting cannot override if digest is given in the original manifest

### ISSUE THREAD

**Issue by iben12** [kubernetes-sigs/kustomize#3682]
**Describe the bug**
Given a manifest that contains an image reference in the format of `image-name:tag@sha:1111` and using image tag setting with kustomize will not update the image in the build output. Removing the digest from the original manifest helps, but setting a new digest in `kustomization.yaml` does not.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: nginx
  newTag: 19.0.4
```

deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-app
  namespace: default
  labels:
    app:  test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  test-app
    spec:
      containers:
      - name:  test-app
        image:  nginx:latest@sha:1111
      restartPolicy: Always
```

**Expected output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-app
  namespace: default
  labels:
    app:  test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  test-app
    spec:
      containers:
      - name:  test-app
        image:  nginx:19.0.4
      restartPolicy: Always
```
**Actual output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-app
  namespace: default
  labels:
    app:  test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  test-app
    spec:
      containers:
      - name:  test-app
        image:  nginx:latest@sha:1111
      restartPolicy: Always
```

**Kustomize version**

`{Version:kustomize/v3.9.3 GitCommit:1ae8303bdc9372bc7c15942df6e9cf5d67fdba1a BuildDate:2021-02-07T18:28:40+00:00 GoOs:darwin GoArch:amd64}`

**Platform**

macOS
