### ISSUE TITLE
YAML directives cause error

### ISSUE THREAD

**Issue by paulyhedral** [kubernetes-sigs/kustomize#369]
If any of the input documents during a `kustomize build` contain YAML directives, an error is produced:
```
Error: loadResMapFromBasesAndResources: SemiResources: loadResMapFromBasesAndResources: rawResources failed to read Resources: YAML file [roles.yaml] encounters a format error.
error converting YAML to JSON: yaml: found incompatible YAML document
```

Example:
```yaml
%YAML 1.2
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  ...
```
