### ISSUE TITLE
[Question] Status of $patch (Strategic Merge Patch) support for Custom Resources

### ISSUE THREAD

**Issue by yanniszark** [kubernetes-sigs/kustomize#3694]
### Question

Do CustomResources support Strategic Merge Patch in kustomize? Specifically for `$patch: delete`.
Can I rely on this feature? It seems to work on 4.0.4 but not on 3.2.0. I couldn't find an issue / pr solving it (except https://github.com/kubernetes-sigs/kustomize/issues/2056 which doesn't include a closing PR), so I'm not sure if this was solved by accident or is a supported feature.

### Scenario

Given the kustomization:

`kustomization.yaml`
```yaml
resources:
- example-cr.yaml

patches:
- patch: |-
    $patch: delete
    apiVersion: "*"
    kind: "*"
    metadata:
      name: "*"
  target:
    kind: ExampleCR
```

`example-cr.yaml`
```yaml
apiVersion: example/v1
kind: ExampleCR
metadata:
  name: example
spec:
  example: example

```

### Outcomes

Version 3.2.0 outputs:
```yaml
$patch: delete
apiVersion: example/v1
kind: ExampleCR
metadata:
  name: example
spec:
  example: example
```

Version 4.0.4 outputs nothing (as expected).
