### ISSUE TITLE
[Question] overwriting environment variables when using the two strategies patchesStrategicMerge and patches.

### ISSUE THREAD

**Issue by keidevs** [kubernetes-sigs/kustomize#3696]
i patching the environment variables of the deployment workload using two strategies: patchesStrategicMerge and patches.

The environment variables patched in each strategy is different, but the problem occurs that the environment variables defined in patches overwrite the contents defined in patchesStrategicMerge.

Environment variables for each deployment workload are defined through patchesStrategicMerge, and common environment variables that the deployment workload should have are defined through patches(deployment-patch.yaml).

In patchesStrategicMerge, if environment variables a,b are defined, and in patches, environment variables c,d,e are defined, the environment variables a,b are overwritten and finally only c,d,e environment variables remain in the yaml file. There is.

How to solve this problem?

My kustomization.yaml

```
resources:
- ../base
namespace: xx
patchesStrategicMerge:
- resource.yaml
- labels.yaml
- env-var.yaml (patch deployment environment variable)
images:
- name: blahblah
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: deployment-patch.yaml (patch deployment environment variable)
  target:
    kind: Deployment

```

**Comment by keidevs** [comment]
@Shell32-Natsu 

env-var.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: PHASE
              value: "in_house_development"
            - name: FLASK_ENV
              value: "development"
```

deployment-patch.yaml
```
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: DD_ENV
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['tags.datadoghq.com/env']
```


kustomize build .  (remove PHASE, FLASK_ENV Environment)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: in_house_development
    tags.datadoghq.com/service: super-api
    tags.datadoghq.com/version: 0.0.0.1
  name: super-api
  namespace: in-house-super
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-backend
      component: api
  template:
    metadata:
      labels:
        app: super-backend
        component: api
        environment: dev
        tags.datadoghq.com/env: in_house_development
        tags.datadoghq.com/service: super-backend-api
        tags.datadoghq.com/version: 0.0.0.1
    spec:
      containers:
       env:
              - name: DD_ENV(only exist DD_ENV)
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/env']
                ...
                ..
```
