### ISSUE TITLE
Generate CRD object from file

### ISSUE THREAD

**Issue by antonionappi88** [kubernetes-sigs/kustomize#3728]
Hello, 
I'd like to generate a CRD object from a file. Is there a way without writing my own generator ?

In particular I have a file with Prometheus rule:

```
  groups:
  - name: mygroup
    rules:
    - alert: QueueSize
      annotations:
        description: Queue has reached {{$value}} items in the past 20 minutes
        summary: '{{$labels.application}} [{{$labels.instance}}]: Queue threshold
          exceeded'
      expr: Queue_size{environment="TEST"} > 3500 and ON()( hour() >= 8 <17
        )
      for: 20m
```
and I'd like that kustomize generates the below object out of the file above.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus
    role: alert-rules
  name: alert-rules
  namespace: monitoring
spec:
  groups:
  - name: mygroup
    rules:
    - alert: QueueSize
      annotations:
        description: Queue has reached {{$value}} items in the past 20 minutes
        summary: '{{$labels.application}} [{{$labels.instance}}]: Queue threshold
          exceeded'
      expr: Queue_size{environment="TEST"} > 3500 and ON()( hour() >= 8 <17
        )
      for: 20m
```

Thanks,
Antonio
