### ISSUE TITLE
Wrong namespace set when combining two versions of a base containing a ValidatingWebhookConfiguration

### ISSUE THREAD

**Issue by dfsdevops** [kubernetes-sigs/kustomize#3732]
**Describe the bug**
This bug manifests only with a very specific set of conditions in a single kustomization.yaml file that meets the following two conditions.
1. It pulls in a resource containing both a ValidatingWebhookConfiguration and a corresponding Service. (It seems to require having a corresponding name to the service name to replicate this bug)
    ```yaml
    ---
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization

    resources:
    - service.yaml
    - validatingwebhook.yaml
    ```
2. It pulls in another resource containing a kustomization.yaml file that pulls in the aforementioned base and overrides the namespace and deletes the validatingWebhookConfiguration object via a `$patch: delete` directive.
    ```yaml
    ---
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    namespace: merge-namespace

    resources:
    - ../no1

    patchesStrategicMerge:
    ##deletions
    - validatingwebhookdelete.yaml
    ```

Each of the two "base" resources described above work as expected when running `kustomize build` alone on their respective directories. Number 1 will create both a Service and ValidatingWebhook. Number 2 will just create just a service.

When combined into a single file such as:
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../no1
- ../no2
```
The validatingWebhookConfiguration file ends up with the wrong namespace reference in the clientConfig, instead of the one from the base.

```yaml
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validatingwebhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: admission
      namespace: merge-namespace
      path: /networking/v1beta1/ingresses
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
```

**Files that can reproduce the issue**
I have created a pull request using krusty that replicates the issue and shows what I believe the desired output to be.
https://github.com/kubernetes-sigs/kustomize/pull/3731

**Expected output**

The ValidatingWebhookConfiguration object maintains the namespace reference from the original base resource.

**Actual output**

The ValidatingWebhookConfiguration object has its clientConfig's namespace reference changed to that of the `namespace:` directive in the secondary kustomize file.

**Kustomize version**

4.5.0

**Platform**

macOS

**Additional context**

An example of the type of scenario where this could manifest: Running two ingress-nginx controllers in parallel.
If there is no `Service` object in the base, this bug does not show up.
