### ISSUE TITLE
configMapGenerator `merge` behavior still seems broken

### ISSUE THREAD

**Issue by pslobo** [kubernetes-sigs/kustomize#3741]
Problem reported in #3393 with 3.9.0 still seems to exist in 4.0.5.

```
❯ kustomize version
{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T22:48:12+00:00 GoOs:darwin GoArch:amd64}
```

Replicated with a simple test with the following structure:

```
❯ tree .
.
├── base
│   ├── config.yaml
│   └── kustomization.yaml
└── dev
    ├── config.yaml
    └── kustomization.yaml

❯ cat base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: my-map
   files:
     - config.yaml


❯ cat base/config.yaml
conf:
  key1: value1
  key2: value2

❯ cat dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

configMapGenerator:
  - name: my-map
    behavior: merge
     files:
       - config.yaml

❯ cat dev/config.yaml
conf2:
  key1: value1
  key2: value2

```

I would expect the output of the dev overlay to be a merge between the 2 configs (super simple), but instead it overrides the base. Am I missing something obvious here, or just not understanding the merge behavior?

**Actual results**

```
❯ kustomize build base/
apiVersion: v1
data:
  config.yaml: |+
    conf:
      key1: value1
      key2: value2

kind: ConfigMap
metadata:
  name: my-map-d8592h5b46

❯ kustomize build dev/
apiVersion: v1
data:
  config.yaml: |
    conf2:
      key1: value1
      key2: value2
kind: ConfigMap
metadata:
  name: my-map-bgdbtm727c
```
