### ISSUE TITLE
[Question] Is the issue of ClusterRoleBinding.subjects.namespace still not resolved in v4.0.5?

### ISSUE THREAD

**Issue by stemid** [kubernetes-sigs/kustomize#3745]
There seem to be several closed issues about this, #1377, #136 and #2717 are some I found.

But namespace is still not being inserted into ClusterRoleBinding.subjects, one of the issue says I must use namespace: default but this also causes errors for me.

I just don't understand this error: `Error: accumulating resources: accumulation err='accumulating resources from 'fluentd.yaml': yaml: line 56: did not find expected key': got file 'fluentd.yaml', but '/home/stemid/Utveckling/efk-stack/kustomize/base/fluentd.yaml' must be a directory to be a root`

I know it stems from this DaemonSet because if I remove it from the fluentd.yaml file kustomize build works. Here is the entire fluentd.yaml file;

```yaml
apiVersion: v1   
kind: ServiceAccount                      
metadata:                                
  name: fluentd
  namespace: default
  labels:
    app: fluentd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd

rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: default

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd

spec:
  selector:
    matchLabels:
      app: fluentd

  template:
    metadata:
      namespace: default
      name: fluentd
      labels:
        app: fluentd

    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.12-debian-elasticsearch7-1
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch.kube-logging.svc.cluster.local"
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        - name: FLUENTD_SYSTEMD_CONF
          value: disable

          resources:
            limits:
              memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
          volumeMounts:
            - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true

      volumes:
        - name: varlog
          hostPath:
            path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

**Comment by Shell32-Natsu** [comment]
At the end of you yaml file there is a syntax error.

```
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
      - name: varlibdockercontainers        <== here
        hostPath:
          path: /var/lib/docker/containers
```
