### ISSUE TITLE
Issue when adding multiple elements to an array using patchesJson6902 add op

### ISSUE THREAD

**Issue by ajonkisz** [kubernetes-sigs/kustomize#3752]
**Describe the bug**

Adding multiple array elements to an array using `patchesJson6902` and `op: add` does not behave as expected.

**Files that can reproduce the issue**
Example:

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1

patchesJson6902:
  - target:
      kind: test
      name: test
    patch: |-
      - op: add
        path: /someArray/-
        value:
          - element2
          - element3

resources:
  - resources.yaml
```

resources:
```
kind: test
metadata:
  name: test
someArray:
  - element0
  - element1
```

**Expected output**

```
kind: test
metadata:
  name: test
someArray:
- element0
- element1
- element2
- element3
```

**Actual output**

```
kind: test
metadata:
  name: test
someArray:
- element0
- element1
- - element2
  - element3
```

**Kustomize version**

Tested on v3.8.7 as well as v4.0.5

**Platform**

Both Linux and Windows have been tested

**Additional Notes**
Specifying multiple add operations in the patch as:
```
- op: add
  path: /someArray/-
  value: element2
- op: add
  path: /someArray/-
  value: element3
```
Works as expected, but this is rather cumbersome and shouldn't be necessary if the type can be detected the type we're adding to is an array.
