### ISSUE TITLE
Patch is applied twice to a suffixed copy of a resource

### ISSUE THREAD

**Issue by walkbooth** [kubernetes-sigs/kustomize#3753]
**Describe the bug**

I'm seeing behavior involving the `nameSuffix` transformer where a suffixed copy of a resource gets the same patch applied twice.

**Files that can reproduce the issue**

Here is the example's directory structure:
```bash
$ tree bug
├── base
│   ├── deployment.yaml
│   └── kustomization.yaml
├── common
│   └── kustomization.yaml
├── example
│   └── kustomization.yaml
├── example-suffix
│   └── kustomization.yaml
└── overlay
    └── patches
        └── kustomization.yaml
```

base/deployment.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: example
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - args: []
        image: example
        name: example
```

base/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
```

common/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example
- ../example-suffix
```

example/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
```

example-suffix/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: example-suffix
nameSuffix: -suffix
```

overlay/patches/kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: example
    namespace: example
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--this-should-not-be-duplicated"
- target:
    group: apps
    version: v1
    kind: Deployment
    name: example-suffix
    namespace: example-suffix
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--this-should-not-be-duplicated"
```

**Expected output**
`$ kustomize build bug/overlay/patches`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
  name: example-suffix
  namespace: example-suffix
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - args:
        - --this-should-not-be-duplicated
        image: example
        name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
  name: example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - args:
        - --this-should-not-be-duplicated
        image: example
        name: example
```

**Actual output**
`$ kustomize build bug/overlay/patches`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
  name: example-suffix
  namespace: example-suffix
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - args:
        - --this-should-not-be-duplicated
        - --this-should-not-be-duplicated
        image: example
        name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
  name: example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - args:
        - --this-should-not-be-duplicated
        image: example
        name: example
```

**Kustomize version**

{Version:kustomize/v3.8.9 GitCommit:f30fea4c072c794e9b936f20bd1592d9fa25d976 BuildDate:2020-12-29T15:54:49Z GoOs:darwin GoArch:amd64}

**Platform**

Linux, macOS

**Additional context**

I'm able to work around this by removing the namespace keyword from `bug/base/deployment.yaml`, and adding a namespace transformer to `bug/example/kustomization.yaml`:
```
$ diff -r bug fix
diff -r bug/base/deployment.yaml fix/base/deployment.yaml
5d4
<   namespace: example
diff -r bug/example/kustomization.yaml fix/example/kustomization.yaml
5a6,7
> 
> namespace: example
```

I can also work around this by using a single patch in the `patches` keyword instead of two patches in `patchesJson6902` in `bug/overlay/patches/kustomization.yaml`, targeting all resources with the `app=example` label:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    labelSelector: "app=example"
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--this-should-not-be-duplicated"
```
While I'm happy to implement either of these workarounds, it's not immediately clear why these workarounds resolve the problem, which is why I decided to create an issue.
