### ISSUE TITLE
components combine all commonLabels and last-write wins

### ISSUE THREAD

**Issue by Jackbennett** [kubernetes-sigs/kustomize#3770]
**Describe the bug**

commonLabels defined in `components` bubble up to the entire config to label every other resource. It is also last-write-wins of the label key.

**Short reproduction of the issue**

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../ingress_config/ # commonLabel project=example
resources:
  - ../../component_as_kind_kustomization/ # commonLabel app=Expected
components:
  - ../../component_kind_a # commonLabel app=A
  - ../../component_kind_b # commonLabel app=B
```

**Expected output**

Every label should only exist from the kustomization.yml it's defined in or down. using a commonLabel from a component is nonsensical. If I wanted this behaviour I could use commonLabel inside the same kustomization as lists the components.

**Actual output**

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: B # wat?!?!
    project: example
  name: cloud

```

**Full working files example to reproduce the issue**
files:  https://github.com/Jackbennett/bugs-kustomize/blob/master/deployed/development/apply/all.yaml

**Actual output**
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: component_b # please no
    for: github
  name: devices
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: component_b # please no
    for: github
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: component_b
    for: github
  name: portal
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: component_b
    for: github
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: component_b # please no
    for: github
    project: overall_example
  name: cloud
spec:
  rules:
  - host: patched.example.com
    http:
      paths:
      - backend:
          serviceName: testing
          servicePort: 80
```

**Desired output**
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: component_a
    for: github
  name: devices
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: component_a
    for: github
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: component_b
    for: github
  name: portal
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: component_b
    for: github
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    for: github
    project: overall_example
  name: cloud
spec:
  rules:
  - host: patched.example.com
    http:
      paths:
      - backend:
          serviceName: testing
          servicePort: 80
```
**Kustomize version & Platform**

```bash
kustomize version
{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}

cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Additional context**

Been watching the other commonLabel issue, seems like the implementation of this is super aggressive in unexpected ways.

neither the following have the word `label` on it so I believe this is undefined behavour
* https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1802-kustomize-components/README.md
* https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md
