### ISSUE TITLE
Immutable ConfigMaps creation via configMapGenerator

### ISSUE THREAD

**Issue by KeisukeYamashita** [kubernetes-sigs/kustomize#3776]
**Is your feature request related to a problem? Please describe.**

This is not problem related.

**Describe the solution you'd like**

I want to configure `immutable` configMaps for ConfigMaps that were generated by `configMapGenerator`.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  ...
data:
  ...
immutable: true <-- Here
```

**Additional context**

These are the references:

* [ConfigMaps](https://kubernetes.io/docs/concepts/configuration/configmap/)
* [Kubernetes 1.18 Introduces Immutable ConfigMaps and Secrets](https://www.alcide.io/kubernetes-1-18-introduces-immutable-configmaps-and-secretes/)
