### ISSUE TITLE
[Question] - Getting an error when trying to replace annotations with successive strategic patches

### ISSUE THREAD

**Issue by rsinden** [kubernetes-sigs/kustomize#3777]
We have a got a set of kustomize components, which have istio-proxy sidecar containers injected into them. We currently apply default resource requests to all components (as a strategic merge patch) and I am trying to apply a second patch which replaces these annotations with different requests, but I am getting an error. Below is a simplified version of what we are seeing:

```
istio-proxy-small.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/proxyCPU: '30m'
        sidecar.istio.io/proxyMemory: '100Mi'
        sidecar.istio.io/proxyCPULimit: '2000m'
        sidecar.istio.io/proxyMemoryLimit: '1024Mi'
```

```
istio-proxy-large.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/proxyCPU: '100m'
        sidecar.istio.io/proxyMemory: '100Mi'
        sidecar.istio.io/proxyCPULimit: '2000m'
        sidecar.istio.io/proxyMemoryLimit: '1024Mi'
 ```
 
 ```
 component.yaml
 
name: component
bases:
  - deployment
patches:
  - istio-proxy-large.yaml
```

```
base.yaml

name: deployment
patches:
  - istio-proxy-small.yaml 
  ```
  
When I run `kustomize build ...` for the component, I get the following error output:
```
Error: conflict between map[string]interface {}{"apiVersion":"apps/v1", "kind":"Deployment", "metadata":map[string]interface {}{"name":"deployment"}, "spec":map[string]interface {}{"template":map[string]interface {}{"metadata":map[string]interface {}{"annotations":map[string]interface {}{"sidecar.istio.io/inject":"true", "sidecar.istio.io/proxyCPU":"30m", "sidecar.istio.io/proxyCPULimit":"2000m", "sidecar.istio.io/proxyMemory":"100Mi", "sidecar.istio.io/proxyMemoryLimit":"1024Mi"}}}}} and map[string]interface {}{"apiVersion":"apps/v1", "kind":"Deployment", "metadata":map[string]interface {}{"name":"deployment"}, "spec":map[string]interface {}{"template":map[string]interface {}{"metadata":map[string]interface {}{"annotations":map[string]interface {}{"sidecar.istio.io/inject":"true", "sidecar.istio.io/proxyCPU":"100m", "sidecar.istio.io/proxyCPULimit":"2000m", "sidecar.istio.io/proxyMemory":"100Mi", "sidecar.istio.io/proxyMemoryLimit":"1024Mi"}}}}}
```

**Comment by Shell32-Natsu** [comment]
What is your kustomization file?

**Comment by rsinden** [comment]
> What is your kustomization file?

A stripped down version is:
```
apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations: {build-tag: 050eb5da44119332f4c5b14412ad8589963a2978}
commonLabels: {application: content, component: contentkeeper, environment: test2}
configMapGenerator:
- behavior: merge
  envs: [db.env, open-census.env]
  name: config
configurations: [config.yaml]
images:
- {name: main, newName: `imagePath`, newTag: 050eb5da44119332f4c5b14412ad8589963a2978}
kind: Kustomization
namePrefix: contentkeeper-
namespace: test2
patchesJson6902: []
patchesStrategicMerge: [patches/istio-proxy-small.yaml]
resources: [bases/deployment]
secretGenerator: []
transformers: [app_labels.yaml, version_labels.yaml, client_version.yaml]
```

What I notice is that the `kustomize build` does not seem to be adding the `istio-proxy-large.yaml` patch to it as I would expect, given the error.

**Comment by Shell32-Natsu** [comment]
From your kustomization I don't find where do you include `contentkeeper.yaml` component.

**Comment by rsinden** [comment]
Apologies, I was looking at the incorrect environment for this.

I have modified the above kustomization file to match what I am actually seeing. 

We use a set of locally written environment maker scripts which compile the above kustomization file from the `contentkeeper.yaml` component file and recursively expand the bases.

As you can see above, in the kustomization file we compile, we have 2 `patchesStrategicMerge` for the 2 patches, but when running `kustomize build --load_restrictor none /contentkeeper` we get the original error (where `/contentkeeper` is the directory which contains the `kustomization.yaml` and other transformers)

**Comment by Shell32-Natsu** [comment]
I tried these 2 patches in a kustomization with a deployment resource but I cannot reproduce this issue.

**Comment by rsinden** [comment]
I've stripped it right back to the following:

```
kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- istio-proxy-small.yaml
- istio-proxy-large.yaml
```

```
istio-proxy-small.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: '30m'
```

```
istio-proxy-large.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: '100m'
```

All 3 files in the same directory, and then running `kustomize build` and get the following error:

```
Error: conflict between map[string]interface {}{"apiVersion":"apps/v1", "kind":"Deployment", "metadata":map[string]interface {}{"name":"deployment"}, "spec":map[string]interface {}{"template":map[string]interface {}{"metadata":map[string]interface {}{"annotations":map[string]interface {}{"sidecar.istio.io/proxyCPU":"30m"}}}}} and map[string]interface {}{"apiVersion":"apps/v1", "kind":"Deployment", "metadata":map[string]interface {}{"name":"deployment"}, "spec":map[string]interface {}{"template":map[string]interface {}{"metadata":map[string]interface {}{"annotations":map[string]interface {}{"sidecar.istio.io/proxyCPU":"100m"}}}}}
```
