### ISSUE TITLE
Can not add any comment in .yaml

### ISSUE THREAD

**Issue by Jojoooo1** [kubernetes-sigs/kustomize#3778]
**Describe the bug**
Can not add a comment in my .yaml

Trying to use kustomize with a .yaml using a comment.
Version 3.8.10 works perfectly
Version 3.9.3 throw yaml: invalid trailing UTF-8 octet

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ingress.yaml
```

ingress.yaml

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-intelipoint
spec:
  rules:
    - host: # A COMMENT
      http:
        paths:
          - backend:
              serviceName: intelipoint-api
              servicePort: 80

```

**Expected output**

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-intelipoint
  namespace: default
spec:
  rules:
    - host:
      http:
        paths:
          - backend:
              serviceName: intelipoint-api
              servicePort: 80
```

**Actual output**

Error: map[string]interface {}{"apiVersion":"networking.k8s.io/v1beta1", "kind":"Ingress", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"cert-manager.io/cluster-issuer":"letsencrypt-prod", "kubernetes.io/ingress.class":"nginx", "nginx.ingress.kubernetes.io/force-ssl-redirect":"true"}, "name":"ingress-intelipoint", "namespace":"default"}, "spec":map[string]interface {}{"rules":[]interface {}{map[string]interface {}{"host":interface {}(nil), "http":map[string]interface {}{"paths":[]interface {}{map[string]interface {}{"backend":map[string]interface {}{"serviceName":"intelipoint-api", "servicePort":80}}}}}}}}: yaml: invalid trailing UTF-8 octet

**Kustomize version**

{Version:kustomize/v3.9.3 GitCommit:1ae8303bdc9372bc7c15942df6e9cf5d67fdba1a BuildDate:2021-02-07T17:02:13Z GoOs:linux GoArch:amd64}

**Platform**

Ubuntu 18.04.5 LTS

Edit: work by using `kustomize build . --enable_kyaml=false`

**Comment by cfraenkel** [comment]
I'm hitting the same error, but only when the comment contains a non ascii unicode character like 'ä'.
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-intelipoint
spec:
  rules:
    - host: # Ä COMMENT
      http:
        paths:
          - backend:
              serviceName: intelipoint-api
              servicePort: 80
```

if the unicode char appears in a non-comment there is no similar error:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-intelipoint
spec:
  rules:
    - host: ä # A COMMENT
      http:
        paths:
          - backend:
              serviceName: intelipoint-api
              servicePort: 80
```

This issue also affects the kustomize bundled in the most recent kubectl 1.21.0
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```
