### ISSUE TITLE
YAML Anchor support broken between versions 3.8.10 and 3.9.2

### ISSUE THREAD

**Issue by tomdymond** [kubernetes-sigs/kustomize#3779]
Using recent versions of Kustomize it appears YAML anchors have stopped working and render empty dictionaries 

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: test
spec:
  chart:
    version: 0.3.02
 ---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: test
  chart:
    name: test
    version: 0.3.01
  values:
    foo:
      bar:
        ns1: &id001
          foo: bar
          baz: boz

        ns2:
          <<: *id001

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - HelmRelease-patch.yaml

resources:
  - ./HelmRelease.yaml
```

Using *3.8.10* It renders properly

```
/usr/local/bin/kustomize-3.8.10 build  .
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  chart:
    name: test
    version: 0.3.01
  name: test
  namespace: test
  values:
    foo:
      bar:
        ns1:
          baz: boz
          foo: bar
        ns2:
          baz: boz
          foo: bar
spec:
  chart:
    version: 0.3.02
```

Using *3.9.2* and onwards (also tested with v4.0.5) it appears to render the anchor as an empty dictionary

```
/usr/local/bin/kustomize-3.9.2 build  .
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  chart:
    name: test
    version: 0.3.01
  name: test
  namespace: test
  values:
    foo:
      bar:
        ns1:
          baz: boz
          foo: bar
        ns2: {}
spec:
  chart:
    version: 0.3.02
```
