### ISSUE TITLE
Ingress.spec.rules.http.paths.backend.resource.name does not receive a suffix based on the name

### ISSUE THREAD

**Issue by stemid** [kubernetes-sigs/kustomize#3796]
Ingress.spec.rules.http.paths.backend.resource.name does not receive a suffix based on the name.

**kustomization.yaml**

```yaml
resources:
  - ingress.yaml

configMapGenerator:
  - name: synapse-server-json
    files:
      - server.json
```

**ingress.yaml**

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: synapse

spec:
  rules:
  - host: my.server
    http:
      paths:
      - path: /.well-known/matrix/server
        backend:
          resource:
            apiGroup: core
            kind: ConfigMap
            name: synapse-server-json
```

**server.json**

```json
{
    "m.server": "my.server:443"
}
```

**Expected output**

```yaml
apiVersion: v1
data:
  server.json: |
    {
        "m.server": "my.server:443"
    }
kind: ConfigMap
metadata:
  name: synapse-server-json-t4cb8g74fg
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: synapse
spec:
  rules:
  - host: my.server
    http:
      paths:
      - backend:
          resource:
            apiGroup: core
            kind: ConfigMap
            name: synapse-server-json-t4cb8g74fg
        path: /.well-known/matrix/server
```

**Actual output**

```yaml
apiVersion: v1
data:
  server.json: |
    {
        "m.server": "my.server:443"
    }
kind: ConfigMap
metadata:
  name: synapse-server-json-t4cb8g74fg
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: synapse
spec:
  rules:
  - host: my.server
    http:
      paths:
      - backend:
          resource:
            apiGroup: core
            kind: ConfigMap
            name: synapse-server-json
        path: /.well-known/matrix/server
```

**Kustomize version**

{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}

**Platform**

```
  Operating System: Fedora 33 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:33
            Kernel: Linux 5.11.10-200.fc33.x86_64
      Architecture: x86-64
```

**Additional context**
