### ISSUE TITLE
Allow using the same base with multiple overlays or transformations

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#38]
Here is an example https://github.com/sethpollack/kustomize_example

When you run `kustomize build cluster_a`

You get the following error:

```
Error: there is already an entry: "extensions_v1beta1_Deployment_example.yaml"
```
Is that the desired result? Or should they be treated as unique based on the `namePrefix` that they use?

**Comment by sethpollack** [comment]
@monopole I would love to get your thoughts on this?

**Comment by monopole** [comment]
IMO, this is a dupe of #18, or a very legitimate complaint about a terrible error message :)

I see you've started on #18, let's see what happens after that.

**Comment by monopole** [comment]
I'm not sure if this is about namespaces or about a desire to wrap two overlays with a third
 kustomization that allows the overlays to be build with one command rather than two.  We can clear that up shortly

**Comment by sethpollack** [comment]
I want two deployments with the same name and the same namespace with different prefixes. But the check happens before the prefix transform runs.

**Comment by monopole** [comment]
Please state the desired end result in yaml :)

**Comment by monopole** [comment]
Or lets just wait till your #54 is in.  The application_test in that PR should define a starting point for further behavior improvements.

**Comment by sethpollack** [comment]
It would look like 
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster: a
  name: example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example
    cluster: a
    env: prod
  name: prod-example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
      cluster: a
      env: prod
  template:
    metadata:
      labels:
        app: example
        cluster: a
        env: prod
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example
    cluster: a
    env: stag
  name: stag-example
  namespace: example
spec:
  selector:
    matchLabels:
      app: example
      cluster: a
      env: stag
  template:
    metadata:
      labels:
        app: example
        cluster: a
        env: stag
    spec:
      containers:
      - image: nginx
        name: nginx
```
