### ISSUE TITLE
namespace not supported by helmCharts

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-sigs/kustomize#3815]
The new `helmCharts` feature (added in #3784) has no way to pass in a namespace. 
This is problematic with many common charts where the namespace is used in e.g. arguments or annotations

e.g. try rendering the cert-manager helm chart:
```yaml
helmCharts:
- name: cert-manager
  releaseName: cert-manager
  version: 1.3.0
  repo: https://charts.jetstack.io
```

**Actual output**

it results in annotations that contain the namespace, e.g.
`cert-manager.io/inject-ca-from-secret: default/cert-manager-webhook-ca`

it also has the argument:
`- --dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.default,cert-manager-webhook.default.svc`

**Kustomize version**/**Platform**

`{Version:4.1.2 GitCommit:$Format:%H$ BuildDate:2021-04-19T00:04:53Z GoOs:linux GoArch:amd64}`

---

CC @monopole

**Comment by monopole** [comment]
The helm program does many many things, including (so I'm told) arbitrary execution of shell commands via `--extra-args` and particularly crafted Go templates.  

The basic chart inflation kustomize performs is intentionally rudimentary to prove out the concept of performing "last mile" chart customization.  Maintaining kustomize long term as a helm runner with full helm flag and argument knowledge as helm evolves would be toilsome and imply kustomize inherits whatever security risks helm presents.

So - anything that looks like what kustomize does should be done by kustomize, rather than delegated to helm, e.g. setting namespace (#3838).

The safest, most performant, and completely unlimited way to use kustomize + helm to generate config is 
 1. manually inflate the helm chart via `helm template --foo --bar ...` (with whatever risky options one wants),
 1. commit the resulting plain old k8s YAML to a repo
 1. use kustomize to operate on that repo, treating it as a base, adding some last mile config changes.

From time to time, capture the latest chart, and repeat steps 1 and 2.

That said, maybe we could always pass `--skip-tests`.

**Comment by monopole** [comment]
BTW, i'm not asserting that #3838 yields the result you want.

I'm wondering what the full use case is, and if it can be satisfied in the fashion suggested by #3838

**Comment by cehoffman** [comment]
> So - anything that looks like what kustomize does should be done by kustomize, rather than delegated to helm, e.g. setting namespace (#3838).

I think the `namespace` setting in kustomize should flow into the `namespace` setting of helm, however I didn't see a way to get that value in the helm inflator plugin. The namespace setting of kustomize currently can not satisfy what the namespace setting of helm does, e.g. setting the namespace component in the middle of an annotation string to the resource like cert-manager does.

> From time to time, capture the latest chart, and repeat steps 1 and 2. It's dangerous to set up a production stack that relies on kustomize to freshly download a helm chart with each build.

Totally agree. Ideally you t don't do that, but it comes down to scheduling prioritization and resources to implement. For me, submitting the PR was less resources to get kustomize in the door than setting up the rest before I could even start with kustomize and our many other usecases that don't usere helm where kustomize would help me.

**Comment by monopole** [comment]
> I think the namespace setting in kustomize should flow into the namespace setting of helm.

That's interesting, and would avoid the easy contradictions one can imagine by not doing it that way.

**Comment by drivelikebrazil** [comment]
> The helm program does many many things, including (so I'm told) arbitrary execution of shell commands via --extra-args and particularly crafted Go templates.

This is an issue with Helm's --post-renderer option in particular and the scary part was that someone running kustomize didn't have to consciously opt-in to run Helm. Given that we now have to explicitly elect to run Helm when we run kustomize, the user is consciously choosing to run Helm and accept the risks associated with it.

> I think the namespace setting in kustomize should flow into the namespace setting of helm

This is a partially workable solution to me. The main places I could see it causing issues is with charts like [Jenkins](https://github.com/jenkinsci/helm-charts/) that create resources in other namespaces intentionally (in this case, creating a role in the agent namepace to allow Jenkins to spin up agent pods there).

> From time to time, capture the latest chart, and repeat steps 1 and 2. It's dangerous to set up a production stack that relies on kustomize to freshly download a helm chart with each build.

Perhaps if you're pulling the Helm chart from an uncontrolled source. We pull specific versions of Helm charts into a private Helm repo and enforce tag immutability from there. We deploy multiple instances of a given application with different configurations and storing the fully templated code for each deployment adds a ton of noise and places for user error.

**Comment by cassid4** [comment]
One side effect of not being able to specify the desired namespace that helm uses is that helm seems to try to use the default namespace in the currently defined KUBECONFIG.

**Comment by monopole** [comment]
It would be tricky to have the namespace transformer effectively communicate with all helm generators below it in the kustomization overlay tree.

**Comment by cassid4** [comment]
Follow-up from my earlier comment
> One side effect of not being able to specify the desired namespace that helm uses is that helm seems to try to use the default namespace in the currently defined KUBECONFIG.

It turns out helm only picks this up if a namespace value is set in the KUBECONFIG, so this isn't a problem if KUBECONFIG is unset or doesn't specify a value.

**Comment by monopole** [comment]
Reopening to track the broader concept of having only one place to specify a namespace change.
Right now, if you use helm charts, you have to set it there too.

**Comment by rdxmb** [comment]
I have tried to define the namespace twice. Works with https://github.com/grafana/helm-charts/tree/main/charts/grafana

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-helm-test
helmCharts:
- name: grafana
  releaseName: customer-metrics-ui-v1
  repo: https://grafana.github.io/helm-charts
  namespace: grafana-helm-test
  version:  6.13.0
```

**Comment by rcmorano** [comment]
> I have tried to define the namespace twice. Works with https://github.com/grafana/helm-charts/tree/main/charts/grafana
> 
> ```
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> namespace: grafana-helm-test
> helmCharts:
> - name: grafana
>   releaseName: customer-metrics-ui-v1
>   repo: https://grafana.github.io/helm-charts
>   namespace: grafana-helm-test
>   version:  6.13.0
> ```
> 
> ```
> $ kustomize version
> {Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:linux GoArch:amd64}
> ```

If I'm not wrong, this wouldn't work with many multi-namespace charts as it would try to use the main namespace for every resource. It doesn't for me and [fission](https://github.com/fission/fission/tree/master/charts/fission-all).

**Comment by rcmorano** [comment]
bump

**Comment by rcmorano** [comment]
bump

**Comment by wibed** [comment]
please reopen.

just to again underline an already made point.
it breaks applied charts for some are created in mind with those capabilities. 
this must be taken into consideration, before electing "kustomize" as a tool to provision your nodes.

atleast i would.

**Comment by wibed** [comment]
@[KnVerey](https://github.com/KnVerey) could you or one of the contributors reopen this issue

**Comment by KnVerey** [comment]
This issue was about the lack of a field that was added in https://github.com/kubernetes-sigs/kustomize/pull/3832. https://github.com/kubernetes-sigs/kustomize/issues/4593 implies it may have since been broken, but it's better to track that in that newer issue.

**Comment by arielweinberger** [comment]
Bump?

**Comment by arielweinberger** [comment]
Bumping again as this breaks our flow of specifying `namespace` in overlays completely.

**Comment by marcjimz** [comment]
The community position on some of these flaws are baffling.

I cannot inline edit multi-line string values for some of my YAML objects after flattening a helm chart, so I go towards the helmChart generator for an exception basis.

I cannot use the helmChart generator effectively, because it does not honor the namespace.

What are my remaining options?

**Comment by wibed** [comment]
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: XXXX

helmCharts:
...
```

sets the namespace correctly, if the chart makes use of the `{.Release.Namespace}` attribute

**Comment by Skaronator** [comment]
@wibed `{{ .Release.Namespace }}` doesn't fully work for me.

My kustomize file looks like this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: the-bug

helmGlobals:
  chartHome: ../../_charts

helmCharts:
- name: namespace
  releaseName: namespace
  valuesFile: values.yaml
```

My Helm Chart looks like this:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: {{ .Release.Namespace }}
  annotations:
    release-namespace: {{ .Release.Namespace }}
spec: {{ .Values.resourceQuota | toYaml | nindent 2 }}
```

And building this looks like this:

```yaml
$ kustomize build . --enable-helm
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: namespace
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: default   #  <- {{ .Release.Namespace }} is still "default"
    helm.sh/chart: namespace-1.0.0
  name: the-bug
---
apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    release-namespace: default        # <- {{ .Release.Namespace }} is still "default"
  name: namespace-quota
  namespace: the-bug                  # <- {{ .Release.Namespace }} correctly set
spec:
  hard:
    pods: 100
```

I suspect that kustomize just replaces the namespace values with the correct values.

This is an issue for us since we dynamically generate namespace and therefore cannot set `namespace` within a `helmCharts` block.
