### ISSUE TITLE
map[string]interface {}(nil): yaml: unmarshal error map key xxx already defined

### ISSUE THREAD

**Issue by wuxingzhong** [kubernetes-sigs/kustomize#3817]
kustomization.yaml

```
helmCharts:
- name: gitlab
  releaseName: gitlab
  version: 4.10.3
  repo: https://charts.gitlab.io/
  valuesInline:
    global:
    hosts: 
        domain: example.com
    certmanager-issuer:
      email:  me@example.com
```

run cmd 

```bash
kustomize build --enable-helm .
```

**Expected output**

Expected  output like 

```bash
helm template  gitlab gitlab/gitlab \
  --set global.hosts.domain=example.com \
  --set certmanager-issuer.email=me@example.com --version 4.10.3
```

**Actual output**

```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 12: mapping key "app" already defined at line 6
```

**Kustomize version**

```
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOS
