### ISSUE TITLE
`images` does not work with YAML anchors

### ISSUE THREAD

**Issue by eyalzek** [kubernetes-sigs/kustomize#3824]
**Describe the bug**

using [images](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/) fails when YAML anchors are in place.

**Files that can reproduce the issue**

kustomization.yaml

```yaml
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - resources.yaml

images:
  - name: busybox
    newTag: stable
```

resources.yaml

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
        - name: foo
          image: &image busybox
        - name: bar
          image: *image

```

**Expected output**

the `Deployment` is generated with the correct image.

**Actual output**

```bash
$ k kustomize .
Error: wrong Node Kind for  expected: ScalarNode was AliasNode: value: {*image}
```

**Kustomize version**

- 4.0.5 (bundled in kubectl)
- 4.1.2 (current latest)

**Platform**

linux

**Additional context**

we're in the process of updating our kustomization files since we use the bundled version in `kubectl` (which was just updated from v2 -> v4). This setup with `images` & yaml anchors used to work on 2.0.3.
