### ISSUE TITLE
Kustomize fails to build with YAML anchors inside `List` resources

### ISSUE THREAD

**Issue by eyalzek** [kubernetes-sigs/kustomize#3825]
Kustomize fails to builds with YAML anchors inside `List` resources.

**Files that can reproduce the issue**

kustomization.yaml

```yaml
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - resources.yaml
```

resources.yaml

```yaml
---
apiVersion: v1
kind: List
items:
  - &item
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: foo
    spec: &kindSpec
      concurrencyPolicy: Forbid
      schedule: "0 * * * *"
      startingDeadlineSeconds: 1800
      jobTemplate:
        spec: &jobSpec
          activeDeadlineSeconds: 7200
          template:
            spec: &templateSpec
              restartPolicy: Never
              containers:
                - &container
                  name: cronjob
                  image: busybox:latest
  - <<: *item
    metadata:
      name: bar
    spec:
      <<: *kindSpec
      schedule: "0 0 * * *"
      jobTemplate:
        spec:
          <<: *jobSpec
          template:
            spec:
              <<: *templateSpec
              containers:
                - <<: *container
                  image: busybox:stable
```

**Expected output**

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bar
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          containers:
          - image: busybox:stable
            name: cronjob
          restartPolicy: Never
  schedule: 0 0 * * *
  startingDeadlineSeconds: 1800
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: foo
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          containers:
          - image: busybox:latest
            name: cronjob
          restartPolicy: Never
  schedule: 0 * * * *
  startingDeadlineSeconds: 1800
```

**Actual output**

```bash
$ k kustomize .
Error: accumulating resources: accumulation err='accumulating resources from 'resources.yaml': missing kind in object {{ } {{bar } map[] map[]}}': got file 'resources.yaml', but '/tmp/kustomize/resources.yaml' must be a directory to be a root
```

**Kustomize version**

- 4.0.5 (bundled with kubectl)
- 4.1.2 current latest

**Platform**

linux

**Additional context**

encountered during kubectl update which bumped kustomize version 2.0.3 -> 4.0.5. This is not an issue with kustomize 2.0.3.

I found this issue: https://github.com/kubernetes-sigs/kustomize/issues/3614 but the error is different so I assume it's not the same issue...
