### ISSUE TITLE
How do I re-use a value?

### ISSUE THREAD

**Issue by zhech2** [kubernetes-sigs/kustomize#3833]
We have many images with the same tag and private registry:

```yaml
images:
- name: image1
  newName: privateregistry/image1
  newTag: TAG1
- name: image2
  newName: privateregistry/image2
  newTag: TAG1
# + more
```

The registry and TAGS are duplicated.  

Is there a way to define a local constant (to a file) to prevent this kind of duplication?
