### ISSUE TITLE
[Question] How can I  change container name?

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [kubernetes-sigs/kustomize#3840]
I have one parent deployment for all backed services.

```
kind: Deployment
apiVersion: v1beta1
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
spec:
  replicas: 3
  strategy: Recreate
  selector:
    matchLabels:
      deploy: example
  
  template:
    metadata:
      labels:
        deploy: example
    spec:
      containers:
        - env:
              # ..here are few variables
          name: CONTAINER_NAME_PLACEHOLDER
          image: IMAGE_PLACE_HOLDER
```

and  want to change it with may patch

```
kind: Deployment
apiVersion: v1beta1
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
spec:   
  template:
    spec:
      containers:
        - env:
              # ..here are few variables
          name: correct_name
          image: correct_image
 
```

I'm changing DEPLOYMENT_NAME_PLACEHOLDER in my kustomization.yaml:

```
patches:
- target:
    kind: DEPLOYMENT_NAME_PLACEHOLDER
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: correct_name
```

None of above does work for container name. (CONTAINER_NAME_PLACEHOLDER)
How can I do this?

**Comment by natasha41575** [comment]
The reason that it is not altering CONTAINER_NAME_PLACEHOLDER is because the patches you have don't tell it to use that patch. 

You could do something like:
```
patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: correct_name
- target:
    kind: Deployment
    path: patch.yaml
```

This would apply the JSON patch for the deployment's metadata/name, and then apply the patch specified in the file patch.yaml.

An alternative, simpler way to do this is as follows:

deployment.yaml
```
kind: Deployment
apiVersion: v1beta1
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
spec:
  replicas: 3
  strategy: Recreate
  selector:
    matchLabels:
      deploy: example

  template:
    metadata:
      labels:
        deploy: example
    spec:
      containers:
        - env:
              # ..here are few variables
            name: CONTAINER_NAME_PLACEHOLDER
            image: IMAGE_PLACE_HOLDER
```

patch.yaml:
```
kind: Deployment
apiVersion: v1beta1
metadata:
  name: correct_name
spec:   
  template:
    spec:
      containers:
        - env:
              # ..here are few variables
            name: correct_name
            image: correct_image
```

kustomization.yaml:
```
resources:
- deployment.yaml

patches:
- path: patch.yaml
  target:
    kind: Deployment
  options:
    allowNameChange: true
```

The output of kustomize build will be as follows:

```
apiVersion: v1beta1
kind: Deployment
metadata:
  name: correct_name
spec:
  replicas: 3
  selector:
    matchLabels:
      deploy: example
  strategy: Recreate
  template:
    metadata:
      labels:
        deploy: example
    spec:
      containers:
      - env:
          image: correct_image
          name: correct_name
```

**Comment by Krzysztof-Lempicki** [comment]
`allowNameChange` not work:

```
Error: trouble configuring builtin PatchTransformer with config: `
options:
  allowNameChange: true
patch: master-agreement-service.yml
target:
  kind: service
`: unable to parse SM or JSON patch from 
```
**kustomise version:**
`{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:linux GoArch:amd64}`

**api version from kustomise.yml:**
`apiVersion: kustomize.config.k8s.io/v1beta1`

**Comment by natasha41575** [comment]
What does my-service-service.yml look like? The error thrown here is [from this line](https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/plugin/builtin/patchtransformer/PatchTransformer.go#L64), which indicates there is something wrong with the patch, and is unrelated to the `allowNameChange` field

**Comment by natasha41575** [comment]
Can you fix the indentation? The Service patch `allowNameChange` field is extra indented.

If that doesn't fix it, what does my-service-service.yml look like?

**Comment by Krzysztof-Lempicki** [comment]
"Can you fix the indentation? The Service patch allowNameChange field is extra indented."

you want me to do this:

```
- path: my-sevice-service.yml
    target:
      kind: Service
    options:
    allowNameChange: true  # less spaces
```

?

**Comment by natasha41575** [comment]
No, leave it indented. Notice how in your previous comment it was even more indented than the others?

It was like this:

```
- path: my-sevice-service.yml
    target:
      kind: Service
    options:
        allowNameChange: true  # less spaces
```

It should be like this:
```
```
- path: my-sevice-service.yml
    target:
      kind: Service
    options:
      allowNameChange: true  # less spaces
```

**Comment by natasha41575** [comment]
I get the same error when removing the options and allowNameChange field, so it is unrelated. There is something wrong with the patch; I'm investigating it now

**Comment by natasha41575** [comment]
Ah, I've found the mistake. 

You are using the `patch` field, which is meant for inline patches. You should be using the "path" field. See https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/

Your kustomization should be: 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../backend
patches:
- path: my-service-service.yml
  target:
    kind: Service
  options:
    allowNameChange: true
- path: my-service-deployment.yml
  target:
    kind: Deployment
  options:
    allowNameChange: true
```

The error here is being thrown because it is trying to marshal the string "my-service-service.yml" into a patch, rather than reading the patch from that patch.

**Comment by P-A-R-U-S** [comment]
You can do this via command line: kubectl run kplabs-nginx --image=mykplabs/kubernetes:nginxkubl -**-overrides='{ "apiVersion": "v1", "spec": { "containers":[{"image":"mykplabs/kubernetes:nginx", "name": "mycontainer"}] }}'**

**Comment by fhmlsml** [comment]
@natasha41575 hi, when I tried to patch deployment name it works perfectly, but it didn't work for the container name `.spec.template.spec.containers.[0].name` it ended with 2 container names (one container from base and the other one from the overlays that i tried patch.)

is it a bug ?? 

i already tried this but it still no difference:

`kustomization.yaml`
```yaml
patches:
  - target: 
      kind: Deployment
    options:
      allowNameChange: true
    path: deployment-patch.yaml
  - target: 
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: my-desired-container-name
```

**Comment by firemdkfighter** [comment]
> is it a bug ??
No it's not a bug. See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md

>i already tried this but it still no difference:

kustomization.yaml

It's work for me.

**Comment by Alexander-N** [comment]
> i already tried this but it still no difference:
> 
> `kustomization.yaml`
> 
> ```yaml
> patches:
>   - target: 
>       kind: Deployment
>     options:
>       allowNameChange: true
>     path: deployment-patch.yaml
>   - target: 
>       kind: Deployment
>     patch: |-
>       - op: replace
>         path: /spec/template/spec/containers/0/name
>         value: my-desired-container-name
> ```

You are adding a second container with your first patch. I think if you change the name first, it will work.
```yaml
patches:
  - target: 
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: my-desired-container-name
  - target: 
      kind: Deployment
    options:
      allowNameChange: true
    path: deployment-patch.yaml
```
