### ISSUE TITLE
Support GoGetter for configurations in kustomization.yaml

### ISSUE THREAD

**Issue by stephenrob** [kubernetes-sigs/kustomize#3846]
**Is your feature request related to a problem? Please describe.**

When using custom resources such as SealedSecrets and Gloo by Solo it's common to need to apply a range of common custom configurations to the CRDs to add support for kustomize and features such as namePrefix, nameSuffix and namespace changing. Currently this returns an `evalsymlink failure on ...` error.

**Describe the solution you'd like**

Ability to use a go-getter url in configurations to specify a common repo to pull custom configurations/files from.

**Describe alternatives you've considered**

Using Git submodules to pull in the custom configurations is an option but given go-getter is supported for bases/resources it seems sensible to add support for this in configurations as well.

**Additional context**

Given the following kustomization it should pull the configurations down and use them as part of the build process (example for sealed secrets namespace is given). [Configuration Repo](https://github.com/stephenrob/kustomize-configuration) (public version from our GHE instance).

#### base/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - upstream.yaml
  - virtualservice.yaml
configurations:
  - git@github.com:stephenrob/kustomize-configuration.git//solo/namespace.yaml
  - git@github.com:stephenrob/kustomize-configuration.git//solo/name.yaml
  - git@github.com:stephenrob/kustomize-configuration.git//sealedsecrets/namespace.yaml
  - git@github.com:stephenrob/kustomize-configuration.git//sealedsecrets/name.yaml
  - git@github.com:stephenrob/kustomize-configuration.git//k8s/service/name.yaml
commonLabels:
  app.kubernetes.io/part-of: api
```

#### kustomize-configuration/sealedsecrets/namespace.yaml
```yaml
namespace:
- path: spec/template/metadata/namespace
  create: true
  kind: SealedSecret
```
