### ISSUE TITLE
[Question] Multiple Deployment with different values

### ISSUE THREAD

**Issue by lfdominguez** [kubernetes-sigs/kustomize#3850]
Hi i have this kustomize .yaml
```yaml
commonLabels:
  app: app-backend
  
images:
- name: registry.company.cu/proyect/image
  newName: registry.company.cu/app/backend
  newTag: 20210419-183225

resources:
- ../../../../common/simple-deploy/deployment.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: simple-deploy
  path: deployment-patch.yaml
```

My question is how in the same kustomize .yaml i can define another deployment based on same `resources` template?
