### ISSUE TITLE
kustomize edit set image removes helmChartInflationGenerator

### ISSUE THREAD

**Issue by jlewi** [kubernetes-sigs/kustomize#3856]
**Describe the bug**

Running `kustomize edit set image ...` on a kustomization.yaml containing a helmChartInflationGenerator causes the helmChartInflationGenerator section to be removed.

**Files that can reproduce the issue**

```
apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  hydros.primer.ai/env: dev-helm
  kustomize.toolkit.fluxcd.io/prune: disabled
helmChartInflationGenerator:
- chartHome: ../../../../..
  chartName: charts
  chartVersion: 0.0.1
  releaseName: migrate
  releaseNamespace: ml-serving
  values: values.yaml
```

**Expected output**

```
apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  hydros.primer.ai/env: dev-helm
  kustomize.toolkit.fluxcd.io/prune: disabled
helmChartInflationGenerator:
- chartHome: ../../../../..
  chartName: charts
  chartVersion: 0.0.1
  releaseName: migrate
  releaseNamespace: ml-serving
  values: values.yaml
images:
- name: image1
  newName: image2
```

**Actual output**

```
apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  hydros.primer.ai/env: dev-helm
  kustomize.toolkit.fluxcd.io/prune: disabled
kind: Kustomization
images:
- name: image1
  newName: image2
```

**Kustomize version**

```
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOs
