### ISSUE TITLE
Multiple strategic merge patches having 'delete' directives produce unexpected variant.

### ISSUE THREAD

**Issue by everpeace** [kubernetes-sigs/kustomize#386]
Hi, I faced an unexpected behavior when multiple patches having [`delete`](https://github.com/kubernetes/community/blob/master/contributors/devel/strategic-merge-patch.md#delete-directive)  directive in `kustumization.yaml`.  I'm not sure but, probably, processing order (transformation?) would have some issue.

Let me describe the issue by simple example.  Say, I have this simple structure.

```shell
$ tree .
.
├── disable-vol1.yaml
├── disable-vol2.yaml
├── kustomization.yaml
└── pod.yaml
0 directories, 4 files
```

each file content is below:
```yaml
# kustomization.yaml
resources:
- pod.yaml
patchesStrategicMerge:
- disable-vol2.yaml
- disable-vol1.yaml
---
# pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: pod
spec:
  volumes:
  - name: vol1
    emptyDir: {}
  - name: vol2
    emptyDir: {}
  containers:
  - name: ctr
    image: busybox
    volumeMounts:
    - name: vol1
      mountPath: /mnt/vol1
    - name: vol2
      mountPath: /mnt/vol2
---
# disable-vol1.yaml
# this tries to remove 'vol1' from pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: pod
spec:
  volumes:
  - $patch: delete
    name: vol1
  containers:
  - name: ctr
    image: busybox
    volumeMounts:
    - $patch: delete
      mountPath: /mnt/vol1
---
# disable-vol2.yaml
# this also tries to remove 'vol2' from pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: pod
spec:
  volumes:
  - $patch: delete
    name: vol2
  containers:
  - name: ctr
    image: busybox
    volumeMounts:
    - $patch: delete
      mountPath: /mnt/vol2
```

In this situation,  when I run `kustomize build .`, what I expected was

```yaml
# this is ideal output (not actual output)
# I expected both vol1 and vol2 are deleted.
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: busybox
    name: ctr
    volumeMounts: []
  volumes: []
```

however, what I got actually was:

```shell
$ kustomize version
Version: {KustomizeVersion:1.0.8 GitCommit:58492e2d83c59ed63881311f46ad6251f77dabc3 BuildDate:2018-09-13T19:14:22Z GoOs:unknown GoArch:unknown}

$ kustomize build .
# only vol2 is removed, but vol1 stil remains...
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: busybox
    name: ctr
    volumeMounts:
    - mountPath: /mnt/vol1
      name: vol1
  volumes:
  - emptyDir: {}
    name: vol1
```

In general, strategic merge operations are not associative. Thus, I imagined that kustomize performs

```
# @ = strategic merge operations (assume this operator is left-associative)
base @ ( patch1 @ patch2 @   ...  @ patchN )
```

But, I think this is more natural and intuitive.

```
# parenthess are explicitly depicted.
((((base @  patch1) @ patch2) @   ... ) @ patchN)
```

What do you think??
