### ISSUE TITLE
[Question] Change value of LabelTransformer labels

### ISSUE THREAD

**Issue by keidevs** [kubernetes-sigs/kustomize#3868]
I want to change the value of labels via kustomize command in ci step.

For example, you can change the commonLabels value through the kustomize edit set label command.
Is there a way to change the values of labels other than commonLables?

**Comment by keidevs** [comment]
```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: metadataLabelTransformer
labels:
  tags.datadoghq.com/version: 0.0.0.1
  tags.datadoghq.com/env: in_house_production
fieldSpecs:
- path: metadata/labels
  create: false
- path: spec/template/metadata/labels
  create: false
```

I am currently using LabelTransformer as above. Is there a Kustomize command that can change the labels value here?
