### ISSUE TITLE
Use ServiceAccount secrets.name as variable input

### ISSUE THREAD

**Issue by rgruyters** [kubernetes-sigs/kustomize#3869]
Hi ya, i'm was digging into Kustomize to see if I can use it for my environment.

For my application I need to create a ServiceAccount and an Issuer, to retrieve certificates from my PKI service.

I have tested it with the following files but couldn't get it to work. Maybe it is not possible, but maybe it is.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issuer
```

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: foo
spec:
  vault:
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          key: token
          name: $(ISSUER_TOKEN) # <--- This should be serviceaccount/issuer.secrets.name
    path: pki/sign/foo-dot-com
    server: http://vault.default
```

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foo

commonLabels:
  app: foo

vars:
- name: ISSUER_TOKEN
  objref:
    kind: ServiceAccount
    name: issuer
    apiVersion: v1
  fieldref:
    fieldpath: secrets.name

resources:
- foo-issuer-serviceaccount.yaml
- foo-issuer.yaml
```

This doesn't work for me, but maybe you can help me.

**Comment by natasha41575** [comment]
You are referring to the path `secrets.name` of this resource:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issuer
```

The path `secrets.name` doesn't exist. Did you truncate the rest of this resource?

**Comment by rgruyters** [comment]
No I didn't. Normally when requesting a ServiceAccount _Issuer_ it will generate a `secrets.name` with a suffix.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-05-07T12:07:09Z"
  name: issuer
  namespace: foo
  resourceVersion: "29309"
  uid: 7bc8702c-8f43-43ba-aaaf-b588be1622f2
secrets:
- name: issuer-token-p7c7f
```

The token which is available in the issuer-token will be used for authentication to the kubernetes auth mountpoint in Vault.
Is there a way with kustomize to get the token name? Or can I find another way to get this done?

**Comment by natasha41575** [comment]
The `secrets.name` path must exist when `kustomize build` runs; otherwise there is no way for kustomize to get it. When does `secrets.name` get generated in relation to `kustomize buidl`?

**Comment by rgruyters** [comment]
Sure!

For Cert Manager I use the Vault configuration solution with Kubernetes authentication against Vault service. For this to happen you need to create an Issuer token. (`kubectl create sa issuer`)
This will create a secret token with a suffix. (see [example](https://github.com/kubernetes-sigs/kustomize/issues/3869#issuecomment-837087302) above, `issuer-token-p7c7f`)
The token (with suffix) is used for the Issuer resource.

```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: sandbox
spec:
  vault:
    path: pki_int/sign/example-dot-com
    server: https://vault.local
    caBundle: <base64 encoded caBundle PEM file>
    auth:
      kubernetes:
        role: my-app-1
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: issuer-token-p7c7f
          key: token
```
