### ISSUE TITLE
[Question] How to extract only image newname in a transformer

### ISSUE THREAD

**Issue by rverma-nsl** [kubernetes-sigs/kustomize#3871]
hi all,  trying to use flux with kustomie. 

One basic challenge is how can i have an image reference updated without including image tag. E.g

```
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: ecr
  namespace: paas
spec:
  image: image <--- update this, only to `ghcr.io/my-image` but it become `ghcr.io/my-image:tagname`
```
updated using kustomization.yaml  
```
images:
  - name: image
    newName: ghcr.io/my-image
    newTag: tagname # {"$imagepolicy": "paas:my-image:tag"}
```
with a simple image transformer, it update with the tag  like which needed to be excluded like, 
```
images:
  - path: spec/image
    kind: ImageRepository
```

Please help :slightly_smiling_face:
