### ISSUE TITLE
[Question]Is it possible to reference to an existing resource?

### ISSUE THREAD

**Issue by Magicloud** [kubernetes-sigs/kustomize#3875]
I am working with Vault injector agent, which manifest contains a `caBundle` field requires a CA cert in form of text, instead of a secret/configmap.

But in my case, the CA for the cluster is automatically generated and stored as a secret. So if I do not want to do manual work as viewing the secret, copying the text to manifests, applying the manifests. I need to figure out a way to reference to the secret and get the value for the `caBundle` field.

I did the following:

- in kustomization.yaml
```
vars:
- name: CA_BUNDLE
  objref:
    kind: Secret
    name: internal-ca
    apiVersion: v1
  fieldref:
    fieldpath: data[ca.crt]
```
- in the patch
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
webhooks:
- name: vault.hashicorp.com
  clientConfig:
    caBundle: $(CA_BUNDLE)
```

I got `Error: var '{CA_BUNDLE ~G_v1_Secret {data[ca.crt]}}' cannot be mapped to a field in the set of known resources`

What should I do?
