### ISSUE TITLE
Invalid build output if resource separator has trailing spaces

### ISSUE THREAD

**Issue by queil** [kubernetes-sigs/kustomize#3876]
If a file has multiple resources separated by `---` and the separator is followed by trailing spaces then `kustomize build` silently generates an invalid output.

**Files that can reproduce the issue**

**kustomization.yaml**:
```yaml
cat <<EOF >./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- install.yaml
EOF
```
**install.yaml**:
```yaml
cat <<EOF >./install.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---    #trailing spaces here
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test
  type: ClusterIP
EOF
```

**Expected output**

An error message indicating the file {full-file-name} is invalid due to trailing spaces in line {line-number}. Alternatively if this is allowed the output should be:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test
  type: ClusterIP
```

**Actual output**

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test

```

**Kustomize version**

```
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:linux GoArch:amd64}
```
**Platform**

Linux

**Additional context**

**Comment by KnVerey** [comment]
I was able to reproduce this (and it definitely is the whitespace causing it, not the comment fwiw)

/triage accepted

**Comment by brianpursley** [comment]
This line of code seems to be the cause:
https://github.com/kubernetes-sigs/kustomize/blob/bdbfb28139db6eefb2c5c147323d78a2894041d2/kyaml/kio/byteio_reader.go#L148

Notice it is splitting on `\n---\n` which does not consider spaces or anything else after the `---`.

According to the [YAML Spec](https://yaml.org/spec/1.2/spec.html) there seem to be a lot of things that can come after `---`.

Two identified in this issue: spaces and comments, neither of which are handled at this time.

Spaces would be relatively straightforward to handle by splitting on a regex that allows spaces.

But comments on the other hand.  Should they be preserved?

For example:
```
--- # what should happen to me?
a: b
```

Should this become...

```
# what should happen to me?
a: b
```

or just...
```
a: b
```

---

Also, what if something is detected after `---`?  Should Kustomize just fail at that point instead of emitting partial output?  It seems like it would be better to fail if the document separator cannot be recognized due to extra stuff after it.

**Comment by natasha41575** [comment]
> But comments on the other hand. Should they be preserved?

Kustomize doesn't generally preserve comments, so I don't see a reason why this needs to be an exception. 

> Also, what if something is detected after ---? Should Kustomize just fail at that point instead of emitting partial output? It seems like it would be better to fail if the document separator cannot be recognized due to extra stuff after it.

I agree. I think kustomize should throw an error in this case.

> According to the YAML Spec there seem to be a lot of things that can come after --- (such as >, !, !!set, !!omap... I don't really use any of those things myself)

I know that this is allowed in yaml, but is there a use case among kustomize users for these things? Is there a scenario would a valid KRM resource need them?

**Comment by brianpursley** [comment]
@natasha41575 thanks for clarifying about the comments.  I haven't really used them with kustomize so I wasn't aware of that.

I don't think there would be a kustomize use case for any of the other things that the yaml spec was saying could come after `---`.  I was mainly just curious how it should be handled to try to add some details to this issue, so it would be work-able.

How does this sound?
1. `---` alone on a line continue to work as it does today
2. ignore white space after `---`
3. ignore any comments after `---` (don't preserve them, as you pointed out is kustomize's normal approach to comments)
4. Anything else after `---` besides spaces or comments, then fail

**Comment by natasha41575** [comment]
@brianpursley sounds good to me.

**Comment by KnVerey** [comment]
@brianpursley @natasha41575 The problematic splitting is in kyaml, and kyaml does preserve comments in general. Could we take inspiration from the hardened document splitting implementation in k/k? Even though it does not appear to support all features of the yaml spec, I think consistency with k/k's document handling is a fair approach.
 https://github.com/kubernetes/kubernetes/blob/7b24c7e4a7a644bd9c4aa173d59fd5bdcddc8652/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go#L171-L202
 
Re: what happens to the comment in `--- # what should happen to me?`, I _think_ the above would drop the rest of the document separator line, but the code is a bit hard to read. Either way we go, I think we should recommend that comments not be included on that line for now, because we can't round-trip them cleanly back onto it without a bunch of work. I'm leaning slightly towards preferring dropping it as not supported in the meantime, because if we retain it as the first line in the document, then we'll be handling the `\n` on the separator line inconsistently.

**Comment by brianpursley** [comment]
@KnVerey I like that idea, using what k/k has done. I looked at the code too and agree it looks like it is dropping everything after the three dashes to the newline.  It probably is the simplest way to handle it.

**Comment by brianpursley** [comment]
Using that k/k has done seemed like a good idea at first, but on second look, it would take quite a bit of refactoring.  The approach in k/k is one of a scanning of the content, identifying each document as it is encountered.  Whereas in kustomize, the entire content is split into an array of documents upfront and then processed after that.

Given that the effect of the k/k approach is to allow (and discard) any content that comes after `---`, I thought a simple approach for kustomize might be to just match that same behavior using a regexp to allow splitting on `\n---.*\n` instead of `\n---\n`.

I opened a [PR for this](https://github.com/kubernetes-sigs/kustomize/pull/4014) in case you want to take a look.

**Comment by natasha41575** [comment]
> I thought a simple approach for kustomize might be to just match that same behavior using a regexp to allow splitting on \n---.*\n instead of \n---\n

This is the solution I was thinking of initially too. Thanks for the PR - we'll take a look when we can!

**Comment by brianpursley** [comment]
> Given that the effect of the k/k approach is to allow (and discard) any content that comes after `---`

I [commented over on the PR](https://github.com/kubernetes-sigs/kustomize/pull/4014/files#r658295152) but wanted to correct myself here.  I don't know if it is using some other code to split documents than what we were looking at, but k/k has a similar problem in that if there is anything after `---`, it skips that entire document without an error:

```
kubectl --dry-run=server apply -f - << EOF
apiVersion: v1
kind: Namespace
metadata:
  name: foo
--- # something    
apiVersion: v1
kind: Namespace
metadata:
  name: bar
---            
apiVersion: v1
kind: Namespace
metadata:
  name: baz
EOF
```

output (bar is not created):

```
namespace/foo created (server dry run)
namespace/baz created (server dry run)
```

(This is the same with or without using dry-run)
