### ISSUE TITLE
ClusterRoleBinding subjects namespace is wrong

### ISSUE THREAD

**Issue by r0bj** [kubernetes-sigs/kustomize#3877]
**Describe the bug**
ClusterRoleBinding subjects namespace is wrong.

**Files that can reproduce the issue**

```
$ tree
.
├── a
│   ├── kustomization.yaml
│   └── resources.yaml
├── b
│   ├── kustomization.yaml
│   └── resources.yaml
├── base
│   ├── kustomization.yaml
│   └── resources.yaml
└── kustomization.yaml
```

a/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- resources.yaml
namespace: a
```

a/resources.yaml:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
- kind: ServiceAccount
  name: sa
```

b/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- resources.yaml
namespace: b
```

b/resources.yaml:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
- kind: ServiceAccount
  name: sa
```

base/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

base/resources.yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- a
- b
```

**Expected output**

```
$ kustomize build
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
- kind: ServiceAccount
  name: sa
  namespace: a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
- kind: ServiceAccount
  name: sa
  namespace: b
```

**Actual output**

```
$ kustomize build
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
- kind: ServiceAccount
  name: sa
  namespace: a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
- kind: ServiceAccount
  name: sa
  namespace: a
```

Note: Last output line, ClusterRoleBinding `crb-b` subjects[0].namespace is `a` instead of `b`.

What's interesting, building part `b` separately works as expected:
```
$ kustomize build b
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr
subjects:
- kind: ServiceAccount
  name: sa
  namespace: b
```

**Kustomize version**

```
$ kustomize version
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T23:23:37+01:00 GoOs:darwin GoArch:amd64}
```
