### ISSUE TITLE
[Question] Is it possible to have Kustomize apply Components "generically"?

### ISSUE THREAD

**Issue by edude03** [kubernetes-sigs/kustomize#3879]
Hi,

Sorry if this is not the right place to ask, but I've checked the usual suspects already and couldn't find an answer so I figured here would be the next logical step.

I have a use case that I feel like is both fairly common, and could be solved with Kustomize but I haven't been able to get it to work so far and would appreciate some guidance. 

I have an application that I want to deploy both locally and in production. To simplify this example assume the application only has a deployment, and it's depends on having a database. 

So I create a `base/deployment.yaml` then a `local/kustomization.yaml` and a `production/kustomization.yaml` that both import the base. OK works perfectly so far as expected. 

Now I want to have two database "implementations" 

If this was helm, for example I might want to use the postgres chart locally, but then use a postgres operator in production. Each database is going to have a username, password and (in the case I'm running into) a secret that contains TLS certs.

In my local patch, I want to patch my deployment to add three things
- env vars like DB_HOST, DB_PASSWORD, DB_USER etc
- envFrom for these variables
- volume(s) & volumeMount(s) for the certs 

Currently, I can make this work by defining a patches in `local/kustomization.yaml` and `production/kustomization.yaml` however what I'd to do is move these patches into something like `local-db` and `db-operator` or something like to make it clear that that's what these patches do.

However, this doesn't work right now because:
- when using components, you need to define the `metadata.name` of the object you want to patch, either in the json patch target, or the strategicmerge metadata.name. I'd like to be able to apply this to any deployment like I can if I put the patch in the kustomization.yaml for the environment. 
- `envFrom` doesn't merge in strategic patches (known issue https://github.com/kubernetes-sigs/kustomize/issues/1835, but annoying in this case) 
- I thought I'd be able to do something like this
```
# local/kustomization.yaml

resources:
  - ../local-db # contains the kustomization.yaml, the deployment for the DB, and the config generator

patches:
  - target:
       kind: Deployment # I want this to apply to all my deployments in this bundle
     patch: ../local-db/patches/deployment-patch.yaml
```

but with all the iterations of that I've tried, I've yet to get that to work. This example does work if I inline the patch that I have in ` ../local-db/patches/deployment-patch.yaml` so I think I'm roughly using kustomize correctly here, however to me having to inline the patch defeats the purpose of having a patch basically. 

So, I know it's kind of a vague ask, but with the problem laid out as I've explained it, Is there a way to get components, or kustomize itsself to be able to apply patches generically to all objects of a type? Ideally by just importing one thing (a component, and overlay a patch, whatever)

**Comment by natasha41575** [comment]
It is because you are using the `patch` field, which should only be used for an inline patch. If you want to use a path, you need to use `path`, e.g. 

```
patches:
  - target:
       kind: Deployment # I want this to apply to all my deployments in this bundle
     path: ../local-db/patches/deployment-patch.yaml # notice that this is `path` and not `patch`
```

You can see the documentation here:
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/

Let me know if this works! You aren't the first to have this problem, the UX could be better. I hope this resolves your issue.
