### ISSUE TITLE
[Question] Patching values that have name references in different namespaces

### ISSUE THREAD

**Issue by albuch** [kubernetes-sigs/kustomize#3892]
From what I've experienced so far is that if a value is patched on a resource that is configured to have name references for this value in resources in a different namespace these are not patched.
Example 
```yaml
apiVersion: v1
kind: Foo
metadata:
  name: myFoo
  namespace: default
spec: {}
---
apiVersion: v1
kind: Bar
metadata:
  name: myBar
  namespace: test
spec:
  fooRef:
    name: myFoo
---
nameReference:
- kind: Foo
  version: v1
  fieldSpecs:
    - path: spec/fooRef/name
      kind: Bar
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - foo.yaml
  - bar.yaml

configurations:
  - namereference.yaml

patches:
  - patch: |-
    - op: replace
      path: /metadata/name
      value: myBaz
    target:
      kind: Foo
```
Is not patching the `fooRef/Name` value in `Bar` to `myBaz` as they reside in different namespaces. Is this an expected behaviour? If so, is there a workaround available?

This is a common scenario in for example multi cluster management where resources defining the cluster for the deployment operator are in the default namespace and the actual cluster resources are in a different namespace but you still want to reference the cluster name in all resources associated with managing your cluster. Additionally, to make it more complicated: the second namespace in our use case has the cluster name as well so is a reference too.

**Comment by Shell32-Natsu** [comment]
This is expected. The `name` and `namespace` field in `target` are regular expressions, so you can use `namespace: .*` to match all namespaces.

**Comment by albuch** [comment]
I've already tested this and tested it again and kustomize seems to only apply the patch to all `Foo` in all namespaces but not to its namereferences when setting `namespace: .*` on the patch `target`. 
It's the same output of `kustomize build` for the proposed change as before:
```yaml
apiVersion: v1
kind: Bar
metadata:
  name: myBar
  namespace: test
spec:
  fooRef:
    name: myFoo
---
apiVersion: v1
kind: Foo
metadata:
  name: myBaz
  namespace: default
spec: {}
```

`spec.fooRef.name` of `Bar` is not changed
