### ISSUE TITLE
namePrefix not working for configMapGenerator when used in Component

### ISSUE THREAD

**Issue by Heathland** [kubernetes-sigs/kustomize#3901]
**Describe the bug**

Configmaps generated by a configMapGenerator won't get a namePrefix when the namePrefix is stated in a Component.

**Files that can reproduce the issue**

base/kustomization.yaml
```
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - working-configmap.yaml

components:
  - ../component

configMapGenerator:
- name: example-config
  literals:
    - foo=bar
```
base/working-configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: working-configmap
data:
  player_initial_lives: "3"
```
component/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namePrefix: tst-
```

**Expected output**

```
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  name: tst-example-config-798k5k7g9f
---
apiVersion: v1
data:
  player_initial_lives: "3"
kind: ConfigMap
metadata:
  name: tst-working-configmap
```

**Actual output**

```
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  name: example-config-798k5k7g9f
---
apiVersion: v1
data:
  player_initial_lives: "3"
kind: ConfigMap
metadata:
  name: tst-working-configmap
```

**Platform**

WSL - Ubuntu 18.04.5 LTS
Version:kustomize/v4.1.2
