### ISSUE TITLE
Generating secret from literal removes trailing quote

### ISSUE THREAD

**Issue by lallinger-arbeit** [kubernetes-sigs/kustomize#3902]
**Describe the bug**
When using the `secretGenerator` with literals a trailing quote `"` at the end of the value will be removed from the value.

**Files that can reproduce the issue**

kustomization.yaml:
```
secretGenerator:
  - name: name
    literals:
      - key=value"
```

**Expected output**

``` yaml
apiVersion: v1
data:
  key: dmFsdWUi # => value"
kind: Secret
metadata:
  name: name-55ff4k8ggt
type: Opaque
```

**Actual output**

``` yaml
apiVersion: v1
data:
  key: dmFsdWU= # => value
kind: Secret
metadata:
  name: name-55ff4k8ggt
type: Opaque
```
**Kustomize version**

```
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux

**Additional context**
