### ISSUE TITLE
Improve documentation for configuring generators to work with CRs

### ISSUE THREAD

**Issue by philippe-lavoie** [kubernetes-sigs/kustomize#3923]
**Describe the bug**

I'm using Kyma to define serverless (i.e. lambda) functions.  secretGenerator nor configMapGenerator work as they are not Deployments

**Files that can reproduce the issue**

kustomize.yaml

```yaml
resources:
- fcn-search-orders2.yaml
namespace: dev
configMapGenerator:
  - literals:
    - ODATA_ORDERS_URL=https://something.commerce.ondemand.com/odata2webservices/Order
    name: plumbing
secretGenerator:
  - name: credentials
    envs:
    - secret.properties
  - literals:
    - db-password=123456
    name: sl-demo-app
    type: Opaque
```

fcn-search-orders2.yaml

```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  creationTimestamp: null
  name: search-orders
spec:
  deps: ""
  env:
    - name: ODATA_ORDERS_URL
      valueFrom:
        configMapKeyRef:
          key: ODATA_ORDERS_URL
          name: plumbing
    - name: ODATA_USER
      valueFrom:
        secretKeyRef:
          key: ODATA_USER
          name: credentials
    - name: ODATA_PASSWORD
      valueFrom:
        secretKeyRef:
          key: ODATA_PASSWORD
          name: credentials 
  runtime: nodejs12
  source: "not important for the bug report"
```

**Actual output**

```
apiVersion: v1
data:
  ODATA_ORDERS_URL: https://something.commerce.ondemand.com/odata2webservices/Order
kind: ConfigMap
metadata:
  name: plumbing-56g66cf2dt
  namespace: dev
---
apiVersion: v1
data:
  ODATA_PASSWORD: bmltZGE=
  ODATA_USER: cGhpbDI=
kind: Secret
metadata:
  name: credentials-75cb7f9m64
  namespace: dev
type: Opaque
---
apiVersion: v1
data:
  db-password: MTIzNDU2
kind: Secret
metadata:
  name: sl-demo-app-kt9947h4gc
  namespace: dev
type: Opaque
---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  creationTimestamp: null
  name: search-orders
  namespace: dev
spec:
  deps: ""
  env:
  - name: ODATA_ORDERS_URL
    valueFrom:
      configMapKeyRef:
        key: ODATA_ORDERS_URL
        name: plumbing
  - name: ODATA_USER
    valueFrom:
      secretKeyRef:
        key: ODATA_USER
        name: credentials
  - name: ODATA_PASSWORD
    valueFrom:
      secretKeyRef:
        key: ODATA_PASSWORD
        name: credentials
  runtime: nodejs12
  source: not important for the bug report
```

It was expected that the secretKeyRef and configkeyRef would leverage the newly created secret and config map. However now, the hash is not appended.

Can kustomize just check for a secretKeyRef construct ? It looks like Deployment is hard coded

**Kustomize version**

v4.1.3 

**Platform**

Linux & Windows

**Additional context**
