### ISSUE TITLE
Replacements transformer overwrites source field (when multiple fieldPaths are specified?)

### ISSUE THREAD

**Issue by jameshochadel** [kubernetes-sigs/kustomize#3927]
**Describe the bug**

When using the new Replacements transformer with multiple target `fieldPaths` in the same target yaml array, the transformer transforms not only the target field, but the source field as well. (I did not test with other targets like maps, just sequences.)

This appears to occur iteratively, once for each entry in `fieldPaths`. This results in the target transformation also being incorrect, with the replacement repeated. See actual output below.

**Files that can reproduce the issue**

Files to reproduce the issue are here: https://github.com/jameshochadel/kustomize-replacements/tree/main/repeat

**Expected output**

```
apiVersion: v1
data:
  value: example
kind: ConfigMap
metadata:
  name: source
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: some-secret
spec:
  backendType: secretsManager
  data:
  - key: some-prefix-example
    name: first
    property: first
    version: latest
  - key: some-prefix-example
    name: second
    property: second
    version: latest
  - key: some-prefix-example
    name: third
    property: third
    version: latest
```

**Actual output**

```
apiVersion: v1
data:
  value: some-prefix-some-prefix-some-prefix-example
kind: ConfigMap
metadata:
  name: source
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: some-secret
spec:
  backendType: secretsManager
  data:
  - key: some-prefix-example
    name: first
    property: first
    version: latest
  - key: some-prefix-some-prefix-example
    name: second
    property: second
    version: latest
  - key: some-prefix-some-prefix-some-prefix-example
    name: third
    property: third
    version: latest
```

**Kustomize version**

{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

n/a. But, bugs aside, huge thanks to the team for adding this transformer! I'm very excited to replace our `vars` usages with this.
