### ISSUE TITLE
Replacements transformer list indexing fails for keys with '.' character

### ISSUE THREAD

**Issue by jameshochadel** [kubernetes-sigs/kustomize#3928]
**Describe the bug**

The new Replacements transformer's `fieldPaths` supports two ways of specifying elements in a list:

1. By index, like `spec.data.0.field`, or
2. By key, like `spec.data.[name=something].field`. 

The second method works for most strings, but if the string contains a `.` character, kustomize seems to try parsing it like it's one of the field accessors, rather than part of the selector.

**Files that can reproduce the issue**

Files to reproduce are here: https://github.com/jameshochadel/kustomize-replacements/tree/main/dotfile

**Expected output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: source
data:
  value: example
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: some-secret
spec:
  backendType: secretsManager
  data:
    - key: some-prefix-example
      name: .first
      version: latest
      property: first
    - key: some-prefix-example
      name: second
      version: latest
      property: second
```

**Actual output**

```
Error: wrong Node Kind for spec.data expected: MappingNode was SequenceNode: value: {- key: some-prefix-replaceme
  name: .first
  version: latest
  property: first
- key: some-prefix-replaceme
  name: second
  version: latest
  property: second}
```

**Kustomize version**

{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

n/a (but thanks again for all you do!)
