### ISSUE TITLE
Trouble configuring ReplacementTransformer when replacements are in separate file

### ISSUE THREAD

**Issue by jameshochadel** [kubernetes-sigs/kustomize#3933]
**Describe the bug**

Based on the docs from [this PR](https://github.com/kubernetes-sigs/cli-experimental/pull/158/files?short_path=97f52cf#diff-97f52cf06adf128007d4c818d9d9832d26c786d008f4025d6b48cb0e48d1ed1e) on `kubernetes-sigs/cli-experimental`, the Replacements transformer should support replacements being specified in a separate file (versus inline). In practice, this seems to result in a JSON decoding error.

**Files that can reproduce the issue**

Files to reproduce: https://github.com/jameshochadel/kustomize-replacements/tree/main/file

**Expected output**

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: some-secret
spec:
  backendType: secretsManager
  data:
    - key: some-prefix-example
      name: first
      version: latest
      property: first
```

**Actual output**

```
Error: trouble configuring builtin ReplacementTransformer with config: `
Replacements:
- path: replacements.yaml
  source: null
  targets: null
`: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type types.Replacement
```

**Kustomize version**

{Version:kustomize/v3.10.0 GitCommit:602ad8aa98e2e17f6c9119e027a09757e63c8bec BuildDate:2021-02-10T01:11:02+00:00 GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

I tried a few other permutations, like including the `replacements:` top-level key in the file, omitting `path:` from the replacements map in the kustomization, but wasn't able to find a working configuration.

**Comment by jameshochadel** [comment]
cc @natasha41575 probably 😄 Thank you!

**Comment by natasha41575** [comment]
Thank you for trying this. There is a mistake in the documentation that I will fix today.

The contents of `replacements.yaml` should be of the format: 
```
source:
  kind: Deployment
  fieldPath: metadata.name
targets:
   - select: 
       name: my-resource
```

[See the test here for reference.](https://github.com/kubernetes-sigs/kustomize/blob/d9435bd1b13a6764b9d271001e61837199494d1c/api/krusty/replacementtransformer_test.go#L60)
