### ISSUE TITLE
Allow kustomize edit add secret to take --behavior option

### ISSUE THREAD

**Issue by makikata** [kubernetes-sigs/kustomize#3935]
Hello all

I have a base overlay defininig

```yaml
# k8s/base/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: app-secret
    literals:
      - SECRET=somesecret
```

When I build my application I would like to add/modify some other entries in that secret . 
My use case is that during the build stage a script adds some other secrets

```shell
cd "${tmpdir}"
./generate-other-secret.sh
kustomize create --resources ../k8s/base
kustomize edit add secret app-secret --from-file=OTHER_SECRET=other-secret.txt
kustomize build . | kubectl apply -f -
```

The resulting kustomization.yaml file is

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../k8s/base

secretGenerator:
- files:
  - OTHER_SECRET=other-secret.txt
  name: app-secret
  type: Opaque
```

The issue is that on `kustomize build` it raises an error:

```
Error: merging from generator exists .... behavior must be merge or replace
```

There is no `--behavior` switch in the `kustomize` command as for now.

It would be nice to have it like for `--namespace` https://github.com/kubernetes-sigs/kustomize/issues/595
