### ISSUE TITLE
Document KRM-style plugin usage with Kustomize build

### ISSUE THREAD

**Issue by irvifa** [kubernetes-sigs/kustomize#3936]
**Is your feature request related to a problem? Please describe.**

As far as I know there's no example on how to pass the starlark function and substitution value
during the `kustomize build` phase.

**Describe the solution you'd like**

I came across this [PR](https://github.com/kubernetes-sigs/kustomize/pull/2267) that mentioned that starlark is now supported within kustomize, however there's no example on how we can pass the starlark function as well as the value substitution on the kustomize. For example I have this function:

```
def run(r, an):
  for resource in r:
    # mutate the resource
    resource["metadata"]["namespace"] = an

an = ctx.resource_list["functionConfig"]["data"]["value"]

run(ctx.resource_list["items"], an)
```
 
What I'd like to do is when I pass `--enable-star` I also would like to pass the function as well.

**Comment by KnVerey** [comment]
To use a KRM-style plugin (starlark or otherwise) with `kustomize build`, you need to specify it declaratively as an annotation on your functionconfig. For example, you'd put something like this in a file, and reference that file from the `generators` or `transformers` field as appropriate.

```yaml
apiVersion: someteam.example.com/v1
kind: Annotator
metadata:  
  name: my-annotator  
  annotations:    
    config.kubernetes.io/function: |      
      starlark:        
        path: myscript.star
data:
  value: foo        
```

See also [this test](https://github.com/kubernetes-sigs/kustomize/blob/39f24ef8d2e02ccf894e06a168a9aec1571da290/plugin/someteam.example.com/v1/starlarkmixer/StarlarkMixer_test.go#L23-L25)

/kind documentation
/retitle Document KRM-style plugin usage with Kustomize build
