### ISSUE TITLE
Ability to load resources from upper directories

### ISSUE THREAD

**Issue by terion-name** [kubernetes-sigs/kustomize#3959]
If I write something like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base.yaml
```

I get `Error: accumulating resources: accumulateFile "accumulating resources from '../../../base.yaml': security; `.

IMO, this is very dumb limitation that gives only pain and nothing more.
If you do gitops you'll want something like this:

```
base-app-template.yml
env-name
|-env-specific-kustomize.yml
|-apps
|-|-app-kustomize.yml
```

Where each child manifest "inherits" upper to make specific customisations. And with this limitation that can't be overridden with any flag you can't do this

**Comment by stribb** [comment]
You can certainly inherit directories of resources. Here's an example from my CWD:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
commonLabels:
  app.kubernetes.io/name: loki
resources:
  - ../../base/
images:
  - name: grafana/loki
    newTag: 2.2.0
```
