### ISSUE TITLE
StatefulSet from base can't use generated ConfigMaps in overlay

### ISSUE THREAD

**Issue by stribb** [kubernetes-sigs/kustomize#3960]
**Describe the bug**

I’m kustomizing Loki. I had a generated configMap in base and now needed to move it to my overlays. When I looked at what `kustomize` did, it looks like the StatefulSet isn’t respecting the overlaid ConfigMap: the generated volume name is just plain `loki` rather than having any hash suffix appended.

**Files that can reproduce the issue**
In `base/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
commonLabels:
  app.kubernetes.io/name: loki
resources:
  - statefulset.yaml
```

In `base/statefulset.yaml`:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  serviceName: loki-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: loki
    spec:
      containers:
        - name: loki
          image: "grafana/loki:latest"
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
              readOnly: true
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: loki
```

In `overlays/dev/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
configMapGenerator:
  - name: loki
    files:
      - loki.yaml
```

In `overlays/dev/loki.yaml`:
```yaml
server:
  http_listen_port: 3100
```

**Expected output**

The StatefulSet should reference the generated ConfigMap including its hash suffix.

**Actual output**

```yaml
apiVersion: v1
data:
  loki.yaml: |
    server:
      http_listen_port: 3100
kind: ConfigMap
metadata:
  name: loki-ggfb54c9tf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: loki
  name: loki
  namespace: observability
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  serviceName: loki-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
      name: loki
    spec:
      containers:
      - args:
        - -config.file=/etc/loki/loki.yaml
        image: grafana/loki:latest
        name: loki
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/loki
          name: config
          readOnly: true
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: loki
  updateStrategy:
    type: RollingUpdate
```

Note the volumeMounts section: this should reference `loki-ggfb54c9tf` not the bare `loki`.

**Kustomize version**

`{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-23T07:52:43+00:00 GoOs:linux GoArch:amd64}`

**Platform**

Linux
