### ISSUE TITLE
`kustomize build` not honoring the `retainKeys` patchStrategy

### ISSUE THREAD

**Issue by vit-zikmund** [kubernetes-sigs/kustomize#3981]
**Describe the bug**

[Since `kustomize` v3.8.0](https://github.com/kubernetes-sigs/kustomize/issues/2790) the Strategic Merge patches using the `$retainKeys` directive no longer work as they would with `kubectl patch`. The `$retainKeys` directive is now considered a normal key and the usual merging occurs.

**Files that can reproduce the issue**
<details><summary><code>kustomization.yaml</code></summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - retainkeys-demo.yaml            
patchesStrategicMerge:     
  - retainkeys-demo-patch.yaml
```
</details>
<details><summary><code>retainkeys-demo.yaml</code></summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retainkeys-demo
spec:
  selector:
    matchLabels:
      app: retainkeys-demo
  template:
    metadata:
      labels:
        app: retainkeys-demo
    spec:
      containers:
      - image: retainkeys-demo-img   
        name: retainkeys-demo-ctr  
      volumes:
      - emptyDir: {}   
        name: my-volume  
```
</details>
<details><summary><code>retainkeys-demo-patch.yaml</code></summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retainkeys-demo
spec:
  template:
    spec:
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-claim
        $retainKeys:
        - name
        - persistentVolumeClaim
```
</details>

**Expected output**

I'd expect it to be on par with the outcome of a `kubectl patch`, i.e. `emptyDir: {}` gone from `volumes` and no `$retainKeys`:
```bash
kubectl  patch --dry-run=client --filename=retainkeys-demo.yaml --patch-file=retainkeys-demo-patch.yaml -o yaml
```
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retainkeys-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: retainkeys-demo
  template:
    metadata:
      labels:
        app: retainkeys-demo
    spec:
      containers:
      - image: retainkeys-demo-img
        name: retainkeys-demo-ctr
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-claim

```

**Actual output**

`kustomize build` obviously ignores the `$retainKeys` directive and adds it as a normal key:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retainkeys-demo
spec:
  selector:
    matchLabels:
      app: retainkeys-demo
  template:
    metadata:
      labels:
        app: retainkeys-demo
    spec:
      containers:
      - image: retainkeys-demo-img
        name: retainkeys-demo-ctr
      volumes:
      - $retainKeys:
        - name
        - persistentVolumeClaim
        emptyDir: {}
        name: my-volume
        persistentVolumeClaim:
          claimName: my-claim
```

**Kustomize version**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
0 tlwhitec@feathora:~/test/kustomize/retainkeys
$ kustomize version
{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:linux GoArch:amd64}
```

**Platform**

linux/amd64

**Additional context**

Although this issue has been raised last year, it has been brushed off with a vague ["It looks like the `$retainKeys` might be useful to kubectl"](https://github.com/kubernetes-sigs/kustomize/issues/2790#issuecomment-710359056), but I don't think that's correct. Maybe it might be useful for `kubectl patch`, but not for `kubectl apply` which is the usual target of `kustomize build`.

I think, overall, that when `kustomize` applies a [strategic merge, but whatever] patch, it shouldn't be different to when `kubectl` does so.

Per [current docs](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#notes-on-the-strategic-merge-patch-using-the-retainkeys-strategy) "The `retainKeys` strategy does not work for all objects.", but it should for this one as demonstrated above (and checked in the [kubernetes code](https://github.com/kubernetes/api/blob/kubernetes-1.21.1/core/v1/types.go#L2942)).

I know there's a [workaround](https://stackoverflow.com/a/66799699/921269) by setting a key to `null`, however that's obviously not the aim of this issue :) Thanks for any help!
