### ISSUE TITLE
`replacements` doesn't work for mapping values with '.'

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#3983]
We want to support a `fieldPath` such as:

```
source:
  kind: ConfigMap
  name: my-config
  fieldPath: data.my-var
targets:
- select:
    name: my-service
    kind: Service
  fieldPaths:
  - metadata.annotations.[service.beta.kubernetes.io/load-balancer-abc]
```

original request: https://github.com/kubernetes-sigs/kustomize/pull/3931#issuecomment-858583265

Alternative:

Require users to escape the delimiters, e.g.
`metadata.annotations.service\.beta\.kubernetes\.io/load-balancer-abc`
which is supported, but seems a bit inconvenient.
