### ISSUE TITLE
Change replica transformer name matching

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#3988]
When using the replicas transformer, it is not always obvious which resources will be altered. For example using a rule like:
```yaml
replicas:
   - name: worker
     count: 5
```
implicitly translates into
```yaml
 replicas:
   - name: worker*
     count: 5
```
This behavior is useful but it should be made clear to the user when it is an exact match and when globing will be used.

**Describe the solution you'd like**
I would like for the name field to be an exact match by default
so that:
```yaml
replicas:
   - name: worker
     count: 5
```
would match `worker` only and not `worker-test`. But also be able to pass a pattern when needed like in:
```yaml
 replicas:
   - name: worker-*
     count: 5
```
This looks like a safer/saner default and offers more possibility.

**Additional context**
Kustomize encourage the use of overlays and it is common to use overlays of overlays. With name suffixes and prefixes transformers, the name of resources generated by multiple layers of overlays is automated and well structured. That's one of the strong point of working with kustomize.
Having an overlay `prod` including an overlay `py3` including a base worker can for example result in a deployment named: `worker-py3-prod`. Unfortunately this kind of pattern, despite being at the core of kustomize get totally messed up by the replica transformer. In this situation, it would be impossible to alter the replica count of a deployment called `worker-py3` withoutt also override the `worker-py3-prod` deployment.
