### ISSUE TITLE
Allow using vars in ValidatingWebhookConfiguration caBundle

### ISSUE THREAD

**Issue by edbighead** [kubernetes-sigs/kustomize#3989]
**Is your feature request related to a problem? Please describe.**
Unable to use [vars](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/) in [ValidatingWebhookConfiguration](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io)

**Describe the solution you'd like**
Use case is inserting variable where `objref` is a Secret.
```

vars:
- name: CA_BUNDLE
  objref:
    kind: Secret
    name: cert
    apiVersion: v1
  fieldref:
    fieldpath: data.value
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: $(CA_BUNDLE)
    service:
      name: webhook-service
      namespace: system
      path: /validate
```

**Describe alternatives you've considered**
Pathing webhook directly:

_kustomize.yaml_
```
patchesJson6902:
- target:
    group: admissionregistration.k8s.io
    version: v1beta1
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  path: patch_webhook.yaml
```
_patch_webhook.yaml_
```
- op: replace
  path: /webhooks/0/clientConfig/caBundle
  value: LS0xxxxxxdJTiBDR
```

**Additional context**
