### ISSUE TITLE
`kustomize build` with replacements alter the replacement source

### ISSUE THREAD

**Issue by vmwiz** [kubernetes-sigs/kustomize#4003]
When using `replacements` to fetch a value from a label and use it somewhere else to build a path, the label of the source is replaced by the target value

**Files that can reproduce the issue**
<details>
  <summary>kustomization.yaml</summary>

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: development
  platform: acme_corp

resources:
- namespace.yaml
- application.yaml

replacements:
- source:
    kind: Namespace
    name: test
    fieldPath: metadata.labels.environment
  targets:
  - select:
      kind: Application
    fieldPaths:
    - spec.source.path
    options:
      delimiter: "/"
      index: 2
- source:
    kind: Namespace
    name: test
    fieldPath: metadata.labels.platform
  targets:
  - select:
      kind: Application
    fieldPaths:
    - spec.source.path
    options:
      delimiter: "/"
      index: 3
```
</details>
<details>
  <summary>namespace.yaml</summary>

```
apiVersion: v1
kind: Namespace
metadata:
  name: test
```
</details>
<details>
  <summary>application.yaml</summary>

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: eks-auth
spec:
  project: infra-components
  source:
    repoURL: https://git.repo.local/eks.git
    targetRevision: HEAD
    path: eks-auth/overlay
  destination:
    namespace: kube-system
```
</details>

**Expected output**

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: development
    platform: acme_corp
  name: test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    environment: development
    platform: acme_corp
  name: eks-auth
  namespace: test
spec:
  destination:
    namespace: kube-system
  project: infra-components
  source:
    path: eks-auth/overlay/development/acme_corp
    repoURL: https://git.repo.local/eks.git
    targetRevision: HEAD
```

**Actual output**

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    environment: eks-auth/overlay/development
    platform: eks-auth/overlay/development/acme_corp
  name: test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    environment: development
    platform: acme_corp
  name: eks-auth
  namespace: test
spec:
  destination:
    namespace: kube-system
  project: kube-infra
  source:
    path: eks-auth/overlay/development/acme_corp
    repoURL: https://git.repo.local/eks.git
    targetRevision: HEAD
```

**Kustomize version**

```
❯ kustomize version
{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux

**Additional context**
