### ISSUE TITLE
kustomize edit set image removes "replacements" block in the kustomization.yaml

### ISSUE THREAD

**Issue by awesomeinsight** [kubernetes-sigs/kustomize#4009]
We're using kustomize 4.1.3
Applying a "kustomize edit set image foo=bar_tag removes the complete replacements block from the kustomization file.

**Files that can reproduce the issue**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git::https://foo.com/base.git?ref=master

patchesStrategicMerge:
- ./patches/loadbalancer-ip.yaml

configMapGenerator:
  - name: global-environment-configuration     
    envs:
      - global.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - path: ./replacements/global-config.storageAccountName.yaml
  - path: ./replacements/global-config.eventHub_name.yaml

images:
  - name: foo
    newName: acr_repo
    newTag: tag
  - name: bar
    newName: acr_repo
    newTag: tag
```

**Expected output**

replacements block stays in the file and is not removed

**Actual output**

replacements block is removed from kustomization file

**Kustomize version**

4.1.3

**Platform**
Linux/Ubuntu 21.04
