### ISSUE TITLE
[Question] How to use ReplacementTransformer for fields that need a text placeholder?

### ISSUE THREAD

**Issue by rkr-kununu** [kubernetes-sigs/kustomize#4012]
Since it's been announced that `vars` will be deprecated in favor of ReplacementTransformer, I'd like to replace our use of `vars` in our test environment.

However, we're using Traefik's CRDs which is running within a dedicated namespace (with a wildcard ssl cert).  This means each test environment exists within their respective namespace and share a single (public) Traefik instance to mock our public facing services.

Traefik's CRD introduces [IngressRoute](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute) which has a [Match](https://doc.traefik.io/traefik/routing/routers/#rule) section which contains an arbitrary number of rules.  Because our instance of Traefik is shared, we use the Host in the request to have Traefik route the request to the proper namespace.

We've been using `vars` to extract the equivalent of the namespace.  So our IngressRoute looks something like:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app-cms
spec:
  entryPoints:
    - websecure
  routes:
  - match:
      Host(`www-$(NAMESPACE).example.com`) && Path(`/test$}`)
    kind: Rule
    services:
    - name: app-cms
      namespace: $(NAMESPACE)
      port: 80
  - match:
      Host(`www-$(NAMESPACE).example.com`) && (PathPrefix(`/example`)
      || Path(
          `/`, `/a`, `/b`, `/c`, `/d`)
      )
    kind: Rule
    services:
    - name: app-cms
      namespace: $(NAMESPACE)
      port: 80
  tls: {}
```

However, from the documentation/experiments I've made it appears that `ReplacementTransformer` is pretty limited when it comes to supporting how we're using `Host()`.

Is there some undocumented feature I'm missing?

**Comment by natasha41575** [comment]
This is a problem we are aware of - a similar use case is described in https://github.com/kubernetes-sigs/kustomize/issues/3978. For now we are thinking about using generators for such use cases, but it will be difficult for us to provide generators for all possible CRDs. 

We've written a [builtin generator plugin](https://github.com/kubernetes-sigs/kustomize/pull/3914) for generating service account resources. Something you can do is write your own generator plugin ([a guide is here](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/)) for your CRD.

**Comment by rkr-kununu** [comment]
Thank you for the feedback - I'm relieved to know it's on the radar.  However, I'm not too thrilled with the prospect of needing to write/install a custom generators for the various CRDs we want to use or expecting the kubernetes community to provide them.  Especially, when great tools like [crossplane](https://github.com/crossplane/crossplane) which create an easy way to make custom opinionated CRDs.

Could we instead unify the configuration of the `ReplacementTransformer` with the `ValueAddTransformer` and extend (potentially both of them)?

An example of the current `ValueAddTransformer`:
```yaml
apiVersion: builtin
kind: ValueAddTransformer
metadata:
  name: MyNamespaceFolder

targets:
  - selector:
      kind: Namespace
    fieldPath: metadata/annotations/my-namespace
    # Replace any existing value
    filePathPosition: 0
```

An example of the current `ReplacementTransformer`:
```yaml
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: notImportantHere
replacements:
- source: 
    kind: Deployment
    fieldPath: spec.template.spec.containers.0.image
  targets:
  - select:
      kind: Deployment
    fieldPaths: 
    - spec.template.spec.containers.1.image
```

...by "unifying" I specifically mean take the `targets` yaml structure from the `ValueAddTransformer` and use it in `ReplacementTransformer` (thus deprecating the current `targets` yaml structure).

```yaml
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: notImportantHere
replacements:
- source: 
    kind: Deployment
    fieldPath: spec.template.spec.containers.0.image
  targets:
  - selector:
      kind: Deployment
    fieldPath: spec.template.spec.containers.1.image
    # Replace any existing value
    filePathPosition: 0
```

Then we can modify the `ReplacementTransformer` (and optionally the `ValudAddTransformer`) to "extend" it's features like `filePathPosition` and introduce a generic one like `placeholderName`.

So, how this would relate to my use-case...  Given:
the `replacement.yaml`
```yaml
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: notImportantHere
replacements:
- source: 
    kind: Namespace
    fieldPath: metadata/name
  targets:
  - selector:
      kind: IngressRoute
    fieldPath: spec.routes.*.match
    # This will replace all-occurrences of NAMESPACE with the value referred in replacements/source/fieldPath (ie: test)
    placeholderName: NAMESPACE
  - selector:
      kind: IngressRoute
    fieldPath: spec.routes.*.services.*.namespace
    # Replace any existing value
    filePathPosition: 0
```
...and the `routes.yaml`
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app-cms
  annotations:
    my-namespace: test
spec:
  entryPoints:
    - websecure
  routes:
  - match:
      Host(`www-NAMESPACE.example.com`) && Path(`/test$}`)
    kind: Rule
    services:
    - name: app-cms
      namespace: IGNORED
      port: 80
  - match:
      Host(`www-NAMESPACE.example.com`) && (PathPrefix(`/example`)
      || Path(
          `/`, `/a`, `/b`, `/c`, `/d`)
      )
    kind: Rule
    services:
    - name: app-cms
      namespace: IGNORED
      port: 80
  tls: {}
```
Which would ultimately yield:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: app-cms
spec:
  entryPoints:
    - websecure
  routes:
  - match:
      Host(`www-test.example.com`) && Path(`/test$}`)
    kind: Rule
    services:
    - name: app-cms
      namespace: test
      port: 80
  - match:
      Host(`www-test.example.com`) && (PathPrefix(`/example`)
      || Path(
          `/`, `/a`, `/b`, `/c`, `/d`)
      )
    kind: Rule
    services:
    - name: app-cms
      namespace: test
      port: 80
  tls: {}
```

**Comment by rkr-kununu** [comment]
/remove-lifecycle stale
For me, this is really a critical defect in the ReplacementTransformer that needs to be resolved before `vars` can be retired.

**Comment by jonashackt** [comment]
We had the same problem and also didn't want to write/maintain our own custom generator plugin. We created [a full-blown stackoverflow Q&A](https://stackoverflow.com/a/71704024/4964553) - but here are the brief steps:

As a workaround we can create yaml files inline in our console using the syntax `cat > ./myyamlfile.yml <<EOF ... EOF` and also use the inline variable substitution. So first define the branch name as variable:
```
    NAMESPACE=foobar
```

And then use the described syntax to create a `ingressroute-patch.yml` file inline:

```
    cat > ./ingressroute-patch.yml <<EOF
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: app-cms
    spec:
      entryPoints:
        - websecure
      routes:
      - match:
          Host(`www-$NAMESPACE.example.com`) && Path(`/test$}`)
        kind: Rule
        services:
        - name: app-cms
          namespace: $NAMESPACE
          port: 80
    
    EOF
```

The last step is to use the `ingressroute-patch.yml` file as `patchesStrategicMerge` inside our `kustomization.yaml` like this:
```
    patchesStrategicMerge:
      - ingressroute-patch.yml
```
Now running `kustomize build .` should output the desired IngressRoute:

```
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: app-cms
    spec:
      entryPoints:
        - websecure
      routes:
      - match:
          Host(`www-foobar.example.com`) && Path(`/test$}`)
        kind: Rule
        services:
        - name: app-cms
          namespace: foobar
          port: 80
```

It's only a workaround, but might help to bridge the time until @rkr-kununu 's great idea might get implemented into Kustomize.
