### ISSUE TITLE
namespace of ClusterRoleBinding subject only overwritten if default

### ISSUE THREAD

**Issue by valorl** [kubernetes-sigs/kustomize#4015]
**Describe the bug**

When I use `namespace` in my kustomization.yaml in order to add/overwrite the namespace of all resources, 
it does so wherever relevant, including `RoleBinding.subjects.namespace`, but _not_ `ClusterRoleBinding.subjects.namespace`, _if_ the namespace is anything other than `default` .

**Files that can reproduce the issue**
kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crb.yaml
namespace: my-namespace
...
```

crb.yaml

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: argo
```

**Expected output**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: my-namespace
```

**Actual output**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: argo
```

**Kustomize version**
Tried with `3.8.6` as well as `4.1.3`.

**Platform**
Linux

**Additional context**

It works if the original subject namespace is "default", but that defeats the purpose. 
For me, the value of using kustomize comes from the fact that I can apply an adjusted version of third party manifests, _without having to touch the officially provided manifest bundle_.

**Comment by natasha41575** [comment]
[The paths here](https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namespace.go) might need to be changed to something like `subjects[]/namespace`.

Are you sure this bug doesn't also happen for `RoleBinding.subjects.namespace`? On my side I reproduced the issue for both ClusterRoleBinding and RoleBinding.

**Comment by natasha41575** [comment]
There is a test for the current behavior here https://github.com/kubernetes-sigs/kustomize/blob/dac84d867ecdc5e2513a7ea27ef652f88a8e3fa4/api/krusty/rolebindingacrossnamespace_test.go#L219 which fails when the fix for this is implemented. The comment:

```
// The ServiceAccount in subjects in role binding can be across namespace
// but the roleRef is not. This test is used to cover such case.
```

makes me think this is intentional Because you can simply reference a ServiceAccount from another namespace in the subjects field, I question if updating the subjects field namespace is correct.

@KnVerey WDYT?

**Comment by valorl** [comment]
> Are you sure this bug doesn't also happen for `RoleBinding.subjects.namespace`?

You're right, isolated it behaves the same. In my case, the following thing you mentioned is happening, as I'm using a full yaml doc stream bundle of manifests for Argo Workflows. Would be nice if that happened for CRBs too.

> update namespace references the same way that we do with name references. For example - only update the subjects field namespace if the service account itself is among the resources in the kustomization and its namespace has been updated.

**Comment by natasha41575** [comment]
Did some digging, and I think the behavior is intentional.

Because you can reference a service account from another namespace in a role binding, kustomize does not automatically update the subjects/namespace field.

Instead, it will update the namespace if that subject account is also among the list of resources kustomize is aware about.

For example:

kustomization.yaml:
```
resources:
- crb.yaml
- sa.yaml
namespace: new
```

crb.yaml:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role
subjects:
- kind: ServiceAccount
  name: server
  namespace: old
```

Output of `kustomize build`: 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role
subjects:
- kind: ServiceAccount
  name: server
  namespace: new
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: new
```

So kustomize does not blindly update the `subjects[]/namespace` field, but if it updates a service account's namespace, it will also know to update references to that service account.
