### ISSUE TITLE
Only the last patchesJson6902-patch is applied

### ISSUE THREAD

**Issue by badamowicz** [kubernetes-sigs/kustomize#4032]
**Describe the bug**
When trying to apply more than one patch of type _patchesJson6902_, only the last one is applied.

**Files that can reproduce the issue**
The attached archive [patchesJson6902-bug-example.zip](https://github.com/kubernetes-sigs/kustomize/files/6754898/patchesJson6902-bug-example.zip) contains all files and directories to reproduce the problem.

**Detailed description**
Given this structure (contained in the attached ZIP) for deploying a simple Helm release whose values are to be patched by two _patchesJson6902_ patches:
```
deploy/
├── base
│   ├── kustomization.yaml
│   └── some-helm-release.yaml
└── env1
    ├── ingress-patch.yaml
    ├── kustomization.yaml
    └── user-spec-patch.yaml
```

base/some-helm-release.yaml:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: some-helm-release
  namespace: flux-system
spec:
  # where to deploy resources defined by chart:
  targetNamespace: some-ns
  interval: 20s
  chart:
    spec:
      chart: ./helm/tekton/some-helm-release
      version: '0.0.2'
      sourceRef:
        kind: GitRepository
        name: some-git-repo
        namespace: flux-system
      interval: 20s
```
base/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - some-helm-release.yaml
```
env1/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patchesJson6902:
- path: user-spec-patch.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    kind: HelmRelease
    name: some-helm-release

- path: ingress-patch.yaml
  target:
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    kind: HelmRelease
    name: some-helm-release
```
env1/ingress-patch.yaml:
```
---
- op: add
  path: /spec
  value:
    values:
      ingress:
        fqdnHostName: some.ingress.host
```
env1/user-spec-patch.yaml:
```
---
- op: add
  path: /spec
  value:
    values:
      misc:
        emailRecipient: some.name@some.host
```

**Expected output**
The expected output of command
```
$ kustomize build env1/
```
is:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: some-helm-release
  namespace: flux-system
spec:
  values:
    ingress:
      fqdnHostName: some.ingress.host
    misc:
        emailRecipient: some.name@some.host
```
**Actual output**
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: some-helm-release
  namespace: flux-system
spec:
  values:
    ingress:
      fqdnHostName: some.ingress.host
```
When changig the order of the patches to be applied, the output is:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: some-helm-release
  namespace: flux-system
spec:
  values:
    misc:
      emailRecipient: some.name@some.host
```
So obviously only the last patch to be applied is actually applied. Seems the first one is kind of discarded.

**Kustomize version**
```
$ kustomize version
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}
```

**Platform**
```
$ uname -a
Linux workmachine 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
**Additional context**
none

**Comment by natasha41575** [comment]
I see you're using v4.2.0 - I'm wondering, were you able to successfully apply both patches in a previous version?

**Comment by badamowicz** [comment]
Made some more tests with these versions:
* v4.1.3
* v4.1.0
* v4.0.1
* v3.10.0
The result was always the same. Only the last patch gets applied.

**Comment by badamowicz** [comment]
One addition which I didn't notice when filing this issue: The whole chart spec of the HelmRelease is also missing. So actually the expected output should be:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: some-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm/tekton/some-helm-release
      interval: 20s
      sourceRef:
        kind: GitRepository
        name: some-git-repo
        namespace: flux-system
      version: 0.0.2
  interval: 20s
  targetNamespace: some-ns
  values:
    ingress:
      fqdnHostName: some.ingress.host
    misc:
      emailRecipient: some.name@some.host
```

**Comment by natasha41575** [comment]
I think the issue is the way you are doing your patches.

```
- op: add
  path: /spec
  value:
    values:
      misc:
        emailRecipient: some.name@some.host
```

Will add the value 

```
  value:
    values:
      misc:
        emailRecipient: some.name@some.host
``` 

to the path `/spec`. This results in it being overwritten. Both patches are applied, but because they are overwriting `/spec`, one overwrites the other and also overwrites the chart spec, which is why it is missing. 

The fix is the altering the patches to the following:

`env1/user-spec-patch.yaml`
```
- op: add
  path: /spec/values
  value: 
    misc:
      emailRecipient: some.name@some.host
```

`env1/ingress-patch.yaml`
```
- op: add
  path: /spec/values/misc/fqdnHostName
  value:
    some.ingress.host
```

With these patches I was able to produce the output you desire.
