### ISSUE TITLE
When using an simple overlay with a namePrefix on a base that contains replacements the prefix does not end up on the target values.

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#4034]
See the test in https://github.com/kubernetes-sigs/kustomize/pull/4031.

```
   EXPECTED                         ACTUAL
   --------                         ------
   apiVersion: apps/v1              apiVersion: apps/v1
   kind: Deployment                 kind: Deployment
   metadata:                        metadata:
     name: prefix-target              name: prefix-target
   spec:                            spec:
     template:                        template:
       spec:                            spec:
         containers:                      containers:
X        - image: prefix-source           - image: source
           name: nginx                      name: nginx
   ---                              ---
   apiVersion: apps/v1              apiVersion: apps/v1
   kind: Deployment                 kind: Deployment
   metadata:                        metadata:
     name: prefix-source              name: prefix-source
   spec:                            spec:
     template:                        template:
       spec:                            spec:
         containers:                      containers:
         - image: nginx:newtag            - image: nginx:newtag
           name: nginx                      name: nginx
```

**Comment by natasha41575** [comment]
Closing this issue. After taking a closer look I believe this is intended behavior.

**Comment by rjferguson21** [comment]
@natasha41575 I'd like to provide another example to illustrate similar behavior that I believe breaks user expectations and would make it very difficult to maintain a reusable base that contained replacements.   

*base/kustomization.yaml*
```
namespace: base-namespace
configMapGenerator:
  - name: bluecm
    literals:
      - color=blue
  - name: redcm
    literals:
      - bluenamespace=base-namespace
replacements:
- source:
    kind: ConfigMap
    name: bluecm
    fieldPath: metadata.namespace
  targets:
  - select:
      name: redcm
    fieldPaths:
    - data.bluenamespace
```

*kustomization.yaml*
```
resources:
  - base
namespace: overlay-namespace
```

This yields:
```
apiVersion: v1
data:
  color: blue
kind: ConfigMap
metadata:
  name: bluecm-747dfcb89d
  namespace: overlay-namespace
---
apiVersion: v1
data:
  bluenamespace: base-namespace
kind: ConfigMap
metadata:
  name: redcm-mfbbg4gd6c
  namespace: overlay-namespace
```

I can appreciate that this is a difficult problem to solve, but I think it creates a bit of a mine field for the user when using replacements in a base.  In our use case we have an overlay that is applied on all of our application deployments that sets things like the `namePrefix` and `namespace`.  Our assumption would be that the application's base could exercise the `replacements` functionality without fear of a downstream overlay doing something that would compromise the functionality by utilizing features like `namespace`.
