### ISSUE TITLE
nameSuffix does not propagate to deployment selector in Service objects

### ISSUE THREAD

**Issue by megakoresh** [kubernetes-sigs/kustomize#4038]
`nameSuffix` property does not propagate to `deployment` selector in `Service` objects. Meaning that if deployment name is `deployment` and `nameSuffix: -test`, the generated Service definition will have selector referencing `deployment` and not `deployment-test` as would be expected

Original files:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
nameSuffix: -test
generatorOptions:
  disableNameSuffixHash: true
---
kind: Service
apiVersion: v1
metadata:
  name: vault-service
spec:
  selector:
    deployment: vault-deployment
  ports:
  - name: http
    protocol: TCP
    port: 8200
    targetPort: 8200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
spec:
  replicas: 1
...
```

After I run `kustomize build -k vault/test`

```yaml
apiVersion: v1
kind: Service
metadata:
  name: vault-service-test
  namespace: vault
spec:
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    deployment: vault-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment-test
  namespace: vault
spec:
...
```

**Expected output**

Reference includes `nameSuffix`

**Actual output**

Reference does not include `nameSuffix` 

**Kustomize version**

{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}

**Platform**

Linux

**Additional context**

N/A
