### ISSUE TITLE
[Question] Change annotations transformers value on fly with kustomize edit set

### ISSUE THREAD

**Issue by dmytrostriletskyi** [kubernetes-sigs/kustomize#4051]
Hi,

first, thank you for this great and useful project. Second, I have a question I could not find an answer on.

Initially, I wanted to put some annotations to my `Deployment` resource. I used `commonAnnotations` setting in `kustomization.yml`. When I built it, I found it is applied to all resources. After, I found that I can solve it by built-in plugins and using annotations transformers. I tried this and succeed, it changes only the `Deployment`resource.

I have done with the following annotations transformer:

```
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: project-name
annotations:
  project-annotation: annotation
fieldSpecs:
- kind: Deployment
  path: metadata/annotations
  create: true
```

I was led by [this example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configureBuiltinPlugin.md), and it completely worked for me.

The only problem I have here is I want to be able to change the annotation value (`project-annotation: annotation`) to any other as I do with an image tag `kustomize edit set image project=2.4.1`.

I can do it with `sed` CLI, but was wondering if I could do it with `kustomize` CLI?
