### ISSUE TITLE
[Question] How to set property every array element ?

### ISSUE THREAD

**Issue by yogeshgadge** [kubernetes-sigs/kustomize#4053]
On the lines of targeting specific array `entry prop.[name=nginx].host` I tried `entry prop.-.host` so that all the array elements are targeted. However this did not work. 

See my example below
kustomization.yaml
```
resources:
- configmap.yaml
- virtual-services.yaml
replacements:
- source:
     kind: ConfigMap
     fieldPath: data.MY_HOST
  target:
    kind: VirtualService
    fieldPaths:
     -  spec.http.-.rpute.0.destination.host
``` 

Here are the detailed values https://stackoverflow.com/questions/68322864/kustomize-how-to-target-replacement-in-every-array

I am using kustomize 4.2.0 version

**Comment by natasha41575** [comment]
There is no mechanism to do so, but I can add one.

**Comment by natasha41575** [comment]
There is no mechanism to do so, but we can consider adding one.

@monopole @KnVerey any concerns or objects with a mechanism to target all array elements in a replacement fieldPath?

**Comment by natasha41575** [comment]
In its current state you would have to list out all the fieldPaths you need.

**Comment by yogeshgadge** [comment]
Using [] or  [*] for representing all elements seems reasonable to me. 
IMO * makes more sense than empty.


```
spec.http.*.route.0.destination.host
```

**Comment by KnVerey** [comment]
I think the feature makes sense. As for the syntax, fieldPath is essentially using a subset of JSONPath syntax, so we should stick with its way of expressing things as we add features. Specifically, our implementation should be consistent with what k/k packages use, i.e. [this parser from client-go](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/client-go/util/jsonpath/jsonpath.go) if my searching is serving me well. In this case, `list[*]`.

**Comment by natasha41575** [comment]
Being consistent with k/k sounds good to me. In that case, the syntax would be something like `spec.http[*].route.0.destination.host` when implemented.

**Comment by natasha41575** [comment]
Adding a comment to note a caveat in that `fieldPath` slightly differs from JSONPath syntax.

fieldPath separates on "." for everything - so while a JSON path is something like `spec.http[1].route`, the equivalent kustomize replacements path would be `spec.http.[1].route`. In order to be analogous to the current fieldPath syntax, the syntax for setting every array element should actually be `spec.http.[*].route`. 

@m-Bilal, feel free to assign yourself if you would like

**Comment by KnVerey** [comment]
@m-Bilal are you still planning to work on this?

**Comment by m-Bilal** [comment]
Sorry I have not been able to work on this yet, been busy with office work. I do plan on working on this, but I'll be occupied this week as well. If anyone else wants to take this up, please feel free to do so. In case nobody takes this up, I'll leave a comment here when I do start working on this.

**Comment by siegenthalerroger** [comment]
A maintainer should probably remove the lifecycle/rotten and stale from this, seeing as it's still active and relevant

**Comment by natasha41575** [comment]
This is fixed by https://github.com/kubernetes-sigs/kustomize/pull/4424. The only thing left to do is documentation.

@koba1t would you be interested in updating the documentation for this feature? The replacement doc lives here: https://github.com/kubernetes-sigs/cli-experimental/tree/master/site/content/en/references/kustomize/kustomization/replacements

**Comment by koba1t** [comment]
I'm creating PR to add a document. https://github.com/kubernetes-sigs/cli-experimental/pull/240
Do you think it needed to add an example?

**Comment by natasha41575** [comment]
Documentation LGTM. Will merge the docs PR when we do a release. Thank you!

**Comment by tis-rpage** [comment]
I think there's a problem with this code.
`kustomize version`
```
{Version:kustomize/v4.5.3 GitCommit:de6b9784912a5c1df309e6ae9152b962be4eba47 BuildDate:2022-03-24T20:51:20Z GoOs:linux GoArch:amd64}
```

`kustomize build test/`
```
Error: wrong Node Kind for spec.template.spec.containers expected: MappingNode was SequenceNode: value: {- name: controller
  image: public.ecr.aws/aws-controllers-k8s/rds-controller:v0.0.19
  imagePullPolicy: IfNotPresent
  env:
  - name: AWS_REGION
  - name: AWS_ENDPOINT_URL
    value: ""
  command:
  - ./bin/controller
  args:
  - --aws-region
  - $(AWS_REGION)
  - --aws-endpoint-url
  - $(AWS_ENDPOINT_URL)
  ports:
  - containerPort: 8080
    name: http
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    runAsNonRoot: true}
```


File: test/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: test
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: controller
          image: public.ecr.aws/aws-controllers-k8s/rds-controller:v0.0.19
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_REGION
            - name: AWS_ENDPOINT_URL
              value: ""
          command:
            - ./bin/controller
          args:
            - --aws-region
            - $(AWS_REGION)
            - --aws-endpoint-url
            - $(AWS_ENDPOINT_URL)
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 10
```

File: test/kustomization.yaml
```
resources:
  - deployment.yaml

configMapGenerator:
  - name: aws
    options:
      disableNameSuffixHash: true
    literals:
      - AWS_REGION=us-east-1

replacements:
  - source:
      kind: ConfigMap
      name: aws
      fieldPath: data.AWS_REGION
    targets:
      - options: { create: true }
        select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.*.env.[name=AWS_REGION].value
# this works if uncommented
#  - source:
#      kind: ConfigMap
#      name: aws
#      fieldPath: data.AWS_REGION
#    targets:
#      - options: { create: true }
#        select:
#          kind: Deployment
#        fieldPaths:
#          - spec.template.spec.containers.[name=controller].env.[name=AWS_REGION].value
```
