### ISSUE TITLE
ConfigMapGenerator updating unrelated ClusterRole rule resource names

### ISSUE THREAD

**Issue by lstoll** [kubernetes-sigs/kustomize#4054]
**Describe the bug**

When using the ConfigMap generator, an unrelated ClusterRole rule for a lease object is updated with the generated ConfigMap's name. This causes the role to fail, and I would not expect that rule to be updated as it is for an unrelated object.

**Files that can reproduce the issue**

kustomization.yaml

```
resources:
- role.yaml
configMapGenerator:
- name: cluster-autoscaler
  namespace: kube-system
  literals:
  - AWS_REGION="us-east-1"
```

role.yaml

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: null
  name: cluster-autoscaler
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - cluster-autoscaler
  resources:
  - leases
  verbs:
  - get
  - update
...
```

**Expected output**

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: null
  name: cluster-autoscaler
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - cluster-autoscaler
  resources:
  - leases
  verbs:
  - get
  - update
---
apiVersion: v1
data:
  AWS_REGION: us-east-1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-h8mmcct52k
  namespace: kube-system
```

**Actual output**

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: null
  name: cluster-autoscaler
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - cluster-autoscaler-h8mmcct52k
  resources:
  - leases
  verbs:
  - get
  - update
---
apiVersion: v1
data:
  AWS_REGION: us-east-1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-h8mmcct52k
  namespace: kube-system
```

**Kustomize version**

* built from commit 259fcfcef8795a794d76bc811f978fb5dac4d5a2
* 4.2.0
* the version embedded in `kubectl` v1.21.2

**Platform**

* macOS
