### ISSUE TITLE
HelmChartInflationGenerator too strict on yamls

### ISSUE THREAD

**Issue by hans-d** [kubernetes-sigs/kustomize#4058]
**Describe the bug**

When a helmchart is inflated using kustomize, it does additional yaml validation. That  validation is not done when the helmchart is inflated externally from kustomize and the yaml is used as resource, that validation is not performed.

**Files that can reproduce the issue**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmcharts:
- name: kyverno
  repo: https://kyverno.github.io/kyverno
  version: v1.4.1
  releaseName: kyverno
```

```
kustomize build base/kyverno-v1.4.1/ --enable-helm
```

**Expected output**

lots of yaml 

**Actual output**

```Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 33: mapping key "restartPolicy" already defined at line 17
```

**Kustomize version**

4.2.0

**Platform**

Linux
