### ISSUE TITLE
patch removing fields for CronJob batch/v1

### ISSUE THREAD

**Issue by r0bj** [kubernetes-sigs/kustomize#4062]
When using kustomize patch with CronJob in version batch/v1 some fields are removed from generated manifest.

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
patches:
- patch: |
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: test
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - name: test
                env:
                - name: ENV_NEW
                  value: val_new
  target:
    kind: CronJob
    name: test
```

resources.yaml

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "5 10 * * 1"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            image: bash
            command:
            - /bin/sh
            - -c
            - echo "test"
            env:
            - name: ENV1
              value: val1
            - name: ENV2
              value: val2
            - name: ENV3
              value: val3
```

**Expected output**

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - echo "test"
            env:
            - name: ENV_NEW
              value: val_new
            - name: ENV1
              value: val1
            - name: ENV2
              value: val2
            - name: ENV3
              value: val3
            image: bash
            name: test
          restartPolicy: Never
  schedule: 5 10 * * 1
```

**Actual output**

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - env:
            - name: ENV_NEW
              value: val_new
            name: test
          restartPolicy: Never
  schedule: 5 10 * * 1
```

Note: There are missing env variables, command and also image.
When `CronJob` object are in version `batch/v1beta1` kustomize patch everything works fine.

**Kustomize version**

kustomize/v4.2.0
