### ISSUE TITLE
Kyaml converts multiline scalars to single lines

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#4066]
A round trip in kyaml converts the following:

```
apiVersion: custom
kind: Custom
metadata:
  name: my-resource
spec:
  validation:
    openAPIV3Schema:
      description: CanonicalService is the Schema for the canonicalservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
```

into 

```
apiVersion: custom
kind: Custom
metadata:
  name: my-resource
spec:
  validation:
    openAPIV3Schema:
      description: CanonicalService is the Schema for the canonicalservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
```

This resource is a snippet taken from [here](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/asm/canonical-service/controller.yaml#L31). The line breaks in the description fields are lost. 

If this is an issue with go-yaml, we should make the fix in our fork and also file an issue/PR to go-yaml upstream.
