### ISSUE TITLE
Replacements: uncaught exception when `source.fieldPath` does not exist

### ISSUE THREAD

**Issue by marshall007** [kubernetes-sigs/kustomize#4078]
**Describe the bug**

Uncaught `nil pointer dereference` exceptions are being raised in certain replacement scenarios. It seems to be primarily related to the source `fieldPath` not being present in the `source` resource.

One important note in reproducing this bug is that it only surfaces when using `options.create: true`. Note the very slight differences in the following two examples. The second example results in a "no-op" in terms of replacing `data.grpcPort` in `ports-to`.

**Files that can reproduce the issue**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: ports-from
  literals:
  - httpPort=80
- name: ports-to

replacements:
# working case
- source:
    kind: ConfigMap
    name: ports-from
    fieldPath: data.httpPort
  targets:
  - select:
      kind: ConfigMap
      name: ports-to
    fieldPaths:
    - data.httpPort
    options:
      create: true

# failing case
- source:
    kind: ConfigMap
    name: ports-from
    fieldPath: data.grpcPort
  targets:
  - select:
      kind: ConfigMap
      name: ports-to
    fieldPaths:
    - data.grpcPort
    options:
      create: true
```

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: ports-from
  literals:
  - httpPort=80
- name: ports-to
  literals:
  - httpPort=
  - grpcPort=

replacements:
# working case
- source:
    kind: ConfigMap
    name: ports-from
    fieldPath: data.httpPort
  targets:
  - select:
      kind: ConfigMap
      name: ports-to
    fieldPaths:
    - data.httpPort

# "no-op" case
- source:
    kind: ConfigMap
    name: ports-from
    fieldPath: data.grpcPort
  targets:
  - select:
      kind: ConfigMap
      name: ports-to
    fieldPaths:
    - data.grpcPort
```

**Expected output**

Subject to debate, but we should probably either see a `Error: nothing selected by ...` raised or a no-op in both cases.

**Actual output**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x97bcec]

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/filters/replacement.applyToNode(0xc0001901c0, 0x0, 0xc000a387c0, 0xc00012d080, 0xc002c3a400)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/filters/replacement/replacement.go:80 +0x10c
sigs.k8s.io/kustomize/api/filters/replacement.applyReplacement(0xc00244bb60, 0x2, 0x2, 0x0, 0xc000a206a0, 0x1, 0x4, 0xc00244bb60, 0x2, 0x2, ...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/filters/replacement/replacement.go:53 +0x239
sigs.k8s.io/kustomize/api/filters/replacement.Filter.Filter(0xc000a38840, 0x2, 0x2, 0xc00244bb60, 0x2, 0x2, 0xd10cf408, 0x24d8fc080d55ac00, 0xadc420, 0x24d8fc080d55ac00, ...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/filters/replacement/replacement.go:30 +0x17a
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).ApplyFilter(0xc0000c3c98, 0xbb8440, 0xc0000c37b8, 0xc0000c37b8, 0xc00244bb40)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/resmap/reswrangler.go:635 +0x213
sigs.k8s.io/kustomize/api/builtins.(*ReplacementTransformerPlugin).Transform(0xc0030785a0, 0xbcdbb0, 0xc0000c3c98, 0x0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/builtins/ReplacementTransformer.go:52 +0x6f
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).Transform(0xc00012d4e8, 0xbcdbb0, 0xc0000c3c98, 0xc000497b80, 0x5)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/internal/target/multitransformer.go:30 +0x79
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/internal/accumulator/resaccumulator.go:142
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runTransformers(0xc000333040, 0xc0003966a0, 0x0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:270 +0x225
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc000333040, 0xc0003966a0, 0xc00029f610, 0x7efd13, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:195 +0x2b0
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc000333040, 0x0, 0xffffffffffffffff, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:156 +0xce
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc000333040, 0x0, 0x0, 0x0, 0x1)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:111 +0x2f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:107
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc00012dd60, 0xbcb760, 0xf66538, 0x7fffed80c01a, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.8.11/krusty/kustomizer.go:88 +0x3dd
sigs.k8s.io/kustomize/kustomize/v4/commands/build.NewCmdBuild.func1(0xc00035e580, 0xc00037c220, 0x1, 0x1, 0x0, 0x0)
        /workspace/myClone/kustomize/commands/build/build.go:80 +0x1c9
github.com/spf13/cobra.(*Command).execute(0xc00035e580, 0xc00037c1f0, 0x1, 0x1, 0xc00035e580, 0xc00037c1f0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00035e000, 0x0, 0xa12400, 0xc000100058)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /workspace/myClone/kustomize/main.go:14 +0x2a
```

**Kustomize version** `v4.2.0`

**Platform** Linux

**Additional context**

Related to discussion in https://github.com/kubernetes-sigs/kustomize/issues/4075#issuecomment-884295831

/cc @natasha41575
