### ISSUE TITLE
Add binaryData support to configMapGenerator

### ISSUE THREAD

**Issue by vultron81** [kubernetes-sigs/kustomize#408]
Something like the following would be super useful to add binary files to a config map and kubectl now supports binaryData field as of v1.10.0:

```yaml
configMapGenerator:
- name: configmap-kafka-certs
  binaryFiles:
    - ../../../../config/dev/keystore/kafka.keystore.jks
    - ../../../../config/dev/keystore/kafka.truststore.jks
```
