### ISSUE TITLE
Cannot unmarshal number into Go struct field Image.images.newTag of type string

### ISSUE THREAD

**Issue by clarkmcc** [kubernetes-sigs/kustomize#4081]
**Describe the bug**

When the Kustomize `newTag` property looks like a number with scientific notation or has no letters at all, Kustomize is unable to unmarshal it.

**Files that can reproduce the issue**

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: alpine:latest
    newTag: 553640e6
```

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    spec:
      containers:
        - name: alpine
          image: alpine:latest
```

**Additional context**
