### ISSUE TITLE
Support multiple targets for one patch

### ISSUE THREAD

**Issue by twz123** [kubernetes-sigs/kustomize#409]
To apply the same patch to multiple resources, one has to declare it twice:

```yaml
patchesJson6902:
- path: patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: frontend
- path: patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: backend
```

Wouldn't it make sense to support multiple targets for one patch? Like so:

```yaml
patchesJson6902:
- path: patch.yaml
  targets:
  - group: apps
    version: v1
    kind: Deployment
    name: frontend
  - group: apps
    version: v1
    kind: Deployment
    name: backend
```
