### ISSUE TITLE
Patches in components can't be applied in version greater then 3.8.9

### ISSUE THREAD

**Issue by wd** [kubernetes-sigs/kustomize#4092]
**Describe the bug**

The yamls can build by 3.8.9 but can't build by version bigger than 3.8.9

```
wd @ base ~/t/kustomize/base ❯❯❯ kustomize_v3.8.9 build .
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: staging
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
wd @ base ~/t/kustomize/base ❯❯❯ kustomize_v3.8.10 build .
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/Users/wd/t/kustomize/base/components/default-namespace': multiple matches for Id ~G_v1_LimitRange|default|default-limits; failed to find unique target for patch ~G_v1_LimitRange|default-limits"

wd @ base ~/t/kustomize/base ❯❯❯ kustomize_v4.2.0 build .
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/Users/wd/t/kustomize/base/components/default-namespace': multiple matches for Id ~G_v1_LimitRange|default|default-limits; failed to find unique target for patch ~G_v1_LimitRange|default-limits"
```

**Files that can reproduce the issue**

```
wd @ base ~/t/kustomize/base ❯❯❯ tree
.
├── components
│   └── default-namespace
│       ├── kustomization.yaml
│       └── limitrange.yaml
├── kustomization.yaml
└── namespaces
    ├── default
    │   └── kustomization.yaml
    ├── ns
    │   ├── kustomization.yaml
    │   └── limitrange.yaml
    └── staging
        └── kustomization.yaml

6 directories, 7 files
```

All the contents of the files
```
find . -name '*.yaml' |xargs -I {} sh -c 'echo "\n\n----> {}" && cat {}'


----> ./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - namespaces/default
  - namespaces/staging

components:
  - components/default-namespace


----> ./namespaces/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../ns


----> ./namespaces/ns/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- limitrange.yaml


----> ./namespaces/ns/limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container


----> ./namespaces/default/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../ns


----> ./components/default-namespace/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: limitrange.yaml


----> ./components/default-namespace/limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
```

**Expected output**

```
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: default
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: staging
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
```
**Actual output**

```
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/Users/wd/t/kustomize/base/components/default-namespace': multiple matches for Id ~G_v1_LimitRange|default|default-limits
; failed to find unique target for patch ~G_v1_LimitRange|default-limits"
```

**Kustomize version**

kustomize_v3.8.10 and above

**Platform**

Mac
