### ISSUE TITLE
Patches cannot target a Label that is applied by the commonLabels transformer

### ISSUE THREAD

**Issue by siegenthalerroger** [kubernetes-sigs/kustomize#4098]
I have the situation that I have patches that are defined globally (i.e. on the first Kustomisation) and I have commonLabels that are defined per service. From what I can tell, the commonLabels are applied, however they are not available for targeting from the defined patches. Is this the intended behaviour, because if so it's extremely unintuitive. Is there a way to use labels defined by commonLabels in the targeting of patches?

**Structure:**
```
/kustomization.yaml
/deployment-spring-config.yaml
/service
    /kustomization.yaml
    /deployment.yaml
    /... (ingress, service, etc)
```

**Files:**
kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service

patches:
  - path: deployment-spring-config.yaml
    target:
      kind: Deployment
      labelSelector: "apptype=spring"
```

deployment-spring-config.yaml
```yaml
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - mountPath: /application-cloud.yml
      name: config-volume
      subPath: application-cloud.yml
```

service/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service
commonLabels:
  apptype: spring

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
```
