### ISSUE TITLE
replacements cannot target field names containing dots/requiring quoting

### ISSUE THREAD

**Issue by iamnoah** [kubernetes-sigs/kustomize#4103]
**Describe the bug**

There doesn't seem to be a way to target labels or other fields containing dots for replacement. At the very least, the syntax is not equivalent to other fieldPaths using the Downward API syntax.

**Files that can reproduce the issue**

kustomization.yaml

```yaml
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - foo.yml
  - name.yml

replacements:
  - source:
      kind: Name
      fieldPath: metadata.name
    targets:
      - select:
          name: foo
        fieldPaths:
          - metadata.name
          - metadata.labels.app
          - metadata.labels["app.kubernetes.io/name"]
          - spec.selector.matchLabels["app.kubernetes.io/name"]
          - spec.template.metadata.labels["app.kubernetes.io/name"]
```

name.yml (just a contrived CRD for example purposes)

```yaml
apiVersion: v1
kind: Name
metadata:
  name: bar
```

foo.yml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app.kubernetes.io/name: foo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: foo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foo
    spec:
      containers:
        - name:  foo
          image: foo

```

**Expected output**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bar
  name: bar
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bar
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bar
    spec:
      containers:
      - image: foo
        name: foo
---
apiVersion: v1
kind: Name
metadata:
  name: bar
```

**Actual output**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: foo
  name: bar
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: foo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foo
    spec:
      containers:
      - image: foo
        name: foo
---
apiVersion: v1
kind: Name
metadata:
  name: bar
```

**Kustomize version**

4.2.0

**Platform**

macOS

**Additional context**

You can see the normal fields are replaced, but the ["quoted"] labels are not. Labels without dots can also be replaced.

Similar to #1220

**Comment by natasha41575** [comment]
You're missing some '.''s in your syntax. 

The escape mechanism isn't documented yet, I will add that this week, but there are two ways you can escape the '.'. The following kustomization will work for your use case:

```
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - foo.yaml
  - name.yaml

replacements:
  - source:
      kind: Name
      fieldPath: metadata.name
    targets:
      - select:
          name: foo
        fieldPaths:
          - metadata.name
          - metadata.labels.app
          - metadata.labels.app\.kubernetes\.io/name
          - spec.selector.matchLabels.[app.kubernetes.io/name]
          - spec.template.metadata.labels.[app.kubernetes.io/name]
```

Note that you can either escape the delimiters with `\` or by surrounding the field name with `[]`.
