### ISSUE TITLE
[Question] Change ONLY the Image Name/Registry in Kustomize Overlay without knowing o.g. image tag?

### ISSUE THREAD

**Issue by julianwilkinson** [kubernetes-sigs/kustomize#4109]
Hi,

For a Kubernetes deployment, given a Kustomize Base like:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
...
images:
  - name: developmentregistry.com/myimage:v1.0
```

Is there a way to change only the image registry and retain the o.g. tag in the new deployment with Overlay *without re-declaring the image tag*?

For example if I use an Overlay like:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
...
images:
  - newName: productionregistry.com/myimage
```
The image is deployed as just productionregistry.com/myimage (with the `:latest` tag)— which is not what I want.

How can I make it so my Overlay deployment yield `productionregistry.com/myimage:v1.0`? 

I took a look at #402 but it doesn't solve this as far as I can tell.

**Comment by julianwilkinson** [comment]
Okay nevermind I figured it out. My yaml wasn't structure correctly (it didn't throw an error though...)

This works:

**Base**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
...
images:
  - name: developmentregistry.com/myimage
    newTag: v1.0
```
**Overlay**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
...
images:
  - name: developmentregistry.com/myimage
    newName: productionregistry.com/myimage
```
