### ISSUE TITLE
Exec plugins with argsFromFile can look for the file in wrong locations

### ISSUE THREAD

**Issue by Gikkman** [kubernetes-sigs/kustomize#4115]
When writing a exec custom plugin, the `argsFromFile` seems to try to load the file relative to the root  folder of the kustomize project, and not relative to the file describing the plugin. I recon this might be intentional, but since there is no documentation on `argsFromFile`, at least to me, this feels unintuitive.

You can find an example repo which exhibits the problem [here](https://github.com/Gikkman/kustomize-plugin-argsFromFile)

**Files that can reproduce the issue**

```
.
├── base/
│   ├── kustomization.yaml
│   ├── ingress.yaml
├── transformers/
│   ├── kustomization.yaml
│   ├── SedTransformer.yaml
│   └── sed-input.txt
└── plugins/teamname/v1/sedtransformer
    └── SedTransformer
```
```
-> base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yml

transformers:
  - ../transformers
```
```
-> base/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: HELLO-SERVER-CLUSTER
      http:
        paths:
          - backend:
              serviceName: some-svc
              servicePort: 8081
```
```
-> transformers/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - SedTransformer.yaml
```
```
-> transformers/SedTransformer.yaml
apiVersion: teamname/v1
kind: SedTransformer
metadata:
  name: not-really-used
argsOneLiner: s/HELLO/WORLD/g
argsFromFile: sed-input.txt
```
```
-> transformers/sed-input.txt
s/SERVER/MyAwsomeServer/g
s/CLUSTER/SomeoneElsesCluster/g
```
```
-> plugins/teamname/v1/sedtransformer/SedTransformer
#!/bin/bash


# Skip the config file name argument.
shift

args=""
for arg in "$@"; do
  args="$args -e $arg"
done

cat - | eval sed $args
```
**Expected output**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: WORLD-MyAwesomeServer-SomeoneElsesCluster
    http:
      paths:
      - backend:
          serviceName: some-svc
          servicePort: 8081
```

**Actual output**

```
$ kustomize build --enable-alpha-plugins kustomize/base
> Error: plugin myteam_v1_SedTransformer|~X|not-really-used fails configuration: evalsymlink failure on '/Users/gikkman/Development/kustomize-plugin/kustomize/base/sed-input.txt' : lstat /Users/gikkman/Development/kustomize-plugin/kustomize/base/sed-input.txt: no such file or directory
```

**Kustomize version**

{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-07-01T01:00:35+01:00 GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional notes**
If you move the `sed-input.txt` to the base folder, the sed transformations are applied as expected.

**Comment by natasha41575** [comment]
Similar issue with exec functions: https://github.com/kubernetes-sigs/kustomize/issues/4117

**Comment by KnVerey** [comment]
#4125 only fixed the "function" version of exec plugins, whereas the examples on this issue are using the older env-lookup-based exec plugins. While we would accept a fix to the older exec plugins so that they also use the Kustomization's dir as their working dir, I would recommend switching to the newer "function" style, as the older style is proposed for deprecation as part of the plan to move plugins as a whole out of alpha: kubernetes/enhancements#2954. 

E.g. it would look like this:

```yaml
apiVersion: teamname/v1
kind: SedTransformer
metadata:
  name: not-really-used
  annotations:
      config.kubernetes.io/function: |-
        exec:
          path: ../plugins/teamname/v1/sedtransformer/SedTransformer # can be anywhere within the Kustomize root
          args:  s/HELLO/WORLD/g
argsFromFile: sed-input.txt
```

The function version of exec doesn't have argsFromFile support, so those can either be inlined in the functionConfig as well, or you can pass the filename for your executable to read. If that is problematic for your use case, I'd be interested to hear more details to inform our deprecation plan.

/triage under-consideration
/unassign
