### ISSUE TITLE
Exec functions look for files in the wrong location

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#4117]
I have the following directory structure: 

```
├── base
│   ├── kustomization.yaml
│   └── local-files
├── kustomization.yaml
└── overlay
    └── kustomization.yaml
```

In my `base/kustomization.yaml`, I have something like:

```
generators:
- |-
  apiVersion: v1
  kind: FunctionKind
  metadata:
    name: demo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: /path/to/function/binary
  functionFiles:
  - local-files
```

My function needs to read local files. However, when running `kustomize build`, I find that when looking up local files, the working directory for the function is wherever `kustomize build` is run. 

I believe the working directory for the function _should_ instead be the directory of the function configuration - `base` in my case. 

As a workaround, I can do: 

```
generators:
- |-
  apiVersion: v1
  kind: FunctionKind
  metadata:
    name: demo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: /path/to/function/binary
  functionFiles:
  - base/local-files
```

but this makes my base configuration nonreusable as my base now needs to know the the relative path to itself from wherever `kustomize build` is run.
