### ISSUE TITLE
How to replace a variable in a template 

### ISSUE THREAD

**Issue by MeijerM1** [kubernetes-sigs/kustomize#4120]
Hi,

Is there a way to replace a variable across a resource without using a patch.yaml or patch.json file?

Say I have the following file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: VARIABLE_WITH_APP_NAME
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VARIABLE_WITH_APP_NAME
  template:
    metadata:
      labels:
        app: VARIABLE_WITH_APP_NAME
    spec:
      containers:
      - name: VARIABLE_WITH_APP_NAME
        image: image:1
```

Is there a way to replace `VARIABLE_WITH_APP_NAME` in the `kustomize` file in a simple way?

**Comment by kferrone** [comment]
Not really what the kustomize folks would intend. You could inline the patches instead of using patch.yaml, something like this

```yaml
patch: |-
  - op: add
    path: /spec/foo
    value: bar
```

The other option for what you are doing is to simply use the commonLabels to add the labels part. Then use the replacements to reference the name on the containers. 

Lastly, for those rare times nothing in Kustomize can do what I want, then I make a plugin using bash and some sed magic.

**Comment by arash-bizcover** [comment]
Lacking this feature is crazy. Customize folks don't like variables inside the Yaml. They say Yaml in Yaml out only. 
https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/

But weirdly enough they have agreed to have tons of complicated transformers. and something as crazy as this:
https://kubectl.docs.kubernetes.io/guides/extending_kustomize/execpluginguidedexample/

**Comment by kferrone** [comment]
The variables idea tends to be too abstract and hard to re-patch, ie once a variable is set it usually can't be set again by something else without completely replacing the value. The plugins are very powerful and easy to use, at least in my opinion. They can be written in any language too. 

If you are interested, here is my little plugin based on this example in kustomize: https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/sedtransformer/SedTransformer

`VarTransformer`
```bash
#!/usr/bin/env bash
​
set -e
​
res="$(cat $1)"
sedMap=()
​
length=$(echo "$res" | yq e '.vars | length' -)
​
for (( i=0; i<$length; i++ ))
do
   var="$(echo "$res" | yq e '.vars['$i']' -)"
   varName=$(echo "$var" | yq e '.name' -)
   if [ "$(echo "$var" | yq e '. | has("env")' -)" == 'true' ]
   then
      envVar=$(echo "$var" | yq e '.env' -)
      var="$(echo "$var" | yq e '.value = env('$envVar')' -)"
   fi
   varValue="$(echo "$var" | yq e '.value' -)"
   sedMap+=(-e "s#\$(${varName})#${varValue}#g")
done
​
# echo "${sedMap[@]}"
sed "${sedMap[@]}"
```

`example-vars.yaml`
```yaml
apiVersion: someteam.example.com/v1
kind: VarTransformer
metadata:
  name: test-variables
vars:
- name: message
  value: hello world
- name: how_many
  value: 20
- name: some.url
  value: example.com
- name: whoami
  env: USER
  
- name: user.home
  env: HOME
​
# multi line value with spaces in name
- name: fancy message
  value: no multi line allowed in VarTransformer
```

`service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: some-place
  labels:
    user: $(whoami)
spec:
  type: ExternalName
  sessionAffinity: None
  externalName: $(some.url)
```

And for a totally different way to think about variables in a patching environment:
 1. make a configmap with all your variables
 2. use the replacement transformer to target configmap and set variables all over your project

I totally agree kustomize should avoid template style variables. They are easy enough to implement in code and Helm is a dedicated templating platform which easily integrates with kustomize. Either you can use a helm operator or kustomizes helm inflator, see here: https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/#_helmchartinflationgenerator_
