### ISSUE TITLE
Reference Starlark Function

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kustomize#4126]
I am particularly interested in using this example and modifying for myself: https://github.com/kubernetes-sigs/kustomize/tree/master/plugin/someteam.example.com/v1/starlarkmixer

My issue is the mixer.star file must be relative of where my terminal is. So if I dom something like `cd ../` the function will not reference the mixer.start anymore. I honestly would like to place the function  in `$XDG_CONFIG_HOME/kustomize/functions`. 

This way I always know where they are and they become reusable. 

Here is the files I am using:
`mixer.yaml`
```yaml
apiVersion: mmsg
kind: StarlarkMixer
metadata:
  name: mixer-instance
  annotations:
    # super strict here
    # can't use ../ nor can I use /
    config.kubernetes.io/function: |
      starlark:
        path: mixer.star 
```
`conf.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-cm
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: delete-me
```
`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- conf.yaml
transformers:
- mixer.yaml
```

How can I safely share the mixer file with any function who want to use it? 

Shouldn't the reference to these files be like every other kind of reference and be relative to the file it's in. Then the `$(pwd)` in the terminal would not matter.
