### ISSUE TITLE
configmap generator hash not applied to volume referecing the config map

### ISSUE THREAD

**Issue by bluebrown** [kubernetes-sigs/kustomize#4129]
I am trying to generate a configmap from a json file vie kustomize and use it as volume in a deployment created by the kustomize build operation. But the generated hash is not applied in the volume definition.

```yaml
---
kind: Kustomization
namespace: staging
resources:
  - staging.ns.yaml
  - sap.mock.yaml
configMapGenerator:
  - name: sap-mock-init
    behavior: create
    files:
      - "initializer.json"
```

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
```

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap-mock
spec:
  selector: ...
  template: ...
  volumeMounts:
  - name: sap-mock-init
    mountPath: /config/
volumes:
  - name: sap-mock-init
    configMap:
      name: sap-mock-init
```

When I run kustomize build, I get the following output.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
data:
  initializer.json: |-
    ...
kind: ConfigMap
metadata:
  name: sap-mock-init-kb76854t2c
  namespace: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap-mock
  namespace: staging
spec:
  selector: ...
  template: ...
  volumeMounts:
  - mountPath: /config/
    name: sap-mock-init
volumes:
- configMap:
    name: sap-mock-init
  name: sap-mock-init
```

I found some issues on github that suggest it should be ultimately possible. One had an issue with the namespace. The other one seems to be about name prefix/suffix which I am not using. The third link is a SO question where OP created the deployment with kubectl while the configmap with kustomize.

I am not using overlays / patches. So this is kind of the base, not sure if it could have to do with that.

- https://github.com/kubernetes-sigs/kustomize/issues/986
- https://github.com/kubernetes-sigs/kustomize/issues/1301
- https://stackoverflow.com/questions/56210674/kubernetes-deployment-is-missing-kustomizes-hash-suffixes
