### ISSUE TITLE
Name reference to ServiceAccount broken with namespace since 1.0.8

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#413]
When setting `namespace` in the Kustomization, name references to ServiceAccounts in ClusterRoleBindings are not resolved.

kustomization.yaml:
```yaml
resources:
- serviceaccount.yaml
- clusterrolebinding.yaml
namePrefix: a-
namespace: ingress
```

clusterrolebinding.yaml:
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole
subjects:
- kind: ServiceAccount
  name: serviceaccount
  namespace: ingress
```

serviceaccount.yaml:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount
  namespace: ingress
```

kustomize build in 1.0.8:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: a-serviceaccount
  namespace: ingress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: a-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole
subjects:
- kind: ServiceAccount
  name: serviceaccount
  namespace: ingress
```

kustomize build in 1.0.7:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: a-serviceaccount
  namespace: ingress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: a-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole
subjects:
- kind: ServiceAccount
  name: a-serviceaccount
  namespace: ingress
```
