### ISSUE TITLE
name references not getting updated for JSON patches after kind change

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-sigs/kustomize#4136]
**Describe the bug**

After doing a `kind` change, name references no longer get updates.
In the example below, notice that the configMap name inside of the volume isn't updated.

**Files that can reproduce the issue**

kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- statefulset.yaml
patches:
- target:
    group: apps
    version: v1
    name: foo
  options:
    allowKindChange: true
  patch: |
    - op: replace
      path: /kind
      value: Deployment
configMapGenerator:
- name: cm
  literals:
  - bar=bar
```
statefulset.yaml:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      foo: foo
  template:
    metadata:
      labels:
        foo: foo
    spec:
      containers:
      - name: foo
        image: example
        volumeMounts:
        - mountPath: /path
          name: myvol
      volumes:
      - configMap:
          name: cm
        name: myvol
```

**Expected output**

```yaml
apiVersion: v1
data:
  bar: bar
kind: ConfigMap
metadata:
  name: cm-8hm8224gfd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      foo: foo
  template:
    metadata:
      labels:
        foo: foo
    spec:
      containers:
      - image: example
        name: foo
        volumeMounts:
        - mountPath: /path
          name: myvol
      volumes:
      - configMap:
          name: cm-8hm8224gfd
        name: myvol
```

**Actual output**

```yaml
apiVersion: v1
data:
  bar: bar
kind: ConfigMap
metadata:
  name: cm-8hm8224gfd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      foo: foo
  template:
    metadata:
      labels:
        foo: foo
    spec:
      containers:
      - image: example
        name: foo
        volumeMounts:
        - mountPath: /path
          name: myvol
      volumes:
      - configMap:
          name: cm
        name: myvol
```

**Kustomize version**

`Version:4.2.0 GitCommit:$Format:%H$ BuildDate:2021-07-22T22:12:15Z GoOs:linux GoArch:amd64`

**Additional context**

https://github.com/BitGo/kustomize-loki/issues/27
