### ISSUE TITLE
kustomize failes to merge yaml anchor

### ISSUE THREAD

**Issue by nbraun-wolf** [kubernetes-sigs/kustomize#4144]
Hi, am trying to merge a yaml anchor but kustomize is throwing errors. It works with kubectl apply.

**Files that can reproduce the issue**

deploy.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchor-test
spec:
  selector:
    matchLabels:
      app: anchor-test
  template:
    metadata:
      labels:
        app: anchor-test
    spec:
containers:
- &foo
  name: foo
  image: traefik/whoami
  ports: [ containerPort: 80 ]
  command: [sleep, infinity]
- <<: *foo
  name: bar
```

kustomization.yaml

```yaml
resources:
  - "deploy.yaml"
```

**Expected output**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchor-test
spec:
  selector:
    matchLabels:
      app: anchor-test
  template:
    metadata:
      labels:
        app: anchor-test
    spec:
      containers:
        - command:
            - sleep
            - infinity
          image: traefik/whoami
          name: foo
          ports:
            - containerPort: 80
        - command:
            - sleep
            - infinity
          image: traefik/whoami
          name: bar
          ports:
            - containerPort: 80
```

**Actual output**

```yaml
Error: map[string]interface {}{"apiVersion":"apps/v1", "containers":[]interface {}{map[string]interface {}{"command":[]interface {}{"sleep", "infinity"}, "image":"traefik/whoami", "name":"foo", "ports":[]interface {}{map[string]interface {}{"containerPort":80}}}, map[interface {}]interface {}{"command":[]interface {}{"sleep", "infinity"}, "image":"traefik/whoami", "name":"bar", "ports":[]interface {}{map[string]interface {}{"containerPort":80}}}}, "kind":"Deployment", "metadata":map[string]interface {}{"name":"anchor-test"}, "spec":map[string]interface {}{"selector":map[string]interface {}{"matchLabels":map[string]interface {}{"app":"anchor-test"}}, "template":map[string]interface {}{"metadata":map[string]interface {}{"labels":map[string]interface {}{"app":"anchor-test"}}, "spec":interface {}(nil)}}}: 
json: unsupported type: map[interface {}]interface {}
```

**Kustomize version**

```
$ kustomize version
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
```

**Platform**

WSL2 Ubuntu20.4
