### ISSUE TITLE
[Question] kustomize edit set image doesn't work with kustomize multibases build

### ISSUE THREAD

**Issue by deepak-gc** [kubernetes-sigs/kustomize#4145]
I am using this [example][1]  

```.
├── base
│   ├── kustomization.yaml
│   └── pod.yaml
├── dev
│   └── kustomization.yaml
├── kustomization.yaml
├── production
│   └── kustomization.yaml
└── staging
    └── kustomization.yaml
```
and in `kustomization.yaml` file in root:

```
resources:
- ./dev
- ./staging
- ./production
```

I also have the image transformer code in `dev, staging, production` kustomization.yaml
```
images:
- name: my-app
  newName: gcr.io/my-platform/my-app

```
To build a single deployment manifest, I use:

```
(cd dev && kustomize edit set image my-app=gcr.io/my-platform/my-app:0.0.2 && kustomize build .)
```
which simply works!

to build deployment manifest for all overlays(dev, staging, production), I use:

```
(kustomize edit set image my-app=gcr.io/my-platform/my-app:0.0.2 && kustomize build .)
```
which uses the `kustomization.yaml` in root which contains all resources(dev, staging, production)

It does work and the final build is printed on console but without the image tag.

It seems like the `kusotmize edit set image` only updates the kustomizaion.yaml of the current dir

Is there anything which can be done to handle this scenario in an easy and efficient way so the final output contains image tag as well for all deployments? 

[Please check this repo for the code](https://github.com/D-GC/kustomize-multibase)

  [1]: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/multibases/README.md

**Comment by natasha41575** [comment]
> The reason why kustomize edit set image doesn't work is because it only updates the tag in current directory. 

This is correct behavior; I don't think it makes sense for `kustomize edit set image` to be invoked recursively by default. `kustomize edit set` is intended to target the root kustomization only. I might be open to setting a recursive option, but having it traverse the kustomization tree by default doesn't make much sense IMO. 

There are a few things going on with your directory structure:

1. To be clear, the `name` field in your `kustomization` file, under `images.name` is targeting containers with a matching image name under `spec.template.spec.containers.image`. 

2. In overlays/production/kustomization.yaml you have the following:

```
images:
- name: my-app
  newName: gcr.io/my-platform/my-app
```

which changes the image in your deployment (originating in bases/deployment.yaml) from

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    spec:
      containers:
      - name: my-app
        image: my-app
``` 

to 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    spec:
      containers:
      - image: gcr.io/my-platform/my-app
        name: my-app
```

A similar thing happens in your staging kustomization file. 

Then, in your overlays/kustomization.yaml, you have the following:

```
images:
- name: my-app
  newName: gcr.io/my-platform/my-app
  newTag: 0.0.1
```

This is effectively a no-op, because at this point, you don't have any containers with the image my-app. Because overlays/production and overlays/staging have changed the deployments' container fields, you only have containers with the image `gcr.io/my-platform/my-app`, so this `images.name` field `my-app` doesn't match anything.

If you want your configuration to apply the tag correctly, you should either:

(a) Remove the `images` fields in your overlays/production/kustomization.yaml and overlays/staging/kustomization.yaml files so that they don't alter the images before reaching the overlay.

OR

(b) In your overlays/kustomization.yaml file, your images field should look like: 

```
images:
- name: gcr.io/my-platform/my-app
  newTag: 0.0.1
```

Then, this overlay can correctly match your changed deployment container image fields and update the tag accordingly.

Reading the documentation here https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/images/ may help.
