### ISSUE TITLE
kustomize is converting quoted("123") string to non-quoted one due to which resource apply is failing

### ISSUE THREAD

**Issue by bkum** [kubernetes-sigs/kustomize#4146]
We have our product namespace as number so when we are declaring same in kustomization.yaml, we are adding under quotes. Now when we are calling the `kustomize build`  it is generating the resource yaml having namespace without quote due to which kubectl apply is failing with error 

unable to decode "STDIN": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 9, error found in #10 byte of ...|mespace":987654321}}|

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "987654321"

secretGenerator:
- name: db-secret-v160
  literals:
  - database=987654321
  type: Opaque

```

**Expected output**

```
apiVersion: v1
data:
  database: OTg3NjU0MzIx
kind: Secret
metadata:
  name: db-secret-v160-6c5k6hh258
  namespace: "987654321"
type: Opaque
```

**Actual output**
```
apiVersion: v1
data:
  database: OTg3NjU0MzIx
kind: Secret
metadata:
  name: db-secret-v160-6c5k6hh258
  namespace: 987654321
type: Opaque
```

**Kustomize version**

{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-07-01T20:59:51+00:00 GoOs:linux GoArch:amd64}

**Platform**

Windows WSL-2

**Additional context**

None
