### ISSUE TITLE
Document `labels` field

### ISSUE THREAD

**Issue by terion-name** [kubernetes-sigs/kustomize#4147]
UPD
After days of struggling I've found this merge: https://github.com/kubernetes-sigs/kustomize/pull/3743
So it is posible with labels field, but this is not documented anywhere :(

Leaving the issue for others to find this

===========================
Orignal text:

Hello.

This is a discussion topic that I want to rise.

Despite being a feature,`commonLabels`s  behaviour was reported as a bug numerous times for years already. This kinda should've tell that such behaviour is counter-intutivie and is not what community wait and want from it.

As pointed [here](https://github.com/kubernetes-sigs/kustomize/issues/2034#issuecomment-675131860) one should use LabelTransforners to set labels only for labels, but this is very bad approach, because requires a huge amount of configs written for every case (ruining the purpose of Kustomize to make small and convenient overlays) and those configs aren't reusable at all, because being used as a resource they can't inherit properties from kustomization.yaml

Very simple example:

```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: "app-name"
  app.kubernetes.io/version: "1.0.1"
resources:
  - ../../../cluster/regcred/
  - ./base
images:
  - name: app-image
    newTag: 1.0.1
    newName: registry.example.com/app-name/master
```

The main app config is in ./base, this overlay alters image to new build and labels all resources to new version.

And this is impossible and will not work, because  In API version apps/v1, a Deployment’s label selector is immutable after it gets created and commonLabels changes selector. And to overcome this one should create each time a new set of cumbersome huge configs in separate files just to make the thing `commonLabels` are supposed to do.

commonLabels — even semantically is common LABELS, not selectors. Labels and selectors are not the same and not always match each other entirely. This behaviour makes commonLabels literally immutable and forces to dance around it.

It would be much better if there were separate props like `commonLabels` and `commonSelectors` or `commonMatchers` that each do what the name says they should.
