### ISSUE TITLE
How can you use {{ .Values.global}}?

### ISSUE THREAD

**Issue by SuitableProduce** [kubernetes-sigs/kustomize#4150]
Trying to use Kustomize, but when if the helm chart is using global values that are specified in the values.yaml?

**Comment by kferrone** [comment]
That is up to helm, not kustomize. 

Helm Globals are just values under the `global` key in the values.

So I'm just going to assume you are using the Helm Chart Inflator built into kustomize, i.e. https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md

You would add all your global vars under the global key under valuesInline:
```yaml
valuesInline:
  global:
    foo: I am a global var for a helm chart
```

**Comment by SuitableProduce** [comment]
Thanks!  Though looks like the Inflation Generator does not currently work with local charts: https://github.com/kubernetes-sigs/kustomize/issues/3658

**Comment by kupi93** [comment]
Hi~ 

I'm also struggling for the same reason.
If I insert a braced variable for a slack message in prometheus alert rule as follows, 
```
...
    - alert: GPUHealthAnomalies
      annotations:
        message: GPU state of `{{ $labels.instance }}: gpu {{ $labels.gpu }}` is unstable.
        summary: GPU helath alert
      expr: "node_gpu_health !=0 \n"
      for: 5m
      labels:
        severity: critical
...
```
kustomize 4.3.0 throws an error like the below.
```
$> kustomize build ./overlays/target/             

Error: accumulating resources: accumulation err='accumulating resources from '../../base_extra': '/Users/user/workspace/iu-k8s/projects/prometheus-operator/base_extra' must resolve to a file': recursed accumulation of path '/Users/user/workspace/iu-k8s/projects/prometheus-operator/base_extra': accumulating resources: accumulation err='accumulating resources from 'prometheus-rules-iu-k8s-gpu.yaml': yaml: line 15: mapping values are not allowed in this context': got file 'prometheus-rules-iu-k8s-gpu.yaml', but '/Users/user/workspace/iu-k8s/projects/prometheus-operator/base_extra/prometheus-rules-iu-k8s-gpu.yaml' must be a directory to be a root
```
