### ISSUE TITLE
How can Transformer Reference a local file

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kustomize#4155]
I am making a transformer plugin and it needs to use a local file which is not a kubernetes object. Basically k8s objects are made based on this file but it does not need to be in the final output once the transformer is done with it. 

Here is the project layout:
```
base:
- kustomization.yaml
- mytransformer.yaml
- thefile.txt
```

Let's say the the mytransformer.yaml looks like this:
```yaml
apiVersion: foo
kind: MyTransformer
metadata:
  name: my-transformer
theFile: thefile.txt
```

The transformer is really basic and just wraps a pre-built command with some bash. Running the plugin manually gives me the exact result I seek.

Manual run:
```bash
./path/to/MyTransformer ./path/to/mytransformer.yaml
```

This way in bash, all I thought I had to do is get the dirname of the first parameter which is the path to the input file. 
Like this: `wkdir=$(dirname $1)`

Unfortunately, I realized kustomize seems to only copy over files explicitly mentioned in the kustomization.yaml. This means I am unable to reference the `thefile.txt` from the bash transformers code. Is there maybe something I am missing? Would be nice if the plugins had their own `resources` key built in for this situation. 

I do think I did see somewhere that functions may do something like this?

**Comment by natasha41575** [comment]
Is this an exec plugin? What version of kustomize are you using?

**Comment by kferrone** [comment]
It's a simple exec plugin with bash. 
I actually just realized it's just `$(pwd)`. I also confirmed `pwd` is relative to the kustomization.yaml. This is perfect! 

Here is the plugin, I made it for the [kompose cli](https://kompose.io/). This way I get seamless transition from docker-compose to kustomize. I have it in a place like `$XDG_CONFIG_HOME/kustomize/plugin/someteam/v1/kompose/Kompose`
```bash
#!/usr/bin/env bash

set -e

# relative to kustomization.yaml
wkdir="$(pwd)"
# input response yamls
res="$(cat $1)"
# a place to gather args and files for the kompose cli
komposeArgs=()
files=()

# a nice error
function fail_on_error() {
    RED="\033[0;31m"
    echo -e "${RED}ERROR: ${1}${RED}" >&2
    exit 1
}

# check if the arg is in the yamls
function hasArg() {
   echo "$res" | yq e '.spec | has("'$1'")' -
}

# add an arg from yaml to cli args
function addArg() {
   if [ "$(hasArg $1)" == 'true' ]; then
      komposeArgs+=("--$1=$(echo "$res" | yq e '.spec.'$1'' -)")
   fi
}

addArg "controller"
addArg "replicas"
addArg "volumes"
addArg "provider"
addArg "with-kompose-annotation"

# get default compose if none provided
if [ "$(hasArg 'files')" != 'true' ]; then
   res="$(echo "$res" | yq e '.spec.files[0] = "docker-compose.yml"' -)"
fi
# gather compose files
fLength=$(echo "$res" | yq e '.spec.files | length' -)
for (( i=0; i<$fLength; i++ ))
do
   f=$(echo "$res" | yq e '.spec.files['$i']' -)
   file="${wkdir}/${f}"
   if [ ! -f "$file" ]; then
      fail_on_error "The file does not exist: $file \n At least one docker-compose is required"
   fi
   files+=(-f "$file")
done

# run the kompose and output yamls as docs
kompose convert \
   "${komposeArgs[@]}" \
   --stdout "${files[@]}" \
   | yq e '.items[] | splitDoc' -
```
Then the plugin yamls somewhere like `/opt/foo/kompose.yaml`
```yaml
apiVersion: someteam/v1
kind: Kompose
metadata:
  name: kompose-example
spec:
  # optional, will default to docker-compose in the same dir as kustomization
  files:
  - docker-compose.yml

  # optional, this can also be set in compose
  # replicas: 3 
  
  # optional, default is deployment
  controller: deployment #  (deployment | daemonSet | replicationController)

  # optional, default is kubernetes
  provider: kubernetes # or openshift

  # optional, default is true
  with-kompose-annotation: true
```
