### ISSUE TITLE
Add support for base names along with prefix an suffix

### ISSUE THREAD

**Issue by svpace** [kubernetes-sigs/kustomize#4156]
I keep repeating the same value for metadata/name in most of my manifests.

**Describe the solution you'd like**
It would be great to be able to set a base name in my kustomization.yaml and have it used in any unamed resources and only override it where needed.

**Describe alternatives you've considered**
I've have been naming my resources "-" and using prefix and suffix to emulate this. For instance:
kustomization:
```
  namePrefix: my
  nameSuffix: app
```

deployment, service, serviceaccount, etc:
```
  metadata:
    name: "-"
```

extra-service:
```
  metadata:
    name: "-extra-"
```
Everything, except extra-service, ends up named "my-app". It works, but It feels "hackish" and I still have to repeat the metadata block in each manifest.

**Comment by natasha41575** [comment]
Have you considered using a patch to update resource names?

For example:

deployment:
```
metadata:
  name: base
```

`kustomization.yaml`: 
```
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-app
  target:
    name: base
  options:
    allowNameChange: true
```

**Comment by svpace** [comment]
Thank you for your suggestion, but I believe that this defeats the purpose. The idea is to have base name defined only once and to DRY the manifests. With a patch, the manifests still require a "placeholder" metadata/name and the base name still gets repeated for each resource.

**Comment by svpace** [comment]
I realize that this is way more complicated than that. But I was thinking something along the lines of:
```
defaultValueGenerator:
- kind: *
  version: *
  path: metadata/name
  value: my-app
```
this, nicely wrapped in the kustomization.yaml as:
```
baseName: my-app # 
```
and then, somewhere within kustomize:
```
if not requiredField.value:
  generator = findGenerator(requiredField.path)
  if generator:
    requiredField.value = generator.value
  else:
    error
```

WDYT?
