### ISSUE TITLE
Is it possible to rename labels?

### ISSUE THREAD

**Issue by svpace** [kubernetes-sigs/kustomize#4174]
I have a bunch of Helm generated manifests that follow the old app/release/heritage labels convention.

Is there a way to use kustomize to rename these labels to the new "app.kubernetes.io/name" convention while keeping their value?

**Comment by kferrone** [comment]
Yes with some imagination. Here is what I came up with real quick and untested but theoretically should work. 

Step 1: Make a new `LabelTransformer` with desired labels
```yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: new-labels
labels:
  # value doesn't matter here, it will be replaced
  app.kubernetes.io/name: foo
  app.kubernetes.io/instance: foo-xyz
```
Step 2: Use `ReplacementTransformer` to copy old label value to new labels.
```yaml
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: replace-labels
replacements:
# one of these per label
- source: 
    kind: Deployment # doesn't really matter what we start with
    fieldPath: metadata.labels.app
  targets:
  - select:
      kind: .* # hopefully this works
    fieldPaths: 
    # this may be the wrong syntax for targeting a label like this
    - metadata.labels[app.kubernetes.io/name]
```
Step 2: Use `PatchTransformer` to remove labels
```yaml
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: remove-old-labels
target:
  kind: .*
patch: |-
  # one for each label to remove
  - op: remove
    path: metadata.labels.app
```

You could also perform this task with code and hack it up with a kustomize plugin. Probably the less verbose and accurate way to go. Here are some examples: https://github.com/kubernetes-sigs/kustomize/tree/master/plugin/someteam.example.com/v1
