### ISSUE TITLE
[Question] What does the 'Line' field represent in a YamlNode?  The value was different than the line I expected in my usage

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes-sigs/kustomize#4181]
When attempting to use kyaml, it seems that the YamlNode `Line` field has a value that is different than what I might expect.  From the below sample code and output I am a bit confused.  I get the YamlNode for the `metadata` field via `node, err := obj.Pipe(yaml.Get("metadata"))` and the metadata tag is on line `3` of the yaml but the value for `node.YNode().Line` is `4`.  I was wondering why this value might be `4` here and what the correct way to get the line number for the `metadata` field might be?  Thanks.
```
// main.go
package main

import (
	"fmt"
	"log"

	"sigs.k8s.io/kustomize/kyaml/yaml"
)

func main() {
	obj, err := yaml.Parse(`apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  annotations:
    a.b.c: d.e.f
    g: h
spec:
  template: {}
`)
	if err != nil {
		log.Fatal(err)
	}
	node, err := obj.Pipe(yaml.Get("metadata"))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("node.YNode().Line: %d\n", node.YNode().Line)
	fmt.Printf("node.YNode().Column: %d\n", node.YNode().Column)
	for _, n := range node.Content() {
		fmt.Printf("n.Line: %v\n", n.Line)
	}

	fmt.Println("============")
	fmt.Println(obj.String())
}
```

output:
```
aprindle@aprindle ~/kyaml-test $ go run .
node.YNode().Line: 4
node.YNode().Column: 3
n.Line: 4
n.Line: 4
n.Line: 5
n.Line: 6
============
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  annotations:
    a.b.c: d.e.f
    g: h
spec:
  template: {}
 <nil>
```

For more context I am currently attempting use kyaml to do some yaml language suggestions in IDEs and was hoping to use the line number information to show in the IDE where the flagged yaml is.

**Comment by natasha41575** [comment]
After some experimentation with the code you've provided (by the way, thank you very much; it made investigating this much easier), I believe that `Line` correctly represents the line of the node where it was found. 

`obj.Pipe(yaml.Get(fieldName))` gives you the _value_ of the mapping node found by the key `fieldName`, so the result of the call to `obj.Pipe(yaml.Get("metadata"))` returns the node:
```
  name: app
  annotations:
    a.b.c: d.e.f
    g: h
```

This starts at line 4. You'll notice something similar if you change it to `obj.Pipe(yaml.Get("spec"))`, because it will return the node `template: {}`. Even though `spec` is at line 8, it gives you a node at line 9 because that is where the returned node object starts. 

If you do `obj.Pipe(yaml.Get("kind"))`, however, the value returned is the node `Deployment`, which is at line 2. If you run these examples you will notice that the line number printed is always where the value of the field key starts, rather than the line number of the field name itself.

I hope that answers your question.
