### ISSUE TITLE
How to reference Files with Starlark Function?

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kustomize#4182]
How do I reference a `functionFiles` from within a Starlark function? 

Here is the yaml for my function:
`embed.yaml`
```yaml
apiVersion: someteam
kind: Embed
metadata:
  name: test-embed
  annotations:
    config.kubernetes.io/function: |
      starlark:
        path: kustomize/functions/embed/embed.star
spec:
  target:
    kind: Function
    fieldPath: spec.source
    fileRef: cool.py
functionFiles:
- cool.py
```
Is it even possible for Starlark to reference files from the host? I have a feeling kustomize would have to read files and pass in the content as variables. 

Within the code I can only get the name of the files in an array like so:
```python
files = ctx.resource_list["functionConfig"]["functionFiles"]
```
Now how to actually read the file contents?
