### ISSUE TITLE
Output difference between 4.2.0 and 4.3.0

### ISSUE THREAD

**Issue by larsks** [kubernetes-sigs/kustomize#4183]
**Describe the bug**

I am running kustomize 4.3.0 locally, but I am deploying into an argocd system that is running kustomize 4.1.1. I ran into a recent problem in which the `kustomize build` output on my system does not match the output generated by 4.1.1. I am unsure if this is a bug in 4.1.1 that has been fixed, a new bug in 4.3.0, or if I am simply bad at reading release notes. I tested releases between 4.1.1 and 4.3.0, and the problem reproduces with everything before 4.3.0. I'll be using 4.2.0 in the rest of this issue.

The tl;dr for the bug is that given a strategic merge patch, in 4.3.0 the patch *modifies* the contents of the original resources, but in 4.2.0 the patch *replaces* the contents of the original resource.

I've put together a reproducer in https://github.com/larsks/kustomize-bug-example, which has a base that defines two resources (a pod and a cronjob) and then applies effectively the same patch to both resources.

The difference only shows up in the patched cronjob resource.

**Files that can reproduce the issue**

In `base/cronjob.yaml`, I have:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: example-cronjob
              image: docker.io/alpine:latest
              command:
                - sleep
                - 10
              env:
                - name: EXAMPLE_FOO
                  value: foo
          restartPolicy: Never
```

In `base/kustomization.yaml` I have:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomize-example
commonLabels:
  app: kustomiez-example

resources:
- cronjob.yaml
```

In `overlay/example/kustomization.yaml` I have:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moc-projects
resources:
  - ../../base

patches:
  - path: patch_cronjob.yaml
```

In `overlay/example/patch_cronjob.yaml` I have:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: example-cronjob
              envFrom:
                - configMapRef:
                    name: moc-project-config
```

**Expected output**

Under 4.3.0, the patch produces the desired output:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: kustomiez-example
  name: example-cronjob
  namespace: moc-projects
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: kustomiez-example
    spec:
      template:
        metadata:
          labels:
            app: kustomiez-example
        spec:
          containers:
          - command:
            - sleep
            - 10
            env:
            - name: EXAMPLE_FOO
              value: foo
            envFrom:
            - configMapRef:
                name: moc-project-config
            image: docker.io/alpine:latest
            name: example-cronjob
          restartPolicy: Never
  schedule: '*/5 * * * *'
```

**Actual output**

Under 4.2.0, `kustomize build` produces:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: kustomiez-example
  name: example-cronjob
  namespace: moc-projects
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: kustomiez-example
    spec:
      template:
        metadata:
          labels:
            app: kustomiez-example
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: moc-project-config
            name: example-cronjob
          restartPolicy: Never
  schedule: '*/5 * * * *'
```

The diff vs 4.3.0 is:

```
--- /dev/fd/63	2021-09-14 20:45:20.727048444 -0400
+++ /dev/fd/62	2021-09-14 20:45:20.728048465 -0400
@@ -18,16 +18,9 @@
             app: kustomiez-example
         spec:
           containers:
-          - command:
-            - sleep
-            - 10
-            env:
-            - name: EXAMPLE_FOO
-              value: foo
-            envFrom:
+          - envFrom:
             - configMapRef:
                 name: moc-project-config
-            image: docker.io/alpine:latest
             name: example-cronjob
           restartPolicy: Never
   schedule: '*/5 * * * *'
```

**Platform**

Linux (Fedora 34), amd64

**Additional context**

https://github.com/larsks/kustomize-bug-example
