### ISSUE TITLE
[Question] Why do Kustomize doesn't apply base commonLabels to resources (not patches) in overlays?

### ISSUE THREAD

**Issue by pentago** [kubernetes-sigs/kustomize#4184]
For example, I have a project where I declare `commonLabels` in base kustomization.yaml.

In each overlay `kustomization.yaml` I have both patches to the base and resources that exist only in overlays (_e.g. secrets_).

When building an overlay, `commonLabels` are applied only to base stuff but not to overlay resources for some reason.

Would it be natural to expect that `commonLabels` should do what they're implying, to be shared across ALL objects in the project, both base, and overlay resources?

This way we can keep DRY and not repeat `commonLabels` in both base and each project overlay.

Thoughts?

**Comment by natasha41575** [comment]
Could you provide sample kustomization files and resources, as well as the output you are getting? From what you've described, I'd expect kustomize to apply the labels to all resources.

**Comment by pentago** [comment]
Sure, here's my `base` `kustomization.yaml`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  deployed: TIMESTAMP

commonLabels:
  project: xxx

resources:
- gar-credentials-secret_sealed.yaml
- cloud-storage-secret_sealed.yaml
- ingress-basic-auth-secret_sealed.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

images:
- name: us-east1-docker.pkg.dev/app-project-321313/app/app
  newTag: latest

```

My `dev` overlay kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: app-dev

commonLabels:
  tier: dev

resources:
  - mysql-development-secret_sealed.yaml
  - adminer_service.yaml
  - adminer_ingress.yaml
  - adminer_deployment.yaml

patches:
  - deployment_env.yaml
  - ingress.yaml
```

When I do  `kustomize build environment/dev -o dev.yaml`, the output manifest file does not inherit and apply `commonLabels` and `commonAnnotations` declared in base's `kustomization.yaml` to any of the files listed under `dev` overlay **resources** section

For example, this is the portion of the output from the `dev.yaml` file:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    tier: dev
  name: adminer
  namespace: app-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
    tier: dev
```

As you can see, I included adminer service as a **resource** in the `dev` overlay but there are no `commonLabels` and `commonAnnotations` declared in base's `kustomization.yaml`.

I understand that I already use `commonLabels` in `dev` overlay but I expected that all resources will inherit other labels/annotations that are added to the base.
