### ISSUE TITLE
IngressClass should be ordered before Ingress

### ISSUE THREAD

**Issue by imgx64** [kubernetes-sigs/kustomize#4191]
**Describe the bug**

If I have both `Ingress` and `IngressClass` in the same kustomization, Ingress is sorted first in the output, and so applying gives this error:

```
Error from server (invalid ingress class: IngressClass.networking.k8s.io "my-ingress-class" not found): error when creating "./ingress-test/": admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: IngressClass.networking.k8s.io "my-ingress-class" not found
```

I can see that the order is defined explicitly for some objects already. I think `IngressClass` should be added to the list, similarly to `StorageClass` or `PriorityClass` :

https://github.com/kubernetes-sigs/kustomize/blob/53577a5190ebf7bee60fdc1c1c022a3ac229e99a/kyaml/resid/gvk.go#L136-L159

However, I don't know how `elbv2.k8s.aws/v1beta1/IngressClassParams` can possibly be explicitly sorted before `IngressClass`, since it's a CRD. And every other ingress controller will have its own CRD for the parameters property.

**Files that can reproduce the issue**

ingress-test.yaml

```
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: my-ingress-class
spec:
  scheme: internet-facing
  group:
    name: my-ingress-class
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: my-ingress-class
spec:
  controller: ingress.k8s.aws/alb
  parameters:
    apiGroup: elbv2.k8s.aws
    kind: IngressClassParams
    name: my-ingress-class

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.6
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: my-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: my-ingress-class
  defaultBackend:
    service:
      name: my-service
      port:
        number: 80

```

**Expected output**

IngressClass should be sorted before Ingress:
```
$ kustomize build . | grep '^kind:'
kind: Service
kind: Deployment
kind: IngressClassParams
kind: IngressClass
kind: Ingress
```

**Actual output**

Ingress is sorted before IngressClass :
```
$ kustomize build . | grep '^kind:'
kind: Service
kind: Deployment
kind: IngressClassParams
kind: Ingress
kind: IngressClass
```

**Kustomize version**

```
$ kustomize version
{Version:kustomize/v4.3.0 GitCommit:cd17338759ef64c14307991fd25d52259697f1fb BuildDate:2021-08-24T19:24:28Z GoOs:linux GoArch:amd64}
```

**Platform**

all
