### ISSUE TITLE
[Question] patch specific list element targeted by element attribute

### ISSUE THREAD

**Issue by polasekr** [kubernetes-sigs/kustomize#4194]
Currently, I have a following kustomization definition, which deletes 9th step from a first task of a tekton pipelinerun definition.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- release.yaml

patches:
- patch: |-
    - op: remove
      path: /spec/pipelineSpec/tasks/0/taskSpec/steps/9
```
As it is right now it references list elements by their indexes in their respective arrays.
There are few problems with such approach:
1) any change of element order requires making changes to kustomization file
2) not very intuitive - you don't know what kustomization is doing just by reading kustimization file

I would like to reference the element by its attributes similarly as used in replacements:

`spec.pipelineSpec.tasks.[name=release].taskSpec.steps.[name=cypress-test]`

Is there such option to achieve it?
