### ISSUE TITLE
Multi-Line values receive injected newlines in the middle of the value in the output of `kustomize build`

### ISSUE THREAD

**Issue by chrisprijic** [kubernetes-sigs/kustomize#4201]
**Describe the bug**

This is based on the helm chart for [Pulsar](https://github.com/apache/pulsar-helm-chart), specifically their file [here](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/pulsar-cluster-initialize.yaml) after running `helm template` and `kustomize build`. Below is a sample smaller project that can reproduce the bug.

I have a Job yaml that includes a multi-line string for an arg. After running `kustomize build`, it introduces extra newlines in the multi-line string that breaks the argument and makes the container not work as intended.

I do have the means to run the helm chart without `kustomize`, but we want to support this workflow in the future in case we do need to make customizations.

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./job.yaml
namespace: pulsar
```

job.yaml

```
apiVersion: batch/v1
kind: Job
metadata:
  name: "pulsar-pulsar-init"
  namespace: default
  labels:
    app: pulsar
    chart: pulsar-2.7.3
    release: pulsar
    heritage: Helm
    cluster: pulsar
    component: pulsar-init
spec:
  template:
    spec:
      initContainers:
        - name: wait-zookeeper-ready
          image: "apachepulsar/pulsar-all:2.7.2"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >-
              until nslookup pulsar-zookeeper-2.pulsar-zookeeper.pulsar; do
                sleep 3;
              done;
        # This initContainer will wait for bookkeeper initnewcluster to complete
        # before initializing pulsar metadata
        - name: pulsar-bookkeeper-verify-clusterid
          image: "apachepulsar/pulsar-all:2.7.2"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >
              bin/apply-config-from-env.py conf/bookkeeper.conf;

              until bin/bookkeeper shell whatisinstanceid; do
                sleep 3;
              done;
          envFrom:
            - configMapRef:
                name: "pulsar-bookie"
          volumeMounts:

      containers:
        - name: "pulsar-pulsar-init"
          image: "apachepulsar/pulsar-all:2.7.2"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >

              bin/pulsar initialize-cluster-metadata \
                --cluster pulsar \
                --zookeeper pulsar-zookeeper:2181 \
                --configuration-store pulsar-zookeeper:2181 \
                --web-service-url http://pulsar-broker.pulsar.svc.cluster.local:8080/ \
                --web-service-url-tls https://pulsar-broker.pulsar.svc.cluster.local:8443/ \
                --broker-service-url pulsar://pulsar-broker.pulsar.svc.cluster.local:6650/ \
                --broker-service-url-tls pulsar+ssl://pulsar-broker.pulsar.svc.cluster.local:6651/ || true;
          volumeMounts:

      volumes:

      restartPolicy: Never
```

**Expected output**

Expect the namespace to be updated; the rest of the file should remain the same:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: "pulsar-pulsar-init"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-2.7.3
    release: pulsar
    heritage: Helm
    cluster: pulsar
    component: pulsar-init
spec:
  template:
    spec:
      initContainers:
        - name: wait-zookeeper-ready
          image: "apachepulsar/pulsar-all:2.7.2"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >-
              until nslookup pulsar-zookeeper-2.pulsar-zookeeper.pulsar; do
                sleep 3;
              done;
        # This initContainer will wait for bookkeeper initnewcluster to complete
        # before initializing pulsar metadata
        - name: pulsar-bookkeeper-verify-clusterid
          image: "apachepulsar/pulsar-all:2.7.2"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >
              bin/apply-config-from-env.py conf/bookkeeper.conf;

              until bin/bookkeeper shell whatisinstanceid; do
                sleep 3;
              done;
          envFrom:
            - configMapRef:
                name: "pulsar-bookie"
          volumeMounts:

      containers:
        - name: "pulsar-pulsar-init"
          image: "apachepulsar/pulsar-all:2.7.2"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - >

              bin/pulsar initialize-cluster-metadata \
                --cluster pulsar \
                --zookeeper pulsar-zookeeper:2181 \
                --configuration-store pulsar-zookeeper:2181 \
                --web-service-url http://pulsar-broker.pulsar.svc.cluster.local:8080/ \
                --web-service-url-tls https://pulsar-broker.pulsar.svc.cluster.local:8443/ \
                --broker-service-url pulsar://pulsar-broker.pulsar.svc.cluster.local:6650/ \
                --broker-service-url-tls pulsar+ssl://pulsar-broker.pulsar.svc.cluster.local:6651/ || true;
          volumeMounts:

      volumes:

      restartPolicy: Never
```

**Actual output**

See the newline between `bin/pulsar initialize-cluster-metadata` and `--cluster ...`, as well as `until nslookup ...` and `sleep ...`:

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: pulsar
    chart: pulsar-2.7.3
    cluster: pulsar
    component: pulsar-init
    heritage: Helm
    release: pulsar
  name: pulsar-pulsar-init
  namespace: pulsar
spec:
  template:
    spec:
      containers:
      - args:
        - |2

          bin/pulsar initialize-cluster-metadata \

            --cluster pulsar \
            --zookeeper pulsar-zookeeper:2181 \
            --configuration-store pulsar-zookeeper:2181 \
            --web-service-url http://pulsar-broker.pulsar.svc.cluster.local:8080/ \
            --web-service-url-tls https://pulsar-broker.pulsar.svc.cluster.local:8443/ \
            --broker-service-url pulsar://pulsar-broker.pulsar.svc.cluster.local:6650/ \
            --broker-service-url-tls pulsar+ssl://pulsar-broker.pulsar.svc.cluster.local:6651/ || true;
        command:
        - sh
        - -c
        image: apachepulsar/pulsar-all:2.7.2
        imagePullPolicy: IfNotPresent
        name: pulsar-pulsar-init
        volumeMounts: null
      initContainers:
      - args:
        - |-
          until nslookup pulsar-zookeeper-2.pulsar-zookeeper.pulsar; do

            sleep 3;
          done;
        command:
        - sh
        - -c
        image: apachepulsar/pulsar-all:2.7.2
        imagePullPolicy: IfNotPresent
        name: wait-zookeeper-ready
      - args:
        - |
          bin/apply-config-from-env.py conf/bookkeeper.conf;
          until bin/bookkeeper shell whatisinstanceid; do

            sleep 3;
          done;
        command:
        - sh
        - -c
        envFrom:
        - configMapRef:
            name: pulsar-bookie
        image: apachepulsar/pulsar-all:2.7.2
        imagePullPolicy: IfNotPresent
        name: pulsar-bookkeeper-verify-clusterid
        volumeMounts: null
      restartPolicy: Never
      volumes: null
```

**Kustomize version**

```
{Version:kustomize/v4.3.0 GitCommit:cd17338759ef64c14307991fd25d52259697f1fb BuildDate:2021-08-24T19:04:58Z GoOs:linux GoArch:amd64}
```

**Platform**

Windows 10, WSL2 on Ubuntu 18.04

```
Windows 10
Release 20H2
OS Build 19042.1237
```

```
$> lsb_release -a
LSB Version:    core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

**Additional context**

The newline introduced between the command and its arguments breaks the command from running as intended. Why is this newline introduced after each muti-line values' first line?
