### ISSUE TITLE
[Question] Using 'replacements' instead 'vars' for inline values

### ISSUE THREAD

**Issue by jkroepke** [kubernetes-sigs/kustomize#4211]
hi,

I recently read https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/ which instructs me thats vars going to be deprecated. While thats describes some case to migrate to replacements, I can not find a way where replacements can be a replacement for vars.

Scenario:

I have a CRD, like this

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
spec:
  kafka:
    authorization:
      superUsers:
        - CN=$(KAFKA_SERVICE_USER)
```

and vars (including varReference) like this:

```yaml
vars:
  - name: KAFKA_SERVICE_USER
    objref:
      apiVersion: v1beta2
      group: kafka.strimzi.io
      kind: KafkaUser
      name: kafka-service-user
```

which results into:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
spec:
  kafka:
    authorization:
      superUsers:
        - CN=kafka-service-user-dev
```

The closed possible example could be this one:

```yaml
replacements:
  - source:
      version: v1beta2
      group: kafka.strimzi.io
      kind: KafkaUser
      name: kafka-service-user
      fieldPath: metadata.name
    targets:
      - select:
          version: v1beta1
          group: kafka.strimzi.io
          kind: Kafka
          name: cluster
        fieldPaths:
        - spec.kafka.authorization.superUsers.0
```

But this results into this:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
spec:
  kafka:
    authorization:
      superUsers:
        - kafka-service-user-dev
```

and strips the required `CN=` value.

Do I miss something? There is a feature like prefix or suffix that can be that the same way like delimiter or index?

**Comment by natasha41575** [comment]
You can use `delimiter` and `index` to add prefixes and suffixes. For your use case:

Your original resource:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
spec:
  kafka:
    authorization:
      superUsers:
        - CN=KAFKA_SERVICE_USER
```

Your replacement:
```
replacements:
  - source:
      version: v1beta2
      group: kafka.strimzi.io
      kind: KafkaUser
      name: kafka-service-user
      fieldPath: metadata.name
    targets:
      - select:
          version: v1beta1
          group: kafka.strimzi.io
          kind: Kafka
          name: cluster
        fieldPaths:
        - spec.kafka.authorization.superUsers.0
        options:
          delimiter: "="
          index: 1
```

Please try this out and let me know if it works.

**Comment by arash-bizcover** [comment]
@natasha41575 
What if we want to add a suffix that is not in the source, for example, I have a json files that I want to create secret out of it, `appsettings.json`

I just want to create the secret with the name of deployment + suffix **so the secret name become deploymentname-appsettings** 

This is what I have which I cannot add any suffix (I just want to add suffix to the secret nothing else)
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  
secretGenerator:
  - name: NA
    files:
      - appsettings.json
    options:
      disableNameSuffixHash: true   
      labels: 
        type: appsettings 

replacements:
  - source:
      kind: Deployment
      fieldPath: metadata.name
    targets:
      - select:
          kind: Secret
        fieldPaths:
          - metadata.name
```

**Comment by james-callahan** [comment]
I have a similar question about an existing `vars` usage.
As part of our CI runs we use `vars` to substitute the pull request number into:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: thing
spec:
  tls:
    - hosts:
        - "pr$(PR_NUMBER)-admin.example.com"
      secretName: admin-tls
  rules:
    - host: "pr$(PR_NUMBER)-admin.example.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              serviceName: myservice
              servicePort: http
```

How can we use `replacements` instead of `vars` here?
