### ISSUE TITLE
Error using [Merge Key Language-Independent Type](https://yaml.org/type/merge.html) support for YAML anchor/alias

### ISSUE THREAD

**Issue by RE-codes** [kubernetes-sigs/kustomize#4215]
**Describe the bug**

Following up on https://github.com/kubernetes-sigs/kustomize/issues/3675. I have found anchor/alias support improved. However, when using _Merge Key Language-Independent Type_ notation (i.e. `<<: *some_anchor`) I am presented with this error:

`Error: map[string]interface {}{"apiVersion":"apps/v1", "kind":"Deployment", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"annotation1":"annotation1", "annotation2":"annotation2", "annotation3":"annotation3"}, "labels":map[string]interface {}{"app":"myApp", "label1":"label1", "label2":"label2", "label3":"label3"}, "name":"myApp", "namespace":"app-namespace"}, "spec":map[string]interface {}{"replicas":3, "selector":map[string]interface {}{"matchLabels":map[string]interface {}{"app":"myApp"}}, "template":map[string]interface {}{"copy-of-metadata":map[string]interface {}{"annotations":map[string]interface {}{"annotation1":"annotation1", "annotation2":"annotation2", "annotation3":"annotation3"}, "labels":map[string]interface {}{"app":"myApp", "label1":"label1", "label2":"label2", "label3":"label3"}, "name":"myApp", "namespace":"app-namespace"}, "metadata":map[string]interface {}{"annotations":map[interface {}]interface {}{"annotation1":"annotation1", "annotation2":"annotation2", "annotation3":"annotation3", "annotation4":"annotation4"}, "labels":map[string]interface {}{"app":"myApp", "label1":"label1", "label2":"label2", "label3":"label3"}, "name":"myApp", "namespace":"app-namespace"}, "spec":map[string]interface {}{"containers":[]interface {}{map[string]interface {}{"image":"some-registry/some-namespace/myApp:latest", "name":"myApp"}}, "imagePullSecrets":[]interface {}{map[string]interface {}{"name":"some_secret"}}}}}}: json: unsupported type: map[interface {}]interface {}`

**Files that can reproduce the issue**

kustomization.yaml

```
resources:
- test-deployment.yam
```

test-deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata: &meta
  name: &name myApp
  namespace: &ns app-namespace
  annotations: &annotations
    annotation1: annotation1
    annotation2: annotation2
    annotation3: annotation3
  labels: &labels
    app: *name
    label1: label1
    label2: label2
    label3: label3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myApp
  template:
    copy-of-metadata: *meta
    metadata: 
      name: *name
      namespace: *ns
      labels: *labels
      annotations:
        <<: *annotations
        annotation4: annotation4
    spec:
      imagePullSecrets:
        - name: some_secret
      containers:
        - name: myApp
          image: some-registry/some-namespace/myApp:latest
```

**Expected output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    annotation1: annotation1
    annotation2: annotation2
    annotation3: annotation3
  labels:
    app: myApp
    label1: label1
    label2: label2
    label3: label3
  name: myApp
  namespace: app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myApp
  template:
    copy-of-metadata:
      annotations:
        annotation1: annotation1
        annotation2: annotation2
        annotation3: annotation3
      labels:
        app: myApp
        label1: label1
        label2: label2
        label3: label3
      name: myApp
      namespace: app-namespace
    metadata:
      annotations:
        annotation1: annotation1
        annotation2: annotation2
        annotation3: annotation3
        annotation4: annotation4
      labels:
        app: myApp
        label1: label1
        label2: label2
        label3: label3
      name: myApp
      namespace: app-namespace
    spec:
      containers:
      - image: some-registry/some-namespace/myApp:latest
        name: myApp
      imagePullSecrets:
      - name: some_secret
 ``` 

**Actual output**

See error message above.

**Kustomize version**

`{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:13:36Z GoOs:darwin GoArch:amd64}`

**Platform**

macOS Big Sur

**Additional context**

The same error is noted in https://github.com/kubernetes-sigs/kustomize/issues/4212.
