### ISSUE TITLE
Support annotation and label selection in replacement targets

### ISSUE THREAD

**Issue by seh** [kubernetes-sigs/kustomize#4223]
# Description

When populating just the "replacements.targets.select.annotationSelector" field for restricting the targets of a [replacement](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/), _kustomize_ mistakenly chooses all candidate resources as targets.

# Test Case

### File _objects.yaml_
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: s-1
  namespace: ns-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-1
  namespace: ns-1
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-1/s-1
```

### File _kustomization.yaml_

Though my _actual_ intention is to match only objects annotated with "cert-manager.io/inject-ca-from-secret" with a specific value, I discovered that no matter what value I use for the "annotationSelector" field, including the empty string, _kustomize_ will apply the replacement to any target object that has the "cert-manager.io/inject-ca-from-secret" annotation present—or at least those are the only targets for which the replacement has consequences. Here I've used the annotation selector "xyz=123" to make it obvious that it should not match any of the objects.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- objects.yaml

namespace: ns-2

replacements:
- source:
    group: ""
    kind: Secret
    name: s-1
    fieldPath: metadata.namespace
  targets:
  - select:
      annotationSelector: xyz=123
    fieldPaths:
    - metadata.annotations.cert-manager\.io/inject-ca-from-secret
    options:
      delimiter: /
```

## Expected Output

I'm expecting the "cm-1" _ConfigMap_ to retain its original annotation value.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-1/s-1
  name: cm-1
  namespace: ns-2
---
apiVersion: v1
kind: Secret
metadata:
  name: s-1
  namespace: ns-2
```

## Actual Output

Note that the "cm-1" _ConfigMap_'s annotation value changed to reflect the "ns-2" namespace in which the "s-1" _Secret_ now sits.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-2/s-1
  name: cm-1
  namespace: ns-2
---
apiVersion: v1
kind: Secret
metadata:
  name: s-1
  namespace: ns-2
```

# Context

## Kustomize Version

`{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:13:36Z GoOs:darwin GoArch:amd64}`

## Platform

macOS

## Additional

My real goal is to select certain objects annotated with particular values of "cert-manager.io/inject-ca-from-secret," and to replace those values. That works, but it works too liberally: _kustomize_ applies the replacement to objects with that annotation, but even those with different values that don't match the selector.

To make the example more realistic, consider the following.

#### File _objects.yaml_
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: s-1
  namespace: ns-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-1
  namespace: ns-1
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-1/s-1
---
apiVersion: v1
kind: Secret
metadata:
  name: s-2
  namespace: ns-3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-2
  namespace: ns-3
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-3/s-2
```

### File _kustomization.yaml_

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- objects.yaml

namespace: ns-2

replacements:
- source:
    group: ""
    kind: Secret
    name: s-1
    fieldPath: metadata.namespace
  targets:
  - select:
      annotationSelector: cert-manager.io/inject-ca-from-secret=ns-1/s-1
    fieldPaths:
    - metadata.annotations.cert-manager\.io/inject-ca-from-secret
    options:
      delimiter: /
```

### Expected Output

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-2/s-1
  name: cm-1
  namespace: ns-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-3/s-2
  name: cm-2
  namespace: ns-2
---
apiVersion: v1
kind: Secret
metadata:
  name: s-1
  namespace: ns-2
---
apiVersion: v1
kind: Secret
metadata:
  name: s-2
  namespace: ns-2
```

### Actual Output

Note that the "cm-2" _ConfigMap_'s annotation value starts with "ns-2"—the namespace of the "s-1" _Secret_—instead of retaining its original value of "ns-3/s-2."

(Let's ignore that the namespace for the "s-2" _Secret_ changed from "ns-3" to "ns-2" by virtue of the "namespace" field in the _kustomization_. That's _kustomize_ working as directed. My real scenario doesn't suffer that problem.)

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-2/s-1
  name: cm-1
  namespace: ns-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: ns-2/s-2
  name: cm-2
  namespace: ns-2
---
apiVersion: v1
kind: Secret
metadata:
  name: s-1
  namespace: ns-2
---
apiVersion: v1
kind: Secret
metadata:
  name: s-2
  namespace: ns-2
```
