### ISSUE TITLE
ConfigMapGenerator merge multiple resources at once

### ISSUE THREAD

**Issue by langrp** [kubernetes-sigs/kustomize#4225]
## Is your feature request related to a problem? Please describe.
I'd like be able to merge `configMap` on different levels of the application structure at once. I currently use `base` and `overlays` for each environment. But in my case each environment consists of multiple clusters with different flavours of my app.
```
├── base
│   ├── flavor-a
│   │   └── kustomization.yaml
│   └── flavor-b
│       └── kustomization.yaml
└── overlay
    └── dev
        ├── c01
        │   ├── flavor-a
        │   │   └── kustomization.yaml
        │   ├── flavor-b
        │   │   └── kustomization.yaml
        │   └── kustomization.yaml
        ├── c02
        │   ├── flavor-b
        │   │   └── kustomization.yaml
        │   └── kustomization.yaml
        └── kustomization.yaml
```
```bash
$cat base/flavor-1/kustomization.yaml

configMapGenerator:
  - name: app-config
    behavior: create
    literals:
    - DB_HOST="db"
```
```bash
$cat overlay/dev/kustomization.yaml
resources:
- c01
- c02

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
    - ENVIRONMENT="dev"
```
```bash
$cat overlay/dev/c01/kustomization.yaml
resources:
- flavor-a
- flavor-b

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
    - DB_HOST="db"
```
```
$cat overlay/dev/c01/flavor-a/kustomization.yaml
resources:
- ../../../../base/flavor-a

nameSuffix: -c01-a

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
    - APP_PROP="some-property-for-a"
```
```
$cat overlay/dev/c01/flavor-b/kustomization.yaml
resources:
- ../../../../base/flavor-b

nameSuffix: -c01-b

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
    - APP_PROP="some-property-for-b"
```

There are multiple level of configurations I'd like to propagate to below resources and was able to modify any property on any level. But the error Im getting is
```
merging from generator &{0xc000315770 {  map[] map[]} {{ app-config merge {[XXX] [] [] } <nil>}}}: found multiple objects [<list of objects>] that could accept merge of ~G_v1_ConfigMap|~X|app-config
```

## Describe the solution you'd like
I'd like to be able to say generator to apply my config generator to each sub-resource matching the generator name.

```bash
$cat overlay/dev/c01/kustomization.yaml
resources:
- flavor-a
- flavor-b

configMapGenerator:
  - name: app-config
    behavior: mergeall <-- merge all
    literals:
    - DB_HOST="db"
```

**Describe alternatives you've considered**
I used single property file on each level and override each configMapGenerator for each flavor on each level. This however grows a lot with each new cluster and flavor.
