### ISSUE TITLE
configMapGenerator: single quote removed from config map literal if quote is last character

### ISSUE THREAD

**Issue by mloesch** [kubernetes-sigs/kustomize#4233]
**Describe the bug**

When defining a literal value in `configMapGenerator` where the last character is a single quote, the last character is removed by `kustomize build`.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: test
    literals:
      - TEST=this is a 'test'
```

**Expected output**

```
apiVersion: v1
data:
  TEST: this is a 'test'
kind: ConfigMap
metadata:
  name: test-k7hhfb697g
```

**Actual output**

``` 
apiVersion: v1
data:
  TEST: this is a 'test
kind: ConfigMap
metadata:
  name: test-k7hhfb697g
``` 
The trailing single quote is missing.

**Note:** if the single quote is not the last character, it works as expected:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: test
    literals:
      - TEST=this is a 'test'.
```

Yields:

```
apiVersion: v1
data:
  TEST: this is a 'test'.
kind: ConfigMap
metadata:
  name: test-2b7bkd58k5
```

**Kustomize version**

`{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:24:12Z GoOs:linux GoArch:amd64}
`

**Platform**

Linux
