### ISSUE TITLE
Running kustomize build panics

### ISSUE THREAD

**Issue by MikaelSmith** [kubernetes-sigs/kustomize#4240]
**Describe the bug**
Panic when building a project with an entry `namespace: `. `kubectl apply` doesn't complain about this, and it's hard to debug what causes it.

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/resmap.getNamespacesForRoleBinding(0xc000355270)
        sigs.k8s.io/kustomize/api@v0.10.0/resmap/reswrangler.go:439 +0x21b
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).SubsetThatCouldBeReferencedByResource(0xc00000f500, 0x4735da0)
        sigs.k8s.io/kustomize/api@v0.10.0/resmap/reswrangler.go:399 +0x105
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc000ac10f0, {0x475bbd0, 0xc00000f500})
        sigs.k8s.io/kustomize/api@v0.10.0/internal/accumulator/namereferencetransformer.go:55 +0xdc
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
        sigs.k8s.io/kustomize/api@v0.10.0/internal/accumulator/resaccumulator.go:142
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0xd0)
        sigs.k8s.io/kustomize/api@v0.10.0/internal/accumulator/resaccumulator.go:168 +0xc5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0003860d0)
        sigs.k8s.io/kustomize/api@v0.10.0/internal/target/kusttarget.go:131 +0x6f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        sigs.k8s.io/kustomize/api@v0.10.0/internal/target/kusttarget.go:112
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc002327d98, {0x4755d60, 0x4b84ac8}, {0x7ffeefbff1b0, 0x1d})
        sigs.k8s.io/kustomize/api@v0.10.0/krusty/kustomizer.go:88 +0x39c
sigs.k8s.io/kustomize/kustomize/v4/commands/build.NewCmdBuild.func1(0xc000356580, {0xc000317900, 0x1, 0x1})
        sigs.k8s.io/kustomize/kustomize/v4/commands/build/build.go:80 +0x176
github.com/spf13/cobra.(*Command).execute(0xc000356580, {0xc0003178d0, 0x1, 0x1})
        github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000356000)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        sigs.k8s.io/kustomize/kustomize/v4/main.go:14 +0x1e
```

**Resources**
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test
subjects:
- kind: ServiceAccount
  name: test
  namespace:
roleRef:
  kind: Role
  name: test
  apiGroup: rbac.authorization.k8s.io
```

**Kustomize version**

```
{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:13:36Z GoOs:darwin GoArch:amd64}
```

on macOS.
