### ISSUE TITLE
configMap hashes are not applied to Reference

### ISSUE THREAD

**Issue by alexhein88** [kubernetes-sigs/kustomize#4246]
Not sure if this is a bug or expected behaviour: I tried to duplicate a config map via a nameSuffix. As I did so, the hash-insertion of  existing deployments stopped working. So here is an example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configs
- base1
- base2
```
configs/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: cm
  literals:
  - foo=bar
```
base1/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -world1

resources:
- deployment.yaml
```

base2/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -world2

resources:
- ../configs
- deployment.yaml
```
base1/deployment.yaml and base2/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: bithavoc/hello-world-env
        name: hello
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: cm
              key: foo
```

**Expected output**
I expect, that 2 ConfigMaps are created, cm-798k5k7g9f and cm-world2-798k5k7g9f. The base1-deployment should reference the first one and the base2-deployment should reference the second one.

**Actual output**

Both ConfigMaps are created, and the base2-deployment references cm-world2-798k5k7g9f. But the base1-deployment references the non-existent ConfigMap cm, where no hash is inserted.

When deleting base2 in the root, the reference is set correctly again.

**Kustomize version**

{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:24:12Z GoOs:linux GoArch:amd64}

**Platform**

Ubuntu 20.04 in Windows (wsl2)
