### ISSUE TITLE
Unable to create serviceMonitor from Helm chart with Kustomize

### ISSUE THREAD

**Issue by stoupance** [kubernetes-sigs/kustomize#4247]
**Describe the bug**

I'm trying to use `Kustomize` to inflate the [Helm chart of ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx) in order to add the `serviceMonitor` and `prometheusRule` sections, for monitoring purposes. It is disabled by default in the provided `helmChart`, but it can be overrided as a [native chart values](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L629).
The YAML built by `Kustomize` outputs the `prometheusRule` section as expected but not the `serviceMonitor` one. I tried multiple configurations and nothing output any YAML configuration for `serviceMonitor`

To put aside any issue from `Helm` itself, it works perfectly with a vanilla `Helm` (output YAML for both `serviceMonitor` and `prometheusRule`) but not when using `Kustomize` ontop of `Helm`.

**Files that can reproduce the issue**

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  valuesInline:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: true
  version: 4.0.6
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: xxx
```
or

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
generators:
  - generators.yaml
```

generators.yaml

```yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: nginx
name: ingress-nginx
repo: https://kubernetes.github.io/ingress-nginx
releaseName: xxx
valuesFile: values.yaml
```

value.yaml

```yaml
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
```

**Expected output**

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: toto-ingress-nginx-controller
  labels:
    helm.sh/chart: ingress-nginx-4.0.6
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: xxx
    app.kubernetes.io/version: "1.0.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
spec:
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: xxx
      app.kubernetes.io/component: controller
```

**Actual output**

The output doesn't have any `serviceMonitor` YAML section as expected but still contains the rest of the YAML manifests (`Service`, `Deployment`, `ClusterRole`...)

**Kustomize version**

`{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:24:12Z GoOs:linux GoArch:amd64}`

**Platform**

`Linux`

**Additional context**

It doesn't work for both `Kustomize` configurations provided and it works when using only `Helm`. Sadly, there is no error and.
Any help will be greatly appreciated. Thanks!
