### ISSUE TITLE
Wrong type detection when using extend anchor in yaml files

### ISSUE THREAD

**Issue by erfan-mehraban** [kubernetes-sigs/kustomize#4251]
**Describe the bug**

In `build` command, If there is extend anchor in yaml file, fatal error accrues.

**Files that can reproduce the issue**

kustomization.yml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
```

deployment.yml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  <<: &anchor
    key: value
  template:
    <<: *anchor
```

**Expected output**

successful build.

**Actual output**

```
$ kustomize build
Error: map[string]interface {}{"apiVersion":"apps/v1", "kind":"Deployment", "metadata":map[string]interface {}{"name":"deployment"}, "spec":map[interface {}]interface {}{"key":"value", "template":map[interface {}]interface {}{"key":"value"}}}: json: unsupported type: map[interface {}]interface {}
```

**Kustomize version**

`{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:24:12Z GoOs:linux GoArch:amd64}`

**Platform**

Ubuntu 20.04.3 LTS
