### ISSUE TITLE
Allow specifying key in secretGenerator

### ISSUE THREAD

**Issue by skluthe** [kubernetes-sigs/kustomize#4252]
**Is your feature request related to a problem? Please describe.**

I am trying to setup an [additional scrape config](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md) in prometheus-operator but I am restricted to one key. When generating a secret, it uses the file names as the key. I would like to combine these all into one key so I can separate the files out some for easier management.

**Describe the solution you'd like**

I would like to specify the following to combine said files into a single key:
```yaml
secretGenerator:
- name: additional-scrape-configs
  files:
  - targets/production/app-servers.yaml
  - targets/production/db-primary.yaml
  key: additional-scrape-configs.yaml
 ```

**Describe alternatives you've considered**
Tried looking through generatorOptions but didn't see anything. I can just combine everything into one file for it to work but it will be significantly more difficult to maintain as I get all of my additional servers into the config. I could request a change on the prometheus-operator side of things.

If this is not something you would like to do, please let me know. I am also happy to open this ticket on the prometheus-operator side of things if you feel like this is not something that would be useful for other usecases.
