### ISSUE TITLE
'ambiguous' replacement of resourceNames in ClusterRole

### ISSUE THREAD

**Issue by mbfr** [kubernetes-sigs/kustomize#4254]
**Describe the bug**

I have a deployment and a generated configmap with the same name and I want to create a clusterrole to allow modifying the deployment. When I create this clusterrole, it replaces the resourceName with the hash-suffix named configmap and I can't stop it doing this.

**Files that can reproduce the issue**

kustomization.yaml

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx.yaml

configMapGenerator:
- name: nginx
  literals:
    - A=B
```

nginx.yaml

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-modify
rules:
- apiGroups: [ "" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "update", "patch" ]
  resourceNames:
  - nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: nginx

```

**Expected output**

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-modify
rules:
- apiGroups:
  - ""
  resourceNames:
  - nginx
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - patch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-mh97k977cd
...
```

**Actual output**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-modify
rules:
- apiGroups:
  - ""
  resourceNames:
  - nginx-mh97k977cd
  resources:
  - deployments
  verbs:
  - get
  - list
  - update
  - patch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-mh97k977cd
...
```

**Kustomize version**

```
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux

**Additional context**

I know I can fix this by disabling the hash suffix name on the configmap, or just changing the name of it, but I can't really do either of them in my real manifests for a few reasons.
