### ISSUE TITLE
Kustomize delete fields in base config for cronjob v1

### ISSUE THREAD

**Issue by camilojimenezf** [kubernetes-sigs/kustomize#4255]
**Describe the bug**

When apply kustomize patch with cronjob v1 some fields that are in base config are removed. This not occurs with cronjob v1beta1

**Files that can reproduce the issue**

Folder structure:

```
├── base
│   ├── cronjob.yaml
│   └── kustomization.yaml
└── overlays
    └── production
        ├── cronjob.yaml
        └── kustomization.yaml
```

Example:

base/kustomization.yaml
```
commonLabels:
  app: importer
resources:
- cronjob.yml

```

base/cronjob.yaml
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer
  namespace: integrations
spec:
  schedule: "30 8 * * *"
  jobTemplate:
    metadata:
      labels:
        cronjob: importer
    spec:
      template:
        spec:
          containers:
          - name: importer
            image: importer
            imagePullPolicy: Never
            envFrom:
            - configMapRef:
                name: importer-cronjob-env
            - secretRef:
                name: importer-cronjob-secrets
            - secretRef:
                name: aws
            - secretRef:
                name: aws-ses
            resources:
              requests:
                memory: "256Mi"
              limits:
                memory: "1Gi"
          restartPolicy: Never
```

production/overlays/kustomization.yaml
```
commonLabels:
  env: production
bases:
- ../../base
patchesStrategicMerge:
- cronjob.yaml
```

production/overlays/cronjob.yaml
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer
  namespace: integrations
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: importer
            image: importer-production-image
            imagePullPolicy: Always
```

**Expected output**

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: importer
    env: production
  name: importer
  namespace: integrations
spec:
  jobTemplate:
    metadata:
      labels:
        app: importer
        cronjob: importer
        env: production
    spec:
      template:
        metadata:
          labels:
            app: importer
            env: production
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: importer-cronjob-env
            - secretRef:
                name: importer-cronjob-secrets
            - secretRef:
                name: aws
            - secretRef:
                name: aws-ses
            image: importer-production-image
            imagePullPolicy: Always
            name: importer
            resources:
              limits:
                memory: 1Gi
              requests:
                memory: 256Mi
          restartPolicy: Never
  schedule: 30 8 * * *
```

**Actual output**

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: importer
    env: production
  name: importer
  namespace: integrations
spec:
  jobTemplate:
    metadata:
      labels:
        app: importer
        cronjob: importer
        env: production
    spec:
      template:
        metadata:
          labels:
            app: importer
            env: production
        spec:
          containers:
          - image: importer-production-image
            imagePullPolicy: Always
            name: importer
          restartPolicy: Never
  schedule: 30 8 * * *
```

In current output some fields like env variables are removed, this happens when i move from cronjob v1beta1 to cronjob v1

**Kustomize version**

kustomize/v4.1.3

**Platform**

Linux
