### ISSUE TITLE
Patching multiple resources implies wildcard name, implementation seems to be regex

### ISSUE THREAD

**Issue by MikaelSmith** [kubernetes-sigs/kustomize#4258]
**Describe the bug**

Documentation at https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v4.4.0/examples/patchMultipleObjects.md states you can provide
```
target:
  name: foo*
```

However as far as I can tell the feature implemented in https://github.com/kubernetes-sigs/kustomize/pull/1355 supported regexp names, which would have to be something like
```
target:
  name: foo.*
```

Documentation is otherwise unclear about what matching is done with `target.name`.

**Files that can reproduce the issue**

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pod1.yaml
- pod2.yaml
patches:
- patch: |-
    - op: add
      path: "/spec/restartPolicy"
      value: Never
  target:
    version: v1
    kind: Pod
    name: pod*
```

pod1.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: busybox
    name: pod1
```

pod2.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: busybox
    name: pod2
```

...
-->

**Expected output**

```
$ kustomize build .
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: busybox
    name: pod1
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: busybox
    name: pod2
  restartPolicy: Never
```

**Actual output**

```
$ kustomize build .
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: busybox
    name: pod1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: busybox
    name: pod2
```

**Kustomize version**

```
{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:13:36Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOS 11.6
