### ISSUE TITLE
CronJobs not being merged properly

### ISSUE THREAD

**Issue by rcomanne** [kubernetes-sigs/kustomize#4261]
**Describe the bug**

When CronJob objects are patches, the result is missing a lot of the initial configuration.  
Mainly, the container configuration and image reference are not updated / removed.

**Files that can reproduce the issue**

base/kustomization.yaml  
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-support

resources:
  - cronjob.yaml

images:
  - name: kube-dump
    newName: woozymasta/kube-dump
    newTag: 1.0.6
```
base/cronjob.yaml  
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-dump
spec:
  schedule: 0 9 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kube-dump
              image: kube-dump
              env:
                - name: DESTINATION_DIR
                  value: /data
              volumeMounts:
                - name: data
                  mountPath: /data
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
          volumes:
            - name: data
              emptyDir: {}
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
```

overlays/ota/kustomization.yaml  
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - cronjob_patch.yaml
```

overlays/ota/cronjob_patch.yaml  
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-dump
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kube-dump
              image: kube-dump
              env:
                - name: GIT_BRANCH
                  value: ota
```

**Expected output**

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-dump
spec:
  schedule: 0 9 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kube-dump
              image: woozymasta/kube-dump:1.0.6
              env:
                - name: DESTINATION_DIR
                  value: /data
                - name: GIT_BRANCH
                  value: ota
              volumeMounts:
                - name: data
                  mountPath: /data
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
          volumes:
            - name: data
              emptyDir: {}
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
```

**Actual output**

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-dump
  namespace: dev-support
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: GIT_BRANCH
              value: ota
            image: kube-dump
            name: kube-dump
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
          volumes:
          - emptyDir: {}
            name: data
  schedule: 0 9 * * *

```

**Kustomize version**

{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:linux GoArch:amd64}

**Platform**

Linux

**Additional context**

As you can see, the image hasn't been changed in this case. I've also found a case where the image reference is removed completely, but I cannot reliably reproduce this case without disclosing too much information about our project.
