### ISSUE TITLE
replacements entries get source and targets with null value appended

### ISSUE THREAD

**Issue by 616b2f** [kubernetes-sigs/kustomize#4270]
**replacements entries get source and targets appended**

when we edit an image to an kustomization.yaml file that has replacements in it, it adds source and targets properties with null values to them:

Example:

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
  - path: replacement.yaml
```

```shell
$ kustomize edit set image mycr.io/myimage:v1.0
```

**Expected output**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- path: replacement.yaml
images:
- name: mycr.io/image
  newTag: v1.0
```

**Actual output**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- path: replacement.yaml
  source: null
  targets: null
images:
- name: mycr.io/image
  newTag: v1.0
```

**Kustomize version**

4.4.0

**Platform**

Linux
