### ISSUE TITLE
inline SMP patch with empty group/version not matching inferred targets

### ISSUE THREAD

**Issue by Miles-Garnsey** [kubernetes-sigs/kustomize#4273]
**Describe the bug**

Patches and replacements do not appear to be applied to `resources` from remote sources.

**Files that can reproduce the issue**

```
cat << EOF > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/jetstack/google-cas-issuer/releases/download/v0.5.2/google-cas-issuer-v0.5.2.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: test-cm
  literals: 
  - annotationvalue=true
replacements:
- source:
    name: test-cm
    fieldPath: data.annotationvalue
  targets:
  - select: 
      kind: ServiceAccount
      name: ksa-google-cas-issuer
    fieldPaths:
    - metadata.annotations.[test-annotation]

patches:
- patch: |-
    kind: ServiceAccount
    metadata:
      name: ksa-google-cas-issuer
      annotations: 
        test-annotation: true
EOF
kustomize build 
```

**Expected output**

```
...
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-google-cas-issuer
  namespace: cert-manager
  annotations:
    test-annotation: true
...
```

**Actual output**

The patches or replacements are not applied. In the case of the patch, we get `Error: no matches for Id ~G_~V_ServiceAccount|~X|ksa-google-cas-issuer; failed to find unique target for patch ~G_~V_ServiceAccount|ksa-google-cas-issuer`.

If I comment out the patch section so that only the replacements are applied, they just silently fail. 

_(EDIT: perhaps this is because there is no existing annotation to replace, if replacements can't ever add an element to an array, or add a value if it doesn't exist, could this be clearer in the docs?)_

```
...
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-google-cas-issuer
  namespace: cert-manager
...
```

**Kustomize version**

Kustomize 4.4.0

**Platform**

MacOS.

**Comment by natasha41575** [comment]
The [replacements docs](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) specify that if a value doesn't exist, you can use the `create` option.

It also seems that you are trying to use the patch to change the name of the resource. Patches by default will not change the name, unless you specify the `allowNameChange` option, which is specified in the [patches documentation](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/). 

Editing your kustomization file to

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/jetstack/google-cas-issuer/releases/download/v0.5.2/google-cas-issuer-v0.5.2.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: test-cm
  literals: 
  - annotationvalue=true
replacements:
- source:
    name: test-cm
    fieldPath: data.annotationvalue
  targets:
  - select: 
      kind: ServiceAccount
      name: ksa-google-cas-issuer
    fieldPaths:
    - metadata.annotations.test-annotation
    options:
      create: true

patches:
- path: patch.yaml
  target: 
    kind: ServiceAccount
  options:
    allowNameChange: true
```

and having patch.yaml as follows:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-google-cas-issuer
  annotations: 
    test-annotation: true
```

runs without errors and produces in its output a resource as follows:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    test-annotation: "true"
  name: ksa-google-cas-issuer
  namespace: cert-manager
```

which unless I'm mistaken seems to be what you are looking for. Please let me know if you have any other questions, or if somehow the docs could have been clearer in guiding you.

**Comment by Miles-Garnsey** [comment]
Thanks for the responses here @natasha41575, they are appreciated!

> The replacements docs specify that if a value doesn't exist, you can use the create option.

I can see that now you've explained it, apologies for missing it initially. I think the only suggestion I'd have is to explicitly call out that adding a field (if it doesn't exist) isn't the default behaviour. Normally a patch would add the field, so it left me scratching my head why a replacement wouldn't do the same.

> It also seems that you are trying to use the patch to change the name of the resource.

I'm not sure I understand this comment. I was attempting to follow the instructions [here](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#patch-using-inline-strategic-merge), which suggest that the target resource will be inferred by the name when `target` is not specified.

This is the original resource:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-google-cas-issuer
  namespace: cert-manager
```

The name is `ksa-google-cas-issuer`. Why would my patch (below) change the name of the resource? From my reading of the docs, it seems it should add the annotation?

```
patches:
- patch: |-
    kind: ServiceAccount
    metadata:
      name: ksa-google-cas-issuer
      annotations: 
        test-annotation: true
```

Thanks again, appreciate your explanations here.

**Comment by natasha41575** [comment]
>> It also seems that you are trying to use the patch to change the name of the resource.
> 
> I'm not sure I understand this comment. I was attempting to follow the instructions here, which suggest that the target resource will be inferred by the name when target is not specified.

Ah sorry my mistake, I'd misread the original file! You don't need the `allowNameChange` option, I was able to successfully run the command without any errors by changing my kustomization file to 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/jetstack/google-cas-issuer/releases/download/v0.5.2/google-cas-issuer-v0.5.2.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: test-cm
  literals: 
  - annotationvalue=true
replacements:
- source:
    name: test-cm
    fieldPath: data.annotationvalue
  targets:
  - select: 
      kind: ServiceAccount
      name: ksa-google-cas-issuer
    fieldPaths:
    - metadata.annotations.test-annotation
    options:
      create: true

patches:
- path: patch.yaml
  target: 
    kind: ServiceAccount
```

What I find interesting is that it seems to fail when there is an inline patch, but succeeds if the patch is defined in a separate yaml file. 

I've found that the following kustomization file works as well:

```
patches:
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ksa-google-cas-issuer
      namespace: cert-manager
      annotations: 
        test-annotation: true
```

I think there is a bug in kustomize when checking if a patch matches a target; an empty group/version/namespace should be treated as a wildcard and evidently that is not the case. I will take a deeper look.

/kind bug
/retitle inline SMP patch with empty group/version not matching inferred targets
