### ISSUE TITLE
`nameReference` cannot update the referred resources when target resource name is changed.

### ISSUE THREAD

**Issue by yuwenma** [kubernetes-sigs/kustomize#4274]
**Describe the bug**

I used nameReference to refer a HorizontalPodAutoscaler to a Deployment (like the example in the [source code](https://github.com/kubernetes-sigs/kustomize/blob/d4e3b4f8324c45486a58b6063081050f69fd9636/api/internal/accumulator/namereferencetransformer.go#L99)), and then change the deployment name via namePrefix. The referred field name in the HPA does not change.
 
**Files that can reproduce the issue**

resources.yaml
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-sample
spec:
  minReplicas: 1
  maxReplicas: 20
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 600
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: expect-to-change
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

namereference.yaml
```yaml
nameReference:
- kind: Deployment
  version: apps/v1
  fieldSpecs:
  - kind: HorizontalPodAutoscaler
    path: spec/scaleTargetRef/name
    create: true
```
kustomization.yaml
```yaml
resources:
- resources.yaml

configurations:
- namereference.yaml

namePrefix: yuwen-
```

Output of `kustomize build`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuwen-d-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: yuwen-hpa-sample
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 600
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      - periodSeconds: 15
        type: Pods
        value: 4
      selectPolicy: Max
      stabilizationWindowSeconds: 5
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # <b>I expect this name to be changed to yuwen-d-sample</b>
    name: expect-to-change
```

**Expected output**

HorizontalPodAutoscaler should have its `spec.scaleTargetRef.name` to be yuwen-d-sample

**Actual output**

HorizontalPodAutoscaler does not have `spec.scaleTargetRef.name` changed.

**Kustomize version**

v4.3.0 

**Platform**

macOS
