### ISSUE TITLE
configMapGenerator should allow behavior: append

### ISSUE THREAD

**Issue by Sokal21** [kubernetes-sigs/kustomize#4279]
**Describe the solution you'd like**

I'm currently configuring a monitoring tool for our kubernetes clusters. One of the features that we want to include is Heartbeat, a tool for checking services status.  I'm trying to generate a base config that each of our environment can modify a little to it's necessities.

Heartbeat is configured via a yaml file, one of those configurations is an array that includes different elastic search instances host. Each environment has different host names for each of this instances so I want to append to the configMap generation this configuration.

base/heartbeat/config/heartbeat.yml
```yaml
providers:
  - type: kubernetes
    resource: service
    scope: cluster
    node: ${NODE_NAME}
    hints.enabled: true
  - type: kubernetes
    resource: pod
    scope: cluster
    node: ${NODE_NAME}
    hints.enabled: true

processors:
  - add_kubernetes_metadata:

heartbeat.monitors:
  path: ${MONITORS_PATH}/*.yml
  # - type: browser
  #   id: service-status
  #   name: Service Status
  #   service.name: Payments
  #   hosts: ["https://api-test.letsbit.io/api/v1/lb/payments/public/health/alive"]
  #   check.response.status: [200]
  #   schedule: "@every 5s"

heartbeat.scheduler:
  limit: 10
```

base/kustomization.yaml

```yaml
configMapGenerator:
  - name: heartbeat-config
    options:
      labels:
        k8s-app: heartbeat
    files:
      - heartbeat/config/heartbeat.yml
```

test/heartbeat/config/heartbeat.yml
```yaml

output.elasticsearch:
  hosts: ["elasticsearch1:9200"]

```

test/kustomization.yaml

```yaml
configMapGenerator:
  - name: heartbeat-config
    behavior: merge
    files:
      - heartbeat/config/heartbeat.yml
```

current output

```yaml
apiVersion: v1
data:
  heartbeat.yml: |
    output.elasticsearch:
      hosts: ["elasticsearch1:9200"]
kind: ConfigMap
metadata:
  labels:
    k8s-app: heartbeat
    kustomize.generated.resource: "true"
  name: heartbeat-config
  namespace: efk
```

expected output

```yaml
apiVersion: v1
data:
  heartbeat.yml: |
    providers:
      - type: kubernetes
        resource: service
        scope: cluster
        node: ${NODE_NAME}
        hints.enabled: true
      - type: kubernetes
        resource: pod
        scope: cluster
        node: ${NODE_NAME}
        hints.enabled: true
    
    processors:
      - add_kubernetes_metadata:
    
    heartbeat.monitors:
      path: ${MONITORS_PATH}/*.yml
      # - type: browser
      #   id: service-status
      #   name: Service Status
      #   service.name: Payments
      #   hosts: ["https://api-test.letsbit.io/api/v1/lb/payments/public/health/alive"]
      #   check.response.status: [200]
      #   schedule: "@every 5s"
    
    heartbeat.scheduler:
      limit: 10
    output.elasticsearch:
      hosts: ["elasticsearch1:9200"]
kind: ConfigMap
metadata:
  labels:
    k8s-app: heartbeat
    kustomize.generated.resource: "true"
  name: heartbeat-config
  namespace: efk
```

It would be very nice if the behavior for non env files was just file append or an option like ```behavior: append```
