### ISSUE TITLE
[configMapGenerator] extra space in end of line gives "\n" instead of line breaks

### ISSUE THREAD

**Issue by marcusbgn** [kubernetes-sigs/kustomize#4287]
**Describe the bug**

When an extra space is at the end of the line in a reference file to a configMapGenerator it will create a single line string with "\n" instead of a multiline string.

**Files that can reproduce the issue**

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config_bla
    files:
      - cfg.text=cfg.text

```
cfg.text
```
bla
bla
bla 

```
_*!notice an extra space at the end of line 3*_

**Expected output**

```
apiVersion: v1
data:
  cfg.text: |
    bla
    bla
    bla
kind: ConfigMap
metadata:
  name: config_bla-4k548khbf5
```
**Actual output**

```
apiVersion: v1
data:
  cfg.text: "bla\nbla\nbla \n"
kind: ConfigMap
metadata:
  name: config_bla-d6m295b8c5
```
**Kustomize version**
{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:13:36Z GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

seems to be the same in when you create a config map from command line in kubernetes, `kubectl create configMap SOME_NAME --from-file=cfg.txt`
