### ISSUE TITLE
[Question] kustomize - disabling adding envFrom/configMapRef field

### ISSUE THREAD

**Issue by AnthonyWC** [kubernetes-sigs/kustomize#4289]
Is there a way to stop kustomize build from adding this field to my deployment?

```
envFrom:
- configMapRef:
  name: env
```

it only happens after i added op add with, e.g. (in patch.yaml):
```
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: foo
      valueFrom:
        secretKeyRef:
          name: foo
          key: bar
```
with
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage
bases:
  - ../base
patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: app1
    path: patch.yaml
```

pod would get error `Error: configmap "env" not found` and i have to comment out that section.. (i am not using ConfigMap but kubectl generic secret).  I also don't have any env file or configmap created.

Version:kustomize/v4.2.0
