### ISSUE TITLE
[Question] Can I apply `generatorOptions:` to `generators:` resources?

### ISSUE THREAD

**Issue by jason-matthew** [kubernetes-sigs/kustomize#4291]
I'm unsure if a question or issue is best here.  I'll assume I'm not properly reading doc and I simply need a push in the right direction. 

I chose to displace a `configMapGenerator` object from `kustomization.yaml` to a standalone resource.  Unfortunately, it appears doing so means I've lost `generatorOptions` functionality.  I can supply `options` within each standalone resource but I'm unsure how I can apply common set of labels or annotations for generated objects.

Is this expected?

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: learn
generatorOptions:
  annotations:
    generated: "true"
  disableNameSuffixHash: true
generators:
- configmap.generator.yaml
```

configmap.generator.yaml
```
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: app-generated-config
literals:
- FRUIT=apple
```

`kustomize build .` produces

```
apiVersion: v1
data:
  FRUIT: apple
kind: ConfigMap
metadata:
  name: app-generated-config-6m6d5ff9d6
  namespace: learn
```

Existing doc:
https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#usage-via-kustomizationyaml-1
https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#usage-via-generators-field

Behavior witnessed with:
```
{Version:kustomize/v3.10.0 GitCommit:602ad8aa98e2e17f6c9119e027a09757e63c8bec BuildDate:2021-02-10T00:00:50Z GoOs:darwin GoArch:amd64}
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:darwin GoArch:amd64}
```
