### ISSUE TITLE
ConfigMaps items are generated with random order

### ISSUE THREAD

**Issue by narg95** [kubernetes-sigs/kustomize#4292]
# Description

 `kustomize build .` produces configmap items in a random order and although it is somehow benign since it produces equivalent YAML files, it would be great if the build outputs are consistent and reproducible.

I tested it with kustomize v4.4.1

**Comment by natasha41575** [comment]
Would you mind providing a specific example with input, actual output, and expected output? This will help us write a test specifically targeted to the issue you're having.

To your point, however, we store the ConfigMap items in a Go map, which does not guarantee the order. What order are you expecting? We have two options if we want a deterministic order:

1. Alphabetical, which would be pretty simple to implement - just sort the keys before adding them to the ConfigMap data.
2. Preserve the input order. This will be a bigger change, we'd have to change the underlying data structure, and might have some consequences on performance - but then again so would option 1. 

I imagine users are expecting option 2.

**Comment by Shatakshi0805** [comment]
Hi, I would like to work on this. 
I'm currently a beginner so could you please guide me a little so that I can get started to solve this issue

**Comment by narg95** [comment]
Hi @natasha41575 and @natasha41575, thanks for your answers.

Option 1. with alphabetical order will work for me. I am keeping in source control the kustomize build output and the non-deterministic behavior is giving false positives of changes.

To reproduce the issue build multiple times the following kustomize file, and you will get different outputs which are equivalent but with different order.

kustomize.yaml
```yaml
configMapGenerator:
  - name: test
    literals:
      - EE10D2E63AF9F498=foo
      - FDC41072BFC0BC7F=foo
      - 32E0817AE855A845=foo
      - 0C6B462C403217C4=foo
      - 024233B4DFB484FC=foo
      - 6E7E3021F1821943=foo
      - DFD86A289C3857EF=foo
```

Outputs of running three times `kustomize build .` with the same file:

output 1
```yaml
apiVersion: v1
data:
  024233B4DFB484FC: foo
  0C6B462C403217C4: foo
  6E7E3021F1821943: foo
  32E0817AE855A845: foo
  DFD86A289C3857EF: foo
  EE10D2E63AF9F498: foo
  FDC41072BFC0BC7F: foo
kind: ConfigMap
metadata:
  name: test-7mt6kd57dt
 ```
 
 output 2
 ```yaml
 apiVersion: v1
data:
  6E7E3021F1821943: foo
  024233B4DFB484FC: foo
  0C6B462C403217C4: foo
  32E0817AE855A845: foo
  DFD86A289C3857EF: foo
  EE10D2E63AF9F498: foo
  FDC41072BFC0BC7F: foo
kind: ConfigMap
metadata:
  name: test-7mt6kd57dt
 ```
 
 output 3
```yaml
apiVersion: v1
data:
  6E7E3021F1821943: foo
  32E0817AE855A845: foo
  024233B4DFB484FC: foo
  0C6B462C403217C4: foo
  DFD86A289C3857EF: foo
  EE10D2E63AF9F498: foo
  FDC41072BFC0BC7F: foo
kind: ConfigMap
metadata:
  name: test-7mt6kd57dt
```

As you can see each output has different order of configmap items.
I tested it with kustomize `v4.4.1`
