### ISSUE TITLE
"Demo: multi namespaces with a common base" does not work

### ISSUE THREAD

**Issue by linkous8** [kubernetes-sigs/kustomize#4293]
**Describe the bug**

The instructions in the [Demo "multi namespaces with a common base"](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/multibases/multi-namespace.md) do not work. Following them produces blank output on kustomize build instead of producing expected manifests

**Files that can reproduce the issue**
prometheus_auth/base/kustomization.yaml:
```
 resources:
- prometheus-role.yaml
- prometheus-binding.yaml
```
prometheus_auth/base/prometheus-role.yaml:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servox-integration-prometheus
#   namespace: test-process
  labels:
    app: prometheus
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods",]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]

```
prometheus_auth/base/prometheus-binding.yaml:
```
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servox-integration-prometheus
  # namespace: test-process
  labels:
    app: prometheus
subjects:
- kind: ServiceAccount
  name: default
  # namespace: test-process
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servox-integration-prometheus
```
prometheus_auth/test-install-wait/kustomization.yaml
```
resources:
- ../base
namespace: test-install-wait
```
prometheus_auth/test-process/kustomization.yaml
```
resources:
- ../base
namespace: test-process
```
prometheus_auth/kustomization.yaml
```
resources:
- test-install-wait
- test-process
```

**Expected output**

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servox-integration-prometheus
  namespace: test-process
  labels:
    app: prometheus
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods",]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: servox-integration-prometheus
  namespace: test-install-wait
  labels:
    app: prometheus
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods",]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servox-integration-prometheus
  namespace: test-process
  labels:
    app: prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-process
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servox-integration-prometheus
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servox-integration-prometheus
  namespace: test-install-wait
  labels:
    app: prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-install-wait
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: servox-integration-prometheus

```

**Actual output**

` ` (blank, no output, same for both `kubectl kustomize` and `kustomize build`)

**Kustomize version**

kustomize: {Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}

kubectl: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

**Platform**

Linux 5.11.0-40-generic #44~20.04.2-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

I have a role and binding that I want to apply identically across a handful of namespaces. The only thing changing is the namespace, it would be nice if there were a `namespaces` field in kustomization.yaml that I could simply provide a list to
