### ISSUE TITLE
`helmGlobals` gets removed on kustomize edit

### ISSUE THREAD

**Issue by kevinawoo** [kubernetes-sigs/kustomize#4298]
**Describe the bug**

As of 2f115223c, if I have the `helmGlobals` in my `kustomization.yaml`, then run `kustomize edit set image app=repo/app:tag` the `helmGlobals` block gets removed when `kustomization.yaml` get rewritten.

**Files that can reproduce the issue**

`kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blah

# kustomize bug, helmGlobals gets removed for some reason when we do an `kustomize edit`
helmGlobals:
  chartHome: ../

helmCharts:
- name: helmchart
  valuesInline:
    envName: dev

images:
- name: app
  newName: repo/app
  newTag: oldTag
```

Then run 
```bash
kustomize edit set image app=repo/app:newTag
```

**Expected output**

I'd expect the `kustomization.yaml` to look like
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blah

# kustomize bug, helmGlobals gets removed for some reason when we do an `kustomize edit`
helmGlobals:
  chartHome: ../

helmCharts:
- name: helmchart
  valuesInline:
    envName: dev

images:
- name: app
  newName: repo/app
  newTag: newTag
```

**Actual output**

`kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomize bug, helmGlobals gets removed for some reason when we do an `kustomize edit`
namespace: blah

helmCharts:
- name: helmchart
  valuesInline:
    envName: dev

images:
- name: app
  newName: repo/app
  newTag: newTag
```

The errors are:
- `helmGlobals` block get remove
- `namespace` block joined with the `helmGlobals` comment

**Kustomize version**: 2f115223c

**Platform**: macOS
