### ISSUE TITLE
Using `helmCharts` doesn't work with charts that use `.Release` fields

### ISSUE THREAD

**Issue by anvouk** [kubernetes-sigs/kustomize#4303]
**What happened:**
Deploying `kustomization.yaml` with `helmCharts` doesn't set `.Release` properties.

This breaks some popular charts in a very hard to debug manner (for example, [bitnami kafka helm chart](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L3) which relies on `.Release.Namespace` for cluster connections).

**What you expected to happen:**
When launching `kubectl kustomize <FOLDER> --enable-helm`, `.Release` properties should have correct values and not default ones.

At least, provide a way to manually set them inside `kustomization.yaml`.

How to reproduce it (as minimally and precisely as possible):

1. Download, unzip and deploy with `kubectl kustomize test --enable-helm | kubectl apply -f -` the following example: [broken-example](https://github.com/kubernetes-sigs/kustomize/files/7579176/test.zip)
2. pod's has wrong `.Release.Namespace` and `.Release.Name` set:
```yaml
        env:
        - name: release-name
          value: RELEASE-NAME # <-- wrong. should be `test`
        - name: release-namespace
          value: default  # <-- wrong. should be `test`
```
**Anything else we need to know?:**
This issue has been previously open under kubectl: https://github.com/kubernetes/kubectl/issues/1151.

**Environment:**

- Kubernetes client and server versions (use kubectl version):
kubectl: `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`
helm: `version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}`
- Cloud provider or hardware configuration:
minikube version: `v1.24.0 commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b`
- OS (e.g: cat /etc/os-release):
`NAME="Ubuntu" VERSION="18.04.5 LTS (Bionic Beaver)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 18.04.5 LTS" VERSION_ID="18.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=bionic UBUNTU_CODENAME=bionic`

**Comment by stephen-dexda** [comment]
At least for the broken namespace value, explicitly setting `helmCharts.*namespace` worked around the issue for me (see https://github.com/kubernetes-sigs/kustomize/issues/3815).

I also had a problem with the release name being set to `release-name` for at least one of my charts, which was worked around by explicitly setting `helmCharts.*.releaseName`.

**Comment by brunocascio** [comment]
do we have any update on this?

**Comment by KnVerey** [comment]
Since Kustomize is not actually performing a Helm release as part of processing, we are using `helm template` under the hood (not for example `helm install`). Is there a `helm template` command that works with these charts?

> At least for the broken namespace value, explicitly setting helmCharts.*namespace worked around the issue for me (see https://github.com/kubernetes-sigs/kustomize/issues/3815).

> I also had a problem with the release name being set to release-name for at least one of my charts, which was worked around by explicitly setting helmCharts.*.releaseName.

This sounds very reasonable to me. Could this be considered a viable solution if we document it?

**Comment by brianpursley** [comment]
According to this:
https://github.com/kubernetes-sigs/kustomize/blob/71bf0d5d14552a137f43c37c80adcc9ceb937417/api/types/helmchartargs.go#L45-L56

it looks like you are supposed to be able to set `helmCharts.releaseName` and `helmCharts.namespace`, like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
helmCharts:
  - name: test
    releaseName: foo
    namespace: bar
```

However, doing this causes the `helm template` command to be constructed incorrectly, and I get this error:
```
Error: Error: expected at most two arguments, unexpected arguments: foo
: unable to run: 'helm template foo --namespace bar /home/bpursley/Downloads/test/charts/test --values /tmp/kustomize-helm-57038941/test-kustomize-values.yaml --release-name foo' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-57038941/helm HELM_CACHE_HOME=/tmp/kustomize-helm-57038941/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-57038941/helm/.data] (is 'helm' installed?)
```

It looks like Helm 3 had a breaking change where it moved the release name from an arg to a flag value
https://github.com/helm/helm/issues/6019

I think I can make a change to the code to get it working with Helm 3.

@KnVerey @natasha41575 Does Kustomize need to support both Helm 2 and Helm 3?

**Comment by brianpursley** [comment]
Actually, after looking at this again, I think it seems to be working fine.  I don't know why I got that error about two arguments before, but maybe I had made a change and forgot to back it out before running that.

@anvouk if you specify `releaseName` and `namespace` in your kustomization.yaml, like this, it should work:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
helmCharts:
  - name: test
    releaseName: foo
    namespace: bar
```

Output:
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      namespace: test
    spec:
      containers:
      - command:
        - sleep
        - infinity
        env:
        - name: release-name
          value: foo
        - name: release-namespace
          value: bar
        image: busybox
        name: test-container
```
