### ISSUE TITLE
[Question] lazy component transform after overlay transform

### ISSUE THREAD

**Issue by zmx** [kubernetes-sigs/kustomize#4306]
Currently Woking Solution we have 
- `base/config.env` has default value
- `overlays/hub-qa-1/config.env` has customize value for FQDN (and other config values) with ConfigMapGenerator
-  Each overlay has `replacements` transform to inject FQDN into alb-controller annotations

```
# This works
configMapGenerator:
- name: config
  behavior: merge
  envs:
  - config.env
replacements:
- source:
    kind: ConfigMap
    fieldPath: data.KN_ISOLATION_FQDN
  targets:
  - select:
      kind: Ingress
      name: janus-ingress
    fieldPaths:
      - spec.rules.0.host
      - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
```

Tried to move `replacements` into `components/ingress-alb/kustomizaiton.yaml`
 
```
├── base
|
├── components
│   └── ingress-alb
├── overlays
│   ├── hub-qa-1
│   ├── hub-qa-2
│   ├── hub-qa-3
│   ├── hub-qa-4
```

```
# This DON'T works
components:
- ../../components/ingress-alb

configMapGenerator:
- name: config
  behavior: merge
  envs:
  - config.env
```

Got this
`Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/.../components/ingress-alb': fieldPath `data.KN_ISOLATION_FQDN` is missing for replacement source ~G_~V_ConfigMap|~X|~N:data.KN_ISOLATION_FQDN`
