### ISSUE TITLE
yaml feature not support

### ISSUE THREAD

**Issue by pythonwood** [kubernetes-sigs/kustomize#4311]
**Files that can reproduce the issue**

version: 4.4.1

```
 resources:                                                                                                              
   - a.yaml
```

```
# a.yaml
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: a-ingress
spec:
  tls:
  - hosts:
      - "*.abc.com"
      - abc.com
    secretName: abc.com
  rules:
  - host: api1.abc.com
    http: &http
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc202111
            port:
              number: 2021
  # kustomize build . not support below , annote it with work
  - host: api2.abc.com
    http:
      <<: *http
```

however, kubectl apply -f a.yaml just ok

**Expected output**

**Actual output**

`error: map[string]interface {}{"apiVersion":"networking.k8s.io/v1", "kind":"Ingress", "metadata":map[string]interface {}{"name":"..... json: unsupported type: map[interface {}]interface {}`

**Kustomize version**

version: 4.4.1

**Platform**

**Additional context**
