### ISSUE TITLE
remote json patch

### ISSUE THREAD

**Issue by sgsh-gh** [kubernetes-sigs/kustomize#4315]
Now kustomize doesn’t have ability to reuse patch in the different repository. 

Support online/remote json patch. Since we can include remote manifest in the resource section, I guess it’s possible. 

I considered to use k8s’s crd and admission webhook but since user like me doesn’t have cluster level right, this feature is helpful

**Comment by KnVerey** [comment]
Patches can already be loaded from git, as demonstrated in this example: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/loadHttp/kustomization.yaml#L6-L7

If that isn't working for you, please reopen with detailed reproduction steps.

/close

**Comment by khusseini** [comment]
I am not sure if I should open a new issue, however this is related.
I have the following repository where I pull my layers from: https://github.com/diePartments/pimcore-k8s

So in my local kustomization I am using this as a base:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  # frontend deployment.
  - releaseName: pimcore-frontend
    name: pimcore-deployment
    repo: https://raw.githubusercontent.com/diePartments/pimcore-k8s/main/base/charts
    valuesInline:
      fullname: pimcore-frontend
      labels:
        tier: frontend
        role: web
        app: pimcore
        lang: php
      pimcore:
        selectorLabels:
          tier: frontend
          role: web
          app: pimcore
          lang: php
        php:
          command:
            - /bin/bash
          args:
            - -c
            - /var/www/bin/console cache:warmup & php-fpm -F

  # messenger deployments.
  - releaseName: messenger-async
    name: pimcore-deployment
    repo: https://raw.githubusercontent.com/diePartments/pimcore-k8s/main/base/charts
    valuesInline:
      labels:
        tier: messenger
        app: pimcore
        role: async-worker
        lang: php
      fullname: messenger-async
      pimcore:
        selectorLabels:
          tier: messenger
          app: pimcore
          role: async-worker
          lang: php
        nginx:
          enabled: false
        php:
          probe: false
          command:
            - /bin/bash
            - -c
            - /var/www/bin/bin/console messenger:consume async -vv

resources:
  - https://github.com/diePartments/pimcore-k8s/base
  
```

and this is my overlay:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - https://github.com/diePartments/pimcore-k8s/overlay/persistence
  - https://github.com/diePartments/pimcore-k8s/overlay/initialization

```

When I bulid the resources, the patches which are defined in https://github.com/diePartments/pimcore-k8s/blob/main/overlay/initialization/kustomization.yaml are not applied to my resources, however resources defined in the remote repository are created (such as services, PVCs etc).

I tried adding the base in https://github.com/diePartments/pimcore-k8s/blob/main/overlay/initialization/kustomization.yaml and it works on its own, however I need to be able to mix and match the layers depending on my environment.

@KnVerey suggested to reference the patches directly, however that would mean I have to add each patch manually, which I was trying to avoid. 

Are patches on remote resources not applied during `kustomize build`?
