### ISSUE TITLE
kustomize fn run doesn't output a resourcelist even when filters do return a resourcelist

### ISSUE THREAD

**Issue by Goodwine** [kubernetes-sigs/kustomize#4321]
**Describe the bug**

`ResourceListProcessor` changed to allow a KRM function to return a `ResourceList` with `.Results`.
When running `kustomize fn run` on a non-resourcelist it will unwrap the resources which means `Results` will be lost.

I attempted a workaround is using a resourcelist as input to begin with but kustomize still seems to drop the results

Running the KRM function directly with `cat local-resource/example-use.yaml | docker run -i --rm gcr.io/kustomize-functions/example-resourcelist-results:v0.1.0` does yield the expected result

**Files that can reproduce the issue**

PR with example: https://github.com/kubernetes-sigs/kustomize/pull/4320

```sh
kustomize fn run local-resource/ --dry-run
```

**Expected output**

```yaml
apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
- apiVersion: examples.config.kubernetes.io/v1beta1
  kind: Validator
  metadata:
    annotations:
      config.kubernetes.io/function: |
        container:
          image: gcr.io/kustomize-functions/example-resourcelist-results:v0.1.0
- # This Deployment creates a "Result" because it has no image tag version
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-unversioned
    labels:
      app: nginx-unversioned
  spec:
    selector:
      matchLabels:
        app: nginx-unversioned
    template:
      metadata:
        labels:
          app: nginx-unversioned
      spec:
        containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 100m
              memory: 300MiB
- # This Deployment is ok because it has a version
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-versioned
    labels:
      app: nginx-versioned
  spec:
    selector:
      matchLabels:
        app: nginx-versioned
    template:
      metadata:
        labels:
          app: nginx-versioned
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              cpu: 100m
              memory: 300MiB
- # Only Deployments are considered in _this_ case, so Pods are ignored.
  apiVersion: v1
  kind: Pod
  metadata:
    name: nginx-pod
    labels:
      app: nginx-pod
  spec:
    containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 100m
          memory: 300MiB
results:
- message: missing image version
  severity: error
  resourceRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-unversioned
  field:
    path: spec.template.spec.containers[0].image
    currentValue: nginx
    proposedValue: nginx:<VERSION>
  file:
    index: 1
```

**Actual output**

(with raw resources as input)

```yaml
# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0
apiVersion: examples.config.kubernetes.io/v1beta1
kind: Validator
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kustomize-functions/example-resourcelist-results:v0.1.0
    config.kubernetes.io/path: 'example-use.yaml'
    internal.config.kubernetes.io/path: 'example-use.yaml'
---
# This Deployment creates a "Result" because it has no image tag version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-unversioned
  labels:
    app: nginx-unversioned
  annotations:
    config.kubernetes.io/path: 'example-use.yaml'
    internal.config.kubernetes.io/path: 'example-use.yaml'
spec:
  selector:
    matchLabels:
      app: nginx-unversioned
  template:
    metadata:
      labels:
        app: nginx-unversioned
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 100m
            memory: 300MiB
---
# This Deployment is ok because it has a version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-versioned
  labels:
    app: nginx-versioned
  annotations:
    config.kubernetes.io/path: 'example-use.yaml'
    internal.config.kubernetes.io/path: 'example-use.yaml'
spec:
  selector:
    matchLabels:
      app: nginx-versioned
  template:
    metadata:
      labels:
        app: nginx-versioned
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            cpu: 100m
            memory: 300MiB
---
# Only Deployments are considered in _this_ case, so Pods are ignored.
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
  annotations:
    config.kubernetes.io/path: 'example-use.yaml'
    internal.config.kubernetes.io/path: 'example-use.yaml'
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 300MiB
```

(with resourcelist as input, still no "results")

```yaml
apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
- apiVersion: examples.config.kubernetes.io/v1beta1
  kind: Validator
  metadata:
    annotations:
      config.kubernetes.io/function: |
        container:
          image: gcr.io/kustomize-functions/example-resourcelist-results:v0.1.0
- # This Deployment creates a "Result" because it has no image tag version
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-unversioned
    labels:
      app: nginx-unversioned
  spec:
    selector:
      matchLabels:
        app: nginx-unversioned
    template:
      metadata:
        labels:
          app: nginx-unversioned
      spec:
        containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: 100m
              memory: 300MiB
- # This Deployment is ok because it has a version
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-versioned
    labels:
      app: nginx-versioned
  spec:
    selector:
      matchLabels:
        app: nginx-versioned
    template:
      metadata:
        labels:
          app: nginx-versioned
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              cpu: 100m
              memory: 300MiB
- # Only Deployments are considered in _this_ case, so Pods are ignored.
  apiVersion: v1
  kind: Pod
  metadata:
    name: nginx-pod
    labels:
      app: nginx-pod
  spec:
    containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 100m
          memory: 300MiB
metadata:
  annotations:
    config.kubernetes.io/path: 'example-use.yaml'
    internal.config.kubernetes.io/path: 'example-use.yaml'

```

**Kustomize version**

`{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}`

**Platform**

macOS

**Additional context**
