### ISSUE TITLE
Image Tag Suffix with Images Transformer

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [kubernetes-sigs/kustomize#4322]
**Describe the solution you'd like**
Add the ability of setting a suffix on image tags using the images transformer.

**Describe alternatives you've considered**
Right now, if you have an image version on a K8s resource and you want to use a variant of that image with the same version, you have to overwrite the entire tag and keep track of the base tag used. This is specially painful if you are patching 3rd-party resources and you just want to change the image to another variant.

**Additional context**
Current solution:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
images:
  - name: redis
    newTag: 6.2.6-alpine
```

With this new feature:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
images:
  - name: redis
    tagSuffix: -alpine
```
