### ISSUE TITLE
Incorrect reference name in Deployments patched by Components if an intermediate layer is used

### ISSUE THREAD

**Issue by lixin9311** [kubernetes-sigs/kustomize#4330]
**Describe the bug**
My file structure:
```text
├── base
│   ├── deployment.yaml
│   └── kustomization.yaml
├── components
│   └── common
│       ├── configmap.yaml
│       ├── config.yaml
│       ├── kustomization.yaml
│       └── patch.yaml
├── dev
│   └── kustomization.yaml
└── prod
    ├── base
    │   └── kustomization.yaml    # an intermediate layer, which imports ../../base
    └── canary
        └── kustomization.yaml    # import ../base and components/common, then append suffix etc.
```

When I build `prod/canary`, it will append suffixes and try to import `prod/base` as an intermediate layer, which will import `base` as resources.
It will also use the `components/common` to add an extra ConfigMap, patch the Deployment to mount ConfigMap.
The produced ConfigMap is correctly patched with the given suffix. But the patched Volumes are still referencing the original names.

However, `dev` which directly import `base`, will produce a correct output.

**Files that can reproduce the issue**
I've also uploaded to https://github.com/lixin9311/kustomize-issue-poc
```yaml
# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
        - name: example
          image: example:1.0
          volumeMounts:
            - name: conf
              mountPath: /etc/config
      volumes:
        - name: conf
          configMap:
            name: conf
```

```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
```

```yaml
# components/common/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: config
    files:
      - config.yaml

# I just tried different resources, and they all failed.
# resources:
#   - configmap.yaml

# secretGenerator:
#   - name: secret
#     files:
#       - config.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
    path: patch.yaml

```

```yaml
# components/common/config.yaml
foo: bar
```

```yaml
# components/common/patch.yaml
- op: replace
  path: /spec/template/spec/volumes/0
  value:
    name: config
    configMap:
      name: config
- op: replace
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    mountPath: /etc/config
    name: config
    readOnly: true
```

```yaml
# dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: dev
commonLabels:
  version: nightly
nameSuffix: -nightly
components:
  - ../components/common
```

```yaml
# prod/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
```

```yaml
# prod/canary/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
commonLabels:
  version: canary
nameSuffix: -canary
components:
  - ../../components/common
```

**Expected output**

```text
$ kustomize build dev
```
It will produce the correct output.

**Actual output**

```yaml
# $ kustomize build prod/canary
apiVersion: v1
data:
  config.yaml: |
    foo: bar
kind: ConfigMap
metadata:
  labels:
    version: canary
  name: config-canary                                    # resource names are patched correctly
---
apiVersion: v1
data:
  config.yaml: |
    foo: bar
kind: ConfigMap
metadata:
  labels:
    version: canary
  name: configmap-canary
---
apiVersion: v1
data:
  config.yaml: Zm9vOiBiYXIK
kind: Secret
metadata:
  labels:
    version: canary
  name: secret-canary
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: canary
  name: example-canary
  namespace: prod
spec:
  selector:
    matchLabels:
      version: canary
  template:
    metadata:
      labels:
        version: canary
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
        - mountPath: /etc/secret
          name: secret
          readOnly: true
        - mountPath: /etc/configmap
          name: configmap
          readOnly: true
      volumes:
      - configMap:
          name: config
        name: config
      - name: secret
        secret:
          secretName: secret
      - configMap:
          name: configmap                                    # reference names are wrong
        name: configmap
```

**Kustomize version**

```
kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 linux/amd64 and later
also tried on macOS
```

**Platform**

linux/amd64
macos/arm64
macos/amd64

**Additional context**
