### ISSUE TITLE
Unable to replace variables in deployment's env definition

### ISSUE THREAD

**Issue by itsnagaraj** [kubernetes-sigs/kustomize#4337]
I have the following deployment manifest

```
cat <<EOF >$DEMO_HOME/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: myapp-container
        image: busybox:1.29.0
EOF
```

I have a patch file with following contents

```
cat <<EOF >$DEMO_HOME/env-java-opts.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
        - name: myapp-container
          env:
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: $(ENVIRONMENT_SECRET_PREFIX)-app-external-secret
                key: app_secret

EOF
```

external secret with following contents

```
cat <<EOF >$DEMO_HOME/app-secrets.yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: $(ENVIRONMENT_SECRET_PREFIX)-app-external-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: $(ENVIRONMENT_SECRET_PREFIX)/app
      name: app_secret
      property: app_secret
EOF
```

kustomization file with following contents

```
cat <<EOF >$DEMO_HOME/kustomization.yaml
configMapGenerator:
  - name: app-vars
    literals:
      - ENVIRONMENT_SECRET_PREFIX="nonprod"

vars:
  - name: ENVIRONMENT_SECRET_PREFIX
    objref:
      kind: ConfigMap
      name: platform-services-address-vars
      apiVersion: v1
    fieldref:
      fieldpath: data.ENVIRONMENT_SECRET_PREFIX

resources:
  - deployment.yaml
  - app-secrets.yaml

patchesStrategicMerge:
  - env-java-opts.yaml

EOF
```

On running `kustomize build` the variable are not replaced.

```
apiVersion: v1
data:
  ENVIRONMENT_SECRET_PREFIX: nonprod
kind: ConfigMap
metadata:
  name: app-vars-ff7mhhf9cg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              key: app_secret
              name: $(ENVIRONMENT_SECRET_PREFIX)-app-external-secret
        image: busybox:1.29.0
        name: myapp-container
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: $(ENVIRONMENT_SECRET_PREFIX)-app-external-secret
secretDescriptor:
  backendType: secretsManager
  data:
  - key: $(ENVIRONMENT_SECRET_PREFIX)/app
    name: app_secret
    property: app_secret
```

Is this expected? Or are there other ways to solve this?

**Comment by natasha41575** [comment]
We are expecting to deprecate and remove vars, I would encourage you to use `replacements` instead. Please see the documentation: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/

For your case, to replace the variable in your secret, you would need something like:

app-secrets.yaml
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: ENVIRONMENT_SECRET_PREFIX/app
      name: app_secret
      property: app_secret
```

kustomization.yaml
```
configMapGenerator:
  - name: app-vars
    literals:
      - ENVIRONMENT_SECRET_PREFIX="nonprod"
generatorOptions:
  disableNameSuffixHash: true

resources:
  - app-secrets.yaml

replacements:
- source: 
      kind: ConfigMap
      name: app-vars
      fieldPath: data.ENVIRONMENT_SECRET_PREFIX
  targets:
  - select:
      name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
      kind: ExternalSecret
    fieldPaths: 
    - secretDescriptor.data.[name=app_secret].key
    options:
      delimiter: '/'
      index: 0
  - select:
      name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
      kind: ExternalSecret
    options:
      delimiter: '-'
      index: 0
```

**Comment by itsnagaraj** [comment]
> We are expecting to deprecate and remove vars, I would encourage you to use `replacements` instead. Please see the documentation: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/
> 
> For your case, to replace the variable in your secret, you would need something like:
> 
> app-secrets.yaml
> 
> ```
> apiVersion: 'kubernetes-client.io/v1'
> kind: ExternalSecret
> metadata:
>   name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
> secretDescriptor:
>   backendType: secretsManager
>   data:
>     - key: ENVIRONMENT_SECRET_PREFIX/app
>       name: app_secret
>       property: app_secret
> ```
> 
> kustomization.yaml
> 
> ```
> configMapGenerator:
>   - name: app-vars
>     literals:
>       - ENVIRONMENT_SECRET_PREFIX="nonprod"
> 
> resources:
>   - app-secrets.yaml
> 
> replacements:
> - source: 
>     kind: ConfigMap
>     name: app-vars
>     fieldPath: data.ENVIRONMENT_SECRET_PREFIX
>   targets:
>   - select:
>       name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
>       kind: ExternalSecret
>     fieldPaths: 
>     - secretDescriptor.data.[name=app_secret].key
>     options:
>       delimiter: '/'
>       index: 0
>   - select:
>       name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
>       kind: ExternalSecret
>     options:
>       delimiter: '-'
>       index: 0
> ```
> 
> Running `kustomize build` with the above files will give you the following output, with your variables replaced:
> 
> ```
> apiVersion: v1
> data:
>   ENVIRONMENT_SECRET_PREFIX: nonprod
> kind: ConfigMap
> metadata:
>   name: app-vars-ff7mhhf9cg
> ---
> apiVersion: kubernetes-client.io/v1
> kind: ExternalSecret
> metadata:
>   name: nonprod-app-external-secret
> secretDescriptor:
>   backendType: secretsManager
>   data:
>   - key: nonprod/app
>     name: app_secret
>     property: app_secret
> ```

If there multiple keys would we have to repeat the replacements multiple times for each key. Could we do it in one go?

**Comment by natasha41575** [comment]
> If there multiple keys would we have to repeat the replacements multiple times for each key. Could we do it in one go?

You can provide multiple fieldpaths for a single target, e.g.

```
replacements:
- source: 
    kind: ConfigMap
    name: app-vars
    fieldPath: data.ENVIRONMENT_SECRET_PREFIX
  targets:
  - select:
      name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
      kind: ExternalSecret
    fieldPaths: 
    - secretDescriptor.data.[name=app_secret_1].key
    - secretDescriptor.data.[name=app_secret_2].key
    options:
      delimiter: '/'
      index: 0
```

Does that answer your question?

**Comment by itsnagaraj** [comment]
> > If there multiple keys would we have to repeat the replacements multiple times for each key. Could we do it in one go?
> 
> You can provide multiple fieldpaths for a single target, e.g.
> 
> ```
> replacements:
> - source: 
>     kind: ConfigMap
>     name: app-vars
>     fieldPath: data.ENVIRONMENT_SECRET_PREFIX
>   targets:
>   - select:
>       name: ENVIRONMENT_SECRET_PREFIX-app-external-secret
>       kind: ExternalSecret
>     fieldPaths: 
>     - secretDescriptor.data.[name=app_secret_1].key
>     - secretDescriptor.data.[name=app_secret_2].key
>     options:
>       delimiter: '/'
>       index: 0
> ```
> 
> Does that answer your question?

Yes. I will give it a go thanks

**Comment by itsnagaraj** [comment]
All the above suggestions and examples worked @natasha41575 and thank you so much for the assistance. 

Is it possible to replace multiple variables in a line using `replacements` or should I continue using `variables` for the scenario below?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
            - name: JAVA_OPTS
              value: -Dspring.profiles.active=$(SPRING_PROFILE) -Dnewrelic.environment=$(NEWRELIC_ENVIRONMENT_NAME) -Dnewrelic.config.app_name=$(NEWRELIC_ENVIRONMENT_NAME)-myapp

```
