### ISSUE TITLE
KRM Exec Function can't locate executable when referencing a base

### ISSUE THREAD

**Issue by pmcjury** [kubernetes-sigs/kustomize#4347]
**Describe the bug**

When using a KRM exec function with a relative path to the _kustomization.yaml_ file, the executable can't be found when referencing a _base_ from a _variant_. 

It appears the function is "exec"-d relative to the base not the variant. 

Things are further complicated when the _base_ references another _remote base_. 

**Files that can reproduce the issue**

``` 

# dir
.
├── base
│   ├── deployment.yaml
│   └── kustomization.yaml
└── krm-exec
    ├── krm-config.yaml
    ├── kustomization.yaml
    └── plugins
        └── function.sh
```

```yaml

# base/kustomization.yaml

resources:
 - deployment.yaml

```

```yaml
# base/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: busybox
        image: busybox:v1.0.0
```

```yaml

#krm-exec/kustomization.yaml
resources:
- ../base
transformers:
- krm-config.yaml
```

```yaml

#krm-exec/krm-config.yaml
apiVersion: my.example.io/v1
kind: MyPlugin
metadata:
  name: notImportantHere
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: ./plugins/function.sh
```

```sh
#krm-exec/plugins/function.sh
#!/bin/bash
resourceList=$(cat) 
# dummy
echo "$resourceList"
```

**Expected output**

The dummy function should just echo out the resources read from stdin. 

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        any: thing
    spec:
      containers:
      - name: busybox
        image: busybox:v1.0.0
     
```

**Actual output**

```sh
#from krm-exec dir
kustomize build --enable-alpha-plugins --enable-exec  .
Error: couldn't execute function: fork/exec ./plugins/function.sh: no such file or directory

```

**Kustomize version**

```sh
kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:darwin GoArch:amd64}

```

**Platform**

macOS ( M1 )
darwin21.0
arm64

**Additional context**

**Some other scenarios:**

- The plugin works as expected when the variant kustomization does not reference the base, but a relative deployment.
```
#krm-exec/kustomizaiton.yaml
resources:
- deployment.yaml
```

- With the original setup If I move the `./plugins/function.sh` to the _base_, the plugin works even if the krm-function.yaml is located in the variant

To further complicate things, if I add a remote base to the local base I get this error:

```yaml
#base/kustomization.yaml
resources:
 - https://github.com/pmcjury/somerepo/manifests/base?ref=main
 - deployment.yaml
```

```
#from krm-exec dir
kustomize build --enable-alpha-plugins --enable-exec  .
Error: couldn't execute function: chdir /private/var/folders/yn/88ww9kqx1b35xylvc0wt0fb80000gn/T/kustomize-124974724/deploy/manifests/base: no such file or directory 
```
