### ISSUE TITLE
Exec KRM functions with relative paths don't resolve when base kustomization is in use

### ISSUE THREAD

**Issue by seh** [kubernetes-sigs/kustomize#4350]
# Description

Following up from #4117, while #4125 made it possible to use relative paths to specify the location of an exec KRM function, that resolution only works correctly when the _kustomization_ containing the KRM function does not use any [bases](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#base), and instead includes only [resources](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#resource)—specifically, references to files below that [_kustomization root_](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#kustomization-root).

The following _kustomization.yaml_ files demonstrate the possibilities:

## No resources
Relative KRN function paths work as expected.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
```
## Only resources
Relative KRN function paths work as expected.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pdb.yaml
```
## Only bases
Relative KRN function paths **do not** work as expected.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
```
## Bases and resources
Relative KRN function paths **do not** work as expected.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa.yaml
```

# Reproduction

Please consult the archive of a base _kustomization_ and an overlay _kustomization_, where the overlay includes a KRM function.

[kustomize-fn-defect.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/7758756/kustomize-fn-defect.tar.gz)

## Preparation
```shell
mkdir -p /tmp/kustomize-demo
cd /tmp/kustomize-demo
tar zxf ~/Downloads/kustomize-fn-defect.tar.gz
kustomize build ./overlays/fn --enable-exec --enable-alpha-plugins
```

## Expected Output
```yaml
apiVersion: v1
data:
  color: red
kind: ConfigMap
metadata:
  name: settings
```

## Actual Output
```
Error: couldn't execute function: fork/exec ./plugins/change-color: no such file or directory 
```

# Environment

## Kustomize Version

`{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}`

## Platform

macOS 11.6 (Darwin Kernel Version 20.6.0)

# Additional Context

If you change the "exec.path" field (embedded in the "config.kubernetes.io/function" annotation) in the _krm-functions.yaml_ file to the absolute path to the _change-color_ program (e.g. _/tmp/kustomize-demo/overlays/fn/plugins/change-color_), then _kustomize build_ works as expected. Likewise, if you use a relative path to the _change-color_ file and comment out the resource _../../base_ in the overlay _kustomization.yaml_ file and instead include the _ConfigMap_ content in a file within the overlay's directory (effectively changing the overlay into a base), then _kustomize build_ works as expected.
