### ISSUE TITLE
Unexpected behavior and output when using configMapGenerator with helmCharts or helmChartInflationGenerator  

### ISSUE THREAD

**Issue by armenr** [kubernetes-sigs/kustomize#4354]
**Describe the bug**

Using configMapGenerator appears to produce errors with both helmCharts & helmChartInflationGenerator...possibly caused by a race condition?

**Files that can reproduce the issue**

**Note:** I keep the argo-cd helm chart from bitnami in a folder called `synced/helm-chart`

tree looks like this:

```
❯ tree argo-cd -L 3
argo-cd
├── kustomization.yaml
├── patches
│   ├── cmp-plugin.yaml
│   ├── extension-rollouts.yaml
│   └── traefik-middleware.yaml
├── synced
│   ├── extension-ui-rollouts
│   │   └── manifests
│   └── helm-chart
│       ├── Chart.lock
│       ├── Chart.yaml
│       ├── README.md
│       ├── charts
│       ├── crds
│       ├── templates
│       └── values.yaml
└── values.yaml
```

**NOTE:** In all cases listed below, I use the following command to build my manifests `kustomize build --enable-helm .`

**Permutation 1** - configMapGenerator + helmChartInflationGenerator
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmChartInflationGenerator:
  - chartName: helm-chart
    chartHome: synced
    values: values.yaml
    releaseName: argo-cd
    extraArgs:
    - --include-crds
resources:
  - patches/traefik-middleware.yaml
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    namespace: argocd
    literals:
      - timeout.reconciliation=15s
      - kustomize.buildOptions=--load-restrictor LoadRestrictionsNone --enable-helm
```

**Error:** merging from generator &{0x14000a0ad20 {  map[] map[]} {{argocd argocd-cm merge {[timeout.reconciliation=15s kustomize.buildOptions=--load-restrictor LoadRestrictionsNone --enable-helm] [] [] } <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"argocd-cm", Namespace:"argocd"} does not exist; cannot merge or replace

**Permutation 2: configMapGenerator + helmCharts**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmGlobals:
  chartHome: synced/
helmCharts:
- name: helm-chart
  releaseName: argo-cd
  namespace: argocd
  includeCRDs: true
  valuesFile: values.yaml
resources:
  - patches/traefik-middleware.yaml
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    namespace: argocd
    literals:
      - timeout.reconciliation=15s
      - kustomize.buildOptions=--load-restrictor LoadRestrictionsNone --enable-helm
```

**Error:** merging from generator &{0x140009e06f0 {  map[] map[]} {{argocd argocd-cm merge {[timeout.reconciliation=15s kustomize.buildOptions=--load-restrictor LoadRestrictionsNone --enable-helm] [] [] } <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"argocd-cm", Namespace:"argocd"} does not exist; cannot merge or replace

### Workarounds I tried

Workaround Try 1 - inline Patch + helmCharts (doesn't work)

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: synced/

helmCharts:
- name: helm-chart
  releaseName: argo-cd
  namespace: argocd
  includeCRDs: true
  valuesFile: values.yaml

resources:
  - patches/traefik-middleware.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
        labels:
          app.kubernetes.io/managed-by: BLEEGS
      namespace: argocd
      data:
        timeout.reconciliation: 15s
        kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
```

**Error:** no matches for Id ~G_v1_ConfigMap|~X|argocd-cm; failed to find unique target for patch ~G_v1_ConfigMap|argocd-cm

### Workaround that WORKS

**Permutation - inline Patch + helmChartInflationGenerator**

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmChartInflationGenerator:
  - chartName: helm-chart
    chartHome: synced
    values: values.yaml
    releaseName: argo-cd
    extraArgs:
    - --include-crds
resources:
  - patches/cmp-plugin.yaml
  - patches/traefik-middleware.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
        labels:
          app.kubernetes.io/managed-by: BLEEGS
      namespace: argocd
      data:
        timeout.reconciliation: 15s
        kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
```

**OUTPUT (correct):**

```yaml
---
apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: ""
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
  timeout.reconciliation: 15s
  url: ""
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: BLEEGS
    app.kubernetes.io/name: argo-cd
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-2.0.19
  name: argocd-cm
  namespace: argocd
namespace: argocd
---
```

-->

**Kustomize version**

❯ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:arm64}

**Platform**

MacBook Pro 16", 2021 --> M1 Pro + MacOS 12.0.1 (21A559)

**Comment by armenr** [comment]
## UPDATE

Among other learnings, I've found that you should pass `namespace` to helm, and NOT include `namespace: argocd` as a top-level key/value pair in the `kustomization.yaml` for argo-cd

If this is all expected behavior, please feel free to very candidly let me know that I'm stupid, and this is *intended* behavior. IF so, I'll be happy to contribute a PR to maybe help make the documentation a bit more explicit/detailed.

## This appears to work

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: argocd

helmGlobals:
  chartHome: synced/

helmCharts:
- name: helm-chart
  releaseName: argo-cd
  includeCRDs: true
  valuesFile: values.yaml
  namespace: argocd

# !!! NOTE: Always use separate f*ing generators for configMaps + HELM
# !!!       REMEMBER THIS FACT!

generators:
  - generators/configmap-argocd-cm.yaml

resources:
  - patches/traefik-middleware.yaml
  - patches/config-map-tls.yaml
  - patches/cm-cmp-plugin.yaml
```

**generators/configmap-argocd-cm.yaml**
```yaml
apiVersion: builtin
kind: ConfigMapGenerator
behavior: merge
metadata:
  name: argocd-cm
  namespace: argocd
literals:
  - "timeout.reconciliation=15s"
  - "kustomize.buildOptions=--load-restrictor LoadRestrictionsNone --enable-helm"
```
