### ISSUE TITLE
[Question] How to replace text in a ConfigMap using replacements instead of vars?

### ISSUE THREAD

**Issue by NickLarsenNZ** [kubernetes-sigs/kustomize#4359]
I recall being able to replace var references in ConfigMaps through configs like so:

**kustomization.yml**

```yml
secretGenerator:
- name: argocd-oidc # will get a hashed suffix so that pods reload when changed
  literals:
  - auth0.clientSecret=secret

configMapGenerator:
- name: argocd-cm
  files:
  - oidc.config=oidc.config.yml

configurations:
- konfig.yml

vars:
- name: KUSTOMIZE_OIDC_SECRET_NAME
  objref:
    kind: Secret
    name: argocd-oidc
    apiVersion: v1
```

**konfig.yml**

```yml
# Specify which resources and keys might contain a variable to interpolate
varReference:
- kind: ConfigMap
  path: data
```

**oidc.config.yml** (as far as Kustomize is concerned, it is plain text)

```txt
name: Auth0
issuer: https://me.auth0.com/
clientID: ...
clientSecret: $$(KUSTOMIZE_OIDC_SECRET_NAME):auth0.clientSecret # Note the first dollar sign is part of the ArgoCD config to signify a Secret name. Not part of kustomize replacement
requestedScopes:
- openid
- profile
- email
```

This doesn't seem to work anymore, and seeing that `vars` is being deprecated, I'm wondering how I can replace text inside a ConfigMap?

For now I guess I'll see if I can find a way to specify the `clientSecret` through an env var, but I'm really at the mercy of the app here.
