### ISSUE TITLE
`namespace` Transformer  Does Not Update Namespace in `nginx.ingress.kubernetes.io/auth-tls-secret`

### ISSUE THREAD

**Issue by GuyPaddock** [kubernetes-sigs/kustomize#4365]
**Describe the bug**
#1302 added support for Kustomize to update secret names referenced by `nginx.ingress.kubernetes.io/auth-tls-secret` annotations when those names are affected by prefix/suffix transformers, but it does not appear that the `namespace` transformer is able to update these annotations.

**Files that can reproduce the issue**
### `ingress.yaml`
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: some-ingress
  namespace: default
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "default/some-ca-cert"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "my.host"
      secretName: my-tls-certificate
  rules:
    - host: "my.host"
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: some-internal-service
                port:
                  number: 8080
```

### `secrets.yaml`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: "some-ca-cert"
  namespace: "default"
type: Opaque
data:
  ca.crt: "--Some ca.crt--"
```

### `kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - secrets.yaml

namespace: bug-repro
namePrefix: some-prefix-
``` 

**Expected output**
```yaml
apiVersion: v1
data:
  ca.crt: --Some ca.crt--
kind: Secret
metadata:
  name: some-prefix-some-ca-cert
  namespace: bug-repro
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/auth-tls-secret: bug-repro/some-prefix-some-ca-cert
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: some-prefix-some-ingress
  namespace: bug-repro
spec:
  ingressClassName: nginx
  rules:
  - host: my.host
    http:
      paths:
      - backend:
          service:
            name: some-internal-service
            port:
              number: 8080
        path: /
        pathType: Exact
  tls:
  - hosts:
    - my.host
    secretName: my-tls-certificate
```

**Actual output**
```yaml
apiVersion: v1
data:
  ca.crt: --Some ca.crt--
kind: Secret
metadata:
  name: some-prefix-some-ca-cert
  namespace: bug-repro
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/auth-tls-secret: default/some-ca-cert
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: some-prefix-some-ingress
  namespace: bug-repro
spec:
  ingressClassName: nginx
  rules:
  - host: my.host
    http:
      paths:
      - backend:
          service:
            name: some-internal-service
            port:
              number: 8080
        path: /
        pathType: Exact
  tls:
  - hosts:
    - my.host
    secretName: my-tls-certificate
```

**Kustomize version**
```
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}
```

**Platform**
* WSL 2
* Ubuntu 20.04.3 LTS
* `5.4.91-microsoft-standard-WSL2 #1 SMP Mon Jan 25 18:39:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
If `ingress.yaml` is changed to the following:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: some-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "some-ca-cert"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "my.host"
      secretName: my-tls-certificate
  rules:
    - host: "my.host"
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: some-internal-service
                port:
                  number: 8080
```

Then the output becomes the following:
```yaml
apiVersion: v1
data:
  ca.crt: --Some ca.crt--
kind: Secret
metadata:
  name: some-prefix-some-ca-cert
  namespace: bug-repro
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/auth-tls-secret: some-prefix-some-ca-cert
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: some-prefix-some-ingress
  namespace: bug-repro
spec:
  ingressClassName: nginx
  rules:
  - host: my.host
    http:
      paths:
      - backend:
          service:
            name: some-internal-service
            port:
              number: 8080
        path: /
        pathType: Exact
  tls:
  - hosts:
    - my.host
    secretName: my-tls-certificate
```
