### ISSUE TITLE
[Question] Wait for conditions before continue applying resources

### ISSUE THREAD

**Issue by brunocascio** [kubernetes-sigs/kustomize#4371]
Hey folks!

I'm working on repo where I bootstrap the Kubernetes clusters and then apply the "addons". In order to apply the addons to the cluster, I need to wait for the cluster creation to finish, of course.

Is there a way to have that configuration in just one place handled by kustomize? For example:

```yaml
resources:
   - path: cluster.yml
     wait: condition=ControlPlaneReady
   - addons/argo  
```

Thanks!
