### ISSUE TITLE
configmapGenerator fails to include files starting with a tab

### ISSUE THREAD

**Issue by larstiq** [kubernetes-sigs/kustomize#4374]
**Describe the bug**

I'm trying to include some files that contain leading tabs in a config map, but this results in a yaml failure presumably because the tabs are interpreted as part of the indentation.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - commas.csv
  - tabs.tsv
  name: cm
```

And resources produced with
```
echo '\tsome\ttsv\tfile' > tabs.tsv
echo ',some,csv,file' > commas.csv
```

**Expected output**

```
apiVersion: v1
data:
  commas.csv: |
    ,some,csv,file
  tabs.tsv: "\tsome\ttsv\tfile\n"
kind: ConfigMap
metadata:
  name: cm-2f2tdc8mdc
```

or alternatively a switch to `binaryData` (looking at https://github.com/kubernetes-sigs/kustomize/pull/674 and https://github.com/kubernetes-sigs/kustomize/pull/3584)

**Actual output**

```
kustomize-4.4.1 build 
Error: yaml: line 3: found a tab character where an indentation space is expected
```

**Kustomize version**

```
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux

**Comment by larstiq** [comment]
If I add a null-byte to tabs.tsv the `kustomize build` I don't run into the tab problem:

```
apiVersion: v1
data:
  commas.csv: |
    ,some,csv,file
  tabs.tsv: "\tome\ttsv\tfile\0\n\tnother\ttsv\tfile\n"
kind: ConfigMap
metadata:
  name: cm-5f4kc79fb8
```

I guess this is due to the utf8 detection at https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/kyaml/yaml/datamap.go#L55 (based on the discussion https://github.com/kubernetes-sigs/kustomize/pull/674#discussion_r245836233)
