### ISSUE TITLE
"kustomize edit set image" does not retain image tag information on setting newName

### ISSUE THREAD

**Issue by strikeout** [kubernetes-sigs/kustomize#4375]
Hi all,

let's say I have a kustomization.yaml with some hardcoded **_image-alias:tag_** definition, like this:

```
images:
  - name: my-image
    newTag: "v3.1.2"
```

Now I want to resolve the alias `my-image` to a real endpoint programmatically in my CI/CD pipeline  like this:

```
kustomize edit set image my-image=private-registry.com/my-image
```

## what happens
`my-image` gets the proper `newName: private-registry.com/my-image` but `newTag: "v3.1.2"` disappears completely.

## what is expected
`newTag: "v3.1.2"` should be retained. The command should create a merged definition like this:

```
images:
  - name: my-image
    newName: private-registry.com/my-image
    newTag: "v3.1.2"
```

**Comment by matticala** [comment]
Hi all, just to add I have the same issue in Kustomize 3.5.1.

If

```yaml
images:
  - name: image
    newName: some-new-name
    newTag: some-new-tag
```

is set in the `base/kustomize.yaml`; when doing `kustomize edit set image image=my-new-name:my-new-tag` **in an overlay**, the result of `kustomize build` totally ignores the `images` set in the overlay.

Moreover, repeating `kustomize edit set image` adds new entries to `images` instead of replacing the existing ones.
