### ISSUE TITLE
helmCharts does not support specifying the path to local Helm charts

### ISSUE THREAD

**Issue by gw0** [kubernetes-sigs/kustomize#4378]
**Is your feature request related to a problem? Please describe.**

I attempted to apply the ["Kustomization of a Helm chart pattern"](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md) with locally-present shared Helm charts. Example:

```
charts/   ... contains Helm charts shared by multiple apps and overlays
charts/mariadb/
apps/
apps/my-first/
apps/my-first/base/kustomization.yaml  ... loads some resources and shared helmCharts (e.g. uses charts/mariadb/)
apps/my-first/prod/kustomization.yaml  ... overlay to deploy production
apps/my-second/
apps/my-second/base/kustomization.yaml  ... loads some resources and shared helmCharts (e.g. uses charts/mariadb/)
apps/my-second/prod/kustomization.yaml  ... overlay to deploy production
```

```
## apps/my-first/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- releaseName: mariadb
  namespace: default
  repo: file://../../../charts/mariadb
  name: mariadb
  version: 0.1.0
  includeCRDs: false
  valuesInline:
    ingress:
      enabled: true
```

Results in the following error, because `helm pull --repo ...` does not support `file://` protocol handle:

```
Error: could not find protocol handler for: file
: unable to run: 'helm pull --untar --untardir /tmp/foo --repo file://../../../charts/mariadb --version 0.1.0'
```

**Describe the solution you'd like**

In case it a local path (or protocol handle `file://`) is passed as `helmCharts.repo`, kustomize should not run `helm pull`, but just use that local directory while rendering the template.

**Comment by natasha41575** [comment]
Can you use `chartHome`? e.g. 

```
helmGlobals:
  chartHome: ../../../charts
helmCharts:
- releaseName: mariadb
  namespace: default
  name: mariadb
  version: 0.1.0
  includeCRDs: false
  valuesInline:
    ingress:
      enabled: true
```

**Comment by gw0** [comment]
Thanks, it works!

I had to add the following parameters to Kustomize `--enable-helm --load-restrictor=LoadRestrictionsNone`.

**Comment by bluebrown** [comment]
doest work for me somehow

```
Error: no repo specified for pull, no chart found at ''`
```

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./repo/charts

helmCharts:
  - name: myapp
    version: 0.2.0
    releaseName: myapp
```

```
$ tree ./repo/charts/
./repo/charts/
└──myapp-0.2.0.tgz

0 directories, 1 file
```

**Comment by nidhi-naviranj** [comment]
This doesn't seem to work if the chart doesn't exists in any upstream repo and only exists at local path

**Comment by kbakk** [comment]
This may not be helpful for those who depends on using Kustomize to drive the process, but if you're using Helm and want to apply Kustomization, there's a `--post-render` flag that can be used:

- https://helm.sh/docs/topics/advanced/#post-rendering
- https://trstringer.com/helm-kustomize/#option-2-helm-installupgrade

**Comment by vini-gorillas** [comment]
Hi do you hav the installCrds working as expected here?

**Comment by Piwero** [comment]
> Can you use `chartHome`? e.g.
> 
> ```
> helmGlobals:
>   chartHome: ../../../charts
> helmCharts:
> - releaseName: mariadb
>   namespace: default
>   name: mariadb
>   version: 0.1.0
>   includeCRDs: false
>   valuesInline:
>     ingress:
>       enabled: true
> ```

Hi @natasha41575, why do I get `Error: no repo specified for pull, no chart found at ''` when not adding repo under ` helmCharts` ?

**Comment by mkoval** [comment]
I am running into the same problem. I tried three different approaches to specify the path to a local Helm chart, none of which work:
- `chartHome: ../../../charts`:
    ```
    Error: no repo specified for pull, no chart found at ''
    ```
- `repo: ../../../charts`:
    ```
    Error: Error: could not find protocol handler for: 
    ```
- `repo: file://../../../charts`:
    ```
    Error: Error: could not find protocol handler for: file
    ```

Did you find a solution for this?

**Comment by JithuPaul24** [comment]
+1 I'm also facing this same issue now in my argocd server 
(**kustomize** version : **v5.4.2 2024-09-13T16:45:01Z**, 
**helm** : **v3.15.2+g1a500d5**)
**ArgoCD version: v2.12.3+6b9cd82**
This is what my kustomization file charts directory looks like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
 chartHome: ../../../base/charts/serviceacontainera/servicea-containera/

helmCharts:
- name: servicea-containera
  releaseName: servicea-containera
  valuesFile: values.yaml
  version: 1.0.0
  includeCRDs: true
```

and this is what my overlays/kustomize file looks like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/charts/serviceacontainera
  - namespace.yaml
 ```
  
I have applied the kustomize build options in the argocd-cm config map

--enable-helm --load-restrictor LoadRestrictionsNone

When I build the application in argocd , I get the error:

`Unable to create application: application spec for servicea-containera-dev1-app is invalid: InvalidSpecError: Unable to generate manifests in overlays/dev1/servicea-containera: rpc error: code = Unknown desc = `kustomize build <path to cached source>/overlays/dev1/servicea-containera --enable-helm --load-restrictor LoadRestrictionsNone` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from '../../../base/charts/serviceacontainera': read <path to cached source>/base/charts/serviceacontainera: is a directory': recursed accumulation of path '<path to cached source>/base/charts/serviceacontainera': no repo specified for pull, no chart found at ''`
