### ISSUE TITLE
patches should throw error on missing targets

### ISSUE THREAD

**Issue by Arabus** [kubernetes-sigs/kustomize#4379]
**Describe the bug**

If `kustomize build` is run with a patchesJson6902 section specifying a nonexistant target it still reports success and outputs its resources as if it worked

**Files that can reproduce the issue**

kustomization.yaml (note the 'v2' in the version field)

```yaml
kind: ""
apiversion: ""
resources:
- manifests/servicemonitor.yaml
patchesJson6902:
- target:
    group: monitoring.coreos.com
    kind: ServiceMonitor
    name: starboard-exporter
    namespace: starboard
    version: v2

  path: jsonpatches/patch.0.yaml
```

manifests/servicemonitor.yaml

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: starboard-exporter
  name: starboard-exporter
  namespace: starboard
spec:
  endpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: starboard-exporter
      app.kubernetes.io/name: starboard-exporter
```

jsonpatches/patch.0.yaml

```yaml
- op: add
  path: /metadata/labels/release
  value: kube-prometheus-stack
```

**Expected output**

Some kind of error e.g, "WARNING: patchesJson6902[0] target not found for $target - please check kustomized resources for correctness" or "ERROR: patchesJson6902[0] target not found for $target! Bailing out."
An exit code > 0 to signal that something went wrong
Some suggestions of partial matches e.g., "Found $similartarget, did you mean $targetdiff?"

**Actual output**

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: starboard-exporter
  name: starboard-exporter
  namespace: starboard
spec:
  endpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: starboard-exporter
      app.kubernetes.io/name: starboard-exporter
```

**Kustomize version**

```
❯ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:arm64}
```

**Platform**

```
❯ sw_vers
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```
