### ISSUE TITLE
patchesJson6902 op replace adds missing location

### ISSUE THREAD

**Issue by Arabus** [kubernetes-sigs/kustomize#4380]
**Describe the bug**

When running `kustomize build` with a patchesJson6902 patch to replace a value on a location not present at the given target, kustomize adds it. This is unexpected behaviour, violates https://datatracker.ietf.org/doc/html/rfc6902/#section-4.3 and should result in an Error instead.

**Files that can reproduce the issue**

kustomization.yaml

```
kind: ""
apiversion: ""
resources:
- templates/resources.yaml
patchesJson6902:
- target:
    kind: ConfigMap
    name: test
    namespace: default
    version: v1

  path: jsonpatches/patch.0.yaml
```

jsonpatches/patch.0.yaml
```
- op: replace
  path: /data/baz
  value: BAZ
```

templates/resources.yaml

```
apiVersion: v1
data:
  foo: FOO
kind: ConfigMap
metadata:
  labels:
    app: test
  name: test
  namespace: default
```

**Expected output**

Some kind of error stating that replacing a missing value is not supported

**Actual output**

```
apiVersion: v1
data:
  baz: BAZ
  foo: FOO
kind: ConfigMap
metadata:
  labels:
    app: test
  name: test
  namespace: default
```

**Kustomize version**

```
❯ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:arm64}
```

**Platform**

```
❯ sw_vers
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```

**Additional context**

The problem seems to haven been fixed in the upstream library kustomize uses, see https://github.com/evanphx/json-patch/issues/119 at the end. It might be suitable to bump the used version to v5 to solve this issue
