### ISSUE TITLE
master branch drops trailing space in multiline strings

### ISSUE THREAD

**Issue by ephesused** [kubernetes-sigs/kustomize#4384]
**Describe the bug**

When presented with a multiline string where a line ends with a space, the master branch currently drops the space. v4.4.1 retains the space as expected.

**Files that can reproduce the issue**

kustomization.yaml (note the two spaces at the end of the appropriate line):
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: trailingWhiteSpace
  literals:
  - |
    trailingSpace=This line ends with two spaces  
    next line
  options:
    disableNameSuffixHash: true
```

**Expected output, using v4.4.1 as an example**

```
$ build/kustomize-execs/release-v4.4.1/kustomize build testdata/kust-issue-xxxx
apiVersion: v1
data:
  trailingSpace: "This line ends with two spaces  \nnext line\n"
kind: ConfigMap
metadata:
  name: trailingWhiteSpace
$
```

**Actual output**

```
$ build/kustomize-execs/branch-master/kustomize build testdata/kust-issue-xxxx
apiVersion: v1
data:
  trailingSpace: "This line ends with two spaces \nnext line\n"
kind: ConfigMap
metadata:
  name: trailingWhiteSpace
$
```

**Kustomize version**

```
$ cat build/kustomize-execs/branch-master/info.yaml
branch: master
sha1: 13e26004fd4e715c1c3fe7251c681b27b499fc12
$
```

**Platform**

Linux
