### ISSUE TITLE
Quotes are dropped from namespace in kustomization resource

### ISSUE THREAD

**Issue by shanalily** [kubernetes-sigs/kustomize#4386]
When adding 'namespace' with only numeric characters to kustomization resource to be applied to all resources, quotes are dropped somewhere during the namespace transformation and the k8s resource becomes invalid when trying to apply.
This works fine in an older versions of kustomize where enable_kyaml was false by default.

Similar to #3412 and #3440 but for namespace field, so the kyaml fix is probably similar.

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "01234"
resources:
- resources.yaml
```

resources.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  key: "val"
```

**Expected output**

```
apiVersion: v1
data:
  key: val
kind: ConfigMap
metadata:
  name: test
  namespace: "01234"
```

**Actual output**

```
apiVersion: v1
data:
  key: val
kind: ConfigMap
metadata:
  name: test
  namespace: 668
```

**Kustomize version**

{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}

**Platform**

macOS

**Additional context**

**Comment by shanalily** [comment]
I realized there are similar issues with bool "true" and "false" values in some cases.

Example with bool map key:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
commonLabels:
  key: "01234"
```

resources.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  key: "val"
  yes: y 
  n: no
  true: trueval
```

**Expected output**

```
apiVersion: v1
data:
  key: val
  "n": "no"
  true: trueval
  "yes": "y"
kind: ConfigMap
metadata:
  labels:
    key: "01234"
  name: test
```

**Actual output**

```
Error: map[string]interface {}{"apiVersion":"v1", "data":map[interface {}]interface {}{true:"trueval", "key":"val", "n":"no", "yes":"y"}, "kind":"ConfigMap", "metadata":map[string]interface {}{"labels":map[string]interface {}{"key":"01234"}, "name":"test"}}: json: unsupported type: map[interface {}]interface {}
```

Example with bool map key:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
commonLabels:
  key: "01234"
```

resources.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  key: "val"
  yes: y 
  n: no
  truekey: true
```

**Expected output**

```
apiVersion: v1
data:
  key: val
  "n": "no"
  truekey: "true"
  "yes": "y"
kind: ConfigMap
metadata:
  labels:
    key: "01234"
  name: test
```

**Actual output**

```
apiVersion: v1
data:
  key: val
  "n": "no"
  truekey: true
  "yes": "y"
kind: ConfigMap
metadata:
  labels:
    key: "01234"
  name: test
```

output of `kustomize build .  | kubectl apply -f -` and `kubectl apply -k .`:

```
The request is invalid: patch: Invalid value: "map[data:map[truekey:true truth:<nil>] metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"v1\",\"data\":{\"key\":\"val\",\"n\":\"no\",\"truekey\":true,\"yes\":\"y\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"key\":\"01234\"},\"name\":\"test\",\"namespace\":\"default\"}}\n]]]": unrecognized type: string
```

**Kustomize version**

{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}

kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-18T00:11:23Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Platform**

macOS

**Additional context**
