### ISSUE TITLE
master branch orders some resource names differently than v4.4.1

### ISSUE THREAD

**Issue by ephesused** [kubernetes-sigs/kustomize#4388]
**Describe the bug**

At v4.4.1 and before, kustomize build produces output with resource names sorted like so:

1. testing
2. testing-one
3. testing-two

In the master branch ~~(I believe first appearing at 92197fd)~~, kustomize build produces output with resource names sorted like so:

1. testing-one
2. testing-two
3. testing

Cross reference https://github.com/kubernetes-sigs/kustomize/pull/4361#issuecomment-1012374075

**Files that can reproduce the issue**

kustomization.yaml

```yaml
resources:
  - resources.yaml
```

resources.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: testing
data:
  key: value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-one
data:
  key: value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-two
data:
  key: value
```

**Expected output, using v4.4.1 as an example**

```
$ build/kustomize-execs/release-v4.4.1/kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}
$ build/kustomize-execs/release-v4.4.1/kustomize build testdata/kust-resource-sort
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: testing
---
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: testing-one
---
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: testing-two
$
```

**Actual output**

```
$ cat build/kustomize-execs/branch-master/info.yaml
branch: master
sha1: 6e82b210a9e0651cc8392d2931c64348137b82ff
$ build/kustomize-execs/branch-master/kustomize build testdata/kust-resource-sort
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: testing-one
---
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: testing-two
---
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: testing
$
```

**Kustomize version**

This change is not (yet) in a released version. I see the change in the master branch, ~~and I believe it first appears at 92197fd~~.

**Platform**

Linux
