### ISSUE TITLE
Namespace for RoleBinding (and possibly other resources) is not respected

### ISSUE THREAD

**Issue by tomaszkiewicz** [kubernetes-sigs/kustomize#439]
Hi, 

While evaluating kustomize to customise some prometheus operator deployment I've probably found a bug.

Assuming we have `test.yaml`:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
```

Which simply binds service account to two namespaces and is a valid declaration of resources. 
Then `kustomization.yaml`:
```
resources:
- test.yaml
```

When I run `kustomize build` I get:

```
Error: loadResMapFromBasesAndResources: rawResources failed to read Resources: GroupVersionKindName: resource.ResId{gvk:schema.GroupVersionKind{Group:"rbac.authorization.k8s.io", Version:"v1", Kind:"RoleBinding"}, name:"prometheus-k8s", prefix:"", namespace:""} already exists b the map
```

It looks like metadata namespace parameter is not taken into account and kustomize sees 2nd resource as a duplicate of the 1st one.

Best regards

Łukasz Tomaszkiewicz
