### ISSUE TITLE
[Question] how to add an env to all containers in Deployment?

### ISSUE THREAD

**Issue by Lwxiang** [kubernetes-sigs/kustomize#4391]
origin resource
```yaml
apiVersion: apps/v1
kind: Deployment
...
    spec:
      containers:
        - name: nginx
           image: nginx
           env:
           - name: foo
             value: bar
        - name: sidecar
           image: sidecar
           env:
           - name: hello
             value: world
```

As the origin resource above, I have 2 container in 1 pod, and each has its own env.
Now I want to insert an env drink=coffee into the 2 container.

I can do this by json patch:
```yaml
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: drink
    value: coffee
- op: add
  path: /spec/template/spec/containers/1/env/-
  value:
    name: drink
    value: coffee
```

But if I don't want to do this with every index of containers or I just don't know how many the containers are. Can I have a batch method, to add env for all containers by one step?
