### ISSUE TITLE
LabelTransformer can't reference inside an array

### ISSUE THREAD

**Issue by wolfmah** [kubernetes-sigs/kustomize#4392]
**Describe the bug**

The usage of `commonLabels` is adding all labels inside `spec.selector.matchLabels` and I don't want that. So, I went with the solution of using a `LabelTransformer` directly.

It was going smootly for a long time, until recently where I have a need to add a `StatefulSet` with the usage of `spec.volumeClaimTemplates`. `volumeClaimTemplates` is an array of `PersistentVolumeClaim`, which can have labels and annotations.

Through testing, I have found that `commonLabels` can manage the objects found within `spec.volumeClaimTemplates` without a problem (labels are injected correctly). Though, I cannot find a way to make it work via `LabelTransformer`.

**Files that can reproduce the issue**

`test/kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  test: commonLabels

resources:
  - statefulset.yaml

transformers:
  - labels.yaml
```

`test/statefulset.yaml`

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  template:
    spec:
      containers:
        - name: test
          image: test
  volumeClaimTemplates:
    - metadata:
        labels:
          test: will be overwritten by commonLabels
        name: test-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
```

`test/labels.yaml`

```yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: any
labels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/managed-by: kustomize
fieldSpecs:
  - path: metadata/labels
    create: true
  - kind: StatefulSet
    path: spec/template/metadata/labels
    create: true
  - kind: StatefulSet
    path: spec/volumeClaimTemplates/0/metadata/labels
    create: false
```

**Expected output**

```
# kustomize build test
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: kustomize
    test: commonLabels
  name: test
spec:
  selector:
    matchLabels:
      test: commonLabels
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: dev
        app.kubernetes.io/managed-by: kustomize
        test: commonLabels
    spec:
      containers:
      - image: test
        name: test
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/environment: dev
        app.kubernetes.io/managed-by: kustomize
        test: commonLabels
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
```

**Actual output**

```
# kustomize build test
Error: considering field 'spec/volumeClaimTemplates/0/metadata/labels' of object
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  labels:
    test: commonLabels
    app.kubernetes.io/environment: dev
spec:
  template:
    spec:
      containers:
      - name: test
        image: test
    metadata:
      labels:
        test: commonLabels
        app.kubernetes.io/environment: dev
  volumeClaimTemplates:
  - metadata:
      labels:
        test: commonLabels
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
  selector:
    matchLabels:
      test: commonLabels
: visit traversal on path: [0 metadata labels]: fieldName: 0: wrong Node Kind for  expected: SequenceNode was MappingNode: value: {metadata:
  labels:
    test: commonLabels
  name: test-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi}
```

**Kustomize version**

```
# kustomize version
{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:24:12Z GoOs:linux GoArch:amd64}
```

**Platform**

```
# uname -a
Linux 17bcbbcff0c1 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 Linux
```

**Additional context**

No amount of change the `fieldSpecs` of `LabelTransformer` to `0`, `-` or `*` resulted in anything different.

**Comment by natasha41575** [comment]
> The usage of commonLabels is adding all labels inside spec.selector.matchLabels and I don't want that. So, I went with the solution of using a LabelTransformer directly.

Have you tried just using `labels`? This fields lacks documentation but its purpose is to add labels to `metadata.labels`, and not include selectors. Would that resolve your issue?

**Comment by wolfmah** [comment]
I just had time to try it out.

I had to do some digging to find out how to use this new `labels` field. For reference, here's the PR that introduced it: https://github.com/kubernetes-sigs/kustomize/pull/3743. As well as the open issue for documenting this field: https://github.com/kubernetes-sigs/kustomize/issues/3756.

Unfortunately, the exact same problem applies. The tests uses the same `statefulset.yaml` as in my first post.

### Test 1
<details>
<summary>kustomization.yaml</summary>
<p>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  test: commonLabels

labels:
  - pairs:
      app.kubernetes.io/environment: dev
      app.kubernetes.io/managed-by: kustomize

resources:
  - statefulset.yaml
```

</p>
</details>

<details>
<summary>Output</summary>
<p>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: kustomize
    test: commonLabels
  name: test
spec:
  selector:
    matchLabels:
      test: commonLabels
  template:
    metadata:
      labels:
        test: commonLabels
    spec:
      containers:
      - image: test
        name: test
  volumeClaimTemplates:
  - metadata:
      labels:
        test: commonLabels
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
```

</p>
</details>

As can be seen, `spec/template/metadata/labels` and `spec/volumeClaimTemplates/0/metadata/labels` doesn't get any labels from `labels`. I would have thought `labels` would behave like `commonLabels`.

### Test 2
<details>
<summary>kustomization.yaml</summary>
<p>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  test: commonLabels

labels:
  - pairs:
      app.kubernetes.io/environment: dev
      app.kubernetes.io/managed-by: kustomize
    fields:
      - kind: StatefulSet
        path: spec/template/metadata/labels
        create: true
      - kind: StatefulSet
        path: spec/volumeClaimTemplates/0/metadata/labels
        create: false

resources:
  - statefulset.yaml
```

</p>
</details>

<details>
<summary>Output</summary>
<p>

```
Error: considering field 'spec/volumeClaimTemplates/0/metadata/labels' of object
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: test
    metadata:
      labels:
        app.kubernetes.io/environment: dev
  volumeClaimTemplates:
  - metadata:
      labels:
        test: will be overwritten by commonLabels
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
: visit traversal on path: [0 metadata labels]: fieldName: 0: wrong Node Kind for  expected: SequenceNode was MappingNode: value: {metadata:
  labels:
    test: will be overwritten by commonLabels
  name: test-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi}
```

</p>
</details>

If I try to specify a path inside the array of `spec/volumeClaimTemplates`, I get the same exact error as in my original post. So, I'm back to square one. :(

### Closing thoughts

The way `labels` is behaving, I have a hard time finding what are the advantages over directly using `LabelTransformer`. I guess it offer a finer management of where to put selectors (compare to `commonLabels`) and in a less verbose way (than `LabelTransformer`).

Quite frankly, I would have like better if `labels` had behave exactly as `commonLabels`, but without the selectors. Meaning, adding the labels everywhere that a `metadata/labels` can go. This would have the problem of having to access an array item to update a `metadata/labels` field. As it is now, `labels` is just a less verbose implementation of `LabelTransformer`.

**Comment by wolfmah** [comment]
I just found out this little piece of code: https://github.com/kubernetes-sigs/kustomize/blob/077c7b2d20bfdb0de78e6873a4ae1ce08afa1c40/api/konfig/builtinpluginconsts/commonlabels.go#L100-L103

<details>
<summary>And if I use it like so...</summary>
<p>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  test: commonLabels

labels:
  - pairs:
      app.kubernetes.io/environment: dev
      app.kubernetes.io/managed-by: kustomize
    fields:
      - kind: StatefulSet
        path: spec/template/metadata/labels
        create: true
      - kind: StatefulSet
        path: spec/volumeClaimTemplates[]/metadata/labels
        create: false

resources:
  - statefulset.yaml
```

</p>
</details>

It work wonders! I guess that in all my testing, I didn't properly tested using a path to the array with `[]`.

Though, my feelings about labels still stand: I think it should behave more `commonLabels` than like `LabelTransformer`.
