### ISSUE TITLE
Support the ability to replace the image registry domain

### ISSUE THREAD

**Issue by vsabella** [kubernetes-sigs/kustomize#4414]
https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/api/types/image.go#L8

In our usage of Kustomize, we use two different registries for images depending on the deployment region (due to use of sovereign clouds).

We are looking to simplify our kustomize so we can have a singe component to replace all instances of <registry-domain-1> with <registry-domain-2> in a single place, instead of the newName tag everywhere for our hundreds of containers.

We're happy to submit a patch but are looking for the best way to solve this problem that is in line with Kustomize philosophy.

1. We could amend the image.go to support a new field (newDomain) and update the processing of image: newImage/NewDigest/newTag to also support newRegistry by processing image tags into the format specified by cncf: (https://github.com/distribution/distribution/blob/main/reference/regexp.go) 

2. We could add regex capture group / capture replace support to the image replacement - so we can capture part of the old value and re-use it in the new value.

3. Are there any other options that we haven't considered?

Thanks!

**Comment by natasha41575** [comment]
Thank you for submitting your issue. I was wondering if you could provide some more detail about what you are trying to do with option 1, perhaps with an example? I am open to the suggestion of a new field in `images` to replace registry names but I would like better clarity on what specifically you are proposing. 

I'm also curious if your use case can be resolved by the existing `replacements` feature [[link to docs](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/)]. For example, if you have some containers that look like:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  template:
    spec:
      containers:
      - name: mypostgresdb
        image: myregistrydomain:port/foo/bar/1
      - name: nginxapp
        image: myregistrydomain:port/foo/bar/2
```
and a ConfigMap with the following:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  registry: new-registry
```
You could write a kustomization file with the following:

```
replacements:
- source:
    kind: ConfigMap
    name: local-config
    fieldPath: data.registry
  targets:
  - select: 
      kind: Deployment
    fieldpaths:
      - spec.template.spec.containers.[0].image
      - spec.template.spec.containers.[1].image
   options: 
     delimiter: ":"
     index: 0
```

The biggest downside with this approach is its verbosity and that you would have to list every container individually. This will be fixed by https://github.com/kubernetes-sigs/kustomize/issues/4053 which will allow you to select every element in an array without having to list them out individually. If you have any other feedback that might make this approach work for you, please let us know. 

That being said, a new field targeted specifically for images seems like a reasonable alternative, especially considering how popular the feature is and that replacements is still new and working out its kinks. 

/kind feature
/kind support
/triage under-consideration
