### ISSUE TITLE
Cannot override ConfigMap entries that were defined in a patch

### ISSUE THREAD

**Issue by NickLarsenNZ** [kubernetes-sigs/kustomize#4419]
I'm unable to override ConfigMap entries that were already defined in a patch.

kustomization.yml

```yml
# The empty ConfigMap is defined in this manifest
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/8b57bc990cd72c6475e2ae88126a1ed57e2460a3/manifests/ha/install.yaml

# It is then populated with template.* and trigger.* entries
patches:
- https://raw.githubusercontent.com/argoproj/argo-cd/8b57bc990cd72c6475e2ae88126a1ed57e2460a3/notifications_catalog/install.yaml # replace hash with version once it's included

# And I want to replace a few of the entries
configMapGenerator:
- name: argocd-notifications-cm
  behavior: merge # I have tried replace too, no change
  literals:
  - example.item=searchable_garbage # this loads in fine because it didn't exist before
  - template.app-deployed=searchable_garbage # we only see the orig

```

**Expected output**

A config map containing the entries from the patch, a new value, and an updated value.

```sh
❯ kustomize build . | grep searchable_garbage
  example.item: searchable_garbage
  template.app-deployed: searchable_garbage

```

**Actual output**

The entries from the patch, and new entries.

```sh
❯ kustomize build . | grep searchable_garbage
  example.item: searchable_garbage

```

**Kustomize version**

```
❯ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}
```

**Platform**

macos

**Additional context**

I don't have trouble with this when it's done in an overlay. I suspect it has to do with the `resources`, `patch` and `configMapGenerator` being in the same overlay.
