### ISSUE TITLE
namePrefix from base is not being applied to certain files in an overlay

### ISSUE THREAD

**Issue by nickjj** [kubernetes-sigs/kustomize#4423]
**Describe the bug**

When I set `namePrefix: hello-` in a base that's being used by an overlay, the `namePrefix` is not applied to certain resources.

My overall goal with this set up is to manage multiple apps across multiple environments. My directory structure is as follows:

```
base/
  alb/
    ingress.yaml
    kustomization.yaml
  kustomization.yaml
overlays/
  hello/
    base/
      kustomization.yaml
      patch-deployment.yaml
    test/
      kustomization.yaml
      patch-deployment.yaml
      sealed-secrets.yaml
```

The basic idea is:

- I have a single base that a bunch of different apps use
- Each app has its own base that overrides / adds things not in the "real" base
- Each app has multiple environments which uses its own base to override as necessary

**Files that can reproduce the issue**

```yaml
# base/kustomization.yaml
---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
- "deployment.yaml"
```

```yaml
# overlays/hello/base/kustomization.yaml
---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

namePrefix: "hello-"

commonLabels:
  app.kubernetes.io/name: "hello-app"

resources:
- "../../../base"

patches:
- path: "patch-deployment.yaml"
  target:
    kind: "Deployment"
    name: "app"
```

```yaml
# overlays/hello/test/kustomization.yaml
---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
- "../base"
- "../../../base/alb"
- "sealed-secrets.yaml"

patches:
- path: "patch-ingress.yaml"
  target:
    kind: "Ingress"
    name: "app"
- path: "patch-deployment.yaml"
  target:
    kind: "Deployment"
    name: "app"
```

```yaml
# base/alb/ingress.yaml
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "app"
  # Omitting a bunch of ALB specific things that aren't important here
```

```yaml
# overlays/hello/test/patch-ingress.yaml
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "app"
spec:
  rules:
  - host: "hello.example.com"
    http:
      paths:
      - backend:
          service:
            name: "app"
            port:
              number: 80
        path: "/"
        pathType: "Prefix"
```

```yaml
# overlays/hello/test/sealed-secrets.yaml
apiVersion: "bitnami.com/v1alpha1"
kind: "SealedSecret"
metadata:
  name: "app"
spec:
  encryptedData:
    # Omitting because it's not important here
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: "app"
```

**Expected output**

- The `Ingress` name would be `hello-app`
- The `SealedSecret` name would be `hello-app`

**Actual output**

- The `Ingress` name is `app`
- The `SealedSecret` name is `app`

**Kustomize version**

4.4.0

**Platform**

macOS (Intel) but the same thing happens on my WSL 2 box running Ubuntu 20.04

**Additional context**

If I remove `namePrefix: hello-` from `overlays/hello/base/kustomization.yaml` and instead put it into `overlays/hello/test/kustomization.yaml` then everything works as intended.

This is an issue because it means I have to duplicate the `namePrefix` in every environment.

All of the names in the `Deployment` are ok without having to make this change.
