### ISSUE TITLE
Unable to merge secretgenerator with different namespace

### ISSUE THREAD

**Issue by davidpellcb** [kubernetes-sigs/kustomize#4427]
I believe this issue may be related to #1328 which dealt with merging configmaps with different namespaces. I'm not totally sure if this is a bug or kustomize is not intended to do what I'm trying to do.

I have a simple base with a single `secretGenerator`. In my overlays, I want to change the secret's namespace. However, when I try to do this I get the following error:

```
Error: merging from generator &{0xc0006191d0 {  map[] map[]} {{bar myconfig merge {[] [] [] } <nil>} }}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"Secret"}, Name:"myconfig", Namespace:"bar"} does not exist; cannot merge or replace
```

It's true that a secret with namespace `bar` doesn't exist - I'm trying to create one with that namespace. The base secretGenerator secret has a namespace of `foo`.

This happens with both `kustomize build` and `kubectl kustomize`:

kubectl version 1.21
kustomize 4.4.1

**Files**

```
# base/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: myconfig
  namespace: foo
  files:
    - ./myconfig.yaml
generatorOptions:
  disableNameSuffixHash: true
```

```yaml
# overlays/dev/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../base
secretGenerator:
- name: myconfig
  namespace: bar
  behavior: merge
```

In this case the file is supposed to be the same, with just a different namespace. I suspect kustomize needs both the name and the namespace to find a unique secret to merge with. Is that correct?  If so, what is the correct way to modify a secret coming from a `secretGenerator` this way?

**Comment by KnVerey** [comment]
> I suspect kustomize needs both the name and the namespace to find a unique secret to merge with. Is that correct? 

Yep, that's correct: in these generators, the name and namespace fields are used to create the new secret and identify the  existing resource it should be merged with, when that option is set. So it build a new secret bar/myconfig and fails to find one with that identifier in the existing set.

> If so, what is the correct way to modify a secret coming from a secretGenerator this way?

I'd suggest using the [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) field to modify it the same way you would any other resource. Since transformers (including patches) run after generators (including the secret generator), you can even do this alongside the overlay generator, assuming you want to add data to the secret there--just target it by the original namespace in the generator.

i.e.:
```yaml
# overlays/dev/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../base

secretGenerator:
- name: myconfig
  namespace: foo
  behavior: merge
  files: # add new things

patches:
- target:
    kind: Secret
    name: myconfig
    namespace: foo
  options:
    allowNamespaceChange: true
  patch: |-
    - op: replace
      path: /metadata/name
      value: bar
```

/kind support
