### ISSUE TITLE
transformers: PrefixSuffixTransformer applied partially in referenced resources

### ISSUE THREAD

**Issue by dttrian** [kubernetes-sigs/kustomize#4428]
**Describe the bug**

Using PrefixSuffixTransformer via `transformers` field to add a prefix to configs/secrets works correctly when build is invoked directly on the kustomization.yaml that uses it, but works only partially when build is invoked on a kustomization.yaml that references via `resources` the kustomization.yaml that uses the transformer.

Partially means that the prefix is added to the configmap definition, but not to the references to the configmap in a deployment.

This means that you can have something like this:

```
apiVersion: v1
data:
  param: value
kind: ConfigMap
metadata:
  name: bar-config-27ch7b2kbt
  namespace: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: stage
spec:
  template:
    spec:
      containers:
      - env:
        - name: SOME_PARAM
          valueFrom:
            configMapKeyRef:
              key: param
              name: config
        image: hashicorp/http-echo:1.1-devel
        name: bar

```

where the `config` ConfigMap is named `bar-config-27ch7b2kbt` when defined and just `config` when used in the deployment.

**Files that can reproduce the issue**

(Anyway, I have attached them to the issue)

./bar/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  template:
    spec:
      containers:
      - name: bar
        image: hashicorp/http-echo:1.1-devel

        env:
          - name: "SOME_PARAM"
            valueFrom:
              configMapKeyRef:
                name: config
                key: param
```
./bar/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage

resources:
- deployment.yaml

configMapGenerator:
- name: config
  literals:
  - param=value

transformers:
- kustomizeconfig.yaml
```
./bar/kustomizeconfig.yaml
```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: configSecretsPrefixer
prefix: "bar-"
fieldSpecs:
- kind: ConfigMap
  path: metadata/name
```
./foo/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    metadata:
      labels:
        app: foo
        version: 1.0.0
    spec:
      containers:
      - name: foo
        image: hashicorp/http-echo

        env:
          - name: "A_PARAM"
            valueFrom:
              configMapKeyRef:
                name: config
                key: param
```
./foo/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage

resources:
- deployment.yaml

configMapGenerator:
- name: config
  literals:
  - param=somevalue

transformers:
- kustomizeconfig.yaml
```
./foo/kustomizeconfig.yaml
```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: configSecretsPrefixer
prefix: "foo-"
fieldSpecs:
- kind: ConfigMap
  path: metadata/name
```
./kustomization.yaml
```
resources:
- bar
- foo
```

If you run `kustomize build .` you can see the bug, if you run `kustomize build foo` or `kustomize build bar` you don't see any bug.

**Expected output**

```
apiVersion: v1
data:
  param: value
kind: ConfigMap
metadata:
  name: bar-config-27ch7b2kbt
  namespace: stage
---
apiVersion: v1
data:
  param: somevalue
kind: ConfigMap
metadata:
  name: foo-config-ffm984ghct
  namespace: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: stage
spec:
  template:
    spec:
      containers:
      - env:
        - name: SOME_PARAM
          valueFrom:
            configMapKeyRef:
              key: param
              name: bar-config-27ch7b2kbt
        image: hashicorp/http-echo:1.1-devel
        name: bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: stage
spec:
  template:
    metadata:
      labels:
        app: foo
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: A_PARAM
          valueFrom:
            configMapKeyRef:
              key: param
              name: foo-config-ffm984ghct
        image: hashicorp/http-echo
        name: foo
```

**Actual output**

```
apiVersion: v1
data:
  param: value
kind: ConfigMap
metadata:
  name: bar-config-27ch7b2kbt
  namespace: stage
---
apiVersion: v1
data:
  param: somevalue
kind: ConfigMap
metadata:
  name: foo-config-ffm984ghct
  namespace: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: stage
spec:
  template:
    spec:
      containers:
      - env:
        - name: SOME_PARAM
          valueFrom:
            configMapKeyRef:
              key: param
              name: config
        image: hashicorp/http-echo:1.1-devel
        name: bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: stage
spec:
  template:
    metadata:
      labels:
        app: foo
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: A_PARAM
          valueFrom:
            configMapKeyRef:
              key: param
              name: config
        image: hashicorp/http-echo
        name: foo
```

**Kustomize version**

{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 Bui
ldDate:2021-03-08T20:53:03Z GoOs:windows GoArch:amd64}

**Platform**

Windows

[trasformers-not-applied.zip](https://github.com/kubernetes-sigs/kustomize/files/7948857/trasformers-not-applied.zip)
