### ISSUE TITLE
Kustomize filter kinds on "base" input

### ISSUE THREAD

**Issue by epcim** [kubernetes-sigs/kustomize#4436]
**Is your feature request related to a problem? Please describe.**

There were already closed discussion whether Kustomize shall remove resources from it's "base" source and these IMO were closed as not a good practice.

I would like to reopen this or rather say more discussion/document what is "bases" for Kustomize. Sorry If I did missed some other issue with the same topic.

In the example bellow, you see Helm chart of longhorn provides this job, with annotation used to be executed on deployment removal:
```
  name: longhorn-uninstall
  annotations:
    helm.sh/hook: pre-delete
```

Why I would like to bring it to light again. This Helm chart in this case is "bad base" for the Kustomize. In fact not a direct bug of Kustomize itself, we could blame longhorn, but it's clear that some deployment annotations (not strictly Helm related) are being used for app life-cycle, but Kustomize itself will never take care of them. 

Let's not speak about "filtering" resources only. We may want to **add annotations, to mark, not to apply specific resource** later. Obviously Kustomize is not yet in this business (not sure but `kpt live applly -` would treat that better?)

With KRM Fn available, with some more time with the project, how does the "Kustomize" team does feel what "bases" are and how they shall be used?

* Do we strictly expect "private" base (where one would do overrides for dev/prod etc)?
* Do we suppose, "base" code for application could be shared resource and Kustomize serve as swiss-knire, to overrides/patch on specific deployment?

If the 2nd is true, and many people use it this way from I have seen, then Helm or any KRM Fn can serve as generic manifest source. However without a primary control of such source (as it probably reside on some public repo, and you can only control it's global values.yaml etc..) one then miss the capability to pick only the Kinds wanted (or filter some not desired, not only transform them).

Imagine this source:
```
# cat ./longhorn/Kustomization 
# https://github.com/longhorn/charts/blob/master/charts/longhorn/values.yaml

namespace: longhorn-system

generatorOptions:
  disableNameSuffixHash: true

helmChartInflationGenerator:
- chartName: longhorn
  chartRepoUrl: https://charts.longhorn.io
  #chartVersion: 
  releaseName: longhorn
  releaseNamespace: longhorn-system
  valuesMerge: override
  extraArgs:
  - --include-crds
  valuesLocal:
    installCRDs: true
    fullnameOverride: longhorn

defaultSettings:
      defaultDataPath: "/var/lib/longhorn"

```

That will render, besides other manifests this, and guess (yes it's immutable if it exist so at first apply will fail, but on each apply you force it effectively do the task - uninstall whole. longhorn, including it's data.
```
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.2.3
    helm.sh/chart: longhorn-1.2.3
  name: longhorn-uninstall
```

Recent discussion, resources
- https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#removal-directives

**Describe the solution you'd like**

- native way to filter kinds, based on name regex, labels and annotations
- update documentation in relation to what "bases" are considered, what Kustomize plays a role in "life-cycle" operations as shown in this example

**Describe alternatives you've considered**

- KRM Fn to filter Kinds would work, but seems like too complex and time consuming to run for this case.
