### ISSUE TITLE
Given two bases, one using nameSuffix - serviceName is replaced in both StatefulSets

### ISSUE THREAD

**Issue by george-angel** [kubernetes-sigs/kustomize#4444]
Kustomize version: Version:4.4.1

Here is a demo repository to showcase the problem: https://github.com/george-angel/kustomize-servicename-namesuffix-bug-demo

The output is:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo
  name: demo
spec:
  ports:
  - name: demo
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo
  name: demo-test
spec:
  ports:
  - name: demo
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: demo
  name: demo
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
  serviceName: demo-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: demo
  name: demo-test
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
  serviceName: demo-test
```

I would expect the `serviceName` of the "demo" StatefulSet to **not** be replaced.

This behaviour was not present in v3.8.5 and worked "as expected". v3.8.5 output:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo
  name: demo
spec:
  ports:
  - name: demo
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo
  name: demo-test
spec:
  ports:
  - name: demo
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: demo
  name: demo
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
  serviceName: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: demo
  name: demo-test
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
  serviceName: demo-test
```
