### ISSUE TITLE
Error when fetching helm chart with 'kustomize build --enable-helm'

### ISSUE THREAD

**Issue by Zedronar** [kubernetes-sigs/kustomize#4451]
**Describe the bug**

When using a `HelmChartInflationGenerator`, kustomize fails with the following command:

```bash
$ kustomize build --enable-helm
```
The output is the following:
```
Error: Error: looks like "oci://f1dev.azurecr.io/helm/f1" is not a valid chart repository or cannot be reached: object required
: unable to run:

'helm pull --untar --untardir /opt/HutchMaster/SharedServer/k8s/f1/kustomize-overlays/dev/we/charts --repo oci://f1dev.azurecr.io/helm/f1 f1 --version 0.1.0'

with env=[HELM_CONFIG_HOME=/var/folders/7q/d7z7scm55kz3jtcwwzdql2m40000gn/T/kustomize-helm-1630665907/helm HELM_CACHE_HOME=/var/folders/7q/d7z7scm55kz3jtcwwzdql2m40000gn/T/kustomize-helm-1630665907/helm/.cache HELM_DATA_HOME=/var/folders/7q/d7z7scm55kz3jtcwwzdql2m40000gn/T/kustomize-helm-1630665907/helm/.data] (is 'helm' installed?)
```

I can confirm that I get the same error when using `helm` directly:

```bash
helm pull --untar --untardir /opt/HutchMaster/SharedServer/k8s/f1/kustomize-overlays/dev/we/charts --repo oci://f1dev.azurecr.io/helm/f1 f1 --version 0.1.0
```
Same output as before:
```
Error: Error: looks like "oci://f1dev.azurecr.io/helm/f1" is not a valid chart repository or cannot be reached: object required
```

**However**, when running that very same command but *without (!)* the `--repo` flag... it works!
```bash
helm pull --untar --untardir /opt/HutchMaster/SharedServer/k8s/f1/kustomize-overlays/dev/we/charts oci://f1dev.azurecr.io/helm/f1 f1 --version 0.1.0
```
Output:
```
Pulled: f1dev.azurecr.io/helm/f1:0.1.0
Digest: sha256:001a5edb2a0ab36090b349f5a9ff6d60b2d4713de15c8a40e3be498b660be731
```

**Files that can reproduce the issue**

kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- chartInflator.yaml
```

chartInflator.yaml:
```yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: f1

# URL to the Repo
repo: "oci://f1dev.azurecr.io/helm/f1"

# The name of the chart to use
name: f1
version: 0.1.0

# Path to a values.yaml
valuesFile: kustom-values.yaml

# The name of the release
releaseName: f1dev
# Namespace to deploy to
releaseNamespace: f1
```

kustom-values.yaml
```yaml
(not relevant)
```

**Expected output**

The kustomize `kustomize --enable-helm` command that internally builds this `helm` command
```bash
helm pull --untar --untardir /opt/HutchMaster/SharedServer/k8s/f1/kustomize-overlays/dev/we/charts --repo oci://f1dev.azurecr.io/helm/f1 f1 --version 0.1.0
```
should be actually building it without the --repo flag:
```bash
helm pull --untar --untardir /opt/HutchMaster/SharedServer/k8s/f1/kustomize-overlays/dev/we/charts oci://f1dev.azurecr.io/helm/f1 f1 --version 0.1.0
```
then it works :)

**Actual output**

```
Error: Error: looks like "oci://f1dev.azurecr.io/helm/f1" is not a valid chart repository or cannot be reached: object required
```

**Kustomize version**

{Version:kustomize/v4.5.1 GitCommit:746bd18a8c0ba5768b4519778c82a5fb3e667466 BuildDate:2022-02-02T19:02:13Z GoOs:darwin GoArch:amd64}

**Helm version**

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

**Platform**

macOs 12.1 (Monterrey)
