### ISSUE TITLE
how to patch a file from other directory

### ISSUE THREAD

**Issue by shay-berman** [kubernetes-sigs/kustomize#4463]
Why kustomize cannot patch from a file in parent directory?

Looks like --load-restrictor LoadRestrictionsNone should help with it, but what its not clear what is the issue to use it.
Can anyone clarify what I will loose by using this flag?  (i have a patch i want to use in many places and i don't want to dup it, any other idea?)
` --load-restrictor="LoadRestrictionsRootOnly" if set to 'LoadRestrictionsNone', local kustomizations may load files from outside their root. This does, however, break the relocatability of the kustomization.
`

**Comment by KnVerey** [comment]
As the error message suggests, what you lose is the encapsulation of your Kustomizations--they would no longer be following the best practice of being self-contained. The recommendation is to retain that encapsulation by creating a Kustomization for the shared files and importing them as a base in the resources field. More context is available in the FAQ section of our docs: https://kubectl.docs.kubernetes.io/faq/kustomize/#security-file-foo-is-not-in-or-below-bar

**Comment by shay-berman** [comment]
@KnVerey but it means that if i have 10 shared patch and i want only 1 patch to apply then i need to create a dedicated directory for this 1 patch right?  because if i include all 10 patchs in the same folder with same kustomization it means it will run all the patchs.

**Comment by StephenPCG** [comment]
@shay-berman You can use [Kustomize Components](https://kubectl.docs.kubernetes.io/guides/config_management/components/)

This is my case:

```
├── base
│   ├── deployment.yaml
│   └── kustomization.yaml
├── components
│   ├── select-testing-node
│   │   └── kustomization.yaml
│   ├── select-staging-node
│   │   └── kustomization.yaml
│   │...
├── overlays
│   ├── testing/
│   │   └── kustomization.yaml
│   ├── staging/
│   │   └── kustomization.yaml
│   │...
```

This is content of components/select-testing-node/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      # applies to all deployments, no matter how many deployments the base resources provides
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: testing
```

If you have 10 shared patches which need to be applied selectively, you need to create 10 folders for them. But I think this is not a big burden. Bases and Components are two kind of sharing mechanisms, Bases are common fundamentals, and Components are like common patches.
