### ISSUE TITLE
replacements: Unable to add/create a new array element

### ISSUE THREAD

**Issue by jceb** [kubernetes-sigs/kustomize#4469]
**Describe the bug**

I'd like to copy the host name from an Ingress and use it in a newly created tls section. However, kustomize seems to be unable to create arrays to build the tls section.

**Files that can reproduce the issue**

ingress.yaml:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
    - host: myingress.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-svc
                port:
                  number: 80
```

kustomize.yaml:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

replacements:
  - source:
      kind: Ingress
      name: myingress
      fieldPath: spec.rules.0.host
    targets:
      - select:
          kind: Ingress
          name: myingress
        fieldPaths:
          - spec.tls.0.hosts.0
          - spec.tls.0.secretName
        options:
          create: true
```

**Expected output:**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
    - host: myingress.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-svc
                port:
                  number: 80
tls:
  - hosts:
    - myingress.example.com
    secretName: myingress.example.com
```

**Actual output:**

```
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '$PWD': wrong Node Kind for spec.tls expected: SequenceNode was MappingNode: value: {{}}"
```

**Workaround:**

Pre-create the tls structure, including a value in hosts, otherwise it won't create the entry.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
  - source:
      kind: Ingress
      name: myingress
      fieldPath: spec.rules.0.host
    targets:
      - select:
          kind: Ingress
          name: myingress
        fieldPaths:
          - spec.tls.0.hosts.0
          - spec.tls.0.secretName
        options:
          create: true
  tls:
    - hosts: ["dummy-entry-to-make-kustomize-replacements-work"]
```

**Expected output**

**Actual output**

**Kustomize version**

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6
", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"
archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.13", Comp
iler:"gc", Platform:"linux/amd64"}

**Additional context**

* Issue might be related to #4053
