### ISSUE TITLE
Quotes removed from containers' env variable values

### ISSUE THREAD

**Issue by stan-sz** [kubernetes-sigs/kustomize#4472]
**Describe the bug**

String quotes are dropped from env variable values in a deployment. This causes apply to fail with:

`Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of...`

**Files that can reproduce the issue**

* `kustomization.yaml`

```yaml
resources:
- resources.yaml
```

* `resources.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - env:
        - name: makesurethisstaysqouted
          value: "++makesurethisstaysqouted++"
```

**Expected output**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - env:
        - name: makesurethisstaysqouted
          value: "++makesurethisstaysqouted++"
```

**Actual output**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - env:
        - name: makesurethisstaysqouted
          value: ++makesurethisstaysqouted++
```

**Kustomize version**

`{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:26:42Z GoOs:windows GoArch:amd64}`

**Platform**

Windows

**Additional context**

Slightly related to #4421
