### ISSUE TITLE
ConfigMap generated hashes don't get replaced when using replacements

### ISSUE THREAD

**Issue by Shalucik** [kubernetes-sigs/kustomize#4475]
**Describe the bug**

I'm trying to replace vars with replacements.
I have a var that is used to give an Deployments env value the name of a ConfigMap created by a configMapGenerator

When using replacements for this, the env value is replaced without the generated hash suffix

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
 
configMapGenerator:
  - name: test
  
replacements:
  - source:
      kind: ConfigMap
      name: test
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: test
        fieldPaths:
          - spec.template.spec.containers.[name=test].env.[name=test].value
```

deployment.yaml

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          env:
            - name: test
              value: REPLACE
```
**Expected output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - env:
        - name: test
          value: test-6ct58987ht
        name: test
```

**Actual output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - env:
        - name: test
          value: test
        name: test
```

**Kustomize version**

4.5.2

**Platform**

Linux

**Additional context**
