### ISSUE TITLE
Ability to run `replacements` after `transformers`

### ISSUE THREAD

**Issue by GuyPaddock** [kubernetes-sigs/kustomize#4476]
### Describe the solution you'd like
Ideally, there would be a way for us to indicate that we want a replacement to run _after_ transformers have run, versus _before_.

We have created a transformer for Kustomize [that generates storage definitions](https://github.com/Inveniem/kustomize-storage-config-transformer) (e.g., PVs, PVCs, volumes, and volume mounts) from a set of templates and a static list of values, to handle the use case where several volumes and mounts can be dynamic but follow the sample basic recipe, such as when you have a multi-tenant situation.

For one of our applications, we need to be able to toggle whether a specific mount is read-only or not based on the value of a config map (e.g., during upgrades, the software being run needs its config volume to be writable, but for security and durability at all other times it needs to be read-only). For this situation, we'd normally use `replacements`, but since the mount in question gets added via our transformer, this doesn't work because the transformer runs _after_ `replacements` has run. 

### Describe alternatives you've considered
Without the ability to run `replacements` after `transformers`, we have three less-ideal options:
1. Re-implement what `replacements` does within our own transformer, greatly increasing the scope and complexity of our transformer; OR
2. Move the volume in question out of being generated by our transformer (creating a maintenance burden since we have two places to maintain similar storage config); OR
3. ~~Switch from using `replacements` to using the now-deprecated `vars`.~~ (Doesn't seem to work; the variables do not get replaced by `vars`, likely because the `readOnly` field on a mount is a boolean field and vars only works for strings).

**Comment by natasha41575** [comment]
You can run `replacements` _within_ the transformers field if you'd like, and if you want it to run after all your other transformers, you can place it last.

Here is an example if what that might look like:

kustomization.yaml:

```
transformers:
  - mytransformer1.yaml
  - |-
  apiVersion: builtin
  kind: ReplacementTransformer
  metadata:
    name: notImportantHere
  replacements:
    # your replacements here
```

Would this work for you?

/kind support
/triage needs-information

**Comment by GuyPaddock** [comment]
@natasha41575 Whoa... I did not realize that you could compose transformers like that! Is it documented?

**Comment by GuyPaddock** [comment]
@natasha41575 The yaml you provided does not parse. When I try to put it into its own file, the transformer fails to resolve config map references:
```
Error: nothing selected by ~G_~V_ConfigMap|~X|environment:data.configReadOnly
```

**Comment by natasha41575** [comment]
Ah I may have gotten something wrong with the indentation with the yaml I provided.

This isn't really documented anywhere... there is some stuff here: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/

And an example in one of our tests here: https://github.com/kubernetes-sigs/kustomize/blob/8dab94964f7a3e4e9700ba9bd3eaba333c29be37/api/krusty/legacyprefixsuffixtransformer_test.go#L18

This really should be documented somewhere, perhaps there should be a guide somewhere near the first link I sent. 

> I have to put a copy of this transformer Yaml file with replacements in every overlay.

Could you try following the indentation style in [this example](https://github.com/kubernetes-sigs/kustomize/blob/8dab94964f7a3e4e9700ba9bd3eaba333c29be37/api/krusty/legacyprefixsuffixtransformer_test.go#L18)? I think that should work. If not, we have a bug somewhere and a very strange one at that.

**Comment by GuyPaddock** [comment]
@natasha41575 That inline syntax works with that indentation; thank you!

I still have to copy the transformer between the various overlays b/c of the aforementioned "components run before transformers" piece, but this is definitely a lot closer to a solution! Thank you very much.

**Comment by natasha41575** [comment]
@GuyPaddock someone else made a similar request to control component ordering, we have KEPS open for a feature that will make it moot. Here is a comment explaining more with links: https://github.com/kubernetes-sigs/kustomize/issues/4345#issuecomment-1018671152

Unless you have further questions, I think this issue can be closed. Feel free to reopen if you think there needs to be further discussion.

**Comment by GuyPaddock** [comment]
Sounds good! Thanks

**Comment by jeanmorais** [comment]
@natasha41575 Can I get the name transformed in some way, following what you suggested above?

I have a transformer to add a `prefix` and I'd like to use the name with the prefix in the replacements after that, in some simpler way.
```yaml
transformers:
- nameprefix-transformer.yaml
- |-
  apiVersion: builtin
  kind: ReplacementTransformer
  metadata:
    name: notImportantHere
  replacements:
  - source:
      kind: Secret
      fieldPath: metadata.name
    targets:
    - select:
        kind: Pod
      fieldPaths:
      - metadata.annotations.[test.com/x]
```


```yaml
apiVersion: v1
kind: Secret
metadata:
  name: prefix-my-secret
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    test.com/x: my-secret # I'd like to put "prefix-my-secret" here
  name: prefix-my-pod
```

**Comment by natasha41575** [comment]
@jeanmorais 

Yeah, it's called `PrefixTransformer`. All of [the transformers here](https://github.com/kubernetes-sigs/kustomize/tree/master/plugin/builtin) work in the exact same way.

**Comment by natasha41575** [comment]
@GuyPaddock @jeanmorais If either of you two (or anyone else reading this) want to help document this, would highly appreciate it. A new guide here https://github.com/kubernetes-sigs/cli-experimental/tree/master/site/content/en/guides called "transformers" or something might be helpful. No pressure though, we

**Comment by jeanmorais** [comment]
> @jeanmorais
> 
> Yeah, it's called `PrefixTransformer`. All of [the transformers here](https://github.com/kubernetes-sigs/kustomize/tree/master/plugin/builtin) work in the exact same way.

First, thanks for the fast response. 

I've used `PrefixSuffixTransformer` (`nameprefix-transformer.yaml`) in the example above. But, the `ReplacementTransformer` is called before the transformation, this way, I can't get the name with the `prefix`+`metadata.name` to use in the `ReplacementTransformer`. There is some way to do that?

Following the example above, I get `metadata.name` without the prefix. There is some way to get `prefix`+`metadata.name`?
```yaml
  - source:
      kind: Secret
      fieldPath: metadata.name
 ```
