### ISSUE TITLE
[Question] Replacements: Match-Traversal where Key has '.' Dot in it

### ISSUE THREAD

**Issue by nickgarber** [kubernetes-sigs/kustomize#4480]
How would this [example](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#example) (reproduced here), work if we wanted to match on a key with a dot in it?

How could match-traversal be used field-key named `for.example`, for example?

### Snippet Excerpted from the Example in the Replacements documentation
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources.yaml
- job.yaml

replacements:
- path: my-replacement.yaml
- source:
    kind: Secret
    name: my-secret
  targets:
  - select:
      name: hello
      kind: Job
    fieldPaths:
    - spec.template.spec.containers.[name=hello].env.[name=SECRET_TOKEN].value  # the example in the documentation
    - spec.template.spec.containers.[name=for.example].env.[name=SECRET_TOKEN].value  # my question case
```

### Alternatives I've tried
- `[name=for\.example]`
- `[name="for.example"]`
- `[name='for.example']`
- `[name="for\.example"]`
- etc...
