### ISSUE TITLE
[FR] Support for multiple "ProposedValues" in a Result object

### ISSUE THREAD

**Issue by Goodwine** [kubernetes-sigs/kustomize#4482]
**Is your feature request related to a problem? Please describe.**

This is related to https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md
When generating `framework.Result` objects we are allowed to set a `CurrentValue` and choose a `ProposedValue`.

While the Spec doesn't mention it explicitly, IIUC the `ProposedValue` is meant to be used by a tool to automatically fix the issues in a file by replacing the value to the one set in `ProposedValue`.

For example if I have:
```yaml
weekend: monday # original
```
And my ProposedValue was "saturday", then this hypothetical tool would do:
```yaml
weekend: saturday # updated with ProposedValue
```

However in some usecases there could be multiple valid values that could have been proposed. (e.g. "saturday" and "sunday")
Today in order to support this use case I would need to generate 2 result objects like this:
```yaml
results:
  - message: "Invalid type. Expected: saturday or sunday, given: monday"
    severity: error
    resourceRef:
      apiVersion: example/v1
      kind: Week
      name: example
    field:
      path: spec.weekend
      currentValue: monday
      proposedValue: saturday # value 1 here
    file:
      path: example.yaml
  - message: "Invalid type. Expected: saturday or sunday, given: monday"
    severity: error
    resourceRef:
      apiVersion: example/v1
      kind: Week
      name: example
    field:
      path: spec.weekend
      currentValue: monday
      proposedValue: sunday # value 2 here
    file:
      path: example.yaml
```

This is probably OK but very verbose.

**Describe the solution you'd like**

Instead of `ProposedValue` I think this should be `ProposedValues` and made into an array of an object that matches `CurrentValue`.

In terms of Go..
```diff
type Field struct {
  // ...
  CurrentValue      interface{}
-  // ProposedValue is a value that will fix CurrentValue
-  ProposedValue    interface{}
+  // ProposedValues are a set of options for values that would fix CurrentValue
+  ProposedValues   []interface{}
}
```

[edit]

So the generated result would now look like:
```yaml
results:
  - message: "Invalid type. Expected: saturday or sunday, given: monday"
    severity: error
    resourceRef:
      apiVersion: example/v1
      kind: Week
      name: example
    field:
      path: spec.weekend
      currentValue: monday
      proposedValues:
      - saturday  # value 1 here
      - sunday    # value 2 here
    file:
      path: example.yaml
```
[/edit]

**Describe alternatives you've considered**

The status quo is fine but if that's the intended way it should be documented as such.
I'm happy to update the documentation if so.
