### ISSUE TITLE
The patch is not applied to the YAML anchor

### ISSUE THREAD

**Issue by martinkroupa** [kubernetes-sigs/kustomize#4483]
**Describe the bug**

Templating with patches[0].patch and YAML anchor stopped working properly in kustomize/v4.4.0.
The patch is not applied to the anchor and the value stays at the original value, e.g. "template.domain.com".

**Files that can reproduce the issue**

/tmp/test/kustomization.yaml

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ing-haproxy-test.yaml

patches:
  - target:
      kind: Ingress
      name: ing-haproxy-test
    patch: |-
      kind: Ingress
      metadata:
        name: ing-haproxy-test
      spec:
        tls:
          - hosts:
            - &dns_test new-test.domain.com
            secretName: cert-secret-test
```

/tmp/test/ing-haproxy-test.yaml

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-haproxy-test
  namespace: test
spec:
  tls:
    - hosts:
        - &dns_test template.domain.com
      secretName: cert-secret-test
  rules:
    - host: *dns_test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-test
                port:
                  number: 10000
```

...

**Expected output**
```
docker run -it --rm --volume /tmp/test:/tmp/ k8s.gcr.io/kustomize/kustomize:v4.5.2 build /tmp/
```
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-haproxy-test
  namespace: test
spec:
  rules:
  - host: new-test.domain.com
    http:
      paths:
      - backend:
          service:
            name: svc-test
            port:
              number: 10000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - new-test.domain.com
    secretName: cert-secret-test
```
**Actual output**

```
docker run -it --rm --volume /tmp/test:/tmp/ k8s.gcr.io/kustomize/kustomize:v4.5.2 build /tmp/
```
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-haproxy-test
  namespace: test
spec:
  rules:
  - host: template.domain.com
    http:
      paths:
      - backend:
          service:
            name: svc-test
            port:
              number: 10000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - new-test.domain.com
    secretName: cert-secret-test
```
**Kustomize version**

```
docker run -it --rm --volume /tmp/test:/tmp/ k8s.gcr.io/kustomize/kustomize:v4.5.2 version
```
```
{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:26:51Z GoOs:linux GoArch:amd64}
```

**Platform**
```
Linux 5.16.9-200.fc35.x86_64 #1 SMP PREEMPT Fri Feb 11 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**

The last working version is:
```
{Version:kustomize/v4.3.0 GitCommit:cd17338759ef64c14307991fd25d52259697f1fb BuildDate:2021-08-24T19:18:48Z GoOs:linux GoArch:amd64}
```
