### ISSUE TITLE
Filter PrefixSuffixTransformer on specific targets.

### ISSUE THREAD

**Issue by karlschriek** [kubernetes-sigs/kustomize#4490]
**Is your feature request related to a problem? Please describe.**

The current `PrefixSuffixTransformer` filters on `fieldSpecs` to identify which resources should be prefix/suffixed. Fieldspecs contains the following filtering criteria:

```yaml
    fieldSpecs:
    - kind: ConfigMap
      path: metadata/name
```

This will proceed to prefix/suffix _all_ `ConfigMaps` (and all references to them) with the same prefix/suffix. We would like to have the ability to filter this down to specific targets.

**Describe the solution you'd like**

Something that allows us to filter not just on the kind of resource, but also on its name. I.e., in the example below, the prefix/suffix would only be applied to `my-configmap` (and wherever it is referenced)

```yaml
    fieldSpecs:
    - kind: ConfigMap
      path: metadata/name
      name: my-configmap
```
