### ISSUE TITLE
images and patches in combination with bases Problem

### ISSUE THREAD

**Issue by AlessandroPerucchi** [kubernetes-sigs/kustomize#4492]
**Describe the bug**

We are using in kustomization.yaml the entry "images" to consolidate all our images version that are spread in several deployment files.
It is working fine. Until we used the "patches" on some of the deployment yaml, then the replacement of the image in the deployment with the entries in the images section is not done anymore.

I have found that if I don't use the 'bases' section it works, but with 'bases' it doesn't work.

**Files that can reproduce the issue**

base/kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: nfs-subdir-external-provisioner-image
    newName: k8s-staging-sig-storage/nfs-subdir-external-provisioner
    newTag: v4.0.2
```

test/kustomization.yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
  - nfs-deployment.yaml

patchesStrategicMerge:
  - myPatch.yaml
```

test/nfs-deployment.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-provisioner
          image: nfs-subdir-external-provisioner-image
          env:
            - name: NFS_PATH
              value: /test_path
```

test/myPatch.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-provisioner
          env:
            - name: NFS_PATH
              value: /new_path
```

**Expected output**

```
$ kustomize build test
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-provisioner
  name: nfs-provisioner
spec:
  template:
    spec:
      containers:
      - env:
        - name: NFS_PATH
          value: /new_path
        image: k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.2
        name: nfs-provisioner
```

**Actual output**

```
$ kustomize build test
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-provisioner
  name: nfs-provisioner
spec:
  template:
    spec:
      containers:
      - env:
        - name: NFS_PATH
          value: /new_path
        image: nfs-subdir-external-provisioner-image
        name: nfs-provisioner
```

**Kustomize version**

{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:26:42Z GoOs:darwin GoArch:amd64}

**Platform**

Linux and macOS

**Additional context**
