### ISSUE TITLE
Support `edit set configmap`

### ISSUE THREAD

**Issue by gaeljw** [kubernetes-sigs/kustomize#4493]
**Is your feature request related to a problem? Please describe.**

I have a deployment workflow that includes:
- generating a bunch of files (specific to application)
- define a `configMapGenerator` referencing those files in `kustomization.yaml`

The list of files is not static and might change (files removed or added), thus I want to automate this (everything is then committed to Git for a GitOps process).

Unfortunately if my `kustomization.yaml` already contains a `configMapGenerator`, I cannot overwrite it with `kustomize edit`: I can only add a new one.

-----

Let's take an example.

If I have this `kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: my-config
  files:
  - conf/file1.properties
```

I would like to have a `kustomize edit` command that allows me to change it to:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: my-config
  files:
  - conf/file1.properties
  - conf/file2.properties
```

**Describe the solution you'd like**

In the same spirit as other `kustomize edit set xxx` commands, something like `kustomize edit set configmap my-config --from-file=conf/*` would be perfect.

**Describe alternatives you've considered**

Only alternative is to manipulate the `kustomization.yaml` manually with any scripting tool.

**Additional context**
