### ISSUE TITLE
"$patch: delete" not working as expected

### ISSUE THREAD

**Issue by cten** [kubernetes-sigs/kustomize#4495]
**Describe the bug**

While trying to remove an element from a list, the output has all elements removed and the text from the patch added as the only element.

**Files that can reproduce the issue**

**Expected output**

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
  name: kubernetes-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - name: kube-apiserver-burnrate.rules
    rules:
    - expr: up
  - name: kube-apiserver-histogram.rules
    rules:
    - expr: up
```

**Actual output**

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
  name: kubernetes-monitoring-rules
  namespace: monitoring
spec:
  groups:
  - $patch: delete
    name: kubernetes-system-kube-proxy
```

**Kustomize version**

{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:darwin GoArch:amd64}

I have tried upgrading and downgrading same result (prefer to stick with v4.2.0 as that is the current version in our CICD) 

**Platform**

macOS

**Comment by KnVerey** [comment]
/triage needs-information

Can you please provide the input files (i.e. your Kustomization and patch) as well?

**Comment by KnVerey** [comment]
In @cten case, I think the issue has to do with the fact that the example targets a list in a CRD type for which no [openapi schema](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/) is provided. By default, lists are atomically replaced, not merged. So, in the absence of a schema indicating otherwise, Kustomize will replace the entire `groups` list, regardless of what's inside it (it never even sees the $patch key). Please try providing the appropriate schema via the [openapi field](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/).

For example, the same thing works fine for lists in a built-in type, for which Kustomize has the openapi built in:

```
# resources.yaml
---
apiVersion: v1
kind: PodTemplate
metadata:
  name: foo
template:
  spec:
    containers:
    - name: foo
    - name: bar

# kustomization.yaml 
resources:
- resources.yaml

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: PodTemplate
  metadata:
    name: foo
  template:
    spec:
      containers:
      - name: foo
        $patch: delete
      - name: bar

# result
---
apiVersion: v1
kind: PodTemplate
metadata:
  name: foo
template:
  spec:
    containers:
    - name: bar
```
