### ISSUE TITLE
Secret hash is not taken into account by spec.template.spec.volumes.azureFile.secretName

### ISSUE THREAD

**Issue by stefano-salari** [kubernetes-sigs/kustomize#4498]
When a deployment file volumes section makes use of {{azureFile}} definition, the {{secretName}} reference inside it, does not takes into account the secret hash generated by Kustomize.

**Files that can reproduce the issue**

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

secretGenerator:
- name: secret-credentials
  envs:
  - secret-credentials.env
```

secret-credentials.env
```
azurestorageaccountname=storage-account-name
azurestorageaccountkey=storage-account-key
```

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-deployment
    spec:
      containers:
      - name: test-deployment
        image: busybox
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: secret-credentials
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: azure-share
          mountPath: /test-share
      volumes:
      - name: azure-share
        azureFile:
          secretName: secret-credentials
          shareName: test-share
```

**Expected output**

The secret referenced in both the {{envFrom}} and {{secretName}} properties is expected to report the hash suffix created by the secret generator:
```
apiVersion: v1
data:
  azurestorageaccountkey: c3RvcmFnZS1hY2NvdW50LWtleQ==
  azurestorageaccountname: c3RvcmFnZS1hY2NvdW50LW5hbWU=
kind: Secret
metadata:
  name: secret-credentials-8b6bkhgkkb
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  [...]
  template:
    [...]
    spec:
      containers:
      - name: test-deployment
        envFrom:
        - secretRef:
            name: secret-credentials-8b6bkhgkkb
        [...]
      volumes:
      - azureFile:
          secretName: secret-credentials-8b6bkhgkkb
        [...]
```

**Actual output**

Here follows the whole output of the {{kustomize build}} command. Note that the {{spec.template.spec.volumes.azureFile.secretName}} does not references the actual secret name because is missing the generated hash:
```
apiVersion: v1
data:
  azurestorageaccountkey: c3RvcmFnZS1hY2NvdW50LWtleQ==
  azurestorageaccountname: c3RvcmFnZS1hY2NvdW50LW5hbWU=
kind: Secret
metadata:
  name: secret-credentials-8b6bkhgkkb
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-deployment
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: secret-credentials-8b6bkhgkkb
        image: busybox
        imagePullPolicy: IfNotPresent
        name: test-deployment
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /test-share
          name: azure-share
      volumes:
      - azureFile:
          secretName: secret-credentials
          shareName: test-share
        name: azure-share
```

**Kustomize version**

Reproduced with both kustomize v4.0.5 and v4.5.2:
{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:darwin GoArch:amd64}
{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:26:42Z GoOs:darwin GoArch:amd64}

**Platform**

Both Linux and macOS
