### ISSUE TITLE
Replacement filter documentation for array creation

### ISSUE THREAD

**Issue by lack** [kubernetes-sigs/kustomize#4507]
**Describe the bug**

Using a replacement filter with the create option set to true, one can create an arbitrarily deep map to the point where the target value is set. However, the tool cannot create arrays or append to arrays.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
replacements:
- source:
    kind: Pod
    name: pod
    fieldPath: spec.containers.0.image
  targets:
  - select:
      name: deploy1
    fieldPaths:
    - spec.template.spec.containers.0.image
    options:
      create: true
```

resources.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: busybox
    name: myapp-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
```

**Expected output**

```
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: busybox
    name: myapp-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  template:
    spec:
      containers:
      - image: busybox
```

**Actual output**

```
Error: wrong Node Kind for spec.template.spec.containers expected: SequenceNode was MappingNode: value: {{}}
```

**Kustomize version**

Built from master branch

git describe:
```
kustomize/v4.5.2-25-gf67dd5bbb
```

**Platform**

Linux
