### ISSUE TITLE
Merge lists?

### ISSUE THREAD

**Issue by dev-samples** [kubernetes-sigs/kustomize#4514]
In my base I have:

**base/deployment.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          containerEnv:
            - name: BASE_A
              value: "value-a"
            - name: BASE_B
              value: "value-b"
```

**base/kustomization.yaml**
```
resources:
- deployment.yaml
```

In my overlay I have:

**overlay/deployment.yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          containerEnv:
            - name: OVERLAY_X
              value: "value-x"
            - name: OVERLAY_Y
              value: "value-y"
```
**overlay/kustomization.yaml**

```
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
```

But when I build its only the ENVs from the overlay that gets generated:

```
kustomize build .
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ldap
  name: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - containerEnv:
        - name: OVERLAY_X
          value: value-x
        - name: OVERLAY_Y
          value: value-y
        name: ldap

```
How do I merge lists?

Possibly related:
https://github.com/fluxcd/helm-controller/issues/300

**Comment by KnVerey** [comment]
The field name is `env`, not `containerEnv`. I've confirmed that the merge works as expected with that fixed.

/close
/kind support

**Comment by dev-samples** [comment]
Yes you are right works as expected. The example I provided was not really clear, sorry for that. I am trying to patch this values file:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml

in a flux release.  E.g with this base:

**base/kustomization.yaml**
```
resources:
- release.yaml

```
**base/release.yaml**
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: jenkins
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 3.11.4
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    rbac:
      create: true
      readSecrets: true   
    controller:
      containerEnv:
        - name: BASE_VAR_A
          value: "base-value-a"
        - name: BASE_VAR_B
          value: "base-value-b"

```
And this overlay.

**dev/kustomization.yaml**

```
resources:
- ../base
patchesStrategicMerge:
- release.yaml

```
**dev/release.yaml**
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: jenkins
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 3.11.4
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    rbac:
      create: true
      readSecrets: true   
    controller:
      containerEnv:
        - name: OVERLAY_X
          value: "overlay-value-a"
        - name: OVERLAY_Y
          value: "overlay-value-b"

```
But when I run build I get:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: jenkins
  namespace: jenkins
spec:
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      version: 3.11.4
  interval: 5m
  releaseName: jenkins
  values:
    controller:
      containerEnv:
      - name: OVERLAY_X
        value: overlay-value-a
      - name: OVERLAY_Y
        value: overlay-value-b
    rbac:
      create: true
      readSecrets: true

```

So the base values are gone. I am sure I am missing something basic here maybe that kustomize is not working with arbitrary values files?
