### ISSUE TITLE
failed to find unique target for patch ~G_v1_Service

### ISSUE THREAD

**Issue by jobinjosem** [kubernetes-sigs/kustomize#4522]
Unable to patch namespace name using patchesStrategicMerge

I have a service.yaml file which creates a service in Kubernetes. The namespace value in the resource file is a placeholder and I a mtrying to patch the namespace name using the patch, It was working with an older version of Kustomize but suddenly after upgrading customize it stopped working.
Current version: Version:kustomize/v4.2.0

Example:
├── lab
│   ├── [kustomization.yaml]  Kustomization
│   └── [patch-namespace.yaml]  Service lab/example-service
└── manifests
    ├── [kustomization.yaml]  Kustomization
    └── [service.yaml]  Service example-service.

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../manifests

patchesStrategicMerge:
  - patch-namespace.yaml
```
patch-namespace.yaml

```
kind: Service
apiVersion: v1
metadata:
  name:  example-service
  namespace: lab
```
kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
```
service.yaml
```
kind: Service
apiVersion: v1
metadata:
  name:  example-service
  namespace: changeme
  selector:
    app:  example-app
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080
```

**Expected output**

Running Kustomize build generates all the manifests with correct namespace value

**Actual output**

Error: no matches for Id ~G_v1_Service|lab|example-service; failed to find unique target for patch ~G_v1_Service|example-service

**Kustomize version**

Version:kustomize/v4.2.0

**Platform**

Ubuntu 20.04

**Comment by natasha41575** [comment]
>  It was working with an older version of Kustomize

Which version did this work with?

**Comment by jobinjosem** [comment]
@natasha41575 Unfortunately I do not have the old version number. That was something I installed a few months back.

**Comment by KnVerey** [comment]
I can't speak to the full history of the project, but this behaviour seems correct to me and has been present at least as far back as v4.0.5, which was released over a year ago. An object in a different namespace is not the same object, so the patch does not match the base you're intending it to operate on. You can explicitly target the other namespace if you use the patches field, but you cannot use the patch to change the namespace. 

```
namespace: lab

patches:
- path: deployment.yaml
  target:
    namespace: changeme
```
