### ISSUE TITLE
replacements updating metadata.name does not "trigger ?" nameReference transformer

### ISSUE THREAD

**Issue by tornike** [kubernetes-sigs/kustomize#4524]
**Describe the bug**

When changing resource's name with patch, e.g:
```
patches:
  - target:
      kind: ConfigMap
      name: cfg
    patch: |-
      - op: replace
        path: /metadata/name
        value: new-cfg
```
it's references are also updated in other resources for example in Pods. I was expecting same behavior with replacements, but turns out it does not work that way.

**Example files**

[replacements-bug.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/8328176/replacements-bug.tar.gz)

Running **kustomize build** on the provided _over/_ dir gives output:

```
apiVersion: v1
data:
  name: new-svc
kind: ConfigMap
metadata:
  name: build-vars
---
apiVersion: v1
kind: Service
metadata:
  name: new-svc
spec:
  ports:
  - port: 80
  selector: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    key: value
  name: ing
spec:
  rules:
  - host: example
    http:
      paths:
      - backend:
          service:
            name: svc
            port:
              number: 80
        path: /
```

But the expected output is:

```
apiVersion: v1
data:
  name: new-svc
kind: ConfigMap
metadata:
  name: build-vars
---
apiVersion: v1
kind: Service
metadata:
  name: new-svc
spec:
  ports:
  - port: 80
  selector: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    key: value
  name: ing
spec:
  rules:
  - host: example
    http:
      paths:
      - backend:
          service:
            name: new-svc
            port:
              number: 80
        path: /
```
where service reference in ingress is also updated.

**Additional context and maybe workaround**

I have no idea how Name reference transformer works, I couldn't find any doc except this one https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#name-reference-transformer. My guess is that if name reference transformer is "triggered"(I don't know if triggering transformer is the correct term), it's applied as the last transformer and updates resource's references in referrers accordingly. I think so, because it's enough to change Service name also by some other way, for example by adding dummy prefix and I get the expected output, Service with the name **new-svc** and it's reference updated in ingress.

**Kustomize Version**
Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:26:42Z GoOs:linux GoArch:amd64

**Platform**
Ubuntu 20.04.4
