### ISSUE TITLE
Env variables are surrounded by double quotes

### ISSUE THREAD

**Issue by meyerhp** [kubernetes-sigs/kustomize#4525]
Extra quotes are added when env variables are already surrounded by quotes. This issue is similar to [460](https://github.com/kubernetes-sigs/kustomize/issues/460) but with configMapGenerator instead of SecretGenerator

.env
```.env
SAMPLE="Sample var"
```

Data output
```yaml
SAMPLE: '"Sample var"'
```

Config map generator
```yaml
configMapGenerator:
  - name: env-config
    behavior: merge
    envs:
      - .env
```

**Expected output**

Env variables should be left as is

**Kustomize version**

{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:19:28Z GoOs:darwin GoArch:amd64}

**Platform**

macOS/Linux

**Comment by annasong20** [comment]
I'm able to reproduce this issue on my mac both with kustomize v4.5.2 and on the current master. My exact setup is similar to the above:

simple.env
```yaml
SAMPLE="Sample var"
```

kustomization.yaml
```yaml
configMapGenerator:
- name: env-config
  envs:
  - simple.env
```

producing the following output:
```yaml
apiVersion: v1
data:
  SAMPLE: '"Sample var"'
kind: ConfigMap
metadata:
  name: env-config-hdg5tmcf2m
```

**Comment by annasong20** [comment]
This is probably a bug because 
1. the [discussion in #460](https://github.com/kubernetes-sigs/kustomize/issues/460#issuecomment-430838214) leans towards kustomize being ignorant of quotation marks
2. `secretGenerator` doesn't add or remove quotes for `envs`

I replicated the setup in [#460](https://github.com/kubernetes-sigs/kustomize/issues/460). On kustomize v4.5.2 and master on mac, I have

simple.env
```yaml
FOO="VAR1"
BAR="VAR2"
```

kustomization.yaml
```yaml
secretGenerator:
- name: env-config
  envs:
  - simple.env
```

producing the following output:
```yaml
apiVersion: v1
data:
  BAR: IlZBUjIi   # "VAR2"
  FOO: IlZBUjEi # "VAR1"
kind: Secret
metadata:
  name: env-config-dcbmd5dtfm
type: Opaque
```
