### ISSUE TITLE
[Question] delete multiple resources with a patch

### ISSUE THREAD

**Issue by abarisuzuner** [kubernetes-sigs/kustomize#4526]
Hi,

I am trying to delete some resources in an overlay with a patch. I basically want to delete everything starting with a certain prefix. This doesn't work because it cannot find a certain resource and I guess regex is not accepted here.

```
patches:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: foo-*
  $patch: delete
```

I tried to do it by adding a target which accepts regex but this also didn't work:
```
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: foo-.*
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: does-not-matter
    $patch: delete
```

Is there any way to do this?

Thanks!
