### ISSUE TITLE
create operator group in current namespace

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-sigs/kustomize#4544]
when creating operatorgroup.yaml:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: test
spec:
  targetNamespace:
  - test
```
and next kustomization.yaml:
```yaml
namespace: test2

resources:
- operatorgroup.yaml
```

the naemspace of the OG is being updated, but the `targetNamespaces` still remains the same

---

i also tried to use vars.
kustomization.yaml:
```yaml
namespace: test2

vars:
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: namespace
    name: test

resources:
- operatorgroup.yaml
- namespace.yaml
```

namespace.yaml:
```yaml
apiVersion: v1
kind: namespace
metadata:
  name: test
```
operatorgroup.yaml:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: test
spec:
  targetNamespace:
  - $(NAMESPACE)
```

but it didnt replaced the string and nothing was injected.

i also tried to do `- \$(NAMESPACE)` instead of `- $(NAMESPACE)` but then i got error:
```
.... found unknown escape character: got file operatorgroup.yaml, but operatorgroup.yaml must be a directory to be a root
```

---

how can i create operator group by using the `namespace: ` in the kustomization.yaml file?

**Comment by KnVerey** [comment]
In order for the namespace transformer to target additional fields in a custom resource, you will need to configure it using the configurations field: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md. Alternatively, you can do the change more manually using [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) or [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/). We do not recommend using Vars, which are deprecated.

/kind support

**Comment by zfrhv** [comment]
@KnVerey oh thats pretty cool

sorry i somehow missed the notification and didnt knew i got a reply :0

i needed this for argocd, but then kustomize was too limited and a little difficult to use, so i just made a job that creates the operator group.

but i really like the configurations fields solution.

very likely i will fix it in the future.

thanks a lot !

**Comment by zfrhv** [comment]
hello, 
i saw the [configuration fields for the CRD](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md) and there is no `namespaceReference`.

the only thing i could find is that in the [docs](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs) they told that there are default transformers, and one if them is `namespace`.
but they didnt told how can i create new namespace transformer. it also seems not possible.

because [here](https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namespace.go) they use `namespace:`, but if i will do:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
- group: operators.coreos.com
  kind: OperatorGroup
  path: spec/targetNamespaces/0
  create: true
```
then it will give me an error that the `namespace` field must be the name of the namespace for the instances and not an array (it expects string)

so the namespace transformer / `namespaceReference` seems to not exist

---

i also dont want to use the [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) or [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/), because i mention the namespace from the argocd. and if it will put it in the kustomize file it will be more hardcoded and i wont be able to use this kustomize / whole application for other namespaces.

---

i still wish to create the OperatorGroup via kustomize and not kubernetes job

so any help with be much appreciated !

**Comment by KnVerey** [comment]
> then it will give me an error that the namespace field must be the name of the namespace for the instances and not an array (it expects string)

Ah yes, the namespace transformer field specs don't support array targets currently. Looking at the example again, I'm not sure that would be the right approach anyway, since the field can contain multiple namespaces, and there's nothing to guarantee the one you want to change will be at index zero.

A better approach could be to use the [name reference transformer](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#name-reference-transformer). This seems to work the way you want:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml

configurations:
  - config.yaml

namespace: updated
```

```yaml
# resources.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: test
spec:
  targetNamespaces:
  - test
  - leave-me
```

```yaml
# config.yaml
nameReference:
- kind: Namespace
  fieldSpecs:
  - group: operators.coreos.com
    kind: OperatorGroup
    path: spec/targetNamespaces
    create: true
```

Produces:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: updated
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: test
  namespace: updated
spec:
  targetNamespaces:
  - updated
  - leave-me
```

Note that to use it for real, you'll need to re-specify [the defaults](https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/namereference.go) as well, unless there's nothing else whose name you need transformed at that layer. https://github.com/kubernetes-sigs/kustomize/issues/4404 is the underlying issue for that fact.
