### ISSUE TITLE
Replacements Transformer: Replace All Instances does not work with create:True

### ISSUE THREAD

**Issue by vsabella** [kubernetes-sigs/kustomize#4561]
When attempting this replacement with wildcard * it fails with
kustomize v4.5.4
```
Error: accumulating components: 
accumulateDirectory: "recursed accumulation of path '/envoyfilter-transformer/istio-1.12': 

accumulating components: accumulateDirectory: \"recursed accumulation of path '/envoyfilter-transformer/base': 
  wrong Node Kind for spec.configPatches expected: MappingNode was SequenceNode: value: 
```

```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: istio-version
      fieldPath: data.ISTIO_REGEX
    targets:
      - select:
          kind: EnvoyFilter
        fieldPaths:
          - spec.configPatches.*.match.proxy.proxyVersion
          #- spec.configPatches.0.match.proxy.proxyVersion

        options:
          create: true
```

```
---
# https://docs.fastly.com/signalsciences/install-guides/kubernetes/kubernetes-istio/
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: axon-sigsci
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_FIRST
        value:
          name: my.ext_authz
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz"
            transport_api_version: V3
            failure_mode_allow: true
            with_request_body:
              max_request_bytes: 16384
              allow_partial_message: true
            grpc_service:
              envoy_grpc:
                cluster_name: my-cluster
    - applyTo: CLUSTER
      patch:
        operation: ADD
        value:
          name: my-cluster
          type: STRICT_DNS
          connect_timeout: 0.5s
          http2_protocol_options: {}
          load_assignment:
            cluster_name: my-cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: my-address
                          port_value: 1234
```
