### ISSUE TITLE
Repeating Custom Generator doesn't throw error

### ISSUE THREAD

**Issue by CandiedCode** [kubernetes-sigs/kustomize#4562]
**Describe the bug**
If kustomize generators don't support specifying the same generator multiple times, I expect an error to be thrown.

**Files that can reproduce the issue**

SGGenerator takes a json config file and generates a k8s manifest.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
- |-
  apiVersion: generators.protopia/v1
  kind: SGGenerator
  metadata:
    name: SGGenerator
    annotations:
      config.kubernetes.io/function: |
        container:
          image: stained-glass-kustomize-plugin:latest
  spec:
    projectName: Experiment_1
    image: 'experiments:535df8d'
    configPath: /workspace/config_1.json
- |-
  apiVersion: generators.protopia/v1
  kind: SGGenerator
  metadata:
    name: SGGenerator
    annotations:
      config.kubernetes.io/function: |
        container:
          image: stained-glass-kustomize-plugin:latest
  spec:
    projectName: Experiment_2
    image: 'experiments:535df8d'
    configPath: /workspace/config_aws.json
```

**Expected output**

I expect two instances of the container krm function to run for the two different specs returning two combined kubernetes manifests.  Or I expect an error to be thrown that does not allow specifying the same generator api/kind multiple times.

**Actual output**

If I comment out one of the generators at a time and run them in series, they both return expected results, but when combined into one file, only the first instance of the spec is run and generated.  If I change the API version in the generator from apiVersion: generators.protopia/v1 to apiVersion: generators.protopia/v2 for one of the instances, then they both will run.

**Kustomize version**
```shell
kustomize version
{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:06:20Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOS 12.3
**Additional context**

Doing some debugging,
https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/target/kusttarget.go#L291-L307

 kt.kustomization.Generators returns both expected generators.
 I think the issue maybe in 
 ```golang
	// AppendAll appends another ResMap to self,
	// failing on any OrgId collision.
	AppendAll(ResMap) error
```
but not sure why an error isn't thrown yet.

Also my generator plugin does not suppress error messages
```golang
package main

import (
...
)
var (
	//go:embed templates/kubernetes_manifest.template.yaml
	kubernetesTemplate string
	generatorSpec      = new(generator.SGGenerator)
)

func preProcessFilter(items []*yaml.RNode) ([]*yaml.RNode, error) {
	return items, generatorSpec.Populate()
}

func main() {
	p := framework.TemplateProcessor{
		TemplateData:      generatorSpec,
		PreProcessFilters: []kio.Filter{kio.FilterFunc(preProcessFilter)},
		ResourceTemplates: []framework.ResourceTemplate{{
			Templates: parser.TemplateStrings(kubernetesTemplate),
		}},
	}

	cmd := command.Build(p, command.StandaloneDisabled, false)
	command.AddGenerateDockerfile(cmd)

	if err := cmd.Execute(); err != nil {
		os.Exit(1)
	}
}
```
