### ISSUE TITLE
configMapGenerator: double quote handling incorrect when generating a config map from properties file

### ISSUE THREAD

**Issue by kingofdisasterr** [kubernetes-sigs/kustomize#4570]
**Description**

The configMapGenerator handles double quotes wrong when a config map is generated from a properties file.
When double quotes or single quotes are provided in the properties file, they should be kept in the output. If necessary, kustomize should add single quotes to the output, i.e. when the property value begins with a space character.
Reserved yaml words should be surrounded with double quotes -> works as expected.
Numbers with leading 0 should be treated as string and therefore surrounded with double quotes. Numbers without leading 0 should be kept as number in the output.

**Files that can reproduce the issue**

base/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: app-config-map
    envs:
      - application.env
```

base/application.env
```
app.base.name=appName
```

overlay/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: app-config-map
    envs:
      - application-overlay.env
    behavior: merge
```

overlay/application-overlay.env
```
spring.datasource.h2db.url1="jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA"
spring.datasource.h2db.url2='jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA'
spring.datasource.h2db.url3=jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA
spring.datasource.h2db.url4= jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA
test.007=007
test.7=7
```

**Expected output**

```
apiVersion: v1
data:
  app.base.name: appName
  spring.datasource.h2db.url1: "jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA"
  spring.datasource.h2db.url2: 'jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA'
  spring.datasource.h2db.url3: jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA
  spring.datasource.h2db.url4: ' jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA'
  test.7: 7
  test.007: "007"
kind: ConfigMap
metadata:
  name: app-config-map-c6k5f8b75g
```

**Actual output**

```
apiVersion: v1
data:
  app.base.name: appName
  spring.datasource.h2db.url1: '"jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA"'
  spring.datasource.h2db.url2: '''jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA'''
  spring.datasource.h2db.url3: jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA
  spring.datasource.h2db.url4: ' jdbc:h2:tcp://appl-svc.appl-e1.svc.cluster.local:9050/h2db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;INIT=CREATE
    SCHEMA IF NOT EXISTS APP_SCHEMA\\;SET SCHEMA APP_SCHEMA'
  test.7: "7"
  test.007: "007"
kind: ConfigMap
metadata:
  name: app-config-map-c6k5f8b75g
```

**Kustomize version**
$ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:windows GoArch:amd64}

**Platform**
Windows

**Additional context**

The problem described leads to problems in a spring boot application. When starting the application, the database connection fails because of missing double quotes in the config map. This leads spring to cut the connection string after the first semicolon.
