### ISSUE TITLE
Kustomize not applying patches to StorageClass

### ISSUE THREAD

**Issue by eric-musliner** [kubernetes-sigs/kustomize#4580]
**Describe the bug**

Kustomize is not applying patches to StorageClass resources types

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-driver.yml

- patch: |-
     - op: add
        path: /parameters/fileSystemId
        value: prod-fs-id
    target:
      namespace: default
      kind: StorageClass
      version: storage.k8s.io/v1
      name: efs-sc

```

aws-driver.yml

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  basePath: "/storage"

```

**Expected output**

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: prod-fs-id
  directoryPerms: "700"
  basePath: "/storage"

```

**Actual output**

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  basePath: "/storage"

```

**Kustomize version**

{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:06:20Z GoOs:darwin GoArch:arm64}

**Platform**

macOS

**Additional context**

Tried applying this patch a number of ways in a number of different permutations. Kustomize doesn't pick apply any change when running `kubectl apply -k environments/production`
