### ISSUE TITLE
How to override images stanza from base in any overlay?

### ISSUE THREAD

**Issue by pentago** [kubernetes-sigs/kustomize#4581]
I'm figuring out a gitops workflow and want to know if it's possible to define a set of `images` in the `base` but to be able to override those images in any or all overlays, like this:

**base:**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: BACKEND_IMAGE
    newName: ghcr.io/user/backend
    newTag: wwwwwww
  - name: FRONTEND_IMAGE
    newName: ghcr.io/user/frontend
    newTag: xxxxxxx

```

**dev overlay:**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: BACKEND_IMAGE
    newName: ghcr.io/user/backend
    newTag: yyyyyyy
  - name: FRONTEND_IMAGE
    newName: ghcr.io/user/frontend
    newTag: zzzzzzz

```

Currently, it's possible to have different `images` stanzas in each overlay but it must not be present already in the base.
Not sure why is that but wouldn’t it be useful to be able to override `images` stanza from the base in any overlay too?

**Comment by annasong20** [comment]
I'm not quite sure what your setup is and how you want kustomize to behave differently. To the best of my understanding, your setup is:

`./base/deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  template:
    spec:
      containers:
      - name: backend
        image: BACKEND_IMAGE:8
      - name: frontend
        image: FRONTEND_IMAGE:1.7.9
```

`./base/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: BACKEND_IMAGE
    newName: ghcr.io/user/backend
    newTag: wwwwwww
  - name: FRONTEND_IMAGE
    newName: ghcr.io/user/frontend
    newTag: xxxxxxx
```

`./overlay/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
  - name: BACKEND_IMAGE
    newName: ghcr.io/user/backend
    newTag: yyyyyyy
  - name: FRONTEND_IMAGE
    newName: ghcr.io/user/frontend
    newTag: zzzzzzz
```

for which I get the following output using kustomize v4.5.7
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/user/backend:wwwwwww
        name: backend
      - image: ghcr.io/user/frontend:xxxxxxx
        name: frontend
```

I believe this is the expected output because by the time you reference `base` with `overlay`, you've already changed the names of the images from `BACKEND_IMAGE` and `FRONTEND_IMAGE` to `ghcr.io/user/backend` and `ghcr.io/user/frontend`, respectively. The `overlay` kustomization will not find any images with the `name`s you specify, and thus we see the output of `base`.

**Comment by annasong20** [comment]
If you want kustomize to further modify the tags in `overlay`, you can change `overlay/kustomization.yaml` to specify the new names as follows:

`overlay/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
  - name: ghcr.io/user/backend
    newTag: yyyyyyy
  - name: ghcr.io/user/frontend
    newTag: zzzzzzz
```

and your output will be
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/user/backend:yyyyyyy
        name: backend
      - image: ghcr.io/user/frontend:zzzzzzz
        name: frontend
```

If I'm misinterpreting your question, please provide more information including all inputs, expected output, and actual output.
