### ISSUE TITLE
[Question] Possible to have multiple components that merge / patch on the same list? Last component applied overwrites any previous component patches

### ISSUE THREAD

**Issue by jketcham** [kubernetes-sigs/kustomize#4584]
I would like to have a base `Deployment` config with a series of `components` that can add values to `tolerations` and `nodeAffinity` selectors, but when I include two components that try to patch/merge on the same list, the last component that is applied overwrites the previous component's patch.

I'm essentially trying to achieve the same functionality as outlined in the [docs for components](https://github.com/kubernetes-sigs/kustomize/blob/a464ed0c594bc67a1254855d32485d97092f8555/examples/components.md).

## `base-deployment`:

`bases/deployment/deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      serviceAccountName: app-sa
```

And two components, `run-type-restricted` and `run-type-off-demand`:

## `run-type-restricted`

`bases/deployment/components/run-type-restricted/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
- patch.yaml
```

`bases/deployment/components/run-type-restricted/patch.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      tolerations:
      - key: "run-type"
        operator: "Equal"
        value: "restricted"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: run-type
                operator: In
                values:
                - restricted
```

## `run-type-off-demand`

`bases/deployment/components/run-type-off-demand/kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
- patch.yaml
```

`bases/deployment/components/run-type-off-demand/patch.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      tolerations:
      - key: "run-type"
        operator: "Equal"
        value: "off-demand"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: run-type
                operator: In
                values:
                - off-demand
```

Now when I try to use them in the base deployment for an app, the last component applied overwrites the previous component patches:

## `descendant-deployment`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../some-deployment

components:
- ../../../deployment/components/run-type-restricted
- ../../../deployment/components/run-type-off-demand
```

# Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: descendant-deployment-app
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: run-type
                operator: In
                values:
                - off-demand
      serviceAccountName: descendant-deployment-app-sa
      tolerations:
      - effect: NoSchedule
        key: run-type
        operator: Equal
        value: off-demand
```

# Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: descendant-deployment-app
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: run-type
                operator: In
                values:
                - restricted
            - matchExpressions:
              - key: run-type
                operator: In
                values:
                - off-demand
      serviceAccountName: descendant-deployment-app-sa
      tolerations:
      - effect: NoSchedule
        key: run-type
        operator: Equal
        value: restricted
      - effect: NoSchedule
        key: run-type
        operator: Equal
        value: off-demand
```

Is this something that should be possible? Or would I need to create multiple base deployments to achieve this?

I've tried this with json patching, but the spec defines that it's not possible to add to a list that doesn't exist yet, and it's not possible to define an empty list for `affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms` (a value is required).

Thanks for taking a look!
