### ISSUE TITLE
Run Generators before Replacements (or give us the option to)

### ISSUE THREAD

**Issue by SelfhostedPro** [kubernetes-sigs/kustomize#4585]
**Describe the bug**
Currently I have a configMap that I'm using a system environment variable to generate which I'd like to use with a replacement in order to replace the ingress field for when my application is deployed. The CD that I'm using allows me to set the environment variable and the configMapGenerator correctly builds said configMap. 

I just am unable to use a value from the configMapGenerator with a replacement in order to dynamically replace a field with the environment variable that I'm setting.

**Files that can reproduce the issue**

Example:
command: `NAMESPACE=test kustomize build /path/to/folder`

kustomization.yaml

```yaml
bases:
  - kowl-ingress.yaml

configMapGenerator:
  - name: namespace-var
    env: ingress.properties

replacements:
  - path: namespace-replacement.yaml

generatorOptions:
 disableNameSuffixHash: true
 labels:
   kustomize.generated.resource: "true"
```

namespace-replacement.yaml
```yaml
source:
  kind: Configmap
  name: namespace-var
  fieldPath: data.NAMESPACE
  version: v1
targets:
- select:
    name: kowl-ingress
```

ingress.properties:
```
NAMESPACE
```

kowl-ingress.yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kowl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - kowl.$(NAMESPACE).sandbox.acme.co #shouldn't matter if this is invalid as it should be replaced.
      secretName: kowl-tls
  rules:
    - host: kowl.$(NAMESPACE).sandbox.acme.co
      http:
        paths:
          - backend:
              serviceName: kowl
              servicePort: http
```

**Expected output**

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  name: kowl-ingress
spec:
  rules:
  - host: kowl.test.sandbox.acme.co
    http:
      paths:
      - backend:
          serviceName: kowl
          servicePort: http
  tls:
  - hosts:
    - kowl.test.sandbox.acme.co
    secretName: kowl-tls
```

**Actual output**

`Error: nothing selected by Configmap.v1.[noGrp]/namespace-var.[noNs]:data.NAMESPACE`

**Kustomize version**

```
{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:06:20Z GoOs:darwin GoArch:arm64}
```

**Platform**

M1 Macbook Pro

**Additional context**

I'm thinking that kustomize is trying to run the replace before the configmap generator runs which is why it can't find the correct configmap. If there's a way to set the replace to run after the configmap is generated this would resolve my issue.

The reason I'm trying to do this is in order to allow developers to spin up a sandbox environment by making a pull request to a github repo. Argocd applicationsets allows me to do the deployment but I'm having some trouble substituting the ingress to allow devs to see and interact with their sandbox (this also will allow me to create the required environment variable dynamically).

If there's a way to do this that I'm missing, I'd be happy to try out alternatives but this would enable an amazingly productive workflow for developers.

**Comment by natasha41575** [comment]
There is a typo in your replacements:

```
source:
  kind: Configmap # <-- this needs to be ConfigMap
  name: namespace-var
  fieldPath: data.NAMESPACE
  version: v1
targets:
- select:
    name: kowl-ingress
```

Generators already do run before replacements. 

I verified that fixing the typo causes the replacements issue to go away, but throws another error that I'm unable to decipher. Please file a separate issue if you are unable to resolve the new error.
