### ISSUE TITLE
configMapGenerator - Error: json: unknown field "generatorOptions"

### ISSUE THREAD

**Issue by TheRealDwright** [kubernetes-sigs/kustomize#4595]
**Describe the bug**

When running kustomize build with a configmap generator, if wanting to disable the name suffix hash, the [Kustomize documentation](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#generatoroptions) suggests using the flag `generatorOptions` however this needs to be `options`

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: deploy-info
  generatorOptions:
    disableNameSuffixHash: true
  behavior: create
  literals:
  - foo=bar
```

**Expected output**

```
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  name: deploy-info
```

**Actual output**

`Error: json: unknown field "generatorOptions"`

**Kustomize version**

v4.5.4

**Platform**

macOS
