### ISSUE TITLE
[Bug] : Cannot reference a generated configMap to a Deployment if namespace ends with the same suffix as defined nameSuffix

### ISSUE THREAD

**Issue by William-LP** [kubernetes-sigs/kustomize#4597]
Hi there ! I don't know if that's a question or a bug but here you go :

I've got a `base` folder with a **deployment.yaml** like this :

```yaml
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-frontend
spec:
  replicas: 1
  template:   
    spec:
      containers:
        - name: my-frontend
          image: container.registry.io/my-frontend
          ports:
          - containerPort: 80
```

and a basic **kustomization.yaml** :

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
``` 

From another folder, I reference this base with the following kustomization file :

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whatever-dev # THOSE TWO LINES 
nameSuffix: -dev  #  DON'T WORK TOGETHER
configMapGenerator:
- name: config-frontend
  envs:
  - config.env
patchesStrategicMerge:
- deployment_patch.yaml
commonLabels:
    app: my-frontend
    env: dev
    tier: frontend
resources:
- dep.yaml
bases:
- ../base/
```
I have my deployement patch  :

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
spec:
  template:
    metadata:
    spec:
      containers:
      - name: my-frontend
        envFrom:
        - configMapRef: 
            name: config-frontend
```
and my **config.env**, source of the configMap :

```
FOO=BAR
```

The problem is, if I have a namespace `whatever-dev` and a nameSuffix `-dev` defined in the kustomization.yaml (see third block of code), the deployement DO NOT reference the generated configMap. As soon as I rename the suffix/namespace, it works just fine.

Is it an intended behavior ? If yes, how can I get my deployment to reference the generated configMap ?
