### ISSUE TITLE
ReplacementTransformer does not trigger NameReferenceTransformer

### ISSUE THREAD

**Issue by cconnert** [kubernetes-sigs/kustomize#4599]
**Describe the bug**

I aim to change the namespace of the cert-manager install manifest. Due to RBAC a standard namespace transformation is not applicable. Thus I use a combination of:

- A inline patch to change the Namespace resource
- The ReplacementTransformer to update relevant fields

But for some reason not all name references are updated, as I would expect. In my example Kustomize fails to update the clientConfig/service/namespace fields of ValidatingWebhookConfiguration & MutatingWebhookConfiguration.

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml

patches: 
  - target:
      kind: Namespace
      name: cert-manager
    patch: |-
      - op: replace
        path: /metadata/name
        value: changed

transformers:
  - |-
    apiVersion: builtin
    kind: ReplacementTransformer
    metadata:
      name: does-not-matter
    replacements:
      - source:
          kind: Namespace
          fieldPath: metadata.name
        targets:
          - select:
              kind: RoleBinding
            fieldPaths:
               - subjects.[namespace=cert-manager].namespace
          - select:
              kind: ClusterRoleBinding
            fieldPaths:
              - subjects.[namespace=cert-manager].namespace
          - select: 
              namespace: cert-manager
            fieldPaths:
              - metadata.namespace

...
```

**Expected output**

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
...
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cert-manager-webhook
      namespace: changed
...
```

**Actual output**

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
...
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cert-manager-webhook
      namespace: cert-manager
...
```

**Kustomize version**

Tested with: 

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

and: 

$ docker run -it --rm k8s.gcr.io/kustomize/kustomize:v4.5.4 version
{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:13:50Z GoOs:linux GoArch:amd64}

**Platform**

Windows / WSL2 / Ubuntu 20.04

**Additional context**

Interestingly with a additional patch on /metadata/namespace it works:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml

patches: 
  - target:
      kind: Namespace
      name: cert-manager
    patch: |-
      - op: replace
        path: /metadata/name
        value: changed
  - target:
      namespace: cert-manager
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: does-not-matter

transformers:
  - |-
    apiVersion: builtin
    kind: ReplacementTransformer
    metadata:
      name: does-not-matter
    replacements:
      - source:
          kind: Namespace
          fieldPath: metadata.name
        targets:
          - select:
              kind: RoleBinding
            fieldPaths:
               - subjects.[namespace=cert-manager].namespace
          - select:
              kind: ClusterRoleBinding
            fieldPaths:
              - subjects.[namespace=cert-manager].namespace
          - select: 
              namespace: cert-manager
            fieldPaths:
              - metadata.namespace

...
```
