### ISSUE TITLE
envCommand with value surrounded by double quotes

### ISSUE THREAD

**Issue by cm-yamasaki-michihiro** [kubernetes-sigs/kustomize#460]
Kustomize's envCommand in SecretGenerator interprets dotenv output oddly.

Some commands like [aws-env](https://github.com/Droplr/aws-env) generate dotenv with following format.
```
FOO="VAR1"
BAR="VAR2"
```
Values are surrounded by double quotes.

When Kustomize interprets this output with envCommand, it generates following output:
```yaml
apiVersion: v1
data:
  # encoded values are surrounded by double quotes
  foo: IlZBUjEi # base64 encoded value of '"VAR1"'.
  bar: IlZBUjIi # base64 encoded value of '"VAR2"'.
kind: Secret
metadata:
  creationTimestamp: null
  name: from-aws-env-879mkbh49f
type: Opaque
```

Encoded values in the secret are surrounded by double quotes.
Is this by design?
