### ISSUE TITLE
patchesStrategicMerge issue with argo Rollout

### ISSUE THREAD

**Issue by nice-pink** [kubernetes-sigs/kustomize#4600]
**Describe the bug**

If using `patchesStrategicMerge` the containers are overwritten instead of merged. Everything works fine if changing from `kind: Rollout` to `kind: Deployment`.

**Files that can reproduce the issue**

Example:

rollout.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
      - name: container
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

version.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
      - name: container
        image: container-image:latest
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml

patchesStrategicMerge:
  - version.yaml
```

-->

**Expected output**

```
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: container-image:latest
        name: container
```

**Actual output**

```
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
      - image: container-image:latest
        name: container
```

**Kustomize version**

{Version:kustomize/v4.4.0 GitCommit:63ec6bdb3d737a7c66901828c5743656c49b60e1 BuildDate:2021-09-27T16:13:36Z GoOs:darwin GoArch:amd64}

**Platform**

MacOSX

**Additional context**

I added a test repo for exploration: https://github.com/nice-pink/kustomize_patch_example
