### ISSUE TITLE
Remove Default Addition of Block Chomp (|-) on ConfigMaps that don't end with New Line

### ISSUE THREAD

**Issue by amahesh98** [kubernetes-sigs/kustomize#4602]
**Describe the bug**

When calling ByteReader.read() on a ConfigMap that doesn't end with a new line, if there is a pipe on the keys, then the last pipe gets replaced with a block chomp indicator (|-). This can be seen through the following flow on a valid yaml string

```
s := "some valid yaml string"
br := kio.ByteReader{
	Reader:                bytes.NewReader([]byte(s)),
	OmitReaderAnnotations: true,
}

rNodes, err := br.Read()
str, err := rNodes[0].String()
fmt.Printf("%v\n", str)
```

**Files that can reproduce the issue**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE
```

The above will replace `deployment-core-platform-service: |` with `deployment-core-platform-service: |-` since it doesn't end with a new line

Whereas

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE

```

The above will not since it ends with a new line.

**Expected output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |
    DummyKey: DUMMY_VALUE
```

**Actual output**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: my-namespace
data:
  base-test: |
    DummyKey: DUMMY_VALUE
    PrintLogs: true
  deployment-abc: |-
    DummyKey: DUMMY_VALUE
```

**Kustomize version**

kustomize/kyaml v0.10.19

**Platform**

Linux / macOS

**Additional context**

We are willing to submit a fix ourselves, just wanted to confirm first if this is actually the expected behavior
