### ISSUE TITLE
Kustomize is not merging configmaps instead is clobbering with the overlay content

### ISSUE THREAD

**Issue by spstarr** [kubernetes-sigs/kustomize#4603]
**Describe the bug**

With the following directory structure:

```
base/
├── base.properties
├── deployment.yaml
└── kustomization.yaml
overlays/
└── dev
    ├── base.properties
    └── kustomization.yaml
```

I am not able to see the merged configmap generated

Here is the contents of them all:

base/base.properties:
```
HELLO WORLD BASE
```

base/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

configMapGenerator:
  - name: example-configmap
    files:
    - base.properties
```

base/deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mydeployment
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mydeployment
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
          - name: configmap-volume-mount
            mountPath: /etc/app/configs
      volumes:
        - name: configmap-volume-mount
          configMap:
            name: example-configmap
            items:
              - key: base.properties
                path: base.properties
```

For Overlay:

overlays/dev/base.properties:
```
---
ADDED IN!
```

overlays/dev/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: mydeployment-dev
configMapGenerator:
  - name: example-configmap
    behavior: merge
    files:
    - base.properties
```

When I run latest kustomize or kubectl command line:
`kustomize build overlays/dev`:

**Expected output**
```
apiVersion: v1
data:
  base.properties: |
    HELLO WORLD BASE
    ---
    ADDED IN!
kind: ConfigMap
metadata:
  name: example-configmap-hfm7t8c6c5
  namespace: mydeployment-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: mydeployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mydeployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mydeployment
    spec:
      containers:
      - args:
        - while true; do sleep 30; done;
        command:
        - /bin/sh
        - -c
        - --
        image: busybox:1.28
        name: busybox
        volumeMounts:
        - mountPath: /etc/mydeployment/configs
          name: configmap-volume-mount
      volumes:
      - configMap:
          items:
          - key: base.properties
            path: base.properties
          name: example-configmap-hfm7t8c6c5
        name: configmap-volume-mount
```
**Actual output**
```
apiVersion: v1
data:
  base.properties: |
    ---
    ADDED IN!
kind: ConfigMap
metadata:
  name: example-configmap-hfm7t8c6c5
  namespace: mydeployment-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: mydeployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mydeployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mydeployment
    spec:
      containers:
      - args:
        - while true; do sleep 30; done;
        command:
        - /bin/sh
        - -c
        - --
        image: busybox:1.28
        name: busybox
        volumeMounts:
        - mountPath: /etc/mydeployment/configs
          name: configmap-volume-mount
      volumes:
      - configMap:
          items:
          - key: base.properties
            path: base.properties
          name: example-configmap-hfm7t8c6c5
        name: configmap-volume-mount
```
The merged configMap in this case does not contain `HELLO WORLD BASE` at the top of the file.

**Kustomize version**

```$ kustomize version
{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:12:45Z GoOs:linux GoArch:amd64}
```

**Platform**
Linux

**Additional context**

My understanding is merge should merge the changes, but that is clobbering them?
