### ISSUE TITLE
[Question] How to json patch contrainer resources?

### ISSUE THREAD

**Issue by tnk-dev** [kubernetes-sigs/kustomize#4609]
I want to specify container resources on a overlay level meaning I don't want to use as much memory and cpu in development as I do in production.

I this at all possible? 

**Note: I don't wanna specify a specific app name but rather have it apply to all my development overlays**

```yaml
# kustomization.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: .*
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/resources/requests/memory
        value: 1G
      - op: replace
        path: /spec/template/spec/containers/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/resources/limits/memory
        value: "2G"
      - op: replace
        path: /spec/template/spec/containers/resources/limits/cpu
        value: "1000m"
```
Running this throws me the following:

```shell
$ kubectl kustomize overlays/dev
error: replace operation does not apply: doc is missing path: /spec/template/spec/containers/resources/requests/memory: missing value
```
