### ISSUE TITLE
Configmap generator not escaping values containing colons

### ISSUE THREAD

**Issue by elassadi** [kubernetes-sigs/kustomize#4610]
**the generated Configmap contains syntax errors**

**Files that can reproduce the issue**

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

...
configMapGenerator:
- name: configmap
  envs:
    - config.env

...
```

config.env

```
VARIABLE_FOO=FOO:10:LO:
VARIABLE_BAR=FOO:10:LO
...
```

...

**Expected output**

configmap.yaml

```
apiVersion: v1
data:
  VARIABLE_FOO: 'FOO:10:LO:'
  VARIABLE_BAR: 'BAR:23:LO'
kind: ConfigMap
metadata:
...
```

**Actual output**

configmap.yaml

```
VARIABLE_FOO: 'FOO:10:LO:'
VARIABLE_BAR: BAR:23:LO
...
```

Colon is raising an exception: invalid value:

**Comment by laxmikantbpandhare** [comment]
I can take a look into it. @KnVerey @natasha41575 Is it okay?

**Comment by KnVerey** [comment]
@laxmikantbpandhare my apologies, I just read over this again and I disagree with my original assessment of the situation. tl;dr I can't find a bug here. 

Take the final configmap we're generating right now:

```yaml
apiVersion: v1
data:
  VARIABLE_BAR: FOO:10:LO
  VARIABLE_FOO: 'FOO:10:LO:'
kind: ConfigMap
metadata:
  name: configmap-f8d76cdgm4
```

That YAML is in fact perfectly valid; we only need to escape terminal colons, and we already do. There's no need to quote `FOO:10:LO`.  I even applied it to a cluster to be sure, and it worked just fine.

I can't reproduce `Colon is raising an exception: invalid value:` on any of the three versions I tried (latest Kustomize, or v4.2.0, or v4.0.3). They all produce the valid yaml pasted above. Please reopen with a sample that can reproduce the problem if applicable.

/triage not-reproducible
/close
