### ISSUE TITLE
Cronjob container part overwritten even in kustomize v4.5.4

### ISSUE THREAD

**Issue by pmithil7** [kubernetes-sigs/kustomize#4621]
As previously mentioned here: https://github.com/kubernetes-sigs/kustomize/issues/4255

The fix for this was in kustomize version 4.3.0. I'm using kubectl version 4.5.4 and i still see the container part incorrectly being overwritten as blank

Example:

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../mock
patchesStrategicMerge:
  - cronjob-patch-env.yaml
```
Inside the mock directory i have the below cronjob.yaml

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-test
  namespace: tests
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: env
              value: mock
            image: test-image
            imagePullPolicy: IfNotPresent
            name: auto-test
            command:
            - /bin/bash
            - -c
            args:
            - |
              name=$(date +"%m-%d-%y-%T")
         imagePullSecrets:
          - name: jfrog-pull-secret
     backoffLimit: 0
  schedule: '0 14 * * *'
```
Patch file cronjob-patch-env.yaml is as below:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-test
  namespace: tests
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: env
              value: dev
...
```
-->

**Expected output**
It should merge and update the env variable in containers section and keep the rest as it is.
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-test
  namespace: tests
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: env
              value: dev
            image: test-image
            imagePullPolicy: IfNotPresent
            name: auto-test
            command:
            - /bin/bash
            - -c
            args:
            - |
              name=$(date +"%m-%d-%y-%T")
         imagePullSecrets:
          - name: jfrog-pull-secret
     backoffLimit: 0
  schedule: '0 14 * * *'
```
**Actual output**

The actual output is that the containers section shows as empty array as below:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-test
  namespace: tests
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers: []
         imagePullSecrets:
          - name: jfrog-pull-secret
     backoffLimit: 0
  schedule: '0 14 * * *'
```

Why is it not able to take the changes of the container section from the original file and just update the env variable? It is overwriting it and marking it blank.

**Kustomize version**

4.5.4

**Platform**

macOS

**Comment by KnVerey** [comment]
I think the problem is that your patch is missing the container merge key, which is the container name (`name: auto-test` in your example).

**Comment by KnVerey** [comment]
I am unable to reproduce what you're seeing. I copied the samples exactly, and with Kustomize v4.5.4 I get the expected output:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-test
  namespace: tests
spec:
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - args:
            - |
              name=$(date +"%m-%d-%y-%T")
            command:
            - /bin/bash
            - -c
            env:
            - name: env
              value: dev
            image: test-image
            imagePullPolicy: IfNotPresent
            name: auto-test
          imagePullSecrets:
          - name: jfrog-pull-secret
  schedule: 0 14 * * *
  ```
