### ISSUE TITLE
Kustomization Var is not replaced in all locations

### ISSUE THREAD

**Issue by marcofranssen** [kubernetes-sigs/kustomize#4626]
**Describe the bug**

My ingress needs to refer to the correct service with potential prefixes/postfixes. For that I want to utilize the Var feature.

When running `kubectl kustomize` or `kustomize build` I notice not all instances of `$(ECHO_SERVICE_NAME)` are replaced. It only replaces a single instance of the variable.

**Files that can reproduce the issue**

Example:

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - echo-server-service.yaml
  - echo-server-ingress.yaml

vars:
  - name: ECHO_SERVICE_NAME
    objref:
      kind: Service
      name: echo-server
      apiVersion: v1
```

echo-server-ingress.yaml

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server
  annotations:
    alb.ingress.kubernetes.io/group.name: my-cluster
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Required to target Pod IPs directly (skips kube-proxy)
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: $(ECHO_SERVICE_NAME)
      port:
        number: 80
  rules:
    - host: $(ECHO_SERVICE_NAME).my-domain.tld
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: $(ECHO_SERVICE_NAME)
                port:
                  number: 80
```

**Expected output**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: my-cluster
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: dev-echo-server
  namespace: my-demo
spec:
  defaultBackend:
    service:
      name: dev-echo-server
      port:
        number: 80
  ingressClassName: alb
  rules:
  - host: dev-echo-server.my-domain.tld
    http:
      paths:
      - backend:
          service:
            name: dev-echo-server
            port:
              number: 80
        path: /
        pathType: Exact
```

**Actual output**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: my-cluster
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: dev-echo-server
  namespace: my-demo
spec:
  defaultBackend:
    service:
      name: $(ECHO_SERVICE_NAME)
      port:
        number: 80
  ingressClassName: alb
  rules:
  - host: dev-echo-server.my-domain.tld
    http:
      paths:
      - backend:
          service:
            name: $(ECHO_SERVICE_NAME)
            port:
              number: 80
        path: /
        pathType: Exact
```

**Kustomize version**

```shell
$ kubectl version          
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-14c7a48", GitCommit:"35f06c94ad99b78216a3d8e55e04734a85da3f7b", GitTreeState:"clean", BuildDate:"2022-04-01T03:18:05Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

$ kustomize version
{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:06:20Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOS Monterey

**Additional context**
