### ISSUE TITLE
How to apply version?

### ISSUE THREAD

**Issue by dominikjeske** [kubernetes-sigs/kustomize#4632]
I'm trying to find how to set version to k8s deployment with kustomize but I have stuck.

There is standard label app.kubernetes.io/version so my first approach was add it using commonLabels but this creates selectors and I cannot update version in next release. I found new labels https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/ but when I applied this in kustomization.yaml label appears is deployment, service and ingress but not in pod and replicaset?
Second thing is that `kustomize edit set label "app.kubernetes.io/version:1.0.2"` is setting commonLabels

What is the proper way to set this version and update this value on next release?

**Comment by natasha41575** [comment]
From my understanding, you want `labels` to be applied to `metadata.labels` and also `spec.template.metadata.labels`, is that correct? 

If so, https://github.com/kubernetes-sigs/kustomize/pull/4209 would allow you to do this in `labels`:

```
labels:
- pairs
    c: d
  includeTemplates: true # new field which will add the label to pod specs, but not matchLabels
```

This will be available in the next release.

If you have further questions or this does not resolve your issue, please reopen.

**Comment by dominikjeske** [comment]
@natasha41575 This would be great but I have second thing. When I finish my k8s deployment it will be rather static - beside next image tags and labels I'm referring to. On my deployment process I'm using kustomize edit to update image and I would do something like this with labels but kustomize edit label is setting commonLabels and this is not good for me (because of immutability of created selectors). Is there any build in way for this or I have to find and replace in files manually?

**Comment by gnarroway-bullish** [comment]
The way to do it these days is to use replacements:


```
replacements:
  - source:
      name: my-deployment
      kind: Deployment
      fieldPath: spec.template.spec.containers.[name=my-container-name].image
      options:
        delimiter: ':'
        index: 1
    targets:
      - select:
          name: my-deployment
          kind: Deployment
        fieldPaths:
          - metadata.labels.version
          - spec.template.metadata.labels.version
          - metadata.labels.app\.kubernetes\.io/version
```

This has to be in the same (or higher) kustomization that you set the image in, otherwise it will not have access to the image version you set.
