### ISSUE TITLE
Patch with value fetched from a file

### ISSUE THREAD

**Issue by gberche-orange** [kubernetes-sigs/kustomize#4636]
**Is your feature request related to a problem? Please describe.**

I meet multiple situations where I need to inject content of a source file (usually a K8S yaml spec files, sometimes files with other formats such as prometheus rule, grafana dashboard) into a K8S resource spec file. To leverage the native IDE tooling ( completion/documentation/syntax validation), I need the format of the source file to be preserved (e.g. a valid CR K8S spec files which matches its open api schema).

Currently, I use strategic patch or json patch to include sub-resources from distinct files, but this requires to modify their structure, and thus prevents usage of the native tooling the subresources files (typically openapi). 

Did I miss a kustomize feature to fullfill this goal ?

**Describe the solution you'd like**

A way to copy content from a file into a k8s resource.

Here is an idea of a json patch `fromFile` extension to the `copy` operator

```yaml
      - op: copy
        fromFile: ./network.yaml
        from: /
        path: /spec/resources[0]/base
```

**Describe alternatives you've considered**

* Using a KRM plugin, but this isn't supported in my context in FluxCD due to multi-tenancy security issues see https://github.com/fluxcd/kustomize-controller/issues/323

**Additional context**

I work with crossplane compositions which Composition CR which includes a nested array of arbitrary dynamically loaded CRs resources (eg NodePool, GKECluster,  CloudSQLInstance, Release ...) which can not statically be defined in a single openapi schema. I need a way to split the Composition CR into manageable yaml files for each nested resource, while preserving ability within the IDE to leverage their openapi for completion/documentation/syntax validation.

See typical example from https://github.com/crossplane-contrib/provider-helm/blob/176aa6812860e95712ea7aecd541a564bc839b14/examples/in-composition/composition.yaml with such a long yaml

composition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: wordpressclusters.example.crossplane.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1alpha1
    kind: WordpressCluster
  resources:
    - base:
        apiVersion: compute.gcp.crossplane.io/v1beta1
        kind: Network
        spec:
          forProvider:
            autoCreateSubnetworks: false
            routingConfig:
              routingMode: REGIONAL
    - base:
        apiVersion: container.gcp.crossplane.io/v1beta1
        kind: GKECluster
        spec:
          forProvider:
            addonsConfig:
              kubernetesDashboard:
                disabled: true
              networkPolicyConfig:
                disabled: false
            databaseEncryption:
              state: DECRYPTED
[...]
```

With a new feature, this could transform into

network.yaml (matching its open api schema):
```yaml
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingConfig:
    routingMode: REGIONAL
[...]
```

composition.yaml (matching its open api schema)
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: wordpressclusters.example.crossplane.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1alpha1
    kind: WordpressCluster
  resources: []
```

kustomization.yaml:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane 

resources:
  - composition.yaml

patchesJson6902:
  - target: &composition
      version: v1
      group: apiextensions.crossplane.io
      kind: Composition
      name: wordpressclusters.example.crossplane.io
    patch: |
      - op: add
        path: /spec/resources
        value: 
          base: {}
      - op: copy
        fromFile: ./network.yaml
        from: /
        path: /spec/resources[0]/base
[....]
```

**Comment by KnVerey** [comment]
I think the configmap and secret generators are the only features that can source data from various specific file formats. Since Kustomize is oriented around structural edits, I don't see us adding a feature that loads arbitrary data into arbitrary resources.

However, the specific use case presented of embedding one k8s resource in another sounds adjacent to something the replacements transformer can do--it works by sourcing values from one resource and inserting them into specified locations in another. The resources in question would need to be in the normal resources field, though the `config.kubernetes.io/local-config` annotation could be used to strip them from the build output if needed.

The example below does not work, but if we were to support this use case, I think it would look something like it. @natasha41575 as the author of replacements, is this reasonable or out of scope?

```yaml
replacements:
- source:
    kind: Network
    version: v1beta1
    group: compute.gcp.crossplane.io
    fieldPath: "." # the whole object--not supported
  targets:
  - select:
      kind: Composition
      group: apiextensions.crossplane.io
      version: v1
      name: wordpressclusters.example.crossplane.io
    fieldPaths:
    - "spec.resources.0" # targeting by index--not supported https://github.com/kubernetes-sigs/kustomize/issues/4507
    options:
      create: true
```

/triage under-consideration
