### ISSUE TITLE
[Question] Append a unique id for each resource?

### ISSUE THREAD

**Issue by xlight05** [kubernetes-sigs/kustomize#4637]
I'm new to Kustomize, been using kustomize for simple tasks to modify yamls.

So I have set of yamls but some of them contains config maps with the same name.  Therefore i get the following error
`Error: accumulating resources: accumulation err='merging resources from 'src/frontend/target/kubernetes/frontend/frontend.yaml': may not add resource with an already registered id: ~G_v1_ConfigMap|~X|config-config-map': got file 'frontend.yaml', but '/home/anjana/repos/gcp-microservices-demo/src/frontend/target/kubernetes/frontend/frontend.yaml' must be a directory to be a root`

Each of the yamls's secrets belongs to the deployment in that specific yaml file. What I want to do is to append some kind of prefix(or identifier) for each resource inside the yaml of that file so this won't get duplicated. 

one.yaml
```yaml
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "config-config-map"
data:
  Config.toml: "msg=15"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "frontend"
  name: "frontend-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
        image: "wso2inc/frontend-service:v0.1.0"
        name: "frontend-deployment"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "config-config-map-volume"
          readOnly: false
      nodeSelector: {}
      volumes:
      - configMap:
          name: "config-config-map"
        name: "config-config-map-volume"
---
```

two.yaml
```yaml
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "config-config-map"
data:
  Config.toml: "msg=12"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "app"
  name: "app-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "app"
  template:
    metadata:
      labels:
        app: "app"
    spec:
      containers:
        image: "wso2inc/app-service:v0.1.0"
        name: "app-deployment"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "config-config-map-volume"
          readOnly: false
      nodeSelector: {}
      volumes:
      - configMap:
          name: "config-config-map"
        name: "config-config-map-volume"
---
```

kustomization.yaml
```yaml
resources:
  - one.yaml
  - two.yaml
```

As you can see the config map `config-config-map` is there in both the yamls. I need a way to use both of them for those respective deployments. Is there are a way to do this without changing the original.yamls using kustomize?

**Comment by KnVerey** [comment]
There are at least two ways you can do this:
- Use [ConfigMapGenerator](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/), which appends a hash suffix to each configmap. This would require you to start with unique names that will automatically be updated with the generated hash, including in the Deployment references.
- If you really can't change the source files for whatever reason, you can import each in its own Kustomization that includes a [nameSuffix](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/namesuffix/) (or [namePrefix](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/nameprefix/)), then combine them in an additional layer:
```yaml
# base1/kustomization.yaml
nameSuffix: -one

resources:
- one.yaml

# base2/kustomization.yaml
nameSuffix: -two

resources:
- two.yaml

# overlay/kustomization.yaml
resources:
- ../base1
- ../base2
```

/kind support
/close
If I've misunderstood the situation, feel free to re-open with additional details.
