### ISSUE TITLE
[Question] Is there a way to generate multiple rolebindings?

### ISSUE THREAD

**Issue by tomsucho** [kubernetes-sigs/kustomize#4643]
Hey!
I got a service account that I want to rolebind in multiple namespaces to a cluster role. Is there any way to generate those rolebindings for each namespace through kustomize?
Many thanks!

**Comment by KnVerey** [comment]
It is admittedly a bit verbose, but this is possible using [Component](https://kubectl.docs.kubernetes.io/guides/config_management/components/). E.g.:

```yaml
# component/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- role-binding.yaml

# base1/kustomization.yaml, and similar for each namespace
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: one

components:
- ../component

# overlay/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base1
- ../base2 # etc
- cluster-role.yaml
- service-account.yaml
```

If having a Kustomization per namespace like that does not suit your workflow, I suggest looking into building a custom generator for your use case: https://kubectl.docs.kubernetes.io/guides/extending_kustomize/

/kind support
/close
Feel free to reopen with additional details if that does not answer your question!
