### ISSUE TITLE
Add labels to all resources in deployment?

### ISSUE THREAD

**Issue by dominikjeske** [kubernetes-sigs/kustomize#4649]
I'm trying to add labels (without selectors) to all resources created by deployment. So far I have LabelTransformer like below but last option for generatorOptions is not working. Is there any way to do this by LabelTransformer? I can add in in kustomization.yaml but I will have two "sources od truth". Maybe there is better way to get what I want?

```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: commonLabelsTransformer
labels:
  app.kubernetes.io/name: forum-app
  app.kubernetes.io/version: 1.2.6

fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
- path: spec/secretTemplate/labels
  create: true
  kind: Certificate
- path: generatorOptions/labels
  create: true
  kind: Kustomization
```

**Comment by KnVerey** [comment]
You're right, it is not possible to use the LabelTransformer to target the Kustomization itself. Could you please provide more info on why you need the generator to also add the labels? Since LabelTransformer runs after generators, I would expect all the generated resources to get the labels in question automatically.

/triage needs-information

**Comment by dominikjeske** [comment]
I need a place to set label on all resources in one place - for now LabelTransformer covers most of them but resources generated by "generatorOptions" can be defined only in kustomization.yaml so when I'm setting label 'app.kubernetes.io/version' I have to set it in two files. As far as why I need generator to set labels - it is simple, I need to know the version of app/deployment that generated given resource. For now I made powershell script to update this version but I was wonder is it possible to do it in LabelTransformer. If no You can close this issue.

**Comment by KnVerey** [comment]
Can you provide the Kustomization you're using? The LabelTranformer should cover all resources from any generator field (including `configMapGenerator` and `secretGenerator`, which are what `generatorOptions` configures), and indeed my testing indicates it is working:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: config
  literals:
    - foo=bar

generatorOptions:
  immutable: true

transformers:
  - |-
    apiVersion: builtin
    kind: LabelTransformer
    metadata:
      name: commonLabelsTransformer
    labels:
      app.kubernetes.io/name: forum-app
      app.kubernetes.io/version: 1.2.6

    fieldSpecs:
    - path: metadata/labels
      create: true
    - path: spec/template/metadata/labels
      create: true
      kind: Deployment
    - path: spec/secretTemplate/labels
      create: true
      kind: Certificate

```

```yaml
# Output
apiVersion: v1
data:
  foo: bar
immutable: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: forum-app
    app.kubernetes.io/version: 1.2.6
  name: config-798k5k7g9f
```

**Comment by dominikjeske** [comment]
My config:


```
Kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base/

configMapGenerator:
- name: forum-config
  files:
  - files/appsettings.Production.json
- name: dotnet-monitor-config
  files:
  - files/dotnet-monitor-appsettings.json

components:
 - ../components/commonLabels

generatorOptions:
  disableNameSuffixHash: true
  # labels:
  #   app.kubernetes.io/name: forum-app
  #   app.kubernetes.io/version: 1.3.0
```

and component for label transformer

```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: commonLabelsTransformer
labels:
  app.kubernetes.io/name: forum-app
  app.kubernetes.io/version: 1.3.0

fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
- path: spec/secretTemplate/labels
  create: true
  kind: Certificate

```

I'm using this component in base and given kustomization. After this I have:

![image](https://user-images.githubusercontent.com/3872348/173408339-7b281782-4b90-4a3f-aebd-fd1766c794da.png)

when I uncomment generatorOptions I have

![image](https://user-images.githubusercontent.com/3872348/173408516-38a3cae5-ade7-48e3-b3b1-4a93ac0a2a63.png)
