### ISSUE TITLE
[Question] When using KRM exec plugins you cannot pass OS environment variables to dynamically change values

### ISSUE THREAD

**Issue by spstarr** [kubernetes-sigs/kustomize#4655]
When you create a ConfigMapGenerator with a KRM exec plugin:

I see no way to specify that configmaps generated should have a suffix

```
echo "
apiVersion: myDevOpsTeam
kind: ResourceList
items:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: my-configmap
  data:
    .....
 ```
 
 Were would I allow setting a prefix for these configMaps?

**Comment by KnVerey** [comment]
We have [an example](https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap#L12) showing that adding the `kustomize.config.k8s.io/needs-hash: "true"` to the resource will cause Kustomize to add the suffix, but it seems to be under-tested in our code. Can you please give that a try?

Can you please also let us know more about your motivation for wanting Kustomize to handle this for you as opposed to having your plugin generate the ConfigMap with the suffix in the first place?

**Comment by spstarr** [comment]
Absolutely, I will test this today

**Comment by spstarr** [comment]
I hope that explains what I'm looking to do, but your help @KnVerey is great for the annotation that will solve one problem!

**Comment by spstarr** [comment]
@KnVerey Yes, `kustomize.config.k8s.io/needs-hash: "true"` worked, and I also removed the sed ugliness, a LabelTransformer plugin I wrote can parse Kustomize's own resources:

```
COMPONENT_NAME=tekton-demo COMPONENT_BUILD=develop DEPLOYMENT_COLOR=blue kustomize build --enable-alpha-plugins --enable-exec kustomize/overlays/dev
```

Results:

```
apiVersion: v1
data:
  configFile.yml: |
    ---
    config:
      timeoutValue: 10000000
      testingString: "foobar"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: tekton
    app.kubernetes.io/name: tekton-demo
    app.kubernetes.io/version: develop
  name: app-configmap-7hggghbh4b
```

The hash is now there and the custom labels are now dynamically added from shell env.

Closing.

If anyone wants to know how to get Kustomize to add dynamic labels from generated:

First have a generator to run your KRM plugin

```
generators:
  - myGenerator.yaml
```

in your kustomization.yaml add a transformer:

```
transformers:
   - set-labels.yaml
```
set-labels.yaml:

```
---
apiVersion: myapp/v1
kind: LabelTransformer
metadata:
  name: label-transformer
```

Your plugin name must be `LabelTransformer` and located in `KUSTOMIZE_PLUGIN_HOME`/plugins/myapp/v1/labeltransformer/LabelTransformer

Then process the YAML generated by Kustomize in your plugin and adjust any thing you like.
