### ISSUE TITLE
Error: multiple matches for Id HorizontalPodAutoscaler.v2beta2.autoscaling/....

### ISSUE THREAD

**Issue by dorianmariefr** [kubernetes-sigs/kustomize#4660]
Hi,

I'm very very new to the kubernetes world and just trying to upgrade dependencies

We were using `3.9.2` and I tried `4.5.5` and got this error.

**Describe the bug**

My build is failing to build the docker image I guess.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../bases/ordering
- secret-provider-class.yaml
- serviceaccount.yaml

patches:
- virtualservice.yaml

commonLabels:
  app.kubernetes.io/name: ordering
  app.kubernetes.io/part-of: our-client-name-not-public

configMapGenerator:
- behavior: merge
  envs:
  - config.env
  name: env

namespace: ordering-dev
```

**Expected output**

It builds the image without any issue like it used to.

**Actual output**

```
Error: multiple matches for Id HorizontalPodAutoscaler.v2beta2.autoscaling/ordering-web.[noNs]; failed to find unique target for patch HorizontalPodAutoscaler.v2beta2.autoscaling/ordering-web.[noNs]
109 |  
110 | [Container] 2022/06/01 07:27:23 Command did not exit successfully for target in dev staging production; do
111 | cd "$CODEBUILD_SRC_DIR/$target/ordering" && \
112 | kustomize edit set image "$REPOSITORY=$REPOSITORY:$SOURCE" && \
113 | kustomize edit add annotation \
114 | "manifests:$MANIFESTS" \
115 | "source:$SOURCE" \
116 | "project:$PROJECT" \
117 | "build:$BUILD" && \
118 | kustomize edit set label \
119 | "initiator:$INITIATOR" \
120 | "app.kubernetes.io/managed-by:codebuild" && \
121 | kustomize build "$CODEBUILD_SRC_DIR/$target/ordering" \
122 | > "$CODEBUILD_SRC_DIR/$target-ordering.yaml" \|\| \
123 | exit 1
124 | done
125 | exit status 1
126 | [Container] 2022/06/01 07:27:23 Phase complete: BUILD State: FAILED
127 | [Container] 2022/06/01 07:27:23 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: for target in dev staging production; do
128
```

**Kustomize version**

```
> kustomize version
{Version:kustomize/v4.5.5 GitCommit:daa3e5e2c2d3a4b8c94021a7384bfb06734bcd26 BuildDate:2022-05-20T20:25:40Z GoOs:darwin GoArch:arm64}
```

**Platform**

Linux

**Additional context**

Really not urgent, just letting you know in case
