### ISSUE TITLE
[Question] `ConfigMapGenerator` not adding the hash to `ConfigMap` name in custom resource

### ISSUE THREAD

**Issue by drenze-athene** [kubernetes-sigs/kustomize#4674]
I'm attempting to use a `ConfigMapGenerator` with a custom resource, however it's not working as expected; it doesn't add the hash to the name of the `ConfigMap`.

According to [the documentation][docs], this should be possible:

> All of kustomize's [builtin operations][builtins] are implemented and usable as plugins.
>
> Using the fields is convenient and brief, but necessarily specifies only part of the entire plugin specification. The unspecified part is defaulted to what are hopefully generally appealing values.
>
> If, instead, one invokes the plugins directly using the `transformers` or `generators` field, one can (indeed must) specify the entire plugin configuration.

The minimum necessary to reproduce the issue is:

```
DEMO_HOME=$(mktemp -d)
cat > $DEMO_HOME/kustomization.yaml << \__EOF__
---
apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'
generators:
  - 'configmapgen.yaml'

resources:
  - 'mykind.yaml'
__EOF__

cat > $DEMO_HOME/configmapgen.yaml << \__EOF__
---
apiVersion: 'builtin'
kind: 'ConfigMapGenerator'
metadata:
  name: 'my-config-map'
literals:
  - 'FOO=bar'
fieldSpecs:
  - kind: 'MyKind'
    path: 'spec/daemonSet/spec/containers/*/envFrom/*/configMapRef/name'
__EOF__

cat > $DEMO_HOME/mykind.yaml << \__EOF__
---
apiVersion: 'customresource.example.com/v1beta1'
kind: 'MyKind'
metadata:
  name: 'mycrd'
spec:
  daemonSet:
    spec:
      containers:
        - name: 'mycontainer'
          envFrom:
            - configMapRef:
                name: 'my-config-map'
__EOF__
```

Then execute: `kustomize build $DEMO_HOME`

Expected output is:

```
apiVersion: v1
data:
  FOO: bar
kind: ConfigMap
metadata:
  name: my-config-map-59m54fbgh2
---
apiVersion: customresource.example.com/v1beta1
kind: MyKind
metadata:
  name: mycrd
spec:
  daemonSet:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: my-config-map-59m54fbgh2
        name: mycontainer
```

Actual output is:

```
apiVersion: v1
data:
  FOO: bar
kind: ConfigMap
metadata:
  name: my-config-map-59m54fbgh2
---
apiVersion: customresource.example.com/v1beta1
kind: MyKind
metadata:
  name: mycrd
spec:
  daemonSet:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: my-config-map
        name: mycontainer
```

This also happens if I hardcode the path in the spec as:

```
spec/daemonSet/spec/containers/0/envFrom/0/configMapRef/name
```

I'm certain that this is an issue on my part.

[builtins]: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md
[docs]:https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configureBuiltinPlugin.md

**Comment by gaeljw** [comment]
Wouldn't this need the `HashTransformer` as well? (Just an idea)

**Comment by drenze-athene** [comment]
> Wouldn't this need the `HashTransformer` as well? (Just an idea)

Not a clue, but I'll certainly look at it.

**Comment by drenze-athene** [comment]
> Had the same problem. #2524 fixed it for me. You can configure kustomize with kustomizeconfig.

Not at all sure how I missed this as I was looking for a solution. Thx!

**Comment by drenze-athene** [comment]
Just in the interest of showing the solution, in case someone stumbles across this issue in the future, here is the `nameReference.yaml` I used:

```yaml
---
nameReference:
  - kind: 'ConfigMap'
    fieldSpecs:
      - kind: 'MyKind'
        path: 'spec/daemonSet/spec/containers/envFrom/configMapRef/name'
```

and here are the additions to `kustomization.yaml`:

```yaml
configurations:
  - 'nameReference.yaml'
```

As @woffiss noted, #2524 does is a good explanation of how to resolve this issue.

**Comment by lowesilvan** [comment]
Thank you @renzedj 
For my case using argo rollouts, I had to make this little change

---
```YAML
nameReference:
  - kind: ConfigMap
    fieldSpecs:
      - kind: Rollout
        path: spec/template/spec/containers/envFrom/configMapRef/name
```
