### ISSUE TITLE
kustomize edit add replacement

### ISSUE THREAD

**Issue by Gikkman** [kubernetes-sigs/kustomize#4679]
**Is your feature request related to a problem? Please describe.**
We got some scripts which generates a replacement file , and would like to automatically add the replacement file to the `kustomization.yaml` file. _(I patch in a init container, and then we want that init container to have the same image as a main container. I know, it's hacky, but I am testing some PoCs)_ Similarly to how we can add a patch with `kustomize edit add patch --path` or a label with `kustomize edit add label`.

I've recently started working with replacements, so maybe I am missing something in the documentation or the intentions with it, but I can't see any support for this feature and I would consider it really useful.

**Comment by annasong20** [comment]
@Gikkman Just to confirm, given a `replacement.yaml`, you'd like to add 
```
replacements:
- path: replacement.yaml
```
to `kustomization.yaml`?

While we triage this feature request, how does `kustomize edit add transformer replacement-transformer.yaml` work for you? Since you already have the `replacement.yaml`, you'd only need to write a script that generates
```
# replacement-transformer.yaml
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: your-choice
replacements:
- path: replacement.yaml
```

**Comment by annasong20** [comment]
@KnVerey How do we feel about this request for `kustomize edit add replacement`? 

I'm not very familiar with the rationale behind the `kustomize edit` command and why we support adding some fields but not others. I assume `kustomize edit add` doesn't have built-in support for `replacements` because it's a newer field?

**Comment by annasong20** [comment]
/triage accepted

on the condition that `kustomize edit add replacement` is only responsible for accepting a `replacement.yaml` and adding
```
replacements:
- path: replacement.yaml
```

This command should **not** be responsible for adding an "inline" replacement
```
replacements:
- source:
    ...
  targets:
  ...
```
given all the field values under `source` and `targets` as flags.

**Comment by Gikkman** [comment]
Hi @annasong20 . Sorry for the late reply.

> Just to confirm, given a `replacement.yaml`, you'd like to add
> 
> ```
> replacements:
> - path: replacement.yaml
> ```
> 
> to `kustomization.yaml`?

Yes. This is the same behavior we see when we use `kustomize edit add patch`, so that seems reasonable. Worth noting I guess is that if the kustomization.yaml file already contains an array of replacements, the added replacement(s) should be added to the existing array (again, similar to how `kustomize edit add patch` works).

**Comment by charles-chenzz** [comment]
to confirm something, are we trying to add a sub-command on ``kustomize edit add`` ? as I would like to take this issue

![Image](https://github.com/kubernetes-sigs/kustomize/assets/73322208/139e6d78-b61f-43f0-ba14-62cf4130bdac)

**Comment by annasong20** [comment]
> add a sub-command on `kustomize edit add` ? as I would like to take this issue

@charles-chenzz, that's correct!

**Comment by charles-chenzz** [comment]
hi @Gikkman . can you provide a detail example of the input and output that we expect? It would help a lot for the implement! Thanks

**Comment by Gikkman** [comment]
From how I've use `kustomize` in the past, I think the following two cases should explain. Please note that the command doesn't validate whether anything actually exists at the path we give it, it merely adds to the kustomization.yaml file (this is consistent with the other `edit add ...` commands).

# Case 1 - No pre-existing replacements list
```
>> Layout
kustomize/
├─ kustomization.yaml
├─ changes.yaml
```
```yaml
>> kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
```
We want to add the `replacement.yaml` file to the `kustomization.yaml`. We position our shell in the `kustomize` folder, and execute the following command:
```shell
kustomize edit add replacement --path changes.yaml
```
This should **add** a list named `replacements` in the `kustomization.yaml`, with one element (the path we passed) like this:
```yaml
>> kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
replacements:
- path: changes.yaml
```

# Case 2 - A pre-existing replacements list
```
>> Layout
kustomize/
├─ kustomization.yaml
├─ replacements.yaml
├─ changes.yaml
```
```yaml
>> kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

replacements:
- path: replacement.yaml
```
We want to add the `replacement.yaml` file to the `kustomization.yaml`. We position our shell in the `kustomize` folder, and execute the following command:
```shell
kustomize edit add replacement --path changes.yaml
```
This should **append** to the list named `replacements` in the `kustomization.yaml` (the path we passed), like this:
```yaml
>> kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  
replacements:
- path: replacement.yaml
- path: changes.yaml
```
