### ISSUE TITLE
[Question] Multiples repositories using same base (remote)

### ISSUE THREAD

**Issue by defaultbr** [kubernetes-sigs/kustomize#4680]
Hi guys, I'm coming from helm, so I'm used to values.yaml.

I've tested `kustomize` and I found some know limitations or decisions to not support some features or some doubts, 

I already know (I guess) the difference between using helm and kustomize. When I decided to switch from helm to kustomize I was looking to bring to developers less abstractions about the infra and give them some power to decide and change some resources, so for this, the manifests files should reside with the application source code to make their life "easier"

The current flow is: CI pipeline build the image on new commit, push to registry, cd to the path of the desired environment (<application-src-repository>/gitops/kustomize) , run a `kustomize build ../overlays/[environment] > result-[custom-branch-name].yaml` and than push  this result yaml to the gitops manifests repository where argocd looking.

I had to add annotations and new resources common to all applications (at this moment two, but will grow to more than 50 similar), now I'm facing the pain to enter in each repository, create the new resource file, edit kustomization.yaml and let the CI process do build and generate the new result.yaml.

So I throught about importing remote files, at the applications source code, base kustomization.yaml had a import from a another base at remote repository.

**<-application-source-code->/gitops/kustomize/base/kustomization.yaml:**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ssh://my-gitlab-instance-endpoint/kubernetes-kustomize-base-for-api.git
```

This solved the annotations common to all, but I faced another problem, from `kubernetes-kustomize-base` is impossible to add some placeholders since there is not substitution at all and no way to know which application repository is importing it

Is there any solution for this? 

I want to avoid to mantain a helm chart repository, bring developers more control but keep a remote base where I can force all applications to use new resource or add a annotation that will use the a dynamic value from each application repository.

The only way that I can imagine now is using some kind of `.env` file at each overlay, update the the upstream remote base to use `${PLACEHOLDERS_VARIABLES}` and run a `envsubst` command after the kustomize build. But I'm not reinventing the wheel?

**Comment by bcha** [comment]
We have a similarish use-case, we've got a repo for "common components" that can be added as resources by developers like so:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base.yml
  - https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/path/to/k8s-commons.git//ingress-common/${ENVIRONMENT}
```
We're using env variables in the `k8s-commons` repo + envsubst when doing kustomize build. Targeting patches to these remote resources is a bit difficult though and currently we've been using just this kind of wildcard workarounds:

```yaml
patchesJson6902:
  - path: patch-common-ingress.yml
    target:
      name: .*-ingress
      kind: Ingress
      group: networking.k8s.io
      version: v1
```

Would love to have some less hacky solution for this & the wildcard target patching isn't really ideal either 😄
