### ISSUE TITLE
NameReference Transformer doesn't work with annotations.

### ISSUE THREAD

**Issue by rishabh625** [kubernetes-sigs/kustomize#4682]
The NameReference Transformer used on annotations doesn't work, Bcoz of the refBy field being added in annotations by this [PR](https://github.com/kubernetes-sigs/kustomize/pull/4002)

some how when it moves up kustomization stack and when refBy field needs to be deleted from Resource Node it also removes  referred annotations and thus transform doesn't apply on annotations.

**Files that can reproduce the issue**

For below files

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - namespace.yaml
configurations:
  - kustomize-namespace.yaml 

```

```
nameReference:
  - kind: Namespace
    fieldSpecs:
      - path: metadata/annotations/foo
        kind: Namespace
        version: v1
```

resources.yaml

```
apiVersion: v1
kind: Namespace
metadata:
  name: namespace
  annotations:
    foo: namespace
```
```kustomize build folder_name ```

doesn't produce expected output, the expected output used to come for version 4.2.0 , so its a bug which should have been caught in regression.

**Expected output**

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    foo: test
  name: test
```

**Actual output**

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    foo: namespace
  name: test
```

**Kustomize version**

kustomize/v4.5.2

**Platform**

Linux/macOS

**Additional context**
I am not sure on how to fix this 

but if i add below code in kustomize/api/resource/resource.go on line no 371  and create the kustomize binary i get the expected output.
```
func (r *Resource) AppendRefBy(id fmt.Stringer) {
	//r.appendCsvAnnotation(utils.BuildAnnotationsRefBy, id.String())
}
```

I am unsure on how to solve it , i don't see the new annotation refBy being used somewhere else, so can we just revert this [PR](https://github.com/kubernetes-sigs/kustomize/pull/4002) or what?
