### ISSUE TITLE
Change (matching) image registries

### ISSUE THREAD

**Issue by ciis0** [kubernetes-sigs/kustomize#4687]
**Is your feature request related to a problem? Please describe.**

We distribute a application containing a number of images and we would like to allow to easily change the registry the images come from, so there is no external dependency on the distribution registry.

It is quite frustrating to have clean kustomization but then have to revert to template-based search-and-replace transformer configuration for updating the registry in the relevant images; currently we would need we deliver also this imageTagTransformer snippet for properly updating the images.
```yaml
images:
- name: frontend-1
  newName: replace.this.registry.example.com:5000/mirrored-repository/frontend-1
- name: backend-1
  newName: replace.this.registry.example.com:5000/mirrored-repository/backend-1
- name: service-2
  newName: replace.this.registry.example.com:5000/mirrored-repository/service-2
- name: frontend-3
  newName: replace.this.registry.example.com:5000/mirrored-repository/frontend-3
- name: backend-3
  newName: replace.this.registry.example.com:5000/mirrored-repository/backend-3
- name: service-41
  newName: replace.this.registry.example.com:5000/mirrored-repository/service-41
- name: service-42
  newName: replace.this.registry.example.com:5000/mirrored-repository/service-42
```

and instruct the consumer to search-an-replace the `replace.this.registry.example.com:5000/mirrored-repository/` with the actual registry and repository. (one could propably shorten that to `newName: image-name` and use `s|newName: (.*)|newName: mirror.example.com/vendor/product/$1|`.)

**Describe the solution you'd like**

That first thing that comes to mind is that a new parameter in the kustomization like the following could be useful:

```yaml
registries:
- images:
  - frontend-1
  - backend-1
  - service-2
  - frontend-3
  - backend-3
  - service-41
  - service-42
  newRegistry: mirror.example.com:5000
  newRepository: vendor/product
```

which would update the listed images to `mirror.example.com:5000/vendor/product/$image`.

this would still mean we would provide the list of images, but you only replace the example values *once*, no search-and-replace required!

Having this in the core would also allow to use the `TransformerConfig.Images` field specs from default and `configuration`s without duplicating that info in plugin.

Would you accept a PR for that?

**Describe alternatives you've considered**

I considered writing an external transfromer plugin.

The customer has Kubernetes only, no "docker run" compatible container runtime (Dpcker, Podman), and as such cannot run containerized plugins. Setting up docker/podman one up is an unwanted additional dependency. Writing an exec plugin would too require unwanted additional setup.

**Additional context**

The following problems from my point of view block having this outside of the core:

1. running krm function plugins in Kubernetes so we don't need to install a container engine as we already have access to kubernetes -- where would we deploy the application to otherwise?!
2. exposing `TransformerConfiguration` to external transformer plugins (in this case for `Images`), but that is nice-to-have in a sense that it would keep the behavior of `images` and the (new) `registries` in sync.
