### ISSUE TITLE
Kustomize does not replace generated secrets with hashed-suffixed name

### ISSUE THREAD

**Issue by abstractalchemist** [kubernetes-sigs/kustomize#4695]
**Describe the bug**

When using a secretgenerator, kustomize does not replace the generated secret name referenced by other resources.

Given the following kustomization.yaml
```
secretGenerator:
- name: bar
resources:
- deploy.yaml
```
and the following deploy.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: quay.io/centos/centos:stream
        name: centos
        resources: {}
        volumeMounts:
        - name: certs-1
          mountPath: /secrets
    volumes:
    - secret:
        secretName: bar
      name: certs-1
```

Kustomize does not replace the secret name with the generated secret name.
**Files that can reproduce the issue**

**Expected output**

Expected output
```
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: bar-46f8b28mk5
  namespace: bar
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd
  namespace: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: quay.io/centos/centos:stream
        name: centos
        resources: {}
        volumeMounts:
        - mountPath: /secrets
          name: certs-1
    volumes:
    - name: certs-1
      secret:
        secretName:  bar-46f8b28mk5
```

**Actual output**

Actual Output:
```
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: bar-46f8b28mk5
  namespace: bar
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd
  namespace: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: quay.io/centos/centos:stream
        name: centos
        resources: {}
        volumeMounts:
        - mountPath: /secrets
          name: certs-1
    volumes:
    - name: certs-1
      secret:
        secretName: bar
```
**Kustomize version**
4.5.5

**Platform**

Linux
**Additional context**
Some other examples seem to work but I can't tell the difference between what they are doing and what I'm doing.

**Comment by abstractalchemist** [comment]
Don't know if this helps, but this is very strange to me as well.  Given a kustomization
```
resources:
- tests/deployment.yaml
- deployment.yaml
secretGenerator:
- name: example
```

The output is
```
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: example-46f8b28mk5
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd
spec:
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: quay.io/centos/centos:stream
        name: centos
        volumeMounts:
        - mountPath: /secrets
          name: certs-1
    volumes:
    - name: certs-1
      secret:
        secretName: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: my-app
        name: app
        volumeMounts:
        - mountPath: /secrets
          name: password
      volumes:
      - name: password
        secret:
          secretName: example-46f8b28mk5
```

So the deployment as specified by deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd
spec:
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: quay.io/centos/centos:stream
        name: centos
        volumeMounts:
        - name: certs-1
          mountPath: /secrets
    volumes:
    - secret:
        secretName: example
      name: certs-1
```
in the kustomization yaml is generated incorrectly, but the deployment specified by tests/deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app
        image: my-app
        volumeMounts:
        - name: password
          mountPath: /secrets
      volumes:
      - name: password
        secret:
          secretName: example
```

seems to generate ok.
