### ISSUE TITLE
Replacement file from different folder

### ISSUE THREAD

**Issue by nice-pink** [kubernetes-sigs/kustomize#4697]
**Is your feature request related to a problem? Please describe.**

I have multiple web apps which all use the same base and basically just change the name of the deployment, service, mapping, etc. This is a wonderful situation for replacements I thought. So I just need to patch the name of the deployment and use it as source for all replacements. So I avoid all the patches in the kustomization.yaml. I defined a replacement.yaml, changing all the values I wanted, but then found out that the replacement.yaml needs to be inside the overlay folder. I completely understand and support, that only values below in the tree of kustomizations are changed, but it would be nice to share a replacement file between overlays.

**Describe the solution you'd like**

Treat replacements like components and make them possible to grab from a different folder somewhere in the repo.

**Current repo structure**

```
- base
  - webapp
    - deployment.yaml
    - service.yaml
    - kustomization.yaml
- overlay
  - webapp-a
    - kustomization.yam
    - replacements.yaml (duplicate)
  - webapp-b
    - kustomization.yaml
    - replacements.yaml (duplicate)
  - ...
```
**Desired repo structure**

```
- base
  - webapp
    - deployment.yaml
    - service.yaml
    - kustomization.yaml
- overlay
  - webapp-a
    - kustomization.yaml (patching the name of deployment, calling replacment with deployment name as source)
  - webapp-b
    - kustomization.yaml (patching the name of deployment, calling replacment with deployment name as source)
  - ...
- replacments
  - webapp
```

**Comment by jamesloosli** [comment]
I'm having this same experience as well. I've got a canned set of replacements that I keep copy-pasting into kustomization.yaml for several services.

I attempted to create a transformer using the replacements transformer, but I'm getting some odd results.

Here's what I tried;
```yaml
# service-a/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

transformers:
  - ../transformers

```

```yaml
# transformers/name.yaml
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: name-transformer
source:
  kind: Deployment
  fieldPath: metadata.name
targets:
  - select:
      kind: Deployment
    fieldPaths:
      - spec.template.spec.containers.0.serviceAccountName
    options:
      create: true
...
```

After running `kustomize build`, the field `serviceAccountName` is never populated. When I put the same replacements directly in kustomization.yaml for a given service-a, I get the results I expect.
