### ISSUE TITLE
Patch Strategy from RollingUpdate to Recreate

### ISSUE THREAD

**Issue by bugbuilder** [kubernetes-sigs/kustomize#470]
Hi,
I'm trying to move from RollingUpdate to Recrete.

base-deployment:
```yml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: example
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
...
```
patch-deployment:
```yml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: example
spec:
  strategy:
    type: Recreate
```
Kustomize-ouput:
```yml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: example
spec:
  strategy:
    type: Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```
I tried with ` $patch: delete ` but without luck, any idea how to accomplish it?

**Comment by Liujingfang1** [comment]
@bugbuilder You can try `$patch: replace`

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: example
spec:
  strategy:
    $patch: replace
    type: Recreate
```
