### ISSUE TITLE
SMP with target does not respect patch GVK

### ISSUE THREAD

**Issue by ciis0** [kubernetes-sigs/kustomize#4710]
**Describe the bug**

When using an Strategic-Merge Patch in kustomization, the GVK from the patch is not used for limiting the `target`, e.g. `labelSelector`. Without GVK in the Kustomize does not accept the SMP.

This makes SMP's with `target` not very comfortable to use as it seems you have to duplicate the GVK in `target` to limit the patch to the wished GVK.

**Files that can reproduce the issue**

Using this patch:

```yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: any
        annotations:
          my-annotation: blubb
    target:
      labelSelector: my-label=foo
```

not only Services, but any resource matching the label selector will get the new annotation but all resource kinds.

see this reproducer repo: https://github.com/ciis0/kustomize-4710

**Expected output**

see reproducer

**Actual output**

see reproducer

**Kustomize version**

discovered with

`{Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:12:45Z GoOs:linux GoArch:amd64}`

verified to still be present in

`{Version:kustomize/v4.5.5 GitCommit:daa3e5e2c2d3a4b8c94021a7384bfb06734bcd26 BuildDate:2022-05-20T20:25:40Z GoOs:linux GoArch:amd64}`

**Platform**

Linux

**Additional context**

**Comment by ciis0** [comment]
this seems to be the relevant place in code:

https://github.com/kubernetes-sigs/kustomize/blob/0c6e827ab81051a95bd061bd1cc917f70335ce86/api/internal/builtins/PatchTransformer.go#L88-L101

maybe an "patchGVK: true" option could be added to copy GVK from SMP to target selector?

**Comment by KnVerey** [comment]
I believe this is behaving as intended: either you specify the `target` field, in which case it is used to identify targets and the patch's identifier (group, version, kind, name, namespace) is ignored, or you don't, in which case the patch's own identifier is used for targeting. 

/triage not-an-issue
/kind support

**Comment by ciis0** [comment]
Ok, I see.

The docs are a little confusing here, because explictly they only tell `name` is ignored when `target` is set.

Thus I always have to write my SMPs with labelSelectors like this?

```
patches:
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: any
        annotations:
          haproxy.router.openshift.io/timeout: 5m
    target:
      group: route.openshift.io
      version: v1
      kind: Route
      labelSelector: label=value
```

not happy about that duplication... ^^
