### ISSUE TITLE
kustomize edit set image should correctly parse both tag and digest

### ISSUE THREAD

**Issue by karlkfi** [kubernetes-sigs/kustomize#4713]
`kustomize edit set image org/repo:tag@sha256:digest` is not parsed correctly.

Currently it results in:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:digest
  name: org/repo:tag
```

If you leave out the digest, the tag gets parsed correctly, but with the digest, the tag is assumed to be part of the image image, which is incorrect.

I would expect them to parse correctly when both supplied.

It's desirable to specify them both to facilitate security requirements as well as human readability, even if the tag is usually ignored by container runtimes when the digest is specified.

**Comment by natasha41575** [comment]
I'm able to reproduce the issue. IIUC, the correct output should be

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:digest
  name: org/repo
  newTag: tag
```

There is some parsing code from https://github.com/kubernetes-sigs/kustomize/pull/4406 that we can probably reuse to resolve this issue. 

/triage accepted
/help
/label good first issue
