### ISSUE TITLE
includeTemplates doesn't work

### ISSUE THREAD

**Issue by TobiasWillig** [kubernetes-sigs/kustomize#4717]
**Describe the bug**

Labels aren't added to the pod metadata and the Deployment spec. `includeTemplates` has no effect.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-kustomization

commonLabels:
  app: test-server

labels:
  - pairs:
      app.kubernetes.io/name: test-server
      app.kubernetes.io/instance: test-server
      app.kubernetes.io/version: ${SERVER_VERSION}
      app.kubernetes.io/component: test
      app.kubernetes.io/part-of: test
      app.kubernetes.io/managed-by: test
      app.kubernetes.io/created-by: test
    includeTemplates: true

resources:
  - deployment.yaml
```

deployment.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server
spec:
  replicas: 1
  template:
    metadata:
      name: test-server
    spec:
      restartPolicy: Always
      containers:
        - name: test-server
          image: test-server
          ports:
            - containerPort: 8080

```

**Expected output**

The Pod should have all defined labels from (`commonLabels` and `labels`).

**Actual output**

The Pod has only the labels from `commonLabels`. 

**Kustomize version**

{Version:kustomize/v4.5.5 GitCommit:daa3e5e2c2d3a4b8c94021a7384bfb06734bcd26 BuildDate:2022-05-20T20:25:40Z GoOs:linux GoArch:amd64}

**Platform**

Ubuntu 20.04 LTS inside WSL
