### ISSUE TITLE
Does kustomize support to patch the resource which are not part of base

### ISSUE THREAD

**Issue by damvinod** [kubernetes-sigs/kustomize#4718]
I have a busybox deployment already running in the cluster with 1 replica.

I am using kustomize to patch the replicas of the deployment to 2.

Below are the details.

### Error Details
```
error: no matches for Id Deployment.v1.apps/busybox-kustomize.web; failed to find unique target for patch Deployment.v1.apps/busybox-kustomize.web
error: no objects passed to apply
```

### Command
`kubectl kustomize . | kubectl apply -f - `

### Folder Structure
```
├── busybox-patch.yaml
└── kustomization.yaml
```

### busybox-patch.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-kustomize
  namespace: web
  labels:
    app: busybox-kustomize
spec:
  replicas: 2
```

### kustomization.yaml
```yaml
patchesStrategicMerge:
- busybox-patch.yaml

namespace: web
```
