### ISSUE TITLE
skipping nameprefix of some resource kinds 

### ISSUE THREAD

**Issue by hiteshgakhreja1234** [kubernetes-sigs/kustomize#4722]
Hi All

is it possible to have kustomization file avoid adding prefixes to few resources

service
configmap
storageclass

I tried using this link but this is not working 
https://stackoverflow.com/questions/69882949/kustomize-namesuffix-skip-on-some-resources

I tried creating a configuration file in kustomize and try skip: true but still its not behaving as expected
hgakhrej@C02G104NMD6M configuration % cat kustomizeconfig/skip-secrets-prefix.yaml 
namePrefix:
- path: metadata/name
  kind: Configmap
  skip: true
- path: metadata/name
  apiVersion: v1
  kind: Service
  skip: true

I tried below example also but no luck
https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0519#preparation-step-resource0

Can anybody provice me some working example for this or anykind of workaround

**Comment by annasong20** [comment]
Hi @hiteshgakhreja1234,

 I don't believe you can currently `skip` in kustomize, but you can specify all the kinds under `configurations` you'd like to apply `namePrefix` to other than the 3 (service, configmap, storageclass) you mentioned above. This is as instructed by the link you provided: https://stackoverflow.com/questions/69882949/kustomize-namesuffix-skip-on-some-resources 
 
 For example, on kustomize v4.5.7, with the following setup:
`kustomization.yaml`
```yaml
resources:
- configmap.yaml
- secret.yaml

namePrefix: my-
configurations:
- prefix-rules.yaml
```

`prefix-rules.yaml`
```yaml
namePrefix:
- path: metadata/name
  apiVersion: v1
  kind: Secret
```

`configmap.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
```

`secret.yaml`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret
```

I get the following output running `kustomize build`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
```
