### ISSUE TITLE
kustomize edit set image should be idempotent 

### ISSUE THREAD

**Issue by simon-an** [kubernetes-sigs/kustomize#4724]
Version:kustomize/v4.4.1

**Is your feature request related to a problem? Please describe.**

When running `kustomize edit set image` multiple times with the same parameters  the result is multiple images blocks.

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- app-deployment.yaml
- app-service.yaml
images:
- name: app:latest
  newTag: "123456"
  newName: anyregistry/app

images:
- name: app:latest
  newTag: "123456"
  newName: anyregistry/app
```

**Describe the solution you'd like**

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- app-deployment.yaml
- app-service.yaml
images:
- name: app:latest
  newTag: "123456"
  newName: anyregistry/app

```
