### ISSUE TITLE
Prefix/suffix transformer for Ingress secretName object

### ISSUE THREAD

**Issue by mathijshoogland** [kubernetes-sigs/kustomize#4725]
**Describe the bug**
I'm trying to configure kustomize so it adds a suffix to the TLS secret name of an Ingress object, I've got the following configuration:

config.yaml
```
nameSuffix:
  - kind: Ingress
    path: /spec/tls/0/secretName
```
ingress.yaml

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: john.doe
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 80
  tls:
  - hosts:
    - john.doe
    secretName: letsencrypt-<THIS-IS-WHERE-SUFFIX-SHOULD-COME>
```
kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -suffix
resources:
- ingress.yaml
configurations:
  - config.yaml
```
**Expected output**
I'd expect the value of secretName to become letsencrypt-suffix.

**Actual output**

Error: considering field '/spec/tls/0/secretName' of object Ingress.v1.networking.k8s.io/ingress.[noNs]: cannot set or create an empty field name

**Kustomize version**

Kustomize 4.5

**Platform**

macOS

**Comment by mathijshoogland** [comment]
If there's any way I can help with the triage, let me know, happy to help.

**Comment by KnVerey** [comment]
The error message definitely isn't helpful, but there are two issues with the configuration file. First, fieldspecs don't start with a leading slash. If you fix that, you'll get a "wrong node kind" error, because fieldspecs don't take indexes to dig through arrays--if the transformer supports arrays (which prefix/suffix does, fortunately), just jump straight to the field. This seems to get the result you want:

```yaml
nameSuffix:
  - kind: Ingress
    path: spec/tls/secretName
```

output:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-suffix
spec:
  rules:
  - host: john.doe
    http:
      paths:
      - backend:
          service:
            name: service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - john.doe
    secretName: letsencrypt-<THIS-IS-WHERE-SUFFIX-SHOULD-COME>-suffix
```

LMK if I've missed something

/kind support
/kind documentation
/remove-kind bug
/triage resolved
