### ISSUE TITLE
[Question] patchMultipleObjects  get one container?

### ISSUE THREAD

**Issue by linuxme** [kubernetes-sigs/kustomize#4728]
1. cat <<EOF >deployments.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: deploy1
spec:
  template:
    metadata:
      labels:
        old-label: old-value
    spec:
      containers:
        - name: nginx
          image: nginx
          args:
          - one
          - two
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: deploy2
spec:
  template:
    metadata:
      labels:
        key: value
    spec:
      containers:
        - name: busybox
          image: busybox
EOF
```
2. cat <<EOF >patch.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: istio-proxy
          image: docker.io/istio/proxyv2
          args:
            - proxy
            - sidecar
EOF
```

3. cat <<EOF >kustomization.yaml
```
resources:
  - deployments.yaml

patches:
  - path: patch.yaml
    target:
      kind: Rollout
EOF
```

4. execte： kubectl kustomize  .   #give the result as follows：
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: deploy1
spec:
  template:
    metadata:
      labels:
        old-label: old-value
    spec:
      containers:
      - args:
        - proxy
        - sidecar
        image: docker.io/istio/proxyv2
        name: istio-proxy
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: deploy2
spec:
  template:
    metadata:
      labels:
        key: value
    spec:
      containers:
      - args:
        - proxy
        - sidecar
        image: docker.io/istio/proxyv2
        name: istio-proxy
```

6. adesired outcome：
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: deploy1
spec:
  template:
    metadata:
      labels:
        old-label: old-value
    spec:
      containers:
      - args:
        - proxy
        - sidecar
        image: docker.io/istio/proxyv2
        name: istio-proxy
      - name: nginx
         image: nginx
         args:
         - one
         - two
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: deploy2
spec:
  template:
    metadata:
      labels:
        key: value
    spec:
      containers:
      - args:
        - proxy
        - sidecar
        image: docker.io/istio/proxyv2
        name: istio-proxy
      - name: busybox
          image: busybox
```
