### ISSUE TITLE
YAML Anchor Override Support

### ISSUE THREAD

**Issue by BorisO** [kubernetes-sigs/kustomize#4747]
Kustomize can't build manifests in some situations when YAML anchors are used. I know that this has been previously addressed in https://github.com/kubernetes-sigs/kustomize/issues/3675 which fixes anchors in some cases but I'm still having an issue when an anchor overrides are used. I'm using `kubectl v1.23` to run the kustomize build. This `kubectl` version uses   kustomize `v4.4.1` which should have the mentioned anchor fix.

Note that in the below example the `name` and `label` anchors work as expected. Only the `default` anchor causes issues.
This build works as expected using `kubectl v1.20`

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
```

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name test-app
  labels:
    app.kubernetes.io/name: test-app
    app.kubernetes.io/part-of: test-app
    app.kubernetes.io/instance: test-app
spec:
  selector:
    matchLabels: &labels
      app.kubernetes.io/instance: test-app
  replicas: 1
  template:
    metadata:
      name: *name
      labels: *labels
    spec:
      restartPolicy: Always
      containers:
        - &default
          name: default
          image: test-app
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          command: ["/bin/sh"]
          args: ["-c", "echo 'test app'"]
        - <<: *default
          name: second
          resources:
            limits:
              memory: 200Mi
              cpu: 0.1
          command: ["/bin/sh"]
          args: ["-c", "echo 'test app 2'"]

```

**Actual output**
```
E0803 14:30:11.589029   58695 run.go:120] "command failed" err="map[string]interface {}{\"apiVersion\":\"apps/v1\", \"kind\":\"Deployment\", \"metadata\":map[string]interface {}{\"labels\":map[string]interface {}{\"app.kubernetes.io/instance\":\"test-app\", \"app.kubernetes.io/name\":\"test-app\", \"app.kubernetes.io/part-of\":\"test-app\"}, \"name\":\"test-app\"}, \"spec\":map[string]interface {}{\"replicas\":1, \"selector\":map[string]interface {}{\"matchLabels\":map[string]interface {}{\"app.kubernetes.io/instance\":\"test-app\"}}, \"template\":map[string]interface {}{\"metadata\":map[string]interface {}{\"labels\":map[string]interface {}{\"app.kubernetes.io/instance\":\"test-app\"}, \"name\":\"test-app\"}, \"spec\":map[string]interface {}{\"containers\":[]interface {}{map[string]interface {}{\"args\":[]interface {}{\"-c\", \"echo 'test app'\"}, \"command\":[]interface {}{\"/bin/sh\"}, \"image\":\"test-app\", \"imagePullPolicy\":\"Always\", \"name\":\"default\", \"resources\":map[string]interface {}{\"limits\":map[string]interface {}{\"cpu\":1, \"memory\":\"4Gi\"}}}, map[interface {}]interface {}{\"args\":[]interface {}{\"-c\", \"echo 'test app'\"}, \"command\":[]interface {}{\"/bin/sh\"}, \"image\":\"test-app\", \"imagePullPolicy\":\"Always\", \"livenessProbe\":interface {}(nil), \"name\":\"second\", \"resources\":map[string]interface {}{\"limits\":map[string]interface {}{\"cpu\":0.1, \"memory\":\"200Mi\"}}}}, \"restartPolicy\":\"Always\"}}}}: json: unsupported type: map[interface {}]interface {}"
```
**Kustomize version**

`v4.4.1`

**Platform**

macOS
