### ISSUE TITLE
Support adding namespace to ServiceMonitor namespaceSelector

### ISSUE THREAD

**Issue by sagikazarmark** [kubernetes-sigs/kustomize#4762]
**Is your feature request related to a problem? Please describe.**

ServiceMonitors are often supposed to be namespace constrained for a specific application. It's possible to apply namespace selectors to a ServiceMonitor:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: some-monitor
spec:
  namespaceSelector:
    matchNames:
      - NAMESPACE
```

It would be nice if that namespace could come from Kustomize.

**Describe the solution you'd like**

Make transformers array aware:

```yaml
namespace:
  - path: spec/namespaceSelector/matchNames[]/0 // Or some alternative syntax
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
    create: true
```

**Describe alternatives you've considered**

Using replacements could be an option, but using the namespace transformer would be much more elegant.

**Additional context**

#1710 describes a solution using `vars`, but that's considered deprecated.

#610 added partial support for this and this specific use case actually came up in https://github.com/kubernetes-sigs/kustomize/pull/610#issuecomment-493067658 , but it doesn't work at the moment.

I realize this is a very specific use case, but it's also a very common one and the final solution could always be made generic enough not to be constrained to this specific use case.
