### ISSUE TITLE
Use labels to filter `source` in `replacements`

### ISSUE THREAD

**Issue by davinkevin** [kubernetes-sigs/kustomize#4763]
**Is your feature request related to a problem? Please describe.**

As a kustomize & Sealed Secrets user, I would like to use `replacement` to populate the field `            spec.tls.0.secretName` of an Ingress. 

The problem is I don't know beforehand the secret name, but only labels. And obviously, I have multiple SealedSecrets in my setup (some for applications, some for certificates…). 

```yaml
replacements:
  - source:
      kind: SealedSecret
      name: "I don't know the name…"
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.0.secretName
        options:
          create: true
```

So if I use something like this, the result is an error like this `Error: multiple matches for selector SealedSecret.[noVer].[noGrp]/[noName].[noNs]`, which is expected from the [specification](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#source)

**Describe the solution you'd like**

I would like to add some more advanced criteria to resolve the object I want in `source`. In my context, and to be Kubernetes idiomatic, using `labels` would do the job perfectly. For example, a potential API for that: 

```yaml
replacements:
  - source:
      kind: SealedSecret
      matchLabels:
        app.kubernetes.io/component: certificate
        app.kubernetes.io/env: dev
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.0.secretName
        options:
          create: true
```
 

**Describe alternatives you've considered**

I don't have any alternative at the moment, so I have to duplicate the name and update the entry in my `Ingress` definition every time I want to deploy it. 

**Additional context**

No additional context, feel free to ask question if you want. The method to be modified, IIUC is named [`selectSourceNode`](https://github.com/kubernetes-sigs/kustomize/blob/2f2ba40876b3b6c5b33281e8dee503010a1bc537/api/filters/replacement/replacement.go#L65-L87)

**Comment by natasha41575** [comment]
We will accept this request, but the syntax for label and/or annotation selection in the source selector should be identical to the label/annotation selection in targets. Looking through the kustomize code, it looks like target selectors are specified with the fields `annotationSelector` and `labelSelector`, which you can see here https://github.com/kubernetes-sigs/kustomize/blob/482e8930fc256672afd4ff5d531ec8fe80d35119/api/types/selector.go#L28.

/triage accepted

**Comment by davinkevin** [comment]
Thank you 🙏 and really good thing to use this api rather than the Kubernetes one. Being able to use labels and/or annotations is a great idea too.

**Comment by jamesloosli** [comment]
Is there any documentation or working examples for labelSelector?

I'm trying the following;

base.yaml
```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: api-regional
  labels:
    host-type: regional
spec:
  hostname: "api.nonprod-us-west-2.some.link"
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: api-apex
  labels:
    host-type: apex
spec:
  hostname: "api.some.link"
```

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: some-namespace
replacements:
  - path: ../replacements/tld.yaml
```

tld.yaml
```
source: { kind: ConfigMap, name: some-env, fieldPath: data.DOMAIN_SUFFIX }
targets:
  # apex hosts
  - select:
      kind: Host
      labelSelector: some-host-type=apex
    fieldPaths: [spec.hostname]
    options: { delimiter: ".", index: 2 }

  # regional hosts
  - select:
      kind: Host
      labelSelector: some-host-type=regional
    fieldPaths: [spec.hostname]
    options: { delimiter: ".", index: 3 }
```

I feel like there's something basic I'm missing here. I'm using the document here; https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api, to guess at what `labelSelector` is expecting, but I don't seem to be on track. I get this error;

`error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field Selector.targets.select.labelSelector of type string`

**Comment by davinkevin** [comment]
@jamesloosli the proposition is not yet implemented 🤔, I think this is why you have this error.

**Comment by vugardzhamalov** [comment]
Dear @natasha41575  @davinkevin,

Is this correct to assume that what you are proposing with will be somewhat identical to 'labelSelector' and/or 'annotationSelector' already implemented in patch transformer, see [here](https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_patchtransformer_)? If so I am correct to assume that these could be implemented both for replacements 'source:' and 'targets[select:]' and 'targets[reject:]'? Thank you!

**Comment by vugardzhamalov** [comment]
The only thing of course is that originally @davinkevin was talking about the list of labels to match. And current implementation in patch transformer does matching on a single label/annotation. This brings me to another question (I guess I shouldn't even ask here) to @natasha41575 : do you think it will be difficult to replace strings with arrays in patch transformer as well? Thank you!

**Comment by davinkevin** [comment]
In my case, only one `labelSelector` or `annotationSelector` couldn't be enough. In k8s, we use both with a lot of information to make debug/operation simpler. In this issue context, it could looks like this: 

```
replacements:
  - source:
      kind: SealedSecret
      labelSelector:
        app.kubernetes.io/type: certificate
        app.kubernetes.io/env: dev
        app.kuberentes.io/domain: "*.foo.com"
    targets:
      …
```

It was really my original request to have multiple filter. Obviously, using a syntax like [this one](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api) is something possible, but a bit strange for a new API.
