### ISSUE TITLE
Allow kustomize to create parameters from non-kustomize created resources

### ISSUE THREAD

**Issue by nnachefski** [kubernetes-sigs/kustomize#4771]
When attempting to use kustomize to parameterize a postgres DB password, i get this:

`{data.master_db_password}}' cannot be mapped to a field in the set of known resources
`
from this config:
```
  - name: master_db_password
    objref:
      kind: Secret
      name: sandboxmaster-pguser-master
      apiVersion: v1
    fieldref:
      fieldpath: data.master_db_password
```

I'm getting this error because the secret "sandboxmaster-pguser-master" is not in the resources list in kustomize.  Kustomize is not responsible for creating this object, the CrunchyData Postgres operator is.  

Is it at all possible to be able to reference objects not populated by Kustomize?  If not, could it be?  I'd hate to have to store that secret in a git repo (gitops) just so kustomize can reference it.
