### ISSUE TITLE
Documentation: make the effect of a specified namespace on transformer application clear

### ISSUE THREAD

**Issue by wrouesnel** [kubernetes-sigs/kustomize#4772]
https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs page does not make any mention of the effect that having resource explicit namespace specifications will have on the application of things like the `nameReference` transformer. I wasted a good couple of hours trying to debug this, with no warnings or error messages to guide me.

The examples page (which is highly ranked in Google) should make it clear that resources with explicit namespaces will not be handled properly by the transformers this applies to. Currently the nameReference transformer is the one I know, but it looks like there are others (i.e. the image transformer).

**Describe alternatives you've considered**

Fixing kustomize so this type of special behavior did not exist would be a possibility (preferable?), but at present getting the documentation consistent seems vital - it is *not* obvious and there are no warnings it is happening. I'm not sure if there is a good reason for the current behavior.

**Comment by natasha41575** [comment]
Thanks for filing the issue. We're not certain what you're referring to when you say "resource explicit namespace specifications", do you mind providing a specific example of the issue you're running into, and what you expect to happen vs what is actually happening?

We are happy to have more documentation, we're just not sure what documentation is needed here.

/triage needs-information
/kind documentation

**Comment by wrouesnel** [comment]
From the documentation linked, if you take something like this:

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # resources.yaml contains a Gorilla and a AnimalPark
  - resources.yaml

# Add name prefix "sample-" to the Gorilla's and AnimalPark's name
namePrefix: sample-

configurations:
  # Tie target Gorilla to AnimalPark's referrer spec.gorillaRef.
  # Once Gorilla name is changed, the AnimalPark referrerd Gorilla name will be changed as well.
  - nameReference.yaml
```

nameReference.yaml
```
nameReference:
  - kind: Gorilla
    fieldSpecs:
      - kind: AnimalPark
        path: spec/gorillaRef/name
```
but your resources.yaml looks like this:
```
apiVersion: animal/v1
kind: Gorilla
metadata:
  name: gg
  namespace: Some-Namespace
---
apiVersion: animal/v1
kind: AnimalPark
metadata:
  name: ap
spec:
  gorillaRef:
    name: gg
    kind: Gorilla
    apiVersion: animal/v1
```
then silently the behavior will skip updating the name on the Gorilla kind - i.e. rather then the supplied example
```
apiVersion: animal/v1
kind: AnimalPark
metadata:
  name: sample-ap # changed by `namePrefix`
spec:
  gorillaRef:
    apiVersion: animal/v1
    kind: Gorilla
    name: sample-gg # changed by `nameReference`
---
apiVersion: animal/v1
kind: Gorilla
metadata:
  name: sample-gg # changed by `namePrefix`
```

you'll get this

```
apiVersion: animal/v1
kind: AnimalPark
metadata:
  name: sample-ap # changed by `namePrefix`
spec:
  gorillaRef:
    apiVersion: animal/v1
    kind: Gorilla
    name: sample-gg # changed by `nameReference`
---
apiVersion: animal/v1
kind: Gorilla
metadata:
  name: gg # changed by `namePrefix`
  namespace: Some-Namespace
```

There's no warning that this is happening, and AFAICT no documentation this is the case.
