### ISSUE TITLE
Using replacements with a commonLabel as a source

### ISSUE THREAD

**Issue by dharmeshgordhan** [kubernetes-sigs/kustomize#4776]
Hi,

Any suggestions on how I can use replacements to read the commonLabels value? I'm getting an error at the moment: `Error: nothing selected by Kustomization.[noVer].[noGrp]/[noName].[noNs]:commonLabels.[pipeline/branch]`.

I'm looking to have my app pod, and database pod deployed on the same node. I'm using podAffinity to do this. My deployment method means application feature branches get deployed, and each deployment has the unique label `pipeline/branch`. I'm looking to use `pipeline/branch` label as the `labelSelector` for podAffinity. I wanted to use replacements to take the label from my kustomization.yaml and replaceme the `BRANCH_NAME` is my deployment. 

sample of my kustomize manifest:
```
# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: tier
                operator: In
                values:
                  - database
        - labelSelector:
            matchExpressions:
              - key: pipeline/branch
                operator: In
                values:
                  - BRANCH_NAME
```

```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: staging
commonLabels:
  pipeline/branch: feature/myBranch
replacements:
  - source:
      kind: Kustomization
      name: staging
      fieldPath: commonLabels.[pipeline/branch]
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:
          - spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution.[1].matchExpressions.[key=pipeline/branch].values.0
```

**Comment by KnVerey** [comment]
It isn't possible to target the Kustomization itself using the replacements transformer--it only operates on the resource data that the Kustomization has already produced. Would you be able to instead target the label field on the `app` Deployment in question? Since the label transformer runs first, I would expect the value you want to be there when the replacement transformer runs.

/triage needs-information
/kind feature

**Comment by dharmeshgordhan** [comment]
I had a quick go, but it threw an error. I will try more diligently in a couple of days - thought I'd share what I had so far.
```
`metadata.labels.pipeline/branch` is missing for replacement source Deployment.[noVer].[noGrp]/db.[noNs]
```

I had a look at the output without the replacements, and the attribute looks like it's there. Trying with square brackets around the label for the replacement source threw: 

```
`error looking up replacement source: list path element must contain fieldName=fieldValue for element to match`
```

Here's a sample of the deployment object output from kustomize:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    pipeline/branch: bloop
  name: db
```

Here's the replacements:
```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: staging
commonLabels:
  pipeline/branch: feature/myBranch
replacements:
  - source:
      kind: Deployment
      name: db
      fieldPath: metadata.labels.pipeline/branch
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:
          - spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution.[1].matchExpressions.[key=pipeline/branch].values.0
```

**Comment by dharmeshgordhan** [comment]
Okay! Got it working :) Not toooo sure why it didn't work the first time.

Thanks!

```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  pipeline/branch: bloop
replacements:
  - source:
      kind: Deployment
      name: db
      fieldPath: metadata.labels.pipeline/branch
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:          
 - spec.template.spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution.1.labelSelector.matchExpressions.0.values.0
```
