### ISSUE TITLE
[Question] Reference Kind Kustomization in replacement transformer

### ISSUE THREAD

**Issue by in-cloud-opensource** [kubernetes-sigs/kustomize#4780]
Hi,
is it possible to reference `kind: Kustomize` in a replacement transformer?

`replacment.yaml`
```
source:
  kind: Kustomization
  group: kustomize.config.k8s.io
  version: v1beta1  
  name: some-name
  fieldPath: metadata.labels.keyspace
targets:
  # ...
```

`kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
   name: some-name
   labels:
      keyspace: test
replacments:
 - replacement.yaml
# ...
```
Regards
