### ISSUE TITLE
[Question] Generate secret for cert manager

### ISSUE THREAD

**Issue by stereoit** [kubernetes-sigs/kustomize#4781]
Hi, how do I generate secret use in cert manager? I have this kustomize.yml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "cert-manager"

secretGenerator:
- name: cloudflare-api-token-secret
  envs: 
    - env.secret

resources:
- issuer.yaml
```

This issuer:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory

    email: my.email@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
```

And I provide the key via `cho "api-token=$CF_API_TOKEN" > env.secret`.

I see the secret generated fine, but kustomized does not update the reference to it (it still shows the name without suffix) :(

```
apiVersion: v1
data:
  api-token: Tjc4RXNTeEZOVlNdasdkasdhksbfb4fTTDdaRw==
kind: Secret
metadata:
  name: cloudflare-api-token-secret-927g6d95c8
  namespace: cert-manager
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: jan.zubr@dnai.ai
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
---
```

Any hints what might be wrong?

**Comment by KnVerey** [comment]
I think the problem is that the name reference transformer that takes care of updating names doesn't know about the ClusterIssuer custom resources type. Please have a look at the `nameReference` aspects of this guide and re-open if it does not solve your issue: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md.

/close
/triage resolved
/kind support

**Comment by jtermine** [comment]
For the cert manager problem listed above -- 

Using the example above from [https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md),

create a file called `$DEMO_HOME/kustomizeconfig/clusterIssuer.yaml` with these contents:

```yaml
nameReference:
  - kind: Secret
    fieldSpecs:
      - path: spec/acme/externalAccountBinding/keySecretRef/name
        kind: ClusterIssuer
```

Add this block to your `$DEMO_HOME/kustomization.yaml` file

```yaml
configurations:
  -  kustomizeconfig/ClusterIssuer.yaml
```

And presto!
