### ISSUE TITLE
[Question] PrefixTransformer select resource by name and GVK

### ISSUE THREAD

**Issue by in-cloud-opensource** [kubernetes-sigs/kustomize#4782]
Hi,

is there a way to apply transformers like the PrefixTransformer only to a resource selected by name and GVK (group, version, kind)?
Example:
```
apiVersion: builtin
kind: PrefixTransformer
metadata:
  name: global-config-transformer
prefix: app1-
fieldSpecs:
- kind: ConfigMap
  version: v1
  path: metadata/name
  # additionally select resource by name
  name: some-name
```

From the docs it looks that it is only possible to apply the prefix transformer based on Kind, Version and Group.

If not supported would it make sense to support that feature for some build-in transformers?

Regards
