### ISSUE TITLE
[Question] How can i use variables in kustomization.yaml file 

### ISSUE THREAD

**Issue by Kristin0** [kubernetes-sigs/kustomize#4787]
For example i want in file 
`kustomization.yaml` smth like this

```
resources:
  - deployment.yaml
namespace: $(namespace)

vars:
  - name: namespace
    objref:
      kind: ClusterContext
      name: clustercontext
      apiVersion: msc.test.com/v1alpha1
    fieldref:
      fieldpath: spec.TEST_NAMESPACE
```
