### ISSUE TITLE
Helm charts: updated version field is ignored after first build

### ISSUE THREAD

**Issue by fritzrehde** [kubernetes-sigs/kustomize#4794]
If I run `kustomize build . --enable-helm` with the following kustomization.yaml:
```
helmCharts:
- name: grafana
  version: 6.36.2
  repo: https://grafana.github.io/helm-charts
```
the output displays the correct version number (i.e. 6.36.2). However, once I change the version number in the yaml file (e.g. to 6.36.1) and then run the kustomize build command again, the version is still 6.36.2. Updated version numbers in the yaml seem to be ignored after the first build.

Helm version: 3.9.4
kustomize version: 4.5.7
