### ISSUE TITLE
configMapGenerator unable to replace ConfigMap from a Helm chart

### ISSUE THREAD

**Issue by cjyar** [kubernetes-sigs/kustomize#4799]
**Describe the bug**

Kustomize is unable to replace the contents of a ConfigMap if the ConfigMap comes from the Helm generator.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vault
  namespace: vault
  releaseName: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.22.0

configMapGenerator:
- behavior: replace
  literals:
  - thing=stuff
  name: vault-config
  namespace: vault
  options:
    disableNameSuffixHash: true
```

**Expected output**

It should generate manifests

**Actual output**

```
Error: merging from generator &{0xc00028a5b0 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"vault-config", Namespace:"vault"} does not exist; cannot merge or replace
```

If I remove `behavior: replace` then I get this instead:
```
Error: merging from generator &{0xc0000dc480 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"vault-config", Namespace:"vault"} exists; behavior must be merge or replace
```

**Kustomize version**

```
{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:28:01Z GoOs:darwin GoArch:amd64}
```

**Platform**

macOS

**Comment by annasong20** [comment]
Hi @cjyar, I see the same error running kustomize v4.5.7 on macOS using the given `kustomization.yaml`.

I don't believe this is a bug. Kustomize runs its built-in kustomization fields in a certain order; the `helmCharts` generator is ahead of `configMapGenerator` in that order. Therefore, when kustomize runs `configMapGenerator`, it has yet to generate the helm chart specified and hence, the error. 

An easy workaround is to move the `configMapGenerator`, as a plugin, under `generators` because kustomize runs plugins after built-in fields. You'd run `kustomize build --enable-helm` on the setup below:
`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vault
  namespace: vault
  releaseName: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.22.0

generators:
- configmap-generator.yaml
```

`configmap-generator.yaml`
```yaml
apiVersion: builtin
kind: ConfigMapGenerator
behavior: replace
metadata:
  name: vault-config
  namespace: vault
literals:
  - thing=stuff
options:
  disableNameSuffixHash: true
```

Hope this helps.
