### ISSUE TITLE
krm container mounts relative to base instead of overlay 

### ISSUE THREAD

**Issue by bluebrown** [kubernetes-sigs/kustomize#4800]
**Describe the bug**

I noticed that the krm function container mount is relative to the base instead of the overlay. 

**Files that can reproduce the issue**

```yaml
config.kubernetes.io/function: |
  container:
    image: myreg.azurecr.io/kustomize-plugins/vault-secret
    network: true
    mounts:
      - type: bind
        src: ./mnt
        dst: /tmp/mnt
```

If you look at the tree, you see that a mnt folder was created in base even though the generator is in the staging overlay.

```
kube/services/serials/
├── base
│   ├── kustomization.yaml
│   └── mnt
└── overlays
    └── staging
        ├── kustomization.yaml
        └── secretGenerator.yaml
```

**Expected output**

I expected it to be created in the staging overlay next to the generator config. (Originally I tried to mount from there)

**Actual output**

The mount path was created in the base directory. 

**Kustomize version**

`{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}`

**Platform**

`Debian GNU/Linux 11 (bullseye)`
`5.10.16.3-microsoft-standard-WSL2`
