### ISSUE TITLE
[junior] `helmChartInflationGenerator` is unable to pull the helm chart

### ISSUE THREAD

**Issue by Vanderscycle** [kubernetes-sigs/kustomize#4812]
Unable to use `helmChartInflationGenerator` but the helm command works.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmChartInflationGenerator: # all that it does is a helm pull
  - chartName: argo
    chartRepoUrl: https://argoproj.github.io/argo-helm
    chartVersion: 5.5.5
    releaseName: argo/argo-cd
    releaseNamespace: argocd
```

**Expected output**

Kustomize pulls the chart.

**Actual output**

```bash
Error: Error: chart "argo" version "^5.0.0" not found in https://argoproj.github.io/argo-helm repository
: unable to run: 'helm pull --untar --untardir /home/henri/Documents/infrastructure/charts/argocd/charts --repo https://argoproj.github.io/argo-helm argo --version ^5.0.0' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-1748177833/helm HELM_CACHE_HOME=/tmp/kustomize-helm-1748177833/helm/.cache HELM_DATA_HOME=/tmp/kustom
ize-helm-1748177833/helm/.data] (is 'helm' installed?)
```
```bash
helm search repo argo-cd --version ^5.0.0
# output
NAME            CHART VERSION   APP VERSION     DESCRIPTION
argo/argo-cd    5.5.5           v2.4.12         A Helm chart for Argo CD, a declarative, GitOps...
```
When using the repo directly to find version it does show nothing so the error makes sense.
```bash
helm search repo argo-cd https://argoproj.github.io/argo-helm
No results found
```

**What worked**

```bash
# add the helm repo
helm repo add argo https://argoproj.github.io/argo-helm
```
```bash
NAME                    URL
[...]
argo                    https://argoproj.github.io/argo-helm
```
```bash
helm pull --untar --untardir /home/henri/Documents/infrastructure/charts/argocd/charts argo/argo-cd --version 5.5.5
```
Essentially, I am a bit confused because helm uses the same exact repo to get the right version. It is very possible that, as a junior, I am missing something.

**Kustomize version**

**Platform**

Running on Linux (EndeavourOS)

Kustomize version
```bash
{Version:4.5.7 GitCommit:$Format:%H$ BuildDate:2022-08-12T18:18:43Z GoOs:linux GoArch:amd64}
```
Helm version
```bash
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"dirty", GoVersion:"go1.19"}
```

Works with `gitea`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: git

resources:
  - secrets/

helmChartInflationGenerator:
  - chartName: gitea
    chartRepoUrl: https://dl.gitea.io/charts/
    chartVersion: 6.0.1
    releaseName: gitea
    # override with these custom values
    values: values.yaml
```

Thank you for reading.
