### ISSUE TITLE
helmCharts does not support 1+ instances of same chart, with different versions

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/kustomize#4813]
**Describe the bug**

When I define multiple chart instances in `helmCharts` for same chart but with different versions, the first version defined is pulled and used for all instances.

**Files that can reproduce the issue**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podinfo

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: 6.2.1
    releaseName: podinfo1
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: 6.1.8                                      # <------ same chart, different version
    releaseName: podinfo2
```

**Expected output**

For the supplied `kustomization.yaml` we should see two Deployment resources with different images, but we do not.

**Actual output**

For the supplied `kustomization.yaml` we see two Deployment resources with matching images.

To verify:

```
$ kustomize build --enable-helm | grep -E 'image:.*podinfo'
        image: ghcr.io/stefanprodan/podinfo:6.2.1
        image: ghcr.io/stefanprodan/podinfo:6.2.1
```

**Versions**

Kustomize version: 4.5.7

Helm version: 3.9.4

**Platform**

I don't believe it's relevant, but I am on Mac.

**Additional context**

Since kustomize has a `--helm-command` I wrote a wrapper to inspect the `helm` executions made by kustomize.

Here are the executions:

```
helm version -c --short
helm pull --untar --untardir ./charts --repo https://stefanprodan.github.io/podinfo podinfo --version 6.2.1
helm template podinfo1 ./charts/podinfo --values .../kustomize-helm-3061748730/podinfo-kustomize-values.yaml
helm version -c --short
helm template podinfo2 ./charts/podinfo --values .../kustomize-helm-3953294510/podinfo-kustomize-values.yaml
```

Observerations:

- only 1 `helm pull` of the 1st version, untarred to unversioned path
- two `helm template` execs on the unversioned chart location

I conclude this is not a Helm issue, but a Kustomize issue.

Suggested fix: add the version to the chart directory (eg `podinfo-6.2.1`) and use the versioned dir in the `helm template` execs.

Regards.
