### ISSUE TITLE
Replacement for key

### ISSUE THREAD

**Issue by NickLarsenNZ** [kubernetes-sigs/kustomize#4817]
**Is your feature request related to a problem? Please describe.**

I have a CRD where a map key need to reference a name of a resources (which may or may not have a namePrefix or nameSuffix).

**Describe the solution you'd like**

I would like to be able to replace the map key with the resource name.

**Describe alternatives you've considered**

I wondered about using vars, but see they are deprecated so I won't even try that.

**Additional context**

`kustomization.yml`

```yml
namePrefix: my-project-

resources:
- component.yml
- resiliency.yml

replacements:
- source:
    group: dapr.io
    version: v1alpha1
    kind: Component
    name: pubsub-customers
  targets:
  - select:
      group: dapr.io
      version: v1alpha1
      kind: Resiliency
    fieldPaths:
    - spec.targets.components # this is where it all goes wrong, and it replaces the whole section with the component name.
```

`component.yml`

```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-component
spec: {}
```

`resiliency.yml`

```yml
apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: my-resiliency
spec:
  targets:
    components:
      my-component: # I need this to be named "my-project-my-resiliency", and still contain the original value.
        inbound:
          retry: pubsubRetry
```
