### ISSUE TITLE
Value from YAML fragment that is embedded as multiline scalar value

### ISSUE THREAD

**Issue by christian-2** [kubernetes-sigs/kustomize#4822]
I would like to exact a value from a `ConfigMap` that contains a YAML fragment that is embedded inside another YAML fragment as multlline scalar value. `ConfigMap`s like this  constitute a fairly common pattern with Kubernetes.

The relevant part of my `ConfigMap` looks as follows:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config: |
    test:
      url: https://github.com
```

The relevant part of my `kustomization.yaml` looks as follows:

```
vars:
- name: URL
  objref:
    kind: ConfigMap
    name: config
    apiVersion: v1
  fieldref:
    fieldpath: data.config.test.url
```
This does not work for comprehensible reasons: It assumes that there is a single YAML fragment, not one that embeds another one as multiline string.

I guess what would be needed is support for `fieldpath`s such as `yaml(data.config).test.url`, conceptually speaking. Or am I missing something? Is there support for accessing such embedded values for the purpose of setting environment variables in `kustomization.yaml` and if so, how could this be accomplished in my concrete example.
