### ISSUE TITLE
[Question] How can I place a secret.txt file in base, and then use that .txt-file to generate a secret in overlays/tst

### ISSUE THREAD

**Issue by IP14Y3RI** [kubernetes-sigs/kustomize#4825]
I have the following folder structure:
```
kustomize/
├─ base/
│  ├─ files/
│  │  ├─ some-secret.txt
│  ├─ deployment.yaml
│  ├─ kustomization.yaml
│  ├─ ingress.yaml
├─ overlays/
│  ├─ tst/
│  │  ├─ kustomization.yaml
│  │  ├─ ingress.yaml
│  ├─ prod/
│       ├─ ingress.yaml
│       ├─ kustomizaton.yaml

```
I want to share the some-secret.txt among the tst and prod overlays.

I want to generate the secret using secret generator like so:
```
secretGenerator:
- name: elasticsearch-users
  files:
  - some-secret.txt
  options:
    disableNameSuffixHash: true
```
However, since, some-secret.txt is not a Kubernetes object, I cannot add it to the resources of overlays/tst/kustomization.yaml file.

How can I generate the secret in an overlay through a file that is placed in base, and is not a k8s object?
