### ISSUE TITLE
may not add resource with an already registered id

### ISSUE THREAD

**Issue by dudo** [kubernetes-sigs/kustomize#4832]
## tree

```sh
.
├── base
│   ├── graphql-federated-gateway
│   │   └── kustomization.yaml
│   ├── person-service
│   │   └── kustomization.yaml
│   └── kustomization.yaml
├── components
│   └── flux-automation
│       ├── git-repository.yaml
│       ├── image-policy.yaml
│       ├── image-repository.yaml
│       ├── image-update-automation.yaml
│       └── kustomization.yaml
└── overlays
    ├── develop
    │   └── kustomization.yaml
    └── production
        └── kustomization.yaml
```

## base/person-service

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/flux-automation
patches:
  - target:
      kind: GitRepository
      name: person-service
    patch: |-
      kind: GitRepository
      metadata:
        name: person-service
      spec:
        url: https://github.com/org/repo
  - target:
      kind: Kustomization
      name: person-service
    patch: |-
      kind: Kustomization
      metadata:
        name: person-service
      spec:
        sourceRef:
          name: person-service
  - target:
      kind: ImageUpdateAutomation
      name: person-service
    patch: |-
      kind: ImageUpdateAutomation
      metadata:
        name: person-service
      spec:
        sourceRef:
          name: person-service
  - target:
      kind: ImageRepository
      name: person-service
    patch: |-
      kind: ImageRepository
      metadata:
        name: person-service
      spec:
        image: ghcr.io/org/repo
  - target:
      kind: ImagePolicy
      name: person-service
    patch: |-
      kind: ImagePolicy
      metadata:
        name: person-service
      spec:
        imageRepositoryRef:
          name: person-service
```

## components/flux-automation

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - git-repository.yaml
  - image-update-automation.yaml
  - image-repository.yaml
  - image-policy.yaml
```

```sh
kubectl apply -k apps/overlays/develop --dry-run=client                                                                                                                                        

error: 
  accumulating resources: 
    ...
    recursed merging from path '/Users/dudo/Projects/org/cd/apps/base/person-service': 
      may not add resource with an already registered id: 
        GitRepository.v1beta2.source.toolkit.fluxcd.io/service.[noNs]
```

I would like to reuse the resources from components/flux-automation multiple times. Is this possible?
