### ISSUE TITLE
Annotation `kustomize.config.k8s.io/needs-hash` not working on static resources

### ISSUE THREAD

**Issue by LittleChimera** [kubernetes-sigs/kustomize#4833]
**Describe the bug**

Setting annotation `kustomize.config.k8s.io/needs-hash: "true"` on static resources doesn't add hash suffix to the name. Setting the annotation `internal.config.kubernetes.io/needsHashSuffix: "enabled"` instead gets the expected result.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

resources.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
data:
  foo: bar
```

**Expected output**

```yaml
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  name: foo-798k5k7g9f
```

**Actual output**

```yaml
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
  name: foo
```

**Kustomize version**

4.5.7
