### ISSUE TITLE
 Can you add podLabels and podAnnotations ?

### ISSUE THREAD

**Issue by jaemyeonglee** [kubernetes-sigs/kustomize#4835]
**Is your feature request related to a problem? Please describe.**
I want to add a label to the pod spec only.

**Describe the solution you'd like**
I want to handle it in kustomization.yaml .

**Describe alternatives you've considered**

**Additional context**
Version:kustomize/v4.2.0

`kustomization.yaml`

```
podLabels:
  label_a: a
  label_b: b

podAnnotations:
  anno_a: a
  anno_b: b
```

`before`

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    esMajorVersion: "7"
  labels:
    app: event-master
  name: master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-master
  template:
    metadata:
      labels:
        app: event-master
      name: event-master
    spec:
      ...
```

`after`

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    esMajorVersion: "7"
  labels:
    app: event-master
  name: master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-master
  template:
    metadata:
      annotations:
        anno_a: a <- added
        anno_b: b <- added
      labels:
        app: event-master
        label_a: a <- added
        label_b: b <- added
      name: event-master
    spec:
      ...
```
