### ISSUE TITLE
Component patch not applied when using helmChart generator

### ISSUE THREAD

**Issue by c0c0n3** [kubernetes-sigs/kustomize#4841]
### Describe the bug

After inflating a Helm chart, applying a patch defined in a separate `Component` has no effect. In a nutshell, the problem happens with this kind of setup:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
# the chart to inflate
- name: the-chart
  repo: http://some.where/over/the/rainbow
# ... other fields

components:
# a component containing a patch to apply after inflation
- ../component
```

### Reproducing the issue

I've put together a self-contained, but eensy-weensy testbed to reproduce the issue:

- https://github.com/c0c0n3/anubis.deployment/tree/main/k8s/test/helm

There you can find all the files needed to reproduce, the commands to run as well as expected and actual output.

### Kustomize version
The issue is there both in an old version
* Version: `4.4.0`
* Git commit: `9e8e7a7fe99ec9fbf801463e8607928322fc5245`

and in the latest
* Version: `kustomize/v4.5.7`
* Git commit: `56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7`

### Platform
* Mac OS 11.0.1 (Big Sur)
* (Go) architecture/os: `amd64`/`darwin`

### Additional context
- https://github.com/c0c0n3/anubis.deployment/tree/main/k8s/test/helm

**Comment by marekciel** [comment]
We are seeing the same issue. Strangely enough the images: is working as expected and patching the inflated helmchart.

**Comment by rcarpa** [comment]
I  see a similar problem with configMapGenerators and replacements. So probably related to generator in general.

I have a Component

```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ingress-a.yaml
  - ingress-b.yaml
replacements:
  - source:
      kind: ConfigMap
      name: config
      fieldPath: data.fqdn
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.[secretName=ingress-cert].hosts.0
          - spec.rules.[host=placeholder.com].host
```

If I use a configMapGenerator, it doesn't work with the error `error: accumulating components: accumulateDirectory: "recursed accumulation of path '<some_path>/ingresses': nothing selected by ConfigMap.[noVer].[noGrp]/config.[noNs]:data.fqdn"
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: config
    literals:
      - fqdn=a.com
components:
  - ../ingresses
```

It works, however, with a ConfigMap in the resources field:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  fqdn: a.com
```
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - configmap-config.yaml
components:
  - ../ingresses
```

**Comment by yuwenma** [comment]
@c0c0n3 @rcarpa Kustomize has a dedicated order on which transformation features should run first, and in both cases `components` happens first (before generators). 

To fix the first `helmChart` with `components` case, you can define an overlay directory to "force" `components` runs after the `helmCharts`

```
├── overlay
│   └── kustomization.yaml
├── service.chart
│   ├── charts
│   │   └── servo
│   │       ├── Chart.yaml
│   │       ├── templates
│   │       │   └── deployment.yaml
│   │       └── values.yaml
│   ├── helm-values.yaml
│   └── kustomization.yaml
├── service.plain
│   ├── kustomization.yaml
│   └── rendered-chart.yaml
└── sidecar
    ├── add-container.yaml
    └── kustomization.yaml
```

In the `overlay/kustomization.yaml`
```
resources:
- ../service.chart


components:
- ../sidecar
```

In the `service.chart/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: charts
helmCharts:
- name: servo
  valuesFile: helm-values.yaml
  releaseName: servo
  version: 2.1.7
# remove `components`
```  

@c0c0n3 let me know if you have any further questions. Otherwise feel free to close this issue.
