### ISSUE TITLE
`kustomize create --resources` does not support remote file references

### ISSUE THREAD

**Issue by scodeman** [kubernetes-sigs/kustomize#4842]
**Description**

kustomisation.yaml file accepts url within resources  but the `kustomize` cli does not allow to create the corresponding file

```sh
kustomize create --stack-trace --resources=https://github.com/operator-framework/operator-lifecyclemanager/releases/download/v0.22.0/olm.yaml
```

**Expected output**

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/olm.yaml
```

**Actual output**

```
2022/10/25 15:31:43 https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/olm.yaml has no match
```
**Kustomize version**

kustomize/v4.1.3

**Platform**

macOS amd64

**Additional context**

Could be that the kustomize cli assumes local files or does not follow redirection on fetching url
