### ISSUE TITLE
variable substitution does not always work

### ISSUE THREAD

**Issue by lionelvillard** [kubernetes-sigs/kustomize#486]
Here 2 configmaps:

`configmap.yaml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-pass
data:
  password: admin
```
and `configmap2.yaml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-pass2
data:
  password: $(ADMIN)
```

And a kustomization file:

```
resources:
- configmap.yaml
- configmap2.yaml

vars:
- name: ADMIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mysql-pass
  fieldref:
     fieldpath: data.password
```

when running `kustomize build`, `$(ADMIN)` does not get substituted.

## version 
```
$ kustomize version
Version: {KustomizeVersion:v1.0.8 GitCommit:58492e2d83c59ed63881311f46ad6251f77dabc3 BuildDate:1970-01-01T00:00:00Z GoOs:unknown GoArch:unknown}
```
