### ISSUE TITLE
`replacements` uses base values instead of merged values from a ConfigMap

### ISSUE THREAD

**Issue by swapzero** [kubernetes-sigs/kustomize#4871]
**Describe the bug**
Before going through this report please note that the same logic works when using `vars` (which according to the docs should be replaced by `replacements`). The following example is not a real deployment manifest but just a simple example.

**Files that can reproduce the issue**
Structure:
```
test
├── base
│   ├── configs
│   │   └── cm.env
│   ├── kustomization.yaml
│   └── manifests
│       └── deployment.yaml
└── demo
    ├── configs
    │   └── cm.env
    └── kustomization.yaml
```

- `base/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/deployment.yaml

configMapGenerator:
- name: cm
  envs:
  - configs/cm.env

replacements:
  - source:
      kind: ConfigMap
      name: cm
      fieldPath: data.NAME
    targets:
      - select:
          kind: Deployment
          name: test
        fieldPaths:
        - spec.name
  - source:
      kind: ConfigMap
      name: cm
      fieldPath: data.CITY
    targets:
      - select:
          kind: Deployment
          name: test
        fieldPaths:
        - spec.city
```
- `base/manifests/deployment.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  name: PLACEHOLDER_NAME
  city: PLACEHOLDER_CITY
```
- `base/configs/cm.env`
```
NAME=foo
CITY=bar
```
- `demo/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

configMapGenerator:
- name: cm
  behavior: merge
  envs:
  - configs/cm.env
```
- `demo/configs/cm.env`
```
NAME=another_name
CITY=another_city
```

**Expected output**

- `kustomize build test/demo`
```
apiVersion: v1
data:
  CITY: another_city
  NAME: another_name
kind: ConfigMap
metadata:
  name: cm-27h22g8k89
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  city: another_city
  name: another_name
```

**Actual output**
```
apiVersion: v1
data:
  CITY: another_city
  NAME: another_name
kind: ConfigMap
metadata:
  name: cm-27h22g8k89
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  city: bar # <------- should be the value from demo env
  name: foo # <------- should be the value from demo env
```

**Kustomize version**
```
{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:28:01Z GoOs:darwin GoArch:arm64}
```

**Platform**
M1
```
ProductName:	macOS
ProductVersion:	12.2
BuildVersion:	21D49
```

**Additional context**
It appears that the ConfigMap merge works, yet the values used for replacements are the ones _before_ merge (the base ones).

**Comment by KnVerey** [comment]
/kind support
/triage not-an-issue

The reason this is not working is that the replacements transformer is configured inside the base rather than the overlay. That means the transformation will happen while Kustomize evaluates the base, before importing the resources as the starting point for the overlay. The overlay then directs it to update the existing configmap, but does not include anything to update the deployment as well. The solution is to move the replacements transformer to the overlay.

this is somewhat related to: https://github.com/kubernetes-sigs/kustomize/issues/4524 (substitutions carried out by the replacements transformer do no dynamically create name references for future tracking)

**Comment by swapzero** [comment]
but...I don't want to define the same replacements in each overlay...what's the point of using  `replacements` and bases if they do not work like `vars`? (`vars` will be deprecated and your recommendation is to use `replacements` instead)

**Comment by sambonbonne** [comment]
@swapzero an alternative solution I used was to use a [component](https://kubectl.docs.kubernetes.io/guides/config_management/components/): you can define replacements in a component and set the "values" of the replacement in the overlay.

I would also prefere defining replacements in the base and using my overlay to just defined the values, without than creating a component in the middle. At least, the overlay's `resources` ordering should be respected, for example this dot not work but I would expect it to:

```yaml
# Base kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

replacements:
  - source:
      kind: ConfigMap
      name: configuration
      fieldPath: data.my-config
    targets: # …

---

# Overlay kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-map.yaml # ConfigMap with my-config key loaded before the base
  - ../../base/ # base with replacement, ConfigMap already loaded
```

**Comment by MaheeGamage** [comment]
@sambonbonne Can you explain more how to move replacements into a component and update it with overlay value?

I used following replacement inside a component but I face same issue which it only uses base level namespace

`componentA/replacements.yaml`
```
source:
  kind: Namespace
  fieldPath: metadata.name
targets:
- select:
    kind: Ingress
    name: mlflow-ingress
  fieldPaths:
  - metadata.annotations.[traefik.ingress.kubernetes.io/router.middlewares]
  options:
    delimiter: "-"
    index: 0
```

`componentB/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - path: replacements.yaml
```

**Comment by cnd4** [comment]
@MaheeGamage I see you have two components, in my case the component includes the replacements (all is in one component, except the resource used by the replacement).

Here is an example.

`component/kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - service.yaml

replacements:
  - path: replacement.yaml
```

`component/replacement.yaml`

```yaml
source:
  kind: ConfigMap
  name: configuration
  fieldPath: data.custom_label

targets:
  - select:
      kind: Service
      name: MyService
    fieldPaths:
      - 'metadata.labels.custom'
```

`component/service.yaml`

```yaml
apiVersion: v1
kind: Service

metadata:
  name: MyService

  labels:
    custom: "" # Updated by replacement

spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
```

`overlays/kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../component

# Also works with any not-generated ressource, this is just for the example
configMapGenerator:
  - name: configuration
    literals:
      - "custom_label=My custom label!"
    options:
      disableNameSuffixHash: true
```

<details>
<summary>So when you run <code>kustomize build overlays/final</code>, you get:</summary>
<pre lang="yaml">
apiVersion: v1
data:
  custom_label: My custom label!
kind: ConfigMap
metadata:
  name: configuration
---
apiVersion: v1
kind: Service
metadata:
  labels:
    custom: My custom label! # 🎉 
  name: MyService
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
</pre>
</details>
