### ISSUE TITLE
nameReference breaks when adding outer Kustomization (multiple identical base imports)

### ISSUE THREAD

**Issue by paul-bormans** [kubernetes-sigs/kustomize#4880]
I need to include a base manifest multiple times and since (obviously) their names will clash i like to use a Kustomization to make the names / namespace unique I do this using a nameSuffix + namespace and then use a nameReference to fix all references to the namespace name. This technique works just fine when i apply it on only 1 included overlay but as soon as a include another then i get no errors but the nameReferences no longer work.

Reproduce in following minimized setup:

./base/prometheus/kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus.yaml
````
./base/prometheus/prometheus.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: my-placeholder
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - my-placeholder
```
./overlay/a/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/prometheus

nameSuffix: -suffix-a
namespace: namespace-a
configurations:
  - namespace-reference.yaml
```

./overlay/a/namespace-reference.yaml
```
nameReference:
  - kind: Namespace
    apiVersion: v1
    fieldSpecs:
      - kind: Prometheus
        path: spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution[]/podAffinityTerm/namespaces[]
```
./overlay/a/namespace.yaml
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-placeholder
```

./overlay/b/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/prometheus

nameSuffix: -suffix-b
namespace: namespace-b
configurations:
  - namespace-reference.yaml
```

./overlay/b/namespace-reference.yaml
```
nameReference:
  - kind: Namespace
    apiVersion: v1
    fieldSpecs:
      - kind: Prometheus
        path: spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution[]/podAffinityTerm/namespaces[]

```

./overlay/b/namespace.yaml
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-placeholder

```

./overlay/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- a
- b
```

**Expected output**

```
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-a
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s-suffix-a
  namespace: namespace-a
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - namespace-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-b
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s-suffix-b
  namespace: namespace-b
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - namespace-b
```

**Actual output**

```
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-b
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s-suffix-a
  namespace: namespace-a
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - my-placeholder
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s-suffix-b
  namespace: namespace-b
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - my-placeholder

```

As can be seen the nameSuffix and namespace specifiers both behave as expected but the nameReference no longer updates the "placeholders".

**Kustomize version**

{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}

**Platform**

Linux

**Comment by paul-bormans** [comment]
We found a solution by using replacements iso nameReference, so effectively changing:

```
configurations:
  - namespace-reference.yaml
```

into:

```
replacements:
- path: replacements.yaml
```

having (for instance):
```
- source: 
    kind: Namespace
    version: v1
  targets:
  - select: 
      kind: Prometheus
    fieldPaths:
    - spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution.0.podAffinityTerm.namespaces.0
```
