### ISSUE TITLE
[Question] Built-in PatchTransformers supports add/replace content from yaml file?

### ISSUE THREAD

**Issue by thirumurthis** [kubernetes-sigs/kustomize#4881]
Using Kustomzie I am trying to generate manifest for k8s, is there any option to directly use an yaml file within PatchTransformer built in plugin instead of passing map of values?

Below works when the map of value is passed to PatchTransformer

- Directory structure of the files

```
example
 |_ base
 |    |_ app1
 |       |_deployment.yaml
 |       |_ kustomization.yaml
 |_ overlay
 |       |_staging
 |           |_ kustomization.yaml
 |           |_ addAffinity.yaml
 |_ common
        |_ affinity_common.yaml
```

- Content of  `staging/kustomization.yaml` file content looks like below

```yaml
bases:
    - ../base/app1/

transformers:
  - addAffinity.yaml
```
- `app1/deployment.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:1.22.1
        ports:
        - containerPort: 80
```

- `app1/kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - deployment.yaml
```

- Content of `staging/addAffinity.yaml` 

```yaml
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-affinity
target:
    kind: Deployment
patch : |-
  - op: add
    path: /spec/template/spec/affinity
    value:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - simple-deployment
          topologyKey: "kubernetes.io/hostname"
```

Executing below command it works as expected. 

```
> kustomize build overlay/staging/ 
```

Question: 

What I am looking is, placing the content in a yaml file and refer it in PatchTransformer value in place of value map.
Something like below

The addAffinity.yaml to directly refer the yaml file.

```yaml
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-affinity-prop
target:
    group: apps
    kind: Deployment
  - op: add
    path: '/spec/template/spec/affinity'
    value:
	  - common_affinity.yaml # <--------------------  pass the yaml file directly
```

where the `affinity_common.yaml` 

```yaml
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - simple-deployment
        topologyKey: "kubernetes.io/hostname"
```

Is it achievable with Kustomzie, I just want to substitute the value from yaml directly, now it considers the yaml as value.

```yaml
#...
        app: nginx-app
        env: demo
    spec:
      affinity: 
	   - common_affinity.yaml
      containers:
      - image: nginx:1.22.1
        name: nginx-app
        ports:
        - containerPort: 80
```
[Stackoverflow link for details](https://stackoverflow.com/questions/74496671/can-kustomize-built-in-patchtransformers-take-yaml-file-instead-of-map-of-values)
