### ISSUE TITLE
Add generatorOptions

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#489]
Add an option field in kustomization.yaml to
- allow disable appending namehash to generated secrets/configmaps #459
- allow add annotations/labels #353 
- allow setting shell #362
- set timeout for executing command, move timeout from SecretGenerator to GeneratorOptions

These options will have a global impact. All configmapGenerator and secretGenerator in one kustomization.yaml will follow the same option.

**Comment by Liujingfang1** [comment]
Add documentation as well.

**Comment by Liujingfang1** [comment]
doc PR #501

**Comment by schweikert** [comment]
Cool!

I wonder: what was the motivation to implement this only as a global option, and not specific to single generators?

Maybe in the future it could be also specified like this:

    configMapGenerator:
    - name: ldap-configmap
      generatorOptions:
       disableHash: true

**Comment by mgoodness** [comment]
Following up on @schweikert's request, I'd like to be able to add different labels to my generated ConfigMaps. I.e.

````
configMapGenerator:
- name: fluent-bit
  labels:
    component: fluent-bit
  files:
  - fluent-bit.conf
  - parsers.conf
- name: fluentd
  labels:
    component: fluentd
  files:
  - fluentd.conf
```
