### ISSUE TITLE
Helm chart generated resources are prefixed with RELEASE-NAME

### ISSUE THREAD

**Issue by b1zzu** [kubernetes-sigs/kustomize#4897]
**Describe the bug**

I want to generate the configuration from a Helm char, but the generated resources are all prefixed with `RELEASE-NAME`.

**Files that can reproduce the issue**

kustomization.yaml

```
helmCharts:
  - name: postgres-operator
    repo: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator
    version: v1.8.2
    includeCRDs: false # Probably should be set to true
```

**Expected output**

That resources are not prefixed with `RELEASE-NAME`

**Actual output**

Resources are prefixed with `RELEASE-NAME`

**Kustomize version**

`{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}`

**Platform**

`Fedora 37`

**Comment by brianpursley** [comment]
Try including `releaseName` in your `kustomization.yaml`, like this:

```
helmCharts:
  - name: postgres-operator
    repo: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator
    version: v1.8.2
    includeCRDs: false # Probably should be set to true
    releaseName: foo
```

**Comment by Lindenk** [comment]
I'm r into the same issue. Setting `releaseName` does in fact change the prefix, but there seems to be no way to remove it (ie setting `releaseName: ""` sets it to a default `release-name-`)

**Comment by b1zzu** [comment]
Same here I can change the `releaseName` but not remove it

**Comment by mrclrchtr** [comment]
same problem here.. why is this closed?

**Comment by zimmertr** [comment]
You should really be able to disable this....

**Comment by paranoiasystem** [comment]
I have temporarily resolved in this way

```ah
kustomize build --enable-helm . | sed 's/release-name-//g'  | kubectl apply -f - --server-side
```

**Comment by xgalaxy** [comment]
This is because the Helm charts you are deploying have templates on the `.Release.Name`.
To fix it you can do one of the following:

- Create a values file with the field `fullnameOverride` and add it to the `helmChart` section of your `kustomize` file
- Or, add the `fullnameOverride` directly to the `kustomize` file under `helmChart.valuesInline`

For example:
```
helmCharts:
  - name: cassandra
    repo: https://charts.bitnami.com/bitnami/
    namespace: cool-beans
    valuesFile: values.cassandra.yaml
    valuesInline:
      fullnameOverride: cassandra
    includeCRDs: true
```
