### ISSUE TITLE
replacement not using generated value

### ISSUE THREAD

**Issue by chronicc** [kubernetes-sigs/kustomize#4903]
### What happened?

I am creating a secret with the secretGenerator and a user resource which uses a CRD. The user uses the secret and thus needs to know the exact name of the secret. The secret however gets a generated name with a random string attached as suffix. When the final manifest is build by kubernetes, the user resource however is using the secret name without the suffix.

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user.yaml

secretGenerator:
  - name: rabbitmq-admin-credentials
    behavior: create
    envs:
      - secret-admin-credentials.env

replacements:
  - source:
      kind: Secret
      name: rabbitmq-admin-credentials
      fieldPath: metadata.name
    targets:
      - select:
          group: rabbitmq.com
          version: v1beta1
          kind: User
          name: rabbitmq-admin
        fieldPaths:
          - spec.importCredentialsSecret.name

commonLabels:
  app: rabbitmq
namespace: default
```

```
# secret-admin-credentials.env
username=admin
password=password
```

```yaml
# user.yaml
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-admin
spec:
  importCredentialsSecret:
    name: rabbitmq-admin-credentials
  rabbitmqClusterReference:
    name: rabbitmq
  tags:
    - administrator
```

**Output**

```yaml
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: rabbitmq
    env: local
  name: rabbitmq-admin-credentials-fd8288cb7g
  namespace: default
type: Opaque
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  labels:
    app: rabbitmq
    env: local
  name: rabbitmq-admin
  namespace: default
spec:
  importCredentialsSecret:
    name: rabbitmq-admin-credentials
  rabbitmqClusterReference:
    name: rabbitmq
  tags:
  - administrator
```

### What did you expect to happen?

The user resource references the generated secret name:

```yaml
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  username: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: rabbitmq
    env: local
  name: rabbitmq-admin-credentials-fd8288cb7g
  namespace: default
type: Opaque
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  labels:
    app: rabbitmq
    env: local
  name: rabbitmq-admin
  namespace: default
spec:
  importCredentialsSecret:
    name: rabbitmq-admin-credentials-fd8288cb7g
  rabbitmqClusterReference:
    name: rabbitmq
  tags:
  - administrator
```

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml

secretGenerator:
  - name: test-secret
    behavior: create
    envs:
      - secret.env

replacements:
  - source:
      kind: Secret
      name: test-secret
      fieldPath: metadata.name
    targets:
      - select:
          kind: Pod
          name: test-pod
        fieldPaths:
          - spec.containers.[name=nginx].env.[name=foobar].valueFrom.configMapKeyRef.name
```

```yaml
# resources.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: foobar
          valueFrom:
            configMapKeyRef:
              key: foo
              name: undefined
```

```yaml
#secret.env
foo=bar
```

### Expected output

```yaml
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test-secret-572hm7m64f
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - env:
    - name: foobar
      valueFrom:
        configMapKeyRef:
          key: foo
          name: test-secret-572hm7m64f
    image: nginx
    name: nginx
```

### Actual output

```yaml
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test-secret-572hm7m64f
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - env:
    - name: foobar
      valueFrom:
        configMapKeyRef:
          key: foo
          name: test-secret
    image: nginx
    name: nginx
```

### Kustomize version

{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}

### Operating system

Linux
