### ISSUE TITLE
`nameReference` `configuration` is injecting undesired namespace field

### ISSUE THREAD

**Issue by kriswuollett** [kubernetes-sigs/kustomize#4917]
### What happened?

The `nameReference` in `configurations:` updates `namespace` in addition to `name` even if `namespace` was never set as a sibling property. The word `namespace` is not mentioned anywhere in the [name reference transformer](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#name-reference-transformer) documentation.

Resources may fail to apply if `namespace` is not a valid sibling field.

### What did you expect to happen?

Don't inject/update `namespace` unless the resource defines it.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-namespace

configurations:
  - namingConfiguration.yaml

resources:
  - rabbitmqUser.yaml

secretGenerator:
  - name: user-credentials
    literals:
      - username=joe
      - password=welcome
```

```yaml
# namingConfiguration.yaml
nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: User
        path: spec/importCredentialsSecret
```

```yaml
# rabbitmqUser.yaml
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: joe
spec:
  rabbitmqClusterReference:
    name: my-rabbitmq-cluster
  importCredentialsSecret:
    name: user-credentials
```

### Expected output

```yaml                                                           
apiVersion: v1
data:
  password: d2VsY29tZQ==
  username: am9l
kind: Secret
metadata:
  name: user-credentials-47fhgh582m
  namespace: my-namespace
type: Opaque
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: joe
  namespace: my-namespace
spec:
  importCredentialsSecret:
    name: user-credentials-47fhgh582m
  rabbitmqClusterReference:
    name: my-rabbitmq-cluster
```

### Actual output

```yaml                                                        
apiVersion: v1
data:
  password: d2VsY29tZQ==
  username: am9l
kind: Secret
metadata:
  name: user-credentials-47fhgh582m
  namespace: my-namespace
type: Opaque
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: joe
  namespace: my-namespace
spec:
  importCredentialsSecret:
    name: user-credentials-47fhgh582m
    namespace: my-namespace
  rabbitmqClusterReference:
    name: my-rabbitmq-cluster
```

### Kustomize version

v4.5.7

### Operating system

MacOS

**Comment by KnVerey** [comment]
The problem is that the path in your fieldSpec is pointing to a Mapping node rather than a Scalar node. When that is the case, yes, Kustomize will assume both `name` and `namespace` need to be managed. The solution is to point Kustomize directly to the name field:

```yaml
nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: User
        path: spec/importCredentialsSecret/name
```

When I try your example with that change, I get the desired output.

/triage not-an-issue
/kind support
/kind documentation
/close
