### ISSUE TITLE
images feature overrides all uses of YAML anchors used for image name

### ISSUE THREAD

**Issue by filip-zyzniewski** [kubernetes-sigs/kustomize#4927]
### What happened?

changing a name of the image using the [images feature](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md) results in a replacement of all values referring to an YAML anchor, if this anchor was used for the pre-replacement image name.

In the reproduction example, `spec.template.spec.containers[0].name` got changed from `"foo"` to `"bar"`.

### What did you expect to happen?

I expected only `spec.template.spec.containers[0].image` to be changed.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &appName foo
spec:
  template:
    spec:
      containers:
        - name: *appName
          image: *appName
```

```yaml
# kustomization.yaml
resources:
  - deployment.yaml
images:
  - name: foo
    newName: bar
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - image: bar
        name: foo
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  template:
    spec:
      containers:
      - image: bar
        name: bar
```

### Kustomize version

{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:28:01Z GoOs:darwin GoArch:arm64}

### Operating system

MacOS
