### ISSUE TITLE
Warn when nameReference is being ignored due to namespace via logging options

### ISSUE THREAD

**Issue by wrouesnel** [kubernetes-sigs/kustomize#4934]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

When using nameReference updates, such as when using the configMapGenerator, the current behavior is that objects which specify a namespace will be excluded from any nameReference update.

This behavior is not well documented, and there is no warning that this is the cause of the exclusion.

Kustomize should have logging options for the build process which provide warnings or at least notifications that this is happening - i.e. the exclusion for "sameNamespace" is knocking an object out of nameReference update consideration.

### Why is this needed?

Because I just spent many hours culminating in stepping through the replacement code before I realized that manifest I was working with specified a namespace on the custom resource definition I was looking at, and that this was why the no name reference updates were working for me (whereas they were in another repository).

This behavior is *not* obvious or expected, and it should be possible to get a warning that it is happening. IMO this should be a default enabled warning too, as it is again, generally not what you would expect from the overall typical use case of Kustomize.

### Can you accomplish the motivating task without this feature, and if so, how?

No. There is no way to extract an explanation of why any part of the name substitution system did or did not succeed, which makes debugging unexpected behavior time consuming.

### What other solutions have you considered?

The only other solution would be a substantial documentation improvement to make this behavior clear, but this would depend on adding the relevant text to _every_ location that nameReference transformation is mentioned. This would lower the terseness of the documentation for describing the common case, while still leaving users with no immediate warning that the uncommon case was impacting them.

However, updating the nameReference transformer page of the documentation to show an example where specifying a namespace (or one of other possible excluders) has the effect it does would at least provide help in identifying the source.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by natasha41575** [comment]
Thank you for filing this issue. I'm sorry to hear that you had to spend so many hours debugging something that ended up being unexpected behavior from kustomize.

> When using nameReference updates, such as when using the configMapGenerator, the current behavior is that objects which specify a namespace will be excluded from any nameReference update.

Do you mind providing an example set of manifests that can reproduce this issue? This sounds strange to me, because in theory kustomize should be using namespaces in addition to name to match nameReferences.

/triage needs-information

**Comment by wrouesnel** [comment]
```yaml
---
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- web.yaml

configMapGenerator:
- name: config
  literals:
  - SOMEVALUE=thisvalue
```
```yaml
---
# web.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: web
      app.kubernetes.io/name: web
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: web
        app.kubernetes.io/name: web
        app.kubernetes.io/component: app
    spec:
      containers:
      - name: the-application
        image: the-application-image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: config
````

Using the following comand the above succeeds:

`kustomize build .`

```
apiVersion: v1
data:
  SOMEVALUE: thisvalue
kind: ConfigMap
metadata:
  name: config-7tkt5d9789
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: web
      app.kubernetes.io/part-of: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: web
        app.kubernetes.io/part-of: web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-7tkt5d9789
        image: the-application-image
        imagePullPolicy: Always
        name: the-application
```

but if there's a namespace sitting on the deployment:

```yaml
---
# web.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: ns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: web
      app.kubernetes.io/name: web
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: web
        app.kubernetes.io/name: web
        app.kubernetes.io/component: app
    spec:
      containers:
      - name: the-application
        image: the-application-image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: config
```

then we get (with 
`kustomize build .`)

```yaml
apiVersion: v1
data:
  SOMEVALUE: thisvalue
kind: ConfigMap
metadata:
  name: config-7tkt5d9789
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: ns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: web
      app.kubernetes.io/part-of: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: web
        app.kubernetes.io/part-of: web
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config
        image: the-application-image
        imagePullPolicy: Always
        name: the-application
```

The issue is there is no way to be warned that this is happening. In large YAML files across complex deployments this is a very easy oversight to make. There should be some logging or warning possible when this sort of exclusion is happening - at least when the configuration *would* otherwise be substituted (because I'm using the same names in the right places) but it's going to be rejected because there's a namespace attached to the object (because this is most likely a bug or oversight, not intended since colliding names like this is not something you would normally want to do anyway).
