### ISSUE TITLE
Images - Resolve Previous Name

### ISSUE THREAD

**Issue by crocinsocks** [kubernetes-sigs/kustomize#4936]
### What happened?

Kustomize was unable to use a previous name when setting image tag. Simply ignores line.

### What did you expect to happen?

I would have expected the previous name to be able to be used and only the tag to be updated. This is the only change that I can't seem to make over 100's of app(n) that would otherwise require significant amount more "bases" for each app when all that is need is a simple tag change. Namespaces for environments are used so that other changes between staging, development, production are minimal and do not require a environment base for each app.. 

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# app(n)/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: name
  newName: newName
```

```yaml
# environment/development/kustomization.yaml

resources:
- app(n)

images:
- name: name
  newTag: dev
```

### Expected output

```yaml
image: newName:dev
```

### Actual output

```yaml
image: newName
```

### Kustomize version

4.5.7

### Operating system

None
