### ISSUE TITLE
Missing config maps are not reported if they are used to back a volume mount

### ISSUE THREAD

**Issue by paulmarshall** [kubernetes-sigs/kustomize#4937]
### What happened?

`kustomize` was presented with a k8s deployment featuring a volume mounted with a config map.

The config map didn't exist  

### What did you expect to happen?

Kustomize to error - reporting the volume mounted with a config map that didn't exist

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v4.5.4

### Operating system

Linux
