### ISSUE TITLE
Kustomize can't find helm binary

### ISSUE THREAD

**Issue by jimethn** [kubernetes-sigs/kustomize#4939]
### What happened?

Kustomize fails to render my helm chart.

```
jonathan@ion:~/homelab/applications/mimir$ kustomize build . --enable-helm
Error: : unable to run: 'helm version -c --short' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-2594331247/helm HELM_CACHE_HOME=/tmp/kustomize-helm-2594331247/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-2594331247/helm/.data] (is 'helm' installed?)
```

The kustomization.yaml contains only a `helmCharts` definition. Helm is installed via snap

```
jonathan@ion:~/homelab/applications/mimir$ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
jonathan@ion:~/homelab/applications/mimir$ which helm
/snap/bin/helm
```

### What did you expect to happen?

The chart to be rendered.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
kind: Kustomization
namespace: cert-manager

helmCharts:
  - name: cert-manager
    releaseName: my-cert-manager
    namespace: cert-manager
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}

### Operating system

Linux
