### ISSUE TITLE
The example does not work. (examples/transformerconfigs/images)

### ISSUE THREAD

**Issue by johnzheng1975** [kubernetes-sigs/kustomize#4941]
### What happened?

After I try as: https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/images
The result is:
![image](https://user-images.githubusercontent.com/17720035/208584927-2d3e4d58-386a-468c-957f-2f60a68929ed.png)
The spec/runLatest/container/image cannot be replaced.
Please verify. Thanks.

### What did you expect to happen?

```yaml
apiVersion: config/v1
kind: MyKind
metadata:
  name: testSvc
spec:
  runLatest:
    container:
      image: new-crd-image:new-v1-tag
```

### How can we reproduce it (as minimally and precisely as possible)?

Just as the example show. https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/images
$ kustomize version
{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Expected output

```yaml
apiVersion: config/v1
kind: MyKind
metadata:
  name: testSvc
spec:
  runLatest:
    container:
      image: crd-image
```

### Actual output

```yaml
apiVersion: config/v1
kind: MyKind
metadata:
  name: testSvc
spec:
  runLatest:
    container:
      image: crd-image
```

### Kustomize version

{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:36:27Z GoOs:linux GoArch:amd64}

### Operating system
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

**Comment by natasha41575** [comment]
I can't reproduce this issue with the latest kustomize. Following the linked example, I end up with:

```
apiVersion: config/v1
kind: MyKind
metadata:
  name: testSvc
spec:
  containers:
  - image: my-docker2@sha256:25a0d4
    name: ecosystem
  - image: prod-mysql:v3
    name: testing-1
  runLatest:
    container:
      image: new-crd-image:new-v1-tag
```

where the container image appears to be correct. Could you try upgrading to kustomize v4.5.7 and see if you still have this issue?

/kind support
/triage not-reproducible
