### ISSUE TITLE
why does the yaml generated by version 4.5.7 delete the annotations parameter

### ISSUE THREAD

**Issue by fengshunli** [kubernetes-sigs/kustomize#4961]
### What happened?

why does the yaml generated by version 4.5.7 delete the annotations parameter?
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/18587688/211240393-1208fb67-b0dc-4bfc-ba91-d1c5e194750f.png">
but in version 3.8.9 it is normal

### What did you expect to happen?

use version 3.8.9 —load_restrictor can generate the parameters of annotations, but it cannot be generated by using the —load-restictor of version 4 or above

### How can we reproduce it (as minimally and precisely as possible)?

{{- if not .Values.externalCertInjection.enabled }}
apiVersion: v1
kind: Secret
metadata:
  annotations: {{- toYaml .Values.secretAnnotations | trim | nindent 4 }}
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: gatekeeper-webhook-server-cert
  namespace: '{{ .Release.Namespace }}'
{{- end }}

### Expected output

{{- if not .Values.externalCertInjection.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: gatekeeper-webhook-server-cert
  namespace: '{{ .Release.Namespace }}'
{{- end }}

### Actual output
reference link https://github.com/open-policy-agent/gatekeeper
kustomize build --load-restrictor LoadRestrictionsNone cmd/build/helmify | go run cmd/build/helmify/*.go

### Kustomize version

4.5.7

### Operating system

None

**Comment by ephesused** [comment]
I was curious, so I took a look at this one. I boiled it down to a simplified test case.

It's worth highlighting that the patch does not contain valid annotations. From https://github.com/open-policy-agent/gatekeeper/blob/253124ed/cmd/build/helmify/kustomize-for-helm.yaml#L203-L210

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations: HELMSUBST_SECRET_ANNOTATIONS
  name: gatekeeper-webhook-server-cert
  namespace: gatekeeper-system
```

**Simplified testcase**

kustomization.yaml

```yaml
resources:
  - resources.yaml
patchesStrategicMerge:
  - patches.yaml
```

resources.yaml

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
```

patches.yaml

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations: HELMSUBST_SECRET_ANNOTATIONS
  name: my-secret
```

With those files:

```
$ /src/kustomize/kustomize-v3.8.9 build .
apiVersion: v1
kind: Secret
metadata:
  annotations: HELMSUBST_SECRET_ANNOTATIONS
  name: my-secret
$ /src/kustomize/kustomize-master build .
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
$
```

If I change the kustomization so that it uses `patches` instead of `patchesStrategicMerge`, then master fails with a complaint:

```
$ /src/kustomize/kustomize-v3.8.9 build .
apiVersion: v1
kind: Secret
metadata:
  annotations: HELMSUBST_SECRET_ANNOTATIONS
  name: my-secret
$ /src/kustomize/kustomize-master build .
Error: invalid Kustomization: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
$
```

Not surprisingly, the problem scenario for v3.8.9 is when the resource has annotations. With the following resources.yaml:

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    key: value
  name: my-secret
```

v3.8.9 runs into trouble:

```
$ /src/kustomize/kustomize-v3.8.9 build .
Error: wrong Node Kind for  expected: MappingNode was ScalarNode: value: {"HELMSUBST_SECRET_ANNOTATIONS"}
$
```
