### ISSUE TITLE
name reference with array in the path

### ISSUE THREAD

**Issue by droger88** [kubernetes-sigs/kustomize#4969]
### What happened?

kustomize name reference path does not seem to work with array.
we are using istio virtual service, and I want to have the `host` under `destination` to be replace with the service name, how can I achieve it?
I have tried 
- `sepc/http/0/route/0/destination/host`
- `sepc/http/route/destination/host`
- `sepc/http/*/route/*/destination/host`

### What did you expect to happen?

I expect the name of the service under virtual service to be replaced by the service name with prefix

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../../base/virtualservice.yaml
  labels:
    app: mayapp
    app.kubernetes.io/managed-by: kustomize-v4.5.7
  name: mayapp-virturalservice
spec:
  gateways:
  - golang-gateway
  hosts:
  - somehost
  http:
  - match:
    - uri:
        prefix: /products
    name: default
    route:
    - destination:
        host: my-service.  #<---- I want this to be replaced with myapp-my-service
        port:
          number: 8080
```

### How can we reproduce it (as minimally and precisely as possible)?

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
  #- hpa.yaml
  - gateway.yaml
  - virtualservice.yaml
  - routes.yaml
namePrefix: "myapp-"
commonLabels:
  app: "myapp"
configurations:
- ../base/transform-config/configuration.yaml
```

VirtualService
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virturalservice
  namespace: ht-apps
spec:
  hosts:
    - "somehost.come"
  gateways:
    - gateway
  http:
  - name: default
    match:
      - uri: 
          prefix: "/products"
    route:
    - destination:
        port:
          number: 8080
        host: my-service
```
transform-config/configuration.yaml
```
nameReference:
- kind: Gateway
  fieldSpecs:
  - path: spec/gateways
    kind: VirtualService
- kind: Service
  fieldSpecs:
  - path: sepc/http/0/route/0/destination/host
    kind: VirtualService
  - path: spec/to/name
    kind: Route
```

service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    monitoring.coreos.com/enable-monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 8090
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9000
      targetPort: 9000
      protocol: TCP
```

### Expected output

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../../base/virtualservice.yaml
  labels:
    app: golang
    app.kubernetes.io/managed-by: kustomize-v4.5.7
  name: golang-virturalservice
  namespace: ht-apps
spec:
  gateways:
  - golang-gateway
  hosts:
  - some host
  http:
  - match:
    - uri:
        prefix: /products
    name: default
    route:
    - destination:
        host: my-service
        port:
          number: 8080
```

### Actual output

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../../base/virtualservice.yaml
  labels:
    app: golang
    app.kubernetes.io/managed-by: kustomize-v4.5.7
  name: golang-virturalservice
  namespace: ht-apps
spec:
  gateways:
  - golang-gateway
  hosts:
  - some host
  http:
  - match:
    - uri:
        prefix: /products
    name: default
    route:
    - destination:
        host: myapp-my-service
        port:
          number: 8080
```

### Kustomize version

4.5.7

### Operating system

MacOS
