### ISSUE TITLE
Error: trouble configuring builtin PatchTransformer with config:

### ISSUE THREAD

**Issue by mynkkmr** [kubernetes-sigs/kustomize#4972]
Hi all! 

I have updated kustomize from **3.6.1 to 4.5.5** version. After updating it to **4.5.5** the kustomize build has started to throw mentioned error below. I tried applying the file directly using kubectl which ran successfully but not sure why it doesn't work with kustomize it could be formatting or the commands have changed over time. 

**Command:** 

```
kustomize edit add patch --path azure-argocd.yaml
kustomize build .
```

**kustomize build . --stack-trace**

```
**Error: trouble configuring builtin PatchTransformer with config: `
path: azure-argocd.yaml
`: unable to parse SM or JSON patch from** [apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  oidc.azure.clientSecret: clientsecretvalue

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: | -
    name: Azure
    issuer: https://login.abc.com/
    clientID: onlyclientid
    clientSecret: $oidc.azure.clientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
  url: https://abc.com

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: | -
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    g, "org-admin", role:org-admin
    g, "org-readonly", role:readonly
]

```
**kustomization.yaml**

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: azure-argocd.yaml

```

**azure-argocd.yaml**

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  oidc.azure.clientSecret: clientsecretvalue

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: | -
    name: Azure
    issuer: https://login.abc.com/
    clientID: onlyclientid
    clientSecret: $oidc.azure.clientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
  url: https://abc.com

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: | -
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    g, "org-admin", role:org-admin
    g, "org-readonly", role:readonly

```

**kustomize version**
`{Version:kustomize/v4.5.5 GitCommit:daa3e5e2c2d3a4b8c94021a7384bfb06734bcd26 BuildDate:2022-05-20T20:21:22Z GoOs:darwin GoArch:amd64}`
