### ISSUE TITLE
namespace name should not be changed in override

### ISSUE THREAD

**Issue by sanderma** [kubernetes-sigs/kustomize#4979]
### What happened?

When creating a namespace resource, and setting the namespace property in an overlay, the namespace name is changed.

```yaml
#./ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: original
```

```yaml
#./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: different

resources:
  - ns.yaml
```

`kustomize build .`

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: different
```

### What did you expect to happen?

I would expect this to happen for _namespaced_ resources, but not for a cluster scoped object (like a namespace itself)

The Namespace object I expect should still be called `original`

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
#./ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: original
```

```yaml
#./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: different

resources:
  - ns.yaml
```

### Expected output

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: original
```

### Actual output

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: different
```

### Kustomize version

v4.5.7

### Operating system

MacOS

**Comment by KnVerey** [comment]
The standard configuration for the namespace transformer does ignore cluster-scoped objects in general, but Namespace itself is an intentional exception, and a long-standing behaviour we cannot change at this point. If you see any other cluster-scoped resources being changed, please do report that as a bug.

However, there's a way to configure the namespace transformer to ignore `metadata.name` in Namespace! If you use the following configuration in the `transformers` field instead of using the `namespace` field, you should get the result you want:

```yaml
apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: notImportantHere
  namespace: different
fieldSpecs: # feel free to omit these if you don't use the two resource types below
- path: spec/service/namespace
  group: apiregistration.k8s.io
  kind: APIService
  create: true
- path: spec/conversion/webhook/clientConfig/service/namespace
  group: apiextensions.k8s.io
  kind: CustomResourceDefinition
```

Docs are here: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_namespacetransformer_
This advanced expression of the transformer also has an `unsetOnly` option that you can set to `true` to never override existing values, if that helps your use case.

/triage resolved
/close
