### ISSUE TITLE
Remote openapi: "panic: invalid schema file"

### ISSUE THREAD

**Issue by cazzoo** [kubernetes-sigs/kustomize#4988]
### What happened?

I tried to put my openapi description to a remote location and it's failing.
Kustomize appears to find the schema invalid while it is working just fine when putting the openapi spec next to the Kustomize file locally.

### What did you expect to happen?

Kustomize file to fetch the remote openapi and use it.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

openapi:
  path: https://mygitrepo.com/kustomize-openapi/-/raw/main/org.apache.camel.v1.Integration.json
resources:
  - mybase.yaml
```

```yaml
# openapi
{
  "definitions": {
    "org.apache.camel.v1.Integration": {
      "description": "Integration is the Schema for the integrations API",
      "properties": {
        "spec": {
          "description": "the desired Integration specification",
          "properties": {
            "template": {
              "description": "Pod template customization",
              "properties": {
                "spec": {
                  "description": "the specification",
                  "properties": {
                    "containers": {
                      "description": "Containers",
                      "type": "array",
                      "x-kubernetes-patch-merge-key": "name",
                      "x-kubernetes-patch-strategy": "merge"
                    }
                  },
                  "required": ["containers"],
                  "type": "object"
                }
              },
              "type": "object"
            }
          },
          "type": "object"
        }
      },
      "type": "object",
      "x-kubernetes-group-version-kind": [
        {
          "group": "camel.apache.org",
          "kind": "Integration",
          "version": "v1"
        }
      ]
    }
  }
}
```

### Expected output

```yaml

```

### Actual output

```log
panic: invalid schema file

goroutine 1 [running]:
sigs.k8s.io/kustomize/kyaml/openapi.initSchema()
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.7/openapi/openapi.go:610 +0xe5
sigs.k8s.io/kustomize/kyaml/openapi.isNamespaceScopedFromSchema(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.7/openapi/openapi.go:380
sigs.k8s.io/kustomize/kyaml/openapi.IsNamespaceScoped({{0xc000032c20?, 0x10?}, {0xc00002a224?, 0x2?}})
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.7/openapi/openapi.go:376 +0x85
sigs.k8s.io/kustomize/kyaml/openapi.IsCertainlyClusterScoped(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.7/openapi/openapi.go:390
sigs.k8s.io/kustomize/kyaml/resid.NewGvk({0xc0000341c8?, 0x1228c60?}, {0xc0000341d9?, 0xc00054b180?}, {0xc00002a224?, 0xf5dd92?})
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.7/resid/gvk.go:27 +0x131
sigs.k8s.io/kustomize/kyaml/resid.GvkFromNode(0x0?)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.7/resid/gvk.go:33 +0xd3
sigs.k8s.io/kustomize/api/resource.(*Resource).GetGvk(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/resource/resource.go:57
sigs.k8s.io/kustomize/api/resource.(*Resource).CurId(0xc000394190)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/resource/resource.go:446 +0x65
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).Append(0xc000004168, 0xc000394190)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/resmap/reswrangler.go:77 +0x45
sigs.k8s.io/kustomize/api/resmap.newResMapFromResourceSlice({0xc0000d0310, 0x1, 0xc?})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/resmap/factory.go:130 +0x8d
sigs.k8s.io/kustomize/api/resmap.(*Factory).NewResMapFromBytes(0xc000394000?, {0xc000036800?, 0x21?, 0xc00063f368?})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/resmap/factory.go:73 +0x45
sigs.k8s.io/kustomize/api/resmap.(*Factory).FromFile(0x199?, {0x135ff78?, 0xc000394000?}, {0xc0000c3e90, 0x21})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/resmap/factory.go:60 +0x5a
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateFile(0xc000394050, 0xc00007a040, {0xc0000c3e90, 0x21})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/internal/target/kusttarget.go:525 +0x66
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateResources(0xc000394050, 0x30?, {0xc00027bd00?, 0x1, 0x0?})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/internal/target/kusttarget.go:408 +0xa5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc000394050, 0xf6dcce?)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/internal/target/kusttarget.go:188 +0x3d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0x11984c0?)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/internal/target/kusttarget.go:181 +0xfa
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc000394050)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/internal/target/kusttarget.go:127 +0x5f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/internal/target/kusttarget.go:118
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc00063fd80, {0x1362b60, 0x1862ed8}, {0x17680d0, 0x1})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.11.5/krusty/kustomizer.go:88 +0x317
sigs.k8s.io/kustomize/kustomize/v4/commands/build.NewCmdBuild.func1(0xc0002fb900?, {0xc00030dbc0?, 0x1?, 0x1?})
        /workspace/myClone/kustomize/commands/build/build.go:80 +0x176
github.com/spf13/cobra.(*Command).execute(0xc0002fb900, {0xc00030db90, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fb400)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /workspace/myClone/kustomize/main.go:14 +0x1e
```

### Kustomize version

4.5.5

### Operating system

None
