### ISSUE TITLE
Feature request: base64-decode secrets when using vars

### ISSUE THREAD

**Issue by jcassee** [kubernetes-sigs/kustomize#499]
When using a variable from `vars` that originated in a secret, the secret value is base64 encoded.

Example:

config.env:
```
POSTGRES_DB=dbname
POSTGRES_USER=dbuser
```

secrets.env:
```
POSTGRES_PASSWORD=verysecret
```

pod.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: pod
      image: someapp
      env:
        - name: DATABASE_URI
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DB)

```

kustomization.yaml:
```
resources:
  - pod.yaml

configMapGenerator:
  - name: config
    env: config.env

secretGenerator:
  - name: secrets
    envCommand: "cat secrets.env"

vars:
  - name: POSTGRES_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: postgres
    fieldref:
      fieldpath: metadata.name
  - name: POSTGRES_DB
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
    fieldref:
      fieldpath: data.POSTGRES_DB
  - name: POSTGRES_USER
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
    fieldref:
      fieldpath: data.POSTGRES_USER
  - name: POSTGRES_PASSWORD
    objref:
      apiVersion: v1
      kind: Secret
      name: secrets
    fieldref:
      fieldpath: data.POSTGRES_PASSWORD
```

The goal here is to generate `POSTGRES_URI`, but the `POSTGRES_PASSWORD` variable is base64-encoded, so the URI is invalid.

Would it make sense to base64-decode a secret that is used in a variable?

Issue #267 seems to ask for the same thing, but is resolved either (I'm not sure which) by using patching resources or by noting that the use-case is an unreproducable build, and does not answer whether base64-decoding secrets would be a good idea.

**Comment by Liujingfang1** [comment]
I don't think it's a good idea to inject secrets data through `vars` in kusotmization.yaml.  It is better to use downward API for this case. Add a uri to your secrets. Then in your Pod, use
```
          env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: secrets
                key: uri
```
