### ISSUE TITLE
CommonLabels does not substitute variable

### ISSUE THREAD

**Issue by sosoriov** [kubernetes-sigs/kustomize#4991]
### What happened?

I'm trying to pass as commonLabels the name of the deployment which is available in a variable, however when I output the content the variable only gets replace as main label and not in the other locations.

For example:
```yaml
matchLabels:
      app: nginx
      app.kubernetes.io/managed-by: $(DEPLOYMENT_NAME)
```

### What did you expect to happen?

I expect that the variable $(DEPLOYMENT_NAME) will be replaced everywhere, see below

### How can we reproduce it (as minimally and precisely as possible)?

**On my base I have this:**

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: $(DEPLOYMENT_NAME)

resources:
- deployment.yaml

vars:
- name: DEPLOYMENT_NAME
  objref:
    name: foo
    kind: Deployment 
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.name
```

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        mycustomannotation: "fullName"
      labels:
        app: nginx
    spec:
      containers:
      - name: main
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**and my overlay:**

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
- target:
    kind: Deployment
    name: foo
  patch: |-
    - op: replace
      path: /metadata/name
      value: new-deployment-name
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    app.kubernetes.io/managed-by: new-deployment-name
  name: new-deployment-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      app.kubernetes.io/managed-by: new-deployment-name
  template:
    metadata:
      annotations:
        mycustomannotation: fullName
      labels:
        app: nginx
        app.kubernetes.io/managed-by: new-deployment-name
    spec:
      containers:
      - image: nginx:1.14.2
        name: main
        ports:
        - containerPort: 80

```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    app.kubernetes.io/managed-by: new-deployment-name
  name: new-deployment-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      app.kubernetes.io/managed-by: $(DEPLOYMENT_NAME)
  template:
    metadata:
      annotations:
        mycustomannotation: fullName
      labels:
        app: nginx
        app.kubernetes.io/managed-by: $(DEPLOYMENT_NAME)
    spec:
      containers:
      - image: nginx:1.14.2
        name: main
        ports:
        - containerPort: 80

```

### Kustomize version

v4.5.7

### Operating system

Linux

**Comment by sosoriov** [comment]
Guys nevermind, 

I found out that I need to add some extra configuration in order to extend the variable support on those paths. This is how I fixed it:

var_configuration.yaml
```yaml
varReference:
- path: metadata/name
  kind: Deployment
- path: metadata/name
  kind: ServiceAccount
- path: spec/selector/matchLabels
  kind: Deployment
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: $(TEAM)
  app.kubernetes.io/name: $(DEPLOYMENT_NAME)

resources:
- deployment.yaml
- serviceaccount.yaml

configurations:
- var_configuration.yaml
```
