### ISSUE TITLE
`patchesjson6902` not working correctly

### ISSUE THREAD

**Issue by gabyx** [kubernetes-sigs/kustomize#4993]
### What happened?

**Note:** This issue also appears with `op: test`. See below.

Use `manifest-raw.yaml` as

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: batch|Job|bla
  name: bla
  namespace: bla
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        envFrom:
        image: myimage
        name: bla
      imagePullSecrets:
      - name: artifactory-apikey
      restartPolicy: Never
```

together with `kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - manifest-raw.yaml
kind: Kustomization
patchesJson6902:
  - patch: |-
      - op: add
        path: /metadata/labels/a
        value: hello
    target:
      version: v1
      kind: Job
      name: bla
```

### What did you expect to happen?

Kustomize should have added a label as 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: batch|Job|bla
  name: bla
  namespace: bla
  labels:
    a: hello ### HERE THE VALUE SHOULD HAVE BEEN ADDED
```

### How can we reproduce it (as minimally and precisely as possible)?

Use 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: batch|Job|bla
  name: bla
  namespace: bla
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        envFrom:
        image: myimage
        name: bla
      imagePullSecrets:
      - name: artifactory-apikey
      restartPolicy: Never
```

with

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - manifest-raw.yaml
kind: Kustomization
patchesJson6902:
  - patch: |-
      - op: add
        path: /metadata/labels/a
        value: hello
    target:
      version: v1
      kind: Job
      name: bla
```

### Expected output

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: batch|Job|bla
  name: bla
  namespace: bla
  labels:
    a: hello ## HERE
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        envFrom:
        image: myimage
        name: bla
      imagePullSecrets:
      - name: artifactory-apikey
      restartPolicy: Never
```

### Actual output

```shell
Error: add operation does not apply: doc is missing path: "/metadata/labels/a": missing value
```

If we replace `op: add` with `op: test` the output is also misleading:

```shell
Error: test operation does not apply: is missing path: /metadata/labels/a: missing value
```

### Kustomize version

4.5.7

### Operating system

MacOS
