### ISSUE TITLE
YAML to JSON parsing error when using a numeric as a key in a map?

### ISSUE THREAD

**Issue by spstarr** [kubernetes-sigs/kustomize#5001]
### What happened?

I am trying to apply a Anthos Service Mesh, Istio `PeerAuthentication` CR and get error:

This is from Config Sync which is running `kustomize build` to render the output:

```
Error: error marshaling into JSON: json unsupported type: map[interface {}]interface {} For more information, see https://g.co/cloud/asm-errors#knv1068
```

However, if I quote the numeric keys then all works as normal. I'm not sure if this is a parsing error in Kustomize.

### What did you expect to happen?

The Resource to apply without error.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
- name: myapp
  version: 0.0.1
  releaseName: my-config-connector
  namespace: default
  valuesFile: values-dev.yaml
```

```yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-peerauth
  namespace: mynamespace
spec:
  selector:
    matchLabels:
       app.kubernetes.io/cluster: mynamespace
  portLevelMtls:
    1234:
      mode: PERMISSIVE
    5000:
      mode: PERMISSIVE
    9000:
      mode: PERMISSIVE
  mtls:
    mode: STRICT
```

### Kustomize version

Config Sync 1.14.0 managed Kustomize 

### Operating system

Other
