### ISSUE TITLE
Endpoint resource cannot be patched on its namespace field

### ISSUE THREAD

**Issue by wilmardo** [kubernetes-sigs/kustomize#5003]
### What happened?

When trying to use an overlay to change the namespace with a JSON patch on the namespace field I get an error:
```console
# kustomize build demo1/
Error: replace operation does not apply: doc is missing path: /spec/namespace: missing value
```

While this field is present when building the base:
```
# kustomize build base/
apiVersion: v1
kind: Endpoints
metadata:
  name: test-endpoint
  namespace: placeholder
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - port: 100
    protocol: TCP
```

This while an Endpoint seems to be a namespaced scoped resource in Kubernetes.

Let me know if information is missing or where I can look in the code to fix this bug :)

### What did you expect to happen?

The base namespace to be changed with the JSON patch.

### How can we reproduce it (as minimally and precisely as possible)?

I made a quick and minimal demo repo to checkout:
https://github.com/wilmardo/kustomize-issue-5002

```
git clone https://github.com/wilmardo/kustomize-issue-5002.git
cd kustomize-issue-5002/
kustomize build demo1/
```

### Kustomize version

4.5.7

### Operating system

MacOS

**Comment by kamuridesu** [comment]
You do not have the path `/spec/namespace` in your file [endpoint.yaml](https://github.com/wilmardo/kustomize-issue-5002/blob/main/base/placeholder/endpoint.yml).

The namespace is located on `/metadata/`, not `/spec/`, so, the following config will work:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: demo1
    target:
      namespace: placeholder
```
See how I replaced the `/spec/` with `/metadata/`?

The output was:

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: test-endpoint
  namespace: demo1
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - port: 100
    protocol: TCP
 ```
