### ISSUE TITLE
Kustomize changing namespace on ClusterRoleBinding in sibling overlay

### ISSUE THREAD

**Issue by nijave** [kubernetes-sigs/kustomize#5008]
### What happened?

Kustomize updated the namespace of a ServiceAccount in ClusterRoleBinding in a different directory.

### What did you expect to happen?

I expect `prometheus-default` CRB to have `namespace: default` and `prometheus-grafana` to have `namespace: grafana-system`

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# ./kustomization.yaml
resources:
 - default
 - new

# ./default/binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default

# ./default/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default

# ./default/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch

# ./default/kustomization.yaml
resources:
 - binding.yaml
 - sa.yaml
 - role.yaml


# ./new/kustomization.yaml
resources:
 - prometheus

# ./new/prometheus/binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: grafana-system

# ./new/prometheus/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

# ./new/prometheus/kustomization.yaml
namespace: grafana-system
resources:
- binding.yaml
- sa.yaml
```

### Expected output

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: grafana-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: grafana-system
```

### Actual output

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: grafana-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: grafana-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: grafana-system
```

### Kustomize version

{Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:28:01Z GoOs:darwin GoArch:arm64}

### Operating system

None

**Comment by KnVerey** [comment]
I think the issue is that since the default name is literally "default", your two SAs start out ambiguous:

```yaml
# These are the same object:

# ./default/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default

# ./new/prometheus/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
```

If you make `namespace: grafana-system` explicit in the SA as you did for the ClusterRoleBinding subject in `./new/prometheus/binding.yaml`, it starts out a distinct object and the name tracking is able to achieve the result you want. Using a placeholder value on both the ClusterRoleBinding subject and the SA also works (as long as the value is the same in both places). Feel free to re-open if I've misunderstood.

Similar to https://github.com/kubernetes-sigs/kustomize/issues/4444

/triage resolved
/kind support
/close
