### ISSUE TITLE
More in examples/transformerconfigs/images#adding-a-custom-resource for path that are both ScalarNode and SequenceNode

### ISSUE THREAD

**Issue by kamok** [kubernetes-sigs/kustomize#5018]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I would like more examples on how to configure the image transformer to accomdate detailed fields besides ScalarNodes.

From my testing, more advanced path traversals like `spec/params[name=foobar]/default` is not supported. This makes the `image` transformer only strictly useful for `SclarNode`, as it isn't possible to path to a specific field if it is an Array / SequenceNode

https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/images#adding-a-custom-resource

It would be nice if the transformer just ignores values that are Sequence, and only worry about Scalar. 

### Why is this needed?

Here's an example use case:

```
kind: Task
spec:
    params:
      - name: image-name
         default: 'image-name-duplicated-everywhere' # string, scalar
      - name: i-dont-want-this-one
         default: ['foo'] # array, sequence
```

In my `configuration`, I point to
```
images:
- path: spec/params[]/default
  kind: Task
```
**which errors out `: visit traversal on path: [default]: wrong Node Kind for default expected: ScalarNode was SequenceNode: value: {[]}`, as expected.**

This doesn't work, fails silently
```
images:
- path: spec/params.[name=image-name]/default
  kind: Task
```

This doesn't work either, fails silently
```
images:
- path: spec/params[name=image-name]/default
  kind: Task
```

### Can you accomplish the motivating task without this feature, and if so, how?

No

### What other solutions have you considered?

I've tried other syntax like the new `*`, and spent a long time in the Issues for answers

### Anything else we should know?

I read here https://github.com/kubernetes-sigs/kustomize/issues/3945
that you're deprecating `configurations`, is it even worth spending time trying to get this to work?

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by annasong20** [comment]
Hi @kamok, the current documented behavior in the `configurations` examples for `images` is actually the extent of the actual behavior, more or less. The `configurations` `path` field is also capable of character escaping, but this is irrelevant to your use case. The list filtering `[field=value]` capability that you reference is limited to [`replacements`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#syntax).

The `path` field in `configurations` is capable of traversing sequences. For example, the setup below should work

```yaml
# kustomization.yaml
resources:
- task.yaml
configurations:
- images.yaml
images:
- name: image-name-duplicated-everywhere
  newName: changed
```

```yaml
# task.yaml
apiVersion: custom/v1
kind: Task
metadata:
  name: my-task
spec:
  params:
    - name: image-name
      image: image-name-duplicated-everywhere
    - name: nginxapp
      image: nginx:1.7.9
```

```yaml
# images.yaml
images:
- kind: Task
  path: spec/params/image
```

If your issue was that you weren't aware of this behavior because the [`configurations` documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) wasn't clear enough about its support for sequences, I can retitle and accept your issue.

Otherwise, the problem with your current setup is that kustomize does not expect a single field to have multiple types. Specifically, the `spec/params/default` field of `Task` can be either a scalar or sequence. The [kubernetes specification](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) only allows a single type for each field, with the `int-or-string` being the only exception. Maybe you could provide some more context on your setup?

/triage needs-information
