### ISSUE TITLE
Patch doesn't seems to work in a component

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [kubernetes-sigs/kustomize#5022]
### What happened?

Hi, I work with a Helm chart that is buggy (editor knows it but does not deliver a fix).
So I create a kustomize patch to fix the buggy resource (and add some custom ConfigMaps). This work like a charm.

But now I want to generate the render manifest to execute my unit tests. So I transform the kustomization.yaml to a component and create another kustomization.yaml in my tests directory to add the `helmChartInflationGenerator` to get the helm rendering and apply the patch upon it. And there, the patch doesn't apply (but the generated configMaps does, which proves that my component is correctly implemented)!

Here is what it looks like:
```
├── patches
│   └── kustomization.yaml (my component)
│       patch.yaml
└── unit-tests
    └── kustomization.yaml
        chart-inflation-generator.yaml
```

### What did you expect to happen?

I expect the ConfigMaps AND the patch would be applied.

### How can we reproduce it (as minimally and precisely as possible)?

kustomization.yaml in patch dir
```yaml
# kustomization.yaml in patch dir
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patch.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: my-app-cluster-role
configMapGenerator:
  - name: custom-configmap-nodejs-noreuse
    behavior: create
    files:
      - shim_noreuse.js
  - name: custom-configmap-nodejs
    behavior: create
    files:
      - shim_normal.js
generatorOptions:
  disableNameSuffixHash: true
```

kustomization.yaml in tests dir
```yaml
# kustomization.yaml in tests dir
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# the following doesn't seems to work by the way...
# helmChartInflationGenerator:
# - name: my-chart
#   repo: https://my-repository
#   version: 1.0.0
#   releaseName: test
#   namespace: my-namespace
#   valuesFile: values.yaml

generators:
- chart-inflation-generator.yaml

# If I put the patch here, that works but it makes a duplicate...
# patches:
#   - path: ../patches/patch.yaml
#     target:
#       group: rbac.authorization.k8s.io
#       version: v1
#       kind: ClusterRole
#       name: my-app-cluster-role

components:
  - ../patches
```

the patch.yaml file
```yaml
- op: replace
  path: /rules
  value: 
    - apiGroups:
        - ""
      resources:
        - pods
        - pods/log
        - endpoints
        - persistentvolumeclaims
        - resourcequotas
        - nodes
        - events
        - namespaces
        - services
        - configmaps
        - replicationcontrollers
      verbs:
        - get
        - watch
        - list
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - get
    - apiGroups:
        - apps
      resources:
        - daemonsets
        - statefulsets
        - deployments
        - replicasets
      verbs:
        - get
        - watch
        - list
    - apiGroups:
        - "batch"
        - "extensions"
      resources:
        - "jobs"
      verbs:
        - "get"
        - "list"
        - "watch"
    - apiGroups:
        - metrics.k8s.io
      resources:
        - pods
        - nodes
      verbs:
        - get
        - list
        - watch
```
And the command I run:
```sh
kustomize build --load-restrictor LoadRestrictionsNone --enable-helm unit-tests > tests/manifest.yaml
```

### Expected output

Notice the secrets definition in a standalone group

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-app-cluster-role
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
    - endpoints
    - persistentvolumeclaims
    - resourcequotas
    - nodes
    - events
    - namespaces
    - services
    - configmaps
    - replicationcontrollers
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
- apiGroups:
    - apps
  resources:
    - daemonsets
    - statefulsets
    - deployments
    - replicasets
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - "batch"
    - "extensions"
  resources:
    - "jobs"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - metrics.k8s.io
  resources:
    - pods
    - nodes
  verbs:
    - get
    - list
    - watch
---
apiVersion: v1
data:
  shim_normal.js: "Hello world"
kind: ConfigMap
metadata:
  name: custom-configmap-nodejs
---
apiVersion: v1
data:
  shim_noreuse.js: "Hello world"
kind: ConfigMap
metadata:
  name: custom-configmap-nodejs-noreuse
```

### Actual output

I get the ClusterRole as it was after the helm rendering (without applying the patch)
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-app-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - endpoints
  - persistentvolumeclaims
  - resourcequotas
  - nodes
  - events
  - namespaces
  - services
  - configmaps
  - secrets
  - replicationcontrollers
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  - deployments
  - replicasets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
data:
  shim_normal.js: "Hello world"
kind: ConfigMap
metadata:
  name: custom-configmap-nodejs
---
apiVersion: v1
data:
  shim_noreuse.js: "Hello world"
kind: ConfigMap
metadata:
  name: custom-configmap-nodejs-noreuse
```

### Kustomize version

4.5.5

### Operating system

Linux

**Comment by annasong20** [comment]
Hi @ThibaultDelaune-pro, you are seeing intended behavior. 

The `patches` in `Component` is not applied to the helm rendering because of the order that `kustomize` processes its fields. Because `kustomize` processes `components` before `generators`, `kustomize` does not have any resources to apply the `patches` to. `kustomize` still generates the `ConfigMap`s, as generators, in this case `configMapGenerator`, produce resources independent of existing resources.

With my limited experience structuring kustomization layers and a very basic understanding of your use case, I offer the following workarounds
* Keep your helm `generators`, `configMapGenerator`, and `patches` together in the same `kustomization.yaml`. I might be misunderstanding your use case, but could you `build` this kustomization for your unit tests?
* If you want to use `components`, move the helm `generators` into its own `helm/kustomization.yaml`, preserve the existing `patches/kustomization.yaml`, and replace
  ```
  generators:
    - chart-inflation-generator.yaml
   ```
  with
  ```
  resources:
    - helm
   ```
  in `unit-tests/kustomization.yaml` and every kustomization that uses the `Component`. You can do this because `kustomize` processes `resources` before `components`.

Maybe @KnVerey can offer a better suggestion. `kustomize` may also document this behavior better.

**Comment by ThibaultDelaune-pro** [comment]
I can't put the generator and the patches in the same kustomize (because the CD tool I use deploy the editor helm chart directly) but I tried your 2nd suggestion and it worked! :+1: 

So it looks like this now:
```
├── patches
│   └── kustomization.yaml (my component)
│       patch.yaml
└── unit-tests
    ├── helm
    |   └── kustomization.yaml
    |       chart-inflation-generator.yaml
    └── kustomization.yaml
```
with my unit-tests kustomization.yaml:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm
components:
  - ../patches
```

Thanks for your help @annasong20
