### ISSUE TITLE
configMapGenerator produce single file instead of multiple k:v's

### ISSUE THREAD

**Issue by TheDarkFlame** [kubernetes-sigs/kustomize#5028]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Consider the following:
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
...
configMapGenerator:
  - name: flink-conf.properties
    literals:
    - parallelism.default=1
    - taskmanager.numberOfTaskSlots=1
```

The result is the following:
```yaml
apiVersion: v1
data:
  parallelism.default: "1"
  taskmanager.numberOfTaskSlots: "1"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"parallelism.default":"1","taskmanager.numberOfTaskSlots":"1"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"flink-conf.properties-7c5fd57d5m","namespace":"<redacted>"}}
  creationTimestamp: "2023-02-03T10:26:22Z"
  name: flink-conf.properties-7c5fd57d5m
```

The result is that when mounting as a volume, you get the following files and their contents:
>`/path/to/mount/parallelism.default`
>```properties
>1
>```
>`/path/to/mount/taskmanager.numberOfTaskSlots`
>```properties
>1
>```

instead it would be desirable to create a way to have a single file as follows:
>`/path/to/mount/flink-config.properties`
>```properties
>parallelism.default=1
>taskmanager.numberOfTaskSlots=1
>```

### Why is this needed?

for producing .properties files that can be mounted as volumes directly in the configMapGenerator

### Can you accomplish the motivating task without this feature, and if so, how?

By using traditional ConfigMaps instead of using a configMapGenerator

### What other solutions have you considered?

I have also tried something like the following yamls:
defining the same file multiple times to add lines
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flink.yaml
configMapGenerator:
  - name: flink-conf.properties
    literals:
      - flink-conf.properties=
          parallelism.default=1
      - flink-conf.properties=
          taskmanager.numberOfTaskSlots=1
```

fails because formatting isn't what is expected: `cannot unmarshal object into Go struct field ConfigMapArgs.configMapGenerator.literals of type string`
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flink.yaml
configMapGenerator:
  - name: flink-conf.properties
    literals:
      - flink-conf.properties: |
          parallelism.default=1
          taskmanager.numberOfTaskSlots=1
```

the below works, but puts everything on a single line, which is almost what we want. Unfortunately, the line breaks are not recognised, even with a \n 
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flink.yaml
configMapGenerator:
  - name: flink-conf.properties
    literals:
      - flink-conf.properties=
        parallelism.default=1
        taskmanager.numberOfTaskSlots=1
```

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉
