### ISSUE TITLE
Replacement feature replaces partially matched targets

### ISSUE THREAD

**Issue by amold1** [kubernetes-sigs/kustomize#5029]
### What happened?

The replacement feature replaces partially matched targets along with the intended specific target.

### What did you expect to happen?

For a given configMap, StatefulSet and replacement like in the section below, I expect only the value of the target env var(SAMPLE_TARGET) to be replaced with __SAMPLE_VALUE__. But kustomize will replacement that target and any other partially matched env var.

#### ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  name: my-cm
data:
  __SAMPLE_KEY__  : __SAMPLE_VALUE__
```

#### Replacement
```
source:
  kind: ConfigMap
  name: my-cm
  fieldPath: data.__SAMPLE_KEY__
targets:
  - select:
      name: my-statefulset
      kind: StatefulSet
    fieldPaths:
    - spec.template.spec.containers.[name=my-container].env.[name=SAMPLE_TARGET].value
```

StatefulSet(env field)
```yaml
        env:
        - name: SAMPLE_TARGET
          value: _PLACEHOLDER_
        - name: SAMPLE_TARGET_2
          value: _PLACEHOLDER_
        - name: SOME_OTHER_ENV_VAR
          value: _PLACEHOLDER_
```

### Expected output

```yaml
        env:
        - name: SAMPLE_TARGET
          value: __SAMPLE_VALUE__
        - name: SAMPLE_TARGET_2
          value: _PLACEHOLDER_
        - name: SOME_OTHER_ENV_VAR
          value: _PLACEHOLDER_
```

### Actual output

```yaml
        env:
        - name: SAMPLE_TARGET
          value: __SAMPLE_VALUE__
        - name: SAMPLE_TARGET_2
          value: __SAMPLE_VALUE__
        - name: SOME_OTHER_ENV_VAR
          value: _PLACEHOLDER_
```

### Kustomize version

v4.5.7

### Operating system

None
