### ISSUE TITLE
Error: loading generator plugins: failed to load generator: HelmChartInflationGenerator

### ISSUE THREAD

**Issue by joesan** [kubernetes-sigs/kustomize#5035]
### What happened?

I have the following chartInflator.yml file:

```
    apiVersion: builtin
    kind: ChartInflator
    metadata:
      name: project-helm-inflator
    chartName: helm-k8s
    chartHome: ../../../helm-k8s/
    releaseName: project-monitoring-chart
    values: ../../values.yaml
    releaseNamespace: project-monitoring-ns
```

When I ran it using this, I got the error message below:

```
    $ kustomize build .
    Error: loading generator plugins: failed to load generator: plugin HelmChartInflationGenerator.builtin.[noGrp]/project-helm-inflator.[noNs] fails configuration: chart name cannot be empty
```

Here is my project structure:

   ```
 project
      - helm-k8s
       - values.yml
       - Chart.yml
       - templates
        - base
          - project-namespace.yml
          - grafana
            - grafana-service.yml
            - grafana-deployment.yml
            - grafana-datasource-config.yml
          - prometheus
            - prometheus-service.yml
            - prometheus-deployment.yml
            - prometheus-config.yml
            - prometheus-roles.yml
          - kustomization.yml
        - prod
          - kustomization.yml
        - test
          - kustomization.yml
```

### What did you expect to happen?

I expected that the kustomize was able to build the manifests with injecting the values from the values.yml. I have the plugin installed in my local machine and added it to the PATH in my bash_profile like this:

```
# export path for kubernetes kustomize plugins
export KUSTOMIZE_ENABLE_PLUGINS=true
export KUSTOMIZE_PLUGIN_HOME=$HOME/.config/kustomize/plugin/kustomize.config.k8s.io/v1/chartinflator/
```

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: project-monitoring-kustomization
generators:
  - chartInflator.yml
resources:
  # 0. Get the namespaces first
  - project-monitoring-namespace.yml

  # 1. Set up monitoring services (prometheus)
  #- monitoring/prometheus/prometheus-roles.yml
  - prometheus/prometheus-config.yml
  - prometheus/prometheus-roles.yml
  - prometheus/prometheus-deployment.yml
  - prometheus/prometheus-service.yml

  # 2. Set up monitoring services (grafana)
  - grafana/grafana-datasource-config.yml
  - grafana/grafana-deployment.yml
  - grafana/grafana-service.yml
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v5.0.0

### Operating system

Linux
