### ISSUE TITLE
Order of `transformers` is not respected

### ISSUE THREAD

**Issue by akamac** [kubernetes-sigs/kustomize#5037]
### What happened?

I have the following `kustomization`, calling my custom plugin and applying strategic merge patch:
```
transformers:
  - |
    apiVersion: joom.com/v1alpha1
    kind: PrometheusRulePatch
    metadata:
      name: prometheus-rule-patch
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: ./plugins/prometheus_rule_patch.sh
  - |
    apiVersion: builtin
    kind: PatchTransformer
    metadata:
      name: notImportantHere
    path: patches/kubernetes_app.yaml
```
Both modifying the same field and I want the patch to override the value set by the plugin. That's why I call patch transformer via `transformers` instead of `patches:` - to specify the order.

Value in the patch is overridden by the value set by the plugin. That makes me feel the plugin is called *after* the patch, even though the order in the list is the opposite. 

### Kustomize version

4.5.7

### Operating system

MacOS
