### ISSUE TITLE
Well-defined vars never replaced changed output stream in 5.0.0

### ISSUE THREAD

**Issue by mcclellanmj** [kubernetes-sigs/kustomize#5039]
### What happened?

My project had a warning about well-defined vars never replaced.  In 5.0.0 it appears that the stream which was used to write out that error changed from stderr to stdout.  I was redirecting my output to a yaml file to be used later and this changed causes malformed yaml.

The error message looks like so
```2023/02/08 08:28:59 well-defined vars that were never replaced: MY_PROJECT/ENV```

### What did you expect to happen?

Same behavior as 4.5.7 where the warning was written out to stderr.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

5.0.0

### Operating system

Linux

**Comment by cailynse** [comment]
I was able to reproduce this issue with the following setup:
```
# file: kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
namePrefix: sample-
vars:
  - name: SERVICE_ONE
    objref:
      kind: Service
      name: backendOne
      apiVersion: v1
  - name: SERVICE_UNUSED
    objref:
      kind: Service
      name: backendTwo
      apiVersion: v1
```

I've identified the issue and will get a fix up soon.

```
# file: resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
  what: how
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec: 
  template:
    spec:
      containers:
        command:
        - myserver
        - --somebackendService $(SERVICE_ONE)
---
apiVersion: v1
kind: Service
name: SERVICE_ONE
metadata:
  name: backendOne
---
apiVersion: v1
kind: Service
name: SERVICE_UNUSED
metadata:
  name: backendTwo
  ```
