### ISSUE TITLE
kustomize edit fix needs to split multi-doc SMP patches into multiple files

### ISSUE THREAD

**Issue by IvanovOleg** [kubernetes-sigs/kustomize#5040]
### What happened?

I've tried my existing kustomize manifests with kustomize 5.0.0 and found a problem. I applied kustomize edit fix, but kustomize build command returns error: 
```
Error: trouble configuring builtin PatchTransformer with config: `
path: secret.patch.yaml
`: unable to parse SM or JSON patch from [
manifest content
]
```

### What did you expect to happen?

Kustomize build returns:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  admin.password: newpassword

---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
stringData:
  admin.user: newuser
```

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
resources:
  - secret.yaml

patches:
  - path: secret.patch.yaml
```

```yaml
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  admin.password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
stringData:
  admin.user: user
```
```yaml
# secret.patch.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  admin.password: newpassword

---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
stringData:
  admin.user: newuser
```

### Expected output

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  admin.password: newpassword

---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
stringData:
  admin.user: newuser
```

### Actual output

```yaml
Error: trouble configuring builtin PatchTransformer with config: `
path: secret.patch.yaml
`: unable to parse SM or JSON patch from [apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  admin.password: newpassword

---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
type: Opaque
stringData:
  admin.user: newuser
]
```

### Kustomize version

5.0.0

### Operating system

Linux

**Comment by iamnoah** [comment]
Also hit by this. Only workaround I have found is to explicitly specify patch targets in kustomization.yaml, but that a ton of refactoring for patches targeting multiple resources by name.

**Comment by KnVerey** [comment]
/retitle kustomize edit fix needs to split multi-doc SMP patches into multiple files
/triage accepted

The problem here is that `kustomize edit fix` is not correctly transforming the Kustomization--for older style patch file that contain multiple documents, we need to split them into separate files and list those files in the 'fixed' kustomization.

/assign @brianpursley

**Comment by iamnoah** [comment]
IMO, splitting into multiple files is worse, even if they are kept in a subdirectory. I have to create multiple patch lines, I have to open multiple files when changes are correlated, etc. Nothing about this is an improvement over the existing behavior of patchStrategicMerge.

It does not seem terribly difficult to transform an existing SM patch, so why can't we keep the functionality? What if it was something like:

```yaml
patches:
- path: my-multi-sm-patch.yaml
  target: { byGVKN: true }
```

**Comment by KnVerey** [comment]
That's an interesting idea; please open a separate issue for the feature request. One thing to address is the fact that the patch file could contain a JSON patch, which does not include GVKNN information.

**Comment by lindhe** [comment]
I'm having a very similar problem with an even more minimal example. Do you think it's the same bug?

I'm running `kustomize` v5.1.0.

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cm.yaml

patches:
- patch: cm.patch.yaml
```

```yaml
# cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
```

```yaml
# cm.patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  foo: bar
```

```console
$ kustomize build .
Error: trouble configuring builtin PatchTransformer with config: `
patch: cm.patch.yaml
`: unable to parse SM or JSON patch from [cm.patch.yaml]
```

It works fine if I change the `kustomization.yaml` to the following:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cm.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cm
    data:
      foo: bar
```
