### ISSUE TITLE
Custom Resources with a Kind Ending in "List" are Silently Ignored

### ISSUE THREAD

**Issue by GuyPaddock** [kubernetes-sigs/kustomize#5042]
### What happened?

If you include a custom resource in an overlay, and the `Kind` of the custom resource ends with the word `List`, it will be ignored from the output when running `kustomize build`. This behavior is undocumented and unexpected.

### What did you expect to happen?

Custom resources should not be ignored based on the suffix of their `Kind`.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml - Based on https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md.
apiVersion: example.com/v1alpha1
kind: MyResource
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: server
          image: server
          command: example
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 8080
---
apiVersion: example.com/v1alpha1
kind: MyResourceList
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: server
          image: server
          command: example
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 8080
```

### Expected output

```yaml
apiVersion: example.com/v1alpha1
kind: MyResource
metadata:
  name: service
  namespace: cloud-shell-dev
spec:
  template:
    spec:
      containers:
      - command: example
        image: server
        name: server
        ports:
        - containerPort: 8080
          name: grpc
          protocol: TCP
---
apiVersion: example.com/v1alpha1
kind: MyResourceList
metadata:
  name: service
  namespace: cloud-shell-dev
spec:
  template:
    spec:
      containers:
      - command: example
        image: server
        name: server
        ports:
        - containerPort: 8080
          name: grpc
          protocol: TCP
```

### Actual output

```yaml
apiVersion: example.com/v1alpha1
kind: MyResource
metadata:
  name: service
  namespace: cloud-shell-dev
spec:
  template:
    spec:
      containers:
      - command: example
        image: server
        name: server
        ports:
        - containerPort: 8080
          name: grpc
          protocol: TCP
```

### Kustomize version

5.0.0

### Operating system

Linux
