### ISSUE TITLE
Make It Possible for "delimiter" in "replacements.target.options" to Join Array Values by a Delimiter into a Scalar

### ISSUE THREAD

**Issue by GuyPaddock** [kubernetes-sigs/kustomize#5043]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Given the following custom-resource Yaml:
```yaml
# allowed-ingress.yaml
apiVersion: k8s.inveniem.com/v1
kind: CidrAddresses
metadata:
  name: allowed-ingress
data:
  addresses:
    - "8.67.53.09/32"
    - "192.168.0.1/32"
```
... I'd like a way to join all of the values under `data.addresses` into a comma-delimited string (e.g., for use in an `nginx.ingress.kubernetes.io/whitelist-source-range` annotation) using a replacement, like this:
```
"8.67.53.09/32,192.168.0.1/32"
```

For example:
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allowed-ingress.yaml

replacements:
  - source:
      kind: CidrAddresses
      name: allowed-ingress
      fieldPath: data.addresses
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/whitelist-source-range]
        options:
          create: true
          # Note the delimiter option below: 
          delimiter: ','

  - source:
      kind: CidrAddresses
      name: allowed-ingress
      fieldPath: data.addresses
    targets:
      - select:
          kind: Service
        fieldPaths:
          - spec.loadBalancerSourceRanges
        options:
          create: true
```

### Why is this needed?

* Some resources need to take in an array of values as a comma-delimited string (e.g., `nginx.ingress.kubernetes.io/whitelist-source-range`), while others require it as an array (`spec.loadBalancerSourceRanges` in services). By providing a way to join these values by a delimiter, both can be provided with values sourced from the same source data.
* If you try to use a delimiter with an array, you will currently get the error message: `delimiter option can only be used with scalar nodes`
* There is already support in Kustomize for splitting a scalar string value by a comma and then selecting a specific value by `index`, so there is precedent for this feature.

### Can you accomplish the motivating task without this feature, and if so, how?

```yaml
# allowed-ingress.yaml
apiVersion: k8s.inveniem.com/v1
kind: CidrAddresses
metadata:
  name: allowed-ingress
data:
  addressesString: "8.67.53.09/32,192.168.0.1/32"
  addressesArray:
    - "8.67.53.09/32"
    - "192.168.0.1/32"
```
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allowed-ingress.yaml

replacements:
  - source:
      kind: CidrAddresses
      name: allowed-ingress
      fieldPath: data.addressesString
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/whitelist-source-range]
        options:
          create: true

  - source:
      kind: CidrAddresses
      name: allowed-ingress
      fieldPath: data.addressesArray
    targets:
      - select:
          kind: Service
        fieldPaths:
          - spec.loadBalancerSourceRanges
        options:
          create: true
```

### What other solutions have you considered?

* Writing a custom transformer for this.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by KnVerey** [comment]
/triage under-consideration

I think this sounds reasonable, but I'd like to get @natasha41575 opinion on it.

**Comment by jskrzypek** [comment]
A coupld thoughts:

1) As a parallel, it might be useful/elegant to similarly respect a `source.options.delimiter` when no `source.options.index` is specified to split a source scalar and then pass it to targets as a slice.

2) A potentially thorny edge-case occurred to me: what do you do when the source array is not an array of scalars or is a mix of scalars and non-scalars?
E.g. what happens if your source finds this:
```
- hello
- world
- key1: val1
  key2: val2
- - itemA
  - itemB
```
A potential solution could be introducing another option (perhaps `coerce`?) to coerce the source into a scalar if the target is a scalar, which would also make it possible to join multiple snippets to build up a scalar file when using a `'\n'` delimiter

**Comment by buddyledungarees** [comment]
Another use case for a coerce (to string) option would be if the duck typing of the reference field mistakenly treats it as a number:

```
replacements:
  - source:
      kind: Deployment
      fieldPath: spec.template.spec.containers.[name=mycontainer].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.labels.version
          - spec.template.metadata.labels.version
        options:
          create: true
```

This causes errors with k8s if the tag convention happens to be `X.Y` and due to certain metadata fields expected to be map[string]string.
