### ISSUE TITLE
Name in a configMapRef is not updated to include the hash as a suffix (nor a prefix)

### ISSUE THREAD

**Issue by jonathanlking** [kubernetes-sigs/kustomize#5047]
### What happened?

While upgrading from an older version kustomize I discovered a breaking change in output between v3.9.2 and v3.9.3, where a `configMapRef` is no longer valid.

~While this behaviour appeared in v3.9.3, it can be reverted by applying the `--enable_kyaml=false` flag and from looking at the release notes for [v3.9.3](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.9.3) I believe the difference is actually due to the switch to the `kyaml` library.~ (I was wrong about this!)

I think it’s different to other GitHub issues I’ve found (e.g. #1301 or #2609) as I can still replicate this on v5.0.0.

### What did you expect to happen?

A hash and suffix to still be included in the `configMapRef`, i.e. `a-example-configmap-6ct58987ht` rather than `-example-configmap`.

Interestingly building `a` or `b` independently (or removing either `- a` or `- b` from the `kustomization.yaml`) still gives the expected behaviour. It's only when there are multiple resources that this unexpected behaviour occurs.

Perhaps I was previously relying on undefined/buggy behaviour?

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
resources:
- a
- b
```

```yaml
# a/kustomization.yaml
resources:
- ../common

namePrefix: a
```

```yaml
# b/kustomization.yaml
resources:
- ../common

namePrefix: b
```

```yaml
# common/kustomization.yaml
resources:
- service

configMapGenerator:
- name: "-example-configmap"
```

```yaml
# common/service/deployment.yaml
kind: Deployment
apiVersion: apps/v1

metadata:
  name: "-"

spec:
  template:
    spec:
      containers:
      - name: app
        envFrom:
        - configMapRef:
            name: "-example-configmap"
```

```yaml
# common/service/kustomization.yaml
resources:
- deployment.yaml

nameSuffix: api
```

I also have a copy of these files here https://github.com/jonathanlking/kustomize-example.

### Expected output

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-example-configmap-6ct58987ht
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b-example-configmap-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-api
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: a-example-configmap-6ct58987ht
        name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-api
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: b-example-configmap-6ct58987ht
        name: app
```

### Actual output

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-example-configmap-6ct58987ht
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b-example-configmap-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-api
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: -example-configmap
        name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-api
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: -example-configmap
        name: app
```

### Kustomize version

v3.9.3 onwards (including v5.0.0)

### Operating system

Linux

**Comment by jonathanlking** [comment]
@Serializator thank you for looking into this! 🙏 

If I understand correctly, you're saying that I can remove:

```
patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: "-example-configmap"
```

With that change, I then get the same output for both versions: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-example-configmap-6ct58987ht
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b-example-configmap-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-api
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: '-'
        name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-api
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: '-'
        name: app
```

So I think the patch is required to demonstrate the change in behaviour described in the issue?
I definitely might have misunderstood your point though!

**Comment by jonathanlking** [comment]
@Serializator Ah, yes I did misunderstand! 🤦‍♂️ 

You're saying that the patch could be replace and instead the deployment could be changed to:

```
kind: Deployment
apiVersion: apps/v1

metadata:
  name: "-"

spec:
  template:
    spec:
      containers:
      - name: app
        envFrom:
        - configMapRef:
            name: "-"
        - configMapRef:
            name: "-example-configmap"
```

I agree, you're right, the patch included does not affect the outcome.
Apologies for this, I'm not sure how I missed it, I will update the example.

**Comment by Serializator** [comment]
Though this is not yet conclusive, I was able to pinpoint the PR in which the regression was introduced.
**Pull Request:** https://github.com/kubernetes-sigs/kustomize/pull/3529

_Gotta ❤️ Git with its bisect command!_

I will go through the changes in this PR and try to identify which specific change is causing this behaviour.

**Comment by natasha41575** [comment]
/triage accepted

I can reproduce the regression between v3.9.2 and v3.9.3, though enabling/disabling the `--enable_kyaml` flag doesn't appear to make a difference for me when using v3.9.3.

**Comment by jonathanlking** [comment]
@natasha41575 Apologies (for the second time today!), you're right about the `--enable_kyaml` flag, I've just tried again and it doesn't appear to make a difference for me.

I'm not sure why I originally thought it did 🤔

**Comment by Serializator** [comment]
Appendix 1. below is taken from `(resource.Resource).PrefixesSuffixesEquals`, this function checks if the prefixes and suffixes of the are equal of the resource itself and provided `resource.ResCtx`.

In the original code (before the change from #3529) `utils.SameEndingSubSlice` would return true in case if one of the two slices were empty. Take a look at the first comparison in the appendix.

Right now this results in `false`, though with the previous logic (see appendix 2.) it would result in `true` as at least the prefixes are the same, basically an or logic.

What my suggestion would be to bring this or logic into `(resource.Resource).PrefixesSuffixesEquals` as current it does an and check on the prefixes and suffixes. Changing this to an or would retain the original logic before the PR whilst retaining what the other changes from the PR.

@natasha41575, what do you think of this suggestion?

**Appendix 1.**
```log
Resource Name Prefixes: [a]
Object Name Prefixes: [a]

Resource Name Suffixes: []
Object Name Suffixes: [api]

Result: false
--------
Resource Name Prefixes: [b]
Object Name Prefixes: [a]

Resource Name Suffixes: []
Object Name Suffixes: [api]

Result: false
--------
Resource Name Prefixes: [a]
Object Name Prefixes: [b]

Resource Name Suffixes: []
Object Name Suffixes: [api]

Result: false
--------
Resource Name Prefixes: [b]
Object Name Prefixes: [b]

Resource Name Suffixes: []
Object Name Suffixes: [api]

Result: false
```

**Appendix 2.**
```go
func SameEndingSubarray(shortest, longest []string) bool {
	if len(shortest) > len(longest) {
		longest, shortest = shortest, longest
	}
	diff := len(longest) - len(shortest)
	if len(shortest) == 0 {
		return diff == 0
	}
	for i := len(shortest) - 1; i >= 0; i-- {
		if longest[i+diff] != shortest[i] {
			return false
		}
	}
	return true
}
```

**Comment by jsitu777** [comment]
I'm facing the same issue even in kustomize v5.0.1

**Comment by jonathanlking** [comment]
@Serializator thanks again for your investigation! I've had a go at trying what I _believe_ you suggested:

```patch
diff --git i/api/resource/resource.go w/api/resource/resource.go
index 53a62dffd..3585593d3 100644
--- i/api/resource/resource.go
+++ w/api/resource/resource.go
@@ -321,7 +321,7 @@ func (r *Resource) getCsvAnnotation(name string) []string {
 // as OutermostPrefixSuffix but performs a deeper comparison
 // of the suffix and prefix slices.
 func (r *Resource) PrefixesSuffixesEquals(o ResCtx) bool {
-	return SameEndingSubarray(r.GetNamePrefixes(), o.GetNamePrefixes()) && SameEndingSubarray(r.GetNameSuffixes(), o.GetNameSuffixes())
+	return SameEndingSubarray(r.GetNamePrefixes(), o.GetNamePrefixes()) || SameEndingSubarray(r.GetNameSuffixes(), o.GetNameSuffixes())
 }
 
 // RemoveBuildAnnotations removes annotations created by the build process.
 ````

This does seem to fix the issue reported! 🎉 
However I think it introduces a new issue; a minimal example of this is:
                                      
```yaml
# kustomization.yaml
resources:
- a
- b
```

```yaml
# a/kustomization.yaml
resources:
- ../common

namePrefix: a
```

```yaml
# b/kustomization.yaml
resources:
- ../common

namePrefix: b
```

```yaml
# common/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "-example"
spec:
  template:
    spec:
      containers:
      - name: app
        envFrom:
        - configMapRef:
            name: "-example-configmap"
```

```yaml
# common/kustomization.yaml
resources:
- deployment.yaml

configMapGenerator:
- name: "-example-configmap"
```

Prior to this change we get (tested on v3.9.3-4.5.7):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-example-configmap-6ct58987ht
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b-example-configmap-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-example
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: a-example-configmap-6ct58987ht
        name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-example
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: b-example-configmap-6ct58987ht
        name: app
```

However after the change we now get:

```yaml
**** Too many possible referral targets to referrer:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.kubernetes.io/prefixes: a
    config.kubernetes.io/previousNames: -example
    config.kubernetes.io/previousNamespaces: default
  name: a-example
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: -example-configmap
        name: app

--- possible referral 0:
apiVersion: v1
kind: ConfigMap                    
metadata:
  annotations:
    config.kubernetes.io/prefixes: a
    config.kubernetes.io/previousNames: -example-configmap,a-example-configmap
    config.kubernetes.io/previousNamespaces: default,default
  name: a-example-configmap-6ct58987ht
------
--- possible referral 1:
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:                     
    config.kubernetes.io/prefixes: b
    config.kubernetes.io/previousNames: -example-configmap,b-example-configmap
    config.kubernetes.io/previousNamespaces: default,default
  name: b-example-configmap-6ct58987ht
------
Error: updating name reference in 'spec/template/spec/containers/envFrom/configMapRef/name' field of 'apps_v1_Deployment|~X|a-example': considering field 'spec/template/spec/containers/envFrom/configMapRef/name' of object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "a-example"                
  annotations:
    config.kubernetes.io/prefixes: a
    config.kubernetes.io/previousNames: -example
    config.kubernetes.io/previousNamespaces: default
spec:                              
  template:                        
    spec:                          
      containers:                  
      - name: app                  
        envFrom:
        - configMapRef:
            name: "-example-configmap"
: visit traversal on path: [envFrom configMapRef name]: visit traversal on path: [configMapRef name]:  found multiple possible referrals: ~G_v1_ConfigMap|~X|a-example-configmap-6ct58987ht, ~G_v1_ConfigMap|~X|b-example-configmap-6ct58987ht
```

I've added this new [example](https://github.com/jonathanlking/kustomize-example/tree/main/patched-example) and also the [patched version of `kustomize`](https://github.com/jonathanlking/kustomize-example/blob/main/default.nix#L32) to my example repository.

Any ideas/suggestions would be greatly appreciated! (and please say if I've misunderstood something/made a silly error again 😅)

**Comment by jonathanlking** [comment]
I re-read your comment and I _think_ this patch might work (it still fixes the original issue, but doesn't introduce the new one):

```patch
diff --git i/api/resource/resource.go w/api/resource/resource.go
index 53a62dffd..3d471e6d9 100644
--- i/api/resource/resource.go
+++ w/api/resource/resource.go
@@ -320,8 +320,8 @@ func (r *Resource) getCsvAnnotation(name string) []string {
 // PrefixesSuffixesEquals is conceptually doing the same task
 // as OutermostPrefixSuffix but performs a deeper comparison
 // of the suffix and prefix slices.
-func (r *Resource) PrefixesSuffixesEquals(o ResCtx) bool {
-	return SameEndingSubarray(r.GetNamePrefixes(), o.GetNamePrefixes()) && SameEndingSubarray(r.GetNameSuffixes(), o.GetNameSuffixes())
+func(r * Resource) PrefixesSuffixesEquals(o ResCtx) bool {
+    return (len(r.GetNamePrefixes()) == 0 || len(o.GetNamePrefixes()) == 0 || SameEndingSubarray(r.GetNamePrefixes(), o.GetNamePrefixes())) && (len(r.GetNameSuffixes()) == 0 || len(o.GetNameSuffixes()) == 0 || SameEndingSubarray(r.GetNameSuffixes(), o.GetNameSuffixes()))
 }
 
 // RemoveBuildAnnotations removes annotations created by the build process.
 ```

If either of the prefixes/suffixes are empty then it treats that prefix/suffix as equal, which is what the previous behaviour was (I think?).

**Comment by jonathanlking** [comment]
While trying to implement a fix, I think I’m getting a better understanding of the problem.
For the example I shared, in `selectReferral`, the value of `candidates` _before_ `doSieve(candidates, prefixSuffixEquals(f.Referrer)`  is
https://github.com/kubernetes-sigs/kustomize/blob/da4e8810079e2a98a3f4caad83618c53014d703b/api/filters/nameref/nameref.go#L328

```json
[
  {
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "metadata": {
      "annotations": {
        "internal.config.kubernetes.io/generatorBehavior": "unspecified",
        "internal.config.kubernetes.io/needsHashSuffix": "enabled",
        "internal.config.kubernetes.io/prefixes": "a",
        "internal.config.kubernetes.io/previousKinds": "ConfigMap,ConfigMap",
        "internal.config.kubernetes.io/previousNames": "-example-configmap,a-example-configmap",
        "internal.config.kubernetes.io/previousNamespaces": "default,default"
      },
      "name": "a-example-configmap-6ct58987ht"
    }
  },
  {
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "metadata": {
      "annotations": {
        "internal.config.kubernetes.io/generatorBehavior": "unspecified",
        "internal.config.kubernetes.io/needsHashSuffix": "enabled",
        "internal.config.kubernetes.io/prefixes": "b",
        "internal.config.kubernetes.io/previousKinds": "ConfigMap,ConfigMap",
        "internal.config.kubernetes.io/previousNames": "-example-configmap,b-example-configmap",
        "internal.config.kubernetes.io/previousNamespaces": "default,default"
      },
      "name": "b-example-configmap-6ct58987ht"
    }
  }
]
```

and the resource is:

```json
{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "annotations": {
      "internal.config.kubernetes.io/prefixes": "b",
      "internal.config.kubernetes.io/previousKinds": "Deployment,Deployment",
      "internal.config.kubernetes.io/previousNames": "-,-api",
      "internal.config.kubernetes.io/previousNamespaces": "default,default",
      "internal.config.kubernetes.io/suffixes": "api"
    },
    "name": "b-api"
  },
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "envFrom": [
              {
                "configMapRef": {
                  "name": "-example-configmap"
                }
              }
            ],
            "name": "app"
          }
        ]
      }
    }
  }
}
```

The second candidate is what _I would like_ to get picked, however while it has the prefix `"b"`, it doesn't have a suffix and therefore is filtered away.
Before https://github.com/kubernetes-sigs/kustomize/pull/3529 this didn't matter
> For some time, SameEndingSubarray (formerly private, with no unit test) was treating an empty array and a one entry array as having the same "ending subarray"

as this is exactly that scenario.

**Comment by jonathanlking** [comment]
If we change the logic to “OR” as @Serializator suggested, we run into the same issue that #3529 was trying to fix, which is that we're left with more than one candidate in some scenarios (which is caught by some existing unit tests, e.g. `TestReusableCustomTransformers`).

If we break the `prefixSuffixEquals` filter step into more granular steps, where you progressively get more aggressive in filtering while there is more than one candidate, I think this could solve the problem.

I think there are a few different heuristics you could use, e.g. _initially_
* Allow _either_ (inclusive) a prefix or suffix to match (like what @Serializator suggested)
* Treat an empty prefix/suffix as having the same `SameEndingSubarray` as a one element prefix/suffix (the behaviour before #3529)
* Treat an empty prefix/suffix as having the same `SameEndingSubarray` as _any_ prefix/suffix (what I have on https://github.com/kubernetes-sigs/kustomize/pull/5236)

This approach does feel a bit hacky to me, however if we’re only searching for the _best_, rather than an _exact_ match (which I get the impression we are) I'm more comfortable. My branch in https://github.com/kubernetes-sigs/kustomize/pull/5236 does seem to pass the `krusty` unit tests, which is promising.

I'd really appreciate feedback on whether this approach makes sense/if you think I've misunderstood the problem/have any other suggestions! 🙏

**Comment by BishuSinha** [comment]
Any fix on v5.1.1, still facing the issue

**Comment by jonathanlking** [comment]
@BishuSinha I'm waiting for feedback on whether my suggested approach makes sense/would be accepted. We've been using a patched version of Kustomize at work (based on #5236) and not had any issues, which is promising.

**Comment by BishuSinha** [comment]
> @BishuSinha I'm waiting for feedback on whether my suggested approach makes sense/would be accepted. We've been using a patched version of Kustomize at work (based on #5236) and not had any issues, which is promising.

Thanks mate , will use the patch for now , cheers

**Comment by safizn** [comment]
The same issue appears when using a **namespace** in the base `kustomization.yml`. I don't think it is intentional. 

### Issue
ConfigMap hash generated metadata.name doesn't match Deployment spec.template.spec.containers.envFrom.configMapRef.name; when base kustomization specifies a namespace.

### Reproduce
Files at: https://gist.github.com/safizn/a37f399fb2706cf8d73331f42b840ddf

```
# base/deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template: 
    spec: 
      containers:
        - name: container
          envFrom: 
          - configMapRef:
              name: configuration
```

```
# base/kustomization.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- deployment.yml
namespace: A
```

```
# overlay/kustomization.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ../base
namePrefix: dev- 
configMapGenerator:
- name: configuration
```

### Expected result
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-configuration-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: A
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: dev-configuration-6ct58987ht
        name: container
```

### Actual result
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-configuration-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: A
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: configuration
        name: container
```

### Difference

```
$ diff with_namespace.txt without_namespace.txt 
10d9
<   namespace: A
17c16
<             name: configuration
---
>             name: dev-configuration-6ct58987ht
```
