### ISSUE TITLE
inconsistency on service account name prefix

### ISSUE THREAD

**Issue by SongGithub** [kubernetes-sigs/kustomize#505]
my goal is to declare a service account `banana` to use in deployment, and create a service account named `banana`. 

however, when use kustomize's overlay `foo`, it prefixes foo only to name in the service account object, then I have a service account named `foo-banana`

the problem is that the serviceAccount flag in deployment is not prefixed, which is still `banana`.  

The mismatch will cause errors such as `service account: banana` not exist.

**Comment by Liujingfang1** [comment]
@SongGithub Can you give more description of `serviceAccount flag in deployment 1`? Is it a field in deployment? Thank you

**Comment by SongGithub** [comment]
yes, it is the field in deployment manifest file. 
i.e.
```
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dex-slo
  labels:
    component: dex

spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "100%"
  selector:
    matchLabels:
      component: dex
  template:
    metadata:
      labels:
        component: dex
    spec:
      serviceAccount: dex-slo
```
