### ISSUE TITLE
kustomize 5 build returns error when labels on a resource is null

### ISSUE THREAD

**Issue by pavansokkenagaraj** [kubernetes-sigs/kustomize#5050]
### What happened?

kustomize build(V5.0.0) with patches and transformer on a resource having labels as null returns error: 
```
Error: considering field 'metadata/labels' of object Job.v1.batch/security-job.[noNs]: wrong node kind: expected MappingNode but got ScalarNode: node contents:
null
```

### What did you expect to happen?

expected: kustomize build to 

merge the resources and resulting yaml to be returned.

kustomize v4.5.7 build returned the results when `labels: null` [as expected]

If I remove `labels: null` from resources the kustomize build works [but should work with `labels:null`]

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
transformers:
- label-transformer.yaml
patches:
- path: pullsecrets.yaml
# patchesStrategicMerge:
#   - pullsecrets.yaml
```

```yaml
# resources.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels: null
  name: security-job
spec:
  backoffLimit: 3
  template:
    metadata:
      name: security-test
    spec:
      containers:
      - name: hook-test
```

```yaml
# label-transformer.yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: label-transformer
labels:
  test.io/name: label-transformer
fieldSpecs:
- path: metadata/labels
  create: true
```

```yaml
# pullsecrets.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: security-job
spec:
  template:
    spec:
      imagePullSecrets:
      - name: multi-namespace-yeti-registry
```

### Expected output

>➜  kustomize4 build
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    test.io/name: label-transformer
  name: security-job
spec:
  backoffLimit: 3
  template:
    metadata:
      name: security-test
    spec:
      containers:
      - name: hook-test
      imagePullSecrets:
      - name: multi-namespace-yeti-registry
```

### Actual output

>➜  kustomize build
```yaml
Error: considering field 'metadata/labels' of object Job.v1.batch/security-job.[noNs]: wrong node kind: expected MappingNode but got ScalarNode: node contents:
null
```

### Kustomize version

V5.0.0

### Operating system

Linux

**Comment by KnVerey** [comment]
What is the intention of including `labels: null` in the base resource? This change is very likely caused by a fix we made to the handling of null values in base resources: #4890 . Previously, they were incorrectly treated as a deletion directive. Now, they are retained, and in this case are not the correct type for the field (empty value should be `{}` for a map).

/triage needs-information

**Comment by sgalsaleh** [comment]
@KnVerey here's another example where kustomize 5 isn't able to process null values that Kubernetes (e.g. kubectl apply) is okay with, which is `initContainers: null`:

`deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers: null
      containers:
      - name: nginx
        image: nginx
```

`pull-secret.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      imagePullSecrets:
      - name: example-pull-secret
```

`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- pull-secret.yaml
resources:
- deployment.yaml
```

Running kustomize build:
```bash
$ kustomize build kustomize-example/
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Error: updating name reference in 'spec/template/spec/initContainers/env/valueFrom/configMapKeyRef/name' field of 'Deployment.v1.apps/nginx.[noNs]': considering field 'spec/template/spec/initContainers/env/valueFrom/configMapKeyRef/name' of object Deployment.v1.apps/nginx.[noNs]: expected sequence or mapping node
```

**Comment by sgalsaleh** [comment]
@KnVerey any plans to address this issue? this unfortunately breaks some of the Helm charts our customers are using in production and it's not easily workaround-able without breaking existing functionality.

**Comment by obfuscurity** [comment]
Any updates?

**Comment by obfuscurity** [comment]
Is anyone able to look at this issue? This remains a blocker to our upgrading to 5.x.

**Comment by cbodonnell** [comment]
Hi @KnVerey, I have some more interesting findings as it relates to this issue.  Apologies in advance for the lengthy comment...

It appears that kustomize _will actually add_ `null` to a field if it is empty.  For example, some resources in community Helm charts may look like the following after rendering templates (notice the empty labels):

`resource.yaml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
  labels:
data:
  key: value
```
If I simply run this resource through kustomize without any transformations:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resource.yaml
```
The build output is the following:
```
$ kustomize build
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  labels: null
  name: myapp
```
If I then try to apply a label transformer _and_ patch to this output, it will fail with the aforementioned error.  However, it will not if I use the original resource with the empty `labels` field.  Additionally, it seems to work fine if I leave out either the label transformer _or_ the patch, which also seems odd.

`new-resource.yaml`:
```
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  labels: null
  name: myapp
```

`kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resource.yaml
transformers:
- label-transformer.yaml
patches:
- path: patch.yaml
```

`label-transformer.yaml`:
```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: label-transformer
labels:
  test.io/name: label-transformer
fieldSpecs:
- path: metadata/labels
  create: true
```

`patch.yaml`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  newkey: newvalue
```

Result:
```
$ kustomize build
Error: considering field 'metadata/labels' of object ConfigMap.v1.[noGrp]/myapp.[noNs]: wrong node kind: expected MappingNode but got ScalarNode: node contents:
null
```

After swapping out `new-resource.yaml` for the original `resource.yaml` with the empty field:
```
$ kustomize build
apiVersion: v1
data:
  key: value
  newkey: newvalue
kind: ConfigMap
metadata:
  labels:
    test.io/name: label-transformer
  name: myapp
```
