### ISSUE TITLE
Problem reusing a base containing a variable

### ISSUE THREAD

**Issue by jcassee** [kubernetes-sigs/kustomize#506]
When I include a base that defines and uses a variable twice, the variable is not expanded.

Example:

component1/kustomization.yaml:
```
resources:
  - resources.yaml

vars:
  - name: VAR
    objref:
      apiVersion: v1
      kind: Pod
      name: component1
```

component1/resources.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: component1
spec:
  containers:
    - name: component1
      image: bash
      env:
        - name: VAR
          value: $(VAR)
```

app1/kustomization.yaml:
```
bases:
  - ../component1

namePrefix: app1-
```

app2/kustomization.yaml:
```
bases:
  - ../component1

namePrefix: app2-
```

kustomization.yaml:
```
bases:
  - app1
  - app2
```

Output:
```
apiVersion: v1
kind: Pod
metadata:
  name: app1-component1
spec:
  containers:
  - env:
    - name: VAR
      value: $(VAR)
    image: bash
    name: component1
---
apiVersion: v1
kind: Pod
metadata:
  name: app2-component1
spec:
  containers:
  - env:
    - name: VAR
      value: $(VAR)
    image: bash
    name: component1
```

Output when you comment out one of the app bases in the toplevel kustomization:
```
apiVersion: v1
kind: Pod
metadata:
  name: app1-component1
spec:
  containers:
  - env:
    - name: VAR
      value: app1-component1
    image: bash
    name: component1
```

Note: this example is silly, but it shows the problem succinctly. In my case, I have an application that uses a variable to discover a database service name to connect to. That application is then used as a base multiple times in order to deploy multiple versions of it.

**Comment by Liujingfang1** [comment]
I can explain why it behaves this way. When kustomize resolves $VAR, it first resolve the object the $VAR is referred to. Here since $VAR is defined in the base. From the top level overlay, there are two objects that this $VAR can be associated with. When you comment one, there is a unique object the $VAR associated with. Thus the substitution happens.

**Comment by jcassee** [comment]
Sure, but the variable is resolved on the lower level, right? It means some kustomizations cannot be reused, because they use variables?

Would you say this is a design decision or could it be "fixed"?

**Comment by Liujingfang1** [comment]
I wouldn't say this is a design decision. A common base should be able to use in different overlays. However, fixing it could be tricky.

**Comment by jcassee** [comment]
Unfortunately, I do not know enough Go to be useful here. :disappointed:

**Comment by Liujingfang1** [comment]
To fix this issue, we can filter the resources by either prefix or namespace as we did for namereference transformation

**Comment by Shalucik** [comment]
I'm also having this problem, is there any news if and when this will be fixed?

**Comment by jbrette** [comment]
@jcassee  @Shalucik Please a look and help test [PR](https://github.com/kubernetes-sigs/kustomize/pull/1253)

There is still a big issue with variable pointing at name which get transformed, but 1253 could potentially be a path forward. The environment used to reproduce your issue is [Here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0506)

The kustomization.yaml contains two variables...one pointing to the name, the other to the image:
```yaml
resources:
  - resources.yaml

vars:
- name: POD_NAME
  objref:
    apiVersion: v1
    kind: Pod
    name: component1
  fieldref:
    fieldpath: metadata.name
- name: IMAGE_NAME
  objref:
    apiVersion: v1
    kind: Pod
    name: component1
  fieldref:
    fieldpath: spec.containers[0].image
```

The resource.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: component1
spec:
  containers:
    - name: component1
      image: bash
      env:
        - name: POD_NAME
          value: $(POD_NAME)
        - name: IMAGE_NAME
          value: $(IMAGE_NAME)
```
The output is the following. Note that POD_NAME in app2-component1 is still wrong...but we are making progress.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: app1-component1
spec:
  containers:
  - env:
    - name: POD_NAME
      value: app1-component1
    - name: IMAGE_NAME
      value: bash
    image: bash
    name: component1
---
apiVersion: v1
kind: Pod
metadata:
  name: app2-component1
spec:
  containers:
  - env:
    - name: POD_NAME
      value: app1-component1
    - name: IMAGE_NAME
      value: bash
    image: bash
    name: component1

```

/cc @monopole @Liujingfang1

**Comment by jbrette** [comment]
@jcassee @Shalucik  I think we finally nailed it. Have [a look here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0506).
and [in the automatic go tests](https://github.com/keleustes/kustomize/blob/allinone/pkg/target/variableref_test.go#L436)

Your need to use this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1316)

```bash
kustomize build .
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: app1-component1
spec:
  containers:
  - env:
    - name: POD_NAME
      value: app1-component1
    - name: IMAGE_NAME
      value: bash
    image: bash
    name: component1
---
apiVersion: v1
kind: Pod
metadata:
  name: app2-component1
spec:
  containers:
  - env:
    - name: POD_NAME
      value: app2-component1
    - name: IMAGE_NAME
      value: bash
    image: bash
    name: component1
```
