### ISSUE TITLE
Inconsistent transformer behavior on configMapGenerator when used via components vs not

### ISSUE THREAD

**Issue by alexlatchford** [kubernetes-sigs/kustomize#5060]
### What happened?

Labels and annotations set from components do not apply to `ConfigMap` resources created by `configMapGenerator`, but do apply to other resources.

### What did you expect to happen?

The labels and annotations from components would apply to `ConfigMap` resources created by `configMapGenerator`.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- components/metadata

resources:
- namespace.yaml

transformers:
  - metadata.yaml

commonAnnotations:
  inline-commonAnnotations: bar

commonLabels:
  inline-commonLabels: bar

configMapGenerator:
  - name: cm
    literals:
      - A=b
```

```yaml
# metadata.yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: metadata
labels:
  inline-labelTransformer: true
fieldSpecs:
- path: metadata/labels
  create: true
---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: metadata
annotations:
  inline-annotationsTransformer: true
fieldSpecs:
- path: metadata/annotations
  create: true
```

```yaml
# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ns
```

```yaml
# components/metadata/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
- metadata.yaml

commonAnnotations:
  component-commonAnnotations: bar

commonLabels:
  component-commonLabels: bar
```

```yaml
# components/metadata/metadata.yaml
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: metadata
labels:
  component-labelTransformer: true
fieldSpecs:
- path: metadata/labels
  create: true
---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: metadata
annotations:
  component-annotationsTransformer: true
fieldSpecs:
- path: metadata/annotations
  create: true
```

### Expected output

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    component-annotationsTransformer: "true"
    component-commonAnnotations: bar
    inline-annotationsTransformer: "true"
    inline-commonAnnotations: bar
  labels:
    component-commonLabels: bar
    component-labelTransformer: "true"
    inline-commonLabels: bar
    inline-labelTransformer: "true"
  name: ns
---
apiVersion: v1
data:
  A: b
kind: ConfigMap
metadata:
  annotations:
    component-annotationsTransformer: "true"
    component-commonAnnotations: bar
    inline-annotationsTransformer: "true"
    inline-commonAnnotations: bar
  labels:
    component-commonLabels: bar
    component-labelTransformer: "true"
    inline-commonLabels: bar
    inline-labelTransformer: "true"
  name: cm-b9t2424hkf
```

### Actual output

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    component-annotationsTransformer: "true"
    component-commonAnnotations: bar
    inline-annotationsTransformer: "true"
    inline-commonAnnotations: bar
  labels:
    component-commonLabels: bar
    component-labelTransformer: "true"
    inline-commonLabels: bar
    inline-labelTransformer: "true"
  name: ns
---
apiVersion: v1
data:
  A: b
kind: ConfigMap
metadata:
  annotations:
    inline-annotationsTransformer: "true"
    inline-commonAnnotations: bar
  labels:
    inline-commonLabels: bar
    inline-labelTransformer: "true"
  name: cm-b9t2424hkf
```

### Kustomize version

v5.0.0

### Operating system

MacOS

---

Obviously a very minor bug (if you can even call it that, maybe this is just expected behavior) for a very niche scenario but wondered whether I'd missed something about resolution order here in the docs.
