### ISSUE TITLE
Use replacement syntax for patch

### ISSUE THREAD

**Issue by b1zzu** [kubernetes-sigs/kustomize#5063]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I want to use the `replacement` syntax which is more powerful than the `patchesJson6902` but without using another resource as the source.

I would like to rewrite this:

```yaml
replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: cluster
      namespace: default
      fieldPath: data.HOSTNAME
    targets:
      - &ingress
        select:
          group: networking.k8s.io
          version: v1
          kind: Ingress
          name: cluster-prometheus-oauth2-proxy
          namespace: default
        options:
          delimiter: .
          index: 1
      - <<: *ingress
        select:
          name: cluster-grafana-oauth2-proxy
      - &deployment
        select:
          group: apps
          version: v1
          kind: Deployment
          name: cluster-prometheus-oauth2-proxy
          namespace: default
        fieldPaths:
          - spec.template.spec.containers.[name=oauth2-proxy].env.[name=REDIRECT_HOST].value
        options:
          delimiter: .
          index: 1
      - <<: *deployment
        select:
          name: cluster-grafana-oauth2-proxy
```

like this:

```yaml
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      labelSelector: component=internal-ingress
      fieldPaths:
        - spec.tls.*.hosts.*
        - spec.rules.*.host
      options:
        delimiter: .
        index: 1
    patch: example.com
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: component=oauth2-proxy-deployment
      fieldPaths:
        - spec.template.spec.containers.[name=oauth2-proxy].env.[name=REDIRECT_HOST].value
      options:
        delimiter: .
        index: 1
      patch: example.com

```

### Why is this needed?

Keep the configuration cleaner, and leverage the `labelSelector` to patch multiple resources at the same time.

### Can you accomplish the motivating task without this feature, and if so, how?

I can achieve the same final result using replacement and ConfigMap

### What other solutions have you considered?

Post kustomize variables substitution like Flux does [1]

1. https://fluxcd.io/flux/components/kustomize/kustomization/#variable-substitution

### Feature ownership

- [x] I am interested in contributing this feature myself! 🎉

**Comment by KnVerey** [comment]
cc @natasha41575 as the main author of replacements, but I believe we would prefer to address any shortcomings in Replacements rather than transferring the more complex syntax to the simpler patches transformer. If I understand correctly from the following:

> Keep the configuration cleaner, and leverage the labelSelector to patch multiple resources at the same time.

part of the problem you have with using replacements is label selector support in targets. The good news is that already exists! Although it seems to be missing from the docs for some reason, it was introduced in https://github.com/kubernetes-sigs/kustomize/pull/4229 and this [test case](https://github.com/kubernetes-sigs/kustomize/blob/2f2ba40876b3b6c5b33281e8dee503010a1bc537/api/filters/replacement/replacement_test.go#L1905-L1977) is an example of how to use it:

```yaml
replacements:
- source:
    kind: Deployment
    name: deploy-1
    fieldPath: spec.template.spec.containers.0.image
  targets:
  - select:
      labelSelector: foo=bar-1
    fieldPaths:
    - spec.template.spec.containers.1.image
```

The other shortcoming seems to be the need to source the replacement value from a resource:

> I want to use the replacement syntax which is more powerful than the patchesJson6902 but without using another resource as the source.

One thing that is already possible is to put the `config.kubernetes.io/local-config: "true"` annotation on your ConfigMap so that it will not appear in the `kustomize build` output. Would you be happy with that solution in conjunction with the labelSelector field? Alternatively, what if Replacements supported an inline value as a source? 

/triage needs-information
