### ISSUE TITLE
ConfigMapGenerator merging does not see the other resource

### ISSUE THREAD

**Issue by LonguCodes** [kubernetes-sigs/kustomize#5066]
### What happened?

I'm trying to setup multiple environments throught `base` configmap and `dev` configmap using generators

```yaml
// Base

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
  - envs:
      - ".env"
    name: api-config



resources:
  - deployment.yaml
```

``` yaml
// Dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
  - envs:
      - ".env"
    behavior: merge
    name: api-config
```

Currently, I'm getting error `merging from generator &{0xc002579930 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"api-config", Namespace:""} does not exist; cannot merge or replace`

When changing the  `merge` to `create` it correctly finds already existing config and throws appropriate error

### What did you expect to happen?

Expected to correctly merge the configs

### How can we reproduce it (as minimally and precisely as possible)?

File structure

![image](https://user-images.githubusercontent.com/48600606/221403424-340bc6ee-0bc9-46e1-9fd7-1adf2495a4e9.png)

```yaml
# base/api/.env
SOME_VAR=0
```

```yaml
# base/api/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
  - envs:
      - .env
    name: api-config
```

```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - api
```

```yaml
# base/dev/.env
SOME_VAR=1
```

```yaml
# dev/api/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
  - envs:
      - .env
    behavior: merge
    name: api-config
```
```yaml
# dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - api

```

### Expected output

```yaml
apiVersion: v1
data:
  SOME_VAR: "1"
kind: ConfigMap
metadata:
  name: api-config-d4m8d2824g
```

### Actual output

```
Error: accumulating resources: accumulation err='accumulating resources from 'api': '*****/dev/api' must resolve to a file': recursed accumulation of path '****/dev/api': merging from generator &{0xc0002bb520 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"api-config", Namespace:""} does not exist; cannot merge or replace
```

### Kustomize version

v5.0.0

### Operating system

Linux

**Comment by yutaroyamanaka** [comment]
@LonguCodes 

I suppose you can add `resources` to your `dev/api/kustomization.yaml`. 
I mean `dev/api/kustomization.yaml` will be as follows.

```yaml
$ // dev/api/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../base"
configMapGenerator:
  - envs:
      - ".env"
    behavior: merge
    name: api-config
```

As far as I can observe, two directories should have the parent-child hierarchy instead of sibling hierarchy in this case.

**Comment by KnVerey** [comment]
The problem is that each base is loaded independently within a single Kustomization; in your `dev/kustomization.yaml`, the Kustomizations from `../base` and `api` are separately and independently loaded and then merged into the final resources list. Moving the configMapGenerator up into `dev/kustomization.yaml` itself works, because `resources` is fully evaluated before `configMapGenerator`, which is then able to do the merge. Alternatively, the alpha [Component](https://kubectl.docs.kubernetes.io/guides/config_management/components/) type works the way you were hoping, because `Components` are able to see all the resources from the `resources` field. It would look like this:

```yaml
# dev/Kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - api
```

```yaml
# dev/api/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


configMapGenerator:
  - envs:
      - .env
    behavior: merge
    name: api-config
```

I hope that helps.

/kinds support
/triage resolved
/close
