### ISSUE TITLE
Components do not separate resources for name reference transformer

### ISSUE THREAD

**Issue by hifi** [kubernetes-sigs/kustomize#5067]
### What happened?

Resource name tracking (name reference transformer?) did not respect component boundaries. I may be holding it wrong but this result was quite unexpected.

Building the component and canary separately gives the expected results. Replacing the component with a normal resource gives the exact same result which would probably be expected but I'm not sure.

### What did you expect to happen?

Resources built from a component be detached from original name reference tracking.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - component
resources:
  - canary
```

```yaml
# component/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - resources.yaml
```

```yaml
# component/resources.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-app
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: backend-app
```

```yaml
# canary/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../component
patches:
  - target:
      kind: Ingress
      name: backend-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: backend-app-canary
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: backend-app-canary
  - target:
      kind: Service
      name: backend-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: backend-app-canary
```

### Expected output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-app
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-canary
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-app
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: backend-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-app-canary
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: backend-app-canary
```

### Actual output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-app
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-canary
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-app
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: backend-app-canary
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-app-canary
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: backend-app-canary
```

### Kustomize version

5.0.0

### Operating system

Linux

**Comment by natasha41575** [comment]
If I understand correctly, you are saying that the name reference to the Service in the Ingress object was incorrectly updated?

This is because the NameReference transformer sees that the service from your canary has been changed from `backend-app` to `backend-app-canary`, and it has no way to disambiguate whether your Ingress object is referring to the one from the canary or the component. It sees a match for `backend-app` and updates the Service reference accordingly. In general, name references will become ambiguous and problematic when you reuse resource directories and components without changing the name in both.

Is there a particular reason you are reusing it in both resource and components? You could achieve your goal more easily with something like:

```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
resources:
  - canary
  - component
```

```
# canary/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -foo
resources:
  - ../component
patches:
  - target:
      kind: Ingress
      name: backend-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: backend-app-canary
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: backend-app-canary
  - target:
      kind: Service
      name: backend-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: backend-app-canary
```

```
# component/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -bar
resources:
  - resources.yaml
```

This is more of the pattern that we expect when reusing base resource directories. Note that there is a nameSuffix added on each kustomization in my example to avoid confusing the NameReference transformer.
