### ISSUE TITLE
Kustomize is confusing Kind: Namespace with other Kind: Namespace's that belong to different API sets.

### ISSUE THREAD

**Issue by buzzaII** [kubernetes-sigs/kustomize#5072]
### What happened?

Using ASO V2 (Azure Operator for Kubernetes v2)

This looks like a bug with Kustomize, though causing issues with the [ServiceBus Namespace CRD
](https://azure.github.io/azure-service-operator/reference/#servicebus)
Kustomize is confusing a ServiceBus namespace with a k8s namespace:

kustomize.yaml:
```

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - azure-servicebus.yaml
```
azure-servicebus.yaml:
```
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: core-sb-99
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```
running:

` kubectl kustomize ./`

produces this output:
```

apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: podinfo
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```

Notice the name of the ServiceBus namespace is now podinfo when it was supposed to be core-sb-99

Also dicussed here: https://github.com/Azure/azure-service-operator/issues/2732

### What did you expect to happen?

The expectation would be that the output would be:

```
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: core-sb-99              <------- this is what it should have produced
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - azure-servicebus.yaml
```

```yaml
# resources.yaml
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: core-sb-99
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```

### Expected output

```yaml
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: core-sb-99
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```

### Actual output

```yaml
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: podinfo
  namespace: podinfo
spec:
  location: australiaeast
  owner:
    name: core-sb
  sku:
    name: Standard
  zoneRedundant: false
```

### Kustomize version

the one included in the latest kubectl

### Operating system

None
