### ISSUE TITLE
ValueAddTransformer crashes w/ stack overflow under Windows if target value contains / as path separator

### ISSUE THREAD

**Issue by Unveraenderbar** [kubernetes-sigs/kustomize#5078]
### What happened?

When setting up a ValueAddTransfomer using kustomize Windows executable that access the kustomization directory basename as value, a Go stack overflow is triggered if the target value contains a forward slash as path separator

### What did you expect to happen?

kustomize should not crash, but instead be able to process Unix-like paths seamlessly also if running under Windows.  
Still better would if kustomize would perform a "normalization" of paths to forward slash Unix notation -- IME, Windows can cope with such paths w/o problems, while generating paths containing backslashes as separators makes it impossible to do trans-platform development (i.e. develop kustomizations under Windows and use them under Unix)

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- application.yaml

transformers:
- application-transformer.yaml
```

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-application
spec:
  source:
    repoURL: https://git.int.co/gitops-kustomize
  targetRevision: prod
  #path: resources\prod # works if kustomize executable for Windows is used
  path: resources/prod  # crashes w/ golang stack overflow if kustomize executable for Windows is used
```

```yaml
---
apiVersion: builtin
kind: ValueAddTransformer
metadata:
  name: application-transformer

# Omitting the 'value:' field means that the current kustomization root directory name will be used as the value.
# value: not specified!

targets:
- selector:
    kind: Application
  fieldPath: spec/path
  filePathPosition: 99

```

### Expected output

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-application
spec:
  path: resources/prod/value-add-transformer-crash
  source:
    repoURL: https://git.int.co/gitops-kustomize
  targetRevision: prod
```

### Actual output

kustomize Windows executables crash  w/ go stack overflow

### Kustomize version

v4.5.7 and v5.0.0

### Operating system

Windows
