### ISSUE TITLE
Using a json6902 patch on a built-in generator/transformer only works with selectors for targets

### ISSUE THREAD

**Issue by snuggie12** [kubernetes-sigs/kustomize#5083]
### What happened?

I want to say up front I just tripped upon the bug and don't need it to work or anything. I figured I'd let you all  know in case you were interested. I realize it is far off the beaten path and pretty sure it only impacts KRM objects and all in-cluster objects must have a version?

While reading the docs on [transforming transformers](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/#transformed-transformers) I decided to see if I could patch a generator to workaround #5060. It seems like targeting without a selector requires the `apiVersion` to contain a version of some sort (note the `target` section of the patch itself does not require `version`, just that the generator says something like `apiVersion: builtin/v1`.)

The problem with that is, as I'm sure you're already aware, is that the generator is then treated as an external plugin.

I was able to get it all working with `labelSelctor` though.

### What did you expect to happen?

The generator would get patched without a version thus keeping it as a builtin generator.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# /generators/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmChart.yaml
```

```yaml
# /generators/base/helmChart.yaml
apiVersion: builtin/v1 # remove "/v1" to get working
kind: HelmChartInflationGenerator
metadata:
# uncomment to get working
#  labels:
#    use: yesplease
  name: sealed-secrets
name: sealed-secrets
namespace: sealed-secrets
repo: https://bitnami-labs.github.io/sealed-secrets
version: 2.7.6
additionalValuesFiles:
  - ../generators/base/base-helm-values.yaml
```

```yaml
# /generators/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      group: builtin # remove to get working
      kind: HelmChartInflationGenerator # remove to get working
# uncomment to get working
#     labelSelector: "use=yesplease"
    patch: |-
      - op: add
        path: /additionalValuesFiles/-
        value: ../generators/dev/helm-values.yaml
resources:
  - ../base
```

### Expected output

```yaml
additionalValuesFiles:
- ../generators/base/base-helm-values.yaml
- ../generators/dev/helm-values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: sealed-secrets
name: sealed-secrets
namespace: sealed-secrets
repo: https://bitnami-labs.github.io/sealed-secrets
version: 2.7.6
```

### Actual output

```yaml
additionalValuesFiles:
- ../generators/base/base-helm-values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: sealed-secrets
name: sealed-secrets
namespace: sealed-secrets
repo: https://bitnami-labs.github.io/sealed-secrets
version: 2.7.6
```

### Kustomize version

5.0.0

### Operating system

MacOS
