### ISSUE TITLE
`kubectl kustomize` can exit with 0 status and no diagnostics on a patch failure

### ISSUE THREAD

**Issue by roy-work** [kubernetes-sigs/kustomize#5093]
### What happened?

This is just #1512, so this is doubly frustrating, as the bot here prevents the issue tracker from effectively tracking issues.

`kubectl kustomize` will exit with success, while failing to apply patches. There is no diagnostic about why the patches failed to apply, nor, AFAICT, any ability to get any, or _any_ sort of logging at all.

### What did you expect to happen?

* The patch to apply
* Failures to apply patches to not silently fail, but rather report an error that the patch couldn't be applied!
* Some ability to debug and figure out why my patch isn't applying

You can find `argocd.yaml` [here](https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml), although honestly, literally any YAML with a `Deployment` in it suffices for this example, given how minimal it is.

Note that the example patch doesn't make semantic sense: I've greatly reduced `path` while trying to debug, all to no avail.

According to <http://helmet.kafuka.org/sbmods/json/#patcher>, the provided patch is valid, and patches the source data as expected.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
patchesJson6902:
  - target:
      version: apps/v1
      kind: Deployment
      name: argocd-server
    patch: |
      - op: replace
        path: "/spec"
        value: ["argocd-server", "--application-namespaces", "*"]
```

The following should suffice for "`argocd.yaml`", although the complete one is linked to above, as well.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
```

### Expected output

`kubectl` emits a diagnostic that the patch can't be applied: while I originally expected this patch to apply, the `target` specification is technically invalid.

```yaml
  - target:
      version: apps/v1
```

should read:

```
- target:
    group: apps
    version: v1
```

Personally, I think representing `target` like that — differently than how Kubernetes represents it with (`apiVersion`, `group`, `kind` and `name`) is a footgun, basically for the reasons here: a naïve reading of it means you'll think `version` == `apiVersion`.

`target` is not documented in the Kustomize reference docs, either. (There _are_ examples that demonstrate `group`, although I failed to see them until I knew to look for them.)

### Actual output

(the patch is ignored)

### Kustomize version

kubectl v1.25.4

### Operating system

MacOS

**Comment by sftim** [comment]
/retitle `kubectl kustomize` can exit with 0 status and no diagnostics on a patch failure

**Comment by sftim** [comment]
@roy-work please consider mentioning the exit status from `kubectl` in the expected behavior here

**Comment by annasong20** [comment]
Hi @roy-work, is this issue specific to `patches` or generic to logging? In other words, would you be satisfied if `patches` gave you feedback if a `target` wasn't found, or do you want logging in general?

I ask because if your concern is specific to `patches`, you can follow this issue instead: https://github.com/kubernetes-sigs/kustomize/issues/4379. There is also an outstanding PR to resolve that issue: https://github.com/kubernetes-sigs/kustomize/pull/4715. Otherwise, I can retitle this issue.

Also, would you say it's fair to reduce your example to the following?

```yaml
# kustomization.yaml
resources:
  - configmap.yaml
patches:
- target:
    version: apps/v1 # should not include group
  patch: |
    - op: replace
      path: "/data/key"
      value: "new-value"
```

```yaml
# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
  key: "value"
```

If I understand correctly, `patches` wasn't applying because instead of `version: v1`, you included the `group` as well. My concern with your original example is that even if you fixed `version`, kustomize would throw an error not because `patches` failed, but because as you said, the result of your example patch "doesn't make sense". I wrote a patch that still makes semantic sense and removed extraneous detail.

> `target` is not documented in the Kustomize reference docs, either.

Does the documentation for `target` [here](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/) help? If not, feel free to file a documentation bug.

FYI, [`patchesJson6902`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesjson6902/) has been deprecated, which is why I use `patches` in the example instead.

Thank you for detailing your setup! 

/triage needs-information
