### ISSUE TITLE
kustomize downloads helm charts and then reuses them when new version specified

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/kustomize#5097]
### What happened?

I believe this issue has come up a few times, but I think there is a very concrete incorrect behaviour bug that I think we can & should fix.  (I'm happy to work on fixing it if need be).

I was using the helmCharts support, with an upstream cilium chart, version 1.12.5.  When I run kustomize, it automatically downloads the cilium chart into ./charts/cilium-1.12.5.tar.gz, and inflates it into ./charts/cilium.

I then change the chart version to 1.13.1, but kustomize continues to use ./charts/cilium, which is version 1.12.5

### What did you expect to happen?

I would expect it to use the version I specified, given I didn't directly populate `./charts/cilium` (if I had created that directory myself, maybe the behaviour would be more understandable)

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
helmCharts:
- name: cilium
  repo: https://helm.cilium.io/
  version: 1.12.5
  releaseName: cilium
  namespace: kube-system
  valuesInline:
    hubble:
      enabled: false
```

Run `kustomize build`, change the version, the old version is used.

### Kustomize version

main

### Operating system

Linux
