### ISSUE TITLE
Support for multiple paths using JSON patch

### ISSUE THREAD

**Issue by gabricc** [kubernetes-sigs/kustomize#5107]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Hi everyone!
It would be great if we could specify multiple paths in a single op, add/replace operation. Lot of times we have paths that require the same value, and we have to repeat it a lot of times.

### Why is this needed?

This is an example where a lot of paths use the same `deployment-name` value. It makes the kustomization.yaml too repetitive:

```
bases:
- ../../../base-workers

patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: deployment-name
    - op: replace
      path: /metadata/namespace
      value: director
    - op: replace
      path: /metadata/labels/app
      value: deployment-name
    - op: replace
      path: /spec/template/metadata/labels/app
      value: deployment-name
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: deployment-name
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: registry
    - op: replace
      path: /spec/template/spec/containers/0/command
      value: ["java", "..."]
    - op: replace
      path: /spec/template/spec/containers/0/env/1
      value:
        name: DD_SERVICE
        value: deployment-name
    - op: replace
      path: "/spec/template/spec/containers/0/envFrom/0"
      value:
        configMapRef:
          name: deployment-name-env-variables
    - op: replace
      path: /spec/selector/matchLabels/app
      value: deployment-name
    - op: replace
      path: "/spec/template/metadata/labels/tags.datadoghq.com~1env"
      value: production
    - op: replace
      path: "/spec/template/metadata/labels/tags.datadoghq.com~1service"
      value: deployment-name
    - op: replace
      path: "/spec/selector/matchLabels/tags.datadoghq.com~1service"
      value: deployment-name
```

It would be great if we could do something like:
```
    - op: replace
      paths: {"/metadata/name", "/metadata/labels/app", "/spec/template/metadata/labels/app"}
      value: deployment-name
```

### Can you accomplish the motivating task without this feature, and if so, how?

Yes, but the code gets too repetitive.

### What other solutions have you considered?

I have considered using [strategic merge patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md), but it doesn’t fit so good to my scenario.

### Anything else we should know?

Thanks!

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉
