### ISSUE TITLE
Introduce Support for kube-version Parameter for Consuming Helm Charts Relying on Capabilities

### ISSUE THREAD

**Issue by cailynse** [kubernetes-sigs/kustomize#5112]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

`--kube-version` flag

example:
``` yaml
- name: reloader
  version: '0.0.113'
  repo: https://stakater.github.io/stakater-charts
  releaseName: reloader
  namespace: reloader
  kubeVersion: '1.21'
  valuesInline:
    # https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
    fullnameOverride: reloader
    reloader:
      deployment:
        replicas: 1
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "10m"
            memory: "128Mi"
      containerSecurityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      service:
        port: 9090
      serviceMonitor:
        enabled: true
        namespace: reloader
````

### Why is this needed?

To be able to consume helm templates that rely on Capabilities the `--kube-version` flag has to be supported.

### Can you accomplish the motivating task without this feature, and if so, how?

N/A

### What other solutions have you considered?

N/A

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉
