### ISSUE TITLE
additionalValuesFiles only allowed in current or child folder

### ISSUE THREAD

**Issue by nicl-dev** [kubernetes-sigs/kustomize#5115]
### What happened?

Trying to build the following `kustomization.yaml:`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../base/charts/argo-cd
helmCharts:
  - name: argo-cd
    releaseName: test
    namespace: testNamespace
    valuesFile: argo-cd-values.yaml
    additionalValuesFiles:
      - ../../variants/prod/argo-cd-values.yaml
```

We are running to the following error:
`could not load additionalValuesFile: security; file '/Users/nb/workspace/variants/dev/argo-cd-values.yaml' is not in or below '/Users/nb/workspace/envs/dev'`

Is this behavior intended? I couldn't find anything in the docs, but they are outdated anyway. If it is, is there any way to disable this behavior? It would really hinder us in using this long awaited feature.

### What did you expect to happen?

Being able to build our `kustomization.yaml` with `additionalValuesFiles` in any other local folder.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../base/charts/argo-cd
helmCharts:
  - name: argo-cd
    releaseName: test
    namespace: testNamespace
    valuesFile: argo-cd-values.yaml
    additionalValuesFiles:
      - ../../variants/prod/argo-cd-values.yaml
```

```
#argo-cd-values.yaml
global:
  spec:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

```
#../../variants/prod/argo-cd-values.yaml
global:
  repo: test-repo.com
```

Chart: Official argo-cd chart

### Expected output

Any output at all without a security error.

### Actual output

`could not load additionalValuesFile: security; file '/Users/nb/workspace/variants/dev/argo-cd-values.yaml' is not in or below '/Users/nb/workspace/envs/dev'`

### Kustomize version

v5.0.1

### Operating system

MacOS
