### ISSUE TITLE
Wrong name patching in apiVersion apps/v1

### ISSUE THREAD

**Issue by BestChinchilla** [kubernetes-sigs/kustomize#5118]
### What happened?

Instead of changing the name of the container, a new field name is added
It start working after changing apiVersion in base and overlay deployment to **v1beta1** or **extensions/v1beta1**, but I need **apps/v1**

OS:
WSL2 Ubuntu 20.04.6 LTS

### What did you expect to happen?

Changing the container name from **PLACEHOLDER** to **demo-app**

### How can we reproduce it (as minimally and precisely as possible)?

```bash
tree
.
├── base
│   ├── dp.yml
│   └── kustomization.yaml
└── overlays
    └── test-app
        ├── dp.yml
        └── kustomization.yaml
```

```yaml
# base/dp.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: PLACEHOLDER
spec:
  template:
    spec:
      containers:
        - name: PLACEHOLDER
```

```yaml
# base/kustomization.yaml
resources:
  - dp.yml
```

```yaml
# overlays/test-app/dp.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
        - name: demo-app
```

```yaml
# overlays/test-app/kustomization.yaml
resources:
  - ../../base
patches:
  - path: dp.yml
    target:
      kind: Deployment
    options:
      allowNameChange: true
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
      - name: demo-app
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
      - name: demo-app
      - name: PLACEHOLDER
```

### Kustomize version

v5.0.1

### Operating system

Linux
