### ISSUE TITLE
Rplace HTTPRoute/backendRefs.name by using replacements.

### ISSUE THREAD

**Issue by soumi-akira** [kubernetes-sigs/kustomize#5119]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

A way to replace HTTPRoute/backendRefs.name by using `replacements`.

### main.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foooooooooooooooo
  name: service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  labels:
    app: WANT_TO_REPLACE_THIS
  name: route
spec:
  hostnames:
    - "*"
  rules:
    - backendRefs:
        - name: WANT_TO_REPLACE_THIS
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /path
```

### kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - main.yaml
replacements:
  - source:
      kind: Service
      name: service
      fieldPath: metadata.labels.app
    targets:
      - select:
          kind: HTTPRoute
          name: route
        fieldPaths:
          - metadata.labels.app
          - spec.rules.[backendRefs.name=WANT_TO_REPLACE_THIS].backendRefs.[name=WANT_TO_REPLACE_THIS].name
```

### `kustomize build` result

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foooooooooooooooo
  name: service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  labels:
    app: foooooooooooooooo
  name: route
spec:
  hostnames:
  - '*'
  rules:
  - backendRefs:
    - name: WANT_TO_REPLACE_THIS
      port: 3000
    matches:
    - path:
        type: PathPrefix
        value: /path
```

### Why is this needed?

`replaces` feature is [officially](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/) recommended for alternative of `vars`. But `vars` could replace this case but `replaces` couldn't.

### Can you accomplish the motivating task without this feature, and if so, how?

N/A

### What other solutions have you considered?

N/A

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by KnVerey** [comment]
I believe the problem is with the syntax in the field path. The following seems to work as expected:

`spec.rules.*.backendRefs.[name=WANT_TO_REPLACE_THIS].name`

Result:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  labels:
    app: foooooooooooooooo
  name: route
spec:
  hostnames:
  - '*'
  rules:
  - backendRefs:
    - name: foooooooooooooooo
      port: 3000
    matches:
    - path:
        type: PathPrefix
        value: /path
```

/triage resolved
/kind support
