### ISSUE TITLE
Kustomize removing quotes

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#5124]
Umbrella issue for kustomize removing quotes where it shouldn't

- https://github.com/kubernetes-sigs/kustomize/issues/4845
- https://github.com/kubernetes-sigs/kustomize/issues/4146

**Comment by gandarez** [comment]
Any update on this thread?

**Comment by natasha41575** [comment]
This depends on https://github.com/kubernetes-sigs/kustomize/issues/4033, which I am hoping someone can pick up soon.

**Comment by spkane** [comment]
@natasha41575 Now that #4033 is done, what is the status of this work? We are running into an issue where `key: "true"` in a ConfigMap is incorrectly converted from a string to a boolean, completely breaking our workflow.

cc/ @akbar-mohammed @sibucan

**Comment by jasper-d** [comment]
Another case when using ConfigMap + Replacements:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: common-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  env:
    - name: SOMETHING
      value: "true"
    - name: SOMETHING_ELSE_THIS_HAS_THE_SAME_PROBLEM
      value: 'true'
    - name:  NORMALIZED_TO_BOOLEAN
      value: "FALSE"
    - name: NORMALIZED_TO_NUMBER
      value: "0"
----
...
replacements:
- source:
    kind: ConfigMap
    name: common-config
    fieldPath: data.env.[name=SOMETHING].value
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.*.env.[name=SOMETHING].value
    options:
      create: true
...
```

No matter what quotes or casing I use, I cannot get kustomize to just output a string literal.
Casing is forcefully normalized to lowercase and all quotes are removed, resulting in invalid YAML.
