### ISSUE TITLE
Secret generator doesn't replace according name with suffix

### ISSUE THREAD

**Issue by rgaoistheone** [kubernetes-sigs/kustomize#5129]
### What happened?

I'm using kustomize to build multi-enviroment manifests base on CloneSet (which is a custom resource other than deployment or statefulset )
So the same kustomization.yaml would result differently 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - files:
      - application.yml
    name: xxx-config
    namespace: xxx
resources:
  - ../base
  ```

configuration snippet for CloneSet 
```
      volumes:
        - name: xxx-config
          secret:
            secretName: xxx-config
```

### What did you expect to happen?

There should be hash like 
```
secretName: xxx-config-akjelkj
```

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - files:
      - application.yml
    name: xxx-config
    namespace: xxx
resources:
  - ../base
  ```
```
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: xxx-server
  name: xxx-server
  namespace: xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-server
  template:
    metadata:
      labels:
        app: xxx-server
    spec:
      containers:
        - image: image-registry
          imagePullPolicy: IfNotPresent
          name: xxx-server
          args: [ "-Xmx1024M" ]
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: xxx-config
              mountPath: /app/config
      volumes:
        - name: xxx-config
          secret:
            secretName: xxx-config
      restartPolicy: Always

```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

{Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64}

### Operating system

MacOS
