### ISSUE TITLE
Git submodule needs origin

### ISSUE THREAD

**Issue by jakedt** [kubernetes-sigs/kustomize#5131]
### What happened?

We've got an overlay system that uses remote git resources like so:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/etc/etc/etc?ref=deadbeefdeafbeef
```

That git repository itself has submodules in it. When we upgraded to the latest kustomize, we started getting errors like the following:

```
Error: accumulating resources: accumulation err='accumulating resources from 'https://github.cometc/etc/etc?ref=deadbeefdeafbeef&timeout=90s': URL is a git repository': failed to run '/usr/bin/git submodule update --init --recursive': warning: could not look up configuration 'remote.origin.url'. Assuming this repository is its own authoritative upstream.
```

This applies whether we use `kustomize build` directly or the kustomize that's bundled with `kubectl`.

### What did you expect to happen?

I expected to see the rendered resources on the command line.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v5.0.1

### Operating system

None
