### ISSUE TITLE
Add option to overwrite "image" of other CRs

### ISSUE THREAD

**Issue by leewoobin789** [kubernetes-sigs/kustomize#5138]
### Eschewed features

- [x] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kubernetes-args
spec:
  templates:
    - name: delete-pod
      inputs:
        parameters:
        - name: pod-name
        - name: namespace
        - name: delay
      script:
        image: kubectl
        command: [bash]
        source: |
          sleep {{inputs.parameters.delay}}
          kubectl delete pod -n {{inputs.parameters.namespace}} {{inputs.parameters.pod-name}}
```
For instance, if you want to apply overwriting image over kustomize for custom resources such as "WorflowTemplate" of argo workflow, you find out that it is certainly not working expectedly. I assume that kustomize alters only images with standard k8s resources. my humble option is that this feature extension would be a great enhancement to it.
```yaml
images:
- name: kubectl
  newName: bitnami/kubectl
  newTag: 1.25-debian-11
```
the setting above changes also the image spec of CRs

### Why is this needed?

once you have multiple CRs with image spec that use same image. users would want to overwrite these images in a central kustomization avoiding definition of current image for every image spec of CRs.

### Can you accomplish the motivating task without this feature, and if so, how?

yes but as the deployment base grows, it becomes more prone to any human mistakes.

### What other solutions have you considered?

None as far as I know

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉

**Comment by blairdrummond** [comment]
There actually is a way to do this, you just have to go down quite the rabbit hole to find it (mostly github issues that I can't remember the locations of)

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- image-transformer.yaml

images:
- name: gcr.io/kaniko-project/executor
  newTag: v1.9.2
  digest: sha256:034f15e6fe235490e64a4173d02d0a41f61382450c314fffed9b8ca96dff66b2
  
...
```

This was for `Tekton` CRs, but just switch the `kind` and the path and you should be in business

```yaml
# image-transformer.yaml
images:
- path: spec/steps[]/image
  kind: Task
```

I have no idea how or why it works haha
