### ISSUE TITLE
secretGenerator to generate Secret with stringData manifest

### ISSUE THREAD

**Issue by valerytschopp** [kubernetes-sigs/kustomize#5142]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

The secretGenerator should be able to generate Secret manifest with unencoded stringData.

We understand that kustomize eschews parameterization, but the resulting manifest is valid YAML, and can be processed by various tools (envsubst, flux post-build variable substitution, ...). 
Therefore we ask the Kustomize SIG to consider this feature.

Example:

```sh
cat<<EOF> secret-values.yaml
# Helm values
---
db:
  auth:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  host: ${DB_HOST}
EOF
cat<<EOF> kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: secret-values
  files:
  - values.yaml=secret-values.yaml
generatorOptions:
  disableNameSuffixHash: true
  stringData: true
EOF
```
```sh
kustomize build .
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-secret-values
stringData:
  values.yaml: |-
    db:
      auth:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      host: ${DB_HOST}
```

### Why is this needed?

We are doing GitOps with Flux's [post-build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomization/#post-build-variable-substitution) which currently requires stringData in the secret.
Base64 encoded values would not be able to be substitued.

### Can you accomplish the motivating task without this feature, and if so, how?

Create the Secret by hand with stringData:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
    name: secret-secret-values
stringData:
  values.yaml: |-
    db:
      auth:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      host: ${DB_HOST}
```

But this negate the usefulness of Kustomize generators. 

### What other solutions have you considered?

Don't use secretGenerator for Helm secret values

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by seh** [comment]
> We are doing GitOps with Flux's [post-build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomization/#post-build-variable-substitution) which currently requires stringData in the secret.

To clarify, post-build substitution does not require use of the "stringData" field in a candidate manifest, but _you_ want to use that field to sidestep the Base64 encoding, which masks the content you wish to replace.

Flux doesn't pay any attention to field names in the manifests. [It serializes them as YAML](https://sourcegraph.com/github.com/fluxcd/pkg@7fa160a2a27d7c8edb34e4c1adce5af721eabd29/-/blob/kustomize/kustomize_varsub.go?L61), and [runs _envsubst_ over the bytes](https://sourcegraph.com/github.com/fluxcd/pkg@7fa160a2a27d7c8edb34e4c1adce5af721eabd29/-/blob/kustomize/kustomize_varsub.go?L156).

**Comment by valerytschopp** [comment]
The Flux's [post-build variable substitution](https://fluxcd.io/flux/components/kustomize/kustomization/#post-build-variable-substitution) documentation clearly states:

> **Note:** For substituting variables in a secret, `.spec.stringData` field must be used i.e:
> ```yaml
> ---
> apiVersion: v1
> kind: Secret
> metadata:
>   name: secret
>   namespace: flux-system
> type: Opaque
> stringData:
>   token: ${token}
> ```

**Comment by seh** [comment]
I could see implementing this, accepting an option in the "secretGenerator[*].options" field, though that field is of type `api/types/GeneratorOptions`, which means that it's shared with other generators. Alternately, we could lift such an option up into `api/types/SecretArgs` which already bears [the _Secret_-specific "type" field](https://sourcegraph.com/github.com/kubernetes-sigs/kustomize@035924bc1e753c954a486e3a46898dc790df110a/-/blob/api/types/secretargs.go?L11-L18).

[The `api/internal/generators.MakeSecret` function](https://sourcegraph.com/github.com/kubernetes-sigs/kustomize@035924bc1e753c954a486e3a46898dc790df110a/-/blob/api/internal/generators/secret.go?L12-L60) appears to be the place to handle such a change.

**Comment by annasong20** [comment]
Hi @valerytschopp, thank you for explaining your use case and providing an example in your description. Thanks @seh for investigating.

Yes, we believe it is a reasonable use case to specify the `secretGenerator` add the data under a `stringData` field. This may also apply to the `binaryData` field for `ConfigMap`s. Can whoever wants to contribute to this feature write a [mini-KEP aka kustomize proposal](https://github.com/kubernetes-sigs/kustomize/tree/master/proposals)? We will start PR reviews for this feature once that KEP has been approved.

/triage accepted

**Comment by filedeploy** [comment]
This works in the meantime:
```
secretGenerator:
  - name: my-secret
    ...details...

patches:
  # Patch the above secret `data` -> `stringData` because secretGenerator doesn't support `stringData`
  - patch: |-
      - op: move
        from: /data
        path: /stringData
    target:
      kind: Secret
      name: my-secret
```

**Comment by seh** [comment]
> This also works in the meantime:

What about the Base64 encoding of the "data" field's value?

**Comment by filedeploy** [comment]
You're right, it still gets Base64 encoded. No dice then.

**Comment by bossm8** [comment]
I found an _ugly_ workaround which works at least for environment variables for pods, which we use with generators so that deployments get restarted once the values change (although this probably doesn't work as well for files):

```yaml
secretGenerator:
  - name: my-secret
    namespace: my-namespace
    literals: []

patches:
  - patch: |-
      - op: move
        from: /data
        path: /stringData
      - op: add
        path: /stringData
        value:
          API_KEY: ${API_KEY}
          SECRET: ${SECRET_KEY}
    target:
      kind: Secret
      name: my-secret
```
