### ISSUE TITLE
extract kustomization infos from path

### ISSUE THREAD

**Issue by fragolinux** [kubernetes-sigs/kustomize#5143]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

can kustomize extract parts of the info from the paths or other external infos?

i mean, if i've a folder structure as:

```
L1
\-L2
  \-L3
```
and a kustomization in L3, can i extract, for example, a prefix formed as "L1-L2-L3-" ?

### Why is this needed?

automatic naming of resources based on path nesting

### Can you accomplish the motivating task without this feature, and if so, how?

we now do something like this using "substitute" and "substituteFrom" in folder specific kustomization files, but having it automatic would allow to remove these substitutions, having them automatically constructed based on path nesting

### What other solutions have you considered?

substitute and substituteFrom

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by annasong20** [comment]
Hi @fragolinux, we'd like to clarify your issue request. Reading the issue description, these are some of the questions that come to mind:
1. By "prefix", do you mean you'd like to prefix the names of your resources with the nested field path?
2. What is the context for "substitute" and "substituteFrom"? I don't believe these are kustomize keywords.
3. Can you further explain your use case? If we understand more about why you'd like to use your directory structure for naming, we could maybe better advise you on a solution or at least gain more insight on this feature request.

/triage needs-information

**Comment by fragolinux** [comment]
ok, let me explain:
we use a git setup for our clusters, managed by flux, which consists in at least 3 repos:

- flux - flux core components, and kustomizations pointing to this same repo and the others below, 1 kustomization for each folder
- system - contains system components common to each env, for example cert-manager, or external-dns, or ingress-nginx, etc
- envX - could be 1 or many, based on different environments on the same cluster

i'll not go in details on how we deploy this, we just follow normal flux recomendations (with some tweaks, for example we use sops to store secrets in git repos, but the 1st secrets - containing the decryption key - should be deployed directly on cluster without sops, of course, and other stuff not related to this issue)

for example, we have a staging cluster, which contains 2 envs: LAB and QA, and each env can contain different instances of our app (in next excerpts, "ha" is the instance name). in Lab env repo, we have this configmap: e4t/ha/core/cm-hr-base.yaml
which contains something like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${instanceName}-core-hr-base
  labels:
    headapp.eu/scope: gitops
    app.kubernetes.io/part-of: e4t
data:
  values.yaml: |
    ingress:
      hostnames:
        app:
          hosts:
            - ${externalHostnamePrefix}-app.${externalHostnameSuffix}
            - ${externalHostnamePrefix}.${externalHostnameSuffix}
            - ${envName}-app.${externalHostnameSuffix}
            - ${envName}.${externalHostnameSuffix}
        media:
          hosts:
            - ${externalHostnamePrefix}-media.${externalHostnameSuffix}
            - ${envName}-media.${externalHostnameSuffix}
```

and in flux repo, we have a corresponding kustomization: flux-system/kustomizations/ext/e4t/lab/ha/kustomization-core.yaml
which contains:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ext-e4t-lab-ha-core
  namespace: flux-system
spec:
  interval: 24h # could be disabled as well, due to availability of webhook + receiver
  retryInterval: 1m # retry at a faster pace
  timeout: 1m # Protection against intermittent failures or timeouts in sops key resolution
  path: ./e4t/ha/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging-lab
  decryption:
    provider: sops
    secretRef:
      name: sops-keys-lab
  dependsOn:
    - name: ext-e4t-lab-common-base
      namespace: flux-system
    - name: ext-e4t-lab-common-nats
      namespace: flux-system
    - name: ext-e4t-lab-common-mongodb
      namespace: flux-system
    - name: ext-e4t-lab-ha-base
      namespace: flux-system
  targetNamespace: lab
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: kustomization
      - kind: ConfigMap
        name: ext-e4t-lab-common-kustomization
      - kind: ConfigMap
        name: lab-ha-base-kustomization
```

as you can see, most of the resource names are directly related to their folder position, so it would be nice if these could be built automatically based on the folder itself, instead of having them directly put inside the manifests

the substitute are kustomization directives in flux terms, they replace what you put directly in "substitute", as in next example, or in configmaps merged via substituteFrom directive:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: int-trivy
  namespace: flux-system
spec:
  interval: 24h # could be disabled as well, due to availability of webhook + receiver
  retryInterval: 1m # retry at a faster pace
  timeout: 1m # Protection against intermittent failures or timeouts in sops key resolution
  path: ./int/trivy
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging-system
  dependsOn:
    - name: system-readiness
      namespace: flux-system
  targetNamespace: trivy
  postBuild:
    substitute:
      namespace: trivy
      release: trivy
    substituteFrom:
      - kind: ConfigMap
        name: kustomization
```

hope this helps and clarifies our use case :)
