### ISSUE TITLE
label/annotation for specific generated configmap

### ISSUE THREAD

**Issue by jcpunk** [kubernetes-sigs/kustomize#5146]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

The ability to add a label/annotation to just one (or so) generated configmap:

```yaml
configMapGenerator:
  - name: my-config
    files: [ example.conf ]
  - name: my-config-otherconfig
    files: [ special.conf ]
    labels:
      extra: note
    annotations:
      something: special
```

### Why is this needed?

When generating a resource it can be handy to attach additional metadata to a subset of the config maps.

### Can you accomplish the motivating task without this feature, and if so, how?

Yes, by instantly using the json patch functionality to patch the generated resource.

### What other solutions have you considered?

Patching each time

### Anything else we should know?

The patching each time is somewhat ugly/error prone

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by annasong20** [comment]
Hi @jcpunk, do you know about the [`labels`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/) and [`commonAnnotations`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/commonannotations/) fields? There's also [`generatorOptions`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/generatoroptions/) if you want to apply a certain label or annotation to all generated resources.

If you're looking to filter certain resources to apply labels or annotations to and you don't want to use `patches`, you can put the select resources into their own kustomization before you apply the `labels`, `annotations`, or `generatorOptions` fields. Does that work better for your use case?

As a last resort, you could also [write your own custom generator under the `generators` field](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/containerized_krm_functions/). Please follow up if these solutions aren't sufficient.

/kind support
/triage needs-information

**Comment by jcpunk** [comment]
I'm aware of the current built in options.  They don't appear to let me target just one of many elements.

My targeted workflow is to take a bunch of grafana dashboards (`.json` files) and turn them into individual configmaps with some having one set of labels/annotations and some having another.  Since the json files are all exported into the same directory multiple kustomize files feels like it wouldn't be ideal...

**Comment by annasong20** [comment]
> My targeted workflow is to take a bunch of grafana dashboards (`.json` files) and turn them into individual configmaps with some having one set of labels/annotations and some having another. Since the json files are all exported into the same directory multiple kustomize files feels like it wouldn't be ideal...

@jcpunk thank you for the insight. That makes a lot of sense.

Unfortunately, I don't think we plan to accept this feature because each of the built-in `generators` and `transformers` serves its own purpose and we don't want to overload `configMapGenerator` with `labels` and `commonAnnotations` functionality. I think `patches` was meant to support your use case: modify a specific resource in the current kustomization. I'd like to understand why that isn't working for you. You mention in your original issue description that

> Yes, by instantly using the json patch functionality to patch the generated resource.

and

> The patching each time is somewhat ugly/error prone

Would it help if you used a strategic merge patch instead? For example,

```yaml
configMapGenerator:
  - name: my-config
    files: [ example.conf ]
  - name: my-config-otherconfig
    files: [ special.conf ]

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: my-other-config
      labels:
       extra: note
     annotations:
       something: special
```
