### ISSUE TITLE
configmapGenerator fails to include files containing valid UTF-8 with control characters

### ISSUE THREAD

**Issue by mpol** [kubernetes-sigs/kustomize#5148]
### What happened?

Trying to include a valid UTF-8 file containing a control character (eg. \u0093) in a config map results in an error during `kustomize build`.

### What did you expect to happen?

A config map containing the file data with the control character correctly escaped or represented using `binaryData`.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - cfile
  name: cmap
```

```sh
# createcfile.sh
#!/bin/bash
echo $'\xc2\x93' > cfile
```

### Actual output

```
$ kustomize build
Error: map[string]interface {}{"apiVersion":"v1", "data":map[string]interface {}{"cfile":"\u0093\n"}, "kind":"ConfigMap", "metadata":map[string]interface {}{"name":"cmap-bdtdtb6f2c"}}: yaml: control characters are not allowed
```

### Kustomize version

v5.0.1

### Operating system

Linux
