### ISSUE TITLE
Warning: 'patchesStrategicMerge' is deprecated with kubectl 1.27.0

### ISSUE THREAD

**Issue by bq1756** [kubernetes-sigs/kustomize#5149]
### Error Messages
Starting with kubectl 1.27.0, I receive the following warning when running `kubectl kustomize ./`:

**Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead.**

When I change patchesStrategicMerge: to patches:, I receive the following error:

**error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch**

### Prior to kubectl 1.27.0
Either patchesStrategicMerge: or patches: work correctly. I do not see any warnings nor errors. Kustomize executes successfully I tested with 1.25.5 and 1.26.3.

### My config
./manifests/base
  kustomization.yaml
  k8sdeployment-manifest.yaml

./manifests/environments/p1
  kustomization.yaml
  env-overlay.yaml
  resources-overlay.yaml

./manifests/base/kustomization.yaml contains:
`resources:`
`  - k8sdeployment-manifest.yaml`

./manifests/environments/p1/kustomization.yaml contains:
`resources:`
`  - ../../base`
`patches: # or patchesStrategicMerge`
`  - env-overlay.yaml`
`  - resources-overlay.yaml`

### What did you expect to happen?

I expected `kubectl kustomize ./` to function the same way with all supported versions of kubectl. I expect a valid manifest file to be created.

### How can we reproduce it (as minimally and precisely as possible)?

./manifests/base/kustomization.yaml contains:
`resources:`
`  - k8sdeployment-manifest.yaml`

./manifests/environments/p1/kustomization.yaml contains:
`resources:`
`  - ../../base`
`patches: # or patchesStrategicMerge`
`  - env-overlay.yaml`
`  - resources-overlay.yaml`

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    environment: QA3
    version: 1.18.2
  name: my-app
spec:
.........
      containers:
      - env:
        - name: MYAPP_DSN
          value: SOMETEXT
        resources:
          limits:
            cpu: 1200m
            memory: 1024Mi
```

### Actual output

```yaml
error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
```
OR
```yaml
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

### Kustomize version

5.0.1??? kubectl 1.27.0

### Operating system

None

**Comment by rrpolanco** [comment]
I'm hitting the same error when trying to migrate my legacy `kustomization.yaml` via `kustomize edit fix`.

**Comment by ebberholmes** [comment]
I believe you need to add path: when using patches:
Have you tried this?

```
resources:
  - ../../base
patches: 
  - path: env-overlay.yaml
  - path: resources-overlay.yaml
```
