### ISSUE TITLE
`patches` unexpectedly dropping list entries in un-patched fields

### ISSUE THREAD

**Issue by jinnovation** [kubernetes-sigs/kustomize#5150]
### What happened?

Using `patches` to add annotations to resources results in list entries on the input resource getting dropped.

### What did you expect to happen?

That the annotations specified in the patch would get applied to the input resource, and that the input resource's list entries remain unchanged.

### How can we reproduce it (as minimally and precisely as possible)?

# `foo.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: foo
  - image: bar
```

# `bar.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  annotations:
    foo: bar
```

# `kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- foo.yaml

patches:
- path: bar.yaml
```

### Expected output

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  annotations:
    foo: bar
spec:
  containers:
  - image: foo
  - image: bar
```

### Actual output

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  annotations:
    foo: bar
spec:
  containers:
  - image: bar
```

### Kustomize version

5.0.1

### Operating system

MacOS
