### ISSUE TITLE
Securely pass credentials to a Containerized KRM

### ISSUE THREAD

**Issue by mdbooth** [kubernetes-sigs/kustomize#5152]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Some mechanism to pass arbitrary authentication data to a a Containerized KRM which doesn't require storing them in the kustomize directory.

This is likely to have to include environment variables and user config files. While this is technically _build-time side-effects from args or env vars_, the purpose is to provide static content. The effect is identical to including the output on disk with the advantage that it is not on disk, but the disadvantage is that you may need additional sensitive information to obtain it.

This is explained better below.

### Why is this needed?

I would like to create a KRM function for generating Secrets which obtains the secret payload from an external secret management system. The purpose of this is to avoid storing deployment secrets in a file or SCM along with other kustomize data, while still allowing a complete deployment using kustomize. My personal use case is manual deployment from the command line, although there may also be cases where this makes sense in automated tooling.

My kustomize will contain something like:
```yaml
apiVersion: openstack-barbican.example.com/v1alpha1
kind: SecretGenerator
metadata:
  name: notImportantHere
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/mdbooth/kustomize-barbican:latest
spec:
  name: passwords
  values:
  - name: root
    ref: https://x.x.x.x:13311/v1/secrets/aaaa-bbbb-cccc-dddd
```

It will generate:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: passwords
data:
  root: c3VwZXJzZWNyZXQ=
type: Opaque
```

### Can you accomplish the motivating task without this feature, and if so, how?

Yes. I can use an Exec KRM. However, my strong preference is to write a containerized KRM as it's simpler to distribute, and is also the explicit recommendation in https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_krm_functions/. An exec function must be embedded within the Kustomization's directory, which is not ideal for a generic tool which can be used anywhere a particular secret management system is deployed.

However, obtaining data from a secret management system inevitably requires data from the environment to provide, e.g. endpoints and authentication. These can be in the form of either environment variables or files. It's possible they could also be access to a hardware token, which could be very difficult to support. As far as I can tell there is no way to pass this type of information to a Containerized KRM without putting it in a file, which would defeat the primary purpose of the tool.

### What other solutions have you considered?

As above, an Exec KRM. I could also deploy secrets to my environment using a tool which is independent of kustomize.

If we decided that this was best implemented in an Exec KRM (e.g. so we don't even need to consider hardware token access), my request would be for better options for distributing an Exec KRM.

### Anything else we should know?

I have not proposed any specific solution because I am not familiar enough with the design space.

Reading 'Eschewed Features' it is clear that the project wants deterministic output. My use case is consistent with this goal, but providing the functionality required to implement my use case may enable use cases which the project doesn't appear to want to support, e.g. setting a VERSION in an object from a build-time environment variable. This is already possible with an Exec KRM, though, so perhaps it could be viewed in that light.

While I don't feel competent to design an API change in a new project, I may be able to find the time to implement one designed by others.

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉
