### ISSUE TITLE
invalid memory address or nil pointer dereference when using patches

### ISSUE THREAD

**Issue by MichaelTrip** [kubernetes-sigs/kustomize#5154]
### What happened?

i am trying to add proxy variables to a argoCD deployment with Kustomize. Tried it using the `patches` in Kustomize to add proxy variables with the replace. It works for 2 patches, but when adding the third Kustomize crashes:

```bash
$ kustomize build
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55f0bba91dbd]

goroutine 1 [running]:
github.com/evanphx/json-patch.findObject(0x55f0bbc92360?, {0xc002e39d40?, 0x55f0bbd8d380?})
	github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:366 +0x11d
github.com/evanphx/json-patch.Patch.add({0xc002ffa000?, 0xe28?, 0x1000?}, 0x55f0bbd23e60?, 0xc000e93f68?)
	github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:510 +0x66
github.com/evanphx/json-patch.Patch.ApplyIndent({0xc000b58ae0?, 0x4, 0x4}, {0xc002ffa000, 0xe28, 0x1000}, {0x0, 0x0})
	github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:748 +0x1f4
github.com/evanphx/json-patch.Patch.Apply(...)
	github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:718
sigs.k8s.io/kustomize/api/filters/patchjson6902.Filter.run({{0xc0027e0780, 0x263}, {0xc000b58ae0, 0x4, 0x4}}, 0x55f0bbd214e0?)
	sigs.k8s.io/kustomize/api/filters/patchjson6902/patchjson6902.go:59 +0x71
sigs.k8s.io/kustomize/kyaml/yaml.FilterFunc.Filter(0xc002f37e30?, 0x0?)
	sigs.k8s.io/kustomize/kyaml/yaml/types.go:127 +0x1f
sigs.k8s.io/kustomize/kyaml/kio.FilterAll.func1({0xc000e92a08?, 0x1, 0x1})
	sigs.k8s.io/kustomize/kyaml/kio/kio.go:166 +0x7a
sigs.k8s.io/kustomize/kyaml/kio.FilterFunc.Filter(0x55f0bbdcc768?, {0xc000e92a08?, 0x0?, 0x0?})
	sigs.k8s.io/kustomize/kyaml/kio/kio.go:71 +0x2a
sigs.k8s.io/kustomize/api/filters/patchjson6902.Filter.Filter({{0xc0027e0780, 0x263}, {0xc000b58ae0, 0x4, 0x4}}, {0xc000e92a08, 0x1, 0x1})
	sigs.k8s.io/kustomize/api/filters/patchjson6902/patchjson6902.go:29 +0xe8
sigs.k8s.io/kustomize/api/resource.(*Resource).ApplyFilter(0xc001a6bae0, {0x55f0bbdcc388, 0xc0024260f0})
	sigs.k8s.io/kustomize/api/resource/resource.go:503 +0x6b
sigs.k8s.io/kustomize/api/internal/builtins.(*PatchTransformerPlugin).transformJson6902(0xc0000a6050, {0x55f0bbdd9b48?, 0xc0000135c0?}, {0xc002f4a200?, 0xc001666960?, 0xc0025f3e00?})
	sigs.k8s.io/kustomize/api/internal/builtins/PatchTransformer.go:116 +0x22c
sigs.k8s.io/kustomize/api/internal/builtins.(*PatchTransformerPlugin).Transform(0xc0000135c0?, {0x55f0bbdd9b48?, 0xc0000135c0?})
	sigs.k8s.io/kustomize/api/internal/builtins/PatchTransformer.go:79 +0x46
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).Transform(0xc0000a6fa0?, {0x55f0bbdd9b48, 0xc0000135c0})
	sigs.k8s.io/kustomize/api/internal/target/multitransformer.go:30 +0x89
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	sigs.k8s.io/kustomize/api/internal/accumulator/resaccumulator.go:141
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runTransformers(0xc0000a6fa0, 0xc0002da360)
	sigs.k8s.io/kustomize/api/internal/target/kusttarget.go:334 +0x1c6
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc0000a6fa0, 0xc00035f578?)
	sigs.k8s.io/kustomize/api/internal/target/kusttarget.go:228 +0x34c
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0x55f0bb9afc60?)
	sigs.k8s.io/kustomize/api/internal/target/kusttarget.go:189 +0x105
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0000a6fa0)
	sigs.k8s.io/kustomize/api/internal/target/kusttarget.go:130 +0x5f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	sigs.k8s.io/kustomize/api/internal/target/kusttarget.go:121
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc0028ddd60, {0x55f0bbdd4b90, 0x55f0bc34f7e0}, {0x55f0bbc330c8, 0x1})
	sigs.k8s.io/kustomize/api/krusty/kustomizer.go:90 +0x33d
sigs.k8s.io/kustomize/kustomize/v5/commands/build.NewCmdBuild.func1(0xc000256780?, {0x55f0bc34f7e0?, 0x0?, 0x0?})
	sigs.k8s.io/kustomize/kustomize/v5/commands/build/build.go:82 +0x1b3
github.com/spf13/cobra.(*Command).execute(0xc000256780, {0x55f0bc34f7e0, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000256280)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
	github.com/spf13/cobra@v1.4.0/command.go:902 +0x19
main.main()
	sigs.k8s.io/kustomize/kustomize/v5/main.go:14 +0x1e
```

### What did you expect to happen?

adding proxy as a environment variable to all `Deployment` and `StatefulSet`.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml
- 2-repoconfig.yml
- 3-repo-creds.yml
- 7-ingress.yml

labels:
- includeSelectors: true
  pairs:
    app: argocd
    appstack: argocd

patches:
  - path: 4-secret.yml
  - path: 6-configmap.yml
  - path: 8-rbac.yml
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: http_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: https_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: no_proxy
          value: "127.0.0.1,::1,localhost,localhost.localdomain,some-domain.tld,10.0.0.8/8,192.168.0.0/16,argocd-repo-server,argocd-server,argocd-dex-server,argocd-dex-server:5556"
    target:
      kind: Deployment
      name: argocd-server

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: http_proxy
          value: "http://proxy-url:8080/"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: https_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: no_proxy
          value: "127.0.0.1,::1,localhost,localhost.localdomain,some-domain.tld,10.0.0.8/8,192.168.0.0/16,argocd-repo-server,argocd-server,argocd-dex-server,argocd-dex-server:5556"
    target:
      kind: Deployment
      name: argocd-repo-server
```

### Expected output

It works for the `argocd-server` and `argocd-repo-server` deployment. But adding a third doesn´t work and Kustomize crashes. 

### Actual output

see error.

### Kustomize version

5.0.1

### Operating system

Linux

**Comment by justinsb** [comment]
Hi @MichaelTrip  - could you possibly include the kustomization.yaml which triggers the panic?  It sounds like it happens when you add a third patch block, but I haven't been able to reproduce by starting with your example.

I think also that it should happen without the additional resources (- 2-repoconfig.yml, - 3-repo-creds.yml, - 7-ingress.yml) and hopefully the additional patches (  - path: 4-secret.yml,   - path: 6-configmap.yml,  - path: 8-rbac.yml).  But if that isn't the case and the panic only happens when the resources are included, could you please include those files also?  (Or at least sanitized versions of them)

**Comment by MichaelTrip** [comment]
> Hi @MichaelTrip - could you possibly include the kustomization.yaml which triggers the panic? It sounds like it happens when you add a third patch block, but I haven't been able to reproduce by starting with your example.
> 
> I think also that it should happen without the additional resources (- 2-repoconfig.yml, - 3-repo-creds.yml, - 7-ingress.yml) and hopefully the additional patches ( - path: 4-secret.yml, - path: 6-configmap.yml, - path: 8-rbac.yml). But if that isn't the case and the panic only happens when the resources are included, could you please include those files also? (Or at least sanitized versions of them)

Hi Justin,

I tested it again with the resources file commented out (only the ArgoCD Install)  and the same thing happens.

**Comment by MichaelTrip** [comment]
> @MichaelTrip could you possibly attach a kustomization.yaml file with the third patch block (and without the resources and patches[].path), so I can reproduce this?

Here is the third patch block. Sorry for the delay:

```yaml
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: http_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: https_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: no_proxy
          value: "127.0.0.1,::1,localhost,localhost.localdomain,some-domain.tld,10.0.0.8/8,192.168.0.0/16,argocd-repo-server,argocd-server,argocd-dex-server,argocd-dex-server:5556"
    target:
      kind: Deployment
      name: argocd-applicationset-controller

```

**Comment by natasha41575** [comment]
I am expecting one of the new kustomize trainees to take a look at this issue soon. 

To whichever trainee looks at this issue, could you please use the above information to see if you can reproduce it? Please leave a comment on your findings. If you can reproduce this, feel free to submit a fix.

**Comment by typeid** [comment]
I would also love to work on this if this isn't reserved to official kustomize trainees :) @natasha41575 let me know in case I can grab this.

**Comment by natasha41575** [comment]
@typeid I see you have already assigned yourself two other issues. To maximize productivity and parallelizability of kustomize contributors, please only assign yourself to 1 or 2 issues at a time.

**Comment by iamnoah** [comment]
Failed to repro with 5.1.1 on MacOS with:

<details><summary>kustomization.yaml</summary>

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml

labels:
  - includeSelectors: true
    pairs:
      app: argocd
      appstack: argocd

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: http_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: https_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: no_proxy
          value: "127.0.0.1,::1,localhost,localhost.localdomain,some-domain.tld,10.0.0.8/8,192.168.0.0/16,argocd-repo-server,argocd-server,argocd-dex-server,argocd-dex-server:5556"
    target:
      kind: Deployment
      name: argocd-server

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: http_proxy
          value: "http://proxy-url:8080/"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: https_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: no_proxy
          value: "127.0.0.1,::1,localhost,localhost.localdomain,some-domain.tld,10.0.0.8/8,192.168.0.0/16,argocd-repo-server,argocd-server,argocd-dex-server,argocd-dex-server:5556"
    target:
      kind: Deployment
      name: argocd-repo-server
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: http_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: https_proxy
          value: "http://proxy-url:8080"
      - op: add
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: no_proxy
          value: "127.0.0.1,::1,localhost,localhost.localdomain,some-domain.tld,10.0.0.8/8,192.168.0.0/16,argocd-repo-server,argocd-server,argocd-dex-server,argocd-dex-server:5556"
    target:
      kind: Deployment
      name: argocd-applicationset-controller

```

</details>

Based on the comments above, I removed the extra resources and added the third patch.
