### ISSUE TITLE
When Using Openshift route in base layer and adding namePreffix\nameSuffix in overlay the namePreffix\nameSuffix not mutates the service name.

### ISSUE THREAD

**Issue by tal-hason** [kubernetes-sigs/kustomize#5156]
### What happened?

i have the following directory structure.

Base
|_Overlay
    |_Dev
    |_Prod

under base, I have the following files:
1. deployment.yaml
2. route.yaml
3. service.yaml
4. kustomization.yaml

under dev\prod overlay i have the following files:
1. kustomization.yaml

the kustomization.yaml reffer to resources from the base layer:

```YAML
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -dev
```

when deploying the dev or prod layer the route isn't working because the service name under the spec.to.name isn't updated with the nameSuffix.

i need to add a Patch:

```YAML
patchesJSON6902:
- target:
    kind: Route
    name: argocicd-dev
  patch: |-
    - op: replace
      path: /spec/to/name
      value: argocicd-dev
```

to add the nameSuffix to the service name under the route config.

### What did you expect to happen?

as with nested names under other objects, like configmaps, secrets, and serviceAccounts when adding a name Suffix\Preffix to a Layer it needs to update all "name" keys of this object.

so no patch need to be made.

### How can we reproduce it (as minimally and precisely as possible)?

Base folder content:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml
```

```yaml
# deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        deployment: hello-world
    spec:
      containers:
        - name: hello-world
          image: 'quay.io/argocicd/hello-world:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
```

```yaml
#service.yaml
kind: Service
apiVersion: v1
metadata:
  name: hello-world
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-world
    deployment: hello-world
```

```yaml
#route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world
spec:
  to:
    kind: Service
    name: hello-world
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
```

Overlay/Dev folder content:

```yaml
#kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -dev
```

### Expected output

of the dev overlay route:

```yaml
#route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world-dev
spec:
  to:
    kind: Service
    name: hello-world-dev
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
```

### Actual output

of the dev overlay route:

```yaml
#route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world-dev
spec:
  to:
    kind: Service
    name: hello-world
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
```

### Kustomize version

4.5.7, Using ArgoCD 2.6.7

### Operating system

Linux

**Comment by annasong20** [comment]
Hi @tal-hason, thank you for such a detailed description! 

I think what you're looking for is the kustomize `configurations` field, which allows you to customize the paths to target fields on different resources.

For example, in your case, you'd just need to add `configurations` to your overlay/dev

```yaml
#kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configurations:
- suffix-rules.yaml

nameSuffix: -dev
```

```yaml
nameSuffix:
- path: spec/to/name
  apiVersion: route.openshift.io/v1
  kind: Route
```

I checked that this works for kustomize `v4.5.7`. Sorry we don't have better documentation for this field. I filed issue https://github.com/kubernetes-sigs/cli-experimental/issues/341. Until the official documentation is added, feel free to filter for `configurations` in kustomize issues. There's a decent number of them and should help you explore this field. Please re-open the issue if this doesn't solve your problem!

/close
