### ISSUE TITLE
kustomize edit fix deletes trailing comments

### ISSUE THREAD

**Issue by exocode** [kubernetes-sigs/kustomize#5158]
### What happened?

running command `kustomize edit fix` changes

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
bases:
  - ../../base
patchesStrategicMerge:
  - ./deployment.yaml
# resources:
# - ./ingress-t2.yaml
# - ./middleware-frontend-t2.yaml
# - ./middleware-backend-t2.yaml

```

to 
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ../../base
patches:
- path: ./deployment.yaml
```

### What did you expect to happen?

it should **keep comments untouched**

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
bases:
  - ../../base
patchesStrategicMerge:
  - ./deployment.yaml
# resources:
# - ./ingress-t2.yaml
# - ./middleware-frontend-t2.yaml
# - ./middleware-backend-t2.yaml
```

run 

`kustomize edit fix`

### Expected output

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ../../base
patches:
- path: ./deployment.yaml
# resources:
# - ./ingress-t2.yaml
# - ./middleware-frontend-t2.yaml
# - ./middleware-backend-t2.yaml
```

### Actual output

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ../../base
patches:
- path: ./deployment.yaml
```

### Kustomize version

v5.0.1

### Operating system

MacOS

**Comment by ramessesii2** [comment]
I'd like to work on it if someone please assign it to me.

**Comment by ramessesii2** [comment]
/assign

Thanks @natasha41575, those are good pointers.

**Comment by wingyplus** [comment]
@ramessesii2 I've a hack code to tackle the issue at #5180. It would be great if you have any suggestions. :)

**Comment by ramessesii2** [comment]
Thanks @wingyplus for the PR, I've been rather busy with my work.

**Comment by annasong20** [comment]
Renamed the issue to clarify that `kustomize edit fix` does currently preserve comments, as demonstrated by [tests in `kustomize/commands/internal/kustfile`](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/internal/kustfile/kustomizationfile_test.go#L188). The command just doesn't preserve trailing comments.

**Comment by cdenneen** [comment]
This also happens when you have comments at the end of a line:

```
images:
- name: imageone
  newName: registry.jfrog.io/docker/imageone # {"$imagepolicy": "platform-flux-tenant-config:imageone:name"}
  newTag: craft-4-957db1b2-1689262100 # {"$imagepolicy": "platform-flux-tenant-config:imageone:tag"}
```

->
```
images:
- name: imageone
  newName: registry.jfrog.io/docker/imageone
  newTag: craft-4-957db1b2-1689262100
```
