### ISSUE TITLE
kustomize 5.0.2 breaks helmCharts w/ chartHome

### ISSUE THREAD

**Issue by kenzht** [kubernetes-sigs/kustomize#5163]
### What happened?

Upgrading to 5.0.2 breaks helmCharts + chartHome. (which works fine in 5.0.1)

steps to reproduce:
```shell
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: charts

helmCharts:
- releaseName: minecraft
  namespace: default
  name: minecraft
  version: 3.1.3
  includeCRDs: true
$ ls
charts  kustomization.yaml
$ ls charts/
minecraft  minecraft-3.1.3.tgz
$ ~/bin/kustomize.5.0.1 build --enable-helm
apiVersion: v1
data:
  rcon-password: Q0hBTkdFTUUh
kind: Secret
metadata:
  labels:
    app: minecraft-minecraft
    chart: minecraft-3.1.3
    heritage: Helm
    release: minecraft
  name: minecraft-minecraft
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft-minecraft
    chart: minecraft-3.1.3
    heritage: Helm
    release: minecraft
  name: minecraft-minecraft
spec:
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: minecraft
  selector:
    app: minecraft-minecraft
  type: ClusterIP
$ ~/bin/kustomize.5.0.1 version
v5.0.1
$ ~/bin/kustomize.5.0.2 build --enable-helm
Error: no repo specified for pull, no chart found at ''
$ ~/bin/kustomize.5.0.2 version
v5.0.2
$
```

### What did you expect to happen?

kustomize build succeeds.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: charts

helmCharts:
- releaseName: minecraft
  namespace: default
  name: minecraft
  version: 3.1.3
  includeCRDs: true
```

### Expected output

```yaml
apiVersion: v1
data:
  rcon-password: Q0hBTkdFTUUh
kind: Secret
metadata:
  labels:
    app: minecraft-minecraft
    chart: minecraft-3.1.3
    heritage: Helm
    release: minecraft
  name: minecraft-minecraft
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft-minecraft
    chart: minecraft-3.1.3
    heritage: Helm
    release: minecraft
  name: minecraft-minecraft
spec:
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: minecraft
  selector:
    app: minecraft-minecraft
  type: ClusterIP
```

### Actual output

```none
Error: no repo specified for pull, no chart found at ''
```

### Kustomize version

5.0.2

### Operating system

Linux
