### ISSUE TITLE
kustomize not able to reject a resource with name field during replacement

### ISSUE THREAD

**Issue by mdfaizsiddiqui** [kubernetes-sigs/kustomize#5169]
### What happened?

In my base configuration I have a deployment object which has a http based health check probes. I've a requirement to kustomize this deployment object for one of my app (test-app2) & replace it with tcp health check. 

We've a common replacement file shared by all the apps (`/apps/common/internal/replacement.yaml`), and there we are renaming part of the http health check endpoint with the app name. (Assume that most of our application have http health check only and only one or two app will have this special requirement of having a tcp health check).

In the test-app2 (where we want tcp health checks), we're first adding a patch to add tcp health check and another patch to remove http health check. But as soon as the http health check is removed by the patch, the field is referenced/referred by replacement.yaml and hence we see this error -

```bash
➜  kustomize-bug git:(main) kustomize build --load-restrictor LoadRestrictionsNone envs/dev
Error: accumulating resources: accumulation err='accumulating resources from 'apps': read /Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps: is a directory': recursed accumulation of path '/Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps': accumulating resources: accumulation err='accumulating resources from 'test-app2': read /Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps/test-app2: is a directory': recursed accumulation of path '/Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps/test-app2': accumulating resources: accumulation err='accumulating resources from '../../../../apps/test-app2': read /Users/faizsiddiqui/github/kustomize-bug/apps/test-app2: is a directory': recursed accumulation of path '/Users/faizsiddiqui/github/kustomize-bug/apps/test-app2': unable to find field "spec.template.spec.containers.[name=main].readinessProbe.httpGet.path" in replacement target
```

In order to overcome this issue, we saw that in replacement object we can use `reject` to exclude a resource but somehow it is not working for us and we're still seeing the same above error.

```
- select:
      kind: Deployment
    reject:
      - name: test-app2
    fieldPaths:
      - spec.template.spec.containers.[name=main].readinessProbe.httpGet.path
      - spec.template.spec.containers.[name=main].livenessProbe.httpGet.path
```

As you can see that we want replacement to happen for all the deployment object excluding where name is `test-app2` (where we want tcp health check), but we're seeing error.

### What did you expect to happen?

We want `reject` section in replacement block to exclude the resource with the given name and only apply the replacement to all the selected resource except those mentioned in reject block.

### How can we reproduce it (as minimally and precisely as possible)?

Git Repo - https://github.com/mdfaizsiddiqui/kustomize-bug/tree/main

Execute -

```bash
kustomize build --load-restrictor LoadRestrictionsNone envs/dev
```

### Expected output

Expected output should have test-app2 probes to only have tcp health check like -

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: test-app2
  name: test-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: test-app2
  template:
    metadata:
      labels:
        app: my_service
        service: test-app2
    spec:
      containers:
      - image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/test-app2:cdfeff-123213
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 3
          periodSeconds: 4
          tcpSocket:
            port: 8080
        name: main
        readinessProbe:
          initialDelaySeconds: 3
          periodSeconds: 4
          tcpSocket:
            port: 8080
```

### Actual output

We're seeing error -

```bash
➜  kustomize-bug git:(main) kustomize build --load-restrictor LoadRestrictionsNone envs/dev
Error: accumulating resources: accumulation err='accumulating resources from 'apps': read /Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps: is a directory': recursed accumulation of path '/Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps': accumulating resources: accumulation err='accumulating resources from 'test-app2': read /Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps/test-app2: is a directory': recursed accumulation of path '/Users/faizsiddiqui/github/kustomize-bug/envs/dev/apps/test-app2': accumulating resources: accumulation err='accumulating resources from '../../../../apps/test-app2': read /Users/faizsiddiqui/github/kustomize-bug/apps/test-app2: is a directory': recursed accumulation of path '/Users/faizsiddiqui/github/kustomize-bug/apps/test-app2': unable to find field "spec.template.spec.containers.[name=main].readinessProbe.httpGet.path" in replacement target
```

### Kustomize version

v5.0.2

### Operating system

MacOS

**Comment by mdfaizsiddiqui** [comment]
> create: true

This suggestion is doing the opposite of what we're looking for, we don't want httpGet to be the part of final output for test-app2. The `create: true` property is populating the httpGet field which we're deleting with this [patch](https://github.com/mdfaizsiddiqui/kustomize-bug/blob/main/apps/test-app2/kustomization.yaml#L20-L26). 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: test-app2
  name: test-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: test-app2
  template:
    metadata:
      labels:
        app: my_service
        service: test-app2
    spec:
      containers:
      - image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/test-app2:cdfeff-123213
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /test-app2
          initialDelaySeconds: 3
          periodSeconds: 4
          tcpSocket:
            port: 8080
        name: main
        readinessProbe:
          httpGet:
            path: /test-app2
          initialDelaySeconds: 3
          periodSeconds: 4
          tcpSocket:
            port: 8080
```
