### ISSUE TITLE
Components are not "evaluated after the resources of the parent"

### ISSUE THREAD

**Issue by Miles-Garnsey** [kubernetes-sigs/kustomize#5172]
### What happened?

As outlined in [this](https://github.com/kubernetes-sigs/kustomize/issues/4099#issuecomment-1470934286) comment, the intention of components was to enable modular transformations which run after all overlays have run. Again per that comment, the API design for components states:

```
A kustomization that is marked as a Component has basically the same capabilities as a normal kustomization. The main distinction is that they are evaluated after the resources of the parent kustomization (overlay or component) have been accumulated, and on top of them.
```

When using replacements in an overlay, the replacements are not run after the parent overlay's transformations. 

For example, if I define a kustomization which calls another kustomization as a remote resource, and that remote resource has components which ensure that namespaces within it remain properly aligned/propagated (to `ValidatingWebhookConfiguration ` annotations and `Certificate` `dnsNames` in our case) then those components will not run after a namespace transformer in the parent.

```
kustomization.yaml
overlay/
├─ kustomization.yaml
base/
├─ kustomization.yaml
├─ service.yaml/
├─ certificate.yaml/
component/
├─ kustomization.yaml
```

In the above structure, if the namespace transformer is in the `overlay` directory everything works fine. But if it is in the parent directory it fails to propagate the namespace to `replacements`.

### What did you expect to happen?

We expected that the replacements we defined in a component would pick up namespace values after their parent overlays had run. Instead, the replacements in our components appear to run prior to the namespace transformation in our overlays.

Why do replacements break the design for components, and how do we adopt replacements given that we can no longer run them after our overlays have completed their namespace transformations?

We have been trying to migrate to replacements for 18 months, and my team is becoming concerned that when the v1 API is deprecated kustomize will no longer be a viable solution for us (since we deploy several related operators into different namespaces on a regular basis).

### How can we reproduce it (as minimally and precisely as possible)?

I'm supplying a gist as there are quite a few files here: https://gist.github.com/Miles-Garnsey/23a909cb6f6acb30268c0a1d62fe11eb

There's also a public repo which may be easier to work with [here](https://github.com/Miles-Garnsey/kustomize-problem).

### Expected output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cass-operator-webhook-service
  namespace: new-namespace
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cass-operator-serving-cert
  namespace: new-namespace
spec:
  dnsNames:
  - new-namespace
```

### Actual output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cass-operator-webhook-service
  namespace: new-namespace
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cass-operator-serving-cert
  namespace: new-namespace
spec:
  dnsNames:
  - cass-operator
```

### Kustomize version

5.0.1

### Operating system

MacOS
