### ISSUE TITLE
Add new built-in transformer for resource-quotas (requests/limits)

### ISSUE THREAD

**Issue by evemorgen** [kubernetes-sigs/kustomize#5173]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

To improve the management of pod resource quotas, I propose adding a new built-in transformer to the `Kustomize` tool. This transformer will simplify the process of setting resource requests and limits for pods within Kubernetes manifests.

Currently, Kustomize supports a multitude of built-in transformers for common use cases including `ReplicaCountTransformer`, `ImageTagTransformer`, etc. Another common use case we often run into is overriding pod resource quotas (requests/limits) - currently done with patching - however, it would be much nicer and make manifests more readable to use a built-in transformer for that.

An example implementation could be:

_kustomization.yaml_
```yaml
...
resourceQuotas:
  - name: some-deployment
     requests:
         memory: 1250Mi
         cpu: 100m
     limits:
         memory: 3000Mi
         cpu: 500m 
```

### Why is this needed?

It would provide a more user-friendly simplified syntax to achieve the common task of setting appropriate resource quotas for pods.

By implementing this transformer, Kustomize users will benefit from a more convenient and streamlined approach to managing pod resource quotas. It will simplify the process of setting requests and limits, especially when dealing with a large number of pods or multiple environments.

### Can you accomplish the motivating task without this feature, and if so, how?

This can be currently done with both inline patch and patch strategic merge.

An example would be:

_kustomization.yaml_
```yaml
...
patchesStrategicMerge:
- patch.yaml
```

_patch.yaml_
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-deployment
spec:
  template:
    spec:
      containers:
        - name: some-deployment
          resources:
            limits:
              memory: 1250Mi
            requests:
              memory: 1250Mi
```

### What other solutions have you considered?

I briefly research if it could be done with existing tools but couldn't find an elegant solution.

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉

Thank you for considering this enhancement proposal. I look forward to hearing your thoughts and collaborating on this feature addition.
