### ISSUE TITLE
Enable calling custom transform with inline data

### ISSUE THREAD

**Issue by aeb-dev** [kubernetes-sigs/kustomize#5176]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Imagine the following scenario:

```
.
├── service
│   ├── deployment.yaml
│   ├── kustomization.yaml
└── transformers
    └── common-annotations-deployment
        ├── annotation-transformer.yaml
        └── kustomization.yaml
```

`service/deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
```

`service/kustomization.yaml`
```yaml
resources:
  - deployment.yaml

transformers:
  - ../transformers/common-annotations-deployment
```

`transformers/common-annotations-deployment/annotation-transformer.yaml`
```yaml
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: not-important-to-example
annotations:
  anno1: val1
  anno2: val2
fieldSpecs:
- path: metadata/annotations
  kind: Deployment
  create: true
```

`transformers/common-annotations-deployment/kustomization.yaml`
```yaml
resources:
  - annotation-transformer.yaml
```

when I run `kustomize build service`
it will yield
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    anno1: val1
    anno2: val2
  name: service
```

So far so good. Now imagine that I want to add `service2`. In order to have separate annotations like the following:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    anno1: val4
    anno2: val8
  name: service
```

I have to patch transformer and if I want to to this for every other service this creates unnecessary boilerplate code. Instead of doing this can we call transformer like the following inside `service/kustomization.yaml`

`service/kustomization.yaml`
```yaml
resources:
  - deployment.yaml

transformers:
  - path: ../transformers/common-annotations-deployment
    annotations:
      anno1: val1
      anno2: val2
```

and in `service2/kustomization.yaml`
```yaml
resources:
  - deployment.yaml

transformers:
  - path: ../transformers/common-annotations-deployment
    annotations:
      anno1: val4
      anno2: val8
```

### Why is this needed?

The features decreases boilerplate files

### Can you accomplish the motivating task without this feature, and if so, how?

Yes, We have to patch transformer for each `service`

### What other solutions have you considered?

None

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉
