### ISSUE TITLE
Kustomize helmCharts valuesInline doesn't replace default valuesFile

### ISSUE THREAD

**Issue by thoraage** [kubernetes-sigs/kustomize#5179]
### What happened?

With kustomization:
```
...
helmGlobals:
  chartHome: ../../../helm-charts

helmCharts:
  - name: da-vault-secret-store
    namespace: vault
    releaseName: da-vault-secret-store
    valuesInline:
      myvalue: "myvalue"
...
```

I get:
```
$ kustomize build --enable-helm infrastructure/vault/test
Error: security; file 'xxxxxxxxxxxxxxxxxxx/da-vault-secret-store/values.yaml' is not in or below 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/infrastructure/vault/test'
```

It seems I would have to make an empty dummy-values-file to point the `valuesFile`-key or turn of load restrictions to make it work. That seems very inelegant.

I tried to remove the `values.yaml`-file from the helm-chart, but that did not solve anything:
```
$ kustomize build --enable-helm infrastructure/vault/test
Error: evalsymlink failure on 'xxxxxxxxxxxxx/helm-charts/da-vault-secret-store/values.yaml' : lstat xxxxxxxxxxxxxxx/helm-charts/da-vault-secret-store/values.yaml: no such file or directory
```

Also it would have been great if this could work without `valuesFile` or `valuesInline`. For example, if the helm-chart didn't depend on any values other than for example namespace (i.e. `.Release.Namespace`).

### What did you expect to happen?

I expected it to only use values from my `valuesInline`-key.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v5.0.1

### Operating system

None
