### ISSUE TITLE
failed to find unique target for patch MutatingWebhookConfiguration.v1.admissionregistration.k8s.io/cert-manager-webhook.[noNs]

### ISSUE THREAD

**Issue by btrepp** [kubernetes-sigs/kustomize#5184]
### What happened?

Kustomize doesn't seem to be able to run patches if the base is from a remote http source.
What is interesting is I had done this before, but with more bases in-between (https://git.sr.ht/~btrepp/infrastructure/tree/main/item/overlays/core/kustomization.yaml)

I suspect maybe the base has transformations (hence the warning), and these are being applied *after* my local transforms somehow?. Where if you have a 'layer of indirection'. The bases get applied first?

Either way it is a very confusing message, Kustomize says it can't patch a resource, that it is producing.

```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Error: no matches for Id MutatingWebhookConfiguration.v1.admissionregistration.k8s.io/cert-manager-webhook.[noNs]; failed to find unique target for patch MutatingWebhookConfiguration.v1.admissionregistration.k8s.io/cert-manager-webhook.[noNs]
```

### What did you expect to happen?

Kustomize produces yaml and patches the webhooks
Eg output includes
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: system/cert-manager-webhook-ca
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.11.0
  name: cert-manager-webhook
```

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/metallb/metallb/config/crd?ref=v0.13.9
- https://github.com/cert-manager/cert-manager/releases/download/v1.12.0-beta.2/cert-manager.crds.yaml

patches:
- path: patch-mutating-webhook.yaml
- path: patch-validating-webhook.yaml
```

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cert-manager-webhook
  annotations:
    cert-manager.io/inject-ca-from-secret: "system/cert-manager-webhook-ca"
```

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cert-manager-webhook
  annotations:
    cert-manager.io/inject-ca-from-secret: "system/cert-manager-webhook-ca"
```

### Expected output

```yaml
....
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: system/cert-manager-webhook-ca
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.11.0
  name: cert-manager-webhook
```

### Actual output

Error

or if patches are uncommented

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: v1.11.0
  name: cert-manager-webhook

```

### Kustomize version

kustomize version v5.0.3

### Operating system

MacOS
