### ISSUE TITLE
Kustomize Kustomization object (e.g. patch)

### ISSUE THREAD

**Issue by thomaschaaf** [kubernetes-sigs/kustomize#5185]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I would like to override the `additionalValuesFiles` in a helmChart dependant on the overlay. Using a patch I wanted to do the following but it did not work:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: aws-node-termination-handler
    version: 0.21.0
    repo: https://aws.github.io/eks-charts
    releaseName: aws-node-termination-handler
    namespace: aws-node-termination-handler
    valuesFile: ./helm-values.yaml
    includeCRDs: true
```

```yaml
kind: Kustomization
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1

patches:
  - patch: |-
      - op: add
        path: /helmCharts/0
        value:
          additionalValuesFiles:
            - ../overlays/stage/helm-values.yaml
    target:
      kind: Kustomization

```

### Why is this needed?

This would allow kustomizing helm charts on an overlay level.

### Can you accomplish the motivating task without this feature, and if so, how?

I am not aware of a way.

### What other solutions have you considered?

I have checked different issues related to helm + overlays but not found a solution.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by natasha41575** [comment]
If I understand your issue correctly, you are looking a way to modify the helm chart plugin configuration before it executes.

This is currently possible with kustomize, but it is kind of annoying. I actually wrote up an example of how you can do this in [this repo](https://github.com/natasha41575/kust-examples/tree/main), which you are free to look at for inspiration.

The long term plan for this feature is the [Composition API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2299-kustomize-plugin-composition), but we don't currently have anyone available to work on it and it has several blocking issues.

If anyone reading this is interested in moving Composition forward, please feel free to reach out and I can provide more details.

I'm going to leave this issue open so that others with the same request can find this response.

**Comment by ashutosh887** [comment]
I wanted to work on this @natasha41575

**Comment by bluebrown** [comment]
Technically this be already possible, if you add a metadata.name field to your kustomization. Kustomize is not bound to any particular resource. The only limitation is that the resource has a gvk (group, version, kind) and a metadata.name to derive a unique id, from.

But, you cant do it in one go. So you need to generate the kustomization this way and write it to your target dir, and then run kustomize on that dir.

For example I have a directory with a file `base-kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-me
```

Next to it is a `kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base-kustomization.yaml
patches:
  - target:
      name: kustomize-me
    patch: |
      - op: add
        path: /resources
        value:
          - foo.yaml
          - bar.yaml
```

Now when I run `kustomize build`, I get this 

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-me
resources:
- foo.yaml
- bar.yaml
```

This output could be written to some other directory as kustomization.yaml and the you run kustomize on that dir as usual.  So it's a 2-phase process.

So this isn't super convenient. Depending on what you want to do natashas, suggestion might be better.
