### ISSUE TITLE
Kustomize-generated secrets cause unnecessary patches

### ISSUE THREAD

**Issue by vbezhenar** [kubernetes-sigs/kustomize#5191]
### What happened?

kubectl reports "configured" status and sends PATCH request for secrets which didn't change.

### What did you expect to happen?

kubectl should report "unchanged" status for secrets which didn't change.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
secretGenerator:
  - name: test
    files:
      - test.txt
generatorOptions:
  disableNameSuffixHash: true
```

```txt
# test.txt
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
1234567890
```

### Expected output

```shell
# first run
% k apply -k .
secret/test created

# second run
% k apply -k .
secret/test unchanged
```

### Actual output

```shell
# first run
% k apply -k .
secret/test created

# second run
% k apply -k .
secret/test configured
```

### Kustomize version

kubectl 1.25.10

### Operating system

None
