### ISSUE TITLE
namePrefix behaves unexpectedly in component

### ISSUE THREAD

**Issue by btrepp** [kubernetes-sigs/kustomize#5202]
### What happened?

I was writing a component to add 'Postgres' to a product as that's a potential configuration/component that could run as a microservice.

There is an upstream 'base' Postgres kustomization, so I thought it would be prudent to pull that in.
Using namePrefix, to say it's a microservice pod under this other resource.

This caused double name prefixes in the 'base'

### What did you expect to happen?

Only the component would be namePrefixed, instead it's added to the base.

However, the base has namePrefix already, so it's *doubled* up for items in the base leading to.
`prefix-postgres` - good
`prefix-prefix-postgres` for anything in the base.

What's odd, is if you omit the namePrefix in the component, the base namePrefix is not applied either. So you can either double up prefixing the base, or have no prefix on your sub-component.

The only workaround for now is to manually patch name using merges and json patches. Which is tedious and error prone.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prefix-
resources:
- resources.yaml
```

```yaml
# component/postgres/kustomization.yaml
kind: Component
namePrefix: prefix-
resources:
- ../../some/other/base
```

```yaml
# overlay/kustomization.yaml

kind: Kustomization
resources:
- ../base

components:
- ../components/postgres
```

### Expected output

names are prefix-original name

### Actual output

names of things under component are prefix-resource name.
names of things under base are prefix-prefix-resource name.

### Kustomize version

5.0.3

### Operating system

MacOS
