### ISSUE TITLE
local-only configMap causing `may not add resource with an already registered id` error.

### ISSUE THREAD

**Issue by mleklund** [kubernetes-sigs/kustomize#5226]
### What happened?

Due to the processing order change in #4895 using components with replacements causes errors in 5.0.0+ where it did not in 4.4.x and 4.5.x.

The use case was to include a component to alter dns for blue/green deployment which would allow me to change the dns set-identifier and weight in a single place for all kustomizations that include the component.

### What did you expect to happen?

Create deployment yaml without error.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# deployment/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../ingress1
- ../ingress2
```

```
# ingress1/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
components:
- ../components
```

```yaml
# ingress1/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress1
spec:
  defaultBackend:
    service:
      name: svc1
      port:
        number: 80
```

```
# ingress2/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
components:
- ../components
```

```yaml
# ingress2/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress2
spec:
  defaultBackend:
    service:
      name: svc2
      port:
        number: 80
```

```yaml
# components/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- literals:
  - deployment=blue
  - weight=100
  name: deployment
  options:
    disableNameSuffixHash: true
    annotations:
      config.kubernetes.io/local-config: "true"

replacements:
- source:
    kind: ConfigMap
    name: deployment
    fieldPath: data.deployment
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - metadata.annotations.[external-dns.alpha.kubernetes.io/set-identifier]
    options:
      create: true
- source:
    kind: ConfigMap
    name: deployment
    fieldPath: data.weight
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - metadata.annotations.[external-dns.alpha.kubernetes.io/aws-weight]
    options:
      create: true
```

### Expected output

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: blue
  name: ingress1
spec:
  defaultBackend:
    service:
      name: svc1
      port:
        number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: blue
  name: ingress2
spec:
  defaultBackend:
    service:
      name: svc2
      port:
        number: 80
```

### Actual output

```bash
Error: accumulating resources: accumulation err='accumulating resources from '../ingress2': '/private/tmp/ingress2' must resolve to a file': recursed merging from path '/private/tmp/ingress2': may not add resource with an already registered id: ConfigMap.v1.[noGrp]/deployment.[noNs]
```

### Kustomize version

5.0.1

### Operating system

MacOS
