### ISSUE TITLE
Name change patch propagating to HorizontalPodAutoscaler scaleTargetRef.name

### ISSUE THREAD

**Issue by quantson** [kubernetes-sigs/kustomize#5229]
### What happened?

I'm trying to use service_a, comprised of a deployment and horizontal pod autoscaler as a base to build a second service, service_b.
When I build those two services from a root kustomization file, changes applied in service b undesirably apply to the horizontal pod autoscaler scaleTargetRef.name field of service_a resources

### What did you expect to happen?

I'd expect service_a to stay untouched

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
resources:
  - ./service_a
  - ./service_b
```

```yaml
# service_a/kustomization.yaml
resources:
  - ./deployment.yaml
  - ./autoscaler.yaml
```

```yaml
# service_a/autoscaler.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service_a
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service_a
```

```yaml
# service_a/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_a
```

```yaml
# service_b/kustomization.yaml
resources:
  - ../service_a

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
      name: service_a
    options:
      allowNameChange: true
  - path: autoscaler.patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: service_a
    options:
      allowNameChange: true
```

```yaml
# service_b/deployment.patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_b
```

```yaml
# service_b/autoscaler.patch.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service_b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service_b
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_b
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service_a
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service_a                       <------ Here
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service_b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service_b
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_b
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service_a
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service_b                        <------ Here
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service_b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service_b
```

### Kustomize version

5.0.3

### Operating system

MacOS
