### ISSUE TITLE
Kustomize v5.0.3 panic runtime error

### ISSUE THREAD

**Issue by deep7861** [kubernetes-sigs/kustomize#5230]
### What happened?

Running 'kustomize build .' with v5.0.3 errors out with 'panic: runtime error: index out of range [-1]'
Same file works with kustomize v4.x. 
I'm not using 'patchesStrategiMerge' or 'bases' in the kustomize file and there's no such warning either. 

### What did you expect to happen?

Running 'kustomize build .' should generate YAML manifests

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-services
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.1/cert-manager.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-1
        value: --leader-election-namespace=core-services
    target:
      kind: Deployment
      name: cert-manager-cainjector
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/-1
        value: --dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.core-services,cert-manager-webhook.core-services.svc
    target:
      kind: Deployment
      name: cert-manager-webhook
  - patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from-secret
        value: core-services/cert-manager-webhook-ca
    target:
      kind: MutatingWebhookConfiguration
      name: cert-manager-webhook
  - patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1inject-ca-from-secret
        value: core-services/cert-manager-webhook-ca
    target:
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook



### Expected output

```yaml

```

### Actual output

#kustomize build .
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/evanphx/json-patch.(*partialArray).get(0xc0002f2280, {0xc00075a7a2?, 0xbd6080?})
        /go/pkg/mod/github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:469 +0xc8
github.com/evanphx/json-patch.Patch.replace({0xc0000c8900?, 0x8a6?, 0x900?}, 0xb72720?, 0xc000012ca8?)
        /go/pkg/mod/github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:556 +0x92
github.com/evanphx/json-patch.Patch.ApplyIndent({0xc000ac7600?, 0x1, 0x4}, {0xc0000c8900, 0x8a6, 0x900}, {0x0, 0x0})
        /go/pkg/mod/github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:752 +0x32c
github.com/evanphx/json-patch.Patch.Apply(...)
        /go/pkg/mod/github.com/evanphx/json-patch@v4.11.0+incompatible/patch.go:718
sigs.k8s.io/kustomize/api/filters/patchjson6902.Filter.run({{0xc0003c2c30, 0xc2}, {0xc000ac7600, 0x1, 0x4}}, 0x7f6c711b9258?)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/filters/patchjson6902/patchjson6902.go:59 +0x71
sigs.k8s.io/kustomize/kyaml/yaml.FilterFunc.Filter(0x0?, 0x7f6c9860e108?)
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.14.2/yaml/types.go:127 +0x1f
sigs.k8s.io/kustomize/kyaml/kio.FilterAll.func1({0xc000012b40?, 0x1, 0x1})
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.14.2/kio/kio.go:166 +0x7a
sigs.k8s.io/kustomize/kyaml/kio.FilterFunc.Filter(0xd41c20?, {0xc000012b40?, 0x0?, 0x0?})
        /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.14.2/kio/kio.go:71 +0x2a
sigs.k8s.io/kustomize/api/filters/patchjson6902.Filter.Filter({{0xc0003c2c30, 0xc2}, {0xc000ac7600, 0x1, 0x4}}, {0xc000012b40, 0x1, 0x1})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/filters/patchjson6902/patchjson6902.go:29 +0xe8
sigs.k8s.io/kustomize/api/resource.(*Resource).ApplyFilter(0xc000620870, {0xd41840, 0xc000b9a570})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/resource/resource.go:503 +0x6b
sigs.k8s.io/kustomize/api/internal/builtins.(*PatchTransformerPlugin).transformJson6902(0xc0006209b0, {0xd504c8?, 0xc000011410?}, {0xc00012c000?, 0xc000620910?, 0xc00012ce00?})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/builtins/PatchTransformer.go:116 +0x22c
sigs.k8s.io/kustomize/api/internal/builtins.(*PatchTransformerPlugin).Transform(0xc000011410?, {0xd504c8?, 0xc000011410?})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/builtins/PatchTransformer.go:79 +0x46
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).Transform(0xc000088ff0?, {0xd504c8, 0xc000011410})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/target/multitransformer.go:30 +0x89
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/accumulator/resaccumulator.go:141
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runTransformers(0xc000088ff0, 0xc000228340)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/target/kusttarget.go:334 +0x1c5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc000088ff0, 0xc0002df590?)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/target/kusttarget.go:228 +0x34c
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0x97bae0?)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/target/kusttarget.go:189 +0x105
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc000088ff0)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/target/kusttarget.go:130 +0x5f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/internal/target/kusttarget.go:121
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc00063dd78, {0xd49ba0, 0x1235630}, {0x7ffcbc8ad52f, 0x1})
        /go/pkg/mod/sigs.k8s.io/kustomize/api@v0.13.4/krusty/kustomizer.go:90 +0x33d
sigs.k8s.io/kustomize/kustomize/v5/commands/build.NewCmdBuild.func1(0xc000190c80?, {0xc00017fc20?, 0x1?, 0x1?})
        /workspace/myClone/kustomize/commands/build/build.go:82 +0x1b3
github.com/spf13/cobra.(*Command).execute(0xc000190c80, {0xc00017fbf0, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000190780)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /workspace/myClone/kustomize/main.go:14 +0x1e

### Kustomize version

v5.0.3

### Operating system

Linux
