### ISSUE TITLE
buildMetadata should be invoked as a transformer and honored in base kustomizations

### ISSUE THREAD

**Issue by Manuelraa** [kubernetes-sigs/kustomize#5238]
### What happened?

buildMetadata is not propagated to overlays

### What did you expect to happen?

buildMetadata is propagated to overlays

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
  - managedByLabel
  - originAnnotations

configMapGenerator:
  - name: my-configmap
    literals:
      - key=value
```

```yaml
# overlay/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
```

Then run `kustomize build overlay/`

### Expected output

```yaml
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/origin: |
      configuredIn: ../base/kustomization.yaml
      configuredBy:
        apiVersion: builtin
        kind: ConfigMapGenerator
  labels:
    app.kubernetes.io/managed-by: kustomize-v5.1.0
  name: my-configmap-t757gk2bmf
```

### Actual output

```yaml
apiVersion: v1
data:
  key: value
kind: ConfigMap
metadata:
  name: my-configmap-t757gk2bmf
```

### Kustomize version

5.1.0

### Operating system

Linux
