### ISSUE TITLE
Patch 6902 removal from array takes more than 1 from the target array.

### ISSUE THREAD

**Issue by baens** [kubernetes-sigs/kustomize#524]
I was trying to remove one port from a service and I was getting unexpected behavior. Maybe I am misusing the patch 6902 feature, but this feels like a bug. 

Given the following files:

*kustomization.yaml*
```yaml
resources:
- service.yaml
patchesJson6902:
- target:
    version: v1
    kind: Service
    name: my-test-service
  path: patch.yaml
```

*service.yaml*
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-test-service
spec:
  type: ClusterIP
  ports:
  - name: "port1"
    port: 1001
    targetPort: 1001
    protocol: TCP
  - name: "port2"
    port: 1002
    targetPort: 1002
    protocol: TCP
  - name: "port3"
    port: 1003
    targetPort: 1003
    protocol: TCP
```

*patch.yaml*
```yaml
- op: remove
  path: "/spec/ports/0"
```

Running `kustomize build` I get the following:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-test-service
spec:
  ports:
  - name: port3
    port: 1003
    protocol: TCP
    targetPort: 1003
  type: ClusterIP
```

I was expecting this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-test-service
spec:
  ports:
  - name: "port2"
    port: 1002
    targetPort: 1002
    protocol: TCP
  - name: port3
    port: 1003
    protocol: TCP
    targetPort: 1003
  type: ClusterIP
```

Kustomize version
> Version: {KustomizeVersion:v1.0.8 GitCommit:58492e2d83c59ed63881311f46ad6251f77dabc3 BuildDate:1970-01-01T00:00:00Z GoOs:unknown GoArch:unknown}
