### ISSUE TITLE
`reject` on replacements requires both current and all previous IDs match

### ISSUE THREAD

**Issue by sourgrasses** [kubernetes-sigs/kustomize#5241]
### What happened?

Preventing a replacement from being applied to a potential target that has had its name changed by the prefix/suffix transformer, or I assume any transformer that changes the group, version, kind, name, or namespace and runs before the replacement transformer, requires enough information to select both the current ID and all previous IDs the potential target had.

e.g., 
```yaml
nameSuffix: -dev
...
replacements:
- source:
    ...
    select:
      kind: Deployment
    reject:
    - name: app1-dev
```
will not be enough to prevent the replacement from being applied to any `Deployment` named `app1`, and neither will
```yaml
    reject:
    - name: app1
```
Instead you need
```yaml
    reject:
    - name: app1
    - name: app1-dev
```
to catch both the current ID and the ID before the suffix transformer changed the name.

### What did you expect to happen?

I expected to be able to prevent a replacement from being applied to a target by specifying its name in the `reject` field, since that's enough to pick out a single potential target in this case, and that's enough to include it using the `select` field. I'm not really sure if I _should_ expect that, since #3956 added the option to refer to resources by previous IDs in replacements, but the behavior in `reject` specifically did confuse me before peeking at the source, since the negation changes the significance of having current and previous IDs in that list, sort of. Maybe this shouldn't be considered a bug at all and just needs to be noted in documentation somewhere? Or maybe I'm just confused altogether about how this should be organized?

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# overlay/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev
resources:
- ../../base/

configMapGenerator:
- name: app-config
  literals:
  - name=something-else

replacements:
- source:
    kind: ConfigMap
    name: app-config
    fieldPath: data.name
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.name
    select:
      kind: Deployment
    reject:
    - name: app1-dev
```

```yaml
# base/app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  template:
    spec:
      containers:
      - image: app1:1.0
        name: app
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dev
spec:
  template:
    spec:
      containers:
      - image: app1:1.0
        name: app
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dev
spec:
  template:
    spec:
      containers:
      - image: app1:1.0
        name: something-else
```

### Kustomize version

5.1.0

### Operating system

Linux
