### ISSUE TITLE
Inconsistency in Component Generation with Kustomize

### ISSUE THREAD

**Issue by TerryTsanglv** [kubernetes-sigs/kustomize#5242]
### What happened?

I have been following the example provided in the Kustomize documentation for learning about components. You can find the example at this link: [Kustomize Components Example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md).

However, I noticed that when I execute the command kustomize build overlays/community, only the recaptcha component is generated. On the other hand, if I comment out the line - ../../components/recaptcha in the overlays/community/kustomization.yaml file, it will generate the external_db component instead.

### What did you expect to happen?

When executing the command kustomize build overlays/community, it is expected to generate both the recaptcha and external_db components.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# base/kustomization.yaml
resources:
- deployment.yaml

configMapGenerator:
- name: conf
  literals:
    - main.conf=|
        color=cornflower_blue
        log_level=info

```

```yaml
# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - name: example
        image: example:1.0
        volumeMounts:
        - name: conf
          mountPath: /etc/config
      volumes:
        - name: conf
          configMap:
            name: conf

```

```yaml
#components/external_db/deployment.yaml
- op: add
  path: /spec/template/spec/volumes/0
  value:
    name: dbpass
    secret:
      secretName: dbpass
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    mountPath: /var/run/secrets/db/
    name: dbpass

```

```yaml
#components/external_db/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

secretGenerator:
- name: dbpass
  files:
    - dbpass.txt

patchesStrategicMerge:
  - configmap.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: example
  path: deployment.yaml

```

```yaml
#components/recaptcha/deployment.yaml
- op: add
  path: /spec/template/spec/volumes/0
  value:
    name: recaptcha
    secret:
      secretName: recaptcha
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    mountPath: /var/run/secrets/recaptcha/
    name: recaptcha

```

```yaml
#components/recaptcha/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
- name: recaptcha
  files:
    - site_key.txt
    - secret_key.txt

# Updating the ConfigMap works with generators as well.
configMapGenerator:
- name: conf
  behavior: merge
  literals:
    - recaptcha.conf=|
        enabled=true
        site_key=/var/run/secrets/recaptcha/site_key.txt
        secret_key=/var/run/secrets/recaptcha/secret_key.txt

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: example
  path: deployment.yaml

```

```yaml
#overlays/community/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/external_db
  - ../../components/recaptcha

```

### Expected output

```yaml

apiVersion: v1
data:
  db.conf: |
    endpoint=127.0.0.1:1234
    name=app
    user=admin
    pass=/var/run/secrets/db/dbpass.txt
  main.conf: '| color=cornflower_blue log_level=info'
kind: ConfigMap
metadata:
  name: conf-9mt242bkfk
---
apiVersion: v1
data:
  dbpass.txt: ""
kind: Secret
metadata:
  name: dbpass-md6884c6m6
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /var/run/secrets/db/
          name: dbpass
        - mountPath: /etc/config
          name: conf
      volumes:
      - name: dbpass
        secret:
          secretName: dbpass-md6884c6m6
      - configMap:
          name: conf-9mt242bkfk
        name: conf
---
apiVersion: v1
data:
  db.conf: |
    endpoint=127.0.0.1:1234
    name=app
    user=admin
    pass=/var/run/secrets/db/dbpass.txt
  main.conf: '| color=cornflower_blue log_level=info'
  recaptcha.conf: '| enabled=true site_key=/var/run/secrets/recaptcha/site_key.txt
    secret_key=/var/run/secrets/recaptcha/secret_key.txt'
kind: ConfigMap
metadata:
  name: conf-g6cf8tfc4b
---
apiVersion: v1
data:
  dbpass.txt: ""
kind: Secret
metadata:
  name: dbpass-md6884c6m6
type: Opaque
---
apiVersion: v1
data:
  secret_key.txt: c2VjcmV0a2V5Cg==
  site_key.txt: c2l0ZWtleQo=
kind: Secret
metadata:
  name: recaptcha-448gm78m9c
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /var/run/secrets/recaptcha/
          name: recaptcha
        - mountPath: /var/run/secrets/db/
          name: dbpass
        - mountPath: /etc/config
          name: conf
      volumes:
      - name: recaptcha
        secret:
          secretName: recaptcha-448gm78m9c
      - name: dbpass
        secret:
          secretName: dbpass-md6884c6m6
      - configMap:
          name: conf-g6cf8tfc4b
        name: conf


```

### Actual output

```yaml
apiVersion: v1
data:
  db.conf: |
    endpoint=127.0.0.1:1234
    name=app
    user=admin
    pass=/var/run/secrets/db/dbpass.txt
  main.conf: '| color=cornflower_blue log_level=info'
  recaptcha.conf: '| enabled=true site_key=/var/run/secrets/recaptcha/site_key.txt
    secret_key=/var/run/secrets/recaptcha/secret_key.txt'
kind: ConfigMap
metadata:
  name: conf-g6cf8tfc4b
---
apiVersion: v1
data:
  dbpass.txt: ""
kind: Secret
metadata:
  name: dbpass-md6884c6m6
type: Opaque
---
apiVersion: v1
data:
  secret_key.txt: c2VjcmV0a2V5Cg==
  site_key.txt: c2l0ZWtleQo=
kind: Secret
metadata:
  name: recaptcha-448gm78m9c
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /var/run/secrets/recaptcha/
          name: recaptcha
        - mountPath: /var/run/secrets/db/
          name: dbpass
        - mountPath: /etc/config
          name: conf
      volumes:
      - name: recaptcha
        secret:
          secretName: recaptcha-448gm78m9c
      - name: dbpass
        secret:
          secretName: dbpass-md6884c6m6
      - configMap:
          name: conf-g6cf8tfc4b
        name: conf

```

### Kustomize version

V5.1.0

### Operating system

Linux

**Comment by natasha41575** [comment]
/assign @laxmikantbpandhare for further investigation

We recently changed the order of component execution (see the release note [here](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.1.0)), you might want to take a look to see if it's related.

**Comment by annasong20** [comment]
Hi @TerryTsanglv, I tried to reproduce your issue and got the output below

```
apiVersion: v1
data:
  db.conf: |
    endpoint=127.0.0.1:1234
    name=app
    user=admin
    pass=/var/run/secrets/db/dbpass.txt
  main.conf: '| color=cornflower_blue log_level=info'
  recaptcha.conf: '| enabled=true site_key=/var/run/secrets/recaptcha/site_key.txt
    secret_key=/var/run/secrets/recaptcha/secret_key.txt'
kind: ConfigMap
metadata:
  name: conf-g6cf8tfc4b
---
apiVersion: v1
data:
  dbpass.txt: ZGJwYXNzCg==
kind: Secret
metadata:
  name: dbpass-96786m5764
type: Opaque
---
apiVersion: v1
data:
  secret_key.txt: c2VjcmV0X2tleQo=
  site_key.txt: c2l0ZV9rZXkK
kind: Secret
metadata:
  name: recaptcha-kf6mcmdkm4
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - image: example:1.0
        name: example
        volumeMounts:
        - mountPath: /var/run/secrets/recaptcha/
          name: recaptcha
        - mountPath: /var/run/secrets/db/
          name: dbpass
        - mountPath: /etc/config
          name: conf
      volumes:
      - name: recaptcha
        secret:
          secretName: recaptcha-kf6mcmdkm4
      - name: dbpass
        secret:
          secretName: dbpass-96786m5764
      - configMap:
          name: conf-g6cf8tfc4b
        name: conf
```

From a quick pass, the output looks correct. Can you clarify what is missing? Both the `external_db` and `recaptcha` components seem to have run. It looks like in your description you have an additional `Deployment`. Is this intentional?

As a side note, I'm using the latest version of Kustomize.

/triage needs-information
