### ISSUE TITLE
configMapGenarator merge behaviour only allows for one override, ignores subsequent overrides

### ISSUE THREAD

**Issue by Gekalash** [kubernetes-sigs/kustomize#5250]
### What happened?

configMapGenarator merge behaviour changed between Kustomize v4 and Kustomize v5.
In v4, multiple overrides could be applied to the same value in the configMapGenerator, with the last one applied becoming the final value.
In v5, only the first override is applied, and any subsequent ones are ignored.

### What did you expect to happen?

Expected compatible manifests to produce the same results when rendered with Kustomize v4 and v5.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# base/kustomization.yaml
configMapGenerator:
  - name: literals-configmap
    literals:
      - literal_variable_one=base-value
```

```yaml
# component/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: literals-configmap
    behavior: merge
    literals:
      - literal_variable_one=component-value
      - literal_variable_two=component-value-two
```

```yaml
# overlay/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../component

configMapGenerator:
  - name: literals-configmap
    behavior: merge
    literals:
      - literal_variable_one=overlay-value
      - literal_variable_two=overlay-value-two
```

### Expected output

```yaml
apiVersion: v1
data:
  literal_variable_one: overlay-value
  literal_variable_two: overlay-value-two
kind: ConfigMap
metadata:
  name: literals-configmap-6t592hc2f7
```

### Actual output

```yaml
apiVersion: v1
data:
  literal_variable_one: component-value
  literal_variable_two: component-value-two
kind: ConfigMap
metadata:
  name: literals-configmap-b8d9m4h5k2
```

### Kustomize version

5.1.0

### Operating system

MacOS
