### ISSUE TITLE
Reusing a deployment causes HPA to error

### ISSUE THREAD

**Issue by etherwitch** [kubernetes-sigs/kustomize#5251]
### What happened?

I have a scenario where I need to stand up two pods in the same namespace that are identical except for the addition of a single environment variable. To accomplish this without having two identical deployment manifests, I created a base layer with just one deployment. Then I added two intermediate overlays, one that calls the base deployment manifest without any patches and a second that calls the base deployment manifest but has a json 6902 patch that changes the metadata/name of the deployment.
This works as expected and I am able to generate two nearly identical deployments based on a single manifest.
see: https://github.com/etherwitch/hpa-error/tree/poc

If, however I add a horizontal pod autoscaler (HPA) to the mix, I get an interesting error:
```
~/hpa-error/accumulate $ kustomize build ./
Error: updating name reference in 'spec/scaleTargetRef/name' field of 'HorizontalPodAutoscaler.v2.autoscaling/pod1-scaler.test': considering field 'spec/scaleTargetRef/name' of object HorizontalPodAutoscaler.v2.autoscaling/pod1-scaler.test: found multiple possible referrals: Deployment.v1.apps/testdeploy.test, Deployment.v1.apps/pod2.test

**** Too many possible referral targets to referrer:
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: HorizontalPodAutoscaler,HorizontalPodAutoscaler
    internal.config.kubernetes.io/previousNames: pod1-scaler,pod1-scaler
    internal.config.kubernetes.io/previousNamespaces: test,test
  name: pod1-scaler
  namespace: test
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testdeploy

--- possible referral 0:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Deployment,Deployment,Deployment
    internal.config.kubernetes.io/previousNames: testdeploy,testdeploy,testdeploy
    internal.config.kubernetes.io/previousNamespaces: test,test,test
  name: testdeploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env: []
        image: nginx
        name: testdeploy

--- possible referral 1:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Deployment,Deployment,Deployment,Deployment
    internal.config.kubernetes.io/previousNames: testdeploy,testdeploy,pod2,pod2
    internal.config.kubernetes.io/previousNamespaces: test,test,test,test
  name: pod2
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: TRANSMOGRIPHY
          value: "true"
        image: nginx
        name: testdeploy
```
The most notable part of the above error is
```
HorizontalPodAutoscaler.v2.autoscaling/pod1-scaler.test: found multiple possible referrals:
Deployment.v1.apps/testdeploy.test, Deployment.v1.apps/pod2.test
```
The scaleTargetRef/name is set to a value that only indicates one of the referral options however the kustomize linter seems to think that there is a conflict.
see: https://github.com/etherwitch/hpa-error/tree/broken

I did discover a fairly simple work-around for my scenario. If you rename the deployment in both intermediary kustomization files, this seems to satisfy the kustomization linter and everything works.
see: https://github.com/etherwitch/hpa-error/tree/workaround

Overall, this is a minor problem with a simple work around. I wanted to document my journey so that others who encounter it can find the work around more easily. Thanks for everything y'all do.

### What did you expect to happen?

see above

### How can we reproduce it (as minimally and precisely as possible)?

see https://github.com/etherwitch/hpa-error/tree/broken

### Expected output

Successful kustomize build

### Actual output

Repeated from error above
```yaml
~/hpa-error/accumulate $ kustomize build ./
Error: updating name reference in 'spec/scaleTargetRef/name' field of 'HorizontalPodAutoscaler.v2.autoscaling/pod1-scaler.test': considering field 'spec/scaleTargetRef/name' of object HorizontalPodAutoscaler.v2.autoscaling/pod1-scaler.test: found multiple possible referrals: Deployment.v1.apps/testdeploy.test, Deployment.v1.apps/pod2.test

**** Too many possible referral targets to referrer:
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: HorizontalPodAutoscaler,HorizontalPodAutoscaler
    internal.config.kubernetes.io/previousNames: pod1-scaler,pod1-scaler
    internal.config.kubernetes.io/previousNamespaces: test,test
  name: pod1-scaler
  namespace: test
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testdeploy

--- possible referral 0:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Deployment,Deployment,Deployment
    internal.config.kubernetes.io/previousNames: testdeploy,testdeploy,testdeploy
    internal.config.kubernetes.io/previousNamespaces: test,test,test
  name: testdeploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env: []
        image: nginx
        name: testdeploy

--- possible referral 1:
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Deployment,Deployment,Deployment,Deployment
    internal.config.kubernetes.io/previousNames: testdeploy,testdeploy,pod2,pod2
    internal.config.kubernetes.io/previousNamespaces: test,test,test,test
  name: pod2
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: TRANSMOGRIPHY
          value: "true"
        image: nginx
        name: testdeploy
```

### Kustomize version

v5.1.0

### Operating system

MacOS

**Comment by natasha41575** [comment]
I think this error is expected. You have this reference in your HPA:

```
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testdeploy
```

Kustomize will try to update all name references if it sees that the original name of the resource has changed to something else. In this case, it appears you have two deployments that started with the same original name of `testdeploy`. You changed one of their names with a patch. The name reference transformer gets confused, because the `scaleTargetRef` here is ambiguous; it could refer to either deployment and it doesn't know which, so it doesn't know whether or not to apply the name transformation here. 

The recommendation that we usually give is that if you are using a common base with multiple overlays, you should change the name of the base resource in every overlay (e.g. with namePrefix or nameSuffix or a patch), and then in your HPA reference or other reference, use the updated name to avoid the ambiguity. 

/kind support

Closing this as expected behavior, please feel free to reopen if you feel this does not answer your question completely.

/close
