### ISSUE TITLE
Replacing array elements not working on multiple elements (patchesStrategicMerge)

### ISSUE THREAD

**Issue by apolo49** [kubernetes-sigs/kustomize#5255]
When replacing multiple array elements, nothing is replaced and instead is giving the default values. (If I am doing this wrong please advise how to fix)

Base.yaml
```yaml
volumes:
- name: x
  csi:
    ...
- name: y
  csi:
    ...
- name: z
  configMap:
    name: ...
```

overlay.yaml
```yaml
volumes:
- name: x
  $patch: replace
  secret:
    ...
- name: y
  $patch: replace
  secret:
    ...
```

Expected/desired output:
```yaml
volumes:
- name: x
  secret:
    ...
- name: y
  secret:
    ...
- name: z
  ...
```

The output I get is the same as the original. I have the patch set up properly in the kustomization.yaml as the file has worked previously. It is since this addition it has broke. How can I remedy this (preferably with strategicMerge)? What am I doing wrong?

**Comment by annasong20** [comment]
I confirm that I see the same behavior in Kustomize `v5.2.1`. If `$patch: replace` is

* in its own element, Kustomize replaces the entire sequence with the sequence in the patch
  ```
  volumes:
  - name: x
  - name: y
  - $patch: replace
  ```
* in an element with existing fields, Kustomize performs a normal strategic merge of other elements in the sequence
  ```
  volumes:
  - name: x
  - name: y
    $patch: replace
    secret: xxx
  ```

Looks similar to #2037. Can someone with more expertise on patch directives clarify what the correct behavior of `$patch: replace` is? Otherwise, I'd need more time to dig into this issue.

**Comment by annasong20** [comment]
Hi @apolo49, I believe what you describe is expected behavior, according to this [documentation](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#list-of-maps). The `$patch: replace` directive is intended to have its own element in a sequence and replaces all original elements above it in the sequence with all elements in the patch.
We are assuming that your setup is as follows
```
# kustomization.yaml
resources:
- deployment.yaml
patchesStrategicMerge:
- patch.yaml
```
```
# deployment.yaml
...
volumes:
- name: x
  csi:
    ...
- name: y
  csi:
    ...
- name: z
  configMap:
    name: ...
```
```
# patch.yaml
...
volumes:
- name: x
  $patch: replace
  secret:
    ...
- name: y
  $patch: replace
  secret:
    ...
```

You can try using [`patchesJson6902`](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesjson6902/) instead.

FYI that `patchesStrategicMerge` is being deprecated, so please use `patches` instead. I'm using `patchesStrategicMerge` here to demonstrate that `$patch: replace` is `patchesStrategicMerge` functionality, not `patchesJson6902`.

=============================================

We triage accept this as a documentation issue, since our official [documentation](https://kubectl.docs.kubernetes.io/references/kustomize/) does not include `$patch: replace`. Whoever works on this issue should document desired behavior instead of changing code behavior in the repo.

/kind documentation
/kind support
/triage accepted
