### ISSUE TITLE
Kustomize tries to patch images on unknown GVK's

### ISSUE THREAD

**Issue by mgazza** [kubernetes-sigs/kustomize#5257]
### What happened?

When using a CRD which contains a field named images kustomize attempts to unmarshal fields called images to set the image tag

### What did you expect to happen?

Unless told about the field in the config kustomize should ignore it.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml

images:
  - name: foo
    newTag: bar
```

```yaml
# resources.yaml
apiVersion: someapi/v1
kind: examplekind
metadata:
  name: example
spec:
  deployment:
    containers:
      - name: example
        image:
          name: example

```

### Expected output

```yaml
apiVersion: someapi/v1
kind: examplekind
metadata:
  name: example
spec:
  deployment:
    containers:
      - name: example
        image:
          name: example


```

### Actual output

```
Error: wrong node kind: expected ScalarNode but got MappingNode: node contents:
name: example

```

### Kustomize version

v5.1.0

### Operating system

MacOS
