### ISSUE TITLE
Vars using fieldPaths whose components contain dots is not possible

### ISSUE THREAD

**Issue by twz123** [kubernetes-sigs/kustomize#526]
Consider a label that has a key that contains dots, e.g. `app.kubernetes.io/instance` when trying to follow the "[Recommended Labels][rl]" approach. Those labels cannot be used as a var, since there's currently no way of escaping dots in fieldPaths.

A dummy example could look like this:

`deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  template:
    spec:
      containers:
      - name: dummy
        image: gcr.io/google_containers/pause-amd64:3.1
        env:
        - name: INSTANCE
          value: "$(INSTANCE)"
```
`kustomization.yaml`:
```yaml
nameprefix: noop-demo-
resources:
- deployment.yaml
commonLabels:
  app.kubernetes.io/instance: noop-demo
vars:
- name: INSTANCE
  objRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dummy
  fieldRef:
    fieldPath: metadata.labels['app.kubernetes.io/instance'] # obviously, this won't work
```

The error is `Error: failed to resolve referred var: {Name:INSTANCE ObjRef:apps_v1_Deployment FieldRef:{FieldPath:metadata.labels['app.kubernetes.io/instance']}}`.

Would it be possible to add some escape magic to fieldPath? One way would be the "array" notation which I used above. Antoher could be to support escape sequences, e.g. backslashes: `metadata.labels.app\.kubernetes\.io/instance`.

[rl]: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
