### ISSUE TITLE
Kustomize Incorrectly Generates Ingress Rules by Reusing Component Values

### ISSUE THREAD

**Issue by theophileds** [kubernetes-sigs/kustomize#5264]
### What happened?

Recently, we identified an issue with Kustomize where it incorrectly generates templates. Rather than populating templates with the intended values, Kustomize seems to borrow values from other components, leading to Kubernetes errors.

To illustrate, consider the following scenario: The expected output should display two distinct ingress rules, each with its own domain. However, Kustomize is incorrectly assigning the domain from the second ingress rule to the first.

This issue has consistently manifested both in our Continuous Integration environment (running on Ubuntu) and locally on OSX. It has been observed with Kustomize versions 5.0.1 and 5.11.

### What did you expect to happen?

The following command `kustomize build overlays/production` should generate the desired output.

### How can we reproduce it (as minimally and precisely as possible)?

The following structure is
```
├── components
│   ├── test
│   │   ├── kustomization.yaml
│   │   └── test.yaml
│   └── test2
│       ├── kustomization.yaml
│       └── test2.yaml
└── overlays
    └── production
        └── kustomization.yaml
```

```yaml
# components/test/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
    - test.yaml

patches:
    - target:
          kind: Ingress
      patch: |-
          - op: replace
            path: /spec/rules/0/host
            value: test.domain.com
```

```yaml
# components/test/test.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: test
spec:
    ingressClassName: nginx
    rules:
        - host: to-be-replaced
```

```yaml
# components/test2/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
    - test2.yaml

patches:
    - target:
          kind: Ingress
      patch: |-
          - op: replace
            path: /spec/rules/0/host
            value: test2.domain.com
```

```yaml
# components/test2/test2.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: test2
spec:
    ingressClassName: nginx
    rules:
        - host: to-be-replaced
```

```yaml
# overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
    - ../../components/test
    - ../../components/test2
```

### Expected output

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  ingressClassName: nginx
  rules:
  - host: test.domain.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2
spec:
  ingressClassName: nginx
  rules:
  - host: test2.domain.com
```

### Actual output

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  ingressClassName: nginx
  rules:
  - host: test2.domain.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test2
spec:
  ingressClassName: nginx
  rules:
  - host: test2.domain.com
```

### Kustomize version

v5.1.1

### Operating system

MacOS

**Comment by theophileds** [comment]
I've resolved the issue by defining the name parameter under `Kind.` Initially, I assumed that components targeted manifests individually and in isolation. However, it appears that all files are treated as a single manifest.

```yaml
patches:
    - target:
          kind: Ingress
          name: CHANGE_ME
      patch: |-
          - op: replace
            path: /spec/rules/0/host
            value: test2.domain.com
```
