### ISSUE TITLE
nameSuffix not being appended or being ignored for container name

### ISSUE THREAD

**Issue by nmofonseca** [kubernetes-sigs/kustomize#5284]
### What happened?

I am not very knowledgeable in Kustomise but I don't believe I am doing anything incorrectly.

I am trying to use nameSuffix to append a suffix to a deployment manifest names, this works for almost everything but it doesn't seem to be working for the container name.

### What did you expect to happen?

Suffix to be appended on the container name

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: nginx
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/name: nginx
        app.kubernetes.io/component: nginx
    spec:
      serviceAccountName: nginx
      securityContext: {}
      containers:
      - name: nginx
        env: []
        securityContext: {}
        image: nginx-image
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /alive.html
            port: 80
          failureThreshold: 5
          initialDelaySeconds: 120
          periodSeconds: 120
        startupProbe:
          httpGet:
            path: /alive.html
            port: 80
          failureThreshold: 20
          periodSeconds: 30
        volumeMounts: []
        resources:
          limits:
            cpu: 2.0
            memory: 1Gi
          requests:
            cpu: 1.0
            memory: 500m
      volumes: []
      nodeSelector: {}
      affinity: {}
      tolerations: []
      topologySpreadConstraints: []
```

```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Sets the resources we are using
resources:
- deployment.yaml
```

```yaml
# overlay/test/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - name: nginx
        env:
        - name: avariable
          value: myvariablevalues
        image: nginx-image
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /alive.html
            port: 80
          failureThreshold: 5
          initialDelaySeconds: 120
          periodSeconds: 120
        startupProbe:
          httpGet:
            path: /alive.html
            port: 80
          failureThreshold: 20
          periodSeconds: 30
        volumeMounts: []
        resources:
          limits:
            cpu: 2.0
            memory: 1Gi
          requests:
            cpu: 1.0
            memory: 500m

```

```yaml
# overlay/test/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Overrides the metadata.namespace value
namespace: nginx-test
# Overrides the metadata.name value adding the suffix
nameSuffix: -test
# Labels we want to set for all resources
commonLabels:
  app.kubernetes.io/name: nginx-test
  app.kubernetes.io/instance: nginx-test
  env: test
# override the pod image (replaces images currently set to epa-nginx-image)
images:
- name: nginx-image
  newName: mydebiannginx
  newTag: 0.1.7
# Any resources we want built before this
resources:
- ../../base
patches:
- path: deployment.yaml
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx-test
    app.kubernetes.io/name: nginx-test
    env: test
  name: nginx-test
  namespace: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-test
      app.kubernetes.io/name: nginx-test
      env: test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx-test
        app.kubernetes.io/name: nginx-test
        env: test
    spec:
      affinity: {}
      containers:
      - env:
        - name: avariable
          value: myvariablevalues
        image: mydebiannginx:0.1.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /alive.html
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 120
        name: nginx-test
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 1
            memory: 500m
        securityContext: {}
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /alive.html
            port: 80
          periodSeconds: 30
        volumeMounts: []
      nodeSelector: {}
      securityContext: {}
      serviceAccountName: nginx
      tolerations: []
      topologySpreadConstraints: []
      volumes: []
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx-test
    app.kubernetes.io/name: nginx-test
    env: test
  name: nginx-test
  namespace: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-test
      app.kubernetes.io/name: nginx-test
      env: test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx-test
        app.kubernetes.io/name: nginx-test
        env: test
    spec:
      affinity: {}
      containers:
      - env:
        - name: avariable
          value: myvariablevalues
        image: mydebiannginx:0.1.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /alive.html
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 120
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 1
            memory: 500m
        securityContext: {}
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /alive.html
            port: 80
          periodSeconds: 30
        volumeMounts: []
      nodeSelector: {}
      securityContext: {}
      serviceAccountName: nginx
      tolerations: []
      topologySpreadConstraints: []
      volumes: []
```

### Kustomize version

Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

### Operating system

Linux
