### ISSUE TITLE
getting error for resource mapping not found for name no matches for kind "PrefixSuffixTransformer" in version "builtin"

### ISSUE THREAD

**Issue by deeco** [kubernetes-sigs/kustomize#5301]
### What happened?

when trying to install into cluster or use PrefixSuffixTransformer getting error back from k8s 

resource mapping not found for name: "customPrefixer" namespace: "" from "Prefix.yaml": no matches for kind "PrefixSuffixTransformer" in version "builtin"

Kustomize Version: v4.5.7
K8S Server Version: v1.28.0

### What did you expect to happen?

CRD install then install Transformer

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: customPrefixer
prefix: dev-
fieldSpecs:
  - kind: ClusterRole
    path: metadata/name
  - kind: ClusterRoleBinding
    path: metadata/name
```

### Actual output

```yaml

```

### Kustomize version

4.5.7

### Operating system

Linux
