### ISSUE TITLE
`command` and `envCommand` in ConfigMapGenerator

### ISSUE THREAD

**Issue by lswith** [kubernetes-sigs/kustomize#531]
There have been a few occurrences where I have required the ability to dynamically generate certain config values.

I've currently been putting these values into secrets because it has been the only way to generate specific values. It would be nice to call out to commands inside config maps as well.

Examples:
```
configMapGenerator:
  - behavior: merge
    env: configs.env
    name: test

secretGenerator:
  - behavior: merge
    envCommand: sops -d secrets.enc
    name: test
  - name: test-extra
    commands:
      DOMAIN: printf ".%s.example.com" "${DEV_DOMAIN}"
```

The main reason for doing this and not simply manipulating files on disk is because I run these overlays with this command:
```
kustomize build github.com/lswith/example//kube-configs/overlays/dev | kubectl apply -f -
```
