### ISSUE TITLE
Replacements doesn't work with source value of empty map `{}`

### ISSUE THREAD

**Issue by ElSamhaa** [kubernetes-sigs/kustomize#5318]
### What happened?

I'm trying to override a resource key of type map with an empty one. I'm using the `replacements` as they allow asterisk in the field path unlike `patches`; e.g, when I need to apply blindly to all the containers.

### What did you expect to happen?

`spec.template.spec.containers.*.livenessProbe` value to be set to an empty map `{}`.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
resources:
- resources.yaml

replacements:
- source:
    kind: ConfigMap
    name: local-config
    fieldPath: data.empty
  targets:
  - select:
      kind: Deployment
    fieldPaths:
    - spec.template.spec.containers.*.livenessProbe
    options:
      create: false
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  empty: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: alpine
        livenessProbe:
          tcpSocket:
            port: 80
        command: [sleep, infinity]
        name: test
```

### Actual output

```
Error: fieldPath `data.empty` is missing for replacement source ConfigMap.[noVer].[noGrp]/local-config.[noNs]
```

### Kustomize version

v5.1.1

### Operating system

MacOS

**Comment by natasha41575** [comment]
First, I just want to clarify that it doesn't look like your ConfigMap is valid as the `data` field needs to be a map of strings to strings. We would need to correct it to:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-config
  annotations:
    config.kubernetes.io/local-config: "true"
data: {}
```

and likewise change the fieldpath in your replacements from `data.empty` to `data` for it to be valid kubernetes yaml.

That said, when we make those changes, I get the same error that you report and we think that is a valid and real issue.

/triage accepted
