### ISSUE TITLE
Namespaces not added to Resources of Components

### ISSUE THREAD

**Issue by sanmai-NL** [kubernetes-sigs/kustomize#5329]
### What happened?

When using a Base, and perhaps Overlay, the `namespace` field in `kustomization.yml` is applied to all Resources. When adding a Resource from a Component, its `kustomization.yml` has to repeat the `namespace` field.

### What did you expect to happen?

Either `namespace` is inherited, optionally controlled, and/or the behavior is documented.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namepace: test
components:
- ../../components/test
resources:
- resource1.yml
```

```yaml
# base/resource1.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

```yaml
# components/test/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- resource2.yml
```

```yaml
# components/test/resource2.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object2
data:
  placeholder: data2
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v5.1.1

### Operating system

MacOS

**Comment by natasha41575** [comment]
@ncapps Could you please investigate how components work with respect to the ordering of transformers (in this case the namespace transformer) and report back? Ideally we will understand how it works, rationalize it, and then decide whether to change or document the behavior.

Here is a starting point for where to look in the code: https://github.com/kubernetes-sigs/kustomize/blob/ab519fdc13ded9875e42d70ac8a5b1b9023a2dbb/api/internal/target/kusttarget.go#L232

Here is the KEP for the original design of components: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1802-kustomize-components

/assign @ncapps

**Comment by sanmai-NL** [comment]
@ncapps What's the status?

**Comment by shapirus** [comment]
This CI robot is annoying. What's the point of auto-closing tickets?

The issue will not magically disappear if we close our eyes, let the ticket be auto-closed and pretend it never existed.

**Comment by stormqueen1990** [comment]
@sanmai-NL could you please include the expected and actual output of Kustomize for your replication scenario in the description of this issue?

I tried it locally with the same structure you described and got the following result with Kustomize v5.6.0:
```yaml
apiVersion: v1
data:
  placeholder: data
kind: ConfigMap
metadata:
  name: test-object
  namespace: test
---
apiVersion: v1
data:
  placeholder: data2
kind: ConfigMap
metadata:
  name: test-object2
  namespace: test
```

Per your description, this looks like what you were trying to achieve.
