### ISSUE TITLE
ConfigMap delared by configmapgenerator not being consumed by ECK created elasticsearch cluster

### ISSUE THREAD

**Issue by malexander2012** [kubernetes-sigs/kustomize#5335]
### What happened?

When i create a configmap using the configmapgenerator the configmap that is created is not consumed by the ECK created elasticsearch (ES) cluster. 

### What did you expect to happen?

I'm expecting the ES cluster to use the configmap I created via the configmap generator to be consumed.

### How can we reproduce it (as minimally and precisely as possible)?

create the following files then paste in the contents from the files below. Go within the Cattle-Cluster directory then run `kustomize build mongoose`:
```
cattle-cluster/
    base/
       es_cluster.yaml
       kustomization.yaml
    mongoose/
       kustomization.yaml       
```

 ```yaml  
# base/es_cluster.yaml 

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
 name: eck-poc-multitenant
 namespace: default
 annotations:
   eck.k8s.elastic.co/downward-node-labels: "topology.kubernetes.io/zone"
 labels:
   kubernetes.seismic.com/team: team
   kubernetes.seismic.com/role: role
spec:
 version: 8.8.1
 revisionHistoryLimit: 2
 nodeSets:
 - name: master
   count: 3
   config:
     node.roles: [ "master" ]
   podTemplate:
     spec:
       initContainers:
         - name: sysctl
           securityContext:
             privileged: true
             runAsUser: 0
           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
       containers:
         - name: elasticsearch
           resources:
             limits:
               memory: 4Gi
               cpu: 1000m
             requests:
               memory: 4Gi
               cpu: 1000m
           envFrom:
           - configMapRef:
               name: mongoose-eck-poc-multitenant-master
           securityContext:
             readOnlyRootFilesystem: true
             allowPrivilegeEscalation: false
             privileged: false
           readinessProbe:
             exec:
               command: ["bash", "-c", "/mnt/elastic-internal/scripts/readiness-probe-script.sh"]
             failureThreshold: 3
             initialDelaySeconds: 10
             periodSeconds: 12
             successThreshold: 1
             timeoutSeconds: 12
           livenessProbe:
             exec:
               command: ["bash", "-c", "/mnt/elastic-internal/scripts/readiness-probe-script.sh"]
             failureThreshold: 3
             initialDelaySeconds: 10
             periodSeconds: 12
             successThreshold: 1
             timeoutSeconds: 12
           volumeMounts:
             - mountPath: /tmp
               name: tmp-volume
       volumes:
         - name: tmp-volume
           emptyDir: {}
       affinity:
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: elasticsearch.k8s.elastic.co/cluster-name
                   operator: In
                   values:
                   - eck-poc-multitenant
               topologyKey: kubernetes.io/hostname
             weight: 100
           - podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: elasticsearch.k8s.elastic.co/cluster-name
                   operator: In
                   values:
                   - eck-poc-multitenant
               topologyKey: topology.kubernetes.io/zone
             weight: 90
       securityContext:
         runAsUser: 65534  # these two have to be the same ID
         fsGroup: 65534  # these two have to be the same ID
   volumeClaimTemplates:
   - metadata:
       name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 5Gi
       storageClassName: standard-ssd
 - name: data
   count: 3
   config:
     node.roles: [ "data" ]
   podTemplate:
     spec:
       initContainers:
         - name: sysctl
           securityContext:
             privileged: true
             runAsUser: 0
           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
       containers:
         - name: elasticsearch
           resources:
             limits:
               memory: 4Gi
               cpu: 1000m
             requests:
               memory: 4Gi
               cpu: 1000m
           envFrom:
           - configMapRef:
               name: mongoose-eck-poc-multitenant-data
           securityContext:
             readOnlyRootFilesystem: true
             allowPrivilegeEscalation: false
             privileged: false
           readinessProbe:
             exec:
               command: ["bash", "-c", "/mnt/elastic-internal/scripts/readiness-probe-script.sh"]
             failureThreshold: 3
             initialDelaySeconds: 10
             periodSeconds: 12
             successThreshold: 1
             timeoutSeconds: 12
           livenessProbe:
             exec:
               command: ["bash", "-c", "/mnt/elastic-internal/scripts/readiness-probe-script.sh"]
             failureThreshold: 3
             initialDelaySeconds: 10
             periodSeconds: 12
             successThreshold: 1
             timeoutSeconds: 12
           volumeMounts:
             - mountPath: /tmp
               name: tmp-volume
       volumes:
         - name: tmp-volume
           emptyDir: {}
       affinity:
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: elasticsearch.k8s.elastic.co/cluster-name
                   operator: In
                   values:
                   - eck-poc-multitenant
               topologyKey: kubernetes.io/hostname
             weight: 100
           - podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: elasticsearch.k8s.elastic.co/cluster-name
                   operator: In
                   values:
                   - eck-poc-multitenant
               topologyKey: topology.kubernetes.io/zone
             weight: 90
       securityContext:
         runAsUser: 65534  # these two have to be the same ID
         fsGroup: 65534  # these two have to be the same ID
   volumeClaimTemplates:
     - metadata:
         name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
       spec:
         accessModes:
         - ReadWriteOnce
         resources:
           requests:
             storage: 5Gi
         storageClassName: default
 updateStrategy:
   changeBudget:
     maxSurge: 3
     maxUnavailable: 1
 podDisruptionBudget: {}
 ```
 
 ```yaml
# base/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - es_cluster.yaml
configMapGenerator:
 - name: mongoose-eck-poc-multitenant-master
   literals:
     - ES_JAVA_OPTS="-Xms2g -Xmx2g"
     - READINESS_PROBE_TIMEOUT="10"
 - name: mongoose-eck-poc-multitenant-data
   literals:
     - ES_JAVA_OPTS="-Xms2g -Xmx2g"
     - READINESS_PROBE_TIMEOUT="10"
generatorOptions:
 immutable: false
 disableNameSuffixHash: false
 ```
 
 ```yaml
# mongoose/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../base
configMapGenerator:
- name: mongoose-eck-poc-multitenant-master
  behavior: merge
  literals:
  - ES_JAVA_OPTS="-Xms2g -Xmx2g"
  - READINESS_PROBE_TIMEOUT="15"
  - ES_NAME="mongoose-eck-poc-multitenant"
  namespace: default
- name: mongoose-eck-poc-multitenant-data
  behavior: merge
  literals:
  - ES_JAVA_OPTS="-Xms2g -Xmx2g"
  - READINESS_PROBE_TIMEOUT="15"
  namespace: default
generatorOptions:
 disableNameSuffixHash: false
 immutable: false
replacements:
 - source:
     kind: ConfigMap
     name: mongoose-eck-poc-multitenant-master
     fieldPath: data.ES_NAME
     namespace: default
   targets:
     - select:
         kind: Elasticsearch
         group: elasticsearch.k8s.elastic.co
         version: v1
       fieldPaths:
         - metadata.name
         - spec.nodeSets.0.podTemplate.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution.0.podAffinityTerm.labelSelector.matchExpressions.0.values.0
         - spec.nodeSets.0.podTemplate.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution.1.podAffinityTerm.labelSelector.matchExpressions.0.values.0
         - spec.nodeSets.1.podTemplate.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution.0.podAffinityTerm.labelSelector.matchExpressions.0.values.0
         - spec.nodeSets.1.podTemplate.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution.1.podAffinityTerm.labelSelector.matchExpressions.0.values.0
```
 
 

### Expected output

```yaml
apiVersion: v1
data:
  ES_JAVA_OPTS: -Xms2g -Xmx2g
  READINESS_PROBE_TIMEOUT: "15"
kind: ConfigMap
metadata:
  name: mongoose-eck-poc-multitenant-data-6mdkt58dd5
---
apiVersion: v1
data:
  ES_JAVA_OPTS: -Xms2g -Xmx2g
  ES_NAME: mongoose-eck-poc-multitenant
  READINESS_PROBE_TIMEOUT: "15"
kind: ConfigMap
metadata:
  name: mongoose-eck-poc-multitenant-master-cm8dfk6hmb
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    eck.k8s.elastic.co/downward-node-labels: topology.kubernetes.io/zone
  labels:
    kubernetes.seismic.com/role: role
    kubernetes.seismic.com/team: team
  name: mongoose-eck-poc-multitenant
  namespace: default
spec:
  nodeSets:
  - config:
      node.roles:
      - master
    count: 3
    name: master
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: topology.kubernetes.io/zone
              weight: 90
        containers:
        - envFrom:
          - configMapRef:
              name:  mongoose-eck-poc-multitenant-master-cm8dfk6hmb   # <--
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
        initContainers:
        - command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144
          name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
        securityContext:
          fsGroup: 65534
          runAsUser: 65534
        volumes:
        - emptyDir: {}
          name: tmp-volume
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard-ssd
  - config:
      node.roles:
      - data
    count: 3
    name: data
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: topology.kubernetes.io/zone
              weight: 90
        containers:
        - envFrom:
          - configMapRef:
              name: mongoose-eck-poc-multitenant-data-6mdkt58dd5   # <--
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
        initContainers:
        - command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144
          name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
        securityContext:
          fsGroup: 65534
          runAsUser: 65534
        volumes:
        - emptyDir: {}
          name: tmp-volume
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: default
  podDisruptionBudget: {}
  revisionHistoryLimit: 2
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  version: 8.8.1
```

### Actual output

```yaml
 apiVersion: v1
data:
  ES_JAVA_OPTS: -Xms2g -Xmx2g
  READINESS_PROBE_TIMEOUT: "15"
kind: ConfigMap
metadata:
  name: mongoose-eck-poc-multitenant-data-6mdkt58dd5
---
apiVersion: v1
data:
  ES_JAVA_OPTS: -Xms2g -Xmx2g
  ES_NAME: mongoose-eck-poc-multitenant
  READINESS_PROBE_TIMEOUT: "15"
kind: ConfigMap
metadata:
  name: mongoose-eck-poc-multitenant-master-cm8dfk6hmb
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    eck.k8s.elastic.co/downward-node-labels: topology.kubernetes.io/zone
  labels:
    kubernetes.seismic.com/role: role
    kubernetes.seismic.com/team: team
  name: mongoose-eck-poc-multitenant
  namespace: default
spec:
  nodeSets:
  - config:
      node.roles:
      - master
    count: 3
    name: master
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: topology.kubernetes.io/zone
              weight: 90
        containers:
        - envFrom:
          - configMapRef:
              name: mongoose-eck-poc-multitenant-master
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
        initContainers:
        - command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144
          name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
        securityContext:
          fsGroup: 65534
          runAsUser: 65534
        volumes:
        - emptyDir: {}
          name: tmp-volume
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard-ssd
  - config:
      node.roles:
      - data
    count: 3
    name: data
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - mongoose-eck-poc-multitenant
                topologyKey: topology.kubernetes.io/zone
              weight: 90
        containers:
        - envFrom:
          - configMapRef:
              name: mongoose-eck-poc-multitenant-data
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
        initContainers:
        - command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144
          name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
        securityContext:
          fsGroup: 65534
          runAsUser: 65534
        volumes:
        - emptyDir: {}
          name: tmp-volume
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: default
  podDisruptionBudget: {}
  revisionHistoryLimit: 2
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  version: 8.8.1
```

### Kustomize version

5.1.1

### Operating system

MacOS
