### ISSUE TITLE
kustomize build fails when resources key is missing

### ISSUE THREAD

**Issue by ckeeney** [kubernetes-sigs/kustomize#5337]
### What happened?

On v5.0, `kustomize build` would build the empty kustomization below .

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
```

On 5.1.1, `kustomize build` would fail with confusing error message:
```
Error: accumulating resources: 
accumulation err='accumulating resources from '../../base': '....../packages/namespaces/base' must resolve to a file': 
couldn't make target for path '...../packages/namespaces/base': kustomization.yaml is empty
```

### What did you expect to happen?

I expected 5.1.1 to build the kustomization without errors.

A simple workaround is to define a `resources` key with an empty array as the value.

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
```

### How can we reproduce it (as minimally and precisely as possible)?

Run `kustomize build` on v5.1.1 on the manifest

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
```

### Kustomize version

5.1.1

### Operating system

Linux
