### ISSUE TITLE
`replacements` changes string to scientific notation float

### ISSUE THREAD

**Issue by ozooxo** [kubernetes-sigs/kustomize#5338]
### What happened?

I have a `replacements` in my Kustomize setup, to retrieve image version from `Deployment` and patched it to a metadata label. However, Kustomize changes my version `20230921.12345678` to a scientific notation of `2.023092112345678e+07`.

https://github.com/ozooxo/kustomize-replacements-potential-bug is the code to reproduce it.
![Screenshot 2023-09-21 at 7 40 14 PM](https://github.com/kubernetes-sigs/kustomize/assets/4197959/100520bd-e793-4c52-a7c2-3de78387159a)

### What did you expect to happen?

We should expect 
```
app.kubernetes.io/version: 20230921.12345678
```
instead of
```
app.kubernetes.io/version: 2.023092112345678e+07
```

### How can we reproduce it (as minimally and precisely as possible)?

```bash
git clone git@github.com:ozooxo/kustomize-replacements-potential-bug.git
cd kustomize-replacements-potential-bug
kustomize build --enable-helm '--load-restrictor=LoadRestrictionsNone' .
```

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: FOOBAR
  name: app
spec:
  template:
    spec:
      containers:
      - image: foobar:20230921.12345678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/version: 20230921.12345678
  name: ingress
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: FOOBAR
  name: app
spec:
  template:
    spec:
      containers:
      - image: foobar:20230921.12345678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/version: 2.023092112345678e+07
  name: ingress
```

### Kustomize version

4.5.5

### Operating system

MacOS

**Comment by DiptoChakrabarty** [comment]
checked up on this and it seems to deliver this issue on certain ranges of integer tags

for such cases it does not work
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: FOOBAR
  name: app
spec:
  template:
    spec:
      containers:
      - image: foobar:10.129091212
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/version: 10.129091212
  name: ingress
```

cases similar to below it displays the issue
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: FOOBAR
  name: app
spec:
  template:
    spec:
      containers:
      - image: foobar:1012313123.129091212
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/version: 1.0123131231290913e+09
  name: ingress
```

for string based values it does not show the issue 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: FOOBAR
  name: app
spec:
  template:
    spec:
      containers:
      - image: foobar:appdev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/version: appdev
  name: ingress
```
