### ISSUE TITLE
Typo in example kustomization.yaml in README file

### ISSUE THREAD

**Issue by paololazzari** [kubernetes-sigs/kustomize#5362]
### What happened?

The example `kustomization.yaml` file shown in the README is:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
.commonLabels:
  app: myapp
resources:
  - deployment.yaml
configMapGenerator:
  - name: myapp-map
    literals:
      - KEY=value
```

so there's a typo in `.commonLabels`, which should instead be `commonLabels`.
