### ISSUE TITLE
kustomize edit add configmap does not support specifying namespace

### ISSUE THREAD

**Issue by stormqueen1990** [kubernetes-sigs/kustomize#5366]
### What happened?

When trying to create a `configMapGenerator` via `kustomize edit add configmap`, it is not possible to specify a namespace for that resource. Running the following command:
```shell
kustomize edit add configmap test-cm --namespace test-ns --from-literal=testkey=testvalue
```

will output
```console
Error: unknown flag: --namespace
```

However, editing the kustomization file to add a namespace, like so:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- literals:
  - testkey=testvalue
  name: test-cm
  namespace: test-ns
```

then running `kustomize build` results in a ConfigMap configuration containing a namespace:
```shell
kustomize build .
```

```yaml
apiVersion: v1
data:
  testkey: testvalue
kind: ConfigMap
metadata:
  name: test-cm-bgk86k8k5t
  namespace: test-ns
```

### What did you expect to happen?

A namespace gets added to the `configMapGenerator`.

### How can we reproduce it (as minimally and precisely as possible)?

Just running

```shell
kustomize edit add configmap test-cm --namespace test-ns --from-literal=testkey=testvalue
```

will demonstrate the issue.

### Expected output

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- literals:
  - testkey=test-value
  name: test-cm
  namespace: test-ns
```

### Actual output

```console
Error: unknown flag: --namespace
```

### Kustomize version

v5.1.1

### Operating system

MacOS
