### ISSUE TITLE
KRM functions are behaving differently for exec and container functions

### ISSUE THREAD

**Issue by xvzf** [kubernetes-sigs/kustomize#5371]
### What happened?

The -e ENV_VAR=VALUE flag is exposed to container KRM functions as an environment variable, while it is dropped for exec-based functions.

### What did you expect to happen?

Container and Exec KRM functions behave the same

### How can we reproduce it (as minimally and precisely as possible)?

Here's a repository with the full configuration and example commands to replicate this: https://github.com/xvzf/kustomize-krm-script-example

### Expected output

See repo above

### Actual output

See repo above

### Kustomize version

5.1.1

### Operating system

None

**Comment by xvzf** [comment]
This issue would be addressed by https://github.com/kubernetes-sigs/kustomize/pull/5316

Ping @koba1t

**Comment by koba1t** [comment]
Thanks @xvzf!
I'll check the details.

**Comment by xvzf** [comment]
@varshaprasad96 can you consider re-opening my PR? Happy to work on it :) 
https://github.com/kubernetes-sigs/kustomize/pull/5316

**Comment by varshaprasad96** [comment]
Hello @xvzf, I was investigating this feature to check if there will ever be a scenario where the env var and input argument (through the annotation) be the same. In this case, looks like any argument cannot be passed from the annotation itself because of an implementation detail. To elaborate what I mean:

Consider the scenario where generator looks like:
```
apiVersion: myDevOpsTeam
kind: SillyConfigMapGenerator
metadata:
  name: whatever
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: ./plugins/silly-generator.sh --test=<something>
spec:
  altGreeting: Bienvenue
  enableRisky: true
```

In this case, kustomize build will error with: `Error: couldn't execute function: fork/exec ./plugins/silly-generator.sh --test: no such file or directory`. Looks like the annotation value is directly passed as is, in the filter path (https://github.com/kubernetes-sigs/kustomize/blob/0122aa82ef953436d0709365d55f0301e838489b/kyaml/runfn/runfn.go#L211) instead of breaking into args, to be executed here: https://github.com/kubernetes-sigs/kustomize/blob/0122aa82ef953436d0709365d55f0301e838489b/kyaml/fn/runtime/exec/exec.go#L37. Given this, I believe it would be safe to make the behaviour same for containerized and exec based KRM functions.  

Thanks for working on the PR. I don't have permissions to re-open it. Probably @natasha41575 / @koba1t can? If not, you can open a new one and reference the issue.
