### ISSUE TITLE
patches not working like patchesStrategicMerge when deleting manifests

### ISSUE THREAD

**Issue by mtrin** [kubernetes-sigs/kustomize#5373]
### What happened?

```
patches:
  - |-
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: foo
      namespace: bar
    $patch: delete
```
Gives
> Error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch

```
patchesStrategicMerge:
  - |-
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: foo
      namespace: bar
    $patch: delete
```
it works with the warning
> Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically

### What did you expect to happen?

`patches` to behave like `patchesStrategicMerge` 

### How can we reproduce it (as minimally and precisely as possible)?

as above

### Kustomize version

v5.1.1

### Operating system

Linux
