### ISSUE TITLE
Documented wildcard matching for replacement is broken

### ISSUE THREAD

**Issue by macetw** [kubernetes-sigs/kustomize#5375]
### What happened?

I am using a glob pattern on my ServiceMonitor endpoints (a prometheus-operator construct) and I cannot defined the port 8080 to all of them -- and I have tons of them. I want to be able to apply the port number (and relabelings, actually) to all of them, but the replacements construct, as documented in docs, is not working.

Here's my example, not using a ServiceMonitor, but just a plain-old Pod with environment variables.

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mynamespace
resources:
  - podexample.yaml
configMapGenerator:
  - name: example
    literals:
      - username=macetw
replacements:
  - source:
      kind: ConfigMap
      name: example
      fieldPath: data.username
    targets:
      - select:
          kind: Pod
          name: mypod
        fieldPaths:
          - spec.containers.[name=mycontainer].env.*.value
        options:
          create: true
```

podexample.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: mynamespace
spec:
  containers:
    - name: mycontainer
      image: docker.io/alpine:latest
      command:
        - sleep
        - inf
      env:
        - name: VARIABLE1
        - name: VARIABLE2
```

And my result:
```
$ kubectl apply -k . --dry-run -o yaml
W1011 14:14:54.782699  640700 helpers.go:660] --dry-run is deprecated and can be replaced with --dry-run=client.
error: wrong Node Kind for spec.containers.env expected: MappingNode was SequenceNode: value: {- name: USER_NAME
```

I am using version 4.5.4. This feature is included in that release.

https://github.com/kubernetes-sigs/kustomize/pull/4424

This is from the docs, here:
https://github.com/kubernetes-sigs/cli-experimental/blob/master/site/content/en/references/kustomize/kustomization/replacements/_index.md#index

Docs say:
> This will target every element in the list.

... but it does not work this way.

### What did you expect to happen?

I want the `value` field rendered in every entry of the list of `env` with the given replacement value defined. In this case, with `options: { create: true} `, I want those fields created.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podexample.yaml
configMapGenerator:
  - name: example
    literals:
      - username=macetw
replacements:
  - source:
      kind: ConfigMap
      name: example
      fieldPath: data.username
    targets:
      - select:
          kind: Pod
          name: mypod
        fieldPaths:
            - spec.containers.[name=mycontainer].env.*.value
        options:
          create: true
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mycontainer
      image: docker.io/alpine:latest
      command:
        - sleep
        - inf
      env:
        - name: VARIABLE1
        - name: VARIABLE2
```

```bash
kubectl apply -k . --dry-run -o yaml
```

### Expected output

```yaml
- apiVersion: v1
  kind: Pod
  metadata:
    name: mypod
  spec:
    containers:
    - command:
      - sleep
      - inf
      env:
      - name: VARIABLE1
        value: macetw
      - name: VARIABLE2
        value: macetw
      image: docker.io/alpine:latest
      name: mycontainer
```

### Actual output

```
$ kubectl apply -k . --dry-run -o yaml
W1011 14:37:46.838210  644735 helpers.go:660] --dry-run is deprecated and can be replaced with --dry-run=client.
error: wrong Node Kind for spec.containers.env expected: MappingNode was SequenceNode: value: {- name: VARIABLE1
- name: VARIABLE2}
$ echo $?
0

```

### Kustomize version

4.5.4

### Operating system

Linux
