### ISSUE TITLE
Question: variable substitution for different environments

### ISSUE THREAD

**Issue by flmmartins** [kubernetes-sigs/kustomize#538]
Hello All,

I am new to Kubernetes and I was looking through the kustomize documentation and I have some doubts if it can solve my issues. I don't want to create multiple yaml files per environment because of small changes through my code.

I have a ingress fie:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: demo.com
    http:
      paths:
......
```

For all my environments this file would be the same except for:
- host: this would change for each environment: demo.com, production.com e etc....
- annotations: the dev version will have this ngnix annotation because of minikube but NOT production, staging and etc....

Can I use kustomize to have the same base file (same rules, ports etc...) but not the same host or annotations? Can someone show me an example?

Best,
