### ISSUE TITLE
labels with includeTemplates get applied to StatefulSet volumeClaimTemplates

### ISSUE THREAD

**Issue by hameno** [kubernetes-sigs/kustomize#5389]
### What happened?

Trying to set datadog version labels on pods of a statefulset using 

```yaml
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      tags.datadoghq.com/version: r1
      app.kubernetes.io/version: r1
```

causes the labels to also be applied to volumeClaimTemplates which cannot be modified after initial creation and thus preventing updates.

### What did you expect to happen?

volumeClaimTemplates should not be modified

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      tags.datadoghq.com/version: r1
      app.kubernetes.io/version: r1
```

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:test
  serviceName: test-headless
  replicas: 3
  template:
    metadata:
      name: test
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
        - name: pod
          image: test:r1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/src/app/data/usercontent
              name: userdata
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: userdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp3
        resources:
          requests:
            storage: 10Gi

```

### Expected output

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  labels:
      tags.datadoghq.com/version: r1
      app.kubernetes.io/version: r1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:test
  serviceName: test-headless
  replicas: 3
  template:
    metadata:
      name: test
      labels:
        app.kubernetes.io/name: test
        tags.datadoghq.com/version: r1
        app.kubernetes.io/version: r1
    spec:
      containers:
        - name: pod
          image: test:r1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/src/app/data/usercontent
              name: userdata
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: userdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp3
        resources:
          requests:
            storage: 10Gi
```

### Actual output

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  labels:
      tags.datadoghq.com/version: r1
      app.kubernetes.io/version: r1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name:test
  serviceName: test-headless
  replicas: 3
  template:
    metadata:
      name: test
      labels:
        app.kubernetes.io/name: test
        tags.datadoghq.com/version: r1
        app.kubernetes.io/version: r1
    spec:
      containers:
        - name: pod
          image: test:r1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/src/app/data/usercontent
              name: userdata
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: userdata
        labels:
          tags.datadoghq.com/version: r1
          app.kubernetes.io/version: r1
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp3
        resources:
          requests:
            storage: 10Gi
```

### Kustomize version

5.1.1

### Operating system

Linux
