### ISSUE TITLE
[helm] new line added in helm outputs

### ISSUE THREAD

**Issue by fengxx** [kubernetes-sigs/kustomize#5428]
### What happened?

`kustomize build --enable-helm . ` generated contents with new line in values and broke yaml format, e.g.

``` yaml
# see sample input in the issue for values.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
stringData:
  key: <aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 1 token |
    base64>
type: Opaque
```

### What did you expect to happen?

sample result as `helm template test-helm --values values.yaml`
```
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  key: "<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 1 token | base64>"
```

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: .
helmCharts:
  - name: test-helm
    valuesFile: values.yaml
```

```yaml
# values.yaml
key: "<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 1 token | base64>"

```

```yaml
# test-helm/templates/test-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  key: {{ .Values.key | quote }}

```

```yaml
# test-helm/Chart.yaml
apiVersion: v1
description: A Helm chart
name: test-helm
version: 1.0.0
appVersion: 0.0.1
```

### Expected output

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  key: "<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 1 token | base64>"
```

### Actual output

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
stringData:
  key: <aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 1 token |
    base64>
type: Opaque
```

### Kustomize version

v5.2.1

### Operating system

Linux

**Comment by ardikabs** [comment]
It seems that this is not a helm error, rather it is the kustomize who did the encoding. You can still get the same result without using `helmCharts`.

```
cat <<EOF > dotenv.example
key=<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 1 token | base64>
EOF

cat <<EOF > kustomization.yaml
configMapGenerator:
  - name: config
    envs:
      - dotenv.example
EOF

kustomize build .
```

Result with:

```yaml
apiVersion: v1
data:
  key: <aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 1 token |
    base64>
kind: ConfigMap
metadata:
  name: config-gmk4f99h25
```
