### ISSUE TITLE
Remove duplicate label behavior: commonLabels vs labels.includeSelectors

### ISSUE THREAD

**Issue by ncapps** [kubernetes-sigs/kustomize#5436]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

The `commonLabels` and `labels` fields with `includeSelectors` enabled produce the same output. It is preferable to have one method to add labels that are propagated to selectors and templates.

The sample kustomization files below would produce the same output.
```yaml
# Add labels with labels and includeSelectors enabled
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      someName: someValue
      owner: alice
      app: bingo
    includeSelectors: true

resources:
- deploy.yaml
- service.yaml
```

```yaml
# Add labels with commonLables
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  someName: someValue
  owner: alice
  app: bingo

resources:
- deploy.yaml
- service.yaml
```

### Why is this needed?

We should remove duplicate behavior where possible to potentially simplify our kustomization API.

### Can you accomplish the motivating task without this feature, and if so, how?

We can produce the same result with either `commonLabels` and `labels` fields.

### What other solutions have you considered?

We can remove duplicate behavior with multiple approaches.

Option 1: Deprecate `commonLabels`
- Deprecate the `commonLabels` field and exclusively use the `labels` field.
- Suggest adding the `annotations` field with an `includeTemplates` option. This would mirror the `labels` field spec.

Option 2: Deprecate `labels`
- Deprecate the `labels` field and add `includeSelectors` and `includeTemplates` options to the `commonLabels` field.
- Suggest adding the `includeTemplates` option to the `commonAnnotations` field.

### Anything else we should know?

This was identified when documenting labels and annotations behavior here: https://github.com/kubernetes-sigs/kustomize/pull/5383

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉
