### ISSUE TITLE
Ability to set create true/false on label

### ISSUE THREAD

**Issue by eduanb** [kubernetes-sigs/kustomize#5445]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

When specifying a label/commonLabel I would like to override whether a specific path should be created.
Seems like [commonLabel might be removed](https://github.com/kubernetes-sigs/kustomize/issues/5436), so makes sense to add it to labels which is already more customizable.

My rough first idea:
```yaml
labels:
  - pairs:
      someName: someValue
    create:
      - path: spec/selector/matchLabels
        kind: PodDisruptionBudget
``` 

### Why is this needed?

I ran into exactly this issue https://github.com/kubernetes-sigs/kustomize/issues/2716
For some reason, the [create is hard-coded to be false for DPB selectors](https://github.com/kubernetes-sigs/kustomize/blob/077c7b2d20bfdb0de78e6873a4ae1ce08afa1c40/api/konfig/builtinpluginconsts/commonlabels.go#L130-L133). 
For my use case, I would like it true, but other users might prefer false. This could be the case for all the labels.
Additionally, if more paths are needed in the future, a user can configure it without Kustomize explicitly adding support. 

### Can you accomplish the motivating task without this feature, and if so, how?

A patch can accomplish it. However, PDBs are fairly small manifests, so a patch is almost the same as recreating the whole manifest over again.

### What other solutions have you considered?

A patch which does work but that makes the overall yaml more when using Kustomize than without it.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by stormqueen1990** [comment]
Hello there, @eduanb! 👋

The built-in transformer `labels` already has a mechanism to override this behaviour for the PodDisruptionBudget resource, through the `fields` option:
```yaml
labels:
  - pairs:
      someName: someValue
    fields:
      - path: spec/selector/matchLabels
        kind: PodDisruptionBudget
        create: true
```

Would you be able to give it a try and confirm whether this works for your use case?
