### ISSUE TITLE
Kustomise build order gives higher priority to ASO ServiceBus Namespace kind above Kubernetes core API Namespace kind

### ISSUE THREAD

**Issue by danielwilsonkainos** [kubernetes-sigs/kustomize#5457]
### What happened?

Azure Service Operator (ASO) allows deployment and maintenance of a wide variety of Azure Resources using CRDs in a K8s native way.

One of the resources supported by ASO is [ServiceBus](https://azure.github.io/azure-service-operator/reference/servicebus/). ServiceBus has the conecept of namespacing for queues and topics and as such one of the sub-resources for setting up a ServiceBus is its [Namespace](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview#namespaces). 

The CRD for ServiceBus Namespace is as below: 

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
```

ServiceBus has its own _GroupValue_ apiVersion however its _Kind_ is **Namespace** which is the same _Kind_ as K8s core Namespace resource.

In the codebase there is the plugin _SortOrderTransformer_ which has a [comparative sort](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/sortordertransformer/SortOrderTransformer.go#L160-166) which finalizes ordering for Kustomization.yaml generated using `kustomise build`. 

This transformer plugin contains [logic to order by _Kind_](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/sortordertransformer/SortOrderTransformer.go#L160-165) and [falls back to a legacy string concatenation of group_value_kind for comparison when resources _Kind_ are the same](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/sortordertransformer/SortOrderTransformer.go#L166). 

In the scenario when there is a core Kubernetes Namespace resource & a ServiceBus Namespace resource the [legacy string concatenation is compared lexicographically](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/sortordertransformer/SortOrderTransformer.go#L160-165). The concatenated strings for each are:

**Kuberentes Namespace:** `~G_v1_namespace`
**ServiceBus Namespace:** `servicebus.azure.com_v1beta20210101preview_namespace`

When SortOrder for Kustomization is left as default (legacy), the lexiographical sort is causing the ServiceBus to placed at the top of the output Kustomization manifest and the core Namespace below (as _~_ has higher unicode value than _s_). This causes failure as there is no Kubernetes namespace to deploy the ServiceBus Namespace into.

### What did you expect to happen?

Core API Namespace should be created first and be placed highest in the Kustomization.yaml output, above ServiceBus

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- core_namespace.yaml
- servicebus_namespace.yaml
```

```yaml
# core_namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
```

```yaml
# servicebus_namespace.yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: test-namespace
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
```

### Expected output

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: test-namespace
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
```

### Actual output

```yaml
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: test-namespace
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
```

### Kustomize version

5.0.3

### Operating system

Other

**Comment by danielwilsonkainos** [comment]
I have opened a PR with one solution to fix this issue - https://github.com/kubernetes-sigs/kustomize/pull/5458

**Comment by natasha41575** [comment]
/assign @ncapps for reproduction and PR review

Thank you for the detailed bug report!

**Comment by ncapps** [comment]
I was able to reproduce this issue.

/triage accepted

**Comment by buzzaII** [comment]
Had the same issue:

https://github.com/kubernetes-sigs/kustomize/issues/5192#issue-1745780171

I worked around this by the following (take note of the Kind):

```
apiVersion: eventhub.azure.com/v1api20211101
kind: NamespaceEH
metadata:
  name: core-eventhub
spec:
  azureName: eventhub
  location: westus
  owner:
    name: core-resourcegroup
  sku:
    name: Standard
    tier: Standard
```

```
apiVersion: servicebus.azure.com/v1api20210101preview
kind: NamespaceSB
metadata:
  name: core-servicebus
spec:
  azureName: servicebus
  location: westus
  owner:
    name: core-resourcegroup
  sku:
    name: Premium
  zoneRedundant: false
  operatorSpec:
    secrets:
      primaryConnectionString:
        name: servicebus-secret
        key: serviceBusConnectionString
```

I then created a Component that fixed the 'kinds':

```
resources:
  - azure-servicebus.yaml
  - azure-eventhub.yaml

components:
  - ../../../../_components/azure
```

```
kind: Component

patches:
  #HACK to fix service bus and eventhub namespace issues
  - patch: |-
      - op: replace
        path: /kind
        value: Namespace
    target:
      group: eventhub.azure.com
      kind: NamespaceEH

  - patch: |-
      - op: replace
        path: /kind
        value: Namespace
    target:
      group: servicebus.azure.com
      kind: NamespaceSB
```

**Comment by danielwilsonkainos** [comment]
@buzzall thank you very much for contributing your work around, we may look to implement similar for the time being

**Comment by ncapps** [comment]
Hi @danielwilsonkainos,

Have you considered using the [sortOptions](https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/sortoptions.go#L7) field?

I found that configuring`order: fifo` with the sortOptions field produces an output where the Namespace resource is above the CRD. Please let me know if this configuration works for your use case.

Below is a Kustomization file that uses the sortOptions field.
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- core_namespace.yaml
- servicebus_namespace.yaml

sortOptions:
  order: fifo 
```

Output:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: aso-namespace
  namespace: test-namespace
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  sku:
    name: Standard
  zoneRedundant: false
```
