### ISSUE TITLE
Reserved Kustomize keyword clashed with helmvalue using Kustomize --enable-helm with HelmChartInflationGenerator (transformed transformers style).

### ISSUE THREAD

**Issue by caspereijkens** [kubernetes-sigs/kustomize#5465]
### What happened?

This helm chart has an `environment` value : https://github.com/minio/minio/blob/master/helm/minio/templates/statefulset.yaml#L178

When using `helm template`, the environment variables are correctly templated in the manifest. When inflating the helm chart with Kustomize, the environment variables are not present.

it looks like `environment` is a reserved variable in Kustomize. When replacing `environment` with `myenvironment` it works.

Is it possible to fix this bug so that helm charts with environment variables are correctly templated?

### What did you expect to happen?

We expected the helm template to achieve the same result as the Kustomize method.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# ./helm/valuesgen.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: just-for-kustomize-matching
name: minio
repo: https://repo
releaseName: myminio
includeCRDs: false
version: 5.0.14
valuesInline:
    environment:
        A: a
  
# ./helm/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - valuesgen.yaml
 
 # ./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

generators:
  - helm
  ```

### Expected output

Statefulset manifest should have a pod with the environment variables.

### Actual output

Statefulset doesn’t have environment variables.

### Kustomize version

4.4

### Operating system

Linux
