### ISSUE TITLE
In `replacements`, the type of source value is not retained when the target fieldPath is not existent an configured with `option.create: true`

### ISSUE THREAD

**Issue by ElSamhaa** [kubernetes-sigs/kustomize#5482]
### What happened?

I'm trying to override an environment variable that might or might not exist in the base. I'm using a local config as a source with the numeric value as a string.

When the base happens to have that overridden environment variable defined, it retains the type right. However, whenever the base is missing the environment variable, the env is created with the numeric value as an integer; not as a string like in the source field.

### What did you expect to happen?

The type of the source value should be retained under all conditions.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  ENV_TEST: "10"
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: alpine
    name: test
```

```yaml
# kustomization.yaml
resources:
- resources.yaml

replacements:
- source:
    kind: ConfigMap
    name: local-config
    fieldPath: data.ENV_TEST
  targets:
  - select:
      kind: Pod
    options:
      create: true
    fieldPaths:
    - spec.containers.[name=test].env.[name=TEST].value
```

### Expected output

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - env:
    - name: TEST
      value: "10"
    image: alpine
    name: test
```

### Actual output

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - env:
    - name: TEST
      value: 10 # the value type is integer; does not match the type in the source (string)
    image: alpine
    name: test
```

### Kustomize version

v5.3.0

### Operating system

MacOS
