### ISSUE TITLE
krusty Ignores Resources with "List" Suffix in Kind Name Without Warning

### ISSUE THREAD

**Issue by EulerLee** [kubernetes-sigs/kustomize#5485]
### What happened?

When using krusty from the Kustomize API, I noticed that it ignores resources whose Kind name ends with "List". For example, resources defined as Kind: AccessWhiteList are not included in the output of krusty. This occurs without any errors or warnings.

### What did you expect to happen?

I expected all resources listed in the kustomization.yaml file to be processed by krusty, regardless of their Kind name. If certain resources are not compatible or cannot be processed, an error or warning should be provided.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a set of YAML files defining custom resources, ensuring some have Kind names ending in "List".
```yaml
# resources.yaml
apiVersion: infra.protonbase.io/v1alpha1
kind: AccessWhiteList
metadata:
  name: wlmls5769f
  namespace: dc7i4hyxzw
spec:
  rules:
  - sourceIps: 0.0.0.0/16
```
2. Add these files to a kustomization.yaml under the resources section.
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources.yaml
```
3. Run krusty to process the directory. dir like:
```
./
├── kustomization.yaml
└── resources.yaml
```
4. Observe that resources with Kind names ending in "List" are not processed.
```go
package main

import (
	"fmt"
	"io/fs"

	securefs "github.com/fluxcd/pkg/kustomize/filesys"
	"sigs.k8s.io/kustomize/api/krusty"
	kustypes "sigs.k8s.io/kustomize/api/types"
)

func main() {
	rootDir := "YOUR_ROOT_DIR"              // for example: /tmp/euler
	subDir := "YOUR_SUB_DIR_UNDER_ROOT_DIR" // for example: /tmp/euler/test

	fst, err := securefs.MakeFsOnDiskSecureBuild(rootDir)
	if err != nil {
		panic(err)
	}

	buildOptions := &krusty.Options{
		LoadRestrictions: kustypes.LoadRestrictionsNone,
		PluginConfig:     kustypes.DisabledPluginConfig(),
	}
	k := krusty.MakeKustomizer(buildOptions)
	m, err := k.Run(fst, subDir)
	if err != nil {
		panic(err)
	}

	fmt.Println("Euler len: ", len(m.Resources()))
	for _, res := range m.Resources() {
		fmt.Printf("euler: resName: %s, resKind: %s, resApiVersion: %s\n", res.GetName(), res.GetKind(), res.GetApiVersion())
	}
}
```

### Expected output

```
Euler len:  1
euler: resName: wlmls5769f, resKind: AccessWhitelist, resApiVersion: infra.protonbase.io/v1alpha1
```
or warning/error

### Actual output

```
Euler len:  0
```

### Kustomize version

sigs.k8s.io/kustomize/api@v0.16.0

### Operating system

None
