### ISSUE TITLE
helmCharts valuesFile does not work when file path contains filepath up (cd ..)

### ISSUE THREAD

**Issue by arkmech** [kubernetes-sigs/kustomize#5494]
### What happened?

File Structure

├── k8s/
|   ├── base/
|   |   ├── helm/
|   |    |    ├── gitops/
|   |    |     |   ├── argo-cd/ (Helm Chart Pulled)
|   |    |     |   ├── base-argo-cd-values.yaml
|   |    |     |   ├── kustomization.yaml
|   ├── dev/
|   |   ├── helm/
|   |    |    ├── gitops/
|   |    |     |   ├── dev-argo-cd-values.yaml
|   |    |     |   ├── kustomization.yaml

`base-argo-cd-values.yaml`
Currently Empty

`k8s/base/helm/gitops/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: argo-cd
helmCharts:
- namespace: gitops-system
  name: gitops
  releaseName: argo-cd
  valuesFile: base-argo-cd-values.yaml
```

`k8s/dev/helm/gitops/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../base/helm/gitops
helmCharts:
- namespace: gitops-system
  name: gitops
  releaseName: argo-cd
  valuesFile: ../../../base/helm/gitops/base-argo-cd-values.yaml
  additionalValuesFiles:
  - kind-argo-cd-values.yaml
```

1) Documentation states `valuesFile` takes a file path, it works for filePaths going down, but does not work when file path contains `..` to go up a directory.

Run:
`kustomize build k8s/dev/helm/gitops --enable-helm`

Error:
1)
```
Error: security; file '/Users/me/project/k8s/base/helm/gitops/base-argo-cd-values.yaml' is not in or below '/Users/me/project/k8s/dev/helm/gitops'
```

2)
```
Error: no repo specified for pull, no chart found at ''
```
I looked at this issue and it doesn't seem fixed: https://github.com/kubernetes-sigs/kustomize/issues/5163

Per docs:
https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_

```
repo: [Optional] The URL of the repository which contains the chart. If this is provided, the generator will try to fetch remote charts. Otherwise it will try to load local chart in chartHome.
```
Even though I don't specify the repo key. Its still trying to pull repo instead of looking at chartHome

Having `base-argo-cd-values.yaml` in a file location without `..` works. For example in the same directory or nested directory

### What did you expect to happen?

kustomize builds successfully.

### How can we reproduce it (as minimally and precisely as possible)?

See file structure and yaml above.

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v5.3.0

### Operating system

MacOS

**Comment by koba1t** [comment]
I think maybe this is a security check that prevents kustomizations from reading files outside their own directory root.
https://kubectl.docs.kubernetes.io/faq/kustomize/#security-file-foo-is-not-in-or-below-bar

Could you try `load-restrictor` option that resolv your problem?

/area helm
/triage need-information

**Comment by max06** [comment]
Since I just had the same issue: Yep, that helps!

**Comment by davquar** [comment]
I have the same issue (specifically output 2) and as OP wrote, it seems to be generally related to #5163.
My chart is local, in another path up in the kustomization's parent.

For this problem `load-restrictor` doesn't help unfortunately.

But an interesting find is that by specifying `chartHome` as an absolute path, it works. Environment variables are not expanded, though

**Comment by alexrecuenco** [comment]
> /triage needs-information

Could this be re-opened?

I think this could be reconsidered, if you wouldn't mind. I am struggling to see if this is currently restricted as a recommendation in general, if using `--load-restrictor=LoadRestrictionsNone` is always recommended, or if there is something else that we are trying to discourage.

Because, to me, `chartHome` would be handled similarly to `resources`/`components`: An external place where we grab resources to inflate/modify. I am not sure I get the restriction of having the LoadRestrictor prevent external access to it.

My example would be the following use. I use a helm chart 

-  in `overlays/dev` the chart is inflated once for a dev app
- in`overlays/test` to inflate the chart a few times for each client (SaSS)
-  in `overlays/prod` to do the same, but without experimental features.

What I want to do is to have a `$ROOT/charts` directory with all the charts I've downloaded and kept.

Then I would have some `base/kustomization.yaml` with other resources

<details>

<summary>Resource descriptions</summary>
```yaml
# overlays/dev/kustomize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources: 
  - ../../base

patches:
 - ...
 
helmGlobals:
  chartHome: ../../charts/
helmCharts:
  - name: ruby-base
    valuesInline:
      resourceName: dev-client-1
      experimental_assets: true

```

```yaml
# overlays/test/kustomize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources: 
  - ../../base

patches:
 - ...

helmGlobals:
  chartHome: ../../charts/
helmCharts:
  - name: ruby-base
    valuesInline:
      resourceName: test-client-1
      experimental_assets: true
  - name: ruby-base
    valuesInline:
      resourceName: test-client-1
      experimental_assets: false

```


And finally, in prod



```yaml
# overlays/production/kustomize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources: 
  - ../../base

patches:
 - ...

helmGlobals:
  chartHome: ../../charts/
helmCharts:
  - name: ruby-base
    valuesInline:
      resourceName: client-1
      experimental_assets: false
  - name: ruby-base
    valuesInline:
      resourceName: client-2
      experimental_assets: false
```

<details>


Of course, `--load-restrictor=LoadRestrictionsNone` would do it, but it feels —as a non-expert user— as if I am disabling something that I shouldn't
