### ISSUE TITLE
namespace transformer ignore "create" option if set to false

### ISSUE THREAD

**Issue by pcarangelo** [kubernetes-sigs/kustomize#5515]
### What happened?

If the option 'create' is set to false, the namespace is still added in the custom resource at the indicated path.

### What did you expect to happen?

I expect the namespace not to be inserted at the path configured as false.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example

resources:
- resources.yaml

configurations:
  - namespace.yaml
```

```yaml
# namespace.yaml
namespace:
  - kind: AnimalPark
    path: spec/gorillaRef/namespace
    create: false
```

```yaml
# resources.yaml
apiVersion: animal/v1
kind: AnimalPark
metadata:
  name: ap
spec:
  gorillaRef:
    name: gg
    kind: Gorilla
    apiVersion: animal/v1
```

### Expected output

```yaml
apiVersion: animal/v1
kind: AnimalPark
metadata:
  name: ap
  namespace: example
spec:
  gorillaRef:
    apiVersion: animal/v1
    kind: Gorilla
    name: gg
```

### Actual output

```yaml
apiVersion: animal/v1
kind: AnimalPark
metadata:
  name: ap
  namespace: example
spec:
  gorillaRef:
    apiVersion: animal/v1
    kind: Gorilla
    name: gg
    namespace: example
```

### Kustomize version

5.3.0

### Operating system

None
