### ISSUE TITLE
Replacements should support an inline value as a source

### ISSUE THREAD

**Issue by grozan** [kubernetes-sigs/kustomize#5516]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

As suggested in other issues, like [here](https://github.com/kubernetes-sigs/kustomize/issues/5063#issuecomment-1470977705), it would be very nice to be able to specify a value directly, inline.
The target value is not always a field of another object. It can simply be a value that the user knows/wants.

### Why is this needed?

There is the workaround of declaring a new object like a configmap and annotating it with `config.kubernetes.io/local-config: "true"`  but this adds extra complexity and bloat to the definition of the desired state IMO

A simple replacement should look something like 

```
replacements:
- source:
    value: bar
  targets:
  - select:
      name: hello
      kind: Job
    fieldPaths:
    - spec.template.spec.containers.[name=hello].env.[name=foo].value
```

without any kind of place holder object to define

### Can you accomplish the motivating task without this feature, and if so, how?

yes, with a "fake" object as mentioned, but it's not an elegant solution at all

### What other solutions have you considered?

json patches, but they don't support defining list items by their name (`"/spec/template/spec/containers/[name=hello]/env/[name=foo].value"` is NOT possible) as mentioned in other issues like #4950

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by koba1t** [comment]
I think it's an interesting feature and that helps write their configuration without temporary configMap.

/triage accepted
/help

**Comment by cunyat** [comment]
Hi there! Currently working on it and got a working solution for the given example. 

Anyway, I have some doubts:
- The value should accept only scalar values or should it allow lists or objects?
- I'm assuming that the `value` field must be given alone, no other selection fields or `fieldPath` can be present.
- This are the docs covering this? https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/docs/Reference/API/Kustomization%20File/replacements.md

In my head makes more sense to add an extra key to the replacement object:
```yaml
replacements:
- value: bar
  targets:
  - select:
      name: hello
      kind: Job
    fieldPaths:
    - spec.template.spec.containers.[name=hello].env.[name=foo].value
```

/assign

**Comment by grozan** [comment]
Hi,
thinking out loud here, but couldn't this also be an opportunity to introduce an easy-to-use mechanism to delete list items ?

jsonpatch does not support paths like `spec.template.spec.containers.[name=hello].env.[name=foo]` for example, unfortunately, so we have to rely on indexes to target a specific entry in a list, which is neither robust to changes, nor self-documenting.

could we imagine a special `sourceValue` value like `null`, or `-`, or something else, to mean "replace it by nothing, aka delete the entry"?

I mean

```yaml
replacements:
- sourceValue: bar
  targets:
  - select:
      name: hello
      kind: Job
    fieldPaths:
    - spec.template.spec.containers.[name=hello].env.[name=foo].value
```
would set the value of the `foo` ENV variable of the `hello` container to `bar`

```yaml
replacements:
- sourceValue: null
  targets:
  - select:
      name: hello
      kind: Job
    fieldPaths:
    - spec.template.spec.containers.[name=hello].env.[name=foo]
```
would remove the `foo` ENV variable from the `hello` container. It's completely gone from the `env` list

**Comment by cunyat** [comment]
Hey @koba1t,  
I issued a PR few months ago, but seems that is not getting reviewed :)
If there is something I can do to get it reviewed please tell me,

**Comment by koba1t** [comment]
> I issued a PR few months ago, but seems that is not getting reviewed :)

I think that it is better to get a review from another maintainer...

**Comment by ErwanDL** [comment]
I deleted my previous comment (asking when this will be merged) upon further reflection. See https://github.com/kubernetes-sigs/kustomize/issues/5063#issuecomment-2348372336 for the rationale.

**Comment by y-nk** [comment]
@grozan since the PR still not merged, could you eventually tell us how you made it work with `config.kubernetes.io/local-config: "true"` ?

**Comment by grozan** [comment]
> @grozan since the PR still not merged, could you eventually tell us how you made it work with `config.kubernetes.io/local-config: "true"` ?

@y-nk  At present, the replacement system works by referencing a source object that contains the value(s) you want. You cannot define the value(s) you want directly (which is the whole point of this feature request). Instead, you need to have those values "copied from" another object (the `fieldPath` property allows you to specify which field of the source object contains the value you want).

The workaround is to define a dummy configmap that contains the value(s) you want, and to use that dummy configmap as the `source` of your replacement. As you do not really want to push that dummy configmap to the cluster, though, you can simply also annotate it with `config.kubernetes.io/local-config: "true"`. Any object with that annotation is removed from the output of `kustomize build`, making it basically disappear from the final result. This allows the dummy configmap to exist only to make the kustomize replacement work.

**Comment by alexrecuenco** [comment]
> `config.kubernetes.io/local-config: "true"`

I wish I had known of that annotation trick before 🥲

**Comment by scott-nance** [comment]
Any ETA on when this will be merged?  This is really useful and will solve more than 1 (or 5) issues I have.  Appreciate all of your hard work!  -S

**Comment by angularsen** [comment]
For anyone else looking how to use temporary configmaps with `replacements`, this is how I got a template for our cron jobs going.

```
- base
  - cronjob-template
    - kustomization.yaml (resources: cronjob-template.yml)
    - cronjob-template.yml
  - my-cronjob1
    - kustomization.yaml (resources: ../cronjob-template, configMapGenerator, replacements, patches, etc.)
  - my-cronjob2
    - kustomization.yaml (resources: ../cronjob-template, configMapGenerator, replacements, patches, etc.)
  - kustomization.yml (resources: [my-cronjob1, my-cronjob2, ..])
- dev
  - kustomization.yml (resource: ../base, configMapGenerator, replacements, patches, etc.)
- prod
  - kustomization.yml (resource: ../base, configMapGenerator, replacements, patches, etc.)
```

**base/my-cronjob1/kustomization.yaml**
```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cronjob-template

configMapGenerator:
  # Cron job config map
  - literals:
      - Foo=bar
    name: my-cronjob1-config
  # Local values for reuse in 'replacements', will not be published
  - literals:
      - Name="my-cronjob1"
    name: replacements-values
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Update name of resource
replacements:
  - source:
      kind: ConfigMap
      name: replacements-values
      fieldPath: data.Name
    targets:
      - select:
          kind: CronJob
          name: cronjob-template
        fieldPaths:
          - metadata.name
          - spec.jobTemplate.spec.template.metadata.labels.app
          - spec.jobTemplate.spec.template.spec.containers.0.name

# Add config map
patches:
  - target:
      kind: CronJob
      name: cronjob-template
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: my-cronjob-config
```

**Comment by alexrecuenco** [comment]
That is cool and all, but you need to know ahead of time where you are doing the replacements, and the shape of the paths you are replacing. 

1. If the replacement needs to be done by segment "-" or "." you need to change the definition
2. If you are replacing multiple and you add a sidecart container in one side, now your definitions no longer work
3. In general, it is as if you wrote some code and instead of saying var A=2, you needed to mention all the places that variable was to be used and *how*... it seems like a scape hatch.

I still have a hard time understanding *why* vars was deprecated in the first place. The only thing that is a bit weird about it is that bug that allows you to use environment variables for var replacements... but once that is removed, I can't see what else is so bad about it, other than gatekeeping usage to require deeper knowledge of fieldspecs and other obscure notations... The notation of varReplacement is so intuitive, I can give it to someone without knowledge about kustomize and they figure it out on a first look.

**Comment by angularsen** [comment]
I'm still fairly new to kustomize, but I too feel simple things like DRY is very complicated to achieve.

Maybe there are issues with this approach, but often I just want to _inherit_ stuff from a base template for APIs, cron jobs etc. and just add/update/remove whatever is unique to the thing I'm publishing.

**Comment by alexrecuenco** [comment]
> I'm still fairly new to kustomize, but I too feel simple things like DRY is very complicated to achieve.
> 
> Maybe there are issues with this approach, but often I just want to _inherit_ stuff from a base template for APIs, cron jobs etc. and just add/update/remove whatever is unique to the thing I'm publishing. 

Components achieve some type of "DRY", but they are non-trivial to understand

Templating through helm-charts helps a ton with being able to stay dry in repetitive **declarative** definitions, but you have to learn an entire templating engine.

Vars helps a lot staying declarative and DRY as well, since you declare how your templates should look, and then variables are replaced at a later stage.

Both helm and vars seem to be frowned upon, but I struggle to see why

**Comment by y-nk** [comment]
> Components 

👀?

**Comment by shapirus** [comment]
This should also support specifying not just scalar strings, but nested data structures too.

Use case example: deactivate specific containers in some environments where they should not be running:

```
replacements:
- source:
    value: [ "sleep", "inf" ]
  targets:
  - fieldPaths:
    - spec.spec.template.spec.containers.[name=rqworker].command
    select:
      kind: Deployment
```
