### ISSUE TITLE
Changing .kind breaks nameReference transformer (at least)

### ISSUE THREAD

**Issue by maxsivkov** [kubernetes-sigs/kustomize#5522]
### What happened?

I'm trying to patch the `kind` field of given `Deployment` to be `StatefulSet`
+ add spec/serviceName
after that I suppose that nameReference transformer will take care of headless service name changes (subsequent `namePrefix`, etc)
but it doesn't happen. 
I suppose that changing `kind` does not change `kind` in internal model and kustomize keeps treating modified reasource as Deployment

### What did you expect to happen?

watch for `kind` change

### How can we reproduce it (as minimally and precisely as possible)?

here we have two folders
`app` - contains deployemnt named `workload` and service named `service`
`app-ss` - transforms deployment to statefulset and creates headless service named `hs`
`kustomization.yaml` in working folder just creates dummy StatefulSet named `statefulset` with serviceName set. In this case nameReference transformer works just fine.

## Current folder
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: app-
resources:
  - app-ss
  - statefulset.yaml
```

```yaml
# statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  replicas: 2
  serviceName: hs
```

## ./app folder

```yaml
# app/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
```

```yaml
# app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
  labels:
    app-type: workload
spec:
  replicas: 2
```

```yaml
# app/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - name: port
      port: 9090
      protocol: TCP
      targetPort: 9090
```

## ./app-ss folder where I want to change kind of the deployment and add headless service

```yaml
# app-ss/kustomization.yaml
resources:
- headless.yaml
- ../app

patches:
- target:
    group: apps
    version: v1
    labelSelector: app-type=workload
  patch: |-
    - op: replace
      path: /kind
      value: StatefulSet
    - op: add
      path: /spec/serviceName
      value: hs
```

```yaml
# app-ss/headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: hs
spec:
  ports:
    - name: port
      port: 9090
      protocol: TCP
      targetPort: 9090

```

### Expected output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: app-hs
spec:
  ports:
  - name: port
    port: 9090
    protocol: TCP
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - name: port
    port: 9090
    protocol: TCP
    targetPort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset
spec:
  replicas: 2
  serviceName: app-hs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app-type: workload
  name: app-workload
spec:
  replicas: 2
  serviceName: app-hs
```

### Actual output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: app-hs
spec:
  ports:
  - name: port
    port: 9090
    protocol: TCP
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - name: port
    port: 9090
    protocol: TCP
    targetPort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset
spec:
  replicas: 2
  serviceName: app-hs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app-type: workload
  name: app-workload
spec:
  replicas: 2
  serviceName: hs
```

### Kustomize version

v5.3.0

### Operating system

Windows

**Comment by koba1t** [comment]
Hi @maxsivkov 

`patches` has an option to be possible to overwrite `kind`. 
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#name-and-kind-changes

Could you try this option to fix your problem?

/triage needs-information

**Comment by maxsivkov** [comment]
> Hi @maxsivkov
> 
> `patches` has an option to be possible to overwrite `kind`. https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/#name-and-kind-changes
> 
> Could you try this option to fix your problem?
> 
> /triage needs-information

Thanks for the response
Yes, later on I found `allowKindChange: true` option myself, but setting this option as  
```yaml
# app-ss/kustomization.yaml
resources:
- headless.yaml
- ../app

patches:
- target:
    group: apps
    version: v1
    labelSelector: app-type=workload
  patch: |-
    - op: replace
      path: /kind
      value: StatefulSet
    - op: add
      path: /spec/serviceName
      value: hs
  options:
    allowKindChange: true
```
Doesn't work either
