### ISSUE TITLE
Labels support for Transformer Configurations

### ISSUE THREAD

**Issue by ciaccotaco** [kubernetes-sigs/kustomize#5527]
### Eschewed features

- [ ] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Currently (as of kustomize 5.3.0), there is no `labels` support for [Transformer Configurations](https://github.com/kubernetes-sigs/kustomize/blob/release-kustomize-v5.3/examples/transformerconfigs/README.md).  It would be beneficial to add support for `labels`, as `commonLabels` is deprecated.

### Why is this needed?

This is needed because
1. `commonLabels` is deprecated
2. The combination of `labels` in the base kustomizationl.yaml file only works with a `commonLabels` transformer configuration when `includeSelectors: true` is configured. If the granularity for not including selectors (or templates) is needed, then there is no support for a `labels` transform configuration.

### Can you accomplish the motivating task without this feature, and if so, how?

There is no way to use custom transformer configurations with `labels` and a combination of `includeSelectors: false`).

### What other solutions have you considered?

The only option is to continue using the `commonLabels` transformer config and `labels` with `includeSelectors: true`

#### Example

An example of what the end user would configure is the following:

###### File Structure

```text
├── kconf
│   └── configurations.yaml
├── kustomization.yaml
└── resources
    └── flinkdeployment.yaml
```

###### Base Kustomization

```yaml
configurations:
  - kconf/configurations.yaml

labels:
  - includeSelectors: false # or true
    includeTemplates: true  # or false
    pairs:
      app: myapp
      contact: username
      department: kustomize
      environment: dv

resources:
  - resources/flinkdeployment.yaml
```

###### Transformer Configuration

```yaml
labels:
  - path: spec/podTemplate/metadata/labels
    create: true
    kind: FlinkDeployment
  - path: spec/jobManager/podTemplate/metadata/labels
    create: true
    kind: FlinkDeployment
  - path: spec/taskManager/podTemplate/metadata/labels
    create: true
    kind: FlinkDeployment
```

###### Resource

```yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  labels: {}
  name: myflinkapp
spec:
  jobManager:
    podTemplate:
      metadata:
        labels: {}
  podTemplate:
    metadata:
      labels: {}
  taskManager:
    podTemplate:
      metadata:
        labels: {}
```

##### Output

```yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  labels:
    app: myapp
    contact: username
    department_name: kustomize
    environment: dv
  name: myflinkapp
spec:
  jobManager:
    podTemplate:
      metadata:
        labels:
          app: myapp
          contact: username
          department_name: kustomize
          environment: dv
  podTemplate:
    metadata:
      labels:
        app: myapp
        contact: username
        department_name: kustomize
        environment: dv
  taskManager:
    podTemplate:
      metadata:
        labels:
          app: myapp
          contact: username
          department_name: kustomize
          environment: dv
```

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by saschaa442** [comment]
Highly interested as well!

**Comment by stormqueen1990** [comment]
Hello there, @ciaccotaco! 👋

The `labels` structure in the Kustomization file can optionally take a list of fields to which you would like to apply the labels. I tested it locally and it appears to cover the use case you described in this issue, but would you please give it a try and confirm whether it works for your use case?

The configuration I tested looks similar to the following:
```yaml
labels:
  - includeSelectors: false # or true
    includeTemplates: true  # or false
    pairs:
      app: myapp
      contact: username
      department: kustomize
      environment: dv
    fields:
      - path: spec/podTemplate/metadata/labels
        create: true
        kind: FlinkDeployment
      - path: spec/jobManager/podTemplate/metadata/labels
        create: true
        kind: FlinkDeployment
      - path: spec/taskManager/podTemplate/metadata/labels
        create: true
        kind: FlinkDeployment

resources:
  - resources/flinkdeployment.yaml
```
