### ISSUE TITLE
Container section gets overrriden when patching CronJob (batch/v1)

### ISSUE THREAD

**Issue by Dazing** [kubernetes-sigs/kustomize#5530]
### What happened?

Container section gets overrriden when patching CronJob (batch/v1) when rendering manifest.

Base contains a minimal definition of a CronJob and patch is adding an environment property to the env section.

```
> kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

### What did you expect to happen?

I expected Kustomize to properly adding a env property without removing/replacing the entire container section of the manifest.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - test-app.yaml

patches:
  - path: test-app-dev.yaml

```

```yaml
# test-app.yaml (base)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-app
  namespace: test-app
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      containers:
        - name: test-app-container
          image: "docker-image-path"
```

```yaml
# test-app-dev.yaml (patch)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-app
  namespace: test-app
spec:
  jobTemplate:
    spec:
      containers:
        - name: test-app-container
          env: 
            - name: Test
              value: asd
```

### Expected output

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-app
  namespace: test-app
spec:
  jobTemplate:
    spec:
      containers:
        - image: docker-image-path
          name: test-app-container
          env: 
            - name: Test
              value: asd
  schedule: '* */1 * * *'

```

### Actual output

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-app
  namespace: test-app
spec:
  jobTemplate:
    spec:
      containers:
      - env:
        - name: Test
          value: asd
        name: test-app-container
  schedule: '* */1 * * *'

```

### Kustomize version

v5.0.4-0.20230601165947-6ce0bf390ce3

### Operating system

Linux
