### ISSUE TITLE
Replacements in components does not behave as expected

### ISSUE THREAD

**Issue by ecoupal-believe** [kubernetes-sigs/kustomize#5531]
### What happened?

I want to add a metadata.label containing the metadata.name added by the namePrefix of an overlay. The replacement is working but it takes the name from the base instead of the one of the overlay. If it's working as intented can you suggest me something ?

Thanks

### What did you expect to happen?

The replacements should  take the rendered name including the prefix from the overlay.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
#base/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  template:
    spec:
      containers:
        - name: service
          image: service
```

```yaml
#component/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
- source:
    kind: Deployment
    fieldPath: metadata.name
  targets:
  - select:
      kind: Deployment
    fieldPaths:
      - metadata.labels.foo
    options:
      create: true
```

```yaml
#overlay/foo/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: foo-

resources:
- ../base

components:
- ../component
```

Complete code is here: https://gist.github.com/ecoupal-believe/1c143045499afbd196505b5911343254

### Expected output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-service
  labels:
    foo:  foo-service
spec:
  template:
    spec:
      containers:
        - name: service
          image: service
```

### Actual output

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-service
  labels:
    foo:  service
spec:
  template:
    spec:
      containers:
        - name: service
          image: service
```

### Kustomize version

v5.3.0

### Operating system

Linux
