### ISSUE TITLE
ConfigMapGenerator should allow for identical named files in output configmap

### ISSUE THREAD

**Issue by Heraclitus** [kubernetes-sigs/kustomize#555]
```
configMapGenerator:
- name: config-map
  files:
  - ../config/A/default.json
  - ../config/B/default.json
  - ../config/C/default.json
```
fails with 
```
Error: NewResMapFromConfigMapArgs: NewResMapFromConfigMapArgs: cannot add key default.json, another key by that name already exists: map[default.json:{
....
```

This is allowed as direct kubectl command like so, by way of custom name assigned to each file.
```

  kubectl create configmap device-config-nginx-content \
--from-file=defaultjson=../config/A/default.json \
--from-file=defaultjsonweb=../config/B/default.json \
--from-file=defaultjsonmob=../config/C/default.json \
--namespace=foo
```

**Comment by vreon** [comment]
You can use the same syntax from kubectl to choose a custom name for each key:

```yaml
configMapGenerator:
- name: config-map
  files:
  - defaultjson=../config/A/default.json
  - defaultjsonweb=../config/B/default.json
  - defaultjsonmob=../config/C/default.json
```
