### ISSUE TITLE
When using ConfigMapGenerator merge as a resource. says "cannot merge or replace"

### ISSUE THREAD

**Issue by zprd** [kubernetes-sigs/kustomize#5561]
### What happened?

Hi,
In attempt to make configMapGenerator (cmg) reusable by some overlays. I included a cmg as a resource in a kustomization file, but it fails to find the CM. if changed the behavior to create, it complains it already exists.

of course, when the cmg is included in the kustomization.yaml it works as expected. 

some hints? thx.

```sh
mkdir -p base overlays/yacm overlays/demo

cat <<EOF > base/map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: the-map
data:
  altGreeting: "Have a pineapple!"
  enableRisky: "true"
EOF

cat <<EOF > base/kustomization.yaml
resources:
- map.yaml
EOF

cat <<EOF > overlays/yacm/kustomization.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: the-map
  behavior: merge
  literals:
    - newGoodBy=Good by!
EOF

cat <<EOF > overlays/demo/kustomization.yaml
resources:
- ../../base
- ../yacm
EOF

kustomize build overlays/demo

```

### What did you expect to happen?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: the-map
data:
  altGreeting: "Have a pineapple!"
  enableRisky: "true"
  newGoodBy: "Good by!"
```

### Kustomize version

5.3.0

**Comment by koba1t** [comment]
I believe if you write the `resources` field parallel, that accumulates with separated.
It means your config will be run if you write base reference in the `overlays/yam/customization.yaml` file.

```

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: the-map
  behavior: merge
  literals:
    - newGoodBy=Good by!

resources:
- ../../base
```
