### ISSUE TITLE
Multiple protocols are clobbered when rendering ports

### ISSUE THREAD

**Issue by cmhillerman** [kubernetes-sigs/kustomize#558]
In the ports section of a manifest, if you are trying to set UDP and TCP for a port, only one of the ports is rendered in kustomize. E.g. If you have: 
```
        ports:
            - containerPort: 53
              hostPort: 53
              hostIP: 0.0.0.0
            - containerPort: 53
              hostPort: 53
              protocol: UDP
              hostIP: 0.0.0.0
```

And when you run kustomize build you get:

```
        ports:
        - containerPort: 53
          hostIP: 0.0.0.0
          hostPort: 53
```

This is because containerPort is used as the key to the hash. Maybe if we forced people to use name in all ports and used that as the key? Or using name as the key if the name exists?

I also could be confused and there's a workaround or something I'm missing?
