### ISSUE TITLE
ConfigMap hash not added for patch of namespaced base resource

### ISSUE THREAD

**Issue by jcassee** [kubernetes-sigs/kustomize#561]
Consider the following base and overlay.

base/kustomization.yaml:
```
resources:
  - resources.yaml

namespace: test
```

base/resources.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: bash
```

kustomization.yaml:
```
bases:
  - base

configMapGenerator:
  - name: config
    files:
      - kustomization.yaml

patches:
  - patch.yaml
```

patch.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  volumes:
    - name: config
      configMap:
        name: config
```

The generated resources do not have the configMap hash expanded:
```
apiVersion: v1
data:
  kustomization.yaml: |
    bases:
      - base

    configMapGenerator:
      - name: config
        files:
          - kustomization.yaml

    patches:
      - patch.yaml
kind: ConfigMap
metadata:
  name: config-h6745dbg6b
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - image: bash
    name: test
  volumes:
  - configMap:
      name: config
    name: config
```

I would have expected the configMap name to be `config-h6745dbg6b`, but it is `config`. (Removing `namespace` from the patch makes no difference.)
