### ISSUE TITLE
replacement in base kustomization missing custom nameSuffix

### ISSUE THREAD

**Issue by pberndt** [kubernetes-sigs/kustomize#5618]
### What happened?

When applying a custom nameSuffix to a base kustomization that is using replacements, _some_ of the replacement values will be missing the nameSuffix.

### What did you expect to happen?

I expected the replacements to consistently reflect the applied nameSuffix. Instead, in some cases they contain the suffix and in other cases they reference non-existent resources (without the suffix).

### How can we reproduce it (as minimally and precisely as possible)?

```
.
├── base
│   ├── 1-pv.yaml
│   ├── 2-pvc.yaml
│   └── kustomization.yaml
└── custom
    └── kustomization.yaml
```

```yaml
# base/1-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-cnb-pv  # will receive a custom suffix "-foo"
spec:
  storageClassName: ""
  claimRef:
    name: will-be-replaced  # => tekton-cnb-pvc (missing suffix!)
```

```yaml
# base/2-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-cnb-pvc  # will receive a custom suffix "-foo"
spec:
  storageClassName: ""
  volumeName: will-be-replaced # => tekton-cnb-pv-foo (works as expected)
```

```yaml
# base/kustomization.yaml
resources:
  - 1-pv.yaml
  - 2-pvc.yaml
replacements:
  - source:
      kind: PersistentVolume
      fieldPath: metadata.name
    targets:
      - select:
          kind: PersistentVolumeClaim
        fieldPaths:
          - spec.volumeName
  - source:
      kind: PersistentVolumeClaim
      fieldPath: metadata.name
    targets:
      - select:
          kind: PersistentVolume
        fieldPaths:
          - spec.claimRef.name
```

```yaml
# custom/kustomization.yaml
resources:
  - ../base
nameSuffix: -foo
```

Then invoke
```bash
kustomize build custom
```

### Expected output

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-cnb-pv-foo
spec:
  claimRef:
    name: tekton-cnb-pvc-foo
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-cnb-pvc-foo
spec:
  storageClassName: ""
  volumeName: tekton-cnb-pv-foo
```

(nameSuffix applied consistently)

### Actual output

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-cnb-pv-foo
spec:
  claimRef:
    name: tekton-cnb-pvc
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-cnb-pvc-foo
spec:
  storageClassName: ""
  volumeName: tekton-cnb-pv-foo
```
(nameSuffix missing from PV's claimRef)

### Kustomize version

v5.3.0

### Operating system

Linux
