### ISSUE TITLE
Failing to apply multiple patches using labelSelector/annotationSelector targeting the same files

### ISSUE THREAD

**Issue by mikecmpbll** [kubernetes-sigs/kustomize#5623]
### What happened?

When I use two JSON patches to copy configuration, and target these patches using annotationSelector, only the first patch applies.

### What did you expect to happen?

I expected the second patch to be applied.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
patches:
  - patch: |-
      - op: copy
        from: /data/original/foo
        path: /data/new/foo
    target:
      annotationSelector: default-env=True
  - patch: |-
      - op: copy
        from: /data/original/baz
        path: /data/new/baz
    target:
      annotationSelector: default-env=True
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
  annotations:
    default-env: True
data:
  original:
    foo: bar
    baz: qux
  new:
    foo:
    baz:
```

### Expected output

```yaml
apiVersion: v1
data:
  new:
    baz: qux
    foo: bar
  original:
    baz: qux
    foo: bar
kind: ConfigMap
metadata:
  annotations:
    default-env: "true"
  name: test-object
```

### Actual output

```yaml
apiVersion: v1
data:
  new:
    baz: null
    foo: bar
  original:
    baz: qux
    foo: bar
kind: ConfigMap
metadata:
  annotations:
    default-env: "true"
  name: test-object
```

### Kustomize version

v5.3.0

### Operating system

MacOS
