### ISSUE TITLE
Kustomize patches overwritten by namespace

### ISSUE THREAD

**Issue by AchimGrolimund** [kubernetes-sigs/kustomize#5626]
### What happened?

We would like to patch a `rolebinding.yaml` with kustomize. The namespace must be set in the meta information and the namespace must be patched in the subjcts area, as the service account can be in a different namespace.

With the old `patchesJson6902` it works. 

### What did you expect to happen?

cI expect the namespace to be in the meta information and the namespace we want to batch in the subject.

### How can we reproduce it (as minimally and precisely as possible)?

# `patches` fails
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ch-future-world-test

resources:
  - rolebinding_image-puller.yaml

patches:
  - target:
      kind: RoleBinding
      name: image-puller
      version: v1
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: ch-future-world-prod
```

```yaml
# rolebinding_image-puller.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: image-puller
  namespace: ch-future-world-123
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ch-future-world-intg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
```

# `patchesJson6902` works
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ch-future-world-test

resources:
  - rolebinding_image-puller.yaml

patchesJson6902:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: ch-future-world-prod
    target:
      kind: RoleBinding
      name: image-puller
      version: v1
```

```yaml
# rolebinding_image-puller.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: image-puller
  namespace: ch-future-world-123
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ch-future-world-intg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
```

### Expected output

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller
  namespace: ch-future-world-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: ch-future-world-prod # <<== Here is the PROD Namespace from the patches part

```

### Actual output

# `patches` fails
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller
  namespace: ch-future-world-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: ch-future-world-test # <<== Here is the wrong namespace coming from `namespace`

```

# `patchesJson6902` works
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller
  namespace: ch-future-world-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: ch-future-world-prod # <<== Here is the right namespace coming from `patchesJson6902`
```

### Kustomize version

4.5.4 & 5.3.0

### Operating system

Linux

**Comment by matthewhughes934** [comment]
Replacing the namespace on the subject of a RoleBinding where the subject name is `"default"` appears to be the expected behaviour (from [here](https://github.com/kubernetes-sigs/kustomize/blob/f0681429ea3f303305ee1b3e722ab87c82474a5b/api/filters/namespace/namespace.go#L115)):

> // In DefaultSubjectsOnly mode (default mode), RoleBinding and ClusterRoleBinding have namespace set on
// elements of the "subjects" field if and only if the subject elements
// "name" is "default".  Otherwise the namespace is not set.

You may be able to configure a namespace transformer to use some other behaviour here (some details/discussion in this issue: https://github.com/kubernetes-sigs/kustomize/issues/629)

As for why it works with a `patchesJson6902` I believe that's because of the ordering of the slice [here](https://github.com/kubernetes-sigs/kustomize/blob/f0681429ea3f303305ee1b3e722ab87c82474a5b/api/internal/target/kusttarget_configplugin.go#L72): `builtinhelpers.PatchTransformer` is before `builtinhelpers.NamespaceTransformer` so the patch is applied, then the namespace transformer updates the namespace, `builtinhelpers.PatchJson6902Transformer` is after the namespace transformer so it applies the patch _after_ the namespace transformer does its update (I am not sure if this is the desired/expected behaviour)

**Comment by okorzhov** [comment]
Having the same issue while tried to replace deprecated `patchesJson6902 ` with `patches`. Seems `patches` doesn't work with SecretStore resources. Namespace transformer can't be used as I need to replace a few different namespaces in exact resources. No luck with `patchesStrategicMerge` as well. Any suitable solution?

**Comment by guettli** [comment]
BTW, I found a way to do make a kustomization after namespace transformation was done: https://stackoverflow.com/a/79296673/633961

**Comment by ralgozino** [comment]
> BTW, I found a way to do make a kustomization after namespace transformation was done: https://stackoverflow.com/a/79296673/633961

I think that way is exactly the same as using `patchesJson6902`, but calling it via the `transformers` option instead of directly, that is much convoluted; isn't it?

**Comment by guettli** [comment]
> > BTW, I found a way to do make a kustomization after namespace transformation was done: https://stackoverflow.com/a/79296673/633961
> 
> I think that way is exactly the same as using `patchesJson6902`, but calling it via the `transformers` option instead of directly, that is much convoluted; isn't it?

Are you sure? The problem was for me, that I need to do something **after** namespace transformation was done. IIRC a patchesJson6902 does get called before namespace transformation.

**Comment by ralgozino** [comment]
> Are you sure? The problem was for me, that I need to do something **after** namespace transformation was done. IIRC a patchesJson6902 does get called before namespace transformation.

Yes.

If you use `patchesJson6902` in the kustomization.yaml, it is applied _after_ the namespace transformer. i.e.:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ch-future-world-test

resources:
  - rolebinding_image-puller.yaml

# This gets applied after the namespace transformer
patchesJson6902:
  - target:
      kind: RoleBinding
      name: image-puller
      version: v1
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: ch-future-world-prod
```

If you do the json patch inside the `patches` section, it is applied _before_ the namespace transformer. i.e.:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ch-future-world-test

resources:
  - rolebinding_image-puller.yaml

# This gets applied before the namespace transformer
patches:
  - target:
      kind: RoleBinding
      name: image-puller
      version: v1
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: ch-future-world-prod
```
