### ISSUE TITLE
Kustomize replaces null with "null" in case of repetetive component inclusion

### ISSUE THREAD

**Issue by vlasov-y** [kubernetes-sigs/kustomize#5631]
### What happened?

Kustomize replaced _null_ value with string `null`. So type change have happened because of component included twice.

It may be related to #5519 

### What did you expect to happen?

Idempotent behavior of the Component if I include it more than once.

### How can we reproduce it (as minimally and precisely as possible)?

Here is a script to create example stack.

```shell
mkdir null-example
cd null-example
mkdir app hr-timeout-2m

cat <<EOF >./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app
# - another-app
# - third-one
# It is a tenant stack that includes several applications
# Some of them have timeout, some of them - not...
components:
# ...so we include component to set timeout on tenant level...
# ...to be sure that all applications have it is set
- hr-timeout-2m
EOF

cat <<EOF >./app/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hr.yaml
# This application already has a timeout set
components:
- ../hr-timeout-2m
EOF

cat <<EOF >./app/hr.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test
spec:
  values:
    containerPorts:
      http: null
      https: 443
EOF

cat <<EOF >./hr-timeout-2m/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta2
    kind: HelmRelease
    metadata:
      name: _
    spec:
      interval: 5m
      timeout: 2m
  target:
    kind: HelmRelease
EOF
```

### Expected output

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test
spec:
  interval: 5m
  timeout: 2m
  values:
    containerPorts:
      http: null
      https: 443
```

### Actual output

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test
spec:
  interval: 5m
  timeout: 2m
  values:
    containerPorts:
      http: "null"
      https: 443
```

### Kustomize version

5.3.0

### Operating system

Linux
