### ISSUE TITLE
Special symbol convert

### ISSUE THREAD

**Issue by zwmyxzs** [kubernetes-sigs/kustomize#5632]
### What happened?

    - op: add
      path: /spec/template/metadata/labels/app.kubernetes.io/instance
      value: hello

get error:
error: add operation does not apply: doc is missing path: "/spec/template/metadata/labels/app.kubernetes.io/instance": missing value

### What did you expect to happen?

output yaml:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hello

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
patches:
- path: patch-deployment.yml
  target:
    kind: Deployment
- patch: |
    - op: add
      path: /spec/template/metadata/labels/app.kubernetes.io/instance
      value: hello
  target:
    kind: Deployment
    name: hello
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

5.0.1

### Operating system

Windows
