### ISSUE TITLE
"annotations: {}" in the input is removed by kustomize while  "labels: {}" isn't 

### ISSUE THREAD

**Issue by JordanGoasdoue** [kubernetes-sigs/kustomize#5647]
### What happened?

I've used kustomize successfully to add some changes to my helm, but i've seen that `annotations: {}` are being removed, while `labels: {}` or even a fake field i've added for testing purpose `fake: {}` are kept

### What did you expect to happen?

I expect `annotations: {}` to stay and not being removed if it's present on the input 

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
resources:
  - resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  labels: {}
  annotations: {}
  fake: {}
```

### Expected output

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  fake: {}
  labels: {}
  annotations: {}
  name: sa
```

### Actual output

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  fake: {}
  labels: {}
  name: sa
```

### Kustomize version

v5.4.1

### Operating system

Linux
