### ISSUE TITLE
Kustomize patches does not work correctly with my deployment 

### ISSUE THREAD

**Issue by mo-dayyeh** [kubernetes-sigs/kustomize#5649]
I have the following multi deployments application : 
1-web 2-worker 3-cronjobs 4-configmaps

✅ working kustomize file : 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- cronjobs.yaml
patches:
- path: web.yaml
- path: worker.yaml
- path: configmap.yaml

```
❓  Is there any caveat using this method ? 

 ❌  Failing kustomizefile :

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: web.yaml
- path: worker.yaml
- path: configmap.yaml
- path: cronjobs.yaml

```

cronjobs.yaml file contains multiple jobs like so : 

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cleanup-db
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: staging
                - name: SNOWFLAKE_WH
                  value: STAGING_WH
              lifecycle: {}
              name: cron-cleanup-db
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cleanup-locks
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: staging
                - name: SNOWFLAKE_WH
                  value: STAGING_WH
              lifecycle: {}
              name: cron-cleanup-locks
```

failure and test details : 

```
kubectl apply -k . --dry-run=client -o yaml '--namespace=${BRANCH_NAME}'
error: trouble configuring builtin PatchTransformer with config: `
path: cronjobs.yaml
`: unable to parse SM or JSON patch from [apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cleanup-db
```
If I remove cronjobs.yaml  the rest of the files renders correctly!  

Checking online people recommend moving back to patchesStrategicMerge ( which is deprecated and its the reason why I'm trying to move to patches).

Thanks
