### ISSUE TITLE
Add target section for all kustomize transformers

### ISSUE THREAD

**Issue by abogdanov37** [kubernetes-sigs/kustomize#5661]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Add a target section for all transformersl like in patch
Example
In patch section I can to select entities by name 
```yaml
patches:
  - path: patches/patch-name.yaml
    target:
      kind: LogConfig
      name: entity-name
```
I want to use that behavior in all transformers
Example 
in label section I WANT to select entities by name 
```yaml
labels:
- pairs:
    service.org.com/name: service-name
    service.org.com/version: 0.1.0
  includeSelectors: true
  target:
    name: entity-name
```

### Why is this needed?

Because I want to create many level customize builds
Example 
Application 1 depends on service 1 that depends on service 2
I create 

1. `kustomize.yaml` for Application 1
2. `kustomize.yaml` for Service 1
3. `kustomize.yaml` for Service 2

If I use labels section in Service 1
```yaml
labels:
- pairs:
    service.org.com/name: service-name 1
    service.org.com/version: 0.1.0
  includeSelectors: true
```
and Service 2 
```yaml
labels:
- pairs:
    service.org.com/name: service-name 2
    service.org.com/version: 1.1.0
  includeSelectors: true
```
The labels from Service 1 replace labals from Service 2
That behavior repeat in all transformers besause they based only on `kind` field

### Can you accomplish the motivating task without this feature, and if so, how?

Yes I can. I can use patch section instead of all transformations/
Example add labels
```yaml
- op: add
  path: /metadata/labels
  value: {}
- op: add
  path: /metadata/labels/service.org.com~1name
  value: service-name
- op: add
  path: /metadata/labels/service.org.com~1version
  value: 0.1.0
```

 

### What other solutions have you considered?

Have no other ideas

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉
