### ISSUE TITLE
patches does not update metadata.name properly 

### ISSUE THREAD

**Issue by Destorntw** [kubernetes-sigs/kustomize#5662]
### What happened?

when using the following structure:
|-Base
|    |-----CRB
|               |
|               | clusterrolebinding.yaml 
|-Overlays
|    |-----CRB
|               |
|               | crb-patches.yaml 

and in the patches file I specify another name than the metadata.name in the patches file the name doesn't change.

### What did you expect to happen?

When building the file in "dry run" or when applying the built manifest with the customization patches to be applied with the new name that what modified from the patches file.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crb.yaml
```

```yaml
# crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-users-n
roleRef:
#data-yyyyyy
```

### Expected output

```yaml
# crb-patches.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: name-patched
roleRef:
#data-xxxxxxx
```

### Actual output

```yaml
# crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-users-n
roleRef:
#data-xxxxxxx
```

### Kustomize version

5.4.1

### Operating system

Windows
