### ISSUE TITLE
Missing objects in kustomize build output

### ISSUE THREAD

**Issue by faust64** [kubernetes-sigs/kustomize#5665]
### What happened?

Colleague of mine is introducing some new CRDs & controllers .... and found about some edge case.

His new objects are named like `SomethingAccessList`.
They are missing from kustomize build outputs.

Hint: probably this: https://github.com/kubernetes-sigs/kustomize/blob/master/api/resource/factory.go#L193

Arguably ... yes, those "List" "usually" relates to the "listKind" we would find on custom resources definitions, ... eg:

```
  group: tekton.dev
  names:
    categories:
    - tekton
    - tekton-pipelines
    kind: PipelineRun
    listKind: PipelineRunList
    plural: pipelineruns
    shortNames:
    - pr
    - prs
    singular: pipelinerun
```` 

Still I'm not aware of any rule preventing usage of such a suffix, actually naming objects ....
.. and as far as I see: refactoring that snippet as an helm Chart: helm is able to produce the expected output.

Then that's a bug?

### What did you expect to happen?

objects showing in stdout, when I "kustomize build ."

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: something.example.com/v1
kind: SomethingAccessList
metadata:
  name: test-object
```

### Expected output

```yaml
apiVersion: something.example.com/v1
kind: SomethingAccessList
metadata:
  name: test-object
```

### Actual output

no output given. kustomize build exits with 0.

### Kustomize version

5.4.0

### Operating system

None
