### ISSUE TITLE
secretGenerator commands put echo parameters into secrets

### ISSUE THREAD

**Issue by aisensiy** [kubernetes-sigs/kustomize#568]
Something like this in my `kustomization.yaml`:

```
secretGenerator:
- name: short-message
  commands:
    SHORT_MESSAGE_API_KEY: "echo -n ${SHORT_MESSAGE_API_KEY}"
  type: Opaque
```

And the value is `-n xxxxx` not `xxxxx` and if I do not give the `-n` parameter then the result will be `xxxxx\n` which is not what I want.
