### ISSUE TITLE
Components: disable LoadRestrictions not working with Components 

### ISSUE THREAD

**Issue by ptr1120** [kubernetes-sigs/kustomize#5683]
### What happened?

I executed kustomize `kustomize build --load-restrictor=LoadRestrictionsNone ./test/` in order to render my manifest given below.

### What did you expect to happen?

Successfully generated kustomize output.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
  # Manifests
  - https://github.com/ptr1120/kustomize-bug.git/deploy/kustomize/manifests?ref=main

components:
  # MongoDb instance only for development
  - https://github.com/ptr1120/kustomize-bug.git/deploy/kustomize/components/mongodb-replicaset?ref=main
  # this is working - ../../../../<redacted>/Desktop/kustomize-bug/deploy/kustomize/components/mongodb-replicaset
```

### Expected output

Successfully generated kustomize output.

### Actual output

Error: accumulating components: accumulateDirectory: "recursed accumulation of path '<redacted>\\AppData\\Local\\Temp\\kustomize-761041946\\deploy\\kustomize\\components\\mongodb-replicaset': accumulating resources: accumulation err='accumulating resources from './../../manifests/generated/mongodb.yaml': security; file '<redacted>\\AppData\\Local\\Temp\\kustomize-761041946\\deploy\\kustomize\\manifests\\generated\\mongodb.yaml' is not in or below '<redacted>\\AppData\\Local\\Temp\\kustomize-761041946\\deploy\\kustomize\\components\\mongodb-replicaset'': must build at directory: '<redacted>\\AppData\\Local\\Temp\\kustomize-761041946\\deploy\\kustomize\\manifests\\generated\\mongodb.yaml': file is not directory"

### Kustomize version

v5.4.1

### Operating system

Windows
