### ISSUE TITLE
`add` works similarly `replace`

### ISSUE THREAD

**Issue by tebaly** [kubernetes-sigs/kustomize#5684]
### What happened?

```
- op: add
  path: /spec
  value: {}
```

Such a patch leads to replacement  `/spec` with a {} object
  

### What did you expect to happen?

Should be added if the path is missing. Don't replace an existing value

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec: 
  minReplicas: 1
---
kind: HorizontalPodAutoscaler
metadata:
  name: api
  labels: 
    add.spec: true
```

### Expected output

```yaml
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec: 
  minReplicas: 1
---
kind: HorizontalPodAutoscaler
metadata:
  name: api
  labels: 
    add.spec: true
spec: {}
```

### Actual output

```yaml
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec: {}
---
kind: HorizontalPodAutoscaler
metadata:
  name: api
  labels: 
    add.spec: true
spec: {}
```

### Kustomize version

v5.3.0

### Operating system

Linux
