### ISSUE TITLE
helmGlobals is not used when HelmChartInflationGenerator is used in generators field

### ISSUE THREAD

**Issue by LarsStegman** [kubernetes-sigs/kustomize#5685]
### What happened?

I am having trouble getting my deployments of a Helm chart to multiple sites/deployments working.

## The setup
```text
/
├─ charts/
│  ├─ my-app/
├─ my-app/
│  ├─ helm/
│  │  ├─ helm.yaml
│  │  ├─ kustomization.yaml
│  ├─ overlays/
│  │  ├─ site1/
│  │  │  ├─ common/
│  │  │  │  ├─ kustomization.yaml
│  │  │  ├─ deployments/
│  │  │  │  ├─ deployment1/
│  │  │  │  │  ├─ kustomization.yaml
│  │  │  │  ├─ kustomization.yaml
```

I have this structure because I need to deploy my app to multiple sites. Some
of the values need to be the same across all sites, like the application
version, for example. Some of the values need to be the same across 1 site,
like some credentials/domain names. Some of the values are specific per 
deployment, like the name.

This is the contents of the `/my-app/helm` folder. It is used as the base  
config for all deployments.

```yaml
# /my-app/helm/helm.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: my-app
name: my-app
```

```yaml
# /my-app/helm/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml
```

Then, per site I kustomize the `HelmChartInflationGenerator` from 
`/my-app/helm/helm.yaml` to provide some `valuesInline`.

```yaml
# /my-app/overlays/site1/common/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

patches:
  - patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: my-app
      valuesInline:
        k8sSecret:
          secretName: my-secret
        outputs:
          - url: "http://database.site1.company.global"
            tokenSecretKey: write1
            db: "db1"
```

Then in `/my-app/overlays/site1/deployments/deployment1/kustomization.yaml` I kustomize the
same `HelmChartInflationGenerator` another time to add additional
`valuesInline` values.

```yaml
# /my-app/overlays/site1/deployments/deployment1/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common-config

patches:
  - patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: my-app
      releaseName: deployment1-my-app
      valuesInline:
        requireActiveAccessToSensors: true
        socketListeners:
          - protocol: UDP
            port: 2000
        appConfig: |
          [config]
            key1 = "value1"
```

Finally, I collect all the different deployments from the site in 
`/my-app/overlays/site1/deployments/kustomization.yaml`.

```yaml
# /my-app/overlays/site1/deployments/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../charts

generators:
  - ./deployment1
```

## The problem
When I try to build this kustomization I get the following:
```bash
> cd my-app/overlays/site1/deployments
> kustomize build . --enable-helm --load-restrictor LoadRestrictionsNone
Error: no repo specified for pull, no chart found at ''
```

It looks like `helmGlobals.chartHome` is not passed to the 
`HelmChartInflationGenerator` at all. Even if I change
it to `foo`, I still get the same error. I would expect it to say 
`no chart found at 'foo'` then.

Am I doing something wrong, or is this a bug?

### What did you expect to happen?

The Helm chart is inflated multiple times, once per sites per deployment.

### Files
```yaml
# /my-app/helm/helm.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: my-app
name: my-app
```

```yaml
# /my-app/helm/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml
```

```yaml
# /my-app/overlays/site1/common/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../helm

patches:
  - patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: my-app
      valuesInline:
        k8sSecret:
          secretName: my-secret
        outputs:
          - url: "http://database.site1.company.global"
            tokenSecretKey: write1
            db: "db1"
```

```yaml
# /my-app/overlays/site1/deployments/deployment1/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common-config

patches:
  - patch: |-
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: my-app
      releaseName: deployment1-my-app
      valuesInline:
        requireActiveAccessToSensors: true
        socketListeners:
          - protocol: UDP
            port: 2000
        appConfig: |
          [config]
            key1 = "value1"
```

```yaml
# /my-app/overlays/site1/deployments/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../charts

generators:
  - ./deployment1
```

### Command
```bash
> cd my-app/overlays/site1/deployments
> kustomize build . --enable-helm --load-restrictor LoadRestrictionsNone
Error: no repo specified for pull, no chart found at ''
```

### Expected output

Inflated Helm Chart per site per deployment

### Actual output

An error saying the Helm chart cannot be found

### Kustomize version

5.3.0

### Operating system

Linux
