### ISSUE TITLE
Kustomize: apply patch results in error "add operation does not apply: doc is missing path"

### ISSUE THREAD

**Issue by edtshuma** [kubernetes-sigs/kustomize#5695]
I am trying to do a kustomize patch to an existing Helm deployment via a CI/CD pipeline. The CI pipeline is failing kustomize checks with error:

`error: accumulating components: accumulateDirectory: "recursed accumulation of path '/runner/_work/ops-infra/ops-infra/current/components/mimir-prod/alertmanager/ops': add operation does not apply: doc is missing path: \"/spec/values/alertmanager/fallbackConfig/receivers/-\": missing value``

The patch is defined in receivers-patch.yaml as follows:

`- op: add
 path: /spec/chart/spec/values/alertmanager/fallbackConfig/receivers/-
  value:
    name: 'slack_receiver'
    slack_configs:
      - channel: "#ops"
        send_resolved: true
        slack_api_url: "https://hooks.slack.com/services/Txxxxx"`

This patch adds a new "receiver" entry to the Mimir AlertManager Helm deployment. The patch is applied in kustomization.yaml file as:

```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: receivers-patch.yaml
    target:
      kind: HelmRelease
      name: mimir-prod
```

The deployment on which the patch is being applied is defined as below:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mimir-prod
  namespace: monitoring
spec:
  ...
  ...
  values:
    alertmanager:
      fallbackConfig: |
        global:
          pagerduty_url: https://events.pagerduty.com/v2/enqueue
          resolve_timeout: 5m
        receivers:
          - name: 'null'
        route:
          group_by: ['alertname']
          group_interval: 5m
          group_wait: 30s
          receiver: 'null'
```

I have looked at other questions here of similar nature but I cant quite find a match to my issue.

What am I doing wrong?
