### ISSUE TITLE
element spec.rules.http.paths.backend.service.port of ingress resource is not inherited

### ISSUE THREAD

**Issue by heroes1412** [kubernetes-sigs/kustomize#5713]
### What happened?

i try to create a ingress-patch.yaml file, to patch some value, i found spec.rules.http.paths.backend.service.port and  spec.rules.http.paths.backend.service.port.number is not inherited from the base

### What did you expect to happen?

spec.rules.http.paths.backend.service.port and  spec.rules.http.paths.backend.service.port.number is inherited from the base

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: ingress-patch.yaml
```

```yaml
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2.rke2.local
  labels:
    app: app2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "app2.hoang92bn.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-app2
            port:
              number: 30080
```

```yaml
# ingress-patch.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2.rke2.local
  labels:
    app: app2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "app2.hoang92bn.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-app2
```

### Expected output

service.port of ingress resource will be inherited from the base.

### Actual output

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ....
  labels:
    app: app2
    env: prod
  name: prod-app2.rke2.local
spec:
  ingressClassName: nginx
  rules:
  - host: prod.app2.rke2.local
    http:
      paths:
      - backend:
          service:
            name: prod-svc-app2
        path: /
        pathType: Prefix
```

### Kustomize version

v5.4.2

### Operating system

Linux
