### ISSUE TITLE
Allow using Helm charts as bases and values.yaml file patching in overlays

### ISSUE THREAD

**Issue by pentago** [kubernetes-sigs/kustomize#5714]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I'd like to have ability to use Helm charts as regular base and allow patching of that base with different values.yaml as patches in overlays, like this:

```
.
├── base
│   ├── Chart.yaml
│   ├── kustomization.yaml
│   └── values.yaml
└── environments
    ├── dev
    │   ├── kustomization.yaml
    │   └── prod-values.yaml
    ├── prod
    │   ├── kustomization.yaml
    │   └── prod-values.yaml
    └── stage
        ├── kustomization.yaml
        └── stage-values.yaml
```

### Why is this needed?

Something like this would make Helm charts first-class citizens in Kustomize projects and allow for uniform patching to standard Kubernetes YAML manifests.

### Can you accomplish the motivating task without this feature, and if so, how?

Only by using a lot of duplication like using full values.yaml for each overlay.

### What other solutions have you considered?

Not aware of anything else doing this and would love to get this thing done with only Kustomize.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by isarns** [comment]
I'm not sure about using a chart a the base. 

We've implemented a multi-layered configuration system that combines base configurations, variants, and local overrides. Here's how it works:

### Architecture Overview

```
base/           # Foundation layer - common defaults
variants/       # Middle layer - environment/region variants  
live/           # Top layer - specific deployment configs
charts/        # Helm chart templates
```

### Configuration Layering

Our `kustomization.yaml` files reference multiple values files in order of precedence:

```yaml
helmCharts:
- additionalValuesFiles:
  - ../../../../../base/service-name/values.yaml      # 1. Base defaults
  - ../../../../../variants/env/non-prod/replicas.yaml # 2. Environment variants
  name: my-chart
  valuesFile: values.yaml                             # 3. Local overrides
```

### Layer Responsibilities

1. **Base Layer** (`base/*/values.yaml`)
   - Common configuration shared across all environments
   - Service defaults, resource templates, standard settings
   - Acts as the foundation that everything builds upon

2. **Variant Layer** (`variants/env/` & `variants/region/`)
   - Environment-specific overrides (dev, staging, prod)
   - Region-specific configurations (us-east-1, eu-west-1)
   - Scaling configurations, environment URLs, etc.

3. **Local Layer** (`live/*/values.yaml`)
   - Deployment-specific final overrides
   - Instance-specific secrets, endpoints, custom configs
   - Highest precedence - wins over base and variants


This pattern gives us the flexibility to maintain consistency while allowing for necessary customization at each deployment level.

**Comment by pentago** [comment]
@isarns would you be able to share a new, example repo with simple kustomize project set like what you're describing?

**Comment by QuinnBast** [comment]
Our current setup also does something similar to what @isarns and allows us to essentially do this. This is what our layout looks like:

<img width="347" height="397" alt="Image" src="https://github.com/user-attachments/assets/77eb36ee-5720-4649-b906-67a0c1a7c11f" />

And the `kustomization.yaml` file only renders the helm chart at the override level (not the base). Typically `base/kustomization.yaml` ends up being just:

```yaml
resources: []
```

Unless there is some global level configuration or a helm chart patch that we need to apply to every environment.

And then this is the `env1/kustomization.yaml` file:
```yaml
# Point to the base to do any other rendering...
resources:
  - ../base

# Render the helm chart once in each override location.
helmCharts:
  - name: postgresql
    releaseName: postgres-postgresql
    namespace: tgrm
    version: 15.5.38
    repo: https://charts.bitnami.com/bitnami
    valuesFile: ../base/values.yaml

   # Overrides the base values.yaml for this environment
    valuesInline:
```

However, that being said, I do have to duplicate this `helmCharts:` block in every environment override. I was kind of hoping that `helmCharts` could be a `base` level block, because I always know that I'm going to be using `helmCharts` in every scenario/environment. Though I am not really sure how it would be possible for Kustomize to be able to "collect" or know about all of the `values.yaml` files for overrides to be able to apply them on top of the base before the chart renders.

Though the layout I mentioned above does work fairly well

**Comment by isarns** [comment]
> [@isarns](https://github.com/isarns) would you be able to share a new, example repo with simple kustomize project set like what you're describing?

https://github.com/isarns/kustomize-helm-example Hope this will clear thing out

**Comment by maruiz93** [comment]
Hi! I was trying to achieve something similar to what you are doing here, but my problem is regarding the need of `--load-restrictor=LoadRestrictionsNone`. With @isarns solution that flag is mandatory but disabling that flag for everything is a problem, specially if this is just for a few of multiple ArgoCD Applications.

So I am wondering if allowing the usage of values outside of the folder could not be consider a security issue without the --load-restrictor=LoadRestrictionsNone.

**Comment by QuinnBast** [comment]
@maruiz93 Yeah you are correct, it does require setting `--load-restrictor=LoadRestrictionsNone`. Personally, I am not sure of the security implications. I guess the security implication could be that if someone external has access to your ArgoCD instance, they could hypothetically point ArgoCD's Kustomize to some files outside of your repository (in the argocd container) to be able to somehow inject something non-kosher into Kustomize? But they would also have to have breached the ArgoCD repository container in k8s to be able to placed something there in the first place.

However, for me, I know only trusted actors will ever have access to ArgoCD/kubectl so we pass this flag to ArgoCD via the argo configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # By default kustomize will refuse to load files from a parent directory
  # So use no load restrictions to disable that for our directory structure
  kustomize.buildOptions: "--enable-helm --load-restrictor LoadRestrictionsNone"
```
