### ISSUE TITLE
helmCharts: kyaml fails when encounting helm charts with emty values.yaml files

### ISSUE THREAD

**Issue by djfinnoy** [kubernetes-sigs/kustomize#5720]
### What happened?

After upgrading from `5.3.0` to `5.4.2` we encountered a bug where kustomize has started failing with the following error:

```
Error: could not parse values file into rnode: EOF 
```

The bug affects helm charts with an empty `values.yaml` file.
We have a private helm chart where the default `values.yaml` files that is packaged alongside the chart is empty, and we typically use `valuesInline` in kustomize to pass values.

```
# kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: my-libchart
    repo: oci://europe-west1-docker.pkg.dev/my-project/my-chart
    valuesInline:
      someKey: someValue
```

The issue is that the [following function](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go#L206) returns an error due to the lack of a populated `values.yaml` file.

I have found two ways to fix the issue:

- Use `valuesFile` instead of (or in addition to) `valuesInline`.
- Add any key-value pair to the upstream helm chart so that it no longer has an empty values file (this is our workaround for the time being).

### What did you expect to happen?

The `replaceValuesInline()` should tolerate empty helm values files.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: my-libchart
    repo: file://path/to/helmchart/with/empty/valuesfile
    valuesInline:
      someKey: someValue
```

### Expected output

No error

### Actual output

Error

### Kustomize version

5.4.2

### Operating system

Linux
