### ISSUE TITLE
Multi-namespace transformer

### ISSUE THREAD

**Issue by TheSpiritXIII** [kubernetes-sigs/kustomize#5721]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

The current namespace transformer replaces and unifies all namespaces to a single one. I would love the ability to specify namespace mappings, e.g. rename namespace `x` to namespace `a`.

### Why is this needed?

Some manifests may have multiple namespaces, e.g. a workload may have different RBAC permissions for different namespaces.

### Can you accomplish the motivating task without this feature, and if so, how?

No. The `replacements` feature comes close but it doesn't replace namespace selectors like the current namespace transformer does -- you would need many `replacements`, e.g. one each for subjects, role bindings, [etc](https://github.com/kubernetes-sigs/kustomize/blob/e3a7615ccb84506cee74e576d05e636aaa4542ad/api/filters/namespace/namespace.go).

### What other solutions have you considered?

N/A

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by TheSpiritXIII** [comment]
@koba1t thanks for the quick reply!

Consider this example where there are two namespaces within a single resource:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: namespace2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator
  namespace: namespace1
roleRef:
  name: operator
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: operator
  namespace: namespace2
  kind: ServiceAccount
```

With Kustomization:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- example.yaml
namespace: foo
```

How can I tell Kustomize to update only `namespace2` to `foo`? Both `namespace1` and `namespace2` were changed to the same namespace `foo`.

I can use replacements to fix it but:
1. Replacements do not scale well when you have many resources with the same problem, making this solution error-prone. If the source manifest changes, I must also edit the `replacement`.
2. There are other resources besides `RoleBinding` where you may have multiple namespaces in a single resource. For example, anyone could create a custom resource and [add it](https://github.com/kubernetes-sigs/kustomize/blob/e3a7615ccb84506cee74e576d05e636aaa4542ad/api/filters/namespace/namespace.go#L21C2-L21C9) to the namespace transformer configuration.

I personally think it's silly that the namespace transformer can lookup and edit namespace references but you can't control how this behavior works.

I'd love to hear your thoughts. It's certainly an edge case so I understand if this can't be prioritized. Thanks!

**Comment by koba1t** [comment]
Hi @TheSpiritXIII 

Sorry, I'm not sure I understand.
The `RoleBinding` resource that references other namespace resources is valid, and what does it mean?
I have concerns that the resource is not working correctly, and I can't find any documents on the k8s.io page....

**Comment by koba1t** [comment]
Hi @TheSpiritXIII 

I'll close this issue.
If you need more help or have additional information, please feel free to reopen!

/close

**Comment by nitishkumar71** [comment]
> Hi [@TheSpiritXIII](https://github.com/TheSpiritXIII)
> 
> Sorry, I'm not sure I understand. The `RoleBinding` resource that references other namespace resources is valid, and what does it mean? I have concerns that the resource is not working correctly, and I can't find any documents on the k8s.io page....

This is a valid use case. I am facing similar issue with one of the helm chart. Helm chart tries to generate rolebinding for different namespaces using range but namespace transformer overwrites namespace for them too resulting in `error: namespace transformation produces ID conflict:`.


In case you want to test, please use these files
```yaml
# kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-operator
helmCharts:
- name: strimzi-kafka-operator
  releaseName: kafka-operator
  nam
  version: 0.45.0
  repo: oci://quay.io/strimzi-helm
  valuesFile: values.yaml
  includeCRDs: true
```

```yaml
# values.yaml

replicas: 1
watchNamespaces: ["analytics"]
rbac:
  create: true
```
