### ISSUE TITLE
Better syntax for ordered operations

### ISSUE THREAD

**Issue by TheSpiritXIII** [kubernetes-sigs/kustomize#5723]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I want to apply transformers in order with a better UX.

### Why is this needed?

For example, let's say I use `labels` to set all resources labels, but I want a few to be different. I want to use `patches` to modify the different labels, but sadly `patches` runs before `labels`.

It would be great if Kustomize supported some sort of `operations` field which let you list otherwise global fixed operations:

```yaml
# These get applied in order.
operations:
- labels:
  - pairs:
      addonmanager.kubernetes.io/mode: Reconcile
- patchesStrategicMerge:
  - patch.yaml
```

### Can you accomplish the motivating task without this feature, and if so, how?

I've been using transformers to accomplish this:

```yaml
transformers
- |-
  apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: addonmanager
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  fieldSpecs:
  - path: metadata/labels
    create: true
- |-
  apiVersion: builtin
  kind: PatchStrategicMergeTransformer
  metadata:
    name: labels
  paths:
  - patch.yaml
```

However, there's some downsides:
- Notice I use the deprecated patch merge transformer... yet no warning.
- No IDE support. Normally I get syntax highlighting and basic field validation except within the transformers.

### What other solutions have you considered?

N/A

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉
