### ISSUE TITLE
`kustomize edit add label` generates deprecated config

### ISSUE THREAD

**Issue by mhutter** [kubernetes-sigs/kustomize#5726]
### What happened?

How to reproduce:

```sh
kustomize edit add label environment:dev
```
This will set `commonLabels.env` in the kustomization file, triggering a deprecation warning.

### What did you expect to happen?

Kustomize commands to not generate deprecated configs.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
```

### Expected output

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    environment: dev
```

### Actual output

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: dev
```

### Kustomize version

5.4.2

### Operating system

Linux
