### ISSUE TITLE
Kio ByteReader changing the structure of YTT Yaml with list in it 

### ISSUE THREAD

**Issue by pauldennehy** [kubernetes-sigs/kustomize#5732]
### What happened?

When using Kio.Bytereader to read in a yaml with YTT data that has a list it will change the structure of that yaml.
This is notice when writing the yaml to file again.

### What did you expect to happen?

Structure should not change from importing and exporting.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: v1
kind: YttTemplate
metadata:
  name: ytt_array_template
ytt_header:
  header:
  #@ load("@ytt:data", "data")
  array_list1:
    -  #@data.1
    -  #@data.2
ytt_template_content:
  content:
    #!---START OF TEMPLATE--DO NOT REMOVE THIS LINE---
    desc: " The array will not work. removes all array elements, except last and will move it out of the array"
    #try string prepend
    array_list2:
      list_items:
        -  #@data.1
        -  #@data.2
        -  #@data.3
      #! END
```

### Expected output

```yaml
apiVersion: v1
kind: YttTemplate
metadata:
  name: ytt_array_template
  annotations:
    config.kubernetes.io/index: '0'
    internal.config.kubernetes.io/index: '0'
    internal.config.kubernetes.io/seqindent: 'wide'
ytt_header:
  header:
  #@ load("@ytt:data", "data")
  array_list1:
    -  #@data.1
    -  #@data.2
ytt_template_content:
  content:
    #!---START OF TEMPLATE--DO NOT REMOVE THIS LINE---
    desc: " The array will not work. removes all array elements, except last and will move it out of the array"
    #try string prepend
    array_list2:
      list_items:
        -  #@data.1
        -  #@data.2
        -  #@data.3
      #! END
```

### Actual output

```yaml
apiVersion: v1
kind: YttTemplate
metadata:
  name: ytt_array_template
  annotations:
    config.kubernetes.io/index: '0'
    internal.config.kubernetes.io/index: '0'
    internal.config.kubernetes.io/seqindent: 'wide'
ytt_header:
  header:
  #@ load("@ytt:data", "data")
  array_list1:
  -
  -
  #@data.2
ytt_template_content:
  content:
    #!---START OF TEMPLATE--DO NOT REMOVE THIS LINE---
    desc: " The array will not work. removes all array elements, except last and will move it out of the array"
    #try string prepend
    array_list2:
      list_items:
      -
      -
      -
      #@data.3
      #! END
```

### Kustomize version

sigs.k8s.io/kustomize/kyaml v0.17.1

### Operating system

Windows
