### ISSUE TITLE
nameSuffix not inherited to replacements in referenced files

### ISSUE THREAD

**Issue by mibutec** [kubernetes-sigs/kustomize#5743]
### What happened?

Typically when using a nameSuffix, I can define it in the outer most customization and it will be "inherited" to all resources I use. In case of replacements this is not the case, replacements see the nameSuffix only, when it is defined in the same customization or an used resource. When using replacements in multiple places, I have to set the nameSuffix in all that places. That's unexpected, as the renaming also works for included resources.

### What did you expect to happen?

When having some replacements in bases defined and some replacements in my overlay, I would expect replacements to work clean even the nameSuffix is only defined in the overlay.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# bases/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: source
  - name: showcase
    literals:
      - name1=unchanged1
      - name2=unchanged2

replacements:
  - source:
      kind: ConfigMap
      name: source
    targets:
      - select:
          kind: ConfigMap
          name: showcase
        fieldPaths:
          - data.name1
```

```yaml
# bug/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: '-42'
resources:
  - ../bases/

replacements:
  - source:
      kind: ConfigMap
      name: source
    targets:
      - select:
          kind: ConfigMap
          name: showcase
        fieldPaths:
          - data.name2
```

kustomize build overlays/bug

### Expected output

```yaml
apiVersion: v1
data:
  name1: source-42
  name2: source-42
kind: ConfigMap
metadata:
  name: showcase-42-mf5m457f88
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: source-42-6ct58987ht
```

### Actual output

```yaml
apiVersion: v1
data:
  name1: source
  name2: source-42
kind: ConfigMap
metadata:
  name: showcase-42-mf5m457f88
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: source-42-6ct58987ht
```

### Kustomize version

v5.3.0

### Operating system

None
