### ISSUE TITLE
kustomize create should take --component to create a kustomize.config.k8s.io/v1alpha1 kind: Component

### ISSUE THREAD

**Issue by ringerc** [kubernetes-sigs/kustomize#5747]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

When using `kustomize create` it would be convenient to be able to generate a `Component` resource, not just a `Kustomization`.

### Why is this needed?

It's not easy to remember the apiVersion of the Component, and components aren't very discoverable as kustomize features.

This would also help to make the excellent and useful Components feature more visible. It's currently severely under-utilized despite being extremely helpful in solving a variety of problems with tree-structured kustomizations.

### Can you accomplish the motivating task without this feature, and if so, how?

Yes, just

```
cat >>kustomization.yaml <<'__END__'
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
__END__
```

### What other solutions have you considered?

What I do now - manually creating them.

### Anything else we should know?

This is mainly a usability/discovery suggestion.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉
