### ISSUE TITLE
Can't build linkerd-viz manifests with Kustomize and helm

### ISSUE THREAD

**Issue by tokongs** [kubernetes-sigs/kustomize#5754]
### What happened?

I'm trying to build the linkerd-viz manifests with Kustomize. However, it exits with an error. It works fine when I try to build directly with Helm. 

### What did you expect to happen?

For the build to complete successfully.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: linkerd-viz
    repo: https://helm.linkerd.io/edge
    version: 2024.8.2
```
`kustomize build <path> --enable-helm --helm-kube-version 1.30`

### Expected output

linker-viz manifests

### Actual output

```sh
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 48: mapping key "runAsUser" already defined at line 47
```

### Kustomize version

5.4.3

### Operating system

Linux
