### ISSUE TITLE
configMapGenerator doesn't create the correct suffix when metadata.namespace: is set. 

### ISSUE THREAD

**Issue by shlomodaari** [kubernetes-sigs/kustomize#5757]
### What happened?

When the namespace is set in the deployment the kustomize doesn't add the suffix to the configMap 

### What did you expect to happen?

adding the suffix correctly 

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

          - configMap:
              name: spinnaker-hb4d76k25c
          - configMap:
              name: orca-c88mftkf6c

### Actual output

          - configMap:
              name: spinnaker
          - configMap:
              name: orca

### Kustomize version

5.4.3

### Operating system

None
