### ISSUE TITLE
vpaGenerator built-in

### ISSUE THREAD

**Issue by lets-call-n-walk** [kubernetes-sigs/kustomize#5776]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I think a built-in vpaGenerator could be a widely convenient field. I imagine it would be formatted something like this:

```
vpaGenerator:
# if target not specified, target all daemonsets/statefulsets/deployments resources
- target: 
     group: apps
     version: v1
     kind: Deployment
     name: argocd-application-controller
  recommender: ''default"
  mode: 'Off'
```

### Why is this needed?

Auto-mode VPAs afford valuable cost savings and maintenance reduction. Even Off-mode VPAs still afford helpful resource usage and prediction data. 

We currently use both modes with all of our 26+ apps we deploy across 26 clusters. Most VPA manifests are highly redundant to write and maintain because of their simplicity.

### Can you accomplish the motivating task without this feature, and if so, how?

I can create a custom generator, but as VPAs increase in popularity and kubernetes integration, I wanted to get a feel for if others would find this useful as well.

### What other solutions have you considered?

Previously our team used the goldilocks operator to generate VPA resources for all our deployments/daemonsets/statefulsets.  We have moved off of it recently and are now manually writing VPAs for our team's apps because it breaks GitOps principles (in addition to a bug that is making Argo performance abysmal).

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉
