### ISSUE TITLE
Different behavior in adding the Block Chomping Indicator to strings

### ISSUE THREAD

**Issue by duritong** [kubernetes-sigs/kustomize#5795]
### What happened?

given the following structure:
```
$ cat configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
data:
  string: ''
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: test2
data:
  string: ''
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml

patches:
- target:
    kind: ConfigMap
    version: v1
    name: test
  patch: |
    - op: replace
      path: /data/string
      value: |+
        this is
        a multiline string

        that should have an empty line at the end

- target:
    kind: ConfigMap
    version: v1
    name: test2
  patch: |
    - op: replace
      value: |+
        this is
        a multiline string

        that should have an empty line at the end

      path: /data/string
```

We get the following output:

```
$ kustomize version
v5.5.0
$ kustomize build
apiVersion: v1
data:
  string: |-
    this is
    a multiline string

    that should have an empty line at the end
kind: ConfigMap
metadata:
  name: test
---
apiVersion: v1
data:
  string: |+
    this is
    a multiline string

    that should have an empty line at the end

kind: ConfigMap
metadata:
  name: test2
```

Although it seems we do have two times the same patch that we do get different results depending on whether we do have something after the string, that is still part of the path or not.

### What did you expect to happen?

Both patches should produce the same output.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
data:
  string: ''
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: test2
data:
  string: ''
```
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml

patches:
- target:
    kind: ConfigMap
    version: v1
    name: test
  patch: |
    - op: replace
      path: /data/string
      value: |+
        this is
        a multiline string

        that should have an empty line at the end

- target:
    kind: ConfigMap
    version: v1
    name: test2
  patch: |
    - op: replace
      value: |+
        this is
        a multiline string

        that should have an empty line at the end

      path: /data/string
```

### Expected output

```yaml
apiVersion: v1
data:
  string: |+
    this is
    a multiline string

    that should have an empty line at the end

kind: ConfigMap
metadata:
  name: test
---
apiVersion: v1
data:
  string: |+
    this is
    a multiline string

    that should have an empty line at the end

kind: ConfigMap
metadata:
  name: test2

```

### Actual output

```yaml
apiVersion: v1
data:
  string: |-
    this is
    a multiline string

    that should have an empty line at the end
kind: ConfigMap
metadata:
  name: test
---
apiVersion: v1
data:
  string: |+
    this is
    a multiline string

    that should have an empty line at the end

kind: ConfigMap
metadata:
  name: test2

```

### Kustomize version

5.5.0

### Operating system

Linux
