### ISSUE TITLE
Patches not applied when target.namespace is specified

### ISSUE THREAD

**Issue by bozho** [kubernetes-sigs/kustomize#5796]
### What happened?

I'm learning Flux, so I'm not sure if this is a Flux or a Kustomize behaviour issue (or a "me" issue :-). I'm deploying the `podinfo` example and trying to patch the `HorizontalPodAutoscaler`.

If I **don't** specify `namespace` in Flux's Kustomization `spec.patches.target`, the patch works. If I **do** specify it, it's not applied and there is no error message. Even if I specify a non-existent namespace, there is no error message.

### What did you expect to happen?

The patch to be applied when `target.namespace` is specified.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: podinfo
  timeout: 3m0s
  wait: true
  patches:
    - target:
        name: podinfo
#        namespace: podinfo # Namespace podinfo exists.
        kind: HorizontalPodAutoscaler
      patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo
        spec:
          minReplicas: 2
          maxReplicas: 5
```

### Expected output

```
NAMESPACE   NAME                                          REFERENCE            TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
podinfo     horizontalpodautoscaler.autoscaling/podinfo   Deployment/podinfo   cpu: <unknown>/99%   2         5         2          99m
```

### Actual output

```
NAMESPACE   NAME                                          REFERENCE            TARGETS              MINPODS   MAXPODS   REPLICAS   AGE
podinfo     horizontalpodautoscaler.autoscaling/podinfo   Deployment/podinfo   cpu: <unknown>/99%   2         4         2          99m
```

### Kustomize version

5.4 (using Flux 2.4.0)

### Operating system

Linux
