### ISSUE TITLE
Make `patch` fail on "create"

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/kustomize#5801]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

A kustomize patch can result into an "update" or a "create". It depends.

Example of a kustomize patch:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: foo-system
spec:
  template:
    spec:
      containers:
      - name: backend
        image: ghcr.io/foo/bar
```

there are two cases: there is already a container with name "backend", or there is no such container.

As an author of the kustomize patch, I want always to do an *update*.

Is there a way to get an error from kustomize if the patch would do a "create"?

Background: Names got changed, and then we had two containers in the deployment, because one place was not updated. I would like this to fail early the next time. 

### Why is this needed?

I don't want two containers in my deployment. I want to update an existing deployment.

### Can you accomplish the motivating task without this feature, and if so, how?

I could use json-patch with "replace". But this is hard to read and write.

### What other solutions have you considered?

.

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉
