### ISSUE TITLE
Null values ignored in HelmChartInflationGenerator

### ISSUE THREAD

**Issue by erwanval** [kubernetes-sigs/kustomize#5803]
### What happened?

Since 5.4.0, there is a regression causing null values in helmChartInflationGenerator to be ignored.  
Setting a null value is useful to remove default values present in values.yaml.

I have tried with all versions of kustomize since 5.0.0, and it seems it was fixed in 5.2.0, but reappeared in 5.4.0.

### What did you expect to happen?

Setting a null value should overwrite and remove a default values present in values.yaml.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helmchartinflation-crowdsec.yaml
```

```yaml
# helmchartinflation-crowdsec.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: crowdsec
releaseName: crowdsec
namespace: crowdsec
name: crowdsec
repo: https://crowdsecurity.github.io/helm-charts
version: 0.13.0
includeCRDs: true
valuesInline:
  lapi:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: null # We want to remove the default from values.yaml
        memory: 100Mi
    persistentVolume:
      config:
        enabled: false
      data:
        enabled: false
  agent:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: null # We want to remove the default from values.yaml
        memory: 100Mi
    acquisition:
      - namespace: ingress-nginx
        podName: ingress-nginx-controller-*
        program: nginx
```

### Expected output

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: crowdsec-agent
spec:
  [...]
  template:
    [...]
    spec:
      [...]
      containers:
        [...]
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
```

### Actual output

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: crowdsec-agent
spec:
  [...]
  template:
    [...]
    spec:
      [...]
      containers:
        [...]
          resources:
            limits:
              cpu: 500m # default from values.yaml still set
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
```

### Kustomize version

5.4.0

### Operating system

None

**Comment by erwanval** [comment]
Still reproductible with 5.6.0

/remove-lifecycle stale

**Comment by isarns** [comment]
adding `valuesMerge: replace` worked for me 

```yaml
# helmchartinflation-crowdsec.yaml

apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: crowdsec
releaseName: crowdsec
namespace: crowdsec
name: crowdsec
repo: https://crowdsecurity.github.io/helm-charts
version: 0.13.0
includeCRDs: true
valuesMerge: replace
valuesInline:
  lapi:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: null # We want to remove the default from values.yaml
        memory: 100Mi
    persistentVolume:
      config:
        enabled: false
      data:
        enabled: false
  agent:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: null # We want to remove the default from values.yaml
        memory: 100Mi
    acquisition:
      - namespace: ingress-nginx
        podName: ingress-nginx-controller-*
        program: nginx
```

output: 
```yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: crowdsec
    type: lapi
    version: v1
  name: crowdsec-lapi
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: crowdsec
      type: lapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/agent-secret: e6639a6c3961058b45e97c6abf1b5f986bbd1d2f9c6386b87ba731739f677bf6
        checksum/lapi-configmap: f1c5b812195242564e3d57e5d84245ceb46d079f41fa31843ec56f51d011b77e
        checksum/lapi-secret: f189c1cbf54cc43d94c8448633217353044fe571525b7e129f62650b9f79aa0b
      labels:
        k8s-app: crowdsec
        type: lapi
        version: v1
    spec:
      containers:
      - env:
        - name: LOCAL_API_URL
          value: http://localhost:8080
        - name: AGENT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: agent-credentials
        - name: AGENT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: agent-credentials
        - name: DISABLE_AGENT
          value: "true"
        - name: INSECURE_SKIP_VERIFY
          value: "false"
        - name: CS_LAPI_SECRET
          valueFrom:
            secretKeyRef:
              key: csLapiSecret
              name: crowdsec-lapi-secrets
        - name: CUSTOM_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: crowdsecurity/crowdsec:v1.6.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: lapi
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: crowdsec-lapi
        ports:
        - containerPort: 8080
          name: lapi
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: lapi
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: lapi
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      priorityClassName: null
      terminationGracePeriodSeconds: 30
```
