### ISSUE TITLE
How to patch items in `List`?

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#581]
Some times resources are defined as items in a list, e.g. https://github.com/awslabs/aws-service-operator/blob/master/configs/aws-service-operator.yaml

How shall we patch them in kustomize? 

Got an error message: `Error: failed to find an object with gvk.Gvk{Group:"apps", Version:"v1beta1", Kind:"Deployment"} to apply the patch`

When using the patch

```
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: aws-service-operator
  namespace: aws-service-operator
...
```

For the item

```
apiVersion: v1
kind: List
items:
...
- kind: Deployment
  apiVersion: apps/v1beta1
  metadata:
    name: aws-service-operator
    namespace: aws-service-operator
```

**Comment by Benjamin-Dobell** [comment]
@yujunz It's not particularly intuitive in that the official documentation quite literally [tells you to refer to the code](https://github.com/kubernetes/community/blob/master/contributors/devel/strategic-merge-patch.md).

> To solve this problem, Strategic Merge Patch uses the **go struct tag** of the API objects to determine what lists should be merged and which ones should not.

What is really means is that each resource type has a "special key" that is used as an identifier, if you specify that in your patch it will look-up based on that key. In practice it would seem that you need to specify the `patchMergeKey` as the first key-value pair in your patch.

For example, the `patchMergeKey` for a container is `name`:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2102

Thus, a patch for a `Deployment` might look like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
        - name: myapp
          image: xxxxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/mycompany/mynamespace/myapp:1.0.0
```

The above patch replaces the `image` of the container with the `name` "myapp" with the `image` value specified in this patch.

**Comment by yujunz** [comment]
Thanks @Benjamin-Dobell 

If the deployment is NOT in `List`, the patch will work as expected.

The problem is that it is wrapped in a `List`. So it fails to find the `Deployment`. And I don't know how to specify the special key for a `List`.

```
apiVersion: v1
kind: List
items: []
```

There is no metadata in a `List`, even a `name`. So it could be something needs to be handled in a different way.

**Comment by Benjamin-Dobell** [comment]
@yujunz I know it's used internally, but is `List` part of the public API?

Nonetheless, kustomize also supports a [JSON patch strategy](http://jsonpatch.com/) that can be used to achieve what you want:

**kustomization.yml**

```yaml
patchesJson6902:
  - target:
      version: v1
      kind: List
    path: patch.yml
```

**patch.yml**

```yaml
- op: replace
  path: /items/0/spec/template/spec/containers/0/image
  value: xxxxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/mycompany/mynamespace/myapp:1.0.0
```

**Comment by yujunz** [comment]
> @yujunz I know it's used internally, but is `List` part of the public API?

I think so, @Benjamin-Dobell . It is included in [Kubernetes testdata](https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/list.yaml)

> Nonetheless, kustomize also supports a [JSON patch strategy](http://jsonpatch.com/) that can be used to achieve what you want:

This could be a work around, but not precise enough. What we want is find a specified item in the list and patch it, while the workaround is targeting a hardcoded item.

**Comment by hyww** [comment]
@yujuhong This issue should be fixed by #637 , which let kustomize recognize resources/patches in `List`.

**Comment by pjanouse** [comment]
Guys,
is there something working I can use nowadays for patching a List resource via `kustomize`? It seems nothing I found and mentioned in the past years still works. (Note: Patching a list *inside* an ordinary Resource works as expected...)

```
$ kustomize version
v5.3.0

$ cat <<EOF >res-list.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Deployment
  metadata:
    name: myapp
  spec:
    foo: bar
EOF

$ cat <<EOF >kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- res-list.yaml

patches:
  - target:
      kind: List
      version: v1
    path: patch.yaml
EOF

$ cat <<EOF >patch.yaml
- op: replace
  path: /items/0/spec/foo
  value: aaarrrggghhh
EOF

$ kustomize build .
apiVersion: v1
kind: Deployment
metadata:
  name: myapp
spec:
  foo: bar
```

When I use above JSON patch syntax precisely (a solution mentioned by @Benjamin-Dobell), an error reported:
```
$ cat <<EOF >kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- res-list.yaml

patchesJson6902:
  - target:
      kind: List
      version: v1
    path: patch.yaml
EOF

$ kustomize build .
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Error: trouble configuring builtin PatchJson6902Transformer with config: `
path: patch.yaml
target:
  kind: List
  version: v1
`: must specify the target name
```

I'm looking for this result:
```
apiVersion: v1
kind: Deployment
metadata:
  name: myapp
spec:
  foo: aaarrrggghhh
```
