### ISSUE TITLE
Typos in fieldSpec do not get detected

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/kustomize#5811]
### What happened?

I had a typo in a fieldSpec, and the typo got silently ignored.

```yaml
apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: dummy
  namespace: dummy
fieldSpecs:
- path: metadata/name
  kind: Namespace
  fooooo: bar
```

### What did you expect to happen?

I expect that my yaml gets validated before it gets executed.

### How can we reproduce it (as minimally and precisely as possible)?

set-namespace.yaml

```yaml
apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: dummy
  namespace: dummy
fieldSpecs:
- path: metadata/name
  kind: Namespace
  fooooo: bar
```

### Expected output

```yaml

```

### Actual output

an error message like: 

> invalid field "fooooo"

### Kustomize version

sigs.k8s.io/kustomize/api v0.18.0

### Operating system

Linux
