### ISSUE TITLE
Better error message if replacement is invalid

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/kustomize#5814]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I get this error message:

> Error: failed to generate manifests: failed to run kustomize build for "foo/": failed to build kustomization: replacements must specify a source and at least one target

But it does not show me the filename which contains the invalid replacement.

File:

```yaml
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: certificate-namespace-replacement
replacements:
  - source:
      value: mgt-system
    targets:
      - select:
          apiVersion: cert-manager.io/v1
          kind: Certificate
        fieldPaths:
          - metadata.namespace
```  

### Why is this needed?

This is needed, so that I solve the issue faster.

### Can you accomplish the motivating task without this feature, and if so, how?

yes, somehow I will find the broken file, but this takes longer.

### What other solutions have you considered?

.

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉
