### ISSUE TITLE
Kustomize hangs on replacements with regex key-value pair and create: true 

### ISSUE THREAD

**Issue by sfbahr** [kubernetes-sigs/kustomize#5816]
### What happened?

`kustomize build` or `kubectl kustomize` both hang indefinitely

### What did you expect to happen?

Resources are output with correct replacements

### How can we reproduce it (as minimally and precisely as possible)?

I've recreated this with a minimal repo here: https://github.com/sfbahr/kustomize-replacement-bug/tree/broken

The key pieces of config are:
```yaml
replacements:
- targets:
  - fieldPaths:
    - spec.containers.[name=^logshipper$]
    options:
      create: true
```

### Expected output

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
  - command:
    - sh
    - -c
    - tail -F /opt/logs.txt
    image: alpine:latest
    name: logshipper
    restartPolicy: Always
```

### Actual output

None

### Kustomize version

v5.5.0

### Operating system

Linux
