### ISSUE TITLE
Kustomize/helmCharts: omitting helmChart.repo value does not fallback cleanly to local chartHome

### ISSUE THREAD

**Issue by DClabaut** [kubernetes-sigs/kustomize#5818]
### What happened?

This [documentation page](https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#usage-via-kustomizationyaml-11)  specifies a way to load a local Chart by omitting helmCharts.repo value and specifying helmGlobals.chartHome instead.

This method does not work, as chartHome does not appear to be taken into account at all:

### What did you expect to happen?

Helm chart should be loaded from mycharts/

### How can we reproduce it (as minimally and precisely as possible)?

Get the chart by using the valid remote repo:

```bash
$ tree -L 3
.
└── kustomization.yaml

0 directories, 1 file
````

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: mycharts

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    releaseName: harbor
    version: 1.16.0
```

```bash
$ kustomize build --enable-helm . > /dev/null
$ tree -L 3
.
├── kustomization.yaml
└── mycharts
    └── harbor-1.16.0
        ├── harbor
        └── harbor-1.16.0.tgz
```

Try to load the chart from the local custom repo by commenting helmCharts.repo:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: mycharts

helmCharts:
  - name: harbor
    #repo: https://helm.goharbor.io
    releaseName: harbor
    version: 1.16.0
```

```bash
$ kustomize build --enable-helm . > /dev/null
Error: no repo specified for pull, no chart found at ''
```

Dirty workaround: set different value for helmGlobals.chartHome, specifying one folder down:

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: mycharts/harbor-1.16.0

helmCharts:
  - name: harbor
    #repo: https://helm.goharbor.io
    releaseName: harbor
    version: 1.16.0
```

Command now runs:
```bash
$ kustomize build --enable-helm . > /dev/null
$ echo $?
0
```

### Expected output

Rendered Helm chart

### Actual output

Error: no repo specified for pull, no chart found at ''

### Kustomize version

5.5.0

### Operating system

Linux
