### ISSUE TITLE
 Name in a configMapRef is not updated to include suffix/prefix when namespace is defined

### ISSUE THREAD

**Issue by safizn** [kubernetes-sigs/kustomize#5827]
### What happened?

The same issue appears when using a **namespace** in the base `kustomization.yml`. I don't think it is intentional. 

### Issue
ConfigMap hash generated metadata.name doesn't match Deployment spec.template.spec.containers.envFrom.configMapRef.name; when base kustomization specifies a namespace.

### Reproduce
Files at: https://gist.github.com/safizn/a37f399fb2706cf8d73331f42b840ddf

_base/deployment.yml_
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template: 
    spec: 
      containers:
        - name: container
          envFrom: 
          - configMapRef:
              name: configuration
```

_base/kustomization.yml_
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- deployment.yml
namespace: A
```

_overlay/kustomization.yml_
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ../base
namePrefix: dev- 
configMapGenerator:
- name: configuration
```

### Expected result
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-configuration-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: A
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: dev-configuration-6ct58987ht
        name: container
```

### Actual result
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-configuration-6ct58987ht
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: A
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: configuration
        name: container
```

### Difference

```
$ diff with_namespace.txt without_namespace.txt 
10d9
<   namespace: A
17c16
<             name: configuration
---
>             name: dev-configuration-6ct58987ht
```

### Versions
Linux

$ `kubectly version`
Client Version: v1.32.0
Kustomize Version: v5.5.0

**Comment by safizn** [comment]
related to https://github.com/kubernetes-sigs/kustomize/issues/5047

**Comment by safizn** [comment]
**A workaround** 

_config-name-reference.yml_ 
```
nameReference:
  - kind: Service
    version: v1
    fieldSpecs:
      - kind: HTTPRoute
        path: spec/rules/backendRefs/name
        version: v1
        group: gateway.networking.k8s.io
```

_kustomization.yml_
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- gateway.yml
- http-route--web-server.yml

configurations: 
- config-name-reference.yml
```
