### ISSUE TITLE
 pass arguments down to the helm chart inflator 

### ISSUE THREAD

**Issue by wibed** [kubernetes-sigs/kustomize#5829]
### What happened?

i want to be able to pass arguments, such as `--set installCRDs=false` down to the inflator from within the command: 
`kustomize build --enable-helm --load-restrictor=LoadRestrictionsNone . | kubectl apply -f -`

how would i do this?

### What did you expect to happen?

to find a solution

### How can we reproduce it (as minimally and precisely as possible)?

it seems not to be possible

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v5.5.0

### Operating system

MacOS

**Comment by isarns** [comment]
You can pass Helm chart value overrides directly in your Kustomize manifest using the `valuesInline` field. This method lets you declare inline values that will be applied during the Helm chart rendering process, removing the need to append flags like `--set installCRDs=false` on the command line.

For example, to disable the installation of CRDs for the Kafka chart, you can configure it as follows:

```yaml
helmCharts:
  - name: kafka
    releaseName: kafka
    namespace: kafka
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      installCRDs: false
```

When you run:

```bash
kustomize build --enable-helm --load-restrictor=LoadRestrictionsNone . | kubectl apply -f -
```

Kustomize will process the inline values and pass them to the inflator, ensuring that the Helm chart is rendered with `installCRDs` set to `false`. This approach keeps your configuration fully declarative and easier to manage, especially as your deployments grow more complex.
