### ISSUE TITLE
Kustomize considers apiVersion a part of object ID, but it is not

### ISSUE THREAD

**Issue by chlunde** [kubernetes-sigs/kustomize#5843]
### What happened?

I think the ID of a object is the tuple (apiGroup/kind/metadata.name/metadata.namespace). The apiVersion is just the current schema version used to represent the object on disk or in transit.

If someone has the same apiGroup/kind/metadata.name/metadata.namespace twice, kustomize will rightfully complain. It does not complain now if the apiVersion differs.

### What did you expect to happen?

Kustomize build should fail

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# a.yaml 
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: a
spec: {}
# b.yaml 
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: a
spec: {}
# kustomization.yaml 
resources:
- a.yaml
- b.yaml
```

### Expected output

`Error: accumulating resources: accumulation err='merging resources from 'b.yaml': may not add resource with an already registered id: AuthorizationPolicy.v1.security.istio.io/a.[noNs]':`

### Actual output

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: a
spec: {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: a
spec: {}
```

### Kustomize version

master as of 2025-01-15

### Operating system

Linux
