### ISSUE TITLE
configMapGenerator unable to replace/merge ConfigMap from another Component

### ISSUE THREAD

**Issue by hylowaker** [kubernetes-sigs/kustomize#5852]
### What happened?

The `configMapGenerator` from a Component is not visible to parent configMapGenerator.

Similar issue with https://github.com/kubernetes-sigs/kustomize/issues/5836

### What did you expect to happen?

It generates a merged ConfigMap from two `configMapGenerator`, one from parent and the other from a Component.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# base/kustomization.yaml

components:
- foo/

configMapGenerator:
- behavior: merge
  literals:
  - hello=wolrd
  name: some-config
  namespace: default
```

```yaml
# base/foo/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- inner/
```

```yaml
# base/foo/inner/kustomization.yaml

configMapGenerator:
- name: some-config
  namespace: default
  literals:
  - foo=bar

generatorOptions:
  disableNameSuffixHash: true
```

Then run `kustomize build .`

### Expected output

```yaml
apiVersion: v1
data:
  foo: bar
  hello: wolrd
kind: ConfigMap
metadata:
  name: some-config
  namespace: default
```

### Actual output

```
Error: merging from generator &{0x140003f4680 <nil>}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"some-config", Namespace:"default"} does not exist; cannot merge or replace
```

### Kustomize version

v5.6.0

### Operating system

MacOS

**Comment by Mlundm** [comment]
The problem for you is the order of execution.

`resources/generators -> components -> transformers`

Your configMapGenerator with merge is applying before the component that creates the configmap.

While you could solve this by wrapping the merge into another component and placing it below the other component.

I would suggest restructuring so the configmap is created in the base/kustomization.yaml and the component moved out.

Example: 
```
# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: some-config
  namespace: default
  literals:
  - foo=bar

generatorOptions:
  disableNameSuffixHash: true
```

```
# components/configuration-a/
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- behavior: merge
  literals:
  - hello=wolrd
  name: some-config
  namespace: default
```


```
# overlays/test-a
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

components:
- ../../components/configuration-a/

```

See https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md for a bigger example.
