### ISSUE TITLE
set-based labelSelector in patches not working as in docs

### ISSUE THREAD

**Issue by danibaeyens** [kubernetes-sigs/kustomize#5854]
### What happened?

I've seen in different places of the documentation that labelSelector works following the standard label/annotation selector rules (https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md#:~:text=label/annotation%20selector%20rules) like https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md or https://github.com/kubernetes-sigs/kustomize/blob/160de8ce76c69b646ee6fb96a88d94bba4e1964a/api/types/selector.go#L25-L28

I'm defining a set of resources with a set-based label which defines the environments where I want the app to get installed, i.e.
```
metadata:
  name: my-app
  namespace: ""
  labels:
    envs:
    - prod
    - dev
 ```

Then, I have a patch like this:
```
patches:
- patch: |-
    $patch: delete
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-app
  target:
    labelSelector: 'envs notin (staging)'
```

but the resource does not get deleted. If I try with the also valid variation in the docs `'envs!=(staging)'` it returns:
`Error: unable to find patch target "[noKind].[noVer].[noGrp]/[noName].[noNs]:a=:l=envs=(staging)" in `resources`: unable to parse requirement: found '(', expected: identifier`

I think this is not supported as it's stated in the Kubernetes docs, or should I do something different?

### What did you expect to happen?

I expect the set-based labelSelectors are followed and resource gets correctly patched

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
patches:
- patch: |-
    $patch: delete
    kind: ConfigMap
    metadata:
      name: test-object
  target:
    labelSelector: 'envs notin (staging)'
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
  label:
    envs:
      - dev
      - prod
data:
  placeholder: data
```

### Expected output

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
  label:
    envs:
      - dev
      - prod
data:
  placeholder: data
```

### Actual output

It's an empty response as it gets deleted s

### Kustomize version

5.6.0

### Operating system

MacOS
