### ISSUE TITLE
Unable to handle 2+ resources kinds using `generateName:`

### ISSUE THREAD

**Issue by jessesuen** [kubernetes-sigs/kustomize#586]
If you have the following kustomization.yaml
```yaml
resources:
- pre-sync-job.yaml
- post-sync-job.yaml
```

Where both resources use `generateName:` instead of `name:`, e.g.:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: before-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
```

and
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: after-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
```

Then when running kustomize build, you get the following error:
```
$ kustomize build .
Error: loadResMapFromBasesAndResources: rawResources failed to read Resources: id '"batch_v1_Job|noNamespace|noPrefix|noName"' already used
```

When only including one of resources independently, then kustomize build works for both manifests. But when both are used at the same time, kustomize seems to consider it as a collision. I think generateName needs to be included in the key being used to detect collisions.
