### ISSUE TITLE
JSON patch add operation should add to list instead of overwriting the list.

### ISSUE THREAD

**Issue by Juastin** [kubernetes-sigs/kustomize#5860]
### Eschewed features

- [x] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

We would like the `- op: add` operation to automatically append a new item to an existing list, rather than overwriting the entire list.

Currently, when using `- op: add` in a Kustomize patch, it only adds a new item when no list is predefined in the YAML. If the list already exists (e.g., for volumes), the operation overwrites the entire list instead of appending the new item.

### Why is this needed?

The current approach requires managing multiple patch files to handle cases where lists are either predefined or need to be added. This creates unnecessary complexity, making the configuration harder to maintain and more prone to errors.

Introducing a feature that automatically appends new items to an existing list, instead of overwriting or requiring separate patches, would simplify the process and reduce boilerplate code. This improvement would make Kustomize more efficient and easier to work with, especially for common Kubernetes resources that need dynamic modifications.

### Can you accomplish the motivating task without this feature, and if so, how?

Yes, it is possible, but it requires using multiple patch files to handle the case where a list may or may not already exist.
Currently, we are using two separate patch files to manage these scenarios for our volumes and volumeMounts:
1. Patch when no volumes or volumeMounts are predefined:
```yaml 
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: tmp
      emptyDir: {}
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: tmp
      mountPath: /tmp
```
2. Patch when volumes and volumeMounts already exist, in order to append new items to the list:
```yaml
- op: add
  path: /spec/template/spec/volumes/-
  value:
      name: tmp
      emptyDir: {}
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
      name: tmp
      mountPath: /tmp
```
This approach adds unnecessary complexity and requires maintaining multiple patches to handle both scenarios. A feature that allows appending to existing lists using a single patch would simplify our configuration.

### What other solutions have you considered?

We’ve tried using StrategicMergePatch, but it has limitations. Specifically, it requires specifying the container name to apply changes, which introduces complexity when working with multiple deployment scripts. The need to explicitly define the container name prevents the patch from being dynamically applied across different configurations, making it less flexible for our use case.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉
