### ISSUE TITLE
`kustomize build .` command should be able to detect when an env variable is not defined in configmap

### ISSUE THREAD

**Issue by psshri-suki** [kubernetes-sigs/kustomize#5861]
### Eschewed features

- [x] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

If we have following file in a directory:
`deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-deployment
  template:
    metadata:
      name: dummy-deployment
      labels:
        app: dummy-deployment
    spec:
      containers:
      - name: dummy-deployment
        resources:
        image: "gcr.io/dummy-project/dummy-service-tag"
        ports:
        - containerPort: 10001
        env:
        - name: ENV_VAR_1
          valueFrom:  
            configMapKeyRef: 
              name: dummy-configmap
              key: ENV_VAR_1
        - name: ENV_VAR_2
          valueFrom:  
            configMapKeyRef: 
              name: dummy-configmap
              key: ENV_VAR_2
```

`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummy-namespace
configMapGenerator:
- name: dummy-configmap
  literals:
  - ENV_VAR_1=VALUE
resources:
  - deployment.yaml
```

And if we run the command `kustomize build .` within the directory, we will get the following output:
```yaml
apiVersion: v1
data:
  ENV_VAR_1: VALUE
kind: ConfigMap
metadata:
  name: dummy-configmap-8bkghbm66f
  namespace: dummy-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
  namespace: dummy-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-deployment
  template:
    metadata:
      labels:
        app: dummy-deployment
      name: dummy-deployment
    spec:
      containers:
      - env:
        - name: ENV_VAR_1
          valueFrom:
            configMapKeyRef:
              key: ENV_VAR_1
              name: dummy-configmap-8bkghbm66f
        - name: ENV_VAR_2
          valueFrom:
            configMapKeyRef:
              key: ENV_VAR_2
              name: dummy-configmap-8bkghbm66f
        image: gcr.io/dummy-project/dummy-service-tag
        name: dummy-deployment
        ports:
        - containerPort: 10001
        resources: null
```

When in fact, the kustomization.yaml file is missing a key `ENV_VAR_2` from the configmap definition. It would be great to have a feature in which kustomize build could check whether a environment variable is missing in the configmap definition. 

### Why is this needed?

We have GitHub workflows that runs `kustomize build .` command for each PR and if the build fails then the workflow will fail. In the scenarios like above, we do not get any kustomize build failure. If we have such a feature, then it will help teams to identify missing environment variables from configmap.

### Can you accomplish the motivating task without this feature, and if so, how?

NA

### What other solutions have you considered?

NA

### Feature ownership

- [x] I am interested in contributing this feature myself! 🎉
