### ISSUE TITLE
Replacement with regex support for selectors

### ISSUE THREAD

**Issue by sda399** [kubernetes-sigs/kustomize#5862]
### Eschewed features

- [x] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I would like to add regex support in replacement selectors

### Why is this needed?

Supporting regex in replacement selectors would:
- reduce redundancy of replacement blocks, by targeting multiple objects with regex
- harmonize replacement selectors with the [patch selectors that already support regex](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md)
- make it possible to migrate from patches to replacements

### Can you accomplish the motivating task without this feature, and if so, how?

example: replace image tag using deploy1 into depoly2, st1 and st2:

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: deploy1
spec:
  template:
    spec:
      containers:
      - image: nginx:1.27.4
        name: nginx-tagged
---
apiVersion: v1
kind: Deployment
metadata:
  name: deploy2
spec:
  template:
    spec:
      containers:
      - image: nginx:1.5
        name: nginx-tagged
---
apiVersion: v1
kind: Statefulset
metadata:
  name: st1
spec:
  template:
    spec:
      containers:
      - image: nginx:1.5
        name: nginx-tagged
---
apiVersion: v1
kind: Statefulset
metadata:
  name: st2
spec:
  template:
    spec:
      containers:
      - image: nginx:1.5
        name: nginx-tagged
```

**current solution**:
```yaml
replacements:
- source:
    kind: Deployment
    name: deploy1
    fieldPath: spec.template.spec.containers.0.image
  targets:
  - select:
      kind: Deployment
      name: deploy2
    fieldPaths:
    - spec.template.spec.containers.0.image
  - select:
      kind: StatefulSet
      name: st1
    fieldPaths:
    - spec.template.spec.containers.0.image
 - select:
      kind: StatefulSet
      name: st2
    fieldPaths:
    - spec.template.spec.containers.0.image
```

### What other solutions have you considered?

**proposed solution**:

```yaml
replacements:
- source:
    kind: Deployment
    name: deploy1
    fieldPath: spec.template.spec.containers.0.image
  targets:
  - select:
      kind: Deployment|StatefulSet
      name: deploy2|st.*
    fieldPaths:
    - spec.template.spec.containers.0.image
```

### Feature ownership

- [x] I am interested in contributing this feature myself! 🎉
