### ISSUE TITLE
nested namePrefix configuration behaviour

### ISSUE THREAD

**Issue by penekk** [kubernetes-sigs/kustomize#5870]
### What happened?

Let me begin with that I'm not entirely sure this is actually a bug but considering the unintuitive nature of this behaviour I'll go with that.

In order to get my point across let's consider this simplified (in a proper scenario there would be for example more 'bars' and more resources) structure:

Case 1:

```
apps/foo
├── bar
│   ├── ingress.yaml
│   ├── kustomization.yaml
│   ├── prefixed-resources.yaml
│   └── service-account.yaml
├── generators.yaml
├── jobs.yaml
├── kustomization.yaml
├── prefixed-resources.yaml
└── secrets.enc.yaml

```
and relevant files:

```
❯ cat apps/foo/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: foo-
namespace: apps
resources:
  - bar
  - jobs.yaml
generators:
  - generators.yaml
configurations:
  - prefixed-resources.yaml

❯ cat apps/foo/bar/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: bar-
namespace: apps
resources:
  - service-account.yaml
  - ingress.yaml

❯ cat apps/foo/prefixed-resources.yaml
namePrefix:
  - path: metadata/name
    kind: Job

❯ cat apps/foo/jobs.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  template:
    spec:
      containers: []
```

In `foo` there's a namePrefix with explicit config for kinds and in `bar` there is namePrefix applied on everything.

This results in for example Job: migrations having prefixed applied twice:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: foo-foo-migrations
  namespace: apps
spec:
  template:
    spec:
      containers: []
```

Case 2:

The difference compared to Case 1 is we do not apply prefix to Job resources in `foo` but decide to apply it to Job resources in `bar`:

```
❯ cat apps/foo/prefixed-resources.yaml
namePrefix:
  # - path: metadata/name
  #   kind: Job
  - path: metadata/name
    kind: Secret
```
```
❯ cat apps/foo/bar/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: bar-
namespace: apps
resources:
  - service-account.yaml
  - ingress.yaml
configurations:
  - prefixed-resources.yaml
```
```
❯ cat apps/foo/bar/prefixed-resources.yaml
namePrefix:
  - path: metadata/name
    kind: IngressRoute
  - path: metadata/name
    kind: ServiceAccount
  - path: metadata/name
    kind: Job
```

Which results with Job: migrations having prefix applied once but with value 'from another namePrefix configuration' (so to speak):

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: foo-migrations
  namespace: apps
spec:
  template:
    spec:
      containers: []
```

### What did you expect to happen?

Case 1:  Job should have prefix `foo` applied once.

Case 2: Job should not have any prefix applied.

Perhaps I'm misunderstanding something fundamental over here but I would've expected to be able to have a granular control over prefix transformer used but things are gettin mixed/confusing here.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Kustomize version

v5.4.1

### Operating system

Linux
