### ISSUE TITLE
Resources inherited with a namespace do not get the configMapGenerator suffix added to a config map name they refer to

### ISSUE THREAD

**Issue by szabba** [kubernetes-sigs/kustomize#5871]
### What happened?

I have 
* a base Kustomization, 
* an overlay, and 
* a component
  * adding a generated config map and 
  * mounting a file the config map it in deployments matching a label selector (this is done with a patch).

The base Kustomization (perhaps unusually) declares a namespace. The overlay and the component do not. Both the base and overlay contain deployments.

When I run `kustomize build overlays/environment`, both deployments get the patch applied. But the deployment from the base refers to `configmap`, without the hash suffix the configMapGenerator creates.

### What did you expect to happen?

Either:
* that all deployments would refer to the generated config map - including the hash suffix,
* or to easily find documentation explaining why it's not supposed to work that way.

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/szabba/kustomize-namespace-affecting-which-components-get-configmapgenerator-fixup

### Expected output

```yaml
apiVersion: v1
data:
  file.txt: Some text.
kind: ConfigMap
metadata:
  name: configmap-h9t7kcfk8f
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: base-deployment
    mount: "yes"
  name: base-deployment
  namespace: ns
spec:
  selector:
    matchLabels:
      app: base-deployment
  template:
    metadata:
      labels:
        app: base-deployment
    spec:
      containers:
      - image: nginx:latest
        name: base-deployment
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /file.txt
          name: configmap
          subPath: file.txt
      volumes:
      - configMap:
          name: configmap-h9t7kcfk8f
        name: configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: overlay-deployment
    mount: "yes"
  name: overlay-deployment
spec:
  selector:
    matchLabels:
      app: overlay-deployment
  template:
    metadata:
      labels:
        app: overlay-deployment
    spec:
      containers:
      - image: nginx:latest
        name: overlay-deployment
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /file.txt
          name: configmap
          subPath: file.txt
      volumes:
      - configMap:
          name: configmap-h9t7kcfk8f
        name: configmap
```

### Actual output

```yaml
apiVersion: v1
data:
  file.txt: Some text.
kind: ConfigMap
metadata:
  name: configmap-h9t7kcfk8f
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: base-deployment
    mount: "yes"
  name: base-deployment
  namespace: ns
spec:
  selector:
    matchLabels:
      app: base-deployment
  template:
    metadata:
      labels:
        app: base-deployment
    spec:
      containers:
      - image: nginx:latest
        name: base-deployment
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /file.txt
          name: configmap
          subPath: file.txt
      volumes:
      - configMap:
          name: configmap
        name: configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: overlay-deployment
    mount: "yes"
  name: overlay-deployment
spec:
  selector:
    matchLabels:
      app: overlay-deployment
  template:
    metadata:
      labels:
        app: overlay-deployment
    spec:
      containers:
      - image: nginx:latest
        name: overlay-deployment
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /file.txt
          name: configmap
          subPath: file.txt
      volumes:
      - configMap:
          name: configmap-h9t7kcfk8f
        name: configmap
```

### Kustomize version

v5.6.0

### Operating system

Windows
