### ISSUE TITLE
Unexpected behaviour with strategic merge patch

### ISSUE THREAD

**Issue by 23navi** [kubernetes-sigs/kustomize#5874]
When performing a $patch: delete I am getting unexpected behaviour.

api deployment config: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: nginx
          image: nginx
        - name: memcached
          image: memcached
```

kustomization.yaml

```
resources:
  - api.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        template:
          spec:
            containers:
              - $patch: delete
                name: memcached
```

When I am doing this, I am getting the container with name: memcached removed but when I change the kustomization.yaml with 

```
resources:
  - api.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        template:
          spec:
            containers:
              - $patch: delete
                image: memcached
```

It is deleting both the container 

output for 2nd kustomization.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers: []
```

both image: memcached and name: memcached can be used to match, if not how are both the containers being removed?
