### ISSUE TITLE
patches is applied in different order than patchesJson6902

### ISSUE THREAD

**Issue by ralgozino** [kubernetes-sigs/kustomize#5875]
### What happened?

I was updating a kustomize v3.10.0 project to v5.6.0. The build was running fine and gave the same output with kustomize v5.6.0 than with v3.10.0, but I got a warning that `patchesJson6902` and `commonLabels` were deprecated and I should update to `patches` and `labels` respectively.

After switching to the "new" `patches` and `labels` the output changed. A lot of debugging later, I realised that `patches` is applied **after** `labels` and `commonLabels` while `patchesJson6902` is applied **before** `labels` and `commonLabels`.

FYI: I did the migration first with `kustomize edit fix` and then manually just in case the automatic migration did something odd, but got the same result in both cases.

### What did you expect to happen?

I expected that switching from `patchesJson6902` to `patches` would give me the same result, as documented, but instead the output changed.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pod.yaml

labels:
  - pairs:
      my: value

patches:
  - target:
      kind: Pod
      version: v1
      name: myPod
    patch: |-
      - op: replace
        path: /metadata/labels
        value:
          patch: patches

#patchesJson6902:
#  - target:
#      kind: Pod
#      version: v1
#      name: myPod
#    patch: |-
#      - op: replace
#        path: /metadata/labels
#        value:
#          patch: patchesJson
```

```yaml
#pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: myPod
spec:
  containers:
    - name: dummy
      image: dummy

```

### Expected output

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    patch: patchesJson
  name: myPod
spec:
  containers:
  - image: dummy
    name: dummy
```

### Actual output

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    my: value
    patch: patches
  name: myPod
spec:
  containers:
  - image: dummy
    name: dummy
```

This is the output you get is you comment the `patches` section and uncomment the `patchesJson6902` section in the kustomization.yaml file above.

### Kustomize version

5.6.10

### Operating system

MacOS
