### ISSUE TITLE
kustomize does not write to /tmp directory

### ISSUE THREAD

**Issue by kristvanbesien** [kubernetes-sigs/kustomize#5883]
### What happened?

I ran customize with the -o option as follows:

mkdir /tmp/kustdir
kustomize build . -o /tmp/kustdir

### What did you expect to happen?

I expected a set of files /tmp/kustdir, however the directory is empty.

If I run kustomize build . -o ~/work/kustdir I do get the expected output.

So it would appear that kustomize silentlly fails to write to directories under /tmp

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```
kustomize buid . -o ~/work/kustdir
kustomize build . -o /tmp/kustdir
ls ~/work/kustdir
v1_configmap_test-object.yaml
ls /tmp/kustdir
v1_configmap_test-object.yaml
```

### Actual output

```
kustomize buid . -o ~/work/kustdir
kustomize build . -o /tmp/kustdir
ls ~/work/kustdir
v1_configmap_test-object.yaml
ls /tmp/kustdir
```

### Kustomize version

v5.3.0

### Operating system

None
