### ISSUE TITLE
NameReferenceTransformer Ignores HelmRelease targetNamespace for Cross-Namespace References

### ISSUE THREAD

**Issue by istvanballok** [kubernetes-sigs/kustomize#5884]
### What happened?

The [NameReferenceTransformer](https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v5.6.0/api/internal/accumulator/namereferencetransformer.go) fails to update ConfigMap references in a HelmRelease’s `spec.values` when the HelmRelease resides in a different namespace (e.g., flux-system) than the ConfigMap (e.g., monitoring-system), despite the HelmRelease specifying a `spec.targetNamespace` matching the ConfigMap’s namespace.

The transformer assumes the referenced resource (e.g., ConfigMap) is in the same namespace as the HelmRelease (`metadata.namespace`), ignoring `spec.targetNamespace`. This breaks common FluxCD setups where HelmRelease resources live in flux-system but target other namespaces for deployment.

When the HelmRelease and ConfigMap share the same namespace, the transformer correctly updates the reference with the generated hash suffix. In the cross-namespace case, the reference remains unchanged.

### What did you expect to happen?

The `NameReferenceTransformer` should be able to be configured to use `spec.targetNamespace`, e.g. `monitoring-system` from the `HelmRelease` to resolve the `ConfigMap` reference in `spec.values.volumes.configMap.name`, updating it to e.g. `dashboards-t757gk2bmf`, even when `metadata.namespace` is `flux-system`.

### How can we reproduce it (as minimally and precisely as possible)?

Create a directory structure with the following files:

`kustomization.yaml`:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrelease.yaml

configMapGenerator:
- name: dashboards
  namespace: monitoring-system
  literals:
  - key=value
  behavior: create

configurations:
- nameReference.yaml
```

`helmrelease.yaml`:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foo
  namespace: flux-system # the HelmRelease is in the flux-system namespace
spec:
  targetNamespace: monitoring-system # the target namespace for the underlying resource is the monitoring-system namespace
  values:
    volumes:
    - name: volumeName
      configMap:
        name: dashboards # the configMap reference refers to configMaps in the monitoring-system namespace
```

`nameReference.yaml`:

```yaml
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2
    path: spec/values/volumes/configMap/name
```

Run

```shell
kustomize build . | yaml2json | jq -s '
  map({key: "\(.kind)/\(.metadata.namespace)/\(.metadata.name)",
       value: .}) |
  from_entries
' | gron | grep '"dashboards'
```

(Requires [yaml2json](https://github.com/bronze1man/yaml2json), [jq](https://github.com/jqlang/jq) and [gron](https://github.com/tomnomnom/gron).)

```text
json["ConfigMap/monitoring-system/dashboards-t757gk2bmf"].metadata.name = "dashboards-t757gk2bmf";
json["HelmRelease/flux-system/foo"].spec.values.volumes[0].configMap.name = "dashboards";
```

The ConfigMap gets a hash suffix, but the HelmRelease reference does not.

Now, move the HelmRelease to the monitoring-system namespace:

```shell
yq -i '.metadata.namespace="monitoring-system"' helmrelease.yaml
```

Rerun the command:

```text
json["ConfigMap/monitoring-system/dashboards-t757gk2bmf"].metadata.name = "dashboards-t757gk2bmf";
json["HelmRelease/monitoring-system/foo"].spec.values.volumes[0].configMap.name = "dashboards-t757gk2bmf";
```

The reference updates correctly when namespaces match.

### Expected output

```text
json["ConfigMap/monitoring-system/dashboards-t757gk2bmf"].metadata.name = "dashboards-t757gk2bmf";
json["HelmRelease/monitoring-system/foo"].spec.values.volumes[0].configMap.name = "dashboards-t757gk2bmf";
```

### Actual output

```text
json["ConfigMap/monitoring-system/dashboards-t757gk2bmf"].metadata.name = "dashboards-t757gk2bmf";
json["HelmRelease/flux-system/foo"].spec.values.volumes[0].configMap.name = "dashboards";
```

### Kustomize version

v5.6.0

### Operating system

None
