### ISSUE TITLE
Negative Lookahead Regex Unsupported in Kustomize Patch Target

### ISSUE THREAD

**Issue by ShivamAgrawal30** [kubernetes-sigs/kustomize#5886]
### What happened?

I encountered an issue while trying to delete all resources except CustomResourceDefinition from the Confluent Helm chart using Kustomize. The approach I tried involves using a negative lookahead regex in the patches.target.kind field to exclude resources that start with CustomResourceDefinition. However, this resulted in an error.
Here is the error:

```
Error: unable to find patch target "^(?!CustomResourceDefinition).[noVer].[noGrp]/[noName].[noNs]:a=:l=" in `resources`: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```
It seems like Kustomize does not support negative lookahead syntax in regular expressions.

### What did you expect to happen?

The regex should match all resources that do not start with CustomResourceDefinition and apply the $patch: delete operation accordingly.

### How can we reproduce it (as minimally and precisely as possible)?

Step 1:  Create the following kustomization.yaml:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: confluent
helmCharts:
  - name: confluent-for-kubernetes
    version: 0.1193.1
    releaseName: confluentinc
    namespace: confluent
    includeCRDs: true
    repo: https://packages.confluent.io/helm
patches:
  - target:
      kind: "^(?!CustomResourceDefinition)"
    patch: |-
      $patch: delete
      kind: "*"
      metadata:
        name: does-not-matter
```
Step 2: Run Kustomize against the Confluent Helm chart.
```sh
kustomize build  --enable-helm --load-restrictor LoadRestrictionsNone . > output.yaml
```

### Expected output

The regex should match all resources that do not start with CustomResourceDefinition and apply the $patch: delete operation accordingly.

### Actual output

Kustomize fails with the error above, indicating that the negative lookahead syntax (?!...) is unsupported.

### Kustomize version

v5.4.3

### Operating system

MacOS

**Comment by sda399** [comment]
I think it is a limitation of golang's regex lib, no negative lookahead

https://groups.google.com/g/golang-nuts/c/7qgSDWPIh_E

**Comment by ShivamAgrawal30** [comment]
Thanks for the suggested options! Could you provide an example to clarify? That would be really helpful.

Here's what I tried:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: confluent
helmCharts:
  - name: confluent-for-kubernetes
    version: 0.1193.1
    releaseName: confluentinc
    namespace: confluent
    includeCRDs: true
    repo: https://packages.confluent.io/helm

# Step 1: Replacement to set labels and exclude CRDs from being labeled
commonLabels:
  to-remove: "true"
replacements:
  - source:
      kind: '*'
      fieldPath: metadata.labels.to-remove
    targets:
      - select:
          kind: '*'
        reject:
          - kind: 'CustomResourceDefinition'

# Step 2: JSON Patch to remove all resources with the "to-remove" label
# patches:
#   - target:
#       labelSelector: "to-remove=true"
#     patch: |-
#       $patch: delete
#       kind: "*"
#       metadata:
#         name: does-not-matter
```

However, it didn’t work as expected. I received the following error:

```
Warning: 'commonLabels' is deprecated. Please use 'labels' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
Error: nothing selected by *.[noVer].[noGrp]/[noName].[noNs]:metadata.labels.to-remove
```

**Comment by sda399** [comment]
the crds are not namespaced, so you can segregate on namespace for your deletion, no need for labels, but it depends on your needs.

 but here it is for the fun of it:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: confluent
helmCharts:
  - name: confluent-for-kubernetes
    version: 0.1193.1
    releaseName: confluentinc
    namespace: confluent
    includeCRDs: true
    repo: https://packages.confluent.io/helm

patches:
- target:
    kind: "CustomR.*"
  patch: |-
    - op: add
      path: /metadata/labels
      value: {type: crd}
- target:
    labelSelector: type!=crd
  patch: |-
    $patch: delete
    kind: "*"
    metadata:
      name: any
- target:
    kind: "CustomR.*"
  patch: |-
    - op: remove
      path: /metadata/labels

```
