### ISSUE TITLE
Image not updating for kind: RunnerDeployment

### ISSUE THREAD

**Issue by lejlapri1** [kubernetes-sigs/kustomize#5889]
### What happened?

Our kustomization.yaml is trying to use the `images` key to update the image automagically like so:
```
images:
- name: name_of_image
  newTag: new_tag
```
for a [Github Actions Controller CRD](https://github.com/actions/actions-runner-controller/blob/master/charts/actions-runner-controller/crds/actions.summerwind.dev_runnerdeployments.yaml) `kind: RunnerDeployment`
When doing a `kustomize build .`, the image isn't getting updated correctly.

The CRD has the image at the `spec.template.spec.image` level and not the `spec.template.spec.containers[].image` level that normal deployments have so kustomize doesn't update the image correctly.

### What did you expect to happen?

`kustomize build .` should update the image 

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- runner-deployment.yaml
images:
- name: docker.io/summerwind/actions-runner-controller
  newTag: new_tag
```

Doesn't update tag:
```yaml
# runner-deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: org
      image: docker.io/summerwind/actions-runner-controller:latest
      dockerdWithinRunnerContainer: true
      dockerMTU: 1500
      dockerRegistryMirror: https://mirror.gcr.io/
      labels:
        - k8s-self-hosted
        - cloud=aws
      automountServiceAccountToken: true
      serviceAccountName: github-actions-runner
```

`kustomize build .`

Does update the tag but isn't what the CRD needs: 
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: lejla
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: org
      containers:
        - name: dind
          image: docker.io/summerwind/actions-runner-controller:latest
      dockerdWithinRunnerContainer: true
      dockerMTU: 1500
      dockerRegistryMirror: https://mirror.gcr.io/
      labels:
        - k8s-self-hosted
        - cloud=aws
      automountServiceAccountToken: true
      serviceAccountName: github-actions-runner
```

`kustomize build .`

### Expected output

```
# runner-deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: lejla
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: org
      image: docker.io/summerwind/actions-runner-controller:new_tag
      dockerdWithinRunnerContainer: true
      dockerMTU: 1500
      dockerRegistryMirror: https://mirror.gcr.io/
      labels:
        - k8s-self-hosted
        - cloud=aws
      automountServiceAccountToken: true
      serviceAccountName: github-actions-runner
```
```


### Actual output

```yaml
# runner-deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      organization: org
      image: docker.io/summerwind/actions-runner-controller:latest
      dockerdWithinRunnerContainer: true
      dockerMTU: 1500
      dockerRegistryMirror: https://mirror.gcr.io/
      labels:
        - k8s-self-hosted
        - cloud=aws
      automountServiceAccountToken: true
      serviceAccountName: github-actions-runner
```

### Kustomize version

v5.0.1

### Operating system

None
