### ISSUE TITLE
Inconsistent behavior of replacements:

### ISSUE THREAD

**Issue by emirot** [kubernetes-sigs/kustomize#5899]
### What happened?

I really don't understand the behavior of replacements and it looks like a bug to me.
Let me show you how to reproduce

## Example 1 

Resources

Ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: private-http-api-ingress
  annotations:
    ns: "my-ns"
    nolan: "repalce-me"
    nginx.ingress.kubernetes.io/auth-tls-secret: "myns/"
spec:
  tls:
    - hosts:
        - test.com
```

```
resources:
 - ingress.yaml

secretGenerator:
- name: my-generated-secret
  type: Opaque
  literals:
  - username=myuser
  - password=mysecurepassword

# E.g 1 will replace result in nolan: my-generated-secret
# Same for kustomze 4.5.7 and 5.6.0
replacements:
  - source:
      kind: Secret
      name: my-generated-secret
      version: v1
    targets:
      - select:
          kind: Ingress
          group: networking.k8s.io
          version: v1
        fieldPaths:
          - metadata.annotations.nolan
```

Result

```
apiVersion: v1
data:
  password: bXlzZWN1cmVwYXNzd29yZA==
  username: bXl1c2Vy
kind: Secret
metadata:
  name: my-generated-secret-h2dm9f76k2
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: myns/
    nolan: my-generated-secret
....
```

## Example 2 

Ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: private-http-api-ingress
  annotations:
    ns: "my-ns"
    nolan: "repalce-me"
    nginx.ingress.kubernetes.io/auth-tls-secret: "myns/"
spec:
  tls:
    - hosts:
        - test.com
```

Kustomization.yaml

```
replacements:
  - source:
      kind: Secret
      name: my-generated-secret
      version: v1
    targets:
      - select:
          kind: Ingress
          group: networking.k8s.io
          version: v1
        fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/auth-tls-secret]
```

Result

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: my-generated-secret-h2dm9f76k2 
    nolan: repalce-me
    ns: my-ns
  name: private-http-api-ingress
```

Example 3:

Ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: private-http-api-ingress
  annotations:
    ns: "my-ns"
    nolan: "repalce-me"
    nginx.ingress.kubernetes.io/auth-tls-secret: "myns/"
spec:
  tls:
    - hosts:
        - test.com
```

Kustomization.yaml
```
replacements:
  - source:
      kind: Secret
      name: my-generated-secret
      version: v1
    targets:
      - select:
          kind: Ingress
          group: networking.k8s.io
          version: v1
        fieldPaths:
          - metadata.annotations.[nginx.ingress.kubernetes.io/auth-tls-secret]
        options:
          delimiter: "/" # I m adding `myns/` in the nginx annotation
          index: 1
          create: false
```

Result
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: myns/my-generated-secret
    nolan: repalce-me
    ns: my-ns
  name: private-http-api-ingress
```

### What did you expect to happen?

That the generated name will be used consistently `my-generated-secret-h2dm9f76k2 ` but instead those three examples will give 3 different outputs

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

5.6.0

### Operating system

MacOS
