### ISSUE TITLE
setup a nameReference to an array of values

### ISSUE THREAD

**Issue by FaKod** [kubernetes-sigs/kustomize#590]
I am using Istio version 1.0.4. 
A CRD called VirtualService references one or several gateways as an array. 
`einbuchen-gateway` is a Gateway resource in this case

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: einbuchen
spec:
  hosts:
  - "*"
  gateways: [einbuchen-gateway]
  http:
  . . .
```

I tried to reference this by

```yaml
nameReference:
- kind: Gateway
  fieldSpecs:
  - path: spec/gateways
    kind: VirtualService
```

but the path is expected to be a string.

Is there any way to describe something like that?
