### ISSUE TITLE
Have an optionalFiles field in secretGenerator

### ISSUE THREAD

**Issue by sei-areuter** [kubernetes-sigs/kustomize#5903]
### Eschewed features

- [x] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Not sure if many other people have faced this issue, but we have a secret that we need to mount into our kustomize deployment if it exists. If not then the deployment can disregard it. I was wondering if there would be any value in setting up something like the following in the `kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - rbac.yaml
  - deployment.yaml
configMapGenerator:
  - name: test-deployment
     files:
    - state-values.yaml
secretGenerator:
  - name: ace-secrets
    files:
    - secret-values.yaml
    optionalFiles:                   # new feature. IF any files under this key do not exist then still deploy
    - LDAP_PASSWORD=./secrets/gitlab/ldap/password
namespace: test-deployment-system
```

### Why is this needed?

If we need optional configs in our deployment depending on where our kustomizes get deployed then this is needed

Example: Gitlab has support for ldap single-sign on. We want to use this in certain environments and need to mount the password. In other environments we don't have LDAP support and don't want to use the password

### Can you accomplish the motivating task without this feature, and if so, how?

Technically yes. At the moment I am just creating a blank file. It is a hacky solution, but it would work for us

### What other solutions have you considered?

if kustomize had env support we could wrap that section so it isn't deployed (don't want to create this file with a bash script)

I know this goes against kustomize so I am not suggesting support for this solution - if there was a way to accomplish this using patching then that is a valid solution

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - rbac.yaml
  - deployment.yaml
configMapGenerator:
  - name: test-deployment
     files:
    - state-values.yaml
secretGenerator:
  - name: ace-secrets
    files:
    - secret-values.yaml
    {{ if $LDAP_ENABLED }}
   - LDAP_PASSWORD=./secrets/gitlab/ldap/password
   {{ end }}
namespace: test-deployment-system
```

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by sda399** [comment]
Hi,
I would probably try an overlay for envs with ldap support

**Comment by sei-areuter** [comment]
> Hi, I would probably go with an overlay for envs with ldap support

Could you elaborate what you mean, since kustomize doesn't have env support (or at least that is what I am told)? Our specific usecase is because we require a secret/key in a secret to exist in the cluster that is mounted into the pod if we are enabling ldap so it can be mounted into necessary deployments. 

However, I think having optional keys / cms / secrets makes sense from a feature perspective (and also fits my usecase better).

Could you provide an example of what you are talking about with env support?

**Comment by sei-areuter** [comment]
The LDAP is external to kubernetes so the gitlab-secret won't be pre-existing. Also this is just the specific usecase I was working with. There are scenarios where this is relatively common in k8s. In deployment/sts volumeMounts the following is supported. Basically I would like similar support for this in kustomize. 

```yaml
# inside container
        ...
	envFrom:
	- configMapRef:
		name: proxy
		optional: true # optional so that you can disable proxy variables by deleting proxy cm
```

I assumed having it as a seperate key would be less work on a development side
