### ISSUE TITLE
network policy rules are incorrectly updated with kustomization labels

### ISSUE THREAD

**Issue by sdickhoven** [kubernetes-sigs/kustomize#5912]
### What happened?

kustomize incorrectly updates network policy _rules_ (rather than just the `podSelector`) when using `labels` with `includeSelectors: true` or `commonLabels` in the kustomization.

### What did you expect to happen?

i expect the network policy _rules_ to remain unaltered.

### How can we reproduce it (as minimally and precisely as possible)?

`kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foo
labels:
- includeSelectors: true
  pairs:
    key1: val1
    key2: val2
- includeTemplates: true
  pairs:
    key3: val3
resources:
- netpol.yaml
```

`netpol.yaml`:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-app
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/component: controller
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - protocol: TCP
      port: 8080
```

### Expected output

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    key1: val1
    key2: val2
    key3: val3
  name: my-app
  namespace: foo
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      key1: val1
      key2: val2
```

### Actual output

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    key1: val1
    key2: val2
    key3: val3
  name: my-app
  namespace: foo
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: ingress-nginx
          key1: val1    # <<<<<<<< incorrect!!!
          key2: val2    # <<<<<<<< incorrect!!!
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
          key1: val1    # <<<<<<<< incorrect!!!
          key2: val2    # <<<<<<<< incorrect!!!
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      key1: val1
      key2: val2
```

### Kustomize version

v5.6.0

### Operating system

None

**Comment by sda399** [comment]
the default list includes those paths to podselectors. I guess you can overcome that with some reorganization of your netpol files.

**Comment by sdickhoven** [comment]
sure... i'm aware that this is an option.

but if i have a kustomization with 50 different resources (`Deployment`s, `ServiceAccount`s, `NetworkPolicy`s, `PodDisruptionBudget`s, `Ingress`es, `Service`s, `ServiceMonitor`s, ...) it becomes a bit tedious to spec out _all_ label fields that i want modified.

kustomize modifying a `NetworkPolicy`'s ingress and egress rules is simply nonsensical since those typically have _nothing_ to do with the resources being kustomize'd at all... except in rare edge cases when i need a network policy that allows traffic from all pods of a `StatefulSet` to themselves for some kind of cluster sync traffic.

it would make much more sense if i had to do something out of the ordinary for such a rare setup vs for something that is the norm: allow traffic from/to _different_ workloads to/from the workload i'm kustomize'ing.

...just my opinion. 🤷 

but i realize that there's probably no way to do this in a way that won't break existing kustomizations that rely on this odd behavior. 😞 

so feel free to close this issue. i just wanted to point out that this behavior is a bit... suboptimal. 🤷

**Comment by sdickhoven** [comment]
actually, come to think of it... i guess the following could be done to make this change backward compatible.

just like `includeSelectors` and `includeTemplates`, a new behavior modifier could be introduced. e.g.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foo
labels:
- includeSelectors: true
  includeNetworkPolicyIngressRules: false # default to `true`
  includeNetworkPolicyEgressRules: false # default to `true
  pairs:
    key1: val1
    key2: val2
- includeTemplates: true
  pairs:
    key3: val3
resources:
- netpol.yaml
```

it's kinda kludgy but it's the only thing i can think of to disable the less-than-perfect existing behavior in a backward-compatible way. 🤷
