### ISSUE TITLE
Is not available for linux/amd64

### ISSUE THREAD

**Issue by GNURub** [kubernetes-sigs/kustomize#5919]
### What happened?

Run curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
  
Version  does not exist or is not available for linux/amd64.
Error: Process completed with exit code 1.

### What did you expect to happen?

install for linux/amd64.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml

```

### Actual output

```yaml
Version  does not exist or is not available for linux/amd64.
Error: Process completed with exit code 1.
```

### Kustomize version

master

### Operating system

None
