### ISSUE TITLE
fileloader: Add support for query parameters

### ISSUE THREAD

**Issue by logand22** [kubernetes-sigs/kustomize#5925]
### Eschewed features

- [x] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I would like to add the ability to specify query parameters when using a remote path in the `configMapGenerator` or the `secretGenerator`. 

### Why is this needed?

The `configMapGenerator` and `secretGenerator` both support specifying a remote path. This can be used to retrieve content before generating a configMap or secret. 

For instance:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
configMapGenerator:
  - name: rds-ca
    files:
      - ca.pem=https://truststore.pki.rds.amazonaws.com/us-west-2/us-west-2-bundle.pem
```

Allows creating a configMap whose contents contain the pem-encoded certificate authority for AWS RDS. However, some endpoints support query parameters that can change the output format of requested content. 

### Can you accomplish the motivating task without this feature, and if so, how?

 I could just download and apply the contents manually. 

### What other solutions have you considered?

N/A

### Anything else we should know?

N/A

### Feature ownership

- [x] I am interested in contributing this feature myself! 🎉
