### ISSUE TITLE
Annotations from Base Service Removed When Referenced in Overlay

### ISSUE THREAD

**Issue by NitishGupta9282** [kubernetes-sigs/kustomize#5929]
### What happened?

I’m experiencing an issue where annotations defined on a Kubernetes Service resource in my base directory are removed when I reference that Service in an overlay.

### Base Service Example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    example.com/annotation1: "value1"
    example.com/annotation2: "value2"
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

No patches or changes to annotations in overlay.

### What did you expect to happen?

Annotations defined in the base Service should be preserved when building the overlay.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    example.com/annotation1: "value1"
    example.com/annotation2: "value2"
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```

### Actual output

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    <no-annotations of base>
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```

### Kustomize version

 v5.4.3 2024-07-19T16:40:33Z

### Operating system

Linux
