### ISSUE TITLE
SecretGenerator namespace

### ISSUE THREAD

**Issue by rdubya16** [kubernetes-sigs/kustomize#595]
I am using kustomize to manage kube-prometheus. This project contains resources in multiple namespaces. I need to override a secret within the project that represents alertmanager.yaml

```
secretGenerator:
- name: alertmanager-main
  behavior: replace
  commands:
    alertmanager.yaml: "cat configs/alertmanager.yaml"
  type: Opaque
```

When I set kustomize to replace the secret I get a generated secret that doesn't match the namespace of the initial resource. I can't set a global namespace because it overrides base resources that need to stay in the kube-system namespace. Is there a better way to handle this situation?

**Comment by tomaszkiewicz** [comment]
Hi, 

I've raised PR that adds namespace argument to secret and config map generators, which I hope resolves your problem.

Best regards

Łukasz Tomaszkiewicz

**Comment by Liujingfang1** [comment]
@rdubya16 @tomaszkiewicz Sorry for delayed response on this issue. You can use `namespace` in the kustomization.yaml. It will set the namespace of the generated secret. Will that work for you?

**Comment by rdubya16** [comment]
@liuhuiping2013 unfortunately namespace overrides all resources with the new namespace. Some of the resources need to be installed into kube-system

**Comment by Liujingfang1** [comment]
@rdubya16 Can you separate the resources by putting the ones with the same namespace into one kustomization.yaml?

**Comment by tomaszkiewicz** [comment]
@rdubya16 Have you checked my PR solution? It allows you to add you a namespace parameter for each secret/cm generator like that:

```
secretGenerator:
- name: the-non-default-namespace-secret
  namespace: non-default
  commands:
    password.txt: "cat password.txt"
- name: the-secret
  commands:
    password.txt: "cat password.txt" 
```

I haven't checked how it interacts with replace feature of generator because I didn't have time for it today, but I think it's a way to go to resolve problems like that.

Best regards

Łukasz Tomaszkiewicz
