### ISSUE TITLE
generatorOptions in different bases are ignored

### ISSUE THREAD

**Issue by UrbanInvader** [kubernetes-sigs/kustomize#597]
https://github.com/kubernetes-sigs/kustomize/issues/489#issuecomment-438043074
> You can put the secrets into different bases, each base with a different generatorOptions

When trying this out it doesn't seem to work:
```
> kustomize version
Version: {KustomizeVersion:1.0.11 GitCommit:8f701a00417a812558a7b785e8354957afa469ae BuildDate:2018-12-04T18:42:24Z GoOs:unknown GoArch:unknown}
```
```
> cat kustomization.yaml
bases:
- subdir
generatorOptions:
  disableNameSuffixHash: false
configMapGenerator:
- name: shouldHaveHash
  files:
  - shouldHaveHash.yaml

> cat subdir/kustomization.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: shouldNotHaveHash
  files:
  - shouldNotHaveHash.yaml
```
```
> kustomize build
apiVersion: v1
data:
  shouldHaveHash.yaml: |
    asdssssf
kind: ConfigMap
metadata:
  name: shouldHaveHash-h9gm2m2g6m
---
apiVersion: v1
data:
  shouldNotHaveHash.yaml: |
    asdf
kind: ConfigMap
metadata:
  name: shouldNotHaveHash-2857gh5t27
```

**Comment by suzutan** [comment]
@Liujingfang1 Are you planning to fix this issue?

**Comment by Liujingfang1** [comment]
`generatorOptions` have following fields:
```
generatorOptions:
  # labels to add to all generated resources
  labels:
    kustomize.generated.resources: somevalue
  # annotations to add to all generated resources
  annotations:
    kustomize.generated.resource: somevalue
  # timeoutSeconds specifies the timeout for commands
  timeoutSeconds: 30
  # shell and arguments to use as a context for commands used in resource
  # generation. Default at time of writing: ["sh", "-c"]
  shell: ["sh", "-c"]
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true
```
Among them, `labels`, `annotations`, `timeoutSeconds` and `shell` are effective when generating ConfigMap or Secret. Thus it is not a problem for those fields. The issue only comes in `disableNameSuffixHash`.

I will work on a fix for this.
