### ISSUE TITLE
Support for rewriting API versions

### ISSUE THREAD

**Issue by sascha-coenen** [kubernetes-sigs/kustomize#61]
Given a base with a resource with a given kubernetes API version (lets say a statefulset with API version app/v1beta1), there seems to be no way to patch this API version within an overlay

I cannot use a patch to rewrite the API version because patches already use the API version to match a resource in the first place. 

To make migrating between Kubernetes versions easier, perhaps it would be quite useful to have another common section to redefine the resource versions within the kustomization.yaml:

```
namePrefix: test-
namespace: test
commonAPIVersions:
  statefulset: apps/v1
  service: v1
  deployment: v1
```

This would replace the existing API versions with new ones.

The reason for requesting this feature, is that I have started creating a directory tree with bases and overlays. It seems necessary to group the "base" directory structure by system/version/subsystem/app, like druid/0.9.2/platform/zookeeper

For the usecase of migrating from one kubernetes version to another or from an outdated manifest to a newer one, I would have to either completely rewrite the base tree which would be disruptive for the overlays, or I would have to organize the base tree by kubernetes version as well application version which is making these directory trees deep and complex.

**Comment by ryanquinn3** [comment]
This would be really useful when using a rendered helm chart as a base for kustomize.

**Comment by sascha-coenen** [comment]
/remove-lifecycle stale

I think several people liked the proposal by voting for it and there were no alternative suggestions so far, so I believe the issue is still relevant until it has received more discussion.

**Comment by reith** [comment]
@sascha-coenen JSON patches served me well as an alternative. Though I liked to have altered API version in next SMPs but it wasn't a big deal for me.

**Comment by unkls** [comment]
Is it still plan ?

**Comment by afirth** [comment]
@reith put the breadcrumb i needed

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
[...]
patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: rbac.authorization.k8s.io/v1beta1
  target:
    group: rbac.authorization.k8s.io
    version: v1
    labelSelector: "app.kubernetes.io/managed-by=Helm"
```

much obliged

**Comment by edrandall** [comment]
@afirth @reith Thankyou for the hint - the magic incantation which worked for me was:

```
# rbac.authorization.k8s.io/v1beta1 was removed from k8s 1.22
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1beta1
      kind: 'Role|RoleBinding|ClusterRole|ClusterRoleBinding'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: rbac.authorization.k8s.io/v1
```
