### ISSUE TITLE
Generated secret name references are not detected in projected volumes

### ISSUE THREAD

**Issue by richardmarshall** [kubernetes-sigs/kustomize#613]
This is a similar issue to #153 but specific to secrets instead.

When using kustomize to generate secrets that will be used in a projected volume the name hash suffix is not correctly added.

kustomization.yaml
```yaml
...
secretGenerator:
- commands:
    foo: echo bar
  name: test-secret
  type: Opaque
...
```

deployment volume definition:
```yaml
      ...
      volumes:
      - name: projected-secret-volume
        projected:
          sources:
          - secret:
              items:
              - key: foo
                path: foo
              name: test-secret
      ...
```

After running build the secret name in the projected volume does not have the hash suffix added.
