### ISSUE TITLE
Allow empty resource names in base templates

### ISSUE THREAD

**Issue by mkokho** [kubernetes-sigs/kustomize#627]
Use case: one deployment base for different deployments to control probes, port, resource allocaitons, annotations, etc.

For example, here is a base deployment template:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ""
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
```

With simple customization I could have templates with different names:
```
bases:
  - ../base
namePrefix: analyzer
```

```
bases:
  - ../base
namePrefix: processor
```

Now with version 1.11, it is required to have non-empty name in the base, so all of the resource will have a common suffix that has no meaning. But in version 1.10, the above structure worked.
