### ISSUE TITLE
namespace breaks namePrefix and nameSuffix for volumeName in PersistentVolumeClaim

### ISSUE THREAD

**Issue by JasperZ** [kubernetes-sigs/kustomize#657]
When using `namespace` in *kustomization.yaml* there is a problem related to PersistentVolume name  referenced in the PersistentVolumeClaim. The `namePrefix` and `nameSuffix` specified in the *kustomization.yaml* aren't applied to the `volumeName` field of the PersistentVolumeClaim.

My guess would be that it has something to to with the fact that a PersistentVolume mustn't have a namespace but PersistentVolumeClaim can have one.

If I comment out the `namespace` in *kustomization.yaml* everything works as expected!

## Version ##
```
$ kustomize version                                                                                                                                                                                                
Version: {KustomizeVersion:1.0.11 GitCommit:8f701a00417a812558a7b785e8354957afa469ae BuildDate:2018-12-04T18:42:24Z GoOs:unknown GoArch:unknown}
```

## Files for reproduction ##
```
$ tree
.
└── test_volume
    ├── kustomization.yaml
    ├── persistentVolumeClaim.yaml
    └── persistentVolume.yaml
```

*kustomization.yaml*
```
namespace: default

namePrefix: namePrefix-
nameSuffix: -nameSuffix

resources:
- persistentVolume.yaml
- persistentVolumeClaim.yaml
```

*persistentVolume.yaml*
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nfsvers=3
  nfs:
    path: /nfs/path
    server: nfs.server.example
```

*persistentVolumeClaim.yaml*
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: test-volume
```
## Build output ##
```
$ kustomize build
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namePrefix-test-volume-nameSuffix
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  mountOptions:
  - nfsvers=3
  nfs:
    path: /nfs/path
    server: nfs.server.example
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namePrefix-test-volume-nameSuffix
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: test-volume
```

### Expected ###
`volumeName` of the PersistentVolumeClaim *namePrefix-test-volume-nameSuffix* is:
```volumeName: namePrefix-test-volume-nameSuffix```
**NOT**
```volumeName: test-volume```
