### ISSUE TITLE
nameref does not work with nested bases

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#662]
```
cat <<'EOF' > example/kustomization.yaml
bases:
- base

secretGenerator:
- commands:
    HELLO: printf 'world'
EOF
```
```
cat <<'EOF' > example/base/kustomization.yaml
bases:
- otherbase
EOF
```
```
cat <<'EOF' > example/base/otherbase/kustomization.yaml
resources:
- deployment.yaml
EOF
```
```
cat <<'EOF' > example/base/otherbase/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - name: example
        image: example
        envFrom:
        - secretRef:
            name: example
EOF
```

The output looks like this

```
apiVersion: v1
data:
  HELLO: d29ybGQ=
kind: Secret
metadata:
  name: example-c89hbk9m56
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: example
        image: example
        name: example
```

It should look like this 

```
apiVersion: v1
data:
  HELLO: d29ybGQ=
kind: Secret
metadata:
  name: example-c89hbk9m56
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: example-c89hbk9m56
        image: example
        name: example
```

**Comment by jcassee** [comment]
The reference to the secret appears in a base that does not define the secret. If you create the secret in `example/base/otherbase/kustomization.yaml` and [merge it](https://github.com/kubernetes-sigs/kustomize/blob/6f566d7a38cffcbb74a2ca2d762f8fbd65055d44/examples/combineConfigs.md) in `example/kustomization.yaml` I believe your code will work.

**Comment by Liujingfang1** [comment]
@sethpollack It should work. Can you try version 1.0.11?

**Comment by sethpollack** [comment]
@Liujingfang1 Ok you are correct. The issue is not the nested bases, it breaks when you add a namePrefix.

```
cat <<'EOF' > kustomization.yaml
apiVersion: v1beta1
kind: Kustomization

bases:
- base

secretGenerator:
- commands:
    HELLO: printf 'world'
  name: example
EOF
```

```
cat <<'EOF' > base/kustomization.yaml
apiVersion: v1beta1
kind: Kustomization

namePrefix: foo-

resources:
- deployment.yaml
EOF
```
```
cat <<'EOF' > base/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - name: example
        image: example
        envFrom:
        - secretRef:
            name: example
EOF
```

**Comment by valer-cara** [comment]
@sethpollack, @jcassee is right - adding a generator to the base, using the same name and merging from higher-level layers works, even if `namePrefix` is provided.


```
R=$(mktemp -d /tmp/kustomizetest.XXXXXXX)
mkdir -p $R/base/

cat <<HERE > $R/base/deploy.yaml
kind: Deployment
metadata:
  name: foobar
spec:
  template:
    spec:
      containers:
      - name: foobar
        image: busybox
        envFrom:
        - secretRef:
            name: xxx
        - configMapRef:
            name: yyy
HERE

cat <<HERE > $R/base/kustomization.yaml
resources:
- ./deploy.yaml
namePrefix: lalala-

secretGenerator:
- name: xxx
  literals:
  - password=123456
HERE

cat <<HERE > $R/kustomization.yaml
resources:
- ./base

secretGenerator:
- name: xxx
  behavior: merge
  literals:
  - password=12345699999

configmapGenerator:
- name: yyy
  literals:
  - password=123456
HERE

kustomize build $R
```

**Comment by jbrette** [comment]
@sethpollack @Liujingfang1 [PR 1378](
https://github.com/kubernetes-sigs/kustomize/pull/1378) is solving the issue

Reproduce the [environment here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0662_b)

When issuing 3.0.3
```bash
$HOME/bin/kustomize.3.0.3 build .
```

```yaml
apiVersion: v1
data:
  HELLO: d29ybGQ=
kind: Secret
metadata:
  name: example-5cm72hhtk8
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo-example
spec:
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: example
        image: example
        name: example
```

When using 3.0.3 + PR1378
```bash
$HOME/bin/kustomize.PR1378 build .
```

```yaml
apiVersion: v1
data:
  HELLO: d29ybGQ=
kind: Secret
metadata:
  name: example-5cm72hhtk8
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foo-example
spec:
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: example-5cm72hhtk8
        image: example
        name: example
```

**Comment by jbrette** [comment]
@valer-cara I think that [PR](https://github.com/kubernetes-sigs/kustomize/pull/1378). If we use your example, without the PR the configMapRef is wrong and does not contain the hash. With the PR the configMapRef is correct.

```bash
$HOME/bin/kustomize.3.0.3 build .
```

```yaml
apiVersion: v1
data:
  password: "123456"
kind: ConfigMap
metadata:
  name: yyy-bkfmbb8t66
---
apiVersion: v1
data:
  password: MTIzNDU2OTk5OTk=
kind: Secret
metadata:
  annotations: {}
  labels: {}
  name: lalala-xxx-ctd2ckb7h7
type: Opaque
---
kind: Deployment
metadata:
  name: lalala-foobar
spec:
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: lalala-xxx-ctd2ckb7h7
        - configMapRef:
            name: yyy
        image: busybox
        name: foobar
```

```bash
$HOME/bin/kustomize.PR1378 build .
```
```yaml
apiVersion: v1
data:
  password: "123456"
kind: ConfigMap
metadata:
  name: yyy-bkfmbb8t66
---
apiVersion: v1
data:
  password: MTIzNDU2OTk5OTk=
kind: Secret
metadata:
  annotations: {}
  labels: {}
  name: lalala-xxx-ctd2ckb7h7
type: Opaque
---
kind: Deployment
metadata:
  name: lalala-foobar
spec:
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: lalala-xxx-ctd2ckb7h7
        - configMapRef:
            name: yyy-bkfmbb8t66
        image: busybox
        name: foobar
```
