### ISSUE TITLE
namespace lost when replacing configMap in an overlay

### ISSUE THREAD

**Issue by ryane** [kubernetes-sigs/kustomize#672]
```
$ kustomize version
Version: {KustomizeVersion:1.0.11 GitCommit:8f701a00417a812558a7b785e8354957afa469ae BuildDate:2018-12-04T18:42:24Z GoOs:unknown GoArch:unknown}
```

```
mkdir -p base overlays/dev
```

```
cat <<'EOF' > base/kustomization.yaml
apiVersion: v1beta1
kind: Kustomization
namespace: testing
resources:
- deployment.yaml
configMapGenerator:
- name: example-config
  literals:
  - CONFIG=base-config
EOF
```

```
cat <<'EOF' > base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: example
        envFrom:
        - configMapRef:
            name: example-config
EOF
```

```
cat <<'EOF' > overlays/dev/kustomization.yaml
apiVersion: v1beta1
kind: Kustomization
bases:
- ../../base
configMapGenerator:
- name: example-config
  behavior: replace
  literals:
  - CONFIG=dev-config
EOF
```

Here is the output (looks like the log entry in the first line is fixed in master):

```
$ kustomize build overlays/dev
2018/12/28 20:50:52 Replace map[kind:ConfigMap apiVersion:v1 metadata:map[name:example-config namespace:testing] data:map[CONFIG:base-config]] with map[kind:ConfigMap apiVersion:v1 metadata:map[name:example-config] data:map[CONFIG:dev-config]]
apiVersion: v1
data:
  CONFIG: dev-config
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: example-config-d6m969h8m5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: testing
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-config-d6m969h8m5
        image: example
        name: example
```

Note that the example-config-* configmap does not have `namespace: testing` in the metadata. If you run `kubectl build overlays/dev | kubectl apply -f -`, you'll end up with an example-config-* configmap in the default namespace (or whatever namespace is set in your current kubectl context).

```
$ kubectl -n testing get deploy,cm
NAME                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/example   1         1         1            0           1m

$ kubectl -n default get deploy,cm
NAME                                  DATA      AGE
configmap/example-config-d6m969h8m5   1         4m
```

In this simple example, I could fix this by redundantly adding `namespace: testing` to `overlays/dev/kustomization.yaml`. However, this wouldn't work in an overlay that composes multiple bases that have different `namespace` kustomizations.

**Comment by Liujingfang1** [comment]
When "replace" is used, the ConfigMap created in the overlay will replace the ConfigMap from the base. I don't think this is a bug. It is the expected behavior to me.

You can use following syntax to fine control the namespace. In #599, `namespace` was added to generators, which allows users to specify the namespace of ConfigMaps/Secrets from generators.
You can use it like
```
configMapGenerator:
- name: example-config
  namespace: you-name-it
  literals:
  - CONFIG=dev-config
```
Note that when `namespace` is not specified, it is "default".
