### ISSUE TITLE
Error: json: unknown field "namespace"

### ISSUE THREAD

**Issue by infinitydon** [kubernetes-sigs/kustomize#676]
Hi,

I am trying to generate secret using the following:

```
- name: production_app_secret
  namespace: production
  # timeoutSeconds specifies the number of seconds to
  # wait for the commands below. It defaults to 5 seconds.
  timeoutSeconds: 30
  commands:
    vgs_username: "../_global/make-scripts/handle_secrets.sh --get=vgs_username"
    vgs_password: "../_global/make-scripts/handle_secrets.sh --get=vgs_password"
  type: Opaque

```
But when I run "kustomize build" I am getting the following error:

$ kustomize build

**Error: json: unknown field "namespace"**

Also why is kustomize appending random characters to the name of the secret that is been generate, e.g. production_app_secret became:

```
kind: Secret
metadata:
  name: production_app_secret-m4t5khhbg6
type: Opaque
```
Anyway to make to prevent it from appending the name?

Thanks
