### ISSUE TITLE
commonLabels creates volumeClaimTemplates in StatefulSet

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#677]
Setting commonLabels on a StatefulSet creates a malformed volumeClaimTemplates populated with metadata containing the labels (it shouldn't have this).

Version: commit:746c7b0b5b6c7661c160cdeb62390ef0bb5ac4fe (Dec 30, 2018)

Steps to reproduce:

Run `kustomize build ./`

> kustomization.yaml

```yaml
commonLabels:
  api: crew.example.com
resources:
- manager/manager.yaml
```

> manager/manager.yaml

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SECRET_NAME
            value: $(WEBHOOK_SECRET_NAME)
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret
```

output:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    api: crew.example.com
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: controller-manager
spec:
  selector:
    matchLabels:
      api: crew.example.com
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        api: crew.example.com
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: $(WEBHOOK_SECRET_NAME)
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret
  volumeClaimTemplates: # this shouldn't exist
    metadata:
      labels:
        api: crew.example.com
```
