### ISSUE TITLE
vars do not work on `mountPath` nor in `labels`

### ISSUE THREAD

**Issue by narg95** [kubernetes-sigs/kustomize#682]
Hi all,

`vars` are not replaced in `mountPath`:

I have the following yaml files:

`kustomize.yaml`
```
resources:
- deployment.yaml
- namespace.yaml

vars:
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: Namespace
    name: my-namespace
```

`deployment.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment 
  labels:
    my-label: $(NAMESPACE) # Here
spec:
  template:
    spec:
      containers:
      - name: app
        image: busybox
        volumeMounts:
        - name: my-volume
          mountPath: "/$(NAMESPACE)" # Here
        env:
        - name: NAMESPACE
          value: $(NAMESPACE) # And here
      volumes:
      - name: my-volume
        emptyDir: {}
```

`namespace.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
```

When I run `kustomize build .` I get the following output:

```
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    my-label: $(NAMESPACE) # NOT replaced
  name: my-deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: my-namespace # REPLACED
        image: busybox
        name: app
        volumeMounts:
        - mountPath: /$(NAMESPACE) # NOT replaced
          name: my-volume
      volumes:
      - emptyDir: {}
        name: my-volume

```

As you can notice the `env` gots correctly replaced but on `mountPath` and `labels` did not.

Kustomize version: `1.0.11`

Thanks!

**Comment by monopole** [comment]
Excellent bug report!

Those fields (labels and container mountPath) aren't supported as a home for $VARs.

I just tweaked the doc (https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml#L215)

Suggest you get what you want working as a [custom config](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md) (there might be trouble doing that - don't have the time to check), and then send out a PR to add your work to the [default config](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/varreference.go).

Labelling this as a feature request

**Comment by narg95** [comment]
@monopole

> Excellent bug report!

Great you like it!

> Suggest you get what you want working as a custom config (there might be trouble doing that - don't have the time to check), and then send out a PR to add your work to the default config.

thanks for the hint,  I will give it a try and then submit a PR

**Comment by narg95** [comment]
Hi @monopole,

for `mountPath` I managed to do it #761 , but for labels seems a bit trickier and harder to fix since the path varies and I do not know how to correctly target it, see in my example the `path` is `metadata/labels/my-label`, I can target `metadata/labels` but the `my-label` is dynamic.  

If it is an easy fix I'll do it otherwise I can easily live without it,  since the `mounthPath` is what really matters in my case.

**Comment by Liujingfang1** [comment]
The `labels` and `annotations` are different from other paths since they are maps and the keys are unknown. Currently Kustomize doesn't have a way to handle $vars in those fields even you add them in a custom config.  

The idea from #610 might be useful. It is proposed to handle array fields.

**Comment by narg95** [comment]
@Liujingfang1
Hi, thanks for the info. Actually I took a look to the code and it turn out to be easy to add support for `map[string]interface{}` without adding any special mark to the path. Check PR  #782

**Comment by Liujingfang1** [comment]
fixed by #761 and #782

**Comment by srfrnk** [comment]
The fix looks like it handles only top level objects.
Using the following to replace the original `deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    my-label: $(NAMESPACE) # Here
spec:
  template:
    metadata:
      labels:
        my-label: $(NAMESPACE) # Here
    spec:
      containers:
      - name: app
        image: busybox
        volumeMounts:
        - name: my-volume
          mountPath: "/$(NAMESPACE)" # Here
        env:
        - name: NAMESPACE
          value: $(NAMESPACE) # And here
      volumes:
      - name: my-volume
        emptyDir: {}
```

You get:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    my-label: my-namespace
  name: my-deployment
spec:
  template:
    metadata:
      labels:
        my-label: $(NAMESPACE)
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: my-namespace
        image: busybox
        name: app
        volumeMounts:
        - mountPath: /my-namespace
          name: my-volume
      volumes:
      - emptyDir: {}
        name: my-volume
```

**Note the `$(NAMESPACE)` not replaced correctly**
