### ISSUE TITLE
Can't define the same VAR in multiple bases 

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#696]
```
cat <<'EOF' > kustomization.yaml
apiVersion: v1beta1
kind: Kustomization

bases:
- base1
- base2
EOF
```
```
cat <<'EOF' > base1/kustomization.yaml
apiVersion: v1beta1
kind: Kustomization

configMapGenerator:
- literals:
  - MY_ENV=foo
  name: example1

vars:
- fieldref:
    fieldPath: data.MY_ENV
  name: MY_ENV
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: example1
EOF
```
```
cat <<'EOF' > base2/kustomization.yaml
apiVersion: v1beta1
kind: Kustomization

configMapGenerator:
- literals:
  - MY_ENV=foo
  name: example2

vars:
- fieldref:
    fieldPath: data.MY_ENV
  name: MY_ENV
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: example2
EOF
```

This gets the following error:

```
Error: base2: var MY_ENV already encountered
```
