### ISSUE TITLE
Support for using SealedSecrets

### ISSUE THREAD

**Issue by chrishiner** [kubernetes-sigs/kustomize#702]
I'd like to use something like the SecretGenerator to create SealedSecrets from files, with the automatic name hashing. These SealedSecrets are encrypted with a public key, and the controller in the cluster has the private key and automatically generates a corresponding Secret after decrypting it.
See https://github.com/bitnami-labs/sealed-secrets for how that part works.

That way I can check the encrypted secret into my source control repo with all the other objects instead of having to maintain yet another set of configuration someplace else.

I'd envision something very much like the configMapGenerator, something like:
```
sealedSecretGenerator:
- name: mysecret
  files:
    - secretfile.yaml
```

Or even just:
```
sealedSecretGenerator:
- name: mysecret
patches:
- secretfile.yaml
```

**Comment by MatteoJoliveau** [comment]
Agree, this would be extremely helpful

**Comment by fentas** [comment]
We use https://git-secret.io to de/encrypt secrets.
I don't know if this suits everybody. Decryption happens within git repo not k8s but could be an option?

**Comment by pst** [comment]
For reference, something to consider: https://github.com/bitnami-labs/sealed-secrets/issues/68#issuecomment-351579064

**Comment by kwladyka** [comment]
Workaround? How do you deal with it today?

**Comment by chrishiner** [comment]
I hacked something into kustomize that does most of what I want. Basically just a version of secretfactory that knows what a sealedsecret looks like.
I have not rebased it lately.
Still trying to see if I can jump through the hoops to get our legal department to let me share it.
I am currently using the cluster-wide annotation to keep it from breaking when the hash gets appended to the name.

I like sealed-secrets because the group that creates the accounts can encrypt the credentials with the correct key for the cluster and just hand the output to our developers to put with the application code along with the rest of their k8s configuration. Commit all the things.

**Comment by kwladyka** [comment]
I would like to solve 2 things for sealed secrets:
- unique names like for Secrets generating. It makes easy Pods reloading after change Secrets.
- easy edit / update secrets values. I don't want to generate all the time whole file while I don't know current state. I want to change something and I want to be sure I am changing only this one value. So it will need probably also `base` on original `kustomization.yaml`. In that way I can keep secrets in another path where only I have access. But here is an issue about namespace. While generating sealed secret there is no namespace provided yet, because it is in `base`. If I provide namespace here, than I will overwrite original namespace which I don't want to touch.

I feel sealed secrets are cool, but using it is very uncomfortable at that moment. I wish to have easy and simple way for updating this secrets. Also solved issue reloading pods when secrets changing. Which is solved with Secrets by unique name depend on values.

**Comment by ptemmer** [comment]
Today I was looking into exactly something as described in this issue. When adding the sealed secrets directly as resource, you miss out on the nice feature of the secretGenerator that forces a redeploy of all  deployments that depend on this particular generated secret. Someone was able to make this work already, and is able to share it?

As a side note @kwladyka, funny that I bump into you everywhere! :-)

**Comment by fentas** [comment]
As for now. The best way to solve this is to create a  kustomize plugin. I've created one for generating random password secret files. Works quiet well.

**Comment by ptemmer** [comment]
Can you elaborate @fentas? Does it work with v2.0?

**Comment by fentas** [comment]
There is no release including this feature (working on master here).
Have a look at these plugins here. Has also a nice description of how to use them.

https://github.com/goabout/goabout-kustomize-plugins

**Comment by glerchundi** [comment]
@fentas this is a fantastic approach, thanks for sharing! We were evaluating to replace our jsonnet specs with kustomize and we discarded just because of this...which is now somehow easily achievable.

**Comment by jcassee** [comment]
> There is no release including this feature (working on master here).
> Have a look at these plugins here. Has also a nice description of how to use them.
> 
> https://github.com/goabout/goabout-kustomize-plugins
> 
> **edit:** I do not know if this version of plugins (`kvSource`) will be supported in the future as this was removed in https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins.md

I wrote these and still use them, but they are no longer relevant. The key-value plugin system has been removed, and the way to go is now to use generator plugins. See this great example by Jeff Regan:

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/goPluginGuidedExample.md

**Comment by lopezator** [comment]
I am still interested on this and I think it would be a great addition.

**Comment by posquit0** [comment]
I used the trick like below. It works well in my case.

```yaml
# kustomization.yaml
...
patchesStrategicMerge:
- deployment.yaml
resources:
- sealed-secret.yaml
...
configMapGenerator:
- name: app-config
  behavior: merge
  files:
  - sealed-secret.yaml
```

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: api
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
```

```yaml
# sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
spec:
  template:
    type: Opaque
    metadata:
      name: app-secret
      namespace: default
  encryptedData:
    SECRET_KEY: AgC2a2JGLcDdndEZa5UZkPBS1L1QKjHR9IpPQ...
```
