### ISSUE TITLE
secretGenerator does not recognize "files" tag 

### ISSUE THREAD

**Issue by hasonhai** [kubernetes-sigs/kustomize#708]
Hi,
I tried to create a secret from kustomization.yaml but kustomize told that it does not recognize the "files" tag. It looks super weird.

```
namespace: kube-system

bases:
- ../../bases

secretGenerator:
- name: abcd-aaptest-tls
  namespace: kube-system
  files:
    - tls.crt=secrets/tls.cert
    - tls.key=secrets/tls.key
  type: "kubernetes.io/tls"

patches:
- radosgw-ingress.yaml
```
I validated the yaml format and there is nothing wrong with the yaml format.
But I build the app, error is reported.
```
[sonhaiha@DEFRXXXX500 aap_ingresses]$ kustomize build overlays/test/
Error: json: unknown field "files"
```
Here is my version of kustomize:
`Version: {KustomizeVersion:1.0.11 GitCommit:8f701a00417a812558a7b785e8354957afa469ae BuildDate:2018-12-04T18:42:24Z GoOs:unknown GoArch:unknown}`

Could it be a bug or did I do something wrong? Thanks
