### ISSUE TITLE
ConfigMap hash not added to overlay patch on nested bases using "namespace“ and "namePrefix“

### ISSUE THREAD

**Issue by bgauduch** [kubernetes-sigs/kustomize#710]
Hello 👋

When using a ConfigMapGenerator in an overlay with nested bases, the generated hash is not applied on the patch referencing the configMap. Here are the details:

File tree:
```bash
── base1
    ├── kustomization.yaml
    └── app-deployment.yaml
── base2
    ├── kustomization.yaml
    └── app-deployment-patch.yaml
    └── app-other-service.yaml
── overlays
    ├── kustomization.yaml
    ├── config-file.json
    └── app-other-deployment-patch.yaml
```

`base1/kustomization.yaml` only references some resources:
```yaml
resources:
  - app-deployment.yaml
```

`base2/kustomization.yaml` references the first base, with some other resource, a patch and metadata:
```yaml
bases:
- ../base1

namespace: appName
namePrefix: prefix-
commonLabels:
  app: appName

resources:
  - app-other-service.yaml

patches:
  - app-deployment-patch.yaml
```

`overlay/kustomization.yaml` references the second base, with a configmap generator and a patch using them:
```yaml
bases:
- ../base2

namespace: appName
commonLabels:
  app: appName

patches:
- app-other-deployment-patch.yaml

configMapGenerator:
- name: config
  files:
    - config-file.json
```

`overlay/app-other-deployment-patch.yaml` patches an existing deployment with configMap volume mounting:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          #[REDACTED]
          volumeMounts:
            - name: config-volume
              mountPath: "/path/to/file"
      volumes:
        - name: config-volume
          configMap:
            name: config
```

In the generated yaml, it is expected to get the hash in the configMap volume definition, but it is not the case:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appName
  name: prefix-app
  namespace: appName
spec:
  selector:
    matchLabels:
      app: appName
      name: app
  template:
    metadata:
      labels:
        app: appName
        name: app
    spec:
      containers:
      - name: name
        volumeMounts:
        - mountPath: /path/to/file
          name: config-volume
      volumes:
      - configMap:
          name: config
        name: config-volume
```

This issue might be related to the [#561](https://github.com/kubernetes-sigs/kustomize/issues/561) and [#662](https://github.com/kubernetes-sigs/kustomize/issues/662).
It might be cause by one of the nested base using the `namePrefix' annotation ?

Any help would be greatly appreciated :wink:

**Comment by bgauduch** [comment]
Temporary fix: use a dummy configMapGenerator in the base, and override it with `behavior: replace` in the overlay. This way the hash is correctly generated and bounded.

But this is not the expected behavior, and produce noise in the kustomization.yaml.

**Comment by benjamin-bergia** [comment]
I have the same issue with something like:
```
base/
  app1/
    base/
    overlays/
      web/
      worker/
  [...]
overlays/
  prod/
```
In this case I create a ConfigMap in the prod overlay and the hash isn't modified in the app1 overlays. Unfortunately adding an empty ConfigMap in app1 base would create multiple resources.

**Comment by monopole** [comment]
@Liujingfang1 maybe add a test to cover this, like #1278.

**Comment by jbrette** [comment]
@bgauduch Can you check that it is fixed by this [PR](https://github.com/kubernetes-sigs/kustomize/pull/1378)

Reproduce your environment here [Issue 710](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0710)

```bash
kustomize build overlay/
```

```yaml
apiVersion: v1
data:
  config-file.json: ""
kind: ConfigMap
metadata:
  labels:
    app: appName
  name: config-79tktd9hkb
  namespace: appName
---
apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app: appName
  name: prefix-app
  namespace: appName
spec:
  selector:
    app: appName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appName
  name: prefix-app
  namespace: appName
spec:
  selector:
    matchLabels:
      app: appName
  template:
    metadata:
      labels:
        app: appName
    spec:
      containers:
      - env:
        - name: ANOTHERENV
          value: ANOTHERVALUE
        name: app
        volumeMounts:
        - mountPath: /path/to/file
          name: config-volume
      - image: anotherimage
        name: anothercontainer
      volumes:
      - configMap:
          name: config-79tktd9hkb
        name: config-volume
```

**Comment by bgauduch** [comment]
Hello @jbrette !

Awesome work on the exemple for testing 👍 It makes it way easier to dive back in after a few month 😅 

I just had to make some updates to make it work on my machine:
* replace `resources:` by `bases:` for the overlays to work;
* merge the expected result in one file, as my current kustomize CLI version only produce a single build file with all yaml inside.

I've just tested on my machine and I still see the issue using kustomize v2.0.3.

Your PR is not merged yet so we have to wait for a release to test again and close this issue, right ?

**Comment by Liujingfang1** [comment]
@bgauduch Just release a version 3.1.0, can you try it?

**Comment by benjamin-bergia** [comment]
@Liujingfang1 I just tested on 3.1.0 and I have the same issue.

**Comment by jbrette** [comment]
@benjamin-bergia Please provide more details and indicate what is different in your environment. According to the test we created to reproduce [your issue](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0710), the bug is fixed

@Liujingfang1 I think we should close the issue.

```bash
$HOME/bin/kustomize.3.1.0 version
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}

```
pwd
~/src/sigs.k8s.io/kustomize/examples/issues/issue_0710
```

```bash
$HOME/bin/kustomize.3.1.0 build overlay/
```

```yaml
apiVersion: v1
data:
  config-file.json: ""
kind: ConfigMap
metadata:
  labels:
    app: appName
  name: config-79tktd9hkb
  namespace: appName
---
apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app: appName
  name: prefix-app
  namespace: appName
spec:
  selector:
    app: appName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appName
  name: prefix-app
  namespace: appName
spec:
  selector:
    matchLabels:
      app: appName
  template:
    metadata:
      labels:
        app: appName
    spec:
      containers:
      - env:
        - name: ANOTHERENV
          value: ANOTHERVALUE
        name: app
        volumeMounts:
        - mountPath: /path/to/file
          name: config-volume
      - image: anotherimage
        name: anothercontainer
      volumes:
      - configMap:
          name: config-79tktd9hkb
        name: config-volume
```
