### ISSUE TITLE
Building remote bases fails on Windows

### ISSUE THREAD

**Issue by queil** [kubernetes-sigs/kustomize#719]
kustomize v1.0.11

I am getting the following error on Windows 10 trying to build a remote base:
```
PS C:\> kustomize build github.com/Liujingfang1/mysql
Error: no separator
```

On linux it works just fine:
```
queil@ubuntu:~$ ./kustomize build github.com/Liujingfang1/mysql
apiVersion: v1
data:
  password: admin
kind: ConfigMap
metadata:
  name: mysql-pass
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: mysql-pass
        image: mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - emptyDir: {}
        name: mysql-persistent-storage
```
