### ISSUE TITLE
kustomize output should be parseable by kustomize

### ISSUE THREAD

**Issue by laverya** [kubernetes-sigs/kustomize#732]
There are workflows that rely on running kustomize multiple times in sequence. To support this, kustomize should probably not produce output that it cannot itself parse. For example:

`deployment.yaml`:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  template:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: "image"
        args: []
```
`kustomization.yaml`:
```
resources:
- deployment.yaml
apiVersion: v1beta1
kind: Kustomization
```

When run, this yields:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example
  name: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - args: null
        image: image
        name: example
```

Unfortunately, `args: null` is not an acceptable input, though `args: []` is. Attempting to kustomize a deployment with `args: null` yields `Error: invalid type encountered <nil>`.

I've encountered this when running both `1.0.11` and master as of https://github.com/kubernetes-sigs/kustomize/commit/68ca28879de1444289c6989349b8dce6348f2746 on macOS, go 1.11.5.
