### ISSUE TITLE
support creating secrets from file contents 

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#74]
For example:

```
secretGenerator:
- name: secret-in-base
  behavior: merge
  commands:
    - type: env
      command: "blackbox_cat secret.env"    
    - type: yaml
      command: "sops -d secret.yaml"    
    - type: json
      command: "cat secret.json"    
    - type: inline
      hello: "echo world"    
```
