### ISSUE TITLE
Parse variables in ConfigMaps

### ISSUE THREAD

**Issue by michalschott** [kubernetes-sigs/kustomize#741]
kustomize 1.0.11

Trying to deploy nginx-ingress-controller with kustomize, I'm facing an issue where I need to be able to dynamically inject namespace name to ConfigMap.

I've tried this:
[REDACTED]
```
kustomization.yaml

---
namespace: test

vars:
  - name: NGINX-INGRESS-NAMESPACE
    objref:
      kind: Deployment
      name: nginx-ingress-controller
      apiVersion: extensions/v1beta1
    fieldref:
      fieldpath: metadata.namespace

configmapGenerator:
  - name: nginx-ingress-controller
    literals:
      - add-headers=$(NGINX-INGRESS-NAMESPACE)/nginx-ingress-add-headers
```

Output is:
```
---
apiVersion: v1
data:
  add-headers: $(NGINX-INGRESS-NAMESPACE)/nginx-ingress-add-headers
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
  name: nginx-ingress-controller-h7f44dhftc
  namespace: test
```

Adding regular ConfigMap.yaml file to resources gives similar output.

**Comment by Liujingfang1** [comment]
duplicate as #682

**Comment by gysel** [comment]
Can you please reopen this bug? I just tested it with a version based on `e1420b40` and the var is still not replaced.

File `kustomization.yaml`

```yaml
resources:
- a-deployment.yaml

namespace: bug-demo

vars:
  - name: NAMESPACE
    objref:
      kind: Deployment
      name: my-deployment
      apiVersion: extensions/v1beta1
    fieldref:
      fieldpath: metadata.namespace

configMapGenerator:
- name: variable-demo
  literals:
    - namespace=the namespace is $(NAMESPACE)
```

File `a-deployment.yaml`

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    component: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: my-deployment
  template:
    metadata:
      labels:
        component: my-deployment
    spec:
      containers:
        - name: a-container
          image: image
```

Current output is:

```yaml
apiVersion: v1
data:
  namespace: the namespace is $(NAMESPACE)
kind: ConfigMap
metadata:
  name: variable-demo-2c2b2d7677
  namespace: bug-demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component: my-deployment
  name: my-deployment
  namespace: bug-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: my-deployment
  template:
    metadata:
      labels:
        component: my-deployment
    spec:
      containers:
      - image: image
        name: a-container
```

Expected output is:

```yaml
apiVersion: v1
data:
  namespace: the namespace is bug-demo
kind: ConfigMap
metadata:
  name: variable-demo-2c2b2d7677
  namespace: bug-demo
# shortened here
```
