### ISSUE TITLE
Ability to set images for CRD objects

### ISSUE THREAD

**Issue by jessesuen** [kubernetes-sigs/kustomize#758]
Consider the following use case where a container image is used in a CRD object. I am using a Knative Configuration as an example, but this applies to any CRD object which has an image as part of it's spec (e.g. Prometheus CRD from prometheus-operator):

```yaml
apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: guestbook
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: mycompany/guestbook:v1
```

From an automated pipeline, we would like to do something like:
```
kustomize edit set imagetag mycompany/guestbook:v2
```

Since kustomize has no understanding of a Knative Configuration kind, it it will not do anything to the relevant field: `spec.revisionTemplate.spec.container.image`.

This means that the entire `kustomize edit set image` feature is only useful for built-in Kinds and not and not CRDs.

The solution I am proposing is for images themselves to somehow be exposed as variables:

```yaml
apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: guestbook
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: "$(GUESTBOOK_IMAGE)"
```

The kustomization.yaml to support this would look something like:
```yaml
vars:
- name: GUESTBOOK_IMAGE
  imageRef: mycompany/guestbook

image:
- name: mycompany/guestbook
  newTag: v2
```

**Comment by vreon** [comment]
This sounds like something that [transformer configurations](https://github.com/kubernetes-sigs/kustomize/tree/f8060f35758336a8a33f4782c4d31defff53fb22/examples/transformerconfigs) should handle, but I was surprised to see there isn't one for image references.

**Comment by jlewi** [comment]
Would it make sense for kustomize edit to support something like [yq](https://github.com/kislyuk/yq) syntax so you could do something like

```
kustomize  edit set  .spec.revisionTemplate.spec.container.image mycompany/guestbook:v2
```

For us (Kubeflow) I think this is mostly sugar so users don't have to install a separate CLI from kustomize.

Our use case is we have a lot of examples/tutorials where we'd like to tell people to change various fields in a YAML spec. I'd like to be able to give simple copy-paste commands.

**Comment by Liujingfang1** [comment]
@jessesuen Image transformers assumes the images are in podtemplate. It finds and replace images under `containers` and `initContainers`. https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/image.go#L60
Your CRD doesn't use pod template and contains only one container instead of a container list. To support that, Kustomize need to have a pathconfig for image transformer similar to other transformers.

**Comment by jlewi** [comment]
@Liujingfang1 So if our CRD contains PodTemplateSpec will this work?

In Kubeflow our CRD's almost always use PodTemplateSpecs. For example a TFJob looks like the resource below. So spec.tfReplicaSpecs[Ps].template is a PodTemplateSpec. Would we be able to use kustomize to set images via kustomize in those pods?

```
apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  labels:
    experiment: experiment10
  name: tfjob
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Ps:
      replicas: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - python
            - tf_cnn_benchmarks.py
            - --batch_size=32
            - --model=resnet50
            - --variable_update=parameter_server
            - --flush_stdout=true
            - --num_gpus=1
            - --local_parameter_device=cpu
            - --device=cpu
            - --data_format=NHWC
            image: gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources: {}
            workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
          restartPolicy: OnFailure
    Worker:
      replicas: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - python
            - tf_cnn_benchmarks.py
            - --batch_size=32
            - --model=resnet50
            - --variable_update=parameter_server
            - --flush_stdout=true
            - --num_gpus=1
            - --local_parameter_device=cpu
            - --device=cpu
            - --data_format=NHWC
            image: gcr.io/kubeflow/tf-benchmarks-cpu:v20171202-bdab599-dirty-284af3
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources: {}
            workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
          restartPolicy: OnFailure
status:
  conditions:
  - lastTransitionTime: 2018-07-29T00:31:48Z
    lastUpdateTime: 2018-07-29T00:31:48Z
    message: TFJob tfjob is running.
    reason: TFJobRunning
    status: "True"
    type: Running
  startTime: 2018-07-29T21:40:13Z
  tfReplicaStatuses:
    PS:
      active: 1
    Worker:
      active: 1
```

**Comment by jessesuen** [comment]
@Liujingfang1 - just so I understand correctly: so for this to work the following would need to happen:

1. kustomize will need to introduce a new feature, an "image" transformer to add in this list: https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs

2. To support the ability to set image in a Knative Configuration CRD object, then some custom knative transformer configuration would need to be created. Probably something like:

knative-image.yaml:
```yaml
image:
- path: spec/revisionTemplate/spec/container/image
  kind: Configuration
```

3. And because Knative is a not one of the "default" configurations, in the kustomization.yaml, there would be a `configurations` section:

```yaml
configurations:
- kustomizeconfig/knative-image.yaml # <<<< added one
- kustomizeconfig/commonannotations.yaml
- kustomizeconfig/commonlabels.yaml
- kustomizeconfig/nameprefix.yaml
- kustomizeconfig/namereference.yaml
- kustomizeconfig/namespace.yaml
- kustomizeconfig/varreference.yaml
```

Is my understanding correct?

My final questions is: after all this done, will I be able to use `kustomize edit set imagetag mycompany/guestbook:v2`, to set the image using the CLI? This last piece is critical to how we would automate image promotion in pipelines.

**Comment by Liujingfang1** [comment]
@jlewi Yes，you can use kustomize to set images for `TFJob` objects.

**Comment by Liujingfang1** [comment]
@jessesuen Basically, you get the key part. Let me clarify in details.
> 1. kustomize will need to introduce a new feature, an "image" transformer to add in this list: https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs

"image" transformer exists already, need to introduce its configuration to allow customizing the paths to perform image transformer.

> 2. To support the ability to set image in a Knative Configuration CRD object, then some custom knative transformer configuration would need to be created. Probably something like:
> knative-image.yaml:
>   ```yaml
>   image:
>   - path: spec/revisionTemplate/spec/container/image
>     kind: Configuration
>   ```

Yes.

> 3. And because Knative is a not one of the "default" configurations, in the kustomization.yaml, there would need to be a `configurations` section:

Here you don't need to list all configurations. Only `knative-image.yaml` should be enough. Now kustomize allows to merge the customize configurations with default ones.
```
configurations:
- kustomizeconfig/knative-image.yaml # <<<< added one
```

Only step 1 need implementation in Kustomize.

**Comment by jessesuen** [comment]
OK, I think this solution seems reasonable. So long as we can automate the setting of an image of a CRD object from a pipeline using the kustomize CLI (e.g. `kustomize edit set imagetag mycompany/guestbook:v2`), then this is not a blocker for us.

 Please feel free to rename the title of the bug appropriately.

**Comment by monopole** [comment]
agreed with above - the image transformer needs to be modified to accept field config, like (for example) the label and annotation transformer.  Cannot take this at the moment.

**Comment by yujunz** [comment]
Trying to help solve this issue. But I need to clarify whether we want to preserve the current behavior, which seems recursively looking for `containers` and `initContainers` in resource map and ignore `Gvk`.

Do we want to specify the `Gvk` and `Path` explicitly like the label and annotation transformer? 

@monopole

**Comment by ringerc** [comment]
Wouldn't it make sense to support the specification of additional selectors for images, in a similar manner to a json patch `target`?

**Comment by ringerc** [comment]
For anyone else who finds this, here's how to do it now.

In `kustomize.yaml`

```
...
configurations:
- my-crd-image-transformer.yaml
images:
 - name: foo
   newName: bar
```

in `my-crd-image-transformer.yaml`:

```
  - path: spec/image
    kind: MyCRD
```

**Comment by SachithKasthuriarachchi** [comment]
The `my-crd-image-transformer.yaml` needs to be updated as follows,

```yaml
images:
  - path: spec/image
    kind: MyCRD
```
