### ISSUE TITLE
Support for mixins

### ISSUE THREAD

**Issue by sergey-shambir** [kubernetes-sigs/kustomize#759]
Kustomize currently interprets each overlay as a full set of resources and patches: each patch can modify only resource which is listed directly in `resources:` or indirectly within `bases:`
This means that collecting resource and patch group together to use them later is impossible.
Currently I can create following overlay hierarchy:

1.  Overlay `base` without any bases: defines cluster skeleton with services and pods
2. Overlay `base_debug` which inherits `base` and enables debug tools included into containers (these debug tools disabled by default to simplify using the same container on production and in test environment)
3. Overlay `base_debug_aws` which adds AWS configs and secrets for services
4. Overlay `base_debug_aws_scale_hard` which adds a lot of replicas for each service to test horizontal scaling
5. Final overlay `test_develop` which contains configuration for concrete test environment available at concrete domain

This looks like inheritance in OOP (with multiple inheritance when you have multiple bases).

Of course, I can mix changes from steps 2-4 into base or final overlays. I also can create several bases (one for skeleton and a few bases for things like secrets/configmaps) and maintain patches in place from which multiple overlays can re-use this patch.

But from my point of view, it's better to allow mixins: overlays that contains patches for resources that overlay doesn't have. Like this:

1. Overlay `base` defines pods `a_deployment.yaml` and `b_deployment.yaml`
2. Overlay `debug` defines patch `a_deployment_debug.yaml`, but includes neither `base` to it's bases nor `a_deployment.yaml` to it's resources
3. Overlay `aws` adds new resource `aws_secret.yaml` and new patch `b_deployment.yaml`
4. Overlay `scale_hard` adds patches with a lot of replicas for `a_deployment.yaml` and `b_deployment.yaml`
5. Overlay `test_develop` combines `base`, `debug`, `aws`, `scale_hard` in predicted order.

It's possible to change kustomize in (at least) two ways:
1. Allow overlays included with `bases` list to patch resources defined in previous base in the same list:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base # defines pods A and B
  - ../mixins/debug # defines patch for A, but does not add A as resource or `base` as it base kustomization
 - ../mixins/aws # defines patch for B, but does not define B
```

2. Add separate `mixins:` key which adds Mixin, which is overlay which can patch resources that it does not define, and process mixins when all bases are already processed.
