### ISSUE TITLE
Cannot kustomize ConfigMapList resource

### ISSUE THREAD

**Issue by alexbrand** [kubernetes-sigs/kustomize#769]
When trying to use kustomize with a ConfigMapList, I get the following error:

```
Error: rawResources failed to read Resources: missing metadata.name in object 
{map[apiVersion:v1 items:[map[apiVersion:v1 data:map[foo:bar] kind:ConfigMap metadata:map[name:foo]]] kind:ConfigMapList]}
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-list.yaml
```

configmap-list.yaml:
```
apiVersion: v1
kind: ConfigMapList
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "foo"
  data:
    foo: bar
```

I suspect this might be an issue for any list type resource.
