### ISSUE TITLE
Merging `stringData` and `data` fields in Secrets

### ISSUE THREAD

**Issue by povilasv** [kubernetes-sigs/kustomize#793]
Currently `kustomize` doesn't support merging of `data` & `stringData` in secrets, which leaves to generated config looking like:

```
apiVersion: v1
data:
  config.yaml: base64_encoded
kind: Secret
metadata:
  name: secret-name
stringData:
  config.yaml: |
    test: yaml
```

which has both fields set instead of 1.
