### ISSUE TITLE
Doesn't expand vars in 'secretName' in ingress

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#799]
If I have the below yaml, it properly fills in `host` and `tls.hosts`, but not `tls.secretName`. `tls.secretName` ends up unchanged. Is there a reason?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: ingress
spec:
  rules:
  - host: logs.$(ENV_BASE_URL)
    http:
      paths:
      - backend:
          serviceName: metrics
          servicePort: 2020
        path: /
  tls:
  - hosts:
    - logs.$(ENV_BASE_URL)
    secretName: logs-$(ENV_BASE_URL)-tls
```

With this `kustomization.yaml`

```
configMapGenerator:
  - name: environment
    literals:
      - ENV_BASE_URL="NONE"

vars:
  - name: ENV_BASE_URL
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
    fieldref:
      fieldpath: data.ENV_BASE_URL
```
