### ISSUE TITLE
secretGenerator does not add labels

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#802]
I have:
```
commonLabels:
  app: MYLABEL
```

I also have:

```
secretGenerator:
  - name: regcred
    env: imagePullSecret.txt
    type: Opaque
```

the resulting secret does not have a label applied.

this in turn breaks the ability to run `kubectl apply -f - --print -l app=MYLABEL`

**Comment by Liujingfang1** [comment]
@donbowman Can you paste the output of kustomize build?

**Comment by donbowman** [comment]
```
---
apiVersion: v1
data:
  FLUENT_CLUSTER: $(ENV_CLUSTER)
kind: ConfigMap
metadata:
  labels:
    app: fluent-bit
  name: env-96t7khh47h
  namespace: dev-fluent-bit
---
apiVersion: v1
data:
  .dockerconfigjson: XXXXX=
kind: Secret
metadata:
  name: regcred-2fmdbbf26b
  namespace: dev-fluent-bit
type: Opaque
---
```
