### ISSUE TITLE
Add ability to create imagePullSecrets

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#814]
Today I use a script:

```
#!/bin/sh
if [ $# != 2 ]
then
    echo "Usage: $0 user-id token-id"
    exit 1
fi
JSON=$(printf '{"auths":{"cr.MYDOMAIN.com":{"auth":"%s"}}}' $(echo -n "$1:$2" | base64 -w0))

echo .dockerconfigjson="$JSON"
```

and then:

```
secretGenerator:                                                                                                        
  - name: regcred                                                                                                       
    env: imagePullSecret.txt                                                                                            
    type: kubernetes.io/dockerconfigjson                           
```

I would like to be able to have registry credentials handled so that i can config auth/user/token directly, similar to how kubectl does with:
``kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>`
i`

Given its at the pod level, not the image level, I guess this would be similar to how images work, but not underneath it.

Its possible that if there was a plugin method like kubectl or helm which allowed me to write a quick script into ~/.kstomize/... I would have pragmatically, but i don't feel it would be right.

Its possible kubernetes should have exposed those 3 fields in imagePullSecrets (rather than a b64 encode of the docker specific format).

its possible that kustomize should have a top-level like images to manage this.
