### ISSUE TITLE
Unable to disable commonLabels injection using transformer config: `Error: conflicting fieldspecs`

### ISSUE THREAD

**Issue by jessesuen** [kubernetes-sigs/kustomize#817]
I am trying to to use the commonLabels feature, but without the behavior to inject the label into selectors by using transformer configs. According to the docs, I believe this is described as [one of the use cases](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#customizing-transformer-configurations): "disabling adding commonLabels to fields in some kind of resources"

However, when trying to use transformer configurations to customize the behavior of commonLabels, I get the following error:

```bash
$ kustomize build
Error: conflicting fieldspecs
```

Here is a simple kustomization app which reproduces the behavior:

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- commonlabels.yaml

commonLabels:
  app.kubernetes.io/part-of: argocd

resources:
- service.yaml
```

service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
```

commonlabels.yaml
```yaml
commonLabels:
- path: metadata/labels
  create: true

- path: spec/selector
  create: false   # <<<<< I wish to disable this behavior
  version: v1
  kind: Service
```

**Comment by Liujingfang1** [comment]
Since `.spec/selector` is present in service.yaml
```
spec:
  selector:
    app: redis
```
you can't disable adding the commonLabel to this path by changing it to `create: false`.

Skipping certain paths in transformers is not supported yet, but is a reasonable requirement. Any thoughts or ideas on this would be really appreciated.

**Comment by acastle** [comment]
Has there been any additional thoughts on this one? As it stands there doesn't appear to be any way of overriding defaults specified in https://github.com/kubernetes-sigs/kustomize/blob/9bff2e88839145ae0ea6e037b261af9653801974/pkg/transformers/config/defaultconfig/commonlabels.go#L24

There are many situations in which this behavior is undesirable (e.g. commonLabels are entirely incompatible with headless services where the endpoints are explicitly created). Perhaps a mechanism for completely disabling the default configurations would be appropriate? I may be in the minority but, on first glance, this is how I expected these transformer configurations to function.

**Comment by jbrette** [comment]
Have a look here for the [kustomize 3.2 out of the box solution](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0817_b). I personnaly find that it is unmaintainable because you have to copy/paste the transformer.yaml in base/staging and production in order to change the labels you want to apply.

If you use this [PR Skip kustomize transformers for paths](https://github.com/kubernetes-sigs/kustomize/pull/1491) you will see that you will achieve the same result. But when you start to have base, staging, production....you will only have to put the commonlabels.yaml in one place. [Your issue has been reproduced here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0817). 

This issue keeps coming up ( see #1567), and also it is not perfect and kind of difficult to use, kustomize 3.2.0 fixes your issue. 

/cc @monopole @Liujingfang1 @septh-nr @richardmarshall @ian-howell

**Comment by richardmarshall** [comment]
@jbrette While I also have concerns about the maintainability of configuring internal plugins in this way, copying the transformer.yaml file around for bases and overlays isn't necessary.

Since the `transformers` (and `generators`) fields of the kustomization file are handled using the resource accumulator the paths specified there can be kustomization directories. This enables setting up a common "base" transformer config that can be reused by the various parts of the greater kustomization setup.

Using the transformer.yaml from your [3.2 example](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0817_b) it could be moved into a new directory

**labeltransformer/kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- transformer.yaml
```
**base/kustomization.yaml**
```
...
transformers:
- ../labeltransformer
...
```
**overlay/kustomization.yaml**
```
...
transformers:
- ../labeltransformer
...
```

I still think we can improve the user experience for this, but at least using this model the config for the transformer can be stored in one place and there wouldn't be the challenges around keeping multiple copies in sync.
