### ISSUE TITLE
VolumeClaimTemplates overwritten by StrategicMergePatch

### ISSUE THREAD

**Issue by tobgu** [kubernetes-sigs/kustomize#819]
I have a stateful set with the following volumeClaimTemplate:
```yaml
  volumeClaimTemplates:
  - metadata:
      name: myapp-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 50Gi
```
When I apply a patch as the below the whole spec is overwritten. I would have assumed only the parts in the patch to have been overwritten.

```yaml
# Patch
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  volumeClaimTemplates:
  - metadata:
      name: myapp-data
    spec:
      resources:
        requests:
          storage: 250Gi

# Result: accessModes and storageClassName are lost
  volumeClaimTemplates:
  - metadata:
      name: myapp-data
    spec:
      resources:
        requests:
          storage: 250Gi
```

Is this the expected behaviour? I can work around it by including `accessModes` and `storageClassName` in the patch but it would be nicer to not have to.

```
$ kustomize version
Version: {KustomizeVersion:v2.0.1 GitCommit:ce7e5ee2c30cc5856fea01fe423cf167f2a2d0c3 BuildDate:2019-02-14T13:47:19+00:00 GoOs:unknown GoArch:unknown}
```
