### ISSUE TITLE
Enhancement: put path/type in json patch rather than in kustomization.yaml

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#824]
Currently we have json patches split into two spots (kustomization.yaml and the patch itself):

```
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: nginx-ingress-controller
    path: controller-service.yaml

  - target:
      group: extensions
      version: v1beta1
      kind: Deployment
      name: nginx-ingress-controller
    path: controller-deployment.yaml

...
---
- op: add
  path: /spec/ports/-
  value: {"name": "24224-tcp", "port": 24224, "protocol": "TCP", "targetPort": "24224-tcp"}
- op: replace
  path: /spec/loadBalancerIP
  value: "52.167.3.63"
```

This makes it hard to manage (since i'm often making a similar patch to 2 or more `base` files). It would be simpler if the type/path was in the patch, like below.

E.g. when changing a containerPort across the deployment + service + ingress, its easier to manage a single file called 'change the port' than 3 files + the config in the kustomization.yaml.

```
---

 kind: Service
 name: foo
 patch:
   - op: add
     path: /spec/ports/-
     value: {"name": "24224-tcp", "port": 24224, "protocol": "TCP", "targetPort": "24224-tcp"}
   - op: replace
     path: /spec/loadBalancerIP
     value: "52.167.3.63"

---
 kind: extensions/v1beta1
 name: foo
 patch:
   - op: replace
     ...
```
