### ISSUE TITLE
json quoting error in configMapGenerator

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#843]
With the below file:

```
configMapGenerator:
  - name: env-config
    literals:
      - v2="[{\"path\": \"var/druid/segment-cache\"}]"
```

we get:
```
kustomize build .
Error: json: cannot unmarshal object into Go struct field ConfigMapArgs.literals of type string
```

I don't believe the yaml is invalid.

I have 3 separate problems with this:

1. No file name is in the error
2. No line number is in the error
3. I don't believe the yaml is invalid. It passes yamllint and can be loaded in python.

**Comment by yujunz** [comment]
The error seems thrown from https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/target/kusttarget.go#L109

**Comment by yujunz** [comment]
It passed test if we modify the configuration to

```
- name: json
	  literals:
	    - 'v2=[{"path": "var/druid/segment-cache"}]'
```

**Comment by Liujingfang1** [comment]
@yujunz Thank you for finding a working solution and adding a test.

**Comment by Liujingfang1** [comment]
We also need to improve the error message indicating (at least) the file name or the generator name when the unmarshal error happens.

**Comment by donbowman** [comment]
The workaround does not work in all cases.

Consider:

```
configMapGenerator:
  - name: foo
    literals:
      - druid_segmentCache_locations=[{"path": "var/druid/segment-cache", "maxSize": 32000000000, "freeSpacePercent": 1.0}]
```

If left as-is, it trips the bug in the parser and crashes.

if we add the quotes to the outer bits of the literal, we get a newline. Since its an environment variable to the container this breaks. 

So i do not have a working workaround.

```
apiVersion: v1
data:
  druid_segmentCache_locations: '[{"path": "var/druid/segment-cache", "maxSize": 32000000000,
    "freeSpacePercent": 1.0}]'
kind: ConfigMap
metadata:
  name: foo-hb74f26t2g
```

**Comment by rvodden** [comment]
I had a look at this because is labeled "help wanted" and "good first issue". It looks like the problem is with sigs.k8s.io/yaml. Replicating the issue in a small test app:
```
func main() {

	yamlFile := []byte(`
  literals:
  - 'v2=[{"path": "var/druid/segment-cache"}]'
  - v3="[{\"path\": \"var/druid/segment-cache\"}]"
`)

	y, err := yaml.YAMLToJSON(yamlFile)

	if( err != nil) {
		fmt.Println("Cannot Parse JSON")
		os.Exit(-1)
	}
	fmt.Print(string(y))
}
```
The output is:
```
{
  "literals": [
    "v2=[{\"path\": \"var/druid/segment-cache\"}]",
    {
      "v3=\"[{\\\"path\\\"": "\\\"var/druid/segment-cache\\\"}]\""
    }
  ]
}
```
So `yaml.YAMLToJSON` is erroneously putting extra `{` arround the 2nd example.

**Comment by rvodden** [comment]
This is (although it doesn't look like it on the surface) correct behaviour. Your line:
```
- v3="[{\"path\": \"var/druid/segment-cache\"}]"
```
is being (correctly) interpreted as a map from `v3="[{\"path\"` to `\"var/druid/segment-cache\"}]"`. 

The behaviour you're looking for requires the colon to also be escaped:

```
configMapGenerator:
  - name: env-config
    literals:
      - v2="[{\"path\"\: \"var/druid/segment-cache\"}]"
```

I think this can be closed now.
