### ISSUE TITLE
Use a env var within another?

### ISSUE THREAD

**Issue by max-sixty** [kubernetes-sigs/kustomize#849]
I don't think this is possible, but please could I confirm:

If I have a variable that I want to put within multiple other environment variables, is there a way of doing that without changing each of the variables; for example, here I have `GOOGLE_CLOUD_PROJECT` within a number of variables. Could I define each of these once, and the final file would fill these in?

```
data:
  AIRFLOW_CONN_BIGQUERY_DEFAULT: ";?extra__google_cloud_platform__project=${GOOGLE_CLOUD_PROJECT}"
  AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: ";?extra__google_cloud_platform__project=${GOOGLE_CLOUD_PROJECT}"
  DB_CONNECTION_NAME: "${GOOGLE_CLOUD_PROJECT}:us-east4:airflow-postgres-119"
  GOOGLE_CLOUD_PROJECT: "sixty-capital-test"
  AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "gs://${GOOGLE_CLOUD_PROJECT}/logs/airflow"
```

Many thanks
