### ISSUE TITLE
`kustomize edit set namespace <namespace>` can't edit namespace field inside a spec in Deployment

### ISSUE THREAD

**Issue by swiftdiaries** [kubernetes-sigs/kustomize#854]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
  namespace: kubeflow
spec:
  ...
    metadata:
      labels:
        service: ambassador
      namespace: kubeflow
    ...
```

`kustomize edit set namespace kubeflow-dev` 

yields

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
  namespace: kubeflow-dev
spec:
  ...
    metadata:
      labels:
        service: ambassador
      namespace: kubeflow
    ...
```
Currently, we have to do a Json patch to set the namespace inside the spec field as well.
[Link to PR](https://github.com/kubeflow/manifests/tree/0c0976338b1bf125c688416bc3b546d2c3fc5949/ambassador/overlays/namespace)
I'm not sure if this is a bug. Any pointers would be really helpful.

**Comment by Liujingfang1** [comment]
@swiftdiaries This is not a bug. You don't need the JSON patch either. The namespace inside `.spec.template` is not effective. The pods created for the Deployment will be in the same namespace as the deployment object.

**Comment by swiftdiaries** [comment]
Thank you so much for your reply. So when I infer the namespace with
```
- name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
It would infer from the top level metadata field and not the immediate one?

Sorry for my ignorance here
