### ISSUE TITLE
configMapGenerator with behavior merge doesn't append hash since v2.0.0

### ISSUE THREAD

**Issue by geofflamrock** [kubernetes-sigs/kustomize#858]
Hi,

I'm not sure if this is expected behavior in v2, but when using `behavior: merge` with a configMapGenerator to an existing ConfigMap no longer appends the hash to the output ConfigMap name.

An example:

configmap.yml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  key: value
```

kustomization.yml
```
resources:
  - configmap.yaml
configMapGenerator:
  - env: config.properties
    behavior: merge
    name: config
```

config.properties
```
test=test
```

Output under v1.0.11:
```
apiVersion: v1
data:
  key: value
  test: test
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: config-g5mt7c5bg9
```

Output under v2.0.3:
```
apiVersion: v1
data:
  key: value
  test: test
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: config
```

Is this behavior expected? It well could be that I'm missing something that needs to be done with v2.

Thanks :)
