### ISSUE TITLE
Unable to substitute variable in patches

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#860]
It seems variables in patches can not be substitute. Is it an expected behavior? If not, can it be implemented?

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- kustomizeconfig.yaml
configMapGenerator:
- name: vars
  literals:
  - agent-dockerconfig=awsecr-cred
patchesStrategicMerge:
- dockerconfig.yaml

vars:
- name: AGENT_DOCKERCONFIG
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vars
  fieldref:
    fieldpath: data.agent-dockerconfig
```

kustomizeconfig.yaml

```yaml
varReference:
- kind: Deployment
  path: spec/template/spec/volumes/secret/secretName
```

dockerconfig.yaml

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etl-agent
spec:
  template:
    spec:
      containers:
      - name: agent
        volumeMounts:
        - name: dockerconfig
          mountPath: /root/.docker
          readOnly: true
        volumes:
        - name: dockerconfig
          secret:
            secretName: $(AGENT_DOCKERCONFIG)
            defaultMode: 420
            items:
            - key: .dockerconfigjson
              path: config.json
```

kustomize build | less
```
        volumes:
        - name: dockerconfig
          secret:
            defaultMode: 420
            items:
            - key: .dockerconfigjson
              path: config.json
            secretName: $(AGENT_DOCKERCONFIG)
          name: scratch
```
