### ISSUE TITLE
Unable to overlay `spec/template/spec/containers/volumeMounts/mountPath`

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#869]
Tried to modify the `mountPath` of the base deployment but it seems append a new entry instead of overlaying. Is it an expected result or bug?

kustomization.yaml

```
bases:
- github.com/kubechart/mongodb//overlays/ebs-data-volume?ref=7e68b7d505c0d064eded7a7606e500893e809125

patchesStrategicMerge:
- pod-volume-mounts.yaml
```

pod-volume-mounts.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
      - name: mongodb
        volumeMounts:
        - mountPath: /data/db
          name: data
```

Results in

```
        volumeMounts:
        - mountPath: /data/db
          name: data
        - mountPath: /bitnami/mongodb
          name: data
```

**Comment by Liujingfang1** [comment]
Change the patch to
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
      - name: mongodb
        volumeMounts:
        - mountPath: /data/db
          name: data
        - $patch: replace
```

Here are more examples and usage of [strategic merge patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#list-of-maps).
