### ISSUE TITLE
Secrets are not namespaced with base.namespace when generated with secretGenerator

### ISSUE THREAD

**Issue by yanc0** [kubernetes-sigs/kustomize#87]
In order to reproduce this:

* Create a `kustomization.yaml` file in base directory with `namespace: foo`

```
namespace: foo-bar
resources:
- foo.yaml
```

* Create a `kustomization.yaml` file in overlay directory with secretGenerator

```
bases:
- "../../base"
secretGenerator:
- name: my-secret
  commands:
    config.secret: "uname -a"
  type: "Opaque"
```

**Result:** generated secret is not namespaced in `foo-bar`

**Workaround**: set also namespace in overlayed `kustomization.yaml`
