### ISSUE TITLE
No possibility of mergeing multiple files into single key

### ISSUE THREAD

**Issue by KarstenSiemer** [kubernetes-sigs/kustomize#878]
Hello,

in kustomize1 it was possible trough external commands to have a secretgenerator to generate a secret that has one key with the data of multiple files combined.
I understand the security concerns regarding multiple commands but why isn't there a possibly to do this? This makes it a lot easier to shard large configuration files in git.

I'm thinking of something like this:
```
 secretGenerator:
- name: prometheus-config
  behavior: mergekeys
  key: additional-scrape-configs.yaml
  files:
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
  - scrape-configs/...
```
