### ISSUE TITLE
CRDs containing 'containers' or 'initContainers' key unusable with kustomize

### ISSUE THREAD

**Issue by fentas** [kubernetes-sigs/kustomize#890]
Given the following files:

**crd.yaml**
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
    openAPIV3Schema:
      properties:
        spec:
          containers:
              description: Containers allows injecting additional containers. This
                is meant to allow adding an authentication proxy to an Alertmanager
                pod.
```

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml

images:
  - name: test/test
    newName: registry.gitlab.com/test
    newTag: latest
```

This will fail with `Error: AccumulateTarget: containers path is not of type []interface{} but map[string]interface {}`.

I guess the reason lies here https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/image.go#L60

It will go through _any object_ and looks for `containers` and `initContainers` key values. If this object happens to be a CRD it will most likely fail.
