### ISSUE TITLE
feature request: common annotations by type

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#901]
currently we can add common labels (e.g. label all things).
it would be nice to be able to add/merge an annotation by type.

The example is Ingress. I find that I create 1 patch per ingress simply to do this:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
```

which creates a lot of extra patches. It would be nice to be able to say something like:

```
commonAnnotations:
 bykind:
  kind: Ingress
  annotation:
    X: Y
```
