### ISSUE TITLE
feature request: job name based on hash like config/secret

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#903]
This is related to https://github.com/kubernetes-sigs/kustomize/issues/168

I would like to run a job once each time an image changes
(the specific use case is a django upgrade...). This is referenced in https://github.com/kubernetes/community/pull/1171 but that seems to have ended when the KEP thing started.

So I have a deployment w/ replicas > 1 that contains a django container. It must do a db upgrade whenever the image tag changes. Since replicas >1 this usually crashes, fails, or corrupts the database.

An approach that is a bit hackish but can work is to have a 2nd deployment, w/ replicas==1, that solely does the upgrade. But then its left running. this is what Job was meant for.

But if I make it a Job, then when i change the image tag it does not get retriggered.

So I am thinking, if the job name could be a hash of the image tag or config map, then it would get created as a new Job each time I re-ran kustomize w/ changed config. If the config doesn't change, it won't retrigger.

So conceptually, if i could have:
```
Kind: Job
name: job-$(hash of image tag)
image: image-tag
 ...
```

I would achieve my goal. Its not `once per kustomize run` its `once per configmap change` that I'm looking for here.

initContainer does not work since it runs once per Pod in the Deployment.

**Comment by bd** [comment]
I too am looking for a way to run the "same" job once per deployment application.

**Comment by arthurio** [comment]
@dantman As a workaround, I just delete the job prior to running kustomize...

e.g.
```
kubectl delete jobs my-job || true
kustomize edit set image $MYIMAGE
kustomize build | kubectl apply -f -
```

**Comment by pie-r** [comment]
> @dantman As a workaround, I just delete the job prior to running kustomize...
> 
> e.g.
> 
> ```
> kubectl delete jobs my-job || true
> kustomize edit set image $MYIMAGE
> kustomize build | kubectl apply -f -
> ```

Better to use this in CD:
```
kubectl delete jobs my-job --ignore-not-found=true
kustomize edit set image $MYIMAGE
kustomize build | kubectl apply -f -
```

Important note: `--ignore-not-found` must be used only if we delete a precise object. It doesn't work a label selector.

**Comment by jeacott1** [comment]
this is already possible based on a kustomize var. (its very unfortunate these are going away) 
works great for auto altering job names based on db schema patch/migration versions etc.

```
kind: Job
metadata:
  name: db-migrate-job-$(MIGRATE_JOB_VERSION)
...

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

vars:
  - name: MIGRATE_JOB_VERSION
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: my-main-config
    fieldref: ...
```
