### ISSUE TITLE
build failure for remote target 

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#913]
This is a regression recently added to head
```
./kustomize build https://github.com/kubernetes/kubectl/docs/book/examples/nginx
Error: evalsymlink failure on '/tmp/kustomize-332098206/docs/book/examples/nginx' : lstat /tmp/kustomize-332098206/docs: no such file or directory
```

Using `2.0.3`, we have
```
./kustomize build https://github.com/kubernetes/kubectl/docs/book/examples/nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
```
