### ISSUE TITLE
image name/tag cannot be set from base

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#915]
Consider this example. In 'parent' I have a deployment using an image. In `overlay` i have `base ../parent` and `base ../common`. I wish to set the image tag in `common`. It does not work.
I can set it from `overlay` or `parent` but not `common`. An example is attached.

My desire is to have one spot to change the image tag for a set of related things. Instead I am forced to cut and paste the same text over and over in the overlays.
```
├── common
│   └── kustomization.yaml
├── overlay
│   └── kustomization.yaml
└── parent
    ├── dep.yaml
    └── kustomization.yaml
```

[image-tag-hierarchy.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/3004123/image-tag-hierarchy.tar.gz)

**Comment by Liujingfang1** [comment]
`images` are only effective to current kustomization and are not visible to its overlays.

**Comment by donbowman** [comment]
but why, is this by design? or by chance?

**Comment by Liujingfang1** [comment]
This is by design. Similar to `namePrefix` or `commonAnnotations`, they only set or modify the resources manged by the current kustomization.

**Comment by donbowman** [comment]
ok.... but is this important? 
its making quite a bit more work and harder to maintain.

**Comment by yujunz** [comment]
It sounds reasonable to me. One benefit would be a deterministic build.

**Comment by gautaz** [comment]
@yujunz I don't see how this limitation ensures a more deterministic build.

As soon as you are relying on base files, any modification to these base files impacts the kustomization using them, be it resources or images seems like the same to me.

Being able to specify images in base files also does not cripple flexibility for overlays, you can still modify again images in each overlay kustomization file.

From what I understand, it seems that this feature would increase even more the ability to factor kustomization code.

Would you mind detailing a bit more why this feature would impeach deterministic build and flexibility (perhaps through examples)?

**Comment by nickatsegment** [comment]
Are contributors still against this on principle? When I found this out, it was really counterintuitive. The limitation is only documented in this bug AFAICT, not docs: https://github.com/kubernetes-sigs/kustomize/blob/c094780aaedd241fedd34d73d409d1699488f167/docs/fields.md#images. 

> Similar to namePrefix or commonAnnotations, they only set or modify the resources manged by the current kustomization.

`commonAnnotations` seems to work fine in a base for me.

**Comment by yujunz** [comment]
> Would you mind detailing a bit more why this feature would impeach deterministic build and flexibility (perhaps through examples)?

@gautaz Just created an example of different tags in one kustomize build. 

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: X-dev
  namespace: X
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: cr.agilicus.com/group/image:dev
        name: X
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: X-stage
  namespace: X
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: cr.agilicus.com/group/image:stage
        name: X
```

See https://github.com/yujunz/image-tag-hierarchy for the hierarchy.
