### ISSUE TITLE
namePrefix does not recursively apply to CRD

### ISSUE THREAD

**Issue by yp28** [kubernetes-sigs/kustomize#916]
Given I have these in `test/base`:
```
# test/base/crd.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx
```
```
# test/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
```
```
# test/base/kustomization.yaml
namePrefix: base--
resources:
- crd.yaml
- service.yaml
```
and these in `test/overlay`:
```
# test/overlay/crd.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx
```
```
# test/overlay/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
```
```
# test/overlay/kustomization.yalm
namePrefix: overlay--
bases:
- ../base
patches:
- crd.yaml
- service.yaml
```
and build using `kustomize build test/overlay`, the result shows a difference in behaviour:
```
apiVersion: v1
kind: Service
metadata:
  name: overlay--base--nginx
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: overlay--nginx
```

**Comment by YP28** [comment]
It seems like this is what's causing it to reset the name after the base has already run:
```go
// k8sdeps/transformer/patch/patch.go:76-93
case runtime.IsNotRegisteredError(err):
  // Use JSON merge patch to handle types w/o schema
  baseBytes, err := json.Marshal(base.Map())
  if err != nil {
  	return err
  }
  patchBytes, err := json.Marshal(patch.Map())
  if err != nil {
  	return err
  }
  mergedBytes, err := jsonpatch.MergePatch(baseBytes, patchBytes)
  if err != nil {
  	return err
  }
  err = json.Unmarshal(mergedBytes, &merged)
  if err != nil {
  	return err
  }
```
where known objects get a strategic merge:
```go
// k8sdeps/transformer/patch/patch.go:96-111
default:
  // Use Strategic-Merge-Patch to handle types w/ schema
  // TODO: Change this to use the new Merge package.
  // Store the name of the base object, because this name may have been munged.
  // Apply this name to the patched object.
  lookupPatchMeta, err := strategicpatch.NewPatchMetaFromStruct(versionedObj)
  if err != nil {
      return err
  }
  merged, err = strategicpatch.StrategicMergeMapPatchUsingLookupPatchMeta(
      base.Map(),
      patch.Map(),
      lookupPatchMeta)
  if err != nil {
      return err
  }
```
What's the reason to make a distinction between custom resources and known resources? I'm guessing metadata should be fairly straight forward to handle in a same way for custom resources?

**Comment by Liujingfang1** [comment]
Same issue as #669

**Comment by abergmeier** [comment]
Especially annoying if you are working with e.g. OpenShift because this fails for
```
apiVersion: v1
kind: DeploymentConfig
```

**Comment by mnpenner** [comment]
Why was this closed? Was it fixed? It doesn't appear to be.

I've got

```yaml
# overlays/staging/kustomization.yaml
commonLabels:
  env: staging
nameSuffix: -staging
resources:
  - ../../base
```

```yaml
# base/kustomization.yaml
commonLabels:
  svc: app
resources:
  - ../shared
  - app-deployment.yaml
  - app-service.yaml
  - artisan-cron.yaml
  - database-backup.yaml
  - artisan-worker.yaml
```

```yaml
# shared/kustomization
commonLabels:
  app: kmbookings
  owner: mpen
namespace: kymark
namePrefix: kmb-
```

And when I build:

```
❯ kustomize build kubernetes/overlays/staging | grep app-deployment
  name: app-deployment-staging
```

The `namePrefix` from shared/kustomization.yaml is missing. My namespace is missing too.

```
❯ kustomize version
{Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
```
