### ISSUE TITLE
Allow variable reference to work with container env

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#92]
In the WordPress example
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/wordpress/patch.yaml
```
      containers:
      - name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
```
The env `WORDPRESS_DB_HOST` is hard coded. We should support it by variable reference with this format.
```
      containers:
      - name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: $(DB_HOST)
```
where `DB_HOST` is defined in `kustomization.yaml`
