### ISSUE TITLE
Ingress annotation for basic-auth not handled when patch

### ISSUE THREAD

**Issue by ambis** [kubernetes-sigs/kustomize#921]
Related to: https://github.com/kubernetes-sigs/kustomize/issues/234

I just tested this. If ingress is a resource in kustomization.yml, the `nginx.ingress.kubernetes.io/auth-secret` secret name gets updated properly.

But if the Igress which has this annotation is in a patchesStrategicMerge to an existing ingress, then the basic-auth secret is not updated to reflect the secret name.

kustomize version: 2.0.3 (via brew)
kubectl version 1.13.4
kube version: 1.13.4

**Comment by Liujingfang1** [comment]
This is a simple example to show how it can work.

The kustomization.yaml:
```
resources:
- ingress.yaml

patchesStrategicMerge:
- patch.yaml

secretGenerator:
- name: my-secret
  literals:
  - foo=bar
  - baz=qux

namePrefix: dev-
```

The ingress.yaml is as:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
The patch.yaml is as
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: my-secret
```
With kustomize 2.0.3, you should be able to get following output
```
apiVersion: v1
data:
  baz: cXV4
  foo: YmFy
kind: Secret
metadata:
  name: dev-my-secret-bbmt44tm74
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: dev-my-secret-bbmt44tm74
  name: dev-test-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
        path: /testpath
```
