### ISSUE TITLE
document custom transformer configurations for knative and istio

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#922]
Figure out and document what the custom configurations should be for knative and istio

https://www.knative.dev/docs/eventing/samples/github-source/
https://istio.io/docs/setup/kubernetes/install/kubernetes/

**Comment by jammerful** [comment]
@Liujingfang1 I would like to use kustomize for istio resources, this is blocking me from using kustomize. Are there any plans to do this work soon?

**Comment by Liujingfang1** [comment]
@jammerful Not yet, don't have cycle to work on this. Anyone who wants to help is appreciated. The work to do is to understand istio and knative CRDs and list the field path for name references(I believe this is the majority of work).

**Comment by jammerful** [comment]
@Liujingfang1 If you send me an example to follow I can help on this, I'm new to kustomize.

**Comment by kunickiaj** [comment]
@jammerful I'm currently considering just using json patches because I haven't found any other way to set host values specifically for DestinationRule and VirtualService.

For example, a VirtualService patch might look like:

```
- op: add
  path: /spec/hosts
  value:
    - www.my-domain.com
    - my-domain.com
- op: add
  path: /spec/gateways/-
  value: my-gateway
- op: replace
  path: /spec/http/0/match/0/authority/exact
  value: my-domain.com
- op: replace
  path: /spec/http/0/redirect/authority
  value: www.my-domain.com
- op: replace
  path: /spec/http/1/match/0/authority/exact
  value: www.my-domain.com
- op: replace
  path: /spec/http/1/route/0/destination/host
  value: my-service.my-namespace.svc.cluster.local
```

It's not a great solution. The other thing we've done for this which is just as ugly is to template these fields and pipe everything through envsubst 🙃

Patterns of <my-service>.<my-namespace>.svc.cluster.local are common. I believe its possible to drop everything except <my-service> if the service is in the same namespace, though its not recommended in the docs. That can eliminate some of the issues preventing more re-use.
