### ISSUE TITLE
Patch doesn't set configmap name generated from overlay resource

### ISSUE THREAD

**Issue by balboah** [kubernetes-sigs/kustomize#924]
### Use case

I want to inject env variables into my deployment that is in a base template, using secrets or configmaps defined in my overlay.

### What I did

building from this kustomize.yaml:
```
bases:
- https://github.com/balboah/kustomize
```

### What I got

```
env:
        - name: hi
          valueFrom:
            configMapKeyRef:
              key: foobar
              name: bai
```

### What I expected

Expected the build output to reference the configmap name that was created by resources:
```
env:
        - name: hi
          valueFrom:
            configMapKeyRef:
              key: foobar
              name: foo-bai
```

# 

Why is it not? What's the best practice for injecting secrets and configmaps into bases?
Also tried using `vars` with generator with same end result.
