### ISSUE TITLE
Support kustomize spec mixins from annotation

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#942]
The requirement originates from a use case to make **variable substitution in custom fields**. 

For example, to substitute namespace in ambassador configuration which is stored in `metadata/annotations/getambassador.io\/config`, we need to make changes as below:

- create var in `kustomization.yaml`
- add field spec to `kustomizeconfig.yaml` and included it

It ends up in lots of code fragment when you have to handle lots of different fields and make it hard to refactoring the overlays (you shall have to cut and paste the code fragment from one overlay to another).

It would be nice to **declare such changes close to where it is used**, e.g. the annotation of related resource.

For example, given the manifest below.

```
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    sigs.k8s.io/kustomize/mixin: |
      ---
      #! kustomization.yaml
      vars:
      - name: ARGOCD_NAMESPACE
        objref:
          apiVersion: v1
          kind: Namespace
          name: argocd
      ---
      #! kustomizeconfig.yaml
      varReference:
      - kind: Service
        path: metadata/annotations/getambassador.io\/config
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  argocd_server_mapping
      grpc: True
      prefix: /argocd/
      rewrite: /argocd/
      service: argocd-server.$(ARGOCD_NAMESPACE)
      timeout_ms: 60000
```

The content of annotation `sigs.k8s.io/kustomize/mixin` shall be parsed and mixed into `kustomization.yaml` on the fly.
