### ISSUE TITLE
Line breaks on long strings with spaces

### ISSUE THREAD

**Issue by maxhomann** [kubernetes-sigs/kustomize#947]
When combining helm templates with kustomize overlays, a line break is inserted when the line is very long and contains spaces.

Tested versions: 2.0.1 and 2.0.3
Using test/base.yml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    app.version: "{{ .Values.services.mariadb.app.version }}"
spec:
  template:
    spec:
      containers:
      - name: mariadb
        image: "thisIsAReallyLongRepositoryLinkThatResultsInALineBreakWhenBuildingWithKustomize/mariadb:{{ .Values.services.mariadb.image.version }}"
```
and test/kustomization.yml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base.yml
```

results in 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.version: '{{ .Values.services.mariadb.app.version }}'
  name: test
spec:
  template:
    spec:
      containers:
      - image: thisIsAReallyLongRepositoryLinkThatResultsInALineBreakWhenBuildingWithKustomize/mariadb:{{
          .Values.services.mariadb.image.version }}
        name: mariadb
```

Expected Behavior:
- Line without line break
- Also, the string/quoted value of the image name in base.yml is converted to an unqouted value on build while the `app.version` label is enclosed in single quotes. I would expect that either the quotes are not removed at all or the quoting behavior is constant

**Comment by laverya** [comment]
I think if https://github.com/go-yaml/yaml/pull/455 gets merged that might be the signal to migrate to yaml.v3, and unlimited line lengths...

**Comment by maxhomann** [comment]
This behavior is still in v3.0.1. Using the same input files, the output has line breaks:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.version: '{{ .Values.services.mariadb.app.version }}'
  name: test
spec:
  template:
    spec:
      containers:
      - image: thisIsAReallyLongRepositoryLinkThatResultsInALineBreakWhenBuildingWithKustomize/mariadb:{{
          .Values.services.mariadb.image.version }}
```

**Comment by rchessa** [comment]
Hi guys,

there is a workaround for this issue?

**Comment by kristofferahl** [comment]
Have the same issue here. Need to keep the formatting as is without breaking long lines. Any ideas?

**Comment by kautsig** [comment]
@kristofferahl, we worked around this by using:

```
attribute: |
  very long line

```

Not sure if this is semantically 100% equal, though. It mitigated the issue in our specific case.

**Comment by laverya** [comment]
There's a fix in gopkg.in/yaml.v2, now released as [v2.3.0](https://github.com/go-yaml/yaml/commit/0b1645d91e851e735d3e23330303ce81f70adbe3) - I'll make a PR to update kustomize to this version. (basically, if the string doesn't have newline literals in it, v2.3.0 won't split the string over multiple lines when encoding things - previously it would wrap before 80 characters)

**Comment by laverya** [comment]
Just validated, and 3.6.1 still exhibits this behavior:

`kustomization.yaml`
```yaml
resources:
- deployment.yaml
```

`deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test
  template:
    metadata:
      labels:
        component: test
    spec:
      containers:
        - name: test
          image: "test"
          env:
            - name: DATABASE_URL
              value: postgres://{{repl ConfigOption "database_user"}}:{{repl ConfigOption "database_password"}}@db.{{repl Namespace}}.svc.cluster.local:5432/db
```

yields this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test
  template:
    metadata:
      labels:
        component: test
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://{{repl ConfigOption "database_user"}}:{{repl ConfigOption
            "database_password"}}@db.{{repl Namespace}}.svc.cluster.local:5432/db
        image: test
        name: test
```
