### ISSUE TITLE
Support multiple resources using the "same" container configuration (env/volumes) without duplication

### ISSUE THREAD

**Issue by dantman** [kubernetes-sigs/kustomize#952]
I have a container with a large env/volume configuration. I would like to be able to re-use that same container configuration in another pod. Namely I have a container defined in a deployment and I'd like to define a job (cron or one-off) with the same image that uses the same env/volume configuration as the deployment pod.

Right now the only way to do this is to just copy and paste the whole env/volumes configuration. Since PodPresets are a possibly volatile alpha feature not available in most places; vars can't seem to handle env lists or whole containers; and json patches only work within a single resource.

There are multiple ways this could be done by allowing container configs to be copied or shared, I'm fine with any of them.

* Allow vars to select an env list and allow `$(VAR)` to be used on `env:`
* Allow structured patches to match containers by name/labels/images? nested inside of docs instead of only being able to match the whole doc by kind/name/etc, so you can patch multiple containers of the same type within deployments, pods, and jobs
* Allow defining a container in some type of file outside the normal resources and then applying that to a container definition inside a resource
* Add a "container generator" that can define env/volumes/etc for a container and what resource to apply them to
* Add a new kustomization.yaml property defining rules for copying container config from one container definition to another

**Comment by dantman** [comment]
For an example, take the following hypothetical setup:
```yaml
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-auth
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-auth
              key: password

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wordpress-cron
  labels:
    app: wordpress
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: wordpress:4.8-apache
            name: wordpress
            command:
            - php
            args:
            - /path/to/wp-cron.php
            env:
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-auth
                  key: user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-auth
                  key: password
          restartPolicy: OnFailure
```

Now imagine that `env` is even more massive than just db user and db password.

The general idea of this issue is we do not have to repeat the following multiple times, the deployment pod and the cron job pod are effectively the same type we just want to define this env configuration once and use it for both the server and cron job.

```yaml
env:
- name: WORDPRESS_DB_USER
  valueFrom:
    secretKeyRef:
      name: wordpress-db-auth
      key: user
- name: WORDPRESS_DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: wordpress-db-auth
      key: password
```
