### ISSUE TITLE
Strategic merge patch for Service Ports

### ISSUE THREAD

**Issue by povilasv** [kubernetes-sigs/kustomize#977]
Currently if I have this service:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
  labels:
    name: grafana
  name: grafana
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
```

And try to strategicMergePatch with this.

```
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: telecom
spec:
  ports:
  - name: grafana
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: grafana

```

`kustomize build .` produces this:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
  labels:
    app: telecom-grafana
    name: telecom-grafana
    service: monitoring
  name: telecom-grafana
  namespace: telecom
spec:
  ports:
  - name: grafana
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: telecom-grafana
    name: telecom-grafana
    service: monitoring
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
```

In the output you can see 2 service ports having same name but different port value, which doesn't work in Kubernetes.

The use case for this is to add Authentication proxy in overlay and make that actually service ponts to a `9080` port instead of `3000`
