### ISSUE TITLE
Reference to location of root kustomization.yaml

### ISSUE THREAD

**Issue by victorandree** [kubernetes-sigs/kustomize#98]
Scripts executing in a secret generator have the working directory of the `kustomization.yaml` file that defined them. To create a re-usable secret generator, I would like to use a secret generator as a base with paths relative to the `kustomization.yaml` file I'm building. I would be useful if we had some variable or built-in environment variable referencing that file.

I realize it may be more "kustomizeable" to try and use an overlay secret generator that merges into a base, so as one does not have to reason so much about what context a base will be used in, or open up for using bases with arguments/variables in general. I do think this could simplify repetitive configuration, however.

## Example

In this example, I have `.pgpass` sitting in the same directory as the secret generator `pg`. It will generate a secret from that file, and I can use it as a base in my `foobar` kustomization. However, I would like to put `.pgpass` with the `foobar` file, or an overlay using it. 

I can replace the relative path with an environment variable (such as `$PGPASS`) and make sure I pass an absolute path to `kustomize build` (e.g. `PGPASS=$PWD/.pgpass kustomize build`).

`tree -a`:
```
.
├── bases
│   └── pg
│       ├── .pgpass
│       └── kustomization.yaml
└── foobar
    ├── deploy.yaml
    └── kustomization.yaml

3 directories, 4 files
```

bases/pg/kustomization.yaml:

```yaml
secretGenerator:
- name: pg
  commands:
    # will reference files in `bases/pg`, not directory of root `kustomization.yaml` file
    # replace with `$PGPASS` and pass that to make it work
    PGDATABASE: "cut -d: -f3 .pgpass"
    PGUSER: "cut -d: -f4 .pgpass"
    PGPASSWORD: "cut -d: -f5 .pgpass"
  type: Opaque
```

bases/pg/.pgpass:

```
hostname:port:database:username:password
```

foobar/deploy.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
  labels:
    app: foobar
spec:
  selector:
    matchLabels:
      app: foobar
  template:
    metadata:
      labels:
        app: foobar
    spec:
      containers:
      - name: foobar
        image: foobar
        env:
        - name: PGDATABASE
          valueFrom: { secretKeyRef: { name: pg, key: PGDATABASE }}
        - name: PGUSER
          valueFrom: { secretKeyRef: { name: pg, key: PGUSER }}
        - name: PGPASSWORD
          valueFrom: { secretKeyRef: { name: pg, key: PGPASSWORD }}
```

foobar/kustomization.yaml:

```yaml
namePrefix: foobar-
bases:
- ../bases/pg
resources:
- deploy.yaml
```

**Comment by Liujingfang1** [comment]
@victorandree Setting an environment variable should work for you. 
In the secretGenerator, you can change the commands $PGPASS. For example
```
secretGenerator:
- name: pg
  commands:
    PATH: "echo ${PGPASS}"
```
Then `PGPASS="aaaaaaaa"; kustomize build .`
and `PGPASS="bbbbbbbb"; kustomize build .`
will give you different secrets.
