### ISSUE TITLE
support for namespace in vars objref

### ISSUE THREAD

**Issue by lionelvillard** [kubernetes-sigs/kustomize#982]
usecase: inject the istio ingress in the `istio-system` namespace into a k8s ingress. 

Kustomization.yaml:

```
resources:
  - ingress.yaml
vars:
  - name: INGRESS_IP
    objref:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
      apiVersion: v1
    fieldref:
      fieldpath: status.loadBalancer.ingress[0].ip
```
