### ISSUE TITLE
configMapGenerator do not support relative path since v2.0.0

### ISSUE THREAD

**Issue by Betula-L** [kubernetes-sigs/kustomize#985]
**What happened**:
configMapGenerator do not support relative file path in v2.0.*.
I have a kustomization.yaml works well in v1.0.11, but failed in v2.0.*.  
```yaml
namespace: kube-system

commonLabels:
  app: ${prometheus_label}
  
bases:
- ../../../base

resources:
- prometheus-ingress.yaml
- prometheus-dc.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: prometheus-config
    files:
      - ../../record/cluster/cluster.yml
       ......
```
When i upgrade my kustomize, error occurred as following, 
```
Error: NewResMapFromConfigMapArgs: NewResMapFromConfigMapArgs: file sources: [../../record/prometheus/pod/pod.yml ../../record/prometheus/node/node.yml ../../record/prometheus/cluster/cluster.yml ../../record/prometheus/namespace/namespace.yml ../../record/prometheus/deployment/deployment.yml ../../record/prometheus/daemonset/daemonset.yml ./prometheus.yml]: security; file '../../record/prometheus/pod/pod.yml' is not in or below '/root/iac/k8s-config/k8s-monitor/template-config/overlays/tj1-cc-k8s-test'
```
**What you expected to happen**:
configMapGenerator relative path should works well in v2.0.*
