### ISSUE TITLE
Namespace not update for service reference in cluster scoped resource

### ISSUE THREAD

**Issue by jta** [kubernetes-sigs/kustomize#987]
To my knowledge there doesn't seem to be a way of correcting namespaces for referenced objects in cluster scoped resources, outside of the hard coded logic in https://github.com/kubernetes-sigs/kustomize/blob/50c076eb3f0e4ffc4c8733aaa9f7421aecedc2aa/pkg/transformers/namespace.go#L93

To replicate, using the following set of resources:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: example
webhooks:
  - name: example
    clientConfig:
      caBundle: ""
      service:
        name: my-service
        namespace: default
```
Kustomizing with `namespace: new-namespace` will not adjust the service reference under webhooks/clientConfig/service.
