### ISSUE TITLE
CronJob initContainer vars not replaced

### ISSUE THREAD

**Issue by ryandbump** [kubernetes-sigs/kustomize#994]
Objref vars are not replaced in CronJob initContainer but the vars are correctly replaced in CronJob containers. The example below recreates the issue I am seeing. 

Run `kustomize build` on directory containing the files below:
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - deployment.yaml
nameSuffix: -extra-stuff
vars:
  - name: VAR
    objref:
      kind: CronJob
      name: cron-job
      apiVersion: batch/v1beta1
    fieldref:
      fieldpath: metadata.name
```

```yaml
# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cron-job
          containers:
            - name: cron-job
              image: some/image:latest
              env:
                - name: VAR
                  value: $(VAR)
          initContainers:
            - name: init-container
              image: some/image:latest
              env:
                - name: VAR
                  value: $(VAR)
```

Output:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-extra-stuff
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
            - name: VAR
              value: cron-job-extra-stuff
            image: some/image:latest
            name: cron-job
          initContainers:
          - env:
            - name: VAR
              value: $(VAR)
            image: some/image:latest
            name: init-container
          serviceAccountName: cron-job
```

kustomize version:
```sh
Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}
```
